Aurora Framework: Window.m File Reference
Window.m File Reference
Classes
class GLFWApplication
class GLFWApplicationDelegate
class GLFWContentView
class GLFWWindow
class GLFWWindowDelegate
Macros
#define NSEventMaskAny NSAnyEventMask
#define NSEventModifierFlagCapsLock NSAlphaShiftKeyMask
#define NSEventModifierFlagCommand NSCommandKeyMask
#define NSEventModifierFlagControl NSControlKeyMask
#define NSEventModifierFlagDeviceIndependentFlagsMask NSDeviceIndependentModifierFlagsMask
#define NSEventModifierFlagOption NSAlternateKeyMask
#define NSEventModifierFlagShift NSShiftKeyMask
#define NSEventTypeApplicationDefined NSApplicationDefined
#define NSEventTypeKeyUp NSKeyUp
#define NSWindowStyleMaskBorderless NSBorderlessWindowMask
#define NSWindowStyleMaskClosable NSClosableWindowMask
#define NSWindowStyleMaskMiniaturizable NSMiniaturizableWindowMask
#define NSWindowStyleMaskResizable NSResizableWindowMask
#define NSWindowStyleMaskTitled NSTitledWindowMask
Functions
int _glfwPlatformCreateCursor (_GLFWcursor *cursor, const GLFWimage *image, int xhot, int yhot)
int _glfwPlatformCreateStandardCursor (_GLFWcursor *cursor, int shape)
int _glfwPlatformCreateWindow (_GLFWwindow *window, const _GLFWwndconfig *wndconfig, const _GLFWctxconfig *ctxconfig, const _GLFWfbconfig *fbconfig)
VkResult _glfwPlatformCreateWindowSurface (VkInstance instance, _GLFWwindow *window, const VkAllocationCallbacks *allocator, VkSurfaceKHR *surface)
void _glfwPlatformDestroyCursor (_GLFWcursor *cursor)
void _glfwPlatformDestroyWindow (_GLFWwindow *window)
void _glfwPlatformFocusWindow (_GLFWwindow *window)
int _glfwPlatformFramebufferTransparent (_GLFWwindow *window)
const char * _glfwPlatformGetClipboardString (void)
void _glfwPlatformGetCursorPos (_GLFWwindow *window, double *xpos, double *ypos)
void _glfwPlatformGetFramebufferSize (_GLFWwindow *window, int *width, int *height)
int _glfwPlatformGetKeyScancode (int key)
int _glfwPlatformGetPhysicalDevicePresentationSupport (VkInstance instance, VkPhysicalDevice device, uint32_t queuefamily)
void _glfwPlatformGetRequiredInstanceExtensions (char **extensions)
const char * _glfwPlatformGetScancodeName (int scancode)
void _glfwPlatformGetWindowContentScale (_GLFWwindow *window, float *xscale, float *yscale)
void _glfwPlatformGetWindowFrameSize (_GLFWwindow *window, int *left, int *top, int *right, int *bottom)
float _glfwPlatformGetWindowOpacity (_GLFWwindow *window)
void _glfwPlatformGetWindowPos (_GLFWwindow *window, int *xpos, int *ypos)
void _glfwPlatformGetWindowSize (_GLFWwindow *window, int *width, int *height)
void _glfwPlatformHideWindow (_GLFWwindow *window)
void _glfwPlatformIconifyWindow (_GLFWwindow *window)
void _glfwPlatformMaximizeWindow (_GLFWwindow *window)
void _glfwPlatformPollEvents (void)
void _glfwPlatformPostEmptyEvent (void)
void _glfwPlatformRequestWindowAttention (_GLFWwindow *window)
void _glfwPlatformRestoreWindow (_GLFWwindow *window)
void _glfwPlatformSetClipboardString (const char *string)
void _glfwPlatformSetCursor (_GLFWwindow *window, _GLFWcursor *cursor)
void _glfwPlatformSetCursorMode (_GLFWwindow *window, int mode)
void _glfwPlatformSetCursorPos (_GLFWwindow *window, double x, double y)
void _glfwPlatformSetWindowAspectRatio (_GLFWwindow *window, int numer, int denom)
void _glfwPlatformSetWindowDecorated (_GLFWwindow *window, GLFWbool enabled)
void _glfwPlatformSetWindowFloating (_GLFWwindow *window, GLFWbool enabled)
void _glfwPlatformSetWindowIcon (_GLFWwindow *window, int count, const GLFWimage *images)
void _glfwPlatformSetWindowMonitor (_GLFWwindow *window, _GLFWmonitor *monitor, int xpos, int ypos, int width, int height, int refreshRate)
void _glfwPlatformSetWindowOpacity (_GLFWwindow *window, float opacity)
void _glfwPlatformSetWindowPos (_GLFWwindow *window, int x, int y)
void _glfwPlatformSetWindowResizable (_GLFWwindow *window, GLFWbool enabled)
void _glfwPlatformSetWindowSize (_GLFWwindow *window, int width, int height)
void _glfwPlatformSetWindowSizeLimits (_GLFWwindow *window, int minwidth, int minheight, int maxwidth, int maxheight)
void _glfwPlatformSetWindowTitle (_GLFWwindow *window, const char *title)
void _glfwPlatformShowWindow (_GLFWwindow *window)
void _glfwPlatformWaitEvents (void)
void _glfwPlatformWaitEventsTimeout (double timeout)
int _glfwPlatformWindowFocused (_GLFWwindow *window)
int _glfwPlatformWindowHovered (_GLFWwindow *window)
int _glfwPlatformWindowIconified (_GLFWwindow *window)
int _glfwPlatformWindowMaximized (_GLFWwindow *window)
int _glfwPlatformWindowVisible (_GLFWwindow *window)
static void acquireMonitor (_GLFWwindow *window)
static void centerCursor (_GLFWwindow *window)
static void createMenuBar (void)
static GLFWbool createNativeWindow (_GLFWwindow *window, const _GLFWwndconfig *wndconfig, const _GLFWfbconfig *fbconfig)
static GLFWbool cursorInClientArea (_GLFWwindow *window)
static NSUInteger getStyleMask (_GLFWwindow *window)
GLFWAPI id glfwGetCocoaWindow (GLFWwindow *handle)
static void hideCursor (_GLFWwindow *window)
static GLFWbool initializeAppKit (void)
static void releaseMonitor (_GLFWwindow *window)
static void showCursor (_GLFWwindow *window)
static float transformY (float y)
static int translateFlags (NSUInteger flags)
static int translateKey (unsigned int key)
static NSUInteger translateKeyToModifierFlag (int key)
static void updateCursorImage (_GLFWwindow *window)
Variables
static const NSRange kEmptyRange = { NSNotFound, 0 }
Macro Definition Documentation
NSWindowStyleMaskBorderless
#define NSWindowStyleMaskBorderless NSBorderlessWindowMask
Referenced by getStyleMask().
NSWindowStyleMaskClosable
#define NSWindowStyleMaskClosable NSClosableWindowMask
Referenced by getStyleMask().
NSWindowStyleMaskMiniaturizable
#define NSWindowStyleMaskMiniaturizable NSMiniaturizableWindowMask
Referenced by getStyleMask().
NSWindowStyleMaskResizable
#define NSWindowStyleMaskResizable NSResizableWindowMask
Referenced by getStyleMask().
NSWindowStyleMaskTitled
#define NSWindowStyleMaskTitled NSTitledWindowMask
Referenced by getStyleMask().
NSEventModifierFlagCommand
#define NSEventModifierFlagCommand NSCommandKeyMask
Referenced by translateFlags(), and translateKeyToModifierFlag().
NSEventModifierFlagControl
#define NSEventModifierFlagControl NSControlKeyMask
Referenced by translateFlags(), and translateKeyToModifierFlag().
NSEventModifierFlagOption
#define NSEventModifierFlagOption NSAlternateKeyMask
Referenced by translateFlags(), and translateKeyToModifierFlag().
NSEventModifierFlagShift
#define NSEventModifierFlagShift NSShiftKeyMask
Referenced by translateFlags(), and translateKeyToModifierFlag().
NSEventModifierFlagCapsLock
#define NSEventModifierFlagCapsLock NSAlphaShiftKeyMask
Referenced by translateFlags().
NSEventModifierFlagDeviceIndependentFlagsMask
#define NSEventModifierFlagDeviceIndependentFlagsMask NSDeviceIndependentModifierFlagsMask
NSEventMaskAny
#define NSEventMaskAny NSAnyEventMask
NSEventTypeApplicationDefined
#define NSEventTypeApplicationDefined NSApplicationDefined
NSEventTypeKeyUp
#define NSEventTypeKeyUp NSKeyUp
Function Documentation
getStyleMask()
static NSUInteger getStyleMask (_GLFWwindow * window) static
References _GLFWwindow::decorated, _GLFWwindow::monitor, NSWindowStyleMaskBorderless, NSWindowStyleMaskClosable, NSWindowStyleMaskMiniaturizable, NSWindowStyleMaskResizable, NSWindowStyleMaskTitled, and _GLFWwindow::resizable.
Referenced by _glfwPlatformSetWindowMonitor().
centerCursor()
static void centerCursor (_GLFWwindow * window) static
References _glfwPlatformGetWindowSize(), _glfwPlatformSetCursorPos(), height, and width.
Referenced by _glfwPlatformSetCursorMode().
cursorInClientArea()
static GLFWbool cursorInClientArea (_GLFWwindow * window) static
Referenced by _glfwPlatformSetCursor(), and _glfwPlatformSetCursorMode().
hideCursor()
static void hideCursor (_GLFWwindow * window) static
References _glfw, and GLFW_TRUE.
Referenced by updateCursorImage().
showCursor()
static void showCursor (_GLFWwindow * window) static
References _glfw, and GLFW_FALSE.
Referenced by updateCursorImage().
updateCursorImage()
static void updateCursorImage (_GLFWwindow * window) static
References _GLFWwindow::cursor, _GLFWwindow::cursorMode, GLFW_CURSOR_NORMAL, hideCursor(), and showCursor().
Referenced by _glfwPlatformSetCursor(), _glfwPlatformSetCursorMode(), and _glfwPlatformSetCursorPos().
transformY()
static float transformY (float y) static
Referenced by _glfwPlatformGetWindowPos(), _glfwPlatformSetCursorPos(), _glfwPlatformSetWindowMonitor(), _glfwPlatformSetWindowPos(), and acquireMonitor().
acquireMonitor()
static void acquireMonitor (_GLFWwindow * window) static
References _glfwInputMonitorWindow(), _glfwSetVideoModeNS(), _GLFWwindow::monitor, transformY(), and _GLFWwindow::videoMode.
Referenced by _glfwPlatformCreateWindow(), _glfwPlatformSetWindowMonitor(), and _glfwPlatformSetWindowSize().
releaseMonitor()
static void releaseMonitor (_GLFWwindow * window) static
References _glfwInputMonitorWindow(), _glfwRestoreVideoModeNS(), _GLFWwindow::monitor, NULL, and _GLFWmonitor::window.
Referenced by _glfwPlatformDestroyWindow(), and _glfwPlatformSetWindowMonitor().
translateFlags()
static int translateFlags (NSUInteger flags) static
References GLFW_MOD_ALT, GLFW_MOD_CAPS_LOCK, GLFW_MOD_CONTROL, GLFW_MOD_SHIFT, GLFW_MOD_SUPER, NSEventModifierFlagCapsLock, NSEventModifierFlagCommand, NSEventModifierFlagControl, NSEventModifierFlagOption, and NSEventModifierFlagShift.
translateKey()
static int translateKey (unsigned int key) static
References _glfw, and GLFW_KEY_UNKNOWN.
translateKeyToModifierFlag()
static NSUInteger translateKeyToModifierFlag (int key) static
References GLFW_KEY_LEFT_ALT, GLFW_KEY_LEFT_CONTROL, GLFW_KEY_LEFT_SHIFT, GLFW_KEY_LEFT_SUPER, GLFW_KEY_RIGHT_ALT, GLFW_KEY_RIGHT_CONTROL, GLFW_KEY_RIGHT_SHIFT, GLFW_KEY_RIGHT_SUPER, NSEventModifierFlagCommand, NSEventModifierFlagControl, NSEventModifierFlagOption, and NSEventModifierFlagShift.
createMenuBar()
static void createMenuBar (void) static
References setup::name, and create_symbols_file::progname.
Referenced by initializeAppKit().
initializeAppKit()
static GLFWbool initializeAppKit (void) static
References _glfw, _glfwInputError(), createMenuBar(), GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, _GLFWlibrary::hints, _GLFWlibrary::init, _GLFWinitconfig::menubar, and _GLFWinitconfig::ns.
Referenced by _glfwPlatformCreateCursor(), _glfwPlatformCreateStandardCursor(), _glfwPlatformCreateWindow(), and _glfwPlatformPollEvents().
createNativeWindow()
static GLFWbool createNativeWindow (_GLFWwindow * window, const _GLFWwndconfig * wndconfig, const _GLFWfbconfig * fbconfig) static
References _glfw, _glfwInputError(), _glfwPlatformGetFramebufferSize(), _glfwPlatformGetMonitorPos(), _glfwPlatformGetVideoMode(), _glfwPlatformGetWindowSize(), _GLFWwndconfig::floating, _GLFWwndconfig::frameName, GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, _GLFWwndconfig::height, _GLFWwndconfig::maximized, mode(), _GLFWwindow::monitor, _GLFWwndconfig::ns, _GLFWwndconfig::resizable, _GLFWwndconfig::retina, _GLFWfbconfig::transparent, and _GLFWwndconfig::width.
Referenced by _glfwPlatformCreateWindow().
_glfwPlatformCreateWindow()
int _glfwPlatformCreateWindow (_GLFWwindow * window, const _GLFWwndconfig * wndconfig, const _GLFWctxconfig * ctxconfig, const _GLFWfbconfig * fbconfig)
Referenced by glfwCreateWindow().
_glfwPlatformDestroyWindow()
void _glfwPlatformDestroyWindow (_GLFWwindow * window)
Referenced by glfwDestroyWindow().
_glfwPlatformSetWindowTitle()
void _glfwPlatformSetWindowTitle (_GLFWwindow * window, const char * title)
Referenced by glfwSetWindowTitle().
_glfwPlatformSetWindowIcon()
void _glfwPlatformSetWindowIcon (_GLFWwindow * window, int count, const GLFWimage * images)
Referenced by glfwSetWindowIcon().
_glfwPlatformGetWindowPos()
void _glfwPlatformGetWindowPos (_GLFWwindow * window, int * xpos, int * ypos)
Referenced by glfwGetWindowPos().
_glfwPlatformSetWindowPos()
void _glfwPlatformSetWindowPos (_GLFWwindow * window, int x, int y)
Referenced by _glfwInputMonitor(), and glfwSetWindowPos().
_glfwPlatformGetWindowSize()
void _glfwPlatformGetWindowSize (_GLFWwindow * window, int * width, int * height)
Referenced by _glfwInputMonitor(), centerCursor(), createNativeWindow(), glfwCreateWindow(), and glfwGetWindowSize().
_glfwPlatformSetWindowSize()
void _glfwPlatformSetWindowSize (_GLFWwindow * window, int width, int height)
Referenced by glfwSetWindowSize().
_glfwPlatformSetWindowSizeLimits()
void _glfwPlatformSetWindowSizeLimits (_GLFWwindow * window, int minwidth, int minheight, int maxwidth, int maxheight)
Referenced by glfwSetWindowSizeLimits().
_glfwPlatformSetWindowAspectRatio()
void _glfwPlatformSetWindowAspectRatio (_GLFWwindow * window, int numer, int denom)
Referenced by glfwSetWindowAspectRatio().
_glfwPlatformGetFramebufferSize()
void _glfwPlatformGetFramebufferSize (_GLFWwindow * window, int * width, int * height)
Referenced by createNativeWindow(), glfwGetFramebufferSize(), and makeContextCurrentOSMesa().
_glfwPlatformGetWindowFrameSize()
void _glfwPlatformGetWindowFrameSize (_GLFWwindow * window, int * left, int * top, int * right, int * bottom)
Referenced by _glfwInputMonitor(), and glfwGetWindowFrameSize().
_glfwPlatformGetWindowContentScale()
void _glfwPlatformGetWindowContentScale (_GLFWwindow * window, float * xscale, float * yscale)
Referenced by glfwGetWindowContentScale().
_glfwPlatformIconifyWindow()
void _glfwPlatformIconifyWindow (_GLFWwindow * window)
Referenced by glfwIconifyWindow().
_glfwPlatformRestoreWindow()
void _glfwPlatformRestoreWindow (_GLFWwindow * window)
Referenced by glfwRestoreWindow().
_glfwPlatformMaximizeWindow()
void _glfwPlatformMaximizeWindow (_GLFWwindow * window)
Referenced by glfwMaximizeWindow().
_glfwPlatformShowWindow()
void _glfwPlatformShowWindow (_GLFWwindow * window)
Referenced by _glfwPlatformCreateWindow(), glfwCreateWindow(), and glfwShowWindow().
_glfwPlatformHideWindow()
void _glfwPlatformHideWindow (_GLFWwindow * window)
Referenced by glfwHideWindow().
_glfwPlatformRequestWindowAttention()
void _glfwPlatformRequestWindowAttention (_GLFWwindow * window)
Referenced by glfwRequestWindowAttention().
_glfwPlatformFocusWindow()
void _glfwPlatformFocusWindow (_GLFWwindow * window)
Referenced by _glfwPlatformCreateWindow(), glfwCreateWindow(), glfwFocusWindow(), and glfwShowWindow().
_glfwPlatformSetWindowMonitor()
void _glfwPlatformSetWindowMonitor (_GLFWwindow * window, _GLFWmonitor * monitor, int xpos, int ypos, int width, int height, int refreshRate)
Referenced by _glfwInputMonitor(), and glfwSetWindowMonitor().
_glfwPlatformWindowFocused()
int _glfwPlatformWindowFocused (_GLFWwindow * window)
Referenced by glfwGetWindowAttrib(), glfwSetCursorPos(), and glfwSetInputMode().
_glfwPlatformWindowIconified()
int _glfwPlatformWindowIconified (_GLFWwindow * window)
Referenced by glfwGetWindowAttrib().
_glfwPlatformWindowVisible()
int _glfwPlatformWindowVisible (_GLFWwindow * window)
Referenced by glfwGetWindowAttrib().
_glfwPlatformWindowMaximized()
int _glfwPlatformWindowMaximized (_GLFWwindow * window)
Referenced by glfwGetWindowAttrib().
_glfwPlatformWindowHovered()
int _glfwPlatformWindowHovered (_GLFWwindow * window)
Referenced by glfwGetWindowAttrib().
_glfwPlatformFramebufferTransparent()
int _glfwPlatformFramebufferTransparent (_GLFWwindow * window)
Referenced by glfwGetWindowAttrib().
_glfwPlatformSetWindowResizable()
void _glfwPlatformSetWindowResizable (_GLFWwindow * window, GLFWbool enabled)
Referenced by glfwSetWindowAttrib().
_glfwPlatformSetWindowDecorated()
void _glfwPlatformSetWindowDecorated (_GLFWwindow * window, GLFWbool enabled)
Referenced by glfwSetWindowAttrib().
_glfwPlatformSetWindowFloating()
void _glfwPlatformSetWindowFloating (_GLFWwindow * window, GLFWbool enabled)
Referenced by glfwSetWindowAttrib().
_glfwPlatformGetWindowOpacity()
float _glfwPlatformGetWindowOpacity (_GLFWwindow * window)
Referenced by glfwGetWindowOpacity().
_glfwPlatformSetWindowOpacity()
void _glfwPlatformSetWindowOpacity (_GLFWwindow * window, float opacity)
Referenced by glfwSetWindowOpacity().
_glfwPlatformPollEvents()
void _glfwPlatformPollEvents (void)
Referenced by _glfwPlatformSetWindowMonitor(), _glfwPlatformWaitEvents(), _glfwPlatformWaitEventsTimeout(), and glfwPollEvents().
_glfwPlatformWaitEvents()
void _glfwPlatformWaitEvents (void)
Referenced by glfwWaitEvents().
_glfwPlatformWaitEventsTimeout()
void _glfwPlatformWaitEventsTimeout (double timeout)
Referenced by glfwWaitEventsTimeout().
_glfwPlatformPostEmptyEvent()
void _glfwPlatformPostEmptyEvent (void)
Referenced by glfwPostEmptyEvent().
_glfwPlatformGetCursorPos()
void _glfwPlatformGetCursorPos (_GLFWwindow * window, double * xpos, double * ypos)
Referenced by _glfwPlatformSetCursorMode(), glfwGetCursorPos(), and glfwSetInputMode().
_glfwPlatformSetCursorPos()
void _glfwPlatformSetCursorPos (_GLFWwindow * window, double x, double y)
Referenced by _glfwPlatformSetCursorMode(), centerCursor(), glfwCreateWindow(), and glfwSetCursorPos().
_glfwPlatformSetCursorMode()
void _glfwPlatformSetCursorMode (_GLFWwindow * window, int mode)
Referenced by glfwSetInputMode().
_glfwPlatformGetScancodeName()
const char* _glfwPlatformGetScancodeName (int scancode)
Referenced by glfwGetKeyName().
_glfwPlatformGetKeyScancode()
int _glfwPlatformGetKeyScancode (int key)
Referenced by _glfwInputWindowFocus(), glfwGetKeyName(), and glfwGetKeyScancode().
_glfwPlatformCreateCursor()
int _glfwPlatformCreateCursor (_GLFWcursor * cursor, const GLFWimage * image, int xhot, int yhot)
Referenced by glfwCreateCursor().
_glfwPlatformCreateStandardCursor()
int _glfwPlatformCreateStandardCursor (_GLFWcursor * cursor, int shape)
Referenced by glfwCreateStandardCursor().
_glfwPlatformDestroyCursor()
void _glfwPlatformDestroyCursor (_GLFWcursor * cursor)
Referenced by glfwDestroyCursor().
_glfwPlatformSetCursor()
void _glfwPlatformSetCursor (_GLFWwindow * window, _GLFWcursor * cursor)
Referenced by glfwSetCursor(), and pointerHandleEnter().
_glfwPlatformSetClipboardString()
void _glfwPlatformSetClipboardString (const char * string)
Referenced by glfwSetClipboardString().
_glfwPlatformGetClipboardString()
const char* _glfwPlatformGetClipboardString (void)
Referenced by glfwGetClipboardString().
_glfwPlatformGetRequiredInstanceExtensions()
void _glfwPlatformGetRequiredInstanceExtensions (char ** extensions)
Referenced by _glfwInitVulkan().
_glfwPlatformGetPhysicalDevicePresentationSupport()
int _glfwPlatformGetPhysicalDevicePresentationSupport (VkInstance instance, VkPhysicalDevice device, uint32_t queuefamily)
Referenced by glfwGetPhysicalDevicePresentationSupport().
_glfwPlatformCreateWindowSurface()
VkResult _glfwPlatformCreateWindowSurface (VkInstance instance, _GLFWwindow * window, const VkAllocationCallbacks * allocator, VkSurfaceKHR * surface)
Referenced by glfwCreateWindowSurface().
glfwGetCocoaWindow()
GLFWAPI id glfwGetCocoaWindow (GLFWwindow * handle)
References _GLFW_REQUIRE_INIT_OR_RETURN.
Variable Documentation
kEmptyRange
const NSRange kEmptyRange = { NSNotFound, 0 } static