Aurora Framework: sds.c File Reference
sds.c File Reference
Classes
struct tag_SDS_PRIVATE
Macros
#define SDS_3BYTE_TO_INT_DECODE(x) (((x) & 0x7F) | (((x) & 0x7F00) >> 1) | (((x) & 0x7F0000) >> 2))
#define SDS_AUDIO_BYTES_PER_BLOCK 120
#define SDS_BLOCK_SIZE 127
#define SDS_DATA_OFFSET 0x15
#define SDS_INT_TO_3BYTE_ENCODE(x) (((x) & 0x7F) | (((x) << 1) & 0x7F00) | (((x) << 2) & 0x7F0000))
Typedefs
typedef struct tag_SDS_PRIVATE SDS_PRIVATE
Functions
static int sds_2byte_read (SF_PRIVATE *psf, SDS_PRIVATE *psds)
static int sds_2byte_write (SF_PRIVATE *psf, SDS_PRIVATE *psds)
static int sds_3byte_read (SF_PRIVATE *psf, SDS_PRIVATE *psds)
static int sds_3byte_write (SF_PRIVATE *psf, SDS_PRIVATE *psds)
static int sds_4byte_read (SF_PRIVATE *psf, SDS_PRIVATE *psds)
static int sds_4byte_write (SF_PRIVATE *psf, SDS_PRIVATE *psds)
static int sds_byterate (SF_PRIVATE *psf)
static int sds_close (SF_PRIVATE *psf)
static int sds_init (SF_PRIVATE *psf, SDS_PRIVATE *psds)
int sds_open (SF_PRIVATE *psf)
static int sds_read (SF_PRIVATE *psf, SDS_PRIVATE *psds, int *iptr, int readcount)
static sf_count_t sds_read_d (SF_PRIVATE *psf, double *ptr, sf_count_t len)
static sf_count_t sds_read_f (SF_PRIVATE *psf, float *ptr, sf_count_t len)
static int sds_read_header (SF_PRIVATE *psf, SDS_PRIVATE *psds)
static sf_count_t sds_read_i (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static sf_count_t sds_read_s (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static sf_count_t sds_seek (SF_PRIVATE *psf, int mode, sf_count_t offset)
static int sds_write (SF_PRIVATE *psf, SDS_PRIVATE *psds, const int *iptr, int writecount)
static sf_count_t sds_write_d (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
static sf_count_t sds_write_f (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
static int sds_write_header (SF_PRIVATE *psf, int calc_length)
static sf_count_t sds_write_i (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
static sf_count_t sds_write_s (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
Macro Definition Documentation
SDS_DATA_OFFSET
#define SDS_DATA_OFFSET 0x15
Referenced by sds_open(), and sds_read_header().
SDS_BLOCK_SIZE
#define SDS_BLOCK_SIZE 127
Referenced by sds_2byte_read(), sds_2byte_write(), sds_3byte_read(), sds_3byte_write(), sds_4byte_read(), sds_4byte_write(), sds_read_header(), sds_seek(), and sds_write_header().
SDS_AUDIO_BYTES_PER_BLOCK
#define SDS_AUDIO_BYTES_PER_BLOCK 120
Referenced by sds_init(), and sds_read_header().
SDS_3BYTE_TO_INT_DECODE
#define SDS_3BYTE_TO_INT_DECODE (x) (((x) & 0x7F) | (((x) & 0x7F00) >> 1) | (((x) & 0x7F0000) >> 2))
Referenced by sds_read_header().
SDS_INT_TO_3BYTE_ENCODE
#define SDS_INT_TO_3BYTE_ENCODE (x) (((x) & 0x7F) | (((x) << 1) & 0x7F00) | (((x) << 2) & 0x7F0000))
Referenced by sds_write_header().
Typedef Documentation
SDS_PRIVATE
typedef struct tag_SDS_PRIVATE SDS_PRIVATE
Function Documentation
sds_close()
static int sds_close (SF_PRIVATE * psf) static
References sf_private_tag::codec_data, sf_private_tag::file, memset(), PSF_FILE::mode, NULL, psf_log_printf(), tag_SDS_PRIVATE::samplesperblock, sds_write_header(), SFE_INTERNAL, tag_SDS_PRIVATE::write_count, tag_SDS_PRIVATE::write_data, and tag_SDS_PRIVATE::writer.
Referenced by sds_open().
sds_write_header()
static int sds_write_header (SF_PRIVATE * psf, int calc_length) static
References BHW1, BHW2, BHW3, tag_SDS_PRIVATE::bitwidth, sf_private_tag::codec_data, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::error, sf_private_tag::header, sf_private_tag::indx, sf_private_tag::is_pipe, NULL, sf_private_tag::pipeoffset, psf_binheader_writef(), psf_fseek(), psf_ftell(), psf_fwrite(), psf_log_printf(), sf_private_tag::ptr, SDS_BLOCK_SIZE, SDS_INT_TO_3BYTE_ENCODE, sf_private_tag::sf, SF_CODEC, SFE_INTERNAL, SFE_SDS_BAD_BIT_WIDTH, tag_SDS_PRIVATE::total_written, tag_SDS_PRIVATE::write_block, tag_SDS_PRIVATE::write_count, and tag_SDS_PRIVATE::writer.
Referenced by sds_close(), and sds_open().
sds_read_header()
static int sds_read_header (SF_PRIVATE * psf, SDS_PRIVATE * psds) static
References tag_SDS_PRIVATE::bitwidth, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::filelength, tag_SDS_PRIVATE::frames, psf_binheader_readf(), psf_fread(), psf_fseek(), psf_log_printf(), tag_SDS_PRIVATE::samplesperblock, SDS_3BYTE_TO_INT_DECODE, SDS_AUDIO_BYTES_PER_BLOCK, SDS_BLOCK_SIZE, SDS_DATA_OFFSET, sf_private_tag::sf, SFE_SDS_BAD_BIT_WIDTH, SFE_SDS_NOT_SDS, and tag_SDS_PRIVATE::total_blocks.
Referenced by sds_open().
sds_init()
static int sds_init (SF_PRIVATE * psf, SDS_PRIVATE * psds) static
References tag_SDS_PRIVATE::bitwidth, sf_private_tag::error, sf_private_tag::file, PSF_FILE::mode, sf_private_tag::read_double, sf_private_tag::read_float, sf_private_tag::read_int, sf_private_tag::read_short, tag_SDS_PRIVATE::reader, tag_SDS_PRIVATE::samplesperblock, sds_2byte_read(), sds_2byte_write(), sds_3byte_read(), sds_3byte_write(), sds_4byte_read(), sds_4byte_write(), SDS_AUDIO_BYTES_PER_BLOCK, sds_read_d(), sds_read_f(), sds_read_i(), sds_read_s(), sds_write_d(), sds_write_f(), sds_write_i(), sds_write_s(), SFE_SDS_BAD_BIT_WIDTH, sf_private_tag::write_double, sf_private_tag::write_float, sf_private_tag::write_int, sf_private_tag::write_short, and tag_SDS_PRIVATE::writer.
Referenced by sds_open().
sds_read_s()
static sf_count_t sds_read_s (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, BUF_UNION::ibuf, NULL, and sds_read().
Referenced by sds_init().
sds_read_i()
static sf_count_t sds_read_i (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
References sf_private_tag::codec_data, NULL, and sds_read().
Referenced by sds_init().
sds_read_f()
static sf_count_t sds_read_f (SF_PRIVATE * psf, float * ptr, sf_count_t len) static
References ARRAY_LEN, tag_SDS_PRIVATE::bitwidth, sf_private_tag::codec_data, BUF_UNION::ibuf, sf_private_tag::norm_float, NULL, and sds_read().
Referenced by sds_init().
sds_read_d()
static sf_count_t sds_read_d (SF_PRIVATE * psf, double * ptr, sf_count_t len) static
References ARRAY_LEN, tag_SDS_PRIVATE::bitwidth, sf_private_tag::codec_data, BUF_UNION::ibuf, sf_private_tag::norm_double, NULL, and sds_read().
Referenced by sds_init().
sds_write_s()
static sf_count_t sds_write_s (SF_PRIVATE * psf, const short * ptr, sf_count_t len) static
References arith_shift_left(), ARRAY_LEN, sf_private_tag::codec_data, BUF_UNION::ibuf, NULL, sds_write(), and tag_SDS_PRIVATE::total_written.
Referenced by sds_init().
sds_write_i()
static sf_count_t sds_write_i (SF_PRIVATE * psf, const int * ptr, sf_count_t len) static
References sf_private_tag::codec_data, NULL, sds_write(), and tag_SDS_PRIVATE::total_written.
Referenced by sds_init().
sds_write_f()
static sf_count_t sds_write_f (SF_PRIVATE * psf, const float * ptr, sf_count_t len) static
References ARRAY_LEN, tag_SDS_PRIVATE::bitwidth, sf_private_tag::codec_data, BUF_UNION::ibuf, sf_private_tag::norm_float, NULL, sds_write(), and tag_SDS_PRIVATE::total_written.
Referenced by sds_init().
sds_write_d()
static sf_count_t sds_write_d (SF_PRIVATE * psf, const double * ptr, sf_count_t len) static
References ARRAY_LEN, tag_SDS_PRIVATE::bitwidth, sf_private_tag::codec_data, BUF_UNION::ibuf, sf_private_tag::norm_double, NULL, sds_write(), and tag_SDS_PRIVATE::total_written.
Referenced by sds_init().
sds_seek()
static sf_count_t sds_seek (SF_PRIVATE * psf, int mode, sf_count_t offset) static
References sf_private_tag::codec_data, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::error, mode(), NULL, psf_fseek(), PSF_SEEK_ERROR, tag_SDS_PRIVATE::read_block, tag_SDS_PRIVATE::read_count, tag_SDS_PRIVATE::reader, tag_SDS_PRIVATE::samplesperblock, SDS_BLOCK_SIZE, sf_private_tag::sf, SFE_BAD_SEEK, SFE_INTERNAL, SFE_SEEK_FAILED, tag_SDS_PRIVATE::total_blocks, tag_SDS_PRIVATE::write_block, tag_SDS_PRIVATE::write_count, and tag_SDS_PRIVATE::writer.
Referenced by sds_open().
sds_byterate()
static int sds_byterate (SF_PRIVATE * psf) static
References sf_private_tag::datalength, sf_private_tag::file, PSF_FILE::mode, and sf_private_tag::sf.
Referenced by sds_open().
sds_2byte_read()
static int sds_2byte_read (SF_PRIVATE * psf, SDS_PRIVATE * psds) static
References arith_shift_left(), tag_SDS_PRIVATE::frames, memset(), psf_fread(), psf_log_printf(), tag_SDS_PRIVATE::read_block, tag_SDS_PRIVATE::read_count, tag_SDS_PRIVATE::read_data, tag_SDS_PRIVATE::read_samples, tag_SDS_PRIVATE::samplesperblock, and SDS_BLOCK_SIZE.
Referenced by sds_init().
sds_3byte_read()
static int sds_3byte_read (SF_PRIVATE * psf, SDS_PRIVATE * psds) static
References tag_SDS_PRIVATE::frames, memset(), psf_fread(), psf_log_printf(), tag_SDS_PRIVATE::read_block, tag_SDS_PRIVATE::read_count, tag_SDS_PRIVATE::read_data, tag_SDS_PRIVATE::read_samples, tag_SDS_PRIVATE::samplesperblock, and SDS_BLOCK_SIZE.
Referenced by sds_init().
sds_4byte_read()
static int sds_4byte_read (SF_PRIVATE * psf, SDS_PRIVATE * psds) static
References tag_SDS_PRIVATE::frames, memset(), psf_fread(), psf_log_printf(), tag_SDS_PRIVATE::read_block, tag_SDS_PRIVATE::read_count, tag_SDS_PRIVATE::read_data, tag_SDS_PRIVATE::read_samples, tag_SDS_PRIVATE::samplesperblock, and SDS_BLOCK_SIZE.
Referenced by sds_init().
sds_read()
static int sds_read (SF_PRIVATE * psf, SDS_PRIVATE * psds, int * iptr, int readcount) static
References tag_SDS_PRIVATE::frames, memcpy(), memset(), tag_SDS_PRIVATE::read_block, tag_SDS_PRIVATE::read_count, tag_SDS_PRIVATE::read_samples, tag_SDS_PRIVATE::reader, and tag_SDS_PRIVATE::samplesperblock.
Referenced by sds_read_d(), sds_read_f(), sds_read_i(), and sds_read_s().
sds_2byte_write()
static int sds_2byte_write (SF_PRIVATE * psf, SDS_PRIVATE * psds) static
References tag_SDS_PRIVATE::frames, psf_fwrite(), psf_log_printf(), tag_SDS_PRIVATE::samplesperblock, SDS_BLOCK_SIZE, tag_SDS_PRIVATE::total_blocks, tag_SDS_PRIVATE::write_block, tag_SDS_PRIVATE::write_count, tag_SDS_PRIVATE::write_data, and tag_SDS_PRIVATE::write_samples.
Referenced by sds_init().
sds_3byte_write()
static int sds_3byte_write (SF_PRIVATE * psf, SDS_PRIVATE * psds) static
References tag_SDS_PRIVATE::frames, psf_fwrite(), psf_log_printf(), tag_SDS_PRIVATE::samplesperblock, SDS_BLOCK_SIZE, tag_SDS_PRIVATE::total_blocks, tag_SDS_PRIVATE::write_block, tag_SDS_PRIVATE::write_count, tag_SDS_PRIVATE::write_data, and tag_SDS_PRIVATE::write_samples.
Referenced by sds_init().
sds_4byte_write()
static int sds_4byte_write (SF_PRIVATE * psf, SDS_PRIVATE * psds) static
References tag_SDS_PRIVATE::frames, psf_fwrite(), psf_log_printf(), tag_SDS_PRIVATE::samplesperblock, SDS_BLOCK_SIZE, tag_SDS_PRIVATE::total_blocks, tag_SDS_PRIVATE::write_block, tag_SDS_PRIVATE::write_count, tag_SDS_PRIVATE::write_data, and tag_SDS_PRIVATE::write_samples.
Referenced by sds_init().
sds_write()
static int sds_write (SF_PRIVATE * psf, SDS_PRIVATE * psds, const int * iptr, int writecount) static
References memcpy(), tag_SDS_PRIVATE::samplesperblock, tag_SDS_PRIVATE::write_count, tag_SDS_PRIVATE::write_samples, and tag_SDS_PRIVATE::writer.
Referenced by sds_write_d(), sds_write_f(), sds_write_i(), and sds_write_s().
sds_open()
int sds_open (SF_PRIVATE * psf)
References sf_private_tag::blockwidth, sf_private_tag::byterate, sf_private_tag::codec_data, sf_private_tag::container_close, sf_private_tag::error, sf_private_tag::file, sf_private_tag::filelength, PSF_FILE::mode, psf_fseek(), sds_byterate(), sds_close(), SDS_DATA_OFFSET, sds_init(), sds_read_header(), sds_seek(), sds_write_header(), sf_private_tag::seek, sf_private_tag::sf, SF_CONTAINER, SFE_BAD_OPEN_FORMAT, SFE_MALLOC_FAILED, and sf_private_tag::write_header.
Referenced by psf_open_file().