Aurora Framework: g723_24.c File Reference
g723_24.c File Reference
Functions
int g723_24_decoder (int i, G72x_STATE *state_ptr)
int g723_24_encoder (int sl, G72x_STATE *state_ptr)
Variables
static short _dqlntab [8] = { -2048, 135, 273, 373, 373, 273, 135, -2048 }
static short _fitab [8] = { 0, 0x200, 0x400, 0xE00, 0xE00, 0x400, 0x200, 0 }
static short _witab [8] = { -128, 960, 4384, 18624, 18624, 4384, 960, -128 }
static short qtab_723_24 [3] = { 8, 218, 331 }
Function Documentation
g723_24_encoder()
int g723_24_encoder (int sl, G72x_STATE * state_ptr)
References _dqlntab, _fitab, _witab, predictor_pole(), predictor_zero(), qtab_723_24, quantize(), reconstruct(), step_size(), and update().
Referenced by g723_test(), and g72x_writer_init().
g723_24_decoder()
int g723_24_decoder (int i, G72x_STATE * state_ptr)
References _dqlntab, _fitab, _witab, arith_shift_left(), predictor_pole(), predictor_zero(), reconstruct(), step_size(), and update().
Referenced by g723_test(), and g72x_reader_init().
Variable Documentation
_dqlntab
short _dqlntab[8] = { -2048, 135, 273, 373, 373, 273, 135, -2048 } static
Referenced by g723_24_decoder(), and g723_24_encoder().
_witab
short _witab[8] = { -128, 960, 4384, 18624, 18624, 4384, 960, -128 } static
Referenced by g723_24_decoder(), and g723_24_encoder().
_fitab
short _fitab[8] = { 0, 0x200, 0x400, 0xE00, 0xE00, 0x400, 0x200, 0 } static
Referenced by g723_24_decoder(), and g723_24_encoder().
qtab_723_24
short qtab_723_24[3] = { 8, 218, 331 } static
Referenced by g723_24_encoder().