Aurora Framework: AuroraFW::GEngine::BaseColor< T > Struct Template Reference
AuroraFW::GEngine::BaseColor< T > Struct Template Reference
A template struct that represents colors.
Public Member Functions
template<>
BaseColor (int r, int g, int b, int a)
template<>
BaseColor (uint32_t hex)
template<>
BaseColor (CommonColor hex)
template<>
BaseColor (uint32_t hex)
template<>
BaseColor (CommonColor hex)
template<>
BaseColor (int r, int g, int b, int a)
BaseColor (int, int, int, int=255)
BaseColor (float, float, float, float=1.0f)
BaseColor (uint32_t)
BaseColor (CommonColor)
BaseColor (const BaseColor< T > &)
template<>
int alpha () const
int alpha () const
template<>
int alpha () const
template<>
float alphaF () const
float alphaF () const
template<>
float alphaF () const
template<>
int blue () const
int blue () const
template<>
int blue () const
template<>
float blueF () const
float blueF () const
template<>
float blueF () const
template<>
int green () const
int green () const
template<>
int green () const
template<>
float greenF () const
float greenF () const
template<>
float greenF () const
template<>
int red () const
int red () const
template<>
int red () const
template<>
float redF () const
float redF () const
template<>
float redF () const
template<>
void setAlpha (float _a)
void setAlpha (int)
void setAlpha (float)
template<>
void setAlpha (int _a)
template<>
void setAlpha (float _a)
template<>
void setAlpha (int _a)
template<>
void setBlue (float _b)
void setBlue (int)
void setBlue (float)
template<>
void setBlue (int _b)
template<>
void setBlue (float _b)
template<>
void setBlue (int _b)
template<>
void setGreen (float _g)
void setGreen (int)
void setGreen (float)
template<>
void setGreen (int _g)
template<>
void setGreen (float _g)
template<>
void setGreen (int _g)
template<>
void setRed (float _r)
void setRed (int)
void setRed (float)
template<>
void setRed (int _r)
template<>
void setRed (float _r)
template<>
void setRed (int _r)
void setRGB (uint32_t)
void setRGB (int[3])
void setRGBA (int[4])
Static Public Member Functions
static BaseColor< T > HSL (int, int, int, int=255)
static BaseColor< T > HSL (float, float, float, float=1.0f)
static BaseColor< T > HSV (int, int, int, int=255)
static BaseColor< T > HSV (float, float, float, float=1.0f)
Public Attributes
T a
T b
T g
T r
Detailed Description
template<class T>
struct AuroraFW::GEngine::BaseColor< T >
A template struct that represents colors.
This struct manipulates colors using a specific data type for color components.
Since
snapshot20170930
Constructor & Destructor Documentation
BaseColor() [1/11]
template<class T> AuroraFW::GEngine::BaseColor< T >::BaseColor (int , int , int , int = 255)
BaseColor() [2/11]
template<class T> AuroraFW::GEngine::BaseColor< T >::BaseColor (float , float , float , float = 1.0f)
BaseColor() [3/11]
template<class T> AuroraFW::GEngine::BaseColor< T >::BaseColor (uint32_t)
BaseColor() [4/11]
template<class T> AuroraFW::GEngine::BaseColor< T >::BaseColor (CommonColor)
BaseColor() [5/11]
template<class T> AuroraFW::GEngine::BaseColor< T >::BaseColor (const BaseColor< T > &)
BaseColor() [6/11]
template<> AuroraFW::GEngine::BaseColor< float >::BaseColor (int r, int g, int b, int a)
BaseColor() [7/11]
template<> AuroraFW::GEngine::BaseColor< float >::BaseColor (uint32_t hex)
BaseColor() [8/11]
template<> AuroraFW::GEngine::BaseColor< float >::BaseColor (CommonColor hex)
BaseColor() [9/11]
template<> AuroraFW::GEngine::BaseColor< byte_t >::BaseColor (uint32_t hex)
BaseColor() [10/11]
template<> AuroraFW::GEngine::BaseColor< byte_t >::BaseColor (CommonColor hex)
BaseColor() [11/11]
template<> AuroraFW::GEngine::BaseColor< byte_t >::BaseColor (int r, int g, int b, int a)
Member Function Documentation
red() [1/3]
template<class T> int AuroraFW::GEngine::BaseColor< T >::red () const
Referenced by AuroraFW::ImageManager::Image::drawPixel().
redF() [1/3]
template<class T> float AuroraFW::GEngine::BaseColor< T >::redF () const
green() [1/3]
template<class T> int AuroraFW::GEngine::BaseColor< T >::green () const
Referenced by AuroraFW::ImageManager::Image::drawPixel().
greenF() [1/3]
template<class T> float AuroraFW::GEngine::BaseColor< T >::greenF () const
blue() [1/3]
template<class T> int AuroraFW::GEngine::BaseColor< T >::blue () const
Referenced by AuroraFW::ImageManager::Image::drawPixel().
blueF() [1/3]
template<class T> float AuroraFW::GEngine::BaseColor< T >::blueF () const
alpha() [1/3]
template<class T> int AuroraFW::GEngine::BaseColor< T >::alpha () const
Referenced by AuroraFW::ImageManager::Image::drawPixel().
alphaF() [1/3]
template<class T> float AuroraFW::GEngine::BaseColor< T >::alphaF () const
setRed() [1/6]
template<class T> void AuroraFW::GEngine::BaseColor< T >::setRed (int)
setRed() [2/6]
template<class T> void AuroraFW::GEngine::BaseColor< T >::setRed (float)
setGreen() [1/6]
template<class T> void AuroraFW::GEngine::BaseColor< T >::setGreen (int)
setGreen() [2/6]
template<class T> void AuroraFW::GEngine::BaseColor< T >::setGreen (float)
setBlue() [1/6]
template<class T> void AuroraFW::GEngine::BaseColor< T >::setBlue (int)
setBlue() [2/6]
template<class T> void AuroraFW::GEngine::BaseColor< T >::setBlue (float)
setAlpha() [1/6]
template<class T> void AuroraFW::GEngine::BaseColor< T >::setAlpha (int)
setAlpha() [2/6]
template<class T> void AuroraFW::GEngine::BaseColor< T >::setAlpha (float)
setRGB() [1/2]
template<class T> void AuroraFW::GEngine::BaseColor< T >::setRGB (uint32_t)
setRGB() [2/2]
template<class T> void AuroraFW::GEngine::BaseColor< T >::setRGB (int [3])
setRGBA()
template<class T> void AuroraFW::GEngine::BaseColor< T >::setRGBA (int [4])
HSL() [1/2]
template<class T> static BaseColor<T> AuroraFW::GEngine::BaseColor< T >::HSL (int , int , int , int = 255) static
HSL() [2/2]
template<class T> static BaseColor<T> AuroraFW::GEngine::BaseColor< T >::HSL (float , float , float , float = 1.0f) static
HSV() [1/2]
template<class T> static BaseColor<T> AuroraFW::GEngine::BaseColor< T >::HSV (int , int , int , int = 255) static
HSV() [2/2]
template<class T> static BaseColor<T> AuroraFW::GEngine::BaseColor< T >::HSV (float , float , float , float = 1.0f) static
red() [2/3]
template<> int AuroraFW::GEngine::BaseColor< byte_t >::red () const inline
green() [2/3]
template<> int AuroraFW::GEngine::BaseColor< byte_t >::green () const inline
blue() [2/3]
template<> int AuroraFW::GEngine::BaseColor< byte_t >::blue () const inline
alpha() [2/3]
template<> int AuroraFW::GEngine::BaseColor< byte_t >::alpha () const inline
References a.
redF() [2/3]
template<> float AuroraFW::GEngine::BaseColor< float >::redF () const inline
greenF() [2/3]
template<> float AuroraFW::GEngine::BaseColor< float >::greenF () const inline
blueF() [2/3]
template<> float AuroraFW::GEngine::BaseColor< float >::blueF () const inline
alphaF() [2/3]
template<> float AuroraFW::GEngine::BaseColor< float >::alphaF () const inline
References a.
setRed() [3/6]
template<> void AuroraFW::GEngine::BaseColor< float >::setRed (float _r) inline
setGreen() [3/6]
template<> void AuroraFW::GEngine::BaseColor< float >::setGreen (float _g) inline
setBlue() [3/6]
template<> void AuroraFW::GEngine::BaseColor< float >::setBlue (float _b) inline
setAlpha() [3/6]
template<> void AuroraFW::GEngine::BaseColor< float >::setAlpha (float _a) inline
References a.
setRed() [4/6]
template<> void AuroraFW::GEngine::BaseColor< byte_t >::setRed (int _r) inline
setGreen() [4/6]
template<> void AuroraFW::GEngine::BaseColor< byte_t >::setGreen (int _g) inline
setBlue() [4/6]
template<> void AuroraFW::GEngine::BaseColor< byte_t >::setBlue (int _b) inline
setAlpha() [4/6]
template<> void AuroraFW::GEngine::BaseColor< byte_t >::setAlpha (int _a) inline
References a.
red() [3/3]
template<> int AuroraFW::GEngine::BaseColor< float >::red () const
green() [3/3]
template<> int AuroraFW::GEngine::BaseColor< float >::green () const
blue() [3/3]
template<> int AuroraFW::GEngine::BaseColor< float >::blue () const
alpha() [3/3]
template<> int AuroraFW::GEngine::BaseColor< float >::alpha () const
References a.
redF() [3/3]
template<> float AuroraFW::GEngine::BaseColor< byte_t >::redF () const
greenF() [3/3]
template<> float AuroraFW::GEngine::BaseColor< byte_t >::greenF () const
blueF() [3/3]
template<> float AuroraFW::GEngine::BaseColor< byte_t >::blueF () const
alphaF() [3/3]
template<> float AuroraFW::GEngine::BaseColor< byte_t >::alphaF () const
References a.
setRed() [5/6]
template<> void AuroraFW::GEngine::BaseColor< byte_t >::setRed (float _r)
setGreen() [5/6]
template<> void AuroraFW::GEngine::BaseColor< byte_t >::setGreen (float _g)
setBlue() [5/6]
template<> void AuroraFW::GEngine::BaseColor< byte_t >::setBlue (float _b)
setAlpha() [5/6]
template<> void AuroraFW::GEngine::BaseColor< byte_t >::setAlpha (float _a)
References a.
setRed() [6/6]
template<> void AuroraFW::GEngine::BaseColor< float >::setRed (int _r)
setGreen() [6/6]
template<> void AuroraFW::GEngine::BaseColor< float >::setGreen (int _g)
setBlue() [6/6]
template<> void AuroraFW::GEngine::BaseColor< float >::setBlue (int _b)
setAlpha() [6/6]
template<> void AuroraFW::GEngine::BaseColor< float >::setAlpha (int _a)
References a.
Member Data Documentation
r
template<class T> T AuroraFW::GEngine::BaseColor< T >::r
g
template<class T> T AuroraFW::GEngine::BaseColor< T >::g
b
template<class T> T AuroraFW::GEngine::BaseColor< T >::b
a
template<class T> T AuroraFW::GEngine::BaseColor< T >::a
The documentation for this struct was generated from the following file:
gengine/core/include/AuroraFW/GEngine/Color.h