Aurora Framework: Init.c File Reference
X11/Init.c File Reference
Functions
Cursor _glfwCreateCursorX11 (const GLFWimage *image, int xhot, int yhot)
void _glfwGrabErrorHandlerX11 (void)
void _glfwInputErrorX11 (int error, const char *message)
const char * _glfwPlatformGetVersionString (void)
int _glfwPlatformInit (void)
void _glfwPlatformTerminate (void)
void _glfwReleaseErrorHandlerX11 (void)
static Window createHelperWindow (void)
static Cursor createHiddenCursor (void)
static void createKeyTables (void)
static void detectEWMH (void)
static int errorHandler (Display *display, XErrorEvent *event)
static Atom getSupportedAtom (Atom *supportedAtoms, unsigned long atomCount, const char *atomName)
static void getSystemContentScale (float *xscale, float *yscale)
static GLFWbool hasUsableInputMethodStyle (void)
static GLFWbool initExtensions (void)
static int translateKeyCode (int scancode)
Function Documentation
translateKeyCode()
static int translateKeyCode (int scancode) static
References _glfw, _GLFWlibrary::available, GLFW_KEY_0, GLFW_KEY_1, GLFW_KEY_2, GLFW_KEY_3, GLFW_KEY_4, GLFW_KEY_5, GLFW_KEY_6, GLFW_KEY_7, GLFW_KEY_8, GLFW_KEY_9, GLFW_KEY_A, GLFW_KEY_APOSTROPHE, GLFW_KEY_B, GLFW_KEY_BACKSLASH, GLFW_KEY_BACKSPACE, GLFW_KEY_C, GLFW_KEY_CAPS_LOCK, GLFW_KEY_COMMA, GLFW_KEY_D, GLFW_KEY_DELETE, GLFW_KEY_DOWN, GLFW_KEY_E, GLFW_KEY_END, GLFW_KEY_ENTER, GLFW_KEY_EQUAL, GLFW_KEY_ESCAPE, GLFW_KEY_F, GLFW_KEY_F1, GLFW_KEY_F10, GLFW_KEY_F11, GLFW_KEY_F12, GLFW_KEY_F13, GLFW_KEY_F14, GLFW_KEY_F15, GLFW_KEY_F16, GLFW_KEY_F17, GLFW_KEY_F18, GLFW_KEY_F19, GLFW_KEY_F2, GLFW_KEY_F20, GLFW_KEY_F21, GLFW_KEY_F22, GLFW_KEY_F23, GLFW_KEY_F24, GLFW_KEY_F25, GLFW_KEY_F3, GLFW_KEY_F4, GLFW_KEY_F5, GLFW_KEY_F6, GLFW_KEY_F7, GLFW_KEY_F8, GLFW_KEY_F9, GLFW_KEY_G, GLFW_KEY_GRAVE_ACCENT, GLFW_KEY_H, GLFW_KEY_HOME, GLFW_KEY_I, GLFW_KEY_INSERT, GLFW_KEY_J, GLFW_KEY_K, GLFW_KEY_KP_0, GLFW_KEY_KP_1, GLFW_KEY_KP_2, GLFW_KEY_KP_3, GLFW_KEY_KP_4, GLFW_KEY_KP_5, GLFW_KEY_KP_6, GLFW_KEY_KP_7, GLFW_KEY_KP_8, GLFW_KEY_KP_9, GLFW_KEY_KP_ADD, GLFW_KEY_KP_DECIMAL, GLFW_KEY_KP_DIVIDE, GLFW_KEY_KP_ENTER, GLFW_KEY_KP_EQUAL, GLFW_KEY_KP_MULTIPLY, GLFW_KEY_KP_SUBTRACT, GLFW_KEY_L, GLFW_KEY_LEFT, GLFW_KEY_LEFT_ALT, GLFW_KEY_LEFT_BRACKET, GLFW_KEY_LEFT_CONTROL, GLFW_KEY_LEFT_SHIFT, GLFW_KEY_LEFT_SUPER, GLFW_KEY_M, GLFW_KEY_MENU, GLFW_KEY_MINUS, GLFW_KEY_N, GLFW_KEY_NUM_LOCK, GLFW_KEY_O, GLFW_KEY_P, GLFW_KEY_PAGE_DOWN, GLFW_KEY_PAGE_UP, GLFW_KEY_PAUSE, GLFW_KEY_PERIOD, GLFW_KEY_PRINT_SCREEN, GLFW_KEY_Q, GLFW_KEY_R, GLFW_KEY_RIGHT, GLFW_KEY_RIGHT_ALT, GLFW_KEY_RIGHT_BRACKET, GLFW_KEY_RIGHT_CONTROL, GLFW_KEY_RIGHT_SHIFT, GLFW_KEY_RIGHT_SUPER, GLFW_KEY_S, GLFW_KEY_SCROLL_LOCK, GLFW_KEY_SEMICOLON, GLFW_KEY_SLASH, GLFW_KEY_SPACE, GLFW_KEY_T, GLFW_KEY_TAB, GLFW_KEY_U, GLFW_KEY_UNKNOWN, GLFW_KEY_UP, GLFW_KEY_V, GLFW_KEY_W, GLFW_KEY_WORLD_1, GLFW_KEY_X, GLFW_KEY_Y, and GLFW_KEY_Z.
Referenced by createKeyTables().
createKeyTables()
static void createKeyTables (void) static
References _glfw, _GLFWlibrary::available, GLFW_KEY_0, GLFW_KEY_1, GLFW_KEY_2, GLFW_KEY_3, GLFW_KEY_4, GLFW_KEY_5, GLFW_KEY_6, GLFW_KEY_7, GLFW_KEY_8, GLFW_KEY_9, GLFW_KEY_A, GLFW_KEY_APOSTROPHE, GLFW_KEY_B, GLFW_KEY_BACKSLASH, GLFW_KEY_C, GLFW_KEY_COMMA, GLFW_KEY_D, GLFW_KEY_E, GLFW_KEY_EQUAL, GLFW_KEY_F, GLFW_KEY_G, GLFW_KEY_GRAVE_ACCENT, GLFW_KEY_H, GLFW_KEY_I, GLFW_KEY_J, GLFW_KEY_K, GLFW_KEY_L, GLFW_KEY_LEFT_BRACKET, GLFW_KEY_M, GLFW_KEY_MINUS, GLFW_KEY_N, GLFW_KEY_O, GLFW_KEY_P, GLFW_KEY_PERIOD, GLFW_KEY_Q, GLFW_KEY_R, GLFW_KEY_RIGHT_BRACKET, GLFW_KEY_S, GLFW_KEY_SEMICOLON, GLFW_KEY_SLASH, GLFW_KEY_T, GLFW_KEY_U, GLFW_KEY_UNKNOWN, GLFW_KEY_V, GLFW_KEY_W, GLFW_KEY_WORLD_1, GLFW_KEY_X, GLFW_KEY_Y, GLFW_KEY_Z, memcpy(), memset(), setup::name, and translateKeyCode().
Referenced by initExtensions().
hasUsableInputMethodStyle()
static GLFWbool hasUsableInputMethodStyle (void) static
References _glfw, GLFW_FALSE, GLFW_TRUE, and NULL.
Referenced by _glfwPlatformInit().
getSupportedAtom()
static Atom getSupportedAtom (Atom * supportedAtoms, unsigned long atomCount, const char * atomName) static
References _glfw, and AuroraFW::None.
Referenced by detectEWMH().
detectEWMH()
static void detectEWMH (void) static
References _glfw, _glfwGetWindowPropertyX11(), _glfwGrabErrorHandlerX11(), _glfwReleaseErrorHandlerX11(), getSupportedAtom(), and NULL.
Referenced by initExtensions().
initExtensions()
static GLFWbool initExtensions (void) static
References _glfw, _glfw_dlopen, _glfw_dlsym, _glfwInputError(), _GLFWlibrary::available, createKeyTables(), detectEWMH(), GLFW_PLATFORM_ERROR, GLFW_TRUE, _GLFWlibrary::handle, setup::name, XF86VidModeQueryExtension, XineramaIsActive, XineramaQueryExtension, XIQueryVersion, XRenderQueryExtension, XRenderQueryVersion, XRRFreeScreenResources, XRRGetCrtcGammaSize, XRRGetScreenResourcesCurrent, XRRQueryExtension, XRRQueryVersion, and XRRSelectInput.
Referenced by _glfwPlatformInit().
getSystemContentScale()
static void getSystemContentScale (float * xscale, float * yscale) static
References _glfw, NULL, and value.
Referenced by _glfwPlatformInit().
createHiddenCursor()
static Cursor createHiddenCursor (void) static
References _glfwCreateCursorX11().
Referenced by _glfwPlatformInit().
createHelperWindow()
static Window createHelperWindow (void) static
References _glfw.
Referenced by _glfwPlatformInit().
errorHandler()
static int errorHandler (Display * display, XErrorEvent * event) static
References _glfw.
Referenced by _glfwGrabErrorHandlerX11().
_glfwGrabErrorHandlerX11()
void _glfwGrabErrorHandlerX11 (void)
References _glfw, and errorHandler().
Referenced by _glfwCreateContextGLX(), createNativeWindow(), and detectEWMH().
_glfwReleaseErrorHandlerX11()
void _glfwReleaseErrorHandlerX11 (void)
References _glfw, and NULL.
Referenced by _glfwCreateContextGLX(), createNativeWindow(), and detectEWMH().
_glfwInputErrorX11()
void _glfwInputErrorX11 (int error, const char * message)
References _glfw, _GLFW_MESSAGE_SIZE, and _glfwInputError().
Referenced by _glfwCreateContextGLX(), and createNativeWindow().
_glfwCreateCursorX11()
Cursor _glfwCreateCursorX11 (const GLFWimage * image, int xhot, int yhot)
References _glfw, _GLFWlibrary::handle, GLFWimage::height, AuroraFW::None, NULL, GLFWimage::pixels, source, GLFWimage::width, XcursorImageCreate, XcursorImageDestroy, and XcursorImageLoadCursor.
Referenced by _glfwPlatformCreateCursor(), and createHiddenCursor().
_glfwPlatformInit()
int _glfwPlatformInit (void)
References _glfw, _glfwInitJoysticksLinux(), _glfwInitJoysticksNS(), _glfwInitTimerNS(), _glfwInitTimerPOSIX(), _glfwInputError(), _glfwPollMonitorsNS(), _glfwPollMonitorsX11(), changeToResourcesDirectory(), _GLFWinitconfig::chdir, _GLFWlibrary::context, createHelperWindow(), createHiddenCursor(), createKeyTables(), display(), getSystemContentScale(), GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, hasUsableInputMethodStyle(), _GLFWlibrary::hints, _GLFWlibrary::init, initExtensions(), initializeTIS(), _GLFWinitconfig::ns, and NULL.
_glfwPlatformTerminate()
void _glfwPlatformTerminate (void)
References _glfw, _glfw_dlclose, _glfwPushSelectionToManagerX11(), _glfwTerminateEGL(), _glfwTerminateGLX(), _glfwTerminateJoysticksLinux(), _glfwTerminateJoysticksNS(), _glfwTerminateNSGL(), _GLFWlibrary::handle, AuroraFW::None, and NULL.
_glfwPlatformGetVersionString()
const char* _glfwPlatformGetVersionString (void)
References _GLFW_VERSION_NUMBER.