Aurora Framework: AuroraFW::Math::mat4< T > Struct Template Reference
AuroraFW::Math::mat4< T > Struct Template Reference
Public Member Functions
mat4 ()
mat4 (T)
mat4 (const mat4< T > &)
mat4 (T *)
mat4 (const vec4< T > &, const vec4< T > &, const vec4< T > &, const vec4< T > &)
vec4< T > getColumn (uint_t) const
vec3< T > getPos () const
mat4< T > & invert ()
mat4 & multiply (const mat4< T > &)
vec3< T > multiply (const vec3< T > &) const
vec4< T > multiply (const vec4< T > &) const
mat4< T > operator* (const mat4< T > &)
vec3< T > operator* (const vec3< T > &) const
vec3< T > operator* (const vec3< T > &)
vec3< T > operator* (const vec4< T > &) const
vec4< T > operator* (const vec4< T > &)
mat4< T > & operator*= (const mat4< T > &)
void setColumn (uint_t, const vec4< T > &)
void setPos (const vec3< T > &)
std::string toString () const
Static Public Member Functions
static mat4< T > identity ()
static mat4< T > invert (const mat4< T > &)
static mat4< T > lookAt (const vec3< T > &, const vec3< T > &, const vec3< T > &)
static mat4< T > orthographic (T, T, T, T, T, T)
static mat4< T > perspective (T, T, T, T)
static mat4< T > rotation (T, const vec3< T > &)
static mat4< T > scale (const vec3< T > &)
static mat4< T > translate (const vec3< T > &)
static mat4< T > transpose (const mat4< T > &)
Public Attributes
union {
T m [4][4]
vec4< T > r [4]
};
Friends
template<typename t >
std::ostream & operator<< (std::ostream &, const vec3< T > &)
Constructor & Destructor Documentation
mat4() [1/5]
template<typename T > AuroraFW::Math::mat4< T >::mat4 ()
References memset().
mat4() [2/5]
template<typename T > AuroraFW::Math::mat4< T >::mat4 (T diagonal)
References memset().
mat4() [3/5]
template<typename T > AuroraFW::Math::mat4< T >::mat4 (const mat4< T > & mat)
References AuroraFW::Math::mat4< T >::m.
mat4() [4/5]
template<typename T > AuroraFW::Math::mat4< T >::mat4 (T * mat)
References memcpy().
mat4() [5/5]
template<typename T > AuroraFW::Math::mat4< T >::mat4 (const vec4< T > & r0, const vec4< T > & r1, const vec4< T > & r2, const vec4< T > & r3)
Member Function Documentation
multiply() [1/3]
template<typename T > mat4< T > & AuroraFW::Math::mat4< T >::multiply (const mat4< T > & mat)
References AuroraFW::Math::mat4< T >::m, and memcpy().
multiply() [2/3]
template<typename T > vec3< T > AuroraFW::Math::mat4< T >::multiply (const vec3< T > & vec) const
References AuroraFW::Math::vec3< T >::multiply().
multiply() [3/3]
template<typename T > vec4< T > AuroraFW::Math::mat4< T >::multiply (const vec4< T > & vec) const
References AuroraFW::Math::vec4< T >::multiply().
operator*() [1/5]
template<typename T > mat4< T > AuroraFW::Math::mat4< T >::operator* (const mat4< T > & mat)
operator*=()
template<typename T > mat4< T > & AuroraFW::Math::mat4< T >::operator*= (const mat4< T > & mat)
operator*() [2/5]
template<typename T> vec3<T> AuroraFW::Math::mat4< T >::operator* (const vec3< T > &) const
operator*() [3/5]
template<typename T > vec3< T > AuroraFW::Math::mat4< T >::operator* (const vec3< T > & vec)
operator*() [4/5]
template<typename T> vec3<T> AuroraFW::Math::mat4< T >::operator* (const vec4< T > &) const
operator*() [5/5]
template<typename T > vec4< T > AuroraFW::Math::mat4< T >::operator* (const vec4< T > & vec)
invert() [1/2]
template<typename T> mat4<T>& AuroraFW::Math::mat4< T >::invert ()
getColumn()
template<typename T> vec4<T> AuroraFW::Math::mat4< T >::getColumn (uint_t) const
getPos()
template<typename T> vec3<T> AuroraFW::Math::mat4< T >::getPos () const
setColumn()
template<typename T> void AuroraFW::Math::mat4< T >::setColumn (uint_t , const vec4< T > &)
setPos()
template<typename T> void AuroraFW::Math::mat4< T >::setPos (const vec3< T > &)
identity()
template<typename T > mat4< T > AuroraFW::Math::mat4< T >::identity () static
orthographic()
template<typename T > mat4< T > AuroraFW::Math::mat4< T >::orthographic (T left, T right, T bottom, T top, T near_, T far_) static
References AuroraFW::Math::mat4< T >::m.
perspective()
template<typename T> static mat4<T> AuroraFW::Math::mat4< T >::perspective (T , T , T , T) static
lookAt()
template<typename T> static mat4<T> AuroraFW::Math::mat4< T >::lookAt (const vec3< T > & , const vec3< T > & , const vec3< T > &) static
translate()
template<typename T > mat4< T > AuroraFW::Math::mat4< T >::translate (const vec3< T > & vec) static
References AuroraFW::Math::mat4< T >::m, AuroraFW::Math::vec3< T >::x, AuroraFW::Math::vec3< T >::y, and AuroraFW::Math::vec3< T >::z.
rotation()
template<typename T> static mat4<T> AuroraFW::Math::mat4< T >::rotation (T , const vec3< T > &) static
scale()
template<typename T> static mat4<T> AuroraFW::Math::mat4< T >::scale (const vec3< T > &) static
invert() [2/2]
template<typename T> static mat4<T> AuroraFW::Math::mat4< T >::invert (const mat4< T > &) static
transpose()
template<typename T> static mat4<T> AuroraFW::Math::mat4< T >::transpose (const mat4< T > &) static
toString()
template<typename T> std::string AuroraFW::Math::mat4< T >::toString () const
Friends And Related Function Documentation
operator<<
template<typename T> template<typename t > std::ostream& operator<< (std::ostream & stream, const vec3< T > & vector) friend
Member Data Documentation
m
template<typename T> T AuroraFW::Math::mat4< T >::m[4][4]
Referenced by AuroraFW::Math::mat4< T >::mat4(), AuroraFW::Math::mat4< T >::multiply(), AuroraFW::Math::mat4< T >::orthographic(), and AuroraFW::Math::mat4< T >::translate().
r
template<typename T> vec4<T> AuroraFW::Math::mat4< T >::r[4]
Referenced by AuroraFW::Math::vec4< T >::multiply(), and AuroraFW::Math::vec3< T >::multiply().
@13
union { ... }
The documentation for this struct was generated from the following file:
Matrix4x4.h