Aurora Framework: matrix_enc.c File Reference
matrix_enc.c File Reference
Functions
void mix16 (const int32_t *in, uint32_t stride, int32_t *u, int32_t *v, int32_t numSamples, int32_t mixbits, int32_t mixres)
void mix20 (const int32_t *in, uint32_t stride, int32_t *u, int32_t *v, int32_t numSamples, int32_t mixbits, int32_t mixres)
void mix24 (const int32_t *in, uint32_t stride, int32_t *u, int32_t *v, int32_t numSamples, int32_t mixbits, int32_t mixres, uint16_t *shiftUV, int32_t bytesShifted)
void mix32 (const int32_t *in, uint32_t stride, int32_t *u, int32_t *v, int32_t numSamples, int32_t mixbits, int32_t mixres, uint16_t *shiftUV, int32_t bytesShifted)
Function Documentation
mix16()
void mix16 (const int32_t * in, uint32_t stride, int32_t * u, int32_t * v, int32_t numSamples, int32_t mixbits, int32_t mixres)
Referenced by EncodeStereo(), and EncodeStereoFast().
mix20()
void mix20 (const int32_t * in, uint32_t stride, int32_t * u, int32_t * v, int32_t numSamples, int32_t mixbits, int32_t mixres)
Referenced by EncodeStereo(), and EncodeStereoFast().
mix24()
void mix24 (const int32_t * in, uint32_t stride, int32_t * u, int32_t * v, int32_t numSamples, int32_t mixbits, int32_t mixres, uint16_t * shiftUV, int32_t bytesShifted)
Referenced by EncodeStereo(), EncodeStereoEscape(), and EncodeStereoFast().
mix32()
void mix32 (const int32_t * in, uint32_t stride, int32_t * u, int32_t * v, int32_t numSamples, int32_t mixbits, int32_t mixres, uint16_t * shiftUV, int32_t bytesShifted)
Referenced by EncodeStereo(), and EncodeStereoFast().