Aurora Framework: _ImGui.h File Reference
_ImGui.h File Reference
Classes
struct ImDrawDataBuilder
struct ImDrawListSharedData
struct ImGuiColMod
struct ImGuiColumnData
struct ImGuiColumnsSet
struct ImGuiContext
struct ImGuiDrawContext
struct ImGuiGroupData
struct ImGuiItemHoveredDataBackup
struct ImGuiMenuColumns
struct ImGuiNavMoveResult
struct ImGuiNextWindowData
struct ImGuiPopupRef
struct ImGuiSettingsHandler
struct ImGuiStyleMod
struct ImGuiTextEditState
struct ImGuiWindow
struct ImGuiWindowSettings
struct ImNewPlacementDummy
struct ImRect
Namespaces
ImGui
ImGuiStb
Macros
#define IM_NEW(_TYPE) new(ImNewPlacementDummy(), ImGui::MemAlloc(sizeof(_TYPE))) _TYPE
#define IM_NEWLINE "\n"
#define IM_PI 3.14159265358979323846f
#define IM_PLACEMENT_NEW(_PTR) new(ImNewPlacementDummy(), _PTR)
#define STB_TEXTEDIT_CHARTYPE ImWchar
#define STB_TEXTEDIT_GETWIDTH_NEWLINE -1.0f
#define STB_TEXTEDIT_STRING ImGuiTextEditState
Typedefs
typedef int ImGuiButtonFlags
typedef int ImGuiItemFlags
typedef int ImGuiItemStatusFlags
typedef int ImGuiLayoutType
typedef int ImGuiNavDirSourceFlags
typedef int ImGuiNavHighlightFlags
typedef int ImGuiSeparatorFlags
typedef int ImGuiSliderFlags
Enumerations
enum ImGuiAxis { ImGuiAxis_None = -1, ImGuiAxis_X = 0, ImGuiAxis_Y = 1 }
enum ImGuiButtonFlags_ {
ImGuiButtonFlags_Repeat = 1 << 0, ImGuiButtonFlags_PressedOnClickRelease = 1 << 1, ImGuiButtonFlags_PressedOnClick = 1 << 2, ImGuiButtonFlags_PressedOnRelease = 1 << 3,
ImGuiButtonFlags_PressedOnDoubleClick = 1 << 4, ImGuiButtonFlags_FlattenChildren = 1 << 5, ImGuiButtonFlags_AllowItemOverlap = 1 << 6, ImGuiButtonFlags_DontClosePopups = 1 << 7,
ImGuiButtonFlags_Disabled = 1 << 8, ImGuiButtonFlags_AlignTextBaseLine = 1 << 9, ImGuiButtonFlags_NoKeyModifiers = 1 << 10, ImGuiButtonFlags_NoHoldingActiveID = 1 << 11,
ImGuiButtonFlags_PressedOnDragDropHold = 1 << 12, ImGuiButtonFlags_NoNavFocus = 1 << 13
}
enum ImGuiColumnsFlags_ {
ImGuiColumnsFlags_NoBorder = 1 << 0, ImGuiColumnsFlags_NoResize = 1 << 1, ImGuiColumnsFlags_NoPreserveWidths = 1 << 2, ImGuiColumnsFlags_NoForceWithinWindow = 1 << 3,
ImGuiColumnsFlags_GrowParentContentsSize = 1 << 4
}
enum ImGuiDataType { ImGuiDataType_Int, ImGuiDataType_Float, ImGuiDataType_Float2 }
enum ImGuiDir {
ImGuiDir_None = -1, ImGuiDir_Left = 0, ImGuiDir_Right = 1, ImGuiDir_Up = 2,
ImGuiDir_Down = 3, ImGuiDir_Count_
}
enum ImGuiInputReadMode {
ImGuiInputReadMode_Down, ImGuiInputReadMode_Pressed, ImGuiInputReadMode_Released, ImGuiInputReadMode_Repeat,
ImGuiInputReadMode_RepeatSlow, ImGuiInputReadMode_RepeatFast
}
enum ImGuiInputSource {
ImGuiInputSource_None = 0, ImGuiInputSource_Mouse, ImGuiInputSource_Nav, ImGuiInputSource_NavKeyboard,
ImGuiInputSource_NavGamepad, ImGuiInputSource_Count_
}
enum ImGuiItemFlags_ {
ImGuiItemFlags_AllowKeyboardFocus = 1 << 0, ImGuiItemFlags_ButtonRepeat = 1 << 1, ImGuiItemFlags_Disabled = 1 << 2, ImGuiItemFlags_NoNav = 1 << 3,
ImGuiItemFlags_NoNavDefaultFocus = 1 << 4, ImGuiItemFlags_SelectableDontClosePopup = 1 << 5, ImGuiItemFlags_Default_ = ImGuiItemFlags_AllowKeyboardFocus
}
enum ImGuiItemStatusFlags_ { ImGuiItemStatusFlags_HoveredRect = 1 << 0, ImGuiItemStatusFlags_HasDisplayRect = 1 << 1 }
enum ImGuiLayoutType_ { ImGuiLayoutType_Vertical, ImGuiLayoutType_Horizontal }
enum ImGuiNavDirSourceFlags_ { ImGuiNavDirSourceFlags_Keyboard = 1 << 0, ImGuiNavDirSourceFlags_PadDPad = 1 << 1, ImGuiNavDirSourceFlags_PadLStick = 1 << 2 }
enum ImGuiNavForward { ImGuiNavForward_None, ImGuiNavForward_ForwardQueued, ImGuiNavForward_ForwardActive }
enum ImGuiNavHighlightFlags_ { ImGuiNavHighlightFlags_TypeDefault = 1 << 0, ImGuiNavHighlightFlags_TypeThin = 1 << 1, ImGuiNavHighlightFlags_AlwaysDraw = 1 << 2, ImGuiNavHighlightFlags_NoRounding = 1 << 3 }
enum ImGuiPlotType { ImGuiPlotType_Lines, ImGuiPlotType_Histogram }
enum ImGuiSelectableFlagsPrivate_ { ImGuiSelectableFlags_Menu = 1 << 3, ImGuiSelectableFlags_MenuItem = 1 << 4, ImGuiSelectableFlags_Disabled = 1 << 5, ImGuiSelectableFlags_DrawFillAvailWidth = 1 << 6 }
enum ImGuiSeparatorFlags_ { ImGuiSeparatorFlags_Horizontal = 1 << 0, ImGuiSeparatorFlags_Vertical = 1 << 1 }
enum ImGuiSliderFlags_ { ImGuiSliderFlags_Vertical = 1 << 0 }
Functions
IMGUI_API void ImGui::ActivateItem (ImGuiID id)
IMGUI_API bool ImGui::ArrowButton (ImGuiID id, ImGuiDir dir, ImVec2 padding, ImGuiButtonFlags flags=0)
IMGUI_API void ImGui::BeginColumns (const char *str_id, int count, ImGuiColumnsFlags flags=0)
IMGUI_API bool ImGui::BeginDragDropTargetCustom (const ImRect &bb, ImGuiID id)
IMGUI_API bool ImGui::BeginPopupEx (ImGuiID id, ImGuiWindowFlags extra_flags)
IMGUI_API void ImGui::BeginTooltipEx (ImGuiWindowFlags extra_flags, bool override_previous_tooltip=true)
IMGUI_API void ImGui::BringWindowToBack (ImGuiWindow *window)
IMGUI_API void ImGui::BringWindowToFront (ImGuiWindow *window)
IMGUI_API bool ImGui::ButtonBehavior (const ImRect &bb, ImGuiID id, bool *out_hovered, bool *out_held, ImGuiButtonFlags flags=0)
IMGUI_API bool ImGui::ButtonEx (const char *label, const ImVec2 &size_arg=ImVec2(0, 0), ImGuiButtonFlags flags=0)
IMGUI_API ImVec2 ImGui::CalcItemSize (ImVec2 size, float default_x, float default_y)
IMGUI_API int ImGui::CalcTypematicPressedRepeatAmount (float t, float t_prev, float repeat_delay, float repeat_rate)
IMGUI_API float ImGui::CalcWrapWidthForPos (const ImVec2 &pos, float wrap_pos_x)
IMGUI_API void ImGui::ClearActiveID ()
IMGUI_API void ImGui::ClearDragDrop ()
IMGUI_API bool ImGui::CloseButton (ImGuiID id, const ImVec2 &pos, float radius)
IMGUI_API void ImGui::ClosePopup (ImGuiID id)
IMGUI_API void ImGui::ClosePopupsOverWindow (ImGuiWindow *ref_window)
IMGUI_API void ImGui::ColorEditOptionsPopup (const float *col, ImGuiColorEditFlags flags)
IMGUI_API void ImGui::ColorTooltip (const char *text, const float *col, ImGuiColorEditFlags flags)
IMGUI_API bool ImGui::DragBehavior (const ImRect &frame_bb, ImGuiID id, float *v, float v_speed, float v_min, float v_max, int decimal_precision, float power)
IMGUI_API bool ImGui::DragFloatN (const char *label, float *v, int components, float v_speed, float v_min, float v_max, const char *display_format, float power)
IMGUI_API bool ImGui::DragIntN (const char *label, int *v, int components, float v_speed, int v_min, int v_max, const char *display_format)
IMGUI_API void ImGui::EndColumns ()
IMGUI_API const char * ImGui::FindRenderedTextEnd (const char *text, const char *text_end=NULL)
IMGUI_API ImGuiSettingsHandler * ImGui::FindSettingsHandler (const char *type_name)
IMGUI_API ImGuiWindow * ImGui::FindWindowByName (const char *name)
IMGUI_API ImGuiWindowSettings * ImGui::FindWindowSettings (ImGuiID id)
IMGUI_API bool ImGui::FocusableItemRegister (ImGuiWindow *window, ImGuiID id, bool tab_stop=true)
IMGUI_API void ImGui::FocusableItemUnregister (ImGuiWindow *window)
IMGUI_API void ImGui::FocusWindow (ImGuiWindow *window)
IMGUI_API ImGuiID ImGui::GetActiveID ()
ImGuiWindow * ImGui::GetCurrentWindow ()
ImGuiWindow * ImGui::GetCurrentWindowRead ()
IMGUI_API ImGuiID ImGui::GetHoveredID ()
IMGUI_API float ImGui::GetNavInputAmount (ImGuiNavInput n, ImGuiInputReadMode mode)
IMGUI_API ImVec2 ImGui::GetNavInputAmount2d (ImGuiNavDirSourceFlags dir_sources, ImGuiInputReadMode mode, float slow_factor=0.0f, float fast_factor=0.0f)
template<typename T >
void IM_DELETE (T *&p)
static bool ImCharIsSpace (int c)
static int ImClamp (int v, int mn, int mx)
static float ImClamp (float v, float mn, float mx)
static ImVec2 ImClamp (const ImVec2 &f, const ImVec2 &mn, ImVec2 mx)
static float ImDot (const ImVec2 &a, const ImVec2 &b)
IMGUI_API void * ImFileLoadToMemory (const char *filename, const char *file_open_mode, int *out_file_size=NULL, int padding_bytes=0)
IMGUI_API FILE * ImFileOpen (const char *filename, const char *file_open_mode)
static float ImFloor (float f)
static ImVec2 ImFloor (const ImVec2 &v)
IMGUI_API void ImFontAtlasBuildFinish (ImFontAtlas *atlas)
IMGUI_API void ImFontAtlasBuildMultiplyCalcLookupTable (unsigned char out_table[256], float in_multiply_factor)
IMGUI_API void ImFontAtlasBuildMultiplyRectAlpha8 (const unsigned char table[256], unsigned char *pixels, int x, int y, int w, int h, int stride)
IMGUI_API void ImFontAtlasBuildPackCustomRects (ImFontAtlas *atlas, void *spc)
IMGUI_API void ImFontAtlasBuildRegisterDefaultCustomRects (ImFontAtlas *atlas)
IMGUI_API void ImFontAtlasBuildSetupFont (ImFontAtlas *atlas, ImFont *font, ImFontConfig *font_config, float ascent, float descent)
IMGUI_API bool ImFontAtlasBuildWithStbTruetype (ImFontAtlas *atlas)
IMGUI_API int ImFormatString (char *buf, size_t buf_size, const char *fmt,...) IM_FMTARGS(3)
IMGUI_API int ImFormatStringV (char *buf, size_t buf_size, const char *fmt, va_list args) IM_FMTLIST(3)
IMGUI_API ImU32 ImHash (const void *data, int data_size, ImU32 seed=0)
static float ImInvLength (const ImVec2 &lhs, float fail_value)
static bool ImIsPowerOfTwo (int v)
static float ImLengthSqr (const ImVec2 &lhs)
static float ImLengthSqr (const ImVec4 &lhs)
static int ImLerp (int a, int b, float t)
static float ImLerp (float a, float b, float t)
static ImVec2 ImLerp (const ImVec2 &a, const ImVec2 &b, float t)
static ImVec2 ImLerp (const ImVec2 &a, const ImVec2 &b, const ImVec2 &t)
static ImVec4 ImLerp (const ImVec4 &a, const ImVec4 &b, float t)
static float ImLinearSweep (float current, float target, float speed)
IMGUI_API ImVec2 ImLineClosestPoint (const ImVec2 &a, const ImVec2 &b, const ImVec2 &p)
static int ImMax (int lhs, int rhs)
static float ImMax (float lhs, float rhs)
static ImVec2 ImMax (const ImVec2 &lhs, const ImVec2 &rhs)
static int ImMin (int lhs, int rhs)
static float ImMin (float lhs, float rhs)
static ImVec2 ImMin (const ImVec2 &lhs, const ImVec2 &rhs)
static ImVec2 ImMul (const ImVec2 &lhs, const ImVec2 &rhs)
static ImVec2 ImRotate (const ImVec2 &v, float cos_a, float sin_a)
static float ImSaturate (float f)
IMGUI_API const ImWchar * ImStrbolW (const ImWchar *buf_mid_line, const ImWchar *buf_begin)
IMGUI_API char * ImStrchrRange (const char *str_begin, const char *str_end, char c)
IMGUI_API char * ImStrdup (const char *str)
IMGUI_API int ImStricmp (const char *str1, const char *str2)
IMGUI_API const char * ImStristr (const char *haystack, const char *haystack_end, const char *needle, const char *needle_end)
IMGUI_API int ImStrlenW (const ImWchar *str)
IMGUI_API void ImStrncpy (char *dst, const char *src, size_t count)
IMGUI_API int ImStrnicmp (const char *str1, const char *str2, size_t count)
static void ImSwap (int &a, int &b)
static void ImSwap (float &a, float &b)
IMGUI_API int ImTextCharFromUtf8 (unsigned int *out_char, const char *in_text, const char *in_text_end)
IMGUI_API int ImTextCountCharsFromUtf8 (const char *in_text, const char *in_text_end)
IMGUI_API int ImTextCountUtf8BytesFromStr (const ImWchar *in_text, const ImWchar *in_text_end)
IMGUI_API int ImTextStrFromUtf8 (ImWchar *buf, int buf_size, const char *in_text, const char *in_text_end, const char **in_remaining=NULL)
IMGUI_API int ImTextStrToUtf8 (char *buf, int buf_size, const ImWchar *in_text, const ImWchar *in_text_end)
IMGUI_API void ImTriangleBarycentricCoords (const ImVec2 &a, const ImVec2 &b, const ImVec2 &c, const ImVec2 &p, float &out_u, float &out_v, float &out_w)
IMGUI_API ImVec2 ImTriangleClosestPoint (const ImVec2 &a, const ImVec2 &b, const ImVec2 &c, const ImVec2 &p)
IMGUI_API bool ImTriangleContainsPoint (const ImVec2 &a, const ImVec2 &b, const ImVec2 &c, const ImVec2 &p)
static int ImUpperPowerOfTwo (int v)
IMGUI_API void ImGui::Initialize (ImGuiContext *context)
IMGUI_API bool ImGui::InputFloatN (const char *label, float *v, int components, int decimal_precision, ImGuiInputTextFlags extra_flags)
IMGUI_API bool ImGui::InputIntN (const char *label, int *v, int components, ImGuiInputTextFlags extra_flags)
IMGUI_API bool ImGui::InputScalarAsWidgetReplacement (const ImRect &aabb, const char *label, ImGuiDataType data_type, void *data_ptr, ImGuiID id, int decimal_precision)
IMGUI_API bool ImGui::InputScalarEx (const char *label, ImGuiDataType data_type, void *data_ptr, void *step_ptr, void *step_fast_ptr, const char *scalar_format, ImGuiInputTextFlags extra_flags)
IMGUI_API bool ImGui::InputTextEx (const char *label, char *buf, int buf_size, const ImVec2 &size_arg, ImGuiInputTextFlags flags, ImGuiTextEditCallback callback=NULL, void *user_data=NULL)
IMGUI_API bool ImGui::IsClippedEx (const ImRect &bb, ImGuiID id, bool clip_even_when_logged)
IMGUI_API bool ImGui::IsDragDropPayloadBeingAccepted ()
IMGUI_API bool ImGui::IsPopupOpen (ImGuiID id)
IMGUI_API bool ImGui::IsWindowChildOf (ImGuiWindow *window, ImGuiWindow *potential_parent)
IMGUI_API bool ImGui::IsWindowNavFocusable (ImGuiWindow *window)
IMGUI_API bool ImGui::ItemAdd (const ImRect &bb, ImGuiID id, const ImRect *nav_bb=NULL)
IMGUI_API bool ImGui::ItemHoverable (const ImRect &bb, ImGuiID id)
IMGUI_API void ImGui::ItemSize (const ImVec2 &size, float text_offset_y=0.0f)
IMGUI_API void ImGui::ItemSize (const ImRect &bb, float text_offset_y=0.0f)
IMGUI_API void ImGui::KeepAliveID (ImGuiID id)
IMGUI_API void ImGui::MarkIniSettingsDirty ()
IMGUI_API void ImGui::NavInitWindow (ImGuiWindow *window, bool force_reinit)
IMGUI_API void ImGui::NavMoveRequestCancel ()
IMGUI_API void ImGui::OpenPopupEx (ImGuiID id)
void operator delete (void *, ImNewPlacementDummy, void *)
void * operator new (size_t, ImNewPlacementDummy, void *ptr)
IMGUI_API int ImGui::ParseFormatPrecision (const char *fmt, int default_value)
IMGUI_API void ImGui::PlotEx (ImGuiPlotType plot_type, const char *label, float(*values_getter)(void *data, int idx), void *data, int values_count, int values_offset, const char *overlay_text, float scale_min, float scale_max, ImVec2 graph_size)
IMGUI_API void ImGui::PopItemFlag ()
IMGUI_API void ImGui::PushColumnClipRect (int column_index=-1)
IMGUI_API void ImGui::PushItemFlag (ImGuiItemFlags option, bool enabled)
IMGUI_API void ImGui::PushMultiItemsWidths (int components, float width_full=0.0f)
IMGUI_API void ImGui::RenderBullet (ImVec2 pos)
IMGUI_API void ImGui::RenderCheckMark (ImVec2 pos, ImU32 col, float sz)
IMGUI_API void ImGui::RenderColorRectWithAlphaCheckerboard (ImVec2 p_min, ImVec2 p_max, ImU32 fill_col, float grid_step, ImVec2 grid_off, float rounding=0.0f, int rounding_corners_flags=~0)
IMGUI_API void ImGui::RenderFrame (ImVec2 p_min, ImVec2 p_max, ImU32 fill_col, bool border=true, float rounding=0.0f)
IMGUI_API void ImGui::RenderFrameBorder (ImVec2 p_min, ImVec2 p_max, float rounding=0.0f)
IMGUI_API void ImGui::RenderNavHighlight (const ImRect &bb, ImGuiID id, ImGuiNavHighlightFlags flags=ImGuiNavHighlightFlags_TypeDefault)
IMGUI_API void ImGui::RenderRectFilledRangeH (ImDrawList *draw_list, const ImRect &rect, ImU32 col, float x_start_norm, float x_end_norm, float rounding)
IMGUI_API void ImGui::RenderText (ImVec2 pos, const char *text, const char *text_end=NULL, bool hide_text_after_hash=true)
IMGUI_API void ImGui::RenderTextClipped (const ImVec2 &pos_min, const ImVec2 &pos_max, const char *text, const char *text_end, const ImVec2 *text_size_if_known, const ImVec2 &align=ImVec2(0, 0), const ImRect *clip_rect=NULL)
IMGUI_API void ImGui::RenderTextWrapped (ImVec2 pos, const char *text, const char *text_end, float wrap_width)
IMGUI_API void ImGui::RenderTriangle (ImVec2 pos, ImGuiDir dir, float scale=1.0f)
IMGUI_API float ImGui::RoundScalar (float value, int decimal_precision)
IMGUI_API void ImGui::Scrollbar (ImGuiLayoutType direction)
IMGUI_API void ImGui::SetActiveID (ImGuiID id, ImGuiWindow *window)
IMGUI_API void ImGui::SetCurrentFont (ImFont *font)
IMGUI_API void ImGui::SetFocusID (ImGuiID id, ImGuiWindow *window)
IMGUI_API void ImGui::SetHoveredID (ImGuiID id)
IMGUI_API void ImGui::ShadeVertsLinearAlphaGradientForLeftToRightText (ImDrawVert *vert_start, ImDrawVert *vert_end, float gradient_p0_x, float gradient_p1_x)
IMGUI_API void ImGui::ShadeVertsLinearColorGradientKeepAlpha (ImDrawVert *vert_start, ImDrawVert *vert_end, ImVec2 gradient_p0, ImVec2 gradient_p1, ImU32 col0, ImU32 col1)
IMGUI_API void ImGui::ShadeVertsLinearUV (ImDrawVert *vert_start, ImDrawVert *vert_end, const ImVec2 &a, const ImVec2 &b, const ImVec2 &uv_a, const ImVec2 &uv_b, bool clamp)
IMGUI_API void ImGui::Shutdown (ImGuiContext *context)
IMGUI_API bool ImGui::SliderBehavior (const ImRect &frame_bb, ImGuiID id, float *v, float v_min, float v_max, float power, int decimal_precision, ImGuiSliderFlags flags=0)
IMGUI_API bool ImGui::SliderFloatN (const char *label, float *v, int components, float v_min, float v_max, const char *display_format, float power)
IMGUI_API bool ImGui::SliderIntN (const char *label, int *v, int components, int v_min, int v_max, const char *display_format)
IMGUI_API bool ImGui::SplitterBehavior (ImGuiID id, const ImRect &bb, ImGuiAxis axis, float *size1, float *size2, float min_size1, float min_size2, float hover_extend=0.0f)
IMGUI_API bool ImGui::TreeNodeBehavior (ImGuiID id, ImGuiTreeNodeFlags flags, const char *label, const char *label_end=NULL)
IMGUI_API bool ImGui::TreeNodeBehaviorIsOpen (ImGuiID id, ImGuiTreeNodeFlags flags=0)
IMGUI_API void ImGui::TreePushRawID (ImGuiID id)
IMGUI_API void ImGui::VerticalSeparator ()
Variables
IMGUI_API ImGuiContext * GImGui
Macro Definition Documentation
STB_TEXTEDIT_STRING
#define STB_TEXTEDIT_STRING ImGuiTextEditState
STB_TEXTEDIT_CHARTYPE
#define STB_TEXTEDIT_CHARTYPE ImWchar
STB_TEXTEDIT_GETWIDTH_NEWLINE
#define STB_TEXTEDIT_GETWIDTH_NEWLINE -1.0f
Referenced by ImGuiStb::STB_TEXTEDIT_GETWIDTH().
IM_PI
#define IM_PI 3.14159265358979323846f
Referenced by ImDrawList::AddCircle(), ImDrawList::AddCircleFilled(), ImGui::ColorPicker4(), ImAcos01(), ImDrawListSharedData::ImDrawListSharedData(), ImGui::RenderRectFilledRangeH(), and ImGui::SliderAngle().
IM_NEWLINE
#define IM_NEWLINE "\n"
Referenced by ImGui::LogFinish(), LogRenderedText(), and ImGui::Separator().
IM_PLACEMENT_NEW
#define IM_PLACEMENT_NEW (_PTR) new(ImNewPlacementDummy(), _PTR)
Referenced by ImDrawList::ChannelsSplit().
IM_NEW
#define IM_NEW (_TYPE) new(ImNewPlacementDummy(), ImGui::MemAlloc(sizeof(_TYPE))) _TYPE
Referenced by ImFontAtlas::AddFont(), ImGui::CreateContext(), CreateNewWindow(), ImGuiContext::ImGuiContext(), ImGuiWindow::ImGuiWindow(), and ImGui::Initialize().
Typedef Documentation
ImGuiLayoutType
typedef int ImGuiLayoutType
ImGuiButtonFlags
typedef int ImGuiButtonFlags
ImGuiItemFlags
typedef int ImGuiItemFlags
ImGuiItemStatusFlags
typedef int ImGuiItemStatusFlags
ImGuiNavHighlightFlags
typedef int ImGuiNavHighlightFlags
ImGuiNavDirSourceFlags
typedef int ImGuiNavDirSourceFlags
ImGuiSeparatorFlags
typedef int ImGuiSeparatorFlags
ImGuiSliderFlags
typedef int ImGuiSliderFlags
Enumeration Type Documentation
ImGuiButtonFlags_
enum ImGuiButtonFlags_
Enumerator
ImGuiButtonFlags_Repeat
ImGuiButtonFlags_PressedOnClickRelease
ImGuiButtonFlags_PressedOnClick
ImGuiButtonFlags_PressedOnRelease
ImGuiButtonFlags_PressedOnDoubleClick
ImGuiButtonFlags_FlattenChildren
ImGuiButtonFlags_AllowItemOverlap
ImGuiButtonFlags_DontClosePopups
ImGuiButtonFlags_Disabled
ImGuiButtonFlags_AlignTextBaseLine
ImGuiButtonFlags_NoKeyModifiers
ImGuiButtonFlags_NoHoldingActiveID
ImGuiButtonFlags_PressedOnDragDropHold
ImGuiButtonFlags_NoNavFocus
ImGuiSliderFlags_
enum ImGuiSliderFlags_
Enumerator
ImGuiSliderFlags_Vertical
ImGuiColumnsFlags_
enum ImGuiColumnsFlags_
Enumerator
ImGuiColumnsFlags_NoBorder
ImGuiColumnsFlags_NoResize
ImGuiColumnsFlags_NoPreserveWidths
ImGuiColumnsFlags_NoForceWithinWindow
ImGuiColumnsFlags_GrowParentContentsSize
ImGuiSelectableFlagsPrivate_
enum ImGuiSelectableFlagsPrivate_
Enumerator
ImGuiSelectableFlags_Menu
ImGuiSelectableFlags_MenuItem
ImGuiSelectableFlags_Disabled
ImGuiSelectableFlags_DrawFillAvailWidth
ImGuiSeparatorFlags_
enum ImGuiSeparatorFlags_
Enumerator
ImGuiSeparatorFlags_Horizontal
ImGuiSeparatorFlags_Vertical
ImGuiItemStatusFlags_
enum ImGuiItemStatusFlags_
Enumerator
ImGuiItemStatusFlags_HoveredRect
ImGuiItemStatusFlags_HasDisplayRect
ImGuiLayoutType_
enum ImGuiLayoutType_
Enumerator
ImGuiLayoutType_Vertical
ImGuiLayoutType_Horizontal
ImGuiAxis
enum ImGuiAxis
Enumerator
ImGuiAxis_None
ImGuiAxis_X
ImGuiAxis_Y
ImGuiPlotType
enum ImGuiPlotType
Enumerator
ImGuiPlotType_Lines
ImGuiPlotType_Histogram
ImGuiDataType
enum ImGuiDataType
Enumerator
ImGuiDataType_Int
ImGuiDataType_Float
ImGuiDataType_Float2
ImGuiDir
enum ImGuiDir
Enumerator
ImGuiDir_None
ImGuiDir_Left
ImGuiDir_Right
ImGuiDir_Up
ImGuiDir_Down
ImGuiDir_Count_
ImGuiInputSource
enum ImGuiInputSource
Enumerator
ImGuiInputSource_None
ImGuiInputSource_Mouse
ImGuiInputSource_Nav
ImGuiInputSource_NavKeyboard
ImGuiInputSource_NavGamepad
ImGuiInputSource_Count_
ImGuiInputReadMode
enum ImGuiInputReadMode
Enumerator
ImGuiInputReadMode_Down
ImGuiInputReadMode_Pressed
ImGuiInputReadMode_Released
ImGuiInputReadMode_Repeat
ImGuiInputReadMode_RepeatSlow
ImGuiInputReadMode_RepeatFast
ImGuiNavHighlightFlags_
enum ImGuiNavHighlightFlags_
Enumerator
ImGuiNavHighlightFlags_TypeDefault
ImGuiNavHighlightFlags_TypeThin
ImGuiNavHighlightFlags_AlwaysDraw
ImGuiNavHighlightFlags_NoRounding
ImGuiNavDirSourceFlags_
enum ImGuiNavDirSourceFlags_
Enumerator
ImGuiNavDirSourceFlags_Keyboard
ImGuiNavDirSourceFlags_PadDPad
ImGuiNavDirSourceFlags_PadLStick
ImGuiNavForward
enum ImGuiNavForward
Enumerator
ImGuiNavForward_None
ImGuiNavForward_ForwardQueued
ImGuiNavForward_ForwardActive
ImGuiItemFlags_
enum ImGuiItemFlags_
Enumerator
ImGuiItemFlags_AllowKeyboardFocus
ImGuiItemFlags_ButtonRepeat
ImGuiItemFlags_Disabled
ImGuiItemFlags_NoNav
ImGuiItemFlags_NoNavDefaultFocus
ImGuiItemFlags_SelectableDontClosePopup
ImGuiItemFlags_Default_
Function Documentation
ImTextStrToUtf8()
IMGUI_API int ImTextStrToUtf8 (char * buf, int buf_size, const ImWchar * in_text, const ImWchar * in_text_end)
References ImTextCharToUtf8().
Referenced by ImGui::InputTextEx().
ImTextCharFromUtf8()
IMGUI_API int ImTextCharFromUtf8 (unsigned int * out_char, const char * in_text, const char * in_text_end)
Referenced by ImFontAtlas::GlyphRangesBuilder::AddText(), ImFont::CalcTextSizeA(), ImFont::CalcWordWrapPositionA(), ImTextCountCharsFromUtf8(), ImTextStrFromUtf8(), ImGui::InputTextEx(), and ImFont::RenderText().
ImTextStrFromUtf8()
IMGUI_API int ImTextStrFromUtf8 (ImWchar * buf, int buf_size, const char * in_text, const char * in_text_end, const char ** in_remaining = NULL)
References ImTextCharFromUtf8().
Referenced by ImGuiIO::AddInputCharactersUTF8(), ImFileOpen(), and ImGui::InputTextEx().
ImTextCountCharsFromUtf8()
IMGUI_API int ImTextCountCharsFromUtf8 (const char * in_text, const char * in_text_end)
References ImTextCharFromUtf8().
Referenced by ImFileOpen(), and ImGui::InputTextEx().
ImTextCountUtf8BytesFromStr()
IMGUI_API int ImTextCountUtf8BytesFromStr (const ImWchar * in_text, const ImWchar * in_text_end)
References ImTextCountUtf8BytesFromChar().
Referenced by ImGui::InputTextEx(), ImGuiStb::STB_TEXTEDIT_DELETECHARS(), and ImGuiStb::STB_TEXTEDIT_INSERTCHARS().
ImHash()
IMGUI_API ImU32 ImHash (const void * data, int data_size, ImU32 seed = 0)
Referenced by AddWindowSettings(), ImGui::BeginDragDropSource(), ImGui::FindSettingsHandler(), ImGui::FindWindowByName(), ImGuiWindow::GetID(), ImGuiWindow::GetIDFromRectangle(), ImGuiWindow::GetIDNoKeepAlive(), ImGuiWindow::ImGuiWindow(), ImGui::Initialize(), and SettingsHandlerWindow_ReadOpen().
ImFileLoadToMemory()
IMGUI_API void* ImFileLoadToMemory (const char * filename, const char * file_open_mode, int * out_file_size = NULL, int padding_bytes = 0)
References IM_ASSERT, ImFileOpen(), ImGui::MemAlloc(), ImGui::MemFree(), memset(), and NULL.
Referenced by ImFontAtlas::AddFontFromFileTTF(), and LoadIniSettingsFromDisk().
ImFileOpen()
IMGUI_API FILE* ImFileOpen (const char * filename, const char * file_open_mode)
References ImTextCountCharsFromUtf8(), ImTextStrFromUtf8(), mode(), NULL, and ImVector< T >::resize().
Referenced by ImFileLoadToMemory(), ImGui::LogToFile(), and SaveIniSettingsToDisk().
ImCharIsSpace()
static bool ImCharIsSpace (int c) inline static
Referenced by ImFont::CalcTextSizeA(), ImFont::CalcWordWrapPositionA(), ImGui::ColorEdit4(), DataTypeApplyOpFromText(), InputTextFilterCharacter(), ImGuiStb::is_separator(), and ImFont::RenderText().
ImIsPowerOfTwo()
static bool ImIsPowerOfTwo (int v) inline static
Referenced by ImGui::BeginCombo(), ImGui::ColorPicker4(), ImGui::Separator(), and ImGui::SetColorEditOptions().
ImUpperPowerOfTwo()
static int ImUpperPowerOfTwo (int v) inline static
Referenced by ImFontAtlasBuildWithStbTruetype().
ImLineClosestPoint()
IMGUI_API ImVec2 ImLineClosestPoint (const ImVec2 & a, const ImVec2 & b, const ImVec2 & p)
References a, ImVec2::x, and ImVec2::y.
Referenced by ImTriangleClosestPoint().
ImTriangleContainsPoint()
IMGUI_API bool ImTriangleContainsPoint (const ImVec2 & a, const ImVec2 & b, const ImVec2 & c, const ImVec2 & p)
References a, ImVec2::x, and ImVec2::y.
Referenced by ImGui::BeginMenu(), and ImGui::ColorPicker4().
ImTriangleClosestPoint()
IMGUI_API ImVec2 ImTriangleClosestPoint (const ImVec2 & a, const ImVec2 & b, const ImVec2 & c, const ImVec2 & p)
References a, ImLengthSqr(), ImLineClosestPoint(), and ImMin().
Referenced by ImGui::ColorPicker4().
ImTriangleBarycentricCoords()
IMGUI_API void ImTriangleBarycentricCoords (const ImVec2 & a, const ImVec2 & b, const ImVec2 & c, const ImVec2 & p, float & out_u, float & out_v, float & out_w)
References a, ImVec2::x, and ImVec2::y.
Referenced by ImGui::ColorPicker4().
ImStricmp()
IMGUI_API int ImStricmp (const char * str1, const char * str2)
ImStrnicmp()
IMGUI_API int ImStrnicmp (const char * str1, const char * str2, size_t count)
ImStrncpy()
IMGUI_API void ImStrncpy (char * dst, const char * src, size_t count)
Referenced by ImGuiTextFilter::ImGuiTextFilter(), ImGui::InputTextEx(), and ImGui::SetDragDropPayload().
ImStrdup()
IMGUI_API char* ImStrdup (const char * str)
References ImGui::MemAlloc(), and memcpy().
Referenced by AddWindowSettings(), ImGuiWindow::ImGuiWindow(), and LoadIniSettingsFromMemory().
ImStrchrRange()
IMGUI_API char* ImStrchrRange (const char * str_begin, const char * str_end, char c)
References NULL.
Referenced by LoadIniSettingsFromMemory().
ImStrlenW()
IMGUI_API int ImStrlenW (const ImWchar * str)
Referenced by ImGuiIO::AddInputCharacter().
ImStrbolW()
IMGUI_API const ImWchar* ImStrbolW (const ImWchar * buf_mid_line, const ImWchar * buf_begin)
Referenced by ImGui::InputTextEx().
ImStristr()
IMGUI_API const char* ImStristr (const char * haystack, const char * haystack_end, const char * needle, const char * needle_end)
References a, and NULL.
Referenced by ImGuiTextFilter::PassFilter().
ImFormatString()
IMGUI_API int ImFormatString (char * buf, size_t buf_size, const char * fmt, ...)
References NULL.
Referenced by BeginChildEx(), ImGui::BeginCombo(), ImGui::BeginPopupEx(), ImGui::BeginTooltipEx(), ImGui::ColorEdit4(), ImGui::ColorEditOptionsPopup(), DataTypeFormatString(), ImGui::DragFloat(), ImGui::InputFloat(), NavScoreItem(), ImGui::NavUpdate(), ImGui::ProgressBar(), ImGui::ShowMetricsWindow(), ImGui::SliderFloat(), ImGui::Value(), and ImGui::VSliderFloat().
ImFormatStringV()
IMGUI_API int ImFormatStringV (char * buf, size_t buf_size, const char * fmt, va_list args)
References NULL.
Referenced by ImGuiTextBuffer::appendfv(), ImGui::BulletTextV(), ImGui::LabelTextV(), ImGui::TextV(), and ImGui::TreeNodeExV().
ImMin() [1/3]
static int ImMin (int lhs, int rhs) inline static
Referenced by ImDrawList::AddText(), ImGui::Begin(), ImGui::BeginColumns(), ImGui::BeginMenu(), ImGui::Bullet(), ImGui::BulletTextV(), CalcNextScrollFromScrollTargetAndClamp(), ImGui::Checkbox(), ImRect::ClipWith(), ImGui::CollapsingHeader(), ImGui::ColorButton(), ImGuiTextEditState::CursorClamp(), ImGui::DragFloatRange2(), ImGui::DragIntRange2(), ImGui::EndColumns(), FindBestWindowPosForPopup(), GetDraggedColumnOffset(), ImGui::ImageButton(), ImLinearSweep(), ImTriangleClosestPoint(), ImGui::InputTextEx(), ImGui::ListBoxHeader(), NavCalcPreferredMousePos(), ImGui::NavUpdate(), ImGui::NavUpdateWindowing(), ImGui::NewFrame(), ImDrawList::PathRect(), ImGui::PlotEx(), ImGui::RadioButton(), ImGui::RenderColorRectWithAlphaCheckerboard(), ImGui::RenderRectFilledRangeH(), ImGui::Scrollbar(), ImGui::SetColumnOffset(), ImGui::ShadeVertsLinearUV(), ImGui::SliderBehavior(), SliderBehaviorCalcRatioFromValue(), ImGui::TreeNodeBehavior(), and ImGui::UpdateManualResize().
ImMax() [1/3]
static int ImMax (int lhs, int rhs) inline static
Referenced by ImDrawList::AddText(), ImGui::AlignTextToFramePadding(), ImGui::Begin(), BeginChildEx(), ImGui::BeginCombo(), ImGui::BeginMenu(), ImGui::BeginMenuBar(), ImFont::BuildLookupTable(), ImGui::Bullet(), ImGui::BulletTextV(), ImGuiMenuColumns::CalcExtraSpace(), ImGui::CalcItemSize(), ImGui::CalcItemWidth(), CalcNextScrollFromScrollTargetAndClamp(), CalcSizeAfterConstraint(), CalcSizeAutoFit(), ImFont::CalcTextSizeA(), ImGui::CalcWrapWidthForPos(), ImGui::Checkbox(), ImRect::ClipWith(), ImGui::CloseButton(), ImGui::ColorEdit4(), ImGui::ColorPicker4(), ColorPickerOptionsPopup(), ImGuiMenuColumns::DeclColumns(), ImGui::DragBehavior(), ImGui::DragFloatRange2(), ImGui::DragIntRange2(), ImGui::EndChild(), ImGui::EndColumns(), ImGui::EndGroup(), FindBestWindowPosForPopup(), GetDraggedColumnOffset(), GetScrollMaxX(), GetScrollMaxY(), ImFontAtlasBuildPackCustomRects(), ImFontAtlasBuildWithStbTruetype(), ImLinearSweep(), ImGui::InputScalarEx(), InputTextCalcTextSizeW(), ImGui::InputTextEx(), ImGui::ItemSize(), ImGui::ListBoxHeader(), ImGui::MenuItem(), NavProcessMoveRequestWrapAround(), ImGui::NavUpdateWindowing(), ImGui::NewFrame(), ImGui::NextColumn(), ImGui::PlotEx(), ImDrawList::PushClipRect(), ImGui::PushMultiItemsWidths(), ImGui::RadioButton(), ImGui::RenderCheckMark(), ImGui::RenderRectFilledRangeH(), ImGui::RenderTextClipped(), ImGui::Scrollbar(), ImGui::Selectable(), ImGui::SetColumnOffset(), ImGui::SetCursorPos(), ImGui::SetCursorPosX(), ImGui::SetCursorPosY(), ImGui::SetCursorScreenPos(), SettingsHandlerWindow_ReadLine(), ImGui::ShadeVertsLinearUV(), ImGui::SliderBehavior(), SliderBehaviorCalcRatioFromValue(), ImGui::TextUnformatted(), ImGui::TreeNodeBehavior(), and ImGui::UpdateManualResize().
ImMin() [2/3]
static float ImMin (float lhs, float rhs) inline static
ImMax() [2/3]
static float ImMax (float lhs, float rhs) inline static
ImMin() [3/3]
static ImVec2 ImMin (const ImVec2 & lhs, const ImVec2 & rhs) inline static
References ImVec2::x, and ImVec2::y.
ImMax() [3/3]
static ImVec2 ImMax (const ImVec2 & lhs, const ImVec2 & rhs) inline static
References ImVec2::x, and ImVec2::y.
ImClamp() [1/3]
static int ImClamp (int v, int mn, int mx) inline static
Referenced by ImGui::BeginMenu(), ImGui::CalcListClipping(), CalcSizeAfterConstraint(), CalcSizeAutoFit(), ImRect::ClipWithFull(), ImGui::ColorEdit4(), ImGui::ColorPicker4(), ImGui::DragBehavior(), FindBestWindowPosForPopup(), ImGui::ImageButton(), ImClamp(), NavCalcPreferredMousePos(), NavScoreItem(), ImGui::NewFrame(), ImGui::PlotEx(), ImGui::ProgressBar(), ImGui::RenderColorRectWithAlphaCheckerboard(), ImGui::RenderRectFilledRangeH(), ImGui::Scrollbar(), ImGui::ShadeVertsLinearAlphaGradientForLeftToRightText(), ImGui::ShadeVertsLinearColorGradientKeepAlpha(), ImGui::ShadeVertsLinearUV(), ImGui::SliderBehavior(), and SliderBehaviorCalcRatioFromValue().
ImClamp() [2/3]
static float ImClamp (float v, float mn, float mx) inline static
ImClamp() [3/3]
static ImVec2 ImClamp (const ImVec2 & f, const ImVec2 & mn, ImVec2 mx) inline static
References ImClamp(), ImVec2::x, and ImVec2::y.
ImSaturate()
static float ImSaturate (float f) inline static
Referenced by ImGui::ColorPicker4(), ImGui::NavUpdateWindowing(), ImGui::PlotEx(), ImGui::ProgressBar(), ImGui::Scrollbar(), and ImGui::SliderBehavior().
ImSwap() [1/2]
static void ImSwap (int & a, int & b) inline static
References a.
Referenced by ImGui::ColorConvertRGBtoHSV(), ImRect::FixInverted(), and ImGui::RenderRectFilledRangeH().
ImSwap() [2/2]
static void ImSwap (float & a, float & b) inline static
References a.
ImLerp() [1/5]
static int ImLerp (int a, int b, float t) inline static
References a.
Referenced by ImGui::Begin(), CalcResizePosSizeFromAnyCorner(), ImGui::ColorPicker4(), ImGui::GetColumnOffset(), ImAlphaBlendColor(), NavScoreItem(), ImGui::PlotEx(), ImGui::ProgressBar(), ImGui::RenderRectFilledRangeH(), ImGui::Scrollbar(), ImGui::ShadeVertsLinearColorGradientKeepAlpha(), ImGui::SliderBehavior(), and ImGui::UpdateManualResize().
ImLerp() [2/5]
static float ImLerp (float a, float b, float t) inline static
References a.
ImLerp() [3/5]
static ImVec2 ImLerp (const ImVec2 & a, const ImVec2 & b, float t) inline static
References a, ImVec2::x, and ImVec2::y.
ImLerp() [4/5]
static ImVec2 ImLerp (const ImVec2 & a, const ImVec2 & b, const ImVec2 & t) inline static
References a, ImVec2::x, and ImVec2::y.
ImLerp() [5/5]
static ImVec4 ImLerp (const ImVec4 & a, const ImVec4 & b, float t) inline static
References a, ImVec4::w, ImVec4::x, ImVec4::y, and ImVec4::z.
ImLengthSqr() [1/2]
static float ImLengthSqr (const ImVec2 & lhs) inline static
References ImVec2::x, and ImVec2::y.
Referenced by ImGui::Begin(), ImGui::ColorPicker4(), CreateNewWindow(), ImGui::EndFrame(), ImTriangleClosestPoint(), ImGui::NewFrame(), and ImGui::ShadeVertsLinearColorGradientKeepAlpha().
ImLengthSqr() [2/2]
static float ImLengthSqr (const ImVec4 & lhs) inline static
References ImVec4::w, ImVec4::x, ImVec4::y, and ImVec4::z.
ImInvLength()
static float ImInvLength (const ImVec2 & lhs, float fail_value) inline static
References ImVec2::x, and ImVec2::y.
Referenced by ImDrawList::AddConvexPolyFilled(), and ImDrawList::AddPolyline().
ImFloor() [1/2]
static float ImFloor (float f) inline static
Referenced by ImGui::Begin(), BeginChildEx(), ImGui::BeginColumns(), ImGui::BeginMenuBar(), CreateNewWindow(), NavCalcPreferredMousePos(), ImGui::NavUpdate(), ImGui::NavUpdateWindowing(), ImGuiStyle::ScaleAllSizes(), SetWindowPos(), and ImGui::UpdateManualResize().
ImFloor() [2/2]
static ImVec2 ImFloor (const ImVec2 & v) inline static
References ImVec2::x, and ImVec2::y.
ImDot()
static float ImDot (const ImVec2 & a, const ImVec2 & b) inline static
References a, ImVec2::x, and ImVec2::y.
Referenced by ImGui::ShadeVertsLinearColorGradientKeepAlpha().
ImRotate()
static ImVec2 ImRotate (const ImVec2 & v, float cos_a, float sin_a) inline static
References ImVec2::x, and ImVec2::y.
Referenced by ImGui::ColorPicker4().
ImLinearSweep()
static float ImLinearSweep (float current, float target, float speed) inline static
References ImMax(), and ImMin().
ImMul()
static ImVec2 ImMul (const ImVec2 & lhs, const ImVec2 & rhs) inline static
References ImVec2::x, and ImVec2::y.
Referenced by ImGui::ShadeVertsLinearUV().
operator new()
void* operator new (size_t , ImNewPlacementDummy , void * ptr) inline
operator delete()
void operator delete (void * , ImNewPlacementDummy , void *) inline
IM_DELETE()
template<typename T > void IM_DELETE (T *& p)
References ImGui::MemFree(), and NULL.
Referenced by ImFontAtlas::ClearFonts(), ImGui::DestroyContext(), ImGui::Shutdown(), and ImGuiWindow::~ImGuiWindow().
ImFontAtlasBuildWithStbTruetype()
IMGUI_API bool ImFontAtlasBuildWithStbTruetype (ImFontAtlas * atlas)
References ImFont::AddGlyph(), ImFont::Ascent, stbtt_pack_range::chardata_for_range, ImFontAtlas::ClearTexData(), ImFontAtlas::ConfigData, ImFont::ContainerAtlas, ImFontConfig::DstFont, ImFont::FindGlyph(), stbtt_pack_range::first_unicode_codepoint_in_range, ImFontAtlas::Flags, stbtt_pack_range::font_size, ImFontConfig::FontData, ImFontConfig::FontNo, ImFontAtlas::GetGlyphRangesDefault(), ImFontConfig::GlyphOffset, ImFontConfig::GlyphRanges, stbtt_pack_context::height, IM_ASSERT, ImFontAtlasBuildFinish(), ImFontAtlasBuildMultiplyCalcLookupTable(), ImFontAtlasBuildMultiplyRectAlpha8(), ImFontAtlasBuildPackCustomRects(), ImFontAtlasBuildRegisterDefaultCustomRects(), ImFontAtlasBuildSetupFont(), ImFontAtlasFlags_NoPowerOfTwoHeight, ImMax(), ImUpperPowerOfTwo(), ImFont::IsLoaded(), ImGui::MemAlloc(), ImGui::MemFree(), memset(), ImFontConfig::MergeMode, NULL, stbtt_pack_range::num_chars, ImFontConfig::OversampleH, ImFontConfig::OversampleV, stbtt_pack_context::pack_info, stbtt_pack_context::pixels, ImFontConfig::RasterizerMultiply, stbtt_aligned_quad::s0, stbtt_aligned_quad::s1, ImVector< T >::Size, ImFontConfig::SizePixels, stbrp_pack_rects(), stbtt_GetFontOffsetForIndex(), stbtt_GetFontVMetrics(), stbtt_GetPackedQuad(), stbtt_InitFont(), stbtt_PackBegin(), stbtt_PackEnd(), stbtt_PackFontRangesGatherRects(), stbtt_PackFontRangesRenderIntoRects(), stbtt_PackSetOversampling(), stbtt_ScaleForPixelHeight(), stbtt_pack_context::stride_in_bytes, stbtt_aligned_quad::t0, stbtt_aligned_quad::t1, ImFontAtlas::TexDesiredWidth, ImFontAtlas::TexGlyphPadding, ImFontAtlas::TexHeight, ImFontAtlas::TexID, ImFontAtlas::TexPixelsAlpha8, ImFontAtlas::TexUvScale, ImFontAtlas::TexUvWhitePixel, ImFontAtlas::TexWidth, ImVec2::x, stbtt_aligned_quad::x0, stbtt_packedchar::x0, stbtt_aligned_quad::x1, stbtt_packedchar::x1, stbtt_packedchar::xadvance, ImVec2::y, stbtt_aligned_quad::y0, stbtt_packedchar::y0, stbtt_aligned_quad::y1, and stbtt_packedchar::y1.
Referenced by ImFontAtlas::Build().
ImFontAtlasBuildRegisterDefaultCustomRects()
IMGUI_API void ImFontAtlasBuildRegisterDefaultCustomRects (ImFontAtlas * atlas)
References ImFontAtlas::AddCustomRectRegular(), ImFontAtlas::CustomRectIds, ImFontAtlas::Flags, FONT_ATLAS_DEFAULT_TEX_DATA_H, FONT_ATLAS_DEFAULT_TEX_DATA_ID, FONT_ATLAS_DEFAULT_TEX_DATA_W_HALF, and ImFontAtlasFlags_NoMouseCursors.
Referenced by ImFontAtlasBuildWithStbTruetype().
ImFontAtlasBuildSetupFont()
IMGUI_API void ImFontAtlasBuildSetupFont (ImFontAtlas * atlas, ImFont * font, ImFontConfig * font_config, float ascent, float descent)
References ImFont::Ascent, ImFont::ClearOutputData(), ImFont::ConfigData, ImFont::ConfigDataCount, ImFont::ContainerAtlas, ImFont::Descent, ImFont::FontSize, ImFontConfig::MergeMode, and ImFontConfig::SizePixels.
Referenced by ImFontAtlasBuildWithStbTruetype().
ImFontAtlasBuildPackCustomRects()
IMGUI_API void ImFontAtlasBuildPackCustomRects (ImFontAtlas * atlas, void * spc)
References ImFontAtlas::CustomRects, ImVector< T >::Data, IM_ASSERT, ImMax(), memset(), ImVector< T >::resize(), ImVector< T >::Size, stbrp_pack_rects(), and ImFontAtlas::TexHeight.
Referenced by ImFontAtlasBuildWithStbTruetype().
ImFontAtlasBuildFinish()
IMGUI_API void ImFontAtlasBuildFinish (ImFontAtlas * atlas)
References ImFont::AddGlyph(), ImFontAtlas::CalcCustomRectUV(), ImFont::ContainerAtlas, ImFontAtlas::CustomRects, ImFontAtlas::CustomRect::Font, ImFontAtlas::Fonts, ImFontAtlas::CustomRect::GlyphAdvanceX, ImFontAtlas::CustomRect::GlyphOffset, ImFontAtlas::CustomRect::Height, ImFontAtlas::CustomRect::ID, IM_ASSERT, ImFontAtlasBuildRenderDefaultTexData(), NULL, ImVector< T >::Size, ImFontAtlas::CustomRect::Width, ImVec2::x, and ImVec2::y.
Referenced by ImFontAtlasBuildWithStbTruetype().
ImFontAtlasBuildMultiplyCalcLookupTable()
IMGUI_API void ImFontAtlasBuildMultiplyCalcLookupTable (unsigned char out_table[256], float in_multiply_factor)
References value.
Referenced by ImFontAtlasBuildWithStbTruetype().
ImFontAtlasBuildMultiplyRectAlpha8()
IMGUI_API void ImFontAtlasBuildMultiplyRectAlpha8 (const unsigned char table[256], unsigned char * pixels, int x, int y, int w, int h, int stride)
Referenced by ImFontAtlasBuildWithStbTruetype().
Variable Documentation
GImGui
IMGUI_API ImGuiContext* GImGui
Referenced by ImGui::AcceptDragDropPayload(), ImGui::ActivateItem(), AddWindowSettings(), AddWindowToDrawDataSelectLayer(), ImGui::AlignTextToFramePadding(), ImGui::ArrowButton(), ImGuiItemHoveredDataBackup::Backup(), ImGui::Begin(), BeginChildEx(), ImGui::BeginChildFrame(), ImGui::BeginColumns(), ImGui::BeginCombo(), ImGui::BeginDragDropSource(), ImGui::BeginDragDropTarget(), ImGui::BeginDragDropTargetCustom(), ImGui::BeginGroup(), ImGui::BeginMainMenuBar(), ImGui::BeginMenu(), ImGui::BeginPopup(), ImGui::BeginPopupContextItem(), ImGui::BeginPopupContextVoid(), ImGui::BeginPopupContextWindow(), ImGui::BeginPopupEx(), ImGui::BeginPopupModal(), ImGui::BeginTooltipEx(), ImGui::BringWindowToBack(), ImGui::BringWindowToFront(), ImGui::Bullet(), ImGui::BulletTextV(), ImGui::ButtonBehavior(), ImGui::ButtonEx(), ImGuiWindow::CalcFontSize(), ImGui::CalcItemSize(), ImGui::CalcListClipping(), CalcMaxPopupHeightFromItemCount(), CalcSizeAfterConstraint(), CalcSizeAutoFit(), ImGui::CalcTextSize(), ImGui::CaptureKeyboardFromApp(), ImGui::CaptureMouseFromApp(), ImGui::Checkbox(), CheckStacksSize(), ImGui::ClearDragDrop(), ImGui::CloseButton(), ImGui::CloseCurrentPopup(), ImGui::ClosePopup(), ImGui::ClosePopupsOverWindow(), ClosePopupToLevel(), ImGui::CollapsingHeader(), ImGui::ColorButton(), ImGui::ColorEdit4(), ImGui::ColorEditOptionsPopup(), ImGui::ColorPicker4(), ColorPickerOptionsPopup(), ImGui::ColorTooltip(), ImGui::CreateContext(), CreateNewWindow(), ImGui::DestroyContext(), ImGui::DragBehavior(), ImGui::DragFloat(), ImGui::DragFloatN(), ImGui::DragFloatRange2(), ImGui::DragIntN(), ImGui::DragIntRange2(), ImGui::End(), ImGui::EndChild(), ImGui::EndColumns(), ImGui::EndCombo(), ImGui::EndDragDropSource(), ImGui::EndDragDropTarget(), ImGui::EndFrame(), ImGui::EndGroup(), ImGui::EndMainMenuBar(), ImGui::EndMenu(), ImGui::EndMenuBar(), ImGui::EndPopup(), FindBestWindowPosForPopup(), FindHoveredWindow(), ImGui::FindSettingsHandler(), ImGui::FindWindowByName(), FindWindowIndex(), FindWindowNavigable(), ImGui::FindWindowSettings(), ImGui::FocusableItemRegister(), ImGui::FocusFrontMostActiveWindow(), ImGui::FocusWindow(), ImGui::GetActiveID(), ImGui::GetClipboardText(), GetClipboardTextFn_DefaultImpl(), ImGui::GetColorU32(), ImGui::GetCurrentContext(), ImGui::GetCurrentWindow(), ImGui::GetCurrentWindowRead(), GetDefaultFont(), GetDraggedColumnOffset(), ImGui::GetDrawData(), ImGui::GetDrawListSharedData(), ImGui::GetFont(), ImGui::GetFontSize(), ImGui::GetFontTexUvWhitePixel(), ImGui::GetFrameCount(), ImGui::GetFrameHeight(), ImGui::GetFrameHeightWithSpacing(), GetFrontMostModalRootWindow(), ImGui::GetHoveredID(), ImGui::GetID(), ImGui::GetIO(), ImGui::GetKeyIndex(), ImGui::GetKeyPressedAmount(), ImGui::GetMouseCursor(), ImGui::GetMouseDragDelta(), ImGui::GetMousePos(), ImGui::GetMousePosOnOpeningCurrentPopup(), ImGui::GetNavInputAmount(), ImGui::GetOverlayDrawList(), ImGui::GetScrollMaxX(), ImGui::GetScrollMaxY(), ImGui::GetScrollX(), ImGui::GetScrollY(), ImGui::GetStyle(), ImGui::GetStyleColorVec4(), ImGui::GetTextLineHeight(), ImGui::GetTextLineHeightWithSpacing(), ImGui::GetTime(), ImGui::GetTreeNodeToLabelSpacing(), GetViewportRect(), ImGui::GetWindowHeight(), ImGui::GetWindowPos(), ImGui::GetWindowWidth(), ImGui::ImageButton(), ImGui::Indent(), ImGui::InputFloatN(), ImGui::InputIntN(), ImGui::InputScalarAsWidgetReplacement(), ImGui::InputScalarEx(), InputTextCalcTextSizeW(), ImGui::InputTextEx(), ImGui::IsAnyItemActive(), ImGui::IsAnyItemFocused(), ImGui::IsAnyItemHovered(), ImGui::IsAnyMouseDown(), ImGui::IsClippedEx(), ImGui::IsDragDropPayloadBeingAccepted(), ImGui::IsItemActive(), ImGui::IsItemFocused(), ImGui::IsItemHovered(), ImGui::IsKeyDown(), ImGui::IsKeyPressed(), IsKeyPressedMap(), ImGui::IsKeyReleased(), ImGui::IsMouseClicked(), ImGui::IsMouseDoubleClicked(), ImGui::IsMouseDown(), ImGui::IsMouseDragging(), ImGui::IsMouseHoveringRect(), ImGui::IsMousePosValid(), ImGui::IsMouseReleased(), IsNavInputDown(), ImGui::IsPopupOpen(), IsWindowContentHoverable(), ImGui::IsWindowFocused(), ImGui::IsWindowHovered(), ImGui::IsWindowNavFocusable(), ImGui::ItemAdd(), ImGui::ItemHoverable(), ImGui::ItemSize(), ImGui::KeepAliveID(), ImGui::LabelTextV(), LoadIniSettingsFromMemory(), ImGui::LogButtons(), ImGui::LogFinish(), LogRenderedText(), ImGui::LogText(), ImGui::LogToClipboard(), ImGui::LogToFile(), ImGui::LogToTTY(), MarkIniSettingsDirty(), ImGui::MarkIniSettingsDirty(), ImGuiWindow::MenuBarHeight(), ImGui::MenuItem(), NavCalcPreferredMousePos(), ImGui::NavInitWindow(), NavMoveRequestButNoResultYet(), ImGui::NavMoveRequestCancel(), ImGui::NavProcessItem(), NavProcessMoveRequestWrapAround(), NavRestoreLayer(), NavScoreItem(), NavScrollToBringItemIntoView(), ImGui::NavUpdate(), NavUpdateAnyRequestFlag(), ImGui::NavUpdateWindowing(), NavUpdateWindowingHighlightWindow(), ImGui::NewFrame(), ImGui::NewLine(), ImGui::NextColumn(), ImGui::OpenPopup(), ImGui::OpenPopupEx(), ImGui::OpenPopupOnItemClick(), ImGui::PlotEx(), ImGui::PopFont(), ImGui::PopStyleColor(), ImGui::PopStyleVar(), ImGui::ProgressBar(), ImGui::PushFont(), ImGui::PushMultiItemsWidths(), ImGui::PushStyleColor(), ImGui::PushStyleVar(), ImGui::RadioButton(), ImGui::Render(), ImGui::RenderBullet(), ImGui::RenderCheckMark(), ImGui::RenderFrame(), ImGui::RenderFrameBorder(), ImGui::RenderNavHighlight(), ImGui::RenderText(), ImGui::RenderTextClipped(), ImGui::RenderTextWrapped(), ImGui::RenderTriangle(), ImGui::ResetMouseDragDelta(), ImGuiItemHoveredDataBackup::Restore(), ImGui::SameLine(), SaveIniSettingsToDisk(), SaveIniSettingsToMemory(), ImGui::Scrollbar(), ImGui::Selectable(), ImGui::Separator(), ImGui::SetActiveID(), ImGui::SetClipboardText(), SetClipboardTextFn_DefaultImpl(), ImGui::SetColorEditOptions(), ImGui::SetColumnOffset(), ImGui::SetCurrentContext(), ImGui::SetCurrentFont(), SetCurrentWindow(), SetCursorPosYAndSetupDummyPrevLine(), ImGui::SetDragDropPayload(), ImGui::SetFocusID(), ImGui::SetHoveredID(), ImGui::SetItemAllowOverlap(), ImGui::SetItemDefaultFocus(), ImGui::SetMouseCursor(), SetNavID(), SetNavIDAndMoveMouse(), ImGui::SetNextTreeNodeOpen(), ImGui::SetNextWindowBgAlpha(), ImGui::SetNextWindowCollapsed(), ImGui::SetNextWindowContentSize(), ImGui::SetNextWindowFocus(), ImGui::SetNextWindowPos(), ImGui::SetNextWindowSize(), ImGui::SetNextWindowSizeConstraints(), ImGui::SetScrollFromPosY(), ImGui::SetScrollHere(), SettingsHandlerWindow_ReadLine(), ImGui::SetWindowCollapsed(), ImGui::SetWindowFocus(), ImGui::SetWindowFontScale(), ImGui::SetWindowSize(), ImGui::ShowMetricsWindow(), ImGui::SliderBehavior(), ImGui::SliderFloat(), ImGui::SliderFloatN(), ImGui::SliderIntN(), ImGui::SmallButton(), ImGui::SplitterBehavior(), ImGuiStb::STB_TEXTEDIT_GETWIDTH(), ImGui::TextDisabledV(), ImGui::TextUnformatted(), ImGui::TextV(), ImGui::TextWrappedV(), ImGuiWindow::TitleBarHeight(), ImGui::TreeAdvanceToLabelPos(), ImGui::TreeNodeBehavior(), ImGui::TreeNodeBehaviorIsOpen(), ImGui::TreeNodeExV(), ImGui::TreePop(), ImGui::Unindent(), ImGui::UpdateManualResize(), ImGui::UpdateMovingWindow(), ImGui::VerticalSeparator(), and ImGui::VSliderFloat().