Aurora Framework: Cross.cpp File Reference
Cross.cpp File Reference
Macros
#define log(...) fprintf(stderr, __VA_ARGS__)
Functions
static string ensure_valid_identifier (const string &name, bool member)
static bool exists_unaccessed_path_to_return (const CFG &cfg, uint32_t block, const unordered_set< uint32_t > &blocks)
static string extract_string (const vector< uint32_t > &spirv, uint32_t offset)
static bool is_valid_spirv_version (uint32_t version)
static bool storage_class_is_interface (spv::StorageClass storage)
static uint32_t swap_endian (uint32_t v)
Macro Definition Documentation
log
#define log (...) fprintf(stderr, __VA_ARGS__)
Function Documentation
ensure_valid_identifier()
static string ensure_valid_identifier (const string & name, bool member) static
References setup::name.
Referenced by spirv_cross::Compiler::set_member_name(), and spirv_cross::Compiler::set_name().
storage_class_is_interface()
static bool storage_class_is_interface (spv::StorageClass storage) inline static
References spv::StorageClassAtomicCounter, spv::StorageClassInput, spv::StorageClassOutput, spv::StorageClassPushConstant, spv::StorageClassStorageBuffer, spv::StorageClassUniform, and spv::StorageClassUniformConstant.
Referenced by spirv_cross::Compiler::InterfaceVariableAccessHandler::handle(), and spirv_cross::Compiler::is_hidden_variable().
swap_endian()
static uint32_t swap_endian (uint32_t v) inline static
Referenced by spirv_cross::Compiler::parse().
extract_string()
static string extract_string (const vector< uint32_t > & spirv, uint32_t offset) static
References spirv_cross::Compiler::spirv, and SPIRV_CROSS_THROW.
Referenced by spirv_cross::Compiler::parse().
is_valid_spirv_version()
static bool is_valid_spirv_version (uint32_t version) static
References create_symbols_file::version.
Referenced by spirv_cross::Compiler::parse().
exists_unaccessed_path_to_return()
static bool exists_unaccessed_path_to_return (const CFG & cfg, uint32_t block, const unordered_set< uint32_t > & blocks) static
References spirv_cross::CFG::get_succeeding_edges().
Referenced by spirv_cross::Compiler::analyze_parameter_preservation().