Aurora Framework: Input.c File Reference
Input.c File Reference
Macros
#define _GLFW_JOYSTICK_AXIS 1
#define _GLFW_JOYSTICK_BUTTON 2
#define _GLFW_JOYSTICK_HATBIT 3
#define _GLFW_STICK 3
Functions
_GLFWjoystick * _glfwAllocJoystick (const char *name, const char *guid, int axisCount, int buttonCount, int hatCount)
void _glfwFreeJoystick (_GLFWjoystick *js)
void _glfwInputChar (_GLFWwindow *window, unsigned int codepoint, int mods, GLFWbool plain)
void _glfwInputCursorEnter (_GLFWwindow *window, GLFWbool entered)
void _glfwInputCursorPos (_GLFWwindow *window, double xpos, double ypos)
void _glfwInputDrop (_GLFWwindow *window, int count, const char **paths)
void _glfwInputJoystick (_GLFWjoystick *js, int event)
void _glfwInputJoystickAxis (_GLFWjoystick *js, int axis, float value)
void _glfwInputJoystickButton (_GLFWjoystick *js, int button, char value)
void _glfwInputJoystickHat (_GLFWjoystick *js, int hat, char value)
void _glfwInputKey (_GLFWwindow *window, int key, int scancode, int action, int mods)
void _glfwInputMouseClick (_GLFWwindow *window, int button, int action, int mods)
void _glfwInputScroll (_GLFWwindow *window, double xoffset, double yoffset)
static _GLFWmapping * findMapping (const char *guid)
static _GLFWmapping * findValidMapping (const _GLFWjoystick *js)
GLFWAPI GLFWcursor * glfwCreateCursor (const GLFWimage *image, int xhot, int yhot)
Creates a custom cursor.
GLFWAPI GLFWcursor * glfwCreateStandardCursor (int shape)
Creates a cursor with a standard shape.
GLFWAPI void glfwDestroyCursor (GLFWcursor *handle)
Destroys a cursor.
GLFWAPI const char * glfwGetClipboardString (GLFWwindow *handle)
Returns the contents of the clipboard as a string.
GLFWAPI void glfwGetCursorPos (GLFWwindow *handle, double *xpos, double *ypos)
Retrieves the position of the cursor relative to the client area of the window.
GLFWAPI const char * glfwGetGamepadName (int jid)
Returns the human-readable gamepad name for the specified joystick.
GLFWAPI int glfwGetGamepadState (int jid, GLFWgamepadstate *state)
Retrieves the state of the specified joystick remapped as a gamepad.
GLFWAPI int glfwGetInputMode (GLFWwindow *handle, int mode)
Returns the value of an input option for the specified window.
GLFWAPI const float * glfwGetJoystickAxes (int jid, int *count)
Returns the values of all axes of the specified joystick.
GLFWAPI const unsigned char * glfwGetJoystickButtons (int jid, int *count)
Returns the state of all buttons of the specified joystick.
GLFWAPI const char * glfwGetJoystickGUID (int jid)
Returns the SDL comaptible GUID of the specified joystick.
GLFWAPI const unsigned char * glfwGetJoystickHats (int jid, int *count)
Returns the state of all hats of the specified joystick.
GLFWAPI const char * glfwGetJoystickName (int jid)
Returns the name of the specified joystick.
GLFWAPI void * glfwGetJoystickUserPointer (int jid)
Returns the user pointer of the specified joystick.
GLFWAPI int glfwGetKey (GLFWwindow *handle, int key)
Returns the last reported state of a keyboard key for the specified window.
GLFWAPI const char * glfwGetKeyName (int key, int scancode)
Returns the layout-specific name of the specified printable key.
GLFWAPI int glfwGetKeyScancode (int key)
Returns the platform-specific scancode of the specified key.
GLFWAPI int glfwGetMouseButton (GLFWwindow *handle, int button)
Returns the last reported state of a mouse button for the specified window.
GLFWAPI double glfwGetTime (void)
Returns the value of the GLFW timer.
GLFWAPI uint64_t glfwGetTimerFrequency (void)
Returns the frequency, in Hz, of the raw timer.
GLFWAPI uint64_t glfwGetTimerValue (void)
Returns the current value of the raw timer.
GLFWAPI int glfwJoystickIsGamepad (int jid)
Returns whether the specified joystick has a gamepad mapping.
GLFWAPI int glfwJoystickPresent (int jid)
Returns whether the specified joystick is present.
GLFWAPI GLFWcharfun glfwSetCharCallback (GLFWwindow *handle, GLFWcharfun cbfun)
Sets the Unicode character callback.
GLFWAPI GLFWcharmodsfun glfwSetCharModsCallback (GLFWwindow *handle, GLFWcharmodsfun cbfun)
Sets the Unicode character with modifiers callback.
GLFWAPI void glfwSetClipboardString (GLFWwindow *handle, const char *string)
Sets the clipboard to the specified string.
GLFWAPI void glfwSetCursor (GLFWwindow *windowHandle, GLFWcursor *cursorHandle)
Sets the cursor for the window.
GLFWAPI GLFWcursorenterfun glfwSetCursorEnterCallback (GLFWwindow *handle, GLFWcursorenterfun cbfun)
Sets the cursor enter/exit callback.
GLFWAPI void glfwSetCursorPos (GLFWwindow *handle, double xpos, double ypos)
Sets the position of the cursor, relative to the client area of the window.
GLFWAPI GLFWcursorposfun glfwSetCursorPosCallback (GLFWwindow *handle, GLFWcursorposfun cbfun)
Sets the cursor position callback.
GLFWAPI GLFWdropfun glfwSetDropCallback (GLFWwindow *handle, GLFWdropfun cbfun)
Sets the file drop callback.
GLFWAPI void glfwSetInputMode (GLFWwindow *handle, int mode, int value)
Sets an input option for the specified window.
GLFWAPI GLFWjoystickfun glfwSetJoystickCallback (GLFWjoystickfun cbfun)
Sets the joystick configuration callback.
GLFWAPI void glfwSetJoystickUserPointer (int jid, void *pointer)
Sets the user pointer of the specified joystick.
GLFWAPI GLFWkeyfun glfwSetKeyCallback (GLFWwindow *handle, GLFWkeyfun cbfun)
Sets the key callback.
GLFWAPI GLFWmousebuttonfun glfwSetMouseButtonCallback (GLFWwindow *handle, GLFWmousebuttonfun cbfun)
Sets the mouse button callback.
GLFWAPI GLFWscrollfun glfwSetScrollCallback (GLFWwindow *handle, GLFWscrollfun cbfun)
Sets the scroll callback.
GLFWAPI void glfwSetTime (double time)
Sets the GLFW timer.
GLFWAPI int glfwUpdateGamepadMappings (const char *string)
Adds the specified SDL_GameControllerDB gamepad mappings.
static GLFWbool isValidElementForJoystick (const _GLFWmapelement *e, const _GLFWjoystick *js)
static GLFWbool parseMapping (_GLFWmapping *mapping, const char *string)
Macro Definition Documentation
_GLFW_STICK
#define _GLFW_STICK 3
Referenced by _glfwInputKey(), _glfwInputMouseClick(), glfwGetKey(), glfwGetMouseButton(), and glfwSetInputMode().
_GLFW_JOYSTICK_AXIS
#define _GLFW_JOYSTICK_AXIS 1
Referenced by glfwGetGamepadState(), isValidElementForJoystick(), and parseMapping().
_GLFW_JOYSTICK_BUTTON
#define _GLFW_JOYSTICK_BUTTON 2
Referenced by glfwGetGamepadState(), isValidElementForJoystick(), and parseMapping().
_GLFW_JOYSTICK_HATBIT
#define _GLFW_JOYSTICK_HATBIT 3
Referenced by glfwGetGamepadState(), isValidElementForJoystick(), and parseMapping().
Function Documentation
findMapping()
static _GLFWmapping* findMapping (const char * guid) static
References _glfw, _GLFWmapping::guid, _GLFWlibrary::mappingCount, _GLFWlibrary::mappings, and NULL.
Referenced by findValidMapping(), and glfwUpdateGamepadMappings().
isValidElementForJoystick()
static GLFWbool isValidElementForJoystick (const _GLFWmapelement * e, const _GLFWjoystick * js) static
References _GLFW_JOYSTICK_AXIS, _GLFW_JOYSTICK_BUTTON, _GLFW_JOYSTICK_HATBIT, _GLFWjoystick::axisCount, _GLFWjoystick::buttonCount, GLFW_FALSE, GLFW_TRUE, _GLFWjoystick::hatCount, _GLFWmapelement::index, and _GLFWmapelement::type.
Referenced by findValidMapping().
findValidMapping()
static _GLFWmapping* findValidMapping (const _GLFWjoystick * js) static
References _glfwInputError(), _GLFWmapping::axes, _GLFWmapping::buttons, findMapping(), GLFW_GAMEPAD_AXIS_LAST, GLFW_GAMEPAD_BUTTON_LAST, GLFW_INVALID_VALUE, _GLFWmapping::guid, _GLFWjoystick::guid, isValidElementForJoystick(), _GLFWmapping::name, and NULL.
Referenced by _glfwAllocJoystick(), and glfwUpdateGamepadMappings().
parseMapping()
static GLFWbool parseMapping (_GLFWmapping * mapping, const char * string) static
References _GLFW_JOYSTICK_AXIS, _GLFW_JOYSTICK_BUTTON, _GLFW_JOYSTICK_HATBIT, _GLFW_PLATFORM_MAPPING_NAME, _glfwInputError(), _glfwPlatformUpdateGamepadGUID(), _GLFWmapping::axes, _GLFWmapelement::axisOffset, _GLFWmapelement::axisScale, _GLFWmapping::buttons, GLFW_FALSE, GLFW_GAMEPAD_AXIS_LEFT_TRIGGER, GLFW_GAMEPAD_AXIS_LEFT_X, GLFW_GAMEPAD_AXIS_LEFT_Y, GLFW_GAMEPAD_AXIS_RIGHT_TRIGGER, GLFW_GAMEPAD_AXIS_RIGHT_X, GLFW_GAMEPAD_AXIS_RIGHT_Y, GLFW_GAMEPAD_BUTTON_A, GLFW_GAMEPAD_BUTTON_B, GLFW_GAMEPAD_BUTTON_BACK, GLFW_GAMEPAD_BUTTON_DPAD_DOWN, GLFW_GAMEPAD_BUTTON_DPAD_LEFT, GLFW_GAMEPAD_BUTTON_DPAD_RIGHT, GLFW_GAMEPAD_BUTTON_DPAD_UP, GLFW_GAMEPAD_BUTTON_GUIDE, GLFW_GAMEPAD_BUTTON_LEFT_BUMPER, GLFW_GAMEPAD_BUTTON_LEFT_THUMB, GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER, GLFW_GAMEPAD_BUTTON_RIGHT_THUMB, GLFW_GAMEPAD_BUTTON_START, GLFW_GAMEPAD_BUTTON_X, GLFW_GAMEPAD_BUTTON_Y, GLFW_INVALID_VALUE, GLFW_TRUE, _GLFWmapping::guid, _GLFWmapelement::index, memcpy(), setup::name, _GLFWmapping::name, NULL, and _GLFWmapelement::type.
Referenced by glfwUpdateGamepadMappings().
_glfwInputKey()
void _glfwInputKey (_GLFWwindow * window, int key, int scancode, int action, int mods)
References _GLFW_STICK, _GLFWwindow::callbacks, GLFW_FALSE, GLFW_KEY_LAST, GLFW_MOD_CAPS_LOCK, GLFW_MOD_NUM_LOCK, GLFW_PRESS, GLFW_RELEASE, GLFW_REPEAT, GLFW_TRUE, _GLFWwindow::key, _GLFWwindow::keys, _GLFWwindow::lockKeyMods, and _GLFWwindow::stickyKeys.
Referenced by _glfwInputWindowFocus(), _glfwPlatformPollEvents(), handleEvents(), handleKeyEvent(), keyboardHandleKey(), processEvent(), and windowProc().
_glfwInputChar()
void _glfwInputChar (_GLFWwindow * window, unsigned int codepoint, int mods, GLFWbool plain)
References _GLFWwindow::callbacks, _GLFWwindow::charmods, GLFW_MOD_CAPS_LOCK, GLFW_MOD_NUM_LOCK, and _GLFWwindow::lockKeyMods.
Referenced by handleKeyEvent(), inputChar(), processEvent(), and windowProc().
_glfwInputScroll()
void _glfwInputScroll (_GLFWwindow * window, double xoffset, double yoffset)
References _GLFWwindow::callbacks, and _GLFWwindow::scroll.
Referenced by handlePointerMotion(), pointerHandleAxis(), processEvent(), and windowProc().
_glfwInputMouseClick()
void _glfwInputMouseClick (_GLFWwindow * window, int button, int action, int mods)
References _GLFW_STICK, _GLFWwindow::callbacks, GLFW_MOD_CAPS_LOCK, GLFW_MOD_NUM_LOCK, GLFW_MOUSE_BUTTON_LAST, GLFW_RELEASE, _GLFWwindow::lockKeyMods, _GLFWwindow::mouseButton, _GLFWwindow::mouseButtons, and _GLFWwindow::stickyMouseButtons.
Referenced by _glfwInputWindowFocus(), handlePointerButton(), pointerHandleButton(), processEvent(), and windowProc().
_glfwInputCursorPos()
void _glfwInputCursorPos (_GLFWwindow * window, double xpos, double ypos)
References _GLFWwindow::callbacks, _GLFWwindow::cursorPos, _GLFWwindow::virtualCursorPosX, and _GLFWwindow::virtualCursorPosY.
Referenced by handlePointerMotion(), handleRelativeMotion(), pointerHandleMotion(), processEvent(), and windowProc().
_glfwInputCursorEnter()
void _glfwInputCursorEnter (_GLFWwindow * window, GLFWbool entered)
References _GLFWwindow::callbacks, and _GLFWwindow::cursorEnter.
Referenced by _glfwPlatformDestroyWindow(), pointerHandleEnter(), pointerHandleLeave(), processEvent(), and windowProc().
_glfwInputDrop()
void _glfwInputDrop (_GLFWwindow * window, int count, const char ** paths)
References _GLFWwindow::callbacks, and _GLFWwindow::drop.
Referenced by processEvent(), and windowProc().
_glfwInputJoystick()
void _glfwInputJoystick (_GLFWjoystick * js, int event)
References _glfw, _GLFWlibrary::callbacks, _GLFWlibrary::joystick, and _GLFWlibrary::joysticks.
Referenced by _glfwDetectJoystickConnectionWin32(), closeJoystick(), deviceCallback(), matchCallback(), and openJoystickDevice().
_glfwInputJoystickAxis()
void _glfwInputJoystickAxis (_GLFWjoystick * js, int axis, float value)
References _GLFWjoystick::axes, and value.
Referenced by _glfwPlatformPollJoystick(), and handleAbsEvent().
_glfwInputJoystickButton()
void _glfwInputJoystickButton (_GLFWjoystick * js, int button, char value)
References _GLFWjoystick::buttons, and value.
Referenced by _glfwPlatformPollJoystick(), and handleKeyEvent().
_glfwInputJoystickHat()
void _glfwInputJoystickHat (_GLFWjoystick * js, int hat, char value)
References _GLFWjoystick::buttonCount, _GLFWjoystick::buttons, GLFW_PRESS, GLFW_RELEASE, _GLFWjoystick::hats, and value.
Referenced by _glfwPlatformPollJoystick(), and handleAbsEvent().
_glfwAllocJoystick()
_GLFWjoystick* _glfwAllocJoystick (const char * name, const char * guid, int axisCount, int buttonCount, int hatCount)
References _glfw, _glfw_strdup(), _GLFWjoystick::axes, _GLFWjoystick::axisCount, _GLFWjoystick::buttonCount, _GLFWjoystick::buttons, findValidMapping(), GLFW_JOYSTICK_LAST, GLFW_TRUE, _GLFWjoystick::guid, _GLFWjoystick::hatCount, _GLFWjoystick::hats, _GLFWlibrary::joysticks, _GLFWjoystick::mapping, setup::name, _GLFWjoystick::name, NULL, and _GLFWjoystick::present.
Referenced by _glfwDetectJoystickConnectionWin32(), deviceCallback(), matchCallback(), and openJoystickDevice().
_glfwFreeJoystick()
void _glfwFreeJoystick (_GLFWjoystick * js)
References _GLFWjoystick::axes, _GLFWjoystick::buttons, _GLFWjoystick::hats, memset(), and _GLFWjoystick::name.
Referenced by closeJoystick().