Aurora Framework: wavlike.h File Reference
wavlike.h File Reference
Classes
struct EXT_SUBFORMAT
struct EXTENSIBLE_WAV_FMT
struct FACT_CHUNK
struct G72x_ADPCM_WAV_FMT
struct GSM610_WAV_FMT
struct IMA_ADPCM_WAV_FMT
struct MIN_WAV_FMT
struct MS_ADPCM_WAV_FMT
union WAV_FMT
struct WAV_FMT_SIZE20
struct WAVLIKE_PRIVATE
Macros
#define adtl_MARKER MAKE_MARKER ('a', 'd', 't', 'l')
#define bext_MARKER MAKE_MARKER ('b', 'e', 'x', 't')
#define cart_MARKER MAKE_MARKER ('c', 'a', 'r', 't')
#define data_MARKER MAKE_MARKER ('d', 'a', 't', 'a')
#define DISP_MARKER MAKE_MARKER ('D', 'I', 'S', 'P')
#define ecor_MARKER MAKE_MARKER ('e', 'c', 'o', 'r')
#define emdl_MARKER MAKE_MARKER ('e', 'm', 'd', 'l')
#define emnt_MARKER MAKE_MARKER ('e', 'm', 'n', 't')
#define erel_MARKER MAKE_MARKER ('e', 'r', 'e', 'l')
#define etim_MARKER MAKE_MARKER ('e', 't', 'i', 'm')
#define eucm_MARKER MAKE_MARKER ('e', 'u', 'c', 'm')
#define ever_MARKER MAKE_MARKER ('e', 'v', 'e', 'r')
#define exif_MARKER MAKE_MARKER ('e', 'x', 'i', 'f')
#define IARL_MARKER MAKE_MARKER ('I', 'A', 'R', 'L')
#define IART_MARKER MAKE_MARKER ('I', 'A', 'R', 'T')
#define IAUT_MARKER MAKE_MARKER ('I', 'A', 'U', 'T')
#define ICMT_MARKER MAKE_MARKER ('I', 'C', 'M', 'T')
#define ICOP_MARKER MAKE_MARKER ('I', 'C', 'O', 'P')
#define ICOP_MARKER MAKE_MARKER ('I', 'C', 'O', 'P')
#define ICRD_MARKER MAKE_MARKER ('I', 'C', 'R', 'D')
#define IENG_MARKER MAKE_MARKER ('I', 'E', 'N', 'G')
#define IGNR_MARKER MAKE_MARKER ('I', 'G', 'N', 'R')
#define INAM_MARKER MAKE_MARKER ('I', 'N', 'A', 'M')
#define INFO_MARKER MAKE_MARKER ('I', 'N', 'F', 'O')
#define IPRD_MARKER MAKE_MARKER ('I', 'P', 'R', 'D')
#define ISBJ_MARKER MAKE_MARKER ('I', 'S', 'B', 'J')
#define ISFT_MARKER MAKE_MARKER ('I', 'S', 'F', 'T')
#define ISRC_MARKER MAKE_MARKER ('I', 'S', 'R', 'C')
#define ITRK_MARKER MAKE_MARKER ('I', 'T', 'R', 'K')
#define labl_MARKER MAKE_MARKER ('l', 'a', 'b', 'l')
#define LIST_MARKER MAKE_MARKER ('L', 'I', 'S', 'T')
#define ltxt_MARKER MAKE_MARKER ('l', 't', 'x', 't')
#define note_MARKER MAKE_MARKER ('n', 'o', 't', 'e')
#define olym_MARKER MAKE_MARKER ('o', 'l', 'y', 'm')
#define PAD_MARKER MAKE_MARKER ('P', 'A', 'D', ' ')
#define PEAK_MARKER MAKE_MARKER ('P', 'E', 'A', 'K')
#define WAVLIKE_GSM610_BLOCKSIZE 65
#define WAVLIKE_GSM610_SAMPLES 320
#define WAVLIKE_MSADPCM_ADAPT_COEFF_COUNT 7
#define WAVLIKE_PEAK_CHUNK_SIZE(ch) (2 * sizeof (int) + ch * (sizeof (float) + sizeof (int)))
Enumerations
enum {
WAVE_FORMAT_UNKNOWN = 0x0000, WAVE_FORMAT_PCM = 0x0001, WAVE_FORMAT_MS_ADPCM = 0x0002, WAVE_FORMAT_IEEE_FLOAT = 0x0003,
WAVE_FORMAT_VSELP = 0x0004, WAVE_FORMAT_IBM_CVSD = 0x0005, WAVE_FORMAT_ALAW = 0x0006, WAVE_FORMAT_MULAW = 0x0007,
WAVE_FORMAT_OKI_ADPCM = 0x0010, WAVE_FORMAT_IMA_ADPCM = 0x0011, WAVE_FORMAT_MEDIASPACE_ADPCM = 0x0012, WAVE_FORMAT_SIERRA_ADPCM = 0x0013,
WAVE_FORMAT_G723_ADPCM = 0x0014, WAVE_FORMAT_DIGISTD = 0x0015, WAVE_FORMAT_DIGIFIX = 0x0016, WAVE_FORMAT_DIALOGIC_OKI_ADPCM = 0x0017,
WAVE_FORMAT_MEDIAVISION_ADPCM = 0x0018, WAVE_FORMAT_CU_CODEC = 0x0019, WAVE_FORMAT_YAMAHA_ADPCM = 0x0020, WAVE_FORMAT_SONARC = 0x0021,
WAVE_FORMAT_DSPGROUP_TRUESPEECH = 0x0022, WAVE_FORMAT_ECHOSC1 = 0x0023, WAVE_FORMAT_AUDIOFILE_AF36 = 0x0024, WAVE_FORMAT_APTX = 0x0025,
WAVE_FORMAT_AUDIOFILE_AF10 = 0x0026, WAVE_FORMAT_PROSODY_1612 = 0x0027, WAVE_FORMAT_LRC = 0x0028, WAVE_FORMAT_DOLBY_AC2 = 0x0030,
WAVE_FORMAT_GSM610 = 0x0031, WAVE_FORMAT_MSNAUDIO = 0x0032, WAVE_FORMAT_ANTEX_ADPCME = 0x0033, WAVE_FORMAT_CONTROL_RES_VQLPC = 0x0034,
WAVE_FORMAT_DIGIREAL = 0x0035, WAVE_FORMAT_DIGIADPCM = 0x0036, WAVE_FORMAT_CONTROL_RES_CR10 = 0x0037, WAVE_FORMAT_NMS_VBXADPCM = 0x0038,
WAVE_FORMAT_ROLAND_RDAC = 0x0039, WAVE_FORMAT_ECHOSC3 = 0x003A, WAVE_FORMAT_ROCKWELL_ADPCM = 0x003B, WAVE_FORMAT_ROCKWELL_DIGITALK = 0x003C,
WAVE_FORMAT_XEBEC = 0x003D, WAVE_FORMAT_G721_ADPCM = 0x0040, WAVE_FORMAT_G728_CELP = 0x0041, WAVE_FORMAT_MSG723 = 0x0042,
WAVE_FORMAT_MPEG = 0x0050, WAVE_FORMAT_RT24 = 0x0052, WAVE_FORMAT_PAC = 0x0053, WAVE_FORMAT_MPEGLAYER3 = 0x0055,
WAVE_FORMAT_LUCENT_G723 = 0x0059, WAVE_FORMAT_CIRRUS = 0x0060, WAVE_FORMAT_ESPCM = 0x0061, WAVE_FORMAT_VOXWARE = 0x0062,
WAVE_FORMAT_CANOPUS_ATRAC = 0x0063, WAVE_FORMAT_G726_ADPCM = 0x0064, WAVE_FORMAT_G722_ADPCM = 0x0065, WAVE_FORMAT_DSAT = 0x0066,
WAVE_FORMAT_DSAT_DISPLAY = 0x0067, WAVE_FORMAT_VOXWARE_BYTE_ALIGNED = 0x0069, WAVE_FORMAT_VOXWARE_AC8 = 0x0070, WAVE_FORMAT_VOXWARE_AC10 = 0x0071,
WAVE_FORMAT_VOXWARE_AC16 = 0x0072, WAVE_FORMAT_VOXWARE_AC20 = 0x0073, WAVE_FORMAT_VOXWARE_RT24 = 0x0074, WAVE_FORMAT_VOXWARE_RT29 = 0x0075,
WAVE_FORMAT_VOXWARE_RT29HW = 0x0076, WAVE_FORMAT_VOXWARE_VR12 = 0x0077, WAVE_FORMAT_VOXWARE_VR18 = 0x0078, WAVE_FORMAT_VOXWARE_TQ40 = 0x0079,
WAVE_FORMAT_SOFTSOUND = 0x0080, WAVE_FORMAT_VOXARE_TQ60 = 0x0081, WAVE_FORMAT_MSRT24 = 0x0082, WAVE_FORMAT_G729A = 0x0083,
WAVE_FORMAT_MVI_MV12 = 0x0084, WAVE_FORMAT_DF_G726 = 0x0085, WAVE_FORMAT_DF_GSM610 = 0x0086, WAVE_FORMAT_ONLIVE = 0x0089,
WAVE_FORMAT_SBC24 = 0x0091, WAVE_FORMAT_DOLBY_AC3_SPDIF = 0x0092, WAVE_FORMAT_ZYXEL_ADPCM = 0x0097, WAVE_FORMAT_PHILIPS_LPCBB = 0x0098,
WAVE_FORMAT_PACKED = 0x0099, WAVE_FORMAT_RHETOREX_ADPCM = 0x0100, IBM_FORMAT_MULAW = 0x0101, IBM_FORMAT_ALAW = 0x0102,
IBM_FORMAT_ADPCM = 0x0103, WAVE_FORMAT_VIVO_G723 = 0x0111, WAVE_FORMAT_VIVO_SIREN = 0x0112, WAVE_FORMAT_DIGITAL_G723 = 0x0123,
WAVE_FORMAT_CREATIVE_ADPCM = 0x0200, WAVE_FORMAT_CREATIVE_FASTSPEECH8 = 0x0202, WAVE_FORMAT_CREATIVE_FASTSPEECH10 = 0x0203, WAVE_FORMAT_QUARTERDECK = 0x0220,
WAVE_FORMAT_FM_TOWNS_SND = 0x0300, WAVE_FORMAT_BZV_DIGITAL = 0x0400, WAVE_FORMAT_VME_VMPCM = 0x0680, WAVE_FORMAT_OLIGSM = 0x1000,
WAVE_FORMAT_OLIADPCM = 0x1001, WAVE_FORMAT_OLICELP = 0x1002, WAVE_FORMAT_OLISBC = 0x1003, WAVE_FORMAT_OLIOPR = 0x1004,
WAVE_FORMAT_LH_CODEC = 0x1100, WAVE_FORMAT_NORRIS = 0x1400, WAVE_FORMAT_SOUNDSPACE_MUSICOMPRESS = 0x1500, WAVE_FORMAT_DVM = 0x2000,
WAVE_FORMAT_INTERWAV_VSC112 = 0x7150, WAVE_FORMAT_IPP_ITU_G_723_1 = 0x7230, WAVE_FORMAT_EXTENSIBLE = 0xFFFE
}
Functions
void wavlike_analyze (SF_PRIVATE *psf)
char const * wavlike_format_str (int k)
int wavlike_gen_channel_mask (const int *chan_map, int channels)
void wavlike_msadpcm_write_adapt_coeffs (SF_PRIVATE *psf)
int wavlike_read_bext_chunk (SF_PRIVATE *psf, uint32_t chunksize)
int wavlike_read_cart_chunk (SF_PRIVATE *psf, uint32_t chunksize)
int wavlike_read_fmt_chunk (SF_PRIVATE *psf, int fmtsize)
int wavlike_read_peak_chunk (SF_PRIVATE *psf, size_t chunk_size)
int wavlike_srate2blocksize (int srate_chan_product)
int wavlike_subchunk_parse (SF_PRIVATE *psf, int chunk, uint32_t length)
int wavlike_write_bext_chunk (SF_PRIVATE *psf)
int wavlike_write_cart_chunk (SF_PRIVATE *psf)
void wavlike_write_custom_chunks (SF_PRIVATE *psf)
void wavlike_write_guid (SF_PRIVATE *psf, const EXT_SUBFORMAT *subformat)
void wavlike_write_peak_chunk (SF_PRIVATE *psf)
void wavlike_write_strings (SF_PRIVATE *psf, int location)
Macro Definition Documentation
adtl_MARKER
#define adtl_MARKER MAKE_MARKER ('a', 'd', 't', 'l')
Referenced by wavlike_subchunk_parse().
bext_MARKER
#define bext_MARKER MAKE_MARKER ('b', 'e', 'x', 't')
cart_MARKER
#define cart_MARKER MAKE_MARKER ('c', 'a', 'r', 't')
data_MARKER
#define data_MARKER MAKE_MARKER ('d', 'a', 't', 'a')
labl_MARKER
#define labl_MARKER MAKE_MARKER ('l', 'a', 'b', 'l')
Referenced by wavlike_subchunk_parse().
ltxt_MARKER
#define ltxt_MARKER MAKE_MARKER ('l', 't', 'x', 't')
Referenced by wavlike_subchunk_parse().
note_MARKER
#define note_MARKER MAKE_MARKER ('n', 'o', 't', 'e')
Referenced by wavlike_subchunk_parse().
DISP_MARKER
#define DISP_MARKER MAKE_MARKER ('D', 'I', 'S', 'P')
Referenced by wav_read_header(), and wavlike_subchunk_parse().
INFO_MARKER
#define INFO_MARKER MAKE_MARKER ('I', 'N', 'F', 'O')
Referenced by rf64_read_header(), wav_read_header(), wavlike_subchunk_parse(), and wavlike_write_strings().
LIST_MARKER
#define LIST_MARKER MAKE_MARKER ('L', 'I', 'S', 'T')
PAD_MARKER
#define PAD_MARKER MAKE_MARKER ('P', 'A', 'D', ' ')
Referenced by rf64_read_header(), rf64_write_header(), wav_read_header(), and wav_write_header().
PEAK_MARKER
#define PEAK_MARKER MAKE_MARKER ('P', 'E', 'A', 'K')
ISFT_MARKER
#define ISFT_MARKER MAKE_MARKER ('I', 'S', 'F', 'T')
Referenced by wavlike_subchunk_parse(), and wavlike_write_strings().
ICRD_MARKER
#define ICRD_MARKER MAKE_MARKER ('I', 'C', 'R', 'D')
Referenced by wavlike_subchunk_parse(), and wavlike_write_strings().
ICOP_MARKER [1/2]
#define ICOP_MARKER MAKE_MARKER ('I', 'C', 'O', 'P')
Referenced by wavlike_subchunk_parse(), and wavlike_write_strings().
IARL_MARKER
#define IARL_MARKER MAKE_MARKER ('I', 'A', 'R', 'L')
Referenced by wavlike_subchunk_parse().
IART_MARKER
#define IART_MARKER MAKE_MARKER ('I', 'A', 'R', 'T')
Referenced by wavlike_subchunk_parse(), and wavlike_write_strings().
INAM_MARKER
#define INAM_MARKER MAKE_MARKER ('I', 'N', 'A', 'M')
Referenced by wavlike_subchunk_parse(), and wavlike_write_strings().
IENG_MARKER
#define IENG_MARKER MAKE_MARKER ('I', 'E', 'N', 'G')
Referenced by wavlike_subchunk_parse().
IGNR_MARKER
#define IGNR_MARKER MAKE_MARKER ('I', 'G', 'N', 'R')
Referenced by wavlike_subchunk_parse(), and wavlike_write_strings().
ICOP_MARKER [2/2]
#define ICOP_MARKER MAKE_MARKER ('I', 'C', 'O', 'P')
IPRD_MARKER
#define IPRD_MARKER MAKE_MARKER ('I', 'P', 'R', 'D')
Referenced by wavlike_subchunk_parse(), and wavlike_write_strings().
ISRC_MARKER
#define ISRC_MARKER MAKE_MARKER ('I', 'S', 'R', 'C')
Referenced by wavlike_subchunk_parse().
ISBJ_MARKER
#define ISBJ_MARKER MAKE_MARKER ('I', 'S', 'B', 'J')
Referenced by wavlike_subchunk_parse().
ICMT_MARKER
#define ICMT_MARKER MAKE_MARKER ('I', 'C', 'M', 'T')
Referenced by wavlike_subchunk_parse(), and wavlike_write_strings().
IAUT_MARKER
#define IAUT_MARKER MAKE_MARKER ('I', 'A', 'U', 'T')
Referenced by wavlike_subchunk_parse().
ITRK_MARKER
#define ITRK_MARKER MAKE_MARKER ('I', 'T', 'R', 'K')
Referenced by wavlike_subchunk_parse(), and wavlike_write_strings().
exif_MARKER
#define exif_MARKER MAKE_MARKER ('e', 'x', 'i', 'f')
Referenced by wavlike_subchunk_parse().
ever_MARKER
#define ever_MARKER MAKE_MARKER ('e', 'v', 'e', 'r')
Referenced by exif_subchunk_parse().
etim_MARKER
#define etim_MARKER MAKE_MARKER ('e', 't', 'i', 'm')
Referenced by exif_subchunk_parse().
ecor_MARKER
#define ecor_MARKER MAKE_MARKER ('e', 'c', 'o', 'r')
Referenced by exif_subchunk_parse().
emdl_MARKER
#define emdl_MARKER MAKE_MARKER ('e', 'm', 'd', 'l')
Referenced by exif_subchunk_parse().
emnt_MARKER
#define emnt_MARKER MAKE_MARKER ('e', 'm', 'n', 't')
Referenced by exif_subchunk_parse().
erel_MARKER
#define erel_MARKER MAKE_MARKER ('e', 'r', 'e', 'l')
Referenced by exif_subchunk_parse().
eucm_MARKER
#define eucm_MARKER MAKE_MARKER ('e', 'u', 'c', 'm')
Referenced by exif_subchunk_parse().
olym_MARKER
#define olym_MARKER MAKE_MARKER ('o', 'l', 'y', 'm')
Referenced by exif_subchunk_parse().
WAVLIKE_GSM610_BLOCKSIZE
#define WAVLIKE_GSM610_BLOCKSIZE 65
Referenced by gsm610_init(), gsm610_wav_decode_block(), gsm610_wav_encode_block(), w64_write_header(), and wav_write_fmt_chunk().
WAVLIKE_GSM610_SAMPLES
#define WAVLIKE_GSM610_SAMPLES 320
Referenced by gsm610_init(), gsm610_wav_decode_block(), gsm610_wav_encode_block(), w64_write_header(), and wav_write_fmt_chunk().
WAVLIKE_PEAK_CHUNK_SIZE
#define WAVLIKE_PEAK_CHUNK_SIZE (ch) (2 * sizeof (int) + ch * (sizeof (float) + sizeof (int)))
WAVLIKE_MSADPCM_ADAPT_COEFF_COUNT
#define WAVLIKE_MSADPCM_ADAPT_COEFF_COUNT 7
Referenced by msadpcm_get_bpred(), w64_write_header(), wav_write_fmt_chunk(), and wavlike_msadpcm_write_adapt_coeffs().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
WAVE_FORMAT_UNKNOWN
WAVE_FORMAT_PCM
WAVE_FORMAT_MS_ADPCM
WAVE_FORMAT_IEEE_FLOAT
WAVE_FORMAT_VSELP
WAVE_FORMAT_IBM_CVSD
WAVE_FORMAT_ALAW
WAVE_FORMAT_MULAW
WAVE_FORMAT_OKI_ADPCM
WAVE_FORMAT_IMA_ADPCM
WAVE_FORMAT_MEDIASPACE_ADPCM
WAVE_FORMAT_SIERRA_ADPCM
WAVE_FORMAT_G723_ADPCM
WAVE_FORMAT_DIGISTD
WAVE_FORMAT_DIGIFIX
WAVE_FORMAT_DIALOGIC_OKI_ADPCM
WAVE_FORMAT_MEDIAVISION_ADPCM
WAVE_FORMAT_CU_CODEC
WAVE_FORMAT_YAMAHA_ADPCM
WAVE_FORMAT_SONARC
WAVE_FORMAT_DSPGROUP_TRUESPEECH
WAVE_FORMAT_ECHOSC1
WAVE_FORMAT_AUDIOFILE_AF36
WAVE_FORMAT_APTX
WAVE_FORMAT_AUDIOFILE_AF10
WAVE_FORMAT_PROSODY_1612
WAVE_FORMAT_LRC
WAVE_FORMAT_DOLBY_AC2
WAVE_FORMAT_GSM610
WAVE_FORMAT_MSNAUDIO
WAVE_FORMAT_ANTEX_ADPCME
WAVE_FORMAT_CONTROL_RES_VQLPC
WAVE_FORMAT_DIGIREAL
WAVE_FORMAT_DIGIADPCM
WAVE_FORMAT_CONTROL_RES_CR10
WAVE_FORMAT_NMS_VBXADPCM
WAVE_FORMAT_ROLAND_RDAC
WAVE_FORMAT_ECHOSC3
WAVE_FORMAT_ROCKWELL_ADPCM
WAVE_FORMAT_ROCKWELL_DIGITALK
WAVE_FORMAT_XEBEC
WAVE_FORMAT_G721_ADPCM
WAVE_FORMAT_G728_CELP
WAVE_FORMAT_MSG723
WAVE_FORMAT_MPEG
WAVE_FORMAT_RT24
WAVE_FORMAT_PAC
WAVE_FORMAT_MPEGLAYER3
WAVE_FORMAT_LUCENT_G723
WAVE_FORMAT_CIRRUS
WAVE_FORMAT_ESPCM
WAVE_FORMAT_VOXWARE
WAVE_FORMAT_CANOPUS_ATRAC
WAVE_FORMAT_G726_ADPCM
WAVE_FORMAT_G722_ADPCM
WAVE_FORMAT_DSAT
WAVE_FORMAT_DSAT_DISPLAY
WAVE_FORMAT_VOXWARE_BYTE_ALIGNED
WAVE_FORMAT_VOXWARE_AC8
WAVE_FORMAT_VOXWARE_AC10
WAVE_FORMAT_VOXWARE_AC16
WAVE_FORMAT_VOXWARE_AC20
WAVE_FORMAT_VOXWARE_RT24
WAVE_FORMAT_VOXWARE_RT29
WAVE_FORMAT_VOXWARE_RT29HW
WAVE_FORMAT_VOXWARE_VR12
WAVE_FORMAT_VOXWARE_VR18
WAVE_FORMAT_VOXWARE_TQ40
WAVE_FORMAT_SOFTSOUND
WAVE_FORMAT_VOXARE_TQ60
WAVE_FORMAT_MSRT24
WAVE_FORMAT_G729A
WAVE_FORMAT_MVI_MV12
WAVE_FORMAT_DF_G726
WAVE_FORMAT_DF_GSM610
WAVE_FORMAT_ONLIVE
WAVE_FORMAT_SBC24
WAVE_FORMAT_DOLBY_AC3_SPDIF
WAVE_FORMAT_ZYXEL_ADPCM
WAVE_FORMAT_PHILIPS_LPCBB
WAVE_FORMAT_PACKED
WAVE_FORMAT_RHETOREX_ADPCM
IBM_FORMAT_MULAW
IBM_FORMAT_ALAW
IBM_FORMAT_ADPCM
WAVE_FORMAT_VIVO_G723
WAVE_FORMAT_VIVO_SIREN
WAVE_FORMAT_DIGITAL_G723
WAVE_FORMAT_CREATIVE_ADPCM
WAVE_FORMAT_CREATIVE_FASTSPEECH8
WAVE_FORMAT_CREATIVE_FASTSPEECH10
WAVE_FORMAT_QUARTERDECK
WAVE_FORMAT_FM_TOWNS_SND
WAVE_FORMAT_BZV_DIGITAL
WAVE_FORMAT_VME_VMPCM
WAVE_FORMAT_OLIGSM
WAVE_FORMAT_OLIADPCM
WAVE_FORMAT_OLICELP
WAVE_FORMAT_OLISBC
WAVE_FORMAT_OLIOPR
WAVE_FORMAT_LH_CODEC
WAVE_FORMAT_NORRIS
WAVE_FORMAT_SOUNDSPACE_MUSICOMPRESS
WAVE_FORMAT_DVM
WAVE_FORMAT_INTERWAV_VSC112
WAVE_FORMAT_IPP_ITU_G_723_1
WAVE_FORMAT_EXTENSIBLE
Function Documentation
wavlike_msadpcm_write_adapt_coeffs()
void wavlike_msadpcm_write_adapt_coeffs (SF_PRIVATE * psf)
References AdaptCoeff1, AdaptCoeff2, BHW2, psf_binheader_writef(), and WAVLIKE_MSADPCM_ADAPT_COEFF_COUNT.
Referenced by w64_write_header(), and wav_write_fmt_chunk().
wavlike_format_str()
char const* wavlike_format_str (int k)
References WAV_FORMAT_DESC::ID, WAV_FORMAT_DESC::name, and wave_descs.
Referenced by wavlike_read_fmt_chunk().
wavlike_srate2blocksize()
int wavlike_srate2blocksize (int srate_chan_product)
Referenced by w64_open(), w64_write_header(), wav_open(), and wav_write_fmt_chunk().
wavlike_read_fmt_chunk()
int wavlike_read_fmt_chunk (SF_PRIVATE * psf, int fmtsize)
References append_snprintf(), ARRAY_LEN, G72x_ADPCM_WAV_FMT::auxblocksize, MIN_WAV_FMT::bitwidth, MS_ADPCM_WAV_FMT::bitwidth, EXTENSIBLE_WAV_FMT::bitwidth, BITWIDTH2BYTES, MIN_WAV_FMT::blockalign, IMA_ADPCM_WAV_FMT::blockalign, GSM610_WAV_FMT::blockalign, EXTENSIBLE_WAV_FMT::blockalign, sf_private_tag::blockwidth, MIN_WAV_FMT::bytespersec, IMA_ADPCM_WAV_FMT::bytespersec, G72x_ADPCM_WAV_FMT::bytespersec, GSM610_WAV_FMT::bytespersec, EXTENSIBLE_WAV_FMT::bytespersec, sf_private_tag::bytewidth, sf_private_tag::channel_map, channel_mask_bits, EXTENSIBLE_WAV_FMT::channelmask, MIN_WAV_FMT::channels, MS_ADPCM_WAV_FMT::channels, GSM610_WAV_FMT::channels, MS_ADPCM_WAV_FMT::coeff1, MS_ADPCM_WAV_FMT::coeff2, MS_ADPCM_WAV_FMT::coeffs, sf_private_tag::container_data, EXTENSIBLE_WAV_FMT::esf, EXT_SUBFORMAT::esf_field1, EXT_SUBFORMAT::esf_field2, EXT_SUBFORMAT::esf_field3, EXT_SUBFORMAT::esf_field4, WAV_FMT::ext, WAV_FMT_SIZE20::extrabytes, MS_ADPCM_WAV_FMT::extrabytes, IMA_ADPCM_WAV_FMT::extrabytes, G72x_ADPCM_WAV_FMT::extrabytes, GSM610_WAV_FMT::extrabytes, EXTENSIBLE_WAV_FMT::extrabytes, WAVLIKE_PRIVATE::fmt_is_broken, WAV_FMT::format, WAV_FMT::g72x, WAV_FMT::gsm610, chanmap_s::id, WAV_FMT::ima, memset(), WAV_FMT::min, WAV_FMT::msadpcm, MSGUID_SUBTYPE_ALAW, MSGUID_SUBTYPE_AMBISONIC_B_FORMAT_IEEE_FLOAT, MSGUID_SUBTYPE_AMBISONIC_B_FORMAT_PCM, MSGUID_SUBTYPE_IEEE_FLOAT, MSGUID_SUBTYPE_MS_ADPCM, MSGUID_SUBTYPE_MULAW, MSGUID_SUBTYPE_PCM, setup::name, NULL, MS_ADPCM_WAV_FMT::numcoeffs, psf_binheader_readf(), psf_log_printf(), MIN_WAV_FMT::samplerate, IMA_ADPCM_WAV_FMT::samplerate, GSM610_WAV_FMT::samplerate, EXTENSIBLE_WAV_FMT::samplerate, MS_ADPCM_WAV_FMT::samplesperblock, IMA_ADPCM_WAV_FMT::samplesperblock, GSM610_WAV_FMT::samplesperblock, sf_private_tag::sf, SFE_INTERNAL, SFE_MALLOC_FAILED, SFE_UNIMPLEMENTED, SFE_WAV_ADPCM_CHANNELS, SFE_WAV_ADPCM_NOT4BIT, SFE_WAV_ADPCM_SAMPLES, SFE_WAV_BAD_FMT, SFE_WAV_FMT_SHORT, SFE_WAV_GSM610_FORMAT, SFE_WAV_NMS_FORMAT, WAV_FMT::size20, u_bitwidth_to_subformat(), EXTENSIBLE_WAV_FMT::validbits, WAVLIKE_PRIVATE::wav_fmt, WAVE_FORMAT_ALAW, WAVE_FORMAT_EXTENSIBLE, WAVE_FORMAT_G721_ADPCM, WAVE_FORMAT_GSM610, WAVE_FORMAT_IEEE_FLOAT, WAVE_FORMAT_IMA_ADPCM, WAVE_FORMAT_IPP_ITU_G_723_1, WAVE_FORMAT_MS_ADPCM, WAVE_FORMAT_MULAW, WAVE_FORMAT_NMS_VBXADPCM, WAVE_FORMAT_PCM, WAVLIKE_PRIVATE::wavex_ambisonic, WAVLIKE_PRIVATE::wavex_channelmask, wavex_guid_equal(), and wavlike_format_str().
Referenced by rf64_read_header(), w64_read_header(), and wav_read_header().
wavlike_write_guid()
void wavlike_write_guid (SF_PRIVATE * psf, const EXT_SUBFORMAT * subformat)
References BHW2, BHW4, BHWv, BHWz, EXT_SUBFORMAT::esf_field1, EXT_SUBFORMAT::esf_field2, EXT_SUBFORMAT::esf_field3, EXT_SUBFORMAT::esf_field4, and psf_binheader_writef().
Referenced by rf64_write_fmt_chunk(), and wavex_write_fmt_chunk().
wavlike_analyze()
void wavlike_analyze (SF_PRIVATE * psf)
References audio_detect(), sf_private_tag::blockwidth, sf_private_tag::bytewidth, AUDIO_DETECT::channels, sf_private_tag::dataoffset, AUDIO_DETECT::endianness, sf_private_tag::is_pipe, psf_fread(), psf_fseek(), psf_log_printf(), and sf_private_tag::sf.
Referenced by rf64_read_header(), and wav_read_header().
wavlike_gen_channel_mask()
int wavlike_gen_channel_mask (const int * chan_map, int channels)
References ARRAY_LEN, channel_mask_bits, and NULL.
Referenced by rf64_command(), and wav_command().
wavlike_read_bext_chunk()
int wavlike_read_bext_chunk (SF_PRIVATE * psf, uint32_t chunksize)
References BHWj, BHWv, BHWz, sf_private_tag::broadcast_16k, broadcast_var_alloc(), sf_private_tag::error, NULL, psf_binheader_readf(), psf_log_printf(), SFE_MALLOC_FAILED, WAV_BEXT_MAX_CHUNK_SIZE, and WAV_BEXT_MIN_CHUNK_SIZE.
Referenced by rf64_read_header(), and wav_read_header().
wavlike_write_bext_chunk()
int wavlike_write_bext_chunk (SF_PRIVATE * psf)
References bext_MARKER, BHW2, BHW4, BHWm, BHWv, BHWz, sf_private_tag::broadcast_16k, NULL, psf_binheader_writef(), and WAV_BEXT_MIN_CHUNK_SIZE.
Referenced by rf64_write_header(), and wav_write_header().
wavlike_read_cart_chunk()
int wavlike_read_cart_chunk (SF_PRIVATE * psf, uint32_t chunksize)
References ARRAY_LEN, sf_private_tag::cart_16k, cart_var_alloc(), sf_private_tag::error, make_size_t(), NULL, psf_binheader_readf(), psf_log_printf(), SFE_MALLOC_FAILED, WAV_CART_MAX_CHUNK_SIZE, and WAV_CART_MIN_CHUNK_SIZE.
Referenced by rf64_read_header(), and wav_read_header().
wavlike_write_cart_chunk()
int wavlike_write_cart_chunk (SF_PRIVATE * psf)
References ARRAY_LEN, BHW4, BHWm, BHWv, BHWz, sf_private_tag::cart_16k, cart_MARKER, NULL, psf_binheader_writef(), and WAV_CART_MIN_CHUNK_SIZE.
Referenced by rf64_write_header(), and wav_write_header().
wavlike_subchunk_parse()
int wavlike_subchunk_parse (SF_PRIVATE * psf, int chunk, uint32_t length)
References adtl_MARKER, data_MARKER, DISP_MARKER, exif_MARKER, exif_subchunk_parse(), sf_private_tag::filelength, IARL_MARKER, IART_MARKER, IAUT_MARKER, ICMT_MARKER, ICOP_MARKER, ICRD_MARKER, IENG_MARKER, IGNR_MARKER, INAM_MARKER, INFO_MARKER, IPRD_MARKER, ISBJ_MARKER, ISFT_MARKER, ISRC_MARKER, ITRK_MARKER, labl_MARKER, ltxt_MARKER, note_MARKER, psf_binheader_readf(), psf_fseek(), psf_log_printf(), psf_store_string(), and SIGNED_SIZEOF.
Referenced by rf64_read_header(), and wav_read_header().
wavlike_write_strings()
void wavlike_write_strings (SF_PRIVATE * psf, int location)
References BHW4, BHWm, BHWs, sf_private_tag::data, STR_DATA::flags, sf_private_tag::header, IART_MARKER, ICMT_MARKER, ICOP_MARKER, ICRD_MARKER, IGNR_MARKER, INAM_MARKER, sf_private_tag::indx, INFO_MARKER, IPRD_MARKER, ISFT_MARKER, ITRK_MARKER, LIST_MARKER, STR_DATA::offset, psf_binheader_writef(), psf_location_string_count(), SF_MAX_STRINGS, sf_private_tag::storage, sf_private_tag::strings, and STR_DATA::type.
Referenced by rf64_write_header(), rf64_write_tailer(), wav_write_header(), and wav_write_tailer().
wavlike_read_peak_chunk()
int wavlike_read_peak_chunk (SF_PRIVATE * psf, size_t chunk_size)
References NULL, sf_private_tag::peak_info, peak_info_calloc(), PEAK_INFO::peaks, PEAK_POS::position, PRId64, psf_binheader_readf(), psf_log_printf(), sf_private_tag::sf, SFE_MALLOC_FAILED, SFE_WAV_BAD_PEAK, PEAK_INFO::timestamp, PEAK_POS::value, value, PEAK_INFO::version, and WAVLIKE_PEAK_CHUNK_SIZE.
Referenced by rf64_read_header(), and wav_read_header().
wavlike_write_peak_chunk()
void wavlike_write_peak_chunk (SF_PRIVATE * psf)
References BHW4, BHW8, BHWf, BHWm, NULL, sf_private_tag::peak_info, PEAK_MARKER, PEAK_INFO::peaks, PEAK_POS::position, psf_binheader_writef(), sf_private_tag::sf, PEAK_POS::value, and WAVLIKE_PEAK_CHUNK_SIZE.
Referenced by rf64_write_header(), wav_write_header(), and wav_write_tailer().
wavlike_write_custom_chunks()
void wavlike_write_custom_chunks (SF_PRIVATE * psf)
References BHW4, BHWm, BHWv, BHWz, WRITE_CHUNKS::chunks, WRITE_CHUNK::data, WRITE_CHUNK::len, WRITE_CHUNK::mark32, psf_binheader_writef(), WRITE_CHUNKS::used, and sf_private_tag::wchunks.
Referenced by rf64_write_header(), and wav_write_header().