Aurora Framework: matrixlib.h File Reference
matrixlib.h File Reference
Functions
void copy20ToPredictor (const int32_t *in, uint32_t stride, int32_t *out, int32_t numSamples)
void copy24ToPredictor (const int32_t *in, uint32_t stride, int32_t *out, int32_t numSamples)
void copyPredictorTo20 (const int32_t *in, int32_t *out, uint32_t stride, int32_t numSamples)
void copyPredictorTo24 (const int32_t *in, int32_t *out, uint32_t stride, int32_t numSamples)
void copyPredictorTo24Shift (const int32_t *in, uint16_t *shift, int32_t *out, uint32_t stride, int32_t numSamples, int32_t bytesShifted)
void copyPredictorTo32 (const int32_t *in, int32_t *out, uint32_t stride, int32_t numSamples)
void copyPredictorTo32Shift (const int32_t *in, uint16_t *shift, int32_t *out, uint32_t stride, int32_t numSamples, int32_t bytesShifted)
void mix16 (const int32_t *in, uint32_t stride, int32_t *u, int32_t *v, int32_t numSamples, int32_t mixbits, int32_t mixres)
void mix20 (const int32_t *in, uint32_t stride, int32_t *u, int32_t *v, int32_t numSamples, int32_t mixbits, int32_t mixres)
void mix24 (const int32_t *in, uint32_t stride, int32_t *u, int32_t *v, int32_t numSamples, int32_t mixbits, int32_t mixres, uint16_t *shiftUV, int32_t bytesShifted)
void mix32 (const int32_t *in, uint32_t stride, int32_t *u, int32_t *v, int32_t numSamples, int32_t mixbits, int32_t mixres, uint16_t *shiftUV, int32_t bytesShifted)
void unmix16 (const int32_t *u, int32_t *v, int32_t *out, uint32_t stride, int32_t numSamples, int32_t mixbits, int32_t mixres)
void unmix20 (const int32_t *u, int32_t *v, int32_t *out, uint32_t stride, int32_t numSamples, int32_t mixbits, int32_t mixres)
void unmix24 (const int32_t *u, int32_t *v, int32_t *out, uint32_t stride, int32_t numSamples, int32_t mixbits, int32_t mixres, uint16_t *shiftUV, int32_t bytesShifted)
void unmix32 (const int32_t *u, int32_t *v, int32_t *out, uint32_t stride, int32_t numSamples, int32_t mixbits, int32_t mixres, uint16_t *shiftUV, int32_t bytesShifted)
Function Documentation
mix16()
void mix16 (const int32_t * in, uint32_t stride, int32_t * u, int32_t * v, int32_t numSamples, int32_t mixbits, int32_t mixres)
Referenced by EncodeStereo(), and EncodeStereoFast().
unmix16()
void unmix16 (const int32_t * u, int32_t * v, int32_t * out, uint32_t stride, int32_t numSamples, int32_t mixbits, int32_t mixres)
References arith_shift_left().
Referenced by alac_decode().
mix20()
void mix20 (const int32_t * in, uint32_t stride, int32_t * u, int32_t * v, int32_t numSamples, int32_t mixbits, int32_t mixres)
Referenced by EncodeStereo(), and EncodeStereoFast().
unmix20()
void unmix20 (const int32_t * u, int32_t * v, int32_t * out, uint32_t stride, int32_t numSamples, int32_t mixbits, int32_t mixres)
References arith_shift_left().
Referenced by alac_decode().
mix24()
void mix24 (const int32_t * in, uint32_t stride, int32_t * u, int32_t * v, int32_t numSamples, int32_t mixbits, int32_t mixres, uint16_t * shiftUV, int32_t bytesShifted)
Referenced by EncodeStereo(), EncodeStereoEscape(), and EncodeStereoFast().
unmix24()
void unmix24 (const int32_t * u, int32_t * v, int32_t * out, uint32_t stride, int32_t numSamples, int32_t mixbits, int32_t mixres, uint16_t * shiftUV, int32_t bytesShifted)
References arith_shift_left().
Referenced by alac_decode().
mix32()
void mix32 (const int32_t * in, uint32_t stride, int32_t * u, int32_t * v, int32_t numSamples, int32_t mixbits, int32_t mixres, uint16_t * shiftUV, int32_t bytesShifted)
Referenced by EncodeStereo(), and EncodeStereoFast().
unmix32()
void unmix32 (const int32_t * u, int32_t * v, int32_t * out, uint32_t stride, int32_t numSamples, int32_t mixbits, int32_t mixres, uint16_t * shiftUV, int32_t bytesShifted)
References arith_shift_left().
Referenced by alac_decode().
copy20ToPredictor()
void copy20ToPredictor (const int32_t * in, uint32_t stride, int32_t * out, int32_t numSamples)
copy24ToPredictor()
void copy24ToPredictor (const int32_t * in, uint32_t stride, int32_t * out, int32_t numSamples)
copyPredictorTo24()
void copyPredictorTo24 (const int32_t * in, int32_t * out, uint32_t stride, int32_t numSamples)
Referenced by alac_decode().
copyPredictorTo24Shift()
void copyPredictorTo24Shift (const int32_t * in, uint16_t * shift, int32_t * out, uint32_t stride, int32_t numSamples, int32_t bytesShifted)
References arith_shift_left().
Referenced by alac_decode().
copyPredictorTo20()
void copyPredictorTo20 (const int32_t * in, int32_t * out, uint32_t stride, int32_t numSamples)
References arith_shift_left().
Referenced by alac_decode().
copyPredictorTo32()
void copyPredictorTo32 (const int32_t * in, int32_t * out, uint32_t stride, int32_t numSamples)
References arith_shift_left().
Referenced by alac_decode().
copyPredictorTo32Shift()
void copyPredictorTo32Shift (const int32_t * in, uint16_t * shift, int32_t * out, uint32_t stride, int32_t numSamples, int32_t bytesShifted)
References arith_shift_left().
Referenced by alac_decode().