Aurora Framework: Context.c File Reference
EGL/Context.c File Reference
Macros
#define setAttrib(a, v)
Functions
GLFWbool _glfwCreateContextEGL (_GLFWwindow *window, const _GLFWctxconfig *ctxconfig, const _GLFWfbconfig *fbconfig)
GLFWbool _glfwInitEGL (void)
void _glfwTerminateEGL (void)
static GLFWbool chooseEGLConfig (const _GLFWctxconfig *ctxconfig, const _GLFWfbconfig *desired, EGLConfig *result)
static void destroyContextEGL (_GLFWwindow *window)
static int extensionSupportedEGL (const char *extension)
static int getEGLConfigAttrib (EGLConfig config, int attrib)
static const char * getEGLErrorString (EGLint error)
static GLFWglproc getProcAddressEGL (const char *procname)
GLFWAPI EGLContext glfwGetEGLContext (GLFWwindow *handle)
GLFWAPI EGLDisplay glfwGetEGLDisplay (void)
GLFWAPI EGLSurface glfwGetEGLSurface (GLFWwindow *handle)
static void makeContextCurrentEGL (_GLFWwindow *window)
static void swapBuffersEGL (_GLFWwindow *window)
static void swapIntervalEGL (int interval)
Macro Definition Documentation
setAttrib
#define setAttrib (a, v)
Value:
{ \
    assert((size_t) (index + 1) < sizeof(attribs) / sizeof(attribs[0])); \
    attribs[index++] = a; \
    attribs[index++] = v; \
}
Referenced by _glfwCreateContextEGL().
Function Documentation
getEGLErrorString()
static const char* getEGLErrorString (EGLint error) static
References EGL_BAD_ACCESS, EGL_BAD_ALLOC, EGL_BAD_ATTRIBUTE, EGL_BAD_CONFIG, EGL_BAD_CONTEXT, EGL_BAD_CURRENT_SURFACE, EGL_BAD_DISPLAY, EGL_BAD_MATCH, EGL_BAD_NATIVE_PIXMAP, EGL_BAD_NATIVE_WINDOW, EGL_BAD_PARAMETER, EGL_BAD_SURFACE, EGL_CONTEXT_LOST, EGL_NOT_INITIALIZED, and EGL_SUCCESS.
Referenced by _glfwCreateContextEGL(), _glfwInitEGL(), and makeContextCurrentEGL().
getEGLConfigAttrib()
static int getEGLConfigAttrib (EGLConfig config, int attrib) static
References _glfw, eglGetConfigAttrib, and value.
Referenced by chooseEGLConfig().
chooseEGLConfig()
static GLFWbool chooseEGLConfig (const _GLFWctxconfig * ctxconfig, const _GLFWfbconfig * desired, EGLConfig * result) static
References _glfw, _glfwChooseFBConfig(), _glfwInputError(), _glfwIsVisualTransparentX11(), _GLFWfbconfig::alphaBits, _GLFWfbconfig::blueBits, _GLFWctxconfig::client, _GLFWfbconfig::depthBits, _GLFWfbconfig::doublebuffer, EGL_ALPHA_SIZE, EGL_BLUE_SIZE, EGL_COLOR_BUFFER_TYPE, EGL_DEPTH_SIZE, EGL_GREEN_SIZE, EGL_NATIVE_VISUAL_ID, EGL_OPENGL_BIT, EGL_OPENGL_ES2_BIT, EGL_OPENGL_ES_BIT, EGL_RED_SIZE, EGL_RENDERABLE_TYPE, EGL_RGB_BUFFER, EGL_SAMPLES, EGL_STENCIL_SIZE, EGL_SURFACE_TYPE, EGL_WINDOW_BIT, eglGetConfigs, getEGLConfigAttrib(), GLFW_API_UNAVAILABLE, GLFW_FALSE, GLFW_OPENGL_API, GLFW_OPENGL_ES_API, GLFW_TRUE, _GLFWfbconfig::greenBits, _GLFWfbconfig::handle, _GLFWctxconfig::major, NULL, _GLFWfbconfig::redBits, _GLFWfbconfig::samples, _GLFWfbconfig::stencilBits, and _GLFWfbconfig::transparent.
Referenced by _glfwCreateContextEGL().
makeContextCurrentEGL()
static void makeContextCurrentEGL (_GLFWwindow * window) static
References _glfw, _glfwInputError(), _glfwPlatformSetTls(), _GLFWwindow::context, _GLFWlibrary::contextSlot, EGL_NO_CONTEXT, EGL_NO_SURFACE, eglGetError, eglMakeCurrent, getEGLErrorString(), and GLFW_PLATFORM_ERROR.
Referenced by _glfwCreateContextEGL().
swapBuffersEGL()
static void swapBuffersEGL (_GLFWwindow * window) static
References _glfw, _glfwInputError(), _glfwPlatformGetTls(), _GLFWwindow::context, _GLFWlibrary::contextSlot, eglSwapBuffers, and GLFW_PLATFORM_ERROR.
Referenced by _glfwCreateContextEGL().
swapIntervalEGL()
static void swapIntervalEGL (int interval) static
References _glfw, and eglSwapInterval.
Referenced by _glfwCreateContextEGL().
extensionSupportedEGL()
static int extensionSupportedEGL (const char * extension) static
References _glfw, _glfwStringInExtensionString(), EGL_EXTENSIONS, eglQueryString, GLFW_FALSE, and GLFW_TRUE.
Referenced by _glfwCreateContextEGL(), and _glfwInitEGL().
getProcAddressEGL()
static GLFWglproc getProcAddressEGL (const char * procname) static
References _glfw, _glfw_dlsym, _glfwPlatformGetTls(), _GLFWcontext::client, _GLFWwindow::context, _GLFWlibrary::contextSlot, and eglGetProcAddress.
Referenced by _glfwCreateContextEGL().
destroyContextEGL()
static void destroyContextEGL (_GLFWwindow * window) static
References _glfw, _glfw_dlclose, _GLFWcontext::client, _GLFWwindow::context, EGL_NO_CONTEXT, EGL_NO_SURFACE, eglDestroyContext, eglDestroySurface, GLFW_OPENGL_API, and NULL.
Referenced by _glfwCreateContextEGL().
_glfwInitEGL()
GLFWbool _glfwInitEGL (void)
References _glfw, _glfw_dlopen, _glfw_dlsym, _GLFW_EGL_NATIVE_DISPLAY, _glfwInputError(), _glfwTerminateEGL(), EGL_NO_DISPLAY, eglGetDisplay, eglGetError, eglInitialize, extensionSupportedEGL(), getEGLErrorString(), GLFW_API_UNAVAILABLE, GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, _GLFWlibrary::handle, and NULL.
Referenced by _glfwPlatformCreateWindow().
_glfwTerminateEGL()
void _glfwTerminateEGL (void)
References _glfw, _glfw_dlclose, EGL_NO_DISPLAY, eglTerminate, _GLFWlibrary::handle, and NULL.
Referenced by _glfwInitEGL(), and _glfwPlatformTerminate().
_glfwCreateContextEGL()
GLFWbool _glfwCreateContextEGL (_GLFWwindow * window, const _GLFWctxconfig * ctxconfig, const _GLFWfbconfig * fbconfig)
References _glfw, _glfw_dlopen, _GLFW_EGL_NATIVE_WINDOW, _glfwInputError(), chooseEGLConfig(), _GLFWctxconfig::client, _GLFWcontext::client, _GLFWwindow::context, _GLFWctxconfig::debug, _GLFWcontext::destroy, destroyContextEGL(), EGL_CONTEXT_CLIENT_VERSION, EGL_CONTEXT_FLAGS_KHR, EGL_CONTEXT_MAJOR_VERSION_KHR, EGL_CONTEXT_MINOR_VERSION_KHR, EGL_CONTEXT_OPENGL_COMPATIBILITY_PROFILE_BIT_KHR, EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT_KHR, EGL_CONTEXT_OPENGL_DEBUG_BIT_KHR, EGL_CONTEXT_OPENGL_FORWARD_COMPATIBLE_BIT_KHR, EGL_CONTEXT_OPENGL_NO_ERROR_KHR, EGL_CONTEXT_OPENGL_PROFILE_MASK_KHR, EGL_CONTEXT_OPENGL_RESET_NOTIFICATION_STRATEGY_KHR, EGL_CONTEXT_OPENGL_ROBUST_ACCESS_BIT_KHR, EGL_CONTEXT_RELEASE_BEHAVIOR_FLUSH_KHR, EGL_CONTEXT_RELEASE_BEHAVIOR_KHR, EGL_CONTEXT_RELEASE_BEHAVIOR_NONE_KHR, EGL_GL_COLORSPACE_KHR, EGL_GL_COLORSPACE_SRGB_KHR, EGL_LOSE_CONTEXT_ON_RESET_KHR, EGL_NO_CONTEXT, EGL_NO_RESET_NOTIFICATION_KHR, EGL_NO_SURFACE, EGL_NONE, EGL_OPENGL_API, EGL_OPENGL_ES_API, eglBindAPI, eglCreateContext, eglCreateWindowSurface, eglGetError, _GLFWcontext::extensionSupported, extensionSupportedEGL(), _GLFWctxconfig::forward, getEGLErrorString(), _GLFWcontext::getProcAddress, getProcAddressEGL(), GLFW_API_UNAVAILABLE, GLFW_FALSE, GLFW_FORMAT_UNAVAILABLE, GLFW_LOSE_CONTEXT_ON_RESET, GLFW_NO_RESET_NOTIFICATION, GLFW_OPENGL_API, GLFW_OPENGL_COMPAT_PROFILE, GLFW_OPENGL_CORE_PROFILE, GLFW_OPENGL_ES_API, GLFW_PLATFORM_ERROR, GLFW_RELEASE_BEHAVIOR_FLUSH, GLFW_RELEASE_BEHAVIOR_NONE, GLFW_TRUE, GLFW_VERSION_UNAVAILABLE, _GLFWctxconfig::major, makeContextCurrentEGL(), _GLFWcontext::makeCurrent, _GLFWctxconfig::minor, _GLFWctxconfig::noerror, NULL, _GLFWctxconfig::profile, _GLFWctxconfig::release, _GLFWctxconfig::robustness, setAttrib, _GLFWctxconfig::share, _GLFWfbconfig::sRGB, _GLFWcontext::swapBuffers, swapBuffersEGL(), _GLFWcontext::swapInterval, and swapIntervalEGL().
Referenced by _glfwPlatformCreateWindow().
glfwGetEGLDisplay()
GLFWAPI EGLDisplay glfwGetEGLDisplay (void)
References _glfw, _GLFW_REQUIRE_INIT_OR_RETURN, and EGL_NO_DISPLAY.
glfwGetEGLContext()
GLFWAPI EGLContext glfwGetEGLContext (GLFWwindow * handle)
References _GLFW_REQUIRE_INIT_OR_RETURN, _glfwInputError(), _GLFWcontext::client, _GLFWwindow::context, EGL_NO_CONTEXT, GLFW_NO_API, GLFW_NO_WINDOW_CONTEXT, and NULL.
glfwGetEGLSurface()
GLFWAPI EGLSurface glfwGetEGLSurface (GLFWwindow * handle)
References _GLFW_REQUIRE_INIT_OR_RETURN, _glfwInputError(), _GLFWcontext::client, _GLFWwindow::context, EGL_NO_SURFACE, GLFW_NO_API, GLFW_NO_WINDOW_CONTEXT, and NULL.