Aurora Framework: dp_enc.c File Reference
dp_enc.c File Reference
Macros
#define ALWAYS_INLINE
#define LOOP_ALIGN
Functions
void copy_coefs (const int16_t *srcCoefs, int16_t *dstCoefs, int32_t numPairs)
void init_coefs (int16_t *coefs, uint32_t denshift, int32_t numPairs)
void pc_block (int32_t *in, int32_t *pc1, int32_t num, int16_t *coefs, int32_t numactive, uint32_t chanbits, uint32_t denshift)
static int32_t ALWAYS_INLINE sign_of_int (int32_t i)
Macro Definition Documentation
ALWAYS_INLINE
#define ALWAYS_INLINE
LOOP_ALIGN
#define LOOP_ALIGN
Referenced by pc_block().
Function Documentation
init_coefs()
void init_coefs (int16_t * coefs, uint32_t denshift, int32_t numPairs)
References AINIT, BINIT, and CINIT.
Referenced by alac_encoder_init().
copy_coefs()
void copy_coefs (const int16_t * srcCoefs, int16_t * dstCoefs, int32_t numPairs)
sign_of_int()
static int32_t ALWAYS_INLINE sign_of_int (int32_t i) inline static
Referenced by pc_block().
pc_block()
void pc_block (int32_t * in, int32_t * pc1, int32_t num, int16_t * coefs, int32_t numactive, uint32_t chanbits, uint32_t denshift)
References arith_shift_left(), LOOP_ALIGN, memcpy(), and sign_of_int().
Referenced by EncodeMono(), EncodeStereo(), and EncodeStereoFast().