Aurora Framework: common.h File Reference
audio/src/sndfile/common.h File Reference
Classes
struct ALAC_DECODER_INFO
struct AUDIO_DETECT
union BUF_UNION
struct PEAK_INFO
struct PEAK_POS
struct PSF_FILE
struct READ_CHUNK
struct READ_CHUNKS
struct SF_CHUNK_ITERATOR
struct sf_private_tag
struct STR_DATA
struct WRITE_CHUNK
struct WRITE_CHUNKS
Macros
#define ALWAYS_INLINE
#define ARRAY_LEN(x) ((int) (sizeof (x) / sizeof ((x) [0])))
#define BHW1(x) ((uint8_t) (x))
#define BHW2(x) ((uint16_t) (x))
#define BHW3(x) ((uint32_t) (x))
#define BHW4(x) ((uint32_t) (x))
#define BHW8(x) ((uint64_t) (x))
#define BHWd(x) ((double) (x))
#define BHWf(x) ((double) (x))
#define BHWh(x) ((void *) (x))
#define BHWj(x) ((size_t) (x))
#define BHWm(x) ((uint32_t) (x))
#define BHWo(x) ((size_t) (x))
#define BHWp(x) ((char *) (x))
#define BHWS(x) ((char *) (x))
#define BHWs(x) ((char *) (x))
#define BHWv(x) ((const void *) (x))
#define BHWz(x) ((size_t) (x))
#define BITWIDTH2BYTES(x) (((x) + 7) / 8)
#define COMPILE_TIME_ASSERT(e) (sizeof (struct { int : - !! (e) ; }))
#define NOT(x) (! (x))
#define PSF_SEEK_ERROR ((sf_count_t) -1)
#define SF_BUFFER_LEN (8192)
#define SF_CODEC(x) ((x) & SF_FORMAT_SUBMASK)
#define SF_CONTAINER(x) ((x) & SF_FORMAT_TYPEMASK)
#define SF_ENDIAN(x) ((x) & SF_FORMAT_ENDMASK)
#define SF_FILENAME_LEN (1024)
#define SF_MAX(a, b) ((a) > (b) ? (a) : (b))
#define SF_MAX_CHANNELS 1024
#define SF_MAX_STRINGS (32)
#define SF_MIN(a, b) ((a) < (b) ? (a) : (b))
#define SF_PARSELOG_LEN (2048)
#define SF_SYSERR_LEN (256)
#define SFM_MASK (SFM_READ | SFM_WRITE | SFM_RDWR)
#define SFM_UNMASK (~SFM_MASK)
#define SIGNED_SIZEOF(x) ((int) sizeof (x))
#define UNUSED(x) x
#define WARN_UNUSED
Typedefs
typedef struct sf_private_tag SF_PRIVATE
typedef int16_t sfwchar_t
Enumerations
enum {
SF_PEAK_START = 42, SF_PEAK_END = 43, SF_SCALE_MAX = 52, SF_SCALE_MIN = 53,
SF_STR_ALLOW_START = 0x0100, SF_STR_ALLOW_END = 0x0200, SF_STR_LOCATE_START = 0x0400, SF_STR_LOCATE_END = 0x0800,
SFD_TYPEMASK = 0x0FFFFFFF
}
enum {
SF_FORMAT_SPEEX = 0x5000000, SF_FORMAT_OGGFLAC = 0x5000001, SF_FORMAT_TXW = 0x4030000, SF_FORMAT_DWD = 0x4040000,
SF_FORMAT_REX = 0x40A0000, SF_FORMAT_REX2 = 0x40D0000, SF_FORMAT_KRZ = 0x40E0000, SF_FORMAT_WMA = 0x4100000,
SF_FORMAT_SHN = 0x4110000, SF_FORMAT_SVX_FIB = 0x1020, SF_FORMAT_SVX_EXP = 0x1021, SF_FORMAT_PCM_N = 0x1030
}
enum {
SFE_NO_ERROR = SF_ERR_NO_ERROR, SFE_BAD_OPEN_FORMAT = SF_ERR_UNRECOGNISED_FORMAT, SFE_SYSTEM = SF_ERR_SYSTEM, SFE_MALFORMED_FILE = SF_ERR_MALFORMED_FILE,
SFE_UNSUPPORTED_ENCODING = SF_ERR_UNSUPPORTED_ENCODING, SFE_ZERO_MAJOR_FORMAT, SFE_ZERO_MINOR_FORMAT, SFE_BAD_FILE,
SFE_BAD_FILE_READ, SFE_OPEN_FAILED, SFE_BAD_SNDFILE_PTR, SFE_BAD_SF_INFO_PTR,
SFE_BAD_SF_INCOMPLETE, SFE_BAD_FILE_PTR, SFE_BAD_INT_PTR, SFE_BAD_STAT_SIZE,
SFE_NO_TEMP_DIR, SFE_MALLOC_FAILED, SFE_UNIMPLEMENTED, SFE_BAD_READ_ALIGN,
SFE_BAD_WRITE_ALIGN, SFE_UNKNOWN_FORMAT, SFE_NOT_READMODE, SFE_NOT_WRITEMODE,
SFE_BAD_MODE_RW, SFE_BAD_SF_INFO, SFE_BAD_OFFSET, SFE_NO_EMBED_SUPPORT,
SFE_NO_EMBEDDED_RDWR, SFE_NO_PIPE_WRITE, SFE_INTERNAL, SFE_BAD_COMMAND_PARAM,
SFE_BAD_ENDIAN, SFE_CHANNEL_COUNT_ZERO, SFE_CHANNEL_COUNT, SFE_CHANNEL_COUNT_BAD,
SFE_BAD_VIRTUAL_IO, SFE_INTERLEAVE_MODE, SFE_INTERLEAVE_SEEK, SFE_INTERLEAVE_READ,
SFE_BAD_SEEK, SFE_NOT_SEEKABLE, SFE_AMBIGUOUS_SEEK, SFE_WRONG_SEEK,
SFE_SEEK_FAILED, SFE_BAD_OPEN_MODE, SFE_OPEN_PIPE_RDWR, SFE_RDWR_POSITION,
SFE_RDWR_BAD_HEADER, SFE_CMD_HAS_DATA, SFE_BAD_BROADCAST_INFO_SIZE, SFE_BAD_BROADCAST_INFO_TOO_BIG,
SFE_BAD_CART_INFO_SIZE, SFE_BAD_CART_INFO_TOO_BIG, SFE_STR_NO_SUPPORT, SFE_STR_NOT_WRITE,
SFE_STR_MAX_DATA, SFE_STR_MAX_COUNT, SFE_STR_BAD_TYPE, SFE_STR_NO_ADD_END,
SFE_STR_BAD_STRING, SFE_STR_WEIRD, SFE_WAV_NO_RIFF, SFE_WAV_NO_WAVE,
SFE_WAV_NO_FMT, SFE_WAV_BAD_FMT, SFE_WAV_FMT_SHORT, SFE_WAV_BAD_FACT,
SFE_WAV_BAD_PEAK, SFE_WAV_PEAK_B4_FMT, SFE_WAV_BAD_FORMAT, SFE_WAV_BAD_BLOCKALIGN,
SFE_WAV_NO_DATA, SFE_WAV_BAD_LIST, SFE_WAV_ADPCM_NOT4BIT, SFE_WAV_ADPCM_CHANNELS,
SFE_WAV_ADPCM_SAMPLES, SFE_WAV_GSM610_FORMAT, SFE_WAV_UNKNOWN_CHUNK, SFE_WAV_WVPK_DATA,
SFE_WAV_NMS_FORMAT, SFE_AIFF_NO_FORM, SFE_AIFF_AIFF_NO_FORM, SFE_AIFF_COMM_NO_FORM,
SFE_AIFF_SSND_NO_COMM, SFE_AIFF_UNKNOWN_CHUNK, SFE_AIFF_COMM_CHUNK_SIZE, SFE_AIFF_BAD_COMM_CHUNK,
SFE_AIFF_PEAK_B4_COMM, SFE_AIFF_BAD_PEAK, SFE_AIFF_NO_SSND, SFE_AIFF_NO_DATA,
SFE_AIFF_RW_SSND_NOT_LAST, SFE_AU_UNKNOWN_FORMAT, SFE_AU_NO_DOTSND, SFE_AU_EMBED_BAD_LEN,
SFE_RAW_READ_BAD_SPEC, SFE_RAW_BAD_BITWIDTH, SFE_RAW_BAD_FORMAT, SFE_PAF_NO_MARKER,
SFE_PAF_VERSION, SFE_PAF_UNKNOWN_FORMAT, SFE_PAF_SHORT_HEADER, SFE_PAF_BAD_CHANNELS,
SFE_SVX_NO_FORM, SFE_SVX_NO_BODY, SFE_SVX_NO_DATA, SFE_SVX_BAD_COMP,
SFE_SVX_BAD_NAME_LENGTH, SFE_NIST_BAD_HEADER, SFE_NIST_CRLF_CONVERISON, SFE_NIST_BAD_ENCODING,
SFE_VOC_NO_CREATIVE, SFE_VOC_BAD_FORMAT, SFE_VOC_BAD_VERSION, SFE_VOC_BAD_MARKER,
SFE_VOC_BAD_SECTIONS, SFE_VOC_MULTI_SAMPLERATE, SFE_VOC_MULTI_SECTION, SFE_VOC_MULTI_PARAM,
SFE_VOC_SECTION_COUNT, SFE_VOC_NO_PIPE, SFE_IRCAM_NO_MARKER, SFE_IRCAM_BAD_CHANNELS,
SFE_IRCAM_UNKNOWN_FORMAT, SFE_W64_64_BIT, SFE_W64_NO_RIFF, SFE_W64_NO_WAVE,
SFE_W64_NO_DATA, SFE_W64_ADPCM_NOT4BIT, SFE_W64_ADPCM_CHANNELS, SFE_W64_GSM610_FORMAT,
SFE_MAT4_BAD_NAME, SFE_MAT4_NO_SAMPLERATE, SFE_MAT5_BAD_ENDIAN, SFE_MAT5_NO_BLOCK,
SFE_MAT5_SAMPLE_RATE, SFE_PVF_NO_PVF1, SFE_PVF_BAD_HEADER, SFE_PVF_BAD_BITWIDTH,
SFE_DWVW_BAD_BITWIDTH, SFE_G72X_NOT_MONO, SFE_NMS_ADPCM_NOT_MONO, SFE_XI_BAD_HEADER,
SFE_XI_EXCESS_SAMPLES, SFE_XI_NO_PIPE, SFE_HTK_NO_PIPE, SFE_SDS_NOT_SDS,
SFE_SDS_BAD_BIT_WIDTH, SFE_SD2_FD_DISALLOWED, SFE_SD2_BAD_DATA_OFFSET, SFE_SD2_BAD_MAP_OFFSET,
SFE_SD2_BAD_DATA_LENGTH, SFE_SD2_BAD_MAP_LENGTH, SFE_SD2_BAD_RSRC, SFE_SD2_BAD_SAMPLE_SIZE,
SFE_FLAC_BAD_HEADER, SFE_FLAC_NEW_DECODER, SFE_FLAC_INIT_DECODER, SFE_FLAC_LOST_SYNC,
SFE_FLAC_BAD_SAMPLE_RATE, SFE_FLAC_CHANNEL_COUNT_CHANGED, SFE_FLAC_UNKOWN_ERROR, SFE_WVE_NOT_WVE,
SFE_WVE_NO_PIPE, SFE_VORBIS_ENCODER_BUG, SFE_RF64_NOT_RF64, SFE_RF64_PEAK_B4_FMT,
SFE_RF64_NO_DATA, SFE_BAD_CHUNK_PTR, SFE_UNKNOWN_CHUNK, SFE_BAD_CHUNK_FORMAT,
SFE_BAD_CHUNK_MARKER, SFE_BAD_CHUNK_DATA_PTR, SFE_ALAC_FAIL_TMPFILE, SFE_FILENAME_TOO_LONG,
SFE_NEGATIVE_RW_LEN, SFE_MAX_ERROR
}
enum { SFC_TEST_AIFF_ADD_INST_CHUNK = 0x2000, SFC_TEST_WAV_ADD_INFO_CHUNK = 0x2010 }
Functions
int aiff_ima_init (SF_PRIVATE *psf, int blockalign, int samplesperblock)
int aiff_open (SF_PRIVATE *psf)
void alac_get_desc_chunk_items (int subformat, uint32_t *fmt_flags, uint32_t *frames_per_packet)
int alac_init (SF_PRIVATE *psf, const ALAC_DECODER_INFO *info)
int alaw_init (SF_PRIVATE *psf)
void append_snprintf (char *dest, size_t maxlen, const char *fmt,...)
static int32_t ALWAYS_INLINE arith_shift_left (int32_t x, int shift)
static int32_t ALWAYS_INLINE arith_shift_right (int32_t x, int shift)
int au_open (SF_PRIVATE *psf)
int audio_detect (SF_PRIVATE *psf, AUDIO_DETECT *ad, const unsigned char *data, int datalen)
int avr_open (SF_PRIVATE *psf)
SF_BROADCAST_INFO_16K * broadcast_var_alloc (void)
int broadcast_var_get (SF_PRIVATE *psf, SF_BROADCAST_INFO *data, size_t datasize)
int broadcast_var_set (SF_PRIVATE *psf, const SF_BROADCAST_INFO *data, size_t datasize)
int caf_open (SF_PRIVATE *psf)
SF_CART_INFO_16K * cart_var_alloc (void)
int cart_var_get (SF_PRIVATE *psf, SF_CART_INFO *data, size_t datasize)
int cart_var_set (SF_PRIVATE *psf, const SF_CART_INFO *date, size_t datasize)
int dither_init (SF_PRIVATE *psf, int mode)
double double64_be_read (const unsigned char *cptr)
void double64_be_write (double in, unsigned char *out)
int double64_init (SF_PRIVATE *psf)
double double64_le_read (const unsigned char *cptr)
void double64_le_write (double in, unsigned char *out)
int dwd_open (SF_PRIVATE *psf)
int dwvw_init (SF_PRIVATE *psf, int bitwidth)
int flac_init (SF_PRIVATE *psf)
int flac_open (SF_PRIVATE *psf)
float float32_be_read (const unsigned char *cptr)
void float32_be_write (float in, unsigned char *out)
int float32_init (SF_PRIVATE *psf)
float float32_le_read (const unsigned char *cptr)
void float32_le_write (float in, unsigned char *out)
static int fourcc_to_marker (const SF_CHUNK_INFO *chunk_info)
int g72x_init (SF_PRIVATE *psf)
int gsm610_init (SF_PRIVATE *psf)
int htk_open (SF_PRIVATE *psf)
int id3_skip (SF_PRIVATE *psf)
int interleave_init (SF_PRIVATE *psf)
int ircam_open (SF_PRIVATE *psf)
int macos_guess_file_type (SF_PRIVATE *psf, const char *filename)
static size_t make_size_t (int x)
int mat4_open (SF_PRIVATE *psf)
int mat5_open (SF_PRIVATE *psf)
int mpc2k_open (SF_PRIVATE *psf)
int mpeg_open (SF_PRIVATE *psf)
int nist_open (SF_PRIVATE *psf)
int nms_adpcm_init (SF_PRIVATE *psf)
int ogg_open (SF_PRIVATE *psf)
int ogg_opus_open (SF_PRIVATE *psf)
int ogg_pcm_open (SF_PRIVATE *psf)
int ogg_speex_open (SF_PRIVATE *psf)
int ogg_vorbis_open (SF_PRIVATE *psf)
int paf_open (SF_PRIVATE *psf)
int pcm_init (SF_PRIVATE *psf)
static PEAK_INFO * peak_info_calloc (int channels)
void peak_update_double (SF_PRIVATE *psf, double *ptr, size_t items)
void peak_update_int (SF_PRIVATE *psf, int *ptr, size_t items)
void peak_update_short (SF_PRIVATE *psf, short *ptr, size_t items)
SF_PRIVATE * psf_allocate (void)
void psf_asciiheader_printf (SF_PRIVATE *psf, const char *format,...)
int psf_binheader_readf (SF_PRIVATE *psf, char const *format,...)
int psf_binheader_writef (SF_PRIVATE *psf, const char *format,...)
int psf_calc_max_all_channels (SF_PRIVATE *psf, double *peaks, int normalize)
double psf_calc_signal_max (SF_PRIVATE *psf, int normalize)
int psf_close_rsrc (SF_PRIVATE *psf)
SF_CUES * psf_cues_alloc (uint32_t cue_count)
SF_CUES * psf_cues_dup (const void *ptr)
void psf_d2i_array (const double *src, int *dest, int count, int normalize)
void psf_d2i_clip_array (const double *src, int *dest, int count, int normalize)
void psf_d2s_array (const double *src, short *dest, int count, int normalize)
void psf_d2s_clip_array (const double *src, short *dest, int count, int normalize)
sf_count_t psf_decode_frame_count (SF_PRIVATE *psf)
sf_count_t psf_default_seek (SF_PRIVATE *psf, int mode, sf_count_t samples_from_start)
void psf_f2i_array (const float *src, int *dest, int count, int normalize)
void psf_f2i_clip_array (const float *src, int *dest, int count, int normalize)
void psf_f2s_array (const float *src, short *dest, int count, int normalize)
void psf_f2s_clip_array (const float *src, short *dest, int count, int normalize)
int psf_fclose (SF_PRIVATE *psf)
sf_count_t psf_fgets (char *buffer, sf_count_t bufsize, SF_PRIVATE *psf)
int psf_file_valid (SF_PRIVATE *psf)
int psf_find_read_chunk_iterator (const READ_CHUNKS *pchk, const SF_CHUNK_ITERATOR *marker)
int psf_find_read_chunk_m32 (const READ_CHUNKS *pchk, uint32_t marker)
int psf_find_read_chunk_str (const READ_CHUNKS *pchk, const char *marker)
int psf_find_write_chunk (WRITE_CHUNKS *pchk, const char *marker)
int psf_fopen (SF_PRIVATE *psf)
sf_count_t psf_fread (void *ptr, sf_count_t bytes, sf_count_t count, SF_PRIVATE *psf)
sf_count_t psf_fseek (SF_PRIVATE *psf, sf_count_t offset, int whence)
void psf_fsync (SF_PRIVATE *psf)
sf_count_t psf_ftell (SF_PRIVATE *psf)
int psf_ftruncate (SF_PRIVATE *psf, sf_count_t len)
sf_count_t psf_fwrite (const void *ptr, sf_count_t bytes, sf_count_t count, SF_PRIVATE *psf)
void psf_generate_format_desc (SF_PRIVATE *psf)
SF_CHUNK_ITERATOR * psf_get_chunk_iterator (SF_PRIVATE *psf, const char *marker_str)
void psf_get_cues (SF_PRIVATE *psf, void *data, size_t datasize)
void psf_get_date_str (char *str, int maxlen)
sf_count_t psf_get_filelen (SF_PRIVATE *psf)
int psf_get_format_info (SF_FORMAT_INFO *data)
int psf_get_format_major (SF_FORMAT_INFO *data)
int psf_get_format_major_count (void)
int psf_get_format_simple (SF_FORMAT_INFO *data)
int psf_get_format_simple_count (void)
int psf_get_format_subtype (SF_FORMAT_INFO *data)
int psf_get_format_subtype_count (void)
int psf_get_max_all_channels (SF_PRIVATE *psf, double *peaks)
int psf_get_signal_max (SF_PRIVATE *psf, double *peak)
const char * psf_get_string (SF_PRIVATE *psf, int str_type)
void psf_hexdump (const void *ptr, int len)
void psf_init_files (SF_PRIVATE *psf)
SF_INSTRUMENT * psf_instrument_alloc (void)
int psf_is_pipe (SF_PRIVATE *psf)
static int psf_isprint (int ch)
int psf_location_string_count (const SF_PRIVATE *psf, int location)
void psf_log_printf (SF_PRIVATE *psf, const char *format,...)
void psf_log_SF_INFO (SF_PRIVATE *psf)
static void * psf_memdup (const void *src, size_t n)
void * psf_memset (void *s, int c, sf_count_t n)
SF_CHUNK_ITERATOR * psf_next_chunk_iterator (const READ_CHUNKS *pchk, SF_CHUNK_ITERATOR *iterator)
SNDFILE * psf_open_file (SF_PRIVATE *psf, SF_INFO *sfinfo)
int psf_open_rsrc (SF_PRIVATE *psf)
FILE * psf_open_tmpfile (char *fname, size_t fnamelen)
int32_t psf_rand_int32 (void)
void psf_sanitize_string (char *cptr, int len)
int psf_save_write_chunk (WRITE_CHUNKS *pchk, const SF_CHUNK_INFO *chunk_info)
void psf_set_file (SF_PRIVATE *psf, int fd)
int psf_set_stdio (SF_PRIVATE *psf)
int psf_set_string (SF_PRIVATE *psf, int str_type, const char *str)
int psf_store_read_chunk_str (READ_CHUNKS *pchk, const char *marker, sf_count_t offset, uint32_t len)
int psf_store_read_chunk_u32 (READ_CHUNKS *pchk, uint32_t marker, sf_count_t offset, uint32_t len)
int psf_store_string (SF_PRIVATE *psf, int str_type, const char *str)
static void psf_strlcat (char *dest, size_t n, const char *src)
static void psf_strlcpy (char *dest, size_t n, const char *src)
void psf_strlcpy_crlf (char *dest, const char *src, size_t destmax, size_t srcmax)
void psf_use_rsrc (SF_PRIVATE *psf, int on_off)
int pvf_open (SF_PRIVATE *psf)
int raw_open (SF_PRIVATE *psf)
int rf64_open (SF_PRIVATE *psf)
int rx2_open (SF_PRIVATE *psf)
int s_bitwidth_to_subformat (int bits)
int sd2_open (SF_PRIVATE *psf)
int sds_open (SF_PRIVATE *psf)
typedef SF_BROADCAST_INFO_VAR (16 *1024) SF_BROADCAST_INFO_16K
typedef SF_CART_INFO_VAR (16 *1024) SF_CART_INFO_16K
const char * str_of_endianness (int end)
const char * str_of_major_format (int format)
const char * str_of_minor_format (int format)
const char * str_of_open_mode (int mode)
int subformat_to_bytewidth (int format)
int svx_open (SF_PRIVATE *psf)
int txw_open (SF_PRIVATE *psf)
int u_bitwidth_to_subformat (int bits)
int ulaw_init (SF_PRIVATE *psf)
int voc_open (SF_PRIVATE *psf)
int vox_adpcm_init (SF_PRIVATE *psf)
int w64_open (SF_PRIVATE *psf)
int wav_open (SF_PRIVATE *psf)
int wavlike_ima_init (SF_PRIVATE *psf, int blockalign, int samplesperblock)
int wavlike_msadpcm_init (SF_PRIVATE *psf, int blockalign, int samplesperblock)
int wve_open (SF_PRIVATE *psf)
int xi_open (SF_PRIVATE *psf)
Macro Definition Documentation
UNUSED
#define UNUSED (x) x
WARN_UNUSED
#define WARN_UNUSED
SF_BUFFER_LEN
#define SF_BUFFER_LEN (8192)
Referenced by g72x_read_d(), g72x_read_f(), g72x_read_i(), g72x_write_d(), g72x_write_f(), g72x_write_i(), nms_adpcm_read_d(), nms_adpcm_read_f(), nms_adpcm_read_i(), nms_adpcm_write_d(), nms_adpcm_write_f(), and nms_adpcm_write_i().
SF_FILENAME_LEN
#define SF_FILENAME_LEN (1024)
SF_SYSERR_LEN
#define SF_SYSERR_LEN (256)
SF_MAX_STRINGS
#define SF_MAX_STRINGS (32)
Referenced by aiff_write_strings(), caf_write_strings(), psf_get_string(), psf_location_string_count(), psf_store_string(), and wavlike_write_strings().
SF_PARSELOG_LEN
#define SF_PARSELOG_LEN (2048)
PSF_SEEK_ERROR
#define PSF_SEEK_ERROR ((sf_count_t) -1)
Referenced by aiff_ima_seek(), alac_seek(), dpcm_seek(), dwvw_seek(), gsm610_seek(), msadpcm_seek(), nms_adpcm_seek(), paf24_seek(), psf_default_seek(), sds_seek(), sf_seek(), and wavlike_ima_seek().
BITWIDTH2BYTES
#define BITWIDTH2BYTES (x) (((x) + 7) / 8)
Referenced by aiff_read_comm_chunk(), and wavlike_read_fmt_chunk().
SIGNED_SIZEOF
#define SIGNED_SIZEOF (x) ((int) sizeof (x))
Referenced by aiff_read_comm_chunk(), aiff_read_header(), caf_read_header(), dwvw_encode_store_bits(), guess_file_type(), interleave_read_double(), interleave_read_float(), interleave_read_int(), interleave_read_short(), log_putchar(), mat4_read_header(), mat5_read_header(), parse_str_rsrc(), psf_get_format_info(), psf_get_format_major(), psf_get_format_simple(), psf_get_format_subtype(), rf64_read_header(), sf_command(), svx_read_header(), voc_read_header(), w64_read_header(), wav_read_header(), and wavlike_subchunk_parse().
ARRAY_LEN
#define ARRAY_LEN (x) ((int) (sizeof (x) / sizeof ((x) [0])))
Referenced by aiff_caf_find_channel_layout_tag(), aiff_caf_of_channel_layout_tag(), aiff_read_header(), alaw_read_alaw2d(), alaw_read_alaw2f(), alaw_read_alaw2i(), alaw_read_alaw2s(), alaw_write_d2alaw(), alaw_write_f2alaw(), alaw_write_i2alaw(), alaw_write_s2alaw(), clamp_ima_step_index(), dpcm_read_dles2d(), dpcm_read_dles2f(), dpcm_read_dles2i(), dpcm_read_dles2s(), dpcm_read_dsc2d(), dpcm_read_dsc2f(), dpcm_read_dsc2i(), dpcm_read_dsc2s(), dpcm_seek(), dpcm_write_d2dles(), dpcm_write_d2dsc(), dpcm_write_f2dles(), dpcm_write_f2dsc(), dpcm_write_i2dles(), dpcm_write_i2dsc(), dpcm_write_s2dles(), dpcm_write_s2dsc(), dwvw_read_d(), dwvw_read_f(), dwvw_read_s(), dwvw_write_d(), dwvw_write_f(), dwvw_write_s(), gsm610_read_d(), gsm610_read_f(), gsm610_read_i(), gsm610_write_d(), gsm610_write_f(), gsm610_write_i(), host_read_d2f(), host_read_d2i(), host_read_d2s(), host_read_f(), host_read_f2d(), host_read_f2i(), host_read_f2s(), host_write_d(), host_write_d2f(), host_write_f(), host_write_f2d(), host_write_i2d(), host_write_i2f(), host_write_s2d(), host_write_s2f(), ima_oki_adpcm_init(), ima_read_d(), ima_read_f(), ima_read_i(), ima_write_d(), ima_write_f(), ima_write_i(), msadpcm_read_d(), msadpcm_read_f(), msadpcm_read_i(), msadpcm_write_d(), msadpcm_write_f(), msadpcm_write_i(), paf24_read_d(), paf24_read_f(), paf24_read_s(), paf24_write_d(), paf24_write_f(), paf24_write_s(), pcm_read_bei2d(), pcm_read_bei2f(), pcm_read_bei2s(), pcm_read_bes2d(), pcm_read_bes2f(), pcm_read_bes2i(), pcm_read_lei2d(), pcm_read_lei2f(), pcm_read_lei2s(), pcm_read_les2d(), pcm_read_les2f(), pcm_read_les2i(), pcm_read_sc2d(), pcm_read_sc2f(), pcm_read_sc2i(), pcm_read_sc2s(), pcm_read_uc2d(), pcm_read_uc2f(), pcm_read_uc2i(), pcm_read_uc2s(), pcm_write_d2bei(), pcm_write_d2bes(), pcm_write_d2lei(), pcm_write_d2les(), pcm_write_d2sc(), pcm_write_d2uc(), pcm_write_f2bei(), pcm_write_f2bes(), pcm_write_f2lei(), pcm_write_f2les(), pcm_write_f2sc(), pcm_write_f2uc(), pcm_write_i2bei(), pcm_write_i2bes(), pcm_write_i2lei(), pcm_write_i2les(), pcm_write_i2sc(), pcm_write_i2uc(), pcm_write_s2bei(), pcm_write_s2bes(), pcm_write_s2lei(), pcm_write_s2les(), pcm_write_s2sc(), pcm_write_s2uc(), psf_calc_max_all_channels(), psf_calc_signal_max(), psf_decode_frame_count(), replace_read_d(), replace_read_d2f(), replace_read_d2i(), replace_read_d2s(), replace_read_f(), replace_read_f2d(), replace_read_f2i(), replace_read_f2s(), replace_write_d(), replace_write_d2f(), replace_write_f(), replace_write_f2d(), replace_write_i2d(), replace_write_i2f(), replace_write_s2d(), replace_write_s2f(), sd2_write_rsrc_fork(), sds_read_d(), sds_read_f(), sds_read_s(), sds_write_d(), sds_write_f(), sds_write_s(), ulaw_read_ulaw2d(), ulaw_read_ulaw2f(), ulaw_read_ulaw2i(), ulaw_read_ulaw2s(), ulaw_write_d2ulaw(), ulaw_write_f2ulaw(), ulaw_write_i2ulaw(), ulaw_write_s2ulaw(), vox_read_d(), vox_read_f(), vox_read_i(), vox_write_d(), vox_write_f(), vox_write_i(), wav_read_smpl_chunk(), wavlike_gen_channel_mask(), wavlike_read_cart_chunk(), wavlike_read_fmt_chunk(), and wavlike_write_cart_chunk().
NOT
#define NOT (x) (! (x))
Referenced by rf64_read_header(), rf64_write_header(), and sf_command().
SF_MAX
#define SF_MAX (a, b) ((a) > (b) ? (a) : (b))
Referenced by adpcm_decode(), psf_bump_header_allocation(), psf_get_signal_max(), and sf_command().
SF_MIN
#define SF_MIN (a, b) ((a) < (b) ? (a) : (b))
Referenced by adpcm_decode(), adpcm_encode(), aiff_get_chunk_data(), aiff_read_chanmap(), aiff_read_comm_chunk(), broadcast_var_get(), caf_get_chunk_data(), caf_read_chanmap(), cart_var_get(), parse_str_rsrc(), psf_get_cues(), rf64_get_chunk_data(), sf_command(), w64_read_header(), and wav_get_chunk_data().
COMPILE_TIME_ASSERT
#define COMPILE_TIME_ASSERT (e) (sizeof (struct { int : - !! (e) ; }))
SF_MAX_CHANNELS
#define SF_MAX_CHANNELS 1024
Referenced by aiff_read_comm_chunk(), aiff_read_header(), au_read_header(), caf_read_header(), double64_init(), ircam_read_header(), mat4_read_header(), paf_read_header(), rf64_read_header(), sf_format_check(), w64_read_header(), and wav_read_header().
SF_CONTAINER
#define SF_CONTAINER (x) ((x) & SF_FORMAT_TYPEMASK)
Referenced by aiff_open(), au_open(), avr_open(), caf_open(), format_from_extension(), gsm610_init(), gsm610_seek(), htk_open(), ima_reader_init(), ima_writer_init(), ircam_open(), mat4_open(), mat5_open(), mpc2k_open(), nist_open(), paf_open(), psf_get_format_info(), psf_open_file(), pvf_open(), rf64_command(), sd2_open(), sds_open(), sf_command(), sf_format_check(), sf_open_fd(), str_of_major_format(), svx_open(), validate_sfinfo(), voc_open(), w64_open(), wav_command(), wav_open(), wav_write_header(), wve_open(), and xi_open().
SF_CODEC
#define SF_CODEC (x) ((x) & SF_FORMAT_SUBMASK)
Referenced by aiff_open(), aiff_write_header(), alac_writer_init(), au_open(), au_write_header(), avr_write_header(), caf_open(), caf_write_header(), dither_init(), dither_write_double(), dither_write_float(), dither_write_int(), dither_write_short(), dpcm_seek(), g72x_init(), gen_coding_history(), htk_open(), ircam_open(), ircam_write_header(), mat4_open(), mat4_write_header(), mat5_open(), mat5_write_header(), nist_open(), nist_read_header(), nist_write_header(), nms_adpcm_init(), paf_open(), paf_write_header(), pcm_init(), psf_get_format_info(), psf_open_file(), pvf_open(), raw_open(), sd2_open(), sds_write_header(), sf_command(), sf_current_byterate(), sf_format_check(), str_of_minor_format(), validate_sfinfo(), voc_open(), voc_write_header(), w64_open(), w64_write_header(), wav_open(), wav_write_fmt_chunk(), wavex_write_fmt_chunk(), and xi_open().
SF_ENDIAN
#define SF_ENDIAN (x) ((x) & SF_FORMAT_ENDMASK)
Referenced by aiff_write_header(), au_open(), au_read_header(), caf_write_header(), ircam_open(), mat4_open(), mat5_open(), nist_open(), paf_open(), raw_open(), sf_format_check(), svx_open(), and wav_open().
BHW1
#define BHW1 (x) ((uint8_t) (x))
Referenced by mpc2k_write_header(), sd2_write_rsrc_fork(), sds_write_header(), svx_write_header(), voc_write_header(), and xi_write_header().
BHW2
#define BHW2 (x) ((uint16_t) (x))
Referenced by aiff_rewrite_header(), aiff_write_header(), avr_write_header(), caf_write_header(), mat5_write_header(), mpc2k_write_header(), rf64_write_fmt_chunk(), sd2_write_rsrc_fork(), sds_write_header(), svx_write_header(), voc_write_header(), w64_write_header(), wav_write_fmt_chunk(), wavex_write_fmt_chunk(), wavlike_msadpcm_write_adapt_coeffs(), wavlike_write_bext_chunk(), wavlike_write_guid(), wve_write_header(), and xi_write_header().
BHW3
#define BHW3 (x) ((uint32_t) (x))
Referenced by sds_write_header(), and voc_write_header().
BHW4
#define BHW4 (x) ((uint32_t) (x))
Referenced by aiff_rewrite_header(), aiff_write_header(), aiff_write_strings(), aiff_write_tailer(), au_write_header(), avr_write_header(), caf_write_header(), caf_write_strings(), htk_write_header(), ircam_write_header(), mat4_write_header(), mat5_write_header(), mpc2k_write_header(), paf_write_header(), rf64_write_fmt_chunk(), rf64_write_header(), sd2_write_rsrc_fork(), svx_write_header(), voc_write_header(), w64_write_header(), wav_write_fmt_chunk(), wav_write_header(), wavex_write_fmt_chunk(), wavlike_write_bext_chunk(), wavlike_write_cart_chunk(), wavlike_write_custom_chunks(), wavlike_write_guid(), wavlike_write_peak_chunk(), wavlike_write_strings(), wve_write_header(), and xi_write_header().
BHW8
#define BHW8 (x) ((uint64_t) (x))
Referenced by aiff_rewrite_header(), aiff_write_header(), aiff_write_tailer(), caf_write_header(), caf_write_strings(), mat4_write_header(), mat5_write_header(), mpc2k_write_header(), rf64_write_header(), svx_write_header(), w64_write_header(), wav_write_fmt_chunk(), wav_write_header(), wavex_write_fmt_chunk(), wavlike_write_peak_chunk(), and xi_write_header().
BHWm
#define BHWm (x) ((uint32_t) (x))
Referenced by aiff_rewrite_header(), aiff_write_header(), aiff_write_strings(), aiff_write_tailer(), au_write_header(), avr_write_header(), caf_write_header(), caf_write_strings(), ircam_write_header(), mat4_write_header(), paf_write_header(), rf64_write_header(), sd2_write_rsrc_fork(), svx_write_header(), wav_write_fmt_chunk(), wav_write_header(), wavex_write_fmt_chunk(), wavlike_write_bext_chunk(), wavlike_write_cart_chunk(), wavlike_write_custom_chunks(), wavlike_write_peak_chunk(), wavlike_write_strings(), and wve_write_header().
BHWS
#define BHWS (x) ((char *) (x))
Referenced by aiff_write_strings().
BHWf
#define BHWf (x) ((double) (x))
Referenced by aiff_rewrite_header(), aiff_write_header(), aiff_write_tailer(), caf_write_header(), ircam_write_header(), and wavlike_write_peak_chunk().
BHWd
#define BHWd (x) ((double) (x))
Referenced by mat4_write_header().
BHWh
#define BHWh (x) ((void *) (x))
Referenced by w64_write_header().
BHWj
#define BHWj (x) ((size_t) (x))
Referenced by wavlike_read_bext_chunk().
BHWp
#define BHWp (x) ((char *) (x))
Referenced by aiff_write_header(), and sd2_write_rsrc_fork().
BHWo
#define BHWo (x) ((size_t) (x))
Referenced by sd2_write_rsrc_fork().
BHWs
#define BHWs (x) ((char *) (x))
Referenced by svx_write_header(), and wavlike_write_strings().
BHWv
#define BHWv (x) ((const void *) (x))
Referenced by aiff_write_header(), aiff_write_strings(), caf_write_header(), caf_write_strings(), mat4_write_header(), mat5_write_header(), mpc2k_write_header(), sd2_write_rsrc_fork(), voc_write_header(), wavlike_read_bext_chunk(), wavlike_write_bext_chunk(), wavlike_write_cart_chunk(), wavlike_write_custom_chunks(), wavlike_write_guid(), and xi_write_header().
BHWz
#define BHWz (x) ((size_t) (x))
Referenced by aiff_write_header(), aiff_write_strings(), avr_write_header(), caf_write_header(), caf_write_strings(), caf_write_tailer(), ircam_write_header(), mat4_write_header(), mat5_write_header(), mpc2k_write_header(), nist_write_header(), paf_write_header(), rf64_write_header(), rf64_write_tailer(), sd2_write_rsrc_fork(), voc_write_header(), w64_write_header(), wav_write_header(), wav_write_tailer(), wavlike_read_bext_chunk(), wavlike_write_bext_chunk(), wavlike_write_cart_chunk(), wavlike_write_custom_chunks(), wavlike_write_guid(), and xi_write_header().
SFM_MASK
#define SFM_MASK (SFM_READ | SFM_WRITE | SFM_RDWR)
Referenced by sf_seek().
SFM_UNMASK
#define SFM_UNMASK (~SFM_MASK)
ALWAYS_INLINE
#define ALWAYS_INLINE
Typedef Documentation
sfwchar_t
typedef int16_t sfwchar_t
SF_PRIVATE
typedef struct sf_private_tag SF_PRIVATE
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SF_PEAK_START
SF_PEAK_END
SF_SCALE_MAX
SF_SCALE_MIN
SF_STR_ALLOW_START
SF_STR_ALLOW_END
SF_STR_LOCATE_START
SF_STR_LOCATE_END
SFD_TYPEMASK
anonymous enum
anonymous enum
Enumerator
SF_FORMAT_SPEEX
SF_FORMAT_OGGFLAC
SF_FORMAT_TXW
SF_FORMAT_DWD
SF_FORMAT_REX
SF_FORMAT_REX2
SF_FORMAT_KRZ
SF_FORMAT_WMA
SF_FORMAT_SHN
SF_FORMAT_SVX_FIB
SF_FORMAT_SVX_EXP
SF_FORMAT_PCM_N
anonymous enum
anonymous enum
Enumerator
SFE_NO_ERROR
SFE_BAD_OPEN_FORMAT
SFE_SYSTEM
SFE_MALFORMED_FILE
SFE_UNSUPPORTED_ENCODING
SFE_ZERO_MAJOR_FORMAT
SFE_ZERO_MINOR_FORMAT
SFE_BAD_FILE
SFE_BAD_FILE_READ
SFE_OPEN_FAILED
SFE_BAD_SNDFILE_PTR
SFE_BAD_SF_INFO_PTR
SFE_BAD_SF_INCOMPLETE
SFE_BAD_FILE_PTR
SFE_BAD_INT_PTR
SFE_BAD_STAT_SIZE
SFE_NO_TEMP_DIR
SFE_MALLOC_FAILED
SFE_UNIMPLEMENTED
SFE_BAD_READ_ALIGN
SFE_BAD_WRITE_ALIGN
SFE_UNKNOWN_FORMAT
SFE_NOT_READMODE
SFE_NOT_WRITEMODE
SFE_BAD_MODE_RW
SFE_BAD_SF_INFO
SFE_BAD_OFFSET
SFE_NO_EMBED_SUPPORT
SFE_NO_EMBEDDED_RDWR
SFE_NO_PIPE_WRITE
SFE_INTERNAL
SFE_BAD_COMMAND_PARAM
SFE_BAD_ENDIAN
SFE_CHANNEL_COUNT_ZERO
SFE_CHANNEL_COUNT
SFE_CHANNEL_COUNT_BAD
SFE_BAD_VIRTUAL_IO
SFE_INTERLEAVE_MODE
SFE_INTERLEAVE_SEEK
SFE_INTERLEAVE_READ
SFE_BAD_SEEK
SFE_NOT_SEEKABLE
SFE_AMBIGUOUS_SEEK
SFE_WRONG_SEEK
SFE_SEEK_FAILED
SFE_BAD_OPEN_MODE
SFE_OPEN_PIPE_RDWR
SFE_RDWR_POSITION
SFE_RDWR_BAD_HEADER
SFE_CMD_HAS_DATA
SFE_BAD_BROADCAST_INFO_SIZE
SFE_BAD_BROADCAST_INFO_TOO_BIG
SFE_BAD_CART_INFO_SIZE
SFE_BAD_CART_INFO_TOO_BIG
SFE_STR_NO_SUPPORT
SFE_STR_NOT_WRITE
SFE_STR_MAX_DATA
SFE_STR_MAX_COUNT
SFE_STR_BAD_TYPE
SFE_STR_NO_ADD_END
SFE_STR_BAD_STRING
SFE_STR_WEIRD
SFE_WAV_NO_RIFF
SFE_WAV_NO_WAVE
SFE_WAV_NO_FMT
SFE_WAV_BAD_FMT
SFE_WAV_FMT_SHORT
SFE_WAV_BAD_FACT
SFE_WAV_BAD_PEAK
SFE_WAV_PEAK_B4_FMT
SFE_WAV_BAD_FORMAT
SFE_WAV_BAD_BLOCKALIGN
SFE_WAV_NO_DATA
SFE_WAV_BAD_LIST
SFE_WAV_ADPCM_NOT4BIT
SFE_WAV_ADPCM_CHANNELS
SFE_WAV_ADPCM_SAMPLES
SFE_WAV_GSM610_FORMAT
SFE_WAV_UNKNOWN_CHUNK
SFE_WAV_WVPK_DATA
SFE_WAV_NMS_FORMAT
SFE_AIFF_NO_FORM
SFE_AIFF_AIFF_NO_FORM
SFE_AIFF_COMM_NO_FORM
SFE_AIFF_SSND_NO_COMM
SFE_AIFF_UNKNOWN_CHUNK
SFE_AIFF_COMM_CHUNK_SIZE
SFE_AIFF_BAD_COMM_CHUNK
SFE_AIFF_PEAK_B4_COMM
SFE_AIFF_BAD_PEAK
SFE_AIFF_NO_SSND
SFE_AIFF_NO_DATA
SFE_AIFF_RW_SSND_NOT_LAST
SFE_AU_UNKNOWN_FORMAT
SFE_AU_NO_DOTSND
SFE_AU_EMBED_BAD_LEN
SFE_RAW_READ_BAD_SPEC
SFE_RAW_BAD_BITWIDTH
SFE_RAW_BAD_FORMAT
SFE_PAF_NO_MARKER
SFE_PAF_VERSION
SFE_PAF_UNKNOWN_FORMAT
SFE_PAF_SHORT_HEADER
SFE_PAF_BAD_CHANNELS
SFE_SVX_NO_FORM
SFE_SVX_NO_BODY
SFE_SVX_NO_DATA
SFE_SVX_BAD_COMP
SFE_SVX_BAD_NAME_LENGTH
SFE_NIST_BAD_HEADER
SFE_NIST_CRLF_CONVERISON
SFE_NIST_BAD_ENCODING
SFE_VOC_NO_CREATIVE
SFE_VOC_BAD_FORMAT
SFE_VOC_BAD_VERSION
SFE_VOC_BAD_MARKER
SFE_VOC_BAD_SECTIONS
SFE_VOC_MULTI_SAMPLERATE
SFE_VOC_MULTI_SECTION
SFE_VOC_MULTI_PARAM
SFE_VOC_SECTION_COUNT
SFE_VOC_NO_PIPE
SFE_IRCAM_NO_MARKER
SFE_IRCAM_BAD_CHANNELS
SFE_IRCAM_UNKNOWN_FORMAT
SFE_W64_64_BIT
SFE_W64_NO_RIFF
SFE_W64_NO_WAVE
SFE_W64_NO_DATA
SFE_W64_ADPCM_NOT4BIT
SFE_W64_ADPCM_CHANNELS
SFE_W64_GSM610_FORMAT
SFE_MAT4_BAD_NAME
SFE_MAT4_NO_SAMPLERATE
SFE_MAT5_BAD_ENDIAN
SFE_MAT5_NO_BLOCK
SFE_MAT5_SAMPLE_RATE
SFE_PVF_NO_PVF1
SFE_PVF_BAD_HEADER
SFE_PVF_BAD_BITWIDTH
SFE_DWVW_BAD_BITWIDTH
SFE_G72X_NOT_MONO
SFE_NMS_ADPCM_NOT_MONO
SFE_XI_BAD_HEADER
SFE_XI_EXCESS_SAMPLES
SFE_XI_NO_PIPE
SFE_HTK_NO_PIPE
SFE_SDS_NOT_SDS
SFE_SDS_BAD_BIT_WIDTH
SFE_SD2_FD_DISALLOWED
SFE_SD2_BAD_DATA_OFFSET
SFE_SD2_BAD_MAP_OFFSET
SFE_SD2_BAD_DATA_LENGTH
SFE_SD2_BAD_MAP_LENGTH
SFE_SD2_BAD_RSRC
SFE_SD2_BAD_SAMPLE_SIZE
SFE_FLAC_BAD_HEADER
SFE_FLAC_NEW_DECODER
SFE_FLAC_INIT_DECODER
SFE_FLAC_LOST_SYNC
SFE_FLAC_BAD_SAMPLE_RATE
SFE_FLAC_CHANNEL_COUNT_CHANGED
SFE_FLAC_UNKOWN_ERROR
SFE_WVE_NOT_WVE
SFE_WVE_NO_PIPE
SFE_VORBIS_ENCODER_BUG
SFE_RF64_NOT_RF64
SFE_RF64_PEAK_B4_FMT
SFE_RF64_NO_DATA
SFE_BAD_CHUNK_PTR
SFE_UNKNOWN_CHUNK
SFE_BAD_CHUNK_FORMAT
SFE_BAD_CHUNK_MARKER
SFE_BAD_CHUNK_DATA_PTR
SFE_ALAC_FAIL_TMPFILE
SFE_FILENAME_TOO_LONG
SFE_NEGATIVE_RW_LEN
SFE_MAX_ERROR
anonymous enum
anonymous enum
Enumerator
SFC_TEST_AIFF_ADD_INST_CHUNK
SFC_TEST_WAV_ADD_INFO_CHUNK
Function Documentation
peak_info_calloc()
static PEAK_INFO* peak_info_calloc (int channels) inline static
Referenced by aiff_open(), aiff_read_header(), caf_open(), caf_read_header(), sf_command(), wav_open(), and wavlike_read_peak_chunk().
make_size_t()
static size_t make_size_t (int x) inline static
Referenced by aiff_read_comm_chunk(), aiff_read_header(), caf_read_header(), caf_read_strings(), mpc2k_read_header(), and wavlike_read_cart_chunk().
SF_BROADCAST_INFO_VAR()
typedef SF_BROADCAST_INFO_VAR (16 * 1024)
SF_CART_INFO_VAR()
typedef SF_CART_INFO_VAR (16 * 1024)
psf_memdup()
static void* psf_memdup (const void * src, size_t n) inline static
References memcpy().
Referenced by psf_save_write_chunk().
psf_isprint()
static int psf_isprint (int ch) inline static
Referenced by aiff_read_header(), psf_hexdump(), psf_sanitize_string(), read_rsrc_str(), svx_read_header(), and wav_read_header().
psf_allocate()
SF_PRIVATE* psf_allocate (void)
References sf_private_tag::header, INITIAL_HEADER_SIZE, sf_private_tag::len, NULL, and sf_private_tag::ptr.
Referenced by sf_open(), sf_open_fd(), and sf_open_virtual().
subformat_to_bytewidth()
int subformat_to_bytewidth (int format)
s_bitwidth_to_subformat()
int s_bitwidth_to_subformat (int bits)
Referenced by aiff_read_comm_chunk().
u_bitwidth_to_subformat()
int u_bitwidth_to_subformat (int bits)
Referenced by rf64_read_header(), w64_read_header(), wav_read_header(), and wavlike_read_fmt_chunk().
float32_be_read()
float float32_be_read (const unsigned char * cptr)
Referenced by psf_binheader_readf().
float32_le_read()
float float32_le_read (const unsigned char * cptr)
Referenced by psf_binheader_readf().
float32_be_write()
void float32_be_write (float in, unsigned char * out)
References memset().
Referenced by psf_binheader_writef().
float32_le_write()
void float32_le_write (float in, unsigned char * out)
References memset().
Referenced by psf_binheader_writef().
double64_be_read()
double double64_be_read (const unsigned char * cptr)
Referenced by caf_read_header(), and psf_binheader_readf().
double64_le_read()
double double64_le_read (const unsigned char * cptr)
Referenced by psf_binheader_readf().
double64_be_write()
void double64_be_write (double in, unsigned char * out)
References memset().
Referenced by caf_write_header(), and psf_binheader_writef().
double64_le_write()
void double64_le_write (double in, unsigned char * out)
References memset().
Referenced by psf_binheader_writef().
psf_log_printf()
void psf_log_printf (SF_PRIVATE * psf, const char * format, ...)
References log_putchar(), NULL, and width.
Referenced by aiff_ima_decode_block(), aiff_ima_encode_block(), aiff_open(), aiff_read_basc_chunk(), aiff_read_chanmap(), aiff_read_comm_chunk(), aiff_read_header(), alac_decode_block(), alac_init(), alac_kuki_read(), alac_pakt_read_decode(), alac_reader_init(), alac_writer_init(), au_read_header(), audio_detect(), avr_read_header(), caf_read_chanmap(), caf_read_header(), caf_read_strings(), codec_close(), decode_desc_chunk(), double64_get_capability(), double64_init(), dpcm_init(), dwvw_init(), exif_subchunk_parse(), flac_open(), float32_get_capability(), float32_init(), g72x_init(), g72x_seek(), gsm610_decode_block(), gsm610_encode_block(), gsm610_init(), gsm610_wav_decode_block(), gsm610_wav_encode_block(), guess_file_type(), header_read(), header_seek(), htk_read_header(), id3_skip(), ima_reader_init(), ima_writer_init(), interleave_init(), ircam_close(), ircam_read_header(), macos_guess_file_type(), mat4_read_header(), mat5_read_header(), mpc2k_read_header(), msadpcm_decode_block(), msadpcm_encode_block(), msadpcm_get_bpred(), nist_read_header(), nms_adpcm_decode_block(), nms_adpcm_encode_block(), nms_adpcm_init(), ogg_open(), ogg_opus_open(), ogg_pcm_open(), ogg_speex_open(), ogg_vorbis_open(), paf24_init(), paf24_read_block(), paf24_write_block(), paf_read_header(), parse_str_rsrc(), pcm_init(), psf_binheader_readf(), psf_binheader_writef(), psf_bump_header_allocation(), psf_fseek(), psf_g72x_decode_block(), psf_g72x_encode_block(), psf_log_SF_INFO(), psf_nms_adpcm_decode_block(), psf_nms_adpcm_encode_block(), psf_open_file(), psf_store_string(), pvf_read_header(), rf64_read_header(), rf64_write_header(), sd2_open(), sd2_parse_rsrc_fork(), sds_2byte_read(), sds_2byte_write(), sds_3byte_read(), sds_3byte_write(), sds_4byte_read(), sds_4byte_write(), sds_close(), sds_read_header(), sds_write_header(), sf_command(), sf_open(), svx_read_header(), try_resource_fork(), validate_psf(), voc_read_header(), vox_adpcm_init(), vox_read_block(), vox_write_block(), w64_read_header(), wav_read_acid_chunk(), wav_read_header(), wav_read_smpl_chunk(), wav_write_header(), wavlike_analyze(), wavlike_ima_decode_block(), wavlike_ima_encode_block(), wavlike_ima_init(), wavlike_msadpcm_init(), wavlike_read_bext_chunk(), wavlike_read_cart_chunk(), wavlike_read_fmt_chunk(), wavlike_read_peak_chunk(), wavlike_subchunk_parse(), wve_read_header(), and xi_read_header().
psf_log_SF_INFO()
void psf_log_SF_INFO (SF_PRIVATE * psf)
References psf_log_printf(), and sf_private_tag::sf.
Referenced by psf_open_file().
psf_rand_int32()
int32_t psf_rand_int32 (void)
References NULL, and value.
Referenced by psf_open_file(), and psf_open_tmpfile().
append_snprintf()
void append_snprintf (char * dest, size_t maxlen, const char * fmt, ...)
Referenced by wavlike_read_fmt_chunk().
psf_strlcpy_crlf()
void psf_strlcpy_crlf (char * dest, const char * src, size_t destmax, size_t srcmax)
Referenced by broadcast_var_set(), and cart_var_set().
psf_decode_frame_count()
sf_count_t psf_decode_frame_count (SF_PRIVATE * psf)
References ARRAY_LEN, sf_private_tag::datalength, sf_private_tag::dataoffset, BUF_UNION::ibuf, psf_fseek(), psf_is_pipe(), sf_private_tag::read_int, and sf_private_tag::sf.
Referenced by dwvw_init().
psf_binheader_writef()
int psf_binheader_writef (SF_PRIVATE * psf, const char * format, ...)
References double64_be_write(), double64_le_write(), sf_private_tag::error, float32_be_write(), float32_le_write(), sf_private_tag::header, header_put_be_3byte(), header_put_be_int(), header_put_be_short(), header_put_byte(), header_put_le_3byte(), header_put_le_int(), header_put_le_short(), sf_private_tag::indx, sf_private_tag::len, memcpy(), psf_bump_header_allocation(), psf_log_printf(), sf_private_tag::ptr, sf_private_tag::rwf_endian, and SFE_INTERNAL.
Referenced by aiff_rewrite_header(), aiff_write_header(), aiff_write_strings(), aiff_write_tailer(), au_write_header(), avr_write_header(), caf_write_header(), caf_write_strings(), caf_write_tailer(), htk_write_header(), ircam_write_header(), mat4_write_header(), mat5_write_header(), mpc2k_write_header(), nist_write_header(), paf_write_header(), rf64_write_fmt_chunk(), rf64_write_header(), rf64_write_tailer(), sd2_write_rsrc_fork(), sds_write_header(), svx_write_header(), voc_write_header(), w64_write_header(), wav_write_fmt_chunk(), wav_write_header(), wav_write_tailer(), wavex_write_fmt_chunk(), wavlike_msadpcm_write_adapt_coeffs(), wavlike_write_bext_chunk(), wavlike_write_cart_chunk(), wavlike_write_custom_chunks(), wavlike_write_guid(), wavlike_write_peak_chunk(), wavlike_write_strings(), wve_write_header(), and xi_write_header().
psf_asciiheader_printf()
void psf_asciiheader_printf (SF_PRIVATE * psf, const char * format, ...)
References sf_private_tag::header, sf_private_tag::indx, sf_private_tag::len, and sf_private_tag::ptr.
Referenced by nist_write_header().
psf_binheader_readf()
int psf_binheader_readf (SF_PRIVATE * psf, char const * format, ...)
References double64_be_read(), double64_le_read(), sf_private_tag::error, float32_be_read(), float32_le_read(), GET_BE_3BYTE, GET_BE_SHORT, GET_LE_3BYTE, GET_LE_SHORT, sf_private_tag::header, header_gets(), header_read(), header_seek(), sf_private_tag::indx, sf_private_tag::len, memset(), psf_bump_header_allocation(), psf_ftell(), psf_get_be32(), psf_get_be64(), psf_get_le32(), psf_get_le64(), psf_log_printf(), sf_private_tag::rwf_endian, and SFE_INTERNAL.
Referenced by aiff_read_basc_chunk(), aiff_read_chanmap(), aiff_read_comm_chunk(), aiff_read_header(), au_read_header(), avr_read_header(), caf_read_chanmap(), caf_read_header(), caf_read_strings(), exif_fill_and_sink(), exif_subchunk_parse(), guess_file_type(), htk_read_header(), id3_skip(), ircam_read_header(), mat4_read_header(), mat5_read_header(), mpc2k_read_header(), nist_read_header(), paf_read_header(), pvf_read_header(), rf64_read_header(), sds_read_header(), svx_read_header(), voc_read_header(), w64_read_header(), wav_read_acid_chunk(), wav_read_header(), wav_read_smpl_chunk(), wavlike_read_bext_chunk(), wavlike_read_cart_chunk(), wavlike_read_fmt_chunk(), wavlike_read_peak_chunk(), wavlike_subchunk_parse(), wve_read_header(), and xi_read_header().
peak_update_short()
void peak_update_short (SF_PRIVATE * psf, short * ptr, size_t items)
peak_update_int()
void peak_update_int (SF_PRIVATE * psf, int * ptr, size_t items)
peak_update_double()
void peak_update_double (SF_PRIVATE * psf, double * ptr, size_t items)
psf_get_format_simple_count()
int psf_get_format_simple_count (void)
References simple_formats.
Referenced by sf_command().
psf_get_format_simple()
int psf_get_format_simple (SF_FORMAT_INFO * data)
References memcpy(), SFE_BAD_COMMAND_PARAM, SIGNED_SIZEOF, and simple_formats.
Referenced by sf_command().
psf_get_format_info()
int psf_get_format_info (SF_FORMAT_INFO * data)
References major_formats, memcpy(), memset(), SF_CODEC, SF_CONTAINER, SFE_BAD_COMMAND_PARAM, SIGNED_SIZEOF, and subtype_formats.
Referenced by sf_command().
psf_get_format_major_count()
int psf_get_format_major_count (void)
References major_formats.
Referenced by sf_command().
psf_get_format_major()
int psf_get_format_major (SF_FORMAT_INFO * data)
References major_formats, memcpy(), SFE_BAD_COMMAND_PARAM, and SIGNED_SIZEOF.
Referenced by sf_command().
psf_get_format_subtype_count()
int psf_get_format_subtype_count (void)
References subtype_formats.
Referenced by sf_command().
psf_get_format_subtype()
int psf_get_format_subtype (SF_FORMAT_INFO * data)
References memcpy(), SFE_BAD_COMMAND_PARAM, SIGNED_SIZEOF, and subtype_formats.
Referenced by sf_command().
psf_generate_format_desc()
void psf_generate_format_desc (SF_PRIVATE * psf)
psf_calc_signal_max()
double psf_calc_signal_max (SF_PRIVATE * psf, int normalize)
References ARRAY_LEN, BUF_UNION::dbuf, sf_private_tag::error, NULL, sf_private_tag::read_double, sf_private_tag::sf, sf_command(), sf_read_double(), sf_seek(), SFE_NOT_SEEKABLE, and SFE_UNIMPLEMENTED.
Referenced by sf_command().
psf_calc_max_all_channels()
int psf_calc_max_all_channels (SF_PRIVATE * psf, double * peaks, int normalize)
References ARRAY_LEN, BUF_UNION::dbuf, sf_private_tag::error, memset(), NULL, sf_private_tag::read_double, sf_private_tag::sf, sf_command(), sf_read_double(), sf_seek(), SFE_NOT_SEEKABLE, and SFE_UNIMPLEMENTED.
Referenced by sf_command().
psf_get_signal_max()
int psf_get_signal_max (SF_PRIVATE * psf, double * peak)
References NULL, sf_private_tag::peak_info, PEAK_INFO::peaks, sf_private_tag::sf, SF_MAX, and PEAK_POS::value.
Referenced by sf_command().
psf_get_max_all_channels()
int psf_get_max_all_channels (SF_PRIVATE * psf, double * peaks)
References NULL, sf_private_tag::peak_info, PEAK_INFO::peaks, sf_private_tag::sf, and PEAK_POS::value.
Referenced by sf_command().
psf_get_string()
const char* psf_get_string (SF_PRIVATE * psf, int str_type)
References sf_private_tag::data, NULL, STR_DATA::offset, SF_MAX_STRINGS, sf_private_tag::storage, sf_private_tag::strings, and STR_DATA::type.
Referenced by caf_write_strings(), and sf_get_string().
psf_set_string()
int psf_set_string (SF_PRIVATE * psf, int str_type, const char * str)
References sf_private_tag::file, PSF_FILE::mode, psf_store_string(), and SFE_STR_NOT_WRITE.
Referenced by sf_set_string().
psf_store_string()
int psf_store_string (SF_PRIVATE * psf, int str_type, const char * str)
References sf_private_tag::data, sf_private_tag::file, STR_DATA::flags, sf_private_tag::flags, sf_private_tag::have_written, memcpy(), PSF_FILE::mode, NULL, STR_DATA::offset, psf_hexdump(), psf_log_printf(), SF_MAX_STRINGS, SF_STR_ALLOW_END, SF_STR_ALLOW_START, SF_STR_LOCATE_END, SF_STR_LOCATE_START, SFE_MALLOC_FAILED, SFE_STR_BAD_STRING, SFE_STR_BAD_TYPE, SFE_STR_MAX_COUNT, SFE_STR_NO_ADD_END, SFE_STR_NO_SUPPORT, SFE_STR_WEIRD, sf_private_tag::storage, sf_private_tag::storage_len, sf_private_tag::storage_used, sf_private_tag::strings, and STR_DATA::type.
Referenced by aiff_read_header(), caf_read_strings(), psf_set_string(), wavlike_subchunk_parse(), and xi_read_header().
psf_location_string_count()
int psf_location_string_count (const SF_PRIVATE * psf, int location)
References sf_private_tag::data, STR_DATA::flags, SF_MAX_STRINGS, sf_private_tag::strings, and STR_DATA::type.
Referenced by wavlike_write_strings().
psf_default_seek()
sf_count_t psf_default_seek (SF_PRIVATE * psf, int mode, sf_count_t samples_from_start)
macos_guess_file_type()
int macos_guess_file_type (SF_PRIVATE * psf, const char * filename)
References psf_log_printf().
psf_fopen()
int psf_fopen (SF_PRIVATE * psf)
References sf_private_tag::error, sf_private_tag::file, PSF_FILE::filedes, psf_log_syserr(), psf_open_fd(), and SFE_BAD_OPEN_MODE.
Referenced by sf_open().
psf_set_stdio()
int psf_set_stdio (SF_PRIVATE * psf)
References sf_private_tag::file, PSF_FILE::filedes, sf_private_tag::filelength, PSF_FILE::mode, SFE_BAD_OPEN_MODE, and SFE_OPEN_PIPE_RDWR.
Referenced by sf_open().
psf_file_valid()
int psf_file_valid (SF_PRIVATE * psf)
References sf_private_tag::file, and PSF_FILE::filedes.
Referenced by sd2_open().
psf_set_file()
void psf_set_file (SF_PRIVATE * psf, int fd)
References sf_private_tag::file, and PSF_FILE::filedes.
Referenced by sf_open_fd().
psf_init_files()
void psf_init_files (SF_PRIVATE * psf)
References sf_private_tag::file, PSF_FILE::filedes, sf_private_tag::rsrc, and PSF_FILE::savedes.
Referenced by sf_open(), sf_open_fd(), and sf_open_virtual().
psf_use_rsrc()
void psf_use_rsrc (SF_PRIVATE * psf, int on_off)
References sf_private_tag::file, PSF_FILE::filedes, sf_private_tag::rsrc, and PSF_FILE::savedes.
Referenced by sd2_open(), sd2_parse_rsrc_fork(), and sd2_write_rsrc_fork().
psf_open_file()
SNDFILE* psf_open_file (SF_PRIVATE * psf, SF_INFO * sfinfo)
References aiff_open(), au_open(), sf_private_tag::auto_header, avr_open(), sf_private_tag::buf, sf_private_tag::bytewidth, caf_open(), sf_private_tag::datalength, sf_private_tag::dataoffset, dwd_open(), sf_private_tag::error, sf_private_tag::file, sf_private_tag::filelength, sf_private_tag::fileoffset, flac_open(), sf_private_tag::float_int_mult, sf_private_tag::float_max, format_from_extension(), guess_file_type(), sf_private_tag::have_written, htk_open(), ircam_open(), sf_private_tag::is_pipe, sf_private_tag::last_op, sf_private_tag::Magick, mat4_open(), mat5_open(), memcpy(), memset(), PSF_FILE::mode, mpc2k_open(), nist_open(), sf_private_tag::norm_double, sf_private_tag::norm_float, NULL, ogg_open(), paf_open(), sf_private_tag::parselog, psf_close(), psf_default_seek(), psf_fseek(), psf_ftell(), psf_get_filelen(), psf_is_pipe(), psf_log_printf(), psf_log_SF_INFO(), psf_rand_int32(), pvf_open(), raw_open(), sf_private_tag::read_current, rf64_open(), sf_private_tag::rwf_endian, rx2_open(), save_header_info(), sd2_open(), sds_open(), sf_private_tag::seek, sf_private_tag::sf, SF_CODEC, SF_CONTAINER, sf_errno, sf_error_number(), sf_format_check(), SF_FORMAT_DWD, SF_FORMAT_REX2, SF_FORMAT_TXW, sf_parselog, sf_syserr, SFE_BAD_MODE_RW, SFE_BAD_OFFSET, SFE_BAD_OPEN_FORMAT, SFE_BAD_OPEN_MODE, SFE_BAD_SF_INFO, SFE_BAD_SF_INFO_PTR, SFE_INTERNAL, SFE_NO_EMBED_SUPPORT, SFE_NO_EMBEDDED_RDWR, SFE_RAW_BAD_FORMAT, SFE_SYSTEM, SFE_UNIMPLEMENTED, SFE_UNKNOWN_FORMAT, SFE_ZERO_MAJOR_FORMAT, SFE_ZERO_MINOR_FORMAT, SNDFILE_MAGICK, svx_open(), sf_private_tag::syserr, txw_open(), sf_private_tag::unique_id, validate_psf(), validate_sfinfo(), voc_open(), w64_open(), wav_open(), sf_private_tag::write_current, wve_open(), and xi_open().
Referenced by sf_open(), sf_open_fd(), and sf_open_virtual().
psf_fseek()
sf_count_t psf_fseek (SF_PRIVATE * psf, sf_count_t offset, int whence)
References sf_private_tag::file, PSF_FILE::filedes, sf_private_tag::fileoffset, sf_private_tag::is_pipe, sf_private_tag::pipeoffset, psf_log_printf(), psf_log_syserr(), sf_private_tag::vio, sf_private_tag::vio_user_data, and sf_private_tag::virtual_io.
Referenced by aiff_get_chunk_data(), aiff_ima_seek(), aiff_open(), aiff_read_header(), aiff_rewrite_header(), aiff_write_header(), aiff_write_tailer(), alac_decode_block(), alac_kuki_read(), alac_seek(), au_write_header(), avr_write_header(), caf_get_chunk_data(), caf_read_header(), caf_write_header(), caf_write_tailer(), dpcm_seek(), dwvw_seek(), gsm610_init(), gsm610_seek(), header_seek(), htk_write_header(), interleave_read_double(), interleave_read_float(), interleave_read_int(), interleave_read_short(), ircam_write_header(), mat4_write_header(), mat5_write_header(), mpc2k_write_header(), msadpcm_seek(), nist_read_header(), nist_write_header(), nms_adpcm_seek(), paf24_seek(), psf_decode_frame_count(), psf_default_seek(), psf_open_file(), pvf_write_header(), rf64_get_chunk_data(), rf64_read_header(), rf64_write_header(), rf64_write_tailer(), sd2_open(), sds_open(), sds_read_header(), sds_seek(), sds_write_header(), sf_command(), svx_open(), svx_read_header(), svx_write_header(), voc_close(), voc_write_header(), vox_adpcm_init(), w64_read_header(), w64_write_header(), wav_get_chunk_data(), wav_read_header(), wav_write_header(), wav_write_tailer(), wavlike_analyze(), wavlike_ima_seek(), wavlike_subchunk_parse(), wve_write_header(), xi_read_header(), and xi_write_header().
psf_fread()
sf_count_t psf_fread (void * ptr, sf_count_t bytes, sf_count_t count, SF_PRIVATE * psf)
References sf_private_tag::file, PSF_FILE::filedes, sf_private_tag::is_pipe, sf_private_tag::pipeoffset, psf_log_syserr(), SENSIBLE_SIZE, ssize_t, sf_private_tag::vio, sf_private_tag::vio_user_data, and sf_private_tag::virtual_io.
Referenced by aiff_get_chunk_data(), aiff_ima_decode_block(), aiff_rewrite_header(), alac_decode_block(), alac_kuki_read(), alaw_read_alaw2d(), alaw_read_alaw2f(), alaw_read_alaw2i(), alaw_read_alaw2s(), caf_get_chunk_data(), dpcm_read_dles2d(), dpcm_read_dles2f(), dpcm_read_dles2i(), dpcm_read_dles2s(), dpcm_read_dsc2d(), dpcm_read_dsc2f(), dpcm_read_dsc2i(), dpcm_read_dsc2s(), dwvw_decode_load_bits(), gsm610_decode_block(), gsm610_wav_decode_block(), header_gets(), header_read(), header_seek(), host_read_d(), host_read_d2f(), host_read_d2i(), host_read_d2s(), host_read_f(), host_read_f2d(), host_read_f2i(), host_read_f2s(), msadpcm_decode_block(), paf24_read_block(), pcm_read_bei2d(), pcm_read_bei2f(), pcm_read_bei2i(), pcm_read_bei2s(), pcm_read_bes2d(), pcm_read_bes2f(), pcm_read_bes2i(), pcm_read_bes2s(), pcm_read_bet2d(), pcm_read_bet2f(), pcm_read_bet2i(), pcm_read_bet2s(), pcm_read_lei2d(), pcm_read_lei2f(), pcm_read_lei2i(), pcm_read_lei2s(), pcm_read_les2d(), pcm_read_les2f(), pcm_read_les2i(), pcm_read_les2s(), pcm_read_let2d(), pcm_read_let2f(), pcm_read_let2i(), pcm_read_let2s(), pcm_read_sc2d(), pcm_read_sc2f(), pcm_read_sc2i(), pcm_read_sc2s(), pcm_read_uc2d(), pcm_read_uc2f(), pcm_read_uc2i(), pcm_read_uc2s(), psf_g72x_decode_block(), psf_nms_adpcm_decode_block(), replace_read_d(), replace_read_d2f(), replace_read_d2i(), replace_read_d2s(), replace_read_f(), replace_read_f2d(), replace_read_f2i(), replace_read_f2s(), rf64_get_chunk_data(), sd2_parse_rsrc_fork(), sds_2byte_read(), sds_3byte_read(), sds_4byte_read(), sds_read_header(), sf_read_raw(), ulaw_read_ulaw2d(), ulaw_read_ulaw2f(), ulaw_read_ulaw2i(), ulaw_read_ulaw2s(), vox_read_block(), wav_get_chunk_data(), wavlike_analyze(), and wavlike_ima_decode_block().
psf_fwrite()
sf_count_t psf_fwrite (const void * ptr, sf_count_t bytes, sf_count_t count, SF_PRIVATE * psf)
References sf_private_tag::file, PSF_FILE::filedes, sf_private_tag::is_pipe, sf_private_tag::pipeoffset, psf_log_syserr(), SENSIBLE_SIZE, ssize_t, sf_private_tag::vio, sf_private_tag::vio_user_data, and sf_private_tag::virtual_io.
Referenced by aiff_ima_encode_block(), aiff_rewrite_header(), aiff_write_header(), aiff_write_tailer(), alac_close(), alaw_write_d2alaw(), alaw_write_f2alaw(), alaw_write_i2alaw(), alaw_write_s2alaw(), au_write_header(), avr_write_header(), caf_write_header(), caf_write_tailer(), dpcm_write_d2dles(), dpcm_write_d2dsc(), dpcm_write_f2dles(), dpcm_write_f2dsc(), dpcm_write_i2dles(), dpcm_write_i2dsc(), dpcm_write_s2dles(), dpcm_write_s2dsc(), dwvw_close(), dwvw_encode_store_bits(), gsm610_encode_block(), gsm610_wav_encode_block(), host_write_d(), host_write_d2f(), host_write_f(), host_write_f2d(), host_write_i2d(), host_write_i2f(), host_write_s2d(), host_write_s2f(), htk_write_header(), ircam_write_header(), mat4_write_header(), mat5_write_header(), mpc2k_write_header(), msadpcm_encode_block(), nist_write_header(), paf24_write_block(), paf_write_header(), pcm_write_d2bei(), pcm_write_d2bes(), pcm_write_d2bet(), pcm_write_d2lei(), pcm_write_d2les(), pcm_write_d2let(), pcm_write_d2sc(), pcm_write_d2uc(), pcm_write_f2bei(), pcm_write_f2bes(), pcm_write_f2bet(), pcm_write_f2lei(), pcm_write_f2les(), pcm_write_f2let(), pcm_write_f2sc(), pcm_write_f2uc(), pcm_write_i2bei(), pcm_write_i2bes(), pcm_write_i2bet(), pcm_write_i2lei(), pcm_write_i2les(), pcm_write_i2let(), pcm_write_i2sc(), pcm_write_i2uc(), pcm_write_s2bei(), pcm_write_s2bes(), pcm_write_s2bet(), pcm_write_s2lei(), pcm_write_s2les(), pcm_write_s2let(), pcm_write_s2sc(), pcm_write_s2uc(), psf_g72x_encode_block(), psf_nms_adpcm_encode_block(), pvf_write_header(), replace_write_d(), replace_write_d2f(), replace_write_f(), replace_write_f2d(), replace_write_i2d(), replace_write_i2f(), replace_write_s2d(), replace_write_s2f(), rf64_write_header(), rf64_write_tailer(), sd2_write_rsrc_fork(), sds_2byte_write(), sds_3byte_write(), sds_4byte_write(), sds_write_header(), sf_write_raw(), svx_write_header(), ulaw_write_d2ulaw(), ulaw_write_f2ulaw(), ulaw_write_i2ulaw(), ulaw_write_s2ulaw(), voc_close(), voc_write_header(), vox_write_block(), w64_write_header(), wav_write_header(), wav_write_tailer(), wavlike_ima_encode_block(), wve_write_header(), and xi_write_header().
psf_fgets()
sf_count_t psf_fgets (char * buffer, sf_count_t bufsize, SF_PRIVATE * psf)
References sf_private_tag::file, PSF_FILE::filedes, and psf_log_syserr().
psf_ftell()
sf_count_t psf_ftell (SF_PRIVATE * psf)
References sf_private_tag::file, PSF_FILE::filedes, sf_private_tag::fileoffset, sf_private_tag::is_pipe, sf_private_tag::pipeoffset, psf_log_syserr(), sf_private_tag::vio, sf_private_tag::vio_user_data, and sf_private_tag::virtual_io.
Referenced by aiff_get_chunk_data(), aiff_read_header(), aiff_write_header(), au_read_header(), au_write_header(), avr_read_header(), avr_write_header(), caf_get_chunk_data(), caf_read_header(), caf_write_header(), htk_write_header(), ircam_write_header(), mat4_read_header(), mat4_write_header(), mat5_read_header(), mat5_write_header(), mpc2k_read_header(), mpc2k_write_header(), nist_write_header(), paf_write_header(), psf_binheader_readf(), psf_open_file(), pvf_read_header(), pvf_write_header(), rf64_get_chunk_data(), rf64_read_header(), rf64_write_header(), sds_write_header(), sf_open_fd(), svx_read_header(), svx_write_header(), voc_write_header(), vox_read_block(), w64_read_header(), w64_write_header(), wav_close(), wav_get_chunk_data(), wav_read_header(), wav_write_header(), wve_write_header(), xi_read_header(), and xi_write_header().
psf_get_filelen()
sf_count_t psf_get_filelen (SF_PRIVATE * psf)
References sf_private_tag::error, sf_private_tag::file, PSF_FILE::filedes, sf_private_tag::filelength, sf_private_tag::fileoffset, PSF_FILE::mode, psf_get_filelen_fd(), psf_log_syserr(), SFE_BAD_STAT_SIZE, sf_private_tag::vio, sf_private_tag::vio_user_data, and sf_private_tag::virtual_io.
Referenced by aiff_write_header(), au_write_header(), avr_write_header(), caf_write_header(), dpcm_init(), g72x_init(), gsm610_init(), htk_write_header(), ima_reader_init(), mat4_write_header(), mpc2k_write_header(), nist_write_header(), nms_adpcm_init(), paf24_init(), psf_open_file(), rf64_write_header(), sd2_parse_rsrc_fork(), svx_write_header(), voc_write_header(), w64_write_header(), wav_write_header(), and wve_write_header().
psf_fsync()
void psf_fsync (SF_PRIVATE * psf)
References sf_private_tag::file, PSF_FILE::filedes, PSF_FILE::mode, and NULL.
Referenced by sf_write_sync().
psf_is_pipe()
int psf_is_pipe (SF_PRIVATE * psf)
References sf_private_tag::file, PSF_FILE::filedes, psf_log_syserr(), S_ISFIFO, and sf_private_tag::virtual_io.
Referenced by psf_decode_frame_count(), psf_open_file(), and sf_open_fd().
psf_ftruncate()
int psf_ftruncate (SF_PRIVATE * psf, sf_count_t len)
References sf_private_tag::file, PSF_FILE::filedes, and psf_log_syserr().
Referenced by sf_command(), and wav_close().
psf_fclose()
int psf_fclose (SF_PRIVATE * psf)
References PSF_FILE::do_not_close_descriptor, sf_private_tag::file, PSF_FILE::filedes, psf_close_fd(), psf_log_syserr(), and sf_private_tag::virtual_io.
Referenced by psf_close().
psf_open_rsrc()
int psf_open_rsrc (SF_PRIVATE * psf)
References PSF_FILE::c, PSF_FILE::dir, sf_private_tag::error, sf_private_tag::file, PSF_FILE::filedes, PSF_FILE::mode, PSF_FILE::name, PSF_FILE::path, psf_close_fd(), psf_get_filelen_fd(), psf_log_syserr(), psf_open_fd(), sf_private_tag::rsrc, sf_private_tag::rsrclength, SFE_BAD_OPEN_MODE, and SFE_NO_ERROR.
Referenced by sd2_open(), and try_resource_fork().
psf_close_rsrc()
int psf_close_rsrc (SF_PRIVATE * psf)
References PSF_FILE::filedes, psf_close_fd(), and sf_private_tag::rsrc.
Referenced by psf_close(), and sd2_open().
aiff_open()
int aiff_open (SF_PRIVATE * psf)
References AIFC_IMA4_BLOCK_LEN, AIFC_IMA4_SAMPLES_PER_BLOCK, aiff_close(), aiff_command(), aiff_get_chunk_data(), aiff_get_chunk_size(), aiff_ima_init(), aiff_next_chunk_iterator(), aiff_read_header(), aiff_set_chunk(), aiff_write_header(), alaw_init(), sf_private_tag::command, sf_private_tag::container_close, sf_private_tag::container_data, sf_private_tag::datalength, sf_private_tag::dataoffset, double64_init(), dwvw_init(), sf_private_tag::file, sf_private_tag::filelength, sf_private_tag::flags, float32_init(), sf_private_tag::get_chunk_data, sf_private_tag::get_chunk_size, gsm610_init(), sf_private_tag::is_pipe, memset(), PSF_FILE::mode, sf_private_tag::next_chunk_iterator, NULL, COMM_CHUNK::numSampleFrames, pcm_init(), sf_private_tag::peak_info, peak_info_calloc(), PEAK_INFO::peak_loc, psf_fseek(), psf_log_printf(), COMM_CHUNK::sampleSize, sf_private_tag::set_chunk, sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SF_PEAK_START, SF_STR_ALLOW_END, SF_STR_ALLOW_START, SFE_BAD_OPEN_FORMAT, SFE_DWVW_BAD_BITWIDTH, SFE_MALLOC_FAILED, SFE_NO_PIPE_WRITE, SFE_UNIMPLEMENTED, sf_private_tag::strings, ulaw_init(), and sf_private_tag::write_header.
Referenced by psf_open_file().
au_open()
int au_open (SF_PRIVATE * psf)
References alaw_init(), au_close(), au_read_header(), au_write_header(), sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::container_close, double64_init(), sf_private_tag::endian, sf_private_tag::error, sf_private_tag::file, sf_private_tag::filelength, float32_init(), g72x_init(), PSF_FILE::mode, pcm_init(), sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SF_ENDIAN, SFE_BAD_OPEN_FORMAT, ulaw_init(), and sf_private_tag::write_header.
Referenced by psf_open_file().
avr_open()
int avr_open (SF_PRIVATE * psf)
References avr_close(), avr_read_header(), avr_write_header(), sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::container_close, sf_private_tag::endian, sf_private_tag::error, sf_private_tag::file, sf_private_tag::filelength, PSF_FILE::mode, pcm_init(), sf_private_tag::sf, SF_CONTAINER, SFE_BAD_OPEN_FORMAT, and sf_private_tag::write_header.
Referenced by psf_open_file().
htk_open()
int htk_open (SF_PRIVATE * psf)
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::container_close, sf_private_tag::endian, sf_private_tag::error, sf_private_tag::file, sf_private_tag::filelength, htk_close(), htk_read_header(), htk_write_header(), sf_private_tag::is_pipe, PSF_FILE::mode, pcm_init(), sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SFE_BAD_OPEN_FORMAT, SFE_HTK_NO_PIPE, and sf_private_tag::write_header.
Referenced by psf_open_file().
ircam_open()
int ircam_open (SF_PRIVATE * psf)
References alaw_init(), sf_private_tag::container_close, sf_private_tag::dataoffset, sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, float32_init(), ircam_close(), IRCAM_DATA_OFFSET, ircam_read_header(), ircam_write_header(), PSF_FILE::mode, pcm_init(), sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SF_ENDIAN, SFE_BAD_OPEN_FORMAT, SFE_NO_ERROR, ulaw_init(), and sf_private_tag::write_header.
Referenced by psf_open_file().
mat4_open()
int mat4_open (SF_PRIVATE * psf)
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::container_close, double64_init(), sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, float32_init(), sf_private_tag::is_pipe, mat4_close(), mat4_read_header(), mat4_write_header(), PSF_FILE::mode, pcm_init(), sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SF_ENDIAN, SFE_BAD_OPEN_FORMAT, SFE_NO_PIPE_WRITE, and sf_private_tag::write_header.
Referenced by psf_open_file().
mat5_open()
int mat5_open (SF_PRIVATE * psf)
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::container_close, double64_init(), sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, float32_init(), sf_private_tag::is_pipe, mat5_close(), mat5_read_header(), mat5_write_header(), PSF_FILE::mode, pcm_init(), sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SF_ENDIAN, SFE_BAD_OPEN_FORMAT, SFE_NO_PIPE_WRITE, and sf_private_tag::write_header.
Referenced by psf_open_file().
nist_open()
int nist_open (SF_PRIVATE * psf)
References alaw_init(), sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::container_close, sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, sf_private_tag::is_pipe, PSF_FILE::mode, nist_close(), nist_read_header(), nist_write_header(), pcm_init(), sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SF_ENDIAN, SFE_BAD_OPEN_FORMAT, SFE_NO_PIPE_WRITE, SFE_UNIMPLEMENTED, ulaw_init(), and sf_private_tag::write_header.
Referenced by psf_open_file().
paf_open()
int paf_open (SF_PRIVATE * psf)
References sf_private_tag::bytewidth, sf_private_tag::dataoffset, sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, PSF_FILE::mode, paf24_init(), PAF_HEADER_LENGTH, paf_read_header(), paf_write_header(), pcm_init(), sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SF_ENDIAN, SFE_BAD_OPEN_FORMAT, SFE_PAF_UNKNOWN_FORMAT, and sf_private_tag::write_header.
Referenced by psf_open_file().
pvf_open()
int pvf_open (SF_PRIVATE * psf)
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::container_close, sf_private_tag::endian, sf_private_tag::error, sf_private_tag::file, sf_private_tag::filelength, PSF_FILE::mode, pcm_init(), pvf_close(), pvf_read_header(), pvf_write_header(), sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SFE_BAD_OPEN_FORMAT, and sf_private_tag::write_header.
Referenced by psf_open_file().
raw_open()
int raw_open (SF_PRIVATE * psf)
References alaw_init(), sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::datalength, sf_private_tag::dataoffset, double64_init(), dwvw_init(), sf_private_tag::endian, sf_private_tag::filelength, float32_init(), gsm610_init(), nms_adpcm_init(), pcm_init(), sf_private_tag::sf, SF_CODEC, SF_ENDIAN, SFE_BAD_OPEN_FORMAT, SFE_NO_ERROR, ulaw_init(), and vox_adpcm_init().
Referenced by psf_open_file().
sd2_open()
int sd2_open (SF_PRIVATE * psf)
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::container_close, sf_private_tag::dataoffset, sf_private_tag::endian, sf_private_tag::file, PSF_FILE::mode, NULL, pcm_init(), psf_close_rsrc(), psf_file_valid(), psf_fseek(), psf_log_printf(), psf_open_rsrc(), psf_use_rsrc(), sf_private_tag::rsrc, sf_private_tag::rsrclength, sd2_close(), sd2_parse_rsrc_fork(), sd2_write_rsrc_fork(), sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SFE_BAD_OPEN_FORMAT, SFE_SD2_BAD_RSRC, SFE_UNIMPLEMENTED, and sf_private_tag::write_header.
Referenced by psf_open_file().
sds_open()
int sds_open (SF_PRIVATE * psf)
References sf_private_tag::blockwidth, sf_private_tag::byterate, sf_private_tag::codec_data, sf_private_tag::container_close, sf_private_tag::error, sf_private_tag::file, sf_private_tag::filelength, PSF_FILE::mode, psf_fseek(), sds_byterate(), sds_close(), SDS_DATA_OFFSET, sds_init(), sds_read_header(), sds_seek(), sds_write_header(), sf_private_tag::seek, sf_private_tag::sf, SF_CONTAINER, SFE_BAD_OPEN_FORMAT, SFE_MALLOC_FAILED, and sf_private_tag::write_header.
Referenced by psf_open_file().
svx_open()
int svx_open (SF_PRIVATE * psf)
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::container_close, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, sf_private_tag::is_pipe, PSF_FILE::mode, pcm_init(), psf_fseek(), sf_private_tag::sf, SF_CONTAINER, SF_ENDIAN, SFE_BAD_ENDIAN, SFE_BAD_OPEN_FORMAT, SFE_NO_PIPE_WRITE, svx_close(), svx_read_header(), svx_write_header(), and sf_private_tag::write_header.
Referenced by psf_open_file().
voc_open()
int voc_open (SF_PRIVATE * psf)
References alaw_init(), sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::container_close, sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, sf_private_tag::is_pipe, PSF_FILE::mode, pcm_init(), sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SFE_BAD_OPEN_FORMAT, SFE_UNIMPLEMENTED, SFE_VOC_NO_PIPE, ulaw_init(), voc_close(), voc_read_header(), voc_write_header(), and sf_private_tag::write_header.
Referenced by psf_open_file().
w64_open()
int w64_open (SF_PRIVATE * psf)
References alaw_init(), sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::container_close, sf_private_tag::container_data, sf_private_tag::datalength, double64_init(), sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, float32_init(), gsm610_init(), sf_private_tag::is_pipe, PSF_FILE::mode, NULL, pcm_init(), sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SFE_BAD_OPEN_FORMAT, SFE_MALLOC_FAILED, SFE_NO_PIPE_WRITE, SFE_UNIMPLEMENTED, ulaw_init(), w64_close(), w64_read_header(), w64_write_header(), wavlike_ima_init(), wavlike_msadpcm_init(), wavlike_srate2blocksize(), and sf_private_tag::write_header.
Referenced by psf_open_file().
wav_open()
int wav_open (SF_PRIVATE * psf)
References alaw_init(), sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::command, sf_private_tag::container_close, sf_private_tag::container_data, sf_private_tag::datalength, sf_private_tag::dataoffset, double64_init(), sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, sf_private_tag::flags, float32_init(), g72x_init(), sf_private_tag::get_chunk_data, sf_private_tag::get_chunk_size, gsm610_init(), sf_private_tag::is_pipe, PSF_FILE::mode, sf_private_tag::next_chunk_iterator, nms_adpcm_init(), NULL, pcm_init(), sf_private_tag::peak_info, peak_info_calloc(), PEAK_INFO::peak_loc, sf_private_tag::set_chunk, sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SF_ENDIAN, SF_PEAK_START, SF_STR_ALLOW_END, SF_STR_ALLOW_START, SFE_BAD_OPEN_FORMAT, SFE_MALLOC_FAILED, SFE_NO_PIPE_WRITE, SFE_UNIMPLEMENTED, sf_private_tag::strings, ulaw_init(), wav_close(), wav_command(), wav_get_chunk_data(), wav_get_chunk_size(), wav_next_chunk_iterator(), wav_read_header(), wav_set_chunk(), wav_write_header(), WAVLIKE_PRIVATE::wavex_ambisonic, wavlike_ima_init(), wavlike_msadpcm_init(), wavlike_srate2blocksize(), and sf_private_tag::write_header.
Referenced by psf_open_file().
xi_open()
int xi_open (SF_PRIVATE * psf)
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::codec_data, sf_private_tag::container_close, dpcm_init(), dpcm_seek(), sf_private_tag::endian, sf_private_tag::error, sf_private_tag::file, sf_private_tag::filelength, XI_PRIVATE::filename, sf_private_tag::is_pipe, memcpy(), memset(), PSF_FILE::mode, NULL, XI_PRIVATE::sample_flags, XI_PRIVATE::sample_name, sf_private_tag::seek, sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SFE_BAD_OPEN_FORMAT, SFE_MALLOC_FAILED, SFE_XI_NO_PIPE, XI_PRIVATE::software, sf_private_tag::write_header, xi_close(), xi_read_header(), and xi_write_header().
Referenced by psf_open_file().
flac_open()
int flac_open (SF_PRIVATE * psf)
References psf_log_printf(), and SFE_UNIMPLEMENTED.
Referenced by psf_open_file().
caf_open()
int caf_open (SF_PRIVATE * psf)
References CAF_PRIVATE::alac, alac_init(), alaw_init(), sf_private_tag::blockwidth, sf_private_tag::bytewidth, caf_close(), caf_command(), caf_get_chunk_data(), caf_get_chunk_size(), caf_next_chunk_iterator(), caf_read_header(), caf_set_chunk(), caf_write_header(), sf_private_tag::command, sf_private_tag::container_close, sf_private_tag::container_data, sf_private_tag::datalength, sf_private_tag::dataoffset, double64_init(), sf_private_tag::file, sf_private_tag::filelength, sf_private_tag::flags, float32_init(), sf_private_tag::get_chunk_data, sf_private_tag::get_chunk_size, sf_private_tag::is_pipe, PSF_FILE::mode, sf_private_tag::next_chunk_iterator, NULL, pcm_init(), sf_private_tag::peak_info, peak_info_calloc(), PEAK_INFO::peak_loc, sf_private_tag::set_chunk, sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SF_PEAK_START, SF_STR_ALLOW_END, SF_STR_ALLOW_START, SFE_BAD_OPEN_FORMAT, SFE_MALLOC_FAILED, SFE_NO_PIPE_WRITE, SFE_UNSUPPORTED_ENCODING, sf_private_tag::strings, ulaw_init(), and sf_private_tag::write_header.
Referenced by psf_open_file().
mpc2k_open()
int mpc2k_open (SF_PRIVATE * psf)
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::container_close, sf_private_tag::error, sf_private_tag::file, sf_private_tag::filelength, PSF_FILE::mode, mpc2k_close(), mpc2k_read_header(), mpc2k_write_header(), pcm_init(), sf_private_tag::sf, SF_CONTAINER, SFE_BAD_OPEN_FORMAT, and sf_private_tag::write_header.
Referenced by psf_open_file().
rf64_open()
int rf64_open (SF_PRIVATE * psf)
References alaw_init(), sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::command, sf_private_tag::container_close, sf_private_tag::container_data, double64_init(), sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, sf_private_tag::flags, float32_init(), sf_private_tag::get_chunk_data, sf_private_tag::get_chunk_size, sf_private_tag::is_pipe, PSF_FILE::mode, sf_private_tag::next_chunk_iterator, NULL, pcm_init(), rf64_close(), rf64_command(), rf64_get_chunk_data(), rf64_get_chunk_size(), rf64_next_chunk_iterator(), rf64_read_header(), rf64_set_chunk(), rf64_write_header(), sf_private_tag::set_chunk, sf_private_tag::sf, SF_STR_ALLOW_END, SF_STR_ALLOW_START, SFE_BAD_OPEN_FORMAT, SFE_MALLOC_FAILED, SFE_NO_PIPE_WRITE, SFE_UNIMPLEMENTED, sf_private_tag::strings, ulaw_init(), WAVLIKE_PRIVATE::wavex_ambisonic, and sf_private_tag::write_header.
Referenced by psf_open_file().
ogg_vorbis_open()
int ogg_vorbis_open (SF_PRIVATE * psf)
References psf_log_printf(), and SFE_UNIMPLEMENTED.
ogg_speex_open()
int ogg_speex_open (SF_PRIVATE * psf)
References psf_log_printf(), and SFE_UNIMPLEMENTED.
ogg_pcm_open()
int ogg_pcm_open (SF_PRIVATE * psf)
References psf_log_printf(), and SFE_UNIMPLEMENTED.
ogg_opus_open()
int ogg_opus_open (SF_PRIVATE * psf)
References psf_log_printf(), and SFE_UNIMPLEMENTED.
ogg_open()
int ogg_open (SF_PRIVATE * psf)
References psf_log_printf(), and SFE_UNIMPLEMENTED.
Referenced by psf_open_file().
mpeg_open()
int mpeg_open (SF_PRIVATE * psf)
rx2_open()
int rx2_open (SF_PRIVATE * psf)
References SFE_UNIMPLEMENTED.
Referenced by psf_open_file().
txw_open()
int txw_open (SF_PRIVATE * psf)
References SFE_UNIMPLEMENTED.
Referenced by psf_open_file().
wve_open()
int wve_open (SF_PRIVATE * psf)
References alaw_init(), sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::container_close, sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, sf_private_tag::is_pipe, PSF_FILE::mode, sf_private_tag::sf, SF_CONTAINER, SFE_BAD_OPEN_FORMAT, SFE_WVE_NO_PIPE, sf_private_tag::write_header, wve_close(), wve_read_header(), and wve_write_header().
Referenced by psf_open_file().
dwd_open()
int dwd_open (SF_PRIVATE * psf)
References SFE_UNIMPLEMENTED.
Referenced by psf_open_file().
pcm_init()
int pcm_init (SF_PRIVATE * psf)
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::data_endswap, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, PSF_FILE::mode, pcm_read_bei2d(), pcm_read_bei2f(), pcm_read_bei2i(), pcm_read_bei2s(), pcm_read_bes2d(), pcm_read_bes2f(), pcm_read_bes2i(), pcm_read_bes2s(), pcm_read_bet2d(), pcm_read_bet2f(), pcm_read_bet2i(), pcm_read_bet2s(), pcm_read_lei2d(), pcm_read_lei2f(), pcm_read_lei2i(), pcm_read_lei2s(), pcm_read_les2d(), pcm_read_les2f(), pcm_read_les2i(), pcm_read_les2s(), pcm_read_let2d(), pcm_read_let2f(), pcm_read_let2i(), pcm_read_let2s(), pcm_read_sc2d(), pcm_read_sc2f(), pcm_read_sc2i(), pcm_read_sc2s(), pcm_read_uc2d(), pcm_read_uc2f(), pcm_read_uc2i(), pcm_read_uc2s(), pcm_write_d2bei(), pcm_write_d2bes(), pcm_write_d2bet(), pcm_write_d2lei(), pcm_write_d2les(), pcm_write_d2let(), pcm_write_d2sc(), pcm_write_d2uc(), pcm_write_f2bei(), pcm_write_f2bes(), pcm_write_f2bet(), pcm_write_f2lei(), pcm_write_f2les(), pcm_write_f2let(), pcm_write_f2sc(), pcm_write_f2uc(), pcm_write_i2bei(), pcm_write_i2bes(), pcm_write_i2bet(), pcm_write_i2lei(), pcm_write_i2les(), pcm_write_i2let(), pcm_write_i2sc(), pcm_write_i2uc(), pcm_write_s2bei(), pcm_write_s2bes(), pcm_write_s2bet(), pcm_write_s2lei(), pcm_write_s2les(), pcm_write_s2let(), pcm_write_s2sc(), pcm_write_s2uc(), psf_log_printf(), sf_private_tag::read_double, sf_private_tag::read_float, sf_private_tag::read_int, sf_private_tag::read_short, sf_private_tag::sf, SF_CHARS_SIGNED, SF_CHARS_UNSIGNED, SF_CODEC, SFE_INTERNAL, SFE_UNIMPLEMENTED, sf_private_tag::write_double, sf_private_tag::write_float, sf_private_tag::write_int, and sf_private_tag::write_short.
Referenced by aiff_open(), au_open(), avr_open(), caf_open(), htk_open(), ircam_open(), mat4_open(), mat5_open(), mpc2k_open(), nist_open(), paf_open(), pvf_open(), raw_open(), rf64_open(), sd2_open(), svx_open(), voc_open(), w64_open(), and wav_open().
ulaw_init()
int ulaw_init (SF_PRIVATE * psf)
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::file, sf_private_tag::filelength, PSF_FILE::mode, sf_private_tag::read_double, sf_private_tag::read_float, sf_private_tag::read_int, sf_private_tag::read_short, sf_private_tag::sf, ulaw_read_ulaw2d(), ulaw_read_ulaw2f(), ulaw_read_ulaw2i(), ulaw_read_ulaw2s(), ulaw_write_d2ulaw(), ulaw_write_f2ulaw(), ulaw_write_i2ulaw(), ulaw_write_s2ulaw(), sf_private_tag::write_double, sf_private_tag::write_float, sf_private_tag::write_int, and sf_private_tag::write_short.
Referenced by aiff_open(), au_open(), caf_open(), ircam_open(), nist_open(), raw_open(), rf64_open(), voc_open(), w64_open(), and wav_open().
alaw_init()
int alaw_init (SF_PRIVATE * psf)
References alaw_read_alaw2d(), alaw_read_alaw2f(), alaw_read_alaw2i(), alaw_read_alaw2s(), alaw_write_d2alaw(), alaw_write_f2alaw(), alaw_write_i2alaw(), alaw_write_s2alaw(), sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::file, sf_private_tag::filelength, PSF_FILE::mode, sf_private_tag::read_double, sf_private_tag::read_float, sf_private_tag::read_int, sf_private_tag::read_short, sf_private_tag::sf, sf_private_tag::write_double, sf_private_tag::write_float, sf_private_tag::write_int, and sf_private_tag::write_short.
Referenced by aiff_open(), au_open(), caf_open(), ircam_open(), nist_open(), raw_open(), rf64_open(), voc_open(), w64_open(), wav_open(), and wve_open().
float32_init()
int float32_init (SF_PRIVATE * psf)
References sf_private_tag::blockwidth, sf_private_tag::data_endswap, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, float32_get_capability(), FLOAT_BROKEN_BE, FLOAT_BROKEN_LE, FLOAT_CAN_RW_BE, FLOAT_CAN_RW_LE, host_read_f(), host_read_f2d(), host_read_f2i(), host_read_f2s(), host_write_d2f(), host_write_f(), host_write_i2f(), host_write_s2f(), PSF_FILE::mode, psf_log_printf(), sf_private_tag::read_double, sf_private_tag::read_float, sf_private_tag::read_int, sf_private_tag::read_short, replace_read_f(), replace_read_f2d(), replace_read_f2i(), replace_read_f2s(), replace_write_d2f(), replace_write_f(), replace_write_i2f(), replace_write_s2f(), sf_private_tag::sf, SFE_INTERNAL, sf_private_tag::write_double, sf_private_tag::write_float, sf_private_tag::write_int, and sf_private_tag::write_short.
Referenced by aiff_open(), au_open(), caf_open(), ircam_open(), mat4_open(), mat5_open(), raw_open(), rf64_open(), sf_command(), w64_open(), and wav_open().
double64_init()
int double64_init (SF_PRIVATE * psf)
References sf_private_tag::blockwidth, sf_private_tag::data_endswap, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, double64_get_capability(), DOUBLE_BROKEN_BE, DOUBLE_BROKEN_LE, DOUBLE_CAN_RW_BE, DOUBLE_CAN_RW_LE, sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, host_read_d(), host_read_d2f(), host_read_d2i(), host_read_d2s(), host_write_d(), host_write_f2d(), host_write_i2d(), host_write_s2d(), PSF_FILE::mode, psf_log_printf(), sf_private_tag::read_double, sf_private_tag::read_float, sf_private_tag::read_int, sf_private_tag::read_short, replace_read_d(), replace_read_d2f(), replace_read_d2i(), replace_read_d2s(), replace_write_d(), replace_write_f2d(), replace_write_i2d(), replace_write_s2d(), sf_private_tag::sf, SF_MAX_CHANNELS, SFE_INTERNAL, sf_private_tag::write_double, sf_private_tag::write_float, sf_private_tag::write_int, and sf_private_tag::write_short.
Referenced by aiff_open(), au_open(), caf_open(), mat4_open(), mat5_open(), raw_open(), rf64_open(), sf_command(), w64_open(), and wav_open().
dwvw_init()
int dwvw_init (SF_PRIVATE * psf, int bitwidth)
References DWVW_PRIVATE::bit_width, sf_private_tag::byterate, sf_private_tag::codec_close, sf_private_tag::codec_data, dwvw_byterate(), dwvw_close(), dwvw_read_d(), dwvw_read_f(), dwvw_read_i(), dwvw_read_reset(), dwvw_read_s(), dwvw_seek(), dwvw_write_d(), dwvw_write_f(), dwvw_write_i(), dwvw_write_s(), sf_private_tag::file, PSF_FILE::mode, NULL, psf_decode_frame_count(), psf_log_printf(), sf_private_tag::read_double, sf_private_tag::read_float, sf_private_tag::read_int, sf_private_tag::read_short, sf_private_tag::seek, sf_private_tag::sf, SFE_BAD_MODE_RW, SFE_DWVW_BAD_BITWIDTH, SFE_INTERNAL, SFE_MALLOC_FAILED, sf_private_tag::write_double, sf_private_tag::write_float, sf_private_tag::write_int, and sf_private_tag::write_short.
Referenced by aiff_open(), and raw_open().
gsm610_init()
int gsm610_init (SF_PRIVATE * psf)
References gsm610_tag::blockcount, gsm610_tag::blocks, gsm610_tag::blocksize, sf_private_tag::codec_close, sf_private_tag::codec_data, sf_private_tag::datalength, sf_private_tag::dataoffset, gsm610_tag::decode_block, gsm610_tag::encode_block, sf_private_tag::file, sf_private_tag::filelength, GSM610_BLOCKSIZE, gsm610_close(), gsm610_decode_block(), gsm610_encode_block(), gsm610_read_d(), gsm610_read_f(), gsm610_read_i(), gsm610_read_s(), GSM610_SAMPLES, gsm610_seek(), gsm610_wav_decode_block(), gsm610_wav_encode_block(), gsm610_write_d(), gsm610_write_f(), gsm610_write_i(), gsm610_write_s(), gsm_create(), gsm610_tag::gsm_data, GSM_OPT_WAV49, gsm_option(), memset(), PSF_FILE::mode, NULL, psf_fseek(), psf_get_filelen(), psf_log_printf(), sf_private_tag::read_double, sf_private_tag::read_float, sf_private_tag::read_int, sf_private_tag::read_short, gsm610_tag::samplecount, gsm610_tag::samplesperblock, sf_private_tag::seek, sf_private_tag::sf, SF_CONTAINER, SFE_BAD_MODE_RW, SFE_INTERNAL, SFE_MALLOC_FAILED, WAVLIKE_GSM610_BLOCKSIZE, WAVLIKE_GSM610_SAMPLES, sf_private_tag::write_double, sf_private_tag::write_float, sf_private_tag::write_int, and sf_private_tag::write_short.
Referenced by aiff_open(), raw_open(), w64_open(), and wav_open().
nms_adpcm_init()
int nms_adpcm_init (SF_PRIVATE * psf)
References NMS_ADPCM_PRIVATE::block_curr, NMS_ADPCM_PRIVATE::blocks_total, sf_private_tag::codec_close, sf_private_tag::codec_data, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::file, sf_private_tag::filelength, PSF_FILE::mode, NMS16, NMS24, NMS32, nms_adpcm_close(), nms_adpcm_codec_init(), nms_adpcm_read_d(), nms_adpcm_read_f(), nms_adpcm_read_i(), nms_adpcm_read_s(), nms_adpcm_seek(), nms_adpcm_write_d(), nms_adpcm_write_f(), nms_adpcm_write_i(), nms_adpcm_write_s(), NMS_BLOCK_SHORTS_16, NMS_BLOCK_SHORTS_24, NMS_BLOCK_SHORTS_32, NMS_SAMPLES_PER_BLOCK, NULL, psf_get_filelen(), psf_log_printf(), sf_private_tag::read_double, sf_private_tag::read_float, sf_private_tag::read_int, sf_private_tag::read_short, NMS_ADPCM_PRIVATE::sample_curr, sf_private_tag::seek, sf_private_tag::sf, SF_CODEC, SFE_INTERNAL, SFE_MALLOC_FAILED, SFE_NMS_ADPCM_NOT_MONO, SFE_UNIMPLEMENTED, NMS_ADPCM_PRIVATE::shortsperblock, NMS_ADPCM_PRIVATE::state, NMS_ADPCM_PRIVATE::type, sf_private_tag::write_double, sf_private_tag::write_float, sf_private_tag::write_int, and sf_private_tag::write_short.
Referenced by raw_open(), and wav_open().
vox_adpcm_init()
int vox_adpcm_init (SF_PRIVATE * psf)
References codec_close(), sf_private_tag::codec_close, sf_private_tag::codec_data, sf_private_tag::file, sf_private_tag::filelength, ima_oki_adpcm_init(), IMA_OKI_ADPCM_TYPE_OKI, memset(), PSF_FILE::mode, NULL, psf_fseek(), psf_log_printf(), sf_private_tag::read_double, sf_private_tag::read_float, sf_private_tag::read_int, sf_private_tag::read_short, sf_private_tag::sf, SFE_BAD_MODE_RW, SFE_BAD_SEEK, SFE_CHANNEL_COUNT, SFE_MALLOC_FAILED, vox_read_d(), vox_read_f(), vox_read_i(), vox_read_s(), vox_write_d(), vox_write_f(), vox_write_i(), vox_write_s(), sf_private_tag::write_double, sf_private_tag::write_float, sf_private_tag::write_int, and sf_private_tag::write_short.
Referenced by raw_open().
flac_init()
int flac_init (SF_PRIVATE * psf)
g72x_init()
int g72x_init (SF_PRIVATE * psf)
References G72x_PRIVATE::block_curr, G72x_PRIVATE::blocks_total, G72x_PRIVATE::blocksize, G72x_PRIVATE::bytesperblock, sf_private_tag::codec_close, sf_private_tag::codec_data, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::file, sf_private_tag::filelength, G721_32_BITS_PER_SAMPLE, G721_32_BYTES_PER_BLOCK, G723_24_BITS_PER_SAMPLE, G723_24_BYTES_PER_BLOCK, G723_40_BITS_PER_SAMPLE, G723_40_BYTES_PER_BLOCK, g72x_close(), g72x_read_d(), g72x_read_f(), g72x_read_i(), g72x_read_s(), g72x_reader_init(), g72x_seek(), g72x_write_d(), g72x_write_f(), g72x_write_i(), g72x_write_s(), g72x_writer_init(), PSF_FILE::mode, NULL, G72x_PRIVATE::private, psf_g72x_decode_block(), psf_get_filelen(), psf_log_printf(), sf_private_tag::read_double, sf_private_tag::read_float, sf_private_tag::read_int, sf_private_tag::read_short, G72x_PRIVATE::sample_curr, G72x_PRIVATE::samplesperblock, sf_private_tag::seek, sf_private_tag::sf, SF_CODEC, SFE_G72X_NOT_MONO, SFE_INTERNAL, SFE_MALLOC_FAILED, SFE_UNIMPLEMENTED, sf_private_tag::write_double, sf_private_tag::write_float, sf_private_tag::write_int, and sf_private_tag::write_short.
Referenced by au_open(), and wav_open().
alac_init()
int alac_init (SF_PRIVATE * psf, const ALAC_DECODER_INFO * info)
References alac_byterate(), alac_close(), ALAC_MAX_FRAME_SIZE, alac_reader_init(), alac_writer_init(), sf_private_tag::byterate, sf_private_tag::codec_close, sf_private_tag::codec_data, sf_private_tag::file, PSF_FILE::mode, NULL, psf_log_printf(), sf_private_tag::sf, SFE_BAD_MODE_RW, SFE_INTERNAL, and SFE_MALLOC_FAILED.
dither_init()
int dither_init (SF_PRIVATE * psf, int mode)
References sf_private_tag::dither, dither_read_int(), dither_read_short(), dither_write_double(), dither_write_float(), dither_write_int(), dither_write_short(), mode(), NULL, sf_private_tag::read_dither, DITHER_DATA::read_double, sf_private_tag::read_double, DITHER_DATA::read_float, sf_private_tag::read_float, DITHER_DATA::read_int, sf_private_tag::read_int, DITHER_DATA::read_short, sf_private_tag::read_short, sf_private_tag::sf, SF_CODEC, SFE_MALLOC_FAILED, sf_private_tag::write_dither, DITHER_DATA::write_double, sf_private_tag::write_double, DITHER_DATA::write_float, sf_private_tag::write_float, DITHER_DATA::write_int, sf_private_tag::write_int, DITHER_DATA::write_short, and sf_private_tag::write_short.
Referenced by sf_command().
wavlike_ima_init()
int wavlike_ima_init (SF_PRIVATE * psf, int blockalign, int samplesperblock)
References sf_private_tag::codec_close, sf_private_tag::codec_data, sf_private_tag::file, ima_close(), ima_reader_init(), ima_writer_init(), PSF_FILE::mode, NULL, psf_log_printf(), IMA_ADPCM_PRIVATE_tag::samplesperblock, sf_private_tag::seek, SFE_BAD_MODE_RW, SFE_INTERNAL, and wavlike_ima_seek().
Referenced by w64_open(), and wav_open().
wavlike_msadpcm_init()
int wavlike_msadpcm_init (SF_PRIVATE * psf, int blockalign, int samplesperblock)
References MSADPCM_PRIVATE::block, MSADPCM_PRIVATE::blocks, MSADPCM_PRIVATE::blocksize, MSADPCM_PRIVATE::channels, sf_private_tag::codec_close, sf_private_tag::codec_data, sf_private_tag::datalength, MSADPCM_PRIVATE::dataremaining, MSADPCM_PRIVATE::dummydata, sf_private_tag::file, PSF_FILE::mode, msadpcm_close(), msadpcm_decode_block(), msadpcm_read_d(), msadpcm_read_f(), msadpcm_read_i(), msadpcm_read_s(), msadpcm_seek(), msadpcm_write_d(), msadpcm_write_f(), msadpcm_write_i(), msadpcm_write_s(), NULL, psf_log_printf(), sf_private_tag::read_double, sf_private_tag::read_float, sf_private_tag::read_int, sf_private_tag::read_short, MSADPCM_PRIVATE::samplecount, MSADPCM_PRIVATE::samples, MSADPCM_PRIVATE::samplesperblock, sf_private_tag::seek, sf_private_tag::sf, SFE_INTERNAL, SFE_MALLOC_FAILED, MSADPCM_PRIVATE::sync_error, sf_private_tag::write_double, sf_private_tag::write_float, sf_private_tag::write_int, and sf_private_tag::write_short.
Referenced by w64_open(), and wav_open().
aiff_ima_init()
int aiff_ima_init (SF_PRIVATE * psf, int blockalign, int samplesperblock)
References aiff_ima_seek(), sf_private_tag::codec_close, sf_private_tag::file, ima_close(), ima_reader_init(), ima_writer_init(), PSF_FILE::mode, IMA_ADPCM_PRIVATE_tag::samplesperblock, sf_private_tag::seek, and SFE_BAD_MODE_RW.
Referenced by aiff_open().
interleave_init()
int interleave_init (SF_PRIVATE * psf)
References sf_private_tag::bytewidth, INTERLEAVE_DATA::channel_len, sf_private_tag::file, sf_private_tag::interleave, interleave_read_double(), interleave_read_float(), interleave_read_int(), interleave_read_short(), interleave_seek(), PSF_FILE::mode, psf_log_printf(), INTERLEAVE_DATA::read_double, sf_private_tag::read_double, INTERLEAVE_DATA::read_float, sf_private_tag::read_float, INTERLEAVE_DATA::read_int, sf_private_tag::read_int, INTERLEAVE_DATA::read_short, sf_private_tag::read_short, sf_private_tag::seek, sf_private_tag::sf, SFE_INTERLEAVE_MODE, and SFE_MALLOC_FAILED.
psf_get_chunk_iterator()
SF_CHUNK_ITERATOR* psf_get_chunk_iterator (SF_PRIVATE * psf, const char * marker_str)
References SF_CHUNK_ITERATOR::current, SF_CHUNK_ITERATOR::hash, hash_of_str(), SF_CHUNK_ITERATOR::id, SF_CHUNK_ITERATOR::id_size, sf_private_tag::iterator, memcpy(), NULL, psf_find_read_chunk_str(), sf_private_tag::rchunks, SF_CHUNK_ITERATOR::sndfile, and READ_CHUNKS::used.
Referenced by alac_pakt_read_decode(), and sf_get_chunk_iterator().
psf_next_chunk_iterator()
SF_CHUNK_ITERATOR* psf_next_chunk_iterator (const READ_CHUNKS * pchk, SF_CHUNK_ITERATOR * iterator)
References READ_CHUNKS::chunks, SF_CHUNK_ITERATOR::current, READ_CHUNK::hash, SF_CHUNK_ITERATOR::hash, memset(), NULL, and READ_CHUNKS::used.
Referenced by aiff_next_chunk_iterator(), caf_next_chunk_iterator(), rf64_next_chunk_iterator(), and wav_next_chunk_iterator().
psf_store_read_chunk_u32()
int psf_store_read_chunk_u32 (READ_CHUNKS * pchk, uint32_t marker, sf_count_t offset, uint32_t len)
References READ_CHUNK::hash, READ_CHUNK::id, READ_CHUNK::id_size, READ_CHUNK::len, READ_CHUNK::mark32, memcpy(), memset(), READ_CHUNK::offset, and psf_store_read_chunk().
Referenced by aiff_read_header(), caf_read_header(), rf64_read_header(), and wav_read_header().
psf_store_read_chunk_str()
int psf_store_read_chunk_str (READ_CHUNKS * pchk, const char * marker, sf_count_t offset, uint32_t len)
References READ_CHUNK::hash, hash_of_str(), READ_CHUNK::id, READ_CHUNK::id_size, READ_CHUNK::len, READ_CHUNK::mark32, memcpy(), memset(), READ_CHUNK::offset, and psf_store_read_chunk().
psf_save_write_chunk()
int psf_save_write_chunk (WRITE_CHUNKS * pchk, const SF_CHUNK_INFO * chunk_info)
References WRITE_CHUNKS::chunks, WRITE_CHUNKS::count, WRITE_CHUNK::data, WRITE_CHUNK::hash, hash_of_str(), WRITE_CHUNK::len, WRITE_CHUNK::mark32, NULL, psf_memdup(), SFE_MALLOC_FAILED, SFE_NO_ERROR, and WRITE_CHUNKS::used.
Referenced by aiff_set_chunk(), alac_close(), caf_set_chunk(), rf64_set_chunk(), and wav_set_chunk().
psf_find_read_chunk_str()
int psf_find_read_chunk_str (const READ_CHUNKS * pchk, const char * marker)
References READ_CHUNKS::chunks, READ_CHUNK::hash, hash_of_str(), and READ_CHUNKS::used.
Referenced by psf_get_chunk_iterator().
psf_find_read_chunk_m32()
int psf_find_read_chunk_m32 (const READ_CHUNKS * pchk, uint32_t marker)
References READ_CHUNKS::chunks, READ_CHUNK::mark32, and READ_CHUNKS::used.
Referenced by aiff_rewrite_header().
psf_find_read_chunk_iterator()
int psf_find_read_chunk_iterator (const READ_CHUNKS * pchk, const SF_CHUNK_ITERATOR * marker)
References SF_CHUNK_ITERATOR::current, and READ_CHUNKS::used.
Referenced by aiff_get_chunk_data(), aiff_get_chunk_size(), caf_get_chunk_data(), caf_get_chunk_size(), rf64_get_chunk_data(), rf64_get_chunk_size(), wav_get_chunk_data(), and wav_get_chunk_size().
psf_find_write_chunk()
int psf_find_write_chunk (WRITE_CHUNKS * pchk, const char * marker)
fourcc_to_marker()
static int fourcc_to_marker (const SF_CHUNK_INFO * chunk_info) inline static
psf_strlcat()
static void psf_strlcat (char * dest, size_t n, const char * src) inline static
Referenced by broadcast_var_set(), and cart_var_set().
psf_strlcpy()
static void psf_strlcpy (char * dest, size_t n, const char * src) inline static
Referenced by aiff_read_header(), format_from_extension(), and gen_coding_history().
psf_memset()
void* psf_memset (void * s, int c, sf_count_t n)
References memset().
Referenced by sf_read_double(), sf_read_float(), sf_read_int(), sf_read_raw(), sf_read_short(), sf_readf_double(), sf_readf_float(), sf_readf_int(), and sf_readf_short().
psf_cues_dup()
SF_CUES* psf_cues_dup (const void * ptr)
References memcpy(), psf_cues_alloc(), and SF_CUES_VAR_SIZE.
Referenced by sf_command().
psf_cues_alloc()
SF_CUES* psf_cues_alloc (uint32_t cue_count)
Referenced by aiff_read_header(), psf_cues_dup(), and wav_read_header().
psf_get_cues()
void psf_get_cues (SF_PRIVATE * psf, void * data, size_t datasize)
References sf_private_tag::cues, memcpy(), SF_CUES_VAR_SIZE, and SF_MIN.
Referenced by sf_command().
psf_instrument_alloc()
SF_INSTRUMENT* psf_instrument_alloc (void)
References NULL.
Referenced by aiff_read_header(), sf_command(), wav_read_smpl_chunk(), and xi_read_header().
psf_sanitize_string()
void psf_sanitize_string (char * cptr, int len)
References psf_isprint().
Referenced by aiff_read_header().
psf_get_date_str()
void psf_get_date_str (char * str, int maxlen)
References memcpy(), and NULL.
Referenced by mat5_write_header().
broadcast_var_alloc()
SF_BROADCAST_INFO_16K* broadcast_var_alloc (void)
Referenced by broadcast_var_set(), and wavlike_read_bext_chunk().
broadcast_var_set()
int broadcast_var_set (SF_PRIVATE * psf, const SF_BROADCAST_INFO * data, size_t datasize)
References bc_min_size(), sf_private_tag::broadcast_16k, broadcast_var_alloc(), sf_private_tag::error, sf_private_tag::file, gen_coding_history(), memcpy(), PSF_FILE::mode, NULL, psf_strlcat(), psf_strlcpy_crlf(), sf_private_tag::sf, SFE_BAD_BROADCAST_INFO_SIZE, SFE_BAD_BROADCAST_INFO_TOO_BIG, and SFE_MALLOC_FAILED.
Referenced by sf_command().
broadcast_var_get()
int broadcast_var_get (SF_PRIVATE * psf, SF_BROADCAST_INFO * data, size_t datasize)
References bc_min_size(), sf_private_tag::broadcast_16k, memcpy(), NULL, and SF_MIN.
Referenced by sf_command().
cart_var_alloc()
SF_CART_INFO_16K* cart_var_alloc (void)
Referenced by cart_var_set(), and wavlike_read_cart_chunk().
cart_var_set()
int cart_var_set (SF_PRIVATE * psf, const SF_CART_INFO * date, size_t datasize)
References sf_private_tag::cart_16k, cart_min_size(), cart_var_alloc(), sf_private_tag::error, memcpy(), NULL, psf_strlcat(), psf_strlcpy_crlf(), SFE_BAD_CART_INFO_SIZE, SFE_BAD_CART_INFO_TOO_BIG, and SFE_MALLOC_FAILED.
Referenced by sf_command().
cart_var_get()
int cart_var_get (SF_PRIVATE * psf, SF_CART_INFO * data, size_t datasize)
References sf_private_tag::cart_16k, cart_min_size(), memcpy(), NULL, and SF_MIN.
Referenced by sf_command().
audio_detect()
int audio_detect (SF_PRIVATE * psf, AUDIO_DETECT * ad, const unsigned char * data, int datalen)
References VOTE::be_float, VOTE::be_int_24_32, sf_private_tag::buf, AUDIO_DETECT::endianness, VOTE::le_float, VOTE::le_int_24_32, NULL, sf_private_tag::parselog, psf_log_printf(), and vote_for_format().
Referenced by wavlike_analyze().
id3_skip()
int id3_skip (SF_PRIVATE * psf)
References sf_private_tag::filelength, sf_private_tag::fileoffset, memset(), psf_binheader_readf(), and psf_log_printf().
Referenced by guess_file_type().
alac_get_desc_chunk_items()
void alac_get_desc_chunk_items (int subformat, uint32_t * fmt_flags, uint32_t * frames_per_packet)
References ALAC_FRAME_LENGTH.
Referenced by caf_write_header().
psf_open_tmpfile()
FILE* psf_open_tmpfile (char * fname, size_t fnamelen)
References memset(), NULL, psf_rand_int32(), R_OK, W_OK, and X_OK.
Referenced by alac_writer_init().
psf_hexdump()
void psf_hexdump (const void * ptr, int len)
References memset(), NULL, and psf_isprint().
Referenced by psf_store_string().
str_of_major_format()
const char* str_of_major_format (int format)
References CASE_NAME, and SF_CONTAINER.
str_of_minor_format()
const char* str_of_minor_format (int format)
References CASE_NAME, and SF_CODEC.
str_of_open_mode()
const char* str_of_open_mode (int mode)
References CASE_NAME, and mode().
str_of_endianness()
const char* str_of_endianness (int end)
References CASE_NAME.
psf_f2s_array()
void psf_f2s_array (const float * src, short * dest, int count, int normalize)
psf_f2s_clip_array()
void psf_f2s_clip_array (const float * src, short * dest, int count, int normalize)
psf_d2s_array()
void psf_d2s_array (const double * src, short * dest, int count, int normalize)
psf_d2s_clip_array()
void psf_d2s_clip_array (const double * src, short * dest, int count, int normalize)
psf_f2i_array()
void psf_f2i_array (const float * src, int * dest, int count, int normalize)
Referenced by alac_write_f().
psf_f2i_clip_array()
void psf_f2i_clip_array (const float * src, int * dest, int count, int normalize)
Referenced by alac_write_f().
psf_d2i_array()
void psf_d2i_array (const double * src, int * dest, int count, int normalize)
Referenced by alac_write_d().
psf_d2i_clip_array()
void psf_d2i_clip_array (const double * src, int * dest, int count, int normalize)
Referenced by alac_write_d().
arith_shift_left()
static int32_t ALWAYS_INLINE arith_shift_left (int32_t x, int shift) inline static
arith_shift_right()
static int32_t ALWAYS_INLINE arith_shift_right (int32_t x, int shift) inline static