Aurora Framework: Monitor.c File Reference
Win32/Monitor.c File Reference
Functions
void _glfwGetMonitorContentScaleWin32 (HMONITOR handle, float *xscale, float *yscale)
void _glfwPlatformFreeMonitor (_GLFWmonitor *monitor)
void _glfwPlatformGetGammaRamp (_GLFWmonitor *monitor, GLFWgammaramp *ramp)
void _glfwPlatformGetMonitorContentScale (_GLFWmonitor *monitor, float *xscale, float *yscale)
void _glfwPlatformGetMonitorPos (_GLFWmonitor *monitor, int *xpos, int *ypos)
void _glfwPlatformGetVideoMode (_GLFWmonitor *monitor, GLFWvidmode *mode)
GLFWvidmode * _glfwPlatformGetVideoModes (_GLFWmonitor *monitor, int *count)
void _glfwPlatformSetGammaRamp (_GLFWmonitor *monitor, const GLFWgammaramp *ramp)
void _glfwPollMonitorsWin32 (void)
void _glfwRestoreVideoModeWin32 (_GLFWmonitor *monitor)
void _glfwSetVideoModeWin32 (_GLFWmonitor *monitor, const GLFWvidmode *desired)
static _GLFWmonitor * createMonitor (DISPLAY_DEVICEW *adapter, DISPLAY_DEVICEW *display)
GLFWAPI const char * glfwGetWin32Adapter (GLFWmonitor *handle)
GLFWAPI const char * glfwGetWin32Monitor (GLFWmonitor *handle)
static BOOL CALLBACK monitorCallback (HMONITOR handle, HDC dc, RECT *rect, LPARAM data)
Function Documentation
monitorCallback()
static BOOL CALLBACK monitorCallback (HMONITOR handle, HDC dc, RECT * rect, LPARAM data) static
Referenced by createMonitor().
createMonitor()
static _GLFWmonitor* createMonitor (DISPLAY_DEVICEW * adapter, DISPLAY_DEVICEW * display) static
References _glfwAllocMonitor(), _glfwCreateUTF8FromWideStringWin32(), display(), GLFW_TRUE, IsWindows8Point1OrGreater, monitorCallback(), setup::name, and NULL.
Referenced by _glfwPollMonitorsWin32().
_glfwPollMonitorsWin32()
void _glfwPollMonitorsWin32 (void)
References _glfw, _GLFW_INSERT_FIRST, _GLFW_INSERT_LAST, _glfwInputMonitor(), createMonitor(), display(), DISPLAY_DEVICE_ACTIVE, GLFW_CONNECTED, GLFW_DISCONNECTED, memcpy(), _GLFWlibrary::monitorCount, _GLFWlibrary::monitors, and NULL.
Referenced by _glfwPlatformInit(), and windowProc().
_glfwSetVideoModeWin32()
void _glfwSetVideoModeWin32 (_GLFWmonitor * monitor, const GLFWvidmode * desired)
References _glfwChooseVideoMode(), _glfwCompareVideoModes(), _glfwInputError(), _glfwPlatformGetVideoMode(), GLFWvidmode::blueBits, setup::description, GLFW_PLATFORM_ERROR, GLFW_TRUE, GLFWvidmode::greenBits, GLFWvidmode::height, NULL, GLFWvidmode::redBits, GLFWvidmode::refreshRate, and GLFWvidmode::width.
Referenced by acquireMonitor().
_glfwRestoreVideoModeWin32()
void _glfwRestoreVideoModeWin32 (_GLFWmonitor * monitor)
References GLFW_FALSE, and NULL.
Referenced by releaseMonitor().
_glfwGetMonitorContentScaleWin32()
void _glfwGetMonitorContentScaleWin32 (HMONITOR handle, float * xscale, float * yscale)
References GetDpiForMonitor, IsWindows8Point1OrGreater, MDT_EFFECTIVE_DPI, and NULL.
Referenced by _glfwPlatformGetMonitorContentScale(), and _glfwPlatformGetWindowContentScale().
_glfwPlatformFreeMonitor()
void _glfwPlatformFreeMonitor (_GLFWmonitor * monitor)
_glfwPlatformGetMonitorPos()
void _glfwPlatformGetMonitorPos (_GLFWmonitor * monitor, int * xpos, int * ypos)
References EDS_ROTATEDMODE.
_glfwPlatformGetMonitorContentScale()
void _glfwPlatformGetMonitorContentScale (_GLFWmonitor * monitor, float * xscale, float * yscale)
References _glfwGetMonitorContentScaleWin32().
_glfwPlatformGetVideoModes()
GLFWvidmode* _glfwPlatformGetVideoModes (_GLFWmonitor * monitor, int * count)
References _glfwCompareVideoModes(), _glfwPlatformGetVideoMode(), _glfwSplitBPP(), mode(), and NULL.
_glfwPlatformGetVideoMode()
void _glfwPlatformGetVideoMode (_GLFWmonitor * monitor, GLFWvidmode * mode)
References _glfwSplitBPP(), and mode().
Referenced by _glfwPlatformGetVideoModes(), and _glfwSetVideoModeWin32().
_glfwPlatformGetGammaRamp()
void _glfwPlatformGetGammaRamp (_GLFWmonitor * monitor, GLFWgammaramp * ramp)
References _glfwAllocGammaArrays(), GLFWgammaramp::blue, GLFWgammaramp::green, memcpy(), NULL, and GLFWgammaramp::red.
_glfwPlatformSetGammaRamp()
void _glfwPlatformSetGammaRamp (_GLFWmonitor * monitor, const GLFWgammaramp * ramp)
References _glfwInputError(), GLFWgammaramp::blue, GLFW_PLATFORM_ERROR, GLFWgammaramp::green, memcpy(), NULL, GLFWgammaramp::red, and GLFWgammaramp::size.
glfwGetWin32Adapter()
GLFWAPI const char* glfwGetWin32Adapter (GLFWmonitor * handle)
References _GLFW_REQUIRE_INIT_OR_RETURN, and NULL.
glfwGetWin32Monitor()
GLFWAPI const char* glfwGetWin32Monitor (GLFWmonitor * handle)
References _GLFW_REQUIRE_INIT_OR_RETURN, and NULL.