Aurora Framework: AuroraFW::MemoryAllocator Class Reference
AuroraFW::MemoryAllocator Class Reference
Public Member Functions
MemoryAllocator ()
MemoryAllocator (MemoryStats)
~MemoryAllocator ()
void * allocate (size_t size)
void * allocate (size_t size, const char *file, uint line)
void free (void *block)
void free (void *block, size_t size)
void free (void *block, const char *file, uint line)
void free (void *block, size_t size, const char *file, uint line)
MemoryStats getMemoryStats () const
Static Public Member Functions
static void * allocate (size_t, MemoryStats &)
static void * allocate (size_t, MemoryStats &, const char *, uint)
static void free (void *, MemoryStats &)
static void free (void *, size_t, MemoryStats &)
static void free (void *block, MemoryStats &stats, const char *, uint)
static void free (void *block, size_t size, MemoryStats &stats, const char *, uint)
Constructor & Destructor Documentation
MemoryAllocator() [1/2]
AuroraFW::MemoryAllocator::MemoryAllocator ()
MemoryAllocator() [2/2]
AuroraFW::MemoryAllocator::MemoryAllocator (MemoryStats stats)
~MemoryAllocator()
AuroraFW::MemoryAllocator::~MemoryAllocator ()
Member Function Documentation
allocate() [1/4]
void* AuroraFW::MemoryAllocator::allocate (size_t size) inline
References allocate().
Referenced by allocate().
allocate() [2/4]
void* AuroraFW::MemoryAllocator::allocate (size_t size, const char * file, uint line) inline
References allocate().
Referenced by allocate().
allocate() [3/4]
void * AuroraFW::MemoryAllocator::allocate (size_t size, MemoryStats & stats) static
References AuroraFW::MemoryStats::add(), AFW_NULLPTR, AuroraFW::MemoryStats::currentUsed, memcpy(), memset(), AuroraFW::MemoryStats::totalAllocated, AuroraFW::MemoryStats::totalAllocations, and AuroraFW::MemoryStats::totalFreed.
allocate() [4/4]
void * AuroraFW::MemoryAllocator::allocate (size_t size, MemoryStats & stats, const char * file, uint line) static
References allocate(), and AuroraFW::DebugManager::Log().
free() [1/8]
void AuroraFW::MemoryAllocator::free (void * block) inline
References free().
Referenced by free().
free() [2/8]
void AuroraFW::MemoryAllocator::free (void * block, size_t size) inline
References free().
Referenced by free().
free() [3/8]
void AuroraFW::MemoryAllocator::free (void * block, const char * file, uint line) inline
References free().
Referenced by free().
free() [4/8]
void AuroraFW::MemoryAllocator::free (void * block, size_t size, const char * file, uint line) inline
References free().
Referenced by free().
free() [5/8]
void AuroraFW::MemoryAllocator::free (void * block, MemoryStats & stats) static
References AFW_NULLPTR, AuroraFW::MemoryStats::currentUsed, AuroraFW::MemoryStats::remove(), AuroraFW::MemoryStats::totalAllocated, AuroraFW::MemoryStats::totalAllocations, and AuroraFW::MemoryStats::totalFreed.
free() [6/8]
static void AuroraFW::MemoryAllocator::free (void * , size_t , MemoryStats &) static
free() [7/8]
static void AuroraFW::MemoryAllocator::free (void * block, MemoryStats & stats, const char * , uint) inline static
References free().
Referenced by free().
free() [8/8]
static void AuroraFW::MemoryAllocator::free (void * block, size_t size, MemoryStats & stats, const char * , uint) static
getMemoryStats()
MemoryStats AuroraFW::MemoryAllocator::getMemoryStats () const inline
The documentation for this class was generated from the following files:
Allocator.h
Allocator.cpp