Aurora Framework: Joystick.h File Reference
Win32/Joystick.h File Reference
Classes
struct _GLFWjoyobjectWin32
struct _GLFWjoystickWin32
Macros
#define _GLFW_PLATFORM_JOYSTICK_STATE _GLFWjoystickWin32 win32
#define _GLFW_PLATFORM_LIBRARY_JOYSTICK_STATE int dummy
#define _GLFW_PLATFORM_MAPPING_NAME "Windows"
Typedefs
typedef struct _GLFWjoyobjectWin32 _GLFWjoyobjectWin32
typedef struct _GLFWjoystickWin32 _GLFWjoystickWin32
Functions
void _glfwDetectJoystickConnectionWin32 (void)
void _glfwDetectJoystickDisconnectionWin32 (void)
void _glfwInitJoysticksWin32 (void)
void _glfwTerminateJoysticksWin32 (void)
Macro Definition Documentation
_GLFW_PLATFORM_JOYSTICK_STATE
#define _GLFW_PLATFORM_JOYSTICK_STATE _GLFWjoystickWin32 win32
_GLFW_PLATFORM_LIBRARY_JOYSTICK_STATE
#define _GLFW_PLATFORM_LIBRARY_JOYSTICK_STATE int dummy
_GLFW_PLATFORM_MAPPING_NAME
#define _GLFW_PLATFORM_MAPPING_NAME "Windows"
Typedef Documentation
_GLFWjoyobjectWin32
typedef struct _GLFWjoyobjectWin32 _GLFWjoyobjectWin32
_GLFWjoystickWin32
typedef struct _GLFWjoystickWin32 _GLFWjoystickWin32
Function Documentation
_glfwInitJoysticksWin32()
void _glfwInitJoysticksWin32 (void)
References _glfw, _glfwDetectJoystickConnectionWin32(), _glfwInputError(), DirectInput8Create, DIRECTINPUT_VERSION, GLFW_PLATFORM_ERROR, IID_IDirectInput8W, and NULL.
Referenced by _glfwPlatformInit().
_glfwTerminateJoysticksWin32()
void _glfwTerminateJoysticksWin32 (void)
References _glfw, closeJoystick(), GLFW_JOYSTICK_1, GLFW_JOYSTICK_LAST, and _GLFWlibrary::joysticks.
Referenced by _glfwPlatformTerminate().
_glfwDetectJoystickConnectionWin32()
void _glfwDetectJoystickConnectionWin32 (void)
References _glfw, _glfwAllocJoystick(), _glfwInputError(), _glfwInputJoystick(), deviceCallback(), getDeviceDescription(), GLFW_CONNECTED, GLFW_JOYSTICK_LAST, GLFW_PLATFORM_ERROR, _GLFWlibrary::joysticks, NULL, _GLFWjoystick::present, XInputGetCapabilities, and XUSER_MAX_COUNT.
Referenced by _glfwInitJoysticksWin32(), and windowProc().
_glfwDetectJoystickDisconnectionWin32()
void _glfwDetectJoystickDisconnectionWin32 (void)
References _glfw, _GLFW_POLL_PRESENCE, _glfwPlatformPollJoystick(), GLFW_JOYSTICK_LAST, _GLFWlibrary::joysticks, and _GLFWjoystick::present.
Referenced by windowProc().