Aurora Framework: Context.h File Reference
core/src/GLFW/OSMesa/Context.h File Reference
Classes
struct _GLFWcontextOSMesa
struct _GLFWlibraryOSMesa
Macros
#define AURORAFW__BUILD_OSMESA_CONTEXT_STATE _GLFWcontextOSMesa osmesa
#define AURORAFW__BUILD_OSMESA_LIBRARY_CONTEXT_STATE _GLFWlibraryOSMesa osmesa
#define OSMESA_ACCUM_BITS 0x32
#define OSMESA_COMPAT_PROFILE 0x35
#define OSMESA_CONTEXT_MAJOR_VERSION 0x36
#define OSMESA_CONTEXT_MINOR_VERSION 0x37
#define OSMESA_CORE_PROFILE 0x34
#define OSMESA_DEPTH_BITS 0x30
#define OSMESA_FORMAT 0x22
#define OSMESA_PROFILE 0x33
#define OSMESA_RGBA 0x1908
#define OSMESA_STENCIL_BITS 0x31
#define OSMesaCreateContextAttribs _glfw.osmesa.CreateContextAttribs
#define OSMesaCreateContextExt _glfw.osmesa.CreateContextExt
#define OSMesaDestroyContext _glfw.osmesa.DestroyContext
#define OSMesaGetColorBuffer _glfw.osmesa.GetColorBuffer
#define OSMesaGetDepthBuffer _glfw.osmesa.GetDepthBuffer
#define OSMesaGetProcAddress _glfw.osmesa.GetProcAddress
#define OSMesaMakeCurrent _glfw.osmesa.MakeCurrent
Typedefs
typedef struct _GLFWcontextOSMesa _GLFWcontextOSMesa
typedef struct _GLFWlibraryOSMesa _GLFWlibraryOSMesa
typedef void * OSMesaContext
typedef void(* OSMESAproc) (void)
typedef OSMesaContext(GLAPIENTRY * PFN_OSMesaCreateContextAttribs) (const int *, OSMesaContext)
typedef OSMesaContext(GLAPIENTRY * PFN_OSMesaCreateContextExt) (GLenum, GLint, GLint, GLint, OSMesaContext)
typedef void(GLAPIENTRY * PFN_OSMesaDestroyContext) (OSMesaContext)
typedef int(GLAPIENTRY * PFN_OSMesaGetColorBuffer) (OSMesaContext, int *, int *, int *, void **)
typedef int(GLAPIENTRY * PFN_OSMesaGetDepthBuffer) (OSMesaContext, int *, int *, int *, void **)
typedef GLFWglproc(GLAPIENTRY * PFN_OSMesaGetProcAddress) (const char *)
typedef int(GLAPIENTRY * PFN_OSMesaMakeCurrent) (OSMesaContext, void *, int, int, int)
Functions
GLFWbool _glfwCreateContextOSMesa (_GLFWwindow *window, const _GLFWctxconfig *ctxconfig, const _GLFWfbconfig *fbconfig)
GLFWbool _glfwInitOSMesa (void)
void _glfwTerminateOSMesa (void)
Macro Definition Documentation
OSMESA_RGBA
#define OSMESA_RGBA 0x1908
Referenced by _glfwCreateContextOSMesa().
OSMESA_FORMAT
#define OSMESA_FORMAT 0x22
Referenced by _glfwCreateContextOSMesa().
OSMESA_DEPTH_BITS
#define OSMESA_DEPTH_BITS 0x30
Referenced by _glfwCreateContextOSMesa().
OSMESA_STENCIL_BITS
#define OSMESA_STENCIL_BITS 0x31
Referenced by _glfwCreateContextOSMesa().
OSMESA_ACCUM_BITS
#define OSMESA_ACCUM_BITS 0x32
Referenced by _glfwCreateContextOSMesa().
OSMESA_PROFILE
#define OSMESA_PROFILE 0x33
Referenced by _glfwCreateContextOSMesa().
OSMESA_CORE_PROFILE
#define OSMESA_CORE_PROFILE 0x34
Referenced by _glfwCreateContextOSMesa().
OSMESA_COMPAT_PROFILE
#define OSMESA_COMPAT_PROFILE 0x35
Referenced by _glfwCreateContextOSMesa().
OSMESA_CONTEXT_MAJOR_VERSION
#define OSMESA_CONTEXT_MAJOR_VERSION 0x36
Referenced by _glfwCreateContextOSMesa().
OSMESA_CONTEXT_MINOR_VERSION
#define OSMESA_CONTEXT_MINOR_VERSION 0x37
Referenced by _glfwCreateContextOSMesa().
OSMesaCreateContextExt
#define OSMesaCreateContextExt _glfw.osmesa.CreateContextExt
Referenced by _glfwCreateContextOSMesa().
OSMesaCreateContextAttribs
#define OSMesaCreateContextAttribs _glfw.osmesa.CreateContextAttribs
Referenced by _glfwCreateContextOSMesa().
OSMesaDestroyContext
#define OSMesaDestroyContext _glfw.osmesa.DestroyContext
Referenced by destroyContextOSMesa().
OSMesaMakeCurrent
#define OSMesaMakeCurrent _glfw.osmesa.MakeCurrent
Referenced by makeContextCurrentOSMesa().
OSMesaGetColorBuffer
#define OSMesaGetColorBuffer _glfw.osmesa.GetColorBuffer
Referenced by glfwGetOSMesaColorBuffer().
OSMesaGetDepthBuffer
#define OSMesaGetDepthBuffer _glfw.osmesa.GetDepthBuffer
Referenced by glfwGetOSMesaDepthBuffer().
OSMesaGetProcAddress
#define OSMesaGetProcAddress _glfw.osmesa.GetProcAddress
Referenced by getProcAddressOSMesa().
AURORAFW__BUILD_OSMESA_CONTEXT_STATE
#define AURORAFW__BUILD_OSMESA_CONTEXT_STATE _GLFWcontextOSMesa osmesa
AURORAFW__BUILD_OSMESA_LIBRARY_CONTEXT_STATE
#define AURORAFW__BUILD_OSMESA_LIBRARY_CONTEXT_STATE _GLFWlibraryOSMesa osmesa
Typedef Documentation
OSMesaContext
typedef void* OSMesaContext
OSMESAproc
typedef void(* OSMESAproc) (void)
PFN_OSMesaCreateContextExt
typedef OSMesaContext(GLAPIENTRY * PFN_OSMesaCreateContextExt) (GLenum, GLint, GLint, GLint, OSMesaContext)
PFN_OSMesaCreateContextAttribs
typedef OSMesaContext(GLAPIENTRY * PFN_OSMesaCreateContextAttribs) (const int *, OSMesaContext)
PFN_OSMesaDestroyContext
typedef void(GLAPIENTRY * PFN_OSMesaDestroyContext) (OSMesaContext)
PFN_OSMesaMakeCurrent
typedef int(GLAPIENTRY * PFN_OSMesaMakeCurrent) (OSMesaContext, void *, int, int, int)
PFN_OSMesaGetColorBuffer
typedef int(GLAPIENTRY * PFN_OSMesaGetColorBuffer) (OSMesaContext, int *, int *, int *, void **)
PFN_OSMesaGetDepthBuffer
typedef int(GLAPIENTRY * PFN_OSMesaGetDepthBuffer) (OSMesaContext, int *, int *, int *, void **)
PFN_OSMesaGetProcAddress
typedef GLFWglproc(GLAPIENTRY * PFN_OSMesaGetProcAddress) (const char *)
_GLFWcontextOSMesa
typedef struct _GLFWcontextOSMesa _GLFWcontextOSMesa
_GLFWlibraryOSMesa
typedef struct _GLFWlibraryOSMesa _GLFWlibraryOSMesa
Function Documentation
_glfwInitOSMesa()
GLFWbool _glfwInitOSMesa (void)
References _glfw, _glfw_dlopen, _glfw_dlsym, _glfwInputError(), _glfwTerminateOSMesa(), GLFW_API_UNAVAILABLE, GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, _GLFWlibrary::handle, and NULL.
Referenced by _glfwPlatformCreateWindow().
_glfwTerminateOSMesa()
void _glfwTerminateOSMesa (void)
References _glfw, _glfw_dlclose, _GLFWlibrary::handle, and NULL.
Referenced by _glfwInitOSMesa(), and _glfwPlatformTerminate().
_glfwCreateContextOSMesa()
GLFWbool _glfwCreateContextOSMesa (_GLFWwindow * window, const _GLFWctxconfig * ctxconfig, const _GLFWfbconfig * fbconfig)
References _glfwInputError(), _GLFWfbconfig::accumAlphaBits, _GLFWfbconfig::accumBlueBits, _GLFWfbconfig::accumGreenBits, _GLFWfbconfig::accumRedBits, _GLFWctxconfig::client, _GLFWwindow::context, _GLFWfbconfig::depthBits, _GLFWcontext::destroy, destroyContextOSMesa(), _GLFWcontext::extensionSupported, extensionSupportedOSMesa(), _GLFWctxconfig::forward, _GLFWcontext::getProcAddress, getProcAddressOSMesa(), GLFW_API_UNAVAILABLE, GLFW_FALSE, GLFW_OPENGL_COMPAT_PROFILE, GLFW_OPENGL_CORE_PROFILE, GLFW_OPENGL_ES_API, GLFW_TRUE, GLFW_VERSION_UNAVAILABLE, _GLFWctxconfig::major, makeContextCurrentOSMesa(), _GLFWcontext::makeCurrent, _GLFWctxconfig::minor, NULL, OSMESA_ACCUM_BITS, OSMESA_COMPAT_PROFILE, OSMESA_CONTEXT_MAJOR_VERSION, OSMESA_CONTEXT_MINOR_VERSION, OSMESA_CORE_PROFILE, OSMESA_DEPTH_BITS, OSMESA_FORMAT, OSMESA_PROFILE, OSMESA_RGBA, OSMESA_STENCIL_BITS, OSMesaCreateContextAttribs, OSMesaCreateContextExt, _GLFWctxconfig::profile, setAttrib, _GLFWctxconfig::share, _GLFWfbconfig::stencilBits, _GLFWcontext::swapBuffers, swapBuffersOSMesa(), _GLFWcontext::swapInterval, and swapIntervalOSMesa().
Referenced by _glfwPlatformCreateWindow().