Aurora Framework: Init.c File Reference
Wayland/Init.c File Reference
Functions
const char * _glfwPlatformGetVersionString (void)
int _glfwPlatformInit (void)
void _glfwPlatformTerminate (void)
static void createKeyTables (void)
static _GLFWwindow * findWindowFromDecorationSurface (struct wl_surface *surface, int *which)
static GLFWbool inputChar (_GLFWwindow *window, uint32_t key)
static void keyboardHandleEnter (void *data, struct wl_keyboard *keyboard, uint32_t serial, struct wl_surface *surface, struct wl_array *keys)
static void keyboardHandleKey (void *data, struct wl_keyboard *keyboard, uint32_t serial, uint32_t time, uint32_t key, uint32_t state)
static void keyboardHandleKeymap (void *data, struct wl_keyboard *keyboard, uint32_t format, int fd, uint32_t size)
static void keyboardHandleLeave (void *data, struct wl_keyboard *keyboard, uint32_t serial, struct wl_surface *surface)
static void keyboardHandleModifiers (void *data, struct wl_keyboard *keyboard, uint32_t serial, uint32_t modsDepressed, uint32_t modsLatched, uint32_t modsLocked, uint32_t group)
static int min (int n1, int n2)
static void pointerHandleAxis (void *data, struct wl_pointer *pointer, uint32_t time, uint32_t axis, wl_fixed_t value)
static void pointerHandleButton (void *data, struct wl_pointer *pointer, uint32_t serial, uint32_t time, uint32_t button, uint32_t state)
static void pointerHandleEnter (void *data, struct wl_pointer *pointer, uint32_t serial, struct wl_surface *surface, wl_fixed_t sx, wl_fixed_t sy)
static void pointerHandleLeave (void *data, struct wl_pointer *pointer, uint32_t serial, struct wl_surface *surface)
static void pointerHandleMotion (void *data, struct wl_pointer *pointer, uint32_t time, wl_fixed_t sx, wl_fixed_t sy)
static void registryHandleGlobal (void *data, struct wl_registry *registry, uint32_t name, const char *interface, uint32_t version)
static void registryHandleGlobalRemove (void *data, struct wl_registry *registry, uint32_t name)
static void seatHandleCapabilities (void *data, struct wl_seat *seat, enum wl_seat_capability caps)
static void seatHandleName (void *data, struct wl_seat *seat, const char *name)
static void setCursor (const char *name)
static int toGLFWKeyCode (uint32_t key)
static void wmBaseHandlePing (void *data, struct xdg_wm_base *wmBase, uint32_t serial)
Variables
static const struct wl_keyboard_listener keyboardListener
static const struct wl_pointer_listener pointerListener
static const struct wl_registry_listener registryListener
static const struct wl_seat_listener seatListener
static const struct xdg_wm_base_listener wmBaseListener
Function Documentation
min()
static int min (int n1, int n2) inline static
Referenced by _glfwKeySym2Unicode(), registryHandleGlobal(), spirv_cross::CompilerGLSL::remap_swizzle(), and ImGui::ShadeVertsLinearUV().
findWindowFromDecorationSurface()
static _GLFWwindow* findWindowFromDecorationSurface (struct wl_surface * surface, int * which) static
References _glfw, bottomDecoration, leftDecoration, _GLFWwindow::next, rightDecoration, topDecoration, and _GLFWlibrary::windowListHead.
Referenced by keyboardHandleEnter(), and pointerHandleEnter().
pointerHandleEnter()
static void pointerHandleEnter (void * data, struct wl_pointer * pointer, uint32_t serial, struct wl_surface * surface, wl_fixed_t sx, wl_fixed_t sy) static
References _glfw, _glfwInputCursorEnter(), _glfwPlatformSetCursor(), findWindowFromDecorationSurface(), _GLFWwindow::focus, and GLFW_TRUE.
pointerHandleLeave()
static void pointerHandleLeave (void * data, struct wl_pointer * pointer, uint32_t serial, struct wl_surface * surface) static
References _glfw, _glfwInputCursorEnter(), GLFW_FALSE, and NULL.
setCursor()
static void setCursor (const char * name) static
References _glfw, _glfwInputError(), GLFW_PLATFORM_ERROR, wl_cursor_image::height, wl_cursor_image::hotspot_x, wl_cursor_image::hotspot_y, wl_cursor::images, setup::name, wl_cursor_image::width, wl_cursor_image_get_buffer, and wl_cursor_theme_get_cursor.
Referenced by pointerHandleMotion().
pointerHandleMotion()
static void pointerHandleMotion (void * data, struct wl_pointer * pointer, uint32_t time, wl_fixed_t sx, wl_fixed_t sy) static
References _glfw, _GLFW_DECORATION_WIDTH, _glfwInputCursorPos(), bottomDecoration, _GLFWwindow::cursorMode, _GLFWwindow::focus, GLFW_CURSOR_DISABLED, leftDecoration, mainWindow, rightDecoration, setCursor(), and topDecoration.
pointerHandleButton()
static void pointerHandleButton (void * data, struct wl_pointer * pointer, uint32_t serial, uint32_t time, uint32_t button, uint32_t state) static
References _glfw, _GLFW_DECORATION_WIDTH, _glfwInputMouseClick(), bottomDecoration, _GLFWwindow::focus, GLFW_PRESS, GLFW_RELEASE, leftDecoration, mainWindow, rightDecoration, and topDecoration.
pointerHandleAxis()
static void pointerHandleAxis (void * data, struct wl_pointer * pointer, uint32_t time, uint32_t axis, wl_fixed_t value) static
References _glfw, _glfwInputScroll(), and value.
keyboardHandleKeymap()
static void keyboardHandleKeymap (void * data, struct wl_keyboard * keyboard, uint32_t format, int fd, uint32_t size) static
References _glfw, _glfwInputError(), _GLFWlibrary::context, GLFW_PLATFORM_ERROR, NULL, xkb_keymap_mod_get_index, xkb_keymap_new_from_string, xkb_keymap_unref, xkb_state_new, and xkb_state_unref.
keyboardHandleEnter()
static void keyboardHandleEnter (void * data, struct wl_keyboard * keyboard, uint32_t serial, struct wl_surface * surface, struct wl_array * keys) static
References _glfw, _glfwInputWindowFocus(), findWindowFromDecorationSurface(), GLFW_TRUE, and NULL.
keyboardHandleLeave()
static void keyboardHandleLeave (void * data, struct wl_keyboard * keyboard, uint32_t serial, struct wl_surface * surface) static
References _glfw, _glfwInputWindowFocus(), GLFW_FALSE, and NULL.
toGLFWKeyCode()
static int toGLFWKeyCode (uint32_t key) static
References _glfw, and GLFW_KEY_UNKNOWN.
Referenced by keyboardHandleKey().
inputChar()
static GLFWbool inputChar (_GLFWwindow * window, uint32_t key) static
References _glfw, _glfwInputChar(), _glfwKeySym2Unicode(), GLFW_MOD_ALT, GLFW_MOD_CONTROL, xkb_keymap_key_repeats, and xkb_state_key_get_syms.
Referenced by keyboardHandleKey().
keyboardHandleKey()
static void keyboardHandleKey (void * data, struct wl_keyboard * keyboard, uint32_t serial, uint32_t time, uint32_t key, uint32_t state) static
References _glfw, _glfwInputKey(), GLFW_PRESS, GLFW_RELEASE, inputChar(), NULL, and toGLFWKeyCode().
keyboardHandleModifiers()
static void keyboardHandleModifiers (void * data, struct wl_keyboard * keyboard, uint32_t serial, uint32_t modsDepressed, uint32_t modsLatched, uint32_t modsLocked, uint32_t group) static
References _glfw, GLFW_MOD_ALT, GLFW_MOD_CAPS_LOCK, GLFW_MOD_CONTROL, GLFW_MOD_NUM_LOCK, GLFW_MOD_SHIFT, GLFW_MOD_SUPER, xkb_state_serialize_mods, and xkb_state_update_mask.
seatHandleCapabilities()
static void seatHandleCapabilities (void * data, struct wl_seat * seat, enum wl_seat_capability caps) static
References _glfw, keyboardListener, NULL, and pointerListener.
seatHandleName()
static void seatHandleName (void * data, struct wl_seat * seat, const char * name) static
wmBaseHandlePing()
static void wmBaseHandlePing (void * data, struct xdg_wm_base * wmBase, uint32_t serial) static
registryHandleGlobal()
static void registryHandleGlobal (void * data, struct wl_registry * registry, uint32_t name, const char * interface, uint32_t version) static
References _glfw, _glfwAddOutputWayland(), min(), setup::name, NULL, seatListener, create_symbols_file::version, and wmBaseListener.
registryHandleGlobalRemove()
static void registryHandleGlobalRemove (void * data, struct wl_registry * registry, uint32_t name) static
References _glfw, _glfwInputMonitor(), GLFW_DISCONNECTED, _GLFWlibrary::monitorCount, _GLFWlibrary::monitors, setup::name, and _GLFWmonitor::name.
createKeyTables()
static void createKeyTables (void) static
References _glfw, GLFW_KEY_0, GLFW_KEY_1, GLFW_KEY_2, GLFW_KEY_3, GLFW_KEY_4, GLFW_KEY_5, GLFW_KEY_6, GLFW_KEY_7, GLFW_KEY_8, GLFW_KEY_9, GLFW_KEY_A, GLFW_KEY_APOSTROPHE, GLFW_KEY_B, GLFW_KEY_BACKSLASH, GLFW_KEY_BACKSPACE, GLFW_KEY_C, GLFW_KEY_CAPS_LOCK, GLFW_KEY_COMMA, GLFW_KEY_D, GLFW_KEY_DELETE, GLFW_KEY_DOWN, GLFW_KEY_E, GLFW_KEY_END, GLFW_KEY_ENTER, GLFW_KEY_EQUAL, GLFW_KEY_ESCAPE, GLFW_KEY_F, GLFW_KEY_F1, GLFW_KEY_F10, GLFW_KEY_F11, GLFW_KEY_F12, GLFW_KEY_F13, GLFW_KEY_F14, GLFW_KEY_F15, GLFW_KEY_F16, GLFW_KEY_F17, GLFW_KEY_F18, GLFW_KEY_F19, GLFW_KEY_F2, GLFW_KEY_F20, GLFW_KEY_F21, GLFW_KEY_F22, GLFW_KEY_F23, GLFW_KEY_F24, GLFW_KEY_F3, GLFW_KEY_F4, GLFW_KEY_F5, GLFW_KEY_F6, GLFW_KEY_F7, GLFW_KEY_F8, GLFW_KEY_F9, GLFW_KEY_G, GLFW_KEY_GRAVE_ACCENT, GLFW_KEY_H, GLFW_KEY_HOME, GLFW_KEY_I, GLFW_KEY_INSERT, GLFW_KEY_J, GLFW_KEY_K, GLFW_KEY_KP_0, GLFW_KEY_KP_1, GLFW_KEY_KP_2, GLFW_KEY_KP_3, GLFW_KEY_KP_4, GLFW_KEY_KP_5, GLFW_KEY_KP_6, GLFW_KEY_KP_7, GLFW_KEY_KP_8, GLFW_KEY_KP_9, GLFW_KEY_KP_ADD, GLFW_KEY_KP_DECIMAL, GLFW_KEY_KP_DIVIDE, GLFW_KEY_KP_ENTER, GLFW_KEY_KP_EQUAL, GLFW_KEY_KP_MULTIPLY, GLFW_KEY_KP_SUBTRACT, GLFW_KEY_L, GLFW_KEY_LEFT, GLFW_KEY_LEFT_ALT, GLFW_KEY_LEFT_BRACKET, GLFW_KEY_LEFT_CONTROL, GLFW_KEY_LEFT_SHIFT, GLFW_KEY_LEFT_SUPER, GLFW_KEY_M, GLFW_KEY_MENU, GLFW_KEY_MINUS, GLFW_KEY_N, GLFW_KEY_NUM_LOCK, GLFW_KEY_O, GLFW_KEY_P, GLFW_KEY_PAGE_DOWN, GLFW_KEY_PAGE_UP, GLFW_KEY_PAUSE, GLFW_KEY_PERIOD, GLFW_KEY_PRINT_SCREEN, GLFW_KEY_Q, GLFW_KEY_R, GLFW_KEY_RIGHT, GLFW_KEY_RIGHT_ALT, GLFW_KEY_RIGHT_BRACKET, GLFW_KEY_RIGHT_CONTROL, GLFW_KEY_RIGHT_SHIFT, GLFW_KEY_RIGHT_SUPER, GLFW_KEY_S, GLFW_KEY_SCROLL_LOCK, GLFW_KEY_SEMICOLON, GLFW_KEY_SLASH, GLFW_KEY_SPACE, GLFW_KEY_T, GLFW_KEY_TAB, GLFW_KEY_U, GLFW_KEY_UP, GLFW_KEY_V, GLFW_KEY_W, GLFW_KEY_X, GLFW_KEY_Y, GLFW_KEY_Z, and memset().
Referenced by _glfwPlatformInit().
_glfwPlatformInit()
int _glfwPlatformInit (void)
References _glfw, _glfw_dlopen, _glfw_dlsym, _glfwInitJoysticksLinux(), _glfwInitTimerPOSIX(), _glfwInputError(), _GLFWlibrary::context, createKeyTables(), GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, _GLFWlibrary::handle, NULL, registryListener, wl_cursor_theme_load, and xkb_context_new.
_glfwPlatformTerminate()
void _glfwPlatformTerminate (void)
References _glfw, _glfw_dlclose, _glfwTerminateEGL(), _glfwTerminateJoysticksLinux(), _GLFWlibrary::context, _GLFWlibrary::handle, NULL, wl_cursor_theme_destroy, xkb_context_unref, xkb_keymap_unref, and xkb_state_unref.
_glfwPlatformGetVersionString()
const char* _glfwPlatformGetVersionString (void)
References _GLFW_VERSION_NUMBER.
Variable Documentation
pointerListener
const struct wl_pointer_listener pointerListener static
Initial value:
= {
    pointerHandleEnter,
    pointerHandleLeave,
    pointerHandleMotion,
    pointerHandleButton,
    pointerHandleAxis,
}
Referenced by seatHandleCapabilities().
keyboardListener
const struct wl_keyboard_listener keyboardListener static
Initial value:
= {
    keyboardHandleKeymap,
    keyboardHandleEnter,
    keyboardHandleLeave,
    keyboardHandleKey,
    keyboardHandleModifiers,
}
Referenced by seatHandleCapabilities().
seatListener
const struct wl_seat_listener seatListener static
Initial value:
= {
    seatHandleCapabilities,
    seatHandleName,
}
Referenced by registryHandleGlobal().
wmBaseListener
const struct xdg_wm_base_listener wmBaseListener static
Initial value:
= {
    wmBaseHandlePing
}
Referenced by registryHandleGlobal().
registryListener
const struct wl_registry_listener registryListener static
Initial value:
= {
    registryHandleGlobal,
    registryHandleGlobalRemove
}
Referenced by _glfwPlatformInit().