Aurora Framework: AuroraFW::DebugManager Class Reference
AuroraFW::DebugManager Class Reference
Static Public Member Functions
static void disable (const bool &silent=false)
static void enable (const bool &silent=false)
static bool getStatus ()
template<typename... T>
static void Log (const T &... args)
Member Function Documentation
enable()
void AuroraFW::DebugManager::enable (const bool & silent = false) static
References Log().
Referenced by AuroraFW::ApplicationContext::ApplicationContext().
disable()
void AuroraFW::DebugManager::disable (const bool & silent = false) static
References Log().
getStatus()
static bool AuroraFW::DebugManager::getStatus () inline static
Log()
template<typename... T> static void AuroraFW::DebugManager::Log (const T &... args) inline static
Referenced by AuroraFW::MemoryAllocator::allocate(), AuroraFW::GUI::Application::Application(), AuroraFW::ApplicationContext::ApplicationContext(), AuroraFW::AudioManager::AudioOStream::AudioOStream(), AuroraFW::ApplicationContext::close(), AuroraFW::GUI::Window::close(), AuroraFW::GUI::Application::connect(), AuroraFW::GUI::Window::connect(), AuroraFW::GUI::Window::deiconify(), disable(), enable(), AuroraFW::Application::ExitFail(), AuroraFW::Application::ExitSuccess(), AuroraFW::GUI::Window::fullscreen(), AuroraFW::GUI::Label::getAlignment(), AuroraFW::GUI::Label::getText(), AuroraFW::GUI::Label::getWrapMode(), AuroraFW::GUI::Label::getXAlignment(), AuroraFW::GUI::Label::getYAlignment(), AuroraFW::GUI::Window::iconify(), AuroraFW::ImageManager::Image::Image(), AuroraFW::GUI::Label::isSelectable(), AuroraFW::GUI::Label::isWrap(), AuroraFW::GUI::Label::Label(), AuroraFW::GUI::Window::maximize(), AuroraFW::GUI::Window::move(), AuroraFW::GUI::Window::resize(), AuroraFW::GUI::Label::setAlignment(), AuroraFW::GUI::Window::setIcon(), AuroraFW::GUI::Window::setOpacity(), AuroraFW::GUI::Window::setPos(), AuroraFW::GUI::Window::setResizable(), AuroraFW::GUI::Label::setSelectable(), AuroraFW::GUI::Label::setText(), AuroraFW::GUI::Window::setTitle(), AuroraFW::GUI::Label::setWrap(), AuroraFW::GUI::Label::setWrapMode(), AuroraFW::ApplicationContext::start(), AuroraFW::GUI::Window::start(), AuroraFW::GUI::Window::stick(), AuroraFW::AudioManager::AudioBackend::terminate(), AuroraFW::GUI::Window::unfullscreen(), AuroraFW::GUI::Window::unmaximize(), AuroraFW::GUI::Window::unstick(), AuroraFW::GUI::Window::Window(), AuroraFW::Application::~Application(), AuroraFW::ApplicationContext::~ApplicationContext(), and AuroraFW::ImageManager::Image::~Image().
The documentation for this class was generated from the following files:
DebugManager.h
DebugManager.cpp