Aurora Framework: spirv_cross::Compiler::ActiveBuiltinHandler Struct Reference
spirv_cross::Compiler::ActiveBuiltinHandler Struct Reference
Public Member Functions
ActiveBuiltinHandler (Compiler &compiler_)
virtual bool begin_function_scope (const uint32_t *, uint32_t)
virtual bool end_function_scope (const uint32_t *, uint32_t)
virtual bool follow_function_call (const SPIRFunction &)
bool handle (spv::Op opcode, const uint32_t *args, uint32_t length) override
void handle_builtin (const SPIRType &type, spv::BuiltIn builtin, const Bitset &decoration_flags)
virtual void set_current_block (const SPIRBlock &)
Public Attributes
Compiler & compiler
Constructor & Destructor Documentation
ActiveBuiltinHandler()
spirv_cross::Compiler::ActiveBuiltinHandler::ActiveBuiltinHandler (Compiler & compiler_) inline
Member Function Documentation
handle()
bool Compiler::ActiveBuiltinHandler::handle (spv::Op opcode, const uint32_t * args, uint32_t length) override virtual
Implements spirv_cross::Compiler::OpcodeHandler.
References spirv_cross::SPIRVariable::decoration, spv::OpAccessChain, spv::OpCopyMemory, spv::OpCopyObject, spv::OpFunctionCall, spv::OpInBoundsAccessChain, spv::OpLoad, spv::OpStore, spirv_cross::SPIRType::storage, spv::StorageClassInput, and spirv_cross::SPIRType::Struct.
handle_builtin()
void Compiler::ActiveBuiltinHandler::handle_builtin (const SPIRType & type, spv::BuiltIn builtin, const Bitset & decoration_flags)
References spirv_cross::SPIRType::array, spirv_cross::SPIRType::array_size_literal, spv::BuiltInClipDistance, spv::BuiltInCullDistance, spv::BuiltInPosition, spv::DecorationInvariant, spirv_cross::Bitset::get(), and SPIRV_CROSS_THROW.
follow_function_call()
virtual bool spirv_cross::Compiler::OpcodeHandler::follow_function_call (const SPIRFunction &) inline virtual inherited
Referenced by spirv_cross::Compiler::traverse_all_reachable_opcodes().
set_current_block()
virtual void spirv_cross::Compiler::OpcodeHandler::set_current_block (const SPIRBlock &) inline virtual inherited
Referenced by spirv_cross::Compiler::traverse_all_reachable_opcodes().
begin_function_scope()
virtual bool spirv_cross::Compiler::OpcodeHandler::begin_function_scope (const uint32_t * , uint32_t) inline virtual inherited
Reimplemented in spirv_cross::Compiler::CombinedImageSamplerUsageHandler, and spirv_cross::Compiler::CombinedImageSamplerHandler.
Referenced by spirv_cross::Compiler::traverse_all_reachable_opcodes().
end_function_scope()
virtual bool spirv_cross::Compiler::OpcodeHandler::end_function_scope (const uint32_t * , uint32_t) inline virtual inherited
Reimplemented in spirv_cross::Compiler::CombinedImageSamplerHandler.
Referenced by spirv_cross::Compiler::traverse_all_reachable_opcodes().
Member Data Documentation
compiler
Compiler& spirv_cross::Compiler::ActiveBuiltinHandler::compiler
The documentation for this struct was generated from the following files:
Cross.h
Cross.cpp