Aurora Framework: chanmap.c File Reference
chanmap.c File Reference
Classes
struct MAP_MAP
Functions
int aiff_caf_find_channel_layout_tag (const int *chan_map, int channels)
const AIFF_CAF_CHANNEL_MAP * aiff_caf_of_channel_layout_tag (int tag)
Variables
static const AIFF_CAF_CHANNEL_MAP eight_chan []
static const AIFF_CAF_CHANNEL_MAP five_chan []
static const int five_channel_dvd_11 [5]
static const int five_channel_dvd_18 [5]
static const int five_channel_dvd_6 [5]
static const int five_channel_mpeg_50_a [5]
static const int five_channel_mpeg_50_b [5]
static const int five_channel_mpeg_50_c [5]
static const int five_channel_mpeg_50_d [5]
static const int five_channel_pentagonal [5]
static const AIFF_CAF_CHANNEL_MAP four_chan []
static const int four_channel_ambisonc_b [4]
static const int four_channel_dvd_10 [4]
static const int four_channel_dvd_5 [4]
static const int four_channel_itu_23 [4]
static const int four_channel_mpeg_40a [4]
static const int four_channel_mpeg_40b [4]
static const int four_channel_quad [4]
static const MAP_MAP map []
static const AIFF_CAF_CHANNEL_MAP one_chan []
static const int one_chan_mono [1] = { SF_CHANNEL_MAP_MONO }
static const AIFF_CAF_CHANNEL_MAP seven_chan []
static const AIFF_CAF_CHANNEL_MAP six_chan []
static const int six_channel_aac_60 [6]
static const int six_channel_aac_61 [7]
static const int six_channel_audio_unit_60 [6]
static const int six_channel_mpeg_51_a [6]
static const int six_channel_mpeg_51_b [6]
static const int six_channel_mpeg_51_c [6]
static const int six_channel_mpeg_51_d [6]
static const int six_channel_mpeg_61a [7]
static const AIFF_CAF_CHANNEL_MAP three_chan []
static const int three_channel_dvd_4 [3]
static const int three_channel_itu_21 [3]
static const int three_channel_mpeg_30a [3]
static const int three_channel_mpeg_30b [3]
static const AIFF_CAF_CHANNEL_MAP two_chan []
static const int two_channel_stereo [2] = { SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_RIGHT }
static const AIFF_CAF_CHANNEL_MAP zero_chan []
Function Documentation
aiff_caf_find_channel_layout_tag()
int aiff_caf_find_channel_layout_tag (const int * chan_map, int channels)
References ARRAY_LEN, AIFF_CAF_CHANNEL_MAP::channel_layout_tag, MAP_MAP::len, MAP_MAP::map, map, memcmp(), and NULL.
Referenced by aiff_command(), and caf_command().
aiff_caf_of_channel_layout_tag()
const AIFF_CAF_CHANNEL_MAP* aiff_caf_of_channel_layout_tag (int tag)
References ARRAY_LEN, MAP_MAP::len, MAP_MAP::map, map, and NULL.
Referenced by aiff_read_chanmap(), and caf_read_chanmap().
Variable Documentation
zero_chan
const AIFF_CAF_CHANNEL_MAP zero_chan[] static
Initial value:
=
{   {   (0 << 16) | 0, NULL, "Use channel descriptions." },
    {   (1 << 16) | 0, NULL, "Use channel bitmap." }
}
one_chan_mono
const int one_chan_mono[1] = { SF_CHANNEL_MAP_MONO } static
one_chan
const AIFF_CAF_CHANNEL_MAP one_chan[] static
Initial value:
=
{   {   (100 << 16) | 1, one_chan_mono, "mono" }
}
two_channel_stereo
const int two_channel_stereo[2] = { SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_RIGHT } static
two_chan
const AIFF_CAF_CHANNEL_MAP two_chan[] static
Initial value:
=
{   {   (101 << 16) | 2, two_channel_stereo, "stereo (L, R)" },
    {   (102 << 16) | 2, two_channel_stereo, "stereo headphones (L, R)" },
}
three_channel_mpeg_30a
const int three_channel_mpeg_30a[3] static
Initial value:
=
    {   SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_RIGHT, SF_CHANNEL_MAP_CENTER }
three_channel_mpeg_30b
const int three_channel_mpeg_30b[3] static
Initial value:
=
    {   SF_CHANNEL_MAP_CENTER, SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_RIGHT }
three_channel_itu_21
const int three_channel_itu_21[3] static
Initial value:
=
    {   SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_RIGHT, SF_CHANNEL_MAP_REAR_CENTER }
three_channel_dvd_4
const int three_channel_dvd_4[3] static
Initial value:
=
    {   SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_RIGHT, SF_CHANNEL_MAP_LFE }
three_chan
const AIFF_CAF_CHANNEL_MAP three_chan[] static
Initial value:
=
{   {   (113 << 16) | 3, three_channel_mpeg_30a, "MPEG 3 0 A (L, R, C)" },
    {   (114 << 16) | 3, three_channel_mpeg_30b, "MPEG 3 0 B (C, L, R)" },
    {   (131 << 16) | 3, three_channel_itu_21, "ITU 2.1 (L, R, Cs)" },
    {   (133 << 16) | 3, three_channel_dvd_4, "DVD 4 (L, R, LFE)" }
}
four_channel_ambisonc_b
const int four_channel_ambisonc_b[4] static
Initial value:
=
    {   SF_CHANNEL_MAP_AMBISONIC_B_W, SF_CHANNEL_MAP_AMBISONIC_B_X, SF_CHANNEL_MAP_AMBISONIC_B_Y, SF_CHANNEL_MAP_AMBISONIC_B_Z }
four_channel_quad
const int four_channel_quad[4] static
Initial value:
=
    {   SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_RIGHT, SF_CHANNEL_MAP_REAR_LEFT, SF_CHANNEL_MAP_REAR_RIGHT }
four_channel_mpeg_40a
const int four_channel_mpeg_40a[4] static
Initial value:
=
    {   SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_RIGHT, SF_CHANNEL_MAP_CENTER, SF_CHANNEL_MAP_REAR_CENTER }
four_channel_mpeg_40b
const int four_channel_mpeg_40b[4] static
Initial value:
=
    {   SF_CHANNEL_MAP_CENTER, SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_RIGHT, SF_CHANNEL_MAP_REAR_CENTER }
four_channel_itu_23
const int four_channel_itu_23[4] static
Initial value:
=
    {   SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_RIGHT, SF_CHANNEL_MAP_REAR_LEFT, SF_CHANNEL_MAP_REAR_RIGHT }
four_channel_dvd_5
const int four_channel_dvd_5[4] static
Initial value:
=
    {   SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_RIGHT, SF_CHANNEL_MAP_LFE, SF_CHANNEL_MAP_REAR_CENTER }
four_channel_dvd_10
const int four_channel_dvd_10[4] static
Initial value:
=
    {   SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_RIGHT, SF_CHANNEL_MAP_CENTER, SF_CHANNEL_MAP_LFE }
four_chan
const AIFF_CAF_CHANNEL_MAP four_chan[] static
Initial value:
=
{   {   (107 << 16) | 4, four_channel_ambisonc_b, "ambisonic B (W,  X, Y, Z)" },
    {   (108 << 16) | 4, four_channel_quad, "quad (Lfront, Rfront, Lrear, Rrear)" },
    {   (115 << 16) | 4, four_channel_mpeg_40a, "MPEG 4.0 A (L, R, C, Cs)" },
    {   (116 << 16) | 4, four_channel_mpeg_40b, "MPEG 4.0 B (C, L, R, Cs)" },
    {   (132 << 16) | 4, four_channel_itu_23, "ITU 2.3 (L, R, Ls, Rs)" },
    {   (134 << 16) | 4, four_channel_dvd_5, "DVD 5 (L, R, LFE, Cs)" },
    {   (136 << 16) | 4, four_channel_dvd_10, "DVD 10 (L, R, C, LFE)" }
}
five_channel_pentagonal
const int five_channel_pentagonal[5] static
Initial value:
=
    {   SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_RIGHT, SF_CHANNEL_MAP_REAR_LEFT, SF_CHANNEL_MAP_REAR_RIGHT, SF_CHANNEL_MAP_CENTER }
five_channel_mpeg_50_a
const int five_channel_mpeg_50_a[5] static
Initial value:
=
    {   SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_RIGHT, SF_CHANNEL_MAP_CENTER, SF_CHANNEL_MAP_REAR_LEFT, SF_CHANNEL_MAP_REAR_RIGHT }
five_channel_mpeg_50_b
const int five_channel_mpeg_50_b[5] static
Initial value:
=
    {   SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_RIGHT, SF_CHANNEL_MAP_REAR_LEFT, SF_CHANNEL_MAP_REAR_RIGHT, SF_CHANNEL_MAP_CENTER }
five_channel_mpeg_50_c
const int five_channel_mpeg_50_c[5] static
Initial value:
=
    {   SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_CENTER, SF_CHANNEL_MAP_RIGHT, SF_CHANNEL_MAP_REAR_LEFT, SF_CHANNEL_MAP_REAR_RIGHT }
five_channel_mpeg_50_d
const int five_channel_mpeg_50_d[5] static
Initial value:
=
    {   SF_CHANNEL_MAP_CENTER, SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_RIGHT, SF_CHANNEL_MAP_REAR_LEFT, SF_CHANNEL_MAP_REAR_RIGHT }
five_channel_dvd_6
const int five_channel_dvd_6[5] static
Initial value:
=
    {   SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_RIGHT, SF_CHANNEL_MAP_LFE, SF_CHANNEL_MAP_REAR_LEFT, SF_CHANNEL_MAP_REAR_RIGHT }
five_channel_dvd_11
const int five_channel_dvd_11[5] static
Initial value:
=
    {   SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_RIGHT, SF_CHANNEL_MAP_CENTER, SF_CHANNEL_MAP_LFE, SF_CHANNEL_MAP_REAR_CENTER }
five_channel_dvd_18
const int five_channel_dvd_18[5] static
Initial value:
=
    {   SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_RIGHT, SF_CHANNEL_MAP_REAR_LEFT, SF_CHANNEL_MAP_REAR_RIGHT, SF_CHANNEL_MAP_LFE }
five_chan
const AIFF_CAF_CHANNEL_MAP five_chan[] static
Initial value:
=
{   {   (109 << 16) | 5, five_channel_pentagonal, "pentagonal (L,  R, Lrear, Rrear, C)" },
    {   (117 << 16) | 5, five_channel_mpeg_50_a, "MPEG 5.0 A (L, R, C, Ls, Rs)" },
    {   (118 << 16) | 5, five_channel_mpeg_50_b, "MPEG 5.0 B (L, R, Ls, Rs, C)" },
    {   (119 << 16) | 5, five_channel_mpeg_50_c, "MPEG 5.0 C (L, C, R, Ls, Rs,)" },
    {   (120 << 16) | 5, five_channel_mpeg_50_d, "MPEG 5.0 D (C, L, R, Ls, Rs)" },
    {   (135 << 16) | 5, five_channel_dvd_6, "DVD 6 (L, R, LFE, Ls, Rs)" },
    {   (137 << 16) | 5, five_channel_dvd_11, "DVD 11 (L, R, C, LFE, Cs)" },
    {   (138 << 16) | 5, five_channel_dvd_18, "DVD 18 (L, R, Ls, Rs, LFE)" }
}
six_channel_mpeg_51_a
const int six_channel_mpeg_51_a[6] static
Initial value:
=
    {   SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_RIGHT, SF_CHANNEL_MAP_CENTER, SF_CHANNEL_MAP_LFE, SF_CHANNEL_MAP_REAR_LEFT, SF_CHANNEL_MAP_REAR_RIGHT }
six_channel_mpeg_51_b
const int six_channel_mpeg_51_b[6] static
Initial value:
=
    {   SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_RIGHT, SF_CHANNEL_MAP_REAR_LEFT, SF_CHANNEL_MAP_REAR_RIGHT, SF_CHANNEL_MAP_CENTER, SF_CHANNEL_MAP_LFE }
six_channel_mpeg_51_c
const int six_channel_mpeg_51_c[6] static
Initial value:
=
    {   SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_CENTER, SF_CHANNEL_MAP_RIGHT, SF_CHANNEL_MAP_REAR_LEFT, SF_CHANNEL_MAP_REAR_RIGHT, SF_CHANNEL_MAP_LFE }
six_channel_mpeg_51_d
const int six_channel_mpeg_51_d[6] static
Initial value:
=
    {   SF_CHANNEL_MAP_CENTER, SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_RIGHT, SF_CHANNEL_MAP_REAR_LEFT, SF_CHANNEL_MAP_REAR_RIGHT, SF_CHANNEL_MAP_LFE }
six_channel_audio_unit_60
const int six_channel_audio_unit_60[6] static
Initial value:
=
    {   SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_RIGHT, SF_CHANNEL_MAP_REAR_LEFT, SF_CHANNEL_MAP_REAR_RIGHT, SF_CHANNEL_MAP_CENTER, SF_CHANNEL_MAP_REAR_CENTER }
six_channel_aac_60
const int six_channel_aac_60[6] static
Initial value:
=
    {   SF_CHANNEL_MAP_CENTER, SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_RIGHT, SF_CHANNEL_MAP_REAR_LEFT, SF_CHANNEL_MAP_REAR_RIGHT, SF_CHANNEL_MAP_REAR_CENTER }
six_chan
const AIFF_CAF_CHANNEL_MAP six_chan[] static
Initial value:
=
{   {   (110 << 16) | 6, NULL, "hexagonal (L, R, Lr, Rr, C, Rear)" },
    {   (121 << 16) | 6, six_channel_mpeg_51_a, "MPEG 5.1 A (L, R, C, LFE, Ls, Rs)" },
    {   (122 << 16) | 6, six_channel_mpeg_51_b, "MPEG 5.1 B (L, R, Ls, Rs, C, LFE)" },
    {   (123 << 16) | 6, six_channel_mpeg_51_c, "MPEG 5.1 C (L, C, R, Ls, Rs, LFE)" },
    {   (124 << 16) | 6, six_channel_mpeg_51_d, "MPEG 5.1 D (C, L, R, Ls, Rs, LFE)" },
    {   (139 << 16) | 6, six_channel_audio_unit_60, "AudioUnit 6.0 (L, R, Ls, Rs, C, Cs)" },
    {   (141 << 16) | 6, six_channel_aac_60, "AAC 6.0 (C, L, R, Ls, Rs, Cs)" }
}
six_channel_mpeg_61a
const int six_channel_mpeg_61a[7] static
Initial value:
=
    {   SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_RIGHT, SF_CHANNEL_MAP_CENTER, SF_CHANNEL_MAP_LFE, SF_CHANNEL_MAP_REAR_LEFT, SF_CHANNEL_MAP_REAR_RIGHT, SF_CHANNEL_MAP_REAR_CENTER }
six_channel_aac_61
const int six_channel_aac_61[7] static
Initial value:
=
    {   SF_CHANNEL_MAP_CENTER, SF_CHANNEL_MAP_LEFT, SF_CHANNEL_MAP_RIGHT, SF_CHANNEL_MAP_REAR_LEFT, SF_CHANNEL_MAP_REAR_RIGHT, SF_CHANNEL_MAP_REAR_CENTER, SF_CHANNEL_MAP_LFE }
seven_chan
const AIFF_CAF_CHANNEL_MAP seven_chan[] static
Initial value:
=
{   {   (125 << 16) | 7, six_channel_mpeg_61a, "MPEG 6.1 A (L, R, C, LFE, Ls, Rs, Cs)" },
    {   (140 << 16) | 7, NULL, "AudioUnit 7.0 (L, R, Ls, Rs, C, Rls, Rrs)" },
    {   (142 << 16) | 7, six_channel_aac_61, "AAC 6.1 (C, L, R, Ls, Rs, Cs, Lfe)" },
    {   (143 << 16) | 7, NULL, "AAC 7.0 (C, L, R, Ls, Rs, Rls, Rrs,)" }
}
eight_chan
const AIFF_CAF_CHANNEL_MAP eight_chan[] static
Initial value:
=
{   {   (111 << 16) | 8, NULL,
        "octagonal (Lf, Rf, Lr, Rr, Cf, Cr, Ls, Rs)"
        },
    {   (112 << 16) | 8, NULL,
        "cube (L, R, Lrear, Rrear, Ltop, Rtop, Ltoprear, Rtoprear)"
        },
    {   (126 << 16) | 8, NULL, "MPEG 7.1 A (L, R, C, LFE, Ls, Rs, Lc, Rc)" },
    {   (127 << 16) | 8, NULL, "MPEG 7.1 B (C, Lc, Rc, L, R, Ls, Rs, LFE)" },
    {   (128 << 16) | 8, NULL, "MPEG 7.1 C (L, R, C, LFE, Ls, R, Rls, Rrs)" },
    {   (129 << 16) | 8, NULL, "Emagic Default 7.1 (L, R, Ls, Rs, C, LFE, Lc, Rc)" },
    {   (130 << 16) | 8, NULL,
        "SMPTE DTV (L, R, C, LFE, Ls, Rs, Lt, Rt)"
        },
    {   (144 << 16) | 8, NULL, "AAC octagonal (C, L, R, Ls, Rs, Rls, Rrs, Cs)" }
}
map
const MAP_MAP map[] static
Initial value:
=
{   { zero_chan,    ARRAY_LEN (zero_chan) },
    { one_chan,     ARRAY_LEN (one_chan) },
    { two_chan,     ARRAY_LEN (two_chan) },
    { three_chan,   ARRAY_LEN (three_chan) },
    { four_chan,    ARRAY_LEN (four_chan) },
    { five_chan,    ARRAY_LEN (five_chan) },
    { six_chan,     ARRAY_LEN (six_chan) },
    { seven_chan,   ARRAY_LEN (seven_chan) },
    { eight_chan,   ARRAY_LEN (eight_chan) }
}
Referenced by aiff_caf_find_channel_layout_tag(), aiff_caf_of_channel_layout_tag(), glloader.lang.common.generator.Generator::commandline(), glloader.parse.Spec::features(), glloader.lang.common.generator.Generator::header(), glloader.__main__::main(), and glloader.lang.common.generator.Generator::online().