Aurora Framework: Draw.cpp File Reference
Draw.cpp File Reference
Macros
#define GetCurrentClipRect() (_ClipRectStack.Size ? _ClipRectStack.Data[_ClipRectStack.Size-1] : _Data->ClipRectFullscreen)
#define GetCurrentTextureId() (_TextureIdStack.Size ? _TextureIdStack.Data[_TextureIdStack.Size-1] : NULL)
#define IMGUI_DEFINE_MATH_OPERATORS
#define stb__in2(x) ((i[x] << 8) + i[(x)+1])
#define stb__in3(x) ((i[x] << 16) + stb__in2((x)+1))
#define stb__in4(x) ((i[x] << 24) + stb__in3((x)+1))
#define STB_RECT_PACK_IMPLEMENTATION
#define STB_TRUETYPE_IMPLEMENTATION
#define STBRP_ASSERT(x) IM_ASSERT(x)
#define STBRP_STATIC
#define STBTT_assert(x) IM_ASSERT(x)
#define STBTT_free(x, u) ((void)(u), ImGui::MemFree(x))
#define STBTT_malloc(x, u) ((void)(u), ImGui::MemAlloc(x))
#define STBTT_STATIC
Functions
static void Decode85 (const unsigned char *src, unsigned char *dst)
static unsigned int Decode85Byte (char c)
static const char * GetDefaultCompressedFontDataTTFBase85 ()
static float ImAcos01 (float x)
void ImFontAtlasBuildFinish (ImFontAtlas *atlas)
void ImFontAtlasBuildMultiplyCalcLookupTable (unsigned char out_table[256], float in_brighten_factor)
void ImFontAtlasBuildMultiplyRectAlpha8 (const unsigned char table[256], unsigned char *pixels, int x, int y, int w, int h, int stride)
void ImFontAtlasBuildPackCustomRects (ImFontAtlas *atlas, void *pack_context_opaque)
void ImFontAtlasBuildRegisterDefaultCustomRects (ImFontAtlas *atlas)
static void ImFontAtlasBuildRenderDefaultTexData (ImFontAtlas *atlas)
void ImFontAtlasBuildSetupFont (ImFontAtlas *atlas, ImFont *font, ImFontConfig *font_config, float ascent, float descent)
bool ImFontAtlasBuildWithStbTruetype (ImFontAtlas *atlas)
static void PathBezierToCasteljau (ImVector< ImVec2 > *path, float x1, float y1, float x2, float y2, float x3, float y3, float x4, float y4, float tess_tol, int level)
static void stb__lit (unsigned char *data, unsigned int length)
static void stb__match (unsigned char *data, unsigned int length)
static unsigned int stb_adler32 (unsigned int adler32, unsigned char *buffer, unsigned int buflen)
static unsigned int stb_decompress (unsigned char *output, unsigned char *i, unsigned int length)
static unsigned int stb_decompress_length (unsigned char *input)
static unsigned char * stb_decompress_token (unsigned char *i)
Variables
static const ImVec2 FONT_ATLAS_DEFAULT_TEX_CURSOR_DATA [ImGuiMouseCursor_Count_][3]
const int FONT_ATLAS_DEFAULT_TEX_DATA_H = 27
const unsigned int FONT_ATLAS_DEFAULT_TEX_DATA_ID = 0x80000000
static const char FONT_ATLAS_DEFAULT_TEX_DATA_PIXELS [FONT_ATLAS_DEFAULT_TEX_DATA_W_HALF *FONT_ATLAS_DEFAULT_TEX_DATA_H+1]
const int FONT_ATLAS_DEFAULT_TEX_DATA_W_HALF = 90
static const char proggy_clean_ttf_compressed_data_base85 [11980+1]
static unsigned char * stb__barrier
static unsigned char * stb__barrier2
static unsigned char * stb__barrier3
static unsigned char * stb__barrier4
static unsigned char * stb__dout
Macro Definition Documentation
IMGUI_DEFINE_MATH_OPERATORS
#define IMGUI_DEFINE_MATH_OPERATORS
STBRP_ASSERT
#define STBRP_ASSERT (x) IM_ASSERT(x)
STBRP_STATIC
#define STBRP_STATIC
STB_RECT_PACK_IMPLEMENTATION
#define STB_RECT_PACK_IMPLEMENTATION
STBTT_malloc
#define STBTT_malloc (x, u) ((void)(u), ImGui::MemAlloc(x))
STBTT_free
#define STBTT_free (x, u) ((void)(u), ImGui::MemFree(x))
STBTT_assert
#define STBTT_assert (x) IM_ASSERT(x)
STBTT_STATIC
#define STBTT_STATIC
STB_TRUETYPE_IMPLEMENTATION
#define STB_TRUETYPE_IMPLEMENTATION
GetCurrentClipRect
#define GetCurrentClipRect () (_ClipRectStack.Size ? _ClipRectStack.Data[_ClipRectStack.Size-1] : _Data->ClipRectFullscreen)
Referenced by ImDrawList::AddDrawCmd(), ImDrawList::UpdateClipRect(), and ImDrawList::UpdateTextureID().
GetCurrentTextureId
#define GetCurrentTextureId () (_TextureIdStack.Size ? _TextureIdStack.Data[_TextureIdStack.Size-1] : NULL)
Referenced by ImDrawList::AddDrawCmd(), ImDrawList::UpdateClipRect(), and ImDrawList::UpdateTextureID().
stb__in2
#define stb__in2 (x) ((i[x] << 8) + i[(x)+1])
Referenced by stb_decompress_token().
stb__in3
#define stb__in3 (x) ((i[x] << 16) + stb__in2((x)+1))
Referenced by stb_decompress_token().
stb__in4
#define stb__in4 (x) ((i[x] << 24) + stb__in3((x)+1))
Referenced by stb_decompress().
Function Documentation
PathBezierToCasteljau()
static void PathBezierToCasteljau (ImVector< ImVec2 > * path, float x1, float y1, float x2, float y2, float x3, float y3, float x4, float y4, float tess_tol, int level) static
References ImVector< T >::push_back().
Referenced by ImDrawList::PathBezierCurveTo().
stb_decompress_length()
static unsigned int stb_decompress_length (unsigned char * input) static
Referenced by ImFontAtlas::AddFontFromMemoryCompressedTTF(), and stb_decompress().
stb_decompress()
static unsigned int stb_decompress (unsigned char * output, unsigned char * i, unsigned int length) static
References IM_ASSERT, stb__barrier, stb__barrier2, stb__barrier3, stb__barrier4, stb__dout, stb__in4, stb_adler32(), stb_decompress_length(), and stb_decompress_token().
Referenced by ImFontAtlas::AddFontFromMemoryCompressedTTF().
GetDefaultCompressedFontDataTTFBase85()
static const char * GetDefaultCompressedFontDataTTFBase85 () static
References proggy_clean_ttf_compressed_data_base85.
Referenced by ImFontAtlas::AddFontDefault().
Decode85Byte()
static unsigned int Decode85Byte (char c) static
Referenced by Decode85().
Decode85()
static void Decode85 (const unsigned char * src, unsigned char * dst) static
References Decode85Byte().
Referenced by ImFontAtlas::AddFontFromMemoryCompressedBase85TTF().
ImFontAtlasBuildMultiplyCalcLookupTable()
void ImFontAtlasBuildMultiplyCalcLookupTable (unsigned char out_table[256], float in_brighten_factor)
References value.
Referenced by ImFontAtlasBuildWithStbTruetype().
ImFontAtlasBuildMultiplyRectAlpha8()
void ImFontAtlasBuildMultiplyRectAlpha8 (const unsigned char table[256], unsigned char * pixels, int x, int y, int w, int h, int stride)
Referenced by ImFontAtlasBuildWithStbTruetype().
ImFontAtlasBuildWithStbTruetype()
bool ImFontAtlasBuildWithStbTruetype (ImFontAtlas * atlas)
References ImFont::AddGlyph(), ImFont::Ascent, stbtt_pack_range::chardata_for_range, ImFontAtlas::ClearTexData(), ImFontAtlas::ConfigData, ImFont::ContainerAtlas, ImFontConfig::DstFont, ImFont::FindGlyph(), stbtt_pack_range::first_unicode_codepoint_in_range, ImFontAtlas::Flags, stbtt_pack_range::font_size, ImFontConfig::FontData, ImFontConfig::FontNo, ImFontAtlas::GetGlyphRangesDefault(), ImFontConfig::GlyphOffset, ImFontConfig::GlyphRanges, stbtt_pack_context::height, IM_ASSERT, ImFontAtlasBuildFinish(), ImFontAtlasBuildMultiplyCalcLookupTable(), ImFontAtlasBuildMultiplyRectAlpha8(), ImFontAtlasBuildPackCustomRects(), ImFontAtlasBuildRegisterDefaultCustomRects(), ImFontAtlasBuildSetupFont(), ImFontAtlasFlags_NoPowerOfTwoHeight, ImMax(), ImUpperPowerOfTwo(), ImFont::IsLoaded(), ImGui::MemAlloc(), ImGui::MemFree(), memset(), ImFontConfig::MergeMode, NULL, stbtt_pack_range::num_chars, ImFontConfig::OversampleH, ImFontConfig::OversampleV, stbtt_pack_context::pack_info, stbtt_pack_context::pixels, ImFontConfig::RasterizerMultiply, stbtt_aligned_quad::s0, stbtt_aligned_quad::s1, ImVector< T >::Size, ImFontConfig::SizePixels, stbrp_pack_rects(), stbtt_GetFontOffsetForIndex(), stbtt_GetFontVMetrics(), stbtt_GetPackedQuad(), stbtt_InitFont(), stbtt_PackBegin(), stbtt_PackEnd(), stbtt_PackFontRangesGatherRects(), stbtt_PackFontRangesRenderIntoRects(), stbtt_PackSetOversampling(), stbtt_ScaleForPixelHeight(), stbtt_pack_context::stride_in_bytes, stbtt_aligned_quad::t0, stbtt_aligned_quad::t1, ImFontAtlas::TexDesiredWidth, ImFontAtlas::TexGlyphPadding, ImFontAtlas::TexHeight, ImFontAtlas::TexID, ImFontAtlas::TexPixelsAlpha8, ImFontAtlas::TexUvScale, ImFontAtlas::TexUvWhitePixel, ImFontAtlas::TexWidth, ImVec2::x, stbtt_aligned_quad::x0, stbtt_packedchar::x0, stbtt_aligned_quad::x1, stbtt_packedchar::x1, stbtt_packedchar::xadvance, ImVec2::y, stbtt_aligned_quad::y0, stbtt_packedchar::y0, stbtt_aligned_quad::y1, and stbtt_packedchar::y1.
Referenced by ImFontAtlas::Build().
ImFontAtlasBuildRegisterDefaultCustomRects()
void ImFontAtlasBuildRegisterDefaultCustomRects (ImFontAtlas * atlas)
References ImFontAtlas::AddCustomRectRegular(), ImFontAtlas::CustomRectIds, ImFontAtlas::Flags, FONT_ATLAS_DEFAULT_TEX_DATA_H, FONT_ATLAS_DEFAULT_TEX_DATA_ID, FONT_ATLAS_DEFAULT_TEX_DATA_W_HALF, and ImFontAtlasFlags_NoMouseCursors.
Referenced by ImFontAtlasBuildWithStbTruetype().
ImFontAtlasBuildSetupFont()
void ImFontAtlasBuildSetupFont (ImFontAtlas * atlas, ImFont * font, ImFontConfig * font_config, float ascent, float descent)
References ImFont::Ascent, ImFont::ClearOutputData(), ImFont::ConfigData, ImFont::ConfigDataCount, ImFont::ContainerAtlas, ImFont::Descent, ImFont::FontSize, ImFontConfig::MergeMode, and ImFontConfig::SizePixels.
Referenced by ImFontAtlasBuildWithStbTruetype().
ImFontAtlasBuildPackCustomRects()
void ImFontAtlasBuildPackCustomRects (ImFontAtlas * atlas, void * pack_context_opaque)
References ImFontAtlas::CustomRects, ImVector< T >::Data, IM_ASSERT, ImMax(), memset(), ImVector< T >::resize(), ImVector< T >::Size, stbrp_pack_rects(), and ImFontAtlas::TexHeight.
Referenced by ImFontAtlasBuildWithStbTruetype().
ImFontAtlasBuildRenderDefaultTexData()
static void ImFontAtlasBuildRenderDefaultTexData (ImFontAtlas * atlas) static
References ImFontAtlas::CustomRectIds, ImFontAtlas::CustomRects, ImFontAtlas::Flags, FONT_ATLAS_DEFAULT_TEX_DATA_H, FONT_ATLAS_DEFAULT_TEX_DATA_ID, FONT_ATLAS_DEFAULT_TEX_DATA_PIXELS, FONT_ATLAS_DEFAULT_TEX_DATA_W_HALF, ImFontAtlas::CustomRect::Height, ImFontAtlas::CustomRect::ID, IM_ASSERT, ImFontAtlasFlags_NoMouseCursors, ImFontAtlas::CustomRect::IsPacked(), NULL, ImFontAtlas::TexPixelsAlpha8, ImFontAtlas::TexUvScale, ImFontAtlas::TexUvWhitePixel, ImFontAtlas::TexWidth, ImFontAtlas::CustomRect::Width, ImVec2::x, ImFontAtlas::CustomRect::X, ImVec2::y, and ImFontAtlas::CustomRect::Y.
Referenced by ImFontAtlasBuildFinish().
ImFontAtlasBuildFinish()
void ImFontAtlasBuildFinish (ImFontAtlas * atlas)
References ImFont::AddGlyph(), ImFontAtlas::CalcCustomRectUV(), ImFont::ContainerAtlas, ImFontAtlas::CustomRects, ImFontAtlas::CustomRect::Font, ImFontAtlas::Fonts, ImFontAtlas::CustomRect::GlyphAdvanceX, ImFontAtlas::CustomRect::GlyphOffset, ImFontAtlas::CustomRect::Height, ImFontAtlas::CustomRect::ID, IM_ASSERT, ImFontAtlasBuildRenderDefaultTexData(), NULL, ImVector< T >::Size, ImFontAtlas::CustomRect::Width, ImVec2::x, and ImVec2::y.
Referenced by ImFontAtlasBuildWithStbTruetype().
ImAcos01()
static float ImAcos01 (float x) inline static
References IM_PI.
Referenced by ImGui::RenderRectFilledRangeH().
stb__match()
static void stb__match (unsigned char * data, unsigned int length) static
References IM_ASSERT, stb__barrier, stb__barrier4, and stb__dout.
Referenced by stb_decompress_token().
stb__lit()
static void stb__lit (unsigned char * data, unsigned int length) static
References IM_ASSERT, memcpy(), stb__barrier, stb__barrier2, and stb__dout.
Referenced by stb_decompress_token().
stb_decompress_token()
static unsigned char* stb_decompress_token (unsigned char * i) static
References stb__dout, stb__in2, stb__in3, stb__lit(), and stb__match().
Referenced by stb_decompress().
stb_adler32()
static unsigned int stb_adler32 (unsigned int adler32, unsigned char * buffer, unsigned int buflen) static
Referenced by stb_decompress().
Variable Documentation
FONT_ATLAS_DEFAULT_TEX_DATA_W_HALF
const int FONT_ATLAS_DEFAULT_TEX_DATA_W_HALF = 90
Referenced by ImFontAtlas::GetMouseCursorTexData(), ImFontAtlasBuildRegisterDefaultCustomRects(), and ImFontAtlasBuildRenderDefaultTexData().
FONT_ATLAS_DEFAULT_TEX_DATA_H
const int FONT_ATLAS_DEFAULT_TEX_DATA_H = 27
Referenced by ImFontAtlasBuildRegisterDefaultCustomRects(), and ImFontAtlasBuildRenderDefaultTexData().
FONT_ATLAS_DEFAULT_TEX_DATA_ID
const unsigned int FONT_ATLAS_DEFAULT_TEX_DATA_ID = 0x80000000
Referenced by ImFontAtlas::GetMouseCursorTexData(), ImFontAtlasBuildRegisterDefaultCustomRects(), and ImFontAtlasBuildRenderDefaultTexData().
FONT_ATLAS_DEFAULT_TEX_DATA_PIXELS
const char FONT_ATLAS_DEFAULT_TEX_DATA_PIXELS[FONT_ATLAS_DEFAULT_TEX_DATA_W_HALF *FONT_ATLAS_DEFAULT_TEX_DATA_H+1] static
Initial value:
=
{
    "..-         -XXXXXXX-    X    -           X           -XXXXXXX          -          XXXXXXX"
    "..-         -X.....X-   X.X   -          X.X          -X.....X          -          X.....X"
    "---         -XXX.XXX-  X...X  -         X...X         -X....X           -           X....X"
    "X           -  X.X  - X.....X -        X.....X        -X...X            -            X...X"
    "XX          -  X.X  -X.......X-       X.......X       -X..X.X           -           X.X..X"
    "X.X         -  X.X  -XXXX.XXXX-       XXXX.XXXX       -X.X X.X          -          X.X X.X"
    "X..X        -  X.X  -   X.X   -          X.X          -XX   X.X         -         X.X   XX"
    "X...X       -  X.X  -   X.X   -    XX    X.X    XX    -      X.X        -        X.X      "
    "X....X      -  X.X  -   X.X   -   X.X    X.X    X.X   -       X.X       -       X.X       "
    "X.....X     -  X.X  -   X.X   -  X..X    X.X    X..X  -        X.X      -      X.X        "
    "X......X    -  X.X  -   X.X   - X...XXXXXX.XXXXXX...X -         X.X   XX-XX   X.X         "
    "X.......X   -  X.X  -   X.X   -X.....................X-          X.X X.X-X.X X.X          "
    "X........X  -  X.X  -   X.X   - X...XXXXXX.XXXXXX...X -           X.X..X-X..X.X           "
    "X.........X -XXX.XXX-   X.X   -  X..X    X.X    X..X  -            X...X-X...X            "
    "X..........X-X.....X-   X.X   -   X.X    X.X    X.X   -           X....X-X....X           "
    "X......XXXXX-XXXXXXX-   X.X   -    XX    X.X    XX    -          X.....X-X.....X          "
    "X...X..X    ---------   X.X   -          X.X          -          XXXXXXX-XXXXXXX          "
    "X..X X..X   -       -XXXX.XXXX-       XXXX.XXXX       ------------------------------------"
    "X.X  X..X   -       -X.......X-       X.......X       -    XX           XX    -           "
    "XX    X..X  -       - X.....X -        X.....X        -   X.X           X.X   -           "
    "      X..X          -  X...X  -         X...X         -  X..X           X..X  -           "
    "       XX           -   X.X   -          X.X          - X...XXXXXXXXXXXXX...X -           "
    "------------        -    X    -           X           -X.....................X-           "
    "                    ----------------------------------- X...XXXXXXXXXXXXX...X -           "
    "                                                      -  X..X           X..X  -           "
    "                                                      -   X.X           X.X   -           "
    "                                                      -    XX           XX    -           "
}
Referenced by ImFontAtlasBuildRenderDefaultTexData().
FONT_ATLAS_DEFAULT_TEX_CURSOR_DATA
const ImVec2 FONT_ATLAS_DEFAULT_TEX_CURSOR_DATA[ImGuiMouseCursor_Count_][3] static
Initial value:
=
{
    { ImVec2(0,3),  ImVec2(12,19), ImVec2( 0, 0) },
    { ImVec2(13,0), ImVec2(7,16),  ImVec2( 4, 8) },
    { ImVec2(31,0), ImVec2(23,23), ImVec2(11,11) },
    { ImVec2(21,0), ImVec2( 9,23), ImVec2( 5,11) },
    { ImVec2(55,18),ImVec2(23, 9), ImVec2(11, 5) },
    { ImVec2(73,0), ImVec2(17,17), ImVec2( 9, 9) },
    { ImVec2(55,0), ImVec2(17,17), ImVec2( 9, 9) },
}
Referenced by ImFontAtlas::GetMouseCursorTexData().
stb__barrier
unsigned char* stb__barrier static
Referenced by stb__lit(), stb__match(), and stb_decompress().
stb__barrier2
unsigned char * stb__barrier2 static
Referenced by stb__lit(), and stb_decompress().
stb__barrier3
unsigned char * stb__barrier3 static
Referenced by stb_decompress().
stb__barrier4
unsigned char * stb__barrier4 static
Referenced by stb__match(), and stb_decompress().
stb__dout
unsigned char* stb__dout static
Referenced by stb__lit(), stb__match(), stb_decompress(), and stb_decompress_token().
proggy_clean_ttf_compressed_data_base85
const char proggy_clean_ttf_compressed_data_base85[11980+1] static
Referenced by GetDefaultCompressedFontDataTTFBase85().