Aurora Framework: dwvw.c File Reference
dwvw.c File Reference
Classes
struct DWVW_PRIVATE
Macros
#define HIGHEST_BIT(x, count)
Functions
static int dwvw_byterate (SF_PRIVATE *psf)
static int dwvw_close (SF_PRIVATE *psf)
static int dwvw_decode_data (SF_PRIVATE *psf, DWVW_PRIVATE *pdwvw, int *ptr, int len)
static int dwvw_decode_load_bits (SF_PRIVATE *psf, DWVW_PRIVATE *pdwvw, int bit_count)
static int dwvw_encode_data (SF_PRIVATE *psf, DWVW_PRIVATE *pdwvw, const int *ptr, int len)
static void dwvw_encode_store_bits (SF_PRIVATE *psf, DWVW_PRIVATE *pdwvw, int data, int new_bits)
int dwvw_init (SF_PRIVATE *psf, int bitwidth)
static sf_count_t dwvw_read_d (SF_PRIVATE *psf, double *ptr, sf_count_t len)
static sf_count_t dwvw_read_f (SF_PRIVATE *psf, float *ptr, sf_count_t len)
static sf_count_t dwvw_read_i (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static void dwvw_read_reset (DWVW_PRIVATE *pdwvw)
static sf_count_t dwvw_read_s (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static sf_count_t dwvw_seek (SF_PRIVATE *psf, int mode, sf_count_t offset)
static sf_count_t dwvw_seek (SF_PRIVATE *psf, int UNUSED(mode), sf_count_t offset)
static sf_count_t dwvw_write_d (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
static sf_count_t dwvw_write_f (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
static sf_count_t dwvw_write_i (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
static sf_count_t dwvw_write_s (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
Macro Definition Documentation
HIGHEST_BIT
#define HIGHEST_BIT (x, count)
Value:
{   int y = x ;         \
                (count) = 0 ;       \
                while (y)           \
                {   (count) ++ ;    \
                    y >>= 1 ;       \
                    } ;             \
                } ;
Referenced by dwvw_encode_data().
Function Documentation
dwvw_read_s()
static sf_count_t dwvw_read_s (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, dwvw_decode_data(), and BUF_UNION::ibuf.
Referenced by dwvw_init().
dwvw_read_i()
static sf_count_t dwvw_read_i (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
References sf_private_tag::codec_data, and dwvw_decode_data().
Referenced by dwvw_init().
dwvw_read_f()
static sf_count_t dwvw_read_f (SF_PRIVATE * psf, float * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, dwvw_decode_data(), BUF_UNION::ibuf, and sf_private_tag::norm_float.
Referenced by dwvw_init().
dwvw_read_d()
static sf_count_t dwvw_read_d (SF_PRIVATE * psf, double * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, dwvw_decode_data(), BUF_UNION::ibuf, and sf_private_tag::norm_double.
Referenced by dwvw_init().
dwvw_write_s()
static sf_count_t dwvw_write_s (SF_PRIVATE * psf, const short * ptr, sf_count_t len) static
References arith_shift_left(), ARRAY_LEN, sf_private_tag::codec_data, dwvw_encode_data(), and BUF_UNION::ibuf.
Referenced by dwvw_init().
dwvw_write_i()
static sf_count_t dwvw_write_i (SF_PRIVATE * psf, const int * ptr, sf_count_t len) static
References sf_private_tag::codec_data, and dwvw_encode_data().
Referenced by dwvw_init().
dwvw_write_f()
static sf_count_t dwvw_write_f (SF_PRIVATE * psf, const float * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, dwvw_encode_data(), BUF_UNION::ibuf, and sf_private_tag::norm_float.
Referenced by dwvw_init().
dwvw_write_d()
static sf_count_t dwvw_write_d (SF_PRIVATE * psf, const double * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, dwvw_encode_data(), BUF_UNION::ibuf, and sf_private_tag::norm_double.
Referenced by dwvw_init().
dwvw_seek() [1/2]
static sf_count_t dwvw_seek (SF_PRIVATE * psf, int mode, sf_count_t offset) static
Referenced by dwvw_init().
dwvw_close()
static int dwvw_close (SF_PRIVATE * psf) static
References DWVW_PRIVATE::b, DWVW_PRIVATE::buffer, sf_private_tag::codec_data, dwvw_encode_data(), sf_private_tag::file, DWVW_PRIVATE::index, PSF_FILE::mode, NULL, psf_fwrite(), and sf_private_tag::write_header.
Referenced by dwvw_init().
dwvw_byterate()
static int dwvw_byterate (SF_PRIVATE * psf) static
References sf_private_tag::datalength, sf_private_tag::file, PSF_FILE::mode, and sf_private_tag::sf.
Referenced by dwvw_init().
dwvw_decode_data()
static int dwvw_decode_data (SF_PRIVATE * psf, DWVW_PRIVATE * pdwvw, int * ptr, int len) static
References arith_shift_left(), DWVW_PRIVATE::b, DWVW_PRIVATE::bit_count, DWVW_PRIVATE::bit_width, dwvw_decode_load_bits(), DWVW_PRIVATE::end, DWVW_PRIVATE::last_delta_width, DWVW_PRIVATE::last_sample, DWVW_PRIVATE::max_delta, DWVW_PRIVATE::samplecount, and DWVW_PRIVATE::span.
Referenced by dwvw_read_d(), dwvw_read_f(), dwvw_read_i(), and dwvw_read_s().
dwvw_decode_load_bits()
static int dwvw_decode_load_bits (SF_PRIVATE * psf, DWVW_PRIVATE * pdwvw, int bit_count) static
References arith_shift_left(), DWVW_PRIVATE::b, DWVW_PRIVATE::bit_count, DWVW_PRIVATE::bits, DWVW_PRIVATE::buffer, DWVW_PRIVATE::dwm_maxsize, DWVW_PRIVATE::end, DWVW_PRIVATE::index, and psf_fread().
Referenced by dwvw_decode_data().
dwvw_encode_data()
static int dwvw_encode_data (SF_PRIVATE * psf, DWVW_PRIVATE * pdwvw, const int * ptr, int len) static
References DWVW_PRIVATE::bit_width, DWVW_PRIVATE::dwm_maxsize, dwvw_encode_store_bits(), HIGHEST_BIT, DWVW_PRIVATE::last_delta_width, DWVW_PRIVATE::last_sample, DWVW_PRIVATE::max_delta, DWVW_PRIVATE::samplecount, and DWVW_PRIVATE::span.
Referenced by dwvw_close(), dwvw_write_d(), dwvw_write_f(), dwvw_write_i(), and dwvw_write_s().
dwvw_encode_store_bits()
static void dwvw_encode_store_bits (SF_PRIVATE * psf, DWVW_PRIVATE * pdwvw, int data, int new_bits) static
References arith_shift_left(), DWVW_PRIVATE::b, DWVW_PRIVATE::bit_count, DWVW_PRIVATE::bits, DWVW_PRIVATE::buffer, DWVW_PRIVATE::index, psf_fwrite(), and SIGNED_SIZEOF.
Referenced by dwvw_encode_data().
dwvw_read_reset()
static void dwvw_read_reset (DWVW_PRIVATE * pdwvw) static
References DWVW_PRIVATE::bit_width, DWVW_PRIVATE::dwm_maxsize, DWVW_PRIVATE::max_delta, memset(), and DWVW_PRIVATE::span.
Referenced by dwvw_init(), and dwvw_seek().
dwvw_init()
int dwvw_init (SF_PRIVATE * psf, int bitwidth)
References DWVW_PRIVATE::bit_width, sf_private_tag::byterate, sf_private_tag::codec_close, sf_private_tag::codec_data, dwvw_byterate(), dwvw_close(), dwvw_read_d(), dwvw_read_f(), dwvw_read_i(), dwvw_read_reset(), dwvw_read_s(), dwvw_seek(), dwvw_write_d(), dwvw_write_f(), dwvw_write_i(), dwvw_write_s(), sf_private_tag::file, PSF_FILE::mode, NULL, psf_decode_frame_count(), psf_log_printf(), sf_private_tag::read_double, sf_private_tag::read_float, sf_private_tag::read_int, sf_private_tag::read_short, sf_private_tag::seek, sf_private_tag::sf, SFE_BAD_MODE_RW, SFE_DWVW_BAD_BITWIDTH, SFE_INTERNAL, SFE_MALLOC_FAILED, sf_private_tag::write_double, sf_private_tag::write_float, sf_private_tag::write_int, and sf_private_tag::write_short.
Referenced by aiff_open(), and raw_open().
dwvw_seek() [2/2]
static sf_count_t dwvw_seek (SF_PRIVATE * psf, int UNUSEDmode, sf_count_t offset) static
References sf_private_tag::codec_data, sf_private_tag::dataoffset, dwvw_read_reset(), sf_private_tag::error, psf_fseek(), PSF_SEEK_ERROR, SFE_BAD_SEEK, and SFE_INTERNAL.