Aurora Framework: w64.c File Reference
w64.c File Reference
Macros
#define ACID_HASH16
#define bext_HASH16
#define data_HASH16
#define fact_HASH16
#define fmt_HASH16
#define junk_HASH16
#define levl_HASH16
#define list_HASH16
#define MAKE_HASH16(x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, xa, xb, xc, xd, xe, xf)
#define MAKE_MARKER16(name, x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, xa, xb, xc, xd, xe, xf)
#define MARKER_HASH16
#define riff_HASH16
#define SUMLIST_HASH16
#define wave_HASH16
Enumerations
enum {
HAVE_riff = 0x01, HAVE_wave = 0x02, HAVE_fmt = 0x04, HAVE_fact = 0x08,
HAVE_data = 0x20
}
Functions
MAKE_MARKER16 (riff_MARKER16, 'r', 'i', 'f', 'f', 0x2E, 0x91, 0xCF, 0x11, 0xA5, 0xD6, 0x28, 0xDB, 0x04, 0xC1, 0x00, 0x00)
MAKE_MARKER16 (wave_MARKER16, 'w', 'a', 'v', 'e', 0xF3, 0xAC, 0xD3, 0x11, 0x8C, 0xD1, 0x00, 0xC0, 0x4F, 0x8E, 0xDB, 0x8A)
MAKE_MARKER16 (fmt_MARKER16, 'f', 'm', 't', ' ', 0xF3, 0xAC, 0xD3, 0x11, 0x8C, 0xD1, 0x00, 0xC0, 0x4F, 0x8E, 0xDB, 0x8A)
MAKE_MARKER16 (fact_MARKER16, 'f', 'a', 'c', 't', 0xF3, 0xAC, 0xD3, 0x11, 0x8C, 0xD1, 0x00, 0xC0, 0x4F, 0x8E, 0xDB, 0x8A)
MAKE_MARKER16 (data_MARKER16, 'd', 'a', 't', 'a', 0xF3, 0xAC, 0xD3, 0x11, 0x8C, 0xD1, 0x00, 0xC0, 0x4F, 0x8E, 0xDB, 0x8A)
static int w64_close (SF_PRIVATE *psf)
int w64_open (SF_PRIVATE *psf)
static int w64_read_header (SF_PRIVATE *psf, int *blockalign, int *framesperblock)
static int w64_write_header (SF_PRIVATE *psf, int calc_length)
Macro Definition Documentation
MAKE_HASH16
#define MAKE_HASH16 (x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, xa, xb, xc, xd, xe, xf)
Value:
((x0)            ^ ((x1) << 1)   ^ ((x2) << 2)   ^ ((x3) << 3) ^ \
                ((x4) << 4)     ^ ((x5) << 5)   ^ ((x6) << 6)   ^ ((x7) << 7) ^ \
                ((x8) << 8)     ^ ((x9) << 9)   ^ ((xa) << 10)  ^ ((xb) << 11) ^ \
                ((xc) << 12)    ^ ((xd) << 13)  ^ ((xe) << 14)  ^ ((xf) << 15)  )
MAKE_MARKER16
#define MAKE_MARKER16 (name, x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, xa, xb, xc, xd, xe, xf)
Value:
static unsigned char name [16] = { (x0), (x1), (x2), (x3), (x4), (x5), \
                (x6), (x7), (x8), (x9), (xa), (xb), (xc), (xd), (xe), (xf) }
riff_HASH16
#define riff_HASH16
Value:
MAKE_HASH16 ('r', 'i', 'f', 'f', 0x2E, 0x91, 0xCF, 0x11, \
                                0xA5, 0xD6, 0x28, 0xDB, 0x04, 0xC1, 0x00, 0x00)
Referenced by w64_read_header().
wave_HASH16
#define wave_HASH16
Value:
MAKE_HASH16 ('w', 'a', 'v', 'e', 0xF3, 0xAC, 0xD3, 0x11, \
                                0x8C, 0xD1, 0x00, 0xC0, 0x4F, 0x8E, 0xDB, 0x8A)
Referenced by w64_read_header().
fmt_HASH16
#define fmt_HASH16
Value:
MAKE_HASH16 ('f', 'm', 't', ' ', 0xF3, 0xAC, 0xD3, 0x11, \
                                0x8C, 0xD1, 0x00, 0xC0, 0x4F, 0x8E, 0xDB, 0x8A)
Referenced by w64_read_header().
fact_HASH16
#define fact_HASH16
Value:
MAKE_HASH16 ('f', 'a', 'c', 't', 0xF3, 0xAC, 0xD3, 0x11, \
                                0x8C, 0xD1, 0x00, 0xC0, 0x4F, 0x8E, 0xDB, 0x8A)
Referenced by w64_read_header().
data_HASH16
#define data_HASH16
Value:
MAKE_HASH16 ('d', 'a', 't', 'a', 0xF3, 0xAC, 0xD3, 0x11, \
                                0x8C, 0xD1, 0x00, 0xC0, 0x4F, 0x8E, 0xDB, 0x8A)
Referenced by w64_read_header().
ACID_HASH16
#define ACID_HASH16
Value:
MAKE_HASH16 (0x6D, 0x07, 0x1C, 0xEA, 0xA3, 0xEF, 0x78, 0x4C, \
                                0x90, 0x57, 0x7F, 0x79, 0xEE, 0x25, 0x2A, 0xAE)
Referenced by w64_read_header().
levl_HASH16
#define levl_HASH16
Value:
MAKE_HASH16 (0x6c, 0x65, 0x76, 0x6c, 0xf3, 0xac, 0xd3, 0x11, \
                                0xd1, 0x8c, 0x00, 0xC0, 0x4F, 0x8E, 0xDB, 0x8A)
Referenced by w64_read_header().
list_HASH16
#define list_HASH16
Value:
MAKE_HASH16 (0x6C, 0x69, 0x73, 0x74, 0x2F, 0x91, 0xCF, 0x11, \
                                0xA5, 0xD6, 0x28, 0xDB, 0x04, 0xC1, 0x00, 0x00)
Referenced by w64_read_header().
junk_HASH16
#define junk_HASH16
Value:
MAKE_HASH16 (0x6A, 0x75, 0x6E, 0x6b, 0xF3, 0xAC, 0xD3, 0x11, \
                                0x8C, 0xD1, 0x00, 0xC0, 0x4f, 0x8E, 0xDB, 0x8A)
Referenced by w64_read_header().
bext_HASH16
#define bext_HASH16
Value:
MAKE_HASH16 (0x62, 0x65, 0x78, 0x74, 0xf3, 0xac, 0xd3, 0xaa, \
                                0xd1, 0x8c, 0x00, 0xC0, 0x4F, 0x8E, 0xDB, 0x8A)
Referenced by w64_read_header().
MARKER_HASH16
#define MARKER_HASH16
Value:
MAKE_HASH16 (0x56, 0x62, 0xf7, 0xab, 0x2d, 0x39, 0xd2, 0x11, \
                                0x86, 0xc7, 0x00, 0xc0, 0x4f, 0x8e, 0xdb, 0x8a)
Referenced by w64_read_header().
SUMLIST_HASH16
#define SUMLIST_HASH16
Value:
MAKE_HASH16 (0xBC, 0x94, 0x5F, 0x92, 0x5A, 0x52, 0xD2, 0x11, \
                                0x86, 0xDC, 0x00, 0xC0, 0x4F, 0x8E, 0xDB, 0x8A)
Referenced by w64_read_header().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
HAVE_riff
HAVE_wave
HAVE_fmt
HAVE_fact
HAVE_data
Function Documentation
MAKE_MARKER16() [1/5]
MAKE_MARKER16 (riff_MARKER16 , 'r' , 'i' , 'f' , 'f' , 0x2E , 0x91 , 0xCF , 0x11 , 0xA5 , 0xD6 , 0x28 , 0xDB , 0x04 , 0xC1 , 0x00 , 0x00)
MAKE_MARKER16() [2/5]
MAKE_MARKER16 (wave_MARKER16 , 'w' , 'a' , 'v' , 'e' , 0xF3 , 0xAC , 0xD3 , 0x11 , 0x8C , 0xD1 , 0x00 , 0xC0 , 0x4F , 0x8E , 0xDB , 0x8A)
MAKE_MARKER16() [3/5]
MAKE_MARKER16 (fmt_MARKER16 , 'f' , 'm' , 't' , ' ' , 0xF3 , 0xAC , 0xD3 , 0x11 , 0x8C , 0xD1 , 0x00 , 0xC0 , 0x4F , 0x8E , 0xDB , 0x8A)
MAKE_MARKER16() [4/5]
MAKE_MARKER16 (fact_MARKER16 , 'f' , 'a' , 'c' , 't' , 0xF3 , 0xAC , 0xD3 , 0x11 , 0x8C , 0xD1 , 0x00 , 0xC0 , 0x4F , 0x8E , 0xDB , 0x8A)
MAKE_MARKER16() [5/5]
MAKE_MARKER16 (data_MARKER16 , 'd' , 'a' , 't' , 'a' , 0xF3 , 0xAC , 0xD3 , 0x11 , 0x8C , 0xD1 , 0x00 , 0xC0 , 0x4F , 0x8E , 0xDB , 0x8A)
w64_read_header()
static int w64_read_header (SF_PRIVATE * psf, int * blockalign, int * framesperblock) static
References ACID_HASH16, bext_HASH16, MS_ADPCM_WAV_FMT::blockalign, IMA_ADPCM_WAV_FMT::blockalign, sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::container_data, data_HASH16, sf_private_tag::datalength, sf_private_tag::dataoffset, done(), sf_private_tag::endian, fact_HASH16, sf_private_tag::filelength, fmt_HASH16, WAV_FMT::format, HAVE_data, HAVE_fmt, HAVE_riff, HAVE_wave, sf_private_tag::header, WAV_FMT::ima, sf_private_tag::indx, junk_HASH16, levl_HASH16, list_HASH16, MARKER_HASH16, WAV_FMT::msadpcm, NULL, psf_binheader_readf(), psf_fseek(), psf_ftell(), psf_log_printf(), riff_HASH16, MS_ADPCM_WAV_FMT::samplesperblock, IMA_ADPCM_WAV_FMT::samplesperblock, sf_private_tag::sf, SF_MAX_CHANNELS, SF_MIN, SFE_CHANNEL_COUNT, SFE_CHANNEL_COUNT_ZERO, SFE_INTERNAL, SFE_UNIMPLEMENTED, SFE_W64_NO_DATA, SFE_W64_NO_RIFF, SFE_W64_NO_WAVE, SFE_WAV_NO_FMT, SIGNED_SIZEOF, SUMLIST_HASH16, u_bitwidth_to_subformat(), WAVLIKE_PRIVATE::wav_fmt, WAVE_FORMAT_ALAW, WAVE_FORMAT_EXTENSIBLE, WAVE_FORMAT_GSM610, WAVE_FORMAT_IEEE_FLOAT, WAVE_FORMAT_IMA_ADPCM, WAVE_FORMAT_MS_ADPCM, WAVE_FORMAT_MULAW, WAVE_FORMAT_PCM, wave_HASH16, and wavlike_read_fmt_chunk().
Referenced by w64_open().
w64_write_header()
static int w64_write_header (SF_PRIVATE * psf, int calc_length) static
References BHW2, BHW4, BHW8, BHWh, BHWz, sf_private_tag::bytewidth, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::error, sf_private_tag::filelength, sf_private_tag::header, sf_private_tag::indx, psf_binheader_writef(), psf_fseek(), psf_ftell(), psf_fwrite(), psf_get_filelen(), sf_private_tag::ptr, sf_private_tag::sf, SF_CODEC, SFE_UNIMPLEMENTED, WAVE_FORMAT_ALAW, WAVE_FORMAT_GSM610, WAVE_FORMAT_IEEE_FLOAT, WAVE_FORMAT_IMA_ADPCM, WAVE_FORMAT_MS_ADPCM, WAVE_FORMAT_MULAW, WAVE_FORMAT_PCM, WAVLIKE_GSM610_BLOCKSIZE, WAVLIKE_GSM610_SAMPLES, WAVLIKE_MSADPCM_ADAPT_COEFF_COUNT, wavlike_msadpcm_write_adapt_coeffs(), and wavlike_srate2blocksize().
Referenced by w64_close(), and w64_open().
w64_close()
static int w64_close (SF_PRIVATE * psf) static
References sf_private_tag::file, PSF_FILE::mode, and w64_write_header().
Referenced by w64_open().
w64_open()
int w64_open (SF_PRIVATE * psf)
References alaw_init(), sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::container_close, sf_private_tag::container_data, sf_private_tag::datalength, double64_init(), sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, float32_init(), gsm610_init(), sf_private_tag::is_pipe, PSF_FILE::mode, NULL, pcm_init(), sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SFE_BAD_OPEN_FORMAT, SFE_MALLOC_FAILED, SFE_NO_PIPE_WRITE, SFE_UNIMPLEMENTED, ulaw_init(), w64_close(), w64_read_header(), w64_write_header(), wavlike_ima_init(), wavlike_msadpcm_init(), wavlike_srate2blocksize(), and sf_private_tag::write_header.
Referenced by psf_open_file().