Aurora Framework: Init.c File Reference
Init.c File Reference
Functions
char * _glfw_strdup (const char *source)
void _glfwInputError (int code, const char *format,...)
static const char * getErrorString (int code)
GLFWAPI int glfwGetError (const char **description)
Returns and clears the last error for the calling thread.
GLFWAPI void glfwGetVersion (int *major, int *minor, int *rev)
Retrieves the version of the GLFW library.
GLFWAPI const char * glfwGetVersionString (void)
Returns a string describing the compile-time configuration.
GLFWAPI int glfwInit (void)
Initializes the GLFW library.
GLFWAPI void glfwInitHint (int hint, int value)
Sets the specified init hint to the desired value.
GLFWAPI GLFWerrorfun glfwSetErrorCallback (GLFWerrorfun cbfun)
Sets the error callback.
GLFWAPI void glfwTerminate (void)
Terminates the GLFW library.
static void terminate (void)
Variables
_GLFWlibrary _glfw = { GLFW_FALSE }
static GLFWerrorfun _glfwErrorCallback
static _GLFWinitconfig _glfwInitHints
static _GLFWerror _glfwMainThreadError
Function Documentation
getErrorString()
static const char* getErrorString (int code) static
References GLFW_API_UNAVAILABLE, GLFW_FORMAT_UNAVAILABLE, GLFW_INVALID_ENUM, GLFW_INVALID_VALUE, GLFW_NO_CURRENT_CONTEXT, GLFW_NO_WINDOW_CONTEXT, GLFW_NOT_INITIALIZED, GLFW_OUT_OF_MEMORY, GLFW_PLATFORM_ERROR, and GLFW_VERSION_UNAVAILABLE.
Referenced by _glfwInputError().
terminate()
static void terminate (void) static
References _glfw, _glfwFreeMonitor(), _glfwPlatformDestroyMutex(), _glfwPlatformDestroyTls(), _glfwPlatformSetGammaRamp(), _glfwPlatformTerminate(), _glfwTerminateVulkan(), _GLFWlibrary::callbacks, _GLFWlibrary::contextSlot, _GLFWlibrary::cursorListHead, _GLFWlibrary::errorListHead, _GLFWlibrary::errorLock, _GLFWlibrary::errorSlot, GLFW_FALSE, glfwDestroyCursor(), glfwDestroyWindow(), _GLFWlibrary::initialized, _GLFWlibrary::mappingCount, _GLFWlibrary::mappings, memset(), _GLFWlibrary::monitorCount, _GLFWlibrary::monitors, _GLFWerror::next, NULL, _GLFWmonitor::originalRamp, GLFWgammaramp::size, and _GLFWlibrary::windowListHead.
Referenced by glfwInit(), and glfwTerminate().
_glfw_strdup()
char* _glfw_strdup (const char * source)
References source.
Referenced by _glfwAllocJoystick(), _glfwAllocMonitor(), _glfwPlatformCreateWindow(), _glfwPlatformGetClipboardString(), _glfwPlatformSetClipboardString(), _glfwPlatformSetWindowTitle(), _glfwPollMonitorsNS(), geometry(), getSelectionString(), and glfwSetX11SelectionString().
_glfwInputError()
void _glfwInputError (int code, const char * format, ...)
References _glfw, _GLFW_MESSAGE_SIZE, _glfwErrorCallback, _glfwMainThreadError, _glfwPlatformGetTls(), _glfwPlatformLockMutex(), _glfwPlatformSetTls(), _glfwPlatformUnlockMutex(), _GLFWerror::code, setup::description, _GLFWerror::description, _GLFWlibrary::errorListHead, _GLFWlibrary::errorLock, _GLFWlibrary::errorSlot, getErrorString(), _GLFWlibrary::initialized, and _GLFWerror::next.
Referenced by _glfwAddOutputWayland(), _glfwChooseVisualGLX(), _glfwCreateContextEGL(), _glfwCreateContextGLX(), _glfwCreateContextNSGL(), _glfwCreateContextOSMesa(), _glfwCreateContextWGL(), _glfwDetectJoystickConnectionWin32(), _glfwInitEGL(), _glfwInitGLX(), _glfwInitJoysticksLinux(), _glfwInitJoysticksNS(), _glfwInitJoysticksWin32(), _glfwInitNSGL(), _glfwInitOSMesa(), _glfwInitVulkan(), _glfwInputErrorWin32(), _glfwInputErrorX11(), _glfwIsValidContextConfig(), _glfwPlatformCreateMutex(), _glfwPlatformCreateStandardCursor(), _glfwPlatformCreateTls(), _glfwPlatformCreateWindow(), _glfwPlatformCreateWindowSurface(), _glfwPlatformFocusWindow(), _glfwPlatformFramebufferTransparent(), _glfwPlatformGetClipboardString(), _glfwPlatformGetCursorPos(), _glfwPlatformGetGammaRamp(), _glfwPlatformGetMonitorContentScale(), _glfwPlatformGetPhysicalDevicePresentationSupport(), _glfwPlatformGetScancodeName(), _glfwPlatformGetVideoModes(), _glfwPlatformGetWindowFrameSize(), _glfwPlatformGetWindowPos(), _glfwPlatformIconifyWindow(), _glfwPlatformInit(), _glfwPlatformRequestWindowAttention(), _glfwPlatformRestoreWindow(), _glfwPlatformSetClipboardString(), _glfwPlatformSetCursor(), _glfwPlatformSetCursorPos(), _glfwPlatformSetGammaRamp(), _glfwPlatformSetWindowAspectRatio(), _glfwPlatformSetWindowDecorated(), _glfwPlatformSetWindowFloating(), _glfwPlatformSetWindowIcon(), _glfwPlatformSetWindowMonitor(), _glfwPlatformSetWindowPos(), _glfwPlatformSetWindowResizable(), _glfwPlatformWindowHovered(), _glfwPlatformWindowIconified(), _glfwRefreshContextAttribs(), _glfwSetVideoModeWin32(), chooseEGLConfig(), chooseGLXFBConfig(), choosePixelFormat(), createNativeWindow(), createShellSurface(), createShmBuffer(), createWindow(), createXdgSurface(), deviceCallback(), findValidMapping(), getDisplayName(), getSelectionString(), glfwCreateStandardCursor(), glfwCreateWindow(), glfwCreateWindowSurface(), glfwExtensionSupported(), glfwGetEGLContext(), glfwGetEGLSurface(), glfwGetGamepadName(), glfwGetGamepadState(), glfwGetGLXContext(), glfwGetGLXWindow(), glfwGetInputMode(), glfwGetJoystickAxes(), glfwGetJoystickButtons(), glfwGetJoystickGUID(), glfwGetJoystickHats(), glfwGetJoystickName(), glfwGetKey(), glfwGetKeyScancode(), glfwGetMouseButton(), glfwGetNSGLContext(), glfwGetOSMesaColorBuffer(), glfwGetOSMesaContext(), glfwGetOSMesaDepthBuffer(), glfwGetPhysicalDevicePresentationSupport(), glfwGetProcAddress(), glfwGetWGLContext(), glfwGetWindowAttrib(), glfwInitHint(), glfwJoystickIsGamepad(), glfwJoystickPresent(), glfwMakeContextCurrent(), glfwSetCursorPos(), glfwSetGamma(), glfwSetGammaRamp(), glfwSetInputMode(), glfwSetTime(), glfwSetWindowAspectRatio(), glfwSetWindowAttrib(), glfwSetWindowMonitor(), glfwSetWindowOpacity(), glfwSetWindowSizeLimits(), glfwSetX11SelectionString(), glfwSwapBuffers(), glfwSwapInterval(), glfwWaitEventsTimeout(), glfwWindowHint(), glfwWindowHintString(), initExtensions(), initializeAppKit(), initializeTIS(), keyboardHandleKeymap(), lockPointer(), makeContextCurrentEGL(), makeContextCurrentGLX(), makeContextCurrentOSMesa(), openJoystickDevice(), parseMapping(), setCursor(), setIdleInhibitor(), swapBuffersEGL(), updateUnicodeDataNS(), and windowProc().
Variable Documentation
_glfw
_GLFWlibrary _glfw = { GLFW_FALSE }
Referenced by _glfwAddOutputWayland(), _glfwAllocJoystick(), _glfwChooseVisualGLX(), _glfwCreateContextEGL(), _glfwCreateContextGLX(), _glfwCreateContextWGL(), _glfwCreateCursorX11(), _glfwDetectJoystickConnectionLinux(), _glfwDetectJoystickConnectionWin32(), _glfwDetectJoystickDisconnectionWin32(), _glfwGetWindowPropertyX11(), _glfwGrabErrorHandlerX11(), _glfwInitEGL(), _glfwInitGLX(), _glfwInitJoysticksLinux(), _glfwInitJoysticksNS(), _glfwInitJoysticksWin32(), _glfwInitNSGL(), _glfwInitOSMesa(), _glfwInitTimerNS(), _glfwInitTimerPOSIX(), _glfwInitTimerWin32(), _glfwInitVulkan(), _glfwInitWGL(), _glfwInputError(), _glfwInputErrorX11(), _glfwInputJoystick(), _glfwInputMonitor(), _glfwIsVisualTransparentX11(), _glfwPlatformCreateCursor(), _glfwPlatformCreateStandardCursor(), _glfwPlatformCreateWindow(), _glfwPlatformCreateWindowSurface(), _glfwPlatformDestroyCursor(), _glfwPlatformDestroyWindow(), _glfwPlatformFocusWindow(), _glfwPlatformFramebufferTransparent(), _glfwPlatformGetClipboardString(), _glfwPlatformGetCursorPos(), _glfwPlatformGetGammaRamp(), _glfwPlatformGetKeyScancode(), _glfwPlatformGetMonitorContentScale(), _glfwPlatformGetMonitorPos(), _glfwPlatformGetPhysicalDevicePresentationSupport(), _glfwPlatformGetRequiredInstanceExtensions(), _glfwPlatformGetScancodeName(), _glfwPlatformGetTimerFrequency(), _glfwPlatformGetTimerValue(), _glfwPlatformGetVideoMode(), _glfwPlatformGetVideoModes(), _glfwPlatformGetWindowContentScale(), _glfwPlatformGetWindowFrameSize(), _glfwPlatformGetWindowOpacity(), _glfwPlatformGetWindowPos(), _glfwPlatformGetWindowSize(), _glfwPlatformHideWindow(), _glfwPlatformIconifyWindow(), _glfwPlatformInit(), _glfwPlatformMaximizeWindow(), _glfwPlatformPollEvents(), _glfwPlatformPollJoystick(), _glfwPlatformPostEmptyEvent(), _glfwPlatformRequestWindowAttention(), _glfwPlatformRestoreWindow(), _glfwPlatformSetClipboardString(), _glfwPlatformSetCursor(), _glfwPlatformSetCursorMode(), _glfwPlatformSetCursorPos(), _glfwPlatformSetGammaRamp(), _glfwPlatformSetWindowAspectRatio(), _glfwPlatformSetWindowDecorated(), _glfwPlatformSetWindowFloating(), _glfwPlatformSetWindowIcon(), _glfwPlatformSetWindowMonitor(), _glfwPlatformSetWindowOpacity(), _glfwPlatformSetWindowPos(), _glfwPlatformSetWindowSize(), _glfwPlatformSetWindowSizeLimits(), _glfwPlatformSetWindowTitle(), _glfwPlatformShowWindow(), _glfwPlatformTerminate(), _glfwPlatformWaitEvents(), _glfwPlatformWaitEventsTimeout(), _glfwPlatformWindowFocused(), _glfwPlatformWindowHovered(), _glfwPlatformWindowMaximized(), _glfwPlatformWindowVisible(), _glfwPollMonitorsMir(), _glfwPollMonitorsNS(), _glfwPollMonitorsWin32(), _glfwPollMonitorsX11(), _glfwPushSelectionToManagerX11(), _glfwRefreshContextAttribs(), _glfwReleaseErrorHandlerX11(), _glfwRestoreVideoModeX11(), _glfwSetVideoModeX11(), _glfwTerminateEGL(), _glfwTerminateGLX(), _glfwTerminateJoysticksLinux(), _glfwTerminateJoysticksNS(), _glfwTerminateJoysticksWin32(), _glfwTerminateOSMesa(), _glfwTerminateWGL(), _glfwUpdateKeyNamesWin32(), acquireMonitor(), checkScaleChange(), chooseEGLConfig(), chooseGLXFBConfig(), choosePixelFormat(), createDecoration(), createDecorations(), createHelperWindow(), createKeyTables(), createLegacyContextGLX(), createNativeWindow(), createShellSurface(), createShmBuffer(), createSurface(), createWindow(), createXdgSurface(), dequeueEvent(), destroyContextEGL(), destroyContextGLX(), detectEWMH(), deviceCallback(), enqueueEvent(), errorHandler(), extensionSupportedEGL(), extensionSupportedGLX(), extensionSupportedWGL(), findMapping(), findValidPixelFormat(), findWindowByHandle(), findWindowFromDecorationSurface(), freeLibraries(), getEGLConfigAttrib(), getGLXFBConfigAttrib(), getPixelFormatAttrib(), getProcAddressEGL(), getProcAddressGLX(), getProcAddressNSGL(), getProcAddressWGL(), getSelectionString(), getSupportedAtom(), getSystemContentScale(), getWindowState(), glfwCreateCursor(), glfwCreateStandardCursor(), glfwCreateWindow(), glfwCreateWindowSurface(), glfwDefaultWindowHints(), glfwDestroyCursor(), glfwDestroyWindow(), glfwExtensionSupported(), glfwGetCurrentContext(), glfwGetEGLDisplay(), glfwGetError(), glfwGetGamepadName(), glfwGetGamepadState(), glfwGetJoystickAxes(), glfwGetJoystickButtons(), glfwGetJoystickGUID(), glfwGetJoystickHats(), glfwGetJoystickName(), glfwGetJoystickUserPointer(), glfwGetMirDisplay(), glfwGetMonitors(), glfwGetPhysicalDevicePresentationSupport(), glfwGetPrimaryMonitor(), glfwGetProcAddress(), glfwGetRequiredInstanceExtensions(), glfwGetTime(), glfwGetWaylandDisplay(), glfwGetX11Display(), glfwGetX11SelectionString(), glfwInit(), glfwJoystickIsGamepad(), glfwJoystickPresent(), glfwMakeContextCurrent(), glfwPostEmptyEvent(), glfwSetJoystickCallback(), glfwSetJoystickUserPointer(), glfwSetMonitorCallback(), glfwSetTime(), glfwSetX11SelectionString(), glfwSwapInterval(), glfwTerminate(), glfwUpdateGamepadMappings(), glfwWaitEvents(), glfwWindowHint(), glfwWindowHintString(), handleConfigure(), handleEvents(), handlePointerMotion(), handleSelectionClear(), handleSelectionRequest(), hasUsableInputMethodStyle(), hideCursor(), initExtensions(), initializeAppKit(), initializeTIS(), inputChar(), isFrameExtentsEvent(), isSelectionEvent(), keyboardHandleEnter(), keyboardHandleKey(), keyboardHandleKeymap(), keyboardHandleLeave(), keyboardHandleModifiers(), loadLibraries(), lockPointer(), makeContextCurrentEGL(), makeContextCurrentGLX(), makeContextCurrentNSGL(), makeContextCurrentOSMesa(), makeContextCurrentWGL(), matchCallback(), openJoystickDevice(), pointerHandleAxis(), pointerHandleButton(), pointerHandleEnter(), pointerHandleLeave(), pointerHandleMotion(), processEvent(), registryHandleGlobal(), registryHandleGlobalRemove(), releaseMonitor(), removeCallback(), seatHandleCapabilities(), sendEventToWM(), setCursor(), setCursorNameForWindow(), setIdleInhibitor(), setOpaqueRegion(), setWindowConfinement(), showCursor(), swapBuffersEGL(), swapBuffersGLX(), swapIntervalEGL(), swapIntervalGLX(), swapIntervalNSGL(), swapIntervalWGL(), terminate(), toGLFWKeyCode(), translateKey(), translateKeyCode(), updateCursorImage(), updateNormalHints(), updateUnicodeDataNS(), updateWindowMode(), vidmodeFromModeInfo(), waitForEvent(), waitForVisibilityNotify(), windowProc(), and writeTargetToProperty().
_glfwMainThreadError
_GLFWerror _glfwMainThreadError static
Referenced by _glfwInputError(), glfwGetError(), and glfwInit().
_glfwErrorCallback
GLFWerrorfun _glfwErrorCallback static
Referenced by _glfwInputError(), and glfwSetErrorCallback().
_glfwInitHints
_GLFWinitconfig _glfwInitHints static
Initial value:
=
{
    GLFW_TRUE,
    {
        GLFW_TRUE,
        GLFW_TRUE
    }
}
Referenced by glfwInit(), and glfwInitHint().