Aurora Framework: wve.c File Reference
wve.c File Reference
Macros
#define ALAW_MARKER MAKE_MARKER ('A', 'L', 'a', 'w')
#define DFIL_MARKER MAKE_MARKER ('d', 'F', 'i', 'l')
#define ESSN_MARKER MAKE_MARKER ('e', '*', '*', '\0')
#define PSION_DATAOFFSET 0x20
#define PSION_VERSION ((unsigned short) 3856)
#define SOUN_MARKER MAKE_MARKER ('S', 'o', 'u', 'n')
Functions
static int wve_close (SF_PRIVATE *psf)
int wve_open (SF_PRIVATE *psf)
static int wve_read_header (SF_PRIVATE *psf)
static int wve_write_header (SF_PRIVATE *psf, int calc_length)
Macro Definition Documentation
ALAW_MARKER
#define ALAW_MARKER MAKE_MARKER ('A', 'L', 'a', 'w')
Referenced by wve_read_header(), and wve_write_header().
SOUN_MARKER
#define SOUN_MARKER MAKE_MARKER ('S', 'o', 'u', 'n')
Referenced by wve_read_header(), and wve_write_header().
DFIL_MARKER
#define DFIL_MARKER MAKE_MARKER ('d', 'F', 'i', 'l')
Referenced by wve_read_header(), and wve_write_header().
ESSN_MARKER
#define ESSN_MARKER MAKE_MARKER ('e', '*', '*', '\0')
Referenced by wve_read_header(), and wve_write_header().
PSION_VERSION
#define PSION_VERSION ((unsigned short) 3856)
Referenced by wve_read_header(), and wve_write_header().
PSION_DATAOFFSET
#define PSION_DATAOFFSET 0x20
Referenced by wve_read_header().
Function Documentation
wve_read_header()
static int wve_read_header (SF_PRIVATE * psf) static
References ALAW_MARKER, sf_private_tag::datalength, sf_private_tag::dataoffset, DFIL_MARKER, ESSN_MARKER, sf_private_tag::filelength, psf_binheader_readf(), psf_log_printf(), PSION_DATAOFFSET, PSION_VERSION, sf_private_tag::sf, SFE_NO_ERROR, SFE_WVE_NOT_WVE, SOUN_MARKER, and create_symbols_file::version.
Referenced by wve_open().
wve_write_header()
static int wve_write_header (SF_PRIVATE * psf, int calc_length) static
References ALAW_MARKER, BHW2, BHW4, BHWm, sf_private_tag::bytewidth, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, DFIL_MARKER, sf_private_tag::error, ESSN_MARKER, sf_private_tag::filelength, sf_private_tag::header, sf_private_tag::indx, psf_binheader_writef(), psf_fseek(), psf_ftell(), psf_fwrite(), psf_get_filelen(), PSION_VERSION, sf_private_tag::ptr, sf_private_tag::sf, SFE_CHANNEL_COUNT, and SOUN_MARKER.
Referenced by wve_close(), and wve_open().
wve_close()
static int wve_close (SF_PRIVATE * psf) static
References sf_private_tag::file, PSF_FILE::mode, and wve_write_header().
Referenced by wve_open().
wve_open()
int wve_open (SF_PRIVATE * psf)
References alaw_init(), sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::container_close, sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, sf_private_tag::is_pipe, PSF_FILE::mode, sf_private_tag::sf, SF_CONTAINER, SFE_BAD_OPEN_FORMAT, SFE_WVE_NO_PIPE, sf_private_tag::write_header, wve_close(), wve_read_header(), and wve_write_header().
Referenced by psf_open_file().