Aurora Framework: g723_16.c File Reference
g723_16.c File Reference
Functions
int g723_16_decoder (int i, G72x_STATE *state_ptr)
int g723_16_encoder (int sl, G72x_STATE *state_ptr)
Variables
static short _dqlntab [4] = { 116, 365, 365, 116 }
static short _fitab [4] = { 0, 0xE00, 0xE00, 0 }
static short _witab [4] = { -704, 14048, 14048, -704 }
static short qtab_723_16 [1] = { 261 }
Function Documentation
g723_16_encoder()
int g723_16_encoder (int sl, G72x_STATE * state_ptr)
References _dqlntab, _fitab, _witab, predictor_pole(), predictor_zero(), qtab_723_16, quantize(), reconstruct(), step_size(), and update().
Referenced by g72x_writer_init().
g723_16_decoder()
int g723_16_decoder (int i, G72x_STATE * state_ptr)
References _dqlntab, _fitab, _witab, predictor_pole(), predictor_zero(), reconstruct(), step_size(), and update().
Referenced by g72x_reader_init().
Variable Documentation
_dqlntab
short _dqlntab[4] = { 116, 365, 365, 116 } static
Referenced by g723_16_decoder(), and g723_16_encoder().
_witab
short _witab[4] = { -704, 14048, 14048, -704 } static
Referenced by g723_16_decoder(), and g723_16_encoder().
_fitab
short _fitab[4] = { 0, 0xE00, 0xE00, 0 } static
Referenced by g723_16_decoder(), and g723_16_encoder().
qtab_723_16
short qtab_723_16[1] = { 261 } static
Referenced by g723_16_encoder().