Aurora Framework: UTF16BE< CharType > Struct Template Reference
UTF16BE< CharType > Struct Template Reference
UTF-16 big endian encoding.
Public Types
enum { supportUnicode = 1 }
typedef CharType Ch
Public Member Functions
RAPIDJSON_STATIC_ASSERT (sizeof(Ch) >=2)
Static Public Member Functions
template<typename InputStream >
static bool Decode (InputStream &is, unsigned *codepoint)
template<typename OutputStream >
static void Encode (OutputStream &os, unsigned codepoint)
template<typename OutputStream >
static void EncodeUnsafe (OutputStream &os, unsigned codepoint)
template<typename OutputByteStream >
static void Put (OutputByteStream &os, CharType c)
template<typename OutputByteStream >
static void PutBOM (OutputByteStream &os)
template<typename InputByteStream >
static CharType Take (InputByteStream &is)
template<typename InputByteStream >
static CharType TakeBOM (InputByteStream &is)
template<typename InputStream , typename OutputStream >
static bool Validate (InputStream &is, OutputStream &os)
Detailed Description
template<typename CharType = wchar_t>
struct UTF16BE< CharType >
UTF-16 big endian encoding.
Member Typedef Documentation
Ch
template<typename CharType = wchar_t> typedef CharType UTF16< CharType >::Ch inherited
Member Enumeration Documentation
anonymous enum
template<typename CharType = wchar_t> anonymous enum inherited
Enumerator
supportUnicode
Member Function Documentation
TakeBOM()
template<typename CharType = wchar_t> template<typename InputByteStream > static CharType UTF16BE< CharType >::TakeBOM (InputByteStream & is) inline static
References UTF16< CharType >::RAPIDJSON_STATIC_ASSERT(), and UTF16BE< CharType >::Take().
Take()
template<typename CharType = wchar_t> template<typename InputByteStream > static CharType UTF16BE< CharType >::Take (InputByteStream & is) inline static
References UTF16< CharType >::RAPIDJSON_STATIC_ASSERT().
Referenced by UTF16BE< CharType >::TakeBOM().
PutBOM()
template<typename CharType = wchar_t> template<typename OutputByteStream > static void UTF16BE< CharType >::PutBOM (OutputByteStream & os) inline static
References UTF16< CharType >::RAPIDJSON_STATIC_ASSERT().
Put()
template<typename CharType = wchar_t> template<typename OutputByteStream > static void UTF16BE< CharType >::Put (OutputByteStream & os, CharType c) inline static
References UTF16< CharType >::RAPIDJSON_STATIC_ASSERT().
RAPIDJSON_STATIC_ASSERT()
template<typename CharType = wchar_t> UTF16< CharType >::RAPIDJSON_STATIC_ASSERT (sizeof(Ch) >= 2) inherited
Referenced by UTF16< CharType >::Decode(), UTF16< CharType >::Encode(), UTF16< CharType >::EncodeUnsafe(), UTF16LE< CharType >::Put(), UTF16BE< CharType >::Put(), UTF16LE< CharType >::PutBOM(), UTF16BE< CharType >::PutBOM(), UTF16LE< CharType >::Take(), UTF16BE< CharType >::Take(), UTF16LE< CharType >::TakeBOM(), UTF16BE< CharType >::TakeBOM(), and UTF16< CharType >::Validate().
Encode()
template<typename CharType = wchar_t> template<typename OutputStream > static void UTF16< CharType >::Encode (OutputStream & os, unsigned codepoint) inline static inherited
References RAPIDJSON_ASSERT, and UTF16< CharType >::RAPIDJSON_STATIC_ASSERT().
EncodeUnsafe()
template<typename CharType = wchar_t> template<typename OutputStream > static void UTF16< CharType >::EncodeUnsafe (OutputStream & os, unsigned codepoint) inline static inherited
References PutUnsafe(), RAPIDJSON_ASSERT, and UTF16< CharType >::RAPIDJSON_STATIC_ASSERT().
Decode()
template<typename CharType = wchar_t> template<typename InputStream > static bool UTF16< CharType >::Decode (InputStream & is, unsigned * codepoint) inline static inherited
References UTF16< CharType >::RAPIDJSON_STATIC_ASSERT().
Validate()
template<typename CharType = wchar_t> template<typename InputStream , typename OutputStream > static bool UTF16< CharType >::Validate (InputStream & is, OutputStream & os) inline static inherited
References UTF16< CharType >::RAPIDJSON_STATIC_ASSERT().
The documentation for this struct was generated from the following file:
encodings.h