Aurora Framework: wav.c File Reference
wav.c File Reference
Macros
#define acid_MARKER (MAKE_MARKER ('a', 'c', 'i', 'd'))
#define AFAn_MARKER (MAKE_MARKER ('A', 'F', 'A', 'n'))
#define afsp_MARKER (MAKE_MARKER ('a', 'f', 's', 'p'))
#define clm_MARKER (MAKE_MARKER ('c', 'l', 'm', ' '))
#define Cr8r_MARKER (MAKE_MARKER ('C', 'r', '8', 'r'))
#define cue_MARKER (MAKE_MARKER ('c', 'u', 'e', ' '))
#define elm1_MARKER (MAKE_MARKER ('e', 'l', 'm', '1'))
#define elmo_MARKER (MAKE_MARKER ('e', 'l', 'm', 'o'))
#define fact_MARKER (MAKE_MARKER ('f', 'a', 'c', 't'))
#define FLLR_MARKER (MAKE_MARKER ('F', 'L', 'L', 'R'))
#define fmt_MARKER (MAKE_MARKER ('f', 'm', 't', ' '))
#define inst_MARKER (MAKE_MARKER ('i', 'n', 's', 't'))
#define iXML_MARKER (MAKE_MARKER ('i', 'X', 'M', 'L'))
#define JUNK_MARKER (MAKE_MARKER ('J', 'U', 'N', 'K'))
#define levl_MARKER (MAKE_MARKER ('l', 'e', 'v', 'l'))
#define MEXT_MARKER (MAKE_MARKER ('M', 'E', 'X', 'T'))
#define minf_MARKER (MAKE_MARKER ('m', 'i', 'n', 'f'))
#define OggS_MARKER (MAKE_MARKER ('O', 'g', 'g', 'S'))
#define ovwf_MARKER (MAKE_MARKER ('o', 'v', 'w', 'f'))
#define plst_MARKER (MAKE_MARKER ('p', 'l', 's', 't'))
#define PMX_MARKER (MAKE_MARKER ('_', 'P', 'M', 'X'))
#define regn_MARKER (MAKE_MARKER ('r', 'e', 'g', 'n'))
#define RIFF_MARKER (MAKE_MARKER ('R', 'I', 'F', 'F'))
#define RIFX_MARKER (MAKE_MARKER ('R', 'I', 'F', 'X'))
#define slnt_MARKER (MAKE_MARKER ('s', 'l', 'n', 't'))
#define smpl_MARKER (MAKE_MARKER ('s', 'm', 'p', 'l'))
#define strc_MARKER (MAKE_MARKER ('s', 't', 'r', 'c'))
#define SyLp_MARKER (MAKE_MARKER ('S', 'y', 'L', 'p'))
#define umid_MARKER (MAKE_MARKER ('u', 'm', 'i', 'd'))
#define WAVE_MARKER (MAKE_MARKER ('W', 'A', 'V', 'E'))
#define wavl_MARKER (MAKE_MARKER ('w', 'a', 'v', 'l'))
#define WAVLIKE_PEAK_CHUNK_SIZE(ch) (2 * sizeof (int) + ch * (sizeof (float) + sizeof (int)))
#define wvpk_MARKER (MAKE_MARKER ('w', 'v', 'p', 'k'))
Enumerations
enum {
HAVE_RIFF = 0x01, HAVE_WAVE = 0x02, HAVE_fmt = 0x04, HAVE_fact = 0x08,
HAVE_PEAK = 0x10, HAVE_data = 0x20, HAVE_other = 0x80000000
}
Functions
static int wav_close (SF_PRIVATE *psf)
static int wav_command (SF_PRIVATE *psf, int command, void *data, int datasize)
static int wav_command (SF_PRIVATE *psf, int command, void *UNUSED(data), int datasize)
static int wav_get_chunk_data (SF_PRIVATE *psf, const SF_CHUNK_ITERATOR *iterator, SF_CHUNK_INFO *chunk_info)
static int wav_get_chunk_size (SF_PRIVATE *psf, const SF_CHUNK_ITERATOR *iterator, SF_CHUNK_INFO *chunk_info)
static SF_CHUNK_ITERATOR * wav_next_chunk_iterator (SF_PRIVATE *psf, SF_CHUNK_ITERATOR *iterator)
int wav_open (SF_PRIVATE *psf)
static int wav_read_acid_chunk (SF_PRIVATE *psf, uint32_t chunklen)
static int wav_read_header (SF_PRIVATE *psf, int *blockalign, int *framesperblock)
static int wav_read_smpl_chunk (SF_PRIVATE *psf, uint32_t chunklen)
static int wav_set_chunk (SF_PRIVATE *psf, const SF_CHUNK_INFO *chunk_info)
static int wav_write_fmt_chunk (SF_PRIVATE *psf)
static int wav_write_header (SF_PRIVATE *psf, int calc_length)
static int wav_write_tailer (SF_PRIVATE *psf)
static int wavex_write_fmt_chunk (SF_PRIVATE *psf)
Variables
static const EXT_SUBFORMAT MSGUID_SUBTYPE_ALAW
static const EXT_SUBFORMAT MSGUID_SUBTYPE_AMBISONIC_B_FORMAT_IEEE_FLOAT
static const EXT_SUBFORMAT MSGUID_SUBTYPE_AMBISONIC_B_FORMAT_PCM
static const EXT_SUBFORMAT MSGUID_SUBTYPE_IEEE_FLOAT
static const EXT_SUBFORMAT MSGUID_SUBTYPE_MULAW
static const EXT_SUBFORMAT MSGUID_SUBTYPE_PCM
Macro Definition Documentation
RIFF_MARKER
#define RIFF_MARKER (MAKE_MARKER ('R', 'I', 'F', 'F'))
Referenced by wav_read_header(), and wav_write_header().
RIFX_MARKER
#define RIFX_MARKER (MAKE_MARKER ('R', 'I', 'F', 'X'))
Referenced by wav_read_header(), and wav_write_header().
WAVE_MARKER
#define WAVE_MARKER (MAKE_MARKER ('W', 'A', 'V', 'E'))
Referenced by wav_read_header(), and wav_write_header().
fmt_MARKER
#define fmt_MARKER (MAKE_MARKER ('f', 'm', 't', ' '))
Referenced by wav_read_header(), and wav_write_header().
fact_MARKER
#define fact_MARKER (MAKE_MARKER ('f', 'a', 'c', 't'))
Referenced by wav_read_header(), wav_write_fmt_chunk(), and wavex_write_fmt_chunk().
cue_MARKER
#define cue_MARKER (MAKE_MARKER ('c', 'u', 'e', ' '))
Referenced by wav_read_header(), and wav_write_header().
slnt_MARKER
#define slnt_MARKER (MAKE_MARKER ('s', 'l', 'n', 't'))
wavl_MARKER
#define wavl_MARKER (MAKE_MARKER ('w', 'a', 'v', 'l'))
plst_MARKER
#define plst_MARKER (MAKE_MARKER ('p', 'l', 's', 't'))
Referenced by wav_read_header().
smpl_MARKER
#define smpl_MARKER (MAKE_MARKER ('s', 'm', 'p', 'l'))
Referenced by rf64_write_header(), wav_read_header(), and wav_write_header().
iXML_MARKER
#define iXML_MARKER (MAKE_MARKER ('i', 'X', 'M', 'L'))
Referenced by wav_read_header().
levl_MARKER
#define levl_MARKER (MAKE_MARKER ('l', 'e', 'v', 'l'))
Referenced by wav_read_header().
MEXT_MARKER
#define MEXT_MARKER (MAKE_MARKER ('M', 'E', 'X', 'T'))
Referenced by wav_read_header().
acid_MARKER
#define acid_MARKER (MAKE_MARKER ('a', 'c', 'i', 'd'))
Referenced by wav_read_header().
strc_MARKER
#define strc_MARKER (MAKE_MARKER ('s', 't', 'r', 'c'))
Referenced by wav_read_header().
afsp_MARKER
#define afsp_MARKER (MAKE_MARKER ('a', 'f', 's', 'p'))
Referenced by wav_read_header().
clm_MARKER
#define clm_MARKER (MAKE_MARKER ('c', 'l', 'm', ' '))
Referenced by wav_read_header().
elmo_MARKER
#define elmo_MARKER (MAKE_MARKER ('e', 'l', 'm', 'o'))
Referenced by wav_read_header().
FLLR_MARKER
#define FLLR_MARKER (MAKE_MARKER ('F', 'L', 'L', 'R'))
Referenced by wav_read_header().
minf_MARKER
#define minf_MARKER (MAKE_MARKER ('m', 'i', 'n', 'f'))
Referenced by wav_read_header().
elm1_MARKER
#define elm1_MARKER (MAKE_MARKER ('e', 'l', 'm', '1'))
Referenced by wav_read_header().
regn_MARKER
#define regn_MARKER (MAKE_MARKER ('r', 'e', 'g', 'n'))
Referenced by wav_read_header().
ovwf_MARKER
#define ovwf_MARKER (MAKE_MARKER ('o', 'v', 'w', 'f'))
Referenced by wav_read_header().
umid_MARKER
#define umid_MARKER (MAKE_MARKER ('u', 'm', 'i', 'd'))
Referenced by wav_read_header().
SyLp_MARKER
#define SyLp_MARKER (MAKE_MARKER ('S', 'y', 'L', 'p'))
Referenced by wav_read_header().
Cr8r_MARKER
#define Cr8r_MARKER (MAKE_MARKER ('C', 'r', '8', 'r'))
Referenced by wav_read_header().
JUNK_MARKER
#define JUNK_MARKER (MAKE_MARKER ('J', 'U', 'N', 'K'))
Referenced by wav_read_header().
PMX_MARKER
#define PMX_MARKER (MAKE_MARKER ('_', 'P', 'M', 'X'))
Referenced by wav_read_header().
inst_MARKER
#define inst_MARKER (MAKE_MARKER ('i', 'n', 's', 't'))
Referenced by wav_read_header().
AFAn_MARKER
#define AFAn_MARKER (MAKE_MARKER ('A', 'F', 'A', 'n'))
Referenced by wav_read_header().
wvpk_MARKER
#define wvpk_MARKER (MAKE_MARKER ('w', 'v', 'p', 'k'))
Referenced by wav_read_header().
OggS_MARKER
#define OggS_MARKER (MAKE_MARKER ('O', 'g', 'g', 'S'))
Referenced by wav_read_header().
WAVLIKE_PEAK_CHUNK_SIZE
#define WAVLIKE_PEAK_CHUNK_SIZE (ch) (2 * sizeof (int) + ch * (sizeof (float) + sizeof (int)))
Referenced by wavlike_read_peak_chunk(), and wavlike_write_peak_chunk().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
HAVE_RIFF
HAVE_WAVE
HAVE_fmt
HAVE_fact
HAVE_PEAK
HAVE_data
HAVE_other
Function Documentation
wav_read_header()
static int wav_read_header (SF_PRIVATE * psf, int * blockalign, int * framesperblock) static
References acid_MARKER, AFAn_MARKER, afsp_MARKER, bext_MARKER, MIN_WAV_FMT::bitwidth, MIN_WAV_FMT::blockalign, MS_ADPCM_WAV_FMT::blockalign, IMA_ADPCM_WAV_FMT::blockalign, sf_private_tag::blockwidth, sf_private_tag::bytewidth, cart_MARKER, clm_MARKER, sf_private_tag::container_data, Cr8r_MARKER, cue_MARKER, sf_private_tag::cues, data_MARKER, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, DISP_MARKER, done(), elm1_MARKER, elmo_MARKER, sf_private_tag::endian, fact_MARKER, sf_private_tag::file, sf_private_tag::filelength, sf_private_tag::fileoffset, FLLR_MARKER, WAVLIKE_PRIVATE::fmt_is_broken, fmt_MARKER, WAV_FMT::format, FACT_CHUNK::frames, HAVE_data, HAVE_fact, HAVE_fmt, HAVE_other, HAVE_PEAK, HAVE_RIFF, HAVE_WAVE, sf_private_tag::header, IBM_FORMAT_ALAW, IBM_FORMAT_MULAW, WAV_FMT::ima, sf_private_tag::indx, INFO_MARKER, inst_MARKER, sf_private_tag::is_pipe, iXML_MARKER, JUNK_MARKER, levl_MARKER, LIST_MARKER, MEXT_MARKER, WAV_FMT::min, minf_MARKER, PSF_FILE::mode, WAV_FMT::msadpcm, NULL, OggS_MARKER, ovwf_MARKER, PAD_MARKER, sf_private_tag::peak_info, PEAK_INFO::peak_loc, PEAK_MARKER, plst_MARKER, PMX_MARKER, psf_binheader_readf(), psf_cues_alloc(), psf_fseek(), psf_ftell(), psf_isprint(), psf_log_printf(), psf_store_read_chunk_u32(), sf_private_tag::rchunks, regn_MARKER, RIFF_MARKER, RIFX_MARKER, sf_private_tag::rwf_endian, MS_ADPCM_WAV_FMT::samplesperblock, IMA_ADPCM_WAV_FMT::samplesperblock, sf_private_tag::sf, SF_MAX_CHANNELS, SF_PEAK_END, SF_PEAK_START, SFE_CHANNEL_COUNT, SFE_CHANNEL_COUNT_ZERO, SFE_INTERNAL, SFE_MALLOC_FAILED, SFE_RDWR_BAD_HEADER, SFE_UNIMPLEMENTED, SFE_WAV_BAD_FACT, SFE_WAV_NO_DATA, SFE_WAV_NO_FMT, SFE_WAV_NO_RIFF, SFE_WAV_NO_WAVE, SFE_WAV_PEAK_B4_FMT, SFE_WAV_WVPK_DATA, SIGNED_SIZEOF, smpl_MARKER, strc_MARKER, SyLp_MARKER, u_bitwidth_to_subformat(), umid_MARKER, WAVLIKE_PRIVATE::wav_fmt, wav_read_acid_chunk(), wav_read_smpl_chunk(), WAVE_FORMAT_ALAW, WAVE_FORMAT_EXTENSIBLE, WAVE_FORMAT_G721_ADPCM, WAVE_FORMAT_GSM610, WAVE_FORMAT_IEEE_FLOAT, WAVE_FORMAT_IMA_ADPCM, WAVE_FORMAT_MS_ADPCM, WAVE_FORMAT_MULAW, WAVE_FORMAT_NMS_VBXADPCM, WAVE_FORMAT_PCM, WAVE_MARKER, wavlike_analyze(), wavlike_read_bext_chunk(), wavlike_read_cart_chunk(), wavlike_read_fmt_chunk(), wavlike_read_peak_chunk(), wavlike_subchunk_parse(), and wvpk_MARKER.
Referenced by wav_open().
wav_write_header()
static int wav_write_header (SF_PRIVATE * psf, int calc_length) static
References BHW4, BHW8, BHWm, BHWz, sf_private_tag::broadcast_16k, sf_private_tag::bytewidth, sf_private_tag::cart_16k, cue_MARKER, sf_private_tag::cues, data_MARKER, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::endian, sf_private_tag::error, sf_private_tag::filelength, sf_private_tag::flags, fmt_MARKER, sf_private_tag::header, sf_private_tag::indx, sf_private_tag::instrument, NULL, PAD_MARKER, sf_private_tag::peak_info, PEAK_INFO::peak_loc, psf_binheader_writef(), psf_fseek(), psf_ftell(), psf_fwrite(), psf_get_filelen(), psf_log_printf(), sf_private_tag::ptr, RIFF_MARKER, RIFX_MARKER, sf_private_tag::sf, SF_CONTAINER, SF_PEAK_START, SF_STR_LOCATE_START, SFE_INTERNAL, SFE_UNIMPLEMENTED, smpl_MARKER, sf_private_tag::strings, WRITE_CHUNKS::used, wav_write_fmt_chunk(), WAVE_MARKER, wavex_write_fmt_chunk(), wavlike_write_bext_chunk(), wavlike_write_cart_chunk(), wavlike_write_custom_chunks(), wavlike_write_peak_chunk(), wavlike_write_strings(), and sf_private_tag::wchunks.
Referenced by wav_open().
wav_write_tailer()
static int wav_write_tailer (SF_PRIVATE * psf) static
References BHWz, sf_private_tag::bytewidth, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::flags, sf_private_tag::header, sf_private_tag::indx, NULL, sf_private_tag::peak_info, PEAK_INFO::peak_loc, psf_binheader_writef(), psf_fseek(), psf_fwrite(), sf_private_tag::ptr, sf_private_tag::sf, SF_PEAK_END, SF_STR_LOCATE_END, sf_private_tag::strings, wavlike_write_peak_chunk(), and wavlike_write_strings().
Referenced by wav_close().
wav_command() [1/2]
static int wav_command (SF_PRIVATE * psf, int command, void * data, int datasize) static
Referenced by wav_open().
wav_close()
static int wav_close (SF_PRIVATE * psf) static
References sf_private_tag::file, sf_private_tag::filelength, PSF_FILE::mode, psf_ftell(), psf_ftruncate(), wav_write_tailer(), and sf_private_tag::write_header.
Referenced by wav_open().
wav_read_smpl_chunk()
static int wav_read_smpl_chunk (SF_PRIVATE * psf, uint32_t chunklen) static
References ARRAY_LEN, sf_private_tag::instrument, NULL, psf_binheader_readf(), psf_instrument_alloc(), psf_log_printf(), and SFE_MALLOC_FAILED.
Referenced by wav_read_header().
wav_read_acid_chunk()
static int wav_read_acid_chunk (SF_PRIVATE * psf, uint32_t chunklen) static
References sf_private_tag::loop_info, NULL, psf_binheader_readf(), psf_log_printf(), and SFE_MALLOC_FAILED.
Referenced by wav_read_header().
wav_set_chunk()
static int wav_set_chunk (SF_PRIVATE * psf, const SF_CHUNK_INFO * chunk_info) static
References psf_save_write_chunk(), and sf_private_tag::wchunks.
Referenced by wav_open().
wav_next_chunk_iterator()
static SF_CHUNK_ITERATOR * wav_next_chunk_iterator (SF_PRIVATE * psf, SF_CHUNK_ITERATOR * iterator) static
References psf_next_chunk_iterator(), and sf_private_tag::rchunks.
Referenced by wav_open().
wav_get_chunk_size()
static int wav_get_chunk_size (SF_PRIVATE * psf, const SF_CHUNK_ITERATOR * iterator, SF_CHUNK_INFO * chunk_info) static
References READ_CHUNKS::chunks, READ_CHUNK::len, psf_find_read_chunk_iterator(), sf_private_tag::rchunks, SFE_NO_ERROR, and SFE_UNKNOWN_CHUNK.
Referenced by wav_open().
wav_get_chunk_data()
static int wav_get_chunk_data (SF_PRIVATE * psf, const SF_CHUNK_ITERATOR * iterator, SF_CHUNK_INFO * chunk_info) static
References READ_CHUNKS::chunks, READ_CHUNK::id, READ_CHUNK::id_size, READ_CHUNK::len, memcpy(), NULL, READ_CHUNK::offset, psf_find_read_chunk_iterator(), psf_fread(), psf_fseek(), psf_ftell(), sf_private_tag::rchunks, SF_MIN, SFE_BAD_CHUNK_DATA_PTR, SFE_NO_ERROR, and SFE_UNKNOWN_CHUNK.
Referenced by wav_open().
wav_open()
int wav_open (SF_PRIVATE * psf)
References alaw_init(), sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::command, sf_private_tag::container_close, sf_private_tag::container_data, sf_private_tag::datalength, sf_private_tag::dataoffset, double64_init(), sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, sf_private_tag::flags, float32_init(), g72x_init(), sf_private_tag::get_chunk_data, sf_private_tag::get_chunk_size, gsm610_init(), sf_private_tag::is_pipe, PSF_FILE::mode, sf_private_tag::next_chunk_iterator, nms_adpcm_init(), NULL, pcm_init(), sf_private_tag::peak_info, peak_info_calloc(), PEAK_INFO::peak_loc, sf_private_tag::set_chunk, sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SF_ENDIAN, SF_PEAK_START, SF_STR_ALLOW_END, SF_STR_ALLOW_START, SFE_BAD_OPEN_FORMAT, SFE_MALLOC_FAILED, SFE_NO_PIPE_WRITE, SFE_UNIMPLEMENTED, sf_private_tag::strings, ulaw_init(), wav_close(), wav_command(), wav_get_chunk_data(), wav_get_chunk_size(), wav_next_chunk_iterator(), wav_read_header(), wav_set_chunk(), wav_write_header(), WAVLIKE_PRIVATE::wavex_ambisonic, wavlike_ima_init(), wavlike_msadpcm_init(), wavlike_srate2blocksize(), and sf_private_tag::write_header.
Referenced by psf_open_file().
wav_write_fmt_chunk()
static int wav_write_fmt_chunk (SF_PRIVATE * psf) static
References BHW2, BHW4, BHW8, BHWm, sf_private_tag::bytewidth, fact_MARKER, psf_binheader_writef(), sf_private_tag::sf, SF_CODEC, SFE_UNIMPLEMENTED, WAVE_FORMAT_ALAW, WAVE_FORMAT_G721_ADPCM, WAVE_FORMAT_GSM610, WAVE_FORMAT_IEEE_FLOAT, WAVE_FORMAT_IMA_ADPCM, WAVE_FORMAT_MS_ADPCM, WAVE_FORMAT_MULAW, WAVE_FORMAT_NMS_VBXADPCM, WAVE_FORMAT_PCM, WAVLIKE_GSM610_BLOCKSIZE, WAVLIKE_GSM610_SAMPLES, WAVLIKE_MSADPCM_ADAPT_COEFF_COUNT, wavlike_msadpcm_write_adapt_coeffs(), and wavlike_srate2blocksize().
Referenced by wav_write_header().
wavex_write_fmt_chunk()
static int wavex_write_fmt_chunk (SF_PRIVATE * psf) static
References BHW2, BHW4, BHW8, BHWm, sf_private_tag::bytewidth, sf_private_tag::container_data, fact_MARKER, MSGUID_SUBTYPE_ALAW, MSGUID_SUBTYPE_AMBISONIC_B_FORMAT_IEEE_FLOAT, MSGUID_SUBTYPE_AMBISONIC_B_FORMAT_PCM, MSGUID_SUBTYPE_IEEE_FLOAT, MSGUID_SUBTYPE_MS_ADPCM, MSGUID_SUBTYPE_MULAW, MSGUID_SUBTYPE_PCM, NULL, psf_binheader_writef(), sf_private_tag::sf, SF_CODEC, SFE_INTERNAL, SFE_UNIMPLEMENTED, WAVE_FORMAT_EXTENSIBLE, WAVLIKE_PRIVATE::wavex_ambisonic, WAVLIKE_PRIVATE::wavex_channelmask, and wavlike_write_guid().
Referenced by wav_write_header().
wav_command() [2/2]
static int wav_command (SF_PRIVATE * psf, int command, void * UNUSEDdata, int datasize) static
References sf_private_tag::channel_map, sf_private_tag::container_data, NULL, sf_private_tag::sf, SF_CONTAINER, SFE_INTERNAL, WAVLIKE_PRIVATE::wavex_ambisonic, WAVLIKE_PRIVATE::wavex_channelmask, and wavlike_gen_channel_mask().
Variable Documentation
MSGUID_SUBTYPE_PCM
const EXT_SUBFORMAT MSGUID_SUBTYPE_PCM static
Initial value:
=
{   0x00000001, 0x0000, 0x0010, {   0x80, 0x00, 0x00, 0xaa, 0x00, 0x38, 0x9b, 0x71 }
}
Referenced by wavex_write_fmt_chunk().
MSGUID_SUBTYPE_IEEE_FLOAT
const EXT_SUBFORMAT MSGUID_SUBTYPE_IEEE_FLOAT static
Initial value:
=
{   0x00000003, 0x0000, 0x0010, {   0x80, 0x00, 0x00, 0xaa, 0x00, 0x38, 0x9b, 0x71 }
}
Referenced by wavex_write_fmt_chunk().
MSGUID_SUBTYPE_ALAW
const EXT_SUBFORMAT MSGUID_SUBTYPE_ALAW static
Initial value:
=
{   0x00000006, 0x0000, 0x0010, {   0x80, 0x00, 0x00, 0xaa, 0x00, 0x38, 0x9b, 0x71 }
}
Referenced by wavex_write_fmt_chunk().
MSGUID_SUBTYPE_MULAW
const EXT_SUBFORMAT MSGUID_SUBTYPE_MULAW static
Initial value:
=
{   0x00000007, 0x0000, 0x0010, {   0x80, 0x00, 0x00, 0xaa, 0x00, 0x38, 0x9b, 0x71 }
}
Referenced by wavex_write_fmt_chunk().
MSGUID_SUBTYPE_AMBISONIC_B_FORMAT_PCM
const EXT_SUBFORMAT MSGUID_SUBTYPE_AMBISONIC_B_FORMAT_PCM static
Initial value:
=
{   0x00000001, 0x0721, 0x11d3, {   0x86, 0x44, 0xC8, 0xC1, 0xCA, 0x00, 0x00, 0x00 }
}
Referenced by wavex_write_fmt_chunk().
MSGUID_SUBTYPE_AMBISONIC_B_FORMAT_IEEE_FLOAT
const EXT_SUBFORMAT MSGUID_SUBTYPE_AMBISONIC_B_FORMAT_IEEE_FLOAT static
Initial value:
=
{   0x00000003, 0x0721, 0x11d3, {   0x86, 0x44, 0xC8, 0xC1, 0xCA, 0x00, 0x00, 0x00 }
}
Referenced by wavex_write_fmt_chunk().