Aurora Framework: g723_40.c File Reference
g723_40.c File Reference
Functions
int g723_40_decoder (int i, G72x_STATE *state_ptr)
int g723_40_encoder (int sl, G72x_STATE *state_ptr)
Variables
static short _dqlntab [32]
static short _fitab [32]
static short _witab [32]
static short qtab_723_40 [15]
Function Documentation
g723_40_encoder()
int g723_40_encoder (int sl, G72x_STATE * state_ptr)
References _dqlntab, _fitab, _witab, predictor_pole(), predictor_zero(), qtab_723_40, quantize(), reconstruct(), step_size(), and update().
Referenced by g72x_writer_init().
g723_40_decoder()
int g723_40_decoder (int i, G72x_STATE * state_ptr)
References _dqlntab, _fitab, _witab, arith_shift_left(), predictor_pole(), predictor_zero(), reconstruct(), step_size(), and update().
Referenced by g72x_reader_init().
Variable Documentation
_dqlntab
short _dqlntab[32] static
Initial value:
= { -2048, -66, 28, 104, 169, 224, 274, 318,
                358, 395, 429, 459, 488, 514, 539, 566,
                566, 539, 514, 488, 459, 429, 395, 358,
                318, 274, 224, 169, 104, 28, -66, -2048 }
Referenced by g723_40_decoder(), and g723_40_encoder().
_witab
short _witab[32] static
Initial value:
= { 448, 448, 768, 1248, 1280, 1312, 1856, 3200,
            4512, 5728, 7008, 8960, 11456, 14080, 16928, 22272,
            22272, 16928, 14080, 11456, 8960, 7008, 5728, 4512,
            3200, 1856, 1312, 1280, 1248, 768, 448, 448 }
Referenced by g723_40_decoder(), and g723_40_encoder().
_fitab
short _fitab[32] static
Initial value:
= { 0, 0, 0, 0, 0, 0x200, 0x200, 0x200,
            0x200, 0x200, 0x400, 0x600, 0x800, 0xA00, 0xC00, 0xC00,
            0xC00, 0xC00, 0xA00, 0x800, 0x600, 0x400, 0x200, 0x200,
            0x200, 0x200, 0x200, 0, 0, 0, 0, 0 }
Referenced by g723_40_decoder(), and g723_40_encoder().
qtab_723_40
short qtab_723_40[15] static
Initial value:
= { -122, -16, 68, 139, 198, 250, 298, 339,
                378, 413, 445, 475, 502, 528, 553 }
Referenced by g723_40_encoder().