Aurora Framework: sndfile.c File Reference
sndfile.c File Reference
Classes
struct ErrorStruct
Macros
#define SNDFILE_MAGICK 0x1234C0DE
#define VALIDATE_SNDFILE_AND_ASSIGN_PSF(a, b, c)
Functions
static int copy_filename (SF_PRIVATE *psf, const char *path)
static int format_from_extension (SF_PRIVATE *psf)
static int guess_file_type (SF_PRIVATE *psf)
static int psf_close (SF_PRIVATE *psf)
SNDFILE * psf_open_file (SF_PRIVATE *psf, SF_INFO *sfinfo)
static void save_header_info (SF_PRIVATE *psf)
int sf_close (SNDFILE *sndfile)
int sf_command (SNDFILE *sndfile, int command, void *data, int datasize)
int sf_current_byterate (SNDFILE *sndfile)
int sf_error (SNDFILE *sndfile)
const char * sf_error_number (int errnum)
int sf_error_str (SNDFILE *sndfile, char *str, size_t maxlen)
int sf_format_check (const SF_INFO *info)
int sf_get_chunk_data (const SF_CHUNK_ITERATOR *iterator, SF_CHUNK_INFO *chunk_info)
SF_CHUNK_ITERATOR * sf_get_chunk_iterator (SNDFILE *sndfile, const SF_CHUNK_INFO *chunk_info)
int sf_get_chunk_size (const SF_CHUNK_ITERATOR *iterator, SF_CHUNK_INFO *chunk_info)
const char * sf_get_string (SNDFILE *sndfile, int str_type)
SF_CHUNK_ITERATOR * sf_next_chunk_iterator (SF_CHUNK_ITERATOR *iterator)
SNDFILE * sf_open (const char *path, int mode, SF_INFO *sfinfo)
SNDFILE * sf_open_fd (int fd, int mode, SF_INFO *sfinfo, int close_desc)
SNDFILE * sf_open_virtual (SF_VIRTUAL_IO *sfvirtual, int mode, SF_INFO *sfinfo, void *user_data)
int sf_perror (SNDFILE *sndfile)
sf_count_t sf_read_double (SNDFILE *sndfile, double *ptr, sf_count_t len)
sf_count_t sf_read_float (SNDFILE *sndfile, float *ptr, sf_count_t len)
sf_count_t sf_read_int (SNDFILE *sndfile, int *ptr, sf_count_t len)
sf_count_t sf_read_raw (SNDFILE *sndfile, void *ptr, sf_count_t bytes)
sf_count_t sf_read_short (SNDFILE *sndfile, short *ptr, sf_count_t len)
sf_count_t sf_readf_double (SNDFILE *sndfile, double *ptr, sf_count_t frames)
sf_count_t sf_readf_float (SNDFILE *sndfile, float *ptr, sf_count_t frames)
sf_count_t sf_readf_int (SNDFILE *sndfile, int *ptr, sf_count_t frames)
sf_count_t sf_readf_short (SNDFILE *sndfile, short *ptr, sf_count_t frames)
sf_count_t sf_seek (SNDFILE *sndfile, sf_count_t offset, int whence)
int sf_set_chunk (SNDFILE *sndfile, const SF_CHUNK_INFO *chunk_info)
int sf_set_string (SNDFILE *sndfile, int str_type, const char *str)
const char * sf_strerror (SNDFILE *sndfile)
const char * sf_version_string (void)
sf_count_t sf_write_double (SNDFILE *sndfile, const double *ptr, sf_count_t len)
sf_count_t sf_write_float (SNDFILE *sndfile, const float *ptr, sf_count_t len)
sf_count_t sf_write_int (SNDFILE *sndfile, const int *ptr, sf_count_t len)
sf_count_t sf_write_raw (SNDFILE *sndfile, const void *ptr, sf_count_t len)
sf_count_t sf_write_short (SNDFILE *sndfile, const short *ptr, sf_count_t len)
void sf_write_sync (SNDFILE *sndfile)
sf_count_t sf_writef_double (SNDFILE *sndfile, const double *ptr, sf_count_t frames)
sf_count_t sf_writef_float (SNDFILE *sndfile, const float *ptr, sf_count_t frames)
sf_count_t sf_writef_int (SNDFILE *sndfile, const int *ptr, sf_count_t frames)
sf_count_t sf_writef_short (SNDFILE *sndfile, const short *ptr, sf_count_t frames)
static int try_resource_fork (SF_PRIVATE *psf)
static int validate_psf (SF_PRIVATE *psf)
static int validate_sfinfo (SF_INFO *sfinfo)
Variables
int sf_errno = 0
static char sf_parselog [SF_BUFFER_LEN] = { 0 }
static char sf_syserr [SF_SYSERR_LEN] = { 0 }
static ErrorStruct SndfileErrors []
Macro Definition Documentation
SNDFILE_MAGICK
#define SNDFILE_MAGICK 0x1234C0DE
Referenced by psf_open_file(), sf_current_byterate(), sf_get_string(), and sf_strerror().
VALIDATE_SNDFILE_AND_ASSIGN_PSF
#define VALIDATE_SNDFILE_AND_ASSIGN_PSF (a, b, c)
Value:
{   if ((a) == NULL)                        \
            {   sf_errno = SFE_BAD_SNDFILE_PTR ;    \
                return 0 ;                          \
                } ;                                 \
            (b) = (SF_PRIVATE*) (a) ;               \
            if ((b)->virtual_io == SF_FALSE &&      \
                psf_file_valid (b) == 0)            \
            {   (b)->error = SFE_BAD_FILE_PTR ;     \
                return 0 ;                          \
                } ;                                 \
            if ((b)->Magick != SNDFILE_MAGICK)      \
            {   (b)->error = SFE_BAD_SNDFILE_PTR ;  \
                return 0 ;                          \
                } ;                                 \
            if (c) (b)->error = 0 ;                 \
            }
Referenced by sf_close(), sf_command(), sf_error(), sf_error_str(), sf_get_chunk_data(), sf_get_chunk_iterator(), sf_get_chunk_size(), sf_next_chunk_iterator(), sf_perror(), sf_read_double(), sf_read_float(), sf_read_int(), sf_read_raw(), sf_read_short(), sf_readf_double(), sf_readf_float(), sf_readf_int(), sf_readf_short(), sf_seek(), sf_set_chunk(), sf_set_string(), sf_write_double(), sf_write_float(), sf_write_int(), sf_write_raw(), sf_write_short(), sf_writef_double(), sf_writef_float(), sf_writef_int(), and sf_writef_short().
Function Documentation
format_from_extension()
static int format_from_extension (SF_PRIVATE * psf) static
References PSF_FILE::c, sf_private_tag::dataoffset, sf_private_tag::file, PSF_FILE::name, NULL, psf_strlcpy(), sf_private_tag::sf, and SF_CONTAINER.
Referenced by psf_open_file().
guess_file_type()
static int guess_file_type (SF_PRIVATE * psf) static
References sf_private_tag::error, sf_private_tag::filelength, id3_skip(), psf_binheader_readf(), psf_log_printf(), SF_FORMAT_DWD, SF_FORMAT_REX2, SF_FORMAT_TXW, SFE_BAD_FILE_READ, SIGNED_SIZEOF, and try_resource_fork().
Referenced by psf_open_file().
validate_sfinfo()
static int validate_sfinfo (SF_INFO * sfinfo) static
References SF_CODEC, and SF_CONTAINER.
Referenced by psf_open_file().
validate_psf()
static int validate_psf (SF_PRIVATE * psf) static
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::datalength, sf_private_tag::dataoffset, psf_log_printf(), and sf_private_tag::sf.
Referenced by psf_open_file().
save_header_info()
static void save_header_info (SF_PRIVATE * psf) static
References sf_private_tag::buf, sf_private_tag::parselog, and sf_parselog.
Referenced by psf_open_file().
copy_filename()
static int copy_filename (SF_PRIVATE * psf, const char * path) static
References PSF_FILE::c, PSF_FILE::dir, sf_private_tag::error, sf_private_tag::file, PSF_FILE::name, PSF_FILE::path, and SFE_FILENAME_TOO_LONG.
Referenced by sf_open(), and sf_open_fd().
psf_close()
static int psf_close (SF_PRIVATE * psf) static
References sf_private_tag::broadcast_16k, sf_private_tag::cart_16k, sf_private_tag::channel_map, READ_CHUNKS::chunks, WRITE_CHUNKS::chunks, sf_private_tag::codec_close, sf_private_tag::codec_data, sf_private_tag::container_close, sf_private_tag::container_data, sf_private_tag::cues, WRITE_CHUNK::data, sf_private_tag::dither, sf_private_tag::format_desc, sf_private_tag::header, sf_private_tag::instrument, sf_private_tag::interleave, sf_private_tag::iterator, sf_private_tag::loop_info, NULL, sf_private_tag::peak_info, psf_close_rsrc(), psf_fclose(), sf_private_tag::ptr, sf_private_tag::rchunks, sf_private_tag::storage, sf_private_tag::strings, WRITE_CHUNKS::used, and sf_private_tag::wchunks.
Referenced by psf_open_file(), and sf_close().
try_resource_fork()
static int try_resource_fork (SF_PRIVATE * psf) static
References PSF_FILE::c, sf_private_tag::error, PSF_FILE::mode, PSF_FILE::path, psf_log_printf(), psf_open_rsrc(), and sf_private_tag::rsrc.
Referenced by guess_file_type().
sf_open()
SNDFILE* sf_open (const char * path, int mode, SF_INFO * sfinfo)
References copy_filename(), sf_private_tag::error, sf_private_tag::file, mode(), PSF_FILE::mode, NULL, psf_allocate(), psf_fopen(), psf_init_files(), psf_log_printf(), psf_open_file(), psf_set_stdio(), sf_errno, and SFE_MALLOC_FAILED.
Referenced by AuroraFW::AudioManager::AudioIStream::AudioIStream(), AuroraFW::AudioManager::AudioOStream::AudioOStream(), and SndfileHandle::SndfileHandle().
sf_open_fd()
SNDFILE* sf_open_fd (int fd, int mode, SF_INFO * sfinfo, int close_desc)
References copy_filename(), PSF_FILE::do_not_close_descriptor, sf_private_tag::file, sf_private_tag::fileoffset, sf_private_tag::is_pipe, mode(), PSF_FILE::mode, NULL, psf_allocate(), psf_ftell(), psf_init_files(), psf_is_pipe(), psf_open_file(), psf_set_file(), SF_CONTAINER, sf_errno, SFE_MALLOC_FAILED, and SFE_SD2_FD_DISALLOWED.
Referenced by SndfileHandle::SndfileHandle().
sf_open_virtual()
SNDFILE* sf_open_virtual (SF_VIRTUAL_IO * sfvirtual, int mode, SF_INFO * sfinfo, void * user_data)
References sf_private_tag::file, mode(), PSF_FILE::mode, NULL, psf_allocate(), psf_init_files(), psf_open_file(), sf_errno, sf_parselog, SFE_BAD_VIRTUAL_IO, SFE_MALLOC_FAILED, sf_private_tag::vio, sf_private_tag::vio_user_data, and sf_private_tag::virtual_io.
Referenced by SndfileHandle::SndfileHandle().
sf_close()
int sf_close (SNDFILE * sndfile)
References psf_close(), and VALIDATE_SNDFILE_AND_ASSIGN_PSF.
Referenced by AuroraFW::AudioManager::AudioInfo::~AudioInfo().
sf_write_sync()
void sf_write_sync (SNDFILE * sndfile)
References NULL, and psf_fsync().
Referenced by SndfileHandle::writeSync().
sf_error_number()
const char* sf_error_number (int errnum)
References SFE_MAX_ERROR, SndfileErrors, and ErrorStruct::str.
Referenced by psf_open_file(), sf_error_str(), sf_perror(), and sf_strerror().
sf_strerror()
const char* sf_strerror (SNDFILE * sndfile)
References sf_private_tag::error, sf_private_tag::Magick, NULL, sf_errno, sf_error_number(), sf_syserr, SFE_SYSTEM, SNDFILE_MAGICK, and sf_private_tag::syserr.
Referenced by SndfileHandle::strError().
sf_error()
int sf_error (SNDFILE * sndfile)
References sf_private_tag::error, NULL, sf_errno, and VALIDATE_SNDFILE_AND_ASSIGN_PSF.
Referenced by SndfileHandle::error().
sf_perror()
int sf_perror (SNDFILE * sndfile)
References sf_private_tag::error, NULL, sf_errno, sf_error_number(), SFE_NO_ERROR, and VALIDATE_SNDFILE_AND_ASSIGN_PSF.
sf_error_str()
int sf_error_str (SNDFILE * sndfile, char * str, size_t maxlen)
References sf_private_tag::error, NULL, sf_errno, sf_error_number(), SFE_INTERNAL, SFE_NO_ERROR, and VALIDATE_SNDFILE_AND_ASSIGN_PSF.
sf_format_check()
int sf_format_check (const SF_INFO * info)
References SF_CODEC, SF_CONTAINER, SF_ENDIAN, and SF_MAX_CHANNELS.
Referenced by SndfileHandle::formatCheck(), and psf_open_file().
sf_version_string()
const char* sf_version_string (void)
Referenced by sf_command().
sf_command()
int sf_command (SNDFILE * sndfile, int command, void * data, int datasize)
References sf_private_tag::add_clipping, sf_private_tag::auto_header, sf_private_tag::broadcast_16k, broadcast_var_get(), broadcast_var_set(), sf_private_tag::buf, sf_private_tag::cart_16k, cart_var_get(), cart_var_set(), sf_private_tag::channel_map, sf_private_tag::command, sf_private_tag::cues, sf_private_tag::data_endswap, sf_private_tag::dataoffset, dither_init(), double64_init(), sf_private_tag::error, sf_private_tag::file, sf_private_tag::filelength, sf_private_tag::fileoffset, float32_init(), sf_private_tag::float_int_mult, sf_private_tag::float_max, sf_private_tag::have_written, sf_private_tag::ieee_replace, sf_private_tag::instrument, sf_private_tag::loop_info, memcpy(), PSF_FILE::mode, sf_private_tag::norm_double, sf_private_tag::norm_float, NOT, NULL, sf_private_tag::parselog, sf_private_tag::peak_info, peak_info_calloc(), PEAK_INFO::peak_loc, psf_calc_max_all_channels(), psf_calc_signal_max(), psf_cues_dup(), psf_fseek(), psf_ftruncate(), psf_get_cues(), psf_get_format_info(), psf_get_format_major(), psf_get_format_major_count(), psf_get_format_simple(), psf_get_format_simple_count(), psf_get_format_subtype(), psf_get_format_subtype_count(), psf_get_max_all_channels(), psf_get_signal_max(), psf_instrument_alloc(), psf_log_printf(), sf_private_tag::read_dither, sf_private_tag::scale_int_float, sf_private_tag::sf, SF_CODEC, SF_CONTAINER, sf_errno, SF_MAX, SF_MIN, sf_parselog, SF_PEAK_START, sf_seek(), sf_version_string(), SFE_BAD_COMMAND_PARAM, SFE_CMD_HAS_DATA, SFE_MALLOC_FAILED, SIGNED_SIZEOF, VALIDATE_SNDFILE_AND_ASSIGN_PSF, sf_private_tag::write_dither, and sf_private_tag::write_header.
Referenced by SndfileHandle::command(), psf_calc_max_all_channels(), and psf_calc_signal_max().
sf_seek()
sf_count_t sf_seek (SNDFILE * sndfile, sf_count_t offset, int whence)
References sf_private_tag::error, sf_private_tag::file, sf_private_tag::last_op, PSF_FILE::mode, PSF_SEEK_ERROR, sf_private_tag::read_current, sf_private_tag::seek, sf_private_tag::sf, SFE_AMBIGUOUS_SEEK, SFE_BAD_SEEK, SFE_NOT_SEEKABLE, SFE_WRONG_SEEK, SFM_MASK, VALIDATE_SNDFILE_AND_ASSIGN_PSF, and sf_private_tag::write_current.
Referenced by AuroraFW::AudioManager::audioOutputCallback(), AuroraFW::AudioManager::AudioOStream::play(), psf_calc_max_all_channels(), psf_calc_signal_max(), SndfileHandle::seek(), and sf_command().
sf_get_string()
const char* sf_get_string (SNDFILE * sndfile, int str_type)
References sf_private_tag::Magick, NULL, psf_get_string(), and SNDFILE_MAGICK.
Referenced by AuroraFW::AudioManager::AudioInfo::getAlbum(), AuroraFW::AudioManager::AudioInfo::getArtist(), AuroraFW::AudioManager::AudioInfo::getComment(), AuroraFW::AudioManager::AudioInfo::getCopyright(), AuroraFW::AudioManager::AudioInfo::getDate(), AuroraFW::AudioManager::AudioInfo::getGenre(), AuroraFW::AudioManager::AudioInfo::getLicense(), AuroraFW::AudioManager::AudioInfo::getSoftware(), SndfileHandle::getString(), AuroraFW::AudioManager::AudioInfo::getTitle(), and AuroraFW::AudioManager::AudioInfo::getTrackNumber().
sf_set_string()
int sf_set_string (SNDFILE * sndfile, int str_type, const char * str)
References psf_set_string(), and VALIDATE_SNDFILE_AND_ASSIGN_PSF.
Referenced by AuroraFW::AudioManager::AudioInfo::setAlbum(), AuroraFW::AudioManager::AudioInfo::setArtist(), AuroraFW::AudioManager::AudioInfo::setComment(), AuroraFW::AudioManager::AudioInfo::setCopyright(), AuroraFW::AudioManager::AudioInfo::setDate(), AuroraFW::AudioManager::AudioInfo::setGenre(), AuroraFW::AudioManager::AudioInfo::setLicense(), AuroraFW::AudioManager::AudioInfo::setSoftware(), SndfileHandle::setString(), AuroraFW::AudioManager::AudioInfo::setTitle(), and AuroraFW::AudioManager::AudioInfo::setTrackNumber().
sf_current_byterate()
int sf_current_byterate (SNDFILE * sndfile)
References sf_private_tag::byterate, sf_private_tag::bytewidth, sf_private_tag::Magick, NULL, sf_private_tag::sf, SF_CODEC, and SNDFILE_MAGICK.
sf_read_raw()
sf_count_t sf_read_raw (SNDFILE * sndfile, void * ptr, sf_count_t bytes)
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::error, sf_private_tag::file, sf_private_tag::last_op, PSF_FILE::mode, psf_fread(), psf_memset(), sf_private_tag::read_current, sf_private_tag::seek, sf_private_tag::sf, SFE_BAD_READ_ALIGN, SFE_NOT_READMODE, and VALIDATE_SNDFILE_AND_ASSIGN_PSF.
Referenced by SndfileHandle::readRaw().
sf_read_short()
sf_count_t sf_read_short (SNDFILE * sndfile, short * ptr, sf_count_t len)
References sf_private_tag::error, sf_private_tag::file, sf_private_tag::last_op, PSF_FILE::mode, NULL, psf_memset(), sf_private_tag::read_current, sf_private_tag::read_short, sf_private_tag::seek, sf_private_tag::sf, SFE_BAD_READ_ALIGN, SFE_NEGATIVE_RW_LEN, SFE_NOT_READMODE, SFE_UNIMPLEMENTED, and VALIDATE_SNDFILE_AND_ASSIGN_PSF.
Referenced by SndfileHandle::read().
sf_readf_short()
sf_count_t sf_readf_short (SNDFILE * sndfile, short * ptr, sf_count_t frames)
References sf_private_tag::error, sf_private_tag::file, sf_private_tag::last_op, PSF_FILE::mode, NULL, psf_memset(), sf_private_tag::read_current, sf_private_tag::read_short, sf_private_tag::seek, sf_private_tag::sf, SFE_NEGATIVE_RW_LEN, SFE_NOT_READMODE, SFE_UNIMPLEMENTED, and VALIDATE_SNDFILE_AND_ASSIGN_PSF.
Referenced by SndfileHandle::readf().
sf_read_int()
sf_count_t sf_read_int (SNDFILE * sndfile, int * ptr, sf_count_t len)
References sf_private_tag::error, sf_private_tag::file, sf_private_tag::last_op, PSF_FILE::mode, NULL, psf_memset(), sf_private_tag::read_current, sf_private_tag::read_int, sf_private_tag::seek, sf_private_tag::sf, SFE_BAD_READ_ALIGN, SFE_NEGATIVE_RW_LEN, SFE_NOT_READMODE, SFE_UNIMPLEMENTED, and VALIDATE_SNDFILE_AND_ASSIGN_PSF.
Referenced by SndfileHandle::read().
sf_readf_int()
sf_count_t sf_readf_int (SNDFILE * sndfile, int * ptr, sf_count_t frames)
References sf_private_tag::error, sf_private_tag::file, sf_private_tag::last_op, PSF_FILE::mode, NULL, psf_memset(), sf_private_tag::read_current, sf_private_tag::read_int, sf_private_tag::seek, sf_private_tag::sf, SFE_NEGATIVE_RW_LEN, SFE_NOT_READMODE, SFE_UNIMPLEMENTED, and VALIDATE_SNDFILE_AND_ASSIGN_PSF.
Referenced by SndfileHandle::readf().
sf_read_float()
sf_count_t sf_read_float (SNDFILE * sndfile, float * ptr, sf_count_t len)
References sf_private_tag::error, sf_private_tag::file, sf_private_tag::last_op, PSF_FILE::mode, NULL, psf_memset(), sf_private_tag::read_current, sf_private_tag::read_float, sf_private_tag::seek, sf_private_tag::sf, SFE_BAD_READ_ALIGN, SFE_NEGATIVE_RW_LEN, SFE_NOT_READMODE, SFE_UNIMPLEMENTED, and VALIDATE_SNDFILE_AND_ASSIGN_PSF.
Referenced by SndfileHandle::read().
sf_readf_float()
sf_count_t sf_readf_float (SNDFILE * sndfile, float * ptr, sf_count_t frames)
References sf_private_tag::error, sf_private_tag::file, sf_private_tag::last_op, PSF_FILE::mode, NULL, psf_memset(), sf_private_tag::read_current, sf_private_tag::read_float, sf_private_tag::seek, sf_private_tag::sf, SFE_NEGATIVE_RW_LEN, SFE_NOT_READMODE, SFE_UNIMPLEMENTED, and VALIDATE_SNDFILE_AND_ASSIGN_PSF.
Referenced by AuroraFW::AudioManager::AudioOStream::AudioOStream(), AuroraFW::AudioManager::audioOutputCallback(), and SndfileHandle::readf().
sf_read_double()
sf_count_t sf_read_double (SNDFILE * sndfile, double * ptr, sf_count_t len)
References sf_private_tag::error, sf_private_tag::file, sf_private_tag::last_op, PSF_FILE::mode, NULL, psf_memset(), sf_private_tag::read_current, sf_private_tag::read_double, sf_private_tag::seek, sf_private_tag::sf, SFE_BAD_READ_ALIGN, SFE_NEGATIVE_RW_LEN, SFE_NOT_READMODE, SFE_UNIMPLEMENTED, and VALIDATE_SNDFILE_AND_ASSIGN_PSF.
Referenced by psf_calc_max_all_channels(), psf_calc_signal_max(), and SndfileHandle::read().
sf_readf_double()
sf_count_t sf_readf_double (SNDFILE * sndfile, double * ptr, sf_count_t frames)
References sf_private_tag::error, sf_private_tag::file, sf_private_tag::last_op, PSF_FILE::mode, NULL, psf_memset(), sf_private_tag::read_current, sf_private_tag::read_double, sf_private_tag::seek, sf_private_tag::sf, SFE_NEGATIVE_RW_LEN, SFE_NOT_READMODE, SFE_UNIMPLEMENTED, and VALIDATE_SNDFILE_AND_ASSIGN_PSF.
Referenced by SndfileHandle::readf().
sf_write_raw()
sf_count_t sf_write_raw (SNDFILE * sndfile, const void * ptr, sf_count_t len)
References sf_private_tag::auto_header, sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::dataend, sf_private_tag::error, sf_private_tag::file, sf_private_tag::have_written, sf_private_tag::last_op, PSF_FILE::mode, NULL, psf_fwrite(), sf_private_tag::seek, sf_private_tag::sf, SFE_BAD_WRITE_ALIGN, SFE_NEGATIVE_RW_LEN, SFE_NOT_WRITEMODE, VALIDATE_SNDFILE_AND_ASSIGN_PSF, sf_private_tag::write_current, and sf_private_tag::write_header.
Referenced by SndfileHandle::writeRaw().
sf_write_short()
sf_count_t sf_write_short (SNDFILE * sndfile, const short * ptr, sf_count_t len)
References sf_private_tag::auto_header, sf_private_tag::dataend, sf_private_tag::error, sf_private_tag::file, sf_private_tag::have_written, sf_private_tag::last_op, PSF_FILE::mode, NULL, sf_private_tag::seek, sf_private_tag::sf, SFE_BAD_WRITE_ALIGN, SFE_NEGATIVE_RW_LEN, SFE_NOT_WRITEMODE, SFE_UNIMPLEMENTED, VALIDATE_SNDFILE_AND_ASSIGN_PSF, sf_private_tag::write_current, sf_private_tag::write_header, and sf_private_tag::write_short.
Referenced by SndfileHandle::write().
sf_writef_short()
sf_count_t sf_writef_short (SNDFILE * sndfile, const short * ptr, sf_count_t frames)
References sf_private_tag::auto_header, sf_private_tag::dataend, sf_private_tag::error, sf_private_tag::file, sf_private_tag::have_written, sf_private_tag::last_op, PSF_FILE::mode, NULL, sf_private_tag::seek, sf_private_tag::sf, SFE_NEGATIVE_RW_LEN, SFE_NOT_WRITEMODE, SFE_UNIMPLEMENTED, VALIDATE_SNDFILE_AND_ASSIGN_PSF, sf_private_tag::write_current, sf_private_tag::write_header, and sf_private_tag::write_short.
Referenced by SndfileHandle::writef().
sf_write_int()
sf_count_t sf_write_int (SNDFILE * sndfile, const int * ptr, sf_count_t len)
References sf_private_tag::auto_header, sf_private_tag::dataend, sf_private_tag::error, sf_private_tag::file, sf_private_tag::have_written, sf_private_tag::last_op, PSF_FILE::mode, NULL, sf_private_tag::seek, sf_private_tag::sf, SFE_BAD_WRITE_ALIGN, SFE_NEGATIVE_RW_LEN, SFE_NOT_WRITEMODE, SFE_UNIMPLEMENTED, VALIDATE_SNDFILE_AND_ASSIGN_PSF, sf_private_tag::write_current, sf_private_tag::write_header, and sf_private_tag::write_int.
Referenced by SndfileHandle::write().
sf_writef_int()
sf_count_t sf_writef_int (SNDFILE * sndfile, const int * ptr, sf_count_t frames)
References sf_private_tag::auto_header, sf_private_tag::dataend, sf_private_tag::error, sf_private_tag::file, sf_private_tag::have_written, sf_private_tag::last_op, PSF_FILE::mode, NULL, sf_private_tag::seek, sf_private_tag::sf, SFE_NEGATIVE_RW_LEN, SFE_NOT_WRITEMODE, SFE_UNIMPLEMENTED, VALIDATE_SNDFILE_AND_ASSIGN_PSF, sf_private_tag::write_current, sf_private_tag::write_header, and sf_private_tag::write_int.
Referenced by SndfileHandle::writef().
sf_write_float()
sf_count_t sf_write_float (SNDFILE * sndfile, const float * ptr, sf_count_t len)
References sf_private_tag::auto_header, sf_private_tag::dataend, sf_private_tag::error, sf_private_tag::file, sf_private_tag::have_written, sf_private_tag::last_op, PSF_FILE::mode, NULL, sf_private_tag::seek, sf_private_tag::sf, SFE_BAD_WRITE_ALIGN, SFE_NEGATIVE_RW_LEN, SFE_NOT_WRITEMODE, SFE_UNIMPLEMENTED, VALIDATE_SNDFILE_AND_ASSIGN_PSF, sf_private_tag::write_current, sf_private_tag::write_float, and sf_private_tag::write_header.
Referenced by SndfileHandle::write().
sf_writef_float()
sf_count_t sf_writef_float (SNDFILE * sndfile, const float * ptr, sf_count_t frames)
References sf_private_tag::auto_header, sf_private_tag::dataend, sf_private_tag::error, sf_private_tag::file, sf_private_tag::have_written, sf_private_tag::last_op, PSF_FILE::mode, NULL, sf_private_tag::seek, sf_private_tag::sf, SFE_NEGATIVE_RW_LEN, SFE_NOT_WRITEMODE, SFE_UNIMPLEMENTED, VALIDATE_SNDFILE_AND_ASSIGN_PSF, sf_private_tag::write_current, sf_private_tag::write_float, and sf_private_tag::write_header.
Referenced by AuroraFW::AudioManager::AudioIStream::save(), and SndfileHandle::writef().
sf_write_double()
sf_count_t sf_write_double (SNDFILE * sndfile, const double * ptr, sf_count_t len)
References sf_private_tag::auto_header, sf_private_tag::dataend, sf_private_tag::error, sf_private_tag::file, sf_private_tag::have_written, sf_private_tag::last_op, PSF_FILE::mode, NULL, sf_private_tag::seek, sf_private_tag::sf, SFE_BAD_WRITE_ALIGN, SFE_NEGATIVE_RW_LEN, SFE_NOT_WRITEMODE, SFE_UNIMPLEMENTED, VALIDATE_SNDFILE_AND_ASSIGN_PSF, sf_private_tag::write_current, sf_private_tag::write_double, and sf_private_tag::write_header.
Referenced by SndfileHandle::write().
sf_writef_double()
sf_count_t sf_writef_double (SNDFILE * sndfile, const double * ptr, sf_count_t frames)
References sf_private_tag::auto_header, sf_private_tag::dataend, sf_private_tag::error, sf_private_tag::file, sf_private_tag::have_written, sf_private_tag::last_op, PSF_FILE::mode, NULL, sf_private_tag::seek, sf_private_tag::sf, SFE_NEGATIVE_RW_LEN, SFE_NOT_WRITEMODE, SFE_UNIMPLEMENTED, VALIDATE_SNDFILE_AND_ASSIGN_PSF, sf_private_tag::write_current, sf_private_tag::write_double, and sf_private_tag::write_header.
Referenced by SndfileHandle::writef().
psf_open_file()
SNDFILE* psf_open_file (SF_PRIVATE * psf, SF_INFO * sfinfo)
References aiff_open(), au_open(), sf_private_tag::auto_header, avr_open(), sf_private_tag::buf, sf_private_tag::bytewidth, caf_open(), sf_private_tag::datalength, sf_private_tag::dataoffset, dwd_open(), sf_private_tag::error, sf_private_tag::file, sf_private_tag::filelength, sf_private_tag::fileoffset, flac_open(), sf_private_tag::float_int_mult, sf_private_tag::float_max, format_from_extension(), guess_file_type(), sf_private_tag::have_written, htk_open(), ircam_open(), sf_private_tag::is_pipe, sf_private_tag::last_op, sf_private_tag::Magick, mat4_open(), mat5_open(), memcpy(), memset(), PSF_FILE::mode, mpc2k_open(), nist_open(), sf_private_tag::norm_double, sf_private_tag::norm_float, NULL, ogg_open(), paf_open(), sf_private_tag::parselog, psf_close(), psf_default_seek(), psf_fseek(), psf_ftell(), psf_get_filelen(), psf_is_pipe(), psf_log_printf(), psf_log_SF_INFO(), psf_rand_int32(), pvf_open(), raw_open(), sf_private_tag::read_current, rf64_open(), sf_private_tag::rwf_endian, rx2_open(), save_header_info(), sd2_open(), sds_open(), sf_private_tag::seek, sf_private_tag::sf, SF_CODEC, SF_CONTAINER, sf_errno, sf_error_number(), sf_format_check(), SF_FORMAT_DWD, SF_FORMAT_REX2, SF_FORMAT_TXW, sf_parselog, sf_syserr, SFE_BAD_MODE_RW, SFE_BAD_OFFSET, SFE_BAD_OPEN_FORMAT, SFE_BAD_OPEN_MODE, SFE_BAD_SF_INFO, SFE_BAD_SF_INFO_PTR, SFE_INTERNAL, SFE_NO_EMBED_SUPPORT, SFE_NO_EMBEDDED_RDWR, SFE_RAW_BAD_FORMAT, SFE_SYSTEM, SFE_UNIMPLEMENTED, SFE_UNKNOWN_FORMAT, SFE_ZERO_MAJOR_FORMAT, SFE_ZERO_MINOR_FORMAT, SNDFILE_MAGICK, svx_open(), sf_private_tag::syserr, txw_open(), sf_private_tag::unique_id, validate_psf(), validate_sfinfo(), voc_open(), w64_open(), wav_open(), sf_private_tag::write_current, wve_open(), and xi_open().
Referenced by sf_open(), sf_open_fd(), and sf_open_virtual().
sf_set_chunk()
int sf_set_chunk (SNDFILE * sndfile, const SF_CHUNK_INFO * chunk_info)
References NULL, sf_private_tag::set_chunk, SFE_BAD_CHUNK_FORMAT, SFE_BAD_CHUNK_PTR, and VALIDATE_SNDFILE_AND_ASSIGN_PSF.
sf_get_chunk_iterator()
SF_CHUNK_ITERATOR* sf_get_chunk_iterator (SNDFILE * sndfile, const SF_CHUNK_INFO * chunk_info)
References NULL, psf_get_chunk_iterator(), and VALIDATE_SNDFILE_AND_ASSIGN_PSF.
sf_next_chunk_iterator()
SF_CHUNK_ITERATOR* sf_next_chunk_iterator (SF_CHUNK_ITERATOR * iterator)
References sf_private_tag::next_chunk_iterator, NULL, SF_CHUNK_ITERATOR::sndfile, and VALIDATE_SNDFILE_AND_ASSIGN_PSF.
sf_get_chunk_size()
int sf_get_chunk_size (const SF_CHUNK_ITERATOR * iterator, SF_CHUNK_INFO * chunk_info)
References sf_private_tag::get_chunk_size, NULL, SFE_BAD_CHUNK_FORMAT, SFE_BAD_CHUNK_PTR, SF_CHUNK_ITERATOR::sndfile, and VALIDATE_SNDFILE_AND_ASSIGN_PSF.
sf_get_chunk_data()
int sf_get_chunk_data (const SF_CHUNK_ITERATOR * iterator, SF_CHUNK_INFO * chunk_info)
References sf_private_tag::get_chunk_data, NULL, SFE_BAD_CHUNK_FORMAT, SFE_BAD_CHUNK_PTR, SF_CHUNK_ITERATOR::sndfile, and VALIDATE_SNDFILE_AND_ASSIGN_PSF.
Variable Documentation
SndfileErrors
ErrorStruct SndfileErrors[] static
Referenced by sf_error_number().
sf_errno
int sf_errno = 0
Referenced by psf_open_file(), sf_command(), sf_error(), sf_error_str(), sf_open(), sf_open_fd(), sf_open_virtual(), sf_perror(), and sf_strerror().
sf_parselog
char sf_parselog[SF_BUFFER_LEN] = { 0 } static
Referenced by psf_open_file(), save_header_info(), sf_command(), and sf_open_virtual().
sf_syserr
char sf_syserr[SF_SYSERR_LEN] = { 0 } static
Referenced by psf_open_file(), and sf_strerror().