Aurora Framework: alac_encoder.c File Reference
alac_encoder.c File Reference
Macros
#define DebugMsg printf
#define VERBOSE_DEBUG 0
Typedefs
typedef int16_t(* SearchCoefs)[kALACMaxCoefs]
Enumerations
enum bool {
false = 0, true = 1, false = 0, ALAC_TRUE = 1,
false = 0, true = 1
}
Functions
int32_t alac_encode (ALAC_ENCODER *p, uint32_t numSamples, const int32_t *theReadBuffer, unsigned char *theWriteBuffer, uint32_t *ioNumBytes)
int32_t alac_encoder_init (ALAC_ENCODER *p, uint32_t samplerate, uint32_t channels, uint32_t format_flags, uint32_t frameSize)
void alac_get_magic_cookie (ALAC_ENCODER *p, void *outCookie, uint32_t *ioSize)
uint32_t alac_get_magic_cookie_size (uint32_t inNumChannels)
void alac_get_source_format (ALAC_ENCODER *p, const AudioFormatDescription *source, AudioFormatDescription *output)
void alac_set_fastmode (ALAC_ENCODER *p, int32_t fast)
static int32_t EncodeMono (ALAC_ENCODER *p, struct BitBuffer *bitstream, const int32_t *input, uint32_t stride, uint32_t channelIndex, uint32_t numSamples)
static int32_t EncodeStereo (ALAC_ENCODER *p, struct BitBuffer *bitstream, const int32_t *input, uint32_t stride, uint32_t channelIndex, uint32_t numSamples)
static int32_t EncodeStereoEscape (ALAC_ENCODER *p, struct BitBuffer *bitstream, const int32_t *input, uint32_t stride, uint32_t numSamples)
static int32_t EncodeStereoFast (ALAC_ENCODER *p, struct BitBuffer *bitstream, const int32_t *input, uint32_t stride, uint32_t channelIndex, uint32_t numSamples)
static void GetConfig (ALAC_ENCODER *p, ALACSpecificConfig *config)
Variables
const uint32_t kALACEncoderMagic = MAKE_MARKER ('d', 'p', 'g', 'e')
const uint32_t kDefaultMixBits = 2
const uint32_t kDefaultMixRes = 0
const uint32_t kDefaultNumUV = 8
const uint32_t kMaxRes = 4
const uint32_t kMaxSampleSize = 32
const uint32_t kMaxUV = 8
const uint32_t kMinUV = 4
static const uint32_t sChannelMaps [kALACMaxChannels]
Macro Definition Documentation
VERBOSE_DEBUG
#define VERBOSE_DEBUG 0
DebugMsg
#define DebugMsg printf
Referenced by EncodeMono(), EncodeStereo(), and EncodeStereoFast().
Typedef Documentation
SearchCoefs
typedef int16_t(* SearchCoefs)[kALACMaxCoefs]
Enumeration Type Documentation
bool
enum bool
Enumerator
false
true
false
ALAC_TRUE
false
true
Function Documentation
GetConfig()
void GetConfig (ALAC_ENCODER * p, ALACSpecificConfig * config) static
References ALACSpecificConfig::avgBitRate, ALACSpecificConfig::bitDepth, ALACSpecificConfig::compatibleVersion, ALACSpecificConfig::frameLength, kALACCompatibleVersion, ALACSpecificConfig::kb, KB0, alac_encoder_s::mAvgBitRate, MAX_RUN_DEFAULT, ALACSpecificConfig::maxFrameBytes, ALACSpecificConfig::maxRun, ALACSpecificConfig::mb, MB0, alac_encoder_s::mBitDepth, alac_encoder_s::mFrameSize, alac_encoder_s::mMaxFrameBytes, alac_encoder_s::mNumChannels, alac_encoder_s::mOutputSampleRate, ALACSpecificConfig::numChannels, ALACSpecificConfig::pb, PB0, ALACSpecificConfig::sampleRate, Swap16NtoB, and Swap32NtoB.
Referenced by alac_get_magic_cookie().
EncodeStereo()
static int32_t EncodeStereo (ALAC_ENCODER * p, struct BitBuffer * bitstream, const int32_t * input, uint32_t stride, uint32_t channelIndex, uint32_t numSamples) static
References ALAC_noErr, BitBufferGetPosition(), BitBufferInit(), BitBufferWrite(), DebugMsg, DENSHIFT_DEFAULT, dyn_comp(), EncodeStereoEscape(), kALAC_ParamError, KB0, kDefaultMixBits, kDefaultNumUV, kMaxRes, kMaxUV, kMinUV, MAX_RUN_DEFAULT, MB0, alac_encoder_s::mBitDepth, alac_encoder_s::mCoefsU, alac_encoder_s::mCoefsV, alac_encoder_s::mFrameSize, mix16(), mix20(), mix24(), mix32(), alac_encoder_s::mLastMixRes, alac_encoder_s::mMaxOutputBytes, alac_encoder_s::mMixBufferU, alac_encoder_s::mMixBufferV, mode(), alac_encoder_s::mPredictorU, alac_encoder_s::mPredictorV, alac_encoder_s::mShiftBufferUV, alac_encoder_s::mWorkBuffer, NULL, PB0, pc_block(), RequireAction, RequireNoErr, set_ag_params(), and true.
Referenced by alac_encode().
EncodeStereoFast()
static int32_t EncodeStereoFast (ALAC_ENCODER * p, struct BitBuffer * bitstream, const int32_t * input, uint32_t stride, uint32_t channelIndex, uint32_t numSamples) static
References BitBufferGetPosition(), BitBufferWrite(), DebugMsg, DENSHIFT_DEFAULT, dyn_comp(), EncodeStereoEscape(), kALAC_ParamError, KB0, kDefaultMixBits, kDefaultMixRes, kDefaultNumUV, MAX_RUN_DEFAULT, MB0, alac_encoder_s::mBitDepth, alac_encoder_s::mCoefsU, alac_encoder_s::mCoefsV, alac_encoder_s::mFrameSize, mix16(), mix20(), mix24(), mix32(), alac_encoder_s::mMixBufferU, alac_encoder_s::mMixBufferV, mode(), alac_encoder_s::mPredictorU, alac_encoder_s::mPredictorV, alac_encoder_s::mShiftBufferUV, PB0, pc_block(), RequireAction, RequireNoErr, set_ag_params(), and true.
Referenced by alac_encode().
EncodeStereoEscape()
static int32_t EncodeStereoEscape (ALAC_ENCODER * p, struct BitBuffer * bitstream, const int32_t * input, uint32_t stride, uint32_t numSamples) static
References ALAC_noErr, BitBufferWrite(), alac_encoder_s::mBitDepth, alac_encoder_s::mFrameSize, mix24(), alac_encoder_s::mMixBufferU, alac_encoder_s::mMixBufferV, and alac_encoder_s::mShiftBufferUV.
Referenced by EncodeStereo(), and EncodeStereoFast().
EncodeMono()
static int32_t EncodeMono (ALAC_ENCODER * p, struct BitBuffer * bitstream, const int32_t * input, uint32_t stride, uint32_t channelIndex, uint32_t numSamples) static
References ALAC_noErr, BitBufferGetPosition(), BitBufferInit(), BitBufferWrite(), DebugMsg, DENSHIFT_DEFAULT, dyn_comp(), kALAC_ParamError, KB0, MAX_RUN_DEFAULT, MB0, alac_encoder_s::mBitDepth, alac_encoder_s::mCoefsU, alac_encoder_s::mFrameSize, alac_encoder_s::mMaxOutputBytes, alac_encoder_s::mMixBufferU, alac_encoder_s::mPredictorU, alac_encoder_s::mShiftBufferUV, alac_encoder_s::mWorkBuffer, PB0, pc_block(), RequireAction, RequireNoErr, set_ag_params(), set_standard_ag_params(), and true.
Referenced by alac_encode().
alac_set_fastmode()
void alac_set_fastmode (ALAC_ENCODER * p, int32_t fast)
References alac_encoder_s::mFastMode.
alac_encode()
int32_t alac_encode (ALAC_ENCODER * p, uint32_t numSamples, const int32_t * theReadBuffer, unsigned char * theWriteBuffer, uint32_t * ioNumBytes)
References ALAC_noErr, BitBufferByteAlign(), BitBufferGetPosition(), BitBufferInit(), BitBufferWrite(), BitBuffer::byteSize, EncodeMono(), EncodeStereo(), EncodeStereoFast(), ID_CPE, ID_END, ID_LFE, ID_SCE, kALAC_ParamError, MAX, alac_encoder_s::mBitDepth, alac_encoder_s::mFastMode, alac_encoder_s::mMaxFrameBytes, alac_encoder_s::mMaxOutputBytes, alac_encoder_s::mNumChannels, alac_encoder_s::mTotalBytesGenerated, RequireAction, RequireNoErr, and sChannelMaps.
Referenced by alac_encode_block().
alac_get_magic_cookie_size()
uint32_t alac_get_magic_cookie_size (uint32_t inNumChannels)
References kChannelAtomSize.
Referenced by alac_writer_init().
alac_get_magic_cookie()
void alac_get_magic_cookie (ALAC_ENCODER * p, void * outCookie, uint32_t * ioSize)
References ALACChannelLayoutTags, GetConfig(), kChannelAtomSize, ALACAudioChannelLayout::mChannelLayoutTag, memcpy(), ALACSpecificConfig::numChannels, and Swap32NtoB.
Referenced by alac_close().
alac_encoder_init()
int32_t alac_encoder_init (ALAC_ENCODER * p, uint32_t samplerate, uint32_t channels, uint32_t format_flags, uint32_t frameSize)
References ALAC_FRAME_LENGTH, ALAC_noErr, DENSHIFT_DEFAULT, init_coefs(), kALACMaxChannels, kALACMaxCoefs, kALACMaxSearches, kDefaultMixRes, kMaxSampleSize, alac_encoder_s::mBitDepth, alac_encoder_s::mCoefsU, alac_encoder_s::mCoefsV, alac_encoder_s::mFrameSize, alac_encoder_s::mLastMixRes, alac_encoder_s::mMaxOutputBytes, alac_encoder_s::mNumChannels, and alac_encoder_s::mOutputSampleRate.
Referenced by alac_writer_init().
alac_get_source_format()
void alac_get_source_format (ALAC_ENCODER * p, const AudioFormatDescription * source, AudioFormatDescription * output)
References kALACFormatFlagIsFloat, kALACFormatLinearPCM, alac_encoder_s::mBitDepth, and source.
Variable Documentation
kALACEncoderMagic
const uint32_t kALACEncoderMagic = MAKE_MARKER ('d', 'p', 'g', 'e')
kMaxSampleSize
const uint32_t kMaxSampleSize = 32
Referenced by alac_encoder_init().
kDefaultMixBits
const uint32_t kDefaultMixBits = 2
Referenced by EncodeStereo(), and EncodeStereoFast().
kDefaultMixRes
const uint32_t kDefaultMixRes = 0
Referenced by alac_encoder_init(), and EncodeStereoFast().
kMaxRes
const uint32_t kMaxRes = 4
Referenced by EncodeStereo().
kDefaultNumUV
const uint32_t kDefaultNumUV = 8
Referenced by EncodeStereo(), and EncodeStereoFast().
kMinUV
const uint32_t kMinUV = 4
Referenced by EncodeStereo().
kMaxUV
const uint32_t kMaxUV = 8
Referenced by EncodeStereo().
sChannelMaps
const uint32_t sChannelMaps[kALACMaxChannels] static
Initial value:
=
{
    ID_SCE,
    ID_CPE,
    (ID_CPE << 3) | (ID_SCE),
    (ID_SCE << 9) | (ID_CPE << 3) | (ID_SCE),
    (ID_CPE << 9) | (ID_CPE << 3) | (ID_SCE),
    (ID_SCE << 15) | (ID_CPE << 9) | (ID_CPE << 3) | (ID_SCE),
    (ID_SCE << 18) | (ID_SCE << 15) | (ID_CPE << 9) | (ID_CPE << 3) | (ID_SCE),
    (ID_SCE << 21) | (ID_CPE << 15) | (ID_CPE << 9) | (ID_CPE << 3) | (ID_SCE)
}
Referenced by alac_encode().