Aurora Framework: gsm_create.c File Reference
gsm_create.c File Reference
Functions
gsm gsm_create (void)
void gsm_init (gsm state)
Function Documentation
gsm_create()
gsm gsm_create (void)
References memset().
Referenced by gsm610_init().
gsm_init()
void gsm_init (gsm state)
References memset(), and gsm_state::nrp.
Referenced by gsm610_seek().