Aurora Framework: AuroraFW::GEngine::VKContext Class Reference
AuroraFW::GEngine::VKContext Class Reference
Public Member Functions
VKContext (std::string &)
Static Public Member Functions
static void create (WindowProperties, std::string &)
static void destroy ()
static uint getAPIVersion ()
static VKContext * getInstance ()
static RenderAPI getRenderAPI ()
static void init (GLFWwindow *)
static void setRenderAPI (RenderAPI api)
Protected Member Functions
void _destroy () override
void _init (GLFWwindow *) override
Static Protected Attributes
static Context * _instance = AFW_NULLPTR
static RenderAPI _rapi = RenderAPI::OpenGL
static uint _version
Constructor & Destructor Documentation
VKContext()
AuroraFW::GEngine::VKContext::VKContext (std::string & name)
References GLFW_CLIENT_API, GLFW_NO_API, and glfwWindowHint().
Member Function Documentation
getInstance()
static VKContext* AuroraFW::GEngine::VKContext::getInstance () inline static
_init()
void AuroraFW::GEngine::VKContext::_init (GLFWwindow * window) override protected virtual
Implements AuroraFW::GEngine::API::Context.
References AFW_NEW, AFW_NULLPTR, AFW_NULLVAL, AURORAFW_VERSION_MAJOR, AURORAFW_VERSION_MINOR, AURORAFW_VERSION_REVISION, glfwCreateWindowSurface(), glfwGetRequiredInstanceExtensions(), VK_ERROR_EXTENSION_NOT_PRESENT, and VK_SUCCESS.
_destroy()
void AuroraFW::GEngine::VKContext::_destroy () override protected virtual
Implements AuroraFW::GEngine::API::Context.
References AFW_NULLPTR.
create()
void AuroraFW::GEngine::API::Context::create (WindowProperties wp, std::string & name) static inherited
References AuroraFW::GEngine::API::Context::_instance, AFW_NEW, AuroraFW::GEngine::API::Context::getRenderAPI(), setup::name, and OpenGL.
Referenced by AuroraFW::GEngine::Window::Window().
init()
void AuroraFW::GEngine::API::Context::init (GLFWwindow * window) static inherited
References AuroraFW::GEngine::API::Context::_init(), and AuroraFW::GEngine::API::Context::_instance.
Referenced by AuroraFW::GEngine::Window::Window().
destroy()
void AuroraFW::GEngine::API::Context::destroy () static inherited
References AuroraFW::GEngine::API::Context::_destroy(), and AuroraFW::GEngine::API::Context::_instance.
Referenced by AuroraFW::GEngine::Window::~Window().
getRenderAPI()
static RenderAPI AuroraFW::GEngine::API::Context::getRenderAPI () inline static inherited
Referenced by AuroraFW::GEngine::API::Context::create(), AuroraFW::GEngine::ImGuiLoader::Load(), and AuroraFW::GEngine::Renderer::Load().
getAPIVersion()
static uint AuroraFW::GEngine::API::Context::getAPIVersion () inline static inherited
setRenderAPI()
static void AuroraFW::GEngine::API::Context::setRenderAPI (RenderAPI api) inline static inherited
Referenced by AuroraFW::GEngine::Application::Application(), and AuroraFW::GEngine::GraphicsContext::GraphicsContext().
Member Data Documentation
_instance
Context * AuroraFW::GEngine::API::Context::_instance = AFW_NULLPTR static protected inherited
Referenced by AuroraFW::GEngine::API::Context::create(), AuroraFW::GEngine::API::Context::destroy(), and AuroraFW::GEngine::API::Context::init().
_rapi
RenderAPI AuroraFW::GEngine::API::Context::_rapi = RenderAPI::OpenGL static protected inherited
_version
uint AuroraFW::GEngine::API::Context::_version static protected inherited
The documentation for this class was generated from the following files:
vulkan/include/AuroraFW/GEngine/Vulkan/Context.h
VKContext.cpp