Aurora Framework: ag_enc.c File Reference
ag_enc.c File Reference
Macros
#define ALWAYS_INLINE
#define arithmin (a, b) ((a) < (b) ? (a) : (b))
#define CODE_TO_LONG_MAXBITS 32
#define N_MAX_MEAN_CLAMP 0xffff
#define N_MEAN_CLAMP_VAL 0xffff
#define REPORT_VAL 40
Functions
static int32_t ALWAYS_INLINE abs_func (int32_t a)
static int32_t dyn_code (int32_t m, int32_t k, int32_t n, uint32_t *outNumBits)
static int32_t dyn_code_32bit (int32_t maxbits, uint32_t m, uint32_t k, uint32_t n, uint32_t *outNumBits, uint32_t *outValue, uint32_t *overflow, uint32_t *overflowbits)
int32_t dyn_comp (AGParamRecPtr params, int32_t *pc, BitBuffer *bitstream, int32_t numSamples, int32_t bitSize, uint32_t *outNumBits)
static void ALWAYS_INLINE dyn_jam_noDeref (unsigned char *out, uint32_t bitPos, uint32_t numBits, uint32_t value)
static void ALWAYS_INLINE dyn_jam_noDeref_large (unsigned char *out, uint32_t bitPos, uint32_t numBits, uint32_t value)
static int32_t lead (int32_t m)
static int32_t ALWAYS_INLINE lg3a (int32_t x)
Macro Definition Documentation
CODE_TO_LONG_MAXBITS
#define CODE_TO_LONG_MAXBITS 32
N_MAX_MEAN_CLAMP
#define N_MAX_MEAN_CLAMP 0xffff
Referenced by dyn_comp().
N_MEAN_CLAMP_VAL
#define N_MEAN_CLAMP_VAL 0xffff
Referenced by dyn_comp().
REPORT_VAL
#define REPORT_VAL 40
ALWAYS_INLINE
#define ALWAYS_INLINE
arithmin
#define arithmin (a, b) ((a) < (b) ? (a) : (b))
Function Documentation
lead()
static int32_t lead (int32_t m) inline static
Referenced by dyn_comp(), and lg3a().
lg3a()
static int32_t ALWAYS_INLINE lg3a (int32_t x) inline static
References lead().
Referenced by dyn_comp().
abs_func()
static int32_t ALWAYS_INLINE abs_func (int32_t a) inline static
References a.
Referenced by dyn_comp().
dyn_code()
static int32_t dyn_code (int32_t m, int32_t k, int32_t n, uint32_t * outNumBits) inline static
References MAX_DATATYPE_BITS_16, MAX_PREFIX_16, and value.
Referenced by dyn_comp().
dyn_code_32bit()
static int32_t dyn_code_32bit (int32_t maxbits, uint32_t m, uint32_t k, uint32_t n, uint32_t * outNumBits, uint32_t * outValue, uint32_t * overflow, uint32_t * overflowbits) inline static
References MAX_PREFIX_32, and value.
Referenced by dyn_comp().
dyn_jam_noDeref()
static void ALWAYS_INLINE dyn_jam_noDeref (unsigned char * out, uint32_t bitPos, uint32_t numBits, uint32_t value) inline static
References psf_get_be32(), psf_put_be32(), and value.
Referenced by dyn_comp().
dyn_jam_noDeref_large()
static void ALWAYS_INLINE dyn_jam_noDeref_large (unsigned char * out, uint32_t bitPos, uint32_t numBits, uint32_t value) inline static
References psf_get_be32(), psf_put_be32(), and value.
Referenced by dyn_comp().
dyn_comp()
int32_t dyn_comp (AGParamRecPtr params, int32_t * pc, BitBuffer * bitstream, int32_t numSamples, int32_t bitSize, uint32_t * outNumBits)
References abs_func(), ALAC_noErr, BitBufferAdvance(), BitBuffer::bitIndex, BITOFF, BitBuffer::cur, dyn_code(), dyn_code_32bit(), dyn_jam_noDeref(), dyn_jam_noDeref_large(), AGParamRec::fw, kALAC_ParamError, AGParamRec::kb, lead(), lg3a(), AGParamRec::mb, AGParamRec::mb0, MDENSHIFT, MMULSHIFT, MOFF, N_MAX_MEAN_CLAMP, N_MEAN_CLAMP_VAL, AGParamRec::pb, QB, QBSHIFT, RequireAction, AGParamRec::sw, value, and AGParamRec::wb.
Referenced by EncodeMono(), EncodeStereo(), and EncodeStereoFast().