Aurora Framework: g72x_priv.h File Reference
g72x_priv.h File Reference
Classes
struct g72x_state
Macros
#define ALWAYS_INLINE
Typedefs
typedef struct g72x_state G72x_STATE
Functions
static int ALWAYS_INLINE arith_shift_left (int x, int shift)
static int ALWAYS_INLINE arith_shift_right (int x, int shift)
int g721_decoder (int code, G72x_STATE *state_ptr)
int g721_encoder (int sample, G72x_STATE *state_ptr)
int g723_16_decoder (int code, G72x_STATE *state_ptr)
int g723_16_encoder (int sample, G72x_STATE *state_ptr)
int g723_24_decoder (int code, G72x_STATE *state_ptr)
int g723_24_encoder (int sample, G72x_STATE *state_ptr)
int g723_40_decoder (int code, G72x_STATE *state_ptr)
int g723_40_encoder (int sample, G72x_STATE *state_ptr)
int predictor_pole (G72x_STATE *state_ptr)
int predictor_zero (G72x_STATE *state_ptr)
void private_init_state (G72x_STATE *state_ptr)
int quantize (int d, int y, short *table, int size)
int reconstruct (int sign, int dqln, int y)
int step_size (G72x_STATE *state_ptr)
void update (int code_size, int y, int wi, int fi, int dq, int sr, int dqsez, G72x_STATE *state_ptr)
Macro Definition Documentation
ALWAYS_INLINE
#define ALWAYS_INLINE
Typedef Documentation
G72x_STATE
typedef struct g72x_state G72x_STATE
Function Documentation
predictor_zero()
int predictor_zero (G72x_STATE * state_ptr)
References g72x_state::b, g72x_state::dq, and fmult().
Referenced by g721_decoder(), g721_encoder(), g723_16_decoder(), g723_16_encoder(), g723_24_decoder(), g723_24_encoder(), g723_40_decoder(), and g723_40_encoder().
predictor_pole()
int predictor_pole (G72x_STATE * state_ptr)
References g72x_state::a, fmult(), and g72x_state::sr.
Referenced by g721_decoder(), g721_encoder(), g723_16_decoder(), g723_16_encoder(), g723_24_decoder(), g723_24_encoder(), g723_40_decoder(), and g723_40_encoder().
step_size()
int step_size (G72x_STATE * state_ptr)
References g72x_state::ap, g72x_state::yl, and g72x_state::yu.
Referenced by g721_decoder(), g721_encoder(), g723_16_decoder(), g723_16_encoder(), g723_24_decoder(), g723_24_encoder(), g723_40_decoder(), and g723_40_encoder().
quantize()
int quantize (int d, int y, short * table, int size)
References power2, and quan().
Referenced by g721_encoder(), g723_16_encoder(), g723_24_encoder(), and g723_40_encoder().
reconstruct()
int reconstruct (int sign, int dqln, int y)
References g72x_state::dq.
Referenced by g721_decoder(), g721_encoder(), g723_16_decoder(), g723_16_encoder(), g723_24_decoder(), g723_24_encoder(), g723_40_decoder(), and g723_40_encoder().
update()
void update (int code_size, int y, int wi, int fi, int dq, int sr, int dqsez, G72x_STATE * state_ptr)
References g72x_state::a, g72x_state::ap, g72x_state::b, g72x_state::dml, g72x_state::dms, g72x_state::dq, g72x_state::pk, power2, quan(), g72x_state::sr, g72x_state::td, g72x_state::yl, and g72x_state::yu.
Referenced by g721_decoder(), g721_encoder(), g723_16_decoder(), g723_16_encoder(), g723_24_decoder(), g723_24_encoder(), g723_40_decoder(), and g723_40_encoder().
g721_encoder()
int g721_encoder (int sample, G72x_STATE * state_ptr)
References _dqlntab, _fitab, _witab, arith_shift_left(), predictor_pole(), predictor_zero(), qtab_721, quantize(), reconstruct(), step_size(), and update().
Referenced by g72x_writer_init().
g721_decoder()
int g721_decoder (int code, G72x_STATE * state_ptr)
References _dqlntab, _fitab, _witab, arith_shift_left(), predictor_pole(), predictor_zero(), reconstruct(), step_size(), and update().
Referenced by g72x_reader_init().
g723_16_encoder()
int g723_16_encoder (int sample, G72x_STATE * state_ptr)
References _dqlntab, _fitab, _witab, predictor_pole(), predictor_zero(), qtab_723_16, quantize(), reconstruct(), step_size(), and update().
Referenced by g72x_writer_init().
g723_16_decoder()
int g723_16_decoder (int code, G72x_STATE * state_ptr)
References _dqlntab, _fitab, _witab, predictor_pole(), predictor_zero(), reconstruct(), step_size(), and update().
Referenced by g72x_reader_init().
g723_24_encoder()
int g723_24_encoder (int sample, G72x_STATE * state_ptr)
References _dqlntab, _fitab, _witab, predictor_pole(), predictor_zero(), qtab_723_24, quantize(), reconstruct(), step_size(), and update().
Referenced by g723_test(), and g72x_writer_init().
g723_24_decoder()
int g723_24_decoder (int code, G72x_STATE * state_ptr)
References _dqlntab, _fitab, _witab, arith_shift_left(), predictor_pole(), predictor_zero(), reconstruct(), step_size(), and update().
Referenced by g723_test(), and g72x_reader_init().
g723_40_encoder()
int g723_40_encoder (int sample, G72x_STATE * state_ptr)
References _dqlntab, _fitab, _witab, predictor_pole(), predictor_zero(), qtab_723_40, quantize(), reconstruct(), step_size(), and update().
Referenced by g72x_writer_init().
g723_40_decoder()
int g723_40_decoder (int code, G72x_STATE * state_ptr)
References _dqlntab, _fitab, _witab, arith_shift_left(), predictor_pole(), predictor_zero(), reconstruct(), step_size(), and update().
Referenced by g72x_reader_init().
private_init_state()
void private_init_state (G72x_STATE * state_ptr)
References g72x_state::a, g72x_state::ap, g72x_state::b, g72x_state::dml, g72x_state::dms, g72x_state::dq, g72x_state::pk, g72x_state::sr, g72x_state::td, g72x_state::yl, and g72x_state::yu.
Referenced by g723_test(), g72x_reader_init(), and g72x_writer_init().
arith_shift_left()
static int ALWAYS_INLINE arith_shift_left (int x, int shift) inline static
arith_shift_right()
static int ALWAYS_INLINE arith_shift_right (int x, int shift) inline static