Aurora Framework: nist.c File Reference
nist.c File Reference
Macros
#define NIST_HEADER_LENGTH 1024
Functions
static int nist_close (SF_PRIVATE *psf)
int nist_open (SF_PRIVATE *psf)
static int nist_read_header (SF_PRIVATE *psf)
static int nist_write_header (SF_PRIVATE *psf, int calc_length)
Variables
static char bad_header []
Macro Definition Documentation
NIST_HEADER_LENGTH
#define NIST_HEADER_LENGTH 1024
Referenced by nist_read_header(), and nist_write_header().
Function Documentation
nist_close()
static int nist_close (SF_PRIVATE * psf) static
References sf_private_tag::file, PSF_FILE::mode, and nist_write_header().
Referenced by nist_open().
nist_write_header()
static int nist_write_header (SF_PRIVATE * psf, int calc_length) static
References BHWz, sf_private_tag::bytewidth, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::endian, sf_private_tag::error, sf_private_tag::filelength, sf_private_tag::header, sf_private_tag::indx, sf_private_tag::len, memset(), NIST_HEADER_LENGTH, psf_asciiheader_printf(), psf_binheader_writef(), psf_fseek(), psf_ftell(), psf_fwrite(), psf_get_filelen(), sf_private_tag::ptr, sf_private_tag::sf, SF_CODEC, and SFE_UNIMPLEMENTED.
Referenced by nist_close(), and nist_open().
nist_read_header()
static int nist_read_header (SF_PRIVATE * psf) static
References bad_header, sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::endian, sf_private_tag::filelength, NIST_HEADER_LENGTH, NULL, psf_binheader_readf(), psf_fseek(), psf_log_printf(), sf_private_tag::sf, SF_CODEC, SFE_NIST_BAD_ENCODING, SFE_NIST_BAD_HEADER, SFE_NIST_CRLF_CONVERISON, and SFE_UNIMPLEMENTED.
Referenced by nist_open().
nist_open()
int nist_open (SF_PRIVATE * psf)
References alaw_init(), sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::container_close, sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, sf_private_tag::is_pipe, PSF_FILE::mode, nist_close(), nist_read_header(), nist_write_header(), pcm_init(), sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SF_ENDIAN, SFE_BAD_OPEN_FORMAT, SFE_NO_PIPE_WRITE, SFE_UNIMPLEMENTED, ulaw_init(), and sf_private_tag::write_header.
Referenced by psf_open_file().
Variable Documentation
bad_header
char bad_header[] static
Initial value:
=
{   'N', 'I', 'S', 'T', '_', '1', 'A', 0x0d, 0x0a,
    ' ', ' ', ' ', '1', '0', '2', '4', 0x0d, 0x0a,
    0
}
Referenced by nist_read_header().