Aurora Framework: caf.c File Reference
caf.c File Reference
Classes
struct CAF_PRIVATE
struct DESC_CHUNK
struct put_buffer
Macros
#define aac_MARKER MAKE_MARKER ('a', 'a', 'c', ' ')
#define alac_MARKER MAKE_MARKER ('a', 'l', 'a', 'c')
#define alaw_MARKER MAKE_MARKER ('a', 'l', 'a', 'w')
#define CAF_PEAK_CHUNK_SIZE(ch) ((int) (sizeof (int) + ch * (sizeof (float) + 8)))
#define caff_MARKER MAKE_MARKER ('c', 'a', 'f', 'f')
#define chan_MARKER MAKE_MARKER ('c', 'h', 'a', 'n')
#define data_MARKER MAKE_MARKER ('d', 'a', 't', 'a')
#define desc_MARKER MAKE_MARKER ('d', 'e', 's', 'c')
#define edct_MARKER MAKE_MARKER ('e', 'd', 'c', 't')
#define free_MARKER MAKE_MARKER ('f', 'r', 'e', 'e')
#define ima4_MARKER MAKE_MARKER ('i', 'm', 'a', '4')
#define info_MARKER MAKE_MARKER ('i', 'n', 'f', 'o')
#define inst_MARKER MAKE_MARKER ('i', 'n', 's', 't')
#define kuki_MARKER MAKE_MARKER ('k', 'u', 'k', 'i')
#define lpcm_MARKER MAKE_MARKER ('l', 'p', 'c', 'm')
#define MAC3_MARKER MAKE_MARKER ('M', 'A', 'C', '3')
#define MAC6_MARKER MAKE_MARKER ('M', 'A', 'C', '6')
#define mark_MARKER MAKE_MARKER ('m', 'a', 'r', 'k')
#define midi_MARKER MAKE_MARKER ('m', 'i', 'd', 'i')
#define mp1_MARKER MAKE_MARKER ('.', 'm', 'p', '1')
#define mp2_MARKER MAKE_MARKER ('.', 'm', 'p', '2')
#define mp3_MARKER MAKE_MARKER ('.', 'm', 'p', '3')
#define ovvw_MARKER MAKE_MARKER ('o', 'v', 'v', 'w')
#define pakt_MARKER MAKE_MARKER ('p', 'a', 'k', 't')
#define peak_MARKER MAKE_MARKER ('p', 'e', 'a', 'k')
#define regn_MARKER MAKE_MARKER ('r', 'e', 'g', 'n')
#define SFE_CAF_BAD_PEAK 668
#define SFE_CAF_NO_DESC 667
#define SFE_CAF_NOT_CAF 666
#define strg_MARKER MAKE_MARKER ('s', 't', 'r', 'g')
#define ulaw_MARKER MAKE_MARKER ('u', 'l', 'a', 'w')
#define umid_MARKER MAKE_MARKER ('u', 'm', 'i', 'd')
#define uuid_MARKER MAKE_MARKER ('u', 'u', 'i', 'd')
Functions
static int caf_close (SF_PRIVATE *psf)
static int caf_command (SF_PRIVATE *psf, int command, void *data, int datasize)
static int caf_command (SF_PRIVATE *psf, int command, void *UNUSED(data), int UNUSED(datasize))
static int caf_get_chunk_data (SF_PRIVATE *psf, const SF_CHUNK_ITERATOR *iterator, SF_CHUNK_INFO *chunk_info)
static int caf_get_chunk_size (SF_PRIVATE *psf, const SF_CHUNK_ITERATOR *iterator, SF_CHUNK_INFO *chunk_info)
static SF_CHUNK_ITERATOR * caf_next_chunk_iterator (SF_PRIVATE *psf, SF_CHUNK_ITERATOR *iterator)
int caf_open (SF_PRIVATE *psf)
static int caf_read_chanmap (SF_PRIVATE *psf, sf_count_t chunk_size)
static int caf_read_header (SF_PRIVATE *psf)
static int caf_read_strings (SF_PRIVATE *psf, sf_count_t chunk_size)
static int caf_set_chunk (SF_PRIVATE *psf, const SF_CHUNK_INFO *chunk_info)
static int caf_write_header (SF_PRIVATE *psf, int calc_length)
static void caf_write_strings (SF_PRIVATE *psf, int location)
static int caf_write_tailer (SF_PRIVATE *psf)
static int decode_desc_chunk (SF_PRIVATE *psf, const DESC_CHUNK *desc)
static uint32_t put_key_value (struct put_buffer *buf, const char *key, const char *value)
static uint32_t string_hash32 (const char *str)
Macro Definition Documentation
aac_MARKER
#define aac_MARKER MAKE_MARKER ('a', 'a', 'c', ' ')
alac_MARKER
#define alac_MARKER MAKE_MARKER ('a', 'l', 'a', 'c')
Referenced by caf_write_header(), and decode_desc_chunk().
alaw_MARKER
#define alaw_MARKER MAKE_MARKER ('a', 'l', 'a', 'w')
Referenced by caf_write_header(), and decode_desc_chunk().
caff_MARKER
#define caff_MARKER MAKE_MARKER ('c', 'a', 'f', 'f')
Referenced by caf_read_header(), and caf_write_header().
chan_MARKER
#define chan_MARKER MAKE_MARKER ('c', 'h', 'a', 'n')
Referenced by caf_read_header(), and caf_write_header().
data_MARKER
#define data_MARKER MAKE_MARKER ('d', 'a', 't', 'a')
Referenced by caf_read_header(), caf_write_header(), wav_read_header(), wav_write_header(), and wavlike_subchunk_parse().
desc_MARKER
#define desc_MARKER MAKE_MARKER ('d', 'e', 's', 'c')
Referenced by caf_read_header(), and caf_write_header().
edct_MARKER
#define edct_MARKER MAKE_MARKER ('e', 'd', 'c', 't')
free_MARKER
#define free_MARKER MAKE_MARKER ('f', 'r', 'e', 'e')
Referenced by caf_read_header(), and caf_write_header().
ima4_MARKER
#define ima4_MARKER MAKE_MARKER ('i', 'm', 'a', '4')
info_MARKER
#define info_MARKER MAKE_MARKER ('i', 'n', 'f', 'o')
Referenced by caf_read_header(), and caf_write_strings().
inst_MARKER
#define inst_MARKER MAKE_MARKER ('i', 'n', 's', 't')
kuki_MARKER
#define kuki_MARKER MAKE_MARKER ('k', 'u', 'k', 'i')
Referenced by caf_read_header().
lpcm_MARKER
#define lpcm_MARKER MAKE_MARKER ('l', 'p', 'c', 'm')
Referenced by caf_write_header(), and decode_desc_chunk().
mark_MARKER
#define mark_MARKER MAKE_MARKER ('m', 'a', 'r', 'k')
midi_MARKER
#define midi_MARKER MAKE_MARKER ('m', 'i', 'd', 'i')
mp1_MARKER
#define mp1_MARKER MAKE_MARKER ('.', 'm', 'p', '1')
mp2_MARKER
#define mp2_MARKER MAKE_MARKER ('.', 'm', 'p', '2')
mp3_MARKER
#define mp3_MARKER MAKE_MARKER ('.', 'm', 'p', '3')
ovvw_MARKER
#define ovvw_MARKER MAKE_MARKER ('o', 'v', 'v', 'w')
pakt_MARKER
#define pakt_MARKER MAKE_MARKER ('p', 'a', 'k', 't')
Referenced by caf_read_header().
peak_MARKER
#define peak_MARKER MAKE_MARKER ('p', 'e', 'a', 'k')
Referenced by caf_read_header(), and caf_write_header().
regn_MARKER
#define regn_MARKER MAKE_MARKER ('r', 'e', 'g', 'n')
strg_MARKER
#define strg_MARKER MAKE_MARKER ('s', 't', 'r', 'g')
umid_MARKER
#define umid_MARKER MAKE_MARKER ('u', 'm', 'i', 'd')
uuid_MARKER
#define uuid_MARKER MAKE_MARKER ('u', 'u', 'i', 'd')
ulaw_MARKER
#define ulaw_MARKER MAKE_MARKER ('u', 'l', 'a', 'w')
Referenced by caf_write_header(), and decode_desc_chunk().
MAC3_MARKER
#define MAC3_MARKER MAKE_MARKER ('M', 'A', 'C', '3')
MAC6_MARKER
#define MAC6_MARKER MAKE_MARKER ('M', 'A', 'C', '6')
CAF_PEAK_CHUNK_SIZE
#define CAF_PEAK_CHUNK_SIZE (ch) ((int) (sizeof (int) + ch * (sizeof (float) + 8)))
Referenced by caf_read_header(), and caf_write_header().
SFE_CAF_NOT_CAF
#define SFE_CAF_NOT_CAF 666
Referenced by caf_read_header().
SFE_CAF_NO_DESC
#define SFE_CAF_NO_DESC 667
Referenced by caf_read_header().
SFE_CAF_BAD_PEAK
#define SFE_CAF_BAD_PEAK 668
Referenced by caf_read_header().
Function Documentation
caf_close()
static int caf_close (SF_PRIVATE * psf) static
References caf_write_header(), caf_write_tailer(), sf_private_tag::file, and PSF_FILE::mode.
Referenced by caf_open().
caf_read_header()
static int caf_read_header (SF_PRIVATE * psf) static
References CAF_PRIVATE::alac, DESC_CHUNK::bits_per_chan, sf_private_tag::bytewidth, CAF_PEAK_CHUNK_SIZE, caf_read_chanmap(), caf_read_strings(), caff_MARKER, BUF_UNION::cbuf, chan_MARKER, DESC_CHUNK::channels_per_frame, sf_private_tag::container_data, data_MARKER, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, decode_desc_chunk(), desc_MARKER, double64_be_read(), PEAK_INFO::edit_number, sf_private_tag::endian, sf_private_tag::filelength, DESC_CHUNK::fmt_flags, DESC_CHUNK::fmt_id, DESC_CHUNK::frames_per_packet, free_MARKER, sf_private_tag::header, sf_private_tag::indx, info_MARKER, kuki_MARKER, ALAC_DECODER_INFO::kuki_offset, make_size_t(), memset(), NULL, ALAC_DECODER_INFO::packets, pakt_MARKER, ALAC_DECODER_INFO::pakt_offset, sf_private_tag::peak_info, peak_info_calloc(), PEAK_INFO::peak_loc, peak_MARKER, PEAK_INFO::peaks, DESC_CHUNK::pkt_bytes, PEAK_POS::position, PRId64, ALAC_DECODER_INFO::priming_frames, psf_binheader_readf(), psf_fseek(), psf_ftell(), psf_log_printf(), psf_store_read_chunk_u32(), sf_private_tag::rchunks, ALAC_DECODER_INFO::remainder_frames, sf_private_tag::sf, SF_MAX_CHANNELS, SF_PEAK_START, SFE_CAF_BAD_PEAK, SFE_CAF_NO_DESC, SFE_CAF_NOT_CAF, SFE_INTERNAL, SFE_MALFORMED_FILE, SFE_MALLOC_FAILED, SFE_UNSUPPORTED_ENCODING, SIGNED_SIZEOF, BUF_UNION::ucbuf, ALAC_DECODER_INFO::valid_frames, PEAK_POS::value, value, and create_symbols_file::version.
Referenced by caf_open().
caf_write_header()
static int caf_write_header (SF_PRIVATE * psf, int calc_length) static
References alac_get_desc_chunk_items(), alac_MARKER, alaw_MARKER, BHW2, BHW4, BHW8, BHWf, BHWm, BHWv, BHWz, DESC_CHUNK::bits_per_chan, sf_private_tag::bytewidth, CAF_PEAK_CHUNK_SIZE, caf_write_strings(), caff_MARKER, chan_MARKER, CAF_PRIVATE::chanmap_tag, sf_private_tag::channel_map, DESC_CHUNK::channels_per_frame, WRITE_CHUNKS::chunks, sf_private_tag::container_data, WRITE_CHUNK::data, data_MARKER, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, desc_MARKER, double64_be_write(), PEAK_INFO::edit_number, sf_private_tag::endian, sf_private_tag::error, sf_private_tag::filelength, DESC_CHUNK::fmt_flags, DESC_CHUNK::fmt_id, DESC_CHUNK::frames_per_packet, free_MARKER, sf_private_tag::header, sf_private_tag::indx, WRITE_CHUNK::len, lpcm_MARKER, WRITE_CHUNK::mark32, memset(), NULL, sf_private_tag::peak_info, peak_MARKER, PEAK_INFO::peaks, DESC_CHUNK::pkt_bytes, PEAK_POS::position, psf_binheader_writef(), psf_fseek(), psf_ftell(), psf_fwrite(), psf_get_filelen(), sf_private_tag::ptr, sf_private_tag::sf, SF_CODEC, SF_ENDIAN, SF_STR_LOCATE_START, SFE_INTERNAL, SFE_UNIMPLEMENTED, BUF_UNION::ucbuf, ulaw_MARKER, WRITE_CHUNKS::used, PEAK_POS::value, and sf_private_tag::wchunks.
Referenced by caf_close(), and caf_open().
caf_write_tailer()
static int caf_write_tailer (SF_PRIVATE * psf) static
References BHWz, sf_private_tag::bytewidth, caf_write_strings(), sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::flags, sf_private_tag::header, sf_private_tag::indx, psf_binheader_writef(), psf_fseek(), psf_fwrite(), sf_private_tag::ptr, sf_private_tag::sf, SF_STR_LOCATE_END, and sf_private_tag::strings.
Referenced by caf_close().
caf_command() [1/2]
static int caf_command (SF_PRIVATE * psf, int command, void * data, int datasize) static
Referenced by caf_open().
caf_read_chanmap()
static int caf_read_chanmap (SF_PRIVATE * psf, sf_count_t chunk_size) static
References aiff_caf_of_channel_layout_tag(), AIFF_CAF_CHANNEL_MAP::channel_map, sf_private_tag::channel_map, memcpy(), AIFF_CAF_CHANNEL_MAP::name, NULL, psf_binheader_readf(), psf_log_printf(), sf_private_tag::sf, SF_MIN, and SFE_MALLOC_FAILED.
Referenced by caf_read_header().
caf_read_strings()
static int caf_read_strings (SF_PRIVATE * psf, sf_count_t chunk_size) static
References sf_private_tag::error, make_size_t(), NULL, psf_binheader_readf(), psf_log_printf(), psf_store_string(), SFE_MALLOC_FAILED, string_hash32(), and value.
Referenced by caf_read_header().
caf_write_strings()
static void caf_write_strings (SF_PRIVATE * psf, int location) static
References BHW4, BHW8, BHWm, BHWv, BHWz, sf_private_tag::data, STR_DATA::flags, put_buffer::index, info_MARKER, memset(), NULL, psf_binheader_writef(), psf_get_string(), put_key_value(), put_buffer::s, SF_MAX_STRINGS, sf_private_tag::strings, and STR_DATA::type.
Referenced by caf_write_header(), and caf_write_tailer().
caf_set_chunk()
static int caf_set_chunk (SF_PRIVATE * psf, const SF_CHUNK_INFO * chunk_info) static
References psf_save_write_chunk(), and sf_private_tag::wchunks.
Referenced by caf_open().
caf_next_chunk_iterator()
static SF_CHUNK_ITERATOR * caf_next_chunk_iterator (SF_PRIVATE * psf, SF_CHUNK_ITERATOR * iterator) static
References psf_next_chunk_iterator(), and sf_private_tag::rchunks.
Referenced by caf_open().
caf_get_chunk_size()
static int caf_get_chunk_size (SF_PRIVATE * psf, const SF_CHUNK_ITERATOR * iterator, SF_CHUNK_INFO * chunk_info) static
References READ_CHUNKS::chunks, READ_CHUNK::len, psf_find_read_chunk_iterator(), sf_private_tag::rchunks, SFE_NO_ERROR, and SFE_UNKNOWN_CHUNK.
Referenced by caf_open().
caf_get_chunk_data()
static int caf_get_chunk_data (SF_PRIVATE * psf, const SF_CHUNK_ITERATOR * iterator, SF_CHUNK_INFO * chunk_info) static
References READ_CHUNKS::chunks, READ_CHUNK::id, READ_CHUNK::id_size, READ_CHUNK::len, memcpy(), NULL, READ_CHUNK::offset, psf_find_read_chunk_iterator(), psf_fread(), psf_fseek(), psf_ftell(), sf_private_tag::rchunks, SF_MIN, SFE_BAD_CHUNK_DATA_PTR, SFE_NO_ERROR, and SFE_UNKNOWN_CHUNK.
Referenced by caf_open().
caf_open()
int caf_open (SF_PRIVATE * psf)
References CAF_PRIVATE::alac, alac_init(), alaw_init(), sf_private_tag::blockwidth, sf_private_tag::bytewidth, caf_close(), caf_command(), caf_get_chunk_data(), caf_get_chunk_size(), caf_next_chunk_iterator(), caf_read_header(), caf_set_chunk(), caf_write_header(), sf_private_tag::command, sf_private_tag::container_close, sf_private_tag::container_data, sf_private_tag::datalength, sf_private_tag::dataoffset, double64_init(), sf_private_tag::file, sf_private_tag::filelength, sf_private_tag::flags, float32_init(), sf_private_tag::get_chunk_data, sf_private_tag::get_chunk_size, sf_private_tag::is_pipe, PSF_FILE::mode, sf_private_tag::next_chunk_iterator, NULL, pcm_init(), sf_private_tag::peak_info, peak_info_calloc(), PEAK_INFO::peak_loc, sf_private_tag::set_chunk, sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SF_PEAK_START, SF_STR_ALLOW_END, SF_STR_ALLOW_START, SFE_BAD_OPEN_FORMAT, SFE_MALLOC_FAILED, SFE_NO_PIPE_WRITE, SFE_UNSUPPORTED_ENCODING, sf_private_tag::strings, ulaw_init(), and sf_private_tag::write_header.
Referenced by psf_open_file().
caf_command() [2/2]
static int caf_command (SF_PRIVATE * psf, int command, void * UNUSEDdata, int UNUSEDdatasize) static
References aiff_caf_find_channel_layout_tag(), CAF_PRIVATE::chanmap_tag, sf_private_tag::channel_map, sf_private_tag::container_data, NULL, sf_private_tag::sf, and SFE_INTERNAL.
decode_desc_chunk()
static int decode_desc_chunk (SF_PRIVATE * psf, const DESC_CHUNK * desc) static
References CAF_PRIVATE::alac, alac_MARKER, alaw_MARKER, DESC_CHUNK::bits_per_chan, ALAC_DECODER_INFO::bits_per_sample, sf_private_tag::bytewidth, DESC_CHUNK::channels_per_frame, sf_private_tag::container_data, sf_private_tag::endian, DESC_CHUNK::fmt_flags, DESC_CHUNK::fmt_id, DESC_CHUNK::frames_per_packet, ALAC_DECODER_INFO::frames_per_packet, lpcm_MARKER, NULL, DESC_CHUNK::pkt_bytes, psf_log_printf(), sf_private_tag::sf, and ulaw_MARKER.
Referenced by caf_read_header().
string_hash32()
static uint32_t string_hash32 (const char * str) static
Referenced by caf_read_strings().
put_key_value()
static uint32_t put_key_value (struct put_buffer * buf, const char * key, const char * value) static
References put_buffer::index, put_buffer::s, and value.
Referenced by caf_write_strings().