Aurora Framework: ulaw.c File Reference
ulaw.c File Reference
Functions
static void d2ulaw_array (const double *ptr, int count, unsigned char *buffer, double normfact)
static void f2ulaw_array (const float *ptr, int count, unsigned char *buffer, float normfact)
static void i2ulaw_array (const int *ptr, int count, unsigned char *buffer)
static void s2ulaw_array (const short *ptr, int count, unsigned char *buffer)
static void ulaw2d_array (const unsigned char *buffer, int count, double *ptr, double normfact)
static void ulaw2f_array (unsigned char *buffer, int count, float *ptr, float normfact)
static void ulaw2i_array (unsigned char *buffer, int count, int *ptr)
static void ulaw2s_array (unsigned char *buffer, int count, short *ptr)
int ulaw_init (SF_PRIVATE *psf)
static sf_count_t ulaw_read_ulaw2d (SF_PRIVATE *psf, double *ptr, sf_count_t len)
static sf_count_t ulaw_read_ulaw2f (SF_PRIVATE *psf, float *ptr, sf_count_t len)
static sf_count_t ulaw_read_ulaw2i (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static sf_count_t ulaw_read_ulaw2s (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static sf_count_t ulaw_write_d2ulaw (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
static sf_count_t ulaw_write_f2ulaw (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
static sf_count_t ulaw_write_i2ulaw (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
static sf_count_t ulaw_write_s2ulaw (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
Variables
static short ulaw_decode [256]
static unsigned char ulaw_encode [8193]
Function Documentation
ulaw_read_ulaw2s()
static sf_count_t ulaw_read_ulaw2s (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
References ARRAY_LEN, psf_fread(), BUF_UNION::ucbuf, and ulaw2s_array().
Referenced by ulaw_init().
ulaw_read_ulaw2i()
static sf_count_t ulaw_read_ulaw2i (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
References ARRAY_LEN, psf_fread(), BUF_UNION::ucbuf, and ulaw2i_array().
Referenced by ulaw_init().
ulaw_read_ulaw2f()
static sf_count_t ulaw_read_ulaw2f (SF_PRIVATE * psf, float * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::norm_float, psf_fread(), BUF_UNION::ucbuf, and ulaw2f_array().
Referenced by ulaw_init().
ulaw_read_ulaw2d()
static sf_count_t ulaw_read_ulaw2d (SF_PRIVATE * psf, double * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::norm_double, psf_fread(), BUF_UNION::ucbuf, and ulaw2d_array().
Referenced by ulaw_init().
ulaw_write_s2ulaw()
static sf_count_t ulaw_write_s2ulaw (SF_PRIVATE * psf, const short * ptr, sf_count_t len) static
References ARRAY_LEN, psf_fwrite(), s2ulaw_array(), and BUF_UNION::ucbuf.
Referenced by ulaw_init().
ulaw_write_i2ulaw()
static sf_count_t ulaw_write_i2ulaw (SF_PRIVATE * psf, const int * ptr, sf_count_t len) static
References ARRAY_LEN, i2ulaw_array(), psf_fwrite(), and BUF_UNION::ucbuf.
Referenced by ulaw_init().
ulaw_write_f2ulaw()
static sf_count_t ulaw_write_f2ulaw (SF_PRIVATE * psf, const float * ptr, sf_count_t len) static
References ARRAY_LEN, f2ulaw_array(), sf_private_tag::norm_float, psf_fwrite(), and BUF_UNION::ucbuf.
Referenced by ulaw_init().
ulaw_write_d2ulaw()
static sf_count_t ulaw_write_d2ulaw (SF_PRIVATE * psf, const double * ptr, sf_count_t len) static
References ARRAY_LEN, d2ulaw_array(), sf_private_tag::norm_double, psf_fwrite(), and BUF_UNION::ucbuf.
Referenced by ulaw_init().
ulaw_init()
int ulaw_init (SF_PRIVATE * psf)
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::file, sf_private_tag::filelength, PSF_FILE::mode, sf_private_tag::read_double, sf_private_tag::read_float, sf_private_tag::read_int, sf_private_tag::read_short, sf_private_tag::sf, ulaw_read_ulaw2d(), ulaw_read_ulaw2f(), ulaw_read_ulaw2i(), ulaw_read_ulaw2s(), ulaw_write_d2ulaw(), ulaw_write_f2ulaw(), ulaw_write_i2ulaw(), ulaw_write_s2ulaw(), sf_private_tag::write_double, sf_private_tag::write_float, sf_private_tag::write_int, and sf_private_tag::write_short.
Referenced by aiff_open(), au_open(), caf_open(), ircam_open(), nist_open(), raw_open(), rf64_open(), voc_open(), w64_open(), and wav_open().
ulaw2s_array()
static void ulaw2s_array (unsigned char * buffer, int count, short * ptr) inline static
References ulaw_decode.
Referenced by ulaw_read_ulaw2s().
ulaw2i_array()
static void ulaw2i_array (unsigned char * buffer, int count, int * ptr) inline static
References ulaw_decode.
Referenced by ulaw_read_ulaw2i().
ulaw2f_array()
static void ulaw2f_array (unsigned char * buffer, int count, float * ptr, float normfact) inline static
References ulaw_decode.
Referenced by ulaw_read_ulaw2f().
ulaw2d_array()
static void ulaw2d_array (const unsigned char * buffer, int count, double * ptr, double normfact) inline static
References ulaw_decode.
Referenced by ulaw_read_ulaw2d().
s2ulaw_array()
static void s2ulaw_array (const short * ptr, int count, unsigned char * buffer) inline static
References ulaw_encode.
Referenced by ulaw_write_s2ulaw().
i2ulaw_array()
static void i2ulaw_array (const int * ptr, int count, unsigned char * buffer) inline static
References ulaw_encode.
Referenced by ulaw_write_i2ulaw().
f2ulaw_array()
static void f2ulaw_array (const float * ptr, int count, unsigned char * buffer, float normfact) inline static
References ulaw_encode.
Referenced by ulaw_write_f2ulaw().
d2ulaw_array()
static void d2ulaw_array (const double * ptr, int count, unsigned char * buffer, double normfact) inline static
References ulaw_encode.
Referenced by ulaw_write_d2ulaw().
Variable Documentation
ulaw_decode
short ulaw_decode[256] static
Referenced by ulaw2d_array(), ulaw2f_array(), ulaw2i_array(), and ulaw2s_array().
ulaw_encode
unsigned char ulaw_encode[8193] static
Referenced by d2ulaw_array(), f2ulaw_array(), i2ulaw_array(), and s2ulaw_array().