Aurora Framework: Monitor.c File Reference
Monitor.c File Reference
Functions
void _glfwAllocGammaArrays (GLFWgammaramp *ramp, unsigned int size)
_GLFWmonitor * _glfwAllocMonitor (const char *name, int widthMM, int heightMM)
const GLFWvidmode * _glfwChooseVideoMode (_GLFWmonitor *monitor, const GLFWvidmode *desired)
int _glfwCompareVideoModes (const GLFWvidmode *fm, const GLFWvidmode *sm)
void _glfwFreeGammaArrays (GLFWgammaramp *ramp)
void _glfwFreeMonitor (_GLFWmonitor *monitor)
void _glfwInputMonitor (_GLFWmonitor *monitor, int action, int placement)
void _glfwInputMonitorWindow (_GLFWmonitor *monitor, _GLFWwindow *window)
void _glfwSplitBPP (int bpp, int *red, int *green, int *blue)
static int compareVideoModes (const void *fp, const void *sp)
GLFWAPI const GLFWgammaramp * glfwGetGammaRamp (GLFWmonitor *handle)
Returns the current gamma ramp for the specified monitor.
GLFWAPI void glfwGetMonitorContentScale (GLFWmonitor *handle, float *xscale, float *yscale)
Retrieves the content scale for the specified monitor.
GLFWAPI const char * glfwGetMonitorName (GLFWmonitor *handle)
Returns the name of the specified monitor.
GLFWAPI void glfwGetMonitorPhysicalSize (GLFWmonitor *handle, int *widthMM, int *heightMM)
Returns the physical size of the monitor.
GLFWAPI void glfwGetMonitorPos (GLFWmonitor *handle, int *xpos, int *ypos)
Returns the position of the monitor's viewport on the virtual screen.
GLFWAPI GLFWmonitor ** glfwGetMonitors (int *count)
Returns the currently connected monitors.
GLFWAPI void * glfwGetMonitorUserPointer (GLFWmonitor *handle)
Returns the user pointer of the specified monitor.
GLFWAPI GLFWmonitor * glfwGetPrimaryMonitor (void)
Returns the primary monitor.
GLFWAPI const GLFWvidmode * glfwGetVideoMode (GLFWmonitor *handle)
Returns the current mode of the specified monitor.
GLFWAPI const GLFWvidmode * glfwGetVideoModes (GLFWmonitor *handle, int *count)
Returns the available video modes for the specified monitor.
GLFWAPI void glfwSetGamma (GLFWmonitor *handle, float gamma)
Generates a gamma ramp and sets it for the specified monitor.
GLFWAPI void glfwSetGammaRamp (GLFWmonitor *handle, const GLFWgammaramp *ramp)
Sets the current gamma ramp for the specified monitor.
GLFWAPI GLFWmonitorfun glfwSetMonitorCallback (GLFWmonitorfun cbfun)
Sets the monitor configuration callback.
GLFWAPI void glfwSetMonitorUserPointer (GLFWmonitor *handle, void *pointer)
Sets the user pointer of the specified monitor.
static GLFWbool refreshVideoModes (_GLFWmonitor *monitor)
Function Documentation
compareVideoModes()
static int compareVideoModes (const void * fp, const void * sp) static
References GLFWvidmode::blueBits, GLFWvidmode::greenBits, GLFWvidmode::height, GLFWvidmode::redBits, GLFWvidmode::refreshRate, and GLFWvidmode::width.
Referenced by _glfwCompareVideoModes(), and refreshVideoModes().
refreshVideoModes()
static GLFWbool refreshVideoModes (_GLFWmonitor * monitor) static
References _glfwPlatformGetVideoModes(), compareVideoModes(), GLFW_FALSE, GLFW_TRUE, _GLFWmonitor::modeCount, and _GLFWmonitor::modes.
Referenced by _glfwChooseVideoMode(), and glfwGetVideoModes().
_glfwInputMonitor()
void _glfwInputMonitor (_GLFWmonitor * monitor, int action, int placement)
References _glfw, _GLFW_INSERT_FIRST, _glfwFreeMonitor(), _glfwPlatformGetWindowFrameSize(), _glfwPlatformGetWindowSize(), _glfwPlatformSetWindowMonitor(), _glfwPlatformSetWindowPos(), _GLFWlibrary::callbacks, GLFW_CONNECTED, GLFW_DISCONNECTED, height, memmove(), _GLFWwindow::monitor, _GLFWlibrary::monitor, _GLFWlibrary::monitorCount, _GLFWlibrary::monitors, _GLFWwindow::next, NULL, width, and _GLFWlibrary::windowListHead.
Referenced by _glfwPollMonitorsMir(), _glfwPollMonitorsNS(), _glfwPollMonitorsWin32(), _glfwPollMonitorsX11(), done(), and registryHandleGlobalRemove().
_glfwInputMonitorWindow()
void _glfwInputMonitorWindow (_GLFWmonitor * monitor, _GLFWwindow * window)
References _GLFWmonitor::window.
Referenced by acquireMonitor(), and releaseMonitor().
_glfwAllocMonitor()
_GLFWmonitor* _glfwAllocMonitor (const char * name, int widthMM, int heightMM)
References _glfw_strdup(), _GLFWmonitor::heightMM, setup::name, _GLFWmonitor::name, and _GLFWmonitor::widthMM.
Referenced by _glfwAddOutputWayland(), _glfwPollMonitorsMir(), _glfwPollMonitorsNS(), _glfwPollMonitorsX11(), and createMonitor().
_glfwFreeMonitor()
void _glfwFreeMonitor (_GLFWmonitor * monitor)
References _glfwFreeGammaArrays(), _glfwPlatformFreeMonitor(), _GLFWmonitor::currentRamp, _GLFWmonitor::modes, _GLFWmonitor::name, NULL, and _GLFWmonitor::originalRamp.
Referenced by _glfwAddOutputWayland(), _glfwInputMonitor(), and terminate().
_glfwAllocGammaArrays()
void _glfwAllocGammaArrays (GLFWgammaramp * ramp, unsigned int size)
References GLFWgammaramp::blue, GLFWgammaramp::green, GLFWgammaramp::red, and GLFWgammaramp::size.
Referenced by _glfwPlatformGetGammaRamp().
_glfwFreeGammaArrays()
void _glfwFreeGammaArrays (GLFWgammaramp * ramp)
References GLFWgammaramp::blue, GLFWgammaramp::green, memset(), and GLFWgammaramp::red.
Referenced by _glfwFreeMonitor(), and glfwGetGammaRamp().
_glfwChooseVideoMode()
const GLFWvidmode* _glfwChooseVideoMode (_GLFWmonitor * monitor, const GLFWvidmode * desired)
References GLFWvidmode::blueBits, GLFW_DONT_CARE, GLFWvidmode::greenBits, GLFWvidmode::height, _GLFWmonitor::modeCount, _GLFWmonitor::modes, NULL, GLFWvidmode::redBits, GLFWvidmode::refreshRate, refreshVideoModes(), and GLFWvidmode::width.
Referenced by _glfwSetVideoModeNS(), _glfwSetVideoModeWin32(), and _glfwSetVideoModeX11().
_glfwCompareVideoModes()
int _glfwCompareVideoModes (const GLFWvidmode * fm, const GLFWvidmode * sm)
References compareVideoModes().
Referenced by _glfwPlatformGetVideoModes(), _glfwSetVideoModeNS(), _glfwSetVideoModeWin32(), and _glfwSetVideoModeX11().
_glfwSplitBPP()
void _glfwSplitBPP (int bpp, int * red, int * green, int * blue)
Referenced by _glfwPlatformGetVideoMode(), _glfwPlatformGetVideoModes(), and vidmodeFromModeInfo().