Aurora Framework: Unicode.c File Reference
Unicode.c File Reference
Classes
struct codepair
Functions
long _glfwKeySym2Unicode (unsigned int keysym)
Variables
static const struct codepair keysymtab []
Function Documentation
_glfwKeySym2Unicode()
long _glfwKeySym2Unicode (unsigned int keysym)
References keysymtab, afwstd::max(), min(), and codepair::ucs.
Referenced by _glfwPlatformGetScancodeName(), handleKeyEvent(), inputChar(), and processEvent().
Variable Documentation
keysymtab
const struct codepair keysymtab[] static
Referenced by _glfwKeySym2Unicode().