Aurora Framework: AuroraFW::AudioManager::AudioOStream Struct Reference
AuroraFW::AudioManager::AudioOStream Struct Reference
A struct representing an audio output stream.
Public Member Functions
AudioOStream ()
Constructs a debug AudioOStream, which plays a "sawtooth" stereo wave.
AudioOStream (const char *, AudioSource *=nullptr, bool=false)
Constructs an AudioOStream with the specified file.
~AudioOStream ()
Destruct an AudioOStream object.
AudioSource * getAudioSource ()
Returns a pointer for the AudioSource, it there's any.
float getCpuLoad ()
Gets the current CPU load this stream is causing.
float getNumLoops ()
Gets the number of loops this stream did already.
bool isPaused ()
Returns whether the stream is currently paused.
bool isPlaying ()
Returns whether the stream is currently being played.
bool isStopped ()
Returns whether the stream is currently stopped and not just paused.
void pause ()
Pauses this audio stream.
void play ()
Starts playing this audio stream.
void setAudioSource (const AudioSource &)
Sets the current AudioSource to the given one.
void setStreamPos (unsigned int)
Sets the stream's read position to the given value in seconds.
void setStreamPosFrame (unsigned int)
Sets the stream's read position to the given frame, without counting in the number of channels.
void stop ()
Stops this audio stream, resetting it's read position to 0.
Public Attributes
AudioInfo audioInfo
The stream's AudioInfo.
AudioPlayMode audioPlayMode
The stream's AudioPlayMode.
float pitch = 1
The stream's pitch.
float volume = 1
The stream's volume.
Friends
int audioOutputCallback (const void *, void *, size_t, const PaStreamCallbackTimeInfo *, PaStreamCallbackFlags, void *)
Detailed Description
A struct representing an audio output stream.
A struct that allows a user to open an audio file and play it.
Since
snapshot20180330
Constructor & Destructor Documentation
AudioOStream() [1/2]
AuroraFW::AudioManager::AudioOStream::AudioOStream ()
Constructs a debug AudioOStream, which plays a "sawtooth" stereo wave.
See also
AudioOStream(const char* , AudioSource* , bool)
Since
snapshot20180330
References AuroraFW::AudioManager::catchPAProblem(), AuroraFW::AudioManager::debugCallback(), AuroraFW::AudioManager::AudioDevice::getDefaultSampleRate(), AuroraFW::DebugManager::Log(), and NULL.
AudioOStream() [2/2]
AuroraFW::AudioManager::AudioOStream::AudioOStream (const char * path, AudioSource * audioSource = nullptr, bool buffered = false)
Constructs an AudioOStream with the specified file.
Parameters
path The path of the file to be played. (including the file's extension)
audioSource An AudioSource object to add a 3D effect to this audio stream. (default = none)
buffered Specifies whether this audio stream should be pre-buffered on memory or streamed from disk. (default = false)
Exceptions
AudioFileNotFound In case it couldn't locate or read the audio file.
PAErrorException In case there was a PortAudio error.
See also
AudioOStream()
Since
snapshot20180330
References AFW_NEW, audioInfo, audioOutputCallback, AuroraFW::AudioManager::catchPAProblem(), AuroraFW::AudioManager::AudioInfo::getChannels(), AuroraFW::AudioManager::AudioDevice::getDefaultSampleRate(), AuroraFW::AudioManager::AudioInfo::getFrames(), AuroraFW::DebugManager::Log(), sf_open(), and sf_readf_float().
~AudioOStream()
AuroraFW::AudioManager::AudioOStream::~AudioOStream ()
Destruct an AudioOStream object.
Since
snapshot20180330
References AFW_NULLPTR.
Member Function Documentation
play()
void AuroraFW::AudioManager::AudioOStream::play ()
Starts playing this audio stream.
Exceptions
PAErrorException In case there was a PortAudio error.
See also
pause()
stop()
Since
snapshot20180330
References audioInfo, AuroraFW::AudioManager::catchPAProblem(), and sf_seek().
pause()
void AuroraFW::AudioManager::AudioOStream::pause ()
Pauses this audio stream.
Exceptions
PAErrorException In case there was a PortAudio error.
See also
play()
stop()
Since
snapshot20180330
References AuroraFW::AudioManager::catchPAProblem().
stop()
void AuroraFW::AudioManager::AudioOStream::stop ()
Stops this audio stream, resetting it's read position to 0.
Exceptions
PAErrorException In case there was a PortAudio error.
See also
play()
pause()
Since
snapshot20180330
References AuroraFW::AudioManager::catchPAProblem().
isPlaying()
bool AuroraFW::AudioManager::AudioOStream::isPlaying ()
Returns whether the stream is currently being played.
Returns
true if the stream is being currently played. false otherwise.
See also
isPaused()
isStopped()
Since
snapshot20180330
isPaused()
bool AuroraFW::AudioManager::AudioOStream::isPaused ()
Returns whether the stream is currently paused.
Returns
true if the stream is currently paused. false otherwise.
Note
If the stream is stopped, it doesn't count as being paused.
See also
isPlaying()
isStopped()
Since
snapshot20180330
References isStopped().
isStopped()
bool AuroraFW::AudioManager::AudioOStream::isStopped ()
Returns whether the stream is currently stopped and not just paused.
Returns
true if the stream is currently stopped false otherwise.
See also
isPlaying()
isPaused()
Since
snapshot20180330
Referenced by isPaused().
setStreamPos()
void AuroraFW::AudioManager::AudioOStream::setStreamPos (unsigned int pos)
Sets the stream's read position to the given value in seconds.
Parameters
pos The position from the start in seconds.
See also
setStreamPosFrame(unsigned int)
Since
snapshot20180330
setStreamPosFrame()
void AuroraFW::AudioManager::AudioOStream::setStreamPosFrame (unsigned int pos)
Sets the stream's read position to the given frame, without counting in the number of channels.
Parameters
pos The position from the start in frames.
See also
setStreamPos(unsigned int)
Since
snapshot20180330
getAudioSource()
AudioSource * AuroraFW::AudioManager::AudioOStream::getAudioSource ()
Returns a pointer for the AudioSource, it there's any.
Returns
A pointer to this stream AudioSource. nullptr in case this effect wasn't added.
See also
setAudioSource(const AudioSource&)
Since
snapshot20180330
setAudioSource()
void AuroraFW::AudioManager::AudioOStream::setAudioSource (const AudioSource & audioSource)
Sets the current AudioSource to the given one.
If this stream had a source before, it's discarded.
Parameters
audioSource The AudioSource object desired.
See also
getAudioSource()
Since
snapshot20180330
References AudioSource.
getNumLoops()
float AuroraFW::AudioManager::AudioOStream::getNumLoops () inline
Gets the number of loops this stream did already.
Returns
The number of completed loops. -1 if the AudioPlayMode is set to Once
Since
snapshot20180330
References audioPlayMode, and AuroraFW::AudioManager::Loop.
getCpuLoad()
float AuroraFW::AudioManager::AudioOStream::getCpuLoad ()
Gets the current CPU load this stream is causing.
Returns
A value ranging from 0 to 100 representing this stream's CPU load.
Since
snapshot20180330
Friends And Related Function Documentation
audioOutputCallback
int audioOutputCallback (const void * inputBuffer, void * outputBuffer, size_t framesPerBuffer, const PaStreamCallbackTimeInfo * timeInfo, PaStreamCallbackFlags statusFlags, void * userData) friend
Referenced by AudioOStream().
Member Data Documentation
audioPlayMode
AudioPlayMode AuroraFW::AudioManager::AudioOStream::audioPlayMode
The stream's AudioPlayMode.
Since
snapshot20180330
Referenced by AuroraFW::AudioManager::audioOutputCallback(), and getNumLoops().
audioInfo
AudioInfo AuroraFW::AudioManager::AudioOStream::audioInfo
The stream's AudioInfo.
Since
snapshot20180330
Referenced by AudioOStream(), AuroraFW::AudioManager::audioOutputCallback(), and play().
volume
float AuroraFW::AudioManager::AudioOStream::volume = 1
The stream's volume.
Can be set to any value, but ideally shoudl be set between 0 and 1.
Since
snapshot20180330
Referenced by AuroraFW::AudioManager::audioOutputCallback().
pitch
float AuroraFW::AudioManager::AudioOStream::pitch = 1
The stream's pitch.
To be implemented...
Since
snapshot20180330
The documentation for this struct was generated from the following files:
AudioOutput.h
AudioOutput.cpp