Aurora Framework: spirv_cross::Bitset Class Reference
spirv_cross::Bitset Class Reference
Public Member Functions
Bitset ()=default
Bitset (uint64_t lower_)
void clear (uint32_t bit)
bool empty () const
template<typename Op >
void for_each_bit (const Op &op) const
bool get (uint32_t bit) const
uint64_t get_lower () const
void merge_and (const Bitset &other)
void merge_or (const Bitset &other)
bool operator!= (const Bitset &other) const
bool operator== (const Bitset &other) const
void reset ()
void set (uint32_t bit)
Constructor & Destructor Documentation
Bitset() [1/2]
spirv_cross::Bitset::Bitset () default
Bitset() [2/2]
spirv_cross::Bitset::Bitset (uint64_t lower_) inline explicit
Member Function Documentation
get()
bool spirv_cross::Bitset::get (uint32_t bit) const inline
Referenced by spirv_cross::CompilerMSL::add_interface_block(), spirv_cross::CompilerGLSL::emit_declared_builtin_block(), spirv_cross::CompilerGLSL::emit_struct_member(), spirv_cross::CompilerGLSL::flags_to_precision_qualifiers_glsl(), spirv_cross::Compiler::ActiveBuiltinHandler::handle_builtin(), spirv_cross::Compiler::has_active_builtin(), spirv_cross::Compiler::has_decoration(), spirv_cross::Compiler::has_member_decoration(), spirv_cross::CompilerGLSL::layout_for_member(), spirv_cross::CompilerGLSL::layout_for_variable(), spirv_cross::CompilerGLSL::to_interpolation_qualifiers(), spirv_cross::CompilerGLSL::type_to_packed_alignment(), and spirv_cross::CompilerGLSL::type_to_packed_size().
set()
void spirv_cross::Bitset::set (uint32_t bit) inline
Referenced by spirv_cross::CompilerGLSL::emit_declared_builtin_block().
clear()
void spirv_cross::Bitset::clear (uint32_t bit) inline
get_lower()
uint64_t spirv_cross::Bitset::get_lower () const inline
Referenced by spirv_cross::CompilerGLSL::emit_declared_builtin_block(), spirv_cross::Compiler::get_decoration_mask(), spirv_cross::Compiler::get_execution_mode_mask(), and spirv_cross::Compiler::get_member_decoration_mask().
reset()
void spirv_cross::Bitset::reset () inline
Referenced by spirv_cross::Compiler::update_active_builtins().
merge_and()
void spirv_cross::Bitset::merge_and (const Bitset & other) inline
Referenced by spirv_cross::Compiler::get_buffer_block_flags().
merge_or()
void spirv_cross::Bitset::merge_or (const Bitset & other) inline
Referenced by spirv_cross::CompilerGLSL::combined_decoration_for_member(), spirv_cross::Compiler::get_buffer_block_flags(), and spirv_cross::CompilerGLSL::layout_for_variable().
operator==()
bool spirv_cross::Bitset::operator== (const Bitset & other) const inline
operator!=()
bool spirv_cross::Bitset::operator!= (const Bitset & other) const inline
for_each_bit()
template<typename Op > void spirv_cross::Bitset::for_each_bit (const Op & op) const inline
empty()
bool spirv_cross::Bitset::empty () const inline
Referenced by spirv_cross::CompilerGLSL::emit_declared_builtin_block().
The documentation for this class was generated from the following file:
gengine/core/include/AuroraFW/GEngine/SPIR-V/common.h