Aurora Framework: Platform.h File Reference
Mir/Platform.h File Reference
Classes
struct _GLFWcursorMir
struct _GLFWlibraryMir
struct _GLFWmonitorMir
struct _GLFWwindowMir
struct EventQueue
struct VkMirWindowCreateInfoKHR
Macros
#define _glfw_dlclose(handle) dlclose(handle)
#define _glfw_dlopen(name) dlopen(name, RTLD_LAZY | RTLD_LOCAL)
#define _glfw_dlsym(handle, name) dlsym(handle, name)
#define _GLFW_EGL_NATIVE_DISPLAY ((EGLNativeDisplayType) _glfw.mir.display)
#define _GLFW_EGL_NATIVE_WINDOW ((EGLNativeWindowType) window->mir.nativeWindow)
#define _GLFW_PLATFORM_CONTEXT_STATE
#define _GLFW_PLATFORM_CURSOR_STATE _GLFWcursorMir mir
#define _GLFW_PLATFORM_LIBRARY_CONTEXT_STATE
#define _GLFW_PLATFORM_LIBRARY_WINDOW_STATE _GLFWlibraryMir mir
#define _GLFW_PLATFORM_MONITOR_STATE _GLFWmonitorMir mir
#define _GLFW_PLATFORM_WINDOW_STATE _GLFWwindowMir mir
Typedefs
typedef struct _GLFWcursorMir _GLFWcursorMir
typedef struct _GLFWlibraryMir _GLFWlibraryMir
typedef struct _GLFWmonitorMir _GLFWmonitorMir
typedef struct _GLFWwindowMir _GLFWwindowMir
typedef struct EventQueue EventQueue
typedef VkResult(APIENTRY * PFN_vkCreateMirWindowKHR) (VkInstance, const VkMirWindowCreateInfoKHR *, const VkAllocationCallbacks *, VkSurfaceKHR *)
typedef VkBool32(APIENTRY * PFN_vkGetPhysicalDeviceMirPresentationSupportKHR) (VkPhysicalDevice, uint32_t, MirConnection *)
typedef VkFlags VkMirWindowCreateFlagsKHR
typedef struct VkMirWindowCreateInfoKHR VkMirWindowCreateInfoKHR
Functions
void _glfwDeleteEventQueueMir (EventQueue *queue)
void _glfwInitEventQueueMir (EventQueue *queue)
void _glfwPollMonitorsMir (void)
Macro Definition Documentation
_glfw_dlopen
#define _glfw_dlopen (name) dlopen(name, RTLD_LAZY | RTLD_LOCAL)
_glfw_dlclose
#define _glfw_dlclose (handle) dlclose(handle)
_glfw_dlsym
#define _glfw_dlsym (handle, name) dlsym(handle, name)
_GLFW_EGL_NATIVE_WINDOW
#define _GLFW_EGL_NATIVE_WINDOW ((EGLNativeWindowType) window->mir.nativeWindow)
_GLFW_EGL_NATIVE_DISPLAY
#define _GLFW_EGL_NATIVE_DISPLAY ((EGLNativeDisplayType) _glfw.mir.display)
_GLFW_PLATFORM_WINDOW_STATE
#define _GLFW_PLATFORM_WINDOW_STATE _GLFWwindowMir mir
_GLFW_PLATFORM_MONITOR_STATE
#define _GLFW_PLATFORM_MONITOR_STATE _GLFWmonitorMir mir
_GLFW_PLATFORM_LIBRARY_WINDOW_STATE
#define _GLFW_PLATFORM_LIBRARY_WINDOW_STATE _GLFWlibraryMir mir
_GLFW_PLATFORM_CURSOR_STATE
#define _GLFW_PLATFORM_CURSOR_STATE _GLFWcursorMir mir
_GLFW_PLATFORM_CONTEXT_STATE
#define _GLFW_PLATFORM_CONTEXT_STATE
_GLFW_PLATFORM_LIBRARY_CONTEXT_STATE
#define _GLFW_PLATFORM_LIBRARY_CONTEXT_STATE
Typedef Documentation
VkMirWindowCreateFlagsKHR
typedef VkFlags VkMirWindowCreateFlagsKHR
VkMirWindowCreateInfoKHR
typedef struct VkMirWindowCreateInfoKHR VkMirWindowCreateInfoKHR
PFN_vkCreateMirWindowKHR
typedef VkResult(APIENTRY * PFN_vkCreateMirWindowKHR) (VkInstance, const VkMirWindowCreateInfoKHR *, const VkAllocationCallbacks *, VkSurfaceKHR *)
PFN_vkGetPhysicalDeviceMirPresentationSupportKHR
typedef VkBool32(APIENTRY * PFN_vkGetPhysicalDeviceMirPresentationSupportKHR) (VkPhysicalDevice, uint32_t, MirConnection *)
EventQueue
typedef struct EventQueue EventQueue
_GLFWwindowMir
typedef struct _GLFWwindowMir _GLFWwindowMir
_GLFWmonitorMir
typedef struct _GLFWmonitorMir _GLFWmonitorMir
_GLFWlibraryMir
typedef struct _GLFWlibraryMir _GLFWlibraryMir
_GLFWcursorMir
typedef struct _GLFWcursorMir _GLFWcursorMir
Function Documentation
_glfwPollMonitorsMir()
void _glfwPollMonitorsMir (void)
References _glfw, _GLFW_INSERT_LAST, _glfwAllocMonitor(), _glfwInputMonitor(), _glfwPlatformGetVideoModes(), GLFW_CONNECTED, _GLFWmonitor::modeCount, _GLFWmonitor::modes, and setup::name.
Referenced by _glfwPlatformInit().
_glfwInitEventQueueMir()
void _glfwInitEventQueueMir (EventQueue * queue)
Referenced by _glfwPlatformInit().
_glfwDeleteEventQueueMir()
void _glfwDeleteEventQueueMir (EventQueue * queue)
References deleteNode(), and NULL.
Referenced by _glfwPlatformTerminate().