Aurora Framework: mat4.c File Reference
mat4.c File Reference
Macros
#define MAT4_BE_DOUBLE (MAKE_MARKER (0, 0, 0x03, 0xE8))
#define MAT4_BE_FLOAT (MAKE_MARKER (0, 0, 0x03, 0xF2))
#define MAT4_BE_PCM_16 (MAKE_MARKER (0, 0, 0x04, 0x06))
#define MAT4_BE_PCM_32 (MAKE_MARKER (0, 0, 0x03, 0xFC))
#define MAT4_BE_PCM_U8 (MAKE_MARKER (0, 0, 0x04, 0x1A))
#define MAT4_LE_DOUBLE (MAKE_MARKER (0, 0, 0, 0))
#define MAT4_LE_FLOAT (MAKE_MARKER (0x0A, 0, 0, 0))
#define MAT4_LE_PCM_16 (MAKE_MARKER (0x1E, 0, 0, 0))
#define MAT4_LE_PCM_32 (MAKE_MARKER (0x14, 0, 0, 0))
#define MAT4_LE_PCM_U8 (MAKE_MARKER (0x32, 0, 0, 0))
Functions
static int mat4_close (SF_PRIVATE *psf)
static int mat4_format_to_encoding (int format, int endian)
static const char * mat4_marker_to_str (int marker)
int mat4_open (SF_PRIVATE *psf)
static int mat4_read_header (SF_PRIVATE *psf)
static int mat4_write_header (SF_PRIVATE *psf, int calc_length)
Macro Definition Documentation
MAT4_BE_DOUBLE
#define MAT4_BE_DOUBLE (MAKE_MARKER (0, 0, 0x03, 0xE8))
Referenced by mat4_format_to_encoding(), mat4_marker_to_str(), mat4_read_header(), and mat4_write_header().
MAT4_LE_DOUBLE
#define MAT4_LE_DOUBLE (MAKE_MARKER (0, 0, 0, 0))
Referenced by mat4_format_to_encoding(), mat4_marker_to_str(), mat4_read_header(), and mat4_write_header().
MAT4_BE_FLOAT
#define MAT4_BE_FLOAT (MAKE_MARKER (0, 0, 0x03, 0xF2))
Referenced by mat4_format_to_encoding(), mat4_marker_to_str(), and mat4_read_header().
MAT4_LE_FLOAT
#define MAT4_LE_FLOAT (MAKE_MARKER (0x0A, 0, 0, 0))
Referenced by mat4_format_to_encoding(), mat4_marker_to_str(), and mat4_read_header().
MAT4_BE_PCM_32
#define MAT4_BE_PCM_32 (MAKE_MARKER (0, 0, 0x03, 0xFC))
Referenced by mat4_format_to_encoding(), mat4_marker_to_str(), and mat4_read_header().
MAT4_LE_PCM_32
#define MAT4_LE_PCM_32 (MAKE_MARKER (0x14, 0, 0, 0))
Referenced by mat4_format_to_encoding(), mat4_marker_to_str(), and mat4_read_header().
MAT4_BE_PCM_16
#define MAT4_BE_PCM_16 (MAKE_MARKER (0, 0, 0x04, 0x06))
Referenced by mat4_format_to_encoding(), mat4_marker_to_str(), and mat4_read_header().
MAT4_LE_PCM_16
#define MAT4_LE_PCM_16 (MAKE_MARKER (0x1E, 0, 0, 0))
Referenced by mat4_format_to_encoding(), mat4_marker_to_str(), and mat4_read_header().
MAT4_BE_PCM_U8
#define MAT4_BE_PCM_U8 (MAKE_MARKER (0, 0, 0x04, 0x1A))
MAT4_LE_PCM_U8
#define MAT4_LE_PCM_U8 (MAKE_MARKER (0x32, 0, 0, 0))
Function Documentation
mat4_close()
static int mat4_close (SF_PRIVATE * psf) static
References sf_private_tag::file, mat4_write_header(), and PSF_FILE::mode.
Referenced by mat4_open().
mat4_format_to_encoding()
static int mat4_format_to_encoding (int format, int endian) static
References MAT4_BE_DOUBLE, MAT4_BE_FLOAT, MAT4_BE_PCM_16, MAT4_BE_PCM_32, MAT4_LE_DOUBLE, MAT4_LE_FLOAT, MAT4_LE_PCM_16, and MAT4_LE_PCM_32.
Referenced by mat4_write_header().
mat4_write_header()
static int mat4_write_header (SF_PRIVATE * psf, int calc_length) static
References BHW4, BHW8, BHWd, BHWm, BHWv, BHWz, sf_private_tag::bytewidth, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::endian, sf_private_tag::error, sf_private_tag::filelength, sf_private_tag::header, sf_private_tag::indx, MAT4_BE_DOUBLE, mat4_format_to_encoding(), MAT4_LE_DOUBLE, psf_binheader_writef(), psf_fseek(), psf_ftell(), psf_fwrite(), psf_get_filelen(), sf_private_tag::ptr, sf_private_tag::sf, SF_CODEC, and SFE_BAD_OPEN_FORMAT.
Referenced by mat4_close(), and mat4_open().
mat4_read_header()
static int mat4_read_header (SF_PRIVATE * psf) static
References sf_private_tag::bytewidth, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::endian, sf_private_tag::filelength, MAT4_BE_DOUBLE, MAT4_BE_FLOAT, MAT4_BE_PCM_16, MAT4_BE_PCM_32, MAT4_LE_DOUBLE, MAT4_LE_FLOAT, MAT4_LE_PCM_16, MAT4_LE_PCM_32, mat4_marker_to_str(), setup::name, psf_binheader_readf(), psf_ftell(), psf_log_printf(), sf_private_tag::rwf_endian, sf_private_tag::sf, SF_MAX_CHANNELS, SFE_CHANNEL_COUNT, SFE_CHANNEL_COUNT_ZERO, SFE_MAT4_BAD_NAME, SFE_MAT4_NO_SAMPLERATE, SFE_UNIMPLEMENTED, SIGNED_SIZEOF, and value.
Referenced by mat4_open().
mat4_marker_to_str()
static const char * mat4_marker_to_str (int marker) static
References MAT4_BE_DOUBLE, MAT4_BE_FLOAT, MAT4_BE_PCM_16, MAT4_BE_PCM_32, MAT4_LE_DOUBLE, MAT4_LE_FLOAT, MAT4_LE_PCM_16, and MAT4_LE_PCM_32.
Referenced by mat4_read_header().
mat4_open()
int mat4_open (SF_PRIVATE * psf)
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::container_close, double64_init(), sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, float32_init(), sf_private_tag::is_pipe, mat4_close(), mat4_read_header(), mat4_write_header(), PSF_FILE::mode, pcm_init(), sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SF_ENDIAN, SFE_BAD_OPEN_FORMAT, SFE_NO_PIPE_WRITE, and sf_private_tag::write_header.
Referenced by psf_open_file().