Aurora Framework: Joystick.h File Reference
Linux/Joystick.h File Reference
Classes
struct _GLFWjoystickLinux
struct _GLFWlibraryLinux
Macros
#define _GLFW_PLATFORM_JOYSTICK_STATE _GLFWjoystickLinux linjs
#define _GLFW_PLATFORM_LIBRARY_JOYSTICK_STATE _GLFWlibraryLinux linjs
#define _GLFW_PLATFORM_MAPPING_NAME "Linux"
Typedefs
typedef struct _GLFWjoystickLinux _GLFWjoystickLinux
typedef struct _GLFWlibraryLinux _GLFWlibraryLinux
Functions
void _glfwDetectJoystickConnectionLinux (void)
GLFWbool _glfwInitJoysticksLinux (void)
void _glfwTerminateJoysticksLinux (void)
Macro Definition Documentation
_GLFW_PLATFORM_JOYSTICK_STATE
#define _GLFW_PLATFORM_JOYSTICK_STATE _GLFWjoystickLinux linjs
_GLFW_PLATFORM_LIBRARY_JOYSTICK_STATE
#define _GLFW_PLATFORM_LIBRARY_JOYSTICK_STATE _GLFWlibraryLinux linjs
_GLFW_PLATFORM_MAPPING_NAME
#define _GLFW_PLATFORM_MAPPING_NAME "Linux"
Typedef Documentation
_GLFWjoystickLinux
typedef struct _GLFWjoystickLinux _GLFWjoystickLinux
_GLFWlibraryLinux
typedef struct _GLFWlibraryLinux _GLFWlibraryLinux
Function Documentation
_glfwInitJoysticksLinux()
GLFWbool _glfwInitJoysticksLinux (void)
References _glfw, _glfwInputError(), compareJoysticks(), GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, _GLFWlibrary::joysticks, and openJoystickDevice().
Referenced by _glfwPlatformInit().
_glfwTerminateJoysticksLinux()
void _glfwTerminateJoysticksLinux (void)
References _glfw, closeJoystick(), GLFW_JOYSTICK_LAST, _GLFWlibrary::joysticks, and _GLFWjoystick::present.
Referenced by _glfwPlatformTerminate().
_glfwDetectJoystickConnectionLinux()
void _glfwDetectJoystickConnectionLinux (void)
References _glfw, closeJoystick(), GLFW_JOYSTICK_LAST, _GLFWlibrary::joysticks, openJoystickDevice(), and ssize_t.
Referenced by _glfwPlatformPollEvents().