Aurora Framework: INTERLEAVE_DATA Struct Reference
INTERLEAVE_DATA Struct Reference
Public Attributes
double buffer [SF_BUFFER_LEN/sizeof(double)]
sf_count_t channel_len
sf_count_t(* read_double)(SF_PRIVATE *, double *ptr, sf_count_t len)
sf_count_t(* read_float)(SF_PRIVATE *, float *ptr, sf_count_t len)
sf_count_t(* read_int)(SF_PRIVATE *, int *ptr, sf_count_t len)
sf_count_t(* read_short)(SF_PRIVATE *, short *ptr, sf_count_t len)
Member Data Documentation
buffer
double INTERLEAVE_DATA::buffer[SF_BUFFER_LEN/sizeof(double)]
Referenced by interleave_read_double(), interleave_read_float(), interleave_read_int(), and interleave_read_short().
channel_len
sf_count_t INTERLEAVE_DATA::channel_len
Referenced by interleave_init(), and interleave_read_float().
read_short
sf_count_t(* INTERLEAVE_DATA::read_short) (SF_PRIVATE *, short *ptr, sf_count_t len)
Referenced by interleave_init(), and interleave_read_short().
read_int
sf_count_t(* INTERLEAVE_DATA::read_int) (SF_PRIVATE *, int *ptr, sf_count_t len)
Referenced by interleave_init(), and interleave_read_int().
read_float
sf_count_t(* INTERLEAVE_DATA::read_float) (SF_PRIVATE *, float *ptr, sf_count_t len)
Referenced by interleave_init(), and interleave_read_float().
read_double
sf_count_t(* INTERLEAVE_DATA::read_double) (SF_PRIVATE *, double *ptr, sf_count_t len)
Referenced by interleave_init(), and interleave_read_double().
The documentation for this struct was generated from the following file:
interleave.c