Aurora Framework: ImDrawData Struct Reference
ImDrawData Struct Reference
Public Member Functions
ImDrawData ()
void Clear ()
IMGUI_API void DeIndexAllBuffers ()
IMGUI_API void ScaleClipRects (const ImVec2 &sc)
Public Attributes
ImDrawList ** CmdLists
int CmdListsCount
int TotalIdxCount
int TotalVtxCount
bool Valid
Constructor & Destructor Documentation
ImDrawData()
ImDrawData::ImDrawData () inline
Member Function Documentation
Clear()
void ImDrawData::Clear () inline
References NULL.
Referenced by ImGui::NewFrame().
DeIndexAllBuffers()
void ImDrawData::DeIndexAllBuffers ()
References ImVector< T >::empty(), ImDrawList::IdxBuffer, ImVector< T >::resize(), ImVector< T >::Size, ImVector< T >::swap(), and ImDrawList::VtxBuffer.
ScaleClipRects()
void ImDrawData::ScaleClipRects (const ImVec2 & sc)
References ImDrawCmd::ClipRect, ImDrawList::CmdBuffer, scale(), ImVector< T >::Size, ImVec4::w, ImVec4::x, ImVec4::y, and ImVec4::z.
Referenced by AuroraFW::GEngine::GLImGuiLoader::renderDrawLists().
Member Data Documentation
Valid
bool ImDrawData::Valid
Referenced by ImGui::GetDrawData(), and SetupDrawData().
CmdLists
ImDrawList** ImDrawData::CmdLists
Referenced by AuroraFW::GEngine::GLImGuiLoader::renderDrawLists(), and SetupDrawData().
CmdListsCount
int ImDrawData::CmdListsCount
Referenced by ImGui::Render(), AuroraFW::GEngine::GLImGuiLoader::renderDrawLists(), and SetupDrawData().
TotalVtxCount
int ImDrawData::TotalVtxCount
Referenced by ImGui::Render(), and SetupDrawData().
TotalIdxCount
int ImDrawData::TotalIdxCount
Referenced by ImGui::Render(), and SetupDrawData().
The documentation for this struct was generated from the following files:
ImGui.h
Draw.cpp