Aurora Framework: create_symbols_file Namespace Reference
create_symbols_file Namespace Reference
Functions
def darwin_symbols (progname, version)
def linux_symbols (progname, version)
def no_symbols (os_name)
def os2_symbols (progname, version, name)
def plain_symbols (progname, version, name)
def win32_symbols (progname, version, name)
Variables
tuple ALL_SYMBOLS
os_name = sys.argv [1]
progname = re.sub (".*[\\/]", "", sys.argv [0])
version = re.sub ("\.[a-z0-9]+$", "", sys.argv [2])
Function Documentation
linux_symbols()
def create_symbols_file.linux_symbols (progname, version)
darwin_symbols()
def create_symbols_file.darwin_symbols (progname, version)
win32_symbols()
def create_symbols_file.win32_symbols (progname, version, name)
os2_symbols()
def create_symbols_file.os2_symbols (progname, version, name)
plain_symbols()
def create_symbols_file.plain_symbols (progname, version, name)
no_symbols()
def create_symbols_file.no_symbols (os_name)
Variable Documentation
ALL_SYMBOLS
tuple create_symbols_file.ALL_SYMBOLS
progname
create_symbols_file.progname = re.sub (".*[\\/]", "", sys.argv [0])
Referenced by createMenuBar().
os_name
create_symbols_file.os_name = sys.argv [1]
version
create_symbols_file.version = re.sub ("\.[a-z0-9]+$", "", sys.argv [2])
Referenced by _glfwAddOutputWayland(), _glfwRefreshContextAttribs(), caf_read_header(), createNativeWindow(), is_valid_spirv_version(), glloader.__main__.main(), mat5_read_header(), matchCallback(), openJoystickDevice(), registryHandleGlobal(), voc_read_header(), wve_read_header(), and xi_read_header().