Aurora Framework: AuroraFW::ApplicationContext Class Reference
AuroraFW::ApplicationContext Class Reference
Public Member Functions
ApplicationContext (const std::string="AuroraFW Application", int=0, char **=AFW_NULL)
virtual ~ApplicationContext ()
void close ()
std::string getName ()
virtual void onClose ()
virtual void onStart ()
void setName (std::string)
void start ()
Constructor & Destructor Documentation
ApplicationContext()
AuroraFW::ApplicationContext::ApplicationContext (const std::string = "AuroraFW Application", int = 0, char ** = AFW_NULL) explicit
References AuroraFW::SplitedOptionElement::active, AuroraFW::OptionHandler::addOption(), AuroraFW::DebugManager::enable(), AuroraFW::OptionHandler::getOption(), and AuroraFW::DebugManager::Log().
~ApplicationContext()
AuroraFW::ApplicationContext::~ApplicationContext () virtual
References AuroraFW::DebugManager::Log().
Member Function Documentation
onStart()
void AuroraFW::ApplicationContext::onStart () virtual
Referenced by start().
onClose()
void AuroraFW::ApplicationContext::onClose () virtual
Referenced by close().
start()
void AuroraFW::ApplicationContext::start ()
References AuroraFW::DebugManager::Log(), and onStart().
close()
void AuroraFW::ApplicationContext::close ()
References AuroraFW::DebugManager::Log(), and onClose().
Referenced by glloader.lang.common.generator.Generator::__exit__().
getName()
std::string AuroraFW::ApplicationContext::getName ()
setName()
void AuroraFW::ApplicationContext::setName (std::string)
The documentation for this class was generated from the following files:
ApplicationContext.h
ApplicationContext.cpp