Aurora Framework: Window.c File Reference
Win32/Window.c File Reference
Macros
#define _GLFW_KEY_INVALID -2
Functions
GLFWbool _glfwIsCompositionEnabledWin32 (void)
int _glfwPlatformCreateCursor (_GLFWcursor *cursor, const GLFWimage *image, int xhot, int yhot)
int _glfwPlatformCreateStandardCursor (_GLFWcursor *cursor, int shape)
int _glfwPlatformCreateWindow (_GLFWwindow *window, const _GLFWwndconfig *wndconfig, const _GLFWctxconfig *ctxconfig, const _GLFWfbconfig *fbconfig)
VkResult _glfwPlatformCreateWindowSurface (VkInstance instance, _GLFWwindow *window, const VkAllocationCallbacks *allocator, VkSurfaceKHR *surface)
void _glfwPlatformDestroyCursor (_GLFWcursor *cursor)
void _glfwPlatformDestroyWindow (_GLFWwindow *window)
void _glfwPlatformFocusWindow (_GLFWwindow *window)
int _glfwPlatformFramebufferTransparent (_GLFWwindow *window)
const char * _glfwPlatformGetClipboardString (void)
void _glfwPlatformGetCursorPos (_GLFWwindow *window, double *xpos, double *ypos)
void _glfwPlatformGetFramebufferSize (_GLFWwindow *window, int *width, int *height)
int _glfwPlatformGetKeyScancode (int key)
int _glfwPlatformGetPhysicalDevicePresentationSupport (VkInstance instance, VkPhysicalDevice device, uint32_t queuefamily)
void _glfwPlatformGetRequiredInstanceExtensions (char **extensions)
const char * _glfwPlatformGetScancodeName (int scancode)
void _glfwPlatformGetWindowContentScale (_GLFWwindow *window, float *xscale, float *yscale)
void _glfwPlatformGetWindowFrameSize (_GLFWwindow *window, int *left, int *top, int *right, int *bottom)
float _glfwPlatformGetWindowOpacity (_GLFWwindow *window)
void _glfwPlatformGetWindowPos (_GLFWwindow *window, int *xpos, int *ypos)
void _glfwPlatformGetWindowSize (_GLFWwindow *window, int *width, int *height)
void _glfwPlatformHideWindow (_GLFWwindow *window)
void _glfwPlatformIconifyWindow (_GLFWwindow *window)
void _glfwPlatformMaximizeWindow (_GLFWwindow *window)
void _glfwPlatformPollEvents (void)
void _glfwPlatformPostEmptyEvent (void)
void _glfwPlatformRequestWindowAttention (_GLFWwindow *window)
void _glfwPlatformRestoreWindow (_GLFWwindow *window)
void _glfwPlatformSetClipboardString (const char *string)
void _glfwPlatformSetCursor (_GLFWwindow *window, _GLFWcursor *cursor)
void _glfwPlatformSetCursorMode (_GLFWwindow *window, int mode)
void _glfwPlatformSetCursorPos (_GLFWwindow *window, double xpos, double ypos)
void _glfwPlatformSetWindowAspectRatio (_GLFWwindow *window, int numer, int denom)
void _glfwPlatformSetWindowDecorated (_GLFWwindow *window, GLFWbool enabled)
void _glfwPlatformSetWindowFloating (_GLFWwindow *window, GLFWbool enabled)
void _glfwPlatformSetWindowIcon (_GLFWwindow *window, int count, const GLFWimage *images)
void _glfwPlatformSetWindowMonitor (_GLFWwindow *window, _GLFWmonitor *monitor, int xpos, int ypos, int width, int height, int refreshRate)
void _glfwPlatformSetWindowOpacity (_GLFWwindow *window, float opacity)
void _glfwPlatformSetWindowPos (_GLFWwindow *window, int xpos, int ypos)
void _glfwPlatformSetWindowResizable (_GLFWwindow *window, GLFWbool enabled)
void _glfwPlatformSetWindowSize (_GLFWwindow *window, int width, int height)
void _glfwPlatformSetWindowSizeLimits (_GLFWwindow *window, int minwidth, int minheight, int maxwidth, int maxheight)
void _glfwPlatformSetWindowTitle (_GLFWwindow *window, const char *title)
void _glfwPlatformShowWindow (_GLFWwindow *window)
void _glfwPlatformWaitEvents (void)
void _glfwPlatformWaitEventsTimeout (double timeout)
int _glfwPlatformWindowFocused (_GLFWwindow *window)
int _glfwPlatformWindowHovered (_GLFWwindow *window)
int _glfwPlatformWindowIconified (_GLFWwindow *window)
int _glfwPlatformWindowMaximized (_GLFWwindow *window)
int _glfwPlatformWindowVisible (_GLFWwindow *window)
GLFWbool _glfwRegisterWindowClassWin32 (void)
void _glfwUnregisterWindowClassWin32 (void)
static void acquireMonitor (_GLFWwindow *window)
static void applyAspectRatio (_GLFWwindow *window, int edge, RECT *area)
static void centerCursor (_GLFWwindow *window)
static const GLFWimage * chooseImage (int count, const GLFWimage *images, int width, int height)
static HICON createIcon (const GLFWimage *image, int xhot, int yhot, GLFWbool icon)
static int createNativeWindow (_GLFWwindow *window, const _GLFWwndconfig *wndconfig, const _GLFWfbconfig *fbconfig)
static GLFWbool cursorInClientArea (_GLFWwindow *window)
static void fitToMonitor (_GLFWwindow *window)
static int getAsyncKeyMods (void)
static void getFullWindowSize (DWORD style, DWORD exStyle, int clientWidth, int clientHeight, int *fullWidth, int *fullHeight)
static int getKeyMods (void)
static DWORD getWindowExStyle (const _GLFWwindow *window)
static DWORD getWindowStyle (const _GLFWwindow *window)
GLFWAPI HWND glfwGetWin32Window (GLFWwindow *handle)
static void releaseMonitor (_GLFWwindow *window)
static LPWSTR translateCursorShape (int shape)
static int translateKey (WPARAM wParam, LPARAM lParam)
static void updateClipRect (_GLFWwindow *window)
static void updateCursorImage (_GLFWwindow *window)
static void updateFramebufferTransparency (const _GLFWwindow *window)
static void updateWindowStyles (const _GLFWwindow *window)
static LRESULT CALLBACK windowProc (HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam)
Macro Definition Documentation
_GLFW_KEY_INVALID
#define _GLFW_KEY_INVALID -2
Referenced by translateKey(), and windowProc().
Function Documentation
getWindowStyle()
static DWORD getWindowStyle (const _GLFWwindow * window) static
References _GLFWwindow::decorated, _GLFWwindow::monitor, and _GLFWwindow::resizable.
Referenced by _glfwPlatformGetWindowFrameSize(), _glfwPlatformSetWindowMonitor(), _glfwPlatformSetWindowPos(), _glfwPlatformSetWindowSize(), applyAspectRatio(), createNativeWindow(), updateWindowStyles(), and windowProc().
getWindowExStyle()
static DWORD getWindowExStyle (const _GLFWwindow * window) static
References _GLFWwindow::floating, and _GLFWwindow::monitor.
Referenced by _glfwPlatformGetWindowFrameSize(), _glfwPlatformSetWindowMonitor(), _glfwPlatformSetWindowPos(), _glfwPlatformSetWindowSize(), applyAspectRatio(), createNativeWindow(), updateWindowStyles(), and windowProc().
chooseImage()
static const GLFWimage* chooseImage (int count, const GLFWimage * images, int width, int height) static
References height, NULL, and width.
Referenced by _glfwPlatformSetWindowIcon().
createIcon()
static HICON createIcon (const GLFWimage * image, int xhot, int yhot, GLFWbool icon) static
References _glfwInputErrorWin32(), GLFW_PLATFORM_ERROR, GLFWimage::height, NULL, GLFWimage::pixels, source, and GLFWimage::width.
Referenced by _glfwPlatformCreateCursor(), and _glfwPlatformSetWindowIcon().
getFullWindowSize()
static void getFullWindowSize (DWORD style, DWORD exStyle, int clientWidth, int clientHeight, int * fullWidth, int * fullHeight) static
Referenced by applyAspectRatio(), createNativeWindow(), and windowProc().
applyAspectRatio()
static void applyAspectRatio (_GLFWwindow * window, int edge, RECT * area) static
References _GLFWwindow::denom, getFullWindowSize(), getWindowExStyle(), getWindowStyle(), and _GLFWwindow::numer.
Referenced by _glfwPlatformSetWindowAspectRatio(), and windowProc().
centerCursor()
static void centerCursor (_GLFWwindow * window) static
References _glfwPlatformGetWindowSize(), _glfwPlatformSetCursorPos(), height, and width.
Referenced by _glfwPlatformSetCursorMode().
cursorInClientArea()
static GLFWbool cursorInClientArea (_GLFWwindow * window) static
References ImGui::GetCursorPos(), and GLFW_FALSE.
Referenced by _glfwPlatformSetCursor(), _glfwPlatformSetCursorMode(), and _glfwPlatformWindowHovered().
updateCursorImage()
static void updateCursorImage (_GLFWwindow * window) static
References _GLFWwindow::cursor, _GLFWwindow::cursorMode, GLFW_CURSOR_NORMAL, and NULL.
Referenced by _glfwPlatformSetCursor(), _glfwPlatformSetCursorMode(), and windowProc().
updateClipRect()
static void updateClipRect (_GLFWwindow * window) static
References NULL.
Referenced by _glfwPlatformSetCursorMode(), and windowProc().
updateWindowStyles()
static void updateWindowStyles (const _GLFWwindow * window) static
References getWindowExStyle(), getWindowStyle(), and SetWindowPos().
Referenced by _glfwPlatformSetWindowDecorated(), and _glfwPlatformSetWindowResizable().
updateFramebufferTransparency()
static void updateFramebufferTransparency (const _GLFWwindow * window) static
References _glfwIsCompositionEnabledWin32(), DWM_BLURBEHIND::dwFlags, DWM_BB_BLURREGION, DWM_BB_ENABLE, DwmEnableBlurBehindWindow, DWM_BLURBEHIND::fEnable, DWM_BLURBEHIND::hRgnBlur, IsWindowsVistaOrGreater, and NULL.
Referenced by createNativeWindow(), and windowProc().
translateCursorShape()
static LPWSTR translateCursorShape (int shape) static
References GLFW_ARROW_CURSOR, GLFW_CROSSHAIR_CURSOR, GLFW_HAND_CURSOR, GLFW_HRESIZE_CURSOR, GLFW_IBEAM_CURSOR, GLFW_VRESIZE_CURSOR, and NULL.
Referenced by _glfwPlatformCreateStandardCursor().
getKeyMods()
static int getKeyMods (void) static
References GLFW_MOD_ALT, GLFW_MOD_CAPS_LOCK, GLFW_MOD_CONTROL, GLFW_MOD_NUM_LOCK, GLFW_MOD_SHIFT, and GLFW_MOD_SUPER.
Referenced by windowProc().
getAsyncKeyMods()
static int getAsyncKeyMods (void) static
References GLFW_MOD_ALT, GLFW_MOD_CAPS_LOCK, GLFW_MOD_CONTROL, GLFW_MOD_NUM_LOCK, GLFW_MOD_SHIFT, and GLFW_MOD_SUPER.
Referenced by _glfwPlatformPollEvents().
translateKey()
static int translateKey (WPARAM wParam, LPARAM lParam) static
References _glfw, _GLFW_KEY_INVALID, GLFW_KEY_LEFT_CONTROL, GLFW_KEY_RIGHT_CONTROL, and NULL.
Referenced by windowProc().
fitToMonitor()
static void fitToMonitor (_GLFWwindow * window) static
References _GLFWwindow::monitor, and SetWindowPos().
Referenced by _glfwPlatformCreateWindow(), _glfwPlatformSetWindowMonitor(), _glfwPlatformSetWindowSize(), and windowProc().
acquireMonitor()
static void acquireMonitor (_GLFWwindow * window) static
References _glfw, _glfwInputMonitorWindow(), _glfwSetVideoModeWin32(), _GLFWwindow::monitor, _GLFWwindow::videoMode, and _GLFWmonitor::window.
Referenced by _glfwPlatformCreateWindow(), _glfwPlatformSetWindowMonitor(), _glfwPlatformSetWindowSize(), and windowProc().
releaseMonitor()
static void releaseMonitor (_GLFWwindow * window) static
References _glfw, _glfwInputMonitorWindow(), _glfwRestoreVideoModeWin32(), _GLFWwindow::monitor, NULL, and _GLFWmonitor::window.
Referenced by _glfwPlatformDestroyWindow(), _glfwPlatformSetWindowMonitor(), and windowProc().
windowProc()
static LRESULT CALLBACK windowProc (HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam) static
References _glfw, _GLFW_KEY_INVALID, _glfwCreateUTF8FromWideStringWin32(), _glfwDetectJoystickConnectionWin32(), _glfwDetectJoystickDisconnectionWin32(), _glfwInputChar(), _glfwInputCursorEnter(), _glfwInputCursorPos(), _glfwInputDrop(), _glfwInputError(), _glfwInputFramebufferSize(), _glfwInputKey(), _glfwInputMouseClick(), _glfwInputScroll(), _glfwInputWindowCloseRequest(), _glfwInputWindowContentScale(), _glfwInputWindowDamage(), _glfwInputWindowFocus(), _glfwInputWindowIconify(), _glfwInputWindowMaximize(), _glfwInputWindowPos(), _glfwInputWindowSize(), _glfwPlatformIconifyWindow(), _glfwPlatformSetCursorMode(), _glfwPollMonitorsWin32(), _glfwUpdateKeyNamesWin32(), acquireMonitor(), applyAspectRatio(), _GLFWwindow::autoIconify, _GLFWwindow::cursorMode, _GLFWwindow::decorated, _GLFWwindow::denom, fitToMonitor(), GET_XBUTTON_WPARAM, getFullWindowSize(), getKeyMods(), getWindowExStyle(), getWindowStyle(), GLFW_CURSOR_DISABLED, GLFW_CURSOR_NORMAL, GLFW_DONT_CARE, GLFW_FALSE, GLFW_KEY_LEFT_SHIFT, GLFW_KEY_RIGHT_SHIFT, GLFW_MOUSE_BUTTON_4, GLFW_MOUSE_BUTTON_5, GLFW_MOUSE_BUTTON_LAST, GLFW_MOUSE_BUTTON_LEFT, GLFW_MOUSE_BUTTON_MIDDLE, GLFW_MOUSE_BUTTON_RIGHT, GLFW_PLATFORM_ERROR, GLFW_PRESS, GLFW_RELEASE, GLFW_TRUE, _GLFWwindow::maxheight, _GLFWwindow::maxwidth, _GLFWwindow::minheight, _GLFWwindow::minwidth, _GLFWwindow::monitor, _GLFWwindow::mouseButtons, NULL, _GLFWwindow::numer, releaseMonitor(), translateKey(), UNICODE_NOCHAR, updateClipRect(), updateCursorImage(), updateFramebufferTransparency(), _GLFWwindow::virtualCursorPosX, _GLFWwindow::virtualCursorPosY, WM_DPICHANGED, WM_DWMCOMPOSITIONCHANGED, WM_MOUSEHWHEEL, and WM_UNICHAR.
Referenced by _glfwRegisterWindowClassWin32().
createNativeWindow()
static int createNativeWindow (_GLFWwindow * window, const _GLFWwndconfig * wndconfig, const _GLFWfbconfig * fbconfig) static
References _GLFW_WNDCLASSNAME, _glfwCreateWideStringFromUTF8Win32(), _glfwInputErrorWin32(), _glfwPlatformGetMonitorPos(), _glfwPlatformGetVideoMode(), ChangeWindowMessageFilterEx, getFullWindowSize(), getWindowExStyle(), getWindowStyle(), GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, _GLFWwndconfig::height, IsWindows7OrGreater, _GLFWwndconfig::maximized, mode(), _GLFWwindow::monitor, MSGFLT_ALLOW, NULL, _GLFWwndconfig::title, _GLFWfbconfig::transparent, updateFramebufferTransparency(), _GLFWwndconfig::width, and WM_COPYGLOBALDATA.
Referenced by _glfwPlatformCreateWindow().
_glfwRegisterWindowClassWin32()
GLFWbool _glfwRegisterWindowClassWin32 (void)
References _GLFW_WNDCLASSNAME, _glfwInputErrorWin32(), GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, NULL, and windowProc().
Referenced by _glfwPlatformInit().
_glfwUnregisterWindowClassWin32()
void _glfwUnregisterWindowClassWin32 (void)
References _GLFW_WNDCLASSNAME, and NULL.
Referenced by _glfwPlatformTerminate().
_glfwIsCompositionEnabledWin32()
GLFWbool _glfwIsCompositionEnabledWin32 (void)
References DwmIsCompositionEnabled, and IsWindowsVistaOrGreater.
Referenced by _glfwPlatformFramebufferTransparent(), swapBuffersWGL(), swapIntervalWGL(), and updateFramebufferTransparency().
_glfwPlatformCreateWindow()
int _glfwPlatformCreateWindow (_GLFWwindow * window, const _GLFWwndconfig * wndconfig, const _GLFWctxconfig * ctxconfig, const _GLFWfbconfig * fbconfig)
References _glfwCreateContextEGL(), _glfwCreateContextOSMesa(), _glfwCreateContextWGL(), _glfwInitEGL(), _glfwInitOSMesa(), _glfwInitWGL(), _glfwPlatformFocusWindow(), _glfwPlatformShowWindow(), acquireMonitor(), _GLFWctxconfig::client, createNativeWindow(), fitToMonitor(), GLFW_EGL_CONTEXT_API, GLFW_FALSE, GLFW_NATIVE_CONTEXT_API, GLFW_NO_API, GLFW_OSMESA_CONTEXT_API, GLFW_TRUE, _GLFWwindow::monitor, and _GLFWctxconfig::source.
_glfwPlatformDestroyWindow()
void _glfwPlatformDestroyWindow (_GLFWwindow * window)
References _glfw, _GLFWwindow::context, _GLFWcontext::destroy, _GLFWwindow::monitor, NULL, and releaseMonitor().
_glfwPlatformSetWindowTitle()
void _glfwPlatformSetWindowTitle (_GLFWwindow * window, const char * title)
References _glfwCreateWideStringFromUTF8Win32().
_glfwPlatformSetWindowIcon()
void _glfwPlatformSetWindowIcon (_GLFWwindow * window, int count, const GLFWimage * images)
References chooseImage(), createIcon(), GLFW_TRUE, and NULL.
_glfwPlatformGetWindowPos()
void _glfwPlatformGetWindowPos (_GLFWwindow * window, int * xpos, int * ypos)
_glfwPlatformSetWindowPos()
void _glfwPlatformSetWindowPos (_GLFWwindow * window, int xpos, int ypos)
References getWindowExStyle(), getWindowStyle(), NULL, and SetWindowPos().
_glfwPlatformGetWindowSize()
void _glfwPlatformGetWindowSize (_GLFWwindow * window, int * width, int * height)
References height, and width.
Referenced by _glfwPlatformGetFramebufferSize(), _glfwPlatformGetWindowFrameSize(), _glfwPlatformPollEvents(), and centerCursor().
_glfwPlatformSetWindowSize()
void _glfwPlatformSetWindowSize (_GLFWwindow * window, int width, int height)
References acquireMonitor(), fitToMonitor(), getWindowExStyle(), getWindowStyle(), height, _GLFWwindow::monitor, SetWindowPos(), width, and _GLFWmonitor::window.
_glfwPlatformSetWindowSizeLimits()
void _glfwPlatformSetWindowSizeLimits (_GLFWwindow * window, int minwidth, int minheight, int maxwidth, int maxheight)
References GLFW_DONT_CARE.
_glfwPlatformSetWindowAspectRatio()
void _glfwPlatformSetWindowAspectRatio (_GLFWwindow * window, int numer, int denom)
References applyAspectRatio(), and GLFW_DONT_CARE.
_glfwPlatformGetFramebufferSize()
void _glfwPlatformGetFramebufferSize (_GLFWwindow * window, int * width, int * height)
References _glfwPlatformGetWindowSize(), height, and width.
_glfwPlatformGetWindowFrameSize()
void _glfwPlatformGetWindowFrameSize (_GLFWwindow * window, int * left, int * top, int * right, int * bottom)
References _glfwPlatformGetWindowSize(), getWindowExStyle(), getWindowStyle(), height, and width.
_glfwPlatformGetWindowContentScale()
void _glfwPlatformGetWindowContentScale (_GLFWwindow * window, float * xscale, float * yscale)
References _glfwGetMonitorContentScaleWin32().
_glfwPlatformIconifyWindow()
void _glfwPlatformIconifyWindow (_GLFWwindow * window)
Referenced by windowProc().
_glfwPlatformRestoreWindow()
void _glfwPlatformRestoreWindow (_GLFWwindow * window)
_glfwPlatformMaximizeWindow()
void _glfwPlatformMaximizeWindow (_GLFWwindow * window)
_glfwPlatformShowWindow()
void _glfwPlatformShowWindow (_GLFWwindow * window)
Referenced by _glfwPlatformCreateWindow().
_glfwPlatformHideWindow()
void _glfwPlatformHideWindow (_GLFWwindow * window)
_glfwPlatformRequestWindowAttention()
void _glfwPlatformRequestWindowAttention (_GLFWwindow * window)
_glfwPlatformFocusWindow()
void _glfwPlatformFocusWindow (_GLFWwindow * window)
Referenced by _glfwPlatformCreateWindow().
_glfwPlatformSetWindowMonitor()
void _glfwPlatformSetWindowMonitor (_GLFWwindow * window, _GLFWmonitor * monitor, int xpos, int ypos, int width, int height, int refreshRate)
References _glfwInputWindowMonitor(), acquireMonitor(), _GLFWwindow::decorated, fitToMonitor(), _GLFWwindow::floating, getWindowExStyle(), getWindowStyle(), height, _GLFWwindow::monitor, releaseMonitor(), SetWindowPos(), width, and _GLFWmonitor::window.
_glfwPlatformWindowFocused()
int _glfwPlatformWindowFocused (_GLFWwindow * window)
_glfwPlatformWindowIconified()
int _glfwPlatformWindowIconified (_GLFWwindow * window)
_glfwPlatformWindowVisible()
int _glfwPlatformWindowVisible (_GLFWwindow * window)
_glfwPlatformWindowMaximized()
int _glfwPlatformWindowMaximized (_GLFWwindow * window)
_glfwPlatformWindowHovered()
int _glfwPlatformWindowHovered (_GLFWwindow * window)
References cursorInClientArea().
_glfwPlatformFramebufferTransparent()
int _glfwPlatformFramebufferTransparent (_GLFWwindow * window)
References _glfwIsCompositionEnabledWin32().
_glfwPlatformSetWindowResizable()
void _glfwPlatformSetWindowResizable (_GLFWwindow * window, GLFWbool enabled)
References updateWindowStyles().
_glfwPlatformSetWindowDecorated()
void _glfwPlatformSetWindowDecorated (_GLFWwindow * window, GLFWbool enabled)
References updateWindowStyles().
_glfwPlatformSetWindowFloating()
void _glfwPlatformSetWindowFloating (_GLFWwindow * window, GLFWbool enabled)
References SetWindowPos().
_glfwPlatformGetWindowOpacity()
float _glfwPlatformGetWindowOpacity (_GLFWwindow * window)
References NULL.
_glfwPlatformSetWindowOpacity()
void _glfwPlatformSetWindowOpacity (_GLFWwindow * window, float opacity)
_glfwPlatformPollEvents()
void _glfwPlatformPollEvents (void)
References _glfw, _glfwInputKey(), _glfwInputWindowCloseRequest(), _glfwPlatformGetWindowSize(), _glfwPlatformSetCursorPos(), getAsyncKeyMods(), GLFW_KEY_LEFT_SHIFT, GLFW_KEY_RIGHT_SHIFT, GLFW_PRESS, GLFW_RELEASE, height, _GLFWwindow::keys, _GLFWwindow::next, NULL, width, and _GLFWlibrary::windowListHead.
Referenced by _glfwPlatformWaitEvents(), and _glfwPlatformWaitEventsTimeout().
_glfwPlatformWaitEvents()
void _glfwPlatformWaitEvents (void)
References _glfwPlatformPollEvents().
_glfwPlatformWaitEventsTimeout()
void _glfwPlatformWaitEventsTimeout (double timeout)
References _glfwPlatformPollEvents(), and NULL.
_glfwPlatformPostEmptyEvent()
void _glfwPlatformPostEmptyEvent (void)
References _glfw.
_glfwPlatformGetCursorPos()
void _glfwPlatformGetCursorPos (_GLFWwindow * window, double * xpos, double * ypos)
References ImGui::GetCursorPos().
Referenced by _glfwPlatformSetCursorMode().
_glfwPlatformSetCursorPos()
void _glfwPlatformSetCursorPos (_GLFWwindow * window, double xpos, double ypos)
References ImGui::SetCursorPos().
Referenced by _glfwPlatformPollEvents(), _glfwPlatformSetCursorMode(), and centerCursor().
_glfwPlatformSetCursorMode()
void _glfwPlatformSetCursorMode (_GLFWwindow * window, int mode)
References _glfw, _glfwInputErrorWin32(), _glfwPlatformGetCursorPos(), _glfwPlatformSetCursorPos(), centerCursor(), cursorInClientArea(), GLFW_CURSOR_DISABLED, GLFW_PLATFORM_ERROR, mode(), NULL, updateClipRect(), and updateCursorImage().
Referenced by windowProc().
_glfwPlatformGetScancodeName()
const char* _glfwPlatformGetScancodeName (int scancode)
References _glfw.
_glfwPlatformGetKeyScancode()
int _glfwPlatformGetKeyScancode (int key)
References _glfw.
_glfwPlatformCreateCursor()
int _glfwPlatformCreateCursor (_GLFWcursor * cursor, const GLFWimage * image, int xhot, int yhot)
References createIcon(), GLFW_FALSE, and GLFW_TRUE.
_glfwPlatformCreateStandardCursor()
int _glfwPlatformCreateStandardCursor (_GLFWcursor * cursor, int shape)
References _glfwInputErrorWin32(), GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, NULL, and translateCursorShape().
_glfwPlatformDestroyCursor()
void _glfwPlatformDestroyCursor (_GLFWcursor * cursor)
_glfwPlatformSetCursor()
void _glfwPlatformSetCursor (_GLFWwindow * window, _GLFWcursor * cursor)
References cursorInClientArea(), and updateCursorImage().
_glfwPlatformSetClipboardString()
void _glfwPlatformSetClipboardString (const char * string)
References _glfw, _glfwInputErrorWin32(), GLFW_PLATFORM_ERROR, and NULL.
_glfwPlatformGetClipboardString()
const char* _glfwPlatformGetClipboardString (void)
References _glfw, _glfwCreateUTF8FromWideStringWin32(), _glfwInputErrorWin32(), GLFW_FORMAT_UNAVAILABLE, GLFW_PLATFORM_ERROR, and NULL.
_glfwPlatformGetRequiredInstanceExtensions()
void _glfwPlatformGetRequiredInstanceExtensions (char ** extensions)
References _glfw, _GLFWlibrary::KHR_surface, and _GLFWlibrary::vk.
_glfwPlatformGetPhysicalDevicePresentationSupport()
int _glfwPlatformGetPhysicalDevicePresentationSupport (VkInstance instance, VkPhysicalDevice device, uint32_t queuefamily)
References _glfwInputError(), GLFW_API_UNAVAILABLE, GLFW_FALSE, and vkGetInstanceProcAddr().
_glfwPlatformCreateWindowSurface()
VkResult _glfwPlatformCreateWindowSurface (VkInstance instance, _GLFWwindow * window, const VkAllocationCallbacks * allocator, VkSurfaceKHR * surface)
References _glfwGetVulkanResultString(), _glfwInputError(), GLFW_API_UNAVAILABLE, GLFW_PLATFORM_ERROR, VkWin32SurfaceCreateInfoKHR::hinstance, VkWin32SurfaceCreateInfoKHR::hwnd, memset(), NULL, VkWin32SurfaceCreateInfoKHR::sType, VK_ERROR_EXTENSION_NOT_PRESENT, VK_STRUCTURE_TYPE_WIN32_SURFACE_CREATE_INFO_KHR, and vkGetInstanceProcAddr().
glfwGetWin32Window()
GLFWAPI HWND glfwGetWin32Window (GLFWwindow * handle)
References _GLFW_REQUIRE_INIT_OR_RETURN, and NULL.
Referenced by AuroraFW::GEngine::ImGuiLoader::Load().