Aurora Framework: GLSL.cpp File Reference
GLSL.cpp File Reference
Macros
#define BFOP(op) emit_binary_func_op(ops[0], ops[1], ops[2], ops[3], #op)
#define BFOP(op) emit_binary_func_op(ops[0], ops[1], ops[2], ops[3], #op)
#define BFOP_CAST(op, type) emit_binary_func_op_cast(ops[0], ops[1], ops[2], ops[3], #op, type, glsl_opcode_is_sign_invariant(opcode))
#define BOP(opname, x)
#define BOP(op) emit_binary_op(ops[0], ops[1], ops[2], ops[3], #op)
#define BOP_CAST(op, type) emit_binary_op_cast(ops[0], ops[1], ops[2], ops[3], #op, type, glsl_opcode_is_sign_invariant(opcode))
#define QFOP(op) emit_quaternary_func_op(ops[0], ops[1], ops[2], ops[3], ops[4], ops[5], #op)
#define TFOP(op) emit_trinary_func_op(ops[0], ops[1], ops[2], ops[3], ops[4], #op)
#define UFOP(op) emit_unary_func_op(ops[0], ops[1], ops[2], #op)
#define UOP(opname, x)
#define UOP(op) emit_unary_op(ops[0], ops[1], ops[2], #op)
Functions
static bool glsl_opcode_is_sign_invariant (Op opcode)
static bool packing_has_flexible_offset (BufferPackingStandard packing)
static bool packing_is_hlsl (BufferPackingStandard packing)
static bool packing_is_vec4_padded (BufferPackingStandard packing)
static BufferPackingStandard packing_to_substruct_packing (BufferPackingStandard packing)
static SPIRType::BaseType pls_format_to_basetype (PlsFormat format)
static uint32_t pls_format_to_components (PlsFormat format)
static const char * to_pls_layout (PlsFormat format)
static const char * vector_swizzle (int vecsize, int index)
Macro Definition Documentation
BOP [1/2]
#define BOP (opname, x)
Value:
case Op##opname:   \
        binary = true; \
        op = x;        \
        break
Referenced by spirv_cross::CompilerGLSL::constant_op_expression(), and spirv_cross::CompilerGLSL::emit_instruction().
UOP [1/2]
#define UOP (opname, x)
Value:
case Op##opname:   \
        unary = true;  \
        op = x;        \
        break
Referenced by spirv_cross::CompilerGLSL::constant_op_expression(), and spirv_cross::CompilerGLSL::emit_instruction().
BOP [2/2]
#define BOP (op) emit_binary_op(ops[0], ops[1], ops[2], ops[3], #op)
BOP_CAST
#define BOP_CAST (op, type) emit_binary_op_cast(ops[0], ops[1], ops[2], ops[3], #op, type, glsl_opcode_is_sign_invariant(opcode))
Referenced by spirv_cross::CompilerGLSL::emit_instruction().
UOP [2/2]
#define UOP (op) emit_unary_op(ops[0], ops[1], ops[2], #op)
QFOP
#define QFOP (op) emit_quaternary_func_op(ops[0], ops[1], ops[2], ops[3], ops[4], ops[5], #op)
Referenced by spirv_cross::CompilerGLSL::emit_instruction().
TFOP
#define TFOP (op) emit_trinary_func_op(ops[0], ops[1], ops[2], ops[3], ops[4], #op)
Referenced by spirv_cross::CompilerGLSL::emit_instruction().
BFOP [1/2]
#define BFOP (op) emit_binary_func_op(ops[0], ops[1], ops[2], ops[3], #op)
Referenced by spirv_cross::CompilerGLSL::emit_instruction().
BFOP_CAST
#define BFOP_CAST (op, type) emit_binary_func_op_cast(ops[0], ops[1], ops[2], ops[3], #op, type, glsl_opcode_is_sign_invariant(opcode))
Referenced by spirv_cross::CompilerGLSL::emit_instruction().
BFOP [2/2]
#define BFOP (op) emit_binary_func_op(ops[0], ops[1], ops[2], ops[3], #op)
UFOP
#define UFOP (op) emit_unary_func_op(ops[0], ops[1], ops[2], #op)
Referenced by spirv_cross::CompilerGLSL::emit_instruction().
Function Documentation
packing_is_vec4_padded()
static bool packing_is_vec4_padded (BufferPackingStandard packing) static
References spirv_cross::BufferPackingHLSLCbuffer, spirv_cross::BufferPackingHLSLCbufferPackOffset, spirv_cross::BufferPackingStd140, and spirv_cross::BufferPackingStd140EnhancedLayout.
Referenced by spirv_cross::CompilerGLSL::type_to_packed_alignment(), and spirv_cross::CompilerGLSL::type_to_packed_size().
packing_is_hlsl()
static bool packing_is_hlsl (BufferPackingStandard packing) static
References spirv_cross::BufferPackingHLSLCbuffer, and spirv_cross::BufferPackingHLSLCbufferPackOffset.
Referenced by spirv_cross::CompilerGLSL::buffer_is_packing_standard(), and spirv_cross::CompilerGLSL::type_to_packed_alignment().
packing_has_flexible_offset()
static bool packing_has_flexible_offset (BufferPackingStandard packing) static
References spirv_cross::BufferPackingHLSLCbuffer, spirv_cross::BufferPackingStd140, and spirv_cross::BufferPackingStd430.
Referenced by spirv_cross::CompilerGLSL::buffer_is_packing_standard().
packing_to_substruct_packing()
static BufferPackingStandard packing_to_substruct_packing (BufferPackingStandard packing) static
References spirv_cross::BufferPackingHLSLCbuffer, spirv_cross::BufferPackingHLSLCbufferPackOffset, spirv_cross::BufferPackingStd140, spirv_cross::BufferPackingStd140EnhancedLayout, spirv_cross::BufferPackingStd430, and spirv_cross::BufferPackingStd430EnhancedLayout.
Referenced by spirv_cross::CompilerGLSL::buffer_is_packing_standard().
glsl_opcode_is_sign_invariant()
static bool glsl_opcode_is_sign_invariant (Op opcode) static
References spv::OpBitwiseAnd, spv::OpBitwiseOr, spv::OpBitwiseXor, spv::OpIAdd, spv::OpIEqual, spv::OpIMul, spv::OpINotEqual, spv::OpISub, and spv::OpShiftLeftLogical.
Referenced by spirv_cross::CompilerGLSL::constant_op_expression().
to_pls_layout()
static const char* to_pls_layout (PlsFormat format) static
References spirv_cross::PlsR11FG11FB10F, spirv_cross::PlsR32F, spirv_cross::PlsR32UI, spirv_cross::PlsRG16, spirv_cross::PlsRG16F, spirv_cross::PlsRG16I, spirv_cross::PlsRG16UI, spirv_cross::PlsRGB10A2, spirv_cross::PlsRGB10A2UI, spirv_cross::PlsRGBA8, spirv_cross::PlsRGBA8I, and spirv_cross::PlsRGBA8UI.
Referenced by spirv_cross::CompilerGLSL::pls_decl().
pls_format_to_basetype()
static SPIRType::BaseType pls_format_to_basetype (PlsFormat format) static
References spirv_cross::PlsR11FG11FB10F, spirv_cross::PlsR32F, spirv_cross::PlsR32UI, spirv_cross::PlsRG16, spirv_cross::PlsRG16F, spirv_cross::PlsRG16I, spirv_cross::PlsRG16UI, spirv_cross::PlsRGB10A2, spirv_cross::PlsRGB10A2UI, spirv_cross::PlsRGBA8, spirv_cross::PlsRGBA8I, and spirv_cross::PlsRGBA8UI.
Referenced by spirv_cross::CompilerGLSL::pls_decl().
pls_format_to_components()
static uint32_t pls_format_to_components (PlsFormat format) static
References spirv_cross::PlsR11FG11FB10F, spirv_cross::PlsR32F, spirv_cross::PlsR32UI, spirv_cross::PlsRG16, spirv_cross::PlsRG16F, spirv_cross::PlsRG16I, spirv_cross::PlsRG16UI, spirv_cross::PlsRGB10A2, spirv_cross::PlsRGB10A2UI, spirv_cross::PlsRGBA8, spirv_cross::PlsRGBA8I, and spirv_cross::PlsRGBA8UI.
Referenced by spirv_cross::CompilerGLSL::emit_instruction(), and spirv_cross::CompilerGLSL::pls_decl().
vector_swizzle()
static const char* vector_swizzle (int vecsize, int index) static
Referenced by spirv_cross::CompilerGLSL::flattened_access_chain_vector().