Aurora Framework: GenericReader< SourceEncoding, TargetEncoding, StackAllocator > Class Template Reference
GenericReader< SourceEncoding, TargetEncoding, StackAllocator > Class Template Reference
SAX-style JSON parser. Use Reader for UTF8 encoding and default allocator.
Public Types
typedef SourceEncoding::Ch Ch
SourceEncoding character type.
Public Member Functions
GenericReader (StackAllocator *stackAllocator=0, size_t stackCapacity=kDefaultStackCapacity)
Constructor.
size_t GetErrorOffset () const
Get the position of last parsing error in input, 0 otherwise.
ParseErrorCode GetParseErrorCode () const
Get the ParseErrorCode of last parsing.
bool HasParseError () const
Whether a parse error has occurred in the last parsing.
RAPIDJSON_FORCEINLINE bool IterativeParseComplete ()
Check if token-by-token parsing JSON text is complete.
void IterativeParseInit ()
Initialize JSON text token-by-token parsing.
template<unsigned parseFlags, typename InputStream , typename Handler >
bool IterativeParseNext (InputStream &is, Handler &handler)
Parse one token from JSON text.
template<unsigned parseFlags, typename InputStream , typename Handler >
ParseResult Parse (InputStream &is, Handler &handler)
Parse JSON text.
template<typename InputStream , typename Handler >
ParseResult Parse (InputStream &is, Handler &handler)
Parse JSON text (with kParseDefaultFlags)
Protected Member Functions
void SetParseError (ParseErrorCode code, size_t offset)
Detailed Description
template<typename SourceEncoding, typename TargetEncoding, typename StackAllocator = CrtAllocator>
class GenericReader< SourceEncoding, TargetEncoding, StackAllocator >
SAX-style JSON parser. Use Reader for UTF8 encoding and default allocator.
GenericReader parses JSON text from a stream, and send events synchronously to an object implementing Handler concept.
It needs to allocate a stack for storing a single decoded string during non-destructive parsing.
For in-situ parsing, the decoded string is directly written to the source text string, no temporary buffer is required.
A GenericReader object can be reused for parsing multiple JSON text.
Template Parameters
SourceEncoding Encoding of the input stream.
TargetEncoding Encoding of the parse output.
StackAllocator Allocator type for stack.
Member Typedef Documentation
Ch
template<typename SourceEncoding, typename TargetEncoding, typename StackAllocator = CrtAllocator> typedef SourceEncoding::Ch GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Ch
SourceEncoding character type.
Constructor & Destructor Documentation
GenericReader()
template<typename SourceEncoding, typename TargetEncoding, typename StackAllocator = CrtAllocator> GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::GenericReader (StackAllocator * stackAllocator = 0, size_t stackCapacity = kDefaultStackCapacity) inline
Constructor.
Parameters
stackAllocator Optional allocator for allocating stack memory. (Only use for non-destructive parsing)
stackCapacity stack capacity in bytes for storing a single decoded string. (Only use for non-destructive parsing)
Member Function Documentation
Parse() [1/2]
template<typename SourceEncoding, typename TargetEncoding, typename StackAllocator = CrtAllocator> template<unsigned parseFlags, typename InputStream , typename Handler > ParseResult GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse (InputStream & is, Handler & handler) inline
Parse JSON text.
Template Parameters
parseFlags Combination of ParseFlag.
InputStream Type of input stream, implementing Stream concept.
Handler Type of handler, implementing Handler concept.
Parameters
is Input stream to be parsed.
handler The handler to receive events.
Returns
Whether the parsing is successful.
References ParseResult::Clear(), kParseErrorDocumentEmpty, kParseErrorDocumentRootNotSingular, kParseIterativeFlag, kParseStopWhenDoneFlag, RAPIDJSON_PARSE_ERROR_NORETURN, and RAPIDJSON_UNLIKELY.
Parse() [2/2]
template<typename SourceEncoding, typename TargetEncoding, typename StackAllocator = CrtAllocator> template<typename InputStream , typename Handler > ParseResult GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::Parse (InputStream & is, Handler & handler) inline
Parse JSON text (with kParseDefaultFlags)
Template Parameters
InputStream Type of input stream, implementing Stream concept
Handler Type of handler, implementing Handler concept.
Parameters
is Input stream to be parsed.
handler The handler to receive events.
Returns
Whether the parsing is successful.
IterativeParseInit()
template<typename SourceEncoding, typename TargetEncoding, typename StackAllocator = CrtAllocator> void GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseInit () inline
Initialize JSON text token-by-token parsing.
References ParseResult::Clear().
IterativeParseNext()
template<typename SourceEncoding, typename TargetEncoding, typename StackAllocator = CrtAllocator> template<unsigned parseFlags, typename InputStream , typename Handler > bool GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseNext (InputStream & is, Handler & handler) inline
Parse one token from JSON text.
Template Parameters
InputStream Type of input stream, implementing Stream concept
Handler Type of handler, implementing Handler concept.
Parameters
is Input stream to be parsed.
handler The handler to receive events.
Returns
Whether the parsing is successful.
References internal::Stack< Allocator >::Clear(), kParseStopWhenDoneFlag, RAPIDJSON_ASSERT, RAPIDJSON_LIKELY, and RAPIDJSON_UNLIKELY.
IterativeParseComplete()
template<typename SourceEncoding, typename TargetEncoding, typename StackAllocator = CrtAllocator> RAPIDJSON_FORCEINLINE bool GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::IterativeParseComplete () inline
Check if token-by-token parsing JSON text is complete.
Returns
Whether the JSON has been fully decoded.
HasParseError()
template<typename SourceEncoding, typename TargetEncoding, typename StackAllocator = CrtAllocator> bool GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::HasParseError () const inline
Whether a parse error has occurred in the last parsing.
References ParseResult::IsError().
GetParseErrorCode()
template<typename SourceEncoding, typename TargetEncoding, typename StackAllocator = CrtAllocator> ParseErrorCode GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::GetParseErrorCode () const inline
Get the ParseErrorCode of last parsing.
References ParseResult::Code().
GetErrorOffset()
template<typename SourceEncoding, typename TargetEncoding, typename StackAllocator = CrtAllocator> size_t GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::GetErrorOffset () const inline
Get the position of last parsing error in input, 0 otherwise.
References ParseResult::Offset().
SetParseError()
template<typename SourceEncoding, typename TargetEncoding, typename StackAllocator = CrtAllocator> void GenericReader< SourceEncoding, TargetEncoding, StackAllocator >::SetParseError (ParseErrorCode code, size_t offset) inline protected
References ParseResult::Set().
The documentation for this class was generated from the following files:
fwd.h
reader.h