Aurora Framework: common.c File Reference
common.c File Reference
Macros
#define CASE_NAME(x) case x : return #x ; break ;
#define GET_BE_3BYTE(ptr) (((ptr) [0] << 16) | ((ptr) [1] << 8) | ((ptr) [2]))
#define GET_BE_8BYTE(ptr)
#define GET_BE_INT(ptr)
#define GET_BE_SHORT(ptr) (((ptr) [0] << 8) | ((ptr) [1]))
#define GET_LE_3BYTE(ptr) (((ptr) [2] << 16) | ((ptr) [1] << 8) | ((ptr) [0]))
#define GET_LE_8BYTE(ptr)
#define GET_LE_INT(ptr)
#define GET_LE_SHORT(ptr) (((ptr) [1] << 8) | ((ptr) [0]))
#define INITIAL_HEADER_SIZE 256
#define SF_CUES_VAR_SIZE(count) (sizeof (SF_CUES_0) + count * sizeof (SF_CUE_POINT))
Functions
void append_snprintf (char *dest, size_t maxlen, const char *fmt,...)
static int header_gets (SF_PRIVATE *psf, char *ptr, int bufsize)
static void header_put_be_3byte (SF_PRIVATE *psf, int x)
static void header_put_be_int (SF_PRIVATE *psf, int x)
static void header_put_be_short (SF_PRIVATE *psf, int x)
static void header_put_byte (SF_PRIVATE *psf, char x)
static void header_put_le_3byte (SF_PRIVATE *psf, int x)
static void header_put_le_int (SF_PRIVATE *psf, int x)
static void header_put_le_short (SF_PRIVATE *psf, int x)
static int header_read (SF_PRIVATE *psf, void *ptr, int bytes)
static void header_seek (SF_PRIVATE *psf, sf_count_t position, int whence)
static void log_putchar (SF_PRIVATE *psf, char ch)
SF_PRIVATE * psf_allocate (void)
void psf_asciiheader_printf (SF_PRIVATE *psf, const char *format,...)
int psf_binheader_readf (SF_PRIVATE *psf, char const *format,...)
int psf_binheader_writef (SF_PRIVATE *psf, const char *format,...)
static int psf_bump_header_allocation (SF_PRIVATE *psf, sf_count_t needed)
SF_CUES * psf_cues_dup (const void *ptr)
void psf_d2i_array (const double *src, int *dest, int count, int normalize)
void psf_d2i_clip_array (const double *src, int *dest, int count, int normalize)
void psf_d2s_array (const double *src, short *dest, int count, int normalize)
void psf_d2s_clip_array (const double *src, short *dest, int count, int normalize)
sf_count_t psf_decode_frame_count (SF_PRIVATE *psf)
sf_count_t psf_default_seek (SF_PRIVATE *psf, int UNUSED(mode), sf_count_t samples_from_start)
void psf_f2i_array (const float *src, int *dest, int count, int normalize)
void psf_f2i_clip_array (const float *src, int *dest, int count, int normalize)
void psf_f2s_array (const float *src, short *dest, int count, int normalize)
void psf_f2s_clip_array (const float *src, short *dest, int count, int normalize)
void psf_get_cues (SF_PRIVATE *psf, void *data, size_t datasize)
void psf_get_date_str (char *str, int maxlen)
void psf_hexdump (const void *ptr, int len)
SF_INSTRUMENT * psf_instrument_alloc (void)
void psf_log_printf (SF_PRIVATE *psf, const char *format,...)
void psf_log_SF_INFO (SF_PRIVATE *psf)
void * psf_memset (void *s, int c, sf_count_t len)
FILE * psf_open_tmpfile (char *fname, size_t fnamelen)
int32_t psf_rand_int32 (void)
void psf_sanitize_string (char *cptr, int len)
void psf_strlcpy_crlf (char *dest, const char *src, size_t destmax, size_t srcmax)
int s_bitwidth_to_subformat (int bits)
typedef SF_CUES_VAR (0)
const char * str_of_endianness (int end)
const char * str_of_major_format (int format)
const char * str_of_minor_format (int format)
const char * str_of_open_mode (int mode)
int subformat_to_bytewidth (int format)
int u_bitwidth_to_subformat (int bits)
Macro Definition Documentation
INITIAL_HEADER_SIZE
#define INITIAL_HEADER_SIZE 256
Referenced by psf_allocate(), and psf_bump_header_allocation().
GET_LE_SHORT
#define GET_LE_SHORT (ptr) (((ptr) [1] << 8) | ((ptr) [0]))
Referenced by psf_binheader_readf().
GET_BE_SHORT
#define GET_BE_SHORT (ptr) (((ptr) [0] << 8) | ((ptr) [1]))
Referenced by psf_binheader_readf().
GET_LE_3BYTE
#define GET_LE_3BYTE (ptr) (((ptr) [2] << 16) | ((ptr) [1] << 8) | ((ptr) [0]))
Referenced by psf_binheader_readf().
GET_BE_3BYTE
#define GET_BE_3BYTE (ptr) (((ptr) [0] << 16) | ((ptr) [1] << 8) | ((ptr) [2]))
Referenced by psf_binheader_readf().
GET_LE_INT
#define GET_LE_INT (ptr)
Value:
(((ptr) [3] << 24)   | ((ptr) [2] << 16) |   \
                                ((ptr) [1] << 8)    | ((ptr) [0]))
GET_BE_INT
#define GET_BE_INT (ptr)
Value:
(((ptr) [0] << 24)   | ((ptr) [1] << 16) |   \
                                ((ptr) [2] << 8)    | ((ptr) [3]))
GET_LE_8BYTE
#define GET_LE_8BYTE (ptr)
Value:
((((sf_count_t) (ptr) [7]) << 56)    | (((sf_count_t) (ptr) [6]) << 48) |    \
                                (((sf_count_t) (ptr) [5]) << 40)    | (((sf_count_t) (ptr) [4]) << 32) |    \
                                (((sf_count_t) (ptr) [3]) << 24)    | (((sf_count_t) (ptr) [2]) << 16) |    \
                                (((sf_count_t) (ptr) [1]) << 8)     | ((ptr) [0]))
GET_BE_8BYTE
#define GET_BE_8BYTE (ptr)
Value:
((((sf_count_t) (ptr) [0]) << 56)    | (((sf_count_t) (ptr) [1]) << 48) |    \
                                (((sf_count_t) (ptr) [2]) << 40)    | (((sf_count_t) (ptr) [3]) << 32) |    \
                                (((sf_count_t) (ptr) [4]) << 24)    | (((sf_count_t) (ptr) [5]) << 16) |    \
                                (((sf_count_t) (ptr) [6]) << 8)     | ((ptr) [7]))
SF_CUES_VAR_SIZE
#define SF_CUES_VAR_SIZE (count) (sizeof (SF_CUES_0) + count * sizeof (SF_CUE_POINT))
Referenced by psf_cues_dup(), psf_get_cues(), and SF_CUES_VAR().
CASE_NAME
#define CASE_NAME (x) case x : return #x ; break ;
Referenced by str_of_endianness(), str_of_major_format(), str_of_minor_format(), and str_of_open_mode().
Function Documentation
psf_allocate()
SF_PRIVATE* psf_allocate (void)
References sf_private_tag::header, INITIAL_HEADER_SIZE, sf_private_tag::len, NULL, and sf_private_tag::ptr.
Referenced by sf_open(), sf_open_fd(), and sf_open_virtual().
psf_bump_header_allocation()
static int psf_bump_header_allocation (SF_PRIVATE * psf, sf_count_t needed) static
References sf_private_tag::error, sf_private_tag::header, INITIAL_HEADER_SIZE, sf_private_tag::len, memset(), NULL, psf_log_printf(), sf_private_tag::ptr, SF_MAX, and SFE_MALLOC_FAILED.
Referenced by header_gets(), header_read(), header_seek(), psf_binheader_readf(), and psf_binheader_writef().
log_putchar()
static void log_putchar (SF_PRIVATE * psf, char ch) inline static
References sf_private_tag::buf, sf_private_tag::indx, sf_private_tag::parselog, and SIGNED_SIZEOF.
Referenced by psf_log_printf().
psf_log_printf()
void psf_log_printf (SF_PRIVATE * psf, const char * format, ...)
References log_putchar(), NULL, and width.
Referenced by aiff_ima_decode_block(), aiff_ima_encode_block(), aiff_open(), aiff_read_basc_chunk(), aiff_read_chanmap(), aiff_read_comm_chunk(), aiff_read_header(), alac_decode_block(), alac_init(), alac_kuki_read(), alac_pakt_read_decode(), alac_reader_init(), alac_writer_init(), au_read_header(), audio_detect(), avr_read_header(), caf_read_chanmap(), caf_read_header(), caf_read_strings(), codec_close(), decode_desc_chunk(), double64_get_capability(), double64_init(), dpcm_init(), dwvw_init(), exif_subchunk_parse(), flac_open(), float32_get_capability(), float32_init(), g72x_init(), g72x_seek(), gsm610_decode_block(), gsm610_encode_block(), gsm610_init(), gsm610_wav_decode_block(), gsm610_wav_encode_block(), guess_file_type(), header_read(), header_seek(), htk_read_header(), id3_skip(), ima_reader_init(), ima_writer_init(), interleave_init(), ircam_close(), ircam_read_header(), macos_guess_file_type(), mat4_read_header(), mat5_read_header(), mpc2k_read_header(), msadpcm_decode_block(), msadpcm_encode_block(), msadpcm_get_bpred(), nist_read_header(), nms_adpcm_decode_block(), nms_adpcm_encode_block(), nms_adpcm_init(), ogg_open(), ogg_opus_open(), ogg_pcm_open(), ogg_speex_open(), ogg_vorbis_open(), paf24_init(), paf24_read_block(), paf24_write_block(), paf_read_header(), parse_str_rsrc(), pcm_init(), psf_binheader_readf(), psf_binheader_writef(), psf_bump_header_allocation(), psf_fseek(), psf_g72x_decode_block(), psf_g72x_encode_block(), psf_log_SF_INFO(), psf_nms_adpcm_decode_block(), psf_nms_adpcm_encode_block(), psf_open_file(), psf_store_string(), pvf_read_header(), rf64_read_header(), rf64_write_header(), sd2_open(), sd2_parse_rsrc_fork(), sds_2byte_read(), sds_2byte_write(), sds_3byte_read(), sds_3byte_write(), sds_4byte_read(), sds_4byte_write(), sds_close(), sds_read_header(), sds_write_header(), sf_command(), sf_open(), svx_read_header(), try_resource_fork(), validate_psf(), voc_read_header(), vox_adpcm_init(), vox_read_block(), vox_write_block(), w64_read_header(), wav_read_acid_chunk(), wav_read_header(), wav_read_smpl_chunk(), wav_write_header(), wavlike_analyze(), wavlike_ima_decode_block(), wavlike_ima_encode_block(), wavlike_ima_init(), wavlike_msadpcm_init(), wavlike_read_bext_chunk(), wavlike_read_cart_chunk(), wavlike_read_fmt_chunk(), wavlike_read_peak_chunk(), wavlike_subchunk_parse(), wve_read_header(), and xi_read_header().
psf_asciiheader_printf()
void psf_asciiheader_printf (SF_PRIVATE * psf, const char * format, ...)
References sf_private_tag::header, sf_private_tag::indx, sf_private_tag::len, and sf_private_tag::ptr.
Referenced by nist_write_header().
header_put_byte()
static void header_put_byte (SF_PRIVATE * psf, char x) inline static
References sf_private_tag::header, sf_private_tag::indx, and sf_private_tag::ptr.
Referenced by psf_binheader_writef().
header_put_be_short()
static void header_put_be_short (SF_PRIVATE * psf, int x) inline static
References sf_private_tag::header, sf_private_tag::indx, and sf_private_tag::ptr.
Referenced by psf_binheader_writef().
header_put_le_short()
static void header_put_le_short (SF_PRIVATE * psf, int x) inline static
References sf_private_tag::header, sf_private_tag::indx, and sf_private_tag::ptr.
Referenced by psf_binheader_writef().
header_put_be_3byte()
static void header_put_be_3byte (SF_PRIVATE * psf, int x) inline static
References sf_private_tag::header, sf_private_tag::indx, and sf_private_tag::ptr.
Referenced by psf_binheader_writef().
header_put_le_3byte()
static void header_put_le_3byte (SF_PRIVATE * psf, int x) inline static
References sf_private_tag::header, sf_private_tag::indx, and sf_private_tag::ptr.
Referenced by psf_binheader_writef().
header_put_be_int()
static void header_put_be_int (SF_PRIVATE * psf, int x) inline static
References sf_private_tag::header, sf_private_tag::indx, and sf_private_tag::ptr.
Referenced by psf_binheader_writef().
header_put_le_int()
static void header_put_le_int (SF_PRIVATE * psf, int x) inline static
References sf_private_tag::header, sf_private_tag::indx, and sf_private_tag::ptr.
Referenced by psf_binheader_writef().
psf_binheader_writef()
int psf_binheader_writef (SF_PRIVATE * psf, const char * format, ...)
References double64_be_write(), double64_le_write(), sf_private_tag::error, float32_be_write(), float32_le_write(), sf_private_tag::header, header_put_be_3byte(), header_put_be_int(), header_put_be_short(), header_put_byte(), header_put_le_3byte(), header_put_le_int(), header_put_le_short(), sf_private_tag::indx, sf_private_tag::len, memcpy(), psf_bump_header_allocation(), psf_log_printf(), sf_private_tag::ptr, sf_private_tag::rwf_endian, and SFE_INTERNAL.
Referenced by aiff_rewrite_header(), aiff_write_header(), aiff_write_strings(), aiff_write_tailer(), au_write_header(), avr_write_header(), caf_write_header(), caf_write_strings(), caf_write_tailer(), htk_write_header(), ircam_write_header(), mat4_write_header(), mat5_write_header(), mpc2k_write_header(), nist_write_header(), paf_write_header(), rf64_write_fmt_chunk(), rf64_write_header(), rf64_write_tailer(), sd2_write_rsrc_fork(), sds_write_header(), svx_write_header(), voc_write_header(), w64_write_header(), wav_write_fmt_chunk(), wav_write_header(), wav_write_tailer(), wavex_write_fmt_chunk(), wavlike_msadpcm_write_adapt_coeffs(), wavlike_write_bext_chunk(), wavlike_write_cart_chunk(), wavlike_write_custom_chunks(), wavlike_write_guid(), wavlike_write_peak_chunk(), wavlike_write_strings(), wve_write_header(), and xi_write_header().
header_read()
static int header_read (SF_PRIVATE * psf, void * ptr, int bytes) static
References sf_private_tag::end, sf_private_tag::header, sf_private_tag::indx, sf_private_tag::len, memcpy(), psf_bump_header_allocation(), psf_fread(), psf_log_printf(), and sf_private_tag::ptr.
Referenced by psf_binheader_readf().
header_seek()
static void header_seek (SF_PRIVATE * psf, sf_count_t position, int whence) static
References sf_private_tag::end, sf_private_tag::header, sf_private_tag::indx, sf_private_tag::len, psf_bump_header_allocation(), psf_fread(), psf_fseek(), psf_log_printf(), and sf_private_tag::ptr.
Referenced by psf_binheader_readf().
header_gets()
static int header_gets (SF_PRIVATE * psf, char * ptr, int bufsize) static
References sf_private_tag::end, sf_private_tag::header, sf_private_tag::indx, sf_private_tag::len, psf_bump_header_allocation(), psf_fread(), and sf_private_tag::ptr.
Referenced by psf_binheader_readf().
psf_binheader_readf()
int psf_binheader_readf (SF_PRIVATE * psf, char const * format, ...)
References double64_be_read(), double64_le_read(), sf_private_tag::error, float32_be_read(), float32_le_read(), GET_BE_3BYTE, GET_BE_SHORT, GET_LE_3BYTE, GET_LE_SHORT, sf_private_tag::header, header_gets(), header_read(), header_seek(), sf_private_tag::indx, sf_private_tag::len, memset(), psf_bump_header_allocation(), psf_ftell(), psf_get_be32(), psf_get_be64(), psf_get_le32(), psf_get_le64(), psf_log_printf(), sf_private_tag::rwf_endian, and SFE_INTERNAL.
Referenced by aiff_read_basc_chunk(), aiff_read_chanmap(), aiff_read_comm_chunk(), aiff_read_header(), au_read_header(), avr_read_header(), caf_read_chanmap(), caf_read_header(), caf_read_strings(), exif_fill_and_sink(), exif_subchunk_parse(), guess_file_type(), htk_read_header(), id3_skip(), ircam_read_header(), mat4_read_header(), mat5_read_header(), mpc2k_read_header(), nist_read_header(), paf_read_header(), pvf_read_header(), rf64_read_header(), sds_read_header(), svx_read_header(), voc_read_header(), w64_read_header(), wav_read_acid_chunk(), wav_read_header(), wav_read_smpl_chunk(), wavlike_read_bext_chunk(), wavlike_read_cart_chunk(), wavlike_read_fmt_chunk(), wavlike_read_peak_chunk(), wavlike_subchunk_parse(), wve_read_header(), and xi_read_header().
psf_default_seek()
sf_count_t psf_default_seek (SF_PRIVATE * psf, int UNUSEDmode, sf_count_t samples_from_start)
References sf_private_tag::blockwidth, sf_private_tag::dataoffset, sf_private_tag::error, psf_fseek(), PSF_SEEK_ERROR, sf_private_tag::sf, SFE_BAD_SEEK, SFE_NOT_SEEKABLE, and SFE_SEEK_FAILED.
Referenced by psf_open_file().
psf_hexdump()
void psf_hexdump (const void * ptr, int len)
References memset(), NULL, and psf_isprint().
Referenced by psf_store_string().
psf_log_SF_INFO()
void psf_log_SF_INFO (SF_PRIVATE * psf)
References psf_log_printf(), and sf_private_tag::sf.
Referenced by psf_open_file().
psf_memset()
void* psf_memset (void * s, int c, sf_count_t len)
References memset().
Referenced by sf_read_double(), sf_read_float(), sf_read_int(), sf_read_raw(), sf_read_short(), sf_readf_double(), sf_readf_float(), sf_readf_int(), and sf_readf_short().
SF_CUES_VAR()
typedef SF_CUES_VAR (0)
References SF_CUES_VAR_SIZE.
psf_cues_dup()
SF_CUES* psf_cues_dup (const void * ptr)
References memcpy(), psf_cues_alloc(), and SF_CUES_VAR_SIZE.
Referenced by sf_command().
psf_get_cues()
void psf_get_cues (SF_PRIVATE * psf, void * data, size_t datasize)
References sf_private_tag::cues, memcpy(), SF_CUES_VAR_SIZE, and SF_MIN.
Referenced by sf_command().
psf_instrument_alloc()
SF_INSTRUMENT* psf_instrument_alloc (void)
References NULL.
Referenced by aiff_read_header(), sf_command(), wav_read_smpl_chunk(), and xi_read_header().
psf_sanitize_string()
void psf_sanitize_string (char * cptr, int len)
References psf_isprint().
Referenced by aiff_read_header().
psf_get_date_str()
void psf_get_date_str (char * str, int maxlen)
References memcpy(), and NULL.
Referenced by mat5_write_header().
subformat_to_bytewidth()
int subformat_to_bytewidth (int format)
s_bitwidth_to_subformat()
int s_bitwidth_to_subformat (int bits)
Referenced by aiff_read_comm_chunk().
u_bitwidth_to_subformat()
int u_bitwidth_to_subformat (int bits)
Referenced by rf64_read_header(), w64_read_header(), wav_read_header(), and wavlike_read_fmt_chunk().
psf_rand_int32()
int32_t psf_rand_int32 (void)
References NULL, and value.
Referenced by psf_open_file(), and psf_open_tmpfile().
append_snprintf()
void append_snprintf (char * dest, size_t maxlen, const char * fmt, ...)
Referenced by wavlike_read_fmt_chunk().
psf_strlcpy_crlf()
void psf_strlcpy_crlf (char * dest, const char * src, size_t destmax, size_t srcmax)
Referenced by broadcast_var_set(), and cart_var_set().
psf_decode_frame_count()
sf_count_t psf_decode_frame_count (SF_PRIVATE * psf)
References ARRAY_LEN, sf_private_tag::datalength, sf_private_tag::dataoffset, BUF_UNION::ibuf, psf_fseek(), psf_is_pipe(), sf_private_tag::read_int, and sf_private_tag::sf.
Referenced by dwvw_init().
str_of_major_format()
const char* str_of_major_format (int format)
References CASE_NAME, and SF_CONTAINER.
str_of_minor_format()
const char* str_of_minor_format (int format)
References CASE_NAME, and SF_CODEC.
str_of_open_mode()
const char* str_of_open_mode (int mode)
References CASE_NAME, and mode().
str_of_endianness()
const char* str_of_endianness (int end)
References CASE_NAME.
psf_f2s_array()
void psf_f2s_array (const float * src, short * dest, int count, int normalize)
psf_f2s_clip_array()
void psf_f2s_clip_array (const float * src, short * dest, int count, int normalize)
psf_d2s_array()
void psf_d2s_array (const double * src, short * dest, int count, int normalize)
psf_d2s_clip_array()
void psf_d2s_clip_array (const double * src, short * dest, int count, int normalize)
psf_f2i_array()
void psf_f2i_array (const float * src, int * dest, int count, int normalize)
Referenced by alac_write_f().
psf_f2i_clip_array()
void psf_f2i_clip_array (const float * src, int * dest, int count, int normalize)
Referenced by alac_write_f().
psf_d2i_array()
void psf_d2i_array (const double * src, int * dest, int count, int normalize)
Referenced by alac_write_d().
psf_d2i_clip_array()
void psf_d2i_clip_array (const double * src, int * dest, int count, int normalize)
Referenced by alac_write_d().
psf_open_tmpfile()
FILE* psf_open_tmpfile (char * fname, size_t fnamelen)
References memset(), NULL, psf_rand_int32(), R_OK, W_OK, and X_OK.
Referenced by alac_writer_init().