Aurora Framework: xi.c File Reference
xi.c File Reference
Classes
struct XI_PRIVATE
Macros
#define MAX_XI_SAMPLES 16
Functions
static void d2dles_array (XI_PRIVATE *pxi, const double *src, short *dest, int count, double normfact)
static void d2dsc_array (XI_PRIVATE *pxi, const double *src, signed char *dest, int count, double normfact)
static void dles2d_array (XI_PRIVATE *pxi, short *src, int count, double *dest, double normfact)
static void dles2f_array (XI_PRIVATE *pxi, short *src, int count, float *dest, float normfact)
static void dles2i_array (XI_PRIVATE *pxi, short *src, int count, int *dest)
static void dles2s_array (XI_PRIVATE *pxi, short *src, int count, short *dest)
static int dpcm_init (SF_PRIVATE *psf)
static sf_count_t dpcm_read_dles2d (SF_PRIVATE *psf, double *ptr, sf_count_t len)
static sf_count_t dpcm_read_dles2f (SF_PRIVATE *psf, float *ptr, sf_count_t len)
static sf_count_t dpcm_read_dles2i (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static sf_count_t dpcm_read_dles2s (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static sf_count_t dpcm_read_dsc2d (SF_PRIVATE *psf, double *ptr, sf_count_t len)
static sf_count_t dpcm_read_dsc2f (SF_PRIVATE *psf, float *ptr, sf_count_t len)
static sf_count_t dpcm_read_dsc2i (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static sf_count_t dpcm_read_dsc2s (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static sf_count_t dpcm_seek (SF_PRIVATE *psf, int mode, sf_count_t offset)
static sf_count_t dpcm_write_d2dles (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
static sf_count_t dpcm_write_d2dsc (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
static sf_count_t dpcm_write_f2dles (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
static sf_count_t dpcm_write_f2dsc (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
static sf_count_t dpcm_write_i2dles (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
static sf_count_t dpcm_write_i2dsc (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
static sf_count_t dpcm_write_s2dles (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
static sf_count_t dpcm_write_s2dsc (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
static void dsc2d_array (XI_PRIVATE *pxi, signed char *src, int count, double *dest, double normfact)
static void dsc2f_array (XI_PRIVATE *pxi, signed char *src, int count, float *dest, float normfact)
static void dsc2i_array (XI_PRIVATE *pxi, signed char *src, int count, int *dest)
static void dsc2s_array (XI_PRIVATE *pxi, signed char *src, int count, short *dest)
static void f2dles_array (XI_PRIVATE *pxi, const float *src, short *dest, int count, float normfact)
static void f2dsc_array (XI_PRIVATE *pxi, const float *src, signed char *dest, int count, float normfact)
static void i2dles_array (XI_PRIVATE *pxi, const int *src, short *dest, int count)
static void i2dsc_array (XI_PRIVATE *pxi, const int *src, signed char *dest, int count)
static void s2dles_array (XI_PRIVATE *pxi, const short *src, short *dest, int count)
static void s2dsc_array (XI_PRIVATE *pxi, const short *src, signed char *dest, int count)
static int xi_close (SF_PRIVATE *psf)
static int xi_close (SF_PRIVATE *UNUSED(psf))
int xi_open (SF_PRIVATE *psf)
static int xi_read_header (SF_PRIVATE *psf)
static int xi_write_header (SF_PRIVATE *psf, int calc_length)
static int xi_write_header (SF_PRIVATE *psf, int UNUSED(calc_length))
Macro Definition Documentation
MAX_XI_SAMPLES
#define MAX_XI_SAMPLES 16
Referenced by xi_read_header().
Function Documentation
xi_close() [1/2]
static int xi_close (SF_PRIVATE * psf) static
Referenced by xi_open().
xi_write_header() [1/2]
static int xi_write_header (SF_PRIVATE * psf, int calc_length) static
Referenced by xi_open().
xi_read_header()
static int xi_read_header (SF_PRIVATE * psf) static
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::endian, sf_private_tag::filelength, sf_private_tag::instrument, MAX_XI_SAMPLES, memset(), setup::name, NULL, psf_binheader_readf(), psf_fseek(), psf_ftell(), psf_instrument_alloc(), psf_log_printf(), psf_store_string(), sf_private_tag::sf, SFE_BAD_OFFSET, SFE_BAD_SEEK, SFE_MALLOC_FAILED, SFE_XI_BAD_HEADER, SFE_XI_EXCESS_SAMPLES, and create_symbols_file::version.
Referenced by xi_open().
dpcm_init()
static int dpcm_init (SF_PRIVATE * psf) static
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, dpcm_read_dles2d(), dpcm_read_dles2f(), dpcm_read_dles2i(), dpcm_read_dles2s(), dpcm_read_dsc2d(), dpcm_read_dsc2f(), dpcm_read_dsc2i(), dpcm_read_dsc2s(), dpcm_write_d2dles(), dpcm_write_d2dsc(), dpcm_write_f2dles(), dpcm_write_f2dsc(), dpcm_write_i2dles(), dpcm_write_i2dsc(), dpcm_write_s2dles(), dpcm_write_s2dsc(), sf_private_tag::file, sf_private_tag::filelength, PSF_FILE::mode, psf_get_filelen(), psf_log_printf(), sf_private_tag::read_double, sf_private_tag::read_float, sf_private_tag::read_int, sf_private_tag::read_short, sf_private_tag::sf, SFE_INTERNAL, SFE_UNIMPLEMENTED, sf_private_tag::write_double, sf_private_tag::write_float, sf_private_tag::write_int, and sf_private_tag::write_short.
Referenced by xi_open().
dpcm_seek()
static sf_count_t dpcm_seek (SF_PRIVATE * psf, int mode, sf_count_t offset) static
References ARRAY_LEN, sf_private_tag::codec_data, sf_private_tag::datalength, sf_private_tag::dataoffset, dpcm_read_dles2s(), dpcm_read_dsc2s(), sf_private_tag::error, XI_PRIVATE::last_16, mode(), NULL, psf_fseek(), PSF_SEEK_ERROR, BUF_UNION::sbuf, sf_private_tag::sf, SF_CODEC, SFE_BAD_SEEK, and SFE_INTERNAL.
Referenced by xi_open().
xi_open()
int xi_open (SF_PRIVATE * psf)
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::codec_data, sf_private_tag::container_close, dpcm_init(), dpcm_seek(), sf_private_tag::endian, sf_private_tag::error, sf_private_tag::file, sf_private_tag::filelength, XI_PRIVATE::filename, sf_private_tag::is_pipe, memcpy(), memset(), PSF_FILE::mode, NULL, XI_PRIVATE::sample_flags, XI_PRIVATE::sample_name, sf_private_tag::seek, sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SFE_BAD_OPEN_FORMAT, SFE_MALLOC_FAILED, SFE_XI_NO_PIPE, XI_PRIVATE::software, sf_private_tag::write_header, xi_close(), xi_read_header(), and xi_write_header().
Referenced by psf_open_file().
xi_close() [2/2]
static int xi_close (SF_PRIVATE * UNUSEDpsf) static
dpcm_read_dsc2s()
static sf_count_t dpcm_read_dsc2s (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, dsc2s_array(), NULL, psf_fread(), BUF_UNION::scbuf, and BUF_UNION::ucbuf.
Referenced by dpcm_init(), and dpcm_seek().
dpcm_read_dsc2i()
static sf_count_t dpcm_read_dsc2i (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, dsc2i_array(), NULL, psf_fread(), BUF_UNION::scbuf, and BUF_UNION::ucbuf.
Referenced by dpcm_init().
dpcm_read_dsc2f()
static sf_count_t dpcm_read_dsc2f (SF_PRIVATE * psf, float * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, dsc2f_array(), sf_private_tag::norm_float, NULL, psf_fread(), BUF_UNION::scbuf, and BUF_UNION::ucbuf.
Referenced by dpcm_init().
dpcm_read_dsc2d()
static sf_count_t dpcm_read_dsc2d (SF_PRIVATE * psf, double * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, dsc2d_array(), sf_private_tag::norm_double, NULL, psf_fread(), BUF_UNION::scbuf, and BUF_UNION::ucbuf.
Referenced by dpcm_init().
dpcm_write_s2dsc()
static sf_count_t dpcm_write_s2dsc (SF_PRIVATE * psf, const short * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, NULL, psf_fwrite(), s2dsc_array(), BUF_UNION::scbuf, and BUF_UNION::ucbuf.
Referenced by dpcm_init().
dpcm_write_i2dsc()
static sf_count_t dpcm_write_i2dsc (SF_PRIVATE * psf, const int * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, i2dsc_array(), NULL, psf_fwrite(), BUF_UNION::scbuf, and BUF_UNION::ucbuf.
Referenced by dpcm_init().
dpcm_write_f2dsc()
static sf_count_t dpcm_write_f2dsc (SF_PRIVATE * psf, const float * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, f2dsc_array(), sf_private_tag::norm_float, NULL, psf_fwrite(), BUF_UNION::scbuf, and BUF_UNION::ucbuf.
Referenced by dpcm_init().
dpcm_write_d2dsc()
static sf_count_t dpcm_write_d2dsc (SF_PRIVATE * psf, const double * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, d2dsc_array(), sf_private_tag::norm_double, NULL, psf_fwrite(), BUF_UNION::scbuf, and BUF_UNION::ucbuf.
Referenced by dpcm_init().
dpcm_read_dles2s()
static sf_count_t dpcm_read_dles2s (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, dles2s_array(), NULL, psf_fread(), and BUF_UNION::sbuf.
Referenced by dpcm_init(), and dpcm_seek().
dpcm_read_dles2i()
static sf_count_t dpcm_read_dles2i (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, dles2i_array(), NULL, psf_fread(), and BUF_UNION::sbuf.
Referenced by dpcm_init().
dpcm_read_dles2f()
static sf_count_t dpcm_read_dles2f (SF_PRIVATE * psf, float * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, dles2f_array(), sf_private_tag::norm_float, NULL, psf_fread(), and BUF_UNION::sbuf.
Referenced by dpcm_init().
dpcm_read_dles2d()
static sf_count_t dpcm_read_dles2d (SF_PRIVATE * psf, double * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, dles2d_array(), sf_private_tag::norm_double, NULL, psf_fread(), and BUF_UNION::sbuf.
Referenced by dpcm_init().
dpcm_write_s2dles()
static sf_count_t dpcm_write_s2dles (SF_PRIVATE * psf, const short * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, NULL, psf_fwrite(), s2dles_array(), and BUF_UNION::sbuf.
Referenced by dpcm_init().
dpcm_write_i2dles()
static sf_count_t dpcm_write_i2dles (SF_PRIVATE * psf, const int * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, i2dles_array(), NULL, psf_fwrite(), and BUF_UNION::sbuf.
Referenced by dpcm_init().
dpcm_write_f2dles()
static sf_count_t dpcm_write_f2dles (SF_PRIVATE * psf, const float * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, f2dles_array(), sf_private_tag::norm_float, NULL, psf_fwrite(), and BUF_UNION::sbuf.
Referenced by dpcm_init().
dpcm_write_d2dles()
static sf_count_t dpcm_write_d2dles (SF_PRIVATE * psf, const double * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, d2dles_array(), sf_private_tag::norm_double, NULL, psf_fwrite(), and BUF_UNION::sbuf.
Referenced by dpcm_init().
xi_write_header() [2/2]
static int xi_write_header (SF_PRIVATE * psf, int UNUSEDcalc_length) static
References BHW1, BHW2, BHW4, BHW8, BHWv, BHWz, sf_private_tag::codec_data, sf_private_tag::dataoffset, sf_private_tag::error, XI_PRIVATE::filename, sf_private_tag::header, sf_private_tag::indx, XI_PRIVATE::loop_begin, XI_PRIVATE::loop_end, NULL, psf_binheader_writef(), psf_fseek(), psf_ftell(), psf_fwrite(), sf_private_tag::ptr, XI_PRIVATE::sample_flags, XI_PRIVATE::sample_name, sf_private_tag::sf, SFE_INTERNAL, and XI_PRIVATE::software.
dsc2s_array()
static void dsc2s_array (XI_PRIVATE * pxi, signed char * src, int count, short * dest) static
References arith_shift_left(), and XI_PRIVATE::last_16.
Referenced by dpcm_read_dsc2s().
dsc2i_array()
static void dsc2i_array (XI_PRIVATE * pxi, signed char * src, int count, int * dest) static
References arith_shift_left(), and XI_PRIVATE::last_16.
Referenced by dpcm_read_dsc2i().
dsc2f_array()
static void dsc2f_array (XI_PRIVATE * pxi, signed char * src, int count, float * dest, float normfact) static
References arith_shift_left(), and XI_PRIVATE::last_16.
Referenced by dpcm_read_dsc2f().
dsc2d_array()
static void dsc2d_array (XI_PRIVATE * pxi, signed char * src, int count, double * dest, double normfact) static
References arith_shift_left(), and XI_PRIVATE::last_16.
Referenced by dpcm_read_dsc2d().
dles2s_array()
static void dles2s_array (XI_PRIVATE * pxi, short * src, int count, short * dest) static
References XI_PRIVATE::last_16.
Referenced by dpcm_read_dles2s().
dles2i_array()
static void dles2i_array (XI_PRIVATE * pxi, short * src, int count, int * dest) static
References arith_shift_left(), and XI_PRIVATE::last_16.
Referenced by dpcm_read_dles2i().
dles2f_array()
static void dles2f_array (XI_PRIVATE * pxi, short * src, int count, float * dest, float normfact) static
References XI_PRIVATE::last_16.
Referenced by dpcm_read_dles2f().
dles2d_array()
static void dles2d_array (XI_PRIVATE * pxi, short * src, int count, double * dest, double normfact) static
References XI_PRIVATE::last_16.
Referenced by dpcm_read_dles2d().
s2dsc_array()
static void s2dsc_array (XI_PRIVATE * pxi, const short * src, signed char * dest, int count) static
References arith_shift_left(), and XI_PRIVATE::last_16.
Referenced by dpcm_write_s2dsc().
i2dsc_array()
static void i2dsc_array (XI_PRIVATE * pxi, const int * src, signed char * dest, int count) static
References arith_shift_left(), and XI_PRIVATE::last_16.
Referenced by dpcm_write_i2dsc().
f2dsc_array()
static void f2dsc_array (XI_PRIVATE * pxi, const float * src, signed char * dest, int count, float normfact) static
References arith_shift_left(), and XI_PRIVATE::last_16.
Referenced by dpcm_write_f2dsc().
d2dsc_array()
static void d2dsc_array (XI_PRIVATE * pxi, const double * src, signed char * dest, int count, double normfact) static
References arith_shift_left(), and XI_PRIVATE::last_16.
Referenced by dpcm_write_d2dsc().
s2dles_array()
static void s2dles_array (XI_PRIVATE * pxi, const short * src, short * dest, int count) static
References XI_PRIVATE::last_16.
Referenced by dpcm_write_s2dles().
i2dles_array()
static void i2dles_array (XI_PRIVATE * pxi, const int * src, short * dest, int count) static
References XI_PRIVATE::last_16.
Referenced by dpcm_write_i2dles().
f2dles_array()
static void f2dles_array (XI_PRIVATE * pxi, const float * src, short * dest, int count, float normfact) static
References XI_PRIVATE::last_16.
Referenced by dpcm_write_f2dles().
d2dles_array()
static void d2dles_array (XI_PRIVATE * pxi, const double * src, short * dest, int count, double normfact) static
References XI_PRIVATE::last_16.
Referenced by dpcm_write_d2dles().