Aurora Framework: BUF_UNION Union Reference
BUF_UNION Union Reference
Public Attributes
char cbuf [SF_BUFFER_LEN/sizeof(char)]
double dbuf [SF_BUFFER_LEN/sizeof(double)]
float fbuf [SF_BUFFER_LEN/sizeof(float)]
int ibuf [SF_BUFFER_LEN/sizeof(int)]
long lbuf [SF_BUFFER_LEN/sizeof(double)]
short sbuf [SF_BUFFER_LEN/sizeof(short)]
signed char scbuf [SF_BUFFER_LEN/sizeof(signed char)]
unsigned char ucbuf [SF_BUFFER_LEN/sizeof(signed char)]
Member Data Documentation
dbuf
double BUF_UNION::dbuf[SF_BUFFER_LEN/sizeof(double)]
Referenced by host_read_d2f(), host_read_d2i(), host_read_d2s(), host_write_d(), host_write_f2d(), host_write_i2d(), host_write_s2d(), psf_calc_max_all_channels(), psf_calc_signal_max(), replace_read_d(), replace_read_d2f(), replace_read_d2i(), replace_read_d2s(), replace_write_d(), replace_write_f2d(), replace_write_i2d(), and replace_write_s2d().
lbuf
long BUF_UNION::lbuf[SF_BUFFER_LEN/sizeof(double)]
fbuf
float BUF_UNION::fbuf[SF_BUFFER_LEN/sizeof(float)]
Referenced by host_read_f(), host_read_f2d(), host_read_f2i(), host_read_f2s(), host_write_d2f(), host_write_f(), host_write_i2f(), host_write_s2f(), replace_read_f(), replace_read_f2d(), replace_read_f2i(), replace_read_f2s(), replace_write_d2f(), replace_write_f(), replace_write_i2f(), and replace_write_s2f().
ibuf
int BUF_UNION::ibuf[SF_BUFFER_LEN/sizeof(int)]
Referenced by dwvw_read_d(), dwvw_read_f(), dwvw_read_s(), dwvw_write_d(), dwvw_write_f(), dwvw_write_s(), host_read_f(), host_read_f2d(), host_read_f2i(), host_read_f2s(), host_write_d2f(), host_write_f(), host_write_i2f(), host_write_s2f(), paf24_read_d(), paf24_read_f(), paf24_read_s(), paf24_write_d(), paf24_write_f(), paf24_write_s(), pcm_read_bei2d(), pcm_read_bei2f(), pcm_read_bei2s(), pcm_read_lei2d(), pcm_read_lei2f(), pcm_read_lei2s(), pcm_write_d2bei(), pcm_write_d2lei(), pcm_write_f2bei(), pcm_write_f2lei(), pcm_write_i2bei(), pcm_write_i2lei(), pcm_write_s2bei(), pcm_write_s2lei(), psf_decode_frame_count(), replace_read_f(), replace_read_f2d(), replace_read_f2i(), replace_read_f2s(), replace_write_d2f(), replace_write_f(), replace_write_i2f(), replace_write_s2f(), sds_read_d(), sds_read_f(), sds_read_s(), sds_write_d(), sds_write_f(), and sds_write_s().
sbuf
short BUF_UNION::sbuf[SF_BUFFER_LEN/sizeof(short)]
Referenced by dpcm_read_dles2d(), dpcm_read_dles2f(), dpcm_read_dles2i(), dpcm_read_dles2s(), dpcm_seek(), dpcm_write_d2dles(), dpcm_write_f2dles(), dpcm_write_i2dles(), dpcm_write_s2dles(), g72x_read_d(), g72x_read_f(), g72x_read_i(), g72x_write_d(), g72x_write_f(), g72x_write_i(), gsm610_read_d(), gsm610_read_f(), gsm610_read_i(), gsm610_write_d(), gsm610_write_f(), gsm610_write_i(), ima_read_d(), ima_read_f(), ima_read_i(), ima_write_d(), ima_write_f(), ima_write_i(), msadpcm_read_d(), msadpcm_read_f(), msadpcm_read_i(), msadpcm_write_d(), msadpcm_write_f(), msadpcm_write_i(), nms_adpcm_read_d(), nms_adpcm_read_f(), nms_adpcm_read_i(), nms_adpcm_write_d(), nms_adpcm_write_f(), nms_adpcm_write_i(), pcm_read_bes2d(), pcm_read_bes2f(), pcm_read_bes2i(), pcm_read_les2d(), pcm_read_les2f(), pcm_read_les2i(), pcm_write_d2bes(), pcm_write_d2les(), pcm_write_f2bes(), pcm_write_f2les(), pcm_write_i2bes(), pcm_write_i2les(), pcm_write_s2bes(), pcm_write_s2les(), vox_read_d(), vox_read_f(), vox_read_i(), vox_write_d(), vox_write_f(), and vox_write_i().
cbuf
char BUF_UNION::cbuf[SF_BUFFER_LEN/sizeof(char)]
Referenced by aiff_read_header(), and caf_read_header().
scbuf
signed char BUF_UNION::scbuf[SF_BUFFER_LEN/sizeof(signed char)]
Referenced by aiff_read_comm_chunk(), aiff_read_header(), dpcm_read_dsc2d(), dpcm_read_dsc2f(), dpcm_read_dsc2i(), dpcm_read_dsc2s(), dpcm_write_d2dsc(), dpcm_write_f2dsc(), dpcm_write_i2dsc(), dpcm_write_s2dsc(), pcm_read_sc2d(), pcm_read_sc2f(), pcm_read_sc2i(), pcm_read_sc2s(), pcm_write_d2sc(), pcm_write_f2sc(), pcm_write_i2sc(), and pcm_write_s2sc().
ucbuf
unsigned char BUF_UNION::ucbuf[SF_BUFFER_LEN/sizeof(signed char)]
Referenced by alac_close(), alaw_read_alaw2d(), alaw_read_alaw2f(), alaw_read_alaw2i(), alaw_read_alaw2s(), alaw_write_d2alaw(), alaw_write_f2alaw(), alaw_write_i2alaw(), alaw_write_s2alaw(), caf_read_header(), caf_write_header(), dpcm_read_dsc2d(), dpcm_read_dsc2f(), dpcm_read_dsc2i(), dpcm_read_dsc2s(), dpcm_write_d2dsc(), dpcm_write_f2dsc(), dpcm_write_i2dsc(), dpcm_write_s2dsc(), pcm_read_bet2d(), pcm_read_bet2f(), pcm_read_bet2i(), pcm_read_bet2s(), pcm_read_let2d(), pcm_read_let2f(), pcm_read_let2i(), pcm_read_let2s(), pcm_read_uc2d(), pcm_read_uc2f(), pcm_read_uc2i(), pcm_read_uc2s(), pcm_write_d2bet(), pcm_write_d2let(), pcm_write_d2uc(), pcm_write_f2bet(), pcm_write_f2let(), pcm_write_f2uc(), pcm_write_i2bet(), pcm_write_i2let(), pcm_write_i2uc(), pcm_write_s2bet(), pcm_write_s2let(), pcm_write_s2uc(), ulaw_read_ulaw2d(), ulaw_read_ulaw2f(), ulaw_read_ulaw2i(), ulaw_read_ulaw2s(), ulaw_write_d2ulaw(), ulaw_write_f2ulaw(), ulaw_write_i2ulaw(), and ulaw_write_s2ulaw().
The documentation for this union was generated from the following file:
audio/src/sndfile/common.h