Aurora Framework: AuroraFW::AudioManager::AudioIStream Struct Reference
AuroraFW::AudioManager::AudioIStream Struct Reference
A struct representing an audio input stream.
Public Member Functions
AudioIStream (const char *, AudioInfo *, int)
Constructs an audio input stream.
~AudioIStream ()
Destructs an audio input stream.
void clearBuffer ()
Clears the entire buffer so it can start fresh for new recordings.
void clearBuffer (unsigned int start, unsigned int finish)
Clears only a portion of the buffer specified by the start and finish parameters.
bool isBufferFull ()
Returns is the buffer is completely filled with audio data.
bool isPaused ()
Returns if the stream is currently paused.
bool isRecording ()
Returns if the stream is recording audio input.
bool isStopped ()
Returns if the stream is completely stopped and not just paused.
void pause ()
Pauses the current recording.
void record ()
Starts recording audio input.
bool save ()
Saves the current audio stream (wheter it's empty, full or partially filled) to the disk on the path specified in the constructor.
void stop ()
Stops the current recording.
Public Attributes
float * buffer
The audio stream buffer, that is equal to the product of frames and the number of channels.
const int bufferSize
The buffer's size, that is equal to the number of frames requested, without considering the number of channels.
AudioInfo * info
The AudioInfo object with all the information needed.
const char * path
The path to save the audio stream to.
Friends
int audioInputCallback (const void *, void *, size_t, const PaStreamCallbackTimeInfo *, PaStreamCallbackFlags, void *)
Detailed Description
A struct representing an audio input stream.
A struct that enables the user to record audio input and store it on disk.
Since
snapshot20180330
Constructor & Destructor Documentation
AudioIStream()
AuroraFW::AudioManager::AudioIStream::AudioIStream (const char * path, AudioInfo * info, int bufferSize)
Constructs an audio input stream.
Parameters
path The path to where to save the audio stream.
info The AudioInfo object specifying all info about the stream.
int The number of frames (without considering the number of channels) to store.
See also
~AudioIStream()
Since
snapshot20180330
References AFW_NEW, audioInputCallback, buffer, bufferSize, AuroraFW::AudioManager::catchPAProblem(), AuroraFW::AudioManager::AudioInfo::getChannels(), AuroraFW::AudioManager::AudioInfo::getSampleRate(), info, path, and sf_open().
~AudioIStream()
AuroraFW::AudioManager::AudioIStream::~AudioIStream ()
Destructs an audio input stream.
See also
AudioIStream()
Since
snapshot20180330
References AFW_NULLPTR, buffer, and info.
Member Function Documentation
record()
void AuroraFW::AudioManager::AudioIStream::record ()
Starts recording audio input.
Exceptions
PAErrorException In case there was a PortAudio error.
See also
pause()
stop()
Since
snapshot20180330
References AuroraFW::AudioManager::catchPAProblem().
pause()
void AuroraFW::AudioManager::AudioIStream::pause ()
Pauses the current recording.
Exceptions
PAErrorException In case there was a PortAudio error.
See also
record()
stop()
Since
snapshot20180330
References AuroraFW::AudioManager::catchPAProblem().
stop()
void AuroraFW::AudioManager::AudioIStream::stop ()
Stops the current recording.
(resets the position back to 0)
Exceptions
PAErrorException In case there was a PortAudio error.
See also
record()
pause()
Since
snapshot20180330
References AuroraFW::AudioManager::catchPAProblem().
isRecording()
bool AuroraFW::AudioManager::AudioIStream::isRecording ()
Returns if the stream is recording audio input.
Returns
true if the stream is recording audio. false otherwise.
See also
isPaused()
isStopped()
Since
snapshot20180330
isPaused()
bool AuroraFW::AudioManager::AudioIStream::isPaused ()
Returns if the stream is currently paused.
Returns
true if the stream was been paused. false otherwise.
Note
If the stream is stopped, it doesn't count as being paused.
See also
isRecording()
isStopped()
Since
snapshot20180330
References isStopped().
isStopped()
bool AuroraFW::AudioManager::AudioIStream::isStopped ()
Returns if the stream is completely stopped and not just paused.
Returns
true if the stream is stopped. false otherwise.
See also
isRecording()
isPaused()
Since
snapshot20180330
Referenced by isPaused().
isBufferFull()
bool AuroraFW::AudioManager::AudioIStream::isBufferFull ()
Returns is the buffer is completely filled with audio data.
Returns
true if the buffer is full. false otherwise.
Since
snapshot20180330
clearBuffer() [1/2]
void AuroraFW::AudioManager::AudioIStream::clearBuffer ()
Clears the entire buffer so it can start fresh for new recordings.
Warning
Calling this without saving the buffer first will discard any data currently stored in the buffer.
See also
clearBuffer(unsigned int , unsigned int)
Since
snapshot20180330
clearBuffer() [2/2]
void AuroraFW::AudioManager::AudioIStream::clearBuffer (unsigned int start, unsigned int finish)
Clears only a portion of the buffer specified by the start and finish parameters.
Parameters
start The start frame.
finish The end frame.
Note
The frame values above must not consider the number of channels the stream has.
See also
clearBuffer()
Since
snapshot20180330
save()
bool AuroraFW::AudioManager::AudioIStream::save ()
Saves the current audio stream (wheter it's empty, full or partially filled) to the disk on the path specified in the constructor.
Returns
true if the saving was successfull. false otherwise.
Since
snapshot20180330
References buffer, bufferSize, info, and sf_writef_float().
Friends And Related Function Documentation
audioInputCallback
int audioInputCallback (const void * inputBuffer, void * outputBuffer, size_t framesPerBuffer, const PaStreamCallbackTimeInfo * timeInfo, PaStreamCallbackFlags statusFlags, void * userData) friend
Referenced by AudioIStream().
Member Data Documentation
path
const char* AuroraFW::AudioManager::AudioIStream::path
The path to save the audio stream to.
Since
snapshot20180330
Referenced by AudioIStream(), glloader.lang.nim.generator.NimGenerator::make_path(), and glloader.lang.d.generator.BaseDGenerator::make_path().
info
AudioInfo* AuroraFW::AudioManager::AudioIStream::info
The AudioInfo object with all the information needed.
Since
snapshot20180330
Referenced by AuroraFW::AudioManager::audioInputCallback(), AudioIStream(), save(), and ~AudioIStream().
buffer
float* AuroraFW::AudioManager::AudioIStream::buffer
The audio stream buffer, that is equal to the product of frames and the number of channels.
See also
bufferSize
Since
snapshot20180330
Referenced by AuroraFW::AudioManager::audioInputCallback(), AudioIStream(), save(), and ~AudioIStream().
bufferSize
const int AuroraFW::AudioManager::AudioIStream::bufferSize
The buffer's size, that is equal to the number of frames requested, without considering the number of channels.
See also
buffer
Since
snapshot20180330
Referenced by AuroraFW::AudioManager::audioInputCallback(), AudioIStream(), and save().
The documentation for this struct was generated from the following files:
AudioInput.h
AudioInput.cpp