Aurora Framework: String.h File Reference
stdl/include/AuroraFW/STDL/LibC/String.h File Reference
Functions
int memcmp (const void *cs, const void *ct, size_t n)
void * memcpy (void *dst, const void *src, size_t n)
void * memmove (void *dst, const void *src, size_t n)
void * memset (void *s, const int c, size_t n)
Function Documentation
memcpy()
void* memcpy (void * dst, const void * src, size_t n)
Referenced by ImFontAtlas::AddFont(), AuroraFW::MemoryAllocator::allocate(), ImDrawList::ChannelsMerge(), ImDrawList::ChannelsSetCurrent(), ImGui::ColorEdit4(), ImGui::ColorPicker4(), ColorPickerOptionsPopup(), AuroraFW::AES::decrypt(), AuroraFW::AES::encrypt(), ImDrawDataBuilder::FlattenIntoSingleLayer(), ImFontAtlas::GetGlyphRangesJapanese(), ImStrdup(), ImGuiTextEditCallbackData::InsertChars(), AuroraFW::Math::mat4< T >::mat4(), AuroraFW::Math::mat4< T >::multiply(), ImGui::NavUpdate(), ImGui::NewFrame(), ImVector< ImGuiStorage::Pair >::reserve(), SetClipboardTextFn_DefaultImpl(), ImGui::SetDragDropPayload(), stb__lit(), and ImGuiStb::STB_TEXTEDIT_INSERTCHARS().
memmove()
void* memmove (void * dst, const void * src, size_t n)
Referenced by ImGui::BringWindowToBack(), ImVector< ImGuiStorage::Pair >::erase(), ImVector< ImGuiStorage::Pair >::insert(), ImGuiTextEditCallbackData::InsertChars(), and ImGuiStb::STB_TEXTEDIT_INSERTCHARS().
memcmp()
int memcmp (const void * cs, const void * ct, size_t n)
Referenced by ImGui::ColorPicker4(), ImDrawList::PathLineToMergeDuplicate(), ImDrawList::UpdateClipRect(), and ImDrawList::UpdateTextureID().
memset()
void* memset (void * s, const int c, size_t n)
Referenced by AuroraFW::MemoryAllocator::allocate(), ImDrawList::ChannelsSplit(), ImGuiPayload::Clear(), ImDrawList::ClearFreeMemory(), ImGui::EndFrame(), ImFontAtlas::GlyphRangesBuilder::GlyphRangesBuilder(), ImFileLoadToMemory(), ImFontAtlasBuildPackCustomRects(), ImFontAtlasBuildWithStbTruetype(), ImFontConfig::ImFontConfig(), ImGuiContext::ImGuiContext(), ImGuiDrawContext::ImGuiDrawContext(), ImGuiIO::ImGuiIO(), ImGuiMenuColumns::ImGuiMenuColumns(), ImGuiSettingsHandler::ImGuiSettingsHandler(), ImGuiTextEditState::ImGuiTextEditState(), ImGui::InputTextEx(), InputTextFilterCharacter(), AuroraFW::Math::mat4< T >::mat4(), ImGui::NavUpdate(), AuroraFW::GEngine::ImGuiLoader::newFrame(), ImGui::NewFrame(), ImGui::SetDragDropPayload(), AuroraFW::GEngine::ImGuiLoader::Unload(), and ImGuiMenuColumns::Update().