Aurora Framework: Init.c File Reference
Win32/Init.c File Reference
Macros
#define GUID_DEVINTERFACE_HID _glfw_GUID_DEVINTERFACE_HID
Functions
char * _glfwCreateUTF8FromWideStringWin32 (const WCHAR *source)
WCHAR * _glfwCreateWideStringFromUTF8Win32 (const char *source)
void _glfwInputErrorWin32 (int error, const char *description)
const char * _glfwPlatformGetVersionString (void)
int _glfwPlatformInit (void)
void _glfwPlatformTerminate (void)
void _glfwUpdateKeyNamesWin32 (void)
static HWND createHelperWindow (void)
static void createKeyTables (void)
static void freeLibraries (void)
BOOL IsWindowsVersionOrGreater (WORD major, WORD minor, WORD sp)
static GLFWbool loadLibraries (void)
Variables
static const GUID _glfw_GUID_DEVINTERFACE_HID
Macro Definition Documentation
GUID_DEVINTERFACE_HID
#define GUID_DEVINTERFACE_HID _glfw_GUID_DEVINTERFACE_HID
Referenced by createHelperWindow().
Function Documentation
IsWindowsVersionOrGreater()
BOOL IsWindowsVersionOrGreater (WORD major, WORD minor, WORD sp)
loadLibraries()
static GLFWbool loadLibraries (void) static
References _glfw, _glfwInputErrorWin32(), GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, and NULL.
Referenced by _glfwPlatformInit().
freeLibraries()
static void freeLibraries (void) static
References _glfw.
Referenced by _glfwPlatformTerminate().
createKeyTables()
static void createKeyTables (void) static
References _glfw, GLFW_KEY_0, GLFW_KEY_1, GLFW_KEY_2, GLFW_KEY_3, GLFW_KEY_4, GLFW_KEY_5, GLFW_KEY_6, GLFW_KEY_7, GLFW_KEY_8, GLFW_KEY_9, GLFW_KEY_A, GLFW_KEY_APOSTROPHE, GLFW_KEY_B, GLFW_KEY_BACKSLASH, GLFW_KEY_BACKSPACE, GLFW_KEY_C, GLFW_KEY_CAPS_LOCK, GLFW_KEY_COMMA, GLFW_KEY_D, GLFW_KEY_DELETE, GLFW_KEY_DOWN, GLFW_KEY_E, GLFW_KEY_END, GLFW_KEY_ENTER, GLFW_KEY_EQUAL, GLFW_KEY_ESCAPE, GLFW_KEY_F, GLFW_KEY_F1, GLFW_KEY_F10, GLFW_KEY_F11, GLFW_KEY_F12, GLFW_KEY_F13, GLFW_KEY_F14, GLFW_KEY_F15, GLFW_KEY_F16, GLFW_KEY_F17, GLFW_KEY_F18, GLFW_KEY_F19, GLFW_KEY_F2, GLFW_KEY_F20, GLFW_KEY_F21, GLFW_KEY_F22, GLFW_KEY_F23, GLFW_KEY_F24, GLFW_KEY_F3, GLFW_KEY_F4, GLFW_KEY_F5, GLFW_KEY_F6, GLFW_KEY_F7, GLFW_KEY_F8, GLFW_KEY_F9, GLFW_KEY_G, GLFW_KEY_GRAVE_ACCENT, GLFW_KEY_H, GLFW_KEY_HOME, GLFW_KEY_I, GLFW_KEY_INSERT, GLFW_KEY_J, GLFW_KEY_K, GLFW_KEY_KP_0, GLFW_KEY_KP_1, GLFW_KEY_KP_2, GLFW_KEY_KP_3, GLFW_KEY_KP_4, GLFW_KEY_KP_5, GLFW_KEY_KP_6, GLFW_KEY_KP_7, GLFW_KEY_KP_8, GLFW_KEY_KP_9, GLFW_KEY_KP_ADD, GLFW_KEY_KP_DECIMAL, GLFW_KEY_KP_DIVIDE, GLFW_KEY_KP_ENTER, GLFW_KEY_KP_MULTIPLY, GLFW_KEY_KP_SUBTRACT, GLFW_KEY_L, GLFW_KEY_LEFT, GLFW_KEY_LEFT_ALT, GLFW_KEY_LEFT_BRACKET, GLFW_KEY_LEFT_CONTROL, GLFW_KEY_LEFT_SHIFT, GLFW_KEY_LEFT_SUPER, GLFW_KEY_M, GLFW_KEY_MENU, GLFW_KEY_MINUS, GLFW_KEY_N, GLFW_KEY_NUM_LOCK, GLFW_KEY_O, GLFW_KEY_P, GLFW_KEY_PAGE_DOWN, GLFW_KEY_PAGE_UP, GLFW_KEY_PAUSE, GLFW_KEY_PERIOD, GLFW_KEY_PRINT_SCREEN, GLFW_KEY_Q, GLFW_KEY_R, GLFW_KEY_RIGHT, GLFW_KEY_RIGHT_ALT, GLFW_KEY_RIGHT_BRACKET, GLFW_KEY_RIGHT_CONTROL, GLFW_KEY_RIGHT_SHIFT, GLFW_KEY_RIGHT_SUPER, GLFW_KEY_S, GLFW_KEY_SCROLL_LOCK, GLFW_KEY_SEMICOLON, GLFW_KEY_SLASH, GLFW_KEY_SPACE, GLFW_KEY_T, GLFW_KEY_TAB, GLFW_KEY_U, GLFW_KEY_UP, GLFW_KEY_V, GLFW_KEY_W, GLFW_KEY_WORLD_2, GLFW_KEY_X, GLFW_KEY_Y, GLFW_KEY_Z, and memset().
Referenced by _glfwPlatformInit().
createHelperWindow()
static HWND createHelperWindow (void) static
References _glfw, _GLFW_WNDCLASSNAME, _glfwInputErrorWin32(), GLFW_PLATFORM_ERROR, GUID_DEVINTERFACE_HID, and NULL.
Referenced by _glfwPlatformInit().
_glfwCreateWideStringFromUTF8Win32()
WCHAR* _glfwCreateWideStringFromUTF8Win32 (const char * source)
References _glfwInputErrorWin32(), GLFW_PLATFORM_ERROR, NULL, and source.
Referenced by _glfwPlatformSetWindowTitle(), and createNativeWindow().
_glfwCreateUTF8FromWideStringWin32()
char* _glfwCreateUTF8FromWideStringWin32 (const WCHAR * source)
References _glfwInputErrorWin32(), GLFW_PLATFORM_ERROR, NULL, and source.
Referenced by _glfwPlatformGetClipboardString(), createMonitor(), and windowProc().
_glfwInputErrorWin32()
void _glfwInputErrorWin32 (int error, const char * description)
References _GLFW_MESSAGE_SIZE, _glfwInputError(), setup::description, and NULL.
Referenced by _glfwCreateContextWGL(), _glfwCreateUTF8FromWideStringWin32(), _glfwCreateWideStringFromUTF8Win32(), _glfwInitWGL(), _glfwPlatformCreateStandardCursor(), _glfwPlatformCreateTls(), _glfwPlatformGetClipboardString(), _glfwPlatformSetClipboardString(), _glfwPlatformSetCursorMode(), _glfwRegisterWindowClassWin32(), createHelperWindow(), createIcon(), createNativeWindow(), getPixelFormatAttrib(), loadLibraries(), and makeContextCurrentWGL().
_glfwUpdateKeyNamesWin32()
void _glfwUpdateKeyNamesWin32 (void)
References _glfw, GLFW_KEY_KP_0, GLFW_KEY_KP_ADD, GLFW_KEY_LAST, GLFW_KEY_SPACE, memset(), and NULL.
Referenced by _glfwPlatformInit(), and windowProc().
_glfwPlatformInit()
int _glfwPlatformInit (void)
References _glfw, _glfwInitJoysticksWin32(), _glfwInitTimerWin32(), _glfwPollMonitorsWin32(), _glfwRegisterWindowClassWin32(), _glfwUpdateKeyNamesWin32(), createHelperWindow(), createKeyTables(), GLFW_FALSE, GLFW_TRUE, IsWindows8Point1OrGreater, IsWindowsVistaOrGreater, loadLibraries(), PROCESS_PER_MONITOR_DPI_AWARE, SetProcessDPIAware, and SetProcessDpiAwareness.
_glfwPlatformTerminate()
void _glfwPlatformTerminate (void)
References _glfw, _glfwTerminateEGL(), _glfwTerminateJoysticksWin32(), _glfwTerminateWGL(), _glfwUnregisterWindowClassWin32(), and freeLibraries().
_glfwPlatformGetVersionString()
const char* _glfwPlatformGetVersionString (void)
References _GLFW_VERSION_NUMBER.
Variable Documentation
_glfw_GUID_DEVINTERFACE_HID
const GUID _glfw_GUID_DEVINTERFACE_HID static
Initial value:
=
    {0x4d1e55b2,0xf16f,0x11cf,{0x88,0xcb,0x00,0x11,0x11,0x00,0x00,0x30}}