Aurora Framework: PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags > Class Template Reference
PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags > Class Template Reference
Writer with indentation and spacing.
Public Types
typedef Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags > Base
typedef Base::Ch Ch
Public Member Functions
PrettyWriter (OutputStream &os, StackAllocator *allocator=0, size_t levelDepth=Base::kDefaultLevelDepth)
Constructor.
PrettyWriter (StackAllocator *allocator=0, size_t levelDepth=Base::kDefaultLevelDepth)
void Flush ()
Flush the output stream.
int GetMaxDecimalPlaces () const
bool IsComplete () const
Checks whether the output is a complete JSON.
bool RawValue (const Ch *json, size_t length, Type type)
Write a raw JSON value.
void Reset (OutputStream &os)
Reset the writer with a new stream.
PrettyWriter & SetFormatOptions (PrettyFormatOptions options)
Set pretty writer formatting options.
PrettyWriter & SetIndent (Ch indentChar, unsigned indentCharCount)
Set custom indentation.
void SetMaxDecimalPlaces (int maxDecimalPlaces)
Sets the maximum number of decimal places for double output.
Implementation of Handler
See also
Handler
bool Null ()
bool Bool (bool b)
bool Int (int i)
bool Uint (unsigned u)
bool Int64 (int64_t i64)
bool Uint64 (uint64_t u64)
bool Double (double d)
bool RawNumber (const Ch *str, SizeType length, bool copy=false)
bool String (const Ch *str, SizeType length, bool copy=false)
bool StartObject ()
bool Key (const Ch *str, SizeType length, bool copy=false)
bool EndObject (SizeType memberCount=0)
bool StartArray ()
bool EndArray (SizeType memberCount=0)
Convenience extensions
bool String (const Ch *str)
Simpler but slower overload.
bool Key (const Ch *str)
Convenience extensions
bool String (const Ch *const &str)
Simpler but slower overload.
bool Key (const Ch *const &str)
Static Public Attributes
static const int kDefaultMaxDecimalPlaces = 324
Protected Member Functions
bool EndValue (bool ret)
void Prefix (Type type)
void PrettyPrefix (Type type)
bool ScanWriteUnescapedString (GenericStringStream< SourceEncoding > &is, size_t length)
bool WriteBool (bool b)
bool WriteDouble (double d)
template<>
bool WriteDouble (double d)
bool WriteEndArray ()
bool WriteEndObject ()
void WriteIndent ()
bool WriteInt (int i)
template<>
bool WriteInt (int i)
bool WriteInt64 (int64_t i64)
template<>
bool WriteInt64 (int64_t i64)
bool WriteNull ()
bool WriteRawValue (const Ch *json, size_t length)
bool WriteStartArray ()
bool WriteStartObject ()
bool WriteString (const Ch *str, SizeType length)
bool WriteUint (unsigned u)
template<>
bool WriteUint (unsigned u)
bool WriteUint64 (uint64_t u64)
template<>
bool WriteUint64 (uint64_t u)
Protected Attributes
PrettyFormatOptions formatOptions_
bool hasRoot_
Ch indentChar_
unsigned indentCharCount_
internal::Stack< StackAllocator > level_stack_
int maxDecimalPlaces_
OutputStream * os_
Static Protected Attributes
static const size_t kDefaultLevelDepth = 32
Detailed Description
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags>
class PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >
Writer with indentation and spacing.
Template Parameters
OutputStream Type of output os.
SourceEncoding Encoding of source string.
TargetEncoding Encoding of output stream.
StackAllocator Type of allocator for allocating memory of stack.
Member Typedef Documentation
Base
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> typedef Writer<OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags> PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Base
Ch
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> typedef Base::Ch PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Ch
Constructor & Destructor Documentation
PrettyWriter() [1/2]
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::PrettyWriter (OutputStream & os, StackAllocator * allocator = 0, size_t levelDepth = Base::kDefaultLevelDepth) inline explicit
Constructor.
Parameters
os Output stream.
allocator User supplied allocator. If it is null, it will create a private one.
levelDepth Initial capacity of stack.
PrettyWriter() [2/2]
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::PrettyWriter (StackAllocator * allocator = 0, size_t levelDepth = Base::kDefaultLevelDepth) inline explicit
Member Function Documentation
SetIndent()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> PrettyWriter& PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::SetIndent (Ch indentChar, unsigned indentCharCount) inline
Set custom indentation.
Parameters
indentChar Character for indentation. Must be whitespace character (' ', '\t', '\n', '\r').
indentCharCount Number of indent characters for each indentation level.
Note
The default indentation is 4 spaces.
References PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::indentChar_, PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::indentCharCount_, and RAPIDJSON_ASSERT.
SetFormatOptions()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> PrettyWriter& PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::SetFormatOptions (PrettyFormatOptions options) inline
Set pretty writer formatting options.
Parameters
options Formatting options.
References PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::formatOptions_.
Null()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Null () inline
References kNullType, PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::PrettyPrefix(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteNull().
Bool()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Bool (bool b) inline
References kFalseType, kTrueType, PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::PrettyPrefix(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteBool().
Int()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Int (int i) inline
References kNumberType, PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::PrettyPrefix(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteInt().
Uint()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Uint (unsigned u) inline
References kNumberType, PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::PrettyPrefix(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteUint().
Int64()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Int64 (int64_t i64) inline
References kNumberType, PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::PrettyPrefix(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteInt64().
Uint64()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Uint64 (uint64_t u64) inline
References kNumberType, PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::PrettyPrefix(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteUint64().
Double()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Double (double d) inline
References kNumberType, PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::PrettyPrefix(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteDouble().
RawNumber()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::RawNumber (const Ch * str, SizeType length, bool copy = false) inline
References kNumberType, PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::PrettyPrefix(), RAPIDJSON_ASSERT, and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteString().
String() [1/3]
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String (const Ch * str, SizeType length, bool copy = false) inline
References kStringType, PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::PrettyPrefix(), RAPIDJSON_ASSERT, and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteString().
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Key().
StartObject()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartObject () inline
References kObjectType, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::level_stack_, PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::PrettyPrefix(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteStartObject().
Key() [1/3]
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Key (const Ch * str, SizeType length, bool copy = false) inline
References PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String().
EndObject()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndObject (SizeType memberCount = 0) inline
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Flush(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::level_stack_, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_, RAPIDJSON_ASSERT, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteEndObject(), and PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteIndent().
StartArray()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartArray () inline
References kArrayType, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::level_stack_, PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::PrettyPrefix(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteStartArray().
EndArray()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndArray (SizeType memberCount = 0) inline
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Flush(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::formatOptions_, kFormatSingleLineArray, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::level_stack_, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_, RAPIDJSON_ASSERT, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteEndArray(), and PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteIndent().
String() [2/3]
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String (const Ch * str) inline
Simpler but slower overload.
References PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String(), and internal::StrLen().
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String().
Key() [2/3]
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Key (const Ch * str) inline
References PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Key(), and internal::StrLen().
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Key().
RawValue()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::RawValue (const Ch * json, size_t length, Type type) inline
Write a raw JSON value.
For user to write a stringified JSON as a value.
Parameters
json A well-formed JSON value. It should not contain null character within [0, length - 1] range.
length Length of the json.
type Type of the root of json.
Note
When using PrettyWriter::RawValue(), the result json may not be indented correctly.
References PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::PrettyPrefix(), RAPIDJSON_ASSERT, and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteRawValue().
PrettyPrefix()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> void PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::PrettyPrefix (Type type) inline protected
References PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::formatOptions_, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::hasRoot_, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Level::inArray, kFormatSingleLineArray, kStringType, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::level_stack_, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_, RAPIDJSON_ASSERT, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Level::valueCount, and PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteIndent().
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Bool(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Double(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Int(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Int64(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Null(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::RawNumber(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::RawValue(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartArray(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartObject(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Uint(), and PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Uint64().
WriteIndent()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> void PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteIndent () inline protected
References internal::Stack< Allocator >::GetSize(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::indentChar_, PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::indentCharCount_, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::level_stack_, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_, and PutN().
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndArray(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndObject(), and PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::PrettyPrefix().
Reset()
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> void Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Reset (OutputStream & os) inline inherited
Reset the writer with a new stream.
This function reset the writer with a new stream and default settings, in order to make a Writer object reusable for output multiple JSONs.
Parameters
os New output stream.
Writer<OutputStream> writer(os1);
writer.StartObject();
// ...
writer.EndObject();
writer.Reset(os2);
writer.StartObject();
// ...
writer.EndObject();
References internal::Stack< Allocator >::Clear(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::hasRoot_, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::level_stack_, and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_.
IsComplete()
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::IsComplete () const inline inherited
Checks whether the output is a complete JSON.
A complete JSON has a complete root object or array.
References internal::Stack< Allocator >::Empty(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::hasRoot_, and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::level_stack_.
GetMaxDecimalPlaces()
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> int Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::GetMaxDecimalPlaces () const inline inherited
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::maxDecimalPlaces_.
SetMaxDecimalPlaces()
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> void Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::SetMaxDecimalPlaces (int maxDecimalPlaces) inline inherited
Sets the maximum number of decimal places for double output.
This setting truncates the output with specified number of decimal places.
For example,
writer.SetMaxDecimalPlaces(3);
writer.StartArray();
writer.Double(0.12345);                 // "0.123"
writer.Double(0.0001);                  // "0.0"
writer.Double(1.234567890123456e30);    // "1.234567890123456e30" (do not truncate significand for positive exponent)
writer.Double(1.23e-4);                 // "0.0"                  (do truncate significand for negative exponent)
writer.EndArray();
The default setting does not truncate any decimal places. You can restore to this setting by calling
writer.SetMaxDecimalPlaces(Writer::kDefaultMaxDecimalPlaces);
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::maxDecimalPlaces_.
String() [3/3]
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String (const Ch *const & str) inline inherited
Simpler but slower overload.
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String(), and internal::StrLen().
Referenced by Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String().
Key() [3/3]
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Key (const Ch *const & str) inline inherited
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Key(), and internal::StrLen().
Referenced by Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Key().
Flush()
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> void Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Flush () inline inherited
Flush the output stream.
Allows the user to flush the output stream immediately.
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_.
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndArray(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndObject(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndValue().
WriteNull()
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteNull () inline protected inherited
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_, PutReserve(), and PutUnsafe().
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Null(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Null().
WriteBool()
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteBool (bool b) inline protected inherited
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_, PutReserve(), and PutUnsafe().
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Bool(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Bool().
WriteInt() [1/2]
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteInt (int i) inline protected inherited
References internal::i32toa(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_, PutReserve(), and PutUnsafe().
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Int(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Int().
WriteInt() [2/2]
template<> bool Writer< StringBuffer >::WriteInt (int i) inline protected inherited
References internal::i32toa().
WriteUint() [1/2]
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteUint (unsigned u) inline protected inherited
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_, PutReserve(), PutUnsafe(), and internal::u32toa().
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Uint(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Uint().
WriteUint() [2/2]
template<> bool Writer< StringBuffer >::WriteUint (unsigned u) inline protected inherited
References internal::u32toa().
WriteInt64() [1/2]
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteInt64 (int64_t i64) inline protected inherited
References internal::i64toa(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_, PutReserve(), and PutUnsafe().
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Int64(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Int64().
WriteInt64() [2/2]
template<> bool Writer< StringBuffer >::WriteInt64 (int64_t i64) inline protected inherited
References internal::i64toa().
WriteUint64() [1/2]
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteUint64 (uint64_t u64) inline protected inherited
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_, PutReserve(), PutUnsafe(), and internal::u64toa().
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Uint64(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Uint64().
WriteUint64() [2/2]
template<> bool Writer< StringBuffer >::WriteUint64 (uint64_t u) inline protected inherited
References internal::u64toa().
WriteDouble() [1/2]
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteDouble (double d) inline protected inherited
References internal::dtoa(), kWriteNanAndInfFlag, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::maxDecimalPlaces_, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_, PutReserve(), and PutUnsafe().
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Double(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Double().
WriteDouble() [2/2]
template<> bool Writer< StringBuffer >::WriteDouble (double d) inline protected inherited
References internal::dtoa(), kWriteDefaultFlags, kWriteNanAndInfFlag, PutReserve(), and PutUnsafe().
WriteString()
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteString (const Ch * str, SizeType length) inline protected inherited
References kWriteValidateEncodingFlag, lead(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_, GenericStringStream< Encoding >::Peek(), PutReserve(), PutUnsafe(), RAPIDJSON_ASSERT, RAPIDJSON_UNLIKELY, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::ScanWriteUnescapedString(), GenericStringStream< Encoding >::Take(), and Z16.
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::RawNumber(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::RawNumber(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String().
ScanWriteUnescapedString()
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::ScanWriteUnescapedString (GenericStringStream< SourceEncoding > & is, size_t length) inline protected inherited
References RAPIDJSON_LIKELY, and GenericStringStream< Encoding >::Tell().
Referenced by Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteString().
WriteStartObject()
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteStartObject () inline protected inherited
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_.
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartObject(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartObject().
WriteEndObject()
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteEndObject () inline protected inherited
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_.
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndObject(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndObject().
WriteStartArray()
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteStartArray () inline protected inherited
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_.
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartArray(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartArray().
WriteEndArray()
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteEndArray () inline protected inherited
References Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_.
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndArray(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndArray().
WriteRawValue()
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteRawValue (const Ch * json, size_t length) inline protected inherited
References kWriteValidateEncodingFlag, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_, GenericStringStream< Encoding >::Peek(), PutReserve(), RAPIDJSON_ASSERT, RAPIDJSON_LIKELY, RAPIDJSON_UNLIKELY, and GenericStringStream< Encoding >::Tell().
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::RawValue(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::RawValue().
Prefix()
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> void Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Prefix (Type type) inline protected inherited
References internal::Stack< Allocator >::GetSize(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::hasRoot_, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Level::inArray, kStringType, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::level_stack_, Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_, RAPIDJSON_ASSERT, RAPIDJSON_LIKELY, and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Level::valueCount.
Referenced by Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Bool(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Double(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Int(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Int64(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Null(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::RawNumber(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::RawValue(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartArray(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartObject(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Uint(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Uint64().
EndValue()
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndValue (bool ret) inline protected inherited
References internal::Stack< Allocator >::Empty(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Flush(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::level_stack_, and RAPIDJSON_UNLIKELY.
Referenced by Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Bool(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Double(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndArray(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndObject(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Int(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Int64(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Null(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::RawNumber(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::RawValue(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Uint(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Uint64().
Member Data Documentation
indentChar_
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> Ch PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::indentChar_ protected
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::SetIndent(), and PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteIndent().
indentCharCount_
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> unsigned PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::indentCharCount_ protected
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::SetIndent(), and PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteIndent().
formatOptions_
template<typename OutputStream , typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> PrettyFormatOptions PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::formatOptions_ protected
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndArray(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::PrettyPrefix(), and PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::SetFormatOptions().
kDefaultMaxDecimalPlaces
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> const int Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::kDefaultMaxDecimalPlaces = 324 static inherited
kDefaultLevelDepth
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> const size_t Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::kDefaultLevelDepth = 32 static protected inherited
os_
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> OutputStream* Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::os_ protected inherited
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndArray(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndObject(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Flush(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Prefix(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::PrettyPrefix(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Reset(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteBool(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteDouble(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteEndArray(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteEndObject(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteIndent(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteInt(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteInt64(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteNull(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteRawValue(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteStartArray(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteStartObject(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteString(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteUint(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteUint64().
level_stack_
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> internal::Stack<StackAllocator> Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::level_stack_ protected inherited
Referenced by PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndArray(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndArray(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndObject(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndObject(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::EndValue(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::IsComplete(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Prefix(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::PrettyPrefix(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Reset(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartArray(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartArray(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartObject(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::StartObject(), and PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteIndent().
maxDecimalPlaces_
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> int Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::maxDecimalPlaces_ protected inherited
Referenced by Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::GetMaxDecimalPlaces(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::SetMaxDecimalPlaces(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteDouble().
hasRoot_
template<typename OutputStream, typename SourceEncoding = UTF8<>, typename TargetEncoding = UTF8<>, typename StackAllocator = CrtAllocator, unsigned writeFlags = kWriteDefaultFlags> bool Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::hasRoot_ protected inherited
Referenced by Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::IsComplete(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Prefix(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::PrettyPrefix(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Reset().
The documentation for this class was generated from the following files:
fwd.h
prettywriter.h