Aurora Framework: AuroraFW::GUI::Label Class Reference
AuroraFW::GUI::Label Class Reference
Public Member Functions
Label (Widget *=AFW_NULLPTR, const std::string &name="New Label")
Label (const Label &)=delete
template<typename R , typename... Args>
void connect (const std::string &, R(*)(Args...), void *=AFW_NULLPTR)
template<typename R , typename... Args>
void connect (const std::string &signal_, std::function< R(Args...)> callback, void *data=AFW_NULLPTR)
void destroy ()
AlignMode getAlignment () const
void getAlignment (float &, float &) const
AFW_FORCE_INLINE GtkWidget * getNativeGtkWidget () const
std::string getText () const
WrapMode getWrapMode () const
float getXAlignment () const
float getYAlignment () const
void hide ()
bool isSelectable () const
bool isWrap () const
std::string name () const
Label & operator= (const Label &)=delete
Widget * parent () const
void setAlignment (AlignMode)
void setAlignment (const float, const float)
void setName (const std::string &)
void setParent (Widget *)
void setSelectable (bool)
void setText (std::string)
void setWrap (bool)
void setWrapMode (WrapMode)
virtual void show ()
Protected Member Functions
void _show ()
Protected Attributes
GtkWidget * _widget
Constructor & Destructor Documentation
Label() [1/2]
AuroraFW::GUI::Label::Label (Widget * parent = AFW_NULLPTR, const std::string & name = "New Label")
References AuroraFW::GUI::Widget::_widget, AuroraFW::DebugManager::Log(), AuroraFW::GUI::Widget::name(), AuroraFW::GUI::Widget::parent(), and AuroraFW::GUI::Widget::setParent().
Label() [2/2]
AuroraFW::GUI::Label::Label (const Label &) delete
Member Function Documentation
operator=()
Label& AuroraFW::GUI::Label::operator= (const Label &) delete
setText()
void AuroraFW::GUI::Label::setText (std::string text)
References AuroraFW::GUI::Widget::_widget, and AuroraFW::DebugManager::Log().
setSelectable()
void AuroraFW::GUI::Label::setSelectable (bool value)
References AuroraFW::GUI::Widget::_widget, AuroraFW::DebugManager::Log(), and value.
setWrap()
void AuroraFW::GUI::Label::setWrap (bool value)
References AuroraFW::GUI::Widget::_widget, AuroraFW::DebugManager::Log(), and value.
setWrapMode()
void AuroraFW::GUI::Label::setWrapMode (WrapMode mode)
References AuroraFW::GUI::Widget::_widget, AuroraFW::DebugManager::Log(), and mode().
setAlignment() [1/2]
void AuroraFW::GUI::Label::setAlignment (AlignMode mode)
References AuroraFW::GUI::Widget::_widget, AuroraFW::GUI::BottomCenter, AuroraFW::GUI::BottomLeft, AuroraFW::GUI::BottomRight, AuroraFW::GUI::Center, AuroraFW::GUI::Custom, AuroraFW::GUI::Left, AuroraFW::DebugManager::Log(), mode(), AuroraFW::GUI::Right, AuroraFW::GUI::TopCenter, AuroraFW::GUI::TopLeft, and AuroraFW::GUI::TopRight.
setAlignment() [2/2]
void AuroraFW::GUI::Label::setAlignment (const float x, const float y)
References AuroraFW::GUI::Widget::_widget, and AuroraFW::DebugManager::Log().
getText()
std::string AuroraFW::GUI::Label::getText () const
References AuroraFW::GUI::Widget::_widget, and AuroraFW::DebugManager::Log().
isSelectable()
bool AuroraFW::GUI::Label::isSelectable () const
References AuroraFW::GUI::Widget::_widget, and AuroraFW::DebugManager::Log().
isWrap()
bool AuroraFW::GUI::Label::isWrap () const
References AuroraFW::GUI::Widget::_widget, and AuroraFW::DebugManager::Log().
getWrapMode()
WrapMode AuroraFW::GUI::Label::getWrapMode () const
References AuroraFW::GUI::Widget::_widget, and AuroraFW::DebugManager::Log().
getAlignment() [1/2]
AlignMode AuroraFW::GUI::Label::getAlignment () const
References AuroraFW::GUI::Widget::_widget, AuroraFW::GUI::BottomCenter, AuroraFW::GUI::BottomLeft, AuroraFW::GUI::BottomRight, AuroraFW::GUI::Center, AuroraFW::GUI::Custom, AuroraFW::GUI::Left, AuroraFW::DebugManager::Log(), AuroraFW::GUI::Right, AuroraFW::GUI::TopCenter, AuroraFW::GUI::TopLeft, and AuroraFW::GUI::TopRight.
getAlignment() [2/2]
void AuroraFW::GUI::Label::getAlignment (float & x, float & y) const
References AuroraFW::GUI::Widget::_widget.
getXAlignment()
float AuroraFW::GUI::Label::getXAlignment () const
References AuroraFW::GUI::Widget::_widget, and AuroraFW::DebugManager::Log().
getYAlignment()
float AuroraFW::GUI::Label::getYAlignment () const
References AuroraFW::GUI::Widget::_widget, and AuroraFW::DebugManager::Log().
hide()
void AuroraFW::GUI::Widget::hide () inherited
References AuroraFW::GUI::Widget::_widget.
show()
virtual void AuroraFW::GUI::Widget::show () inline virtual inherited
Reimplemented in AuroraFW::GUI::Window.
destroy()
void AuroraFW::GUI::Widget::destroy () inherited
References AuroraFW::GUI::Widget::_widget.
Referenced by AuroraFW::GUI::Window::~Window().
setParent()
void AuroraFW::GUI::Widget::setParent (Widget * parent) inherited
References AuroraFW::GUI::Widget::_widget, and AuroraFW::GUI::Widget::parent().
Referenced by AuroraFW::GUI::Button::Button(), and Label().
setName()
void AuroraFW::GUI::Widget::setName (const std::string & str) inherited
References AuroraFW::GUI::Widget::_widget.
name()
std::string AuroraFW::GUI::Widget::name () const inherited
Referenced by AuroraFW::GUI::Button::Button(), Label(), and AuroraFW::GUI::Window::Window().
parent()
Widget * AuroraFW::GUI::Widget::parent () const inherited
References AuroraFW::GUI::Widget::_widget.
Referenced by AuroraFW::GUI::Button::Button(), Label(), and AuroraFW::GUI::Widget::setParent().
getNativeGtkWidget()
AFW_FORCE_INLINE GtkWidget* AuroraFW::GUI::Widget::getNativeGtkWidget () const inline inherited
Referenced by AuroraFW::GUI::Window::addWidget().
connect() [1/2]
template<typename R , typename... Args> void AuroraFW::GUI::Widget::connect (const std::string & signal_, R(*)(Args...) callback, void * data = AFW_NULLPTR) inherited
References AuroraFW::GUI::Widget::_widget, and AuroraFW::DebugManager::Log().
Referenced by AuroraFW::GUI::Window::Window().
connect() [2/2]
template<typename R , typename... Args> void AuroraFW::GUI::Widget::connect (const std::string & signal_, std::function< R(Args...)> callback, void * data = AFW_NULLPTR) inline inherited
References AuroraFW::getCallbackPtr().
_show()
void AuroraFW::GUI::Widget::_show () protected inherited
References AuroraFW::GUI::Widget::_widget.
Referenced by AuroraFW::GUI::Window::show().
Member Data Documentation
_widget
GtkWidget* AuroraFW::GUI::Widget::_widget protected inherited
Referenced by AuroraFW::GUI::Widget::_show(), AuroraFW::GUI::Window::addWidget(), AuroraFW::GUI::Button::Button(), AuroraFW::GUI::Window::close(), AuroraFW::GUI::Widget::connect(), AuroraFW::GUI::Window::deiconify(), AuroraFW::GUI::Widget::destroy(), AuroraFW::GUI::Window::fullscreen(), getAlignment(), getText(), getWrapMode(), getXAlignment(), getYAlignment(), AuroraFW::GUI::Widget::hide(), AuroraFW::GUI::Window::iconify(), isSelectable(), isWrap(), Label(), AuroraFW::GUI::Window::maximize(), AuroraFW::GUI::Window::move(), AuroraFW::GUI::Widget::parent(), AuroraFW::GUI::Window::resize(), setAlignment(), AuroraFW::GUI::Window::setIcon(), AuroraFW::GUI::Widget::setName(), AuroraFW::GUI::Window::setOpacity(), AuroraFW::GUI::Widget::setParent(), AuroraFW::GUI::Window::setPos(), AuroraFW::GUI::Window::setResizable(), setSelectable(), setText(), AuroraFW::GUI::Window::setTitle(), setWrap(), setWrapMode(), AuroraFW::GUI::Window::stick(), AuroraFW::GUI::Window::unfullscreen(), AuroraFW::GUI::Window::unmaximize(), AuroraFW::GUI::Window::unstick(), and AuroraFW::GUI::Window::Window().
The documentation for this class was generated from the following files:
Label.h
Label.cpp