Aurora Framework: Joystick.m File Reference
Joystick.m File Reference
Classes
struct _GLFWjoyelementNS
Typedefs
typedef struct _GLFWjoyelementNS _GLFWjoyelementNS
Functions
void _glfwInitJoysticksNS (void)
int _glfwPlatformPollJoystick (_GLFWjoystick *js, int mode)
void _glfwPlatformUpdateGamepadGUID (char *guid)
void _glfwTerminateJoysticksNS (void)
static void closeJoystick (_GLFWjoystick *js)
static CFComparisonResult compareElements (const void *fp, const void *sp, void *user)
static long getElementValue (_GLFWjoystick *js, _GLFWjoyelementNS *element)
static void matchCallback (void *context, IOReturn result, void *sender, IOHIDDeviceRef device)
static void removeCallback (void *context, IOReturn result, void *sender, IOHIDDeviceRef device)
Typedef Documentation
_GLFWjoyelementNS
typedef struct _GLFWjoyelementNS _GLFWjoyelementNS
Function Documentation
getElementValue()
static long getElementValue (_GLFWjoystick * js, _GLFWjoyelementNS * element) static
References _GLFWjoyelementNS::native, and value.
Referenced by _glfwPlatformPollJoystick().
compareElements()
static CFComparisonResult compareElements (const void * fp, const void * sp, void * user) static
References _GLFWjoyelementNS::index, and _GLFWjoyelementNS::usage.
Referenced by matchCallback().
closeJoystick()
static void closeJoystick (_GLFWjoystick * js) static
References _glfwFreeJoystick(), _glfwInputJoystick(), _GLFWjoystick::axes, _GLFWjoystick::buttons, GLFW_DISCONNECTED, _GLFWjoystick::hats, and _GLFWjoystick::present.
Referenced by _glfwTerminateJoysticksNS(), and removeCallback().
matchCallback()
static void matchCallback (void * context, IOReturn result, void * sender, IOHIDDeviceRef device) static
References _glfw, _glfwAllocJoystick(), _glfwInputJoystick(), _GLFWjoystick::axes, _GLFWjoystick::buttons, compareElements(), GLFW_CONNECTED, GLFW_JOYSTICK_LAST, _GLFWjoystick::hats, _GLFWjoyelementNS::index, _GLFWlibrary::joysticks, _GLFWjoyelementNS::maximum, _GLFWjoyelementNS::minimum, setup::name, _GLFWjoyelementNS::native, NULL, _GLFWjoyelementNS::usage, and create_symbols_file::version.
Referenced by _glfwInitJoysticksNS().
removeCallback()
static void removeCallback (void * context, IOReturn result, void * sender, IOHIDDeviceRef device) static
References _glfw, closeJoystick(), GLFW_JOYSTICK_LAST, and _GLFWlibrary::joysticks.
Referenced by _glfwInitJoysticksNS().
_glfwInitJoysticksNS()
void _glfwInitJoysticksNS (void)
References _glfw, _glfwInputError(), GLFW_PLATFORM_ERROR, matchCallback(), NULL, and removeCallback().
Referenced by _glfwPlatformInit().
_glfwTerminateJoysticksNS()
void _glfwTerminateJoysticksNS (void)
References _glfw, closeJoystick(), GLFW_JOYSTICK_LAST, _GLFWlibrary::joysticks, and NULL.
Referenced by _glfwPlatformTerminate().
_glfwPlatformPollJoystick()
int _glfwPlatformPollJoystick (_GLFWjoystick * js, int mode)
Referenced by glfwGetGamepadName(), glfwGetGamepadState(), glfwGetJoystickAxes(), glfwGetJoystickButtons(), glfwGetJoystickGUID(), glfwGetJoystickHats(), glfwGetJoystickName(), glfwJoystickIsGamepad(), and glfwJoystickPresent().
_glfwPlatformUpdateGamepadGUID()
void _glfwPlatformUpdateGamepadGUID (char * guid)
Referenced by parseMapping().