Aurora Framework: ImGuiStb Namespace Reference
ImGuiStb Namespace Reference
Functions
static bool is_separator (unsigned int c)
static int is_word_boundary_from_right (STB_TEXTEDIT_STRING *obj, int idx)
static void STB_TEXTEDIT_DELETECHARS (STB_TEXTEDIT_STRING *obj, int pos, int n)
static ImWchar STB_TEXTEDIT_GETCHAR (const STB_TEXTEDIT_STRING *obj, int idx)
static float STB_TEXTEDIT_GETWIDTH (STB_TEXTEDIT_STRING *obj, int line_start_idx, int char_idx)
static bool STB_TEXTEDIT_INSERTCHARS (STB_TEXTEDIT_STRING *obj, int pos, const ImWchar *new_text, int new_text_len)
static int STB_TEXTEDIT_KEYTOTEXT (int key)
static void STB_TEXTEDIT_LAYOUTROW (StbTexteditRow *r, STB_TEXTEDIT_STRING *obj, int line_start_idx)
static int STB_TEXTEDIT_MOVEWORDLEFT_IMPL (STB_TEXTEDIT_STRING *obj, int idx)
static int STB_TEXTEDIT_MOVEWORDRIGHT_IMPL (STB_TEXTEDIT_STRING *obj, int idx)
static int STB_TEXTEDIT_STRINGLEN (const STB_TEXTEDIT_STRING *obj)
Variables
static ImWchar STB_TEXTEDIT_NEWLINE = '\n'
Function Documentation
STB_TEXTEDIT_STRINGLEN()
static int ImGuiStb::STB_TEXTEDIT_STRINGLEN (const STB_TEXTEDIT_STRING * obj) static
STB_TEXTEDIT_GETCHAR()
static ImWchar ImGuiStb::STB_TEXTEDIT_GETCHAR (const STB_TEXTEDIT_STRING * obj, int idx) static
STB_TEXTEDIT_GETWIDTH()
static float ImGuiStb::STB_TEXTEDIT_GETWIDTH (STB_TEXTEDIT_STRING * obj, int line_start_idx, int char_idx) static
References ImGuiContext::Font, ImGuiContext::FontSize, ImFont::FontSize, ImFont::GetCharAdvance(), GImGui, and STB_TEXTEDIT_GETWIDTH_NEWLINE.
STB_TEXTEDIT_KEYTOTEXT()
static int ImGuiStb::STB_TEXTEDIT_KEYTOTEXT (int key) static
STB_TEXTEDIT_LAYOUTROW()
static void ImGuiStb::STB_TEXTEDIT_LAYOUTROW (StbTexteditRow * r, STB_TEXTEDIT_STRING * obj, int line_start_idx) static
References StbTexteditRow::baseline_y_delta, InputTextCalcTextSizeW(), NULL, StbTexteditRow::num_chars, ImVec2::x, StbTexteditRow::x0, StbTexteditRow::x1, ImVec2::y, StbTexteditRow::ymax, and StbTexteditRow::ymin.
is_separator()
static bool ImGuiStb::is_separator (unsigned int c) static
References ImCharIsSpace().
Referenced by is_word_boundary_from_right().
is_word_boundary_from_right()
static int ImGuiStb::is_word_boundary_from_right (STB_TEXTEDIT_STRING * obj, int idx) static
References is_separator().
Referenced by STB_TEXTEDIT_MOVEWORDLEFT_IMPL(), and STB_TEXTEDIT_MOVEWORDRIGHT_IMPL().
STB_TEXTEDIT_MOVEWORDLEFT_IMPL()
static int ImGuiStb::STB_TEXTEDIT_MOVEWORDLEFT_IMPL (STB_TEXTEDIT_STRING * obj, int idx) static
References is_word_boundary_from_right().
STB_TEXTEDIT_MOVEWORDRIGHT_IMPL()
static int ImGuiStb::STB_TEXTEDIT_MOVEWORDRIGHT_IMPL (STB_TEXTEDIT_STRING * obj, int idx) static
References is_word_boundary_from_right().
STB_TEXTEDIT_DELETECHARS()
static void ImGuiStb::STB_TEXTEDIT_DELETECHARS (STB_TEXTEDIT_STRING * obj, int pos, int n) static
References ImTextCountUtf8BytesFromStr().
STB_TEXTEDIT_INSERTCHARS()
static bool ImGuiStb::STB_TEXTEDIT_INSERTCHARS (STB_TEXTEDIT_STRING * obj, int pos, const ImWchar * new_text, int new_text_len) static
References IM_ASSERT, ImTextCountUtf8BytesFromStr(), memcpy(), and memmove().
Variable Documentation
STB_TEXTEDIT_NEWLINE
ImWchar ImGuiStb::STB_TEXTEDIT_NEWLINE = '\n' static