Aurora Framework: ALACBitUtilities.h File Reference
ALACBitUtilities.h File Reference
Classes
struct BitBuffer
Macros
#define MAX(x, y) ((x) > (y) ? (x) : (y))
#define MIN(x, y) ((x) < (y) ? (x) : (y))
#define RequireAction(condition, action) if (! (condition)) { action }
#define RequireActionSilent(condition, action) if (! (condition)) { action }
#define RequireNoErr(condition, action) if (condition) { action }
Typedefs
typedef struct BitBuffer BitBuffer
Enumerations
enum { ALAC_noErr = 0 }
enum ELEMENT_TYPE {
ID_SCE = 0, ID_CPE = 1, ID_CCE = 2, ID_LFE = 3,
ID_DSE = 4, ID_PCE = 5, ID_FIL = 6, ID_END = 7
}
Functions
void BitBufferAdvance (BitBuffer *bits, uint32_t numBits)
void BitBufferByteAlign (BitBuffer *bits, int32_t addZeros)
uint32_t BitBufferGetPosition (BitBuffer *bits)
void BitBufferInit (BitBuffer *bits, uint8_t *buffer, uint32_t byteSize)
uint32_t BitBufferPeek (BitBuffer *bits, uint8_t numBits)
uint32_t BitBufferPeekOne (BitBuffer *bits)
uint32_t BitBufferRead (BitBuffer *bits, uint8_t numBits)
uint8_t BitBufferReadOne (BitBuffer *bits)
uint8_t BitBufferReadSmall (BitBuffer *bits, uint8_t numBits)
void BitBufferReset (BitBuffer *bits)
void BitBufferRewind (BitBuffer *bits, uint32_t numBits)
uint32_t BitBufferUnpackBERSize (BitBuffer *bits)
void BitBufferWrite (BitBuffer *bits, uint32_t value, uint32_t numBits)
Macro Definition Documentation
MIN
#define MIN (x, y) ((x) < (y) ? (x) : (y))
Referenced by BitBufferWrite().
MAX
#define MAX (x, y) ((x) > (y) ? (x) : (y))
Referenced by alac_encode().
RequireAction
#define RequireAction (condition, action) if (! (condition)) { action }
Referenced by alac_data_stream_element(), alac_decode(), alac_decoder_init(), alac_encode(), alac_fill_element(), BitBufferWrite(), dyn_comp(), dyn_decomp(), EncodeMono(), EncodeStereo(), and EncodeStereoFast().
RequireActionSilent
#define RequireActionSilent (condition, action) if (! (condition)) { action }
Referenced by BitBufferWrite().
RequireNoErr
#define RequireNoErr (condition, action) if (condition) { action }
Referenced by alac_decode(), alac_encode(), EncodeMono(), EncodeStereo(), and EncodeStereoFast().
Typedef Documentation
BitBuffer
typedef struct BitBuffer BitBuffer
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ALAC_noErr
ELEMENT_TYPE
enum ELEMENT_TYPE
Enumerator
ID_SCE
ID_CPE
ID_CCE
ID_LFE
ID_DSE
ID_PCE
ID_FIL
ID_END
Function Documentation
BitBufferInit()
void BitBufferInit (BitBuffer * bits, uint8_t * buffer, uint32_t byteSize)
References BitBuffer::bitIndex, BitBuffer::byteSize, BitBuffer::cur, and BitBuffer::end.
Referenced by alac_decode_block(), alac_encode(), EncodeMono(), and EncodeStereo().
BitBufferRead()
uint32_t BitBufferRead (BitBuffer * bits, uint8_t numBits)
References BitBuffer::bitIndex, and BitBuffer::cur.
Referenced by alac_decode().
BitBufferReadSmall()
uint8_t BitBufferReadSmall (BitBuffer * bits, uint8_t numBits)
References BitBuffer::bitIndex, and BitBuffer::cur.
Referenced by alac_data_stream_element(), alac_decode(), alac_fill_element(), and BitBufferUnpackBERSize().
BitBufferReadOne()
uint8_t BitBufferReadOne (BitBuffer * bits)
References BitBuffer::bitIndex, and BitBuffer::cur.
Referenced by alac_data_stream_element().
BitBufferPeek()
uint32_t BitBufferPeek (BitBuffer * bits, uint8_t numBits)
References BitBuffer::bitIndex, and BitBuffer::cur.
BitBufferPeekOne()
uint32_t BitBufferPeekOne (BitBuffer * bits)
References BitBuffer::bitIndex, and BitBuffer::cur.
BitBufferUnpackBERSize()
uint32_t BitBufferUnpackBERSize (BitBuffer * bits)
References BitBufferReadSmall().
BitBufferGetPosition()
uint32_t BitBufferGetPosition (BitBuffer * bits)
References BitBuffer::bitIndex, BitBuffer::byteSize, BitBuffer::cur, and BitBuffer::end.
Referenced by alac_encode(), EncodeMono(), EncodeStereo(), and EncodeStereoFast().
BitBufferByteAlign()
void BitBufferByteAlign (BitBuffer * bits, int32_t addZeros)
References BitBufferAdvance(), BitBufferWrite(), and BitBuffer::bitIndex.
Referenced by alac_data_stream_element(), alac_decode(), and alac_encode().
BitBufferAdvance()
void BitBufferAdvance (BitBuffer * bits, uint32_t numBits)
References BitBuffer::bitIndex, and BitBuffer::cur.
Referenced by alac_data_stream_element(), alac_decode(), alac_fill_element(), BitBufferByteAlign(), dyn_comp(), and dyn_decomp().
BitBufferRewind()
void BitBufferRewind (BitBuffer * bits, uint32_t numBits)
References BitBuffer::bitIndex, BitBuffer::byteSize, BitBuffer::cur, and BitBuffer::end.
BitBufferWrite()
void BitBufferWrite (BitBuffer * bits, uint32_t value, uint32_t numBits)
References BitBuffer::bitIndex, BitBuffer::cur, MIN, NULL, RequireAction, and RequireActionSilent.
Referenced by alac_encode(), BitBufferByteAlign(), EncodeMono(), EncodeStereo(), EncodeStereoEscape(), and EncodeStereoFast().
BitBufferReset()
void BitBufferReset (BitBuffer * bits)
References BitBuffer::bitIndex, BitBuffer::byteSize, BitBuffer::cur, and BitBuffer::end.