Aurora Framework: alaw.c File Reference
alaw.c File Reference
Functions
static void alaw2d_array (unsigned char *buffer, int count, double *ptr, double normfact)
static void alaw2f_array (unsigned char *buffer, int count, float *ptr, float normfact)
static void alaw2i_array (unsigned char *buffer, int count, int *ptr)
static void alaw2s_array (unsigned char *buffer, int count, short *ptr)
int alaw_init (SF_PRIVATE *psf)
static sf_count_t alaw_read_alaw2d (SF_PRIVATE *psf, double *ptr, sf_count_t len)
static sf_count_t alaw_read_alaw2f (SF_PRIVATE *psf, float *ptr, sf_count_t len)
static sf_count_t alaw_read_alaw2i (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static sf_count_t alaw_read_alaw2s (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static sf_count_t alaw_write_d2alaw (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
static sf_count_t alaw_write_f2alaw (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
static sf_count_t alaw_write_i2alaw (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
static sf_count_t alaw_write_s2alaw (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
static void d2alaw_array (const double *buffer, int count, unsigned char *ptr, double normfact)
static void f2alaw_array (const float *buffer, int count, unsigned char *ptr, float normfact)
static void i2alaw_array (const int *buffer, int count, unsigned char *ptr)
static void s2alaw_array (const short *buffer, int count, unsigned char *ptr)
Variables
static short alaw_decode [256]
static unsigned char alaw_encode [2048+1]
Function Documentation
alaw_read_alaw2s()
static sf_count_t alaw_read_alaw2s (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
References alaw2s_array(), ARRAY_LEN, psf_fread(), and BUF_UNION::ucbuf.
Referenced by alaw_init().
alaw_read_alaw2i()
static sf_count_t alaw_read_alaw2i (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
References alaw2i_array(), ARRAY_LEN, psf_fread(), and BUF_UNION::ucbuf.
Referenced by alaw_init().
alaw_read_alaw2f()
static sf_count_t alaw_read_alaw2f (SF_PRIVATE * psf, float * ptr, sf_count_t len) static
References alaw2f_array(), ARRAY_LEN, sf_private_tag::norm_float, psf_fread(), and BUF_UNION::ucbuf.
Referenced by alaw_init().
alaw_read_alaw2d()
static sf_count_t alaw_read_alaw2d (SF_PRIVATE * psf, double * ptr, sf_count_t len) static
References alaw2d_array(), ARRAY_LEN, sf_private_tag::norm_double, psf_fread(), and BUF_UNION::ucbuf.
Referenced by alaw_init().
alaw_write_s2alaw()
static sf_count_t alaw_write_s2alaw (SF_PRIVATE * psf, const short * ptr, sf_count_t len) static
References ARRAY_LEN, psf_fwrite(), s2alaw_array(), and BUF_UNION::ucbuf.
Referenced by alaw_init().
alaw_write_i2alaw()
static sf_count_t alaw_write_i2alaw (SF_PRIVATE * psf, const int * ptr, sf_count_t len) static
References ARRAY_LEN, i2alaw_array(), psf_fwrite(), and BUF_UNION::ucbuf.
Referenced by alaw_init().
alaw_write_f2alaw()
static sf_count_t alaw_write_f2alaw (SF_PRIVATE * psf, const float * ptr, sf_count_t len) static
References ARRAY_LEN, f2alaw_array(), sf_private_tag::norm_float, psf_fwrite(), and BUF_UNION::ucbuf.
Referenced by alaw_init().
alaw_write_d2alaw()
static sf_count_t alaw_write_d2alaw (SF_PRIVATE * psf, const double * ptr, sf_count_t len) static
References ARRAY_LEN, d2alaw_array(), sf_private_tag::norm_double, psf_fwrite(), and BUF_UNION::ucbuf.
Referenced by alaw_init().
alaw2s_array()
static void alaw2s_array (unsigned char * buffer, int count, short * ptr) inline static
References alaw_decode.
Referenced by alaw_read_alaw2s().
alaw2i_array()
static void alaw2i_array (unsigned char * buffer, int count, int * ptr) inline static
References alaw_decode.
Referenced by alaw_read_alaw2i().
alaw2f_array()
static void alaw2f_array (unsigned char * buffer, int count, float * ptr, float normfact) inline static
References alaw_decode.
Referenced by alaw_read_alaw2f().
alaw2d_array()
static void alaw2d_array (unsigned char * buffer, int count, double * ptr, double normfact) inline static
References alaw_decode.
Referenced by alaw_read_alaw2d().
s2alaw_array()
static void s2alaw_array (const short * buffer, int count, unsigned char * ptr) inline static
References alaw_encode.
Referenced by alaw_write_s2alaw().
i2alaw_array()
static void i2alaw_array (const int * buffer, int count, unsigned char * ptr) inline static
References alaw_encode.
Referenced by alaw_write_i2alaw().
f2alaw_array()
static void f2alaw_array (const float * buffer, int count, unsigned char * ptr, float normfact) inline static
References alaw_encode.
Referenced by alaw_write_f2alaw().
d2alaw_array()
static void d2alaw_array (const double * buffer, int count, unsigned char * ptr, double normfact) inline static
References alaw_encode.
Referenced by alaw_write_d2alaw().
alaw_init()
int alaw_init (SF_PRIVATE * psf)
References alaw_read_alaw2d(), alaw_read_alaw2f(), alaw_read_alaw2i(), alaw_read_alaw2s(), alaw_write_d2alaw(), alaw_write_f2alaw(), alaw_write_i2alaw(), alaw_write_s2alaw(), sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::file, sf_private_tag::filelength, PSF_FILE::mode, sf_private_tag::read_double, sf_private_tag::read_float, sf_private_tag::read_int, sf_private_tag::read_short, sf_private_tag::sf, sf_private_tag::write_double, sf_private_tag::write_float, sf_private_tag::write_int, and sf_private_tag::write_short.
Referenced by aiff_open(), au_open(), caf_open(), ircam_open(), nist_open(), raw_open(), rf64_open(), voc_open(), w64_open(), wav_open(), and wve_open().
Variable Documentation
alaw_decode
short alaw_decode[256] static
Referenced by alaw2d_array(), alaw2f_array(), alaw2i_array(), and alaw2s_array().
alaw_encode
unsigned char alaw_encode[2048+1] static
Referenced by d2alaw_array(), f2alaw_array(), i2alaw_array(), and s2alaw_array().