Aurora Framework: Platform.h File Reference
X11/Platform.h File Reference
Classes
struct _GLFWcursorX11
struct _GLFWlibraryX11
struct _GLFWmonitorX11
struct _GLFWwindowX11
struct VkXcbSurfaceCreateInfoKHR
struct VkXlibSurfaceCreateInfoKHR
Macros
#define _glfw_dlclose(handle) dlclose(handle)
#define _glfw_dlopen(name) dlopen(name, RTLD_LAZY | RTLD_LOCAL)
#define _glfw_dlsym(handle, name) dlsym(handle, name)
#define _GLFW_EGL_NATIVE_DISPLAY ((EGLNativeDisplayType) _glfw.x11.display)
#define _GLFW_EGL_NATIVE_WINDOW ((EGLNativeWindowType) window->x11.handle)
#define _GLFW_PLATFORM_CURSOR_STATE _GLFWcursorX11 x11
#define _GLFW_PLATFORM_LIBRARY_WINDOW_STATE _GLFWlibraryX11 x11
#define _GLFW_PLATFORM_MONITOR_STATE _GLFWmonitorX11 x11
#define _GLFW_PLATFORM_WINDOW_STATE _GLFWwindowX11 x11
#define XcursorImageCreate _glfw.x11.xcursor.ImageCreate
#define XcursorImageDestroy _glfw.x11.xcursor.ImageDestroy
#define XcursorImageLoadCursor _glfw.x11.xcursor.ImageLoadCursor
#define XF86VidModeGetGammaRamp _glfw.x11.vidmode.GetGammaRamp
#define XF86VidModeGetGammaRampSize _glfw.x11.vidmode.GetGammaRampSize
#define XF86VidModeQueryExtension _glfw.x11.vidmode.QueryExtension
#define XF86VidModeSetGammaRamp _glfw.x11.vidmode.SetGammaRamp
#define XGetXCBConnection _glfw.x11.x11xcb.GetXCBConnection
#define XineramaIsActive _glfw.x11.xinerama.IsActive
#define XineramaQueryExtension _glfw.x11.xinerama.QueryExtension
#define XineramaQueryScreens _glfw.x11.xinerama.QueryScreens
#define XIQueryVersion _glfw.x11.xi.QueryVersion
#define XISelectEvents _glfw.x11.xi.SelectEvents
#define XRenderFindVisualFormat _glfw.x11.xrender.FindVisualFormat
#define XRenderQueryExtension _glfw.x11.xrender.QueryExtension
#define XRenderQueryVersion _glfw.x11.xrender.QueryVersion
#define XRRAllocGamma _glfw.x11.randr.AllocGamma
#define XRRFreeCrtcInfo _glfw.x11.randr.FreeCrtcInfo
#define XRRFreeGamma _glfw.x11.randr.FreeGamma
#define XRRFreeOutputInfo _glfw.x11.randr.FreeOutputInfo
#define XRRFreeScreenResources _glfw.x11.randr.FreeScreenResources
#define XRRGetCrtcGamma _glfw.x11.randr.GetCrtcGamma
#define XRRGetCrtcGammaSize _glfw.x11.randr.GetCrtcGammaSize
#define XRRGetCrtcInfo _glfw.x11.randr.GetCrtcInfo
#define XRRGetOutputInfo _glfw.x11.randr.GetOutputInfo
#define XRRGetOutputPrimary _glfw.x11.randr.GetOutputPrimary
#define XRRGetScreenResourcesCurrent _glfw.x11.randr.GetScreenResourcesCurrent
#define XRRQueryExtension _glfw.x11.randr.QueryExtension
#define XRRQueryVersion _glfw.x11.randr.QueryVersion
#define XRRSelectInput _glfw.x11.randr.SelectInput
#define XRRSetCrtcConfig _glfw.x11.randr.SetCrtcConfig
#define XRRSetCrtcGamma _glfw.x11.randr.SetCrtcGamma
#define XRRUpdateConfiguration _glfw.x11.randr.UpdateConfiguration
Typedefs
typedef struct _GLFWcursorX11 _GLFWcursorX11
typedef struct _GLFWlibraryX11 _GLFWlibraryX11
typedef struct _GLFWmonitorX11 _GLFWmonitorX11
typedef struct _GLFWwindowX11 _GLFWwindowX11
typedef VkResult(APIENTRY * PFN_vkCreateXcbSurfaceKHR) (VkInstance, const VkXcbSurfaceCreateInfoKHR *, const VkAllocationCallbacks *, VkSurfaceKHR *)
typedef VkResult(APIENTRY * PFN_vkCreateXlibSurfaceKHR) (VkInstance, const VkXlibSurfaceCreateInfoKHR *, const VkAllocationCallbacks *, VkSurfaceKHR *)
typedef VkBool32(APIENTRY * PFN_vkGetPhysicalDeviceXcbPresentationSupportKHR) (VkPhysicalDevice, uint32_t, xcb_connection_t *, xcb_visualid_t)
typedef VkBool32(APIENTRY * PFN_vkGetPhysicalDeviceXlibPresentationSupportKHR) (VkPhysicalDevice, uint32_t, Display *, VisualID)
typedef XcursorImage *(* PFN_XcursorImageCreate) (int, int)
typedef void(* PFN_XcursorImageDestroy) (XcursorImage *)
typedef Cursor(* PFN_XcursorImageLoadCursor) (Display *, const XcursorImage *)
typedef Bool(* PFN_XF86VidModeGetGammaRamp) (Display *, int, int, unsigned short *, unsigned short *, unsigned short *)
typedef Bool(* PFN_XF86VidModeGetGammaRampSize) (Display *, int, int *)
typedef Bool(* PFN_XF86VidModeQueryExtension) (Display *, int *, int *)
typedef Bool(* PFN_XF86VidModeSetGammaRamp) (Display *, int, int, unsigned short *, unsigned short *, unsigned short *)
typedef xcb_connection_t *(* PFN_XGetXCBConnection) (Display *)
typedef Bool(* PFN_XineramaIsActive) (Display *)
typedef Bool(* PFN_XineramaQueryExtension) (Display *, int *, int *)
typedef XineramaScreenInfo *(* PFN_XineramaQueryScreens) (Display *, int *)
typedef Status(* PFN_XIQueryVersion) (Display *, int *, int *)
typedef int(* PFN_XISelectEvents) (Display *, Window, XIEventMask *, int)
typedef XRenderPictFormat *(* PFN_XRenderFindVisualFormat) (Display *, Visual const *)
typedef Bool(* PFN_XRenderQueryExtension) (Display *, int *, int *)
typedef Status(* PFN_XRenderQueryVersion) (Display *dpy, int *, int *)
typedef XRRCrtcGamma *(* PFN_XRRAllocGamma) (int)
typedef void(* PFN_XRRFreeCrtcInfo) (XRRCrtcInfo *)
typedef void(* PFN_XRRFreeGamma) (XRRCrtcGamma *)
typedef void(* PFN_XRRFreeOutputInfo) (XRROutputInfo *)
typedef void(* PFN_XRRFreeScreenResources) (XRRScreenResources *)
typedef XRRCrtcGamma *(* PFN_XRRGetCrtcGamma) (Display *, RRCrtc)
typedef int(* PFN_XRRGetCrtcGammaSize) (Display *, RRCrtc)
typedef XRRCrtcInfo *(* PFN_XRRGetCrtcInfo) (Display *, XRRScreenResources *, RRCrtc)
typedef XRROutputInfo *(* PFN_XRRGetOutputInfo) (Display *, XRRScreenResources *, RROutput)
typedef RROutput(* PFN_XRRGetOutputPrimary) (Display *, Window)
typedef XRRScreenResources *(* PFN_XRRGetScreenResourcesCurrent) (Display *, Window)
typedef Bool(* PFN_XRRQueryExtension) (Display *, int *, int *)
typedef Status(* PFN_XRRQueryVersion) (Display *, int *, int *)
typedef void(* PFN_XRRSelectInput) (Display *, Window, int)
typedef Status(* PFN_XRRSetCrtcConfig) (Display *, XRRScreenResources *, RRCrtc, Time, int, int, RRMode, Rotation, RROutput *, int)
typedef void(* PFN_XRRSetCrtcGamma) (Display *, RRCrtc, XRRCrtcGamma *)
typedef int(* PFN_XRRUpdateConfiguration) (XEvent *)
typedef VkFlags VkXcbSurfaceCreateFlagsKHR
typedef struct VkXcbSurfaceCreateInfoKHR VkXcbSurfaceCreateInfoKHR
typedef VkFlags VkXlibSurfaceCreateFlagsKHR
typedef struct VkXlibSurfaceCreateInfoKHR VkXlibSurfaceCreateInfoKHR
typedef struct xcb_connection_t xcb_connection_t
typedef XID xcb_visualid_t
typedef XID xcb_window_t
Functions
Cursor _glfwCreateCursorX11 (const GLFWimage *image, int xhot, int yhot)
unsigned long _glfwGetWindowPropertyX11 (Window window, Atom property, Atom type, unsigned char **value)
void _glfwGrabErrorHandlerX11 (void)
void _glfwInputErrorX11 (int error, const char *message)
GLFWbool _glfwIsVisualTransparentX11 (Visual *visual)
void _glfwPollMonitorsX11 (void)
void _glfwPushSelectionToManagerX11 (void)
void _glfwReleaseErrorHandlerX11 (void)
void _glfwRestoreVideoModeX11 (_GLFWmonitor *monitor)
void _glfwSetVideoModeX11 (_GLFWmonitor *monitor, const GLFWvidmode *desired)
Macro Definition Documentation
XRRAllocGamma
#define XRRAllocGamma _glfw.x11.randr.AllocGamma
Referenced by _glfwPlatformSetGammaRamp().
XRRFreeCrtcInfo
#define XRRFreeCrtcInfo _glfw.x11.randr.FreeCrtcInfo
Referenced by _glfwPlatformGetMonitorPos(), _glfwPlatformGetVideoMode(), _glfwPlatformGetVideoModes(), _glfwPollMonitorsX11(), _glfwRestoreVideoModeX11(), and _glfwSetVideoModeX11().
XRRFreeGamma
#define XRRFreeGamma _glfw.x11.randr.FreeGamma
Referenced by _glfwPlatformGetGammaRamp(), and _glfwPlatformSetGammaRamp().
XRRFreeOutputInfo
#define XRRFreeOutputInfo _glfw.x11.randr.FreeOutputInfo
Referenced by _glfwPlatformGetVideoModes(), _glfwPollMonitorsX11(), and _glfwSetVideoModeX11().
XRRFreeScreenResources
#define XRRFreeScreenResources _glfw.x11.randr.FreeScreenResources
Referenced by _glfwPlatformGetMonitorPos(), _glfwPlatformGetVideoMode(), _glfwPlatformGetVideoModes(), _glfwPollMonitorsX11(), _glfwRestoreVideoModeX11(), _glfwSetVideoModeX11(), and initExtensions().
XRRGetCrtcGamma
#define XRRGetCrtcGamma _glfw.x11.randr.GetCrtcGamma
Referenced by _glfwPlatformGetGammaRamp().
XRRGetCrtcGammaSize
#define XRRGetCrtcGammaSize _glfw.x11.randr.GetCrtcGammaSize
Referenced by _glfwPlatformGetGammaRamp(), _glfwPlatformSetGammaRamp(), and initExtensions().
XRRGetCrtcInfo
#define XRRGetCrtcInfo _glfw.x11.randr.GetCrtcInfo
Referenced by _glfwPlatformGetMonitorPos(), _glfwPlatformGetVideoMode(), _glfwPlatformGetVideoModes(), _glfwPollMonitorsX11(), _glfwRestoreVideoModeX11(), and _glfwSetVideoModeX11().
XRRGetOutputInfo
#define XRRGetOutputInfo _glfw.x11.randr.GetOutputInfo
Referenced by _glfwPlatformGetVideoModes(), _glfwPollMonitorsX11(), and _glfwSetVideoModeX11().
XRRGetOutputPrimary
#define XRRGetOutputPrimary _glfw.x11.randr.GetOutputPrimary
Referenced by _glfwPollMonitorsX11().
XRRGetScreenResourcesCurrent
#define XRRGetScreenResourcesCurrent _glfw.x11.randr.GetScreenResourcesCurrent
Referenced by _glfwPlatformGetMonitorPos(), _glfwPlatformGetVideoMode(), _glfwPlatformGetVideoModes(), _glfwPollMonitorsX11(), _glfwRestoreVideoModeX11(), _glfwSetVideoModeX11(), and initExtensions().
XRRQueryExtension
#define XRRQueryExtension _glfw.x11.randr.QueryExtension
Referenced by initExtensions().
XRRQueryVersion
#define XRRQueryVersion _glfw.x11.randr.QueryVersion
Referenced by initExtensions().
XRRSelectInput
#define XRRSelectInput _glfw.x11.randr.SelectInput
Referenced by initExtensions().
XRRSetCrtcConfig
#define XRRSetCrtcConfig _glfw.x11.randr.SetCrtcConfig
Referenced by _glfwRestoreVideoModeX11(), and _glfwSetVideoModeX11().
XRRSetCrtcGamma
#define XRRSetCrtcGamma _glfw.x11.randr.SetCrtcGamma
Referenced by _glfwPlatformSetGammaRamp().
XRRUpdateConfiguration
#define XRRUpdateConfiguration _glfw.x11.randr.UpdateConfiguration
Referenced by processEvent().
XcursorImageCreate
#define XcursorImageCreate _glfw.x11.xcursor.ImageCreate
Referenced by _glfwCreateCursorX11().
XcursorImageDestroy
#define XcursorImageDestroy _glfw.x11.xcursor.ImageDestroy
Referenced by _glfwCreateCursorX11().
XcursorImageLoadCursor
#define XcursorImageLoadCursor _glfw.x11.xcursor.ImageLoadCursor
Referenced by _glfwCreateCursorX11().
XineramaIsActive
#define XineramaIsActive _glfw.x11.xinerama.IsActive
Referenced by initExtensions().
XineramaQueryExtension
#define XineramaQueryExtension _glfw.x11.xinerama.QueryExtension
Referenced by initExtensions().
XineramaQueryScreens
#define XineramaQueryScreens _glfw.x11.xinerama.QueryScreens
Referenced by _glfwPollMonitorsX11().
XGetXCBConnection
#define XGetXCBConnection _glfw.x11.x11xcb.GetXCBConnection
Referenced by _glfwPlatformCreateWindowSurface(), and _glfwPlatformGetPhysicalDevicePresentationSupport().
XF86VidModeQueryExtension
#define XF86VidModeQueryExtension _glfw.x11.vidmode.QueryExtension
Referenced by initExtensions().
XF86VidModeGetGammaRamp
#define XF86VidModeGetGammaRamp _glfw.x11.vidmode.GetGammaRamp
Referenced by _glfwPlatformGetGammaRamp().
XF86VidModeSetGammaRamp
#define XF86VidModeSetGammaRamp _glfw.x11.vidmode.SetGammaRamp
Referenced by _glfwPlatformSetGammaRamp().
XF86VidModeGetGammaRampSize
#define XF86VidModeGetGammaRampSize _glfw.x11.vidmode.GetGammaRampSize
Referenced by _glfwPlatformGetGammaRamp().
XIQueryVersion
#define XIQueryVersion _glfw.x11.xi.QueryVersion
Referenced by initExtensions().
XISelectEvents
#define XISelectEvents _glfw.x11.xi.SelectEvents
Referenced by _glfwPlatformSetCursorMode().
XRenderQueryExtension
#define XRenderQueryExtension _glfw.x11.xrender.QueryExtension
Referenced by initExtensions().
XRenderQueryVersion
#define XRenderQueryVersion _glfw.x11.xrender.QueryVersion
Referenced by initExtensions().
XRenderFindVisualFormat
#define XRenderFindVisualFormat _glfw.x11.xrender.FindVisualFormat
Referenced by _glfwIsVisualTransparentX11().
_glfw_dlopen
#define _glfw_dlopen (name) dlopen(name, RTLD_LAZY | RTLD_LOCAL)
_glfw_dlclose
#define _glfw_dlclose (handle) dlclose(handle)
_glfw_dlsym
#define _glfw_dlsym (handle, name) dlsym(handle, name)
_GLFW_EGL_NATIVE_WINDOW
#define _GLFW_EGL_NATIVE_WINDOW ((EGLNativeWindowType) window->x11.handle)
_GLFW_EGL_NATIVE_DISPLAY
#define _GLFW_EGL_NATIVE_DISPLAY ((EGLNativeDisplayType) _glfw.x11.display)
_GLFW_PLATFORM_WINDOW_STATE
#define _GLFW_PLATFORM_WINDOW_STATE _GLFWwindowX11 x11
_GLFW_PLATFORM_LIBRARY_WINDOW_STATE
#define _GLFW_PLATFORM_LIBRARY_WINDOW_STATE _GLFWlibraryX11 x11
_GLFW_PLATFORM_MONITOR_STATE
#define _GLFW_PLATFORM_MONITOR_STATE _GLFWmonitorX11 x11
_GLFW_PLATFORM_CURSOR_STATE
#define _GLFW_PLATFORM_CURSOR_STATE _GLFWcursorX11 x11
Typedef Documentation
PFN_XRRAllocGamma
typedef XRRCrtcGamma*(* PFN_XRRAllocGamma) (int)
PFN_XRRFreeCrtcInfo
typedef void(* PFN_XRRFreeCrtcInfo) (XRRCrtcInfo *)
PFN_XRRFreeGamma
typedef void(* PFN_XRRFreeGamma) (XRRCrtcGamma *)
PFN_XRRFreeOutputInfo
typedef void(* PFN_XRRFreeOutputInfo) (XRROutputInfo *)
PFN_XRRFreeScreenResources
typedef void(* PFN_XRRFreeScreenResources) (XRRScreenResources *)
PFN_XRRGetCrtcGamma
typedef XRRCrtcGamma*(* PFN_XRRGetCrtcGamma) (Display *, RRCrtc)
PFN_XRRGetCrtcGammaSize
typedef int(* PFN_XRRGetCrtcGammaSize) (Display *, RRCrtc)
PFN_XRRGetCrtcInfo
typedef XRRCrtcInfo*(* PFN_XRRGetCrtcInfo) (Display *, XRRScreenResources *, RRCrtc)
PFN_XRRGetOutputInfo
typedef XRROutputInfo*(* PFN_XRRGetOutputInfo) (Display *, XRRScreenResources *, RROutput)
PFN_XRRGetOutputPrimary
typedef RROutput(* PFN_XRRGetOutputPrimary) (Display *, Window)
PFN_XRRGetScreenResourcesCurrent
typedef XRRScreenResources*(* PFN_XRRGetScreenResourcesCurrent) (Display *, Window)
PFN_XRRQueryExtension
typedef Bool(* PFN_XRRQueryExtension) (Display *, int *, int *)
PFN_XRRQueryVersion
typedef Status(* PFN_XRRQueryVersion) (Display *, int *, int *)
PFN_XRRSelectInput
typedef void(* PFN_XRRSelectInput) (Display *, Window, int)
PFN_XRRSetCrtcConfig
typedef Status(* PFN_XRRSetCrtcConfig) (Display *, XRRScreenResources *, RRCrtc, Time, int, int, RRMode, Rotation, RROutput *, int)
PFN_XRRSetCrtcGamma
typedef void(* PFN_XRRSetCrtcGamma) (Display *, RRCrtc, XRRCrtcGamma *)
PFN_XRRUpdateConfiguration
typedef int(* PFN_XRRUpdateConfiguration) (XEvent *)
PFN_XcursorImageCreate
typedef XcursorImage*(* PFN_XcursorImageCreate) (int, int)
PFN_XcursorImageDestroy
typedef void(* PFN_XcursorImageDestroy) (XcursorImage *)
PFN_XcursorImageLoadCursor
typedef Cursor(* PFN_XcursorImageLoadCursor) (Display *, const XcursorImage *)
PFN_XineramaIsActive
typedef Bool(* PFN_XineramaIsActive) (Display *)
PFN_XineramaQueryExtension
typedef Bool(* PFN_XineramaQueryExtension) (Display *, int *, int *)
PFN_XineramaQueryScreens
typedef XineramaScreenInfo*(* PFN_XineramaQueryScreens) (Display *, int *)
xcb_window_t
typedef XID xcb_window_t
xcb_visualid_t
typedef XID xcb_visualid_t
xcb_connection_t
typedef struct xcb_connection_t xcb_connection_t
PFN_XGetXCBConnection
typedef xcb_connection_t*(* PFN_XGetXCBConnection) (Display *)
PFN_XF86VidModeQueryExtension
typedef Bool(* PFN_XF86VidModeQueryExtension) (Display *, int *, int *)
PFN_XF86VidModeGetGammaRamp
typedef Bool(* PFN_XF86VidModeGetGammaRamp) (Display *, int, int, unsigned short *, unsigned short *, unsigned short *)
PFN_XF86VidModeSetGammaRamp
typedef Bool(* PFN_XF86VidModeSetGammaRamp) (Display *, int, int, unsigned short *, unsigned short *, unsigned short *)
PFN_XF86VidModeGetGammaRampSize
typedef Bool(* PFN_XF86VidModeGetGammaRampSize) (Display *, int, int *)
PFN_XIQueryVersion
typedef Status(* PFN_XIQueryVersion) (Display *, int *, int *)
PFN_XISelectEvents
typedef int(* PFN_XISelectEvents) (Display *, Window, XIEventMask *, int)
PFN_XRenderQueryExtension
typedef Bool(* PFN_XRenderQueryExtension) (Display *, int *, int *)
PFN_XRenderQueryVersion
typedef Status(* PFN_XRenderQueryVersion) (Display *dpy, int *, int *)
PFN_XRenderFindVisualFormat
typedef XRenderPictFormat*(* PFN_XRenderFindVisualFormat) (Display *, Visual const *)
VkXlibSurfaceCreateFlagsKHR
typedef VkFlags VkXlibSurfaceCreateFlagsKHR
VkXcbSurfaceCreateFlagsKHR
typedef VkFlags VkXcbSurfaceCreateFlagsKHR
VkXlibSurfaceCreateInfoKHR
typedef struct VkXlibSurfaceCreateInfoKHR VkXlibSurfaceCreateInfoKHR
VkXcbSurfaceCreateInfoKHR
typedef struct VkXcbSurfaceCreateInfoKHR VkXcbSurfaceCreateInfoKHR
PFN_vkCreateXlibSurfaceKHR
typedef VkResult(APIENTRY * PFN_vkCreateXlibSurfaceKHR) (VkInstance, const VkXlibSurfaceCreateInfoKHR *, const VkAllocationCallbacks *, VkSurfaceKHR *)
PFN_vkGetPhysicalDeviceXlibPresentationSupportKHR
typedef VkBool32(APIENTRY * PFN_vkGetPhysicalDeviceXlibPresentationSupportKHR) (VkPhysicalDevice, uint32_t, Display *, VisualID)
PFN_vkCreateXcbSurfaceKHR
typedef VkResult(APIENTRY * PFN_vkCreateXcbSurfaceKHR) (VkInstance, const VkXcbSurfaceCreateInfoKHR *, const VkAllocationCallbacks *, VkSurfaceKHR *)
PFN_vkGetPhysicalDeviceXcbPresentationSupportKHR
typedef VkBool32(APIENTRY * PFN_vkGetPhysicalDeviceXcbPresentationSupportKHR) (VkPhysicalDevice, uint32_t, xcb_connection_t *, xcb_visualid_t)
_GLFWwindowX11
typedef struct _GLFWwindowX11 _GLFWwindowX11
_GLFWlibraryX11
typedef struct _GLFWlibraryX11 _GLFWlibraryX11
_GLFWmonitorX11
typedef struct _GLFWmonitorX11 _GLFWmonitorX11
_GLFWcursorX11
typedef struct _GLFWcursorX11 _GLFWcursorX11
Function Documentation
_glfwPollMonitorsX11()
void _glfwPollMonitorsX11 (void)
References _glfw, _GLFW_INSERT_FIRST, _GLFW_INSERT_LAST, _glfwAllocMonitor(), _glfwInputMonitor(), _GLFWlibrary::available, GLFW_CONNECTED, GLFW_DISCONNECTED, memcpy(), _GLFWlibrary::monitorCount, _GLFWlibrary::monitors, AuroraFW::None, NULL, XineramaQueryScreens, XRRFreeCrtcInfo, XRRFreeOutputInfo, XRRFreeScreenResources, XRRGetCrtcInfo, XRRGetOutputInfo, XRRGetOutputPrimary, and XRRGetScreenResourcesCurrent.
Referenced by _glfwPlatformInit(), and processEvent().
_glfwSetVideoModeX11()
void _glfwSetVideoModeX11 (_GLFWmonitor * monitor, const GLFWvidmode * desired)
References _glfw, _glfwChooseVideoMode(), _glfwCompareVideoModes(), _glfwPlatformGetVideoMode(), _GLFWlibrary::available, getModeInfo(), mode(), modeIsGood(), AuroraFW::None, vidmodeFromModeInfo(), XRRFreeCrtcInfo, XRRFreeOutputInfo, XRRFreeScreenResources, XRRGetCrtcInfo, XRRGetOutputInfo, XRRGetScreenResourcesCurrent, and XRRSetCrtcConfig.
Referenced by acquireMonitor().
_glfwRestoreVideoModeX11()
void _glfwRestoreVideoModeX11 (_GLFWmonitor * monitor)
References _glfw, _GLFWlibrary::available, AuroraFW::None, XRRFreeCrtcInfo, XRRFreeScreenResources, XRRGetCrtcInfo, XRRGetScreenResourcesCurrent, and XRRSetCrtcConfig.
Referenced by releaseMonitor().
_glfwCreateCursorX11()
Cursor _glfwCreateCursorX11 (const GLFWimage * image, int xhot, int yhot)
References _glfw, _GLFWlibrary::handle, GLFWimage::height, AuroraFW::None, NULL, GLFWimage::pixels, source, GLFWimage::width, XcursorImageCreate, XcursorImageDestroy, and XcursorImageLoadCursor.
Referenced by _glfwPlatformCreateCursor(), and createHiddenCursor().
_glfwGetWindowPropertyX11()
unsigned long _glfwGetWindowPropertyX11 (Window window, Atom property, Atom type, unsigned char ** value)
References _glfw, and value.
Referenced by _glfwPlatformGetWindowFrameSize(), _glfwPlatformGetWindowOpacity(), _glfwPlatformSetWindowFloating(), _glfwPlatformWindowMaximized(), detectEWMH(), getWindowState(), processEvent(), and writeTargetToProperty().
_glfwIsVisualTransparentX11()
GLFWbool _glfwIsVisualTransparentX11 (Visual * visual)
References _glfw, _GLFWlibrary::available, GLFW_FALSE, and XRenderFindVisualFormat.
Referenced by chooseEGLConfig(), chooseGLXFBConfig(), and createNativeWindow().
_glfwGrabErrorHandlerX11()
void _glfwGrabErrorHandlerX11 (void)
References _glfw, and errorHandler().
Referenced by _glfwCreateContextGLX(), createNativeWindow(), and detectEWMH().
_glfwReleaseErrorHandlerX11()
void _glfwReleaseErrorHandlerX11 (void)
References _glfw, and NULL.
Referenced by _glfwCreateContextGLX(), createNativeWindow(), and detectEWMH().
_glfwInputErrorX11()
void _glfwInputErrorX11 (int error, const char * message)
References _glfw, _GLFW_MESSAGE_SIZE, and _glfwInputError().
Referenced by _glfwCreateContextGLX(), and createNativeWindow().
_glfwPushSelectionToManagerX11()
void _glfwPushSelectionToManagerX11 (void)
References _glfw, handleSelectionClear(), handleSelectionRequest(), isSelectionEvent(), AuroraFW::None, NULL, and waitForEvent().
Referenced by _glfwPlatformTerminate().