Aurora Framework: spirv_cross::Compiler::BufferAccessHandler Struct Reference
spirv_cross::Compiler::BufferAccessHandler Struct Reference
Public Member Functions
BufferAccessHandler (const Compiler &compiler_, std::vector< BufferRange > &ranges_, uint32_t id_)
virtual bool begin_function_scope (const uint32_t *, uint32_t)
virtual bool end_function_scope (const uint32_t *, uint32_t)
virtual bool follow_function_call (const SPIRFunction &)
bool handle (spv::Op opcode, const uint32_t *args, uint32_t length) override
virtual void set_current_block (const SPIRBlock &)
Public Attributes
const Compiler & compiler
uint32_t id
std::vector< BufferRange > & ranges
std::unordered_set< uint32_t > seen
Constructor & Destructor Documentation
BufferAccessHandler()
spirv_cross::Compiler::BufferAccessHandler::BufferAccessHandler (const Compiler & compiler_, std::vector< BufferRange > & ranges_, uint32_t id_) inline
Member Function Documentation
handle()
bool Compiler::BufferAccessHandler::handle (spv::Op opcode, const uint32_t * args, uint32_t length) override virtual
Implements spirv_cross::Compiler::OpcodeHandler.
References spv::OpAccessChain, and spv::OpInBoundsAccessChain.
follow_function_call()
virtual bool spirv_cross::Compiler::OpcodeHandler::follow_function_call (const SPIRFunction &) inline virtual inherited
Referenced by spirv_cross::Compiler::traverse_all_reachable_opcodes().
set_current_block()
virtual void spirv_cross::Compiler::OpcodeHandler::set_current_block (const SPIRBlock &) inline virtual inherited
Referenced by spirv_cross::Compiler::traverse_all_reachable_opcodes().
begin_function_scope()
virtual bool spirv_cross::Compiler::OpcodeHandler::begin_function_scope (const uint32_t * , uint32_t) inline virtual inherited
Reimplemented in spirv_cross::Compiler::CombinedImageSamplerUsageHandler, and spirv_cross::Compiler::CombinedImageSamplerHandler.
Referenced by spirv_cross::Compiler::traverse_all_reachable_opcodes().
end_function_scope()
virtual bool spirv_cross::Compiler::OpcodeHandler::end_function_scope (const uint32_t * , uint32_t) inline virtual inherited
Reimplemented in spirv_cross::Compiler::CombinedImageSamplerHandler.
Referenced by spirv_cross::Compiler::traverse_all_reachable_opcodes().
Member Data Documentation
compiler
const Compiler& spirv_cross::Compiler::BufferAccessHandler::compiler
ranges
std::vector<BufferRange>& spirv_cross::Compiler::BufferAccessHandler::ranges
id
uint32_t spirv_cross::Compiler::BufferAccessHandler::id
seen
std::unordered_set<uint32_t> spirv_cross::Compiler::BufferAccessHandler::seen
The documentation for this struct was generated from the following files:
Cross.h
Cross.cpp