Aurora Framework: interleave.c File Reference
interleave.c File Reference
Classes
struct INTERLEAVE_DATA
Macros
#define INTERLEAVE_CHANNELS 6
Functions
int interleave_init (SF_PRIVATE *psf)
static sf_count_t interleave_read_double (SF_PRIVATE *psf, double *ptr, sf_count_t len)
static sf_count_t interleave_read_float (SF_PRIVATE *psf, float *ptr, sf_count_t len)
static sf_count_t interleave_read_int (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static sf_count_t interleave_read_short (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static sf_count_t interleave_seek (SF_PRIVATE *, int mode, sf_count_t samples_from_start)
static sf_count_t interleave_seek (SF_PRIVATE *UNUSED(psf), int UNUSED(mode), sf_count_t samples_from_start)
Macro Definition Documentation
INTERLEAVE_CHANNELS
#define INTERLEAVE_CHANNELS 6
Function Documentation
interleave_read_short()
static sf_count_t interleave_read_short (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
References INTERLEAVE_DATA::buffer, sf_private_tag::bytewidth, sf_private_tag::dataoffset, sf_private_tag::error, sf_private_tag::interleave, psf_fseek(), sf_private_tag::read_current, INTERLEAVE_DATA::read_short, sf_private_tag::sf, SFE_INTERLEAVE_READ, SFE_INTERLEAVE_SEEK, and SIGNED_SIZEOF.
Referenced by interleave_init().
interleave_read_int()
static sf_count_t interleave_read_int (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
References INTERLEAVE_DATA::buffer, sf_private_tag::bytewidth, sf_private_tag::dataoffset, sf_private_tag::error, sf_private_tag::interleave, psf_fseek(), sf_private_tag::read_current, INTERLEAVE_DATA::read_int, sf_private_tag::sf, SFE_INTERLEAVE_READ, SFE_INTERLEAVE_SEEK, and SIGNED_SIZEOF.
Referenced by interleave_init().
interleave_read_float()
static sf_count_t interleave_read_float (SF_PRIVATE * psf, float * ptr, sf_count_t len) static
References INTERLEAVE_DATA::buffer, sf_private_tag::bytewidth, INTERLEAVE_DATA::channel_len, sf_private_tag::dataoffset, sf_private_tag::error, sf_private_tag::interleave, psf_fseek(), sf_private_tag::read_current, INTERLEAVE_DATA::read_float, sf_private_tag::sf, SFE_INTERLEAVE_READ, SFE_INTERLEAVE_SEEK, and SIGNED_SIZEOF.
Referenced by interleave_init().
interleave_read_double()
static sf_count_t interleave_read_double (SF_PRIVATE * psf, double * ptr, sf_count_t len) static
References INTERLEAVE_DATA::buffer, sf_private_tag::bytewidth, sf_private_tag::dataoffset, sf_private_tag::error, sf_private_tag::interleave, psf_fseek(), sf_private_tag::read_current, INTERLEAVE_DATA::read_double, sf_private_tag::sf, SFE_INTERLEAVE_READ, SFE_INTERLEAVE_SEEK, and SIGNED_SIZEOF.
Referenced by interleave_init().
interleave_seek() [1/2]
static sf_count_t interleave_seek (SF_PRIVATE * , int mode, sf_count_t samples_from_start) static
Referenced by interleave_init().
interleave_init()
int interleave_init (SF_PRIVATE * psf)
References sf_private_tag::bytewidth, INTERLEAVE_DATA::channel_len, sf_private_tag::file, sf_private_tag::interleave, interleave_read_double(), interleave_read_float(), interleave_read_int(), interleave_read_short(), interleave_seek(), PSF_FILE::mode, psf_log_printf(), INTERLEAVE_DATA::read_double, sf_private_tag::read_double, INTERLEAVE_DATA::read_float, sf_private_tag::read_float, INTERLEAVE_DATA::read_int, sf_private_tag::read_int, INTERLEAVE_DATA::read_short, sf_private_tag::read_short, sf_private_tag::seek, sf_private_tag::sf, SFE_INTERLEAVE_MODE, and SFE_MALLOC_FAILED.
interleave_seek() [2/2]
static sf_count_t interleave_seek (SF_PRIVATE * UNUSEDpsf, int UNUSEDmode, sf_count_t samples_from_start) static