Aurora Framework: AuroraFW::GEngine::Window Class Reference
AuroraFW::GEngine::Window Class Reference
Public Member Functions
Window (std::string, const WindowProperties={})
Constructs a Window.
Window (const Window &)=delete
The copy constructor was deleted, since Window is not suitable to be copied.
~Window ()
Destructs the Window object.
bool getDoubleBuffer () const
bool getFloating () const
uint getHeight () const
Returns the height of the window.
bool getResizable () const
uint getWidth () const
Returns the width of the window.
bool isClosed () const
Returs whether the window is closed or not.
Window & operator= (const Window &)=delete
The copy assignment was deleted, since Window is not suitable to be copied.
void present ()
Swap buffers and present window stuff.
WindowProperties properties ()
void setDoubleBuffer (bool val)
void setFloating (bool val)
void setResizable (bool val)
bool setSamples (int s)
void update ()
Update the window events.
Protected Attributes
GLFWwindow * window
The GLFWwindow used to render.
WindowProperties wp
Constructor & Destructor Documentation
Window() [1/2]
AuroraFW::GEngine::Window::Window (std::string name, const WindowProperties wp = {})
Constructs a Window.
Parameters
gapp The Application connected to this window.
name The name of the window.
wp The WindowProperties desired.
See also
WindowProperties
~Window()
Since
snapshot20170930
References AuroraFW::GEngine::WindowProperties::autoIconify, AuroraFW::GEngine::WindowProperties::auxBuffers, AuroraFW::GEngine::API::Context::create(), AuroraFW::GEngine::WindowProperties::decorated, AuroraFW::GEngine::WindowProperties::doubleBuffer, AuroraFW::GEngine::WindowProperties::floating, AuroraFW::GEngine::WindowProperties::focused, AuroraFW::GEngine::WindowProperties::fullscreen, GLFW_AUTO_ICONIFY, GLFW_AUX_BUFFERS, GLFW_BLUE_BITS, GLFW_DECORATED, GLFW_DOUBLEBUFFER, GLFW_FLOATING, GLFW_FOCUSED, GLFW_GREEN_BITS, GLFW_MAXIMIZED, GLFW_RED_BITS, GLFW_REFRESH_RATE, GLFW_RESIZABLE, GLFW_SAMPLES, GLFW_SRGB_CAPABLE, GLFW_STEREO, GLFW_VISIBLE, glfwCreateWindow(), glfwDefaultWindowHints(), glfwGetPrimaryMonitor(), glfwGetVideoMode(), glfwInit(), glfwMakeContextCurrent(), glfwSetWindowMonitor(), glfwTerminate(), glfwWindowHint(), AuroraFW::GEngine::WindowProperties::height, AuroraFW::GEngine::API::Context::init(), AuroraFW::GEngine::WindowProperties::maximized, mode(), NULL, AuroraFW::GEngine::WindowProperties::refreshRate, AuroraFW::GEngine::WindowProperties::resizable, AuroraFW::GEngine::WindowProperties::samples, AuroraFW::GEngine::WindowProperties::sRGB, AuroraFW::GEngine::WindowProperties::stereo, AuroraFW::GEngine::WindowProperties::visible, AuroraFW::GEngine::WindowProperties::vsync, AuroraFW::GEngine::WindowProperties::width, window, AuroraFW::GEngine::WindowProperties::windowSettingsDialog, and wp.
~Window()
AuroraFW::GEngine::Window::~Window ()
Destructs the Window object.
See also
Window()
Since
snapshot20170930
References AuroraFW::GEngine::API::Context::destroy(), glfwDestroyWindow(), glfwTerminate(), and window.
Window() [2/2]
AuroraFW::GEngine::Window::Window (const Window &) delete
The copy constructor was deleted, since Window is not suitable to be copied.
Since
snapshot20170930
Member Function Documentation
operator=()
Window& AuroraFW::GEngine::Window::operator= (const Window &) delete
The copy assignment was deleted, since Window is not suitable to be copied.
Since
snapshot20170930
update()
void AuroraFW::GEngine::Window::update ()
Update the window events.
See also
clear()
Since
snapshot20170930
References glfwSwapBuffers(), glfwSwapInterval(), AuroraFW::GEngine::WindowProperties::swapBuffers, AuroraFW::GEngine::WindowProperties::vsync, window, and wp.
Referenced by AuroraFW::GEngine::GraphicsContext::renderLoop().
present()
void AuroraFW::GEngine::Window::present ()
Swap buffers and present window stuff.
See also
clear()
Since
snapshot20180303
References glfwGetFramebufferSize(), glfwPollEvents(), AuroraFW::GEngine::WindowProperties::height, AuroraFW::GEngine::WindowProperties::width, window, and wp.
Referenced by AuroraFW::GEngine::GraphicsContext::renderLoop().
isClosed()
bool AuroraFW::GEngine::Window::isClosed () const
Returs whether the window is closed or not.
Returns
true if the window was closed. false otherwise.
Since
snapshot20170930
References glfwWindowShouldClose(), and window.
Referenced by AuroraFW::GEngine::GraphicsContext::renderLoop().
getWidth()
uint AuroraFW::GEngine::Window::getWidth () const inline
Returns the width of the window.
Returns
Width of the window.
See also
getHeight()
Since
snapshot20170930
Referenced by AuroraFW::GEngine::GraphicsContext::renderLoop().
getHeight()
uint AuroraFW::GEngine::Window::getHeight () const inline
Returns the height of the window.
Returns
Height of the window.
See also
getWidth()
Since
snapshot20170930
Referenced by AuroraFW::GEngine::GraphicsContext::renderLoop().
properties()
WindowProperties AuroraFW::GEngine::Window::properties () inline
getFloating()
bool AuroraFW::GEngine::Window::getFloating () const inline
setFloating()
void AuroraFW::GEngine::Window::setFloating (bool val) inline
getResizable()
bool AuroraFW::GEngine::Window::getResizable () const inline
setResizable()
void AuroraFW::GEngine::Window::setResizable (bool val) inline
getDoubleBuffer()
bool AuroraFW::GEngine::Window::getDoubleBuffer () const inline
setDoubleBuffer()
void AuroraFW::GEngine::Window::setDoubleBuffer (bool val) inline
setSamples()
bool AuroraFW::GEngine::Window::setSamples (int s) inline
Member Data Documentation
window
GLFWwindow* AuroraFW::GEngine::Window::window protected
The GLFWwindow used to render.
Since
snapshot20170930
Referenced by AuroraFW::GEngine::InputManager::InputManager(), isClosed(), AuroraFW::GEngine::ImGuiLoader::Load(), present(), update(), Window(), and ~Window().
wp
WindowProperties AuroraFW::GEngine::Window::wp protected
Referenced by present(), update(), and Window().
The documentation for this class was generated from the following files:
gengine/core/include/AuroraFW/GEngine/Window.h
gengine/core/src/Window.cpp