Aurora Framework: AuroraFW::AudioManager::AudioBackend Class Reference
AuroraFW::AudioManager::AudioBackend Class Reference
A singleton class representing the audio backend.
Public Member Functions
~AudioBackend ()
AudioBackend destructor.
const AudioDevice * getAllDevices ()
Gets an array containing all the audio devices.
const AudioDevice * getInputDevices ()
Gets an array containing all the input audio devices.
int getNumDevices ()
Gets the total number of audio devices available.
int getNumInputDevices ()
Gets the total number of input audio devices available.
int getNumOutputDevices ()
Gets the total number of output audio devices available.
const AudioDevice * getOutputDevices ()
Gets an array containing all the output audio devices.
void setInputDevice (AudioDevice)
Sets the backend input device to the one given.
void setOutputDevice (AudioDevice)
Sets the backend output device to the one given.
Static Public Member Functions
static AudioBackend & getInstance ()
The singleton's getIntance() method to get access to the AudioListener.
static void start ()
Starts the AudioBackend instance, making it ready to process audio.
static void terminate ()
Terminates the AudioBackend instance, signaling no more audio is needed.
Public Attributes
float globalVolume = 1
The global volume for all output audio.
Detailed Description
A singleton class representing the audio backend.
A singleton class with the function of handling all the audio processing and settings.
Since
snapshot20180330
Constructor & Destructor Documentation
~AudioBackend()
AuroraFW::AudioManager::AudioBackend::~AudioBackend () inline
AudioBackend destructor.
Doesn't do anything, to prevent accidental deletions. To terminate it, you must call terminate().
Since
snapshot20180330
Member Function Documentation
start()
void AuroraFW::AudioManager::AudioBackend::start () static
Starts the AudioBackend instance, making it ready to process audio.
Exceptions
PAErrorException In case there was a PortAudio error.
Note
Every call to start() should be followed by a terminate(), to ensure the backend is closed before the app leaves.
Warning
Do not call start() when it's started already. You can check if it's started already by calling getInstance(), which should return a non-null pointer.
See also
terminate()
Since
snapshot20180330
References AuroraFW::CLI::Log(), and AuroraFW::CLI::Warning.
getInstance()
AudioBackend & AuroraFW::AudioManager::AudioBackend::getInstance () static
The singleton's getIntance() method to get access to the AudioListener.
Exceptions
AudioNotInitializedException In case the AudioBackend wasn't initialized when this is called.
Returns
A valid AudioListener instance, if is initialized.
Since
snapshot20180330
Referenced by AuroraFW::AudioManager::audioOutputCallback().
terminate()
void AuroraFW::AudioManager::AudioBackend::terminate () static
Terminates the AudioBackend instance, signaling no more audio is needed.
Exceptions
PAErrorException In case there was a PortAudio error.
Note
Every call to start() should be followed by a terminate(), to ensure the backend is closed before the app leaves.
Warning
Do not call terminate() when it's terminated already. You can check if it's started already by calling getInstance(), which should return a null pointer.
See also
start()
Since
snapshot20180330
References AuroraFW::AudioManager::catchPAProblem(), AuroraFW::DebugManager::Log(), AuroraFW::CLI::Log(), and AuroraFW::CLI::Warning.
getAllDevices()
const AudioDevice * AuroraFW::AudioManager::AudioBackend::getAllDevices ()
Gets an array containing all the audio devices.
Use the getNumDevices() method to get the size of the array.
Returns
A pointer containing all AudioDevices.
Since
snapshot20180330
getOutputDevices()
const AudioDevice * AuroraFW::AudioManager::AudioBackend::getOutputDevices ()
Gets an array containing all the output audio devices.
Use the getNumOutputDevices() method to get the size of the array.
Returns
A pointer containing all output AudioDevices.
See also
getInputDevices()
Since
snapshot20180330
References AuroraFW::AudioManager::AudioDevice::getMaxOutputChannels().
getInputDevices()
const AudioDevice * AuroraFW::AudioManager::AudioBackend::getInputDevices ()
Gets an array containing all the input audio devices.
Use the getNumInputDevices() method to get the size of the array.
Returns
A pointer containing all input AudioDevices.
See also
getOutputDevices()
Since
snapshot20180330
References AuroraFW::AudioManager::AudioDevice::getMaxInputChannels().
setInputDevice()
void AuroraFW::AudioManager::AudioBackend::setInputDevice (AudioDevice device)
Sets the backend input device to the one given.
Parameters
device The desired AudioDevice
Warning
The given device must have input channels, or an error will occur.
See also
setOutputDevice(AudioDevice)
Since
snapshot20180330
setOutputDevice()
void AuroraFW::AudioManager::AudioBackend::setOutputDevice (AudioDevice device)
Sets the backend output device to the one given.
Parameters
device The desired AudioDevice
Warning
The given device must have output channels, or an error will occur.
See also
setInputDevice(AudioDevice)
Since
snapshot20180330
getNumDevices()
int AuroraFW::AudioManager::AudioBackend::getNumDevices () inline
Gets the total number of audio devices available.
Returns
The number of all audio devices available.
Since
snapshot20180330
getNumOutputDevices()
int AuroraFW::AudioManager::AudioBackend::getNumOutputDevices () inline
Gets the total number of output audio devices available.
Returns
The number of output devices available.
See also
getNumInputDevices()
Since
snapshot20180330
getNumInputDevices()
int AuroraFW::AudioManager::AudioBackend::getNumInputDevices () inline
Gets the total number of input audio devices available.
Returns
The number of input devices available.
See also
getNumOutputDevices()
Since
snapshot20180330
Member Data Documentation
globalVolume
float AuroraFW::AudioManager::AudioBackend::globalVolume = 1
The global volume for all output audio.
Ideally, it should only range from 0 to 1.
Since
snapshot20180330
Referenced by AuroraFW::AudioManager::audioOutputCallback().
The documentation for this class was generated from the following files:
AudioBackend.h
AudioBackend.cpp