Aurora Framework: Time.c File Reference
Cocoa/Time.c File Reference
Functions
void _glfwInitTimerNS (void)
uint64_t _glfwPlatformGetTimerFrequency (void)
uint64_t _glfwPlatformGetTimerValue (void)
Function Documentation
_glfwInitTimerNS()
void _glfwInitTimerNS (void)
References _glfw, and _GLFWlibrary::timer.
Referenced by _glfwPlatformInit().
_glfwPlatformGetTimerValue()
uint64_t _glfwPlatformGetTimerValue (void)
Referenced by glfwGetTime(), glfwGetTimerValue(), glfwInit(), glfwSetTime(), and waitForEvent().
_glfwPlatformGetTimerFrequency()
uint64_t _glfwPlatformGetTimerFrequency (void)
Referenced by glfwGetTime(), glfwGetTimerFrequency(), glfwSetTime(), and waitForEvent().