Aurora Framework: Context.c File Reference
OSMesa/Context.c File Reference
Macros
#define setAttrib(a, v)
Functions
GLFWbool _glfwCreateContextOSMesa (_GLFWwindow *window, const _GLFWctxconfig *ctxconfig, const _GLFWfbconfig *fbconfig)
GLFWbool _glfwInitOSMesa (void)
void _glfwTerminateOSMesa (void)
static void destroyContextOSMesa (_GLFWwindow *window)
static int extensionSupportedOSMesa (const char *extension)
static GLFWglproc getProcAddressOSMesa (const char *procname)
GLFWAPI int glfwGetOSMesaColorBuffer (GLFWwindow *handle, int *width, int *height, int *format, void **buffer)
GLFWAPI OSMesaContext glfwGetOSMesaContext (GLFWwindow *handle)
GLFWAPI int glfwGetOSMesaDepthBuffer (GLFWwindow *handle, int *width, int *height, int *bytesPerValue, void **buffer)
static void makeContextCurrentOSMesa (_GLFWwindow *window)
static void swapBuffersOSMesa (_GLFWwindow *window)
static void swapIntervalOSMesa (int interval)
Macro Definition Documentation
setAttrib
#define setAttrib (a, v)
Value:
{ \
    assert((size_t) (index + 1) < sizeof(attribs) / sizeof(attribs[0])); \
    attribs[index++] = a; \
    attribs[index++] = v; \
}
Referenced by _glfwCreateContextOSMesa().
Function Documentation
makeContextCurrentOSMesa()
static void makeContextCurrentOSMesa (_GLFWwindow * window) static
References _glfw, _glfwInputError(), _glfwPlatformGetFramebufferSize(), _glfwPlatformSetTls(), _GLFWwindow::context, _GLFWlibrary::contextSlot, GL_UNSIGNED_BYTE, GLFW_PLATFORM_ERROR, height, NULL, OSMesaMakeCurrent, and width.
Referenced by _glfwCreateContextOSMesa().
getProcAddressOSMesa()
static GLFWglproc getProcAddressOSMesa (const char * procname) static
References OSMesaGetProcAddress.
Referenced by _glfwCreateContextOSMesa().
destroyContextOSMesa()
static void destroyContextOSMesa (_GLFWwindow * window) static
References _GLFWwindow::context, NULL, and OSMesaDestroyContext.
Referenced by _glfwCreateContextOSMesa().
swapBuffersOSMesa()
static void swapBuffersOSMesa (_GLFWwindow * window) static
Referenced by _glfwCreateContextOSMesa().
swapIntervalOSMesa()
static void swapIntervalOSMesa (int interval) static
Referenced by _glfwCreateContextOSMesa().
extensionSupportedOSMesa()
static int extensionSupportedOSMesa (const char * extension) static
References GLFW_FALSE.
Referenced by _glfwCreateContextOSMesa().
_glfwInitOSMesa()
GLFWbool _glfwInitOSMesa (void)
References _glfw, _glfw_dlopen, _glfw_dlsym, _glfwInputError(), _glfwTerminateOSMesa(), GLFW_API_UNAVAILABLE, GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, _GLFWlibrary::handle, and NULL.
Referenced by _glfwPlatformCreateWindow().
_glfwTerminateOSMesa()
void _glfwTerminateOSMesa (void)
References _glfw, _glfw_dlclose, _GLFWlibrary::handle, and NULL.
Referenced by _glfwInitOSMesa(), and _glfwPlatformTerminate().
_glfwCreateContextOSMesa()
GLFWbool _glfwCreateContextOSMesa (_GLFWwindow * window, const _GLFWctxconfig * ctxconfig, const _GLFWfbconfig * fbconfig)
References _glfwInputError(), _GLFWfbconfig::accumAlphaBits, _GLFWfbconfig::accumBlueBits, _GLFWfbconfig::accumGreenBits, _GLFWfbconfig::accumRedBits, _GLFWctxconfig::client, _GLFWwindow::context, _GLFWfbconfig::depthBits, _GLFWcontext::destroy, destroyContextOSMesa(), _GLFWcontext::extensionSupported, extensionSupportedOSMesa(), _GLFWctxconfig::forward, _GLFWcontext::getProcAddress, getProcAddressOSMesa(), GLFW_API_UNAVAILABLE, GLFW_FALSE, GLFW_OPENGL_COMPAT_PROFILE, GLFW_OPENGL_CORE_PROFILE, GLFW_OPENGL_ES_API, GLFW_TRUE, GLFW_VERSION_UNAVAILABLE, _GLFWctxconfig::major, makeContextCurrentOSMesa(), _GLFWcontext::makeCurrent, _GLFWctxconfig::minor, NULL, OSMESA_ACCUM_BITS, OSMESA_COMPAT_PROFILE, OSMESA_CONTEXT_MAJOR_VERSION, OSMESA_CONTEXT_MINOR_VERSION, OSMESA_CORE_PROFILE, OSMESA_DEPTH_BITS, OSMESA_FORMAT, OSMESA_PROFILE, OSMESA_RGBA, OSMESA_STENCIL_BITS, OSMesaCreateContextAttribs, OSMesaCreateContextExt, _GLFWctxconfig::profile, setAttrib, _GLFWctxconfig::share, _GLFWfbconfig::stencilBits, _GLFWcontext::swapBuffers, swapBuffersOSMesa(), _GLFWcontext::swapInterval, and swapIntervalOSMesa().
Referenced by _glfwPlatformCreateWindow().
glfwGetOSMesaColorBuffer()
GLFWAPI int glfwGetOSMesaColorBuffer (GLFWwindow * handle, int * width, int * height, int * format, void ** buffer)
References _GLFW_REQUIRE_INIT_OR_RETURN, _glfwInputError(), _GLFWwindow::context, GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, height, NULL, OSMesaGetColorBuffer, and width.
glfwGetOSMesaDepthBuffer()
GLFWAPI int glfwGetOSMesaDepthBuffer (GLFWwindow * handle, int * width, int * height, int * bytesPerValue, void ** buffer)
References _GLFW_REQUIRE_INIT_OR_RETURN, _glfwInputError(), _GLFWwindow::context, GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, height, NULL, OSMesaGetDepthBuffer, and width.
glfwGetOSMesaContext()
GLFWAPI OSMesaContext glfwGetOSMesaContext (GLFWwindow * handle)
References _GLFW_REQUIRE_INIT_OR_RETURN, _glfwInputError(), _GLFWcontext::client, _GLFWwindow::context, GLFW_NO_API, GLFW_NO_WINDOW_CONTEXT, and NULL.