Aurora Framework: cart.c File Reference
cart.c File Reference
Functions
static size_t cart_min_size (const SF_CART_INFO *info)
SF_CART_INFO_16K * cart_var_alloc (void)
int cart_var_get (SF_PRIVATE *psf, SF_CART_INFO *data, size_t datasize)
int cart_var_set (SF_PRIVATE *psf, const SF_CART_INFO *info, size_t datasize)
Function Documentation
cart_min_size()
static size_t cart_min_size (const SF_CART_INFO * info) inline static
References NULL.
Referenced by cart_var_get(), and cart_var_set().
cart_var_alloc()
SF_CART_INFO_16K* cart_var_alloc (void)
Referenced by cart_var_set(), and wavlike_read_cart_chunk().
cart_var_set()
int cart_var_set (SF_PRIVATE * psf, const SF_CART_INFO * info, size_t datasize)
References sf_private_tag::cart_16k, cart_min_size(), cart_var_alloc(), sf_private_tag::error, memcpy(), NULL, psf_strlcat(), psf_strlcpy_crlf(), SFE_BAD_CART_INFO_SIZE, SFE_BAD_CART_INFO_TOO_BIG, and SFE_MALLOC_FAILED.
Referenced by sf_command().
cart_var_get()
int cart_var_get (SF_PRIVATE * psf, SF_CART_INFO * data, size_t datasize)
References sf_private_tag::cart_16k, cart_min_size(), memcpy(), NULL, and SF_MIN.
Referenced by sf_command().