Aurora Framework: pcm.c File Reference
pcm.c File Reference
Macros
#define SIZEOF_TRIBYTE 3
Typedefs
typedef void tribyte
Enumerations
enum { SF_CHARS_SIGNED = 200, SF_CHARS_UNSIGNED = 201 }
Functions
static void bei2d_array (int *src, int count, double *dest, double normfact)
static void bei2f_array (int *src, int count, float *dest, float normfact)
static void bei2s_array (int *src, int count, short *dest)
static void bes2d_array (short *src, int count, double *dest, double normfact)
static void bes2f_array (short *src, int count, float *dest, float normfact)
static void bes2i_array (short *src, int count, int *dest)
static void bet2d_array (tribyte *src, int count, double *dest, double normfact)
static void bet2f_array (tribyte *src, int count, float *dest, float normfact)
static void bet2i_array (tribyte *src, int count, int *dest)
static void bet2s_array (tribyte *src, int count, short *dest)
static void d2bei_array (const double *src, int *dest, int count, int normalize)
static void d2bei_clip_array (const double *src, int *dest, int count, int normalize)
static void d2bes_array (const double *src, short *dest, int count, int normalize)
static void d2bes_clip_array (const double *src, short *dest, int count, int normalize)
static void d2bet_array (const double *src, tribyte *dest, int count, int normalize)
static void d2bet_clip_array (const double *src, tribyte *dest, int count, int normalize)
static void d2lei_array (const double *src, int *dest, int count, int normalize)
static void d2lei_clip_array (const double *src, int *dest, int count, int normalize)
static void d2les_array (const double *src, short *dest, int count, int normalize)
static void d2les_clip_array (const double *src, short *dest, int count, int normalize)
static void d2let_array (const double *src, tribyte *dest, int count, int normalize)
static void d2let_clip_array (const double *src, tribyte *dest, int count, int normalize)
static void d2sc_array (const double *src, signed char *dest, int count, int normalize)
static void d2sc_clip_array (const double *src, signed char *dest, int count, int normalize)
static void d2uc_array (const double *src, unsigned char *dest, int count, int normalize)
static void d2uc_clip_array (const double *src, unsigned char *dest, int count, int normalize)
static void f2bei_array (const float *src, int *dest, int count, int normalize)
static void f2bei_clip_array (const float *src, int *dest, int count, int normalize)
static void f2bes_array (const float *src, short *dest, int count, int normalize)
static void f2bes_clip_array (const float *src, short *dest, int count, int normalize)
static void f2bet_array (const float *src, tribyte *dest, int count, int normalize)
static void f2bet_clip_array (const float *src, tribyte *dest, int count, int normalize)
static void f2lei_array (const float *src, int *dest, int count, int normalize)
static void f2lei_clip_array (const float *src, int *dest, int count, int normalize)
static void f2les_array (const float *src, short *dest, int count, int normalize)
static void f2les_clip_array (const float *src, short *dest, int count, int normalize)
static void f2let_array (const float *src, tribyte *dest, int count, int normalize)
static void f2let_clip_array (const float *src, tribyte *dest, int count, int normalize)
static void f2sc_array (const float *src, signed char *dest, int count, int normalize)
static void f2sc_clip_array (const float *src, signed char *dest, int count, int normalize)
static void f2uc_array (const float *src, unsigned char *dest, int count, int normalize)
static void f2uc_clip_array (const float *src, unsigned char *dest, int count, int normalize)
static void i2bes_array (const int *src, short *dest, int count)
static void i2bet_array (const int *src, tribyte *dest, int count)
static void i2les_array (const int *src, short *dest, int count)
static void i2let_array (const int *src, tribyte *dest, int count)
static void i2sc_array (const int *src, signed char *dest, int count)
static void i2uc_array (const int *src, unsigned char *dest, int count)
static void lei2d_array (int *src, int count, double *dest, double normfact)
static void lei2f_array (int *src, int count, float *dest, float normfact)
static void lei2s_array (int *src, int count, short *dest)
static void les2d_array (short *src, int count, double *dest, double normfact)
static void les2f_array (short *src, int count, float *dest, float normfact)
static void les2i_array (short *src, int count, int *dest)
static void let2d_array (tribyte *src, int count, double *dest, double normfact)
static void let2f_array (tribyte *src, int count, float *dest, float normfact)
static void let2i_array (tribyte *src, int count, int *dest)
static void let2s_array (tribyte *src, int count, short *dest)
int pcm_init (SF_PRIVATE *psf)
static sf_count_t pcm_read_bei2d (SF_PRIVATE *psf, double *ptr, sf_count_t len)
static sf_count_t pcm_read_bei2f (SF_PRIVATE *psf, float *ptr, sf_count_t len)
static sf_count_t pcm_read_bei2i (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static sf_count_t pcm_read_bei2s (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static sf_count_t pcm_read_bes2d (SF_PRIVATE *psf, double *ptr, sf_count_t len)
static sf_count_t pcm_read_bes2f (SF_PRIVATE *psf, float *ptr, sf_count_t len)
static sf_count_t pcm_read_bes2i (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static sf_count_t pcm_read_bes2s (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static sf_count_t pcm_read_bet2d (SF_PRIVATE *psf, double *ptr, sf_count_t len)
static sf_count_t pcm_read_bet2f (SF_PRIVATE *psf, float *ptr, sf_count_t len)
static sf_count_t pcm_read_bet2i (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static sf_count_t pcm_read_bet2s (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static sf_count_t pcm_read_lei2d (SF_PRIVATE *psf, double *ptr, sf_count_t len)
static sf_count_t pcm_read_lei2f (SF_PRIVATE *psf, float *ptr, sf_count_t len)
static sf_count_t pcm_read_lei2i (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static sf_count_t pcm_read_lei2s (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static sf_count_t pcm_read_les2d (SF_PRIVATE *psf, double *ptr, sf_count_t len)
static sf_count_t pcm_read_les2f (SF_PRIVATE *psf, float *ptr, sf_count_t len)
static sf_count_t pcm_read_les2i (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static sf_count_t pcm_read_les2s (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static sf_count_t pcm_read_let2d (SF_PRIVATE *psf, double *ptr, sf_count_t len)
static sf_count_t pcm_read_let2f (SF_PRIVATE *psf, float *ptr, sf_count_t len)
static sf_count_t pcm_read_let2i (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static sf_count_t pcm_read_let2s (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static sf_count_t pcm_read_sc2d (SF_PRIVATE *psf, double *ptr, sf_count_t len)
static sf_count_t pcm_read_sc2f (SF_PRIVATE *psf, float *ptr, sf_count_t len)
static sf_count_t pcm_read_sc2i (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static sf_count_t pcm_read_sc2s (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static sf_count_t pcm_read_uc2d (SF_PRIVATE *psf, double *ptr, sf_count_t len)
static sf_count_t pcm_read_uc2f (SF_PRIVATE *psf, float *ptr, sf_count_t len)
static sf_count_t pcm_read_uc2i (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static sf_count_t pcm_read_uc2s (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static sf_count_t pcm_write_d2bei (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
static sf_count_t pcm_write_d2bes (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
static sf_count_t pcm_write_d2bet (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
static sf_count_t pcm_write_d2lei (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
static sf_count_t pcm_write_d2les (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
static sf_count_t pcm_write_d2let (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
static sf_count_t pcm_write_d2sc (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
static sf_count_t pcm_write_d2uc (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
static sf_count_t pcm_write_f2bei (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
static sf_count_t pcm_write_f2bes (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
static sf_count_t pcm_write_f2bet (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
static sf_count_t pcm_write_f2lei (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
static sf_count_t pcm_write_f2les (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
static sf_count_t pcm_write_f2let (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
static sf_count_t pcm_write_f2sc (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
static sf_count_t pcm_write_f2uc (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
static sf_count_t pcm_write_i2bei (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
static sf_count_t pcm_write_i2bes (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
static sf_count_t pcm_write_i2bet (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
static sf_count_t pcm_write_i2lei (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
static sf_count_t pcm_write_i2les (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
static sf_count_t pcm_write_i2let (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
static sf_count_t pcm_write_i2sc (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
static sf_count_t pcm_write_i2uc (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
static sf_count_t pcm_write_s2bei (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
static sf_count_t pcm_write_s2bes (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
static sf_count_t pcm_write_s2bet (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
static sf_count_t pcm_write_s2lei (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
static sf_count_t pcm_write_s2les (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
static sf_count_t pcm_write_s2let (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
static sf_count_t pcm_write_s2sc (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
static sf_count_t pcm_write_s2uc (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
static void s2bei_array (const short *src, int *dest, int count)
static void s2bet_array (const short *src, tribyte *dest, int count)
static void s2lei_array (const short *src, int *dest, int count)
static void s2let_array (const short *src, tribyte *dest, int count)
static void s2sc_array (const short *src, signed char *dest, int count)
static void s2uc_array (const short *src, unsigned char *dest, int count)
static void sc2d_array (signed char *src, int count, double *dest, double normfact)
static void sc2f_array (signed char *src, int count, float *dest, float normfact)
static void sc2i_array (signed char *src, int count, int *dest)
static void sc2s_array (signed char *src, int count, short *dest)
static void uc2d_array (unsigned char *src, int count, double *dest, double normfact)
static void uc2f_array (unsigned char *src, int count, float *dest, float normfact)
static void uc2i_array (unsigned char *src, int count, int *dest)
static void uc2s_array (unsigned char *src, int count, short *dest)
Macro Definition Documentation
SIZEOF_TRIBYTE
#define SIZEOF_TRIBYTE 3
Referenced by pcm_read_bet2d(), pcm_read_bet2f(), pcm_read_bet2i(), pcm_read_bet2s(), pcm_read_let2d(), pcm_read_let2f(), pcm_read_let2i(), pcm_read_let2s(), pcm_write_d2bet(), pcm_write_d2let(), pcm_write_f2bet(), pcm_write_f2let(), pcm_write_i2bet(), pcm_write_i2let(), pcm_write_s2bet(), and pcm_write_s2let().
Typedef Documentation
tribyte
typedef void tribyte
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
SF_CHARS_SIGNED
SF_CHARS_UNSIGNED
Function Documentation
pcm_read_sc2s()
static sf_count_t pcm_read_sc2s (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
References ARRAY_LEN, psf_fread(), sc2s_array(), and BUF_UNION::scbuf.
Referenced by pcm_init().
pcm_read_uc2s()
static sf_count_t pcm_read_uc2s (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
References ARRAY_LEN, psf_fread(), uc2s_array(), and BUF_UNION::ucbuf.
Referenced by pcm_init().
pcm_read_bes2s()
static sf_count_t pcm_read_bes2s (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
References endswap_short_array(), and psf_fread().
Referenced by pcm_init().
pcm_read_les2s()
static sf_count_t pcm_read_les2s (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
References endswap_short_array(), and psf_fread().
Referenced by pcm_init().
pcm_read_bet2s()
static sf_count_t pcm_read_bet2s (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
References bet2s_array(), psf_fread(), SIZEOF_TRIBYTE, and BUF_UNION::ucbuf.
Referenced by pcm_init().
pcm_read_let2s()
static sf_count_t pcm_read_let2s (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
References let2s_array(), psf_fread(), SIZEOF_TRIBYTE, and BUF_UNION::ucbuf.
Referenced by pcm_init().
pcm_read_bei2s()
static sf_count_t pcm_read_bei2s (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
References ARRAY_LEN, bei2s_array(), BUF_UNION::ibuf, and psf_fread().
Referenced by pcm_init().
pcm_read_lei2s()
static sf_count_t pcm_read_lei2s (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
References ARRAY_LEN, BUF_UNION::ibuf, lei2s_array(), and psf_fread().
Referenced by pcm_init().
pcm_read_sc2i()
static sf_count_t pcm_read_sc2i (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
References ARRAY_LEN, psf_fread(), sc2i_array(), and BUF_UNION::scbuf.
Referenced by pcm_init().
pcm_read_uc2i()
static sf_count_t pcm_read_uc2i (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
References ARRAY_LEN, psf_fread(), uc2i_array(), and BUF_UNION::ucbuf.
Referenced by pcm_init().
pcm_read_bes2i()
static sf_count_t pcm_read_bes2i (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
References ARRAY_LEN, bes2i_array(), psf_fread(), and BUF_UNION::sbuf.
Referenced by pcm_init().
pcm_read_les2i()
static sf_count_t pcm_read_les2i (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
References ARRAY_LEN, les2i_array(), psf_fread(), and BUF_UNION::sbuf.
Referenced by pcm_init().
pcm_read_bet2i()
static sf_count_t pcm_read_bet2i (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
References bet2i_array(), psf_fread(), SIZEOF_TRIBYTE, and BUF_UNION::ucbuf.
Referenced by pcm_init().
pcm_read_let2i()
static sf_count_t pcm_read_let2i (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
References let2i_array(), psf_fread(), SIZEOF_TRIBYTE, and BUF_UNION::ucbuf.
Referenced by pcm_init().
pcm_read_bei2i()
static sf_count_t pcm_read_bei2i (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
References endswap_int_array(), and psf_fread().
Referenced by pcm_init().
pcm_read_lei2i()
static sf_count_t pcm_read_lei2i (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
References endswap_int_array(), and psf_fread().
Referenced by pcm_init().
pcm_read_sc2f()
static sf_count_t pcm_read_sc2f (SF_PRIVATE * psf, float * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::norm_float, psf_fread(), sc2f_array(), and BUF_UNION::scbuf.
Referenced by pcm_init().
pcm_read_uc2f()
static sf_count_t pcm_read_uc2f (SF_PRIVATE * psf, float * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::norm_float, psf_fread(), uc2f_array(), and BUF_UNION::ucbuf.
Referenced by pcm_init().
pcm_read_bes2f()
static sf_count_t pcm_read_bes2f (SF_PRIVATE * psf, float * ptr, sf_count_t len) static
References ARRAY_LEN, bes2f_array(), sf_private_tag::norm_float, psf_fread(), and BUF_UNION::sbuf.
Referenced by pcm_init().
pcm_read_les2f()
static sf_count_t pcm_read_les2f (SF_PRIVATE * psf, float * ptr, sf_count_t len) static
References ARRAY_LEN, les2f_array(), sf_private_tag::norm_float, psf_fread(), and BUF_UNION::sbuf.
Referenced by pcm_init().
pcm_read_bet2f()
static sf_count_t pcm_read_bet2f (SF_PRIVATE * psf, float * ptr, sf_count_t len) static
References bet2f_array(), sf_private_tag::norm_float, psf_fread(), SIZEOF_TRIBYTE, and BUF_UNION::ucbuf.
Referenced by pcm_init().
pcm_read_let2f()
static sf_count_t pcm_read_let2f (SF_PRIVATE * psf, float * ptr, sf_count_t len) static
References let2f_array(), sf_private_tag::norm_float, psf_fread(), SIZEOF_TRIBYTE, and BUF_UNION::ucbuf.
Referenced by pcm_init().
pcm_read_bei2f()
static sf_count_t pcm_read_bei2f (SF_PRIVATE * psf, float * ptr, sf_count_t len) static
References ARRAY_LEN, bei2f_array(), BUF_UNION::ibuf, sf_private_tag::norm_float, and psf_fread().
Referenced by pcm_init().
pcm_read_lei2f()
static sf_count_t pcm_read_lei2f (SF_PRIVATE * psf, float * ptr, sf_count_t len) static
References ARRAY_LEN, BUF_UNION::ibuf, lei2f_array(), sf_private_tag::norm_float, and psf_fread().
Referenced by pcm_init().
pcm_read_sc2d()
static sf_count_t pcm_read_sc2d (SF_PRIVATE * psf, double * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::norm_double, psf_fread(), sc2d_array(), and BUF_UNION::scbuf.
Referenced by pcm_init().
pcm_read_uc2d()
static sf_count_t pcm_read_uc2d (SF_PRIVATE * psf, double * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::norm_double, psf_fread(), uc2d_array(), and BUF_UNION::ucbuf.
Referenced by pcm_init().
pcm_read_bes2d()
static sf_count_t pcm_read_bes2d (SF_PRIVATE * psf, double * ptr, sf_count_t len) static
References ARRAY_LEN, bes2d_array(), sf_private_tag::norm_double, psf_fread(), and BUF_UNION::sbuf.
Referenced by pcm_init().
pcm_read_les2d()
static sf_count_t pcm_read_les2d (SF_PRIVATE * psf, double * ptr, sf_count_t len) static
References ARRAY_LEN, les2d_array(), sf_private_tag::norm_double, psf_fread(), and BUF_UNION::sbuf.
Referenced by pcm_init().
pcm_read_bet2d()
static sf_count_t pcm_read_bet2d (SF_PRIVATE * psf, double * ptr, sf_count_t len) static
References bet2d_array(), sf_private_tag::norm_double, psf_fread(), SIZEOF_TRIBYTE, and BUF_UNION::ucbuf.
Referenced by pcm_init().
pcm_read_let2d()
static sf_count_t pcm_read_let2d (SF_PRIVATE * psf, double * ptr, sf_count_t len) static
References let2d_array(), sf_private_tag::norm_double, psf_fread(), SIZEOF_TRIBYTE, and BUF_UNION::ucbuf.
Referenced by pcm_init().
pcm_read_bei2d()
static sf_count_t pcm_read_bei2d (SF_PRIVATE * psf, double * ptr, sf_count_t len) static
References ARRAY_LEN, bei2d_array(), BUF_UNION::ibuf, sf_private_tag::norm_double, and psf_fread().
Referenced by pcm_init().
pcm_read_lei2d()
static sf_count_t pcm_read_lei2d (SF_PRIVATE * psf, double * ptr, sf_count_t len) static
References ARRAY_LEN, BUF_UNION::ibuf, lei2d_array(), sf_private_tag::norm_double, and psf_fread().
Referenced by pcm_init().
pcm_write_s2sc()
static sf_count_t pcm_write_s2sc (SF_PRIVATE * psf, const short * ptr, sf_count_t len) static
References ARRAY_LEN, psf_fwrite(), s2sc_array(), and BUF_UNION::scbuf.
Referenced by pcm_init().
pcm_write_s2uc()
static sf_count_t pcm_write_s2uc (SF_PRIVATE * psf, const short * ptr, sf_count_t len) static
References ARRAY_LEN, psf_fwrite(), s2uc_array(), and BUF_UNION::ucbuf.
Referenced by pcm_init().
pcm_write_s2bes()
static sf_count_t pcm_write_s2bes (SF_PRIVATE * psf, const short * ptr, sf_count_t len) static
References ARRAY_LEN, endswap_short_copy(), psf_fwrite(), and BUF_UNION::sbuf.
Referenced by pcm_init().
pcm_write_s2les()
static sf_count_t pcm_write_s2les (SF_PRIVATE * psf, const short * ptr, sf_count_t len) static
References ARRAY_LEN, endswap_short_copy(), psf_fwrite(), and BUF_UNION::sbuf.
Referenced by pcm_init().
pcm_write_s2bet()
static sf_count_t pcm_write_s2bet (SF_PRIVATE * psf, const short * ptr, sf_count_t len) static
References psf_fwrite(), s2bet_array(), SIZEOF_TRIBYTE, and BUF_UNION::ucbuf.
Referenced by pcm_init().
pcm_write_s2let()
static sf_count_t pcm_write_s2let (SF_PRIVATE * psf, const short * ptr, sf_count_t len) static
References psf_fwrite(), s2let_array(), SIZEOF_TRIBYTE, and BUF_UNION::ucbuf.
Referenced by pcm_init().
pcm_write_s2bei()
static sf_count_t pcm_write_s2bei (SF_PRIVATE * psf, const short * ptr, sf_count_t len) static
References ARRAY_LEN, BUF_UNION::ibuf, psf_fwrite(), and s2bei_array().
Referenced by pcm_init().
pcm_write_s2lei()
static sf_count_t pcm_write_s2lei (SF_PRIVATE * psf, const short * ptr, sf_count_t len) static
References ARRAY_LEN, BUF_UNION::ibuf, psf_fwrite(), and s2lei_array().
Referenced by pcm_init().
pcm_write_i2sc()
static sf_count_t pcm_write_i2sc (SF_PRIVATE * psf, const int * ptr, sf_count_t len) static
References ARRAY_LEN, i2sc_array(), psf_fwrite(), and BUF_UNION::scbuf.
Referenced by pcm_init().
pcm_write_i2uc()
static sf_count_t pcm_write_i2uc (SF_PRIVATE * psf, const int * ptr, sf_count_t len) static
References ARRAY_LEN, i2uc_array(), psf_fwrite(), and BUF_UNION::ucbuf.
Referenced by pcm_init().
pcm_write_i2bes()
static sf_count_t pcm_write_i2bes (SF_PRIVATE * psf, const int * ptr, sf_count_t len) static
References ARRAY_LEN, i2bes_array(), psf_fwrite(), and BUF_UNION::sbuf.
Referenced by pcm_init().
pcm_write_i2les()
static sf_count_t pcm_write_i2les (SF_PRIVATE * psf, const int * ptr, sf_count_t len) static
References ARRAY_LEN, i2les_array(), psf_fwrite(), and BUF_UNION::sbuf.
Referenced by pcm_init().
pcm_write_i2bet()
static sf_count_t pcm_write_i2bet (SF_PRIVATE * psf, const int * ptr, sf_count_t len) static
References i2bet_array(), psf_fwrite(), SIZEOF_TRIBYTE, and BUF_UNION::ucbuf.
Referenced by pcm_init().
pcm_write_i2let()
static sf_count_t pcm_write_i2let (SF_PRIVATE * psf, const int * ptr, sf_count_t len) static
References i2let_array(), psf_fwrite(), SIZEOF_TRIBYTE, and BUF_UNION::ucbuf.
Referenced by pcm_init().
pcm_write_i2bei()
static sf_count_t pcm_write_i2bei (SF_PRIVATE * psf, const int * ptr, sf_count_t len) static
References ARRAY_LEN, endswap_int_copy(), BUF_UNION::ibuf, and psf_fwrite().
Referenced by pcm_init().
pcm_write_i2lei()
static sf_count_t pcm_write_i2lei (SF_PRIVATE * psf, const int * ptr, sf_count_t len) static
References ARRAY_LEN, endswap_int_copy(), BUF_UNION::ibuf, and psf_fwrite().
Referenced by pcm_init().
pcm_write_f2sc()
static sf_count_t pcm_write_f2sc (SF_PRIVATE * psf, const float * ptr, sf_count_t len) static
References sf_private_tag::add_clipping, ARRAY_LEN, f2sc_array(), f2sc_clip_array(), sf_private_tag::norm_float, psf_fwrite(), and BUF_UNION::scbuf.
Referenced by pcm_init().
pcm_write_f2uc()
static sf_count_t pcm_write_f2uc (SF_PRIVATE * psf, const float * ptr, sf_count_t len) static
References sf_private_tag::add_clipping, ARRAY_LEN, f2uc_array(), f2uc_clip_array(), sf_private_tag::norm_float, psf_fwrite(), and BUF_UNION::ucbuf.
Referenced by pcm_init().
pcm_write_f2bes()
static sf_count_t pcm_write_f2bes (SF_PRIVATE * psf, const float * ptr, sf_count_t len) static
References sf_private_tag::add_clipping, ARRAY_LEN, f2bes_array(), f2bes_clip_array(), sf_private_tag::norm_float, psf_fwrite(), and BUF_UNION::sbuf.
Referenced by pcm_init().
pcm_write_f2les()
static sf_count_t pcm_write_f2les (SF_PRIVATE * psf, const float * ptr, sf_count_t len) static
References sf_private_tag::add_clipping, ARRAY_LEN, f2les_array(), f2les_clip_array(), sf_private_tag::norm_float, psf_fwrite(), and BUF_UNION::sbuf.
Referenced by pcm_init().
pcm_write_f2bet()
static sf_count_t pcm_write_f2bet (SF_PRIVATE * psf, const float * ptr, sf_count_t len) static
References sf_private_tag::add_clipping, f2bet_array(), f2bet_clip_array(), sf_private_tag::norm_float, psf_fwrite(), SIZEOF_TRIBYTE, and BUF_UNION::ucbuf.
Referenced by pcm_init().
pcm_write_f2let()
static sf_count_t pcm_write_f2let (SF_PRIVATE * psf, const float * ptr, sf_count_t len) static
References sf_private_tag::add_clipping, f2let_array(), f2let_clip_array(), sf_private_tag::norm_float, psf_fwrite(), SIZEOF_TRIBYTE, and BUF_UNION::ucbuf.
Referenced by pcm_init().
pcm_write_f2bei()
static sf_count_t pcm_write_f2bei (SF_PRIVATE * psf, const float * ptr, sf_count_t len) static
References sf_private_tag::add_clipping, ARRAY_LEN, f2bei_array(), f2bei_clip_array(), BUF_UNION::ibuf, sf_private_tag::norm_float, and psf_fwrite().
Referenced by pcm_init().
pcm_write_f2lei()
static sf_count_t pcm_write_f2lei (SF_PRIVATE * psf, const float * ptr, sf_count_t len) static
References sf_private_tag::add_clipping, ARRAY_LEN, f2lei_array(), f2lei_clip_array(), BUF_UNION::ibuf, sf_private_tag::norm_float, and psf_fwrite().
Referenced by pcm_init().
pcm_write_d2sc()
static sf_count_t pcm_write_d2sc (SF_PRIVATE * psf, const double * ptr, sf_count_t len) static
References sf_private_tag::add_clipping, ARRAY_LEN, d2sc_array(), d2sc_clip_array(), sf_private_tag::norm_double, psf_fwrite(), and BUF_UNION::scbuf.
Referenced by pcm_init().
pcm_write_d2uc()
static sf_count_t pcm_write_d2uc (SF_PRIVATE * psf, const double * ptr, sf_count_t len) static
References sf_private_tag::add_clipping, ARRAY_LEN, d2uc_array(), d2uc_clip_array(), sf_private_tag::norm_double, psf_fwrite(), and BUF_UNION::ucbuf.
Referenced by pcm_init().
pcm_write_d2bes()
static sf_count_t pcm_write_d2bes (SF_PRIVATE * psf, const double * ptr, sf_count_t len) static
References sf_private_tag::add_clipping, ARRAY_LEN, d2bes_array(), d2bes_clip_array(), sf_private_tag::norm_double, psf_fwrite(), and BUF_UNION::sbuf.
Referenced by pcm_init().
pcm_write_d2les()
static sf_count_t pcm_write_d2les (SF_PRIVATE * psf, const double * ptr, sf_count_t len) static
References sf_private_tag::add_clipping, ARRAY_LEN, d2les_array(), d2les_clip_array(), sf_private_tag::norm_double, psf_fwrite(), and BUF_UNION::sbuf.
Referenced by pcm_init().
pcm_write_d2bet()
static sf_count_t pcm_write_d2bet (SF_PRIVATE * psf, const double * ptr, sf_count_t len) static
References sf_private_tag::add_clipping, d2bet_array(), d2bet_clip_array(), sf_private_tag::norm_double, psf_fwrite(), SIZEOF_TRIBYTE, and BUF_UNION::ucbuf.
Referenced by pcm_init().
pcm_write_d2let()
static sf_count_t pcm_write_d2let (SF_PRIVATE * psf, const double * ptr, sf_count_t len) static
References sf_private_tag::add_clipping, d2let_array(), d2let_clip_array(), sf_private_tag::norm_double, psf_fwrite(), SIZEOF_TRIBYTE, and BUF_UNION::ucbuf.
Referenced by pcm_init().
pcm_write_d2bei()
static sf_count_t pcm_write_d2bei (SF_PRIVATE * psf, const double * ptr, sf_count_t len) static
References sf_private_tag::add_clipping, ARRAY_LEN, d2bei_array(), d2bei_clip_array(), BUF_UNION::ibuf, sf_private_tag::norm_double, and psf_fwrite().
Referenced by pcm_init().
pcm_write_d2lei()
static sf_count_t pcm_write_d2lei (SF_PRIVATE * psf, const double * ptr, sf_count_t len) static
References sf_private_tag::add_clipping, ARRAY_LEN, d2lei_array(), d2lei_clip_array(), BUF_UNION::ibuf, sf_private_tag::norm_double, and psf_fwrite().
Referenced by pcm_init().
pcm_init()
int pcm_init (SF_PRIVATE * psf)
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::data_endswap, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, PSF_FILE::mode, pcm_read_bei2d(), pcm_read_bei2f(), pcm_read_bei2i(), pcm_read_bei2s(), pcm_read_bes2d(), pcm_read_bes2f(), pcm_read_bes2i(), pcm_read_bes2s(), pcm_read_bet2d(), pcm_read_bet2f(), pcm_read_bet2i(), pcm_read_bet2s(), pcm_read_lei2d(), pcm_read_lei2f(), pcm_read_lei2i(), pcm_read_lei2s(), pcm_read_les2d(), pcm_read_les2f(), pcm_read_les2i(), pcm_read_les2s(), pcm_read_let2d(), pcm_read_let2f(), pcm_read_let2i(), pcm_read_let2s(), pcm_read_sc2d(), pcm_read_sc2f(), pcm_read_sc2i(), pcm_read_sc2s(), pcm_read_uc2d(), pcm_read_uc2f(), pcm_read_uc2i(), pcm_read_uc2s(), pcm_write_d2bei(), pcm_write_d2bes(), pcm_write_d2bet(), pcm_write_d2lei(), pcm_write_d2les(), pcm_write_d2let(), pcm_write_d2sc(), pcm_write_d2uc(), pcm_write_f2bei(), pcm_write_f2bes(), pcm_write_f2bet(), pcm_write_f2lei(), pcm_write_f2les(), pcm_write_f2let(), pcm_write_f2sc(), pcm_write_f2uc(), pcm_write_i2bei(), pcm_write_i2bes(), pcm_write_i2bet(), pcm_write_i2lei(), pcm_write_i2les(), pcm_write_i2let(), pcm_write_i2sc(), pcm_write_i2uc(), pcm_write_s2bei(), pcm_write_s2bes(), pcm_write_s2bet(), pcm_write_s2lei(), pcm_write_s2les(), pcm_write_s2let(), pcm_write_s2sc(), pcm_write_s2uc(), psf_log_printf(), sf_private_tag::read_double, sf_private_tag::read_float, sf_private_tag::read_int, sf_private_tag::read_short, sf_private_tag::sf, SF_CHARS_SIGNED, SF_CHARS_UNSIGNED, SF_CODEC, SFE_INTERNAL, SFE_UNIMPLEMENTED, sf_private_tag::write_double, sf_private_tag::write_float, sf_private_tag::write_int, and sf_private_tag::write_short.
Referenced by aiff_open(), au_open(), avr_open(), caf_open(), htk_open(), ircam_open(), mat4_open(), mat5_open(), mpc2k_open(), nist_open(), paf_open(), pvf_open(), raw_open(), rf64_open(), sd2_open(), svx_open(), voc_open(), w64_open(), and wav_open().
sc2s_array()
static void sc2s_array (signed char * src, int count, short * dest) inline static
Referenced by pcm_read_sc2s().
uc2s_array()
static void uc2s_array (unsigned char * src, int count, short * dest) inline static
Referenced by pcm_read_uc2s().
let2s_array()
static void let2s_array (tribyte * src, int count, short * dest) inline static
References LET2H_16_PTR.
Referenced by pcm_read_let2s().
bet2s_array()
static void bet2s_array (tribyte * src, int count, short * dest) inline static
References BET2H_16_PTR.
Referenced by pcm_read_bet2s().
lei2s_array()
static void lei2s_array (int * src, int count, short * dest) inline static
References value.
Referenced by pcm_read_lei2s().
bei2s_array()
static void bei2s_array (int * src, int count, short * dest) inline static
References value.
Referenced by pcm_read_bei2s().
sc2i_array()
static void sc2i_array (signed char * src, int count, int * dest) inline static
References arith_shift_left().
Referenced by pcm_read_sc2i().
uc2i_array()
static void uc2i_array (unsigned char * src, int count, int * dest) inline static
References arith_shift_left().
Referenced by pcm_read_uc2i().
bes2i_array()
static void bes2i_array (short * src, int count, int * dest) inline static
References arith_shift_left(), and value.
Referenced by pcm_read_bes2i().
les2i_array()
static void les2i_array (short * src, int count, int * dest) inline static
References arith_shift_left(), and value.
Referenced by pcm_read_les2i().
bet2i_array()
static void bet2i_array (tribyte * src, int count, int * dest) inline static
References psf_get_be24().
Referenced by pcm_read_bet2i().
let2i_array()
static void let2i_array (tribyte * src, int count, int * dest) inline static
References psf_get_le24().
Referenced by pcm_read_let2i().
sc2f_array()
static void sc2f_array (signed char * src, int count, float * dest, float normfact) inline static
Referenced by pcm_read_sc2f().
uc2f_array()
static void uc2f_array (unsigned char * src, int count, float * dest, float normfact) inline static
Referenced by pcm_read_uc2f().
les2f_array()
static void les2f_array (short * src, int count, float * dest, float normfact) inline static
References value.
Referenced by pcm_read_les2f().
bes2f_array()
static void bes2f_array (short * src, int count, float * dest, float normfact) inline static
References value.
Referenced by pcm_read_bes2f().
let2f_array()
static void let2f_array (tribyte * src, int count, float * dest, float normfact) inline static
References psf_get_le24(), and value.
Referenced by pcm_read_let2f().
bet2f_array()
static void bet2f_array (tribyte * src, int count, float * dest, float normfact) inline static
References psf_get_be24(), and value.
Referenced by pcm_read_bet2f().
lei2f_array()
static void lei2f_array (int * src, int count, float * dest, float normfact) inline static
References value.
Referenced by pcm_read_lei2f().
bei2f_array()
static void bei2f_array (int * src, int count, float * dest, float normfact) inline static
References value.
Referenced by pcm_read_bei2f().
sc2d_array()
static void sc2d_array (signed char * src, int count, double * dest, double normfact) inline static
Referenced by pcm_read_sc2d().
uc2d_array()
static void uc2d_array (unsigned char * src, int count, double * dest, double normfact) inline static
Referenced by pcm_read_uc2d().
les2d_array()
static void les2d_array (short * src, int count, double * dest, double normfact) inline static
References value.
Referenced by pcm_read_les2d().
bes2d_array()
static void bes2d_array (short * src, int count, double * dest, double normfact) inline static
References value.
Referenced by pcm_read_bes2d().
let2d_array()
static void let2d_array (tribyte * src, int count, double * dest, double normfact) inline static
References psf_get_le24(), and value.
Referenced by pcm_read_let2d().
bet2d_array()
static void bet2d_array (tribyte * src, int count, double * dest, double normfact) inline static
References psf_get_be24(), and value.
Referenced by pcm_read_bet2d().
lei2d_array()
static void lei2d_array (int * src, int count, double * dest, double normfact) inline static
References value.
Referenced by pcm_read_lei2d().
bei2d_array()
static void bei2d_array (int * src, int count, double * dest, double normfact) inline static
References value.
Referenced by pcm_read_bei2d().
s2sc_array()
static void s2sc_array (const short * src, signed char * dest, int count) inline static
Referenced by pcm_write_s2sc().
s2uc_array()
static void s2uc_array (const short * src, unsigned char * dest, int count) inline static
Referenced by pcm_write_s2uc().
s2let_array()
static void s2let_array (const short * src, tribyte * dest, int count) inline static
Referenced by pcm_write_s2let().
s2bet_array()
static void s2bet_array (const short * src, tribyte * dest, int count) inline static
Referenced by pcm_write_s2bet().
s2lei_array()
static void s2lei_array (const short * src, int * dest, int count) inline static
Referenced by pcm_write_s2lei().
s2bei_array()
static void s2bei_array (const short * src, int * dest, int count) inline static
Referenced by pcm_write_s2bei().
i2sc_array()
static void i2sc_array (const int * src, signed char * dest, int count) inline static
Referenced by pcm_write_i2sc().
i2uc_array()
static void i2uc_array (const int * src, unsigned char * dest, int count) inline static
Referenced by pcm_write_i2uc().
i2bes_array()
static void i2bes_array (const int * src, short * dest, int count) inline static
Referenced by pcm_write_i2bes().
i2les_array()
static void i2les_array (const int * src, short * dest, int count) inline static
Referenced by pcm_write_i2les().
i2let_array()
static void i2let_array (const int * src, tribyte * dest, int count) inline static
References value.
Referenced by pcm_write_i2let().
i2bet_array()
static void i2bet_array (const int * src, tribyte * dest, int count) inline static
References value.
Referenced by pcm_write_i2bet().
f2sc_array()
static void f2sc_array (const float * src, signed char * dest, int count, int normalize) static
Referenced by pcm_write_f2sc().
f2sc_clip_array()
static void f2sc_clip_array (const float * src, signed char * dest, int count, int normalize) static
Referenced by pcm_write_f2sc().
f2uc_array()
static void f2uc_array (const float * src, unsigned char * dest, int count, int normalize) static
Referenced by pcm_write_f2uc().
f2uc_clip_array()
static void f2uc_clip_array (const float * src, unsigned char * dest, int count, int normalize) static
Referenced by pcm_write_f2uc().
f2bes_array()
static void f2bes_array (const float * src, short * dest, int count, int normalize) static
References value.
Referenced by pcm_write_f2bes().
f2bes_clip_array()
static void f2bes_clip_array (const float * src, short * dest, int count, int normalize) static
References value.
Referenced by pcm_write_f2bes().
f2les_array()
static void f2les_array (const float * src, short * dest, int count, int normalize) static
References value.
Referenced by pcm_write_f2les().
f2les_clip_array()
static void f2les_clip_array (const float * src, short * dest, int count, int normalize) static
References value.
Referenced by pcm_write_f2les().
f2let_array()
static void f2let_array (const float * src, tribyte * dest, int count, int normalize) static
References value.
Referenced by pcm_write_f2let().
f2let_clip_array()
static void f2let_clip_array (const float * src, tribyte * dest, int count, int normalize) static
References value.
Referenced by pcm_write_f2let().
f2bet_array()
static void f2bet_array (const float * src, tribyte * dest, int count, int normalize) static
References value.
Referenced by pcm_write_f2bet().
f2bet_clip_array()
static void f2bet_clip_array (const float * src, tribyte * dest, int count, int normalize) static
References value.
Referenced by pcm_write_f2bet().
f2bei_array()
static void f2bei_array (const float * src, int * dest, int count, int normalize) static
References value.
Referenced by pcm_write_f2bei().
f2bei_clip_array()
static void f2bei_clip_array (const float * src, int * dest, int count, int normalize) static
References value.
Referenced by pcm_write_f2bei().
f2lei_array()
static void f2lei_array (const float * src, int * dest, int count, int normalize) static
References value.
Referenced by pcm_write_f2lei().
f2lei_clip_array()
static void f2lei_clip_array (const float * src, int * dest, int count, int normalize) static
References value.
Referenced by pcm_write_f2lei().
d2sc_array()
static void d2sc_array (const double * src, signed char * dest, int count, int normalize) static
Referenced by pcm_write_d2sc().
d2sc_clip_array()
static void d2sc_clip_array (const double * src, signed char * dest, int count, int normalize) static
Referenced by pcm_write_d2sc().
d2uc_array()
static void d2uc_array (const double * src, unsigned char * dest, int count, int normalize) static
Referenced by pcm_write_d2uc().
d2uc_clip_array()
static void d2uc_clip_array (const double * src, unsigned char * dest, int count, int normalize) static
Referenced by pcm_write_d2uc().
d2bes_array()
static void d2bes_array (const double * src, short * dest, int count, int normalize) static
References value.
Referenced by pcm_write_d2bes().
d2bes_clip_array()
static void d2bes_clip_array (const double * src, short * dest, int count, int normalize) static
References value.
Referenced by pcm_write_d2bes().
d2les_array()
static void d2les_array (const double * src, short * dest, int count, int normalize) static
References value.
Referenced by pcm_write_d2les().
d2les_clip_array()
static void d2les_clip_array (const double * src, short * dest, int count, int normalize) static
References value.
Referenced by pcm_write_d2les().
d2let_array()
static void d2let_array (const double * src, tribyte * dest, int count, int normalize) static
References value.
Referenced by pcm_write_d2let().
d2let_clip_array()
static void d2let_clip_array (const double * src, tribyte * dest, int count, int normalize) static
References value.
Referenced by pcm_write_d2let().
d2bet_array()
static void d2bet_array (const double * src, tribyte * dest, int count, int normalize) static
References value.
Referenced by pcm_write_d2bet().
d2bet_clip_array()
static void d2bet_clip_array (const double * src, tribyte * dest, int count, int normalize) static
References value.
Referenced by pcm_write_d2bet().
d2bei_array()
static void d2bei_array (const double * src, int * dest, int count, int normalize) static
References value.
Referenced by pcm_write_d2bei().
d2bei_clip_array()
static void d2bei_clip_array (const double * src, int * dest, int count, int normalize) static
References value.
Referenced by pcm_write_d2bei().
d2lei_array()
static void d2lei_array (const double * src, int * dest, int count, int normalize) static
References value.
Referenced by pcm_write_d2lei().
d2lei_clip_array()
static void d2lei_clip_array (const double * src, int * dest, int count, int normalize) static
References value.
Referenced by pcm_write_d2lei().