var files_dup =
[
    [ "__init__.py", "d3/d9a/____init_____8py.html", null ],
    [ "lang/__init__.py", "d4/d2d/lang_2____init_____8py.html", "d4/d2d/lang_2____init_____8py" ],
    [ "lang/c/__init__.py", "df/dbe/lang_2c_2____init_____8py.html", "df/dbe/lang_2c_2____init_____8py" ],
    [ "lang/c/loader/__init__.py", "d3/de6/lang_2c_2loader_2____init_____8py.html", "d3/de6/lang_2c_2loader_2____init_____8py" ],
    [ "lang/common/__init__.py", "d8/d5d/lang_2common_2____init_____8py.html", null ],
    [ "lang/d/__init__.py", "db/dc7/lang_2d_2____init_____8py.html", "db/dc7/lang_2d_2____init_____8py" ],
    [ "lang/d/loader/__init__.py", "dc/d32/lang_2d_2loader_2____init_____8py.html", null ],
    [ "lang/nim/__init__.py", "db/da9/lang_2nim_2____init_____8py.html", "db/da9/lang_2nim_2____init_____8py" ],
    [ "lang/nim/loader/__init__.py", "d1/d88/lang_2nim_2loader_2____init_____8py.html", null ],
    [ "lang/volt/__init__.py", "d7/d51/lang_2volt_2____init_____8py.html", "d7/d51/lang_2volt_2____init_____8py" ],
    [ "lang/volt/loader/__init__.py", "d0/df2/lang_2volt_2loader_2____init_____8py.html", null ],
    [ "__main__.py", "d8/d1e/____main_____8py.html", "d8/d1e/____main_____8py" ],
    [ "_Direct3D.h", "d8/d94/___direct3_d_8h.html", null ],
    [ "_GEngine.h", "de/dbf/___g_engine_8h.html", "de/dbf/___g_engine_8h" ],
    [ "_GL.h", "d1/d69/___g_l_8h.html", null ],
    [ "_GLEW.h", "d3/d2a/___g_l_e_w_8h.html", null ],
    [ "_GLFW.h", "d3/dd3/___g_l_f_w_8h.html", null ],
    [ "_GTK.h", "d2/d4b/___g_t_k_8h.html", "d2/d4b/___g_t_k_8h" ],
    [ "_ImGui.h", "d1/d3d/___im_gui_8h.html", "d1/d3d/___im_gui_8h" ],
    [ "_Vulkan.h", "d3/d11/___vulkan_8h.html", null ],
    [ "add.c", "d3/d0d/add_8c.html", "d3/d0d/add_8c" ],
    [ "AES.cpp", "da/d98/_a_e_s_8cpp.html", null ],
    [ "AES.h", "d4/d5e/_a_e_s_8h.html", "d4/d5e/_a_e_s_8h" ],
    [ "ag_dec.c", "d7/d3b/ag__dec_8c.html", "d7/d3b/ag__dec_8c" ],
    [ "ag_enc.c", "da/d7b/ag__enc_8c.html", "da/d7b/ag__enc_8c" ],
    [ "aglib.h", "df/d58/aglib_8h.html", "df/d58/aglib_8h" ],
    [ "aiff.c", "dc/de9/aiff_8c.html", "dc/de9/aiff_8c" ],
    [ "alac.c", "d2/d08/alac_8c.html", "d2/d08/alac_8c" ],
    [ "alac_codec.h", "da/dbf/alac__codec_8h.html", "da/dbf/alac__codec_8h" ],
    [ "alac_decoder.c", "da/d39/alac__decoder_8c.html", "da/d39/alac__decoder_8c" ],
    [ "alac_decoder.h", "dd/df7/alac__decoder_8h.html", "dd/df7/alac__decoder_8h" ],
    [ "alac_encoder.c", "db/dde/alac__encoder_8c.html", "db/dde/alac__encoder_8c" ],
    [ "ALACAudioTypes.h", "dd/d14/_a_l_a_c_audio_types_8h.html", "dd/d14/_a_l_a_c_audio_types_8h" ],
    [ "ALACBitUtilities.c", "d0/d47/_a_l_a_c_bit_utilities_8c.html", "d0/d47/_a_l_a_c_bit_utilities_8c" ],
    [ "ALACBitUtilities.h", "da/d9e/_a_l_a_c_bit_utilities_8h.html", "da/d9e/_a_l_a_c_bit_utilities_8h" ],
    [ "ALACDecoder.h", "dd/d24/_a_l_a_c_decoder_8h.html", [
      [ "ALACDecoder", "d3/d8c/class_a_l_a_c_decoder.html", "d3/d8c/class_a_l_a_c_decoder" ]
    ] ],
    [ "ALACEncoder.h", "d3/d6d/_a_l_a_c_encoder_8h.html", [
      [ "ALACEncoder", "d3/d36/class_a_l_a_c_encoder.html", "d3/d36/class_a_l_a_c_encoder" ]
    ] ],
    [ "alaw.c", "df/d27/alaw_8c.html", "df/d27/alaw_8c" ],
    [ "math/include/AuroraFW/Math/Algorithm.h", "d7/dc0/math_2include_2_aurora_f_w_2_math_2_algorithm_8h.html", "d7/dc0/math_2include_2_aurora_f_w_2_math_2_algorithm_8h" ],
    [ "stdl/include/AuroraFW/STDL/Internal/STL/Algorithm.h", "d0/d2f/stdl_2include_2_aurora_f_w_2_s_t_d_l_2_internal_2_s_t_l_2_algorithm_8h.html", null ],
    [ "stdl/include/AuroraFW/STDL/STL/Algorithm.h", "d5/dca/stdl_2include_2_aurora_f_w_2_s_t_d_l_2_s_t_l_2_algorithm_8h.html", "d5/dca/stdl_2include_2_aurora_f_w_2_s_t_d_l_2_s_t_l_2_algorithm_8h" ],
    [ "Allocator.cpp", "d0/d55/_allocator_8cpp.html", null ],
    [ "Allocator.h", "df/d4d/_allocator_8h.html", "df/d4d/_allocator_8h" ],
    [ "allocators.h", "da/dfb/allocators_8h.html", [
      [ "CrtAllocator", "dc/dbb/class_crt_allocator.html", "dc/dbb/class_crt_allocator" ],
      [ "MemoryPoolAllocator", "dd/dec/class_memory_pool_allocator.html", "dd/dec/class_memory_pool_allocator" ]
    ] ],
    [ "core/src/Application.cpp", "d9/d3f/core_2src_2_application_8cpp.html", null ],
    [ "gengine/core/src/Application.cpp", "d5/deb/gengine_2core_2src_2_application_8cpp.html", null ],
    [ "gui/src/Application.cpp", "dd/d45/gui_2src_2_application_8cpp.html", null ],
    [ "core/include/AuroraFW/Core/Application.h", "da/db5/core_2include_2_aurora_f_w_2_core_2_application_8h.html", [
      [ "Application", "dd/dec/struct_aurora_f_w_1_1_application.html", "dd/dec/struct_aurora_f_w_1_1_application" ]
    ] ],
    [ "gengine/core/include/AuroraFW/GEngine/Application.h", "d0/d1f/gengine_2core_2include_2_aurora_f_w_2_g_engine_2_application_8h.html", [
      [ "Application", "da/df1/class_aurora_f_w_1_1_g_engine_1_1_application.html", "da/df1/class_aurora_f_w_1_1_g_engine_1_1_application" ]
    ] ],
    [ "gui/include/AuroraFW/GUI/Application.h", "d7/db6/gui_2include_2_aurora_f_w_2_g_u_i_2_application_8h.html", "d7/db6/gui_2include_2_aurora_f_w_2_g_u_i_2_application_8h" ],
    [ "Application_impl.h", "dd/dd2/_application__impl_8h.html", null ],
    [ "ApplicationContext.cpp", "d6/dec/_application_context_8cpp.html", null ],
    [ "ApplicationContext.h", "d4/d3b/_application_context_8h.html", [
      [ "ApplicationContext", "dc/d6f/class_aurora_f_w_1_1_application_context.html", "dc/d6f/class_aurora_f_w_1_1_application_context" ]
    ] ],
    [ "Architecture.h", "dc/dd2/_architecture_8h.html", "dc/dd2/_architecture_8h" ],
    [ "Internal/LibC/Assert.h", "d6/dab/_internal_2_lib_c_2_assert_8h.html", null ],
    [ "LibC/Assert.h", "dc/de5/_lib_c_2_assert_8h.html", null ],
    [ "AssetManager.cpp", "df/da4/_asset_manager_8cpp.html", null ],
    [ "AssetManager.h", "da/d65/_asset_manager_8h.html", "da/d65/_asset_manager_8h" ],
    [ "AssetType.cpp", "dc/d5a/_asset_type_8cpp.html", null ],
    [ "AssetType.h", "d8/d7e/_asset_type_8h.html", [
      [ "TextureAsset", "dd/d1b/class_aurora_f_w_1_1_g_engine_1_1_texture_asset.html", "dd/d1b/class_aurora_f_w_1_1_g_engine_1_1_texture_asset" ]
    ] ],
    [ "au.c", "dd/dd0/au_8c.html", "dd/dd0/au_8c" ],
    [ "audio_detect.c", "d6/d68/audio__detect_8c.html", "d6/d68/audio__detect_8c" ],
    [ "AudioBackend.cpp", "d2/d41/_audio_backend_8cpp.html", null ],
    [ "AudioBackend.h", "d0/dea/_audio_backend_8h.html", "d0/dea/_audio_backend_8h" ],
    [ "AudioEffect.h", "d6/db8/_audio_effect_8h.html", [
      [ "AudioEffect", "d6/d28/struct_aurora_f_w_1_1_audio_manager_1_1_audio_effect.html", "d6/d28/struct_aurora_f_w_1_1_audio_manager_1_1_audio_effect" ],
      [ "HighPassEffect", "dc/d43/struct_aurora_f_w_1_1_audio_manager_1_1_high_pass_effect.html", "dc/d43/struct_aurora_f_w_1_1_audio_manager_1_1_high_pass_effect" ],
      [ "LowPassEffect", "d6/d02/struct_aurora_f_w_1_1_audio_manager_1_1_low_pass_effect.html", "d6/d02/struct_aurora_f_w_1_1_audio_manager_1_1_low_pass_effect" ],
      [ "ReverbEffect", "da/d8d/struct_aurora_f_w_1_1_audio_manager_1_1_reverb_effect.html", "da/d8d/struct_aurora_f_w_1_1_audio_manager_1_1_reverb_effect" ]
    ] ],
    [ "AudioInput.cpp", "d7/dec/_audio_input_8cpp.html", "d7/dec/_audio_input_8cpp" ],
    [ "AudioInput.h", "d8/dce/_audio_input_8h.html", [
      [ "AudioIStream", "da/d61/struct_aurora_f_w_1_1_audio_manager_1_1_audio_i_stream.html", "da/d61/struct_aurora_f_w_1_1_audio_manager_1_1_audio_i_stream" ]
    ] ],
    [ "AudioOutput.cpp", "d2/de7/_audio_output_8cpp.html", "d2/de7/_audio_output_8cpp" ],
    [ "AudioOutput.h", "da/d25/_audio_output_8h.html", "da/d25/_audio_output_8h" ],
    [ "AudioUtils.cpp", "d1/dd7/_audio_utils_8cpp.html", null ],
    [ "AudioUtils.h", "dc/d21/_audio_utils_8h.html", [
      [ "AudioInfo", "d0/d6e/struct_aurora_f_w_1_1_audio_manager_1_1_audio_info.html", "d0/d6e/struct_aurora_f_w_1_1_audio_manager_1_1_audio_info" ]
    ] ],
    [ "Aurora.h", "df/d93/_aurora_8h.html", null ],
    [ "avr.c", "d1/d26/avr_8c.html", "d1/d26/avr_8c" ],
    [ "biginteger.h", "d1/d49/biginteger_8h.html", [
      [ "BigInteger", "de/d92/classinternal_1_1_big_integer.html", "de/d92/classinternal_1_1_big_integer" ]
    ] ],
    [ "binheader_writef_check.py", "d5/da0/binheader__writef__check_8py.html", "d5/da0/binheader__writef__check_8py" ],
    [ "broadcast.c", "d2/d33/broadcast_8c.html", "d2/d33/broadcast_8c" ],
    [ "Buffer.h", "d7/d1b/_buffer_8h.html", "d7/d1b/_buffer_8h" ],
    [ "Button.cpp", "d5/d4d/_button_8cpp.html", null ],
    [ "Button.h", "d2/daa/_button_8h.html", "d2/daa/_button_8h" ],
    [ "caf.c", "d3/d93/caf_8c.html", "d3/d93/caf_8c" ],
    [ "Callback.h", "d0/d4b/_callback_8h.html", "d0/d4b/_callback_8h" ],
    [ "cart.c", "d2/de2/cart_8c.html", "d2/de2/cart_8c" ],
    [ "CFG.cpp", "d7/d6c/_c_f_g_8cpp.html", null ],
    [ "CFG.h", "d4/d1c/_c_f_g_8h.html", [
      [ "CFG", "d7/db9/classspirv__cross_1_1_c_f_g.html", "d7/db9/classspirv__cross_1_1_c_f_g" ],
      [ "DominatorBuilder", "dc/de9/classspirv__cross_1_1_dominator_builder.html", "dc/de9/classspirv__cross_1_1_dominator_builder" ]
    ] ],
    [ "chanmap.c", "d1/d9c/chanmap_8c.html", "d1/d9c/chanmap_8c" ],
    [ "chanmap.h", "d8/def/chanmap_8h.html", "d8/def/chanmap_8h" ],
    [ "chunk.c", "d8/d39/chunk_8c.html", "d8/d39/chunk_8c" ],
    [ "CircularShift.cpp", "d8/d29/_circular_shift_8cpp.html", "d8/d29/_circular_shift_8cpp" ],
    [ "CircularShift.h", "d5/d8d/_circular_shift_8h.html", "d5/d8d/_circular_shift_8h" ],
    [ "CLI.h", "d8/db8/_c_l_i_8h.html", null ],
    [ "code.c", "d3/d06/code_8c.html", "d3/d06/code_8c" ],
    [ "cli/src/Color.cpp", "d4/da4/cli_2src_2_color_8cpp.html", "d4/da4/cli_2src_2_color_8cpp" ],
    [ "gengine/core/src/Color.cpp", "d2/dfa/gengine_2core_2src_2_color_8cpp.html", null ],
    [ "cli/include/AuroraFW/CLI/Color.h", "df/dd1/cli_2include_2_aurora_f_w_2_c_l_i_2_color_8h.html", "df/dd1/cli_2include_2_aurora_f_w_2_c_l_i_2_color_8h" ],
    [ "gengine/core/include/AuroraFW/GEngine/Color.h", "d5/de1/gengine_2core_2include_2_aurora_f_w_2_g_engine_2_color_8h.html", "d5/de1/gengine_2core_2include_2_aurora_f_w_2_g_engine_2_color_8h" ],
    [ "command.c", "d5/d2e/command_8c.html", "d5/d2e/command_8c" ],
    [ "CommandBuffer.h", "d7/d22/_command_buffer_8h.html", null ],
    [ "common.c", "d8/d19/common_8c.html", "d8/d19/common_8c" ],
    [ "audio/src/sndfile/common.h", "d3/df3/audio_2src_2sndfile_2common_8h.html", "d3/df3/audio_2src_2sndfile_2common_8h" ],
    [ "gengine/core/include/AuroraFW/GEngine/SPIR-V/common.h", "de/d1a/gengine_2core_2include_2_aurora_f_w_2_g_engine_2_s_p_i_r-_v_2common_8h.html", "de/d1a/gengine_2core_2include_2_aurora_f_w_2_g_engine_2_s_p_i_r-_v_2common_8h" ],
    [ "Compiler.h", "da/da7/_compiler_8h.html", "da/da7/_compiler_8h" ],
    [ "audio/src/sndfile/GSM610/config.h", "da/df2/audio_2src_2sndfile_2_g_s_m610_2config_8h.html", "da/df2/audio_2src_2sndfile_2_g_s_m610_2config_8h" ],
    [ "corelib/include/AuroraFW/Internal/config.h", "d2/d06/corelib_2include_2_aurora_f_w_2_internal_2config_8h.html", "d2/d06/corelib_2include_2_aurora_f_w_2_internal_2config_8h" ],
    [ "gengine/core/include/AuroraFW/GEngine/ImGui/Internal/config.h", "df/d32/gengine_2core_2include_2_aurora_f_w_2_g_engine_2_im_gui_2_internal_2config_8h.html", null ],
    [ "stdl/include/AuroraFW/STDL/Internal/config.h", "d4/db1/stdl_2include_2_aurora_f_w_2_s_t_d_l_2_internal_2config_8h.html", "d4/db1/stdl_2include_2_aurora_f_w_2_s_t_d_l_2_internal_2config_8h" ],
    [ "Container.h", "d8/d9d/_container_8h.html", null ],
    [ "Context.c", "de/dc3/_context_8c.html", "de/dc3/_context_8c" ],
    [ "EGL/Context.c", "d2/dc8/_e_g_l_2_context_8c.html", "d2/dc8/_e_g_l_2_context_8c" ],
    [ "GLX/Context.c", "d8/d5c/_g_l_x_2_context_8c.html", "d8/d5c/_g_l_x_2_context_8c" ],
    [ "OSMesa/Context.c", "d9/d08/_o_s_mesa_2_context_8c.html", "d9/d08/_o_s_mesa_2_context_8c" ],
    [ "WGL/Context.c", "d7/d47/_w_g_l_2_context_8c.html", "d7/d47/_w_g_l_2_context_8c" ],
    [ "Context.cpp", "dd/df6/_context_8cpp.html", null ],
    [ "core/include/AuroraFW/GEngine/API/Context.h", "d8/dbc/core_2include_2_aurora_f_w_2_g_engine_2_a_p_i_2_context_8h.html", [
      [ "Context", "dc/d5c/class_aurora_f_w_1_1_g_engine_1_1_a_p_i_1_1_context.html", "dc/d5c/class_aurora_f_w_1_1_g_engine_1_1_a_p_i_1_1_context" ]
    ] ],
    [ "core/src/GLFW/EGL/Context.h", "d7/d92/core_2src_2_g_l_f_w_2_e_g_l_2_context_8h.html", "d7/d92/core_2src_2_g_l_f_w_2_e_g_l_2_context_8h" ],
    [ "core/src/GLFW/GLX/Context.h", "d3/d20/core_2src_2_g_l_f_w_2_g_l_x_2_context_8h.html", "d3/d20/core_2src_2_g_l_f_w_2_g_l_x_2_context_8h" ],
    [ "core/src/GLFW/NSGL/Context.h", "d9/d74/core_2src_2_g_l_f_w_2_n_s_g_l_2_context_8h.html", "d9/d74/core_2src_2_g_l_f_w_2_n_s_g_l_2_context_8h" ],
    [ "core/src/GLFW/OSMesa/Context.h", "de/d06/core_2src_2_g_l_f_w_2_o_s_mesa_2_context_8h.html", "de/d06/core_2src_2_g_l_f_w_2_o_s_mesa_2_context_8h" ],
    [ "core/src/GLFW/WGL/Context.h", "d2/d58/core_2src_2_g_l_f_w_2_w_g_l_2_context_8h.html", "d2/d58/core_2src_2_g_l_f_w_2_w_g_l_2_context_8h" ],
    [ "opengl/include/AuroraFW/GEngine/GL/Context.h", "db/d25/opengl_2include_2_aurora_f_w_2_g_engine_2_g_l_2_context_8h.html", [
      [ "GLContext", "d5/dc8/class_aurora_f_w_1_1_g_engine_1_1_g_l_context.html", "d5/dc8/class_aurora_f_w_1_1_g_engine_1_1_g_l_context" ]
    ] ],
    [ "vulkan/include/AuroraFW/GEngine/Vulkan/Context.h", "dd/de8/vulkan_2include_2_aurora_f_w_2_g_engine_2_vulkan_2_context_8h.html", [
      [ "VKContext", "d3/d79/class_aurora_f_w_1_1_g_engine_1_1_v_k_context.html", "d3/d79/class_aurora_f_w_1_1_g_engine_1_1_v_k_context" ],
      [ "PhysicalDevice", "d9/d26/struct_aurora_f_w_1_1_g_engine_1_1_vulkan_1_1_physical_device.html", "d9/d26/struct_aurora_f_w_1_1_g_engine_1_1_vulkan_1_1_physical_device" ]
    ] ],
    [ "Context.m", "d1/deb/_context_8m.html", "d1/deb/_context_8m" ],
    [ "Core.h", "d4/d09/_core_8h.html", null ],
    [ "CPP.cpp", "df/dc0/_c_p_p_8cpp.html", null ],
    [ "CPP.h", "d9/d19/_c_p_p_8h.html", [
      [ "CompilerCPP", "d2/d0e/classspirv__cross_1_1_compiler_c_p_p.html", "d2/d0e/classspirv__cross_1_1_compiler_c_p_p" ]
    ] ],
    [ "create_symbols_file.py", "dd/db5/create__symbols__file_8py.html", "dd/db5/create__symbols__file_8py" ],
    [ "Cross.cpp", "dd/db9/_cross_8cpp.html", "dd/db9/_cross_8cpp" ],
    [ "Cross.h", "de/d39/_cross_8h.html", "de/d39/_cross_8h" ],
    [ "CrossUtil.cpp", "de/dbc/_cross_util_8cpp.html", "de/dbc/_cross_util_8cpp" ],
    [ "CrossUtil.h", "da/d22/_cross_util_8h.html", "da/d22/_cross_util_8h" ],
    [ "Crypto.h", "d3/d3a/_crypto_8h.html", null ],
    [ "cursorstreamwrapper.h", "d7/dd3/cursorstreamwrapper_8h.html", [
      [ "CursorStreamWrapper", "db/daf/class_cursor_stream_wrapper.html", "db/daf/class_cursor_stream_wrapper" ]
    ] ],
    [ "CustomLayout.h", "d0/d99/_custom_layout_8h.html", [
      [ "CustomLayout", "db/d3b/class_aurora_f_w_1_1_g_u_i_1_1_custom_layout.html", "db/d3b/class_aurora_f_w_1_1_g_u_i_1_1_custom_layout" ]
    ] ],
    [ "debug.py", "d2/dee/debug_8py.html", "d2/dee/debug_8py" ],
    [ "DebugManager.cpp", "d0/daa/_debug_manager_8cpp.html", null ],
    [ "DebugManager.h", "da/dee/_debug_manager_8h.html", [
      [ "DebugManager", "d7/dae/class_aurora_f_w_1_1_debug_manager.html", "d7/dae/class_aurora_f_w_1_1_debug_manager" ]
    ] ],
    [ "decode.c", "da/d0d/decode_8c.html", "da/d0d/decode_8c" ],
    [ "dither.c", "d9/dbb/dither_8c.html", "d9/dbb/dither_8c" ],
    [ "diyfp.h", "d9/dd2/diyfp_8h.html", "d9/dd2/diyfp_8h" ],
    [ "document.h", "db/df5/document_8h.html", "db/df5/document_8h" ],
    [ "double64.c", "d9/d17/double64_8c.html", "d9/d17/double64_8c" ],
    [ "dp_dec.c", "d5/df9/dp__dec_8c.html", "d5/df9/dp__dec_8c" ],
    [ "dp_enc.c", "d2/dc8/dp__enc_8c.html", "d2/dc8/dp__enc_8c" ],
    [ "dplib.h", "db/d31/dplib_8h.html", "db/d31/dplib_8h" ],
    [ "Draw.cpp", "d2/d32/_draw_8cpp.html", "d2/d32/_draw_8cpp" ],
    [ "dtoa.h", "d2/ded/dtoa_8h.html", "d2/ded/dtoa_8h" ],
    [ "dwd.c", "d4/da3/dwd_8c.html", "d4/da3/dwd_8c" ],
    [ "dwvw.c", "da/d74/dwvw_8c.html", "da/d74/dwvw_8c" ],
    [ "c/loader/egl.py", "dc/d06/c_2loader_2egl_8py.html", "dc/d06/c_2loader_2egl_8py" ],
    [ "d/loader/egl.py", "de/dc0/d_2loader_2egl_8py.html", "de/dc0/d_2loader_2egl_8py" ],
    [ "nim/loader/egl.py", "d9/d2d/nim_2loader_2egl_8py.html", "d9/d2d/nim_2loader_2egl_8py" ],
    [ "volt/loader/egl.py", "d3/d4f/volt_2loader_2egl_8py.html", "d3/d4f/volt_2loader_2egl_8py" ],
    [ "en.h", "de/d76/en_8h.html", "de/d76/en_8h" ],
    [ "encodedstream.h", "d8/d4d/encodedstream_8h.html", "d8/d4d/encodedstream_8h" ],
    [ "encodings.h", "de/d06/encodings_8h.html", "de/d06/encodings_8h" ],
    [ "Endian.h", "d7/d30/_endian_8h.html", null ],
    [ "EndianPortable.h", "de/d33/_endian_portable_8h.html", "de/d33/_endian_portable_8h" ],
    [ "error.h", "da/d41/error_8h.html", "da/d41/error_8h" ],
    [ "File.cpp", "de/d7b/_file_8cpp.html", "de/d7b/_file_8cpp" ],
    [ "File.h", "df/d0c/_file_8h.html", "df/d0c/_file_8h" ],
    [ "file_io.c", "d1/dfa/file__io_8c.html", "d1/dfa/file__io_8c" ],
    [ "filereadstream.h", "d1/d0d/filereadstream_8h.html", [
      [ "FileReadStream", "d1/d0f/class_file_read_stream.html", "d1/d0f/class_file_read_stream" ]
    ] ],
    [ "filewritestream.h", "d2/d33/filewritestream_8h.html", "d2/d33/filewritestream_8h" ],
    [ "flac.c", "d1/d6e/flac_8c.html", "d1/d6e/flac_8c" ],
    [ "Flags.h", "dd/ded/_flags_8h.html", "dd/ded/_flags_8h" ],
    [ "Internal/LibC/Float.h", "de/dd9/_internal_2_lib_c_2_float_8h.html", null ],
    [ "LibC/Float.h", "dd/d5c/_lib_c_2_float_8h.html", "dd/d5c/_lib_c_2_float_8h" ],
    [ "float32.c", "d2/daa/float32_8c.html", "d2/daa/float32_8c" ],
    [ "Frustum.h", "d5/d69/_frustum_8h.html", "d5/d69/_frustum_8h" ],
    [ "fwd.h", "db/db1/fwd_8h.html", "db/db1/fwd_8h" ],
    [ "g721.c", "d7/d9b/g721_8c.html", "d7/d9b/g721_8c" ],
    [ "g723_16.c", "d0/dfe/g723__16_8c.html", "d0/dfe/g723__16_8c" ],
    [ "g723_24.c", "d9/d4b/g723__24_8c.html", "d9/d4b/g723__24_8c" ],
    [ "g723_40.c", "d2/df2/g723__40_8c.html", "d2/df2/g723__40_8c" ],
    [ "G72x/g72x.c", "d2/d77/_g72x_2g72x_8c.html", "d2/d77/_g72x_2g72x_8c" ],
    [ "g72x.c", "dd/ded/g72x_8c.html", "dd/ded/g72x_8c" ],
    [ "g72x.h", "d5/d99/g72x_8h.html", "d5/d99/g72x_8h" ],
    [ "g72x_priv.h", "d9/d49/g72x__priv_8h.html", "d9/d49/g72x__priv_8h" ],
    [ "g72x_test.c", "d9/db8/g72x__test_8c.html", "d9/db8/g72x__test_8c" ],
    [ "c/generator.py", "d2/dd3/c_2generator_8py.html", "d2/dd3/c_2generator_8py" ],
    [ "common/generator.py", "d5/d3a/common_2generator_8py.html", "d5/d3a/common_2generator_8py" ],
    [ "d/generator.py", "de/da8/d_2generator_8py.html", "de/da8/d_2generator_8py" ],
    [ "nim/generator.py", "d9/ddf/nim_2generator_8py.html", "d9/ddf/nim_2generator_8py" ],
    [ "volt/generator.py", "d0/d5e/volt_2generator_8py.html", "d0/d5e/volt_2generator_8py" ],
    [ "GL.h", "d9/dd7/_g_l_8h.html", "d9/dd7/_g_l_8h" ],
    [ "c/loader/gl.py", "db/d43/c_2loader_2gl_8py.html", "db/d43/c_2loader_2gl_8py" ],
    [ "d/loader/gl.py", "dd/d85/d_2loader_2gl_8py.html", "dd/d85/d_2loader_2gl_8py" ],
    [ "nim/loader/gl.py", "da/dfb/nim_2loader_2gl_8py.html", "da/dfb/nim_2loader_2gl_8py" ],
    [ "volt/loader/gl.py", "db/da6/volt_2loader_2gl_8py.html", "db/da6/volt_2loader_2gl_8py" ],
    [ "GLBuffer.cpp", "db/d55/_g_l_buffer_8cpp.html", null ],
    [ "GLContext.cpp", "db/d4c/_g_l_context_8cpp.html", null ],
    [ "glfw3.h", "de/dc4/glfw3_8h.html", "de/dc4/glfw3_8h" ],
    [ "glfw3native.h", "d0/d39/glfw3native_8h.html", null ],
    [ "GLGlobal.cpp", "d9/d26/_g_l_global_8cpp.html", "d9/d26/_g_l_global_8cpp" ],
    [ "GLImGuiLoader.cpp", "d5/dc3/_g_l_im_gui_loader_8cpp.html", null ],
    [ "GLIndexBuffer.cpp", "db/d15/_g_l_index_buffer_8cpp.html", null ],
    [ "corelib/include/AuroraFW/Global.h", "db/d51/corelib_2include_2_aurora_f_w_2_global_8h.html", "db/d51/corelib_2include_2_aurora_f_w_2_global_8h" ],
    [ "gengine/opengl/include/AuroraFW/GEngine/GL/Global.h", "d1/d29/gengine_2opengl_2include_2_aurora_f_w_2_g_engine_2_g_l_2_global_8h.html", "d1/d29/gengine_2opengl_2include_2_aurora_f_w_2_g_engine_2_g_l_2_global_8h" ],
    [ "gengine/vulkan/include/AuroraFW/GEngine/Vulkan/Global.h", "d0/dc8/gengine_2vulkan_2include_2_aurora_f_w_2_g_engine_2_vulkan_2_global_8h.html", null ],
    [ "GLProgram.cpp", "d7/de8/_g_l_program_8cpp.html", null ],
    [ "GLRenderer.cpp", "d2/d0d/_g_l_renderer_8cpp.html", null ],
    [ "GLShader.cpp", "d5/dc5/_g_l_shader_8cpp.html", null ],
    [ "GLSL.cpp", "dd/d12/_g_l_s_l_8cpp.html", "dd/d12/_g_l_s_l_8cpp" ],
    [ "GLSL.h", "d0/d75/_g_l_s_l_8h.html", "d0/d75/_g_l_s_l_8h" ],
    [ "GLVertexArray.cpp", "d0/d11/_g_l_vertex_array_8cpp.html", null ],
    [ "c/loader/glx.py", "d8/d77/c_2loader_2glx_8py.html", "d8/d77/c_2loader_2glx_8py" ],
    [ "d/loader/glx.py", "d7/d9d/d_2loader_2glx_8py.html", "d7/d9d/d_2loader_2glx_8py" ],
    [ "nim/loader/glx.py", "d7/ddb/nim_2loader_2glx_8py.html", "d7/ddb/nim_2loader_2glx_8py" ],
    [ "volt/loader/glx.py", "d8/d23/volt_2loader_2glx_8py.html", "d8/d23/volt_2loader_2glx_8py" ],
    [ "GraphicsContext.cpp", "d0/dd1/_graphics_context_8cpp.html", null ],
    [ "GraphicsContext.h", "d8/d38/_graphics_context_8h.html", [
      [ "GraphicsContext", "d3/d0d/class_aurora_f_w_1_1_g_engine_1_1_graphics_context.html", "d3/d0d/class_aurora_f_w_1_1_g_engine_1_1_graphics_context" ]
    ] ],
    [ "gsm.h", "dc/d96/gsm_8h.html", "dc/d96/gsm_8h" ],
    [ "gsm610.c", "df/dbd/gsm610_8c.html", "df/dbd/gsm610_8c" ],
    [ "gsm610_priv.h", "d1/d45/gsm610__priv_8h.html", "d1/d45/gsm610__priv_8h" ],
    [ "gsm_create.c", "d9/d02/gsm__create_8c.html", "d9/d02/gsm__create_8c" ],
    [ "gsm_decode.c", "d7/d5d/gsm__decode_8c.html", "d7/d5d/gsm__decode_8c" ],
    [ "gsm_destroy.c", "da/dfd/gsm__destroy_8c.html", "da/dfd/gsm__destroy_8c" ],
    [ "gsm_encode.c", "d0/dc6/gsm__encode_8c.html", "d0/dc6/gsm__encode_8c" ],
    [ "gsm_option.c", "db/d24/gsm__option_8c.html", "db/d24/gsm__option_8c" ],
    [ "hellowindow2.cpp", "d6/d39/hellowindow2_8cpp.html", "d6/d39/hellowindow2_8cpp" ],
    [ "HLSL.cpp", "d1/db6/_h_l_s_l_8cpp.html", "d1/db6/_h_l_s_l_8cpp" ],
    [ "HLSL.h", "d7/d02/_h_l_s_l_8h.html", [
      [ "CompilerHLSL", "d0/dd7/classspirv__cross_1_1_compiler_h_l_s_l.html", "d0/dd7/classspirv__cross_1_1_compiler_h_l_s_l" ],
      [ "Options", "dc/d63/structspirv__cross_1_1_compiler_h_l_s_l_1_1_options.html", "dc/d63/structspirv__cross_1_1_compiler_h_l_s_l_1_1_options" ],
      [ "HLSLVertexAttributeRemap", "d0/d72/structspirv__cross_1_1_h_l_s_l_vertex_attribute_remap.html", "d0/d72/structspirv__cross_1_1_h_l_s_l_vertex_attribute_remap" ],
      [ "RootConstants", "d2/d50/structspirv__cross_1_1_root_constants.html", "d2/d50/structspirv__cross_1_1_root_constants" ]
    ] ],
    [ "htk.c", "d0/d62/htk_8c.html", "d0/d62/htk_8c" ],
    [ "id3.c", "d2/d6e/id3_8c.html", "d2/d6e/id3_8c" ],
    [ "ieee754.h", "d0/d3a/ieee754_8h.html", [
      [ "Double", "d5/d26/classinternal_1_1_double.html", "d5/d26/classinternal_1_1_double" ]
    ] ],
    [ "ima_adpcm.c", "d8/dea/ima__adpcm_8c.html", "d8/dea/ima__adpcm_8c" ],
    [ "ima_oki_adpcm.c", "da/dcc/ima__oki__adpcm_8c.html", "da/dcc/ima__oki__adpcm_8c" ],
    [ "ima_oki_adpcm.h", "de/d89/ima__oki__adpcm_8h.html", "de/d89/ima__oki__adpcm_8h" ],
    [ "Image.cpp", "d0/dac/_image_8cpp.html", null ],
    [ "Image.h", "d9/de5/_image_8h.html", "d9/de5/_image_8h" ],
    [ "ImGui.cpp", "dd/d50/_im_gui_8cpp.html", "dd/d50/_im_gui_8cpp" ],
    [ "ImGui.h", "d7/d96/_im_gui_8h.html", "d7/d96/_im_gui_8h" ],
    [ "core/include/AuroraFW/GEngine/API/IndexBuffer.h", "dc/d2f/core_2include_2_aurora_f_w_2_g_engine_2_a_p_i_2_index_buffer_8h.html", [
      [ "IndexBuffer", "d6/d9a/class_aurora_f_w_1_1_g_engine_1_1_a_p_i_1_1_index_buffer.html", "d6/d9a/class_aurora_f_w_1_1_g_engine_1_1_a_p_i_1_1_index_buffer" ]
    ] ],
    [ "opengl/include/AuroraFW/GEngine/GL/IndexBuffer.h", "db/d5c/opengl_2include_2_aurora_f_w_2_g_engine_2_g_l_2_index_buffer_8h.html", [
      [ "GLIndexBuffer", "d7/d5b/class_aurora_f_w_1_1_g_engine_1_1_a_p_i_1_1_g_l_index_buffer.html", "d7/d5b/class_aurora_f_w_1_1_g_engine_1_1_a_p_i_1_1_g_l_index_buffer" ]
    ] ],
    [ "InfoMemory.cpp", "d1/dad/_info_memory_8cpp.html", "d1/dad/_info_memory_8cpp" ],
    [ "InfoSystem.cpp", "d5/da7/_info_system_8cpp.html", "d5/da7/_info_system_8cpp" ],
    [ "Init.c", "dd/d96/_init_8c.html", "dd/d96/_init_8c" ],
    [ "Mir/Init.c", "d7/d88/_mir_2_init_8c.html", "d7/d88/_mir_2_init_8c" ],
    [ "NULL/Init.c", "db/daa/_n_u_l_l_2_init_8c.html", "db/daa/_n_u_l_l_2_init_8c" ],
    [ "Wayland/Init.c", "d4/d4b/_wayland_2_init_8c.html", "d4/d4b/_wayland_2_init_8c" ],
    [ "Win32/Init.c", "d8/d27/_win32_2_init_8c.html", "d8/d27/_win32_2_init_8c" ],
    [ "X11/Init.c", "d6/d6d/_x11_2_init_8c.html", "d6/d6d/_x11_2_init_8c" ],
    [ "Init.m", "d1/dba/_init_8m.html", "d1/dba/_init_8m" ],
    [ "Input.c", "d5/dd8/_input_8c.html", "d5/dd8/_input_8c" ],
    [ "cli/src/Input.cpp", "de/d3a/cli_2src_2_input_8cpp.html", "de/d3a/cli_2src_2_input_8cpp" ],
    [ "gengine/core/src/Input.cpp", "de/d95/gengine_2core_2src_2_input_8cpp.html", null ],
    [ "cli/include/AuroraFW/CLI/Input.h", "d7/d86/cli_2include_2_aurora_f_w_2_c_l_i_2_input_8h.html", "d7/d86/cli_2include_2_aurora_f_w_2_c_l_i_2_input_8h" ],
    [ "gengine/core/include/AuroraFW/GEngine/Input.h", "d2/d7b/gengine_2core_2include_2_aurora_f_w_2_g_engine_2_input_8h.html", "d2/d7b/gengine_2core_2include_2_aurora_f_w_2_g_engine_2_input_8h" ],
    [ "io/include/AuroraFW/IO/Input.h", "de/d43/io_2include_2_aurora_f_w_2_i_o_2_input_8h.html", null ],
    [ "InputListener.cpp", "d1/d08/_input_listener_8cpp.html", null ],
    [ "InputListener.h", "da/dca/_input_listener_8h.html", [
      [ "InputListener", "da/d94/class_aurora_f_w_1_1_input_listener.html", "da/d94/class_aurora_f_w_1_1_input_listener" ],
      [ "KeyboardEvent", "d7/db0/struct_aurora_f_w_1_1_keyboard_event.html", "d7/db0/struct_aurora_f_w_1_1_keyboard_event" ],
      [ "MouseButtonEvent", "dd/dda/struct_aurora_f_w_1_1_mouse_button_event.html", "dd/dda/struct_aurora_f_w_1_1_mouse_button_event" ],
      [ "MouseMotionEvent", "d4/de0/struct_aurora_f_w_1_1_mouse_motion_event.html", "d4/de0/struct_aurora_f_w_1_1_mouse_motion_event" ],
      [ "MouseScrollEvent", "d4/d3e/struct_aurora_f_w_1_1_mouse_scroll_event.html", "d4/d3e/struct_aurora_f_w_1_1_mouse_scroll_event" ]
    ] ],
    [ "interleave.c", "de/d20/interleave_8c.html", "de/d20/interleave_8c" ],
    [ "Internal.h", "d9/d21/_internal_8h.html", "d9/d21/_internal_8h" ],
    [ "inttypes.h", "d3/dd6/inttypes_8h.html", "d3/dd6/inttypes_8h" ],
    [ "Internal/STL/IOStream.h", "dd/d4b/_internal_2_s_t_l_2_i_o_stream_8h.html", null ],
    [ "STL/IOStream.h", "d8/de2/_s_t_l_2_i_o_stream_8h.html", null ],
    [ "ircam.c", "de/d99/ircam_8c.html", "de/d99/ircam_8c" ],
    [ "Internal/STL/IStream.h", "d7/d96/_internal_2_s_t_l_2_i_stream_8h.html", null ],
    [ "STL/IStream.h", "d3/d2f/_s_t_l_2_i_stream_8h.html", null ],
    [ "istreamwrapper.h", "d4/de4/istreamwrapper_8h.html", "d4/de4/istreamwrapper_8h" ],
    [ "itoa.h", "de/d79/itoa_8h.html", "de/d79/itoa_8h" ],
    [ "Linux/Joystick.c", "d4/d24/_linux_2_joystick_8c.html", "d4/d24/_linux_2_joystick_8c" ],
    [ "NULL/Joystick.c", "d4/da6/_n_u_l_l_2_joystick_8c.html", "d4/da6/_n_u_l_l_2_joystick_8c" ],
    [ "Win32/Joystick.c", "d6/d75/_win32_2_joystick_8c.html", "d6/d75/_win32_2_joystick_8c" ],
    [ "Cocoa/Joystick.h", "d9/dcf/_cocoa_2_joystick_8h.html", "d9/dcf/_cocoa_2_joystick_8h" ],
    [ "Linux/Joystick.h", "d0/d8b/_linux_2_joystick_8h.html", "d0/d8b/_linux_2_joystick_8h" ],
    [ "NULL/Joystick.h", "d4/ddc/_n_u_l_l_2_joystick_8h.html", "d4/ddc/_n_u_l_l_2_joystick_8h" ],
    [ "Win32/Joystick.h", "dd/df7/_win32_2_joystick_8h.html", "dd/df7/_win32_2_joystick_8h" ],
    [ "Joystick.m", "d2/d27/_joystick_8m.html", "d2/d27/_joystick_8m" ],
    [ "Label.cpp", "db/db4/_label_8cpp.html", null ],
    [ "Label.h", "de/dfe/_label_8h.html", [
      [ "Label", "d6/dc0/class_aurora_f_w_1_1_g_u_i_1_1_label.html", "d6/dc0/class_aurora_f_w_1_1_g_u_i_1_1_label" ]
    ] ],
    [ "Layout.h", "d6/d48/_layout_8h.html", "d6/d48/_layout_8h" ],
    [ "Lexer.h", "dc/ddc/_lexer_8h.html", [
      [ "Lexer", "d0/d3f/class_aurora_f_w_1_1_parser_1_1_lexer.html", "d0/d3f/class_aurora_f_w_1_1_parser_1_1_lexer" ]
    ] ],
    [ "Internal/LibC/Limits.h", "d2/da0/_internal_2_lib_c_2_limits_8h.html", null ],
    [ "Internal/STL/Limits.h", "d4/d4a/_internal_2_s_t_l_2_limits_8h.html", null ],
    [ "LibC/Limits.h", "d2/dc3/_lib_c_2_limits_8h.html", null ],
    [ "STL/Limits.h", "d3/d70/_s_t_l_2_limits_8h.html", null ],
    [ "Loader.cpp", "d1/d51/_loader_8cpp.html", "d1/d51/_loader_8cpp" ],
    [ "core/include/AuroraFW/GEngine/ImGui/Loader.h", "da/df7/core_2include_2_aurora_f_w_2_g_engine_2_im_gui_2_loader_8h.html", [
      [ "ImGuiLoader", "d3/d2d/class_aurora_f_w_1_1_g_engine_1_1_im_gui_loader.html", "d3/d2d/class_aurora_f_w_1_1_g_engine_1_1_im_gui_loader" ]
    ] ],
    [ "opengl/include/AuroraFW/GEngine/GL/ImGui/Loader.h", "d0/de3/opengl_2include_2_aurora_f_w_2_g_engine_2_g_l_2_im_gui_2_loader_8h.html", [
      [ "GLImGuiLoader", "d1/ddd/class_aurora_f_w_1_1_g_engine_1_1_g_l_im_gui_loader.html", "d1/ddd/class_aurora_f_w_1_1_g_engine_1_1_g_l_im_gui_loader" ]
    ] ],
    [ "loader.py", "d4/de3/loader_8py.html", [
      [ "BaseLoader", "d4/d29/classglloader_1_1lang_1_1common_1_1loader_1_1_base_loader.html", "d4/d29/classglloader_1_1lang_1_1common_1_1loader_1_1_base_loader" ],
      [ "NullLoader", "d4/df8/classglloader_1_1lang_1_1common_1_1loader_1_1_null_loader.html", "d4/df8/classglloader_1_1lang_1_1common_1_1loader_1_1_null_loader" ]
    ] ],
    [ "Log.h", "da/df4/_log_8h.html", "da/df4/_log_8h" ],
    [ "long_term.c", "da/d14/long__term_8c.html", "da/d14/long__term_8c" ],
    [ "lpc.c", "d4/d9b/lpc_8c.html", "d4/d9b/lpc_8c" ],
    [ "macos.c", "d1/d64/macos_8c.html", "d1/d64/macos_8c" ],
    [ "main.py", "dc/dba/main_8py.html", "dc/dba/main_8py" ],
    [ "Mappings.h", "d2/d4a/_mappings_8h.html", "d2/d4a/_mappings_8h" ],
    [ "mat4.c", "df/d69/mat4_8c.html", "df/d69/mat4_8c" ],
    [ "mat5.c", "d5/dbd/mat5_8c.html", "d5/dbd/mat5_8c" ],
    [ "math/include/AuroraFW/Math.h", "dc/da8/math_2include_2_aurora_f_w_2_math_8h.html", null ],
    [ "stdl/include/AuroraFW/STDL/Internal/LibC/Math.h", "d6/d49/stdl_2include_2_aurora_f_w_2_s_t_d_l_2_internal_2_lib_c_2_math_8h.html", null ],
    [ "stdl/include/AuroraFW/STDL/LibC/Math.h", "d5/dd3/stdl_2include_2_aurora_f_w_2_s_t_d_l_2_lib_c_2_math_8h.html", "d5/dd3/stdl_2include_2_aurora_f_w_2_s_t_d_l_2_lib_c_2_math_8h" ],
    [ "Matrix.h", "d0/d45/_matrix_8h.html", "d0/d45/_matrix_8h" ],
    [ "matrix_dec.c", "d7/df6/matrix__dec_8c.html", "d7/df6/matrix__dec_8c" ],
    [ "matrix_enc.c", "d5/d1c/matrix__enc_8c.html", "d5/d1c/matrix__enc_8c" ],
    [ "Matrix_impl.h", "db/d52/_matrix__impl_8h.html", null ],
    [ "matrixlib.h", "d0/d32/matrixlib_8h.html", "d0/d32/matrixlib_8h" ],
    [ "Memory.c", "dc/dd6/_memory_8c.html", "dc/dd6/_memory_8c" ],
    [ "Memory.h", "d3/de6/_memory_8h.html", "d3/de6/_memory_8h" ],
    [ "memorybuffer.h", "dc/de9/memorybuffer_8h.html", "dc/de9/memorybuffer_8h" ],
    [ "MemoryManager.cpp", "dd/dcb/_memory_manager_8cpp.html", null ],
    [ "MemoryManager.h", "d5/d87/_memory_manager_8h.html", [
      [ "MemoryLeakTracker", "d3/df2/class_aurora_f_w_1_1_memory_leak_tracker.html", "d3/df2/class_aurora_f_w_1_1_memory_leak_tracker" ],
      [ "MemoryManager", "db/da7/class_aurora_f_w_1_1_memory_manager.html", "db/da7/class_aurora_f_w_1_1_memory_manager" ],
      [ "MemoryStats", "d2/dd4/struct_aurora_f_w_1_1_memory_stats.html", "d2/dd4/struct_aurora_f_w_1_1_memory_stats" ]
    ] ],
    [ "memorystream.h", "dd/d3c/memorystream_8h.html", [
      [ "MemoryStream", "d4/d2d/struct_memory_stream.html", "d4/d2d/struct_memory_stream" ]
    ] ],
    [ "meta.h", "dd/dbc/meta_8h.html", null ],
    [ "ModularLexer.h", "d2/d32/_modular_lexer_8h.html", null ],
    [ "ModularParser.h", "d4/d90/_modular_parser_8h.html", [
      [ "ModularParser", "d6/d68/class_aurora_f_w_1_1_parser_1_1_modular_parser.html", null ]
    ] ],
    [ "ModularToken.h", "d3/dd7/_modular_token_8h.html", [
      [ "ModularToken", "d1/da6/class_aurora_f_w_1_1_parser_1_1_modular_token.html", null ]
    ] ],
    [ "Mir/Monitor.c", "d2/dc4/_mir_2_monitor_8c.html", "d2/dc4/_mir_2_monitor_8c" ],
    [ "Monitor.c", "d6/de4/_monitor_8c.html", "d6/de4/_monitor_8c" ],
    [ "NULL/Monitor.c", "d9/d05/_n_u_l_l_2_monitor_8c.html", "d9/d05/_n_u_l_l_2_monitor_8c" ],
    [ "Wayland/Monitor.c", "d7/d0c/_wayland_2_monitor_8c.html", "d7/d0c/_wayland_2_monitor_8c" ],
    [ "Win32/Monitor.c", "d5/d23/_win32_2_monitor_8c.html", "d5/d23/_win32_2_monitor_8c" ],
    [ "X11/Monitor.c", "d1/d37/_x11_2_monitor_8c.html", "d1/d37/_x11_2_monitor_8c" ],
    [ "Monitor.m", "de/df9/_monitor_8m.html", "de/df9/_monitor_8m" ],
    [ "mpc2k.c", "d9/daf/mpc2k_8c.html", "d9/daf/mpc2k_8c" ],
    [ "ms_adpcm.c", "d1/d70/ms__adpcm_8c.html", "d1/d70/ms__adpcm_8c" ],
    [ "MSL.cpp", "d4/d54/_m_s_l_8cpp.html", "d4/d54/_m_s_l_8cpp" ],
    [ "MSL.h", "db/d4b/_m_s_l_8h.html", "db/d4b/_m_s_l_8h" ],
    [ "NativeWindow.h", "de/dd6/_native_window_8h.html", null ],
    [ "new.c", "d4/d0b/new_8c.html", "d4/d0b/new_8c" ],
    [ "nist.c", "df/d86/nist_8c.html", "df/d86/nist_8c" ],
    [ "nms_adpcm.c", "d0/d9b/nms__adpcm_8c.html", "d0/d9b/nms__adpcm_8c" ],
    [ "ogg.c", "dc/d5b/ogg_8c.html", "dc/d5b/ogg_8c" ],
    [ "ogg.h", "d6/d68/ogg_8h.html", "d6/d68/ogg_8h" ],
    [ "ogg_opus.c", "d3/d1c/ogg__opus_8c.html", "d3/d1c/ogg__opus_8c" ],
    [ "ogg_pcm.c", "d4/d11/ogg__pcm_8c.html", "d4/d11/ogg__pcm_8c" ],
    [ "ogg_speex.c", "d9/df5/ogg__speex_8c.html", "d9/df5/ogg__speex_8c" ],
    [ "ogg_vorbis.c", "d4/d19/ogg__vorbis_8c.html", "d4/d19/ogg__vorbis_8c" ],
    [ "opener.py", "d5/da2/opener_8py.html", "d5/da2/opener_8py" ],
    [ "OpenGL.h", "d7/d72/_open_g_l_8h.html", null ],
    [ "OptionHandler.cpp", "d3/dc9/_option_handler_8cpp.html", null ],
    [ "OptionHandler.h", "d7/d5b/_option_handler_8h.html", "d7/d5b/_option_handler_8h" ],
    [ "Internal/STL/OStream.h", "d6/d53/_internal_2_s_t_l_2_o_stream_8h.html", null ],
    [ "STL/OStream.h", "d7/ddf/_s_t_l_2_o_stream_8h.html", null ],
    [ "ostreamwrapper.h", "dc/dc7/ostreamwrapper_8h.html", "dc/dc7/ostreamwrapper_8h" ],
    [ "Output.cpp", "dd/d4c/_output_8cpp.html", "dd/d4c/_output_8cpp" ],
    [ "Output.h", "d6/d77/_output_8h.html", "d6/d77/_output_8h" ],
    [ "paf.c", "dd/d5f/paf_8c.html", "dd/d5f/paf_8c" ],
    [ "parse.py", "d2/dba/parse_8py.html", "d2/dba/parse_8py" ],
    [ "Parser.h", "de/d40/_parser_8h.html", [
      [ "Parser", "d9/de7/class_aurora_f_w_1_1_math_1_1_parser.html", null ]
    ] ],
    [ "pcm.c", "d2/de2/pcm_8c.html", "d2/de2/pcm_8c" ],
    [ "Cocoa/Platform.h", "d2/d7c/_cocoa_2_platform_8h.html", "d2/d7c/_cocoa_2_platform_8h" ],
    [ "Mir/Platform.h", "d1/d05/_mir_2_platform_8h.html", "d1/d05/_mir_2_platform_8h" ],
    [ "NULL/Platform.h", "d5/dc9/_n_u_l_l_2_platform_8h.html", "d5/dc9/_n_u_l_l_2_platform_8h" ],
    [ "Wayland/Platform.h", "d8/dd4/_wayland_2_platform_8h.html", "d8/dd4/_wayland_2_platform_8h" ],
    [ "Win32/Platform.h", "dc/d45/_win32_2_platform_8h.html", "dc/d45/_win32_2_platform_8h" ],
    [ "X11/Platform.h", "dd/dc1/_x11_2_platform_8h.html", "dd/dc1/_x11_2_platform_8h" ],
    [ "pointer.h", "d5/d9f/pointer_8h.html", "d5/d9f/pointer_8h" ],
    [ "pow10.h", "de/dae/pow10_8h.html", "de/dae/pow10_8h" ],
    [ "preprocess.c", "d2/d47/preprocess_8c.html", "d2/d47/preprocess_8c" ],
    [ "prettywriter.h", "dc/dcf/prettywriter_8h.html", "dc/dcf/prettywriter_8h" ],
    [ "Program.h", "d0/d88/_program_8h.html", "d0/d88/_program_8h" ],
    [ "pvf.c", "d9/de4/pvf_8c.html", "d9/de4/pvf_8c" ],
    [ "rapidjson.h", "d4/dc0/rapidjson_8h.html", "d4/dc0/rapidjson_8h" ],
    [ "raw.c", "d5/d11/raw_8c.html", "d5/d11/raw_8c" ],
    [ "reader.h", "d6/dda/reader_8h.html", "d6/dda/reader_8h" ],
    [ "RectPack.h", "d0/de0/_rect_pack_8h.html", "d0/de0/_rect_pack_8h" ],
    [ "regex.h", "d1/d21/regex_8h.html", "d1/d21/regex_8h" ],
    [ "Renderable.h", "d9/d74/_renderable_8h.html", [
      [ "Renderable", "d0/d0c/class_aurora_f_w_1_1_g_engine_1_1_renderable.html", null ]
    ] ],
    [ "RenderAPI.h", "da/d7f/_render_a_p_i_8h.html", "da/d7f/_render_a_p_i_8h" ],
    [ "Renderer.cpp", "da/d84/_renderer_8cpp.html", null ],
    [ "core/include/AuroraFW/GEngine/API/Renderer.h", "df/d9c/core_2include_2_aurora_f_w_2_g_engine_2_a_p_i_2_renderer_8h.html", "df/d9c/core_2include_2_aurora_f_w_2_g_engine_2_a_p_i_2_renderer_8h" ],
    [ "opengl/include/AuroraFW/GEngine/GL/Renderer.h", "d5/d30/opengl_2include_2_aurora_f_w_2_g_engine_2_g_l_2_renderer_8h.html", [
      [ "GLRenderer", "d4/ddd/class_aurora_f_w_1_1_g_engine_1_1_g_l_renderer.html", "d4/ddd/class_aurora_f_w_1_1_g_engine_1_1_g_l_renderer" ]
    ] ],
    [ "vulkan/include/AuroraFW/GEngine/Vulkan/Renderer.h", "d6/d3d/vulkan_2include_2_aurora_f_w_2_g_engine_2_vulkan_2_renderer_8h.html", [
      [ "VKRenderer", "de/d85/class_aurora_f_w_1_1_g_engine_1_1_v_k_renderer.html", "de/d85/class_aurora_f_w_1_1_g_engine_1_1_v_k_renderer" ]
    ] ],
    [ "rf64.c", "d1/d86/rf64_8c.html", "d1/d86/rf64_8c" ],
    [ "Root.h", "d7/df2/_root_8h.html", [
      [ "Root", "d4/d9e/struct_aurora_f_w_1_1_g_engine_1_1_root.html", "d4/d9e/struct_aurora_f_w_1_1_g_engine_1_1_root" ]
    ] ],
    [ "rpe.c", "d6/d61/rpe_8c.html", "d6/d61/rpe_8c" ],
    [ "RTShader.cpp", "d9/dde/_r_t_shader_8cpp.html", null ],
    [ "RTShader.h", "db/d75/_r_t_shader_8h.html", [
      [ "RTShader", "d2/d43/class_aurora_f_w_1_1_g_engine_1_1_r_t_shader.html", "d2/d43/class_aurora_f_w_1_1_g_engine_1_1_r_t_shader" ],
      [ "Settings", "d5/d85/struct_aurora_f_w_1_1_g_engine_1_1_r_t_shader_1_1_settings.html", "d5/d85/struct_aurora_f_w_1_1_g_engine_1_1_r_t_shader_1_1_settings" ]
    ] ],
    [ "RTShaderConverter.h", "d8/d87/_r_t_shader_converter_8h.html", [
      [ "RTShaderConverter", "dc/d4f/class_aurora_f_w_1_1_g_engine_1_1_r_t_shader_converter.html", "dc/d4f/class_aurora_f_w_1_1_g_engine_1_1_r_t_shader_converter" ]
    ] ],
    [ "RTShaderConverterGLSL.cpp", "d5/de9/_r_t_shader_converter_g_l_s_l_8cpp.html", null ],
    [ "RTShaderConverterHLSL.cpp", "d9/d08/_r_t_shader_converter_h_l_s_l_8cpp.html", null ],
    [ "RTShaderConverterSPIRV.cpp", "d3/d08/_r_t_shader_converter_s_p_i_r_v_8cpp.html", null ],
    [ "RTShaderFactory.h", "dd/d65/_r_t_shader_factory_8h.html", null ],
    [ "RTShaderManager.h", "db/d83/_r_t_shader_manager_8h.html", [
      [ "RTShaderManager", "d9/dd5/class_aurora_f_w_1_1_g_engine_1_1_r_t_shader_manager.html", null ]
    ] ],
    [ "RTShaderPipeline.h", "d8/ddd/_r_t_shader_pipeline_8h.html", [
      [ "RTShaderPipeline", "db/d45/class_aurora_f_w_1_1_g_engine_1_1_r_t_shader_pipeline.html", null ]
    ] ],
    [ "rx2.c", "d5/d2a/rx2_8c.html", "d5/d2a/rx2_8c" ],
    [ "schema.h", "d7/de3/schema_8h.html", "d7/de3/schema_8h" ],
    [ "sd2.c", "d7/d43/sd2_8c.html", "d7/d43/sd2_8c" ],
    [ "sds.c", "de/d31/sds_8c.html", "de/d31/sds_8c" ],
    [ "setup.py", "da/dab/setup_8py.html", "da/dab/setup_8py" ],
    [ "sf_unistd.h", "dd/dd5/sf__unistd_8h.html", "dd/dd5/sf__unistd_8h" ],
    [ "sfconfig.h", "db/d17/sfconfig_8h.html", "db/d17/sfconfig_8h" ],
    [ "sfendian.h", "db/d83/sfendian_8h.html", "db/d83/sfendian_8h" ],
    [ "Shader.cpp", "d5/d16/_shader_8cpp.html", null ],
    [ "core/include/AuroraFW/GEngine/Shader.h", "dd/d30/core_2include_2_aurora_f_w_2_g_engine_2_shader_8h.html", [
      [ "Shader", "db/d6a/class_aurora_f_w_1_1_g_engine_1_1_shader.html", "db/d6a/class_aurora_f_w_1_1_g_engine_1_1_shader" ]
    ] ],
    [ "opengl/include/AuroraFW/GEngine/GL/Shader.h", "dd/d21/opengl_2include_2_aurora_f_w_2_g_engine_2_g_l_2_shader_8h.html", [
      [ "GLShader", "d4/dbe/class_aurora_f_w_1_1_g_engine_1_1_g_l_shader.html", "d4/dbe/class_aurora_f_w_1_1_g_engine_1_1_g_l_shader" ],
      [ "InvalidShaderException", "de/dc3/class_aurora_f_w_1_1_g_engine_1_1_invalid_shader_exception.html", "de/dc3/class_aurora_f_w_1_1_g_engine_1_1_invalid_shader_exception" ]
    ] ],
    [ "shaders/include/AuroraFW/GEngine/Shader.h", "dc/d1f/shaders_2include_2_aurora_f_w_2_g_engine_2_shader_8h.html", null ],
    [ "shift.h", "d3/d8e/shift_8h.html", "d3/d8e/shift_8h" ],
    [ "short_term.c", "d1/d21/short__term_8c.html", "d1/d21/short__term_8c" ],
    [ "simple.c", "db/dfa/simple_8c.html", "db/dfa/simple_8c" ],
    [ "sndfile.c", "de/df7/sndfile_8c.html", "de/df7/sndfile_8c" ],
    [ "sndfile.hh", "db/d65/sndfile_8hh.html", [
      [ "SndfileHandle", "dc/d2f/class_sndfile_handle.html", "dc/d2f/class_sndfile_handle" ]
    ] ],
    [ "Socket.cpp", "d9/dab/_socket_8cpp.html", null ],
    [ "Socket.h", "de/d1c/_socket_8h.html", [
      [ "Socket", "de/dba/class_socket.html", null ]
    ] ],
    [ "spec.py", "df/dc1/spec_8py.html", "df/dc1/spec_8py" ],
    [ "SPIR-V.h", "d2/dcf/_s_p_i_r-_v_8h.html", "d2/dcf/_s_p_i_r-_v_8h" ],
    [ "stack.h", "d7/de0/stack_8h.html", [
      [ "Stack", "de/d6c/classinternal_1_1_stack.html", "de/d6c/classinternal_1_1_stack" ]
    ] ],
    [ "std.450.h", "db/d7c/std_8450_8h.html", "db/d7c/std_8450_8h" ],
    [ "Internal/LibC/STDBool.h", "d1/dbf/_internal_2_lib_c_2_s_t_d_bool_8h.html", null ],
    [ "LibC/STDBool.h", "de/d31/_lib_c_2_s_t_d_bool_8h.html", null ],
    [ "Internal/LibC/STDDef.h", "d8/df3/_internal_2_lib_c_2_s_t_d_def_8h.html", null ],
    [ "LibC/STDDef.h", "df/d25/_lib_c_2_s_t_d_def_8h.html", "df/d25/_lib_c_2_s_t_d_def_8h" ],
    [ "parser/include/AuroraFW/Parser/JSON/msinttypes/stdint.h", "d2/d45/parser_2include_2_aurora_f_w_2_parser_2_j_s_o_n_2msinttypes_2stdint_8h.html", "d2/d45/parser_2include_2_aurora_f_w_2_parser_2_j_s_o_n_2msinttypes_2stdint_8h" ],
    [ "stdl/include/AuroraFW/STDL/Internal/LibC/stdint.h", "d8/d70/stdl_2include_2_aurora_f_w_2_s_t_d_l_2_internal_2_lib_c_2stdint_8h.html", null ],
    [ "stdl/include/AuroraFW/STDL/LibC/stdint.h", "d6/de7/stdl_2include_2_aurora_f_w_2_s_t_d_l_2_lib_c_2stdint_8h.html", "d6/de7/stdl_2include_2_aurora_f_w_2_s_t_d_l_2_lib_c_2stdint_8h" ],
    [ "stdl/include/AuroraFW/STDL/Vendor/MSVC/2008/stdint.h", "d1/ddf/stdl_2include_2_aurora_f_w_2_s_t_d_l_2_vendor_2_m_s_v_c_22008_2stdint_8h.html", "d1/ddf/stdl_2include_2_aurora_f_w_2_s_t_d_l_2_vendor_2_m_s_v_c_22008_2stdint_8h" ],
    [ "stream.h", "d8/d95/stream_8h.html", "d8/d95/stream_8h" ],
    [ "strfunc.h", "d2/d60/strfunc_8h.html", "d2/d60/strfunc_8h" ],
    [ "String.cpp", "d9/dae/_string_8cpp.html", null ],
    [ "corelib/include/AuroraFW/CoreLib/String.h", "dc/d5a/corelib_2include_2_aurora_f_w_2_core_lib_2_string_8h.html", "dc/d5a/corelib_2include_2_aurora_f_w_2_core_lib_2_string_8h" ],
    [ "stdl/include/AuroraFW/STDL/Internal/LibC/String.h", "d5/dc3/stdl_2include_2_aurora_f_w_2_s_t_d_l_2_internal_2_lib_c_2_string_8h.html", null ],
    [ "stdl/include/AuroraFW/STDL/Internal/STL/String.h", "db/d8a/stdl_2include_2_aurora_f_w_2_s_t_d_l_2_internal_2_s_t_l_2_string_8h.html", null ],
    [ "stdl/include/AuroraFW/STDL/LibC/String.h", "dc/d65/stdl_2include_2_aurora_f_w_2_s_t_d_l_2_lib_c_2_string_8h.html", "dc/d65/stdl_2include_2_aurora_f_w_2_s_t_d_l_2_lib_c_2_string_8h" ],
    [ "stdl/include/AuroraFW/STDL/STL/String.h", "dc/dee/stdl_2include_2_aurora_f_w_2_s_t_d_l_2_s_t_l_2_string_8h.html", null ],
    [ "stringbuffer.h", "d7/dde/stringbuffer_8h.html", "d7/dde/stringbuffer_8h" ],
    [ "strings.c", "d2/d48/strings_8c.html", "d2/d48/strings_8c" ],
    [ "strtod.h", "dd/dc7/strtod_8h.html", "dd/dc7/strtod_8h" ],
    [ "Style.cpp", "d6/db4/_style_8cpp.html", null ],
    [ "svx.c", "d6/dbf/svx_8c.html", "d6/dbf/svx_8c" ],
    [ "swap.h", "db/dd2/swap_8h.html", "db/dd2/swap_8h" ],
    [ "corelib/include/AuroraFW/CoreLib/Target/System.h", "d8/d4a/corelib_2include_2_aurora_f_w_2_core_lib_2_target_2_system_8h.html", null ],
    [ "io/include/AuroraFW/IO/Info/System.h", "d8/d54/io_2include_2_aurora_f_w_2_i_o_2_info_2_system_8h.html", "d8/d54/io_2include_2_aurora_f_w_2_i_o_2_info_2_system_8h" ],
    [ "table.c", "dc/d33/table_8c.html", "dc/d33/table_8c" ],
    [ "Target.h", "d0/d32/_target_8h.html", null ],
    [ "TextEdit.h", "df/da9/_text_edit_8h.html", "df/da9/_text_edit_8h" ],
    [ "POSIX/Thread.c", "dd/d04/_p_o_s_i_x_2_thread_8c.html", "dd/d04/_p_o_s_i_x_2_thread_8c" ],
    [ "Win32/Thread.c", "d2/d0c/_win32_2_thread_8c.html", "d2/d0c/_win32_2_thread_8c" ],
    [ "Thread.h", "d8/d48/_thread_8h.html", "d8/d48/_thread_8h" ],
    [ "Cocoa/Time.c", "d5/d01/_cocoa_2_time_8c.html", "d5/d01/_cocoa_2_time_8c" ],
    [ "POSIX/Time.c", "d8/d1a/_p_o_s_i_x_2_time_8c.html", "d8/d1a/_p_o_s_i_x_2_time_8c" ],
    [ "Win32/Time.c", "d5/d96/_win32_2_time_8c.html", "d5/d96/_win32_2_time_8c" ],
    [ "Time.h", "d7/dfe/_time_8h.html", "d7/dfe/_time_8h" ],
    [ "Timer.cpp", "d8/d77/_timer_8cpp.html", null ],
    [ "Timer.h", "d5/d29/_timer_8h.html", [
      [ "Timer", "dc/d80/class_aurora_f_w_1_1_i_o_1_1_timer.html", "dc/d80/class_aurora_f_w_1_1_i_o_1_1_timer" ]
    ] ],
    [ "TrueType.h", "d1/de1/_true_type_8h.html", "d1/de1/_true_type_8h" ],
    [ "txw.c", "d5/dc7/txw_8c.html", "d5/dc7/txw_8c" ],
    [ "Type.h", "d0/d89/_type_8h.html", "d0/d89/_type_8h" ],
    [ "Types.h", "d0/db6/_types_8h.html", "d0/db6/_types_8h" ],
    [ "TypeTraits.h", "d4/dd5/_type_traits_8h.html", [
      [ "ActualType", "d1/d69/struct_aurora_f_w_1_1_actual_type.html", "d1/d69/struct_aurora_f_w_1_1_actual_type" ],
      [ "ActualType< T *>", "d6/dbd/struct_aurora_f_w_1_1_actual_type_3_01_t_01_5_4.html", "d6/dbd/struct_aurora_f_w_1_1_actual_type_3_01_t_01_5_4" ]
    ] ],
    [ "ulaw.c", "d9/d8b/ulaw_8c.html", "d9/d8b/ulaw_8c" ],
    [ "Unicode.c", "d3/d6e/_unicode_8c.html", "d3/d6e/_unicode_8c" ],
    [ "Unicode.h", "da/dc7/_unicode_8h.html", "da/dc7/_unicode_8h" ],
    [ "lang/common/util.py", "d0/db6/lang_2common_2util_8py.html", "d0/db6/lang_2common_2util_8py" ],
    [ "util.py", "d0/d5e/util_8py.html", "d0/d5e/util_8py" ],
    [ "corelib/include/AuroraFW/CoreLib/Utils.h", "dc/dad/corelib_2include_2_aurora_f_w_2_core_lib_2_utils_8h.html", "dc/dad/corelib_2include_2_aurora_f_w_2_core_lib_2_utils_8h" ],
    [ "math/include/AuroraFW/Math/Utils.h", "d5/d30/math_2include_2_aurora_f_w_2_math_2_utils_8h.html", "d5/d30/math_2include_2_aurora_f_w_2_math_2_utils_8h" ],
    [ "Internal/STL/Vector.h", "de/dd7/_internal_2_s_t_l_2_vector_8h.html", null ],
    [ "STL/Vector.h", "db/d6f/_s_t_l_2_vector_8h.html", null ],
    [ "Vector2D.h", "d1/dae/_vector2_d_8h.html", "d1/dae/_vector2_d_8h" ],
    [ "Vector3D.h", "d6/d90/_vector3_d_8h.html", "d6/d90/_vector3_d_8h" ],
    [ "Vector4D.h", "da/d5a/_vector4_d_8h.html", "da/d5a/_vector4_d_8h" ],
    [ "VertexArray.h", "d0/df4/_vertex_array_8h.html", [
      [ "GLVertexArray", "db/db4/class_aurora_f_w_1_1_g_engine_1_1_g_l_vertex_array.html", "db/db4/class_aurora_f_w_1_1_g_engine_1_1_g_l_vertex_array" ]
    ] ],
    [ "VertexBufferElement.h", "d8/dde/_vertex_buffer_element_8h.html", [
      [ "GLVertexBufferElement", "d5/dd5/struct_aurora_f_w_1_1_g_engine_1_1_g_l_vertex_buffer_element.html", "d5/dd5/struct_aurora_f_w_1_1_g_engine_1_1_g_l_vertex_buffer_element" ]
    ] ],
    [ "VertexBufferLayout.h", "df/d3f/_vertex_buffer_layout_8h.html", [
      [ "GLVertexBufferLayout", "db/d0d/class_aurora_f_w_1_1_g_engine_1_1_g_l_vertex_buffer_layout.html", "db/d0d/class_aurora_f_w_1_1_g_engine_1_1_g_l_vertex_buffer_layout" ]
    ] ],
    [ "VKContext.cpp", "d0/db8/_v_k_context_8cpp.html", null ],
    [ "VKRenderer.cpp", "df/d34/_v_k_renderer_8cpp.html", null ],
    [ "voc.c", "d1/df1/voc_8c.html", "d1/df1/voc_8c" ],
    [ "vox_adpcm.c", "db/ddd/vox__adpcm_8c.html", "db/ddd/vox__adpcm_8c" ],
    [ "Vulkan.c", "d0/dad/_vulkan_8c.html", "d0/dad/_vulkan_8c" ],
    [ "w64.c", "da/d74/w64_8c.html", "da/d74/w64_8c" ],
    [ "wav.c", "d0/d75/wav_8c.html", "d0/d75/wav_8c" ],
    [ "wavlike.c", "d7/d0b/wavlike_8c.html", "d7/d0b/wavlike_8c" ],
    [ "wavlike.h", "d5/dd8/wavlike_8h.html", "d5/dd8/wavlike_8h" ],
    [ "Internal/LibC/WChar.h", "dc/d1f/_internal_2_lib_c_2_w_char_8h.html", null ],
    [ "LibC/WChar.h", "de/d33/_lib_c_2_w_char_8h.html", null ],
    [ "c/loader/wgl.py", "d8/dd7/c_2loader_2wgl_8py.html", "d8/dd7/c_2loader_2wgl_8py" ],
    [ "d/loader/wgl.py", "d9/d9a/d_2loader_2wgl_8py.html", "d9/d9a/d_2loader_2wgl_8py" ],
    [ "nim/loader/wgl.py", "db/d30/nim_2loader_2wgl_8py.html", "db/d30/nim_2loader_2wgl_8py" ],
    [ "volt/loader/wgl.py", "d5/d02/volt_2loader_2wgl_8py.html", "d5/d02/volt_2loader_2wgl_8py" ],
    [ "Widget.cpp", "dc/d19/_widget_8cpp.html", null ],
    [ "Widget.h", "d4/d75/_widget_8h.html", "d4/d75/_widget_8h" ],
    [ "Widget_impl.h", "d8/de9/_widget__impl_8h.html", null ],
    [ "Mir/Window.c", "dd/dc9/_mir_2_window_8c.html", "dd/dc9/_mir_2_window_8c" ],
    [ "NULL/Window.c", "d5/dfa/_n_u_l_l_2_window_8c.html", "d5/dfa/_n_u_l_l_2_window_8c" ],
    [ "Wayland/Window.c", "d0/d50/_wayland_2_window_8c.html", "d0/d50/_wayland_2_window_8c" ],
    [ "Win32/Window.c", "d7/df4/_win32_2_window_8c.html", "d7/df4/_win32_2_window_8c" ],
    [ "Window.c", "d5/d07/_window_8c.html", "d5/d07/_window_8c" ],
    [ "X11/Window.c", "d8/d9d/_x11_2_window_8c.html", "d8/d9d/_x11_2_window_8c" ],
    [ "gengine/core/src/Window.cpp", "d6/d62/gengine_2core_2src_2_window_8cpp.html", null ],
    [ "gui/src/Window.cpp", "d9/d19/gui_2src_2_window_8cpp.html", null ],
    [ "gengine/core/include/AuroraFW/GEngine/Window.h", "dc/d57/gengine_2core_2include_2_aurora_f_w_2_g_engine_2_window_8h.html", [
      [ "Window", "df/d57/class_aurora_f_w_1_1_g_engine_1_1_window.html", "df/d57/class_aurora_f_w_1_1_g_engine_1_1_window" ],
      [ "WindowProperties", "d2/d9a/struct_aurora_f_w_1_1_g_engine_1_1_window_properties.html", "d2/d9a/struct_aurora_f_w_1_1_g_engine_1_1_window_properties" ]
    ] ],
    [ "gui/include/AuroraFW/GUI/Window.h", "dc/de7/gui_2include_2_aurora_f_w_2_g_u_i_2_window_8h.html", [
      [ "Window", "d3/d1e/class_aurora_f_w_1_1_g_u_i_1_1_window.html", "d3/d1e/class_aurora_f_w_1_1_g_u_i_1_1_window" ]
    ] ],
    [ "Window.m", "d2/d11/_window_8m.html", "d2/d11/_window_8m" ],
    [ "windows.c", "d1/d3f/windows_8c.html", null ],
    [ "writer.h", "d9/d53/writer_8h.html", "d9/d53/writer_8h" ],
    [ "wve.c", "dd/d2b/wve_8c.html", "dd/d2b/wve_8c" ],
    [ "xi.c", "d9/d07/xi_8c.html", "d9/d07/xi_8c" ]
];