var hierarchy =
[
    [ "afwglGLversionStruct", "d3/d73/structafwgl_g_lversion_struct.html", null ],
    [ "AuroraFW::ActualType< T >", "d1/d69/struct_aurora_f_w_1_1_actual_type.html", null ],
    [ "AuroraFW::ActualType< T *>", "d6/dbd/struct_aurora_f_w_1_1_actual_type_3_01_t_01_5_4.html", null ],
    [ "AuroraFW::AES", "d9/d93/class_aurora_f_w_1_1_a_e_s.html", null ],
    [ "AuroraFW::Application", "dd/dec/struct_aurora_f_w_1_1_application.html", null ],
    [ "AuroraFW::ApplicationContext", "dc/d6f/class_aurora_f_w_1_1_application_context.html", null ],
    [ "AuroraFW::AudioManager::AudioBackend", "df/dbe/class_aurora_f_w_1_1_audio_manager_1_1_audio_backend.html", null ],
    [ "AuroraFW::AudioManager::AudioDevice", "d8/dd6/struct_aurora_f_w_1_1_audio_manager_1_1_audio_device.html", null ],
    [ "AuroraFW::AudioManager::AudioInfo", "d0/d6e/struct_aurora_f_w_1_1_audio_manager_1_1_audio_info.html", null ],
    [ "AuroraFW::AudioManager::AudioIStream", "da/d61/struct_aurora_f_w_1_1_audio_manager_1_1_audio_i_stream.html", null ],
    [ "AuroraFW::AudioManager::AudioListener", "d4/d39/class_aurora_f_w_1_1_audio_manager_1_1_audio_listener.html", null ],
    [ "AuroraFW::AudioManager::AudioOStream", "d6/de8/struct_aurora_f_w_1_1_audio_manager_1_1_audio_o_stream.html", null ],
    [ "AuroraFW::AudioManager::AudioSource", "df/d09/struct_aurora_f_w_1_1_audio_manager_1_1_audio_source.html", null ],
    [ "AuroraFW::Callback< T, n, CallerType >", "d2/d3d/struct_aurora_f_w_1_1_callback.html", null ],
    [ "AuroraFW::Callback< Ret(Params...), n, CallerType >", "d7/d81/struct_aurora_f_w_1_1_callback_3_01_ret_07_params_8_8_8_08_00_01n_00_01_caller_type_01_4.html", null ],
    [ "AuroraFW::CLI::Logger", "df/dea/class_aurora_f_w_1_1_c_l_i_1_1_logger.html", null ],
    [ "AuroraFW::DebugManager", "d7/dae/class_aurora_f_w_1_1_debug_manager.html", null ],
    [ "AuroraFW::GEngine::API::Context", "dc/d5c/class_aurora_f_w_1_1_g_engine_1_1_a_p_i_1_1_context.html", [
      [ "AuroraFW::GEngine::GLContext", "d5/dc8/class_aurora_f_w_1_1_g_engine_1_1_g_l_context.html", null ]
    ] ],
    [ "AuroraFW::GEngine::API::IndexBuffer", "d6/d9a/class_aurora_f_w_1_1_g_engine_1_1_a_p_i_1_1_index_buffer.html", [
      [ "AuroraFW::GEngine::API::GLIndexBuffer", "d7/d5b/class_aurora_f_w_1_1_g_engine_1_1_a_p_i_1_1_g_l_index_buffer.html", null ]
    ] ],
    [ "AuroraFW::GEngine::Application", "da/df1/class_aurora_f_w_1_1_g_engine_1_1_application.html", null ],
    [ "AuroraFW::GEngine::AssetManager", "d9/d4a/class_aurora_f_w_1_1_g_engine_1_1_asset_manager.html", null ],
    [ "AuroraFW::GEngine::BaseColor< T >", "d3/d7d/struct_aurora_f_w_1_1_g_engine_1_1_base_color.html", null ],
    [ "AuroraFW::GEngine::GLBuffer", "d3/d2b/class_aurora_f_w_1_1_g_engine_1_1_g_l_buffer.html", null ],
    [ "AuroraFW::GEngine::GLProgram", "d5/da3/class_aurora_f_w_1_1_g_engine_1_1_g_l_program.html", null ],
    [ "AuroraFW::GEngine::GLShader", "d4/dbe/class_aurora_f_w_1_1_g_engine_1_1_g_l_shader.html", null ],
    [ "AuroraFW::GEngine::GLVertexArray", "db/db4/class_aurora_f_w_1_1_g_engine_1_1_g_l_vertex_array.html", null ],
    [ "AuroraFW::GEngine::GLVertexBufferElement", "d5/dd5/struct_aurora_f_w_1_1_g_engine_1_1_g_l_vertex_buffer_element.html", null ],
    [ "AuroraFW::GEngine::GLVertexBufferLayout", "db/d0d/class_aurora_f_w_1_1_g_engine_1_1_g_l_vertex_buffer_layout.html", null ],
    [ "AuroraFW::GEngine::GraphicsContext", "d3/d0d/class_aurora_f_w_1_1_g_engine_1_1_graphics_context.html", null ],
    [ "AuroraFW::GEngine::ImGuiLoader", "d3/d2d/class_aurora_f_w_1_1_g_engine_1_1_im_gui_loader.html", [
      [ "AuroraFW::GEngine::GLImGuiLoader", "d1/ddd/class_aurora_f_w_1_1_g_engine_1_1_g_l_im_gui_loader.html", null ]
    ] ],
    [ "AuroraFW::GEngine::InputManager", "d3/d54/class_aurora_f_w_1_1_g_engine_1_1_input_manager.html", null ],
    [ "AuroraFW::GEngine::Renderer", "dd/dcb/class_aurora_f_w_1_1_g_engine_1_1_renderer.html", [
      [ "AuroraFW::GEngine::GLRenderer", "d4/ddd/class_aurora_f_w_1_1_g_engine_1_1_g_l_renderer.html", null ]
    ] ],
    [ "AuroraFW::GEngine::TextureAsset", "dd/d1b/class_aurora_f_w_1_1_g_engine_1_1_texture_asset.html", null ],
    [ "AuroraFW::GEngine::Window", "df/d57/class_aurora_f_w_1_1_g_engine_1_1_window.html", null ],
    [ "AuroraFW::GEngine::WindowProperties", "d2/d9a/struct_aurora_f_w_1_1_g_engine_1_1_window_properties.html", null ],
    [ "AuroraFW::GUI::Application", "d2/d7c/class_aurora_f_w_1_1_g_u_i_1_1_application.html", null ],
    [ "AuroraFW::GUI::Button", "dc/d58/class_aurora_f_w_1_1_g_u_i_1_1_button.html", null ],
    [ "AuroraFW::GUI::Label", "d6/dc0/class_aurora_f_w_1_1_g_u_i_1_1_label.html", null ],
    [ "AuroraFW::GUI::Window", "d3/d1e/class_aurora_f_w_1_1_g_u_i_1_1_window.html", null ],
    [ "AuroraFW::ImageManager::Image", "de/d77/class_aurora_f_w_1_1_image_manager_1_1_image.html", null ],
    [ "AuroraFW::InputListener", "da/d94/class_aurora_f_w_1_1_input_listener.html", null ],
    [ "AuroraFW::IO::File", "d0/df6/class_aurora_f_w_1_1_i_o_1_1_file.html", null ],
    [ "AuroraFW::IO::Info::SystemMemory", "dd/dd3/struct_aurora_f_w_1_1_i_o_1_1_info_1_1_system_memory.html", null ],
    [ "AuroraFW::IO::Timer", "dc/d80/class_aurora_f_w_1_1_i_o_1_1_timer.html", null ],
    [ "AuroraFW::KeyboardEvent", "d7/db0/struct_aurora_f_w_1_1_keyboard_event.html", null ],
    [ "AuroraFW::Math::mat4< T >", "d1/df2/struct_aurora_f_w_1_1_math_1_1mat4.html", null ],
    [ "AuroraFW::Math::Matrix< N, M, T >", "d4/d12/struct_aurora_f_w_1_1_math_1_1_matrix.html", null ],
    [ "AuroraFW::Math::Parser< T >", "d9/de7/class_aurora_f_w_1_1_math_1_1_parser.html", null ],
    [ "AuroraFW::Math::vec2< T >", "d8/d34/struct_aurora_f_w_1_1_math_1_1vec2.html", null ],
    [ "AuroraFW::Math::vec3< T >", "df/da8/struct_aurora_f_w_1_1_math_1_1vec3.html", null ],
    [ "AuroraFW::Math::vec4< T >", "d8/d6c/struct_aurora_f_w_1_1_math_1_1vec4.html", null ],
    [ "AuroraFW::MemoryAllocator", "d7/d9e/class_aurora_f_w_1_1_memory_allocator.html", null ],
    [ "AuroraFW::MemoryLeakTracker", "d3/df2/class_aurora_f_w_1_1_memory_leak_tracker.html", null ],
    [ "AuroraFW::MemoryManager", "db/da7/class_aurora_f_w_1_1_memory_manager.html", null ],
    [ "AuroraFW::MemoryStats", "d2/dd4/struct_aurora_f_w_1_1_memory_stats.html", null ],
    [ "AuroraFW::MouseButtonEvent", "dd/dda/struct_aurora_f_w_1_1_mouse_button_event.html", null ],
    [ "AuroraFW::MouseMotionEvent", "d4/de0/struct_aurora_f_w_1_1_mouse_motion_event.html", null ],
    [ "AuroraFW::MouseScrollEvent", "d4/d3e/struct_aurora_f_w_1_1_mouse_scroll_event.html", null ],
    [ "AuroraFW::OptionElement", "d2/d00/struct_aurora_f_w_1_1_option_element.html", null ],
    [ "AuroraFW::OptionHandler", "d8/d43/class_aurora_f_w_1_1_option_handler.html", null ],
    [ "AuroraFW::Parser::Lexer", "d0/d3f/class_aurora_f_w_1_1_parser_1_1_lexer.html", null ],
    [ "AuroraFW::Parser::ModularParser", "d6/d68/class_aurora_f_w_1_1_parser_1_1_modular_parser.html", null ],
    [ "AuroraFW::Parser::ModularToken< iter >", "d1/da6/class_aurora_f_w_1_1_parser_1_1_modular_token.html", null ],
    [ "AuroraFW::SplitedOptionElement", "dc/d90/struct_aurora_f_w_1_1_splited_option_element.html", null ],
    [ "ImColor", "db/da3/struct_im_color.html", null ],
    [ "ImDrawChannel", "df/d94/struct_im_draw_channel.html", null ],
    [ "ImDrawCmd", "d6/d65/struct_im_draw_cmd.html", null ],
    [ "ImDrawData", "d9/d78/struct_im_draw_data.html", null ],
    [ "ImDrawDataBuilder", "de/d11/struct_im_draw_data_builder.html", null ],
    [ "ImDrawList", "dd/d30/struct_im_draw_list.html", null ],
    [ "ImDrawListSharedData", "dd/d70/struct_im_draw_list_shared_data.html", null ],
    [ "ImDrawVert", "dc/d86/struct_im_draw_vert.html", null ],
    [ "ImFont", "d7/dc9/struct_im_font.html", null ],
    [ "ImFontAtlas", "d5/d9e/struct_im_font_atlas.html", null ],
    [ "ImFontAtlas::CustomRect", "da/d4d/struct_im_font_atlas_1_1_custom_rect.html", null ],
    [ "ImFontAtlas::GlyphRangesBuilder", "dc/dd9/struct_im_font_atlas_1_1_glyph_ranges_builder.html", null ],
    [ "ImFontConfig", "d5/d84/struct_im_font_config.html", null ],
    [ "ImFontGlyph", "df/d57/struct_im_font_glyph.html", null ],
    [ "ImGuiColMod", "d4/d6f/struct_im_gui_col_mod.html", null ],
    [ "ImGuiColumnData", "db/d3c/struct_im_gui_column_data.html", null ],
    [ "ImGuiColumnsSet", "d3/d79/struct_im_gui_columns_set.html", null ],
    [ "ImGuiContext", "d7/da3/struct_im_gui_context.html", null ],
    [ "ImGuiDrawContext", "d8/d5e/struct_im_gui_draw_context.html", null ],
    [ "ImGuiGroupData", "da/dc1/struct_im_gui_group_data.html", null ],
    [ "ImGuiIO", "d5/dbc/struct_im_gui_i_o.html", null ],
    [ "ImGuiItemHoveredDataBackup", "d3/dc0/struct_im_gui_item_hovered_data_backup.html", null ],
    [ "ImGuiListClipper", "df/d0a/struct_im_gui_list_clipper.html", null ],
    [ "ImGuiMenuColumns", "dc/d02/struct_im_gui_menu_columns.html", null ],
    [ "ImGuiNavMoveResult", "d5/d10/struct_im_gui_nav_move_result.html", null ],
    [ "ImGuiNextWindowData", "d3/dd8/struct_im_gui_next_window_data.html", null ],
    [ "ImGuiOnceUponAFrame", "d4/da6/struct_im_gui_once_upon_a_frame.html", null ],
    [ "ImGuiPayload", "d7/d1d/struct_im_gui_payload.html", null ],
    [ "ImGuiPlotArrayGetterData", "d5/dc4/struct_im_gui_plot_array_getter_data.html", null ],
    [ "ImGuiPopupRef", "d9/d83/struct_im_gui_popup_ref.html", null ],
    [ "ImGuiResizeGripDef", "d7/d0d/struct_im_gui_resize_grip_def.html", null ],
    [ "ImGuiSettingsHandler", "d2/d98/struct_im_gui_settings_handler.html", null ],
    [ "ImGuiSizeCallbackData", "da/d8c/struct_im_gui_size_callback_data.html", null ],
    [ "ImGuiStorage", "df/d15/struct_im_gui_storage.html", null ],
    [ "ImGuiStorage::Pair", "d4/d64/struct_im_gui_storage_1_1_pair.html", null ],
    [ "ImGuiStyle", "d7/d12/struct_im_gui_style.html", null ],
    [ "ImGuiStyleMod", "d4/df8/struct_im_gui_style_mod.html", null ],
    [ "ImGuiStyleVarInfo", "db/df8/struct_im_gui_style_var_info.html", null ],
    [ "ImGuiTextBuffer", "da/d7d/struct_im_gui_text_buffer.html", null ],
    [ "ImGuiTextEditCallbackData", "df/def/struct_im_gui_text_edit_callback_data.html", null ],
    [ "ImGuiTextEditState", "d8/d04/struct_im_gui_text_edit_state.html", null ],
    [ "ImGuiTextFilter", "d5/de6/struct_im_gui_text_filter.html", null ],
    [ "ImGuiTextFilter::TextRange", "d7/db3/struct_im_gui_text_filter_1_1_text_range.html", null ],
    [ "ImGuiWindow", "d6/d8f/struct_im_gui_window.html", null ],
    [ "ImGuiWindowSettings", "d5/db5/struct_im_gui_window_settings.html", null ],
    [ "ImNewPlacementDummy", "db/df3/struct_im_new_placement_dummy.html", null ],
    [ "ImRect", "df/d8d/struct_im_rect.html", null ],
    [ "ImVec2", "d7/d55/struct_im_vec2.html", null ],
    [ "ImVec4", "de/d2a/struct_im_vec4.html", null ],
    [ "ImVector< T >", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< char >", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< float >", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< ImDrawChannel >", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< ImDrawCmd >", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< ImDrawIdx >", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< ImDrawList *>", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< ImDrawVert >", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< ImFont *>", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< ImFontAtlas::CustomRect >", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< ImFontConfig >", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< ImFontGlyph >", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< ImGuiColMod >", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< ImGuiColumnData >", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< ImGuiColumnsSet >", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< ImGuiGroupData >", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< ImGuiID >", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< ImGuiItemFlags >", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< ImGuiPopupRef >", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< ImGuiSettingsHandler >", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< ImGuiStorage::Pair >", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< ImGuiStyleMod >", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< ImGuiTextFilter::TextRange >", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< ImGuiWindow *>", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< ImGuiWindowSettings >", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< ImTextureID >", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< ImVec2 >", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< ImVec4 >", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< ImWchar >", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< unsigned char >", "d9/de0/class_im_vector.html", null ],
    [ "ImVector< unsigned short >", "d9/de0/class_im_vector.html", null ],
    [ "object", null, [
      [ "glloader.lang.common.generator.Generator", "da/d1c/classglloader_1_1lang_1_1common_1_1generator_1_1_generator.html", [
        [ "glloader.lang.c.generator.CGenerator", "d5/d0b/classglloader_1_1lang_1_1c_1_1generator_1_1_c_generator.html", [
          [ "glloader.lang.c.debug.CDebugGenerator", "d6/d2b/classglloader_1_1lang_1_1c_1_1debug_1_1_c_debug_generator.html", null ]
        ] ]
      ] ],
      [ "glloader.lang.common.loader.BaseLoader", "d4/d29/classglloader_1_1lang_1_1common_1_1loader_1_1_base_loader.html", [
        [ "glloader.lang.c.loader.egl.EGLCLoader", "dc/d4c/classglloader_1_1lang_1_1c_1_1loader_1_1egl_1_1_e_g_l_c_loader.html", null ],
        [ "glloader.lang.c.loader.gl.OpenGLCLoader", "d9/d49/classglloader_1_1lang_1_1c_1_1loader_1_1gl_1_1_open_g_l_c_loader.html", null ],
        [ "glloader.lang.c.loader.glx.GLXCLoader", "db/dca/classglloader_1_1lang_1_1c_1_1loader_1_1glx_1_1_g_l_x_c_loader.html", null ],
        [ "glloader.lang.c.loader.wgl.WGLCLoader", "d4/dac/classglloader_1_1lang_1_1c_1_1loader_1_1wgl_1_1_w_g_l_c_loader.html", null ],
        [ "glloader.lang.common.loader.NullLoader", "d4/df8/classglloader_1_1lang_1_1common_1_1loader_1_1_null_loader.html", null ]
      ] ],
      [ "glloader.opener.URLOpener", "d5/d6a/classglloader_1_1opener_1_1_u_r_l_opener.html", null ],
      [ "glloader.parse.Command", "d7/d24/classglloader_1_1parse_1_1_command.html", null ],
      [ "glloader.parse.Enum", "d1/db4/classglloader_1_1parse_1_1_enum.html", null ],
      [ "glloader.parse.Extension", "d7/d3d/classglloader_1_1parse_1_1_extension.html", [
        [ "glloader.parse.Feature", "d4/d6b/classglloader_1_1parse_1_1_feature.html", null ]
      ] ],
      [ "glloader.parse.Group", "dd/d12/classglloader_1_1parse_1_1_group.html", null ],
      [ "glloader.parse.OGLType", "d7/dc6/classglloader_1_1parse_1_1_o_g_l_type.html", null ],
      [ "glloader.parse.Param", "d9/d13/classglloader_1_1parse_1_1_param.html", null ],
      [ "glloader.parse.Proto", "d8/dde/classglloader_1_1parse_1_1_proto.html", null ],
      [ "glloader.parse.Spec", "d8/df7/classglloader_1_1parse_1_1_spec.html", [
        [ "glloader.spec.EGLSpec", "d1/dc2/classglloader_1_1spec_1_1_e_g_l_spec.html", null ],
        [ "glloader.spec.GLSpec", "d6/d2d/classglloader_1_1spec_1_1_g_l_spec.html", null ],
        [ "glloader.spec.GLXSpec", "d4/d58/classglloader_1_1spec_1_1_g_l_x_spec.html", null ],
        [ "glloader.spec.WGLSpec", "da/dad/classglloader_1_1spec_1_1_w_g_l_spec.html", null ]
      ] ],
      [ "glloader.parse.Type", "df/dc4/classglloader_1_1parse_1_1_type.html", null ]
    ] ],
    [ "Socket", "de/dba/class_socket.html", null ],
    [ "STB_TexteditState", "d4/d92/struct_s_t_b___textedit_state.html", null ],
    [ "stbrp_context", "d7/dc7/structstbrp__context.html", null ],
    [ "stbrp_node", "d0/dbb/structstbrp__node.html", null ],
    [ "stbrp_rect", "d5/d50/structstbrp__rect.html", null ],
    [ "StbTexteditRow", "d1/d1e/struct_stb_textedit_row.html", null ],
    [ "stbtt__bitmap", "d6/d7d/structstbtt____bitmap.html", null ],
    [ "stbtt__buf", "dd/d25/structstbtt____buf.html", null ],
    [ "stbtt_aligned_quad", "d9/d0c/structstbtt__aligned__quad.html", null ],
    [ "stbtt_bakedchar", "d7/d70/structstbtt__bakedchar.html", null ],
    [ "stbtt_fontinfo", "d1/d3f/structstbtt__fontinfo.html", null ],
    [ "stbtt_pack_context", "d6/dc9/structstbtt__pack__context.html", null ],
    [ "stbtt_pack_range", "d9/d46/structstbtt__pack__range.html", null ],
    [ "stbtt_packedchar", "d2/d0c/structstbtt__packedchar.html", null ],
    [ "stbtt_vertex", "d4/d8d/structstbtt__vertex.html", null ],
    [ "StbUndoRecord", "d8/d4a/struct_stb_undo_record.html", null ],
    [ "StbUndoState", "dd/dfa/struct_stb_undo_state.html", null ],
    [ "exception", null, [
      [ "AuroraFW::AudioManager::AudioFileNotFound", "de/d16/class_aurora_f_w_1_1_audio_manager_1_1_audio_file_not_found.html", null ],
      [ "AuroraFW::AudioManager::AudioNotInitializedException", "d1/d98/class_aurora_f_w_1_1_audio_manager_1_1_audio_not_initialized_exception.html", null ],
      [ "AuroraFW::AudioManager::PAErrorException", "d9/d60/class_aurora_f_w_1_1_audio_manager_1_1_p_a_error_exception.html", null ],
      [ "AuroraFW::AudioManager::SNDFILEErrorException", "d3/da6/class_aurora_f_w_1_1_audio_manager_1_1_s_n_d_f_i_l_e_error_exception.html", null ],
      [ "AuroraFW::GEngine::AssetNotFoundException", "d6/de1/class_aurora_f_w_1_1_g_engine_1_1_asset_not_found_exception.html", null ],
      [ "AuroraFW::GEngine::AssetTypeInvalidException", "d0/d51/class_aurora_f_w_1_1_g_engine_1_1_asset_type_invalid_exception.html", null ],
      [ "AuroraFW::GEngine::DuplicatedShaderException", "d9/de4/class_aurora_f_w_1_1_g_engine_1_1_duplicated_shader_exception.html", null ],
      [ "AuroraFW::GEngine::InvalidShaderException", "de/dc3/class_aurora_f_w_1_1_g_engine_1_1_invalid_shader_exception.html", null ],
      [ "AuroraFW::ImageManager::ImageAllocationFailedException", "d3/d3b/class_aurora_f_w_1_1_image_manager_1_1_image_allocation_failed_exception.html", null ],
      [ "AuroraFW::ImageManager::ImageIsReadOnlyException", "df/dcf/class_aurora_f_w_1_1_image_manager_1_1_image_is_read_only_exception.html", null ],
      [ "AuroraFW::ImageManager::ImageIsWriteOnlyException", "d7/d98/class_aurora_f_w_1_1_image_manager_1_1_image_is_write_only_exception.html", null ],
      [ "AuroraFW::ImageManager::ImageNotFoundException", "db/d09/class_aurora_f_w_1_1_image_manager_1_1_image_not_found_exception.html", null ],
      [ "AuroraFW::IO::FileAllocationFailedException", "d5/d09/class_aurora_f_w_1_1_i_o_1_1_file_allocation_failed_exception.html", null ],
      [ "AuroraFW::IO::FileIsReadOnlyException", "d0/d66/class_aurora_f_w_1_1_i_o_1_1_file_is_read_only_exception.html", null ],
      [ "AuroraFW::IO::FileIsWriteOnlyException", "df/da1/class_aurora_f_w_1_1_i_o_1_1_file_is_write_only_exception.html", null ],
      [ "AuroraFW::IO::FileNotFoundException", "d7/db0/class_aurora_f_w_1_1_i_o_1_1_file_not_found_exception.html", null ]
    ] ],
    [ "Generator", null, [
      [ "glloader.lang.d.generator.BaseDGenerator", "d4/d18/classglloader_1_1lang_1_1d_1_1generator_1_1_base_d_generator.html", [
        [ "glloader.lang.d.generator.DGenerator", "dd/d9a/classglloader_1_1lang_1_1d_1_1generator_1_1_d_generator.html", null ]
      ] ],
      [ "glloader.lang.nim.generator.NimGenerator", "d7/dd9/classglloader_1_1lang_1_1nim_1_1generator_1_1_nim_generator.html", null ]
    ] ],
    [ "BaseLoader", null, [
      [ "glloader.lang.d.loader.egl.EGLDLoader", "dc/d0d/classglloader_1_1lang_1_1d_1_1loader_1_1egl_1_1_e_g_l_d_loader.html", null ],
      [ "glloader.lang.d.loader.gl.OpenGLDLoader", "d9/da2/classglloader_1_1lang_1_1d_1_1loader_1_1gl_1_1_open_g_l_d_loader.html", null ],
      [ "glloader.lang.d.loader.glx.GLXDLoader", "d5/d50/classglloader_1_1lang_1_1d_1_1loader_1_1glx_1_1_g_l_x_d_loader.html", null ],
      [ "glloader.lang.d.loader.wgl.WGLDLoader", "db/de7/classglloader_1_1lang_1_1d_1_1loader_1_1wgl_1_1_w_g_l_d_loader.html", null ],
      [ "glloader.lang.nim.loader.egl.EGLNimLoader", "d4/dac/classglloader_1_1lang_1_1nim_1_1loader_1_1egl_1_1_e_g_l_nim_loader.html", null ],
      [ "glloader.lang.nim.loader.gl.OpenGLNimLoader", "d5/dc6/classglloader_1_1lang_1_1nim_1_1loader_1_1gl_1_1_open_g_l_nim_loader.html", null ],
      [ "glloader.lang.nim.loader.glx.GLXNimLoader", "de/d6b/classglloader_1_1lang_1_1nim_1_1loader_1_1glx_1_1_g_l_x_nim_loader.html", null ],
      [ "glloader.lang.nim.loader.wgl.WGLNimLoader", "d2/df3/classglloader_1_1lang_1_1nim_1_1loader_1_1wgl_1_1_w_g_l_nim_loader.html", null ],
      [ "glloader.lang.volt.loader.egl.EGLVoltLoader", "dc/d5f/classglloader_1_1lang_1_1volt_1_1loader_1_1egl_1_1_e_g_l_volt_loader.html", null ],
      [ "glloader.lang.volt.loader.gl.OpenGLVoltLoader", "de/dbe/classglloader_1_1lang_1_1volt_1_1loader_1_1gl_1_1_open_g_l_volt_loader.html", null ],
      [ "glloader.lang.volt.loader.glx.GLXVoltLoader", "d7/d7d/classglloader_1_1lang_1_1volt_1_1loader_1_1glx_1_1_g_l_x_volt_loader.html", null ],
      [ "glloader.lang.volt.loader.wgl.WGLVoltLoader", "db/df3/classglloader_1_1lang_1_1volt_1_1loader_1_1wgl_1_1_w_g_l_volt_loader.html", null ]
    ] ],
    [ "DGenerator", null, [
      [ "glloader.lang.volt.generator.VoltGenerator", "db/d3f/classglloader_1_1lang_1_1volt_1_1generator_1_1_volt_generator.html", null ]
    ] ]
];