Aurora Framework: Joystick.c File Reference
Win32/Joystick.c File Reference
Classes
struct _GLFWobjenumWin32
Macros
#define _GLFW_TYPE_AXIS 0
#define _GLFW_TYPE_BUTTON 2
#define _GLFW_TYPE_POV 3
#define _GLFW_TYPE_SLIDER 1
#define GUID_POV _glfw_GUID_POV
#define GUID_RxAxis _glfw_GUID_RxAxis
#define GUID_RyAxis _glfw_GUID_RyAxis
#define GUID_RzAxis _glfw_GUID_RzAxis
#define GUID_Slider _glfw_GUID_Slider
#define GUID_XAxis _glfw_GUID_XAxis
#define GUID_YAxis _glfw_GUID_YAxis
#define GUID_ZAxis _glfw_GUID_ZAxis
#define IID_IDirectInput8W _glfw_IID_IDirectInput8W
Typedefs
typedef struct _GLFWobjenumWin32 _GLFWobjenumWin32
Functions
void _glfwDetectJoystickConnectionWin32 (void)
void _glfwDetectJoystickDisconnectionWin32 (void)
void _glfwInitJoysticksWin32 (void)
int _glfwPlatformPollJoystick (_GLFWjoystick *js, int mode)
void _glfwPlatformUpdateGamepadGUID (char *guid)
void _glfwTerminateJoysticksWin32 (void)
static void closeJoystick (_GLFWjoystick *js)
static int compareJoystickObjects (const void *first, const void *second)
static BOOL CALLBACK deviceCallback (const DIDEVICEINSTANCE *di, void *user)
static BOOL CALLBACK deviceObjectCallback (const DIDEVICEOBJECTINSTANCEW *doi, void *user)
static const char * getDeviceDescription (const XINPUT_CAPABILITIES *xic)
static GLFWbool supportsXInput (const GUID *guid)
Variables
static const GUID _glfw_GUID_POV
static const GUID _glfw_GUID_RxAxis
static const GUID _glfw_GUID_RyAxis
static const GUID _glfw_GUID_RzAxis
static const GUID _glfw_GUID_Slider
static const GUID _glfw_GUID_XAxis
static const GUID _glfw_GUID_YAxis
static const GUID _glfw_GUID_ZAxis
static const GUID _glfw_IID_IDirectInput8W
static const DIDATAFORMAT _glfwDataFormat
static DIOBJECTDATAFORMAT _glfwObjectDataFormats []
Macro Definition Documentation
_GLFW_TYPE_AXIS
#define _GLFW_TYPE_AXIS 0
Referenced by _glfwPlatformPollJoystick(), and deviceObjectCallback().
_GLFW_TYPE_SLIDER
#define _GLFW_TYPE_SLIDER 1
Referenced by _glfwPlatformPollJoystick(), and deviceObjectCallback().
_GLFW_TYPE_BUTTON
#define _GLFW_TYPE_BUTTON 2
Referenced by _glfwPlatformPollJoystick(), and deviceObjectCallback().
_GLFW_TYPE_POV
#define _GLFW_TYPE_POV 3
Referenced by _glfwPlatformPollJoystick(), and deviceObjectCallback().
IID_IDirectInput8W
#define IID_IDirectInput8W _glfw_IID_IDirectInput8W
Referenced by _glfwInitJoysticksWin32().
GUID_XAxis
#define GUID_XAxis _glfw_GUID_XAxis
Referenced by deviceObjectCallback().
GUID_YAxis
#define GUID_YAxis _glfw_GUID_YAxis
Referenced by deviceObjectCallback().
GUID_ZAxis
#define GUID_ZAxis _glfw_GUID_ZAxis
Referenced by deviceObjectCallback().
GUID_RxAxis
#define GUID_RxAxis _glfw_GUID_RxAxis
Referenced by deviceObjectCallback().
GUID_RyAxis
#define GUID_RyAxis _glfw_GUID_RyAxis
Referenced by deviceObjectCallback().
GUID_RzAxis
#define GUID_RzAxis _glfw_GUID_RzAxis
Referenced by deviceObjectCallback().
GUID_Slider
#define GUID_Slider _glfw_GUID_Slider
Referenced by deviceObjectCallback().
GUID_POV
#define GUID_POV _glfw_GUID_POV
Typedef Documentation
_GLFWobjenumWin32
typedef struct _GLFWobjenumWin32 _GLFWobjenumWin32
Function Documentation
getDeviceDescription()
static const char* getDeviceDescription (const XINPUT_CAPABILITIES * xic) static
References XINPUT_CAPS_WIRELESS, XINPUT_DEVSUBTYPE_ARCADE_STICK, XINPUT_DEVSUBTYPE_DANCE_PAD, XINPUT_DEVSUBTYPE_DRUM_KIT, XINPUT_DEVSUBTYPE_FLIGHT_STICK, XINPUT_DEVSUBTYPE_GUITAR, and XINPUT_DEVSUBTYPE_WHEEL.
Referenced by _glfwDetectJoystickConnectionWin32().
compareJoystickObjects()
static int compareJoystickObjects (const void * first, const void * second) static
References _GLFWjoyobjectWin32::offset, and _GLFWjoyobjectWin32::type.
Referenced by deviceCallback().
supportsXInput()
static GLFWbool supportsXInput (const GUID * guid) static
References GLFW_FALSE, GLFW_TRUE, memset(), setup::name, and NULL.
Referenced by deviceCallback().
closeJoystick()
static void closeJoystick (_GLFWjoystick * js) static
References _glfwFreeJoystick(), _glfwInputJoystick(), and GLFW_DISCONNECTED.
Referenced by _glfwPlatformPollJoystick(), and _glfwTerminateJoysticksWin32().
deviceObjectCallback()
static BOOL CALLBACK deviceObjectCallback (const DIDEVICEOBJECTINSTANCEW * doi, void * user) static
References _GLFW_TYPE_AXIS, _GLFW_TYPE_BUTTON, _GLFW_TYPE_POV, _GLFW_TYPE_SLIDER, _GLFWobjenumWin32::axisCount, _GLFWobjenumWin32::buttonCount, _GLFWobjenumWin32::device, GUID_RxAxis, GUID_RyAxis, GUID_RzAxis, GUID_Slider, GUID_XAxis, GUID_YAxis, GUID_ZAxis, memcmp(), _GLFWobjenumWin32::objectCount, _GLFWobjenumWin32::objects, _GLFWobjenumWin32::povCount, and _GLFWobjenumWin32::sliderCount.
Referenced by deviceCallback().
deviceCallback()
static BOOL CALLBACK deviceCallback (const DIDEVICEINSTANCE * di, void * user) static
References _glfw, _glfwAllocJoystick(), _glfwDataFormat, _glfwInputError(), _glfwInputJoystick(), _GLFWobjenumWin32::axisCount, _GLFWobjenumWin32::buttonCount, compareJoystickObjects(), _GLFWobjenumWin32::device, deviceObjectCallback(), GLFW_CONNECTED, GLFW_JOYSTICK_LAST, GLFW_PLATFORM_ERROR, _GLFWjoystick::guid, _GLFWlibrary::joysticks, memcmp(), memset(), setup::name, NULL, _GLFWobjenumWin32::objectCount, _GLFWobjenumWin32::objects, _GLFWobjenumWin32::povCount, _GLFWjoystick::present, _GLFWobjenumWin32::sliderCount, and supportsXInput().
Referenced by _glfwDetectJoystickConnectionWin32().
_glfwInitJoysticksWin32()
void _glfwInitJoysticksWin32 (void)
References _glfw, _glfwDetectJoystickConnectionWin32(), _glfwInputError(), DirectInput8Create, DIRECTINPUT_VERSION, GLFW_PLATFORM_ERROR, IID_IDirectInput8W, and NULL.
Referenced by _glfwPlatformInit().
_glfwTerminateJoysticksWin32()
void _glfwTerminateJoysticksWin32 (void)
References _glfw, closeJoystick(), GLFW_JOYSTICK_1, GLFW_JOYSTICK_LAST, and _GLFWlibrary::joysticks.
Referenced by _glfwPlatformTerminate().
_glfwDetectJoystickConnectionWin32()
void _glfwDetectJoystickConnectionWin32 (void)
References _glfw, _glfwAllocJoystick(), _glfwInputError(), _glfwInputJoystick(), deviceCallback(), getDeviceDescription(), GLFW_CONNECTED, GLFW_JOYSTICK_LAST, GLFW_PLATFORM_ERROR, _GLFWlibrary::joysticks, NULL, _GLFWjoystick::present, XInputGetCapabilities, and XUSER_MAX_COUNT.
Referenced by _glfwInitJoysticksWin32(), and windowProc().
_glfwDetectJoystickDisconnectionWin32()
void _glfwDetectJoystickDisconnectionWin32 (void)
References _glfw, _GLFW_POLL_PRESENCE, _glfwPlatformPollJoystick(), GLFW_JOYSTICK_LAST, _GLFWlibrary::joysticks, and _GLFWjoystick::present.
Referenced by windowProc().
_glfwPlatformPollJoystick()
int _glfwPlatformPollJoystick (_GLFWjoystick * js, int mode)
References _GLFW_POLL_AXES, _GLFW_POLL_BUTTONS, _GLFW_POLL_PRESENCE, _GLFW_TYPE_AXIS, _GLFW_TYPE_BUTTON, _GLFW_TYPE_POV, _GLFW_TYPE_SLIDER, _glfwInputJoystickAxis(), _glfwInputJoystickButton(), _glfwInputJoystickHat(), _GLFWjoystick::axes, _GLFWjoystick::buttons, closeJoystick(), getElementValue(), GLFW_FALSE, GLFW_HAT_CENTERED, GLFW_HAT_DOWN, GLFW_HAT_LEFT, GLFW_HAT_LEFT_DOWN, GLFW_HAT_LEFT_UP, GLFW_HAT_RIGHT, GLFW_HAT_RIGHT_DOWN, GLFW_HAT_RIGHT_UP, GLFW_HAT_UP, GLFW_TRUE, _GLFWjoystick::hats, _GLFWjoyelementNS::maximum, _GLFWjoyelementNS::minimum, mode(), _GLFWjoystick::present, value, and XInputGetState.
Referenced by _glfwDetectJoystickDisconnectionWin32().
_glfwPlatformUpdateGamepadGUID()
void _glfwPlatformUpdateGamepadGUID (char * guid)
Variable Documentation
_glfw_IID_IDirectInput8W
const GUID _glfw_IID_IDirectInput8W static
Initial value:
=
    {0xbf798031,0x483a,0x4da2,{0xaa,0x99,0x5d,0x64,0xed,0x36,0x97,0x00}}
_glfw_GUID_XAxis
const GUID _glfw_GUID_XAxis static
Initial value:
=
    {0xa36d02e0,0xc9f3,0x11cf,{0xbf,0xc7,0x44,0x45,0x53,0x54,0x00,0x00}}
_glfw_GUID_YAxis
const GUID _glfw_GUID_YAxis static
Initial value:
=
    {0xa36d02e1,0xc9f3,0x11cf,{0xbf,0xc7,0x44,0x45,0x53,0x54,0x00,0x00}}
_glfw_GUID_ZAxis
const GUID _glfw_GUID_ZAxis static
Initial value:
=
    {0xa36d02e2,0xc9f3,0x11cf,{0xbf,0xc7,0x44,0x45,0x53,0x54,0x00,0x00}}
_glfw_GUID_RxAxis
const GUID _glfw_GUID_RxAxis static
Initial value:
=
    {0xa36d02f4,0xc9f3,0x11cf,{0xbf,0xc7,0x44,0x45,0x53,0x54,0x00,0x00}}
_glfw_GUID_RyAxis
const GUID _glfw_GUID_RyAxis static
Initial value:
=
    {0xa36d02f5,0xc9f3,0x11cf,{0xbf,0xc7,0x44,0x45,0x53,0x54,0x00,0x00}}
_glfw_GUID_RzAxis
const GUID _glfw_GUID_RzAxis static
Initial value:
=
    {0xa36d02e3,0xc9f3,0x11cf,{0xbf,0xc7,0x44,0x45,0x53,0x54,0x00,0x00}}
_glfw_GUID_Slider
const GUID _glfw_GUID_Slider static
Initial value:
=
    {0xa36d02e4,0xc9f3,0x11cf,{0xbf,0xc7,0x44,0x45,0x53,0x54,0x00,0x00}}
_glfw_GUID_POV
const GUID _glfw_GUID_POV static
Initial value:
=
    {0xa36d02f2,0xc9f3,0x11cf,{0xbf,0xc7,0x44,0x45,0x53,0x54,0x00,0x00}}
_glfwObjectDataFormats
DIOBJECTDATAFORMAT _glfwObjectDataFormats[] static
_glfwDataFormat
const DIDATAFORMAT _glfwDataFormat static
Initial value:
=
{
    sizeof(DIDATAFORMAT),
    sizeof(DIOBJECTDATAFORMAT),
    DIDFT_ABSAXIS,
    sizeof(DIJOYSTATE),
    sizeof(_glfwObjectDataFormats) / sizeof(DIOBJECTDATAFORMAT),
    _glfwObjectDataFormats
}
Referenced by deviceCallback().