Aurora Framework: ImGui Namespace Reference
ImGui Namespace Reference
Functions
IMGUI_API const ImGuiPayload * AcceptDragDropPayload (const char *type, ImGuiDragDropFlags flags=0)
IMGUI_API void ActivateItem (ImGuiID id)
static void AlignFirstTextHeightToWidgets ()
IMGUI_API void AlignTextToFramePadding ()
IMGUI_API bool ArrowButton (ImGuiID id, ImGuiDir dir, ImVec2 padding, ImGuiButtonFlags flags=0)
IMGUI_API bool Begin (const char *name, bool *p_open=NULL, ImGuiWindowFlags flags=0)
bool Begin (const char *name, bool *p_open, const ImVec2 &size_on_first_use, float bg_alpha_override=-1.0f, ImGuiWindowFlags flags=0)
IMGUI_API bool BeginChild (const char *str_id, const ImVec2 &size=ImVec2(0, 0), bool border=false, ImGuiWindowFlags flags=0)
IMGUI_API bool BeginChild (ImGuiID id, const ImVec2 &size=ImVec2(0, 0), bool border=false, ImGuiWindowFlags flags=0)
IMGUI_API bool BeginChildFrame (ImGuiID id, const ImVec2 &size, ImGuiWindowFlags flags=0)
IMGUI_API void BeginColumns (const char *str_id, int count, ImGuiColumnsFlags flags=0)
IMGUI_API bool BeginCombo (const char *label, const char *preview_value, ImGuiComboFlags flags=0)
IMGUI_API bool BeginDragDropSource (ImGuiDragDropFlags flags=0)
IMGUI_API bool BeginDragDropTarget ()
IMGUI_API bool BeginDragDropTargetCustom (const ImRect &bb, ImGuiID id)
IMGUI_API void BeginGroup ()
IMGUI_API bool BeginMainMenuBar ()
IMGUI_API bool BeginMenu (const char *label, bool enabled=true)
IMGUI_API bool BeginMenuBar ()
IMGUI_API bool BeginPopup (const char *str_id, ImGuiWindowFlags flags=0)
IMGUI_API bool BeginPopupContextItem (const char *str_id=NULL, int mouse_button=1)
IMGUI_API bool BeginPopupContextVoid (const char *str_id=NULL, int mouse_button=1)
IMGUI_API bool BeginPopupContextWindow (const char *str_id=NULL, int mouse_button=1, bool also_over_items=true)
IMGUI_API bool BeginPopupEx (ImGuiID id, ImGuiWindowFlags extra_flags)
IMGUI_API bool BeginPopupModal (const char *name, bool *p_open=NULL, ImGuiWindowFlags flags=0)
IMGUI_API void BeginTooltip ()
IMGUI_API void BeginTooltipEx (ImGuiWindowFlags extra_flags, bool override_previous_tooltip=true)
IMGUI_API void BringWindowToBack (ImGuiWindow *window)
IMGUI_API void BringWindowToFront (ImGuiWindow *window)
IMGUI_API void Bullet ()
IMGUI_API void BulletText (const char *fmt,...) IM_FMTARGS(1)
IMGUI_API void BulletTextV (const char *fmt, va_list args) IM_FMTLIST(1)
IMGUI_API bool Button (const char *label, const ImVec2 &size=ImVec2(0, 0))
IMGUI_API bool ButtonBehavior (const ImRect &bb, ImGuiID id, bool *out_hovered, bool *out_held, ImGuiButtonFlags flags=0)
IMGUI_API bool ButtonEx (const char *label, const ImVec2 &size_arg=ImVec2(0, 0), ImGuiButtonFlags flags=0)
static ImVec2 CalcItemRectClosestPoint (const ImVec2 &pos, bool on_edge=false, float outward=0.f)
IMGUI_API ImVec2 CalcItemSize (ImVec2 size, float default_x, float default_y)
IMGUI_API float CalcItemWidth ()
IMGUI_API void CalcListClipping (int items_count, float items_height, int *out_items_display_start, int *out_items_display_end)
IMGUI_API ImVec2 CalcTextSize (const char *text, const char *text_end=NULL, bool hide_text_after_double_hash=false, float wrap_width=-1.0f)
IMGUI_API int CalcTypematicPressedRepeatAmount (float t, float t_prev, float repeat_delay, float repeat_rate)
IMGUI_API float CalcWrapWidthForPos (const ImVec2 &pos, float wrap_pos_x)
IMGUI_API void CaptureKeyboardFromApp (bool capture=true)
IMGUI_API void CaptureMouseFromApp (bool capture=true)
IMGUI_API bool Checkbox (const char *label, bool *v)
IMGUI_API bool CheckboxFlags (const char *label, unsigned int *flags, unsigned int flags_value)
IMGUI_API void ClearActiveID ()
IMGUI_API void ClearDragDrop ()
IMGUI_API bool CloseButton (ImGuiID id, const ImVec2 &pos, float radius)
IMGUI_API void CloseCurrentPopup ()
IMGUI_API void ClosePopup (ImGuiID id)
IMGUI_API void ClosePopupsOverWindow (ImGuiWindow *ref_window)
IMGUI_API bool CollapsingHeader (const char *label, ImGuiTreeNodeFlags flags=0)
IMGUI_API bool CollapsingHeader (const char *label, bool *p_open, ImGuiTreeNodeFlags flags=0)
static bool CollapsingHeader (const char *label, const char *str_id, bool framed=true, bool default_open=false)
IMGUI_API bool ColorButton (const char *desc_id, const ImVec4 &col, ImGuiColorEditFlags flags=0, ImVec2 size=ImVec2(0, 0))
IMGUI_API ImU32 ColorConvertFloat4ToU32 (const ImVec4 &in)
IMGUI_API void ColorConvertHSVtoRGB (float h, float s, float v, float &out_r, float &out_g, float &out_b)
IMGUI_API void ColorConvertRGBtoHSV (float r, float g, float b, float &out_h, float &out_s, float &out_v)
IMGUI_API ImVec4 ColorConvertU32ToFloat4 (ImU32 in)
IMGUI_API bool ColorEdit3 (const char *label, float col[3], ImGuiColorEditFlags flags=0)
IMGUI_API bool ColorEdit4 (const char *label, float col[4], ImGuiColorEditFlags flags=0)
IMGUI_API void ColorEditOptionsPopup (const float *col, ImGuiColorEditFlags flags)
IMGUI_API bool ColorPicker3 (const char *label, float col[3], ImGuiColorEditFlags flags=0)
IMGUI_API bool ColorPicker4 (const char *label, float col[4], ImGuiColorEditFlags flags=0, const float *ref_col=NULL)
IMGUI_API void ColorTooltip (const char *text, const float *col, ImGuiColorEditFlags flags)
IMGUI_API void Columns (int count=1, const char *id=NULL, bool border=true)
IMGUI_API bool Combo (const char *label, int *current_item, const char *const items[], int items_count, int popup_max_height_in_items=-1)
IMGUI_API bool Combo (const char *label, int *current_item, const char *items_separated_by_zeros, int popup_max_height_in_items=-1)
IMGUI_API bool Combo (const char *label, int *current_item, bool(*items_getter)(void *data, int idx, const char **out_text), void *data, int items_count, int popup_max_height_in_items=-1)
IMGUI_API ImGuiContext * CreateContext (ImFontAtlas *shared_font_atlas=NULL)
IMGUI_API void DestroyContext (ImGuiContext *ctx=NULL)
IMGUI_API bool DragBehavior (const ImRect &frame_bb, ImGuiID id, float *v, float v_speed, float v_min, float v_max, int decimal_precision, float power)
IMGUI_API bool DragFloat (const char *label, float *v, float v_speed=1.0f, float v_min=0.0f, float v_max=0.0f, const char *display_format="%.3f", float power=1.0f)
IMGUI_API bool DragFloat2 (const char *label, float v[2], float v_speed=1.0f, float v_min=0.0f, float v_max=0.0f, const char *display_format="%.3f", float power=1.0f)
IMGUI_API bool DragFloat3 (const char *label, float v[3], float v_speed=1.0f, float v_min=0.0f, float v_max=0.0f, const char *display_format="%.3f", float power=1.0f)
IMGUI_API bool DragFloat4 (const char *label, float v[4], float v_speed=1.0f, float v_min=0.0f, float v_max=0.0f, const char *display_format="%.3f", float power=1.0f)
IMGUI_API bool DragFloatN (const char *label, float *v, int components, float v_speed, float v_min, float v_max, const char *display_format, float power)
IMGUI_API bool DragFloatRange2 (const char *label, float *v_current_min, float *v_current_max, float v_speed=1.0f, float v_min=0.0f, float v_max=0.0f, const char *display_format="%.3f", const char *display_format_max=NULL, float power=1.0f)
IMGUI_API bool DragInt (const char *label, int *v, float v_speed=1.0f, int v_min=0, int v_max=0, const char *display_format="%.0f")
IMGUI_API bool DragInt2 (const char *label, int v[2], float v_speed=1.0f, int v_min=0, int v_max=0, const char *display_format="%.0f")
IMGUI_API bool DragInt3 (const char *label, int v[3], float v_speed=1.0f, int v_min=0, int v_max=0, const char *display_format="%.0f")
IMGUI_API bool DragInt4 (const char *label, int v[4], float v_speed=1.0f, int v_min=0, int v_max=0, const char *display_format="%.0f")
IMGUI_API bool DragIntN (const char *label, int *v, int components, float v_speed, int v_min, int v_max, const char *display_format)
IMGUI_API bool DragIntRange2 (const char *label, int *v_current_min, int *v_current_max, float v_speed=1.0f, int v_min=0, int v_max=0, const char *display_format="%.0f", const char *display_format_max=NULL)
IMGUI_API void Dummy (const ImVec2 &size)
IMGUI_API void End ()
IMGUI_API void EndChild ()
IMGUI_API void EndChildFrame ()
IMGUI_API void EndColumns ()
IMGUI_API void EndCombo ()
IMGUI_API void EndDragDropSource ()
IMGUI_API void EndDragDropTarget ()
IMGUI_API void EndFrame ()
IMGUI_API void EndGroup ()
IMGUI_API void EndMainMenuBar ()
IMGUI_API void EndMenu ()
IMGUI_API void EndMenuBar ()
IMGUI_API void EndPopup ()
IMGUI_API void EndTooltip ()
IMGUI_API const char * FindRenderedTextEnd (const char *text, const char *text_end=NULL)
IMGUI_API ImGuiSettingsHandler * FindSettingsHandler (const char *type_name)
IMGUI_API ImGuiWindow * FindWindowByName (const char *name)
IMGUI_API ImGuiWindowSettings * FindWindowSettings (ImGuiID id)
IMGUI_API bool FocusableItemRegister (ImGuiWindow *window, ImGuiID id, bool tab_stop=true)
IMGUI_API void FocusableItemUnregister (ImGuiWindow *window)
static void FocusFrontMostActiveWindow (ImGuiWindow *ignore_window)
IMGUI_API void FocusWindow (ImGuiWindow *window)
IMGUI_API ImGuiID GetActiveID ()
IMGUI_API const char * GetClipboardText ()
IMGUI_API ImU32 GetColorU32 (ImGuiCol idx, float alpha_mul=1.0f)
IMGUI_API ImU32 GetColorU32 (const ImVec4 &col)
IMGUI_API ImU32 GetColorU32 (ImU32 col)
IMGUI_API int GetColumnIndex ()
IMGUI_API float GetColumnOffset (int column_index=-1)
IMGUI_API int GetColumnsCount ()
IMGUI_API float GetColumnWidth (int column_index=-1)
IMGUI_API ImVec2 GetContentRegionAvail ()
IMGUI_API float GetContentRegionAvailWidth ()
IMGUI_API ImVec2 GetContentRegionMax ()
IMGUI_API ImGuiContext * GetCurrentContext ()
ImGuiWindow * GetCurrentWindow ()
ImGuiWindow * GetCurrentWindowRead ()
IMGUI_API ImVec2 GetCursorPos ()
IMGUI_API float GetCursorPosX ()
IMGUI_API float GetCursorPosY ()
IMGUI_API ImVec2 GetCursorScreenPos ()
IMGUI_API ImVec2 GetCursorStartPos ()
IMGUI_API ImDrawData * GetDrawData ()
IMGUI_API ImDrawListSharedData * GetDrawListSharedData ()
IMGUI_API ImFont * GetFont ()
IMGUI_API float GetFontSize ()
IMGUI_API ImVec2 GetFontTexUvWhitePixel ()
IMGUI_API int GetFrameCount ()
IMGUI_API float GetFrameHeight ()
IMGUI_API float GetFrameHeightWithSpacing ()
IMGUI_API ImGuiID GetHoveredID ()
IMGUI_API ImGuiID GetID (const char *str_id)
IMGUI_API ImGuiID GetID (const char *str_id_begin, const char *str_id_end)
IMGUI_API ImGuiID GetID (const void *ptr_id)
IMGUI_API ImGuiIO & GetIO ()
IMGUI_API ImVec2 GetItemRectMax ()
IMGUI_API ImVec2 GetItemRectMin ()
IMGUI_API ImVec2 GetItemRectSize ()
static float GetItemsLineHeightWithSpacing ()
IMGUI_API int GetKeyIndex (ImGuiKey imgui_key)
IMGUI_API int GetKeyPressedAmount (int key_index, float repeat_delay, float rate)
IMGUI_API ImGuiMouseCursor GetMouseCursor ()
IMGUI_API ImVec2 GetMouseDragDelta (int button=0, float lock_threshold=-1.0f)
IMGUI_API ImVec2 GetMousePos ()
IMGUI_API ImVec2 GetMousePosOnOpeningCurrentPopup ()
IMGUI_API float GetNavInputAmount (ImGuiNavInput n, ImGuiInputReadMode mode)
IMGUI_API ImVec2 GetNavInputAmount2d (ImGuiNavDirSourceFlags dir_sources, ImGuiInputReadMode mode, float slow_factor=0.0f, float fast_factor=0.0f)
IMGUI_API ImDrawList * GetOverlayDrawList ()
IMGUI_API float GetScrollMaxX ()
IMGUI_API float GetScrollMaxY ()
IMGUI_API float GetScrollX ()
IMGUI_API float GetScrollY ()
IMGUI_API ImGuiStorage * GetStateStorage ()
IMGUI_API ImGuiStyle & GetStyle ()
IMGUI_API const char * GetStyleColorName (ImGuiCol idx)
IMGUI_API const ImVec4 & GetStyleColorVec4 (ImGuiCol idx)
IMGUI_API float GetTextLineHeight ()
IMGUI_API float GetTextLineHeightWithSpacing ()
IMGUI_API float GetTime ()
IMGUI_API float GetTreeNodeToLabelSpacing ()
IMGUI_API const char * GetVersion ()
IMGUI_API ImVec2 GetWindowContentRegionMax ()
IMGUI_API ImVec2 GetWindowContentRegionMin ()
IMGUI_API float GetWindowContentRegionWidth ()
IMGUI_API ImDrawList * GetWindowDrawList ()
IMGUI_API float GetWindowHeight ()
IMGUI_API ImVec2 GetWindowPos ()
IMGUI_API ImVec2 GetWindowSize ()
IMGUI_API float GetWindowWidth ()
IMGUI_API void Image (ImTextureID user_texture_id, const ImVec2 &size, const ImVec2 &uv0=ImVec2(0, 0), const ImVec2 &uv1=ImVec2(1, 1), const ImVec4 &tint_col=ImVec4(1, 1, 1, 1), const ImVec4 &border_col=ImVec4(0, 0, 0, 0))
IMGUI_API bool ImageButton (ImTextureID user_texture_id, const ImVec2 &size, const ImVec2 &uv0=ImVec2(0, 0), const ImVec2 &uv1=ImVec2(1, 1), int frame_padding=-1, const ImVec4 &bg_col=ImVec4(0, 0, 0, 0), const ImVec4 &tint_col=ImVec4(1, 1, 1, 1))
IMGUI_API void Indent (float indent_w=0.0f)
IMGUI_API void Initialize (ImGuiContext *context)
IMGUI_API bool InputFloat (const char *label, float *v, float step=0.0f, float step_fast=0.0f, int decimal_precision=-1, ImGuiInputTextFlags extra_flags=0)
IMGUI_API bool InputFloat2 (const char *label, float v[2], int decimal_precision=-1, ImGuiInputTextFlags extra_flags=0)
IMGUI_API bool InputFloat3 (const char *label, float v[3], int decimal_precision=-1, ImGuiInputTextFlags extra_flags=0)
IMGUI_API bool InputFloat4 (const char *label, float v[4], int decimal_precision=-1, ImGuiInputTextFlags extra_flags=0)
IMGUI_API bool InputFloatN (const char *label, float *v, int components, int decimal_precision, ImGuiInputTextFlags extra_flags)
IMGUI_API bool InputInt (const char *label, int *v, int step=1, int step_fast=100, ImGuiInputTextFlags extra_flags=0)
IMGUI_API bool InputInt2 (const char *label, int v[2], ImGuiInputTextFlags extra_flags=0)
IMGUI_API bool InputInt3 (const char *label, int v[3], ImGuiInputTextFlags extra_flags=0)
IMGUI_API bool InputInt4 (const char *label, int v[4], ImGuiInputTextFlags extra_flags=0)
IMGUI_API bool InputIntN (const char *label, int *v, int components, ImGuiInputTextFlags extra_flags)
IMGUI_API bool InputScalarAsWidgetReplacement (const ImRect &aabb, const char *label, ImGuiDataType data_type, void *data_ptr, ImGuiID id, int decimal_precision)
IMGUI_API bool InputScalarEx (const char *label, ImGuiDataType data_type, void *data_ptr, void *step_ptr, void *step_fast_ptr, const char *scalar_format, ImGuiInputTextFlags extra_flags)
IMGUI_API bool InputText (const char *label, char *buf, size_t buf_size, ImGuiInputTextFlags flags=0, ImGuiTextEditCallback callback=NULL, void *user_data=NULL)
IMGUI_API bool InputTextEx (const char *label, char *buf, int buf_size, const ImVec2 &size_arg, ImGuiInputTextFlags flags, ImGuiTextEditCallback callback=NULL, void *user_data=NULL)
IMGUI_API bool InputTextMultiline (const char *label, char *buf, size_t buf_size, const ImVec2 &size=ImVec2(0, 0), ImGuiInputTextFlags flags=0, ImGuiTextEditCallback callback=NULL, void *user_data=NULL)
IMGUI_API bool InvisibleButton (const char *str_id, const ImVec2 &size)
IMGUI_API bool IsAnyItemActive ()
IMGUI_API bool IsAnyItemFocused ()
IMGUI_API bool IsAnyItemHovered ()
IMGUI_API bool IsAnyMouseDown ()
static bool IsAnyWindowFocused ()
static bool IsAnyWindowHovered ()
IMGUI_API bool IsClippedEx (const ImRect &bb, ImGuiID id, bool clip_even_when_logged)
IMGUI_API bool IsDragDropPayloadBeingAccepted ()
IMGUI_API bool IsItemActive ()
IMGUI_API bool IsItemClicked (int mouse_button=0)
IMGUI_API bool IsItemFocused ()
IMGUI_API bool IsItemHovered (ImGuiHoveredFlags flags=0)
static bool IsItemHoveredRect ()
IMGUI_API bool IsItemVisible ()
IMGUI_API bool IsKeyDown (int user_key_index)
IMGUI_API bool IsKeyPressed (int user_key_index, bool repeat=true)
IMGUI_API bool IsKeyReleased (int user_key_index)
IMGUI_API bool IsMouseClicked (int button, bool repeat=false)
IMGUI_API bool IsMouseDoubleClicked (int button)
IMGUI_API bool IsMouseDown (int button)
IMGUI_API bool IsMouseDragging (int button=0, float lock_threshold=-1.0f)
static bool IsMouseHoveringAnyWindow ()
IMGUI_API bool IsMouseHoveringRect (const ImVec2 &r_min, const ImVec2 &r_max, bool clip=true)
static bool IsMouseHoveringWindow ()
IMGUI_API bool IsMousePosValid (const ImVec2 *mouse_pos=NULL)
IMGUI_API bool IsMouseReleased (int button)
IMGUI_API bool IsPopupOpen (const char *str_id)
IMGUI_API bool IsPopupOpen (ImGuiID id)
static bool IsPosHoveringAnyWindow (const ImVec2 &)
IMGUI_API bool IsRectVisible (const ImVec2 &size)
IMGUI_API bool IsRectVisible (const ImVec2 &rect_min, const ImVec2 &rect_max)
static bool IsRootWindowFocused ()
static bool IsRootWindowOrAnyChildFocused ()
static bool IsRootWindowOrAnyChildHovered ()
IMGUI_API bool IsWindowAppearing ()
IMGUI_API bool IsWindowChildOf (ImGuiWindow *window, ImGuiWindow *potential_parent)
IMGUI_API bool IsWindowCollapsed ()
IMGUI_API bool IsWindowFocused (ImGuiFocusedFlags flags=0)
IMGUI_API bool IsWindowHovered (ImGuiHoveredFlags flags=0)
IMGUI_API bool IsWindowNavFocusable (ImGuiWindow *window)
IMGUI_API bool ItemAdd (const ImRect &bb, ImGuiID id, const ImRect *nav_bb=NULL)
IMGUI_API bool ItemHoverable (const ImRect &bb, ImGuiID id)
IMGUI_API void ItemSize (const ImVec2 &size, float text_offset_y=0.0f)
IMGUI_API void ItemSize (const ImRect &bb, float text_offset_y=0.0f)
IMGUI_API void KeepAliveID (ImGuiID id)
IMGUI_API void LabelText (const char *label, const char *fmt,...) IM_FMTARGS(2)
IMGUI_API void LabelTextV (const char *label, const char *fmt, va_list args) IM_FMTLIST(2)
IMGUI_API bool ListBox (const char *label, int *current_item, const char *const items[], int items_count, int height_in_items=-1)
IMGUI_API bool ListBox (const char *label, int *current_item, bool(*items_getter)(void *data, int idx, const char **out_text), void *data, int items_count, int height_in_items=-1)
IMGUI_API void ListBoxFooter ()
IMGUI_API bool ListBoxHeader (const char *label, const ImVec2 &size=ImVec2(0, 0))
IMGUI_API bool ListBoxHeader (const char *label, int items_count, int height_in_items=-1)
IMGUI_API void LogButtons ()
IMGUI_API void LogFinish ()
IMGUI_API void LogText (const char *fmt,...) IM_FMTARGS(1)
IMGUI_API void LogToClipboard (int max_depth=-1)
IMGUI_API void LogToFile (int max_depth=-1, const char *filename=NULL)
IMGUI_API void LogToTTY (int max_depth=-1)
IMGUI_API void MarkIniSettingsDirty ()
IMGUI_API void * MemAlloc (size_t size)
IMGUI_API void MemFree (void *ptr)
IMGUI_API bool MenuItem (const char *label, const char *shortcut=NULL, bool selected=false, bool enabled=true)
IMGUI_API bool MenuItem (const char *label, const char *shortcut, bool *p_selected, bool enabled=true)
IMGUI_API void NavInitWindow (ImGuiWindow *window, bool force_reinit)
IMGUI_API void NavMoveRequestCancel ()
static void NavProcessItem (ImGuiWindow *window, const ImRect &nav_bb, const ImGuiID id)
static void NavUpdate ()
static void NavUpdateWindowing ()
IMGUI_API void NewFrame ()
IMGUI_API void NewLine ()
IMGUI_API void NextColumn ()
IMGUI_API void OpenPopup (const char *str_id)
IMGUI_API void OpenPopupEx (ImGuiID id)
IMGUI_API bool OpenPopupOnItemClick (const char *str_id=NULL, int mouse_button=1)
IMGUI_API int ParseFormatPrecision (const char *fmt, int default_value)
IMGUI_API void PlotEx (ImGuiPlotType plot_type, const char *label, float(*values_getter)(void *data, int idx), void *data, int values_count, int values_offset, const char *overlay_text, float scale_min, float scale_max, ImVec2 graph_size)
IMGUI_API void PlotHistogram (const char *label, const float *values, int values_count, int values_offset=0, const char *overlay_text=NULL, float scale_min=FLT_MAX, float scale_max=FLT_MAX, ImVec2 graph_size=ImVec2(0, 0), int stride=sizeof(float))
IMGUI_API void PlotHistogram (const char *label, float(*values_getter)(void *data, int idx), void *data, int values_count, int values_offset=0, const char *overlay_text=NULL, float scale_min=FLT_MAX, float scale_max=FLT_MAX, ImVec2 graph_size=ImVec2(0, 0))
IMGUI_API void PlotLines (const char *label, const float *values, int values_count, int values_offset=0, const char *overlay_text=NULL, float scale_min=FLT_MAX, float scale_max=FLT_MAX, ImVec2 graph_size=ImVec2(0, 0), int stride=sizeof(float))
IMGUI_API void PlotLines (const char *label, float(*values_getter)(void *data, int idx), void *data, int values_count, int values_offset=0, const char *overlay_text=NULL, float scale_min=FLT_MAX, float scale_max=FLT_MAX, ImVec2 graph_size=ImVec2(0, 0))
IMGUI_API void PopAllowKeyboardFocus ()
IMGUI_API void PopButtonRepeat ()
IMGUI_API void PopClipRect ()
IMGUI_API void PopFont ()
IMGUI_API void PopID ()
IMGUI_API void PopItemFlag ()
IMGUI_API void PopItemWidth ()
IMGUI_API void PopStyleColor (int count=1)
IMGUI_API void PopStyleVar (int count=1)
IMGUI_API void PopTextWrapPos ()
IMGUI_API void ProgressBar (float fraction, const ImVec2 &size_arg=ImVec2(-1, 0), const char *overlay=NULL)
IMGUI_API void PushAllowKeyboardFocus (bool allow_keyboard_focus)
IMGUI_API void PushButtonRepeat (bool repeat)
IMGUI_API void PushClipRect (const ImVec2 &clip_rect_min, const ImVec2 &clip_rect_max, bool intersect_with_current_clip_rect)
IMGUI_API void PushColumnClipRect (int column_index=-1)
IMGUI_API void PushFont (ImFont *font)
IMGUI_API void PushID (const char *str_id)
IMGUI_API void PushID (const char *str_id_begin, const char *str_id_end)
IMGUI_API void PushID (const void *ptr_id)
IMGUI_API void PushID (int int_id)
IMGUI_API void PushItemFlag (ImGuiItemFlags option, bool enabled)
IMGUI_API void PushItemWidth (float item_width)
IMGUI_API void PushMultiItemsWidths (int components, float width_full=0.0f)
IMGUI_API void PushStyleColor (ImGuiCol idx, ImU32 col)
IMGUI_API void PushStyleColor (ImGuiCol idx, const ImVec4 &col)
IMGUI_API void PushStyleVar (ImGuiStyleVar idx, float val)
IMGUI_API void PushStyleVar (ImGuiStyleVar idx, const ImVec2 &val)
IMGUI_API void PushTextWrapPos (float wrap_pos_x=0.0f)
IMGUI_API bool RadioButton (const char *label, bool active)
IMGUI_API bool RadioButton (const char *label, int *v, int v_button)
IMGUI_API void Render ()
IMGUI_API void RenderBullet (ImVec2 pos)
IMGUI_API void RenderCheckMark (ImVec2 pos, ImU32 col, float sz)
IMGUI_API void RenderColorRectWithAlphaCheckerboard (ImVec2 p_min, ImVec2 p_max, ImU32 fill_col, float grid_step, ImVec2 grid_off, float rounding=0.0f, int rounding_corners_flags=~0)
IMGUI_API void RenderFrame (ImVec2 p_min, ImVec2 p_max, ImU32 fill_col, bool border=true, float rounding=0.0f)
IMGUI_API void RenderFrameBorder (ImVec2 p_min, ImVec2 p_max, float rounding=0.0f)
IMGUI_API void RenderNavHighlight (const ImRect &bb, ImGuiID id, ImGuiNavHighlightFlags flags=ImGuiNavHighlightFlags_TypeDefault)
IMGUI_API void RenderRectFilledRangeH (ImDrawList *draw_list, const ImRect &rect, ImU32 col, float x_start_norm, float x_end_norm, float rounding)
IMGUI_API void RenderText (ImVec2 pos, const char *text, const char *text_end=NULL, bool hide_text_after_hash=true)
IMGUI_API void RenderTextClipped (const ImVec2 &pos_min, const ImVec2 &pos_max, const char *text, const char *text_end, const ImVec2 *text_size_if_known, const ImVec2 &align=ImVec2(0, 0), const ImRect *clip_rect=NULL)
IMGUI_API void RenderTextWrapped (ImVec2 pos, const char *text, const char *text_end, float wrap_width)
IMGUI_API void RenderTriangle (ImVec2 pos, ImGuiDir dir, float scale=1.0f)
IMGUI_API void ResetMouseDragDelta (int button=0)
IMGUI_API float RoundScalar (float value, int decimal_precision)
IMGUI_API void SameLine (float pos_x=0.0f, float spacing_w=-1.0f)
IMGUI_API void Scrollbar (ImGuiLayoutType direction)
IMGUI_API bool Selectable (const char *label, bool selected=false, ImGuiSelectableFlags flags=0, const ImVec2 &size=ImVec2(0, 0))
IMGUI_API bool Selectable (const char *label, bool *p_selected, ImGuiSelectableFlags flags=0, const ImVec2 &size=ImVec2(0, 0))
IMGUI_API void Separator ()
IMGUI_API void SetActiveID (ImGuiID id, ImGuiWindow *window)
IMGUI_API void SetAllocatorFunctions (void *(*alloc_func)(size_t sz, void *user_data), void(*free_func)(void *ptr, void *user_data), void *user_data=NULL)
IMGUI_API void SetClipboardText (const char *text)
IMGUI_API void SetColorEditOptions (ImGuiColorEditFlags flags)
IMGUI_API void SetColumnOffset (int column_index, float offset_x)
IMGUI_API void SetColumnWidth (int column_index, float width)
IMGUI_API void SetCurrentContext (ImGuiContext *ctx)
IMGUI_API void SetCurrentFont (ImFont *font)
IMGUI_API void SetCursorPos (const ImVec2 &local_pos)
IMGUI_API void SetCursorPosX (float x)
IMGUI_API void SetCursorPosY (float y)
IMGUI_API void SetCursorScreenPos (const ImVec2 &pos)
IMGUI_API bool SetDragDropPayload (const char *type, const void *data, size_t size, ImGuiCond cond=0)
IMGUI_API void SetFocusID (ImGuiID id, ImGuiWindow *window)
IMGUI_API void SetHoveredID (ImGuiID id)
IMGUI_API void SetItemAllowOverlap ()
IMGUI_API void SetItemDefaultFocus ()
IMGUI_API void SetKeyboardFocusHere (int offset=0)
IMGUI_API void SetMouseCursor (ImGuiMouseCursor type)
IMGUI_API void SetNextTreeNodeOpen (bool is_open, ImGuiCond cond=0)
IMGUI_API void SetNextWindowBgAlpha (float alpha)
IMGUI_API void SetNextWindowCollapsed (bool collapsed, ImGuiCond cond=0)
IMGUI_API void SetNextWindowContentSize (const ImVec2 &size)
static void SetNextWindowContentWidth (float w)
IMGUI_API void SetNextWindowFocus ()
IMGUI_API void SetNextWindowPos (const ImVec2 &pos, ImGuiCond cond=0, const ImVec2 &pivot=ImVec2(0, 0))
static void SetNextWindowPosCenter (ImGuiCond c=0)
IMGUI_API void SetNextWindowSize (const ImVec2 &size, ImGuiCond cond=0)
IMGUI_API void SetNextWindowSizeConstraints (const ImVec2 &size_min, const ImVec2 &size_max, ImGuiSizeCallback custom_callback=NULL, void *custom_callback_data=NULL)
IMGUI_API void SetScrollFromPosY (float pos_y, float center_y_ratio=0.5f)
IMGUI_API void SetScrollHere (float center_y_ratio=0.5f)
IMGUI_API void SetScrollX (float scroll_x)
IMGUI_API void SetScrollY (float scroll_y)
IMGUI_API void SetStateStorage (ImGuiStorage *tree)
IMGUI_API void SetTooltip (const char *fmt,...) IM_FMTARGS(1)
IMGUI_API void SetTooltipV (const char *fmt, va_list args) IM_FMTLIST(1)
IMGUI_API void SetWindowCollapsed (bool collapsed, ImGuiCond cond=0)
IMGUI_API void SetWindowCollapsed (const char *name, bool collapsed, ImGuiCond cond=0)
IMGUI_API void SetWindowFocus ()
IMGUI_API void SetWindowFocus (const char *name)
IMGUI_API void SetWindowFontScale (float scale)
IMGUI_API void SetWindowPos (const ImVec2 &pos, ImGuiCond cond=0)
IMGUI_API void SetWindowPos (const char *name, const ImVec2 &pos, ImGuiCond cond=0)
IMGUI_API void SetWindowSize (const ImVec2 &size, ImGuiCond cond=0)
IMGUI_API void SetWindowSize (const char *name, const ImVec2 &size, ImGuiCond cond=0)
IMGUI_API void ShadeVertsLinearAlphaGradientForLeftToRightText (ImDrawVert *vert_start, ImDrawVert *vert_end, float gradient_p0_x, float gradient_p1_x)
IMGUI_API void ShadeVertsLinearColorGradientKeepAlpha (ImDrawVert *vert_start, ImDrawVert *vert_end, ImVec2 gradient_p0, ImVec2 gradient_p1, ImU32 col0, ImU32 col1)
IMGUI_API void ShadeVertsLinearUV (ImDrawVert *vert_start, ImDrawVert *vert_end, const ImVec2 &a, const ImVec2 &b, const ImVec2 &uv_a, const ImVec2 &uv_b, bool clamp)
IMGUI_API void ShowDemoWindow (bool *p_open=NULL)
IMGUI_API void ShowFontSelector (const char *label)
IMGUI_API void ShowMetricsWindow (bool *p_open=NULL)
IMGUI_API void ShowStyleEditor (ImGuiStyle *ref=NULL)
IMGUI_API bool ShowStyleSelector (const char *label)
static void ShowTestWindow ()
IMGUI_API void ShowUserGuide ()
IMGUI_API void Shutdown (ImGuiContext *context)
IMGUI_API bool SliderAngle (const char *label, float *v_rad, float v_degrees_min=-360.0f, float v_degrees_max=+360.0f)
IMGUI_API bool SliderBehavior (const ImRect &frame_bb, ImGuiID id, float *v, float v_min, float v_max, float power, int decimal_precision, ImGuiSliderFlags flags=0)
IMGUI_API bool SliderFloat (const char *label, float *v, float v_min, float v_max, const char *display_format="%.3f", float power=1.0f)
IMGUI_API bool SliderFloat2 (const char *label, float v[2], float v_min, float v_max, const char *display_format="%.3f", float power=1.0f)
IMGUI_API bool SliderFloat3 (const char *label, float v[3], float v_min, float v_max, const char *display_format="%.3f", float power=1.0f)
IMGUI_API bool SliderFloat4 (const char *label, float v[4], float v_min, float v_max, const char *display_format="%.3f", float power=1.0f)
IMGUI_API bool SliderFloatN (const char *label, float *v, int components, float v_min, float v_max, const char *display_format, float power)
IMGUI_API bool SliderInt (const char *label, int *v, int v_min, int v_max, const char *display_format="%.0f")
IMGUI_API bool SliderInt2 (const char *label, int v[2], int v_min, int v_max, const char *display_format="%.0f")
IMGUI_API bool SliderInt3 (const char *label, int v[3], int v_min, int v_max, const char *display_format="%.0f")
IMGUI_API bool SliderInt4 (const char *label, int v[4], int v_min, int v_max, const char *display_format="%.0f")
IMGUI_API bool SliderIntN (const char *label, int *v, int components, int v_min, int v_max, const char *display_format)
IMGUI_API bool SmallButton (const char *label)
IMGUI_API void Spacing ()
IMGUI_API bool SplitterBehavior (ImGuiID id, const ImRect &bb, ImGuiAxis axis, float *size1, float *size2, float min_size1, float min_size2, float hover_extend=0.0f)
IMGUI_API void StyleColorsClassic (ImGuiStyle *dst=NULL)
IMGUI_API void StyleColorsDark (ImGuiStyle *dst=NULL)
IMGUI_API void StyleColorsLight (ImGuiStyle *dst=NULL)
IMGUI_API void Text (const char *fmt,...) IM_FMTARGS(1)
IMGUI_API void TextColored (const ImVec4 &col, const char *fmt,...) IM_FMTARGS(2)
IMGUI_API void TextColoredV (const ImVec4 &col, const char *fmt, va_list args) IM_FMTLIST(2)
IMGUI_API void TextDisabled (const char *fmt,...) IM_FMTARGS(1)
IMGUI_API void TextDisabledV (const char *fmt, va_list args) IM_FMTLIST(1)
IMGUI_API void TextUnformatted (const char *text, const char *text_end=NULL)
IMGUI_API void TextV (const char *fmt, va_list args) IM_FMTLIST(1)
IMGUI_API void TextWrapped (const char *fmt,...) IM_FMTARGS(1)
IMGUI_API void TextWrappedV (const char *fmt, va_list args) IM_FMTLIST(1)
IMGUI_API void TreeAdvanceToLabelPos ()
IMGUI_API bool TreeNode (const char *label)
IMGUI_API bool TreeNode (const char *str_id, const char *fmt,...) IM_FMTARGS(2)
IMGUI_API bool TreeNode (const void *ptr_id, const char *fmt,...) IM_FMTARGS(2)
IMGUI_API bool TreeNodeBehavior (ImGuiID id, ImGuiTreeNodeFlags flags, const char *label, const char *label_end=NULL)
IMGUI_API bool TreeNodeBehaviorIsOpen (ImGuiID id, ImGuiTreeNodeFlags flags=0)
IMGUI_API bool TreeNodeEx (const char *label, ImGuiTreeNodeFlags flags=0)
IMGUI_API bool TreeNodeEx (const char *str_id, ImGuiTreeNodeFlags flags, const char *fmt,...) IM_FMTARGS(3)
IMGUI_API bool TreeNodeEx (const void *ptr_id, ImGuiTreeNodeFlags flags, const char *fmt,...) IM_FMTARGS(3)
IMGUI_API bool TreeNodeExV (const char *str_id, ImGuiTreeNodeFlags flags, const char *fmt, va_list args) IM_FMTLIST(3)
IMGUI_API bool TreeNodeExV (const void *ptr_id, ImGuiTreeNodeFlags flags, const char *fmt, va_list args) IM_FMTLIST(3)
IMGUI_API bool TreeNodeV (const char *str_id, const char *fmt, va_list args) IM_FMTLIST(2)
IMGUI_API bool TreeNodeV (const void *ptr_id, const char *fmt, va_list args) IM_FMTLIST(2)
IMGUI_API void TreePop ()
IMGUI_API void TreePush (const char *str_id)
IMGUI_API void TreePush (const void *ptr_id=NULL)
IMGUI_API void TreePushRawID (ImGuiID id)
IMGUI_API void Unindent (float indent_w=0.0f)
static void UpdateManualResize (ImGuiWindow *window, const ImVec2 &size_auto_fit, int *border_held, int resize_grip_count, ImU32 resize_grip_col[4])
static void UpdateMovingWindow ()
IMGUI_API void Value (const char *prefix, bool b)
IMGUI_API void Value (const char *prefix, int v)
IMGUI_API void Value (const char *prefix, unsigned int v)
IMGUI_API void Value (const char *prefix, float v, const char *float_format=NULL)
IMGUI_API void VerticalSeparator ()
IMGUI_API bool VSliderFloat (const char *label, const ImVec2 &size, float *v, float v_min, float v_max, const char *display_format="%.3f", float power=1.0f)
IMGUI_API bool VSliderInt (const char *label, const ImVec2 &size, int *v, int v_min, int v_max, const char *display_format="%.0f")
Function Documentation
GetCurrentWindowRead()
ImGuiWindow* ImGui::GetCurrentWindowRead () inline
References ImGuiContext::CurrentWindow, and GImGui.
Referenced by CalcItemWidth(), CalcWrapWidthForPos(), EndTooltip(), GetColumnIndex(), GetColumnOffset(), GetColumnsCount(), GetColumnWidth(), GetContentRegionAvail(), GetContentRegionMax(), GetCursorPos(), GetCursorPosX(), GetCursorPosY(), GetCursorScreenPos(), GetCursorStartPos(), GetItemRectMax(), GetItemRectMin(), GetItemRectSize(), GetStateStorage(), GetWindowContentRegionMax(), GetWindowContentRegionMin(), GetWindowContentRegionWidth(), GetWindowSize(), IsItemVisible(), IsRectVisible(), IsWindowAppearing(), IsWindowCollapsed(), PopID(), PushColumnClipRect(), PushID(), SetColumnWidth(), SetWindowPos(), and ImGuiListClipper::Step().
GetCurrentWindow()
ImGuiWindow* ImGui::GetCurrentWindow () inline
References ImGuiContext::CurrentWindow, GImGui, and ImGuiWindow::WriteAccessed.
Referenced by AlignTextToFramePadding(), BeginChild(), BeginChildEx(), BeginColumns(), BeginCombo(), BeginGroup(), BeginMenu(), BeginMenuBar(), Bullet(), BulletTextV(), ButtonBehavior(), ButtonEx(), Checkbox(), CollapsingHeader(), ColorButton(), ColorEdit4(), ColorPicker4(), Columns(), DragFloat(), DragFloatN(), DragFloatRange2(), DragIntN(), DragIntRange2(), Dummy(), EndColumns(), EndGroup(), EndMenuBar(), GetWindowDrawList(), Image(), ImageButton(), Indent(), InputFloatN(), InputIntN(), InputScalarAsWidgetReplacement(), InputScalarEx(), InputTextEx(), InvisibleButton(), LabelTextV(), ListBoxFooter(), ListBoxHeader(), MenuItem(), NewLine(), NextColumn(), PlotEx(), PopClipRect(), PopItemFlag(), PopItemWidth(), PopTextWrapPos(), ProgressBar(), PushClipRect(), PushItemFlag(), PushItemWidth(), PushMultiItemsWidths(), PushTextWrapPos(), RadioButton(), RenderColorRectWithAlphaCheckerboard(), RenderNavHighlight(), SameLine(), Selectable(), Separator(), SetCursorPos(), SetCursorPosX(), SetCursorPosY(), SetCursorPosYAndSetupDummyPrevLine(), SetCursorScreenPos(), SetKeyboardFocusHere(), SetScrollFromPosY(), SetScrollHere(), SetScrollX(), SetScrollY(), SetStateStorage(), SetWindowFontScale(), SliderBehavior(), SliderFloat(), SliderFloatN(), SliderIntN(), Spacing(), TextUnformatted(), TextV(), TreeNode(), TreeNodeBehavior(), TreeNodeEx(), TreeNodeExV(), TreePush(), TreePushRawID(), Unindent(), VerticalSeparator(), and VSliderFloat().
FindWindowByName()
ImGuiWindow * ImGui::FindWindowByName (const char * name)
References ImGuiStorage::GetVoidPtr(), GImGui, ImHash(), setup::name, and ImGuiContext::WindowsById.
Referenced by Begin(), BeginCombo(), BeginTooltipEx(), SetWindowCollapsed(), SetWindowFocus(), SetWindowPos(), and SetWindowSize().
FocusWindow()
void ImGui::FocusWindow (ImGuiWindow * window)
References ImGuiContext::ActiveId, ImGuiContext::ActiveIdWindow, BringWindowToFront(), ClearActiveID(), ImGuiWindow::Flags, GImGui, ImGuiWindowFlags_NoBringToFrontOnFocus, ImGuiWindowFlags_Popup, ImGuiContext::NavDisableMouseHover, ImGuiContext::NavId, ImGuiContext::NavIdIsAlive, ImGuiContext::NavInitRequest, ImGuiWindow::NavLastIds, ImGuiContext::NavLayer, ImGuiContext::NavMousePosDirty, ImGuiContext::NavWindow, and ImGuiWindow::RootWindow.
Referenced by Begin(), BeginChildEx(), BeginDragDropSource(), ButtonBehavior(), ClosePopupToLevel(), DragFloat(), EndFrame(), EndMenuBar(), FocusFrontMostActiveWindow(), InputTextEx(), NavUpdate(), NavUpdateWindowing(), SetWindowFocus(), SliderFloat(), UpdateMovingWindow(), and VSliderFloat().
BringWindowToFront()
void ImGui::BringWindowToFront (ImGuiWindow * window)
References ImVector< T >::back(), ImVector< T >::Data, ImVector< T >::erase(), GImGui, ImVector< T >::push_back(), ImGuiWindow::RootWindow, ImVector< T >::Size, and ImGuiContext::Windows.
Referenced by FocusWindow().
BringWindowToBack()
void ImGui::BringWindowToBack (ImGuiWindow * window)
References GImGui, memmove(), ImVector< T >::Size, and ImGuiContext::Windows.
IsWindowChildOf()
bool ImGui::IsWindowChildOf (ImGuiWindow * window, ImGuiWindow * potential_parent)
References NULL, ImGuiWindow::ParentWindow, and ImGuiWindow::RootWindow.
Referenced by IsWindowFocused(), IsWindowHovered(), and NewFrame().
IsWindowNavFocusable()
bool ImGui::IsWindowNavFocusable (ImGuiWindow * window)
References ImGuiWindow::Active, ImGuiWindow::Flags, GImGui, ImGuiWindowFlags_NoNavFocus, ImGuiContext::NavWindow, and ImGuiWindow::RootWindowForTabbing.
Referenced by FindWindowNavigable().
Initialize()
void ImGui::Initialize (ImGuiContext * context)
References IM_ASSERT, IM_NEW, ImHash(), ImGuiContext::Initialized, ImGuiContext::LogClipboard, ImVector< T >::push_front(), ImGuiSettingsHandler::ReadLineFn, ImGuiSettingsHandler::ReadOpenFn, ImGuiContext::SettingsHandlers, SettingsHandlerWindow_ReadLine(), SettingsHandlerWindow_ReadOpen(), SettingsHandlerWindow_WriteAll(), ImGuiContext::SettingsLoaded, ImGuiSettingsHandler::TypeHash, ImGuiSettingsHandler::TypeName, and ImGuiSettingsHandler::WriteAllFn.
Referenced by CreateContext().
Shutdown()
void ImGui::Shutdown (ImGuiContext * context)
References ImGuiContext::ActiveIdWindow, ImVector< T >::clear(), ImGuiStorage::Clear(), ImDrawDataBuilder::ClearFreeMemory(), ImDrawList::ClearFreeMemory(), ImGuiContext::ColorModifiers, ImGuiContext::CurrentPopupStack, ImGuiContext::CurrentWindow, ImGuiContext::CurrentWindowStack, ImGuiContext::DrawDataBuilder, ImGuiContext::FontAtlasOwnedByContext, ImGuiIO::Fonts, ImGuiContext::FontStack, ImGuiContext::HoveredRootWindow, ImGuiContext::HoveredWindow, IM_DELETE(), ImGuiIO::IniFilename, ImGuiContext::Initialized, ImGuiTextEditState::InitialText, ImGuiContext::InputTextState, ImGuiContext::IO, ImGuiContext::LogClipboard, ImGuiContext::LogFile, ImGuiContext::MovingWindow, ImGuiContext::NavWindow, NULL, ImGuiContext::OpenPopupStack, ImGuiContext::OverlayDrawList, ImGuiContext::PrivateClipboard, SaveIniSettingsToDisk(), ImGuiContext::SettingsHandlers, ImGuiContext::SettingsWindows, ImVector< T >::Size, ImGuiContext::StyleModifiers, ImGuiTextEditState::TempTextBuffer, ImGuiTextEditState::Text, ImGuiContext::Windows, ImGuiContext::WindowsById, and ImGuiContext::WindowsSortBuffer.
Referenced by DestroyContext().
MarkIniSettingsDirty()
void ImGui::MarkIniSettingsDirty ()
References GImGui, ImGuiIO::IniSavingRate, ImGuiContext::IO, and ImGuiContext::SettingsDirtyTimer.
FindSettingsHandler()
ImGuiSettingsHandler * ImGui::FindSettingsHandler (const char * type_name)
References GImGui, ImHash(), NULL, ImGuiContext::SettingsHandlers, and ImVector< T >::Size.
Referenced by LoadIniSettingsFromMemory().
FindWindowSettings()
ImGuiWindowSettings * ImGui::FindWindowSettings (ImGuiID id)
References GImGui, NULL, ImGuiContext::SettingsWindows, and ImVector< T >::Size.
Referenced by CreateNewWindow(), SettingsHandlerWindow_ReadOpen(), and SettingsHandlerWindow_WriteAll().
SetActiveID()
void ImGui::SetActiveID (ImGuiID id, ImGuiWindow * window)
References ImGuiContext::ActiveId, ImGuiContext::ActiveIdAllowNavDirFlags, ImGuiContext::ActiveIdAllowOverlap, ImGuiContext::ActiveIdIsAlive, ImGuiContext::ActiveIdIsJustActivated, ImGuiContext::ActiveIdSource, ImGuiContext::ActiveIdTimer, ImGuiContext::ActiveIdWindow, GImGui, ImGuiInputSource_Mouse, ImGuiInputSource_Nav, ImGuiContext::NavActivateId, ImGuiContext::NavInputId, ImGuiContext::NavJustMovedToId, and ImGuiContext::NavJustTabbedId.
Referenced by BeginChildEx(), BeginDragDropSource(), ButtonBehavior(), ClearActiveID(), DragFloat(), EndFrame(), InputScalarAsWidgetReplacement(), InputTextEx(), SliderFloat(), and VSliderFloat().
GetActiveID()
ImGuiID ImGui::GetActiveID ()
References ImGuiContext::ActiveId, and GImGui.
SetFocusID()
void ImGui::SetFocusID (ImGuiID id, ImGuiWindow * window)
References ImGuiContext::ActiveIdSource, ImGuiWindow::DC, GImGui, IM_ASSERT, ImGuiInputSource_Nav, ImGuiDrawContext::LastItemId, ImGuiDrawContext::LastItemRect, ImRect::Max, ImRect::Min, ImGuiContext::NavDisableHighlight, ImGuiContext::NavDisableMouseHover, ImGuiContext::NavId, ImGuiContext::NavInitRequest, ImGuiWindow::NavLastIds, ImGuiContext::NavLayer, ImGuiDrawContext::NavLayerCurrent, ImGuiWindow::NavRectRel, ImGuiContext::NavWindow, and ImGuiWindow::Pos.
Referenced by ButtonBehavior(), DragFloat(), InputTextEx(), SliderFloat(), and VSliderFloat().
ClearActiveID()
void ImGui::ClearActiveID ()
References NULL, and SetActiveID().
Referenced by ButtonBehavior(), DragBehavior(), FocusWindow(), InputTextEx(), NavUpdate(), NewFrame(), SliderBehavior(), UpdateManualResize(), and UpdateMovingWindow().
SetHoveredID()
void ImGui::SetHoveredID (ImGuiID id)
References ImGuiIO::DeltaTime, GImGui, ImGuiContext::HoveredId, ImGuiContext::HoveredIdAllowOverlap, ImGuiContext::HoveredIdPreviousFrame, ImGuiContext::HoveredIdTimer, and ImGuiContext::IO.
Referenced by BeginDragDropSource(), ButtonBehavior(), InputScalarAsWidgetReplacement(), ItemHoverable(), and Scrollbar().
GetHoveredID()
ImGuiID ImGui::GetHoveredID ()
References GImGui, ImGuiContext::HoveredId, and ImGuiContext::HoveredIdPreviousFrame.
KeepAliveID()
void ImGui::KeepAliveID (ImGuiID id)
References ImGuiContext::ActiveId, ImGuiContext::ActiveIdIsAlive, and GImGui.
Referenced by EndColumns(), ImGuiWindow::GetID(), ImGuiWindow::GetIDFromRectangle(), and UpdateMovingWindow().
ItemSize() [1/2]
void ImGui::ItemSize (const ImVec2 & size, float text_offset_y = 0.0f)
References ImGuiDrawContext::ColumnsOffsetX, ImGuiDrawContext::CurrentLineHeight, ImGuiDrawContext::CurrentLineTextBaseOffset, ImGuiContext::CurrentWindow, ImGuiDrawContext::CursorMaxPos, ImGuiDrawContext::CursorPos, ImGuiDrawContext::CursorPosPrevLine, ImGuiWindow::DC, GImGui, ImGuiLayoutType_Horizontal, ImMax(), ImGuiDrawContext::IndentX, ImGuiStyle::ItemSpacing, ImGuiDrawContext::LayoutType, ImGuiWindow::Pos, ImGuiDrawContext::PrevLineHeight, ImGuiDrawContext::PrevLineTextBaseOffset, SameLine(), ImGuiWindow::SkipItems, ImGuiContext::Style, ImVec2::x, and ImVec2::y.
Referenced by ArrowButton(), BeginCombo(), Bullet(), BulletTextV(), ButtonEx(), Checkbox(), ColorButton(), DragFloat(), Dummy(), EndChild(), EndGroup(), Image(), ImageButton(), InputScalarEx(), InputTextEx(), InvisibleButton(), ItemSize(), LabelTextV(), ListBoxFooter(), NewLine(), PlotEx(), ProgressBar(), RadioButton(), Selectable(), Separator(), SliderFloat(), Spacing(), TextUnformatted(), TreeNodeBehavior(), VerticalSeparator(), and VSliderFloat().
ItemSize() [2/2]
void ImGui::ItemSize (const ImRect & bb, float text_offset_y = 0.0f)
References ImRect::GetSize(), and ItemSize().
ItemAdd()
bool ImGui::ItemAdd (const ImRect & bb, ImGuiID id, const ImRect * nav_bb = NULL)
References ImGuiContext::CurrentWindow, ImGuiWindow::DC, ImGuiWindow::Flags, GImGui, ImGuiItemStatusFlags_HoveredRect, ImGuiWindowFlags_NavFlattened, IsClippedEx(), IsMouseHoveringRect(), ImGuiDrawContext::LastItemId, ImGuiDrawContext::LastItemRect, ImGuiDrawContext::LastItemStatusFlags, ImRect::Max, ImRect::Min, ImGuiContext::NavAnyRequest, ImGuiContext::NavId, ImGuiDrawContext::NavLayerActiveMaskNext, ImGuiDrawContext::NavLayerCurrentMask, NavProcessItem(), ImGuiContext::NavWindow, and ImGuiWindow::RootWindowForNav.
Referenced by ArrowButton(), Begin(), BeginCombo(), Bullet(), BulletTextV(), ButtonEx(), Checkbox(), CloseButton(), ColorButton(), DragFloat(), Dummy(), EndChild(), EndGroup(), Image(), ImageButton(), InputTextEx(), InvisibleButton(), LabelTextV(), PlotEx(), ProgressBar(), RadioButton(), Selectable(), Separator(), SliderFloat(), SplitterBehavior(), TextUnformatted(), TreeNodeBehavior(), VerticalSeparator(), and VSliderFloat().
ItemHoverable()
bool ImGui::ItemHoverable (const ImRect & bb, ImGuiID id)
References ImGuiContext::ActiveId, ImGuiContext::ActiveIdAllowOverlap, ImGuiContext::CurrentWindow, ImGuiWindow::DC, GImGui, ImGuiContext::HoveredId, ImGuiContext::HoveredIdAllowOverlap, ImGuiContext::HoveredWindow, ImGuiHoveredFlags_Default, ImGuiItemFlags_Disabled, IsMouseHoveringRect(), IsWindowContentHoverable(), ImGuiDrawContext::ItemFlags, ImRect::Max, ImRect::Min, ImGuiContext::NavDisableMouseHover, and SetHoveredID().
Referenced by BeginMenu(), ButtonBehavior(), DragFloat(), InputTextEx(), PlotEx(), SliderFloat(), and VSliderFloat().
IsClippedEx()
bool ImGui::IsClippedEx (const ImRect & bb, ImGuiID id, bool clip_even_when_logged)
References ImGuiContext::ActiveId, ImGuiWindow::ClipRect, ImGuiContext::CurrentWindow, GImGui, ImGuiContext::LogEnabled, and ImRect::Overlaps().
Referenced by EndColumns(), ItemAdd(), and TextUnformatted().
FocusableItemRegister()
bool ImGui::FocusableItemRegister (ImGuiWindow * window, ImGuiID id, bool tab_stop = true)
References ImGuiContext::ActiveId, ImGuiWindow::DC, ImGuiWindow::FocusIdxAllCounter, ImGuiWindow::FocusIdxAllRequestCurrent, ImGuiWindow::FocusIdxAllRequestNext, ImGuiWindow::FocusIdxTabCounter, ImGuiWindow::FocusIdxTabRequestCurrent, ImGuiWindow::FocusIdxTabRequestNext, GImGui, ImGuiItemFlags_AllowKeyboardFocus, ImGuiItemFlags_Disabled, ImGuiKey_Tab, ImGuiContext::IO, IsKeyPressedMap(), ImGuiDrawContext::ItemFlags, ImGuiIO::KeyCtrl, ImGuiIO::KeyShift, and ImGuiContext::NavJustTabbedId.
Referenced by DragFloat(), InputTextEx(), and SliderFloat().
FocusableItemUnregister()
void ImGui::FocusableItemUnregister (ImGuiWindow * window)
References ImGuiWindow::FocusIdxAllCounter, and ImGuiWindow::FocusIdxTabCounter.
Referenced by InputScalarAsWidgetReplacement().
CalcItemSize()
ImVec2 ImGui::CalcItemSize (ImVec2 size, float default_x, float default_y)
References ImGuiContext::CurrentWindow, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, GetContentRegionMax(), GImGui, ImMax(), ImGuiWindow::Pos, ImVec2::x, and ImVec2::y.
Referenced by ButtonEx(), InputTextEx(), InvisibleButton(), ListBoxHeader(), and ProgressBar().
CalcWrapWidthForPos()
float ImGui::CalcWrapWidthForPos (const ImVec2 & pos, float wrap_pos_x)
References GetContentRegionMax(), GetCurrentWindowRead(), ImMax(), ImGuiWindow::Pos, ImGuiWindow::Scroll, and ImVec2::x.
Referenced by TextUnformatted().
PushMultiItemsWidths()
void ImGui::PushMultiItemsWidths (int components, float width_full = 0.0f)
References ImVector< T >::back(), CalcItemWidth(), ImGuiWindow::DC, GetCurrentWindow(), GImGui, ImMax(), ImGuiStyle::ItemInnerSpacing, ImGuiDrawContext::ItemWidth, ImGuiDrawContext::ItemWidthStack, ImVector< T >::push_back(), ImGuiContext::Style, and ImVec2::x.
Referenced by DragFloatN(), DragFloatRange2(), DragIntN(), DragIntRange2(), InputFloatN(), InputIntN(), SliderFloatN(), and SliderIntN().
PushItemFlag()
void ImGui::PushItemFlag (ImGuiItemFlags option, bool enabled)
References ImGuiWindow::DC, GetCurrentWindow(), ImGuiDrawContext::ItemFlags, ImGuiDrawContext::ItemFlagsStack, and ImVector< T >::push_back().
Referenced by ColorPicker4(), PushAllowKeyboardFocus(), and PushButtonRepeat().
PopItemFlag()
void ImGui::PopItemFlag ()
References ImVector< T >::back(), ImGuiWindow::DC, ImVector< T >::empty(), GetCurrentWindow(), ImGuiItemFlags_Default_, ImGuiDrawContext::ItemFlags, ImGuiDrawContext::ItemFlagsStack, and ImVector< T >::pop_back().
Referenced by ColorPicker4(), PopAllowKeyboardFocus(), and PopButtonRepeat().
SetCurrentFont()
void ImGui::SetCurrentFont (ImFont * font)
References ImGuiWindow::CalcFontSize(), ImFont::ContainerAtlas, ImGuiContext::CurrentWindow, ImGuiContext::DrawListSharedData, ImDrawListSharedData::Font, ImGuiContext::Font, ImGuiContext::FontBaseSize, ImGuiIO::FontGlobalScale, ImDrawListSharedData::FontSize, ImGuiContext::FontSize, ImFont::FontSize, GImGui, IM_ASSERT, ImGuiContext::IO, ImFont::IsLoaded(), ImFont::Scale, ImDrawListSharedData::TexUvWhitePixel, and ImFontAtlas::TexUvWhitePixel.
Referenced by NewFrame(), PopFont(), and PushFont().
OpenPopupEx()
void ImGui::OpenPopupEx (ImGuiID id)
References ImVector< T >::back(), ImGuiContext::CurrentPopupStack, ImGuiContext::CurrentWindow, ImGuiContext::FrameCount, GImGui, ImGuiWindow::IDStack, ImGuiContext::IO, ImGuiIO::MousePos, NavCalcPreferredMousePos(), ImGuiContext::NavDisableHighlight, ImGuiContext::NavDisableMouseHover, NULL, ImGuiPopupRef::OpenFrameCount, ImGuiPopupRef::OpenMousePos, ImGuiPopupRef::OpenParentId, ImGuiPopupRef::OpenPopupPos, ImGuiContext::OpenPopupStack, ImGuiPopupRef::ParentWindow, ImGuiPopupRef::PopupId, ImVector< T >::push_back(), ImVector< T >::resize(), ImVector< T >::Size, and ImGuiPopupRef::Window.
Referenced by BeginCombo(), BeginPopupContextItem(), BeginPopupContextVoid(), BeginPopupContextWindow(), OpenPopup(), and OpenPopupOnItemClick().
ClosePopup()
void ImGui::ClosePopup (ImGuiID id)
References ClosePopupToLevel(), GImGui, IsPopupOpen(), ImGuiContext::OpenPopupStack, and ImVector< T >::Size.
Referenced by BeginPopupModal().
ClosePopupsOverWindow()
void ImGui::ClosePopupsOverWindow (ImGuiWindow * ref_window)
References ClosePopupToLevel(), ImVector< T >::empty(), ImGuiWindow::Flags, GImGui, IM_ASSERT, ImGuiWindowFlags_ChildWindow, ImGuiWindowFlags_Popup, ImGuiContext::OpenPopupStack, ImGuiWindow::RootWindow, ImVector< T >::Size, and ImGuiPopupRef::Window.
Referenced by EndFrame(), NavUpdateWindowing(), and NewFrame().
IsPopupOpen() [1/2]
bool ImGui::IsPopupOpen (ImGuiID id)
References ImGuiContext::CurrentPopupStack, GImGui, ImGuiContext::OpenPopupStack, and ImVector< T >::Size.
Referenced by BeginCombo(), BeginMenu(), BeginPopupEx(), BeginPopupModal(), and ClosePopup().
BeginPopupEx()
bool ImGui::BeginPopupEx (ImGuiID id, ImGuiWindowFlags extra_flags)
References Begin(), ImGuiNextWindowData::Clear(), ImGuiContext::CurrentPopupStack, EndPopup(), GImGui, IM_ARRAYSIZE, ImFormatString(), ImGuiWindowFlags_ChildMenu, ImGuiWindowFlags_Popup, IsPopupOpen(), setup::name, ImGuiContext::NextWindowData, NULL, and ImVector< T >::Size.
Referenced by BeginMenu(), BeginPopup(), BeginPopupContextItem(), BeginPopupContextVoid(), and BeginPopupContextWindow().
BeginTooltipEx()
void ImGui::BeginTooltipEx (ImGuiWindowFlags extra_flags, bool override_previous_tooltip = true)
References Begin(), FindWindowByName(), GImGui, IM_ARRAYSIZE, ImFormatString(), ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoInputs, ImGuiWindowFlags_NoMove, ImGuiWindowFlags_NoNav, ImGuiWindowFlags_NoResize, ImGuiWindowFlags_NoSavedSettings, ImGuiWindowFlags_NoTitleBar, ImGuiWindowFlags_Tooltip, NULL, and ImGuiContext::TooltipOverrideCount.
Referenced by BeginTooltip(), ColorTooltip(), and SetTooltipV().
NavInitWindow()
void ImGui::NavInitWindow (ImGuiWindow * window, bool force_reinit)
References ImGuiWindow::Flags, GImGui, IM_ASSERT, ImGuiWindowFlags_ChildWindow, ImGuiWindowFlags_NoNavInputs, ImGuiWindowFlags_Popup, ImGuiContext::NavId, ImGuiContext::NavInitRequest, ImGuiContext::NavInitRequestFromMove, ImGuiContext::NavInitResultId, ImGuiContext::NavInitResultRectRel, ImGuiWindow::NavLastIds, ImGuiContext::NavLayer, NavUpdateAnyRequestFlag(), ImGuiContext::NavWindow, and SetNavID().
Referenced by Begin(), BeginChildEx(), NavRestoreLayer(), and NavUpdateWindowing().
NavMoveRequestCancel()
void ImGui::NavMoveRequestCancel ()
References GImGui, ImGuiContext::NavMoveRequest, and NavUpdateAnyRequestFlag().
Referenced by BeginMenu(), EndMenu(), EndMenuBar(), NavProcessMoveRequestWrapAround(), TreeNodeBehavior(), and TreePop().
ActivateItem()
void ImGui::ActivateItem (ImGuiID id)
References GImGui, and ImGuiContext::NavNextActivateId.
GetNavInputAmount()
float ImGui::GetNavInputAmount (ImGuiNavInput n, ImGuiInputReadMode mode)
References CalcTypematicPressedRepeatAmount(), ImGuiIO::DeltaTime, GImGui, ImGuiInputReadMode_Down, ImGuiInputReadMode_Pressed, ImGuiInputReadMode_Released, ImGuiInputReadMode_Repeat, ImGuiInputReadMode_RepeatFast, ImGuiInputReadMode_RepeatSlow, ImGuiContext::IO, ImGuiIO::KeyRepeatDelay, ImGuiIO::KeyRepeatRate, mode(), ImGuiIO::NavInputs, ImGuiIO::NavInputsDownDuration, and ImGuiIO::NavInputsDownDurationPrev.
Referenced by GetNavInputAmount2d(), IsNavInputPressed(), and IsNavInputPressedAnyOfTwo().
GetNavInputAmount2d()
ImVec2 ImGui::GetNavInputAmount2d (ImGuiNavDirSourceFlags dir_sources, ImGuiInputReadMode mode, float slow_factor = 0.0f, float fast_factor = 0.0f)
References GetNavInputAmount(), ImGuiNavDirSourceFlags_Keyboard, ImGuiNavDirSourceFlags_PadDPad, ImGuiNavDirSourceFlags_PadLStick, ImGuiNavInput_DpadDown, ImGuiNavInput_DpadLeft, ImGuiNavInput_DpadRight, ImGuiNavInput_DpadUp, ImGuiNavInput_KeyDown_, ImGuiNavInput_KeyLeft_, ImGuiNavInput_KeyRight_, ImGuiNavInput_KeyUp_, ImGuiNavInput_LStickDown, ImGuiNavInput_LStickLeft, ImGuiNavInput_LStickRight, ImGuiNavInput_LStickUp, ImGuiNavInput_TweakFast, ImGuiNavInput_TweakSlow, IsNavInputDown(), and mode().
Referenced by DragBehavior(), NavUpdate(), NavUpdateWindowing(), SliderBehavior(), and UpdateManualResize().
CalcTypematicPressedRepeatAmount()
int ImGui::CalcTypematicPressedRepeatAmount (float t, float t_prev, float repeat_delay, float repeat_rate)
Referenced by ButtonBehavior(), GetKeyPressedAmount(), and GetNavInputAmount().
Scrollbar()
void ImGui::Scrollbar (ImGuiLayoutType direction)
References ImGuiContext::ActiveId, ImDrawList::AddRectFilled(), ButtonBehavior(), ImGuiContext::CurrentWindow, ImGuiWindow::DrawList, ImRect::Expand(), ImGuiWindow::Flags, GetColorU32(), ImRect::GetHeight(), ImGuiWindow::GetID(), ImRect::GetWidth(), GImGui, ImGuiStyle::GrabMinSize, IM_ASSERT, ImClamp(), ImDrawCornerFlags_BotLeft, ImDrawCornerFlags_BotRight, ImDrawCornerFlags_TopRight, ImGuiButtonFlags_NoNavFocus, ImGuiCol_ScrollbarBg, ImGuiCol_ScrollbarGrab, ImGuiCol_ScrollbarGrabActive, ImGuiCol_ScrollbarGrabHovered, ImGuiLayoutType_Horizontal, ImGuiWindowFlags_MenuBar, ImGuiWindowFlags_NoTitleBar, ImLerp(), ImMax(), ImMin(), ImSaturate(), ImGuiContext::IO, ImRect::Max, ImGuiWindow::MenuBarHeight(), ImRect::Min, ImGuiIO::MousePos, ImGuiWindow::Pos, ImGuiWindow::Rect(), ImGuiWindow::Scroll, ImGuiContext::ScrollbarClickDeltaToGrabCenter, ImGuiStyle::ScrollbarRounding, ImGuiStyle::ScrollbarSize, ImGuiWindow::ScrollbarX, ImGuiWindow::ScrollbarY, SetHoveredID(), ImGuiWindow::SizeContents, ImGuiWindow::SizeFull, ImGuiContext::Style, ImGuiWindow::TitleBarHeight(), ImGuiWindow::WindowBorderSize, ImGuiWindow::WindowRounding, ImVec2::x, and ImVec2::y.
Referenced by Begin().
VerticalSeparator()
void ImGui::VerticalSeparator ()
References ImDrawList::AddLine(), ImGuiDrawContext::CurrentLineHeight, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, ImGuiWindow::DrawList, GetColorU32(), GetCurrentWindow(), ImRect::GetWidth(), GImGui, ImGuiCol_Separator, ItemAdd(), ItemSize(), ImGuiContext::LogEnabled, LogText(), ImRect::Max, ImRect::Min, ImGuiWindow::SkipItems, ImVec2::x, and ImVec2::y.
Referenced by Separator().
SplitterBehavior()
bool ImGui::SplitterBehavior (ImGuiID id, const ImRect & bb, ImGuiAxis axis, float * size1, float * size2, float min_size1, float min_size2, float hover_extend = 0.0f)
References ImGuiContext::ActiveId, ImGuiContext::ActiveIdClickOffset, ImDrawList::AddRectFilled(), ButtonBehavior(), ImGuiContext::CurrentWindow, ImGuiWindow::DC, ImGuiWindow::DrawList, ImRect::Expand(), ImGuiStyle::FrameRounding, GetColorU32(), GImGui, ImGuiContext::HoveredId, ImGuiContext::HoveredIdPreviousFrame, ImGuiAxis_X, ImGuiAxis_Y, ImGuiButtonFlags_AllowItemOverlap, ImGuiButtonFlags_FlattenChildren, ImGuiCol_Separator, ImGuiCol_SeparatorActive, ImGuiCol_SeparatorHovered, ImGuiItemFlags_NoNav, ImGuiItemFlags_NoNavDefaultFocus, ImGuiMouseCursor_ResizeEW, ImGuiMouseCursor_ResizeNS, ImGuiContext::IO, ItemAdd(), ImGuiDrawContext::ItemFlags, ImRect::Max, ImRect::Min, ImGuiIO::MousePos, SetItemAllowOverlap(), SetMouseCursor(), ImGuiContext::Style, ImRect::Translate(), ImVec2::x, and ImVec2::y.
BeginDragDropTargetCustom()
bool ImGui::BeginDragDropTargetCustom (const ImRect & bb, ImGuiID id)
References ImGuiContext::CurrentWindow, ImGuiContext::DragDropActive, ImGuiContext::DragDropPayload, ImGuiContext::DragDropTargetId, ImGuiContext::DragDropTargetRect, GImGui, ImGuiContext::HoveredWindow, IM_ASSERT, IsMouseHoveringRect(), ImRect::Max, ImRect::Min, NULL, ImGuiWindow::RootWindow, and ImGuiPayload::SourceId.
ClearDragDrop()
void ImGui::ClearDragDrop ()
References ImGuiPayload::Clear(), ImGuiContext::DragDropAcceptFrameCount, ImGuiContext::DragDropAcceptIdCurr, ImGuiContext::DragDropAcceptIdCurrRectSurface, ImGuiContext::DragDropAcceptIdPrev, ImGuiContext::DragDropActive, ImGuiContext::DragDropPayload, FLT_MAX, and GImGui.
Referenced by BeginDragDropSource(), EndDragDropSource(), and NewFrame().
IsDragDropPayloadBeingAccepted()
bool ImGui::IsDragDropPayloadBeingAccepted ()
References ImGuiContext::DragDropAcceptIdPrev, ImGuiContext::DragDropActive, and GImGui.
BeginColumns()
void ImGui::BeginColumns (const char * str_id, int count, ImGuiColumnsFlags flags = 0)
References ImGuiColumnsSet::CellMaxY, ImGuiColumnsSet::CellMinY, ImDrawList::ChannelsSplit(), ImGuiColumnData::ClipRect, ImGuiWindow::ClipRect, ImRect::ClipWith(), ImGuiColumnsSet::Columns, ImGuiStyle::ColumnsMinSpacing, ImGuiDrawContext::ColumnsOffsetX, ImGuiDrawContext::ColumnsSet, ImGuiColumnsSet::Count, ImGuiColumnsSet::Current, ImGuiDrawContext::CursorMaxPos, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, ImGuiWindow::DrawList, FindOrAddColumnsSet(), ImGuiColumnsSet::Flags, FLT_MAX, GetColumnOffset(), GetColumnWidth(), GetCurrentWindow(), ImGuiWindow::GetID(), GImGui, ImGuiColumnsSet::ID, IM_ASSERT, ImFloor(), ImGuiColumnsFlags_NoForceWithinWindow, ImMin(), ImGuiDrawContext::IndentX, ImGuiColumnsSet::IsFirstFrame, ImGuiStyle::ItemSpacing, ImGuiColumnsSet::MaxX, ImGuiColumnsSet::MinX, NULL, ImGuiColumnData::OffsetNorm, PixelsToOffsetNorm(), PopID(), ImGuiWindow::Pos, ImVector< T >::push_back(), PushColumnClipRect(), PushID(), PushItemWidth(), ImVector< T >::reserve(), ImVector< T >::resize(), ImGuiWindow::Scroll, ImGuiWindow::ScrollbarSizes, ImGuiWindow::Size, ImVector< T >::Size, ImGuiWindow::SizeContentsExplicit, ImGuiColumnsSet::StartMaxPosX, ImGuiColumnsSet::StartPosY, ImGuiContext::Style, ImVec2::x, and ImVec2::y.
Referenced by Columns().
EndColumns()
void ImGui::EndColumns ()
References ImDrawList::AddLine(), ButtonBehavior(), ImGuiColumnsSet::CellMaxY, ImDrawList::ChannelsMerge(), ImGuiWindow::ClipRect, ImGuiColumnsSet::Columns, ImGuiDrawContext::ColumnsOffsetX, ImGuiDrawContext::ColumnsSet, ImGuiColumnsSet::Count, ImGuiDrawContext::CursorMaxPos, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, ImGuiWindow::DrawList, ImGuiColumnsSet::Flags, GetColorU32(), GetColumnOffset(), GetColumnsRectHalfWidth(), GetCurrentWindow(), GetDraggedColumnOffset(), GImGui, ImGuiColumnsSet::ID, IM_ASSERT, ImGuiCol_Separator, ImGuiCol_SeparatorActive, ImGuiCol_SeparatorHovered, ImGuiColumnsFlags_GrowParentContentsSize, ImGuiColumnsFlags_NoBorder, ImGuiColumnsFlags_NoResize, ImGuiMouseCursor_ResizeEW, ImMax(), ImMin(), ImGuiDrawContext::IndentX, ImGuiColumnsSet::IsBeingResized, IsClippedEx(), KeepAliveID(), ImRect::Max, ImGuiColumnsSet::MaxX, ImRect::Min, ImGuiContext::MouseCursor, NULL, PopClipRect(), PopItemWidth(), ImGuiWindow::Pos, SetColumnOffset(), ImGuiWindow::SkipItems, ImGuiColumnsSet::StartMaxPosX, ImGuiColumnsSet::StartPosY, ImVec2::x, and ImVec2::y.
Referenced by Columns(), and End().
PushColumnClipRect()
void ImGui::PushColumnClipRect (int column_index = -1)
References ImGuiColumnsSet::Columns, ImGuiDrawContext::ColumnsSet, ImGuiColumnsSet::Current, ImGuiWindow::DC, GetCurrentWindowRead(), and PushClipRect().
Referenced by BeginColumns(), NextColumn(), Selectable(), and Separator().
RenderText()
void ImGui::RenderText (ImVec2 pos, const char * text, const char * text_end = NULL, bool hide_text_after_hash = true)
References ImDrawList::AddText(), ImGuiContext::CurrentWindow, ImGuiWindow::DrawList, FindRenderedTextEnd(), ImGuiContext::Font, ImGuiContext::FontSize, GetColorU32(), GImGui, ImGuiCol_Text, ImGuiContext::LogEnabled, and LogRenderedText().
Referenced by BeginCombo(), BulletTextV(), Checkbox(), DragFloat(), InputScalarEx(), InputTextEx(), LabelTextV(), ListBoxHeader(), MenuItem(), PlotEx(), RadioButton(), SliderFloat(), TextUnformatted(), TreeNodeBehavior(), and VSliderFloat().
RenderTextWrapped()
void ImGui::RenderTextWrapped (ImVec2 pos, const char * text, const char * text_end, float wrap_width)
References ImDrawList::AddText(), ImGuiContext::CurrentWindow, ImGuiWindow::DrawList, ImGuiContext::Font, ImGuiContext::FontSize, GetColorU32(), GImGui, ImGuiCol_Text, ImGuiContext::LogEnabled, and LogRenderedText().
Referenced by TextUnformatted().
RenderTextClipped()
void ImGui::RenderTextClipped (const ImVec2 & pos_min, const ImVec2 & pos_max, const char * text, const char * text_end, const ImVec2 * text_size_if_known, const ImVec2 & align = ImVec2(0,0), const ImRect * clip_rect = NULL)
References ImDrawList::AddText(), CalcTextSize(), ImGuiContext::CurrentWindow, ImGuiWindow::DrawList, FindRenderedTextEnd(), ImGuiContext::Font, ImGuiContext::FontSize, GetColorU32(), GImGui, ImGuiCol_Text, ImMax(), ImGuiContext::LogEnabled, LogRenderedText(), ImRect::Max, ImRect::Min, NULL, ImVec2::x, and ImVec2::y.
Referenced by Begin(), BeginCombo(), ButtonEx(), DragFloat(), LabelTextV(), PlotEx(), ProgressBar(), Selectable(), SliderFloat(), TreeNodeBehavior(), and VSliderFloat().
RenderFrame()
void ImGui::RenderFrame (ImVec2 p_min, ImVec2 p_max, ImU32 fill_col, bool border = true, float rounding = 0.0f)
References ImDrawList::AddRect(), ImDrawList::AddRectFilled(), ImGuiContext::CurrentWindow, ImGuiWindow::DrawList, ImGuiStyle::FrameBorderSize, GetColorU32(), GImGui, ImDrawCornerFlags_All, ImGuiCol_Border, ImGuiCol_BorderShadow, and ImGuiContext::Style.
Referenced by ArrowButton(), Begin(), BeginCombo(), ButtonEx(), Checkbox(), DragBehavior(), ImageButton(), InputTextEx(), PlotEx(), ProgressBar(), Selectable(), SliderBehavior(), and TreeNodeBehavior().
RenderFrameBorder()
void ImGui::RenderFrameBorder (ImVec2 p_min, ImVec2 p_max, float rounding = 0.0f)
References ImDrawList::AddRect(), ImGuiContext::CurrentWindow, ImGuiWindow::DrawList, ImGuiStyle::FrameBorderSize, GetColorU32(), GImGui, ImDrawCornerFlags_All, ImGuiCol_Border, ImGuiCol_BorderShadow, and ImGuiContext::Style.
Referenced by ColorButton(), and ColorPicker4().
RenderColorRectWithAlphaCheckerboard()
void ImGui::RenderColorRectWithAlphaCheckerboard (ImVec2 p_min, ImVec2 p_max, ImU32 fill_col, float grid_step, ImVec2 grid_off, float rounding = 0.0f, int rounding_corners_flags = ~0)
References ImDrawList::AddRectFilled(), ImGuiWindow::DrawList, GetColorU32(), GetCurrentWindow(), IM_COL32, IM_COL32_A_MASK, IM_COL32_A_SHIFT, ImAlphaBlendColor(), ImClamp(), ImDrawCornerFlags_BotLeft, ImDrawCornerFlags_BotRight, ImDrawCornerFlags_TopLeft, ImDrawCornerFlags_TopRight, ImMin(), ImVec2::x, and ImVec2::y.
Referenced by ColorButton(), and ColorPicker4().
RenderTriangle()
void ImGui::RenderTriangle (ImVec2 pos, ImGuiDir dir, float scale = 1.0f)
References a, ImDrawList::AddTriangleFilled(), ImGuiContext::CurrentWindow, ImGuiWindow::DrawList, ImGuiContext::FontSize, GetColorU32(), GImGui, IM_ASSERT, ImGuiCol_Text, ImGuiDir_Count_, ImGuiDir_Down, ImGuiDir_Left, ImGuiDir_None, ImGuiDir_Right, ImGuiDir_Up, scale(), ImVec2::x, and ImVec2::y.
Referenced by ArrowButton(), Begin(), BeginCombo(), BeginMenu(), and TreeNodeBehavior().
RenderBullet()
void ImGui::RenderBullet (ImVec2 pos)
References ImDrawList::AddCircleFilled(), ImGuiContext::CurrentWindow, ImGuiWindow::DrawList, ImGuiContext::FontSize, GetColorU32(), GImGui, and ImGuiCol_Text.
Referenced by Bullet(), BulletTextV(), and TreeNodeBehavior().
RenderCheckMark()
void ImGui::RenderCheckMark (ImVec2 pos, ImU32 col, float sz)
References ImGuiContext::CurrentWindow, ImGuiWindow::DrawList, GImGui, ImMax(), ImDrawList::PathLineTo(), ImDrawList::PathStroke(), ImVec2::x, and ImVec2::y.
Referenced by Checkbox(), and MenuItem().
RenderNavHighlight()
void ImGui::RenderNavHighlight (const ImRect & bb, ImGuiID id, ImGuiNavHighlightFlags flags = ImGuiNavHighlightFlags_TypeDefault)
References ImDrawList::AddRect(), ImGuiWindow::ClipRect, ImRect::ClipWith(), ImRect::Contains(), ImGuiWindow::DC, ImGuiWindow::DrawList, ImGuiStyle::FrameRounding, GetColorU32(), GetCurrentWindow(), GImGui, ImDrawCornerFlags_All, ImGuiCol_NavHighlight, ImGuiNavHighlightFlags_AlwaysDraw, ImGuiNavHighlightFlags_NoRounding, ImGuiNavHighlightFlags_TypeDefault, ImGuiNavHighlightFlags_TypeThin, ImGuiContext::NavDisableHighlight, ImGuiDrawContext::NavHideHighlightOneFrame, ImGuiContext::NavId, ImDrawList::PopClipRect(), ImDrawList::PushClipRect(), and ImGuiContext::Style.
Referenced by ArrowButton(), Begin(), BeginCombo(), ButtonEx(), Checkbox(), ColorButton(), DragBehavior(), EndChild(), ImageButton(), InputTextEx(), RadioButton(), Selectable(), SliderBehavior(), and TreeNodeBehavior().
RenderRectFilledRangeH()
void ImGui::RenderRectFilledRangeH (ImDrawList * draw_list, const ImRect & rect, ImU32 col, float x_start_norm, float x_end_norm, float rounding)
References ImDrawList::AddRectFilled(), IM_PI, ImAcos01(), ImClamp(), ImLerp(), ImMax(), ImMin(), ImSwap(), ImRect::Max, ImRect::Min, ImDrawList::PathArcTo(), ImDrawList::PathArcToFast(), ImDrawList::PathFillConvex(), ImDrawList::PathLineTo(), ImVec2::x, and ImVec2::y.
Referenced by ProgressBar().
FindRenderedTextEnd()
const char * ImGui::FindRenderedTextEnd (const char * text, const char * text_end = NULL)
Referenced by CalcTextSize(), ColorEdit4(), ColorPicker4(), ColorTooltip(), DragFloatN(), DragFloatRange2(), DragIntN(), DragIntRange2(), InputFloatN(), InputIntN(), LogRenderedText(), RenderText(), RenderTextClipped(), SliderFloatN(), SliderIntN(), and TreeNodeBehavior().
ButtonBehavior()
bool ImGui::ButtonBehavior (const ImRect & bb, ImGuiID id, bool * out_hovered, bool * out_held, ImGuiButtonFlags flags = 0)
References ImGuiContext::ActiveId, ImGuiContext::ActiveIdAllowNavDirFlags, ImGuiContext::ActiveIdClickOffset, ImGuiContext::ActiveIdIsJustActivated, ImGuiContext::ActiveIdSource, CalcTypematicPressedRepeatAmount(), ClearActiveID(), ImGuiIO::DeltaTime, ImGuiContext::DragDropActive, ImGuiContext::DragDropSourceFlags, FocusWindow(), GetCurrentWindow(), GImGui, ImGuiContext::HoveredIdPreviousFrame, ImGuiContext::HoveredIdTimer, ImGuiContext::HoveredRootWindow, ImGuiContext::HoveredWindow, ImGuiButtonFlags_AllowItemOverlap, ImGuiButtonFlags_Disabled, ImGuiButtonFlags_FlattenChildren, ImGuiButtonFlags_NoHoldingActiveID, ImGuiButtonFlags_NoKeyModifiers, ImGuiButtonFlags_NoNavFocus, ImGuiButtonFlags_PressedOnClick, ImGuiButtonFlags_PressedOnClickRelease, ImGuiButtonFlags_PressedOnDoubleClick, ImGuiButtonFlags_PressedOnDragDropHold, ImGuiButtonFlags_PressedOnRelease, ImGuiButtonFlags_Repeat, ImGuiDir_Down, ImGuiDir_Left, ImGuiDir_Right, ImGuiDir_Up, ImGuiDragDropFlags_SourceNoHoldToOpenOthers, ImGuiHoveredFlags_AllowWhenBlockedByActiveItem, ImGuiInputReadMode_Pressed, ImGuiInputReadMode_Repeat, ImGuiInputSource_Mouse, ImGuiInputSource_Nav, ImGuiNavInput_Activate, ImGuiContext::IO, IsItemHovered(), IsMouseClicked(), IsNavInputPressed(), ItemHoverable(), ImGuiIO::KeyAlt, ImGuiIO::KeyCtrl, ImGuiIO::KeyRepeatDelay, ImGuiIO::KeyShift, ImRect::Min, ImGuiIO::MouseClicked, ImGuiIO::MouseDoubleClicked, ImGuiIO::MouseDown, ImGuiIO::MouseDownDuration, ImGuiIO::MouseDownDurationPrev, ImGuiIO::MousePos, ImGuiIO::MouseReleased, ImGuiWindow::MoveId, ImGuiContext::NavActivateDownId, ImGuiContext::NavActivateId, ImGuiContext::NavDisableHighlight, ImGuiContext::NavDisableMouseHover, ImGuiContext::NavId, SetActiveID(), SetFocusID(), and SetHoveredID().
Referenced by ArrowButton(), Begin(), BeginCombo(), ButtonEx(), Checkbox(), CloseButton(), ColorButton(), EndColumns(), ImageButton(), InvisibleButton(), RadioButton(), Scrollbar(), Selectable(), SplitterBehavior(), TreeNodeBehavior(), and UpdateManualResize().
ButtonEx()
bool ImGui::ButtonEx (const char * label, const ImVec2 & size_arg = ImVec2(0,0), ImGuiButtonFlags flags = 0)
References ButtonBehavior(), ImGuiStyle::ButtonTextAlign, CalcItemSize(), CalcTextSize(), ImGuiDrawContext::CurrentLineTextBaseOffset, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, ImGuiStyle::FramePadding, ImGuiStyle::FrameRounding, GetColorU32(), GetCurrentWindow(), ImGuiWindow::GetID(), GImGui, ImGuiButtonFlags_AlignTextBaseLine, ImGuiButtonFlags_Repeat, ImGuiCol_Button, ImGuiCol_ButtonActive, ImGuiCol_ButtonHovered, ImGuiItemFlags_ButtonRepeat, ItemAdd(), ImGuiDrawContext::ItemFlags, ItemSize(), ImRect::Max, ImRect::Min, NULL, RenderFrame(), RenderNavHighlight(), RenderTextClipped(), ImGuiWindow::SkipItems, ImGuiContext::Style, ImVec2::x, and ImVec2::y.
Referenced by Button(), InputScalarEx(), and SmallButton().
CloseButton()
bool ImGui::CloseButton (ImGuiID id, const ImVec2 & pos, float radius)
References ImDrawList::AddCircleFilled(), ImDrawList::AddLine(), ButtonBehavior(), ImGuiContext::CurrentWindow, ImGuiWindow::DrawList, ImRect::GetCenter(), GetColorU32(), GImGui, ImGuiCol_CloseButton, ImGuiCol_CloseButtonActive, ImGuiCol_CloseButtonHovered, ImGuiCol_Text, ImMax(), and ItemAdd().
Referenced by Begin(), CollapsingHeader(), and ImGuiWindow::ImGuiWindow().
ArrowButton()
bool ImGui::ArrowButton (ImGuiID id, ImGuiDir dir, ImVec2 padding, ImGuiButtonFlags flags = 0)
References ButtonBehavior(), ImGuiContext::CurrentWindow, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, ImGuiContext::FontSize, ImGuiStyle::FramePadding, ImGuiStyle::FrameRounding, GetColorU32(), GImGui, ImGuiCol_Button, ImGuiCol_ButtonActive, ImGuiCol_ButtonHovered, ItemAdd(), ItemSize(), ImRect::Max, ImRect::Min, RenderFrame(), RenderNavHighlight(), RenderTriangle(), ImGuiWindow::SkipItems, ImGuiContext::Style, ImVec2::x, and ImVec2::y.
SliderBehavior()
bool ImGui::SliderBehavior (const ImRect & frame_bb, ImGuiID id, float * v, float v_min, float v_max, float power, int decimal_precision, ImGuiSliderFlags flags = 0)
References a, ImGuiContext::ActiveId, ImGuiContext::ActiveIdIsJustActivated, ImGuiContext::ActiveIdSource, ImDrawList::AddRectFilled(), ClearActiveID(), ImGuiWindow::DrawList, ImGuiStyle::FrameRounding, GetColorU32(), GetCurrentWindow(), ImRect::GetHeight(), GetNavInputAmount2d(), ImRect::GetWidth(), GImGui, ImGuiStyle::GrabMinSize, ImGuiStyle::GrabRounding, ImClamp(), ImGuiCol_FrameBg, ImGuiCol_FrameBgActive, ImGuiCol_SliderGrab, ImGuiCol_SliderGrabActive, ImGuiInputReadMode_RepeatFast, ImGuiInputSource_Mouse, ImGuiInputSource_Nav, ImGuiNavDirSourceFlags_Keyboard, ImGuiNavDirSourceFlags_PadDPad, ImGuiNavInput_TweakFast, ImGuiNavInput_TweakSlow, ImGuiSliderFlags_Vertical, ImLerp(), ImMax(), ImMin(), ImSaturate(), ImGuiContext::IO, IsNavInputDown(), ImRect::Max, ImRect::Min, ImGuiIO::MouseDown, ImGuiIO::MousePos, ImGuiContext::NavActivatePressedId, RenderFrame(), RenderNavHighlight(), RoundScalar(), SliderBehaviorCalcRatioFromValue(), ImGuiContext::Style, ImVec2::x, and ImVec2::y.
Referenced by SliderFloat(), and VSliderFloat().
SliderFloatN()
bool ImGui::SliderFloatN (const char * label, float * v, int components, float v_min, float v_max, const char * display_format, float power)
References BeginGroup(), EndGroup(), FindRenderedTextEnd(), GetCurrentWindow(), GImGui, ImGuiStyle::ItemInnerSpacing, PopID(), PopItemWidth(), PushID(), PushMultiItemsWidths(), SameLine(), ImGuiWindow::SkipItems, SliderFloat(), ImGuiContext::Style, TextUnformatted(), and ImVec2::x.
Referenced by SliderFloat2(), SliderFloat3(), and SliderFloat4().
SliderIntN()
bool ImGui::SliderIntN (const char * label, int * v, int components, int v_min, int v_max, const char * display_format)
References BeginGroup(), EndGroup(), FindRenderedTextEnd(), GetCurrentWindow(), GImGui, ImGuiStyle::ItemInnerSpacing, PopID(), PopItemWidth(), PushID(), PushMultiItemsWidths(), SameLine(), ImGuiWindow::SkipItems, SliderInt(), ImGuiContext::Style, TextUnformatted(), and ImVec2::x.
Referenced by SliderInt2(), SliderInt3(), and SliderInt4().
DragBehavior()
bool ImGui::DragBehavior (const ImRect & frame_bb, ImGuiID id, float * v, float v_speed, float v_min, float v_max, int decimal_precision, float power)
References ImGuiContext::ActiveId, ImGuiContext::ActiveIdIsJustActivated, ImGuiContext::ActiveIdSource, ClearActiveID(), ImGuiContext::DragCurrentValue, ImGuiContext::DragLastMouseDelta, ImGuiContext::DragSpeedDefaultRatio, ImGuiContext::DragSpeedScaleFast, ImGuiContext::DragSpeedScaleSlow, FLT_MAX, ImGuiStyle::FrameRounding, GetColorU32(), GetMinimumStepAtDecimalPrecision(), GetMouseDragDelta(), GetNavInputAmount2d(), GImGui, ImGuiContext::HoveredId, ImClamp(), ImGuiCol_FrameBg, ImGuiCol_FrameBgActive, ImGuiCol_FrameBgHovered, ImGuiInputReadMode_RepeatFast, ImGuiInputSource_Mouse, ImGuiInputSource_Nav, ImGuiNavDirSourceFlags_Keyboard, ImGuiNavDirSourceFlags_PadDPad, ImMax(), ImGuiContext::IO, IsMousePosValid(), ImGuiIO::KeyAlt, ImGuiIO::KeyShift, ImRect::Max, ImRect::Min, ImGuiIO::MouseDown, ImGuiContext::NavActivatePressedId, RenderFrame(), RenderNavHighlight(), RoundScalar(), ImGuiContext::Style, and ImVec2::x.
Referenced by DragFloat().
DragFloatN()
bool ImGui::DragFloatN (const char * label, float * v, int components, float v_speed, float v_min, float v_max, const char * display_format, float power)
References BeginGroup(), DragFloat(), EndGroup(), FindRenderedTextEnd(), GetCurrentWindow(), GImGui, ImGuiStyle::ItemInnerSpacing, PopID(), PopItemWidth(), PushID(), PushMultiItemsWidths(), SameLine(), ImGuiWindow::SkipItems, ImGuiContext::Style, TextUnformatted(), and ImVec2::x.
Referenced by DragFloat2(), DragFloat3(), and DragFloat4().
DragIntN()
bool ImGui::DragIntN (const char * label, int * v, int components, float v_speed, int v_min, int v_max, const char * display_format)
References BeginGroup(), DragInt(), EndGroup(), FindRenderedTextEnd(), GetCurrentWindow(), GImGui, ImGuiStyle::ItemInnerSpacing, PopID(), PopItemWidth(), PushID(), PushMultiItemsWidths(), SameLine(), ImGuiWindow::SkipItems, ImGuiContext::Style, TextUnformatted(), and ImVec2::x.
Referenced by DragInt2(), DragInt3(), and DragInt4().
InputTextEx()
bool ImGui::InputTextEx (const char * label, char * buf, int buf_size, const ImVec2 & size_arg, ImGuiInputTextFlags flags, ImGuiTextEditCallback callback = NULL, void * user_data = NULL)
References ImGuiContext::ActiveId, ImGuiContext::ActiveIdAllowNavDirFlags, ImGuiContext::ActiveIdAllowOverlap, ImGuiContext::ActiveIdIsJustActivated, ImGuiContext::ActiveIdPreviousFrame, ImDrawList::AddLine(), ImDrawList::AddRectFilled(), ImDrawList::AddText(), ImFontGlyph::AdvanceX, ImFont::Ascent, BeginChildFrame(), BeginGroup(), ImGuiTextEditCallbackData::Buf, ImGuiTextEditCallbackData::BufDirty, ImGuiTextEditCallbackData::BufSize, ImGuiTextEditState::BufSizeA, ImGuiTextEditCallbackData::BufTextLen, CalcItemSize(), CalcItemWidth(), CalcTextSize(), ClearActiveID(), ImGuiTextEditState::ClearSelection(), ImRect::ClipWith(), ImFont::ContainerAtlas, ImGuiTextEditState::CurLenA, ImGuiTextEditState::CurLenW, ImGuiTextEditState::CursorAnim, ImGuiTextEditState::CursorAnimReset(), ImGuiTextEditState::CursorClamp(), ImGuiTextEditState::CursorFollow, ImGuiDrawContext::CursorPos, ImGuiTextEditCallbackData::CursorPos, ImVector< T >::Data, ImGuiWindow::DC, ImGuiIO::DeltaTime, ImFont::Descent, ImFont::DisplayOffset, ImGuiWindow::DrawList, Dummy(), ImVector< T >::empty(), EndChildFrame(), EndGroup(), ImGuiTextEditCallbackData::EventFlag, ImGuiTextEditCallbackData::EventKey, ImFont::FallbackAdvanceX, ImFont::FallbackGlyph, ImFont::FindGlyph(), ImGuiTextEditCallbackData::Flags, FocusableItemRegister(), ImGuiWindow::FocusIdxAllCounter, ImGuiWindow::FocusIdxAllRequestCurrent, FocusWindow(), ImGuiContext::Font, ImGuiContext::FontSize, ImFont::FontSize, ImGuiStyle::FramePadding, ImGuiStyle::FrameRounding, ImRect::GetBL(), ImFont::GetCharAdvance(), GetClipboardText(), GetColorU32(), GetCurrentWindow(), ImGuiWindow::GetID(), ImGuiWindow::GetIDNoKeepAlive(), GetScrollMaxY(), ImRect::GetSize(), GetTextLineHeight(), GImGui, ImFont::Glyphs, ImGuiTextEditState::HasSelection(), ImGuiTextEditState::Id, IM_ARRAYSIZE, IM_ASSERT, ImGuiCol_FrameBg, ImGuiCol_Text, ImGuiCol_TextSelectedBg, ImGuiDir_Down, ImGuiDir_Up, ImGuiInputTextFlags_AllowTabInput, ImGuiInputTextFlags_AlwaysInsertMode, ImGuiInputTextFlags_AutoSelectAll, ImGuiInputTextFlags_CallbackAlways, ImGuiInputTextFlags_CallbackCompletion, ImGuiInputTextFlags_CallbackHistory, ImGuiInputTextFlags_CtrlEnterForNewLine, ImGuiInputTextFlags_EnterReturnsTrue, ImGuiInputTextFlags_Multiline, ImGuiInputTextFlags_NoHorizontalScroll, ImGuiInputTextFlags_NoUndoRedo, ImGuiInputTextFlags_Password, ImGuiInputTextFlags_ReadOnly, ImGuiKey_A, ImGuiKey_Backspace, ImGuiKey_C, ImGuiKey_COUNT, ImGuiKey_Delete, ImGuiKey_DownArrow, ImGuiKey_End, ImGuiKey_Enter, ImGuiKey_Escape, ImGuiKey_Home, ImGuiKey_Insert, ImGuiKey_LeftArrow, ImGuiKey_RightArrow, ImGuiKey_Tab, ImGuiKey_UpArrow, ImGuiKey_V, ImGuiKey_X, ImGuiKey_Y, ImGuiKey_Z, ImGuiMouseCursor_TextInput, ImMax(), ImMin(), ImStrbolW(), ImStrncpy(), ImTextCharFromUtf8(), ImTextCountCharsFromUtf8(), ImTextCountUtf8BytesFromStr(), ImTextStrFromUtf8(), ImTextStrToUtf8(), ImFont::IndexAdvanceX, ImFont::IndexLookup, ImGuiTextEditState::InitialText, ImGuiIO::InputCharacters, InputTextCalcTextLenAndLineCount(), InputTextCalcTextSizeW(), InputTextFilterCharacter(), ImGuiContext::InputTextPasswordFont, ImGuiContext::InputTextState, ImGuiContext::IO, IsKeyPressedMap(), ItemAdd(), ItemHoverable(), ImGuiStyle::ItemInnerSpacing, ItemSize(), ImGuiIO::KeyAlt, ImGuiIO::KeyCtrl, ImGuiIO::KeyShift, ImGuiIO::KeySuper, ImGuiContext::LogEnabled, LogRenderedText(), ImRect::Max, MemAlloc(), MemFree(), memset(), ImRect::Min, ImGuiIO::MouseClicked, ImGuiContext::MouseCursor, ImGuiIO::MouseDelta, ImGuiIO::MouseDoubleClicked, ImGuiIO::MouseDown, ImGuiIO::MousePos, ImGuiContext::NavInputId, NULL, ImGuiTextEditState::OnKeyPressed(), ImGuiIO::OptCursorBlink, ImGuiIO::OptMacOSXBehaviors, ImGuiContext::OsImePosRequest, ImRect::Overlaps(), PopFont(), PushFont(), ImGuiTextEditCallbackData::ReadOnly, RenderFrame(), RenderNavHighlight(), RenderText(), ImVector< T >::resize(), ImFont::Scale, ImGuiWindow::Scroll, ImGuiWindow::ScrollbarSizes, ImGuiTextEditState::ScrollX, ImGuiTextEditState::SelectAll(), ImGuiTextEditState::SelectedAllMouseLock, ImGuiTextEditCallbackData::SelectionEnd, ImGuiTextEditCallbackData::SelectionStart, SetActiveID(), SetClipboardText(), ImGuiIO::SetClipboardTextFn, SetFocusID(), SetWindowScrollY(), ImVector< T >::Size, ImGuiWindow::SkipItems, STB_TEXTEDIT_K_BACKSPACE, STB_TEXTEDIT_K_DELETE, STB_TEXTEDIT_K_DOWN, STB_TEXTEDIT_K_LEFT, STB_TEXTEDIT_K_LINEEND, STB_TEXTEDIT_K_LINESTART, STB_TEXTEDIT_K_REDO, STB_TEXTEDIT_K_RIGHT, STB_TEXTEDIT_K_SHIFT, STB_TEXTEDIT_K_TEXTEND, STB_TEXTEDIT_K_TEXTSTART, STB_TEXTEDIT_K_UNDO, STB_TEXTEDIT_K_UP, STB_TEXTEDIT_K_WORDLEFT, STB_TEXTEDIT_K_WORDRIGHT, ImGuiTextEditState::StbState, ImGuiContext::Style, ImGuiTextEditState::TempTextBuffer, ImGuiTextEditState::Text, ImGuiTextEditCallbackData::UserData, ImVec4::w, ImGuiContext::WantTextInputNextFrame, ImVec2::x, ImVec2::y, and ImVec4::y.
Referenced by InputScalarAsWidgetReplacement(), InputText(), and InputTextMultiline().
InputFloatN()
bool ImGui::InputFloatN (const char * label, float * v, int components, int decimal_precision, ImGuiInputTextFlags extra_flags)
References BeginGroup(), EndGroup(), FindRenderedTextEnd(), GetCurrentWindow(), GImGui, InputFloat(), ImGuiStyle::ItemInnerSpacing, PopID(), PopItemWidth(), PushID(), PushMultiItemsWidths(), SameLine(), ImGuiWindow::SkipItems, ImGuiContext::Style, TextUnformatted(), and ImVec2::x.
Referenced by InputFloat2(), InputFloat3(), and InputFloat4().
InputIntN()
bool ImGui::InputIntN (const char * label, int * v, int components, ImGuiInputTextFlags extra_flags)
References BeginGroup(), EndGroup(), FindRenderedTextEnd(), GetCurrentWindow(), GImGui, InputInt(), ImGuiStyle::ItemInnerSpacing, PopID(), PopItemWidth(), PushID(), PushMultiItemsWidths(), SameLine(), ImGuiWindow::SkipItems, ImGuiContext::Style, TextUnformatted(), and ImVec2::x.
Referenced by InputInt2(), InputInt3(), and InputInt4().
InputScalarEx()
bool ImGui::InputScalarEx (const char * label, ImGuiDataType data_type, void * data_ptr, void * step_ptr, void * step_fast_ptr, const char * scalar_format, ImGuiInputTextFlags extra_flags)
References ImVector< T >::begin(), BeginGroup(), ButtonEx(), CalcItemWidth(), CalcTextSize(), ImGuiDrawContext::CursorPos, DataTypeApplyOp(), DataTypeApplyOpFromText(), DataTypeFormatString(), ImGuiWindow::DC, EndGroup(), ImGuiStyle::FramePadding, GetCurrentWindow(), GetFrameHeight(), GImGui, IM_ARRAYSIZE, ImGuiButtonFlags_DontClosePopups, ImGuiButtonFlags_Repeat, ImGuiInputTextFlags_AutoSelectAll, ImGuiInputTextFlags_CharsDecimal, ImGuiInputTextFlags_CharsHexadecimal, ImMax(), ImGuiTextEditState::InitialText, InputText(), ImGuiContext::InputTextState, ImGuiContext::IO, ImGuiStyle::ItemInnerSpacing, ItemSize(), ImGuiIO::KeyCtrl, NULL, PopID(), PopItemWidth(), PushID(), PushItemWidth(), RenderText(), SameLine(), ImGuiWindow::SkipItems, ImGuiContext::Style, ImVec2::x, and ImVec2::y.
Referenced by InputFloat(), and InputInt().
InputScalarAsWidgetReplacement()
bool ImGui::InputScalarAsWidgetReplacement (const ImRect & aabb, const char * label, ImGuiDataType data_type, void * data_ptr, ImGuiID id, int decimal_precision)
References ImGuiContext::ActiveId, ImGuiContext::ActiveIdAllowNavDirFlags, ImVector< T >::begin(), DataTypeApplyOpFromText(), DataTypeFormatString(), FocusableItemUnregister(), GetCurrentWindow(), ImRect::GetSize(), GImGui, IM_ARRAYSIZE, IM_ASSERT, ImGuiDir_Down, ImGuiDir_Up, ImGuiInputTextFlags_AutoSelectAll, ImGuiInputTextFlags_CharsDecimal, ImGuiTextEditState::InitialText, InputTextEx(), ImGuiContext::InputTextState, NULL, ImGuiContext::ScalarAsInputTextId, SetActiveID(), and SetHoveredID().
Referenced by DragFloat(), and SliderFloat().
ColorTooltip()
void ImGui::ColorTooltip (const char * text, const float * col, ImGuiColorEditFlags flags)
References BeginTooltipEx(), ColorButton(), EndTooltip(), FindRenderedTextEnd(), ImGuiContext::FontSize, ImGuiStyle::FramePadding, GImGui, IM_F32_TO_INT8_SAT, ImGuiColorEditFlags_AlphaPreview, ImGuiColorEditFlags_AlphaPreviewHalf, ImGuiColorEditFlags_NoAlpha, ImGuiColorEditFlags_NoTooltip, NULL, SameLine(), Separator(), ImGuiContext::Style, Text(), TextUnformatted(), and ImVec2::y.
Referenced by ColorButton().
ColorEditOptionsPopup()
void ImGui::ColorEditOptionsPopup (const float * col, ImGuiColorEditFlags flags)
References BeginPopup(), Button(), ImGuiContext::ColorEditOptions, EndPopup(), GImGui, IM_ARRAYSIZE, IM_F32_TO_INT8_SAT, ImFormatString(), ImGuiColorEditFlags__DataTypeMask, ImGuiColorEditFlags__InputsMask, ImGuiColorEditFlags_Float, ImGuiColorEditFlags_HEX, ImGuiColorEditFlags_HSV, ImGuiColorEditFlags_NoAlpha, ImGuiColorEditFlags_RGB, ImGuiColorEditFlags_Uint8, OpenPopup(), RadioButton(), Selectable(), Separator(), and SetClipboardText().
Referenced by ColorEdit4().
TreeNodeBehavior()
bool ImGui::TreeNodeBehavior (ImGuiID id, ImGuiTreeNodeFlags flags, const char * label, const char * label_end = NULL)
References ButtonBehavior(), CalcTextSize(), ImGuiDrawContext::CurrentLineHeight, ImGuiDrawContext::CurrentLineTextBaseOffset, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, ImGuiContext::DragDropActive, FindRenderedTextEnd(), ImGuiContext::FontSize, ImGuiStyle::FramePadding, ImGuiStyle::FrameRounding, GetColorU32(), GetContentRegionMax(), GetCurrentWindow(), GImGui, ImGuiButtonFlags_AllowItemOverlap, ImGuiButtonFlags_NoKeyModifiers, ImGuiButtonFlags_PressedOnClickRelease, ImGuiButtonFlags_PressedOnDoubleClick, ImGuiButtonFlags_PressedOnDragDropHold, ImGuiCol_Header, ImGuiCol_HeaderActive, ImGuiCol_HeaderHovered, ImGuiDir_Down, ImGuiDir_Left, ImGuiDir_Right, ImGuiItemStatusFlags_HasDisplayRect, ImGuiNavHighlightFlags_TypeThin, ImGuiTreeNodeFlags_AllowItemOverlap, ImGuiTreeNodeFlags_Bullet, ImGuiTreeNodeFlags_Framed, ImGuiTreeNodeFlags_FramePadding, ImGuiTreeNodeFlags_Leaf, ImGuiTreeNodeFlags_NavLeftJumpsBackHere, ImGuiTreeNodeFlags_NoTreePushOnOpen, ImGuiTreeNodeFlags_OpenOnArrow, ImGuiTreeNodeFlags_OpenOnDoubleClick, ImGuiTreeNodeFlags_Selected, ImMax(), ImMin(), ImGuiContext::IO, IsMouseHoveringRect(), ItemAdd(), ItemSize(), ImGuiStyle::ItemSpacing, ImGuiDrawContext::LastItemDisplayRect, ImGuiDrawContext::LastItemStatusFlags, ImGuiContext::LogEnabled, LogRenderedText(), ImRect::Max, ImRect::Min, ImGuiIO::MouseDoubleClicked, ImGuiContext::NavActivateId, ImGuiContext::NavDisableMouseHover, ImGuiContext::NavId, ImGuiContext::NavIdIsAlive, ImGuiContext::NavMoveDir, ImGuiContext::NavMoveRequest, NavMoveRequestCancel(), ImGuiWindow::Pos, RenderBullet(), RenderFrame(), RenderNavHighlight(), RenderText(), RenderTextClipped(), RenderTriangle(), ImGuiStorage::SetInt(), SetItemAllowOverlap(), ImGuiWindow::SkipItems, ImGuiDrawContext::StateStorage, ImGuiContext::Style, ImGuiDrawContext::TreeDepth, ImGuiDrawContext::TreeDepthMayJumpToParentOnPop, TreeNodeBehaviorIsOpen(), TreePushRawID(), ImGuiWindow::WindowPadding, ImVec2::x, and ImVec2::y.
Referenced by CollapsingHeader(), TreeNode(), TreeNodeEx(), and TreeNodeExV().
TreeNodeBehaviorIsOpen()
bool ImGui::TreeNodeBehaviorIsOpen (ImGuiID id, ImGuiTreeNodeFlags flags = 0)
References ImGuiContext::CurrentWindow, ImGuiWindow::DC, ImGuiStorage::GetInt(), GImGui, ImGuiCond_Always, ImGuiTreeNodeFlags_DefaultOpen, ImGuiTreeNodeFlags_Leaf, ImGuiTreeNodeFlags_NoAutoOpenOnLog, ImGuiContext::LogAutoExpandMaxDepth, ImGuiContext::LogEnabled, ImGuiContext::NextTreeNodeOpenCond, ImGuiContext::NextTreeNodeOpenVal, ImGuiStorage::SetInt(), ImGuiDrawContext::StateStorage, and ImGuiDrawContext::TreeDepth.
Referenced by TreeNodeBehavior().
TreePushRawID()
void ImGui::TreePushRawID (ImGuiID id)
References ImGuiWindow::DC, GetCurrentWindow(), ImGuiWindow::IDStack, Indent(), ImVector< T >::push_back(), and ImGuiDrawContext::TreeDepth.
Referenced by TreeNodeBehavior().
PlotEx()
void ImGui::PlotEx (ImGuiPlotType plot_type, const char * label, float(*)(void *data, int idx) values_getter, void * data, int values_count, int values_offset, const char * overlay_text, float scale_min, float scale_max, ImVec2 graph_size)
References ImDrawList::AddLine(), ImDrawList::AddRectFilled(), CalcItemWidth(), CalcTextSize(), ImGuiDrawContext::CursorPos, ImGuiWindow::DC, ImGuiWindow::DrawList, FLT_MAX, ImGuiStyle::FramePadding, ImGuiStyle::FrameRounding, GetColorU32(), GetCurrentWindow(), GImGui, IM_ASSERT, ImClamp(), ImGuiCol_FrameBg, ImGuiCol_PlotHistogram, ImGuiCol_PlotHistogramHovered, ImGuiCol_PlotLines, ImGuiCol_PlotLinesHovered, ImGuiPlotType_Histogram, ImGuiPlotType_Lines, ImLerp(), ImMax(), ImMin(), ImSaturate(), ImGuiContext::IO, ItemAdd(), ItemHoverable(), ImGuiStyle::ItemInnerSpacing, ItemSize(), ImRect::Max, ImRect::Min, ImGuiIO::MousePos, NULL, RenderFrame(), RenderText(), RenderTextClipped(), SetTooltip(), ImGuiWindow::SkipItems, ImGuiContext::Style, ImVec2::x, and ImVec2::y.
Referenced by PlotHistogram(), and PlotLines().
ParseFormatPrecision()
int ImGui::ParseFormatPrecision (const char * fmt, int default_value)
References ImAtoi(), and NULL.
Referenced by DragFloat(), SliderFloat(), and VSliderFloat().
RoundScalar()
float ImGui::RoundScalar (float value, int decimal_precision)
References GetMinimumStepAtDecimalPrecision(), and value.
Referenced by DragBehavior(), and SliderBehavior().
ShadeVertsLinearColorGradientKeepAlpha()
void ImGui::ShadeVertsLinearColorGradientKeepAlpha (ImDrawVert * vert_start, ImDrawVert * vert_end, ImVec2 gradient_p0, ImVec2 gradient_p1, ImU32 col0, ImU32 col1)
References IM_COL32_A_MASK, IM_COL32_B_SHIFT, IM_COL32_G_SHIFT, IM_COL32_R_SHIFT, ImClamp(), ImDot(), ImLengthSqr(), and ImLerp().
Referenced by ColorPicker4().
ShadeVertsLinearAlphaGradientForLeftToRightText()
void ImGui::ShadeVertsLinearAlphaGradientForLeftToRightText (ImDrawVert * vert_start, ImDrawVert * vert_end, float gradient_p0_x, float gradient_p1_x)
References a, IM_COL32_A_MASK, IM_COL32_A_SHIFT, and ImClamp().
ShadeVertsLinearUV()
void ImGui::ShadeVertsLinearUV (ImDrawVert * vert_start, ImDrawVert * vert_end, const ImVec2 & a, const ImVec2 & b, const ImVec2 & uv_a, const ImVec2 & uv_b, bool clamp)
References a, ImClamp(), ImMax(), ImMin(), ImMul(), afwstd::max(), min(), scale(), ImVec2::x, and ImVec2::y.
Referenced by ImDrawList::AddImageRounded().
CreateContext()
ImGuiContext * ImGui::CreateContext (ImFontAtlas * shared_font_atlas = NULL)
References GImGui, IM_NEW, Initialize(), NULL, and SetCurrentContext().
Referenced by AuroraFW::GEngine::GraphicsContext::GraphicsContext().
DestroyContext()
void ImGui::DestroyContext (ImGuiContext * ctx = NULL)
References GImGui, IM_DELETE(), NULL, SetCurrentContext(), and Shutdown().
GetCurrentContext()
ImGuiContext * ImGui::GetCurrentContext ()
References GImGui.
SetCurrentContext()
void ImGui::SetCurrentContext (ImGuiContext * ctx)
References GImGui.
Referenced by CreateContext(), and DestroyContext().
GetIO()
ImGuiIO & ImGui::GetIO ()
References GImGui, IM_ASSERT, ImGuiContext::IO, and NULL.
Referenced by AuroraFW::GEngine::GLImGuiLoader::createDeviceObjects(), AuroraFW::GEngine::GraphicsContext::GraphicsContext(), AuroraFW::GEngine::GLImGuiLoader::invalidateDeviceObjects(), AuroraFW::GEngine::ImGuiLoader::Load(), AuroraFW::GEngine::ImGuiLoader::newFrame(), AuroraFW::GEngine::GLImGuiLoader::renderDrawLists(), SetNextWindowPosCenter(), and ShowMetricsWindow().
GetStyle()
ImGuiStyle & ImGui::GetStyle ()
References GImGui, IM_ASSERT, NULL, and ImGuiContext::Style.
Referenced by ListBoxFooter(), ListBoxHeader(), StyleColorsClassic(), StyleColorsDark(), and StyleColorsLight().
NewFrame()
void ImGui::NewFrame ()
References ImGuiWindow::Active, ImGuiContext::ActiveId, ImGuiContext::ActiveIdIsAlive, ImGuiContext::ActiveIdIsJustActivated, ImGuiContext::ActiveIdPreviousFrame, ImGuiContext::ActiveIdTimer, ImGuiStyle::Alpha, ImGuiStyle::AntiAliasedFill, ImGuiStyle::AntiAliasedLines, Begin(), ImGuiWindow::CalcFontSize(), ImVector< T >::clear(), ImDrawList::Clear(), ImDrawData::Clear(), ClearActiveID(), ClearDragDrop(), ImDrawListSharedData::ClipRectFullscreen, ClosePopupsOverWindow(), ImGuiWindow::Collapsed, ImGuiIO::ConfigFlags, ImGuiWindow::ContentsRegionRect, ImGuiContext::CurrentPopupStack, ImGuiContext::CurrentWindowStack, ImDrawListSharedData::CurveTessellationTol, ImGuiStyle::CurveTessellationTol, ImGuiPayload::DataFrameCount, ImGuiIO::DeltaTime, ImGuiIO::DisplaySize, ImGuiContext::DragDropAcceptIdCurr, ImGuiContext::DragDropAcceptIdCurrRectSurface, ImGuiContext::DragDropAcceptIdPrev, ImGuiContext::DragDropActive, ImGuiContext::DragDropPayload, ImGuiContext::DragDropPayloadBufHeap, ImGuiContext::DragDropPayloadBufLocal, ImGuiContext::DragDropSourceFlags, ImGuiContext::DrawData, ImGuiContext::DrawListSharedData, ImVector< T >::empty(), FindHoveredWindow(), ImGuiWindow::Flags, ImDrawList::Flags, FLT_MAX, FocusFrontMostActiveWindow(), ImGuiWindow::FocusIdxTabRequestNext, ImGuiContext::Font, ImGuiIO::FontAllowUserScaling, ImGuiIO::Fonts, ImFontAtlas::Fonts, ImGuiWindow::FontWindowScale, ImGuiContext::FrameCount, ImGuiContext::FrameCountEnded, ImGuiIO::Framerate, ImGuiContext::FramerateSecPerFrame, ImGuiContext::FramerateSecPerFrameAccum, ImGuiContext::FramerateSecPerFrameIdx, GetDefaultFont(), GetFrontMostModalRootWindow(), ImRect::GetHeight(), GImGui, ImGuiContext::HoveredId, ImGuiContext::HoveredIdAllowOverlap, ImGuiContext::HoveredIdPreviousFrame, ImGuiContext::HoveredIdTimer, ImGuiContext::HoveredRootWindow, ImGuiContext::HoveredWindow, IM_ARRAYSIZE, IM_ASSERT, ImClamp(), ImDrawListFlags_AntiAliasedFill, ImDrawListFlags_AntiAliasedLines, ImGuiCond_FirstUseEver, ImGuiConfigFlags_NavEnableKeyboard, ImGuiConfigFlags_NavNoCaptureKeyboard, ImGuiDragDropFlags_SourceExtern, ImGuiKey_COUNT, ImGuiKey_Space, ImGuiKey_Tab, ImGuiMouseCursor_Arrow, ImGuiWindowFlags_ChildWindow, ImGuiWindowFlags_NoInputs, ImGuiWindowFlags_NoNavInputs, ImGuiWindowFlags_NoScrollbar, ImGuiWindowFlags_NoScrollWithMouse, ImLengthSqr(), ImMax(), ImMin(), ImGuiIO::IniFilename, ImGuiContext::Initialized, ImGuiContext::IO, IsKeyPressedMap(), ImFont::IsLoaded(), IsMousePosValid(), IsWindowChildOf(), ImGuiIO::KeyCtrl, ImGuiIO::KeyMap, ImGuiIO::KeysDown, ImGuiIO::KeysDownDuration, ImGuiIO::KeysDownDurationPrev, ImGuiIO::KeyShift, LoadIniSettingsFromDisk(), memcpy(), memset(), ImGuiContext::ModalWindowDarkeningRatio, ImGuiIO::MouseClicked, ImGuiIO::MouseClickedPos, ImGuiIO::MouseClickedTime, ImGuiContext::MouseCursor, ImGuiIO::MouseDelta, ImGuiIO::MouseDoubleClicked, ImGuiIO::MouseDoubleClickMaxDist, ImGuiIO::MouseDoubleClickTime, ImGuiIO::MouseDown, ImGuiIO::MouseDownDuration, ImGuiIO::MouseDownDurationPrev, ImGuiIO::MouseDownOwned, ImGuiIO::MouseDragMaxDistanceAbs, ImGuiIO::MouseDragMaxDistanceSqr, ImGuiIO::MousePos, ImGuiIO::MousePosPrev, ImGuiIO::MouseReleased, ImGuiIO::MouseWheel, ImGuiIO::MouseWheelH, ImGuiContext::MovingWindow, ImGuiIO::NavActive, ImGuiContext::NavDisableMouseHover, ImGuiContext::NavId, ImGuiContext::NavIdTabCounter, NavUpdate(), ImGuiContext::NavWindow, NULL, ImGuiContext::OpenPopupStack, ImGuiContext::OsImePosRequest, ImGuiContext::OverlayDrawList, ImGuiWindow::ParentWindow, ImGuiWindow::Pos, ImGuiWindow::PosFloat, ImDrawList::PushClipRectFullScreen(), ImDrawList::PushTextureID(), ImVector< T >::resize(), ImGuiWindow::RootWindow, SaveIniSettingsToDisk(), ImGuiContext::ScalarAsInputTextId, scale(), ImGuiWindow::Scroll, SetCurrentFont(), SetNextWindowSize(), ImGuiContext::SettingsDirtyTimer, ImGuiContext::SettingsLoaded, ImGuiContext::SettingsWindows, SetWindowScrollX(), SetWindowScrollY(), ImGuiWindow::Size, ImVector< T >::Size, ImGuiWindow::SizeFull, ImGuiContext::Style, ImFontAtlas::TexID, ImGuiContext::Time, ImGuiContext::TooltipOverrideCount, UpdateMovingWindow(), ImGuiIO::WantCaptureKeyboard, ImGuiContext::WantCaptureKeyboardNextFrame, ImGuiIO::WantCaptureMouse, ImGuiContext::WantCaptureMouseNextFrame, ImGuiIO::WantTextInput, ImGuiContext::WantTextInputNextFrame, ImGuiWindow::WasActive, ImGuiWindow::WindowPadding, ImGuiContext::Windows, ImGuiContext::WindowsActiveCount, ImGuiWindow::WriteAccessed, ImVec2::x, and ImVec2::y.
Referenced by AuroraFW::GEngine::ImGuiLoader::newFrame().
Render()
void ImGui::Render ()
References ImGuiWindow::Active, AddDrawListToDrawData(), ImDrawList::AddImage(), AddWindowToDrawDataSelectLayer(), ImGuiStyle::Alpha, ImDrawDataBuilder::Clear(), ImDrawData::CmdListsCount, ImGuiContext::DrawData, ImGuiContext::DrawDataBuilder, ImVector< T >::empty(), EndFrame(), ImGuiWindow::Flags, ImDrawDataBuilder::FlattenIntoSingleLayer(), ImGuiIO::Fonts, ImGuiContext::FrameCount, ImGuiContext::FrameCountEnded, ImGuiContext::FrameCountRendered, ImFontAtlas::GetMouseCursorTexData(), GImGui, ImGuiWindow::HiddenFrames, IM_ASSERT, IM_COL32, ImGuiWindowFlags_ChildWindow, ImGuiWindowFlags_NoBringToFrontOnFocus, ImGuiContext::Initialized, ImGuiContext::IO, ImDrawDataBuilder::Layers, ImGuiIO::MetricsActiveWindows, ImGuiIO::MetricsRenderIndices, ImGuiIO::MetricsRenderVertices, ImGuiContext::MouseCursor, ImGuiStyle::MouseCursorScale, ImGuiIO::MouseDrawCursor, ImGuiIO::MousePos, ImGuiContext::NavWindowingTarget, NULL, ImGuiContext::OverlayDrawList, ImDrawList::PopTextureID(), ImDrawList::PushTextureID(), ImGuiIO::RenderDrawListsFn, SetupDrawData(), ImVector< T >::Size, ImGuiContext::Style, ImFontAtlas::TexID, ImDrawData::TotalIdxCount, ImDrawData::TotalVtxCount, ImDrawList::VtxBuffer, and ImGuiContext::Windows.
Referenced by AuroraFW::GEngine::GraphicsContext::renderLoop().
GetDrawData()
ImDrawData * ImGui::GetDrawData ()
References ImGuiContext::DrawData, GImGui, NULL, and ImDrawData::Valid.
Referenced by AuroraFW::GEngine::GraphicsContext::renderLoop().
EndFrame()
void ImGui::EndFrame ()
References ImGuiWindow::Active, ImGuiContext::ActiveId, ImGuiContext::ActiveIdClickOffset, AddWindowToSortedBuffer(), ImGuiWindow::Appearing, ClosePopupsOverWindow(), ImGuiContext::CurrentWindow, ImGuiContext::CurrentWindowStack, End(), ImGuiWindow::Flags, FocusWindow(), ImGuiContext::FrameCount, ImGuiContext::FrameCountEnded, GetFrontMostModalRootWindow(), GImGui, ImGuiContext::HoveredId, ImGuiContext::HoveredRootWindow, ImGuiContext::HoveredWindow, IM_ASSERT, ImGuiIO::ImeSetInputScreenPosFn, ImGuiWindowFlags_ChildWindow, ImGuiWindowFlags_NoMove, ImLengthSqr(), ImGuiContext::Initialized, ImGuiIO::InputCharacters, ImGuiContext::IO, memset(), ImGuiIO::MouseClicked, ImGuiIO::MousePos, ImGuiIO::MouseWheel, ImGuiIO::MouseWheelH, ImGuiWindow::MoveId, ImGuiContext::MovingWindow, ImGuiContext::NavDisableHighlight, ImGuiIO::NavInputs, ImGuiContext::NavWindow, NULL, ImGuiContext::OsImePosRequest, ImGuiContext::OsImePosSet, ImGuiWindow::Pos, ImVector< T >::reserve(), ImVector< T >::resize(), SetActiveID(), ImVector< T >::Size, ImVector< T >::swap(), ImGuiContext::Windows, ImGuiContext::WindowsSortBuffer, ImGuiWindow::WriteAccessed, ImVec2::x, and ImVec2::y.
Referenced by Render().
ShowDemoWindow()
IMGUI_API void ImGui::ShowDemoWindow (bool * p_open = NULL)
Referenced by ShowTestWindow().
ShowMetricsWindow()
void ImGui::ShowMetricsWindow (bool * p_open = NULL)
References ImDrawList::_OwnerName, ImGuiWindow::Active, ImGuiContext::ActiveId, ImGuiContext::ActiveIdPreviousFrame, ImGuiContext::ActiveIdSource, ImGuiContext::ActiveIdTimer, ImGuiContext::ActiveIdWindow, ImRect::Add(), ImDrawList::AddPolyline(), ImDrawList::AddRect(), Begin(), ImVector< T >::begin(), BulletText(), Checkbox(), ImGuiDrawContext::ChildWindows, ImDrawList::CmdBuffer, ImDrawVert::col, ImVector< T >::Data, ImGuiStorage::Data, ImGuiPayload::DataSize, ImGuiPayload::DataType, ImGuiWindow::DC, ImGuiListClipper::DisplayEnd, ImGuiListClipper::DisplayStart, ImGuiContext::DragDropActive, ImGuiContext::DragDropPayload, ImGuiContext::DrawDataBuilder, ImGuiWindow::DrawList, ImDrawCmd::ElemCount, End(), ImVector< T >::end(), ImGuiWindow::Flags, ImDrawList::Flags, ImRect::Floor(), GetIO(), GetOverlayDrawList(), GetScrollMaxX(), GetScrollMaxY(), GetVersion(), GetWindowDrawList(), GImAllocatorActiveAllocationsCount, GImGui, ImGuiContext::HoveredId, ImGuiContext::HoveredIdPreviousFrame, ImGuiContext::HoveredIdTimer, ImGuiContext::HoveredRootWindow, ImGuiContext::HoveredWindow, ImDrawList::IdxBuffer, IM_ARRAYSIZE, IM_ASSERT, IM_COL32, ImDrawListFlags_AntiAliasedLines, ImFormatString(), ImGuiInputSource_Count_, ImGuiWindowFlags_ChildMenu, ImGuiWindowFlags_ChildWindow, ImGuiWindowFlags_Modal, ImGuiWindowFlags_NoSavedSettings, ImGuiWindowFlags_Popup, ImGuiWindowFlags_Tooltip, ImGuiContext::IO, ImRect::IsInverted(), IsItemHovered(), ImDrawDataBuilder::Layers, ImRect::Max, ImRect::Min, ImGuiWindow::Name, ImGuiContext::NavActivateId, ImGuiIO::NavActive, ImGuiContext::NavDisableHighlight, ImGuiContext::NavDisableMouseHover, ImGuiContext::NavId, ImGuiContext::NavInputId, ImGuiWindow::NavLastChildNavWindow, ImGuiWindow::NavLastIds, ImGuiContext::NavLayer, ImGuiDrawContext::NavLayerActiveMask, ImGuiWindow::NavRectRel, ImGuiIO::NavVisible, ImGuiContext::NavWindow, NULL, ImGuiContext::OpenPopupStack, ImGuiWindow::Pos, ImDrawVert::pos, ImGuiWindow::RootWindow, SameLine(), ImGuiWindow::Scroll, Selectable(), Separator(), ImGuiWindow::Size, ImVector< T >::Size, ImGuiWindow::SizeContents, ImGuiPayload::SourceId, ImGuiWindow::StateStorage, ImGuiListClipper::Step(), Text(), TextColored(), TreeNode(), TreePop(), ImDrawVert::uv, ImDrawList::VtxBuffer, ImGuiWindow::WasActive, ImGuiContext::Windows, ImGuiWindow::WriteAccessed, ImVec2::x, and ImVec2::y.
ShowStyleEditor()
IMGUI_API void ImGui::ShowStyleEditor (ImGuiStyle * ref = NULL)
ShowStyleSelector()
IMGUI_API bool ImGui::ShowStyleSelector (const char * label)
ShowFontSelector()
IMGUI_API void ImGui::ShowFontSelector (const char * label)
ShowUserGuide()
IMGUI_API void ImGui::ShowUserGuide ()
GetVersion()
const char * ImGui::GetVersion ()
References IMGUI_VERSION.
Referenced by ShowMetricsWindow().
StyleColorsDark()
void ImGui::StyleColorsDark (ImGuiStyle * dst = NULL)
References ImGuiStyle::Colors, GetStyle(), ImGuiCol_Border, ImGuiCol_BorderShadow, ImGuiCol_Button, ImGuiCol_ButtonActive, ImGuiCol_ButtonHovered, ImGuiCol_CheckMark, ImGuiCol_ChildBg, ImGuiCol_CloseButton, ImGuiCol_CloseButtonActive, ImGuiCol_CloseButtonHovered, ImGuiCol_DragDropTarget, ImGuiCol_FrameBg, ImGuiCol_FrameBgActive, ImGuiCol_FrameBgHovered, ImGuiCol_Header, ImGuiCol_HeaderActive, ImGuiCol_HeaderHovered, ImGuiCol_MenuBarBg, ImGuiCol_ModalWindowDarkening, ImGuiCol_NavHighlight, ImGuiCol_NavWindowingHighlight, ImGuiCol_PlotHistogram, ImGuiCol_PlotHistogramHovered, ImGuiCol_PlotLines, ImGuiCol_PlotLinesHovered, ImGuiCol_PopupBg, ImGuiCol_ResizeGrip, ImGuiCol_ResizeGripActive, ImGuiCol_ResizeGripHovered, ImGuiCol_ScrollbarBg, ImGuiCol_ScrollbarGrab, ImGuiCol_ScrollbarGrabActive, ImGuiCol_ScrollbarGrabHovered, ImGuiCol_Separator, ImGuiCol_SeparatorActive, ImGuiCol_SeparatorHovered, ImGuiCol_SliderGrab, ImGuiCol_SliderGrabActive, ImGuiCol_Text, ImGuiCol_TextDisabled, ImGuiCol_TextSelectedBg, ImGuiCol_TitleBg, ImGuiCol_TitleBgActive, ImGuiCol_TitleBgCollapsed, and ImGuiCol_WindowBg.
StyleColorsClassic()
void ImGui::StyleColorsClassic (ImGuiStyle * dst = NULL)
References ImGuiStyle::Colors, GetStyle(), ImGuiCol_Border, ImGuiCol_BorderShadow, ImGuiCol_Button, ImGuiCol_ButtonActive, ImGuiCol_ButtonHovered, ImGuiCol_CheckMark, ImGuiCol_ChildBg, ImGuiCol_CloseButton, ImGuiCol_CloseButtonActive, ImGuiCol_CloseButtonHovered, ImGuiCol_DragDropTarget, ImGuiCol_FrameBg, ImGuiCol_FrameBgActive, ImGuiCol_FrameBgHovered, ImGuiCol_Header, ImGuiCol_HeaderActive, ImGuiCol_HeaderHovered, ImGuiCol_MenuBarBg, ImGuiCol_ModalWindowDarkening, ImGuiCol_NavHighlight, ImGuiCol_NavWindowingHighlight, ImGuiCol_PlotHistogram, ImGuiCol_PlotHistogramHovered, ImGuiCol_PlotLines, ImGuiCol_PlotLinesHovered, ImGuiCol_PopupBg, ImGuiCol_ResizeGrip, ImGuiCol_ResizeGripActive, ImGuiCol_ResizeGripHovered, ImGuiCol_ScrollbarBg, ImGuiCol_ScrollbarGrab, ImGuiCol_ScrollbarGrabActive, ImGuiCol_ScrollbarGrabHovered, ImGuiCol_Separator, ImGuiCol_SeparatorActive, ImGuiCol_SeparatorHovered, ImGuiCol_SliderGrab, ImGuiCol_SliderGrabActive, ImGuiCol_Text, ImGuiCol_TextDisabled, ImGuiCol_TextSelectedBg, ImGuiCol_TitleBg, ImGuiCol_TitleBgActive, ImGuiCol_TitleBgCollapsed, and ImGuiCol_WindowBg.
Referenced by ImGuiStyle::ImGuiStyle().
StyleColorsLight()
void ImGui::StyleColorsLight (ImGuiStyle * dst = NULL)
References ImGuiStyle::Colors, GetStyle(), ImGuiCol_Border, ImGuiCol_BorderShadow, ImGuiCol_Button, ImGuiCol_ButtonActive, ImGuiCol_ButtonHovered, ImGuiCol_CheckMark, ImGuiCol_ChildBg, ImGuiCol_CloseButton, ImGuiCol_CloseButtonActive, ImGuiCol_CloseButtonHovered, ImGuiCol_DragDropTarget, ImGuiCol_FrameBg, ImGuiCol_FrameBgActive, ImGuiCol_FrameBgHovered, ImGuiCol_Header, ImGuiCol_HeaderActive, ImGuiCol_HeaderHovered, ImGuiCol_MenuBarBg, ImGuiCol_ModalWindowDarkening, ImGuiCol_NavHighlight, ImGuiCol_NavWindowingHighlight, ImGuiCol_PlotHistogram, ImGuiCol_PlotHistogramHovered, ImGuiCol_PlotLines, ImGuiCol_PlotLinesHovered, ImGuiCol_PopupBg, ImGuiCol_ResizeGrip, ImGuiCol_ResizeGripActive, ImGuiCol_ResizeGripHovered, ImGuiCol_ScrollbarBg, ImGuiCol_ScrollbarGrab, ImGuiCol_ScrollbarGrabActive, ImGuiCol_ScrollbarGrabHovered, ImGuiCol_Separator, ImGuiCol_SeparatorActive, ImGuiCol_SeparatorHovered, ImGuiCol_SliderGrab, ImGuiCol_SliderGrabActive, ImGuiCol_Text, ImGuiCol_TextDisabled, ImGuiCol_TextSelectedBg, ImGuiCol_TitleBg, ImGuiCol_TitleBgActive, ImGuiCol_TitleBgCollapsed, and ImGuiCol_WindowBg.
Begin() [1/2]
bool ImGui::Begin (const char * name, bool * p_open = NULL, ImGuiWindowFlags flags = 0)
References ImGuiWindow::Active, ImDrawList::AddLine(), ImDrawList::AddRect(), ImDrawList::AddRectFilled(), ImGuiStyle::Alpha, ImGuiResizeGripDef::AngleMax12, ImGuiResizeGripDef::AngleMin12, ImGuiStyle::AntiAliasedFill, ImGuiStyle::AntiAliasedLines, ImGuiWindow::Appearing, ImGuiWindow::AutoFitFramesX, ImGuiWindow::AutoFitFramesY, ImGuiWindow::AutoFitOnlyGrows, ImGuiWindow::AutoPosLastDirection, ImVector< T >::back(), ImGuiWindow::BeginCount, ImGuiWindow::BeginOrderWithinContext, ImGuiWindow::BeginOrderWithinParent, ImGuiNextWindowData::BgAlphaCond, ImGuiNextWindowData::BgAlphaVal, ButtonBehavior(), CalcNextScrollFromScrollTargetAndClamp(), CalcSizeAfterConstraint(), CalcSizeAutoFit(), CalcSizeContents(), CalcTextSize(), CheckStacksSize(), ImGuiStyle::ChildBorderSize, ImGuiStyle::ChildRounding, ImGuiDrawContext::ChildWindows, ImDrawList::Clear(), ImGuiWindow::ClipRect, ImRect::ClipWith(), ImGuiWindow::CloseButton, CloseButton(), ImGuiWindow::Collapsed, ImGuiNextWindowData::CollapsedCond, ImGuiNextWindowData::CollapsedVal, ImGuiWindow::CollapseToggleWanted, ImGuiDrawContext::ColumnsOffsetX, ImGuiDrawContext::ColumnsSet, ImGuiIO::ConfigFlags, ImFont::ContainerAtlas, ImRect::Contains(), ImGuiNextWindowData::ContentSizeCond, ImGuiNextWindowData::ContentSizeVal, ImGuiWindow::ContentsRegionRect, ImGuiResizeGripDef::CornerPos, CreateNewWindow(), ImGuiDrawContext::CurrentLineHeight, ImGuiDrawContext::CurrentLineTextBaseOffset, ImGuiContext::CurrentPopupStack, ImGuiContext::CurrentWindowStack, ImGuiDrawContext::CursorMaxPos, ImGuiDrawContext::CursorPos, ImGuiDrawContext::CursorPosPrevLine, ImGuiDrawContext::CursorStartPos, ImGuiWindow::DC, ImGuiStyle::DisplaySafeAreaPadding, ImGuiIO::DisplaySize, ImGuiStyle::DisplayWindowPadding, ImGuiWindow::DrawList, ImVector< T >::empty(), ImRect::Expand(), FindBestWindowPosForPopup(), FindWindowByName(), ImGuiWindow::Flags, ImDrawList::Flags, FLT_MAX, ImGuiNextWindowData::FocusCond, ImGuiWindow::FocusIdxAllCounter, ImGuiWindow::FocusIdxAllRequestCurrent, ImGuiWindow::FocusIdxAllRequestNext, ImGuiWindow::FocusIdxTabCounter, ImGuiWindow::FocusIdxTabRequestCurrent, ImGuiWindow::FocusIdxTabRequestNext, FocusWindow(), ImGuiContext::Font, ImGuiContext::FontSize, ImGuiStyle::FrameBorderSize, ImGuiContext::FrameCount, ImGuiContext::FrameCountEnded, ImGuiStyle::FramePadding, ImRect::GetBL(), GetBorderRect(), ImRect::GetBR(), GetColorU32(), GetFrontMostModalRootWindow(), ImRect::GetHeight(), ImGuiWindow::GetID(), GetScrollMaxY(), ImRect::GetSize(), ImRect::GetTR(), GetViewportRect(), GetWindowBgColorIdxFromFlags(), GImGui, ImGuiDrawContext::GroupOffsetX, ImGuiDrawContext::GroupStack, ImGuiWindow::HiddenFrames, ImGuiContext::HoveredWindow, ImGuiWindow::IDStack, IM_ASSERT, IM_COL32_A_MASK, IM_COL32_A_SHIFT, IM_F32_TO_INT8_SAT, ImDrawCornerFlags_All, ImDrawCornerFlags_Bot, ImDrawCornerFlags_Top, ImDrawListFlags_AntiAliasedFill, ImDrawListFlags_AntiAliasedLines, ImFloor(), ImGuiCol_Border, ImGuiCol_MenuBarBg, ImGuiCol_ModalWindowDarkening, ImGuiCol_NavWindowingHighlight, ImGuiCol_SeparatorActive, ImGuiCol_TitleBg, ImGuiCol_TitleBgActive, ImGuiCol_TitleBgCollapsed, ImGuiCond_Appearing, ImGuiCond_FirstUseEver, ImGuiCond_Once, ImGuiConfigFlags_NavMoveMouse, ImGuiDir_Down, ImGuiDir_None, ImGuiDir_Right, ImGuiItemFlags_Default_, ImGuiItemFlags_NoNavDefaultFocus, ImGuiItemStatusFlags_HoveredRect, ImGuiLayoutType_Horizontal, ImGuiLayoutType_Vertical, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_AlwaysHorizontalScrollbar, ImGuiWindowFlags_AlwaysUseWindowPadding, ImGuiWindowFlags_AlwaysVerticalScrollbar, ImGuiWindowFlags_ChildMenu, ImGuiWindowFlags_ChildWindow, ImGuiWindowFlags_HorizontalScrollbar, ImGuiWindowFlags_MenuBar, ImGuiWindowFlags_Modal, ImGuiWindowFlags_NavFlattened, ImGuiWindowFlags_NoCollapse, ImGuiWindowFlags_NoFocusOnAppearing, ImGuiWindowFlags_NoInputs, ImGuiWindowFlags_NoMove, ImGuiWindowFlags_NoResize, ImGuiWindowFlags_NoScrollbar, ImGuiWindowFlags_NoTitleBar, ImGuiWindowFlags_Popup, ImGuiWindowFlags_ResizeFromAnySide, ImGuiWindowFlags_Tooltip, ImLengthSqr(), ImLerp(), ImMax(), ImMin(), ImGuiDrawContext::IndentX, ImGuiContext::Initialized, ImGuiResizeGripDef::InnerDir, ImGuiWindow::InnerRect, ImGuiContext::IO, IsMouseHoveringRect(), ItemAdd(), ImGuiDrawContext::ItemFlags, ImGuiDrawContext::ItemFlagsStack, ImGuiStyle::ItemInnerSpacing, ImGuiStyle::ItemSpacing, ImGuiDrawContext::ItemWidth, ImGuiWindow::ItemWidthDefault, ImGuiDrawContext::ItemWidthStack, ImGuiWindow::LastFrameActive, ImGuiDrawContext::LastItemId, ImGuiDrawContext::LastItemRect, ImGuiDrawContext::LastItemStatusFlags, ImGuiDrawContext::LayoutType, ImGuiDrawContext::LogLinePosY, MarkIniSettingsDirty(), ImRect::Max, ImGuiDrawContext::MenuBarAppending, ImGuiWindow::MenuBarHeight(), ImGuiDrawContext::MenuBarOffsetX, ImGuiWindow::MenuBarRect(), ImGuiWindow::MenuColumns, ImRect::Min, ImGuiContext::ModalWindowDarkeningRatio, ImGuiStyle::MouseCursorScale, ImGuiIO::MouseDoubleClicked, ImGuiIO::MousePos, ImGuiWindow::MoveId, setup::name, NavCalcPreferredMousePos(), ImGuiContext::NavDisableHighlight, ImGuiContext::NavDisableMouseHover, ImGuiDrawContext::NavHasScroll, ImGuiDrawContext::NavHideHighlightOneFrame, NavInitWindow(), ImGuiWindow::NavLastIds, ImGuiDrawContext::NavLayerActiveMask, ImGuiDrawContext::NavLayerActiveMaskNext, ImGuiDrawContext::NavLayerCurrent, ImGuiDrawContext::NavLayerCurrentMask, ImGuiContext::NavWindow, ImGuiContext::NavWindowingHighlightAlpha, ImGuiContext::NavWindowingTarget, ImGuiContext::NextWindowData, NULL, ImGuiPopupRef::OpenPopupPos, ImGuiContext::OpenPopupStack, ImGuiDrawContext::ParentLayoutType, ImGuiWindow::ParentWindow, ImDrawList::PathArcToFast(), ImDrawList::PathFillConvex(), ImDrawList::PathLineTo(), ImGuiStyle::PopupBorderSize, ImGuiPopupRef::PopupId, ImGuiWindow::PopupId, ImGuiStyle::PopupRounding, ImGuiWindow::Pos, ImGuiNextWindowData::PosCond, ImGuiWindow::PosFloat, ImGuiNextWindowData::PosPivotVal, ImGuiNextWindowData::PosVal, ImGuiDrawContext::PrevLineHeight, ImGuiDrawContext::PrevLineTextBaseOffset, ImVector< T >::push_back(), PushClipRect(), ImDrawList::PushTextureID(), ImGuiWindow::Rect(), RenderFrame(), RenderNavHighlight(), RenderTextClipped(), RenderTriangle(), ImVector< T >::resize(), resize_grip_def, ImGuiWindow::RootWindow, ImGuiWindow::RootWindowForNav, ImGuiWindow::RootWindowForTabbing, ImGuiWindow::RootWindowForTitleBarHighlight, ImGuiWindow::Scroll, Scrollbar(), ImGuiStyle::ScrollbarSize, ImGuiWindow::ScrollbarSizes, ImGuiWindow::ScrollbarX, ImGuiWindow::ScrollbarY, ImGuiWindow::ScrollTarget, SetCurrentWindow(), SetWindowCollapsed(), SetWindowConditionAllowFlags(), SetWindowFocus(), SetWindowPos(), ImGuiWindow::SetWindowPosAllowFlags, ImGuiWindow::SetWindowPosPivot, ImGuiWindow::SetWindowPosVal, SetWindowSize(), ImGuiWindow::SetWindowSizeAllowFlags, ImGuiWindow::Size, ImVector< T >::Size, ImGuiNextWindowData::SizeCond, ImGuiNextWindowData::SizeConstraintCond, ImGuiWindow::SizeContents, ImGuiWindow::SizeContentsExplicit, ImGuiWindow::SizeFull, ImGuiWindow::SizeFullAtLastBegin, ImGuiNextWindowData::SizeVal, ImGuiWindow::SkipItems, ImGuiDrawContext::StateStorage, ImGuiWindow::StateStorage, ImGuiContext::Style, ImFontAtlas::TexID, ImGuiDrawContext::TextWrapPos, ImGuiDrawContext::TextWrapPosStack, ImGuiWindow::TitleBarHeight(), ImGuiWindow::TitleBarRect(), ImGuiDrawContext::TreeDepth, ImGuiDrawContext::TreeDepthMayJumpToParentOnPop, ImGuiMenuColumns::Update(), UpdateManualResize(), ImGuiPopupRef::Window, ImGuiStyle::WindowBorderSize, ImGuiWindow::WindowBorderSize, ImGuiStyle::WindowPadding, ImGuiWindow::WindowPadding, ImGuiWindow::WindowRectClipped, ImGuiStyle::WindowRounding, ImGuiWindow::WindowRounding, ImGuiContext::WindowsActiveCount, ImGuiStyle::WindowTitleAlign, ImGuiWindow::WriteAccessed, ImVec2::x, and ImVec2::y.
Referenced by Begin(), BeginChildEx(), BeginCombo(), BeginMainMenuBar(), BeginPopupEx(), BeginPopupModal(), BeginTooltipEx(), ImGuiListClipper::ImGuiListClipper(), NewFrame(), ShowMetricsWindow(), and ImGuiListClipper::Step().
End()
void ImGui::End ()
References ImVector< T >::back(), CheckStacksSize(), ImGuiDrawContext::ColumnsSet, ImGuiContext::CurrentPopupStack, ImGuiContext::CurrentWindow, ImGuiContext::CurrentWindowStack, ImGuiWindow::DC, ImVector< T >::empty(), EndColumns(), ImGuiWindow::Flags, GImGui, ImGuiWindowFlags_ChildWindow, ImGuiWindowFlags_Popup, LogFinish(), NULL, ImVector< T >::pop_back(), PopClipRect(), and SetCurrentWindow().
Referenced by BeginMainMenuBar(), EndChild(), EndFrame(), EndMainMenuBar(), EndPopup(), EndTooltip(), ShowMetricsWindow(), and ImGuiListClipper::Step().
BeginChild() [1/2]
bool ImGui::BeginChild (const char * str_id, const ImVec2 & size = ImVec2(0,0), bool border = false, ImGuiWindowFlags flags = 0)
References BeginChildEx(), GetCurrentWindow(), and ImGuiWindow::GetID().
Referenced by BeginChildFrame().
BeginChild() [2/2]
bool ImGui::BeginChild (ImGuiID id, const ImVec2 & size = ImVec2(0,0), bool border = false, ImGuiWindowFlags flags = 0)
References BeginChildEx(), IM_ASSERT, and NULL.
EndChild()
void ImGui::EndChild ()
References ImGuiWindow::AutoFitChildAxises, ImGuiWindow::BeginCount, ImGuiWindow::ChildId, ImGuiContext::CurrentWindow, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, End(), ImGuiWindow::Flags, GetWindowSize(), GImGui, IM_ASSERT, ImGuiAxis_X, ImGuiAxis_Y, ImGuiNavHighlightFlags_TypeThin, ImGuiWindowFlags_ChildWindow, ImGuiWindowFlags_NavFlattened, ImMax(), ItemAdd(), ItemSize(), ImRect::Max, ImRect::Min, ImGuiDrawContext::NavHasScroll, ImGuiContext::NavId, ImGuiDrawContext::NavLayerActiveMask, ImGuiContext::NavWindow, RenderNavHighlight(), ImVec2::x, and ImVec2::y.
Referenced by EndChildFrame().
GetContentRegionMax()
ImVec2 ImGui::GetContentRegionMax ()
References ImGuiDrawContext::ColumnsSet, ImGuiWindow::ContentsRegionRect, ImGuiColumnsSet::Current, ImGuiWindow::DC, GetColumnOffset(), GetCurrentWindowRead(), ImRect::Max, ImGuiWindow::WindowPadding, and ImVec2::x.
Referenced by CalcItemSize(), CalcWrapWidthForPos(), GetContentRegionAvail(), Selectable(), and TreeNodeBehavior().
GetContentRegionAvail()
ImVec2 ImGui::GetContentRegionAvail ()
References ImGuiDrawContext::CursorPos, ImGuiWindow::DC, GetContentRegionMax(), GetCurrentWindowRead(), and ImGuiWindow::Pos.
Referenced by BeginChildEx(), BeginMenu(), CalcItemWidth(), GetContentRegionAvailWidth(), and MenuItem().
GetContentRegionAvailWidth()
float ImGui::GetContentRegionAvailWidth ()
References GetContentRegionAvail(), and ImVec2::x.
GetWindowContentRegionMin()
ImVec2 ImGui::GetWindowContentRegionMin ()
References ImGuiWindow::ContentsRegionRect, GetCurrentWindowRead(), and ImRect::Min.
GetWindowContentRegionMax()
ImVec2 ImGui::GetWindowContentRegionMax ()
References ImGuiWindow::ContentsRegionRect, GetCurrentWindowRead(), and ImRect::Max.
Referenced by Selectable().
GetWindowContentRegionWidth()
float ImGui::GetWindowContentRegionWidth ()
References ImGuiWindow::ContentsRegionRect, GetCurrentWindowRead(), ImRect::Max, ImRect::Min, and ImVec2::x.
GetWindowDrawList()
ImDrawList * ImGui::GetWindowDrawList ()
References ImGuiWindow::DrawList, and GetCurrentWindow().
Referenced by ShowMetricsWindow().
GetWindowPos()
ImVec2 ImGui::GetWindowPos ()
References ImGuiContext::CurrentWindow, GImGui, and ImGuiWindow::Pos.
GetWindowSize()
ImVec2 ImGui::GetWindowSize ()
References GetCurrentWindowRead(), and ImGuiWindow::Size.
Referenced by EndChild().
GetWindowWidth()
float ImGui::GetWindowWidth ()
References ImGuiContext::CurrentWindow, GImGui, ImGuiWindow::Size, and ImVec2::x.
GetWindowHeight()
float ImGui::GetWindowHeight ()
References ImGuiContext::CurrentWindow, GImGui, ImGuiWindow::Size, and ImVec2::y.
IsWindowCollapsed()
bool ImGui::IsWindowCollapsed ()
References ImGuiWindow::Collapsed, and GetCurrentWindowRead().
IsWindowAppearing()
bool ImGui::IsWindowAppearing ()
References ImGuiWindow::Appearing, and GetCurrentWindowRead().
SetWindowFontScale()
void ImGui::SetWindowFontScale (float scale)
References ImGuiWindow::CalcFontSize(), ImGuiContext::DrawListSharedData, ImDrawListSharedData::FontSize, ImGuiContext::FontSize, ImGuiWindow::FontWindowScale, GetCurrentWindow(), GImGui, and scale().
SetNextWindowPos()
void ImGui::SetNextWindowPos (const ImVec2 & pos, ImGuiCond cond = 0, const ImVec2 & pivot = ImVec2(0,0))
References GImGui, ImGuiCond_Always, ImGuiContext::NextWindowData, ImGuiNextWindowData::PosCond, ImGuiNextWindowData::PosPivotVal, and ImGuiNextWindowData::PosVal.
Referenced by BeginCombo(), BeginDragDropSource(), BeginMainMenuBar(), BeginMenu(), BeginPopupModal(), ColorEdit4(), and SetNextWindowPosCenter().
SetNextWindowSize()
void ImGui::SetNextWindowSize (const ImVec2 & size, ImGuiCond cond = 0)
References GImGui, ImGuiCond_Always, ImGuiContext::NextWindowData, ImGuiNextWindowData::SizeCond, and ImGuiNextWindowData::SizeVal.
Referenced by Begin(), BeginChildEx(), BeginMainMenuBar(), and NewFrame().
SetNextWindowSizeConstraints()
void ImGui::SetNextWindowSizeConstraints (const ImVec2 & size_min, const ImVec2 & size_max, ImGuiSizeCallback custom_callback = NULL, void * custom_callback_data = NULL)
References GImGui, ImGuiCond_Always, ImGuiContext::NextWindowData, ImGuiNextWindowData::SizeCallback, ImGuiNextWindowData::SizeCallbackUserData, ImGuiNextWindowData::SizeConstraintCond, and ImGuiNextWindowData::SizeConstraintRect.
Referenced by BeginCombo().
SetNextWindowContentSize()
void ImGui::SetNextWindowContentSize (const ImVec2 & size)
References ImGuiNextWindowData::ContentSizeCond, ImGuiNextWindowData::ContentSizeVal, GImGui, ImGuiCond_Always, and ImGuiContext::NextWindowData.
Referenced by SetNextWindowContentWidth().
SetNextWindowCollapsed()
void ImGui::SetNextWindowCollapsed (bool collapsed, ImGuiCond cond = 0)
References ImGuiNextWindowData::CollapsedCond, ImGuiNextWindowData::CollapsedVal, GImGui, ImGuiCond_Always, and ImGuiContext::NextWindowData.
SetNextWindowFocus()
void ImGui::SetNextWindowFocus ()
References ImGuiNextWindowData::FocusCond, GImGui, ImGuiCond_Always, and ImGuiContext::NextWindowData.
SetNextWindowBgAlpha()
void ImGui::SetNextWindowBgAlpha (float alpha)
References ImGuiNextWindowData::BgAlphaCond, ImGuiNextWindowData::BgAlphaVal, GImGui, ImGuiCond_Always, and ImGuiContext::NextWindowData.
Referenced by Begin().
SetWindowPos() [1/2]
void ImGui::SetWindowPos (const ImVec2 & pos, ImGuiCond cond = 0)
References GetCurrentWindowRead(), and SetWindowPos().
SetWindowSize() [1/2]
void ImGui::SetWindowSize (const ImVec2 & size, ImGuiCond cond = 0)
References ImGuiContext::CurrentWindow, GImGui, and SetWindowSize().
SetWindowCollapsed() [1/2]
void ImGui::SetWindowCollapsed (bool collapsed, ImGuiCond cond = 0)
References ImGuiContext::CurrentWindow, GImGui, and SetWindowCollapsed().
SetWindowFocus() [1/2]
void ImGui::SetWindowFocus ()
References ImGuiContext::CurrentWindow, FocusWindow(), and GImGui.
Referenced by Begin().
SetWindowPos() [2/2]
void ImGui::SetWindowPos (const char * name, const ImVec2 & pos, ImGuiCond cond = 0)
References FindWindowByName(), setup::name, and SetWindowPos().
SetWindowSize() [2/2]
void ImGui::SetWindowSize (const char * name, const ImVec2 & size, ImGuiCond cond = 0)
References FindWindowByName(), setup::name, and SetWindowSize().
SetWindowCollapsed() [2/2]
void ImGui::SetWindowCollapsed (const char * name, bool collapsed, ImGuiCond cond = 0)
References FindWindowByName(), setup::name, and SetWindowCollapsed().
SetWindowFocus() [2/2]
void ImGui::SetWindowFocus (const char * name)
References FindWindowByName(), FocusWindow(), setup::name, and NULL.
GetScrollX()
float ImGui::GetScrollX ()
References ImGuiContext::CurrentWindow, GImGui, ImGuiWindow::Scroll, and ImVec2::x.
GetScrollY()
float ImGui::GetScrollY ()
References ImGuiContext::CurrentWindow, GImGui, ImGuiWindow::Scroll, and ImVec2::y.
GetScrollMaxX()
float ImGui::GetScrollMaxX ()
References ImGuiContext::CurrentWindow, GetScrollMaxX(), and GImGui.
GetScrollMaxY()
float ImGui::GetScrollMaxY ()
References ImGuiContext::CurrentWindow, GetScrollMaxY(), and GImGui.
SetScrollX()
void ImGui::SetScrollX (float scroll_x)
References GetCurrentWindow(), ImGuiWindow::ScrollTarget, ImGuiWindow::ScrollTargetCenterRatio, and ImVec2::x.
SetScrollY()
void ImGui::SetScrollY (float scroll_y)
References GetCurrentWindow(), ImGuiWindow::MenuBarHeight(), ImGuiWindow::ScrollTarget, ImGuiWindow::ScrollTargetCenterRatio, ImGuiWindow::TitleBarHeight(), and ImVec2::y.
SetScrollHere()
void ImGui::SetScrollHere (float center_y_ratio = 0.5f)
References ImGuiDrawContext::CursorPosPrevLine, ImGuiWindow::DC, GetCurrentWindow(), GImGui, ImGuiStyle::ItemSpacing, ImGuiWindow::Pos, ImGuiDrawContext::PrevLineHeight, SetScrollFromPosY(), ImGuiContext::Style, and ImVec2::y.
Referenced by SetItemDefaultFocus().
SetScrollFromPosY()
void ImGui::SetScrollFromPosY (float pos_y, float center_y_ratio = 0.5f)
References GetCurrentWindow(), GImGui, IM_ASSERT, ImGuiStyle::ItemSpacing, ImGuiWindow::Scroll, ImGuiWindow::ScrollTarget, ImGuiWindow::ScrollTargetCenterRatio, ImGuiWindow::SizeContents, ImGuiContext::Style, ImGuiWindow::WindowPadding, and ImVec2::y.
Referenced by SetScrollHere().
SetStateStorage()
void ImGui::SetStateStorage (ImGuiStorage * tree)
References ImGuiWindow::DC, GetCurrentWindow(), ImGuiDrawContext::StateStorage, and ImGuiWindow::StateStorage.
GetStateStorage()
ImGuiStorage * ImGui::GetStateStorage ()
References ImGuiWindow::DC, GetCurrentWindowRead(), and ImGuiDrawContext::StateStorage.
PushFont()
void ImGui::PushFont (ImFont * font)
References ImFont::ContainerAtlas, ImGuiContext::CurrentWindow, ImGuiWindow::DrawList, ImGuiContext::FontStack, GetDefaultFont(), GImGui, ImVector< T >::push_back(), ImDrawList::PushTextureID(), SetCurrentFont(), and ImFontAtlas::TexID.
Referenced by InputTextEx().
PopFont()
void ImGui::PopFont ()
References ImVector< T >::back(), ImGuiContext::CurrentWindow, ImGuiWindow::DrawList, ImVector< T >::empty(), ImGuiContext::FontStack, GetDefaultFont(), GImGui, ImVector< T >::pop_back(), ImDrawList::PopTextureID(), and SetCurrentFont().
Referenced by InputTextEx().
PushStyleColor() [1/2]
void ImGui::PushStyleColor (ImGuiCol idx, ImU32 col)
References ImGuiColMod::BackupValue, ImGuiColMod::Col, ColorConvertU32ToFloat4(), ImGuiContext::ColorModifiers, ImGuiStyle::Colors, GImGui, ImVector< T >::push_back(), and ImGuiContext::Style.
Referenced by BeginChildFrame(), BeginDragDropSource(), BeginMenu(), MenuItem(), Selectable(), TextColoredV(), and TextDisabledV().
PushStyleColor() [2/2]
void ImGui::PushStyleColor (ImGuiCol idx, const ImVec4 & col)
References ImGuiColMod::BackupValue, ImGuiColMod::Col, ImGuiContext::ColorModifiers, ImGuiStyle::Colors, GImGui, ImVector< T >::push_back(), and ImGuiContext::Style.
PopStyleColor()
void ImGui::PopStyleColor (int count = 1)
References ImVector< T >::back(), ImGuiColMod::BackupValue, ImGuiColMod::Col, ImGuiContext::ColorModifiers, ImGuiStyle::Colors, GImGui, ImVector< T >::pop_back(), and ImGuiContext::Style.
Referenced by BeginMenu(), EndChildFrame(), EndDragDropSource(), MenuItem(), Selectable(), TextColoredV(), and TextDisabledV().
PushStyleVar() [1/2]
void ImGui::PushStyleVar (ImGuiStyleVar idx, float val)
References GetStyleVarInfo(), ImGuiStyleVarInfo::GetVarPtr(), GImGui, IM_ASSERT, ImGuiDataType_Float, ImVector< T >::push_back(), ImGuiContext::Style, ImGuiContext::StyleModifiers, and ImGuiStyleVarInfo::Type.
Referenced by BeginChildFrame(), BeginMainMenuBar(), BeginMenu(), and MenuItem().
PushStyleVar() [2/2]
void ImGui::PushStyleVar (ImGuiStyleVar idx, const ImVec2 & val)
References GetStyleVarInfo(), ImGuiStyleVarInfo::GetVarPtr(), GImGui, IM_ASSERT, ImGuiDataType_Float2, ImVector< T >::push_back(), ImGuiContext::Style, ImGuiContext::StyleModifiers, and ImGuiStyleVarInfo::Type.
PopStyleVar()
void ImGui::PopStyleVar (int count = 1)
References ImVector< T >::back(), ImGuiStyleMod::BackupFloat, ImGuiStyleMod::BackupInt, GetStyleVarInfo(), ImGuiStyleVarInfo::GetVarPtr(), GImGui, ImGuiDataType_Float, ImGuiDataType_Float2, ImGuiDataType_Int, ImVector< T >::pop_back(), ImGuiContext::Style, ImGuiContext::StyleModifiers, ImGuiStyleVarInfo::Type, and ImGuiStyleMod::VarIdx.
Referenced by BeginMainMenuBar(), BeginMenu(), EndChildFrame(), EndMainMenuBar(), and MenuItem().
GetStyleColorVec4()
const ImVec4 & ImGui::GetStyleColorVec4 (ImGuiCol idx)
References ImGuiStyle::Colors, GImGui, and ImGuiContext::Style.
Referenced by BeginDragDropSource().
GetFont()
ImFont * ImGui::GetFont ()
References ImGuiContext::Font, and GImGui.
GetFontSize()
float ImGui::GetFontSize ()
References ImGuiContext::FontSize, and GImGui.
GetFontTexUvWhitePixel()
ImVec2 ImGui::GetFontTexUvWhitePixel ()
References ImGuiContext::DrawListSharedData, GImGui, and ImDrawListSharedData::TexUvWhitePixel.
Referenced by ColorPicker4().
GetColorU32() [1/3]
ImU32 ImGui::GetColorU32 (ImGuiCol idx, float alpha_mul = 1.0f)
References ImGuiStyle::Alpha, ColorConvertFloat4ToU32(), ImGuiStyle::Colors, GImGui, ImGuiContext::Style, and ImVec4::w.
Referenced by AcceptDragDropPayload(), ArrowButton(), Begin(), BeginCombo(), ButtonEx(), Checkbox(), CloseButton(), ColorButton(), DragBehavior(), EndColumns(), Image(), ImageButton(), InputTextEx(), MenuItem(), PlotEx(), ProgressBar(), RadioButton(), RenderBullet(), RenderColorRectWithAlphaCheckerboard(), RenderFrame(), RenderFrameBorder(), RenderNavHighlight(), RenderText(), RenderTextClipped(), RenderTextWrapped(), RenderTriangle(), Scrollbar(), Selectable(), Separator(), SliderBehavior(), SplitterBehavior(), TreeNodeBehavior(), UpdateManualResize(), and VerticalSeparator().
GetColorU32() [2/3]
ImU32 ImGui::GetColorU32 (const ImVec4 & col)
References ImGuiStyle::Alpha, ColorConvertFloat4ToU32(), GImGui, ImGuiContext::Style, and ImVec4::w.
GetColorU32() [3/3]
ImU32 ImGui::GetColorU32 (ImU32 col)
References a, ImGuiStyle::Alpha, GImGui, IM_COL32_A_MASK, IM_COL32_A_SHIFT, and ImGuiContext::Style.
PushItemWidth()
void ImGui::PushItemWidth (float item_width)
References ImGuiWindow::DC, GetCurrentWindow(), ImGuiDrawContext::ItemWidth, ImGuiWindow::ItemWidthDefault, ImGuiDrawContext::ItemWidthStack, and ImVector< T >::push_back().
Referenced by BeginColumns(), ColorEdit4(), ColorPicker4(), ColorPickerOptionsPopup(), ImGuiTextFilter::Draw(), InputScalarEx(), LogButtons(), and NextColumn().
PopItemWidth()
void ImGui::PopItemWidth ()
References ImVector< T >::back(), ImGuiWindow::DC, ImVector< T >::empty(), GetCurrentWindow(), ImGuiDrawContext::ItemWidth, ImGuiWindow::ItemWidthDefault, ImGuiDrawContext::ItemWidthStack, and ImVector< T >::pop_back().
Referenced by ColorEdit4(), ColorPicker4(), ColorPickerOptionsPopup(), DragFloatN(), DragFloatRange2(), DragIntN(), DragIntRange2(), ImGuiTextFilter::Draw(), EndColumns(), InputFloatN(), InputIntN(), InputScalarEx(), LogButtons(), NextColumn(), SliderFloatN(), and SliderIntN().
CalcItemWidth()
float ImGui::CalcItemWidth ()
References ImGuiWindow::DC, GetContentRegionAvail(), GetCurrentWindowRead(), ImMax(), ImGuiDrawContext::ItemWidth, and ImVec2::x.
Referenced by BeginCombo(), ColorEdit4(), ColorPicker4(), DragFloat(), InputScalarEx(), InputTextEx(), LabelTextV(), ListBoxHeader(), PlotEx(), ProgressBar(), PushMultiItemsWidths(), and SliderFloat().
PushTextWrapPos()
void ImGui::PushTextWrapPos (float wrap_pos_x = 0.0f)
References ImGuiWindow::DC, GetCurrentWindow(), ImVector< T >::push_back(), ImGuiDrawContext::TextWrapPos, and ImGuiDrawContext::TextWrapPosStack.
Referenced by TextWrappedV().
PopTextWrapPos()
void ImGui::PopTextWrapPos ()
References ImVector< T >::back(), ImGuiWindow::DC, ImVector< T >::empty(), GetCurrentWindow(), ImVector< T >::pop_back(), ImGuiDrawContext::TextWrapPos, and ImGuiDrawContext::TextWrapPosStack.
Referenced by TextWrappedV().
PushAllowKeyboardFocus()
void ImGui::PushAllowKeyboardFocus (bool allow_keyboard_focus)
References ImGuiItemFlags_AllowKeyboardFocus, and PushItemFlag().
Referenced by LogButtons().
PopAllowKeyboardFocus()
void ImGui::PopAllowKeyboardFocus ()
References PopItemFlag().
Referenced by LogButtons().
PushButtonRepeat()
void ImGui::PushButtonRepeat (bool repeat)
References ImGuiItemFlags_ButtonRepeat, and PushItemFlag().
PopButtonRepeat()
void ImGui::PopButtonRepeat ()
References PopItemFlag().
Separator()
void ImGui::Separator ()
References ImDrawList::AddLine(), ImGuiColumnsSet::CellMinY, ImGuiDrawContext::ColumnsSet, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, ImGuiWindow::DrawList, ImVector< T >::empty(), GetColorU32(), GetCurrentWindow(), GImGui, ImGuiDrawContext::GroupStack, IM_ASSERT, IM_NEWLINE, ImGuiCol_Separator, ImGuiLayoutType_Horizontal, ImGuiSeparatorFlags_Horizontal, ImGuiSeparatorFlags_Vertical, ImIsPowerOfTwo(), ImGuiDrawContext::IndentX, ItemAdd(), ItemSize(), ImGuiDrawContext::LayoutType, ImGuiContext::LogEnabled, LogRenderedText(), NULL, PopClipRect(), ImGuiWindow::Pos, PushColumnClipRect(), ImGuiWindow::Size, ImGuiWindow::SkipItems, VerticalSeparator(), ImVec2::x, and ImVec2::y.
Referenced by ColorEdit4(), ColorEditOptionsPopup(), ColorPickerOptionsPopup(), ColorTooltip(), and ShowMetricsWindow().
SameLine()
void ImGui::SameLine (float pos_x = 0.0f, float spacing_w = -1.0f)
References ImGuiDrawContext::ColumnsOffsetX, ImGuiDrawContext::CurrentLineHeight, ImGuiDrawContext::CurrentLineTextBaseOffset, ImGuiDrawContext::CursorPos, ImGuiDrawContext::CursorPosPrevLine, ImGuiWindow::DC, GetCurrentWindow(), GImGui, ImGuiDrawContext::GroupOffsetX, ImGuiStyle::ItemSpacing, ImGuiWindow::Pos, ImGuiDrawContext::PrevLineHeight, ImGuiDrawContext::PrevLineTextBaseOffset, ImGuiWindow::Scroll, ImGuiWindow::SkipItems, ImGuiContext::Style, ImVec2::x, and ImVec2::y.
Referenced by Bullet(), Checkbox(), ColorButton(), ColorEdit4(), ColorPicker4(), ColorTooltip(), DragFloatN(), DragFloatRange2(), DragIntN(), DragIntRange2(), InputFloatN(), InputIntN(), InputScalarEx(), ItemSize(), ListBoxFooter(), LogButtons(), RadioButton(), ShowMetricsWindow(), SliderFloatN(), and SliderIntN().
NewLine()
void ImGui::NewLine ()
References ImGuiDrawContext::CurrentLineHeight, ImGuiWindow::DC, ImGuiContext::FontSize, GetCurrentWindow(), GImGui, ImGuiLayoutType_Vertical, ItemSize(), ImGuiDrawContext::LayoutType, and ImGuiWindow::SkipItems.
Spacing()
void ImGui::Spacing ()
References GetCurrentWindow(), ItemSize(), and ImGuiWindow::SkipItems.
Referenced by ImGuiMenuColumns::DeclColumns(), ImGuiMenuColumns::ImGuiMenuColumns(), and ImGuiMenuColumns::Update().
Dummy()
void ImGui::Dummy (const ImVec2 & size)
References ImGuiDrawContext::CursorPos, ImGuiWindow::DC, GetCurrentWindow(), ItemAdd(), ItemSize(), and ImGuiWindow::SkipItems.
Referenced by InputTextEx().
Indent()
void ImGui::Indent (float indent_w = 0.0f)
References ImGuiDrawContext::ColumnsOffsetX, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, GetCurrentWindow(), GImGui, ImGuiStyle::IndentSpacing, ImGuiDrawContext::IndentX, ImGuiWindow::Pos, ImGuiContext::Style, and ImVec2::x.
Referenced by BeginCombo(), TreePush(), and TreePushRawID().
Unindent()
void ImGui::Unindent (float indent_w = 0.0f)
References ImGuiDrawContext::ColumnsOffsetX, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, GetCurrentWindow(), GImGui, ImGuiStyle::IndentSpacing, ImGuiDrawContext::IndentX, ImGuiWindow::Pos, ImGuiContext::Style, and ImVec2::x.
Referenced by EndCombo(), and TreePop().
BeginGroup()
void ImGui::BeginGroup ()
References ImGuiContext::ActiveIdIsAlive, ImGuiGroupData::AdvanceCursor, ImVector< T >::back(), ImGuiGroupData::BackupActiveIdIsAlive, ImGuiGroupData::BackupCurrentLineHeight, ImGuiGroupData::BackupCurrentLineTextBaseOffset, ImGuiGroupData::BackupCursorMaxPos, ImGuiGroupData::BackupCursorPos, ImGuiGroupData::BackupGroupOffsetX, ImGuiGroupData::BackupIndentX, ImGuiGroupData::BackupLogLinePosY, ImGuiDrawContext::ColumnsOffsetX, ImGuiDrawContext::CurrentLineHeight, ImGuiDrawContext::CurrentLineTextBaseOffset, ImGuiDrawContext::CursorMaxPos, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, GetCurrentWindow(), GImGui, ImGuiDrawContext::GroupOffsetX, ImGuiDrawContext::GroupStack, ImGuiDrawContext::IndentX, ImGuiDrawContext::LogLinePosY, ImGuiWindow::Pos, ImVector< T >::resize(), ImVector< T >::Size, ImVec2::x, and ImVec2::y.
Referenced by BeginMenuBar(), ColorEdit4(), ColorPicker4(), DragFloatN(), DragFloatRange2(), DragIntN(), DragIntRange2(), InputFloatN(), InputIntN(), InputScalarEx(), InputTextEx(), ListBoxHeader(), SliderFloatN(), and SliderIntN().
EndGroup()
void ImGui::EndGroup ()
References ImGuiContext::ActiveId, ImGuiContext::ActiveIdIsAlive, ImGuiContext::ActiveIdWindow, ImVector< T >::back(), ImGuiDrawContext::CurrentLineHeight, ImGuiDrawContext::CurrentLineTextBaseOffset, ImGuiDrawContext::CursorMaxPos, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, ImVector< T >::empty(), GetCurrentWindow(), ImRect::GetSize(), GImGui, ImGuiDrawContext::GroupOffsetX, ImGuiDrawContext::GroupStack, IM_ASSERT, ImMax(), ImGuiDrawContext::IndentX, ItemAdd(), ItemSize(), ImGuiDrawContext::LastItemId, ImGuiDrawContext::LastItemRect, ImGuiDrawContext::LogLinePosY, ImRect::Max, ImRect::Min, ImVector< T >::pop_back(), ImGuiDrawContext::PrevLineTextBaseOffset, ImGuiWindow::RootWindow, and ImVec2::y.
Referenced by ColorEdit4(), ColorPicker4(), DragFloatN(), DragFloatRange2(), DragIntN(), DragIntRange2(), EndMenuBar(), InputFloatN(), InputIntN(), InputScalarEx(), InputTextEx(), ListBoxFooter(), SliderFloatN(), and SliderIntN().
GetCursorPos()
ImVec2 ImGui::GetCursorPos ()
References ImGuiDrawContext::CursorPos, ImGuiWindow::DC, GetCurrentWindowRead(), ImGuiWindow::Pos, and ImGuiWindow::Scroll.
Referenced by _glfwPlatformGetCursorPos(), and cursorInClientArea().
GetCursorPosX()
float ImGui::GetCursorPosX ()
References ImGuiDrawContext::CursorPos, ImGuiWindow::DC, GetCurrentWindowRead(), ImGuiWindow::Pos, ImGuiWindow::Scroll, and ImVec2::x.
GetCursorPosY()
float ImGui::GetCursorPosY ()
References ImGuiDrawContext::CursorPos, ImGuiWindow::DC, GetCurrentWindowRead(), ImGuiWindow::Pos, ImGuiWindow::Scroll, and ImVec2::y.
Referenced by ImGuiListClipper::Begin(), and ImGuiListClipper::Step().
SetCursorPos()
void ImGui::SetCursorPos (const ImVec2 & local_pos)
References ImGuiDrawContext::CursorMaxPos, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, GetCurrentWindow(), ImMax(), ImGuiWindow::Pos, and ImGuiWindow::Scroll.
Referenced by _glfwPlatformSetCursorPos().
SetCursorPosX()
void ImGui::SetCursorPosX (float x)
References ImGuiDrawContext::CursorMaxPos, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, GetCurrentWindow(), ImMax(), ImGuiWindow::Pos, ImGuiWindow::Scroll, and ImVec2::x.
SetCursorPosY()
void ImGui::SetCursorPosY (float y)
References ImGuiDrawContext::CursorMaxPos, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, GetCurrentWindow(), ImMax(), ImGuiWindow::Pos, ImGuiWindow::Scroll, and ImVec2::y.
Referenced by SetCursorPosYAndSetupDummyPrevLine().
GetCursorStartPos()
ImVec2 ImGui::GetCursorStartPos ()
References ImGuiDrawContext::CursorStartPos, ImGuiWindow::DC, GetCurrentWindowRead(), and ImGuiWindow::Pos.
GetCursorScreenPos()
ImVec2 ImGui::GetCursorScreenPos ()
References ImGuiDrawContext::CursorPos, ImGuiWindow::DC, and GetCurrentWindowRead().
Referenced by ColorPickerOptionsPopup().
SetCursorScreenPos()
void ImGui::SetCursorScreenPos (const ImVec2 & pos)
References ImGuiDrawContext::CursorMaxPos, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, GetCurrentWindow(), and ImMax().
Referenced by ColorPicker4(), and ColorPickerOptionsPopup().
AlignTextToFramePadding()
void ImGui::AlignTextToFramePadding ()
References ImGuiDrawContext::CurrentLineHeight, ImGuiDrawContext::CurrentLineTextBaseOffset, ImGuiWindow::DC, ImGuiContext::FontSize, ImGuiStyle::FramePadding, GetCurrentWindow(), GImGui, ImMax(), ImGuiWindow::SkipItems, ImGuiContext::Style, and ImVec2::y.
Referenced by AlignFirstTextHeightToWidgets(), and BeginMenuBar().
GetTextLineHeight()
float ImGui::GetTextLineHeight ()
References ImGuiContext::FontSize, and GImGui.
Referenced by InputTextEx(), and TextUnformatted().
GetTextLineHeightWithSpacing()
float ImGui::GetTextLineHeightWithSpacing ()
References ImGuiContext::FontSize, GImGui, ImGuiStyle::ItemSpacing, ImGuiContext::Style, and ImVec2::y.
Referenced by ListBoxHeader().
GetFrameHeight()
float ImGui::GetFrameHeight ()
References ImGuiContext::FontSize, ImGuiStyle::FramePadding, GImGui, ImGuiContext::Style, and ImVec2::y.
Referenced by BeginCombo(), ColorButton(), ColorEdit4(), ColorPicker4(), ColorPickerOptionsPopup(), and InputScalarEx().
GetFrameHeightWithSpacing()
float ImGui::GetFrameHeightWithSpacing ()
References ImGuiContext::FontSize, ImGuiStyle::FramePadding, GImGui, ImGuiStyle::ItemSpacing, ImGuiContext::Style, and ImVec2::y.
Referenced by GetItemsLineHeightWithSpacing().
Columns()
void ImGui::Columns (int count = 1, const char * id = NULL, bool border = true)
References BeginColumns(), ImGuiDrawContext::ColumnsSet, ImGuiColumnsSet::Count, ImGuiWindow::DC, EndColumns(), GetCurrentWindow(), IM_ASSERT, ImGuiColumnsFlags_NoBorder, and NULL.
Referenced by GetColumnOffset(), and SetColumnOffset().
NextColumn()
void ImGui::NextColumn ()
References ImGuiColumnsSet::CellMaxY, ImGuiColumnsSet::CellMinY, ImDrawList::ChannelsSetCurrent(), ImGuiDrawContext::ColumnsOffsetX, ImGuiDrawContext::ColumnsSet, ImGuiColumnsSet::Count, ImGuiColumnsSet::Current, ImGuiDrawContext::CurrentLineHeight, ImGuiDrawContext::CurrentLineTextBaseOffset, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, ImGuiWindow::DrawList, GetColumnOffset(), GetColumnWidth(), GetCurrentWindow(), GImGui, ImMax(), ImGuiDrawContext::IndentX, ImGuiStyle::ItemSpacing, NULL, PopClipRect(), PopItemWidth(), ImGuiWindow::Pos, PushColumnClipRect(), PushItemWidth(), ImGuiWindow::SkipItems, ImGuiContext::Style, ImVec2::x, and ImVec2::y.
GetColumnIndex()
int ImGui::GetColumnIndex ()
References ImGuiDrawContext::ColumnsSet, ImGuiColumnsSet::Current, ImGuiWindow::DC, and GetCurrentWindowRead().
GetColumnWidth()
float ImGui::GetColumnWidth (int column_index = -1)
References ImGuiColumnsSet::Columns, ImGuiDrawContext::ColumnsSet, ImGuiColumnsSet::Current, ImGuiWindow::DC, GetCurrentWindowRead(), IM_ASSERT, NULL, and OffsetNormToPixels().
Referenced by BeginColumns(), and NextColumn().
SetColumnWidth()
void ImGui::SetColumnWidth (int column_index, float width)
References ImGuiDrawContext::ColumnsSet, ImGuiColumnsSet::Current, ImGuiWindow::DC, GetColumnOffset(), GetCurrentWindowRead(), IM_ASSERT, NULL, SetColumnOffset(), and width.
GetColumnOffset()
float ImGui::GetColumnOffset (int column_index = -1)
References Columns(), ImGuiColumnsSet::Columns, ImGuiDrawContext::ColumnsSet, ImGuiColumnsSet::Current, ImGuiWindow::DC, GetCurrentWindowRead(), IM_ASSERT, ImLerp(), ImGuiColumnsSet::MaxX, ImGuiColumnsSet::MinX, and NULL.
Referenced by BeginColumns(), EndColumns(), GetContentRegionMax(), GetDraggedColumnOffset(), NextColumn(), and SetColumnWidth().
SetColumnOffset()
void ImGui::SetColumnOffset (int column_index, float offset_x)
References Columns(), ImGuiColumnsSet::Columns, ImGuiStyle::ColumnsMinSpacing, ImGuiDrawContext::ColumnsSet, ImGuiColumnsSet::Count, ImGuiColumnsSet::Current, ImGuiContext::CurrentWindow, ImGuiWindow::DC, ImGuiColumnsSet::Flags, GetColumnWidthEx(), GImGui, IM_ASSERT, ImGuiColumnsFlags_NoForceWithinWindow, ImGuiColumnsFlags_NoPreserveWidths, ImMax(), ImMin(), ImGuiColumnsSet::IsBeingResized, ImGuiColumnsSet::MaxX, ImGuiColumnsSet::MinX, NULL, PixelsToOffsetNorm(), ImGuiContext::Style, and width.
Referenced by EndColumns(), and SetColumnWidth().
GetColumnsCount()
int ImGui::GetColumnsCount ()
References ImGuiDrawContext::ColumnsSet, ImGuiColumnsSet::Count, ImGuiWindow::DC, and GetCurrentWindowRead().
PushID() [1/4]
void ImGui::PushID (const char * str_id)
References GetCurrentWindowRead(), ImGuiWindow::GetID(), ImGuiWindow::IDStack, and ImVector< T >::push_back().
Referenced by BeginColumns(), BeginMenuBar(), ColorEdit4(), ColorPicker4(), ColorPickerOptionsPopup(), DragFloatN(), DragFloatRange2(), DragIntN(), DragIntRange2(), ImageButton(), InputFloatN(), InputIntN(), InputScalarEx(), LogButtons(), SliderFloatN(), SliderIntN(), TreePush(), and UpdateManualResize().
PushID() [2/4]
void ImGui::PushID (const char * str_id_begin, const char * str_id_end)
References GetCurrentWindowRead(), ImGuiWindow::GetID(), ImGuiWindow::IDStack, and ImVector< T >::push_back().
PushID() [3/4]
void ImGui::PushID (const void * ptr_id)
References GetCurrentWindowRead(), ImGuiWindow::GetID(), ImGuiWindow::IDStack, and ImVector< T >::push_back().
PushID() [4/4]
void ImGui::PushID (int int_id)
References GetCurrentWindowRead(), ImGuiWindow::GetID(), ImGuiWindow::IDStack, and ImVector< T >::push_back().
PopID()
void ImGui::PopID ()
References GetCurrentWindowRead(), ImGuiWindow::IDStack, and ImVector< T >::pop_back().
Referenced by BeginColumns(), ColorEdit4(), ColorPicker4(), ColorPickerOptionsPopup(), DragFloatN(), DragFloatRange2(), DragIntN(), DragIntRange2(), EndMenuBar(), ImageButton(), InputFloatN(), InputIntN(), InputScalarEx(), LogButtons(), SliderFloatN(), SliderIntN(), TreePop(), and UpdateManualResize().
GetID() [1/3]
ImGuiID ImGui::GetID (const char * str_id)
References ImGuiContext::CurrentWindow, ImGuiWindow::GetID(), and GImGui.
Referenced by ImGuiWindow::ImGuiWindow(), and ListBoxHeader().
GetID() [2/3]
ImGuiID ImGui::GetID (const char * str_id_begin, const char * str_id_end)
References ImGuiContext::CurrentWindow, ImGuiWindow::GetID(), and GImGui.
GetID() [3/3]
ImGuiID ImGui::GetID (const void * ptr_id)
References ImGuiContext::CurrentWindow, ImGuiWindow::GetID(), and GImGui.
TextUnformatted()
void ImGui::TextUnformatted (const char * text, const char * text_end = NULL)
References CalcTextSize(), CalcWrapWidthForPos(), ImGuiWindow::ClipRect, ImGuiDrawContext::CurrentLineTextBaseOffset, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, FLT_MAX, GetCurrentWindow(), GetTextLineHeight(), GImGui, IM_ASSERT, ImMax(), IsClippedEx(), ItemAdd(), ItemSize(), ImGuiContext::LogEnabled, ImRect::Max, ImRect::Min, NULL, RenderText(), RenderTextWrapped(), ImGuiWindow::SkipItems, ImGuiDrawContext::TextWrapPos, ImVec2::x, and ImVec2::y.
Referenced by ColorButton(), ColorEdit4(), ColorPicker4(), ColorTooltip(), DragFloatN(), DragFloatRange2(), DragIntN(), DragIntRange2(), InputFloatN(), InputIntN(), SliderFloatN(), SliderIntN(), and TextV().
Text()
void ImGui::Text (const char * fmt, ...)
References TextV().
Referenced by ColorPicker4(), ColorTooltip(), ShowMetricsWindow(), and Value().
TextV()
void ImGui::TextV (const char * fmt, va_list args)
References GetCurrentWindow(), GImGui, IM_ARRAYSIZE, ImFormatStringV(), ImGuiWindow::SkipItems, ImGuiContext::TempBuffer, and TextUnformatted().
Referenced by SetTooltipV(), Text(), TextColoredV(), TextDisabledV(), and TextWrappedV().
TextColored()
void ImGui::TextColored (const ImVec4 & col, const char * fmt, ...)
References TextColoredV().
Referenced by ShowMetricsWindow().
TextColoredV()
void ImGui::TextColoredV (const ImVec4 & col, const char * fmt, va_list args)
References ImGuiCol_Text, PopStyleColor(), PushStyleColor(), and TextV().
Referenced by TextColored().
TextDisabled()
void ImGui::TextDisabled (const char * fmt, ...)
References TextDisabledV().
TextDisabledV()
void ImGui::TextDisabledV (const char * fmt, va_list args)
References ImGuiStyle::Colors, GImGui, ImGuiCol_Text, ImGuiCol_TextDisabled, PopStyleColor(), PushStyleColor(), ImGuiContext::Style, and TextV().
Referenced by TextDisabled().
TextWrapped()
void ImGui::TextWrapped (const char * fmt, ...)
References TextWrappedV().
TextWrappedV()
void ImGui::TextWrappedV (const char * fmt, va_list args)
References ImGuiContext::CurrentWindow, ImGuiWindow::DC, GImGui, PopTextWrapPos(), PushTextWrapPos(), TextV(), and ImGuiDrawContext::TextWrapPos.
Referenced by TextWrapped().
LabelText()
void ImGui::LabelText (const char * label, const char * fmt, ...)
References LabelTextV().
LabelTextV()
void ImGui::LabelTextV (const char * label, const char * fmt, va_list args)
References CalcItemWidth(), CalcTextSize(), ImGuiDrawContext::CursorPos, ImGuiWindow::DC, ImGuiStyle::FramePadding, GetCurrentWindow(), GImGui, IM_ARRAYSIZE, ImFormatStringV(), ItemAdd(), ImGuiStyle::ItemInnerSpacing, ItemSize(), ImRect::Max, ImRect::Min, NULL, RenderText(), RenderTextClipped(), ImGuiWindow::SkipItems, ImGuiContext::Style, ImGuiContext::TempBuffer, ImVec2::x, and ImVec2::y.
Referenced by LabelText().
BulletText()
void ImGui::BulletText (const char * fmt, ...)
References BulletTextV().
Referenced by ShowMetricsWindow().
BulletTextV()
void ImGui::BulletTextV (const char * fmt, va_list args)
References CalcTextSize(), ImGuiDrawContext::CurrentLineHeight, ImGuiDrawContext::CurrentLineTextBaseOffset, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, ImGuiContext::FontSize, ImGuiStyle::FramePadding, GetCurrentWindow(), GImGui, IM_ARRAYSIZE, ImFormatStringV(), ImMax(), ImMin(), ItemAdd(), ItemSize(), ImRect::Min, RenderBullet(), RenderText(), ImGuiWindow::SkipItems, ImGuiContext::Style, ImGuiContext::TempBuffer, ImVec2::x, and ImVec2::y.
Referenced by BulletText().
Bullet()
void ImGui::Bullet ()
References ImGuiDrawContext::CurrentLineHeight, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, ImGuiContext::FontSize, ImGuiStyle::FramePadding, GetCurrentWindow(), GImGui, ImMax(), ImMin(), ItemAdd(), ItemSize(), ImRect::Min, RenderBullet(), SameLine(), ImGuiWindow::SkipItems, ImGuiContext::Style, ImVec2::x, and ImVec2::y.
Button()
bool ImGui::Button (const char * label, const ImVec2 & size = ImVec2(0,0))
References ButtonEx().
Referenced by ColorEditOptionsPopup(), and LogButtons().
SmallButton()
bool ImGui::SmallButton (const char * label)
References ButtonEx(), ImGuiStyle::FramePadding, GImGui, ImGuiButtonFlags_AlignTextBaseLine, ImGuiContext::Style, and ImVec2::y.
InvisibleButton()
bool ImGui::InvisibleButton (const char * str_id, const ImVec2 & size)
References ButtonBehavior(), CalcItemSize(), ImGuiDrawContext::CursorPos, ImGuiWindow::DC, GetCurrentWindow(), ImGuiWindow::GetID(), ItemAdd(), ItemSize(), and ImGuiWindow::SkipItems.
Referenced by ColorPicker4().
Image()
void ImGui::Image (ImTextureID user_texture_id, const ImVec2 & size, const ImVec2 & uv0 = ImVec2(0,0), const ImVec2 & uv1 = ImVec2(1,1), const ImVec4 & tint_col = ImVec4(1,1,1,1), const ImVec4 & border_col = ImVec4(0,0,0,0))
References ImDrawList::AddImage(), ImDrawList::AddRect(), ImGuiDrawContext::CursorPos, ImGuiWindow::DC, ImGuiWindow::DrawList, GetColorU32(), GetCurrentWindow(), ItemAdd(), ItemSize(), ImRect::Max, ImRect::Min, ImGuiWindow::SkipItems, and ImVec4::w.
Referenced by spirv_cross::CompilerGLSL::check_function_call_constraints(), spirv_cross::CompilerGLSL::emit_instruction(), spirv_cross::CompilerGLSL::emit_resources(), spirv_cross::CompilerGLSL::emit_uniform(), spirv_cross::CompilerGLSL::fixup_image_load_store_access(), spirv_cross::CompilerGLSL::flags_to_precision_qualifiers_glsl(), spirv_cross::CompilerGLSL::image_type_glsl(), spirv_cross::CompilerGLSL::layout_for_variable(), spirv_cross::Compiler::parse(), spirv_cross::CompilerGLSL::skip_argument(), spirv_cross::CompilerGLSL::to_function_args(), and spirv_cross::CompilerGLSL::type_to_glsl().
ImageButton()
bool ImGui::ImageButton (ImTextureID user_texture_id, const ImVec2 & size, const ImVec2 & uv0 = ImVec2(0,0), const ImVec2 & uv1 = ImVec2(1,1), int frame_padding = -1, const ImVec4 & bg_col = ImVec4(0,0,0,0), const ImVec4 & tint_col = ImVec4(1,1,1,1))
References ImDrawList::AddImage(), ImDrawList::AddRectFilled(), ButtonBehavior(), ImGuiDrawContext::CursorPos, ImGuiWindow::DC, ImGuiWindow::DrawList, ImGuiStyle::FramePadding, ImGuiStyle::FrameRounding, GetColorU32(), GetCurrentWindow(), ImGuiWindow::GetID(), GImGui, ImClamp(), ImGuiCol_Button, ImGuiCol_ButtonActive, ImGuiCol_ButtonHovered, ImMin(), ItemAdd(), ItemSize(), ImRect::Max, ImRect::Min, PopID(), PushID(), RenderFrame(), RenderNavHighlight(), ImGuiWindow::SkipItems, ImGuiContext::Style, ImVec4::w, ImVec2::x, and ImVec2::y.
Checkbox()
bool ImGui::Checkbox (const char * label, bool * v)
References ButtonBehavior(), CalcTextSize(), ImGuiDrawContext::CursorPos, ImGuiWindow::DC, ImGuiStyle::FramePadding, ImGuiStyle::FrameRounding, GetColorU32(), GetCurrentWindow(), ImRect::GetHeight(), ImGuiWindow::GetID(), ImRect::GetWidth(), GImGui, ImGuiCol_CheckMark, ImGuiCol_FrameBg, ImGuiCol_FrameBgActive, ImGuiCol_FrameBgHovered, ImMax(), ImMin(), ItemAdd(), ImGuiStyle::ItemInnerSpacing, ItemSize(), ImGuiContext::LogEnabled, LogRenderedText(), ImRect::Max, ImRect::Min, NULL, RenderCheckMark(), RenderFrame(), RenderNavHighlight(), RenderText(), SameLine(), ImGuiWindow::SkipItems, ImGuiContext::Style, ImVec2::x, and ImVec2::y.
Referenced by CheckboxFlags(), and ShowMetricsWindow().
CheckboxFlags()
bool ImGui::CheckboxFlags (const char * label, unsigned int * flags, unsigned int flags_value)
References Checkbox().
Referenced by ColorPickerOptionsPopup().
RadioButton() [1/2]
bool ImGui::RadioButton (const char * label, bool active)
References ImRect::Add(), ImDrawList::AddCircle(), ImDrawList::AddCircleFilled(), ButtonBehavior(), CalcTextSize(), ImGuiDrawContext::CursorPos, ImGuiWindow::DC, ImGuiWindow::DrawList, ImGuiStyle::FrameBorderSize, ImGuiStyle::FramePadding, ImRect::GetCenter(), GetColorU32(), GetCurrentWindow(), ImRect::GetHeight(), ImGuiWindow::GetID(), ImRect::GetWidth(), GImGui, ImGuiCol_Border, ImGuiCol_BorderShadow, ImGuiCol_CheckMark, ImGuiCol_FrameBg, ImGuiCol_FrameBgActive, ImGuiCol_FrameBgHovered, ImMax(), ImMin(), ItemAdd(), ImGuiStyle::ItemInnerSpacing, ItemSize(), ImGuiContext::LogEnabled, LogRenderedText(), ImRect::Min, NULL, RenderNavHighlight(), RenderText(), SameLine(), ImGuiWindow::SkipItems, ImGuiContext::Style, ImVec2::x, and ImVec2::y.
Referenced by ColorEditOptionsPopup(), and RadioButton().
RadioButton() [2/2]
bool ImGui::RadioButton (const char * label, int * v, int v_button)
References RadioButton().
PlotLines() [1/2]
void ImGui::PlotLines (const char * label, const float * values, int values_count, int values_offset = 0, const char * overlay_text = NULL, float scale_min = FLT_MAX, float scale_max = FLT_MAX, ImVec2 graph_size = ImVec2(0,0), int stride = sizeof(float))
References ImGuiPlotType_Lines, Plot_ArrayGetter(), and PlotEx().
PlotLines() [2/2]
void ImGui::PlotLines (const char * label, float(*)(void *data, int idx) values_getter, void * data, int values_count, int values_offset = 0, const char * overlay_text = NULL, float scale_min = FLT_MAX, float scale_max = FLT_MAX, ImVec2 graph_size = ImVec2(0,0))
References ImGuiPlotType_Lines, and PlotEx().
PlotHistogram() [1/2]
void ImGui::PlotHistogram (const char * label, const float * values, int values_count, int values_offset = 0, const char * overlay_text = NULL, float scale_min = FLT_MAX, float scale_max = FLT_MAX, ImVec2 graph_size = ImVec2(0,0), int stride = sizeof(float))
References ImGuiPlotType_Histogram, Plot_ArrayGetter(), and PlotEx().
PlotHistogram() [2/2]
void ImGui::PlotHistogram (const char * label, float(*)(void *data, int idx) values_getter, void * data, int values_count, int values_offset = 0, const char * overlay_text = NULL, float scale_min = FLT_MAX, float scale_max = FLT_MAX, ImVec2 graph_size = ImVec2(0,0))
References ImGuiPlotType_Histogram, and PlotEx().
ProgressBar()
void ImGui::ProgressBar (float fraction, const ImVec2 & size_arg = ImVec2(-1,0), const char * overlay = NULL)
References CalcItemSize(), CalcItemWidth(), CalcTextSize(), ImGuiDrawContext::CursorPos, ImGuiWindow::DC, ImGuiWindow::DrawList, ImRect::Expand(), ImGuiContext::FontSize, ImGuiStyle::FrameBorderSize, ImGuiStyle::FramePadding, ImGuiStyle::FrameRounding, GetColorU32(), GetCurrentWindow(), GImGui, IM_ARRAYSIZE, ImClamp(), ImFormatString(), ImGuiCol_FrameBg, ImGuiCol_PlotHistogram, ImLerp(), ImSaturate(), ItemAdd(), ImGuiStyle::ItemInnerSpacing, ItemSize(), ImGuiStyle::ItemSpacing, ImRect::Max, ImRect::Min, NULL, RenderFrame(), RenderRectFilledRangeH(), RenderTextClipped(), ImGuiWindow::SkipItems, ImGuiContext::Style, ImVec2::x, and ImVec2::y.
BeginCombo()
bool ImGui::BeginCombo (const char * label, const char * preview_value, ImGuiComboFlags flags = 0)
References Begin(), ButtonBehavior(), CalcItemWidth(), CalcMaxPopupHeightFromItemCount(), CalcSizeAfterConstraint(), CalcSizeAutoFit(), CalcSizeContents(), CalcTextSize(), ImGuiContext::CurrentPopupStack, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, EndPopup(), FindBestWindowPosForPopup(), FindWindowByName(), FLT_MAX, ImGuiStyle::FramePadding, ImGuiStyle::FrameRounding, ImRect::GetBL(), GetColorU32(), GetCurrentWindow(), GetFrameHeight(), ImGuiWindow::GetID(), GImGui, IM_ARRAYSIZE, IM_ASSERT, ImFormatString(), ImGuiCol_Button, ImGuiCol_ButtonHovered, ImGuiCol_FrameBg, ImGuiComboFlags_HeightLarge, ImGuiComboFlags_HeightMask_, ImGuiComboFlags_HeightRegular, ImGuiComboFlags_HeightSmall, ImGuiComboFlags_PopupAlignLeft, ImGuiDir_Down, ImGuiDir_Left, ImGuiPopupPositionPolicy_ComboBox, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoResize, ImGuiWindowFlags_NoSavedSettings, ImGuiWindowFlags_NoTitleBar, ImGuiWindowFlags_Popup, ImIsPowerOfTwo(), ImMax(), Indent(), IsPopupOpen(), ItemAdd(), ImGuiStyle::ItemInnerSpacing, ItemSize(), ImRect::Max, ImRect::Min, setup::name, ImGuiContext::NavActivateId, ImGuiWindow::NavLastIds, ImGuiDrawContext::NavLayerCurrent, ImGuiContext::NextWindowData, NULL, OpenPopupEx(), RenderFrame(), RenderNavHighlight(), RenderText(), RenderTextClipped(), RenderTriangle(), SetNextWindowPos(), SetNextWindowSizeConstraints(), ImVector< T >::Size, ImGuiNextWindowData::SizeConstraintCond, ImGuiNextWindowData::SizeConstraintRect, ImGuiWindow::SkipItems, ImGuiContext::Style, ImGuiStyle::WindowPadding, ImVec2::x, and ImVec2::y.
EndCombo()
void ImGui::EndCombo ()
References EndPopup(), ImGuiStyle::FramePadding, GImGui, ImGuiContext::Style, Unindent(), ImGuiStyle::WindowPadding, and ImVec2::x.
Combo() [1/3]
bool ImGui::Combo (const char * label, int * current_item, const char *const items[], int items_count, int popup_max_height_in_items = -1)
References Items_ArrayGetter().
Referenced by Combo().
Combo() [2/3]
bool ImGui::Combo (const char * label, int * current_item, const char * items_separated_by_zeros, int popup_max_height_in_items = -1)
References Combo(), and Items_SingleStringGetter().
Combo() [3/3]
IMGUI_API bool ImGui::Combo (const char * label, int * current_item, bool(*)(void *data, int idx, const char **out_text) items_getter, void * data, int items_count, int popup_max_height_in_items = -1)
DragFloat()
bool ImGui::DragFloat (const char * label, float * v, float v_speed = 1.0f, float v_min = 0.0f, float v_max = 0.0f, const char * display_format = "%.3f", float power = 1.0f)
References ImGuiContext::ActiveId, ImGuiContext::ActiveIdAllowNavDirFlags, CalcItemWidth(), CalcTextSize(), ImGuiDrawContext::CursorPos, ImGuiWindow::DC, DragBehavior(), FocusableItemRegister(), FocusWindow(), ImGuiStyle::FramePadding, GetCurrentWindow(), ImGuiWindow::GetID(), GImGui, IM_ARRAYSIZE, ImFormatString(), ImGuiDataType_Float, ImGuiDir_Down, ImGuiDir_Up, InputScalarAsWidgetReplacement(), ImGuiContext::IO, ItemAdd(), ItemHoverable(), ImGuiStyle::ItemInnerSpacing, ItemSize(), ImGuiIO::KeyCtrl, ImRect::Max, ImRect::Min, ImGuiIO::MouseClicked, ImGuiIO::MouseDoubleClicked, ImGuiContext::NavActivateId, ImGuiContext::NavInputId, NULL, ParseFormatPrecision(), RenderText(), RenderTextClipped(), ImGuiContext::ScalarAsInputTextId, SetActiveID(), SetFocusID(), ImGuiWindow::SkipItems, ImGuiContext::Style, ImVec2::x, and ImVec2::y.
Referenced by ColorEdit4(), DragFloatN(), DragFloatRange2(), and DragInt().
DragFloat2()
bool ImGui::DragFloat2 (const char * label, float v[2], float v_speed = 1.0f, float v_min = 0.0f, float v_max = 0.0f, const char * display_format = "%.3f", float power = 1.0f)
References DragFloatN().
DragFloat3()
bool ImGui::DragFloat3 (const char * label, float v[3], float v_speed = 1.0f, float v_min = 0.0f, float v_max = 0.0f, const char * display_format = "%.3f", float power = 1.0f)
References DragFloatN().
DragFloat4()
bool ImGui::DragFloat4 (const char * label, float v[4], float v_speed = 1.0f, float v_min = 0.0f, float v_max = 0.0f, const char * display_format = "%.3f", float power = 1.0f)
References DragFloatN().
DragFloatRange2()
bool ImGui::DragFloatRange2 (const char * label, float * v_current_min, float * v_current_max, float v_speed = 1.0f, float v_min = 0.0f, float v_max = 0.0f, const char * display_format = "%.3f", const char * display_format_max = NULL, float power = 1.0f)
References BeginGroup(), DragFloat(), EndGroup(), FindRenderedTextEnd(), FLT_MAX, GetCurrentWindow(), GImGui, ImMax(), ImMin(), ImGuiStyle::ItemInnerSpacing, PopID(), PopItemWidth(), PushID(), PushMultiItemsWidths(), SameLine(), ImGuiWindow::SkipItems, ImGuiContext::Style, TextUnformatted(), and ImVec2::x.
DragInt()
bool ImGui::DragInt (const char * label, int * v, float v_speed = 1.0f, int v_min = 0, int v_max = 0, const char * display_format = "%.0f")
References DragFloat().
Referenced by ColorEdit4(), DragIntN(), and DragIntRange2().
DragInt2()
bool ImGui::DragInt2 (const char * label, int v[2], float v_speed = 1.0f, int v_min = 0, int v_max = 0, const char * display_format = "%.0f")
References DragIntN().
DragInt3()
bool ImGui::DragInt3 (const char * label, int v[3], float v_speed = 1.0f, int v_min = 0, int v_max = 0, const char * display_format = "%.0f")
References DragIntN().
DragInt4()
bool ImGui::DragInt4 (const char * label, int v[4], float v_speed = 1.0f, int v_min = 0, int v_max = 0, const char * display_format = "%.0f")
References DragIntN().
DragIntRange2()
bool ImGui::DragIntRange2 (const char * label, int * v_current_min, int * v_current_max, float v_speed = 1.0f, int v_min = 0, int v_max = 0, const char * display_format = "%.0f", const char * display_format_max = NULL)
References BeginGroup(), DragInt(), EndGroup(), FindRenderedTextEnd(), GetCurrentWindow(), GImGui, ImMax(), ImMin(), ImGuiStyle::ItemInnerSpacing, PopID(), PopItemWidth(), PushID(), PushMultiItemsWidths(), SameLine(), ImGuiWindow::SkipItems, ImGuiContext::Style, TextUnformatted(), and ImVec2::x.
InputText()
bool ImGui::InputText (const char * label, char * buf, size_t buf_size, ImGuiInputTextFlags flags = 0, ImGuiTextEditCallback callback = NULL, void * user_data = NULL)
References IM_ASSERT, ImGuiInputTextFlags_Multiline, and InputTextEx().
Referenced by ColorEdit4(), ImGuiTextFilter::Draw(), and InputScalarEx().
InputTextMultiline()
bool ImGui::InputTextMultiline (const char * label, char * buf, size_t buf_size, const ImVec2 & size = ImVec2(0,0), ImGuiInputTextFlags flags = 0, ImGuiTextEditCallback callback = NULL, void * user_data = NULL)
References ImGuiInputTextFlags_Multiline, and InputTextEx().
InputFloat()
bool ImGui::InputFloat (const char * label, float * v, float step = 0.0f, float step_fast = 0.0f, int decimal_precision = -1, ImGuiInputTextFlags extra_flags = 0)
References IM_ARRAYSIZE, ImFormatString(), ImGuiDataType_Float, InputScalarEx(), and NULL.
Referenced by InputFloatN().
InputFloat2()
bool ImGui::InputFloat2 (const char * label, float v[2], int decimal_precision = -1, ImGuiInputTextFlags extra_flags = 0)
References InputFloatN().
InputFloat3()
bool ImGui::InputFloat3 (const char * label, float v[3], int decimal_precision = -1, ImGuiInputTextFlags extra_flags = 0)
References InputFloatN().
InputFloat4()
bool ImGui::InputFloat4 (const char * label, float v[4], int decimal_precision = -1, ImGuiInputTextFlags extra_flags = 0)
References InputFloatN().
InputInt()
bool ImGui::InputInt (const char * label, int * v, int step = 1, int step_fast = 100, ImGuiInputTextFlags extra_flags = 0)
References ImGuiDataType_Int, ImGuiInputTextFlags_CharsHexadecimal, InputScalarEx(), and NULL.
Referenced by InputIntN().
InputInt2()
bool ImGui::InputInt2 (const char * label, int v[2], ImGuiInputTextFlags extra_flags = 0)
References InputIntN().
InputInt3()
bool ImGui::InputInt3 (const char * label, int v[3], ImGuiInputTextFlags extra_flags = 0)
References InputIntN().
InputInt4()
bool ImGui::InputInt4 (const char * label, int v[4], ImGuiInputTextFlags extra_flags = 0)
References InputIntN().
SliderFloat()
bool ImGui::SliderFloat (const char * label, float * v, float v_min, float v_max, const char * display_format = "%.3f", float power = 1.0f)
References ImGuiContext::ActiveId, ImGuiContext::ActiveIdAllowNavDirFlags, CalcItemWidth(), CalcTextSize(), ImGuiDrawContext::CursorPos, ImGuiWindow::DC, FocusableItemRegister(), FocusWindow(), ImGuiStyle::FramePadding, GetCurrentWindow(), ImGuiWindow::GetID(), GImGui, IM_ARRAYSIZE, ImFormatString(), ImGuiDataType_Float, ImGuiDir_Down, ImGuiDir_Up, InputScalarAsWidgetReplacement(), ImGuiContext::IO, ItemAdd(), ItemHoverable(), ImGuiStyle::ItemInnerSpacing, ItemSize(), ImGuiIO::KeyCtrl, ImRect::Max, ImRect::Min, ImGuiIO::MouseClicked, ImGuiContext::NavActivateId, ImGuiContext::NavInputId, NULL, ParseFormatPrecision(), RenderText(), RenderTextClipped(), ImGuiContext::ScalarAsInputTextId, SetActiveID(), SetFocusID(), ImGuiWindow::SkipItems, SliderBehavior(), ImGuiContext::Style, ImVec2::x, and ImVec2::y.
Referenced by SliderAngle(), SliderFloatN(), and SliderInt().
SliderFloat2()
bool ImGui::SliderFloat2 (const char * label, float v[2], float v_min, float v_max, const char * display_format = "%.3f", float power = 1.0f)
References SliderFloatN().
SliderFloat3()
bool ImGui::SliderFloat3 (const char * label, float v[3], float v_min, float v_max, const char * display_format = "%.3f", float power = 1.0f)
References SliderFloatN().
SliderFloat4()
bool ImGui::SliderFloat4 (const char * label, float v[4], float v_min, float v_max, const char * display_format = "%.3f", float power = 1.0f)
References SliderFloatN().
SliderAngle()
bool ImGui::SliderAngle (const char * label, float * v_rad, float v_degrees_min = -360.0f, float v_degrees_max = +360.0f)
References IM_PI, and SliderFloat().
SliderInt()
bool ImGui::SliderInt (const char * label, int * v, int v_min, int v_max, const char * display_format = "%.0f")
References SliderFloat().
Referenced by LogButtons(), and SliderIntN().
SliderInt2()
bool ImGui::SliderInt2 (const char * label, int v[2], int v_min, int v_max, const char * display_format = "%.0f")
References SliderIntN().
SliderInt3()
bool ImGui::SliderInt3 (const char * label, int v[3], int v_min, int v_max, const char * display_format = "%.0f")
References SliderIntN().
SliderInt4()
bool ImGui::SliderInt4 (const char * label, int v[4], int v_min, int v_max, const char * display_format = "%.0f")
References SliderIntN().
VSliderFloat()
bool ImGui::VSliderFloat (const char * label, const ImVec2 & size, float * v, float v_min, float v_max, const char * display_format = "%.3f", float power = 1.0f)
References ImGuiContext::ActiveIdAllowNavDirFlags, CalcTextSize(), ImGuiDrawContext::CursorPos, ImGuiWindow::DC, FocusWindow(), ImGuiStyle::FramePadding, GetCurrentWindow(), ImGuiWindow::GetID(), GImGui, IM_ARRAYSIZE, ImFormatString(), ImGuiDir_Left, ImGuiDir_Right, ImGuiSliderFlags_Vertical, ImGuiContext::IO, ItemAdd(), ItemHoverable(), ImGuiStyle::ItemInnerSpacing, ItemSize(), ImRect::Max, ImRect::Min, ImGuiIO::MouseClicked, ImGuiContext::NavActivateId, ImGuiContext::NavInputId, NULL, ParseFormatPrecision(), RenderText(), RenderTextClipped(), SetActiveID(), SetFocusID(), ImGuiWindow::SkipItems, SliderBehavior(), ImGuiContext::Style, ImVec2::x, and ImVec2::y.
Referenced by VSliderInt().
VSliderInt()
bool ImGui::VSliderInt (const char * label, const ImVec2 & size, int * v, int v_min, int v_max, const char * display_format = "%.0f")
References VSliderFloat().
ColorEdit3()
bool ImGui::ColorEdit3 (const char * label, float col[3], ImGuiColorEditFlags flags = 0)
References ColorEdit4(), and ImGuiColorEditFlags_NoAlpha.
ColorEdit4()
bool ImGui::ColorEdit4 (const char * label, float col[4], ImGuiColorEditFlags flags = 0)
References AcceptDragDropPayload(), ImGuiContext::ActiveId, ImGuiContext::ActiveIdWindow, BeginDragDropTarget(), BeginGroup(), BeginPopup(), CalcItemWidth(), CalcTextSize(), ColorButton(), ColorConvertHSVtoRGB(), ColorConvertRGBtoHSV(), ImGuiContext::ColorEditOptions, ColorEditOptionsPopup(), ColorPicker4(), ImGuiContext::ColorPickerRef, ImGuiContext::CurrentWindow, ImGuiWindow::DC, DragFloat(), DragInt(), EndDragDropTarget(), EndGroup(), EndPopup(), FindRenderedTextEnd(), ImRect::GetBL(), GetCurrentWindow(), GetFrameHeight(), GImGui, IM_ARRAYSIZE, IM_F32_TO_INT8_UNBOUND, ImCharIsSpace(), ImClamp(), ImFormatString(), IMGUI_PAYLOAD_TYPE_COLOR_3F, IMGUI_PAYLOAD_TYPE_COLOR_4F, ImGuiColorEditFlags__DataTypeMask, ImGuiColorEditFlags__InputsMask, ImGuiColorEditFlags__PickerMask, ImGuiColorEditFlags_AlphaBar, ImGuiColorEditFlags_AlphaPreviewHalf, ImGuiColorEditFlags_Float, ImGuiColorEditFlags_HDR, ImGuiColorEditFlags_HEX, ImGuiColorEditFlags_HSV, ImGuiColorEditFlags_NoAlpha, ImGuiColorEditFlags_NoInputs, ImGuiColorEditFlags_NoLabel, ImGuiColorEditFlags_NoOptions, ImGuiColorEditFlags_NoPicker, ImGuiColorEditFlags_NoSmallPreview, ImGuiColorEditFlags_RGB, ImGuiInputTextFlags_CharsHexadecimal, ImGuiInputTextFlags_CharsUppercase, ImGuiItemStatusFlags_HoveredRect, ImMax(), InputText(), ImGuiStyle::ItemInnerSpacing, ImGuiStyle::ItemSpacing, ImGuiDrawContext::LastItemId, ImGuiDrawContext::LastItemRect, ImGuiDrawContext::LastItemStatusFlags, memcpy(), NULL, OpenPopup(), OpenPopupOnItemClick(), PopID(), PopItemWidth(), PushID(), PushItemWidth(), SameLine(), Separator(), SetNextWindowPos(), ImGuiWindow::SkipItems, ImGuiContext::Style, TextUnformatted(), ImVec2::x, ImVec4::x, and ImVec2::y.
Referenced by ColorEdit3(), and ColorPicker4().
ColorPicker3()
bool ImGui::ColorPicker3 (const char * label, float col[3], ImGuiColorEditFlags flags = 0)
References ColorPicker4(), and ImGuiColorEditFlags_NoAlpha.
ColorPicker4()
bool ImGui::ColorPicker4 (const char * label, float col[4], ImGuiColorEditFlags flags = 0, const float * ref_col = NULL)
References ImDrawList::AddCircle(), ImDrawList::AddCircleFilled(), ImDrawList::AddRectFilledMultiColor(), ImDrawList::AddTriangle(), BeginGroup(), CalcItemWidth(), ColorButton(), ColorConvertFloat4ToU32(), ColorConvertHSVtoRGB(), ColorConvertRGBtoHSV(), ColorEdit4(), ImGuiContext::ColorEditOptions, ColorPickerOptionsPopup(), ImGuiDrawContext::CursorPos, ImVector< T >::Data, ImGuiWindow::DC, ImGuiWindow::DrawList, EndGroup(), FindRenderedTextEnd(), GetCurrentWindow(), GetFontTexUvWhitePixel(), GetFrameHeight(), ImRect::GetWidth(), GImGui, IM_ASSERT, IM_COL32, IM_COL32_A_MASK, IM_COL32_BLACK, IM_COL32_BLACK_TRANS, IM_COL32_WHITE, IM_PI, ImClamp(), ImGuiColorEditFlags__DataTypeMask, ImGuiColorEditFlags__InputsMask, ImGuiColorEditFlags__OptionsDefault, ImGuiColorEditFlags__PickerMask, ImGuiColorEditFlags_AlphaBar, ImGuiColorEditFlags_AlphaPreview, ImGuiColorEditFlags_AlphaPreviewHalf, ImGuiColorEditFlags_HDR, ImGuiColorEditFlags_HEX, ImGuiColorEditFlags_HSV, ImGuiColorEditFlags_NoAlpha, ImGuiColorEditFlags_NoInputs, ImGuiColorEditFlags_NoLabel, ImGuiColorEditFlags_NoOptions, ImGuiColorEditFlags_NoPicker, ImGuiColorEditFlags_NoSidePreview, ImGuiColorEditFlags_NoSmallPreview, ImGuiColorEditFlags_NoTooltip, ImGuiColorEditFlags_PickerHueBar, ImGuiColorEditFlags_PickerHueWheel, ImGuiColorEditFlags_RGB, ImGuiItemFlags_NoNav, ImGuiItemFlags_NoNavDefaultFocus, ImIsPowerOfTwo(), ImLengthSqr(), ImLerp(), ImMax(), ImRotate(), ImSaturate(), ImTriangleBarycentricCoords(), ImTriangleClosestPoint(), ImTriangleContainsPoint(), InvisibleButton(), ImGuiContext::IO, IsItemActive(), ImGuiStyle::ItemInnerSpacing, ImRect::Max, memcmp(), memcpy(), ImRect::Min, ImGuiIO::MouseClickedPos, ImGuiIO::MousePos, NULL, OpenPopupOnItemClick(), ImDrawList::PathArcTo(), ImDrawList::PathStroke(), PopID(), PopItemFlag(), PopItemWidth(), ImDrawList::PrimReserve(), ImDrawList::PrimVtx(), PushID(), PushItemFlag(), PushItemWidth(), RenderArrowsForVerticalBar(), RenderColorRectWithAlphaCheckerboard(), RenderFrameBorder(), SameLine(), SetCursorScreenPos(), ShadeVertsLinearColorGradientKeepAlpha(), ImVector< T >::Size, ImGuiContext::Style, Text(), TextUnformatted(), ImDrawList::VtxBuffer, ImVec2::x, ImVec4::x, ImVec2::y, ImVec4::y, and ImVec4::z.
Referenced by ColorEdit4(), ColorPicker3(), and ColorPickerOptionsPopup().
ColorButton()
bool ImGui::ColorButton (const char * desc_id, const ImVec4 & col, ImGuiColorEditFlags flags = 0, ImVec2 size = ImVec2(0,0))
References ImGuiContext::ActiveId, ImDrawList::AddRect(), ImDrawList::AddRectFilled(), BeginDragDropSource(), ButtonBehavior(), ColorTooltip(), ImGuiDrawContext::CursorPos, ImGuiWindow::DC, ImGuiWindow::DrawList, EndDragDropSource(), ImRect::Expand(), ImGuiStyle::FrameBorderSize, ImGuiStyle::FramePadding, ImGuiStyle::FrameRounding, GetColorU32(), GetCurrentWindow(), GetFrameHeight(), ImGuiWindow::GetID(), GImGui, ImDrawCornerFlags_All, ImDrawCornerFlags_BotLeft, ImDrawCornerFlags_BotRight, ImDrawCornerFlags_TopLeft, ImDrawCornerFlags_TopRight, IMGUI_PAYLOAD_TYPE_COLOR_3F, IMGUI_PAYLOAD_TYPE_COLOR_4F, ImGuiCol_FrameBg, ImGuiColorEditFlags_AlphaPreview, ImGuiColorEditFlags_AlphaPreviewHalf, ImGuiColorEditFlags_NoAlpha, ImGuiColorEditFlags_NoTooltip, ImGuiCond_Once, ImMin(), ItemAdd(), ItemSize(), ImRect::Max, ImRect::Min, RenderColorRectWithAlphaCheckerboard(), RenderFrameBorder(), RenderNavHighlight(), SameLine(), SetDragDropPayload(), ImGuiWindow::SkipItems, ImGuiContext::Style, TextUnformatted(), ImVec4::w, ImVec2::x, ImVec4::x, ImVec2::y, ImVec4::y, and ImVec4::z.
Referenced by ColorEdit4(), ColorPicker4(), and ColorTooltip().
SetColorEditOptions()
void ImGui::SetColorEditOptions (ImGuiColorEditFlags flags)
References ImGuiContext::ColorEditOptions, GImGui, IM_ASSERT, ImGuiColorEditFlags__DataTypeMask, ImGuiColorEditFlags__InputsMask, ImGuiColorEditFlags__OptionsDefault, ImGuiColorEditFlags__PickerMask, and ImIsPowerOfTwo().
TreeNode() [1/3]
bool ImGui::TreeNode (const char * label)
References GetCurrentWindow(), ImGuiWindow::GetID(), NULL, ImGuiWindow::SkipItems, and TreeNodeBehavior().
Referenced by ShowMetricsWindow().
TreeNode() [2/3]
bool ImGui::TreeNode (const char * str_id, const char * fmt, ...)
References TreeNodeExV().
TreeNode() [3/3]
bool ImGui::TreeNode (const void * ptr_id, const char * fmt, ...)
References TreeNodeExV().
TreeNodeV() [1/2]
bool ImGui::TreeNodeV (const char * str_id, const char * fmt, va_list args)
References TreeNodeExV().
TreeNodeV() [2/2]
bool ImGui::TreeNodeV (const void * ptr_id, const char * fmt, va_list args)
References TreeNodeExV().
TreeNodeEx() [1/3]
bool ImGui::TreeNodeEx (const char * label, ImGuiTreeNodeFlags flags = 0)
References GetCurrentWindow(), ImGuiWindow::GetID(), NULL, ImGuiWindow::SkipItems, and TreeNodeBehavior().
TreeNodeEx() [2/3]
bool ImGui::TreeNodeEx (const char * str_id, ImGuiTreeNodeFlags flags, const char * fmt, ...)
References TreeNodeExV().
TreeNodeEx() [3/3]
bool ImGui::TreeNodeEx (const void * ptr_id, ImGuiTreeNodeFlags flags, const char * fmt, ...)
References TreeNodeExV().
TreeNodeExV() [1/2]
bool ImGui::TreeNodeExV (const char * str_id, ImGuiTreeNodeFlags flags, const char * fmt, va_list args)
References GetCurrentWindow(), ImGuiWindow::GetID(), GImGui, IM_ARRAYSIZE, ImFormatStringV(), ImGuiWindow::SkipItems, ImGuiContext::TempBuffer, and TreeNodeBehavior().
Referenced by TreeNode(), TreeNodeEx(), and TreeNodeV().
TreeNodeExV() [2/2]
bool ImGui::TreeNodeExV (const void * ptr_id, ImGuiTreeNodeFlags flags, const char * fmt, va_list args)
References GetCurrentWindow(), ImGuiWindow::GetID(), GImGui, IM_ARRAYSIZE, ImFormatStringV(), ImGuiWindow::SkipItems, ImGuiContext::TempBuffer, and TreeNodeBehavior().
TreePush() [1/2]
void ImGui::TreePush (const char * str_id)
References ImGuiWindow::DC, GetCurrentWindow(), Indent(), PushID(), and ImGuiDrawContext::TreeDepth.
TreePush() [2/2]
void ImGui::TreePush (const void * ptr_id = NULL)
References ImGuiWindow::DC, GetCurrentWindow(), Indent(), PushID(), and ImGuiDrawContext::TreeDepth.
TreePop()
void ImGui::TreePop ()
References ImVector< T >::back(), ImGuiContext::CurrentWindow, ImGuiWindow::DC, GImGui, ImGuiWindow::IDStack, ImGuiDir_Left, ImGuiContext::NavIdIsAlive, ImGuiContext::NavLayer, ImGuiContext::NavMoveDir, NavMoveRequestButNoResultYet(), NavMoveRequestCancel(), ImGuiContext::NavWindow, PopID(), SetNavID(), ImGuiDrawContext::TreeDepth, ImGuiDrawContext::TreeDepthMayJumpToParentOnPop, and Unindent().
Referenced by ShowMetricsWindow().
TreeAdvanceToLabelPos()
void ImGui::TreeAdvanceToLabelPos ()
References ImGuiContext::CurrentWindow, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, GetTreeNodeToLabelSpacing(), GImGui, and ImVec2::x.
GetTreeNodeToLabelSpacing()
float ImGui::GetTreeNodeToLabelSpacing ()
References ImGuiContext::FontSize, ImGuiStyle::FramePadding, GImGui, ImGuiContext::Style, and ImVec2::x.
Referenced by TreeAdvanceToLabelPos().
SetNextTreeNodeOpen()
void ImGui::SetNextTreeNodeOpen (bool is_open, ImGuiCond cond = 0)
References ImGuiContext::CurrentWindow, GImGui, ImGuiCond_Always, ImGuiContext::NextTreeNodeOpenCond, ImGuiContext::NextTreeNodeOpenVal, and ImGuiWindow::SkipItems.
CollapsingHeader() [1/3]
bool ImGui::CollapsingHeader (const char * label, ImGuiTreeNodeFlags flags = 0)
References GetCurrentWindow(), ImGuiWindow::GetID(), ImGuiTreeNodeFlags_CollapsingHeader, ImGuiTreeNodeFlags_NoTreePushOnOpen, ImGuiWindow::SkipItems, and TreeNodeBehavior().
Referenced by CollapsingHeader().
CollapsingHeader() [2/3]
bool ImGui::CollapsingHeader (const char * label, bool * p_open, ImGuiTreeNodeFlags flags = 0)
References ImGuiWindow::ClipRect, CloseButton(), ImGuiWindow::DC, ImGuiContext::FontSize, ImGuiStyle::FramePadding, GetCurrentWindow(), ImGuiWindow::GetID(), GImGui, ImGuiTreeNodeFlags_AllowItemOverlap, ImGuiTreeNodeFlags_CollapsingHeader, ImGuiTreeNodeFlags_NoTreePushOnOpen, ImMin(), ImGuiDrawContext::LastItemRect, ImRect::Max, ImRect::Min, ImGuiItemHoveredDataBackup::Restore(), ImGuiWindow::SkipItems, ImGuiContext::Style, TreeNodeBehavior(), ImVec2::x, and ImVec2::y.
Selectable() [1/2]
bool ImGui::Selectable (const char * label, bool selected = false, ImGuiSelectableFlags flags = 0, const ImVec2 & size = ImVec2(0,0))
References ButtonBehavior(), CalcTextSize(), CloseCurrentPopup(), ImGuiStyle::Colors, ImGuiDrawContext::ColumnsSet, ImGuiDrawContext::CurrentLineTextBaseOffset, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, ImGuiWindow::Flags, GetColorU32(), GetContentRegionMax(), GetCurrentWindow(), ImGuiWindow::GetID(), GetWindowContentRegionMax(), GImGui, ImGuiButtonFlags_Disabled, ImGuiButtonFlags_NoHoldingActiveID, ImGuiButtonFlags_PressedOnClick, ImGuiButtonFlags_PressedOnClickRelease, ImGuiButtonFlags_PressedOnDoubleClick, ImGuiButtonFlags_PressedOnRelease, ImGuiCol_Header, ImGuiCol_HeaderActive, ImGuiCol_HeaderHovered, ImGuiCol_Text, ImGuiCol_TextDisabled, ImGuiItemFlags_SelectableDontClosePopup, ImGuiNavHighlightFlags_NoRounding, ImGuiNavHighlightFlags_TypeThin, ImGuiSelectableFlags_AllowDoubleClick, ImGuiSelectableFlags_Disabled, ImGuiSelectableFlags_DontClosePopups, ImGuiSelectableFlags_DrawFillAvailWidth, ImGuiSelectableFlags_Menu, ImGuiSelectableFlags_MenuItem, ImGuiSelectableFlags_SpanAllColumns, ImGuiWindowFlags_Popup, ImMax(), ItemAdd(), ImGuiDrawContext::ItemFlags, ItemSize(), ImGuiStyle::ItemSpacing, ImRect::Max, ImRect::Min, ImGuiContext::NavDisableHighlight, ImGuiContext::NavDisableMouseHover, ImGuiContext::NavLayer, ImGuiDrawContext::NavLayerActiveMask, ImGuiDrawContext::NavLayerCurrent, ImGuiContext::NavWindow, NULL, PopClipRect(), PopStyleColor(), ImGuiWindow::Pos, PushColumnClipRect(), PushStyleColor(), RenderFrame(), RenderNavHighlight(), RenderTextClipped(), SetNavID(), ImGuiWindow::SkipItems, ImGuiContext::Style, ImGuiWindow::WindowPadding, ImVec2::x, and ImVec2::y.
Referenced by BeginMenu(), ColorEditOptionsPopup(), ColorPickerOptionsPopup(), MenuItem(), Selectable(), and ShowMetricsWindow().
Selectable() [2/2]
bool ImGui::Selectable (const char * label, bool * p_selected, ImGuiSelectableFlags flags = 0, const ImVec2 & size = ImVec2(0,0))
References Selectable().
ListBox() [1/2]
bool ImGui::ListBox (const char * label, int * current_item, const char *const items[], int items_count, int height_in_items = -1)
References Items_ArrayGetter().
ListBox() [2/2]
IMGUI_API bool ImGui::ListBox (const char * label, int * current_item, bool(*)(void *data, int idx, const char **out_text) items_getter, void * data, int items_count, int height_in_items = -1)
ListBoxHeader() [1/2]
bool ImGui::ListBoxHeader (const char * label, const ImVec2 & size = ImVec2(0,0))
References BeginChildFrame(), BeginGroup(), CalcItemSize(), CalcItemWidth(), CalcTextSize(), ImGuiDrawContext::CursorPos, ImGuiWindow::DC, ImGuiStyle::FramePadding, GetCurrentWindow(), GetID(), ImRect::GetSize(), GetStyle(), GetTextLineHeightWithSpacing(), ImMax(), ImGuiStyle::ItemInnerSpacing, ImGuiStyle::ItemSpacing, ImGuiDrawContext::LastItemRect, ImRect::Max, ImRect::Min, NULL, RenderText(), ImGuiWindow::SkipItems, ImVec2::x, and ImVec2::y.
Referenced by ListBoxHeader().
ListBoxHeader() [2/2]
bool ImGui::ListBoxHeader (const char * label, int items_count, int height_in_items = -1)
References GetStyle(), GetTextLineHeightWithSpacing(), ImMin(), ImGuiStyle::ItemSpacing, ListBoxHeader(), ImVec2::x, and ImVec2::y.
ListBoxFooter()
void ImGui::ListBoxFooter ()
References ImGuiDrawContext::CursorPos, ImGuiWindow::DC, EndChildFrame(), EndGroup(), ImGuiStyle::FramePadding, GetCurrentWindow(), GetStyle(), ItemSize(), ImGuiDrawContext::LastItemRect, ImRect::Min, ImGuiWindow::ParentWindow, SameLine(), and ImVec2::y.
Value() [1/4]
void ImGui::Value (const char * prefix, bool b)
References Text().
Referenced by ImColor::operator ImVec4().
Value() [2/4]
void ImGui::Value (const char * prefix, int v)
References Text().
Value() [3/4]
void ImGui::Value (const char * prefix, unsigned int v)
References Text().
Value() [4/4]
void ImGui::Value (const char * prefix, float v, const char * float_format = NULL)
References IM_ARRAYSIZE, ImFormatString(), and Text().
SetTooltip()
void ImGui::SetTooltip (const char * fmt, ...)
References SetTooltipV().
Referenced by PlotEx().
SetTooltipV()
void ImGui::SetTooltipV (const char * fmt, va_list args)
References BeginTooltipEx(), EndTooltip(), and TextV().
Referenced by SetTooltip().
BeginTooltip()
void ImGui::BeginTooltip ()
References BeginTooltipEx().
Referenced by BeginDragDropSource().
EndTooltip()
void ImGui::EndTooltip ()
References End(), GetCurrentWindowRead(), IM_ASSERT, and ImGuiWindowFlags_Tooltip.
Referenced by ColorTooltip(), EndDragDropSource(), and SetTooltipV().
BeginMainMenuBar()
bool ImGui::BeginMainMenuBar ()
References Begin(), BeginMenuBar(), ImGuiContext::CurrentWindow, ImGuiWindow::DC, ImGuiStyle::DisplaySafeAreaPadding, ImGuiIO::DisplaySize, End(), ImGuiContext::FontBaseSize, ImGuiStyle::FramePadding, GImGui, ImGuiStyleVar_WindowMinSize, ImGuiStyleVar_WindowRounding, ImGuiWindowFlags_MenuBar, ImGuiWindowFlags_NoMove, ImGuiWindowFlags_NoResize, ImGuiWindowFlags_NoSavedSettings, ImGuiWindowFlags_NoScrollbar, ImGuiWindowFlags_NoTitleBar, ImGuiContext::IO, ImGuiDrawContext::MenuBarOffsetX, NULL, PopStyleVar(), PushStyleVar(), SetNextWindowPos(), SetNextWindowSize(), ImGuiContext::Style, ImVec2::x, and ImVec2::y.
EndMainMenuBar()
void ImGui::EndMainMenuBar ()
References ImGuiContext::CurrentWindow, End(), EndMenuBar(), FocusFrontMostActiveWindow(), GImGui, ImGuiContext::NavLayer, ImGuiContext::NavWindow, and PopStyleVar().
BeginMenuBar()
bool ImGui::BeginMenuBar ()
References AlignTextToFramePadding(), BeginGroup(), ImRect::ClipWith(), ImGuiDrawContext::CursorPos, ImGuiWindow::DC, ImGuiWindow::Flags, GetCurrentWindow(), IM_ASSERT, ImFloor(), ImGuiLayoutType_Horizontal, ImGuiWindowFlags_MenuBar, ImMax(), ImGuiDrawContext::LayoutType, ImRect::Max, ImGuiDrawContext::MenuBarAppending, ImGuiDrawContext::MenuBarOffsetX, ImGuiWindow::MenuBarRect(), ImRect::Min, ImGuiDrawContext::NavLayerCurrent, ImGuiDrawContext::NavLayerCurrentMask, PushClipRect(), PushID(), ImGuiWindow::SkipItems, ImGuiWindow::WindowBorderSize, ImGuiWindow::WindowRectClipped, ImGuiWindow::WindowRounding, ImVec2::x, and ImVec2::y.
Referenced by BeginMainMenuBar().
EndMenuBar()
void ImGui::EndMenuBar ()
References ImGuiGroupData::AdvanceCursor, ImVector< T >::back(), ImGuiDrawContext::CursorPos, ImGuiWindow::DC, EndGroup(), ImGuiWindow::Flags, FocusWindow(), GetCurrentWindow(), GImGui, ImGuiDrawContext::GroupStack, IM_ASSERT, ImGuiDir_Left, ImGuiDir_Right, ImGuiLayoutType_Horizontal, ImGuiLayoutType_Vertical, ImGuiNavForward_ForwardQueued, ImGuiNavForward_None, ImGuiWindowFlags_ChildMenu, ImGuiWindowFlags_MenuBar, ImGuiDrawContext::LayoutType, ImGuiDrawContext::MenuBarAppending, ImGuiDrawContext::MenuBarOffsetX, ImGuiWindow::MenuBarRect(), ImRect::Min, ImGuiContext::NavDisableHighlight, ImGuiWindow::NavLastIds, ImGuiContext::NavLayer, ImGuiDrawContext::NavLayerActiveMaskNext, ImGuiDrawContext::NavLayerCurrent, ImGuiDrawContext::NavLayerCurrentMask, ImGuiContext::NavMoveDir, NavMoveRequestButNoResultYet(), NavMoveRequestCancel(), ImGuiContext::NavMoveRequestForward, ImGuiWindow::NavRectRel, ImGuiContext::NavWindow, ImGuiDrawContext::ParentLayoutType, ImGuiWindow::ParentWindow, PopClipRect(), PopID(), SetNavIDAndMoveMouse(), ImGuiWindow::SkipItems, and ImVec2::x.
Referenced by EndMainMenuBar().
BeginMenu()
bool ImGui::BeginMenu (const char * label, bool enabled = true)
References ImVector< T >::back(), BeginPopupEx(), CalcTextSize(), ClosePopupToLevel(), ImGuiStyle::Colors, ImGuiContext::CurrentPopupStack, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, ImGuiMenuColumns::DeclColumns(), ImGuiWindow::Flags, ImGuiContext::FontSize, ImGuiStyle::FramePadding, ImRect::GetBL(), ImRect::GetBR(), GetContentRegionAvail(), GetCurrentWindow(), ImGuiWindow::GetID(), ImRect::GetTL(), ImRect::GetTR(), GImGui, ImGuiContext::HoveredIdPreviousFrame, ImGuiContext::HoveredWindow, ImGuiWindow::IDStack, ImClamp(), ImGuiCol_Text, ImGuiCol_TextDisabled, ImGuiCond_Always, ImGuiDir_Down, ImGuiDir_Right, ImGuiLayoutType_Horizontal, ImGuiLayoutType_Vertical, ImGuiSelectableFlags_Disabled, ImGuiSelectableFlags_DontClosePopups, ImGuiSelectableFlags_DrawFillAvailWidth, ImGuiSelectableFlags_Menu, ImGuiStyleVar_ItemSpacing, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_ChildMenu, ImGuiWindowFlags_ChildWindow, ImGuiWindowFlags_MenuBar, ImGuiWindowFlags_NoSavedSettings, ImGuiWindowFlags_NoTitleBar, ImGuiWindowFlags_Popup, ImMax(), ImMin(), ImTriangleContainsPoint(), ImGuiContext::IO, IsPopupOpen(), ItemHoverable(), ImGuiStyle::ItemSpacing, ImGuiDrawContext::LastItemRect, ImGuiDrawContext::LayoutType, ImGuiWindow::MenuBarHeight(), ImGuiWindow::MenuColumns, ImGuiIO::MouseDelta, ImGuiIO::MousePos, ImGuiContext::NavActivateId, ImGuiContext::NavId, ImGuiContext::NavMoveDir, ImGuiContext::NavMoveRequest, NavMoveRequestCancel(), ImGuiContext::NavWindow, NULL, OpenPopup(), ImGuiContext::OpenPopupStack, PopStyleColor(), PopStyleVar(), ImGuiMenuColumns::Pos, ImGuiWindow::Pos, PushStyleColor(), PushStyleVar(), RenderTriangle(), Selectable(), SetNextWindowPos(), ImVector< T >::Size, ImGuiWindow::SkipItems, ImGuiContext::Style, ImGuiStyle::WindowPadding, ImGuiWindow::WindowPadding, ImVec2::x, and ImVec2::y.
EndMenu()
void ImGui::EndMenu ()
References ClosePopupToLevel(), ImGuiContext::CurrentWindow, ImGuiWindow::DC, EndPopup(), GImGui, ImGuiDir_Left, ImGuiLayoutType_Vertical, ImGuiDrawContext::LayoutType, ImGuiContext::NavMoveDir, NavMoveRequestButNoResultYet(), NavMoveRequestCancel(), ImGuiContext::NavWindow, ImGuiContext::OpenPopupStack, ImGuiWindow::ParentWindow, and ImVector< T >::Size.
MenuItem() [1/2]
bool ImGui::MenuItem (const char * label, const char * shortcut = NULL, bool selected = false, bool enabled = true)
References CalcTextSize(), ImGuiStyle::Colors, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, ImGuiMenuColumns::DeclColumns(), ImGuiContext::FontSize, GetColorU32(), GetContentRegionAvail(), GetCurrentWindow(), GImGui, ImGuiCol_Text, ImGuiCol_TextDisabled, ImGuiLayoutType_Horizontal, ImGuiSelectableFlags_Disabled, ImGuiSelectableFlags_DrawFillAvailWidth, ImGuiSelectableFlags_MenuItem, ImGuiStyleVar_ItemSpacing, ImMax(), ImGuiStyle::ItemSpacing, ImGuiDrawContext::LayoutType, ImGuiWindow::MenuColumns, NULL, PopStyleColor(), PopStyleVar(), ImGuiMenuColumns::Pos, PushStyleColor(), PushStyleVar(), RenderCheckMark(), RenderText(), Selectable(), ImGuiWindow::SkipItems, ImGuiContext::Style, and ImVec2::x.
Referenced by MenuItem().
MenuItem() [2/2]
bool ImGui::MenuItem (const char * label, const char * shortcut, bool * p_selected, bool enabled = true)
References MenuItem().
OpenPopup()
void ImGui::OpenPopup (const char * str_id)
References ImGuiContext::CurrentWindow, ImGuiWindow::GetID(), GImGui, and OpenPopupEx().
Referenced by BeginMenu(), ColorEdit4(), and ColorEditOptionsPopup().
BeginPopup()
bool ImGui::BeginPopup (const char * str_id, ImGuiWindowFlags flags = 0)
References BeginPopupEx(), ImGuiNextWindowData::Clear(), ImGuiContext::CurrentPopupStack, ImGuiContext::CurrentWindow, ImGuiWindow::GetID(), GImGui, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoSavedSettings, ImGuiWindowFlags_NoTitleBar, ImGuiContext::NextWindowData, ImGuiContext::OpenPopupStack, and ImVector< T >::Size.
Referenced by ColorEdit4(), ColorEditOptionsPopup(), and ColorPickerOptionsPopup().
BeginPopupContextItem()
bool ImGui::BeginPopupContextItem (const char * str_id = NULL, int mouse_button = 1)
References BeginPopupEx(), ImGuiContext::CurrentWindow, ImGuiWindow::DC, ImGuiWindow::GetID(), GImGui, IM_ASSERT, ImGuiHoveredFlags_AllowWhenBlockedByPopup, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoSavedSettings, ImGuiWindowFlags_NoTitleBar, IsItemHovered(), IsMouseReleased(), ImGuiDrawContext::LastItemId, and OpenPopupEx().
BeginPopupContextWindow()
bool ImGui::BeginPopupContextWindow (const char * str_id = NULL, int mouse_button = 1, bool also_over_items = true)
References BeginPopupEx(), ImGuiContext::CurrentWindow, ImGuiWindow::GetID(), GImGui, ImGuiHoveredFlags_AllowWhenBlockedByPopup, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoSavedSettings, ImGuiWindowFlags_NoTitleBar, IsAnyItemHovered(), IsMouseReleased(), IsWindowHovered(), and OpenPopupEx().
BeginPopupContextVoid()
bool ImGui::BeginPopupContextVoid (const char * str_id = NULL, int mouse_button = 1)
References BeginPopupEx(), ImGuiContext::CurrentWindow, ImGuiWindow::GetID(), GImGui, ImGuiHoveredFlags_AnyWindow, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoSavedSettings, ImGuiWindowFlags_NoTitleBar, IsMouseReleased(), IsWindowHovered(), and OpenPopupEx().
BeginPopupModal()
bool ImGui::BeginPopupModal (const char * name, bool * p_open = NULL, ImGuiWindowFlags flags = 0)
References Begin(), ImGuiNextWindowData::Clear(), ClosePopup(), ImGuiContext::CurrentWindow, ImGuiIO::DisplaySize, EndPopup(), ImGuiWindow::GetID(), GImGui, ImGuiCond_Appearing, ImGuiWindowFlags_Modal, ImGuiWindowFlags_NoCollapse, ImGuiWindowFlags_NoSavedSettings, ImGuiWindowFlags_Popup, ImGuiContext::IO, IsPopupOpen(), setup::name, ImGuiContext::NextWindowData, ImGuiNextWindowData::PosCond, and SetNextWindowPos().
EndPopup()
void ImGui::EndPopup ()
References ImGuiContext::CurrentPopupStack, ImGuiContext::CurrentWindow, End(), ImGuiWindow::Flags, GImGui, IM_ASSERT, ImGuiWindowFlags_Popup, NavProcessMoveRequestWrapAround(), and ImVector< T >::Size.
Referenced by BeginCombo(), BeginPopupEx(), BeginPopupModal(), ColorEdit4(), ColorEditOptionsPopup(), ColorPickerOptionsPopup(), EndCombo(), and EndMenu().
OpenPopupOnItemClick()
bool ImGui::OpenPopupOnItemClick (const char * str_id = NULL, int mouse_button = 1)
References ImGuiContext::CurrentWindow, ImGuiWindow::DC, ImGuiWindow::GetID(), GImGui, IM_ASSERT, ImGuiHoveredFlags_AllowWhenBlockedByPopup, IsItemHovered(), IsMouseReleased(), ImGuiDrawContext::LastItemId, and OpenPopupEx().
Referenced by ColorEdit4(), and ColorPicker4().
IsPopupOpen() [2/2]
bool ImGui::IsPopupOpen (const char * str_id)
References ImGuiContext::CurrentPopupStack, ImGuiContext::CurrentWindow, ImGuiWindow::GetID(), GImGui, ImGuiContext::OpenPopupStack, and ImVector< T >::Size.
CloseCurrentPopup()
void ImGui::CloseCurrentPopup ()
References ClosePopupToLevel(), ImGuiContext::CurrentPopupStack, GImGui, ImGuiWindowFlags_ChildMenu, ImGuiContext::OpenPopupStack, and ImVector< T >::Size.
Referenced by Selectable().
LogToTTY()
void ImGui::LogToTTY (int max_depth = -1)
References ImGuiContext::CurrentWindow, ImGuiWindow::DC, GImGui, IM_ASSERT, ImGuiContext::LogAutoExpandMaxDepth, ImGuiContext::LogEnabled, ImGuiContext::LogFile, ImGuiContext::LogStartDepth, NULL, and ImGuiDrawContext::TreeDepth.
Referenced by LogButtons().
LogToFile()
void ImGui::LogToFile (int max_depth = -1, const char * filename = NULL)
References ImGuiContext::CurrentWindow, ImGuiWindow::DC, GImGui, IM_ASSERT, ImFileOpen(), ImGuiContext::IO, ImGuiContext::LogAutoExpandMaxDepth, ImGuiContext::LogEnabled, ImGuiContext::LogFile, ImGuiIO::LogFilename, ImGuiContext::LogStartDepth, NULL, and ImGuiDrawContext::TreeDepth.
Referenced by LogButtons().
LogToClipboard()
void ImGui::LogToClipboard (int max_depth = -1)
References ImGuiContext::CurrentWindow, ImGuiWindow::DC, GImGui, IM_ASSERT, ImGuiContext::LogAutoExpandMaxDepth, ImGuiContext::LogEnabled, ImGuiContext::LogFile, ImGuiContext::LogStartDepth, NULL, and ImGuiDrawContext::TreeDepth.
Referenced by LogButtons().
LogFinish()
void ImGui::LogFinish ()
References ImGuiTextBuffer::begin(), ImGuiTextBuffer::clear(), GImGui, IM_NEWLINE, ImGuiContext::LogClipboard, ImGuiContext::LogEnabled, ImGuiContext::LogFile, LogText(), NULL, SetClipboardText(), and ImGuiTextBuffer::size().
Referenced by End().
LogButtons()
void ImGui::LogButtons ()
References Button(), GImGui, ImGuiContext::IO, ImGuiContext::LogAutoExpandMaxDepth, ImGuiIO::LogFilename, LogToClipboard(), LogToFile(), LogToTTY(), NULL, PopAllowKeyboardFocus(), PopID(), PopItemWidth(), PushAllowKeyboardFocus(), PushID(), PushItemWidth(), SameLine(), and SliderInt().
LogText()
void ImGui::LogText (const char * fmt, ...)
References ImGuiTextBuffer::appendfv(), GImGui, ImGuiContext::LogClipboard, ImGuiContext::LogEnabled, and ImGuiContext::LogFile.
Referenced by LogFinish(), LogRenderedText(), and VerticalSeparator().
BeginDragDropSource()
bool ImGui::BeginDragDropSource (ImGuiDragDropFlags flags = 0)
References ImGuiContext::ActiveId, ImGuiContext::ActiveIdAllowOverlap, ImGuiContext::ActiveIdWindow, ImVector< T >::back(), BeginTooltip(), ClearDragDrop(), ImGuiContext::CurrentWindow, ImGuiWindow::DC, ImGuiContext::DragDropActive, ImGuiContext::DragDropMouseButton, ImGuiContext::DragDropPayload, ImGuiContext::DragDropSourceFlags, FocusWindow(), ImGuiWindow::GetIDFromRectangle(), GetStyleColorVec4(), GImGui, ImGuiWindow::IDStack, IM_ASSERT, ImGuiCol_PopupBg, ImGuiDragDropFlags_SourceAllowNullID, ImGuiDragDropFlags_SourceExtern, ImGuiDragDropFlags_SourceNoDisableHover, ImGuiDragDropFlags_SourceNoPreviewTooltip, ImGuiItemStatusFlags_HoveredRect, ImHash(), ImGuiContext::IO, IsMouseDragging(), ImGuiDrawContext::LastItemId, ImGuiDrawContext::LastItemRect, ImGuiDrawContext::LastItemStatusFlags, ImGuiIO::MouseClicked, ImGuiIO::MouseDown, ImGuiIO::MousePos, NULL, PushStyleColor(), SetActiveID(), SetHoveredID(), SetNextWindowPos(), ImGuiPayload::SourceId, and ImGuiPayload::SourceParentId.
Referenced by ColorButton().
SetDragDropPayload()
bool ImGui::SetDragDropPayload (const char * type, const void * data, size_t size, ImGuiCond cond = 0)
References ImVector< T >::Data, ImGuiPayload::Data, ImGuiPayload::DataFrameCount, ImGuiPayload::DataSize, ImGuiPayload::DataType, ImGuiContext::DragDropAcceptFrameCount, ImGuiContext::DragDropPayload, ImGuiContext::DragDropPayloadBufHeap, ImGuiContext::DragDropPayloadBufLocal, ImGuiContext::FrameCount, GImGui, IM_ARRAYSIZE, IM_ASSERT, ImGuiCond_Always, ImGuiCond_Once, ImStrncpy(), memcpy(), memset(), NULL, ImVector< T >::resize(), and ImGuiPayload::SourceId.
Referenced by ColorButton().
EndDragDropSource()
void ImGui::EndDragDropSource ()
References ClearDragDrop(), ImGuiPayload::DataFrameCount, ImGuiContext::DragDropActive, ImGuiContext::DragDropPayload, ImGuiContext::DragDropSourceFlags, EndTooltip(), GImGui, IM_ASSERT, ImGuiDragDropFlags_SourceNoPreviewTooltip, and PopStyleColor().
Referenced by ColorButton().
BeginDragDropTarget()
bool ImGui::BeginDragDropTarget ()
References ImGuiContext::CurrentWindow, ImGuiWindow::DC, ImGuiContext::DragDropActive, ImGuiContext::DragDropPayload, ImGuiContext::DragDropTargetId, ImGuiContext::DragDropTargetRect, ImGuiWindow::GetIDFromRectangle(), GImGui, ImGuiContext::HoveredWindow, ImGuiItemStatusFlags_HasDisplayRect, ImGuiItemStatusFlags_HoveredRect, ImGuiDrawContext::LastItemDisplayRect, ImGuiDrawContext::LastItemId, ImGuiDrawContext::LastItemRect, ImGuiDrawContext::LastItemStatusFlags, NULL, ImGuiWindow::RootWindow, and ImGuiPayload::SourceId.
Referenced by ColorEdit4().
AcceptDragDropPayload()
const ImGuiPayload * ImGui::AcceptDragDropPayload (const char * type, ImGuiDragDropFlags flags = 0)
References ImDrawList::AddRect(), ImGuiWindow::ClipRect, ImRect::Contains(), ImGuiContext::CurrentWindow, ImGuiPayload::DataFrameCount, ImGuiPayload::Delivery, ImGuiContext::DragDropAcceptFrameCount, ImGuiContext::DragDropAcceptIdCurr, ImGuiContext::DragDropAcceptIdCurrRectSurface, ImGuiContext::DragDropAcceptIdPrev, ImGuiContext::DragDropActive, ImGuiContext::DragDropMouseButton, ImGuiContext::DragDropPayload, ImGuiContext::DragDropSourceFlags, ImGuiContext::DragDropTargetId, ImGuiContext::DragDropTargetRect, ImGuiWindow::DrawList, ImRect::Expand(), ImGuiContext::FrameCount, GetColorU32(), ImRect::GetHeight(), ImRect::GetWidth(), GImGui, IM_ASSERT, ImGuiCol_DragDropTarget, ImGuiDragDropFlags_AcceptBeforeDelivery, ImGuiDragDropFlags_AcceptNoDrawDefaultRect, ImGuiPayload::IsDataType(), IsMouseDown(), ImRect::Max, ImRect::Min, NULL, ImDrawList::PopClipRect(), ImGuiPayload::Preview, and ImDrawList::PushClipRectFullScreen().
Referenced by ColorEdit4().
EndDragDropTarget()
void ImGui::EndDragDropTarget ()
References ImGuiContext::DragDropActive, GImGui, and IM_ASSERT.
Referenced by ColorEdit4().
PushClipRect()
void ImGui::PushClipRect (const ImVec2 & clip_rect_min, const ImVec2 & clip_rect_max, bool intersect_with_current_clip_rect)
References ImDrawList::_ClipRectStack, ImVector< T >::back(), ImGuiWindow::ClipRect, ImGuiWindow::DrawList, GetCurrentWindow(), and ImDrawList::PushClipRect().
Referenced by Begin(), BeginMenuBar(), ImDrawList::PushClipRectFullScreen(), and PushColumnClipRect().
PopClipRect()
void ImGui::PopClipRect ()
References ImDrawList::_ClipRectStack, ImVector< T >::back(), ImGuiWindow::ClipRect, ImGuiWindow::DrawList, GetCurrentWindow(), and ImDrawList::PopClipRect().
Referenced by End(), EndColumns(), EndMenuBar(), NextColumn(), Selectable(), and Separator().
SetItemDefaultFocus()
void ImGui::SetItemDefaultFocus ()
References ImGuiWindow::Appearing, ImGuiContext::CurrentWindow, ImGuiWindow::DC, GImGui, IsItemVisible(), ImGuiDrawContext::LastItemId, ImGuiDrawContext::LastItemRect, ImRect::Max, ImRect::Min, ImGuiContext::NavInitRequest, ImGuiContext::NavInitResultId, ImGuiContext::NavInitResultRectRel, ImGuiContext::NavLayer, ImGuiDrawContext::NavLayerCurrent, NavUpdateAnyRequestFlag(), ImGuiContext::NavWindow, ImGuiWindow::Pos, ImGuiWindow::RootWindowForNav, and SetScrollHere().
SetKeyboardFocusHere()
void ImGui::SetKeyboardFocusHere (int offset = 0)
References ImGuiWindow::FocusIdxAllCounter, ImGuiWindow::FocusIdxAllRequestNext, ImGuiWindow::FocusIdxTabRequestNext, GetCurrentWindow(), and IM_ASSERT.
IsItemHovered()
bool ImGui::IsItemHovered (ImGuiHoveredFlags flags = 0)
References ImGuiContext::ActiveId, ImGuiContext::ActiveIdAllowOverlap, ImGuiContext::CurrentWindow, ImGuiWindow::DC, GImGui, ImGuiContext::HoveredRootWindow, IM_ASSERT, ImGuiHoveredFlags_AllowWhenBlockedByActiveItem, ImGuiHoveredFlags_AllowWhenOverlapped, ImGuiHoveredFlags_ChildWindows, ImGuiHoveredFlags_RootWindow, ImGuiItemFlags_Disabled, ImGuiItemStatusFlags_HoveredRect, IsItemFocused(), IsWindowContentHoverable(), ImGuiDrawContext::ItemFlags, ImGuiDrawContext::LastItemId, ImGuiDrawContext::LastItemStatusFlags, ImGuiWindow::MoveId, ImGuiContext::NavDisableHighlight, ImGuiContext::NavDisableMouseHover, ImGuiWindow::RootWindow, and ImGuiWindow::WriteAccessed.
Referenced by BeginPopupContextItem(), ButtonBehavior(), IsItemClicked(), IsItemHoveredRect(), OpenPopupOnItemClick(), and ShowMetricsWindow().
IsItemActive()
bool ImGui::IsItemActive ()
References ImGuiContext::ActiveId, ImGuiContext::CurrentWindow, ImGuiWindow::DC, GImGui, and ImGuiDrawContext::LastItemId.
Referenced by ColorPicker4().
IsItemFocused()
bool ImGui::IsItemFocused ()
References ImGuiContext::CurrentWindow, ImGuiWindow::DC, GImGui, ImGuiDrawContext::LastItemId, ImGuiContext::NavDisableHighlight, and ImGuiContext::NavId.
Referenced by IsItemHovered().
IsItemClicked()
bool ImGui::IsItemClicked (int mouse_button = 0)
References ImGuiHoveredFlags_Default, IsItemHovered(), and IsMouseClicked().
IsItemVisible()
bool ImGui::IsItemVisible ()
References ImGuiWindow::ClipRect, ImGuiWindow::DC, GetCurrentWindowRead(), ImGuiDrawContext::LastItemRect, and ImRect::Overlaps().
Referenced by SetItemDefaultFocus().
IsAnyItemHovered()
bool ImGui::IsAnyItemHovered ()
References GImGui, ImGuiContext::HoveredId, and ImGuiContext::HoveredIdPreviousFrame.
Referenced by BeginPopupContextWindow().
IsAnyItemActive()
bool ImGui::IsAnyItemActive ()
References ImGuiContext::ActiveId, and GImGui.
IsAnyItemFocused()
bool ImGui::IsAnyItemFocused ()
References GImGui, ImGuiContext::NavDisableHighlight, and ImGuiContext::NavId.
GetItemRectMin()
ImVec2 ImGui::GetItemRectMin ()
References ImGuiWindow::DC, GetCurrentWindowRead(), ImGuiDrawContext::LastItemRect, and ImRect::Min.
GetItemRectMax()
ImVec2 ImGui::GetItemRectMax ()
References ImGuiWindow::DC, GetCurrentWindowRead(), ImGuiDrawContext::LastItemRect, and ImRect::Max.
GetItemRectSize()
ImVec2 ImGui::GetItemRectSize ()
References ImGuiWindow::DC, GetCurrentWindowRead(), ImRect::GetSize(), and ImGuiDrawContext::LastItemRect.
SetItemAllowOverlap()
void ImGui::SetItemAllowOverlap ()
References ImGuiContext::ActiveId, ImGuiContext::ActiveIdAllowOverlap, ImGuiContext::CurrentWindow, ImGuiWindow::DC, GImGui, ImGuiContext::HoveredId, ImGuiContext::HoveredIdAllowOverlap, and ImGuiDrawContext::LastItemId.
Referenced by SplitterBehavior(), and TreeNodeBehavior().
IsWindowFocused()
bool ImGui::IsWindowFocused (ImGuiFocusedFlags flags = 0)
References ImGuiContext::CurrentWindow, GImGui, IM_ASSERT, ImGuiFocusedFlags_AnyWindow, ImGuiFocusedFlags_ChildWindows, ImGuiFocusedFlags_RootWindow, IsWindowChildOf(), ImGuiContext::NavWindow, NULL, and ImGuiWindow::RootWindow.
Referenced by IsAnyWindowFocused(), IsRootWindowFocused(), and IsRootWindowOrAnyChildFocused().
IsWindowHovered()
bool ImGui::IsWindowHovered (ImGuiHoveredFlags flags = 0)
References ImGuiContext::ActiveId, ImGuiContext::ActiveIdAllowOverlap, ImGuiContext::CurrentWindow, GImGui, ImGuiContext::HoveredRootWindow, ImGuiContext::HoveredWindow, IM_ASSERT, ImGuiHoveredFlags_AllowWhenBlockedByActiveItem, ImGuiHoveredFlags_AllowWhenOverlapped, ImGuiHoveredFlags_AnyWindow, ImGuiHoveredFlags_ChildWindows, ImGuiHoveredFlags_RootWindow, IsWindowChildOf(), IsWindowContentHoverable(), ImGuiWindow::MoveId, NULL, and ImGuiWindow::RootWindow.
Referenced by BeginPopupContextVoid(), BeginPopupContextWindow(), IsAnyWindowHovered(), IsMouseHoveringAnyWindow(), IsMouseHoveringWindow(), and IsRootWindowOrAnyChildHovered().
IsRectVisible() [1/2]
bool ImGui::IsRectVisible (const ImVec2 & size)
References ImGuiWindow::ClipRect, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, GetCurrentWindowRead(), and ImRect::Overlaps().
IsRectVisible() [2/2]
bool ImGui::IsRectVisible (const ImVec2 & rect_min, const ImVec2 & rect_max)
References ImGuiWindow::ClipRect, GetCurrentWindowRead(), and ImRect::Overlaps().
GetTime()
float ImGui::GetTime ()
References GImGui, and ImGuiContext::Time.
GetFrameCount()
int ImGui::GetFrameCount ()
References ImGuiContext::FrameCount, and GImGui.
Referenced by ImGuiOnceUponAFrame::operator bool().
GetOverlayDrawList()
ImDrawList * ImGui::GetOverlayDrawList ()
References GImGui, and ImGuiContext::OverlayDrawList.
Referenced by ShowMetricsWindow().
GetDrawListSharedData()
ImDrawListSharedData * ImGui::GetDrawListSharedData ()
References ImGuiContext::DrawListSharedData, and GImGui.
GetStyleColorName()
const char * ImGui::GetStyleColorName (ImGuiCol idx)
References IM_ASSERT, ImGuiCol_Border, ImGuiCol_BorderShadow, ImGuiCol_Button, ImGuiCol_ButtonActive, ImGuiCol_ButtonHovered, ImGuiCol_CheckMark, ImGuiCol_ChildBg, ImGuiCol_CloseButton, ImGuiCol_CloseButtonActive, ImGuiCol_CloseButtonHovered, ImGuiCol_DragDropTarget, ImGuiCol_FrameBg, ImGuiCol_FrameBgActive, ImGuiCol_FrameBgHovered, ImGuiCol_Header, ImGuiCol_HeaderActive, ImGuiCol_HeaderHovered, ImGuiCol_MenuBarBg, ImGuiCol_ModalWindowDarkening, ImGuiCol_NavHighlight, ImGuiCol_NavWindowingHighlight, ImGuiCol_PlotHistogram, ImGuiCol_PlotHistogramHovered, ImGuiCol_PlotLines, ImGuiCol_PlotLinesHovered, ImGuiCol_PopupBg, ImGuiCol_ResizeGrip, ImGuiCol_ResizeGripActive, ImGuiCol_ResizeGripHovered, ImGuiCol_ScrollbarBg, ImGuiCol_ScrollbarGrab, ImGuiCol_ScrollbarGrabActive, ImGuiCol_ScrollbarGrabHovered, ImGuiCol_Separator, ImGuiCol_SeparatorActive, ImGuiCol_SeparatorHovered, ImGuiCol_SliderGrab, ImGuiCol_SliderGrabActive, ImGuiCol_Text, ImGuiCol_TextDisabled, ImGuiCol_TextSelectedBg, ImGuiCol_TitleBg, ImGuiCol_TitleBgActive, ImGuiCol_TitleBgCollapsed, and ImGuiCol_WindowBg.
CalcTextSize()
ImVec2 ImGui::CalcTextSize (const char * text, const char * text_end = NULL, bool hide_text_after_double_hash = false, float wrap_width = -1.0f)
References ImFont::CalcTextSizeA(), FindRenderedTextEnd(), FLT_MAX, ImGuiContext::Font, ImGuiContext::FontSize, ImFont::FontSize, GImGui, NULL, and ImVec2::x.
Referenced by Begin(), BeginCombo(), BeginMenu(), BulletTextV(), ButtonEx(), Checkbox(), ColorEdit4(), DragFloat(), InputScalarEx(), InputTextEx(), LabelTextV(), ListBoxHeader(), MenuItem(), NavScoreItem(), PlotEx(), ProgressBar(), RadioButton(), RenderTextClipped(), Selectable(), SliderFloat(), TextUnformatted(), TreeNodeBehavior(), and VSliderFloat().
CalcListClipping()
void ImGui::CalcListClipping (int items_count, float items_height, int * out_items_display_start, int * out_items_display_end)
References ImGuiWindow::ClipRect, ImGuiContext::CurrentWindow, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, GImGui, ImClamp(), ImGuiDir_Down, ImGuiDir_Up, ImGuiContext::LogEnabled, ImRect::Max, ImRect::Min, ImGuiContext::NavMoveDir, ImGuiContext::NavMoveRequest, ImGuiWindow::SkipItems, and ImVec2::y.
Referenced by ImGuiListClipper::Begin().
BeginChildFrame()
bool ImGui::BeginChildFrame (ImGuiID id, const ImVec2 & size, ImGuiWindowFlags flags = 0)
References BeginChild(), ImGuiStyle::Colors, ImGuiStyle::FrameBorderSize, ImGuiStyle::FramePadding, ImGuiStyle::FrameRounding, GImGui, ImGuiCol_ChildBg, ImGuiCol_FrameBg, ImGuiStyleVar_ChildBorderSize, ImGuiStyleVar_ChildRounding, ImGuiStyleVar_WindowPadding, ImGuiWindowFlags_AlwaysUseWindowPadding, ImGuiWindowFlags_NoMove, PushStyleColor(), PushStyleVar(), and ImGuiContext::Style.
Referenced by InputTextEx(), and ListBoxHeader().
EndChildFrame()
void ImGui::EndChildFrame ()
References EndChild(), PopStyleColor(), and PopStyleVar().
Referenced by InputTextEx(), and ListBoxFooter().
ColorConvertU32ToFloat4()
ImVec4 ImGui::ColorConvertU32ToFloat4 (ImU32 in)
References IM_COL32_A_SHIFT, IM_COL32_B_SHIFT, IM_COL32_G_SHIFT, and IM_COL32_R_SHIFT.
Referenced by PushStyleColor().
ColorConvertFloat4ToU32()
ImU32 ImGui::ColorConvertFloat4ToU32 (const ImVec4 & in)
References IM_COL32_A_SHIFT, IM_COL32_B_SHIFT, IM_COL32_G_SHIFT, IM_COL32_R_SHIFT, IM_F32_TO_INT8_SAT, ImVec4::w, ImVec4::x, ImVec4::y, and ImVec4::z.
Referenced by ColorPicker4(), GetColorU32(), and ImColor::operator ImU32().
ColorConvertRGBtoHSV()
void ImGui::ColorConvertRGBtoHSV (float r, float g, float b, float & out_h, float & out_s, float & out_v)
References ImSwap().
Referenced by ColorEdit4(), and ColorPicker4().
ColorConvertHSVtoRGB()
void ImGui::ColorConvertHSVtoRGB (float h, float s, float v, float & out_r, float & out_g, float & out_b)
Referenced by ColorEdit4(), ColorPicker4(), ImColor::HSV(), and ImColor::SetHSV().
GetKeyIndex()
int ImGui::GetKeyIndex (ImGuiKey imgui_key)
References GImGui, IM_ASSERT, ImGuiKey_COUNT, ImGuiContext::IO, and ImGuiIO::KeyMap.
IsKeyDown()
bool ImGui::IsKeyDown (int user_key_index)
References GImGui, IM_ARRAYSIZE, IM_ASSERT, ImGuiContext::IO, and ImGuiIO::KeysDown.
IsKeyPressed()
bool ImGui::IsKeyPressed (int user_key_index, bool repeat = true)
References GetKeyPressedAmount(), GImGui, IM_ARRAYSIZE, IM_ASSERT, ImGuiContext::IO, ImGuiIO::KeyRepeatDelay, ImGuiIO::KeyRepeatRate, ImGuiIO::KeysDown, and ImGuiIO::KeysDownDuration.
Referenced by IsKeyPressedMap().
IsKeyReleased()
bool ImGui::IsKeyReleased (int user_key_index)
References GImGui, IM_ARRAYSIZE, IM_ASSERT, ImGuiContext::IO, ImGuiIO::KeysDown, and ImGuiIO::KeysDownDurationPrev.
GetKeyPressedAmount()
int ImGui::GetKeyPressedAmount (int key_index, float repeat_delay, float rate)
References CalcTypematicPressedRepeatAmount(), ImGuiIO::DeltaTime, GImGui, IM_ARRAYSIZE, IM_ASSERT, ImGuiContext::IO, ImGuiIO::KeysDown, and ImGuiIO::KeysDownDuration.
Referenced by IsKeyPressed().
IsMouseDown()
bool ImGui::IsMouseDown (int button)
References GImGui, IM_ARRAYSIZE, IM_ASSERT, ImGuiContext::IO, and ImGuiIO::MouseDown.
Referenced by AcceptDragDropPayload().
IsAnyMouseDown()
bool ImGui::IsAnyMouseDown ()
References GImGui, IM_ARRAYSIZE, ImGuiContext::IO, and ImGuiIO::MouseDown.
IsMouseClicked()
bool ImGui::IsMouseClicked (int button, bool repeat = false)
References ImGuiIO::DeltaTime, GImGui, IM_ARRAYSIZE, IM_ASSERT, ImGuiContext::IO, ImGuiIO::KeyRepeatDelay, ImGuiIO::KeyRepeatRate, ImGuiIO::MouseDown, and ImGuiIO::MouseDownDuration.
Referenced by ButtonBehavior(), and IsItemClicked().
IsMouseDoubleClicked()
bool ImGui::IsMouseDoubleClicked (int button)
References GImGui, IM_ARRAYSIZE, IM_ASSERT, ImGuiContext::IO, ImGuiIO::MouseDoubleClicked, and ImGuiIO::MouseDown.
IsMouseReleased()
bool ImGui::IsMouseReleased (int button)
References GImGui, IM_ARRAYSIZE, IM_ASSERT, ImGuiContext::IO, ImGuiIO::MouseDown, and ImGuiIO::MouseReleased.
Referenced by BeginPopupContextItem(), BeginPopupContextVoid(), BeginPopupContextWindow(), and OpenPopupOnItemClick().
IsMouseDragging()
bool ImGui::IsMouseDragging (int button = 0, float lock_threshold = -1.0f)
References GImGui, IM_ARRAYSIZE, IM_ASSERT, ImGuiContext::IO, ImGuiIO::MouseDown, ImGuiIO::MouseDragMaxDistanceSqr, and ImGuiIO::MouseDragThreshold.
Referenced by BeginDragDropSource().
IsMouseHoveringRect()
bool ImGui::IsMouseHoveringRect (const ImVec2 & r_min, const ImVec2 & r_max, bool clip = true)
References ImGuiWindow::ClipRect, ImRect::ClipWith(), ImRect::Contains(), ImGuiContext::CurrentWindow, GImGui, ImGuiContext::IO, ImRect::Max, ImRect::Min, ImGuiIO::MousePos, ImGuiContext::Style, and ImGuiStyle::TouchExtraPadding.
Referenced by Begin(), BeginDragDropTargetCustom(), ItemAdd(), ItemHoverable(), NavScoreItem(), and TreeNodeBehavior().
IsMousePosValid()
bool ImGui::IsMousePosValid (const ImVec2 * mouse_pos = NULL)
References GImGui, ImGuiContext::IO, ImGuiIO::MousePos, NULL, ImVec2::x, and ImVec2::y.
Referenced by DragBehavior(), NavUpdateWindowing(), and NewFrame().
GetMousePos()
ImVec2 ImGui::GetMousePos ()
References GImGui, ImGuiContext::IO, and ImGuiIO::MousePos.
GetMousePosOnOpeningCurrentPopup()
ImVec2 ImGui::GetMousePosOnOpeningCurrentPopup ()
References ImGuiContext::CurrentPopupStack, GImGui, ImGuiContext::IO, ImGuiIO::MousePos, ImGuiContext::OpenPopupStack, and ImVector< T >::Size.
GetMouseDragDelta()
ImVec2 ImGui::GetMouseDragDelta (int button = 0, float lock_threshold = -1.0f)
References GImGui, IM_ARRAYSIZE, IM_ASSERT, ImGuiContext::IO, ImGuiIO::MouseClickedPos, ImGuiIO::MouseDown, ImGuiIO::MouseDragMaxDistanceSqr, ImGuiIO::MouseDragThreshold, and ImGuiIO::MousePos.
Referenced by DragBehavior().
ResetMouseDragDelta()
void ImGui::ResetMouseDragDelta (int button = 0)
References GImGui, IM_ARRAYSIZE, IM_ASSERT, ImGuiContext::IO, ImGuiIO::MouseClickedPos, ImGuiIO::MouseDown, and ImGuiIO::MousePos.
GetMouseCursor()
ImGuiMouseCursor ImGui::GetMouseCursor ()
References GImGui, and ImGuiContext::MouseCursor.
Referenced by AuroraFW::GEngine::ImGuiLoader::newFrame().
SetMouseCursor()
void ImGui::SetMouseCursor (ImGuiMouseCursor type)
References GImGui, and ImGuiContext::MouseCursor.
Referenced by SplitterBehavior().
CaptureKeyboardFromApp()
void ImGui::CaptureKeyboardFromApp (bool capture = true)
References GImGui, and ImGuiContext::WantCaptureKeyboardNextFrame.
CaptureMouseFromApp()
void ImGui::CaptureMouseFromApp (bool capture = true)
References GImGui, and ImGuiContext::WantCaptureMouseNextFrame.
GetClipboardText()
const char * ImGui::GetClipboardText ()
References ImGuiIO::ClipboardUserData, ImGuiIO::GetClipboardTextFn, GImGui, and ImGuiContext::IO.
Referenced by InputTextEx().
SetClipboardText()
void ImGui::SetClipboardText (const char * text)
References ImGuiIO::ClipboardUserData, GImGui, ImGuiContext::IO, and ImGuiIO::SetClipboardTextFn.
Referenced by ColorEditOptionsPopup(), InputTextEx(), and LogFinish().
SetAllocatorFunctions()
void ImGui::SetAllocatorFunctions (void *(*)(size_t sz, void *user_data) alloc_func, void(*)(void *ptr, void *user_data) free_func, void * user_data = NULL)
References GImAllocatorAllocFunc, GImAllocatorFreeFunc, and GImAllocatorUserData.
MemAlloc()
void * ImGui::MemAlloc (size_t size)
References GImAllocatorActiveAllocationsCount, GImAllocatorAllocFunc, and GImAllocatorUserData.
Referenced by ImFontAtlas::AddFont(), ImFontAtlas::AddFontFromMemoryCompressedBase85TTF(), ImFontAtlas::AddFontFromMemoryCompressedTTF(), ImFontAtlas::GetTexDataAsRGBA32(), ImFileLoadToMemory(), ImFontAtlasBuildWithStbTruetype(), ImStrdup(), InputTextEx(), and ImVector< ImGuiStorage::Pair >::reserve().
MemFree()
void ImGui::MemFree (void * ptr)
References GImAllocatorActiveAllocationsCount, GImAllocatorFreeFunc, and GImAllocatorUserData.
Referenced by ImFontAtlas::AddFontFromMemoryCompressedBase85TTF(), ImVector< ImGuiStorage::Pair >::clear(), ImFontAtlas::ClearInputData(), ImFontAtlas::ClearTexData(), IM_DELETE(), ImFileLoadToMemory(), ImFontAtlasBuildWithStbTruetype(), InputTextEx(), LoadIniSettingsFromDisk(), LoadIniSettingsFromMemory(), ImVector< ImGuiStorage::Pair >::reserve(), and ImVector< ImGuiStorage::Pair >::~ImVector().
IsAnyWindowFocused()
static bool ImGui::IsAnyWindowFocused () inline static
References ImGuiFocusedFlags_AnyWindow, and IsWindowFocused().
IsAnyWindowHovered()
static bool ImGui::IsAnyWindowHovered () inline static
References ImGuiHoveredFlags_AnyWindow, and IsWindowHovered().
CalcItemRectClosestPoint()
static ImVec2 ImGui::CalcItemRectClosestPoint (const ImVec2 & pos, bool on_edge = false, float outward = 0.f) inline static
References IM_ASSERT.
ShowTestWindow()
static void ImGui::ShowTestWindow () inline static
References ShowDemoWindow().
IsRootWindowFocused()
static bool ImGui::IsRootWindowFocused () inline static
References ImGuiFocusedFlags_RootWindow, and IsWindowFocused().
IsRootWindowOrAnyChildFocused()
static bool ImGui::IsRootWindowOrAnyChildFocused () inline static
References ImGuiFocusedFlags_RootAndChildWindows, and IsWindowFocused().
SetNextWindowContentWidth()
static void ImGui::SetNextWindowContentWidth (float w) inline static
References SetNextWindowContentSize().
GetItemsLineHeightWithSpacing()
static float ImGui::GetItemsLineHeightWithSpacing () inline static
References GetFrameHeightWithSpacing().
Begin() [2/2]
bool ImGui::Begin (const char * name, bool * p_open, const ImVec2 & size_on_first_use, float bg_alpha_override = -1.0f, ImGuiWindowFlags flags = 0)
References Begin(), ImGuiCond_FirstUseEver, setup::name, SetNextWindowBgAlpha(), SetNextWindowSize(), ImVec2::x, and ImVec2::y.
IsRootWindowOrAnyChildHovered()
static bool ImGui::IsRootWindowOrAnyChildHovered () inline static
References ImGuiHoveredFlags_RootAndChildWindows, and IsWindowHovered().
AlignFirstTextHeightToWidgets()
static void ImGui::AlignFirstTextHeightToWidgets () inline static
References AlignTextToFramePadding().
SetNextWindowPosCenter()
static void ImGui::SetNextWindowPosCenter (ImGuiCond c = 0) inline static
References ImGuiIO::DisplaySize, GetIO(), SetNextWindowPos(), ImVec2::x, and ImVec2::y.
IsItemHoveredRect()
static bool ImGui::IsItemHoveredRect () inline static
References ImGuiHoveredFlags_RectOnly, and IsItemHovered().
IsPosHoveringAnyWindow()
static bool ImGui::IsPosHoveringAnyWindow (const ImVec2 &) inline static
References IM_ASSERT.
IsMouseHoveringAnyWindow()
static bool ImGui::IsMouseHoveringAnyWindow () inline static
References ImGuiHoveredFlags_AnyWindow, and IsWindowHovered().
IsMouseHoveringWindow()
static bool ImGui::IsMouseHoveringWindow () inline static
References ImGuiHoveredFlags_AllowWhenBlockedByActiveItem, ImGuiHoveredFlags_AllowWhenBlockedByPopup, and IsWindowHovered().
CollapsingHeader() [3/3]
static bool ImGui::CollapsingHeader (const char * label, const char * str_id, bool framed = true, bool default_open = false) inline static
References CollapsingHeader().
NavUpdate()
static void ImGui::NavUpdate () static
References ImGuiContext::ActiveId, ImGuiContext::ActiveIdAllowNavDirFlags, ImDrawList::AddCircleFilled(), ImDrawList::AddRect(), ImDrawList::AddText(), ImVector< T >::back(), ImGuiWindow::CalcFontSize(), ImGuiWindow::ChildId, ImGuiNavMoveResult::Clear(), ClearActiveID(), ImRect::ClipWith(), ClosePopupToLevel(), ImGuiIO::ConfigFlags, ImRect::Contains(), ImGuiWindow::DC, ImGuiIO::DeltaTime, ImGuiNavMoveResult::DistBox, ImGuiNavMoveResult::DistCenter, ImRect::Expand(), ImGuiWindow::Flags, FocusWindow(), ImGuiContext::FrameCount, ImRect::GetHeight(), GetNavInputAmount2d(), GetViewportRect(), ImRect::GetWidth(), GImGui, ImGuiWindow::HiddenFrames, ImGuiNavMoveResult::ID, IM_ARRAYSIZE, IM_ASSERT, IM_COL32, ImFloor(), ImFormatString(), ImGuiConfigFlags_NavEnableGamepad, ImGuiConfigFlags_NavEnableKeyboard, ImGuiConfigFlags_NavMoveMouse, ImGuiDir_Down, ImGuiDir_Left, ImGuiDir_None, ImGuiDir_Right, ImGuiDir_Up, ImGuiInputReadMode_Down, ImGuiInputReadMode_Pressed, ImGuiInputReadMode_Repeat, ImGuiKey_DownArrow, ImGuiKey_Enter, ImGuiKey_Escape, ImGuiKey_LeftArrow, ImGuiKey_RightArrow, ImGuiKey_Space, ImGuiKey_UpArrow, ImGuiNavDirSourceFlags_PadLStick, ImGuiNavForward_ForwardActive, ImGuiNavForward_ForwardQueued, ImGuiNavForward_None, ImGuiNavInput_Activate, ImGuiNavInput_Cancel, ImGuiNavInput_COUNT, ImGuiNavInput_DpadDown, ImGuiNavInput_DpadLeft, ImGuiNavInput_DpadRight, ImGuiNavInput_DpadUp, ImGuiNavInput_Input, ImGuiNavInput_InternalStart_, ImGuiNavInput_KeyDown_, ImGuiNavInput_KeyLeft_, ImGuiNavInput_KeyMenu_, ImGuiNavInput_KeyRight_, ImGuiNavInput_KeyUp_, ImGuiNavInput_TweakFast, ImGuiNavInput_TweakSlow, ImGuiWindowFlags_ChildWindow, ImGuiWindowFlags_Modal, ImGuiWindowFlags_NoNavInputs, ImGuiWindowFlags_Popup, ImMin(), ImGuiWindow::InnerRect, ImGuiContext::IO, ImRect::IsInverted(), IsNavInputDown(), IsNavInputPressed(), IsNavInputPressedAnyOfTwo(), ImGuiIO::KeyAlt, ImGuiIO::KeyCtrl, ImGuiIO::KeyShift, ImRect::Max, memcpy(), memset(), ImRect::Min, ImGuiIO::MousePos, ImGuiIO::MousePosPrev, ImGuiWindow::Name, NAV_MAP_KEY, ImGuiContext::NavActivateDownId, ImGuiContext::NavActivateId, ImGuiContext::NavActivatePressedId, ImGuiIO::NavActive, NavCalcPreferredMousePos(), ImGuiContext::NavDisableHighlight, ImGuiContext::NavDisableMouseHover, ImGuiDrawContext::NavHasScroll, ImGuiContext::NavId, ImGuiContext::NavIdIsAlive, ImGuiContext::NavInitRequest, ImGuiContext::NavInitRequestFromMove, ImGuiContext::NavInitResultId, ImGuiContext::NavInitResultRectRel, ImGuiContext::NavInputId, ImGuiIO::NavInputs, ImGuiIO::NavInputsDownDuration, ImGuiIO::NavInputsDownDurationPrev, ImGuiContext::NavJustMovedToId, ImGuiContext::NavJustTabbedId, ImGuiWindow::NavLastChildNavWindow, ImGuiWindow::NavLastIds, ImGuiContext::NavLayer, ImGuiDrawContext::NavLayerActiveMask, ImGuiContext::NavMousePosDirty, ImGuiContext::NavMoveDir, ImGuiContext::NavMoveDirLast, ImGuiContext::NavMoveFromClampedRefRect, ImGuiContext::NavMoveRequest, ImGuiContext::NavMoveRequestForward, ImGuiContext::NavMoveResultLocal, ImGuiContext::NavMoveResultOther, ImGuiContext::NavNextActivateId, ImGuiWindow::NavRectRel, NavRestoreLayer(), NavSaveLastChildNavWindow(), ImGuiContext::NavScoringCount, ImGuiContext::NavScoringRectScreen, NavScrollToBringItemIntoView(), NavUpdateAnyRequestFlag(), NavUpdateWindowing(), ImGuiIO::NavVisible, ImGuiContext::NavWindow, ImGuiContext::NavWindowingTarget, NULL, ImGuiContext::OpenPopupStack, ImGuiContext::OverlayDrawList, ImGuiWindow::ParentWindow, ImGuiWindow::Pos, ImGuiNavMoveResult::RectRel, ImGuiWindow::Scroll, ImGuiWindow::ScrollbarX, SetNavID(), SetNavIDAndMoveMouse(), SetWindowScrollX(), SetWindowScrollY(), ImVector< T >::Size, ImGuiIO::WantMoveMouse, ImGuiPopupRef::Window, ImGuiNavMoveResult::Window, ImVec2::x, and ImVec2::y.
Referenced by NewFrame().
NavUpdateWindowing()
static void ImGui::NavUpdateWindowing () static
References ImGuiContext::ActiveId, ImGuiContext::ActiveIdAllowOverlap, ClosePopupsOverWindow(), ImGuiIO::ConfigFlags, ImGuiWindow::DC, ImGuiIO::DeltaTime, ImGuiIO::DisplayFramebufferScale, false, FindWindowNavigable(), ImGuiWindow::Flags, FocusWindow(), GetNavInputAmount2d(), GImGui, ImFloor(), ImGuiConfigFlags_NavEnableKeyboard, ImGuiInputReadMode_Down, ImGuiInputReadMode_Pressed, ImGuiInputReadMode_Released, ImGuiInputReadMode_RepeatSlow, ImGuiInputSource_NavGamepad, ImGuiInputSource_NavKeyboard, ImGuiKey_Tab, ImGuiNavDirSourceFlags_Keyboard, ImGuiNavDirSourceFlags_PadLStick, ImGuiNavInput_FocusNext, ImGuiNavInput_FocusPrev, ImGuiNavInput_KeyMenu_, ImGuiNavInput_Menu, ImGuiWindowFlags_ChildMenu, ImGuiWindowFlags_ChildWindow, ImGuiWindowFlags_NoMove, ImGuiWindowFlags_Popup, ImMax(), ImMin(), ImSaturate(), ImGuiContext::IO, IsKeyPressedMap(), IsMousePosValid(), IsNavInputDown(), IsNavInputPressed(), ImGuiIO::KeyCtrl, ImGuiIO::KeyShift, MarkIniSettingsDirty(), ImGuiIO::MousePos, ImGuiIO::MousePosPrev, ImGuiContext::NavDisableHighlight, ImGuiContext::NavDisableMouseHover, NavInitWindow(), ImGuiWindow::NavLastChildNavWindow, ImGuiWindow::NavLastIds, ImGuiContext::NavLayer, ImGuiDrawContext::NavLayerActiveMask, NavRestoreLastChildNavWindow(), NavRestoreLayer(), NavUpdateWindowingHighlightWindow(), ImGuiContext::NavWindow, ImGuiContext::NavWindowingHighlightAlpha, ImGuiContext::NavWindowingHighlightTimer, ImGuiContext::NavWindowingInputSource, ImGuiContext::NavWindowingTarget, ImGuiContext::NavWindowingToggleLayer, NULL, ImGuiWindow::ParentWindow, ImGuiWindow::PosFloat, ImGuiWindow::RootWindowForTabbing, ImVector< T >::Size, ImGuiContext::Windows, ImVec2::x, and ImVec2::y.
Referenced by NavUpdate().
NavProcessItem()
static void ImGui::NavProcessItem (ImGuiWindow * window, const ImRect & nav_bb, const ImGuiID id) static
References ImVector< T >::back(), ImGuiWindow::DC, ImGuiWindow::FocusIdxTabCounter, GImGui, ImGuiNavMoveResult::ID, ImGuiWindow::IDStack, IMGUI_DEBUG_NAV_SCORING, ImGuiItemFlags_NoNav, ImGuiItemFlags_NoNavDefaultFocus, ImGuiDrawContext::ItemFlags, ImRect::Max, ImRect::Min, ImGuiContext::NavId, ImGuiContext::NavIdIsAlive, ImGuiContext::NavIdTabCounter, ImGuiContext::NavInitRequest, ImGuiContext::NavInitResultId, ImGuiContext::NavInitResultRectRel, ImGuiContext::NavLayer, ImGuiDrawContext::NavLayerCurrent, ImGuiContext::NavMoveDir, ImGuiContext::NavMoveDirLast, ImGuiContext::NavMoveRequest, ImGuiContext::NavMoveResultLocal, ImGuiContext::NavMoveResultOther, ImGuiWindow::NavRectRel, NavScoreItem(), NavUpdateAnyRequestFlag(), ImGuiContext::NavWindow, ImGuiNavMoveResult::ParentID, ImGuiWindow::Pos, ImGuiNavMoveResult::RectRel, and ImGuiNavMoveResult::Window.
Referenced by ItemAdd().
UpdateMovingWindow()
static void ImGui::UpdateMovingWindow () static
References ImGuiContext::ActiveId, ImGuiContext::ActiveIdClickOffset, ImGuiContext::ActiveIdSource, ImGuiContext::ActiveIdWindow, ClearActiveID(), FocusWindow(), GImGui, IM_ASSERT, ImGuiInputSource_Mouse, ImGuiContext::IO, KeepAliveID(), MarkIniSettingsDirty(), ImGuiIO::MouseDown, ImGuiIO::MousePos, ImGuiWindow::MoveId, ImGuiContext::MovingWindow, NULL, ImGuiWindow::PosFloat, ImGuiWindow::RootWindow, ImVec2::x, and ImVec2::y.
Referenced by NewFrame().
UpdateManualResize()
static void ImGui::UpdateManualResize (ImGuiWindow * window, const ImVec2 & size_auto_fit, int * border_held, int resize_grip_count, ImU32 resize_grip_col[4]) static
References ImGuiContext::ActiveIdClickOffset, ImGuiWindow::AutoFitFramesX, ImGuiWindow::AutoFitFramesY, ButtonBehavior(), CalcResizePosSizeFromAnyCorner(), CalcSizeAfterConstraint(), ClearActiveID(), ImGuiResizeGripDef::CornerPos, ImGuiIO::DeltaTime, ImGuiIO::DisplayFramebufferScale, ImRect::FixInverted(), ImGuiWindow::Flags, FLT_MAX, ImGuiContext::FontSize, GetBorderRect(), GetColorU32(), ImGuiWindow::GetID(), GetNavInputAmount2d(), ImRect::GetSize(), GImGui, ImGuiContext::HoveredIdTimer, ImGuiContext::HoveredWindow, ImFloor(), ImGuiButtonFlags_FlattenChildren, ImGuiButtonFlags_NoNavFocus, ImGuiCol_ResizeGrip, ImGuiCol_ResizeGripActive, ImGuiCol_ResizeGripHovered, ImGuiInputReadMode_Down, ImGuiInputSource_NavGamepad, ImGuiInputSource_NavKeyboard, ImGuiMouseCursor_ResizeEW, ImGuiMouseCursor_ResizeNESW, ImGuiMouseCursor_ResizeNS, ImGuiMouseCursor_ResizeNWSE, ImGuiNavDirSourceFlags_Keyboard, ImGuiNavDirSourceFlags_PadDPad, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoResize, ImGuiWindowFlags_ResizeFromAnySide, ImLerp(), ImMax(), ImMin(), ImGuiResizeGripDef::InnerDir, ImGuiContext::IO, ImGuiIO::KeyShift, MarkIniSettingsDirty(), ImGuiContext::MouseCursor, ImGuiIO::MouseDoubleClicked, ImGuiIO::MousePos, ImGuiContext::NavDisableMouseHover, ImGuiContext::NavWindowingInputSource, ImGuiContext::NavWindowingTarget, ImGuiContext::NavWindowingToggleLayer, PopID(), ImGuiWindow::Pos, ImGuiWindow::PosFloat, PushID(), resize_grip_def, ImGuiWindow::Size, ImGuiWindow::SizeFull, ImGuiWindow::WindowRounding, ImVec2::x, and ImVec2::y.
Referenced by Begin().
FocusFrontMostActiveWindow()
void ImGui::FocusFrontMostActiveWindow (ImGuiWindow * ignore_window) static
References FocusWindow(), GImGui, ImGuiWindowFlags_ChildWindow, NavRestoreLastChildNavWindow(), ImVector< T >::Size, and ImGuiContext::Windows.
Referenced by EndMainMenuBar(), and NewFrame().