Aurora Framework: UTF32LE< CharType > Struct Template Reference
UTF32LE< CharType > Struct Template Reference
UTF-32 little endian enocoding.
Public Types
enum { supportUnicode = 1 }
typedef CharType Ch
Public Member Functions
RAPIDJSON_STATIC_ASSERT (sizeof(Ch) >=4)
Static Public Member Functions
template<typename InputStream >
static bool Decode (InputStream &is, unsigned *codepoint)
template<typename OutputStream >
static void Encode (OutputStream &os, unsigned codepoint)
template<typename OutputStream >
static void EncodeUnsafe (OutputStream &os, unsigned codepoint)
template<typename OutputByteStream >
static void Put (OutputByteStream &os, CharType c)
template<typename OutputByteStream >
static void PutBOM (OutputByteStream &os)
template<typename InputByteStream >
static CharType Take (InputByteStream &is)
template<typename InputByteStream >
static CharType TakeBOM (InputByteStream &is)
template<typename InputStream , typename OutputStream >
static bool Validate (InputStream &is, OutputStream &os)
Detailed Description
template<typename CharType = unsigned>
struct UTF32LE< CharType >
UTF-32 little endian enocoding.
Member Typedef Documentation
Ch
template<typename CharType = unsigned> typedef CharType UTF32< CharType >::Ch inherited
Member Enumeration Documentation
anonymous enum
template<typename CharType = unsigned> anonymous enum inherited
Enumerator
supportUnicode
Member Function Documentation
TakeBOM()
template<typename CharType = unsigned> template<typename InputByteStream > static CharType UTF32LE< CharType >::TakeBOM (InputByteStream & is) inline static
References UTF32< CharType >::RAPIDJSON_STATIC_ASSERT(), and UTF32LE< CharType >::Take().
Take()
template<typename CharType = unsigned> template<typename InputByteStream > static CharType UTF32LE< CharType >::Take (InputByteStream & is) inline static
References UTF32< CharType >::RAPIDJSON_STATIC_ASSERT().
Referenced by UTF32LE< CharType >::TakeBOM().
PutBOM()
template<typename CharType = unsigned> template<typename OutputByteStream > static void UTF32LE< CharType >::PutBOM (OutputByteStream & os) inline static
References UTF32< CharType >::RAPIDJSON_STATIC_ASSERT().
Put()
template<typename CharType = unsigned> template<typename OutputByteStream > static void UTF32LE< CharType >::Put (OutputByteStream & os, CharType c) inline static
References UTF32< CharType >::RAPIDJSON_STATIC_ASSERT().
RAPIDJSON_STATIC_ASSERT()
template<typename CharType = unsigned> UTF32< CharType >::RAPIDJSON_STATIC_ASSERT (sizeof(Ch) >= 4) inherited
Referenced by UTF32< CharType >::Decode(), UTF32< CharType >::Encode(), UTF32< CharType >::EncodeUnsafe(), UTF32LE< CharType >::Put(), UTF32BE< CharType >::Put(), UTF32LE< CharType >::PutBOM(), UTF32BE< CharType >::PutBOM(), UTF32LE< CharType >::Take(), UTF32BE< CharType >::Take(), UTF32LE< CharType >::TakeBOM(), UTF32BE< CharType >::TakeBOM(), and UTF32< CharType >::Validate().
Encode()
template<typename CharType = unsigned> template<typename OutputStream > static void UTF32< CharType >::Encode (OutputStream & os, unsigned codepoint) inline static inherited
References RAPIDJSON_ASSERT, and UTF32< CharType >::RAPIDJSON_STATIC_ASSERT().
EncodeUnsafe()
template<typename CharType = unsigned> template<typename OutputStream > static void UTF32< CharType >::EncodeUnsafe (OutputStream & os, unsigned codepoint) inline static inherited
References PutUnsafe(), RAPIDJSON_ASSERT, and UTF32< CharType >::RAPIDJSON_STATIC_ASSERT().
Decode()
template<typename CharType = unsigned> template<typename InputStream > static bool UTF32< CharType >::Decode (InputStream & is, unsigned * codepoint) inline static inherited
References UTF32< CharType >::RAPIDJSON_STATIC_ASSERT().
Validate()
template<typename CharType = unsigned> template<typename InputStream , typename OutputStream > static bool UTF32< CharType >::Validate (InputStream & is, OutputStream & os) inline static inherited
References UTF32< CharType >::RAPIDJSON_STATIC_ASSERT().
The documentation for this struct was generated from the following file:
encodings.h