Aurora Framework: SndfileHandle Class Reference
SndfileHandle Class Reference
Public Member Functions
SndfileHandle (void)
SndfileHandle (const char *path, int mode=SFM_READ, int format=0, int channels=0, int samplerate=0)
SndfileHandle (std::string const &path, int mode=SFM_READ, int format=0, int channels=0, int samplerate=0)
SndfileHandle (int fd, bool close_desc, int mode=SFM_READ, int format=0, int channels=0, int samplerate=0)
SndfileHandle (SF_VIRTUAL_IO &sfvirtual, void *user_data, int mode=SFM_READ, int format=0, int channels=0, int samplerate=0)
SndfileHandle (const SndfileHandle &orig)
~SndfileHandle (void)
int channels (void) const
int command (int cmd, void *data, int datasize)
int error (void) const
int format (void) const
sf_count_t frames (void) const
const char * getString (int str_type) const
operator bool () const
SndfileHandle & operator= (const SndfileHandle &rhs)
bool operator== (const SndfileHandle &rhs) const
SNDFILE * rawHandle (void)
Take ownership of handle, if reference count is 1.
sf_count_t read (short *ptr, sf_count_t items)
sf_count_t read (int *ptr, sf_count_t items)
sf_count_t read (float *ptr, sf_count_t items)
sf_count_t read (double *ptr, sf_count_t items)
sf_count_t readf (short *ptr, sf_count_t frames)
sf_count_t readf (int *ptr, sf_count_t frames)
sf_count_t readf (float *ptr, sf_count_t frames)
sf_count_t readf (double *ptr, sf_count_t frames)
sf_count_t readRaw (void *ptr, sf_count_t bytes)
int refCount (void) const
int samplerate (void) const
sf_count_t seek (sf_count_t frames, int whence)
int setString (int str_type, const char *str)
const char * strError (void) const
SNDFILE * takeOwnership (void)
sf_count_t write (const short *ptr, sf_count_t items)
sf_count_t write (const int *ptr, sf_count_t items)
sf_count_t write (const float *ptr, sf_count_t items)
sf_count_t write (const double *ptr, sf_count_t items)
sf_count_t writef (const short *ptr, sf_count_t frames)
sf_count_t writef (const int *ptr, sf_count_t frames)
sf_count_t writef (const float *ptr, sf_count_t frames)
sf_count_t writef (const double *ptr, sf_count_t frames)
sf_count_t writeRaw (const void *ptr, sf_count_t bytes)
Raw access to the handle.
void writeSync (void)
Static Public Member Functions
static int formatCheck (int format, int channels, int samplerate)
Constructor & Destructor Documentation
SndfileHandle() [1/6]
SndfileHandle::SndfileHandle (void) inline
SndfileHandle() [2/6]
SndfileHandle::SndfileHandle (const char * path, int mode = SFM_READ, int format = 0, int channels = 0, int samplerate = 0) inline
References mode(), NULL, and sf_open().
SndfileHandle() [3/6]
SndfileHandle::SndfileHandle (std::string const & path, int mode = SFM_READ, int format = 0, int channels = 0, int samplerate = 0) inline
References mode(), NULL, and sf_open().
SndfileHandle() [4/6]
SndfileHandle::SndfileHandle (int fd, bool close_desc, int mode = SFM_READ, int format = 0, int channels = 0, int samplerate = 0) inline
References mode(), NULL, and sf_open_fd().
SndfileHandle() [5/6]
SndfileHandle::SndfileHandle (SF_VIRTUAL_IO & sfvirtual, void * user_data, int mode = SFM_READ, int format = 0, int channels = 0, int samplerate = 0) inline
References mode(), NULL, and sf_open_virtual().
~SndfileHandle()
SndfileHandle::~SndfileHandle (void) inline
References NULL.
SndfileHandle() [6/6]
SndfileHandle::SndfileHandle (const SndfileHandle & orig) inline
References NULL.
Member Function Documentation
operator=()
SndfileHandle & SndfileHandle::operator= (const SndfileHandle & rhs) inline
References NULL.
refCount()
int SndfileHandle::refCount (void) const inline
References NULL.
operator bool()
SndfileHandle::operator bool () const inline
References NULL.
operator==()
bool SndfileHandle::operator== (const SndfileHandle & rhs) const inline
frames()
sf_count_t SndfileHandle::frames (void) const inline
format()
int SndfileHandle::format (void) const inline
channels()
int SndfileHandle::channels (void) const inline
samplerate()
int SndfileHandle::samplerate (void) const inline
error()
int SndfileHandle::error (void) const inline
References sf_error().
strError()
const char * SndfileHandle::strError (void) const inline
References sf_strerror().
command()
int SndfileHandle::command (int cmd, void * data, int datasize) inline
References sf_command().
seek()
sf_count_t SndfileHandle::seek (sf_count_t frames, int whence) inline
References sf_seek().
writeSync()
void SndfileHandle::writeSync (void) inline
References sf_write_sync().
setString()
int SndfileHandle::setString (int str_type, const char * str) inline
References sf_set_string().
getString()
const char * SndfileHandle::getString (int str_type) const inline
References sf_get_string().
formatCheck()
int SndfileHandle::formatCheck (int format, int channels, int samplerate) inline static
References sf_format_check().
read() [1/4]
sf_count_t SndfileHandle::read (short * ptr, sf_count_t items) inline
References sf_read_short().
read() [2/4]
sf_count_t SndfileHandle::read (int * ptr, sf_count_t items) inline
References sf_read_int().
read() [3/4]
sf_count_t SndfileHandle::read (float * ptr, sf_count_t items) inline
References sf_read_float().
read() [4/4]
sf_count_t SndfileHandle::read (double * ptr, sf_count_t items) inline
References sf_read_double().
write() [1/4]
sf_count_t SndfileHandle::write (const short * ptr, sf_count_t items) inline
References sf_write_short().
write() [2/4]
sf_count_t SndfileHandle::write (const int * ptr, sf_count_t items) inline
References sf_write_int().
write() [3/4]
sf_count_t SndfileHandle::write (const float * ptr, sf_count_t items) inline
References sf_write_float().
write() [4/4]
sf_count_t SndfileHandle::write (const double * ptr, sf_count_t items) inline
References sf_write_double().
readf() [1/4]
sf_count_t SndfileHandle::readf (short * ptr, sf_count_t frames) inline
References sf_readf_short().
readf() [2/4]
sf_count_t SndfileHandle::readf (int * ptr, sf_count_t frames) inline
References sf_readf_int().
readf() [3/4]
sf_count_t SndfileHandle::readf (float * ptr, sf_count_t frames) inline
References sf_readf_float().
readf() [4/4]
sf_count_t SndfileHandle::readf (double * ptr, sf_count_t frames) inline
References sf_readf_double().
writef() [1/4]
sf_count_t SndfileHandle::writef (const short * ptr, sf_count_t frames) inline
References sf_writef_short().
writef() [2/4]
sf_count_t SndfileHandle::writef (const int * ptr, sf_count_t frames) inline
References sf_writef_int().
writef() [3/4]
sf_count_t SndfileHandle::writef (const float * ptr, sf_count_t frames) inline
References sf_writef_float().
writef() [4/4]
sf_count_t SndfileHandle::writef (const double * ptr, sf_count_t frames) inline
References sf_writef_double().
readRaw()
sf_count_t SndfileHandle::readRaw (void * ptr, sf_count_t bytes) inline
References sf_read_raw().
writeRaw()
sf_count_t SndfileHandle::writeRaw (const void * ptr, sf_count_t bytes) inline
Raw access to the handle.
SndfileHandle keeps ownership.
References sf_write_raw().
rawHandle()
SNDFILE * SndfileHandle::rawHandle (void) inline
Take ownership of handle, if reference count is 1.
References NULL.
takeOwnership()
SNDFILE * SndfileHandle::takeOwnership (void) inline
References NULL.
The documentation for this class was generated from the following file:
sndfile.hh