Aurora Framework: Internal.h File Reference
Internal.h File Reference
Classes
struct _GLFWcontext
struct _GLFWctxconfig
struct _GLFWcursor
struct _GLFWerror
struct _GLFWfbconfig
struct _GLFWinitconfig
struct _GLFWjoystick
struct _GLFWlibrary
struct _GLFWmapelement
struct _GLFWmapping
struct _GLFWmonitor
struct _GLFWmutex
struct _GLFWtls
struct _GLFWwindow
struct _GLFWwndconfig
struct VkExtensionProperties
Macros
#define _GLFW_CONCAT_VERSION(m, n, r) #m "." #n "." #r
#define _GLFW_INSERT_FIRST 0
#define _GLFW_INSERT_LAST 1
#define _GLFW_MAKE_VERSION(m, n, r) _GLFW_CONCAT_VERSION(m, n, r)
#define _GLFW_MESSAGE_SIZE 1024
#define _GLFW_POLL_ALL (_GLFW_POLL_AXES | _GLFW_POLL_BUTTONS)
#define _GLFW_POLL_AXES 1
#define _GLFW_POLL_BUTTONS 2
#define _GLFW_POLL_PRESENCE 0
#define _GLFW_REQUIRE_INIT()
#define _GLFW_REQUIRE_INIT_OR_RETURN(x)
#define _GLFW_SWAP_POINTERS(x, y)
#define _GLFW_VERSION_NUMBER
#define GL_COLOR_BUFFER_BIT 0x00004000
#define GL_CONTEXT_COMPATIBILITY_PROFILE_BIT 0x00000002
#define GL_CONTEXT_CORE_PROFILE_BIT 0x00000001
#define GL_CONTEXT_FLAG_DEBUG_BIT 0x00000002
#define GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT 0x00000001
#define GL_CONTEXT_FLAG_NO_ERROR_BIT_KHR 0x00000008
#define GL_CONTEXT_FLAGS 0x821e
#define GL_CONTEXT_PROFILE_MASK 0x9126
#define GL_CONTEXT_RELEASE_BEHAVIOR 0x82fb
#define GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH 0x82fc
#define GL_EXTENSIONS 0x1f03
#define GL_LOSE_CONTEXT_ON_RESET_ARB 0x8252
#define GL_NO_RESET_NOTIFICATION_ARB 0x8261
#define GL_NONE 0
#define GL_NUM_EXTENSIONS 0x821d
#define GL_RESET_NOTIFICATION_STRATEGY_ARB 0x8256
#define GL_UNSIGNED_BYTE 0x1401
#define GL_VERSION 0x1f02
#define GLFW_INCLUDE_NONE
#define VK_NULL_HANDLE 0
Typedefs
typedef struct _GLFWcontext _GLFWcontext
typedef struct _GLFWctxconfig _GLFWctxconfig
typedef struct _GLFWcursor _GLFWcursor
typedef void(* _GLFWdestroycontextfun) (_GLFWwindow *)
typedef struct _GLFWerror _GLFWerror
typedef int(* _GLFWextensionsupportedfun) (const char *)
typedef struct _GLFWfbconfig _GLFWfbconfig
typedef GLFWglproc(* _GLFWgetprocaddressfun) (const char *)
typedef struct _GLFWinitconfig _GLFWinitconfig
typedef struct _GLFWjoystick _GLFWjoystick
typedef struct _GLFWlibrary _GLFWlibrary
typedef void(* _GLFWmakecontextcurrentfun) (_GLFWwindow *)
typedef struct _GLFWmapelement _GLFWmapelement
typedef struct _GLFWmapping _GLFWmapping
typedef struct _GLFWmonitor _GLFWmonitor
typedef struct _GLFWmutex _GLFWmutex
typedef void(* _GLFWswapbuffersfun) (_GLFWwindow *)
typedef void(* _GLFWswapintervalfun) (int)
typedef struct _GLFWtls _GLFWtls
typedef struct _GLFWwindow _GLFWwindow
typedef struct _GLFWwndconfig _GLFWwndconfig
typedef unsigned int GLbitfield
typedef unsigned int GLenum
typedef int GLFWbool
typedef int GLint
typedef unsigned char GLubyte
typedef unsigned int GLuint
typedef void(APIENTRY * PFN_vkVoidFunction) (void)
typedef void(APIENTRY * PFNGLCLEARPROC) (GLbitfield)
typedef void(APIENTRY * PFNGLGETINTEGERVPROC) (GLenum, GLint *)
typedef const GLubyte *(APIENTRY * PFNGLGETSTRINGIPROC) (GLenum, GLuint)
typedef const GLubyte *(APIENTRY * PFNGLGETSTRINGPROC) (GLenum)
typedef struct VkAllocationCallbacks VkAllocationCallbacks
typedef uint32_t VkBool32
typedef struct VkExtensionProperties VkExtensionProperties
typedef uint32_t VkFlags
typedef void * VkInstance
typedef void * VkPhysicalDevice
typedef enum VkResult VkResult
typedef enum VkStructureType VkStructureType
typedef uint64_t VkSurfaceKHR
Enumerations
enum VkResult {
VK_SUCCESS = 0, VK_NOT_READY = 1, VK_TIMEOUT = 2, VK_EVENT_SET = 3,
VK_EVENT_RESET = 4, VK_INCOMPLETE = 5, VK_ERROR_OUT_OF_HOST_MEMORY = -1, VK_ERROR_OUT_OF_DEVICE_MEMORY = -2,
VK_ERROR_INITIALIZATION_FAILED = -3, VK_ERROR_DEVICE_LOST = -4, VK_ERROR_MEMORY_MAP_FAILED = -5, VK_ERROR_LAYER_NOT_PRESENT = -6,
VK_ERROR_EXTENSION_NOT_PRESENT = -7, VK_ERROR_FEATURE_NOT_PRESENT = -8, VK_ERROR_INCOMPATIBLE_DRIVER = -9, VK_ERROR_TOO_MANY_OBJECTS = -10,
VK_ERROR_FORMAT_NOT_SUPPORTED = -11, VK_ERROR_SURFACE_LOST_KHR = -1000000000, VK_SUBOPTIMAL_KHR = 1000001003, VK_ERROR_OUT_OF_DATE_KHR = -1000001004,
VK_ERROR_INCOMPATIBLE_DISPLAY_KHR = -1000003001, VK_ERROR_NATIVE_WINDOW_IN_USE_KHR = -1000000001, VK_ERROR_VALIDATION_FAILED_EXT = -1000011001, VK_RESULT_MAX_ENUM = 0x7FFFFFFF
}
enum VkStructureType {
VK_STRUCTURE_TYPE_XLIB_SURFACE_CREATE_INFO_KHR = 1000004000, VK_STRUCTURE_TYPE_XCB_SURFACE_CREATE_INFO_KHR = 1000005000, VK_STRUCTURE_TYPE_WAYLAND_SURFACE_CREATE_INFO_KHR = 1000006000, VK_STRUCTURE_TYPE_MIR_SURFACE_CREATE_INFO_KHR = 1000007000,
VK_STRUCTURE_TYPE_WIN32_SURFACE_CREATE_INFO_KHR = 1000009000, VK_STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK = 1000123000, VK_STRUCTURE_TYPE_MAX_ENUM = 0x7FFFFFFF
}
Functions
char * _glfw_strdup (const char *source)
void _glfwAllocGammaArrays (GLFWgammaramp *ramp, unsigned int size)
_GLFWjoystick * _glfwAllocJoystick (const char *name, const char *guid, int axisCount, int buttonCount, int hatCount)
_GLFWmonitor * _glfwAllocMonitor (const char *name, int widthMM, int heightMM)
const _GLFWfbconfig * _glfwChooseFBConfig (const _GLFWfbconfig *desired, const _GLFWfbconfig *alternatives, unsigned int count)
const GLFWvidmode * _glfwChooseVideoMode (_GLFWmonitor *monitor, const GLFWvidmode *desired)
int _glfwCompareVideoModes (const GLFWvidmode *first, const GLFWvidmode *second)
void _glfwFreeGammaArrays (GLFWgammaramp *ramp)
void _glfwFreeJoystick (_GLFWjoystick *js)
void _glfwFreeMonitor (_GLFWmonitor *monitor)
const char * _glfwGetVulkanResultString (VkResult result)
GLFWbool _glfwInitVulkan (int mode)
void _glfwInputChar (_GLFWwindow *window, unsigned int codepoint, int mods, GLFWbool plain)
void _glfwInputCursorEnter (_GLFWwindow *window, GLFWbool entered)
void _glfwInputCursorPos (_GLFWwindow *window, double xpos, double ypos)
void _glfwInputDrop (_GLFWwindow *window, int count, const char **names)
void _glfwInputError (int code, const char *format,...)
void _glfwInputFramebufferSize (_GLFWwindow *window, int width, int height)
void _glfwInputJoystick (_GLFWjoystick *js, int event)
void _glfwInputJoystickAxis (_GLFWjoystick *js, int axis, float value)
void _glfwInputJoystickButton (_GLFWjoystick *js, int button, char value)
void _glfwInputJoystickHat (_GLFWjoystick *js, int hat, char value)
void _glfwInputKey (_GLFWwindow *window, int key, int scancode, int action, int mods)
void _glfwInputMonitor (_GLFWmonitor *monitor, int action, int placement)
void _glfwInputMonitorWindow (_GLFWmonitor *monitor, _GLFWwindow *window)
void _glfwInputMouseClick (_GLFWwindow *window, int button, int action, int mods)
void _glfwInputScroll (_GLFWwindow *window, double xoffset, double yoffset)
void _glfwInputWindowCloseRequest (_GLFWwindow *window)
void _glfwInputWindowContentScale (_GLFWwindow *window, float xscale, float yscale)
void _glfwInputWindowDamage (_GLFWwindow *window)
void _glfwInputWindowFocus (_GLFWwindow *window, GLFWbool focused)
void _glfwInputWindowIconify (_GLFWwindow *window, GLFWbool iconified)
void _glfwInputWindowMaximize (_GLFWwindow *window, GLFWbool maximized)
void _glfwInputWindowMonitor (_GLFWwindow *window, _GLFWmonitor *monitor)
void _glfwInputWindowPos (_GLFWwindow *window, int xpos, int ypos)
void _glfwInputWindowSize (_GLFWwindow *window, int width, int height)
GLFWbool _glfwIsValidContextConfig (const _GLFWctxconfig *ctxconfig)
int _glfwPlatformCreateCursor (_GLFWcursor *cursor, const GLFWimage *image, int xhot, int yhot)
GLFWbool _glfwPlatformCreateMutex (_GLFWmutex *mutex)
int _glfwPlatformCreateStandardCursor (_GLFWcursor *cursor, int shape)
GLFWbool _glfwPlatformCreateTls (_GLFWtls *tls)
int _glfwPlatformCreateWindow (_GLFWwindow *window, const _GLFWwndconfig *wndconfig, const _GLFWctxconfig *ctxconfig, const _GLFWfbconfig *fbconfig)
VkResult _glfwPlatformCreateWindowSurface (VkInstance instance, _GLFWwindow *window, const VkAllocationCallbacks *allocator, VkSurfaceKHR *surface)
void _glfwPlatformDestroyCursor (_GLFWcursor *cursor)
void _glfwPlatformDestroyMutex (_GLFWmutex *mutex)
void _glfwPlatformDestroyTls (_GLFWtls *tls)
void _glfwPlatformDestroyWindow (_GLFWwindow *window)
void _glfwPlatformFocusWindow (_GLFWwindow *window)
int _glfwPlatformFramebufferTransparent (_GLFWwindow *window)
void _glfwPlatformFreeMonitor (_GLFWmonitor *monitor)
const char * _glfwPlatformGetClipboardString (void)
void _glfwPlatformGetCursorPos (_GLFWwindow *window, double *xpos, double *ypos)
void _glfwPlatformGetFramebufferSize (_GLFWwindow *window, int *width, int *height)
void _glfwPlatformGetGammaRamp (_GLFWmonitor *monitor, GLFWgammaramp *ramp)
int _glfwPlatformGetKeyScancode (int key)
void _glfwPlatformGetMonitorContentScale (_GLFWmonitor *monitor, float *xscale, float *yscale)
void _glfwPlatformGetMonitorPos (_GLFWmonitor *monitor, int *xpos, int *ypos)
int _glfwPlatformGetPhysicalDevicePresentationSupport (VkInstance instance, VkPhysicalDevice device, uint32_t queuefamily)
void _glfwPlatformGetRequiredInstanceExtensions (char **extensions)
const char * _glfwPlatformGetScancodeName (int scancode)
uint64_t _glfwPlatformGetTimerFrequency (void)
uint64_t _glfwPlatformGetTimerValue (void)
void * _glfwPlatformGetTls (_GLFWtls *tls)
const char * _glfwPlatformGetVersionString (void)
void _glfwPlatformGetVideoMode (_GLFWmonitor *monitor, GLFWvidmode *mode)
GLFWvidmode * _glfwPlatformGetVideoModes (_GLFWmonitor *monitor, int *count)
void _glfwPlatformGetWindowContentScale (_GLFWwindow *window, float *xscale, float *yscale)
void _glfwPlatformGetWindowFrameSize (_GLFWwindow *window, int *left, int *top, int *right, int *bottom)
float _glfwPlatformGetWindowOpacity (_GLFWwindow *window)
void _glfwPlatformGetWindowPos (_GLFWwindow *window, int *xpos, int *ypos)
void _glfwPlatformGetWindowSize (_GLFWwindow *window, int *width, int *height)
void _glfwPlatformHideWindow (_GLFWwindow *window)
void _glfwPlatformIconifyWindow (_GLFWwindow *window)
int _glfwPlatformInit (void)
void _glfwPlatformLockMutex (_GLFWmutex *mutex)
void _glfwPlatformMaximizeWindow (_GLFWwindow *window)
void _glfwPlatformPollEvents (void)
int _glfwPlatformPollJoystick (_GLFWjoystick *js, int mode)
void _glfwPlatformPostEmptyEvent (void)
void _glfwPlatformRequestWindowAttention (_GLFWwindow *window)
void _glfwPlatformRestoreWindow (_GLFWwindow *window)
void _glfwPlatformSetClipboardString (const char *string)
void _glfwPlatformSetCursor (_GLFWwindow *window, _GLFWcursor *cursor)
void _glfwPlatformSetCursorMode (_GLFWwindow *window, int mode)
void _glfwPlatformSetCursorPos (_GLFWwindow *window, double xpos, double ypos)
void _glfwPlatformSetGammaRamp (_GLFWmonitor *monitor, const GLFWgammaramp *ramp)
void _glfwPlatformSetTls (_GLFWtls *tls, void *value)
void _glfwPlatformSetWindowAspectRatio (_GLFWwindow *window, int numer, int denom)
void _glfwPlatformSetWindowDecorated (_GLFWwindow *window, GLFWbool enabled)
void _glfwPlatformSetWindowFloating (_GLFWwindow *window, GLFWbool enabled)
void _glfwPlatformSetWindowIcon (_GLFWwindow *window, int count, const GLFWimage *images)
void _glfwPlatformSetWindowMonitor (_GLFWwindow *window, _GLFWmonitor *monitor, int xpos, int ypos, int width, int height, int refreshRate)
void _glfwPlatformSetWindowOpacity (_GLFWwindow *window, float opacity)
void _glfwPlatformSetWindowPos (_GLFWwindow *window, int xpos, int ypos)
void _glfwPlatformSetWindowResizable (_GLFWwindow *window, GLFWbool enabled)
void _glfwPlatformSetWindowSize (_GLFWwindow *window, int width, int height)
void _glfwPlatformSetWindowSizeLimits (_GLFWwindow *window, int minwidth, int minheight, int maxwidth, int maxheight)
void _glfwPlatformSetWindowTitle (_GLFWwindow *window, const char *title)
void _glfwPlatformShowWindow (_GLFWwindow *window)
void _glfwPlatformTerminate (void)
void _glfwPlatformUnlockMutex (_GLFWmutex *mutex)
void _glfwPlatformUpdateGamepadGUID (char *guid)
void _glfwPlatformWaitEvents (void)
void _glfwPlatformWaitEventsTimeout (double timeout)
int _glfwPlatformWindowFocused (_GLFWwindow *window)
int _glfwPlatformWindowHovered (_GLFWwindow *window)
int _glfwPlatformWindowIconified (_GLFWwindow *window)
int _glfwPlatformWindowMaximized (_GLFWwindow *window)
int _glfwPlatformWindowVisible (_GLFWwindow *window)
GLFWbool _glfwRefreshContextAttribs (_GLFWwindow *window, const _GLFWctxconfig *ctxconfig)
void _glfwSplitBPP (int bpp, int *red, int *green, int *blue)
GLFWbool _glfwStringInExtensionString (const char *string, const char *extensions)
void _glfwTerminateVulkan (void)
VkResult vkEnumerateInstanceExtensionProperties (const char *, uint32_t *, VkExtensionProperties *)
PFN_vkVoidFunction vkGetInstanceProcAddr (VkInstance, const char *)
Variables
_GLFWlibrary _glfw
Macro Definition Documentation
GLFW_INCLUDE_NONE
#define GLFW_INCLUDE_NONE
_GLFW_INSERT_FIRST
#define _GLFW_INSERT_FIRST 0
Referenced by _glfwInputMonitor(), _glfwPollMonitorsWin32(), and _glfwPollMonitorsX11().
_GLFW_INSERT_LAST
#define _GLFW_INSERT_LAST 1
Referenced by _glfwPollMonitorsMir(), _glfwPollMonitorsNS(), _glfwPollMonitorsWin32(), _glfwPollMonitorsX11(), and done().
_GLFW_POLL_PRESENCE
#define _GLFW_POLL_PRESENCE 0
Referenced by _glfwDetectJoystickDisconnectionWin32(), _glfwPlatformPollJoystick(), glfwGetGamepadName(), glfwGetJoystickGUID(), glfwGetJoystickName(), glfwJoystickIsGamepad(), and glfwJoystickPresent().
_GLFW_POLL_AXES
#define _GLFW_POLL_AXES 1
Referenced by _glfwPlatformPollJoystick(), and glfwGetJoystickAxes().
_GLFW_POLL_BUTTONS
#define _GLFW_POLL_BUTTONS 2
Referenced by _glfwPlatformPollJoystick(), glfwGetJoystickButtons(), and glfwGetJoystickHats().
_GLFW_POLL_ALL
#define _GLFW_POLL_ALL (_GLFW_POLL_AXES | _GLFW_POLL_BUTTONS)
Referenced by glfwGetGamepadState().
_GLFW_MESSAGE_SIZE
#define _GLFW_MESSAGE_SIZE 1024
Referenced by _glfwInputError(), _glfwInputErrorWin32(), and _glfwInputErrorX11().
GL_VERSION
#define GL_VERSION 0x1f02
Referenced by _glfwRefreshContextAttribs(), AuroraFW::GEngine::GL::getVersion(), and main().
GL_NONE
#define GL_NONE 0
Referenced by _glfwRefreshContextAttribs().
GL_COLOR_BUFFER_BIT
#define GL_COLOR_BUFFER_BIT 0x00004000
Referenced by _glfwRefreshContextAttribs(), display(), AuroraFW::GEngine::GLRenderer::getGLRendererBuffer(), and main().
GL_UNSIGNED_BYTE
#define GL_UNSIGNED_BYTE 0x1401
Referenced by AuroraFW::GEngine::GLImGuiLoader::createDeviceObjects(), makeContextCurrentOSMesa(), AuroraFW::GEngine::GLVertexBufferLayout::push(), AuroraFW::GEngine::GLImGuiLoader::renderDrawLists(), and AuroraFW::GEngine::GLVertexBufferElement::sizeOf().
GL_EXTENSIONS
#define GL_EXTENSIONS 0x1f03
Referenced by glfwExtensionSupported().
GL_NUM_EXTENSIONS
#define GL_NUM_EXTENSIONS 0x821d
Referenced by glfwExtensionSupported().
GL_CONTEXT_FLAGS
#define GL_CONTEXT_FLAGS 0x821e
Referenced by _glfwRefreshContextAttribs().
GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT
#define GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT 0x00000001
Referenced by _glfwRefreshContextAttribs().
GL_CONTEXT_FLAG_DEBUG_BIT
#define GL_CONTEXT_FLAG_DEBUG_BIT 0x00000002
Referenced by _glfwRefreshContextAttribs().
GL_CONTEXT_PROFILE_MASK
#define GL_CONTEXT_PROFILE_MASK 0x9126
Referenced by _glfwRefreshContextAttribs().
GL_CONTEXT_COMPATIBILITY_PROFILE_BIT
#define GL_CONTEXT_COMPATIBILITY_PROFILE_BIT 0x00000002
Referenced by _glfwRefreshContextAttribs().
GL_CONTEXT_CORE_PROFILE_BIT
#define GL_CONTEXT_CORE_PROFILE_BIT 0x00000001
Referenced by _glfwRefreshContextAttribs().
GL_RESET_NOTIFICATION_STRATEGY_ARB
#define GL_RESET_NOTIFICATION_STRATEGY_ARB 0x8256
Referenced by _glfwRefreshContextAttribs().
GL_LOSE_CONTEXT_ON_RESET_ARB
#define GL_LOSE_CONTEXT_ON_RESET_ARB 0x8252
Referenced by _glfwRefreshContextAttribs().
GL_NO_RESET_NOTIFICATION_ARB
#define GL_NO_RESET_NOTIFICATION_ARB 0x8261
Referenced by _glfwRefreshContextAttribs().
GL_CONTEXT_RELEASE_BEHAVIOR
#define GL_CONTEXT_RELEASE_BEHAVIOR 0x82fb
Referenced by _glfwRefreshContextAttribs().
GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH
#define GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH 0x82fc
Referenced by _glfwRefreshContextAttribs().
GL_CONTEXT_FLAG_NO_ERROR_BIT_KHR
#define GL_CONTEXT_FLAG_NO_ERROR_BIT_KHR 0x00000008
Referenced by _glfwRefreshContextAttribs().
VK_NULL_HANDLE
#define VK_NULL_HANDLE 0
Referenced by _glfwPlatformGetPhysicalDevicePresentationSupport(), glfwCreateWindowSurface(), and glfwGetPhysicalDevicePresentationSupport().
_GLFW_CONCAT_VERSION
#define _GLFW_CONCAT_VERSION (m, n, r) #m "." #n "." #r
_GLFW_MAKE_VERSION
#define _GLFW_MAKE_VERSION (m, n, r) _GLFW_CONCAT_VERSION(m, n, r)
_GLFW_VERSION_NUMBER
#define _GLFW_VERSION_NUMBER
Value:
_GLFW_MAKE_VERSION(GLFW_VERSION_MAJOR, \
                                                GLFW_VERSION_MINOR, \
                                                GLFW_VERSION_REVISION)
Referenced by _glfwPlatformGetVersionString().
_GLFW_REQUIRE_INIT
#define _GLFW_REQUIRE_INIT ()
Value:
if (!_glfw.initialized)                          \
    {                                                \
        _glfwInputError(GLFW_NOT_INITIALIZED, NULL); \
        return;                                      \
    }
Referenced by glfwDefaultWindowHints(), glfwDestroyCursor(), glfwDestroyWindow(), glfwFocusWindow(), glfwGetCursorPos(), glfwGetFramebufferSize(), glfwGetMonitorContentScale(), glfwGetMonitorPhysicalSize(), glfwGetMonitorPos(), glfwGetWindowContentScale(), glfwGetWindowFrameSize(), glfwGetWindowPos(), glfwGetWindowSize(), glfwHideWindow(), glfwIconifyWindow(), glfwMakeContextCurrent(), glfwMaximizeWindow(), glfwPollEvents(), glfwPostEmptyEvent(), glfwRequestWindowAttention(), glfwRestoreWindow(), glfwSetClipboardString(), glfwSetCursor(), glfwSetCursorPos(), glfwSetGamma(), glfwSetGammaRamp(), glfwSetInputMode(), glfwSetJoystickUserPointer(), glfwSetMonitorUserPointer(), glfwSetTime(), glfwSetWindowAspectRatio(), glfwSetWindowAttrib(), glfwSetWindowIcon(), glfwSetWindowMonitor(), glfwSetWindowOpacity(), glfwSetWindowPos(), glfwSetWindowShouldClose(), glfwSetWindowSize(), glfwSetWindowSizeLimits(), glfwSetWindowTitle(), glfwSetWindowUserPointer(), glfwSetX11SelectionString(), glfwShowWindow(), glfwSwapBuffers(), glfwSwapInterval(), glfwWaitEvents(), glfwWaitEventsTimeout(), glfwWindowHint(), and glfwWindowHintString().
_GLFW_REQUIRE_INIT_OR_RETURN
#define _GLFW_REQUIRE_INIT_OR_RETURN (x)
Value:
if (!_glfw.initialized)                          \
    {                                                \
        _glfwInputError(GLFW_NOT_INITIALIZED, NULL); \
        return x;                                    \
    }
Referenced by glfwCreateCursor(), glfwCreateStandardCursor(), glfwCreateWindow(), glfwCreateWindowSurface(), glfwExtensionSupported(), glfwGetClipboardString(), glfwGetCocoaMonitor(), glfwGetCocoaWindow(), glfwGetCurrentContext(), glfwGetEGLContext(), glfwGetEGLDisplay(), glfwGetEGLSurface(), glfwGetGamepadName(), glfwGetGamepadState(), glfwGetGammaRamp(), glfwGetGLXContext(), glfwGetGLXWindow(), glfwGetInputMode(), glfwGetInstanceProcAddress(), glfwGetJoystickAxes(), glfwGetJoystickButtons(), glfwGetJoystickGUID(), glfwGetJoystickHats(), glfwGetJoystickName(), glfwGetJoystickUserPointer(), glfwGetKey(), glfwGetKeyName(), glfwGetKeyScancode(), glfwGetMirDisplay(), glfwGetMirMonitor(), glfwGetMirWindow(), glfwGetMonitorName(), glfwGetMonitors(), glfwGetMonitorUserPointer(), glfwGetMouseButton(), glfwGetNSGLContext(), glfwGetOSMesaColorBuffer(), glfwGetOSMesaContext(), glfwGetOSMesaDepthBuffer(), glfwGetPhysicalDevicePresentationSupport(), glfwGetPrimaryMonitor(), glfwGetProcAddress(), glfwGetRequiredInstanceExtensions(), glfwGetTime(), glfwGetTimerFrequency(), glfwGetTimerValue(), glfwGetVideoMode(), glfwGetVideoModes(), glfwGetWaylandDisplay(), glfwGetWaylandMonitor(), glfwGetWaylandWindow(), glfwGetWGLContext(), glfwGetWin32Adapter(), glfwGetWin32Monitor(), glfwGetWin32Window(), glfwGetWindowAttrib(), glfwGetWindowMonitor(), glfwGetWindowOpacity(), glfwGetWindowUserPointer(), glfwGetX11Adapter(), glfwGetX11Display(), glfwGetX11Monitor(), glfwGetX11SelectionString(), glfwGetX11Window(), glfwJoystickIsGamepad(), glfwJoystickPresent(), glfwSetCharCallback(), glfwSetCharModsCallback(), glfwSetCursorEnterCallback(), glfwSetCursorPosCallback(), glfwSetDropCallback(), glfwSetFramebufferSizeCallback(), glfwSetJoystickCallback(), glfwSetKeyCallback(), glfwSetMonitorCallback(), glfwSetMouseButtonCallback(), glfwSetScrollCallback(), glfwSetWindowCloseCallback(), glfwSetWindowContentScaleCallback(), glfwSetWindowFocusCallback(), glfwSetWindowIconifyCallback(), glfwSetWindowMaximizeCallback(), glfwSetWindowPosCallback(), glfwSetWindowRefreshCallback(), glfwSetWindowSizeCallback(), glfwUpdateGamepadMappings(), glfwVulkanSupported(), and glfwWindowShouldClose().
_GLFW_SWAP_POINTERS
#define _GLFW_SWAP_POINTERS (x, y)
Value:
{                             \
        void* t;                  \
        t = x;                    \
        x = y;                    \
        y = t;                    \
    }
Referenced by glfwSetCharCallback(), glfwSetCharModsCallback(), glfwSetCursorEnterCallback(), glfwSetCursorPosCallback(), glfwSetDropCallback(), glfwSetErrorCallback(), glfwSetFramebufferSizeCallback(), glfwSetJoystickCallback(), glfwSetKeyCallback(), glfwSetMonitorCallback(), glfwSetMouseButtonCallback(), glfwSetScrollCallback(), glfwSetWindowCloseCallback(), glfwSetWindowContentScaleCallback(), glfwSetWindowFocusCallback(), glfwSetWindowIconifyCallback(), glfwSetWindowMaximizeCallback(), glfwSetWindowPosCallback(), glfwSetWindowRefreshCallback(), and glfwSetWindowSizeCallback().
Typedef Documentation
GLFWbool
typedef int GLFWbool
_GLFWerror
typedef struct _GLFWerror _GLFWerror
_GLFWinitconfig
typedef struct _GLFWinitconfig _GLFWinitconfig
_GLFWwndconfig
typedef struct _GLFWwndconfig _GLFWwndconfig
_GLFWctxconfig
typedef struct _GLFWctxconfig _GLFWctxconfig
_GLFWfbconfig
typedef struct _GLFWfbconfig _GLFWfbconfig
_GLFWcontext
typedef struct _GLFWcontext _GLFWcontext
_GLFWwindow
typedef struct _GLFWwindow _GLFWwindow
_GLFWlibrary
typedef struct _GLFWlibrary _GLFWlibrary
_GLFWmonitor
typedef struct _GLFWmonitor _GLFWmonitor
_GLFWcursor
typedef struct _GLFWcursor _GLFWcursor
_GLFWmapelement
typedef struct _GLFWmapelement _GLFWmapelement
_GLFWmapping
typedef struct _GLFWmapping _GLFWmapping
_GLFWjoystick
typedef struct _GLFWjoystick _GLFWjoystick
_GLFWtls
typedef struct _GLFWtls _GLFWtls
_GLFWmutex
typedef struct _GLFWmutex _GLFWmutex
_GLFWmakecontextcurrentfun
typedef void(* _GLFWmakecontextcurrentfun) (_GLFWwindow *)
_GLFWswapbuffersfun
typedef void(* _GLFWswapbuffersfun) (_GLFWwindow *)
_GLFWswapintervalfun
typedef void(* _GLFWswapintervalfun) (int)
_GLFWextensionsupportedfun
typedef int(* _GLFWextensionsupportedfun) (const char *)
_GLFWgetprocaddressfun
typedef GLFWglproc(* _GLFWgetprocaddressfun) (const char *)
_GLFWdestroycontextfun
typedef void(* _GLFWdestroycontextfun) (_GLFWwindow *)
GLint
typedef int GLint
GLuint
typedef unsigned int GLuint
GLenum
typedef unsigned int GLenum
GLbitfield
typedef unsigned int GLbitfield
GLubyte
typedef unsigned char GLubyte
PFNGLCLEARPROC
typedef void(APIENTRY * PFNGLCLEARPROC) (GLbitfield)
PFNGLGETSTRINGPROC
typedef const GLubyte*(APIENTRY * PFNGLGETSTRINGPROC) (GLenum)
PFNGLGETINTEGERVPROC
typedef void(APIENTRY * PFNGLGETINTEGERVPROC) (GLenum, GLint *)
PFNGLGETSTRINGIPROC
typedef const GLubyte*(APIENTRY * PFNGLGETSTRINGIPROC) (GLenum, GLuint)
VkInstance
typedef void* VkInstance
VkPhysicalDevice
typedef void* VkPhysicalDevice
VkSurfaceKHR
typedef uint64_t VkSurfaceKHR
VkFlags
typedef uint32_t VkFlags
VkBool32
typedef uint32_t VkBool32
VkStructureType
typedef enum VkStructureType VkStructureType
VkResult
typedef enum VkResult VkResult
VkAllocationCallbacks
typedef struct VkAllocationCallbacks VkAllocationCallbacks
VkExtensionProperties
typedef struct VkExtensionProperties VkExtensionProperties
PFN_vkVoidFunction
typedef void(APIENTRY * PFN_vkVoidFunction) (void)
Enumeration Type Documentation
VkStructureType
enum VkStructureType
Enumerator
VK_STRUCTURE_TYPE_XLIB_SURFACE_CREATE_INFO_KHR
VK_STRUCTURE_TYPE_XCB_SURFACE_CREATE_INFO_KHR
VK_STRUCTURE_TYPE_WAYLAND_SURFACE_CREATE_INFO_KHR
VK_STRUCTURE_TYPE_MIR_SURFACE_CREATE_INFO_KHR
VK_STRUCTURE_TYPE_WIN32_SURFACE_CREATE_INFO_KHR
VK_STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK
VK_STRUCTURE_TYPE_MAX_ENUM
VkResult
enum VkResult
Enumerator
VK_SUCCESS
VK_NOT_READY
VK_TIMEOUT
VK_EVENT_SET
VK_EVENT_RESET
VK_INCOMPLETE
VK_ERROR_OUT_OF_HOST_MEMORY
VK_ERROR_OUT_OF_DEVICE_MEMORY
VK_ERROR_INITIALIZATION_FAILED
VK_ERROR_DEVICE_LOST
VK_ERROR_MEMORY_MAP_FAILED
VK_ERROR_LAYER_NOT_PRESENT
VK_ERROR_EXTENSION_NOT_PRESENT
VK_ERROR_FEATURE_NOT_PRESENT
VK_ERROR_INCOMPATIBLE_DRIVER
VK_ERROR_TOO_MANY_OBJECTS
VK_ERROR_FORMAT_NOT_SUPPORTED
VK_ERROR_SURFACE_LOST_KHR
VK_SUBOPTIMAL_KHR
VK_ERROR_OUT_OF_DATE_KHR
VK_ERROR_INCOMPATIBLE_DISPLAY_KHR
VK_ERROR_NATIVE_WINDOW_IN_USE_KHR
VK_ERROR_VALIDATION_FAILED_EXT
VK_RESULT_MAX_ENUM
Function Documentation
vkGetInstanceProcAddr()
PFN_vkVoidFunction vkGetInstanceProcAddr (VkInstance , const char *)
Referenced by _glfwPlatformCreateWindowSurface(), _glfwPlatformGetPhysicalDevicePresentationSupport(), and glfwGetInstanceProcAddress().
vkEnumerateInstanceExtensionProperties()
VkResult vkEnumerateInstanceExtensionProperties (const char * , uint32_t * , VkExtensionProperties *)
Referenced by _glfwInitVulkan().
_glfwPlatformInit()
int _glfwPlatformInit (void)
References _glfw, _glfw_dlopen, _glfw_dlsym, _glfwInitEventQueueMir(), _glfwInitJoysticksLinux(), _glfwInitJoysticksNS(), _glfwInitJoysticksWin32(), _glfwInitTimerNS(), _glfwInitTimerPOSIX(), _glfwInitTimerWin32(), _glfwInputError(), _glfwPollMonitorsMir(), _glfwPollMonitorsNS(), _glfwPollMonitorsWin32(), _glfwPollMonitorsX11(), _glfwRegisterWindowClassWin32(), _glfwUpdateKeyNamesWin32(), changeToResourcesDirectory(), _GLFWinitconfig::chdir, _GLFWlibrary::context, createHelperWindow(), createHiddenCursor(), createKeyTables(), display(), getSystemContentScale(), GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, _GLFWlibrary::handle, hasUsableInputMethodStyle(), _GLFWlibrary::hints, _GLFWlibrary::init, initExtensions(), initializeTIS(), IsWindows8Point1OrGreater, IsWindowsVistaOrGreater, loadLibraries(), _GLFWinitconfig::ns, NULL, PROCESS_PER_MONITOR_DPI_AWARE, registryListener, SetProcessDPIAware, SetProcessDpiAwareness, wl_cursor_theme_load, and xkb_context_new.
Referenced by glfwInit().
_glfwPlatformTerminate()
void _glfwPlatformTerminate (void)
References _glfw, _glfw_dlclose, _glfwDeleteEventQueueMir(), _glfwPushSelectionToManagerX11(), _glfwTerminateEGL(), _glfwTerminateGLX(), _glfwTerminateJoysticksLinux(), _glfwTerminateJoysticksNS(), _glfwTerminateJoysticksWin32(), _glfwTerminateNSGL(), _glfwTerminateOSMesa(), _glfwTerminateWGL(), _glfwUnregisterWindowClassWin32(), _GLFWlibrary::context, freeLibraries(), _GLFWlibrary::handle, AuroraFW::None, NULL, wl_cursor_theme_destroy, xkb_context_unref, xkb_keymap_unref, and xkb_state_unref.
Referenced by terminate().
_glfwPlatformGetVersionString()
const char* _glfwPlatformGetVersionString (void)
References _GLFW_VERSION_NUMBER.
Referenced by glfwGetVersionString().
_glfwPlatformGetCursorPos()
void _glfwPlatformGetCursorPos (_GLFWwindow * window, double * xpos, double * ypos)
References _glfw, _glfwInputError(), ImGui::GetCursorPos(), and GLFW_PLATFORM_ERROR.
Referenced by _glfwPlatformSetCursorMode(), glfwGetCursorPos(), and glfwSetInputMode().
_glfwPlatformSetCursorPos()
void _glfwPlatformSetCursorPos (_GLFWwindow * window, double xpos, double ypos)
References _glfw, _glfwInputError(), GLFW_PLATFORM_ERROR, isPointerLocked(), _GLFWwindow::monitor, AuroraFW::None, ImGui::SetCursorPos(), _GLFWwindow::size, transformY(), and updateCursorImage().
Referenced by _glfwPlatformPollEvents(), _glfwPlatformSetCursorMode(), centerCursor(), glfwCreateWindow(), and glfwSetCursorPos().
_glfwPlatformSetCursorMode()
void _glfwPlatformSetCursorMode (_GLFWwindow * window, int mode)
References _glfw, _glfwInputErrorWin32(), _glfwPlatformGetCursorPos(), _glfwPlatformSetCursor(), _glfwPlatformSetCursorPos(), _GLFWlibrary::available, centerCursor(), cursorInClientArea(), _GLFWwindow::cursorMode, GLFW_CURSOR_DISABLED, GLFW_CURSOR_HIDDEN, GLFW_CURSOR_NORMAL, GLFW_PLATFORM_ERROR, mode(), NULL, setCursorNameForWindow(), setWindowConfinement(), updateClipRect(), updateCursorImage(), and XISelectEvents.
Referenced by glfwSetInputMode(), processEvent(), and windowProc().
_glfwPlatformCreateCursor()
int _glfwPlatformCreateCursor (_GLFWcursor * cursor, const GLFWimage * image, int xhot, int yhot)
References _glfw, _glfwCreateCursorX11(), createIcon(), createShmBuffer(), GLFW_FALSE, GLFW_TRUE, GLFWimage::height, initializeAppKit(), memcpy(), GLFWimage::pixels, and GLFWimage::width.
Referenced by glfwCreateCursor().
_glfwPlatformCreateStandardCursor()
int _glfwPlatformCreateStandardCursor (_GLFWcursor * cursor, int shape)
References _glfw, _glfwInputError(), _glfwInputErrorWin32(), getSystemCursorName(), GLFW_ARROW_CURSOR, GLFW_CROSSHAIR_CURSOR, GLFW_FALSE, GLFW_HAND_CURSOR, GLFW_HRESIZE_CURSOR, GLFW_IBEAM_CURSOR, GLFW_PLATFORM_ERROR, GLFW_TRUE, GLFW_VRESIZE_CURSOR, wl_cursor::images, initializeAppKit(), NULL, translateCursorShape(), and wl_cursor_theme_get_cursor.
Referenced by glfwCreateStandardCursor().
_glfwPlatformDestroyCursor()
void _glfwPlatformDestroyCursor (_GLFWcursor * cursor)
References _glfw.
Referenced by glfwDestroyCursor().
_glfwPlatformSetCursor()
void _glfwPlatformSetCursor (_GLFWwindow * window, _GLFWcursor * cursor)
References _glfw, _glfwInputError(), cursorInClientArea(), _GLFWwindow::cursorMode, GLFW_CURSOR_DISABLED, GLFW_CURSOR_HIDDEN, GLFW_CURSOR_NORMAL, GLFW_PLATFORM_ERROR, wl_cursor_image::height, wl_cursor_image::hotspot_x, wl_cursor_image::hotspot_y, wl_cursor::images, isPointerLocked(), lockPointer(), NULL, setCursorNameForWindow(), unlockPointer(), updateCursorImage(), wl_cursor_image::width, wl_cursor_image_get_buffer, and wl_cursor_theme_get_cursor.
Referenced by _glfwPlatformSetCursorMode(), glfwSetCursor(), and pointerHandleEnter().
_glfwPlatformGetScancodeName()
const char* _glfwPlatformGetScancodeName (int scancode)
References _glfw, _glfwInputError(), _glfwKeySym2Unicode(), _GLFWlibrary::available, encodeUTF8(), GLFW_PLATFORM_ERROR, LMGetKbdType, and NULL.
Referenced by glfwGetKeyName().
_glfwPlatformGetKeyScancode()
int _glfwPlatformGetKeyScancode (int key)
References _glfw.
Referenced by _glfwInputWindowFocus(), glfwGetKeyName(), and glfwGetKeyScancode().
_glfwPlatformFreeMonitor()
void _glfwPlatformFreeMonitor (_GLFWmonitor * monitor)
Referenced by _glfwFreeMonitor().
_glfwPlatformGetMonitorPos()
void _glfwPlatformGetMonitorPos (_GLFWmonitor * monitor, int * xpos, int * ypos)
References _glfw, _GLFWlibrary::available, EDS_ROTATEDMODE, XRRFreeCrtcInfo, XRRFreeScreenResources, XRRGetCrtcInfo, and XRRGetScreenResourcesCurrent.
Referenced by acquireMonitor(), createNativeWindow(), and glfwGetMonitorPos().
_glfwPlatformGetMonitorContentScale()
void _glfwPlatformGetMonitorContentScale (_GLFWmonitor * monitor, float * xscale, float * yscale)
References _glfw, _glfwGetMonitorContentScaleWin32(), _glfwInputError(), and GLFW_PLATFORM_ERROR.
Referenced by glfwGetMonitorContentScale().
_glfwPlatformGetVideoModes()
GLFWvidmode* _glfwPlatformGetVideoModes (_GLFWmonitor * monitor, int * count)
References _glfw, _glfwCompareVideoModes(), _glfwInputError(), _glfwPlatformGetVideoMode(), _glfwSplitBPP(), _GLFWlibrary::available, FillInRGBBitsFromPixelFormat(), getModeInfo(), GLFW_PLATFORM_ERROR, height, GLFWvidmode::height, mode(), _GLFWmonitor::modeCount, modeIsGood(), _GLFWmonitor::modes, NULL, GLFWvidmode::refreshRate, vidmodeFromCGDisplayMode(), vidmodeFromModeInfo(), width, GLFWvidmode::width, XRRFreeCrtcInfo, XRRFreeOutputInfo, XRRFreeScreenResources, XRRGetCrtcInfo, XRRGetOutputInfo, and XRRGetScreenResourcesCurrent.
Referenced by _glfwPollMonitorsMir(), and refreshVideoModes().
_glfwPlatformGetVideoMode()
void _glfwPlatformGetVideoMode (_GLFWmonitor * monitor, GLFWvidmode * mode)
References _glfw, _glfwSplitBPP(), _GLFWlibrary::available, _GLFWmonitor::currentMode, getModeInfo(), mode(), _GLFWmonitor::modes, vidmodeFromCGDisplayMode(), vidmodeFromModeInfo(), XRRFreeCrtcInfo, XRRFreeScreenResources, XRRGetCrtcInfo, and XRRGetScreenResourcesCurrent.
Referenced by _glfwPlatformCreateWindow(), _glfwPlatformGetVideoModes(), _glfwSetVideoModeNS(), _glfwSetVideoModeWin32(), _glfwSetVideoModeX11(), acquireMonitor(), createNativeWindow(), and glfwGetVideoMode().
_glfwPlatformGetGammaRamp()
void _glfwPlatformGetGammaRamp (_GLFWmonitor * monitor, GLFWgammaramp * ramp)
References _glfw, _glfwAllocGammaArrays(), _glfwInputError(), _GLFWlibrary::available, GLFWgammaramp::blue, GLFW_PLATFORM_ERROR, GLFWgammaramp::green, memcpy(), NULL, GLFWgammaramp::red, GLFWgammaramp::size, XF86VidModeGetGammaRamp, XF86VidModeGetGammaRampSize, XRRFreeGamma, XRRGetCrtcGamma, and XRRGetCrtcGammaSize.
Referenced by glfwGetGammaRamp(), and glfwSetGammaRamp().
_glfwPlatformSetGammaRamp()
void _glfwPlatformSetGammaRamp (_GLFWmonitor * monitor, const GLFWgammaramp * ramp)
References _glfw, _glfwInputError(), _GLFWlibrary::available, GLFWgammaramp::blue, GLFW_PLATFORM_ERROR, GLFWgammaramp::green, memcpy(), NULL, GLFWgammaramp::red, GLFWgammaramp::size, XF86VidModeSetGammaRamp, XRRAllocGamma, XRRFreeGamma, XRRGetCrtcGammaSize, and XRRSetCrtcGamma.
Referenced by glfwSetGammaRamp(), and terminate().
_glfwPlatformSetClipboardString()
void _glfwPlatformSetClipboardString (const char * string)
References _glfw, _glfw_strdup(), _glfwInputError(), _glfwInputErrorWin32(), GLFW_PLATFORM_ERROR, and NULL.
Referenced by glfwSetClipboardString().
_glfwPlatformGetClipboardString()
const char* _glfwPlatformGetClipboardString (void)
References _glfw, _glfw_strdup(), _glfwCreateUTF8FromWideStringWin32(), _glfwInputError(), _glfwInputErrorWin32(), getSelectionString(), GLFW_FORMAT_UNAVAILABLE, GLFW_PLATFORM_ERROR, and NULL.
Referenced by glfwGetClipboardString().
_glfwPlatformPollJoystick()
int _glfwPlatformPollJoystick (_GLFWjoystick * js, int mode)
References _glfw, _GLFW_POLL_AXES, _GLFW_POLL_BUTTONS, _GLFW_POLL_PRESENCE, _GLFW_TYPE_AXIS, _GLFW_TYPE_BUTTON, _GLFW_TYPE_POV, _GLFW_TYPE_SLIDER, _glfwInputJoystickAxis(), _glfwInputJoystickButton(), _glfwInputJoystickHat(), _GLFWjoystick::axes, _GLFWjoystick::buttons, closeJoystick(), getElementValue(), GLFW_FALSE, GLFW_HAT_CENTERED, GLFW_HAT_DOWN, GLFW_HAT_LEFT, GLFW_HAT_LEFT_DOWN, GLFW_HAT_LEFT_UP, GLFW_HAT_RIGHT, GLFW_HAT_RIGHT_DOWN, GLFW_HAT_RIGHT_UP, GLFW_HAT_UP, GLFW_TRUE, handleAbsEvent(), handleKeyEvent(), _GLFWjoystick::hats, _GLFWjoyelementNS::maximum, _GLFWjoyelementNS::minimum, mode(), pollAbsState(), _GLFWjoystick::present, SYN_DROPPED, value, and XInputGetState.
Referenced by _glfwDetectJoystickDisconnectionWin32(), glfwGetGamepadName(), glfwGetGamepadState(), glfwGetJoystickAxes(), glfwGetJoystickButtons(), glfwGetJoystickGUID(), glfwGetJoystickHats(), glfwGetJoystickName(), glfwJoystickIsGamepad(), and glfwJoystickPresent().
_glfwPlatformUpdateGamepadGUID()
void _glfwPlatformUpdateGamepadGUID (char * guid)
Referenced by parseMapping().
_glfwPlatformGetTimerValue()
uint64_t _glfwPlatformGetTimerValue (void)
References _glfw, NULL, timeGetTime, _GLFWlibrary::timer, and value.
Referenced by glfwGetTime(), glfwGetTimerValue(), glfwInit(), glfwSetTime(), and waitForEvent().
_glfwPlatformGetTimerFrequency()
uint64_t _glfwPlatformGetTimerFrequency (void)
References _glfw, and _GLFWlibrary::timer.
Referenced by glfwGetTime(), glfwGetTimerFrequency(), glfwSetTime(), and waitForEvent().
_glfwPlatformCreateWindow()
int _glfwPlatformCreateWindow (_GLFWwindow * window, const _GLFWwndconfig * wndconfig, const _GLFWctxconfig * ctxconfig, const _GLFWfbconfig * fbconfig)
References _glfw, _glfw_strdup(), _glfwChooseVisualGLX(), _glfwCreateContextEGL(), _glfwCreateContextGLX(), _glfwCreateContextNSGL(), _glfwCreateContextOSMesa(), _glfwCreateContextWGL(), _glfwInitEGL(), _glfwInitGLX(), _glfwInitNSGL(), _glfwInitOSMesa(), _glfwInitWGL(), _glfwInputError(), _glfwPlatformFocusWindow(), _glfwPlatformGetVideoMode(), _glfwPlatformShowWindow(), acquireMonitor(), _GLFWctxconfig::client, createNativeWindow(), createShellSurface(), createSurface(), createWindow(), createXdgSurface(), fitToMonitor(), GLFW_API_UNAVAILABLE, GLFW_EGL_CONTEXT_API, GLFW_FALSE, GLFW_NATIVE_CONTEXT_API, GLFW_NO_API, GLFW_OSMESA_CONTEXT_API, GLFW_PLATFORM_ERROR, GLFW_TRUE, _GLFWwndconfig::height, initializeAppKit(), mode(), _GLFWwindow::monitor, NULL, _GLFWctxconfig::source, _GLFWwndconfig::title, _GLFWfbconfig::transparent, updateWindowMode(), _GLFWwndconfig::visible, and _GLFWwndconfig::width.
Referenced by glfwCreateWindow().
_glfwPlatformDestroyWindow()
void _glfwPlatformDestroyWindow (_GLFWwindow * window)
References _glfw, _glfwInputCursorEnter(), _glfwInputWindowFocus(), _GLFWwindow::close, _GLFWwindow::context, _GLFWlibrary::context, _GLFWcontext::destroy, destroyDecorations(), GLFW_FALSE, _GLFWwindow::monitor, NULL, releaseMonitor(), and wl_egl_window_destroy.
Referenced by glfwDestroyWindow().
_glfwPlatformSetWindowTitle()
void _glfwPlatformSetWindowTitle (_GLFWwindow * window, const char * title)
References _glfw, _glfw_strdup(), _glfwCreateWideStringFromUTF8Win32(), and NULL.
Referenced by createNativeWindow(), and glfwSetWindowTitle().
_glfwPlatformSetWindowIcon()
void _glfwPlatformSetWindowIcon (_GLFWwindow * window, int count, const GLFWimage * images)
References _glfw, _glfwInputError(), chooseImage(), createIcon(), GLFW_PLATFORM_ERROR, GLFW_TRUE, height, GLFWimage::height, NULL, GLFWimage::pixels, width, and GLFWimage::width.
Referenced by glfwSetWindowIcon().
_glfwPlatformGetWindowPos()
void _glfwPlatformGetWindowPos (_GLFWwindow * window, int * xpos, int * ypos)
References _glfw, _glfwInputError(), GLFW_PLATFORM_ERROR, and transformY().
Referenced by createNativeWindow(), and glfwGetWindowPos().
_glfwPlatformSetWindowPos()
void _glfwPlatformSetWindowPos (_GLFWwindow * window, int xpos, int ypos)
References _glfw, _glfwInputError(), _glfwPlatformWindowVisible(), getWindowExStyle(), getWindowStyle(), GLFW_PLATFORM_ERROR, NULL, SetWindowPos(), and transformY().
Referenced by _glfwInputMonitor(), and glfwSetWindowPos().
_glfwPlatformGetWindowSize()
void _glfwPlatformGetWindowSize (_GLFWwindow * window, int * width, int * height)
References _glfw, height, and width.
Referenced by _glfwInputMonitor(), _glfwPlatformGetFramebufferSize(), _glfwPlatformGetWindowFrameSize(), _glfwPlatformPollEvents(), _glfwPlatformSetWindowAspectRatio(), _glfwPlatformSetWindowResizable(), _glfwPlatformSetWindowSizeLimits(), centerCursor(), createNativeWindow(), glfwCreateWindow(), and glfwGetWindowSize().
_glfwPlatformSetWindowSize()
void _glfwPlatformSetWindowSize (_GLFWwindow * window, int width, int height)
References _glfw, acquireMonitor(), fitToMonitor(), getWindowExStyle(), getWindowStyle(), height, _GLFWwindow::monitor, _GLFWwindow::resizable, resizeWindow(), SetWindowPos(), updateNormalHints(), width, and _GLFWmonitor::window.
Referenced by glfwSetWindowSize(), handleConfigure(), and xdgToplevelHandleConfigure().
_glfwPlatformSetWindowSizeLimits()
void _glfwPlatformSetWindowSizeLimits (_GLFWwindow * window, int minwidth, int minheight, int maxwidth, int maxheight)
References _glfw, _glfwPlatformGetWindowSize(), GLFW_DONT_CARE, height, updateNormalHints(), and width.
Referenced by glfwSetWindowSizeLimits().
_glfwPlatformSetWindowAspectRatio()
void _glfwPlatformSetWindowAspectRatio (_GLFWwindow * window, int numer, int denom)
References _glfw, _glfwInputError(), _glfwPlatformGetWindowSize(), applyAspectRatio(), GLFW_DONT_CARE, GLFW_PLATFORM_ERROR, height, updateNormalHints(), and width.
Referenced by glfwSetWindowAspectRatio().
_glfwPlatformGetFramebufferSize()
void _glfwPlatformGetFramebufferSize (_GLFWwindow * window, int * width, int * height)
References _glfwPlatformGetWindowSize(), height, _GLFWwindow::scale, and width.
Referenced by createNativeWindow(), glfwGetFramebufferSize(), and makeContextCurrentOSMesa().
_glfwPlatformGetWindowFrameSize()
void _glfwPlatformGetWindowFrameSize (_GLFWwindow * window, int * left, int * top, int * right, int * bottom)
References _glfw, _GLFW_DECORATION_TOP, _GLFW_DECORATION_WIDTH, _glfwGetWindowPropertyX11(), _glfwInputError(), _glfwPlatformGetWindowSize(), _glfwPlatformWindowVisible(), _GLFWwindow::decorated, getWindowExStyle(), getWindowStyle(), GLFW_PLATFORM_ERROR, height, isFrameExtentsEvent(), _GLFWwindow::monitor, AuroraFW::None, NULL, sendEventToWM(), waitForEvent(), and width.
Referenced by _glfwInputMonitor(), and glfwGetWindowFrameSize().
_glfwPlatformGetWindowContentScale()
void _glfwPlatformGetWindowContentScale (_GLFWwindow * window, float * xscale, float * yscale)
References _glfw, _glfwGetMonitorContentScaleWin32(), and _GLFWwindow::scale.
Referenced by glfwGetWindowContentScale().
_glfwPlatformIconifyWindow()
void _glfwPlatformIconifyWindow (_GLFWwindow * window)
References _glfw, _glfwInputError(), and GLFW_PLATFORM_ERROR.
Referenced by glfwIconifyWindow(), processEvent(), windowProc(), and xdgToplevelHandleConfigure().
_glfwPlatformRestoreWindow()
void _glfwPlatformRestoreWindow (_GLFWwindow * window)
References _glfw, _glfwInputError(), _glfwInputWindowMonitor(), _glfwPlatformWindowIconified(), _glfwPlatformWindowVisible(), _NET_WM_STATE_REMOVE, GLFW_FALSE, GLFW_PLATFORM_ERROR, _GLFWwindow::monitor, NULL, sendEventToWM(), and waitForVisibilityNotify().
Referenced by glfwRestoreWindow().
_glfwPlatformMaximizeWindow()
void _glfwPlatformMaximizeWindow (_GLFWwindow * window)
References _glfw, _NET_WM_STATE_ADD, GLFW_TRUE, NULL, and sendEventToWM().
Referenced by glfwMaximizeWindow().
_glfwPlatformShowWindow()
void _glfwPlatformShowWindow (_GLFWwindow * window)
References _glfw, _glfwPlatformWindowVisible(), createShellSurface(), createXdgSurface(), GLFW_TRUE, and waitForVisibilityNotify().
Referenced by _glfwPlatformCreateWindow(), glfwCreateWindow(), and glfwShowWindow().
_glfwPlatformHideWindow()
void _glfwPlatformHideWindow (_GLFWwindow * window)
References _glfw, GLFW_FALSE, and NULL.
Referenced by glfwHideWindow().
_glfwPlatformRequestWindowAttention()
void _glfwPlatformRequestWindowAttention (_GLFWwindow * window)
References _glfw, _glfwInputError(), _NET_WM_STATE_ADD, GLFW_PLATFORM_ERROR, and sendEventToWM().
Referenced by glfwRequestWindowAttention().
_glfwPlatformFocusWindow()
void _glfwPlatformFocusWindow (_GLFWwindow * window)
References _glfw, _glfwInputError(), GLFW_PLATFORM_ERROR, and sendEventToWM().
Referenced by _glfwPlatformCreateWindow(), glfwCreateWindow(), glfwFocusWindow(), and glfwShowWindow().
_glfwPlatformSetWindowMonitor()
void _glfwPlatformSetWindowMonitor (_GLFWwindow * window, _GLFWmonitor * monitor, int xpos, int ypos, int width, int height, int refreshRate)
References _glfw, _glfwInputError(), _glfwInputWindowMonitor(), _glfwPlatformPollEvents(), acquireMonitor(), createDecorations(), _GLFWwindow::decorated, _GLFWwindow::denom, fitToMonitor(), _GLFWwindow::floating, getStyleMask(), getWindowExStyle(), getWindowStyle(), GLFW_DONT_CARE, GLFW_FALSE, GLFW_PLATFORM_ERROR, height, _GLFWwindow::maxheight, _GLFWwindow::maxwidth, _GLFWwindow::minheight, _GLFWwindow::minwidth, _GLFWwindow::monitor, _GLFWwindow::numer, releaseMonitor(), setFullscreen(), setIdleInhibitor(), SetWindowPos(), transformY(), updateNormalHints(), updateWindowMode(), waitForVisibilityNotify(), width, and _GLFWmonitor::window.
Referenced by _glfwInputMonitor(), and glfwSetWindowMonitor().
_glfwPlatformWindowFocused()
int _glfwPlatformWindowFocused (_GLFWwindow * window)
References _glfw, and GLFW_FALSE.
Referenced by glfwGetWindowAttrib(), glfwSetCursorPos(), and glfwSetInputMode().
_glfwPlatformWindowIconified()
int _glfwPlatformWindowIconified (_GLFWwindow * window)
References _glfwInputError(), getWindowState(), GLFW_FALSE, and GLFW_PLATFORM_ERROR.
Referenced by _glfwPlatformRestoreWindow(), and glfwGetWindowAttrib().
_glfwPlatformWindowVisible()
int _glfwPlatformWindowVisible (_GLFWwindow * window)
References _glfw, and GLFW_FALSE.
Referenced by _glfwPlatformGetWindowFrameSize(), _glfwPlatformRestoreWindow(), _glfwPlatformSetWindowFloating(), _glfwPlatformSetWindowPos(), _glfwPlatformShowWindow(), and glfwGetWindowAttrib().
_glfwPlatformWindowMaximized()
int _glfwPlatformWindowMaximized (_GLFWwindow * window)
References _glfw, _glfwGetWindowPropertyX11(), GLFW_FALSE, and GLFW_TRUE.
Referenced by glfwGetWindowAttrib(), and processEvent().
_glfwPlatformWindowHovered()
int _glfwPlatformWindowHovered (_GLFWwindow * window)
References _glfw, _glfwInputError(), cursorInClientArea(), GLFW_FALSE, GLFW_PLATFORM_ERROR, and GLFW_TRUE.
Referenced by glfwGetWindowAttrib().
_glfwPlatformFramebufferTransparent()
int _glfwPlatformFramebufferTransparent (_GLFWwindow * window)
References _glfw, _glfwInputError(), _glfwIsCompositionEnabledWin32(), GLFW_FALSE, GLFW_PLATFORM_ERROR, and AuroraFW::None.
Referenced by glfwGetWindowAttrib().
_glfwPlatformGetWindowOpacity()
float _glfwPlatformGetWindowOpacity (_GLFWwindow * window)
References _glfw, _glfwGetWindowPropertyX11(), NULL, and value.
Referenced by glfwGetWindowOpacity().
_glfwPlatformSetWindowResizable()
void _glfwPlatformSetWindowResizable (_GLFWwindow * window, GLFWbool enabled)
References _glfwInputError(), _glfwPlatformGetWindowSize(), GLFW_PLATFORM_ERROR, height, updateNormalHints(), updateWindowStyles(), and width.
Referenced by glfwSetWindowAttrib().
_glfwPlatformSetWindowDecorated()
void _glfwPlatformSetWindowDecorated (_GLFWwindow * window, GLFWbool enabled)
References _glfw, _glfwInputError(), createDecorations(), destroyDecorations(), GLFW_PLATFORM_ERROR, _GLFWwindow::monitor, and updateWindowStyles().
Referenced by createNativeWindow(), and glfwSetWindowAttrib().
_glfwPlatformSetWindowFloating()
void _glfwPlatformSetWindowFloating (_GLFWwindow * window, GLFWbool enabled)
References _glfw, _glfwGetWindowPropertyX11(), _glfwInputError(), _glfwPlatformWindowVisible(), _NET_WM_STATE_ADD, _NET_WM_STATE_REMOVE, GLFW_PLATFORM_ERROR, sendEventToWM(), and SetWindowPos().
Referenced by glfwSetWindowAttrib().
_glfwPlatformSetWindowOpacity()
void _glfwPlatformSetWindowOpacity (_GLFWwindow * window, float opacity)
References _glfw, and value.
Referenced by glfwSetWindowOpacity().
_glfwPlatformPollEvents()
void _glfwPlatformPollEvents (void)
References _glfw, _glfwDetectJoystickConnectionLinux(), _glfwInputKey(), _glfwInputWindowCloseRequest(), _glfwPlatformGetWindowSize(), _glfwPlatformSetCursorPos(), deleteNode(), dequeueEvent(), getAsyncKeyMods(), GLFW_KEY_LEFT_SHIFT, GLFW_KEY_RIGHT_SHIFT, GLFW_PRESS, GLFW_RELEASE, handleEvent(), handleEvents(), height, initializeAppKit(), _GLFWwindow::keys, _GLFWwindow::next, NULL, processEvent(), width, and _GLFWlibrary::windowListHead.
Referenced by _glfwPlatformSetWindowMonitor(), _glfwPlatformWaitEvents(), _glfwPlatformWaitEventsTimeout(), and glfwPollEvents().
_glfwPlatformWaitEvents()
void _glfwPlatformWaitEvents (void)
References _glfw, _glfwPlatformPollEvents(), emptyEventQueue(), handleEvents(), NULL, and waitForEvent().
Referenced by glfwWaitEvents().
_glfwPlatformWaitEventsTimeout()
void _glfwPlatformWaitEventsTimeout (double timeout)
References _glfw, _glfwPlatformPollEvents(), emptyEventQueue(), handleEvents(), NULL, and waitForEvent().
Referenced by glfwWaitEventsTimeout().
_glfwPlatformPostEmptyEvent()
void _glfwPlatformPostEmptyEvent (void)
References _glfw, and memset().
Referenced by glfwPostEmptyEvent().
_glfwPlatformGetRequiredInstanceExtensions()
void _glfwPlatformGetRequiredInstanceExtensions (char ** extensions)
References _glfw, _GLFWlibrary::handle, _GLFWlibrary::KHR_surface, and _GLFWlibrary::vk.
Referenced by _glfwInitVulkan().
_glfwPlatformGetPhysicalDevicePresentationSupport()
int _glfwPlatformGetPhysicalDevicePresentationSupport (VkInstance instance, VkPhysicalDevice device, uint32_t queuefamily)
References _glfw, _glfwInputError(), GLFW_API_UNAVAILABLE, GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, _GLFWlibrary::handle, _GLFWlibrary::vk, VK_NULL_HANDLE, vkGetInstanceProcAddr(), and XGetXCBConnection.
Referenced by glfwGetPhysicalDevicePresentationSupport().
_glfwPlatformCreateWindowSurface()
VkResult _glfwPlatformCreateWindowSurface (VkInstance instance, _GLFWwindow * window, const VkAllocationCallbacks * allocator, VkSurfaceKHR * surface)
References _glfw, _glfwGetVulkanResultString(), _glfwInputError(), VkMirWindowCreateInfoKHR::connection, VkXcbSurfaceCreateInfoKHR::connection, VkWaylandSurfaceCreateInfoKHR::display, VkXlibSurfaceCreateInfoKHR::dpy, GLFW_API_UNAVAILABLE, GLFW_PLATFORM_ERROR, _GLFWlibrary::handle, VkWin32SurfaceCreateInfoKHR::hinstance, VkWin32SurfaceCreateInfoKHR::hwnd, memset(), VkMirWindowCreateInfoKHR::mirWindow, NULL, VkMacOSSurfaceCreateInfoMVK::pView, VkMirWindowCreateInfoKHR::sType, VkWaylandSurfaceCreateInfoKHR::sType, VkMacOSSurfaceCreateInfoMVK::sType, VkXlibSurfaceCreateInfoKHR::sType, VkXcbSurfaceCreateInfoKHR::sType, VkWin32SurfaceCreateInfoKHR::sType, VkWaylandSurfaceCreateInfoKHR::surface, _GLFWlibrary::vk, VK_ERROR_EXTENSION_NOT_PRESENT, VK_ERROR_INITIALIZATION_FAILED, VK_STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK, VK_STRUCTURE_TYPE_MIR_SURFACE_CREATE_INFO_KHR, VK_STRUCTURE_TYPE_WAYLAND_SURFACE_CREATE_INFO_KHR, VK_STRUCTURE_TYPE_WIN32_SURFACE_CREATE_INFO_KHR, VK_STRUCTURE_TYPE_XCB_SURFACE_CREATE_INFO_KHR, VK_STRUCTURE_TYPE_XLIB_SURFACE_CREATE_INFO_KHR, vkGetInstanceProcAddr(), VkXlibSurfaceCreateInfoKHR::window, VkXcbSurfaceCreateInfoKHR::window, and XGetXCBConnection.
Referenced by glfwCreateWindowSurface().
_glfwPlatformCreateTls()
GLFWbool _glfwPlatformCreateTls (_GLFWtls * tls)
References _glfwInputError(), _glfwInputErrorWin32(), GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, and NULL.
Referenced by glfwInit().
_glfwPlatformDestroyTls()
void _glfwPlatformDestroyTls (_GLFWtls * tls)
References memset().
Referenced by terminate().
_glfwPlatformGetTls()
void* _glfwPlatformGetTls (_GLFWtls * tls)
References GLFW_TRUE.
Referenced by _glfwInputError(), _glfwRefreshContextAttribs(), getProcAddressEGL(), glfwDestroyWindow(), glfwExtensionSupported(), glfwGetCurrentContext(), glfwGetError(), glfwGetProcAddress(), glfwMakeContextCurrent(), glfwSwapInterval(), swapBuffersEGL(), swapIntervalGLX(), swapIntervalNSGL(), and swapIntervalWGL().
_glfwPlatformSetTls()
void _glfwPlatformSetTls (_GLFWtls * tls, void * value)
References GLFW_TRUE, and value.
Referenced by _glfwInputError(), glfwInit(), makeContextCurrentEGL(), makeContextCurrentGLX(), makeContextCurrentNSGL(), makeContextCurrentOSMesa(), and makeContextCurrentWGL().
_glfwPlatformCreateMutex()
GLFWbool _glfwPlatformCreateMutex (_GLFWmutex * mutex)
References _glfwInputError(), GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, and NULL.
Referenced by glfwInit().
_glfwPlatformDestroyMutex()
void _glfwPlatformDestroyMutex (_GLFWmutex * mutex)
References memset().
Referenced by terminate().
_glfwPlatformLockMutex()
void _glfwPlatformLockMutex (_GLFWmutex * mutex)
References GLFW_TRUE.
Referenced by _glfwInputError().
_glfwPlatformUnlockMutex()
void _glfwPlatformUnlockMutex (_GLFWmutex * mutex)
References GLFW_TRUE.
Referenced by _glfwInputError().
_glfwInputWindowFocus()
void _glfwInputWindowFocus (_GLFWwindow * window, GLFWbool focused)
References _glfwInputKey(), _glfwInputMouseClick(), _glfwPlatformGetKeyScancode(), _GLFWwindow::callbacks, _GLFWwindow::focus, GLFW_KEY_LAST, GLFW_MOUSE_BUTTON_LAST, GLFW_PRESS, and GLFW_RELEASE.
Referenced by _glfwPlatformDestroyWindow(), keyboardHandleEnter(), keyboardHandleLeave(), processEvent(), windowProc(), and xdgToplevelHandleConfigure().
_glfwInputWindowPos()
void _glfwInputWindowPos (_GLFWwindow * window, int xpos, int ypos)
References _GLFWwindow::callbacks, and _GLFWwindow::pos.
Referenced by processEvent(), and windowProc().
_glfwInputWindowSize()
void _glfwInputWindowSize (_GLFWwindow * window, int width, int height)
References _GLFWwindow::callbacks, height, _GLFWwindow::size, and width.
Referenced by handleConfigure(), processEvent(), windowProc(), and xdgToplevelHandleConfigure().
_glfwInputFramebufferSize()
void _glfwInputFramebufferSize (_GLFWwindow * window, int width, int height)
References _GLFWwindow::callbacks, _GLFWwindow::fbsize, height, and width.
Referenced by processEvent(), resizeWindow(), and windowProc().
_glfwInputWindowContentScale()
void _glfwInputWindowContentScale (_GLFWwindow * window, float xscale, float yscale)
References _GLFWwindow::callbacks, and _GLFWwindow::scale.
Referenced by resizeWindow(), and windowProc().
_glfwInputWindowIconify()
void _glfwInputWindowIconify (_GLFWwindow * window, GLFWbool iconified)
References _GLFWwindow::callbacks, and _GLFWwindow::iconify.
Referenced by processEvent(), and windowProc().
_glfwInputWindowMaximize()
void _glfwInputWindowMaximize (_GLFWwindow * window, GLFWbool maximized)
References _GLFWwindow::callbacks, and _GLFWwindow::maximize.
Referenced by processEvent(), and windowProc().
_glfwInputWindowDamage()
void _glfwInputWindowDamage (_GLFWwindow * window)
References _GLFWwindow::callbacks, and _GLFWwindow::refresh.
Referenced by handleConfigure(), processEvent(), windowProc(), and xdgToplevelHandleConfigure().
_glfwInputWindowCloseRequest()
void _glfwInputWindowCloseRequest (_GLFWwindow * window)
References _GLFWwindow::callbacks, _GLFWwindow::close, GLFW_TRUE, and _GLFWwindow::shouldClose.
Referenced by _glfwPlatformPollEvents(), handleEvents(), processEvent(), windowProc(), and xdgToplevelHandleClose().
_glfwInputWindowMonitor()
void _glfwInputWindowMonitor (_GLFWwindow * window, _GLFWmonitor * monitor)
References _GLFWwindow::monitor.
Referenced by _glfwPlatformRestoreWindow(), and _glfwPlatformSetWindowMonitor().
_glfwInputKey()
void _glfwInputKey (_GLFWwindow * window, int key, int scancode, int action, int mods)
References _GLFW_STICK, _GLFWwindow::callbacks, GLFW_FALSE, GLFW_KEY_LAST, GLFW_MOD_CAPS_LOCK, GLFW_MOD_NUM_LOCK, GLFW_PRESS, GLFW_RELEASE, GLFW_REPEAT, GLFW_TRUE, _GLFWwindow::key, _GLFWwindow::keys, _GLFWwindow::lockKeyMods, and _GLFWwindow::stickyKeys.
Referenced by _glfwInputWindowFocus(), _glfwPlatformPollEvents(), handleEvents(), handleKeyEvent(), keyboardHandleKey(), processEvent(), and windowProc().
_glfwInputChar()
void _glfwInputChar (_GLFWwindow * window, unsigned int codepoint, int mods, GLFWbool plain)
References _GLFWwindow::callbacks, _GLFWwindow::charmods, GLFW_MOD_CAPS_LOCK, GLFW_MOD_NUM_LOCK, and _GLFWwindow::lockKeyMods.
Referenced by handleKeyEvent(), inputChar(), processEvent(), and windowProc().
_glfwInputScroll()
void _glfwInputScroll (_GLFWwindow * window, double xoffset, double yoffset)
References _GLFWwindow::callbacks, and _GLFWwindow::scroll.
Referenced by handlePointerMotion(), pointerHandleAxis(), processEvent(), and windowProc().
_glfwInputMouseClick()
void _glfwInputMouseClick (_GLFWwindow * window, int button, int action, int mods)
References _GLFW_STICK, _GLFWwindow::callbacks, GLFW_MOD_CAPS_LOCK, GLFW_MOD_NUM_LOCK, GLFW_MOUSE_BUTTON_LAST, GLFW_RELEASE, _GLFWwindow::lockKeyMods, _GLFWwindow::mouseButton, _GLFWwindow::mouseButtons, and _GLFWwindow::stickyMouseButtons.
Referenced by _glfwInputWindowFocus(), handlePointerButton(), pointerHandleButton(), processEvent(), and windowProc().
_glfwInputCursorPos()
void _glfwInputCursorPos (_GLFWwindow * window, double xpos, double ypos)
References _GLFWwindow::callbacks, _GLFWwindow::cursorPos, _GLFWwindow::virtualCursorPosX, and _GLFWwindow::virtualCursorPosY.
Referenced by handlePointerMotion(), handleRelativeMotion(), pointerHandleMotion(), processEvent(), and windowProc().
_glfwInputCursorEnter()
void _glfwInputCursorEnter (_GLFWwindow * window, GLFWbool entered)
References _GLFWwindow::callbacks, and _GLFWwindow::cursorEnter.
Referenced by _glfwPlatformDestroyWindow(), pointerHandleEnter(), pointerHandleLeave(), processEvent(), and windowProc().
_glfwInputDrop()
void _glfwInputDrop (_GLFWwindow * window, int count, const char ** names)
References _GLFWwindow::callbacks, and _GLFWwindow::drop.
Referenced by processEvent(), and windowProc().
_glfwInputJoystick()
void _glfwInputJoystick (_GLFWjoystick * js, int event)
References _glfw, _GLFWlibrary::callbacks, _GLFWlibrary::joystick, and _GLFWlibrary::joysticks.
Referenced by _glfwDetectJoystickConnectionWin32(), closeJoystick(), deviceCallback(), matchCallback(), and openJoystickDevice().
_glfwInputJoystickAxis()
void _glfwInputJoystickAxis (_GLFWjoystick * js, int axis, float value)
References _GLFWjoystick::axes, and value.
Referenced by _glfwPlatformPollJoystick(), and handleAbsEvent().
_glfwInputJoystickButton()
void _glfwInputJoystickButton (_GLFWjoystick * js, int button, char value)
References _GLFWjoystick::buttons, and value.
Referenced by _glfwPlatformPollJoystick(), and handleKeyEvent().
_glfwInputJoystickHat()
void _glfwInputJoystickHat (_GLFWjoystick * js, int hat, char value)
References _GLFWjoystick::buttonCount, _GLFWjoystick::buttons, GLFW_PRESS, GLFW_RELEASE, _GLFWjoystick::hats, and value.
Referenced by _glfwPlatformPollJoystick(), and handleAbsEvent().
_glfwInputMonitor()
void _glfwInputMonitor (_GLFWmonitor * monitor, int action, int placement)
References _glfw, _GLFW_INSERT_FIRST, _glfwFreeMonitor(), _glfwPlatformGetWindowFrameSize(), _glfwPlatformGetWindowSize(), _glfwPlatformSetWindowMonitor(), _glfwPlatformSetWindowPos(), _GLFWlibrary::callbacks, GLFW_CONNECTED, GLFW_DISCONNECTED, height, memmove(), _GLFWwindow::monitor, _GLFWlibrary::monitor, _GLFWlibrary::monitorCount, _GLFWlibrary::monitors, _GLFWwindow::next, NULL, width, and _GLFWlibrary::windowListHead.
Referenced by _glfwPollMonitorsMir(), _glfwPollMonitorsNS(), _glfwPollMonitorsWin32(), _glfwPollMonitorsX11(), done(), and registryHandleGlobalRemove().
_glfwInputMonitorWindow()
void _glfwInputMonitorWindow (_GLFWmonitor * monitor, _GLFWwindow * window)
References _GLFWmonitor::window.
Referenced by acquireMonitor(), and releaseMonitor().
_glfwInputError()
void _glfwInputError (int code, const char * format, ...)
References _glfw, _GLFW_MESSAGE_SIZE, _glfwErrorCallback, _glfwMainThreadError, _glfwPlatformGetTls(), _glfwPlatformLockMutex(), _glfwPlatformSetTls(), _glfwPlatformUnlockMutex(), _GLFWerror::code, setup::description, _GLFWerror::description, _GLFWlibrary::errorListHead, _GLFWlibrary::errorLock, _GLFWlibrary::errorSlot, getErrorString(), _GLFWlibrary::initialized, and _GLFWerror::next.
Referenced by _glfwAddOutputWayland(), _glfwChooseVisualGLX(), _glfwCreateContextEGL(), _glfwCreateContextGLX(), _glfwCreateContextNSGL(), _glfwCreateContextOSMesa(), _glfwCreateContextWGL(), _glfwDetectJoystickConnectionWin32(), _glfwInitEGL(), _glfwInitGLX(), _glfwInitJoysticksLinux(), _glfwInitJoysticksNS(), _glfwInitJoysticksWin32(), _glfwInitNSGL(), _glfwInitOSMesa(), _glfwInitVulkan(), _glfwInputErrorWin32(), _glfwInputErrorX11(), _glfwIsValidContextConfig(), _glfwPlatformCreateMutex(), _glfwPlatformCreateStandardCursor(), _glfwPlatformCreateTls(), _glfwPlatformCreateWindow(), _glfwPlatformCreateWindowSurface(), _glfwPlatformFocusWindow(), _glfwPlatformFramebufferTransparent(), _glfwPlatformGetClipboardString(), _glfwPlatformGetCursorPos(), _glfwPlatformGetGammaRamp(), _glfwPlatformGetMonitorContentScale(), _glfwPlatformGetPhysicalDevicePresentationSupport(), _glfwPlatformGetScancodeName(), _glfwPlatformGetVideoModes(), _glfwPlatformGetWindowFrameSize(), _glfwPlatformGetWindowPos(), _glfwPlatformIconifyWindow(), _glfwPlatformInit(), _glfwPlatformRequestWindowAttention(), _glfwPlatformRestoreWindow(), _glfwPlatformSetClipboardString(), _glfwPlatformSetCursor(), _glfwPlatformSetCursorPos(), _glfwPlatformSetGammaRamp(), _glfwPlatformSetWindowAspectRatio(), _glfwPlatformSetWindowDecorated(), _glfwPlatformSetWindowFloating(), _glfwPlatformSetWindowIcon(), _glfwPlatformSetWindowMonitor(), _glfwPlatformSetWindowPos(), _glfwPlatformSetWindowResizable(), _glfwPlatformWindowHovered(), _glfwPlatformWindowIconified(), _glfwRefreshContextAttribs(), _glfwSetVideoModeWin32(), chooseEGLConfig(), chooseGLXFBConfig(), choosePixelFormat(), createNativeWindow(), createShellSurface(), createShmBuffer(), createWindow(), createXdgSurface(), deviceCallback(), findValidMapping(), getDisplayName(), getSelectionString(), glfwCreateStandardCursor(), glfwCreateWindow(), glfwCreateWindowSurface(), glfwExtensionSupported(), glfwGetEGLContext(), glfwGetEGLSurface(), glfwGetGamepadName(), glfwGetGamepadState(), glfwGetGLXContext(), glfwGetGLXWindow(), glfwGetInputMode(), glfwGetJoystickAxes(), glfwGetJoystickButtons(), glfwGetJoystickGUID(), glfwGetJoystickHats(), glfwGetJoystickName(), glfwGetKey(), glfwGetKeyScancode(), glfwGetMouseButton(), glfwGetNSGLContext(), glfwGetOSMesaColorBuffer(), glfwGetOSMesaContext(), glfwGetOSMesaDepthBuffer(), glfwGetPhysicalDevicePresentationSupport(), glfwGetProcAddress(), glfwGetWGLContext(), glfwGetWindowAttrib(), glfwInitHint(), glfwJoystickIsGamepad(), glfwJoystickPresent(), glfwMakeContextCurrent(), glfwSetCursorPos(), glfwSetGamma(), glfwSetGammaRamp(), glfwSetInputMode(), glfwSetTime(), glfwSetWindowAspectRatio(), glfwSetWindowAttrib(), glfwSetWindowMonitor(), glfwSetWindowOpacity(), glfwSetWindowSizeLimits(), glfwSetX11SelectionString(), glfwSwapBuffers(), glfwSwapInterval(), glfwWaitEventsTimeout(), glfwWindowHint(), glfwWindowHintString(), initExtensions(), initializeAppKit(), initializeTIS(), keyboardHandleKeymap(), lockPointer(), makeContextCurrentEGL(), makeContextCurrentGLX(), makeContextCurrentOSMesa(), openJoystickDevice(), parseMapping(), setCursor(), setIdleInhibitor(), swapBuffersEGL(), updateUnicodeDataNS(), and windowProc().
_glfwStringInExtensionString()
GLFWbool _glfwStringInExtensionString (const char * string, const char * extensions)
References GLFW_FALSE, and GLFW_TRUE.
Referenced by extensionSupportedEGL(), extensionSupportedGLX(), extensionSupportedWGL(), and glfwExtensionSupported().
_glfwChooseFBConfig()
const _GLFWfbconfig* _glfwChooseFBConfig (const _GLFWfbconfig * desired, const _GLFWfbconfig * alternatives, unsigned int count)
References _GLFWfbconfig::accumAlphaBits, _GLFWfbconfig::accumBlueBits, _GLFWfbconfig::accumGreenBits, _GLFWfbconfig::accumRedBits, _GLFWfbconfig::alphaBits, _GLFWfbconfig::auxBuffers, _GLFWfbconfig::blueBits, _GLFWfbconfig::depthBits, _GLFWfbconfig::doublebuffer, GLFW_DONT_CARE, _GLFWfbconfig::greenBits, NULL, _GLFWfbconfig::redBits, _GLFWfbconfig::samples, _GLFWfbconfig::sRGB, _GLFWfbconfig::stencilBits, _GLFWfbconfig::stereo, and _GLFWfbconfig::transparent.
Referenced by chooseEGLConfig(), chooseGLXFBConfig(), and choosePixelFormat().
_glfwRefreshContextAttribs()
GLFWbool _glfwRefreshContextAttribs (_GLFWwindow * window, const _GLFWctxconfig * ctxconfig)
References _glfw, _glfwInputError(), _glfwPlatformGetTls(), _GLFWctxconfig::client, _GLFWcontext::client, _GLFWwindow::context, _GLFWlibrary::contextSlot, _GLFWctxconfig::debug, GL_COLOR_BUFFER_BIT, GL_CONTEXT_COMPATIBILITY_PROFILE_BIT, GL_CONTEXT_CORE_PROFILE_BIT, GL_CONTEXT_FLAG_DEBUG_BIT, GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT, GL_CONTEXT_FLAG_NO_ERROR_BIT_KHR, GL_CONTEXT_FLAGS, GL_CONTEXT_PROFILE_MASK, GL_CONTEXT_RELEASE_BEHAVIOR, GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH, GL_LOSE_CONTEXT_ON_RESET_ARB, GL_NO_RESET_NOTIFICATION_ARB, GL_NONE, GL_RESET_NOTIFICATION_STRATEGY_ARB, GL_VERSION, GLFW_FALSE, GLFW_LOSE_CONTEXT_ON_RESET, GLFW_NO_RESET_NOTIFICATION, GLFW_OPENGL_API, GLFW_OPENGL_COMPAT_PROFILE, GLFW_OPENGL_CORE_PROFILE, GLFW_OPENGL_ES_API, GLFW_PLATFORM_ERROR, GLFW_RELEASE_BEHAVIOR_FLUSH, GLFW_RELEASE_BEHAVIOR_NONE, GLFW_TRUE, GLFW_VERSION_UNAVAILABLE, glfwExtensionSupported(), glfwMakeContextCurrent(), _GLFWctxconfig::major, _GLFWctxconfig::minor, NULL, _GLFWctxconfig::source, _GLFWcontext::source, and create_symbols_file::version.
Referenced by glfwCreateWindow().
_glfwIsValidContextConfig()
GLFWbool _glfwIsValidContextConfig (const _GLFWctxconfig * ctxconfig)
References _glfwInputError(), _GLFWctxconfig::client, _GLFWcontext::client, _GLFWwindow::context, _GLFWctxconfig::forward, GLFW_EGL_CONTEXT_API, GLFW_FALSE, GLFW_INVALID_ENUM, GLFW_INVALID_VALUE, GLFW_LOSE_CONTEXT_ON_RESET, GLFW_NATIVE_CONTEXT_API, GLFW_NO_API, GLFW_NO_RESET_NOTIFICATION, GLFW_NO_WINDOW_CONTEXT, GLFW_OPENGL_API, GLFW_OPENGL_COMPAT_PROFILE, GLFW_OPENGL_CORE_PROFILE, GLFW_OPENGL_ES_API, GLFW_OSMESA_CONTEXT_API, GLFW_RELEASE_BEHAVIOR_FLUSH, GLFW_RELEASE_BEHAVIOR_NONE, GLFW_TRUE, _GLFWctxconfig::major, _GLFWctxconfig::minor, NULL, _GLFWctxconfig::profile, _GLFWctxconfig::release, _GLFWctxconfig::robustness, _GLFWctxconfig::share, and _GLFWctxconfig::source.
Referenced by glfwCreateWindow().
_glfwChooseVideoMode()
const GLFWvidmode* _glfwChooseVideoMode (_GLFWmonitor * monitor, const GLFWvidmode * desired)
References GLFWvidmode::blueBits, GLFW_DONT_CARE, GLFWvidmode::greenBits, GLFWvidmode::height, _GLFWmonitor::modeCount, _GLFWmonitor::modes, NULL, GLFWvidmode::redBits, GLFWvidmode::refreshRate, refreshVideoModes(), and GLFWvidmode::width.
Referenced by _glfwSetVideoModeNS(), _glfwSetVideoModeWin32(), and _glfwSetVideoModeX11().
_glfwCompareVideoModes()
int _glfwCompareVideoModes (const GLFWvidmode * first, const GLFWvidmode * second)
References compareVideoModes().
Referenced by _glfwPlatformGetVideoModes(), _glfwSetVideoModeNS(), _glfwSetVideoModeWin32(), and _glfwSetVideoModeX11().
_glfwAllocMonitor()
_GLFWmonitor* _glfwAllocMonitor (const char * name, int widthMM, int heightMM)
References _glfw_strdup(), _GLFWmonitor::heightMM, setup::name, _GLFWmonitor::name, and _GLFWmonitor::widthMM.
Referenced by _glfwAddOutputWayland(), _glfwPollMonitorsMir(), _glfwPollMonitorsNS(), _glfwPollMonitorsX11(), and createMonitor().
_glfwFreeMonitor()
void _glfwFreeMonitor (_GLFWmonitor * monitor)
References _glfwFreeGammaArrays(), _glfwPlatformFreeMonitor(), _GLFWmonitor::currentRamp, _GLFWmonitor::modes, _GLFWmonitor::name, NULL, and _GLFWmonitor::originalRamp.
Referenced by _glfwAddOutputWayland(), _glfwInputMonitor(), and terminate().
_glfwAllocGammaArrays()
void _glfwAllocGammaArrays (GLFWgammaramp * ramp, unsigned int size)
References GLFWgammaramp::blue, GLFWgammaramp::green, GLFWgammaramp::red, and GLFWgammaramp::size.
Referenced by _glfwPlatformGetGammaRamp().
_glfwFreeGammaArrays()
void _glfwFreeGammaArrays (GLFWgammaramp * ramp)
References GLFWgammaramp::blue, GLFWgammaramp::green, memset(), and GLFWgammaramp::red.
Referenced by _glfwFreeMonitor(), and glfwGetGammaRamp().
_glfwSplitBPP()
void _glfwSplitBPP (int bpp, int * red, int * green, int * blue)
Referenced by _glfwPlatformGetVideoMode(), _glfwPlatformGetVideoModes(), and vidmodeFromModeInfo().
_glfwAllocJoystick()
_GLFWjoystick* _glfwAllocJoystick (const char * name, const char * guid, int axisCount, int buttonCount, int hatCount)
References _glfw, _glfw_strdup(), _GLFWjoystick::axes, _GLFWjoystick::axisCount, _GLFWjoystick::buttonCount, _GLFWjoystick::buttons, findValidMapping(), GLFW_JOYSTICK_LAST, GLFW_TRUE, _GLFWjoystick::guid, _GLFWjoystick::hatCount, _GLFWjoystick::hats, _GLFWlibrary::joysticks, _GLFWjoystick::mapping, setup::name, _GLFWjoystick::name, NULL, and _GLFWjoystick::present.
Referenced by _glfwDetectJoystickConnectionWin32(), deviceCallback(), matchCallback(), and openJoystickDevice().
_glfwFreeJoystick()
void _glfwFreeJoystick (_GLFWjoystick * js)
References _GLFWjoystick::axes, _GLFWjoystick::buttons, _GLFWjoystick::hats, memset(), and _GLFWjoystick::name.
Referenced by closeJoystick().
_glfwInitVulkan()
GLFWbool _glfwInitVulkan (int mode)
References _glfw, _GLFW_REQUIRE_LOADER, _glfwGetVulkanResultString(), _glfwInputError(), _glfwPlatformGetRequiredInstanceExtensions(), _glfwTerminateVulkan(), _GLFWlibrary::available, _GLFWlibrary::extensions, GLFW_API_UNAVAILABLE, GLFW_FALSE, GLFW_TRUE, _GLFWlibrary::KHR_surface, mode(), NULL, _GLFWlibrary::vk, and vkEnumerateInstanceExtensionProperties().
Referenced by glfwCreateWindowSurface(), glfwGetInstanceProcAddress(), glfwGetPhysicalDevicePresentationSupport(), glfwGetRequiredInstanceExtensions(), and glfwVulkanSupported().
_glfwTerminateVulkan()
void _glfwTerminateVulkan (void)
Referenced by _glfwInitVulkan(), and terminate().
_glfwGetVulkanResultString()
const char* _glfwGetVulkanResultString (VkResult result)
References VK_ERROR_DEVICE_LOST, VK_ERROR_EXTENSION_NOT_PRESENT, VK_ERROR_FEATURE_NOT_PRESENT, VK_ERROR_FORMAT_NOT_SUPPORTED, VK_ERROR_INCOMPATIBLE_DISPLAY_KHR, VK_ERROR_INCOMPATIBLE_DRIVER, VK_ERROR_INITIALIZATION_FAILED, VK_ERROR_LAYER_NOT_PRESENT, VK_ERROR_MEMORY_MAP_FAILED, VK_ERROR_NATIVE_WINDOW_IN_USE_KHR, VK_ERROR_OUT_OF_DATE_KHR, VK_ERROR_OUT_OF_DEVICE_MEMORY, VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_SURFACE_LOST_KHR, VK_ERROR_TOO_MANY_OBJECTS, VK_ERROR_VALIDATION_FAILED_EXT, VK_EVENT_RESET, VK_EVENT_SET, VK_INCOMPLETE, VK_NOT_READY, VK_SUBOPTIMAL_KHR, VK_SUCCESS, and VK_TIMEOUT.
Referenced by _glfwInitVulkan(), and _glfwPlatformCreateWindowSurface().
_glfw_strdup()
char* _glfw_strdup (const char * source)
References source.
Referenced by _glfwAllocJoystick(), _glfwAllocMonitor(), _glfwPlatformCreateWindow(), _glfwPlatformGetClipboardString(), _glfwPlatformSetClipboardString(), _glfwPlatformSetWindowTitle(), _glfwPollMonitorsNS(), geometry(), getSelectionString(), and glfwSetX11SelectionString().
Variable Documentation
_glfw
_GLFWlibrary _glfw
Referenced by _glfwAddOutputWayland(), _glfwAllocJoystick(), _glfwChooseVisualGLX(), _glfwCreateContextEGL(), _glfwCreateContextGLX(), _glfwCreateContextWGL(), _glfwCreateCursorX11(), _glfwDetectJoystickConnectionLinux(), _glfwDetectJoystickConnectionWin32(), _glfwDetectJoystickDisconnectionWin32(), _glfwGetWindowPropertyX11(), _glfwGrabErrorHandlerX11(), _glfwInitEGL(), _glfwInitGLX(), _glfwInitJoysticksLinux(), _glfwInitJoysticksNS(), _glfwInitJoysticksWin32(), _glfwInitNSGL(), _glfwInitOSMesa(), _glfwInitTimerNS(), _glfwInitTimerPOSIX(), _glfwInitTimerWin32(), _glfwInitVulkan(), _glfwInitWGL(), _glfwInputError(), _glfwInputErrorX11(), _glfwInputJoystick(), _glfwInputMonitor(), _glfwIsVisualTransparentX11(), _glfwPlatformCreateCursor(), _glfwPlatformCreateStandardCursor(), _glfwPlatformCreateWindow(), _glfwPlatformCreateWindowSurface(), _glfwPlatformDestroyCursor(), _glfwPlatformDestroyWindow(), _glfwPlatformFocusWindow(), _glfwPlatformFramebufferTransparent(), _glfwPlatformGetClipboardString(), _glfwPlatformGetCursorPos(), _glfwPlatformGetGammaRamp(), _glfwPlatformGetKeyScancode(), _glfwPlatformGetMonitorContentScale(), _glfwPlatformGetMonitorPos(), _glfwPlatformGetPhysicalDevicePresentationSupport(), _glfwPlatformGetRequiredInstanceExtensions(), _glfwPlatformGetScancodeName(), _glfwPlatformGetTimerFrequency(), _glfwPlatformGetTimerValue(), _glfwPlatformGetVideoMode(), _glfwPlatformGetVideoModes(), _glfwPlatformGetWindowContentScale(), _glfwPlatformGetWindowFrameSize(), _glfwPlatformGetWindowOpacity(), _glfwPlatformGetWindowPos(), _glfwPlatformGetWindowSize(), _glfwPlatformHideWindow(), _glfwPlatformIconifyWindow(), _glfwPlatformInit(), _glfwPlatformMaximizeWindow(), _glfwPlatformPollEvents(), _glfwPlatformPollJoystick(), _glfwPlatformPostEmptyEvent(), _glfwPlatformRequestWindowAttention(), _glfwPlatformRestoreWindow(), _glfwPlatformSetClipboardString(), _glfwPlatformSetCursor(), _glfwPlatformSetCursorMode(), _glfwPlatformSetCursorPos(), _glfwPlatformSetGammaRamp(), _glfwPlatformSetWindowAspectRatio(), _glfwPlatformSetWindowDecorated(), _glfwPlatformSetWindowFloating(), _glfwPlatformSetWindowIcon(), _glfwPlatformSetWindowMonitor(), _glfwPlatformSetWindowOpacity(), _glfwPlatformSetWindowPos(), _glfwPlatformSetWindowSize(), _glfwPlatformSetWindowSizeLimits(), _glfwPlatformSetWindowTitle(), _glfwPlatformShowWindow(), _glfwPlatformTerminate(), _glfwPlatformWaitEvents(), _glfwPlatformWaitEventsTimeout(), _glfwPlatformWindowFocused(), _glfwPlatformWindowHovered(), _glfwPlatformWindowMaximized(), _glfwPlatformWindowVisible(), _glfwPollMonitorsMir(), _glfwPollMonitorsNS(), _glfwPollMonitorsWin32(), _glfwPollMonitorsX11(), _glfwPushSelectionToManagerX11(), _glfwRefreshContextAttribs(), _glfwReleaseErrorHandlerX11(), _glfwRestoreVideoModeX11(), _glfwSetVideoModeX11(), _glfwTerminateEGL(), _glfwTerminateGLX(), _glfwTerminateJoysticksLinux(), _glfwTerminateJoysticksNS(), _glfwTerminateJoysticksWin32(), _glfwTerminateOSMesa(), _glfwTerminateWGL(), _glfwUpdateKeyNamesWin32(), acquireMonitor(), checkScaleChange(), chooseEGLConfig(), chooseGLXFBConfig(), choosePixelFormat(), createDecoration(), createDecorations(), createHelperWindow(), createKeyTables(), createLegacyContextGLX(), createNativeWindow(), createShellSurface(), createShmBuffer(), createSurface(), createWindow(), createXdgSurface(), dequeueEvent(), destroyContextEGL(), destroyContextGLX(), detectEWMH(), deviceCallback(), enqueueEvent(), errorHandler(), extensionSupportedEGL(), extensionSupportedGLX(), extensionSupportedWGL(), findMapping(), findValidPixelFormat(), findWindowByHandle(), findWindowFromDecorationSurface(), freeLibraries(), getEGLConfigAttrib(), getGLXFBConfigAttrib(), getPixelFormatAttrib(), getProcAddressEGL(), getProcAddressGLX(), getProcAddressNSGL(), getProcAddressWGL(), getSelectionString(), getSupportedAtom(), getSystemContentScale(), getWindowState(), glfwCreateCursor(), glfwCreateStandardCursor(), glfwCreateWindow(), glfwCreateWindowSurface(), glfwDefaultWindowHints(), glfwDestroyCursor(), glfwDestroyWindow(), glfwExtensionSupported(), glfwGetCurrentContext(), glfwGetEGLDisplay(), glfwGetError(), glfwGetGamepadName(), glfwGetGamepadState(), glfwGetJoystickAxes(), glfwGetJoystickButtons(), glfwGetJoystickGUID(), glfwGetJoystickHats(), glfwGetJoystickName(), glfwGetJoystickUserPointer(), glfwGetMirDisplay(), glfwGetMonitors(), glfwGetPhysicalDevicePresentationSupport(), glfwGetPrimaryMonitor(), glfwGetProcAddress(), glfwGetRequiredInstanceExtensions(), glfwGetTime(), glfwGetWaylandDisplay(), glfwGetX11Display(), glfwGetX11SelectionString(), glfwInit(), glfwJoystickIsGamepad(), glfwJoystickPresent(), glfwMakeContextCurrent(), glfwPostEmptyEvent(), glfwSetJoystickCallback(), glfwSetJoystickUserPointer(), glfwSetMonitorCallback(), glfwSetTime(), glfwSetX11SelectionString(), glfwSwapInterval(), glfwTerminate(), glfwUpdateGamepadMappings(), glfwWaitEvents(), glfwWindowHint(), glfwWindowHintString(), handleConfigure(), handleEvents(), handlePointerMotion(), handleSelectionClear(), handleSelectionRequest(), hasUsableInputMethodStyle(), hideCursor(), initExtensions(), initializeAppKit(), initializeTIS(), inputChar(), isFrameExtentsEvent(), isSelectionEvent(), keyboardHandleEnter(), keyboardHandleKey(), keyboardHandleKeymap(), keyboardHandleLeave(), keyboardHandleModifiers(), loadLibraries(), lockPointer(), makeContextCurrentEGL(), makeContextCurrentGLX(), makeContextCurrentNSGL(), makeContextCurrentOSMesa(), makeContextCurrentWGL(), matchCallback(), openJoystickDevice(), pointerHandleAxis(), pointerHandleButton(), pointerHandleEnter(), pointerHandleLeave(), pointerHandleMotion(), processEvent(), registryHandleGlobal(), registryHandleGlobalRemove(), releaseMonitor(), removeCallback(), seatHandleCapabilities(), sendEventToWM(), setCursor(), setCursorNameForWindow(), setIdleInhibitor(), setOpaqueRegion(), setWindowConfinement(), showCursor(), swapBuffersEGL(), swapBuffersGLX(), swapIntervalEGL(), swapIntervalGLX(), swapIntervalNSGL(), swapIntervalWGL(), terminate(), toGLFWKeyCode(), translateKey(), translateKeyCode(), updateCursorImage(), updateNormalHints(), updateUnicodeDataNS(), updateWindowMode(), vidmodeFromModeInfo(), waitForEvent(), waitForVisibilityNotify(), windowProc(), and writeTargetToProperty().