Aurora Framework: vox_adpcm.c File Reference
vox_adpcm.c File Reference
Functions
static int codec_close (SF_PRIVATE *psf)
int vox_adpcm_init (SF_PRIVATE *psf)
static int vox_read_block (SF_PRIVATE *psf, IMA_OKI_ADPCM *pvox, short *ptr, int len)
static sf_count_t vox_read_d (SF_PRIVATE *psf, double *ptr, sf_count_t len)
static sf_count_t vox_read_f (SF_PRIVATE *psf, float *ptr, sf_count_t len)
static sf_count_t vox_read_i (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static sf_count_t vox_read_s (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static int vox_write_block (SF_PRIVATE *psf, IMA_OKI_ADPCM *pvox, const short *ptr, int len)
static sf_count_t vox_write_d (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
static sf_count_t vox_write_f (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
static sf_count_t vox_write_i (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
static sf_count_t vox_write_s (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
Function Documentation
vox_read_s()
static sf_count_t vox_read_s (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
References sf_private_tag::codec_data, and vox_read_block().
Referenced by vox_adpcm_init().
vox_read_i()
static sf_count_t vox_read_i (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
References arith_shift_left(), ARRAY_LEN, sf_private_tag::codec_data, BUF_UNION::sbuf, and vox_read_block().
Referenced by vox_adpcm_init().
vox_read_f()
static sf_count_t vox_read_f (SF_PRIVATE * psf, float * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, sf_private_tag::norm_float, BUF_UNION::sbuf, and vox_read_block().
Referenced by vox_adpcm_init().
vox_read_d()
static sf_count_t vox_read_d (SF_PRIVATE * psf, double * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, sf_private_tag::norm_double, BUF_UNION::sbuf, and vox_read_block().
Referenced by vox_adpcm_init().
vox_write_s()
static sf_count_t vox_write_s (SF_PRIVATE * psf, const short * ptr, sf_count_t len) static
References sf_private_tag::codec_data, and vox_write_block().
Referenced by vox_adpcm_init().
vox_write_i()
static sf_count_t vox_write_i (SF_PRIVATE * psf, const int * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, BUF_UNION::sbuf, and vox_write_block().
Referenced by vox_adpcm_init().
vox_write_f()
static sf_count_t vox_write_f (SF_PRIVATE * psf, const float * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, sf_private_tag::norm_float, BUF_UNION::sbuf, and vox_write_block().
Referenced by vox_adpcm_init().
vox_write_d()
static sf_count_t vox_write_d (SF_PRIVATE * psf, const double * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, sf_private_tag::norm_double, BUF_UNION::sbuf, and vox_write_block().
Referenced by vox_adpcm_init().
vox_read_block()
static int vox_read_block (SF_PRIVATE * psf, IMA_OKI_ADPCM * pvox, short * ptr, int len) static
References IMA_OKI_ADPCM::code_count, IMA_OKI_ADPCM::codes, sf_private_tag::filelength, IMA_OKI_ADPCM_CODE_LEN, ima_oki_adpcm_decode_block(), IMA_OKI_ADPCM_PCM_LEN, memcpy(), IMA_OKI_ADPCM::pcm, IMA_OKI_ADPCM::pcm_count, psf_fread(), psf_ftell(), and psf_log_printf().
Referenced by vox_read_d(), vox_read_f(), vox_read_i(), and vox_read_s().
codec_close()
static int codec_close (SF_PRIVATE * psf) static
References sf_private_tag::codec_data, IMA_OKI_ADPCM::errors, and psf_log_printf().
Referenced by vox_adpcm_init().
vox_adpcm_init()
int vox_adpcm_init (SF_PRIVATE * psf)
References codec_close(), sf_private_tag::codec_close, sf_private_tag::codec_data, sf_private_tag::file, sf_private_tag::filelength, ima_oki_adpcm_init(), IMA_OKI_ADPCM_TYPE_OKI, memset(), PSF_FILE::mode, NULL, psf_fseek(), psf_log_printf(), sf_private_tag::read_double, sf_private_tag::read_float, sf_private_tag::read_int, sf_private_tag::read_short, sf_private_tag::sf, SFE_BAD_MODE_RW, SFE_BAD_SEEK, SFE_CHANNEL_COUNT, SFE_MALLOC_FAILED, vox_read_d(), vox_read_f(), vox_read_i(), vox_read_s(), vox_write_d(), vox_write_f(), vox_write_i(), vox_write_s(), sf_private_tag::write_double, sf_private_tag::write_float, sf_private_tag::write_int, and sf_private_tag::write_short.
Referenced by raw_open().
vox_write_block()
static int vox_write_block (SF_PRIVATE * psf, IMA_OKI_ADPCM * pvox, const short * ptr, int len) static
References IMA_OKI_ADPCM::code_count, IMA_OKI_ADPCM::codes, ima_oki_adpcm_encode_block(), IMA_OKI_ADPCM_PCM_LEN, memcpy(), IMA_OKI_ADPCM::pcm, IMA_OKI_ADPCM::pcm_count, psf_fwrite(), and psf_log_printf().
Referenced by vox_write_d(), vox_write_f(), vox_write_i(), and vox_write_s().