Aurora Framework: Monitor.c File Reference
X11/Monitor.c File Reference
Functions
void _glfwPlatformFreeMonitor (_GLFWmonitor *monitor)
void _glfwPlatformGetGammaRamp (_GLFWmonitor *monitor, GLFWgammaramp *ramp)
void _glfwPlatformGetMonitorContentScale (_GLFWmonitor *monitor, float *xscale, float *yscale)
void _glfwPlatformGetMonitorPos (_GLFWmonitor *monitor, int *xpos, int *ypos)
void _glfwPlatformGetVideoMode (_GLFWmonitor *monitor, GLFWvidmode *mode)
GLFWvidmode * _glfwPlatformGetVideoModes (_GLFWmonitor *monitor, int *count)
void _glfwPlatformSetGammaRamp (_GLFWmonitor *monitor, const GLFWgammaramp *ramp)
void _glfwPollMonitorsX11 (void)
void _glfwRestoreVideoModeX11 (_GLFWmonitor *monitor)
void _glfwSetVideoModeX11 (_GLFWmonitor *monitor, const GLFWvidmode *desired)
static int calculateRefreshRate (const XRRModeInfo *mi)
static const XRRModeInfo * getModeInfo (const XRRScreenResources *sr, RRMode id)
GLFWAPI RRCrtc glfwGetX11Adapter (GLFWmonitor *handle)
GLFWAPI RROutput glfwGetX11Monitor (GLFWmonitor *handle)
static GLFWbool modeIsGood (const XRRModeInfo *mi)
static GLFWvidmode vidmodeFromModeInfo (const XRRModeInfo *mi, const XRRCrtcInfo *ci)
Function Documentation
modeIsGood()
static GLFWbool modeIsGood (const XRRModeInfo * mi) static
Referenced by _glfwPlatformGetVideoModes(), and _glfwSetVideoModeX11().
calculateRefreshRate()
static int calculateRefreshRate (const XRRModeInfo * mi) static
Referenced by vidmodeFromModeInfo().
getModeInfo()
static const XRRModeInfo* getModeInfo (const XRRScreenResources * sr, RRMode id) static
References NULL.
Referenced by _glfwPlatformGetVideoMode(), _glfwPlatformGetVideoModes(), and _glfwSetVideoModeX11().
vidmodeFromModeInfo()
static GLFWvidmode vidmodeFromModeInfo (const XRRModeInfo * mi, const XRRCrtcInfo * ci) static
References _glfw, _glfwSplitBPP(), calculateRefreshRate(), and mode().
Referenced by _glfwPlatformGetVideoMode(), _glfwPlatformGetVideoModes(), and _glfwSetVideoModeX11().
_glfwPollMonitorsX11()
void _glfwPollMonitorsX11 (void)
References _glfw, _GLFW_INSERT_FIRST, _GLFW_INSERT_LAST, _glfwAllocMonitor(), _glfwInputMonitor(), _GLFWlibrary::available, GLFW_CONNECTED, GLFW_DISCONNECTED, memcpy(), _GLFWlibrary::monitorCount, _GLFWlibrary::monitors, AuroraFW::None, NULL, XineramaQueryScreens, XRRFreeCrtcInfo, XRRFreeOutputInfo, XRRFreeScreenResources, XRRGetCrtcInfo, XRRGetOutputInfo, XRRGetOutputPrimary, and XRRGetScreenResourcesCurrent.
Referenced by _glfwPlatformInit(), and processEvent().
_glfwSetVideoModeX11()
void _glfwSetVideoModeX11 (_GLFWmonitor * monitor, const GLFWvidmode * desired)
References _glfw, _glfwChooseVideoMode(), _glfwCompareVideoModes(), _glfwPlatformGetVideoMode(), _GLFWlibrary::available, getModeInfo(), mode(), modeIsGood(), AuroraFW::None, vidmodeFromModeInfo(), XRRFreeCrtcInfo, XRRFreeOutputInfo, XRRFreeScreenResources, XRRGetCrtcInfo, XRRGetOutputInfo, XRRGetScreenResourcesCurrent, and XRRSetCrtcConfig.
Referenced by acquireMonitor().
_glfwRestoreVideoModeX11()
void _glfwRestoreVideoModeX11 (_GLFWmonitor * monitor)
References _glfw, _GLFWlibrary::available, AuroraFW::None, XRRFreeCrtcInfo, XRRFreeScreenResources, XRRGetCrtcInfo, XRRGetScreenResourcesCurrent, and XRRSetCrtcConfig.
Referenced by releaseMonitor().
_glfwPlatformFreeMonitor()
void _glfwPlatformFreeMonitor (_GLFWmonitor * monitor)
_glfwPlatformGetMonitorPos()
void _glfwPlatformGetMonitorPos (_GLFWmonitor * monitor, int * xpos, int * ypos)
References _glfw, _GLFWlibrary::available, XRRFreeCrtcInfo, XRRFreeScreenResources, XRRGetCrtcInfo, and XRRGetScreenResourcesCurrent.
_glfwPlatformGetMonitorContentScale()
void _glfwPlatformGetMonitorContentScale (_GLFWmonitor * monitor, float * xscale, float * yscale)
References _glfw, _glfwInputError(), and GLFW_PLATFORM_ERROR.
_glfwPlatformGetVideoModes()
GLFWvidmode* _glfwPlatformGetVideoModes (_GLFWmonitor * monitor, int * count)
References _glfw, _glfwCompareVideoModes(), _glfwPlatformGetVideoMode(), _GLFWlibrary::available, getModeInfo(), mode(), modeIsGood(), NULL, vidmodeFromCGDisplayMode(), vidmodeFromModeInfo(), XRRFreeCrtcInfo, XRRFreeOutputInfo, XRRFreeScreenResources, XRRGetCrtcInfo, XRRGetOutputInfo, and XRRGetScreenResourcesCurrent.
_glfwPlatformGetVideoMode()
void _glfwPlatformGetVideoMode (_GLFWmonitor * monitor, GLFWvidmode * mode)
References _glfw, _glfwSplitBPP(), _GLFWlibrary::available, getModeInfo(), mode(), vidmodeFromCGDisplayMode(), vidmodeFromModeInfo(), XRRFreeCrtcInfo, XRRFreeScreenResources, XRRGetCrtcInfo, and XRRGetScreenResourcesCurrent.
Referenced by _glfwPlatformGetVideoModes(), and _glfwSetVideoModeX11().
_glfwPlatformGetGammaRamp()
void _glfwPlatformGetGammaRamp (_GLFWmonitor * monitor, GLFWgammaramp * ramp)
References _glfw, _glfwAllocGammaArrays(), _GLFWlibrary::available, GLFWgammaramp::blue, GLFWgammaramp::green, memcpy(), GLFWgammaramp::red, GLFWgammaramp::size, XF86VidModeGetGammaRamp, XF86VidModeGetGammaRampSize, XRRFreeGamma, XRRGetCrtcGamma, and XRRGetCrtcGammaSize.
_glfwPlatformSetGammaRamp()
void _glfwPlatformSetGammaRamp (_GLFWmonitor * monitor, const GLFWgammaramp * ramp)
References _glfw, _glfwInputError(), _GLFWlibrary::available, GLFWgammaramp::blue, GLFW_PLATFORM_ERROR, GLFWgammaramp::green, memcpy(), GLFWgammaramp::red, GLFWgammaramp::size, XF86VidModeSetGammaRamp, XRRAllocGamma, XRRFreeGamma, XRRGetCrtcGammaSize, and XRRSetCrtcGamma.
glfwGetX11Adapter()
GLFWAPI RRCrtc glfwGetX11Adapter (GLFWmonitor * handle)
References _GLFW_REQUIRE_INIT_OR_RETURN, and AuroraFW::None.
glfwGetX11Monitor()
GLFWAPI RROutput glfwGetX11Monitor (GLFWmonitor * handle)
References _GLFW_REQUIRE_INIT_OR_RETURN, and AuroraFW::None.