Aurora Framework: alac.c File Reference
alac.c File Reference
Classes
struct ALAC_PRIVATE
struct PAKT_INFO
Macros
#define ALAC_BYTE_BUFFER_SIZE 0x20000
#define ALAC_MAX_CHANNEL_COUNT 8
#define ALAC_MAX_FRAME_SIZE 8192
#define CASE_NAME(x) case x : return #x ; break ;
Functions
static int alac_byterate (SF_PRIVATE *psf)
static int alac_close (SF_PRIVATE *psf)
static int alac_decode_block (SF_PRIVATE *psf, ALAC_PRIVATE *plac)
static int alac_encode_block (ALAC_PRIVATE *plac)
static const char * alac_error_string (int error)
void alac_get_desc_chunk_items (int subformat, uint32_t *fmt_flags, uint32_t *frames_per_packet)
int alac_init (SF_PRIVATE *psf, const ALAC_DECODER_INFO *info)
static uint32_t alac_kuki_read (SF_PRIVATE *psf, uint32_t kuki_offset, uint8_t *kuki, size_t kuki_maxlen)
static PAKT_INFO * alac_pakt_alloc (uint32_t initial_count)
static PAKT_INFO * alac_pakt_append (PAKT_INFO *info, uint32_t value)
static sf_count_t alac_pakt_block_offset (const PAKT_INFO *info, uint32_t block)
static uint8_t * alac_pakt_encode (const SF_PRIVATE *psf, uint32_t *pakt_size)
static PAKT_INFO * alac_pakt_read_decode (SF_PRIVATE *psf, uint32_t pakt_offset)
static PAKT_INFO * alac_pakt_read_decode (SF_PRIVATE *psf, uint32_t UNUSED(pakt_offset))
static sf_count_t alac_read_d (SF_PRIVATE *psf, double *ptr, sf_count_t len)
static sf_count_t alac_read_f (SF_PRIVATE *psf, float *ptr, sf_count_t len)
static sf_count_t alac_read_i (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static sf_count_t alac_read_s (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static sf_count_t alac_reader_calc_frames (SF_PRIVATE *psf, ALAC_PRIVATE *plac)
static int alac_reader_init (SF_PRIVATE *psf, const ALAC_DECODER_INFO *info)
static uint32_t alac_reader_next_packet_size (PAKT_INFO *info)
static sf_count_t alac_seek (SF_PRIVATE *psf, int mode, sf_count_t offset)
static sf_count_t alac_write_d (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
static sf_count_t alac_write_f (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
static sf_count_t alac_write_i (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
static sf_count_t alac_write_s (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
static int alac_writer_init (SF_PRIVATE *psf)
Macro Definition Documentation
ALAC_MAX_FRAME_SIZE
#define ALAC_MAX_FRAME_SIZE 8192
Referenced by alac_init().
ALAC_BYTE_BUFFER_SIZE
#define ALAC_BYTE_BUFFER_SIZE 0x20000
ALAC_MAX_CHANNEL_COUNT
#define ALAC_MAX_CHANNEL_COUNT 8
CASE_NAME
#define CASE_NAME (x) case x : return #x ; break ;
Referenced by alac_error_string().
Function Documentation
alac_reader_init()
static int alac_reader_init (SF_PRIVATE * psf, const ALAC_DECODER_INFO * info) static
References alac_close(), alac_decoder_init(), alac_error_string(), ALAC_FRAME_LENGTH, alac_kuki_read(), ALAC_noErr, alac_pakt_read_decode(), alac_read_d(), alac_read_f(), alac_read_i(), alac_read_s(), alac_reader_calc_frames(), alac_seek(), ALAC_PRIVATE::bits_per_sample, ALAC_DECODER_INFO::bits_per_sample, ALAC_PRIVATE::channels, sf_private_tag::codec_close, sf_private_tag::codec_data, ALAC_PRIVATE::decoder, ALAC_PRIVATE::frames_per_block, ALAC_DECODER_INFO::frames_per_packet, ALAC_DECODER_INFO::kuki_offset, alac_decoder_s::mNumChannels, NULL, ALAC_PRIVATE::pakt_info, ALAC_DECODER_INFO::pakt_offset, psf_log_printf(), sf_private_tag::read_double, sf_private_tag::read_float, sf_private_tag::read_int, sf_private_tag::read_short, sf_private_tag::seek, sf_private_tag::sf, SFE_INTERNAL, and SFE_UNSUPPORTED_ENCODING.
Referenced by alac_init().
alac_writer_init()
static int alac_writer_init (SF_PRIVATE * psf) static
References alac_encoder_init(), ALAC_FRAME_LENGTH, alac_get_magic_cookie_size(), alac_pakt_alloc(), alac_write_d(), alac_write_f(), alac_write_i(), alac_write_s(), ALAC_PRIVATE::bits_per_sample, ALAC_PRIVATE::channels, sf_private_tag::codec_data, ALAC_PRIVATE::encoder, ALAC_PRIVATE::enctmp, ALAC_PRIVATE::enctmpname, sf_private_tag::file, ALAC_PRIVATE::frames_per_block, ALAC_PRIVATE::kuki_size, PSF_FILE::mode, NULL, ALAC_PRIVATE::pakt_info, psf_log_printf(), psf_open_tmpfile(), sf_private_tag::sf, SF_CODEC, SFE_ALAC_FAIL_TMPFILE, SFE_BAD_MODE_RW, SFE_UNIMPLEMENTED, sf_private_tag::write_double, sf_private_tag::write_float, sf_private_tag::write_int, and sf_private_tag::write_short.
Referenced by alac_init().
alac_reader_calc_frames()
static sf_count_t alac_reader_calc_frames (SF_PRIVATE * psf, ALAC_PRIVATE * plac) static
References alac_decode_block(), alac_reader_next_packet_size(), alac_seek(), PAKT_INFO::current, ALAC_PRIVATE::frames_per_block, ALAC_PRIVATE::frames_this_block, and ALAC_PRIVATE::pakt_info.
Referenced by alac_reader_init().
alac_read_s()
static sf_count_t alac_read_s (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
References alac_decode_block(), ALAC_PRIVATE::buffer, ALAC_PRIVATE::channels, sf_private_tag::codec_data, ALAC_PRIVATE::frames_this_block, NULL, and ALAC_PRIVATE::partial_block_frames.
Referenced by alac_reader_init().
alac_read_i()
static sf_count_t alac_read_i (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
References alac_decode_block(), ALAC_PRIVATE::buffer, ALAC_PRIVATE::channels, sf_private_tag::codec_data, ALAC_PRIVATE::frames_this_block, NULL, and ALAC_PRIVATE::partial_block_frames.
Referenced by alac_reader_init().
alac_read_f()
static sf_count_t alac_read_f (SF_PRIVATE * psf, float * ptr, sf_count_t len) static
References alac_decode_block(), ALAC_PRIVATE::buffer, ALAC_PRIVATE::channels, sf_private_tag::codec_data, ALAC_PRIVATE::frames_this_block, sf_private_tag::norm_float, NULL, and ALAC_PRIVATE::partial_block_frames.
Referenced by alac_reader_init().
alac_read_d()
static sf_count_t alac_read_d (SF_PRIVATE * psf, double * ptr, sf_count_t len) static
References alac_decode_block(), ALAC_PRIVATE::buffer, ALAC_PRIVATE::channels, sf_private_tag::codec_data, ALAC_PRIVATE::frames_this_block, sf_private_tag::norm_double, NULL, and ALAC_PRIVATE::partial_block_frames.
Referenced by alac_reader_init().
alac_write_s()
static sf_count_t alac_write_s (SF_PRIVATE * psf, const short * ptr, sf_count_t len) static
References alac_encode_block(), arith_shift_left(), ALAC_PRIVATE::buffer, ALAC_PRIVATE::channels, sf_private_tag::codec_data, ALAC_PRIVATE::frames_per_block, NULL, and ALAC_PRIVATE::partial_block_frames.
Referenced by alac_writer_init().
alac_write_i()
static sf_count_t alac_write_i (SF_PRIVATE * psf, const int * ptr, sf_count_t len) static
References alac_encode_block(), ALAC_PRIVATE::buffer, ALAC_PRIVATE::channels, sf_private_tag::codec_data, ALAC_PRIVATE::frames_per_block, NULL, and ALAC_PRIVATE::partial_block_frames.
Referenced by alac_writer_init().
alac_write_f()
static sf_count_t alac_write_f (SF_PRIVATE * psf, const float * ptr, sf_count_t len) static
References sf_private_tag::add_clipping, alac_encode_block(), ALAC_PRIVATE::buffer, ALAC_PRIVATE::channels, sf_private_tag::codec_data, ALAC_PRIVATE::frames_per_block, sf_private_tag::norm_float, NULL, ALAC_PRIVATE::partial_block_frames, psf_f2i_array(), and psf_f2i_clip_array().
Referenced by alac_writer_init().
alac_write_d()
static sf_count_t alac_write_d (SF_PRIVATE * psf, const double * ptr, sf_count_t len) static
References sf_private_tag::add_clipping, alac_encode_block(), ALAC_PRIVATE::buffer, ALAC_PRIVATE::channels, sf_private_tag::codec_data, ALAC_PRIVATE::frames_per_block, sf_private_tag::norm_float, NULL, ALAC_PRIVATE::partial_block_frames, psf_d2i_array(), and psf_d2i_clip_array().
Referenced by alac_writer_init().
alac_seek()
static sf_count_t alac_seek (SF_PRIVATE * psf, int mode, sf_count_t offset) static
References alac_decode_block(), alac_pakt_block_offset(), sf_private_tag::codec_data, PAKT_INFO::count, PAKT_INFO::current, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::error, ALAC_PRIVATE::frames_per_block, ALAC_PRIVATE::frames_this_block, ALAC_PRIVATE::input_data_pos, mode(), ALAC_PRIVATE::pakt_info, ALAC_PRIVATE::partial_block_frames, psf_fseek(), PSF_SEEK_ERROR, and SFE_BAD_SEEK.
Referenced by alac_reader_calc_frames(), and alac_reader_init().
alac_close()
static int alac_close (SF_PRIVATE * psf) static
References alac_encode_block(), alac_get_magic_cookie(), alac_pakt_encode(), sf_private_tag::codec_data, ALAC_PRIVATE::encoder, ALAC_PRIVATE::enctmp, ALAC_PRIVATE::enctmpname, sf_private_tag::file, ALAC_PRIVATE::final_write_block, ALAC_PRIVATE::frames_per_block, ALAC_PRIVATE::kuki_size, memset(), PSF_FILE::mode, NULL, ALAC_PRIVATE::pakt_info, ALAC_PRIVATE::partial_block_frames, psf_fwrite(), psf_save_write_chunk(), BUF_UNION::ucbuf, sf_private_tag::wchunks, and sf_private_tag::write_header.
Referenced by alac_init(), and alac_reader_init().
alac_byterate()
static int alac_byterate (SF_PRIVATE * psf) static
References sf_private_tag::datalength, sf_private_tag::file, PSF_FILE::mode, and sf_private_tag::sf.
Referenced by alac_init().
alac_decode_block()
static int alac_decode_block (SF_PRIVATE * psf, ALAC_PRIVATE * plac) static
References alac_decode(), alac_reader_next_packet_size(), BitBufferInit(), ALAC_PRIVATE::buffer, ALAC_PRIVATE::byte_buffer, PAKT_INFO::count, PAKT_INFO::current, ALAC_PRIVATE::decoder, ALAC_PRIVATE::frames_per_block, ALAC_PRIVATE::frames_this_block, ALAC_PRIVATE::input_data_pos, ALAC_PRIVATE::pakt_info, ALAC_PRIVATE::partial_block_frames, psf_fread(), psf_fseek(), and psf_log_printf().
Referenced by alac_read_d(), alac_read_f(), alac_read_i(), alac_read_s(), alac_reader_calc_frames(), and alac_seek().
alac_encode_block()
static int alac_encode_block (ALAC_PRIVATE * plac) static
References alac_encode(), alac_pakt_append(), ALAC_PRIVATE::buffer, ALAC_PRIVATE::byte_buffer, ALAC_PRIVATE::encoder, ALAC_PRIVATE::enctmp, NULL, ALAC_PRIVATE::pakt_info, and ALAC_PRIVATE::partial_block_frames.
Referenced by alac_close(), alac_write_d(), alac_write_f(), alac_write_i(), and alac_write_s().
alac_kuki_read()
static uint32_t alac_kuki_read (SF_PRIVATE * psf, uint32_t kuki_offset, uint8_t * kuki, size_t kuki_maxlen) static
References psf_fread(), psf_fseek(), and psf_log_printf().
Referenced by alac_reader_init().
alac_pakt_alloc()
static PAKT_INFO * alac_pakt_alloc (uint32_t initial_count) static
References PAKT_INFO::allocated, PAKT_INFO::count, PAKT_INFO::current, NULL, and PAKT_INFO::packet_size.
Referenced by alac_pakt_read_decode(), and alac_writer_init().
alac_pakt_read_decode() [1/2]
static PAKT_INFO* alac_pakt_read_decode (SF_PRIVATE * psf, uint32_t pakt_offset) static
Referenced by alac_reader_init().
alac_pakt_append()
static PAKT_INFO * alac_pakt_append (PAKT_INFO * info, uint32_t value) static
References PAKT_INFO::allocated, PAKT_INFO::count, NULL, PAKT_INFO::packet_size, and value.
Referenced by alac_encode_block(), and alac_pakt_read_decode().
alac_pakt_encode()
static uint8_t * alac_pakt_encode (const SF_PRIVATE * psf, uint32_t * pakt_size) static
References sf_private_tag::codec_data, PAKT_INFO::count, kALACDefaultFramesPerPacket, NULL, PAKT_INFO::packet_size, ALAC_PRIVATE::pakt_info, ALAC_PRIVATE::partial_block_frames, psf_put_be32(), psf_put_be64(), sf_private_tag::sf, and value.
Referenced by alac_close().
alac_pakt_block_offset()
static sf_count_t alac_pakt_block_offset (const PAKT_INFO * info, uint32_t block) static
References PAKT_INFO::packet_size.
Referenced by alac_seek().
alac_error_string()
static const char * alac_error_string (int error) static
References CASE_NAME, fALAC_FrameLengthError, kALAC_BadBitWidth, kALAC_BadSpecificConfigSize, kALAC_FileNotFoundError, kALAC_IncompatibleVersion, kALAC_MemFullError, kALAC_NumSamplesTooBig, kALAC_ParamError, kALAC_UnimplementedError, kALAC_UnsupportedElement, and kALAC_ZeroChannelCount.
Referenced by alac_reader_init().
alac_init()
int alac_init (SF_PRIVATE * psf, const ALAC_DECODER_INFO * info)
References alac_byterate(), alac_close(), ALAC_MAX_FRAME_SIZE, alac_reader_init(), alac_writer_init(), sf_private_tag::byterate, sf_private_tag::codec_close, sf_private_tag::codec_data, sf_private_tag::file, PSF_FILE::mode, NULL, psf_log_printf(), sf_private_tag::sf, SFE_BAD_MODE_RW, SFE_INTERNAL, and SFE_MALLOC_FAILED.
alac_get_desc_chunk_items()
void alac_get_desc_chunk_items (int subformat, uint32_t * fmt_flags, uint32_t * frames_per_packet)
References ALAC_FRAME_LENGTH.
Referenced by caf_write_header().
alac_reader_next_packet_size()
static uint32_t alac_reader_next_packet_size (PAKT_INFO * info) inline static
References PAKT_INFO::count, PAKT_INFO::current, and PAKT_INFO::packet_size.
Referenced by alac_decode_block(), and alac_reader_calc_frames().
alac_pakt_read_decode() [2/2]
static PAKT_INFO* alac_pakt_read_decode (SF_PRIVATE * psf, uint32_t UNUSEDpakt_offset) static
References alac_pakt_alloc(), alac_pakt_append(), sf_private_tag::get_chunk_data, sf_private_tag::get_chunk_size, memset(), sf_private_tag::next_chunk_iterator, NULL, psf_get_chunk_iterator(), psf_log_printf(), and value.