Aurora Framework: Monitor.m File Reference
Monitor.m File Reference
Functions
void _glfwPlatformFreeMonitor (_GLFWmonitor *monitor)
void _glfwPlatformGetGammaRamp (_GLFWmonitor *monitor, GLFWgammaramp *ramp)
void _glfwPlatformGetMonitorContentScale (_GLFWmonitor *monitor, float *xscale, float *yscale)
void _glfwPlatformGetMonitorPos (_GLFWmonitor *monitor, int *xpos, int *ypos)
void _glfwPlatformGetVideoMode (_GLFWmonitor *monitor, GLFWvidmode *mode)
GLFWvidmode * _glfwPlatformGetVideoModes (_GLFWmonitor *monitor, int *count)
void _glfwPlatformSetGammaRamp (_GLFWmonitor *monitor, const GLFWgammaramp *ramp)
void _glfwPollMonitorsNS (void)
void _glfwRestoreVideoModeNS (_GLFWmonitor *monitor)
void _glfwSetVideoModeNS (_GLFWmonitor *monitor, const GLFWvidmode *desired)
static CGDisplayFadeReservationToken beginFadeReservation (void)
static void endFadeReservation (CGDisplayFadeReservationToken token)
static char * getDisplayName (CGDirectDisplayID displayID)
GLFWAPI CGDirectDisplayID glfwGetCocoaMonitor (GLFWmonitor *handle)
static GLFWbool modeIsGood (CGDisplayModeRef mode)
static GLFWvidmode vidmodeFromCGDisplayMode (CGDisplayModeRef mode, CVDisplayLinkRef link)
Function Documentation
getDisplayName()
static char* getDisplayName (CGDirectDisplayID displayID) static
References _glfwInputError(), GLFW_PLATFORM_ERROR, setup::name, and NULL.
Referenced by _glfwPollMonitorsNS().
modeIsGood()
static GLFWbool modeIsGood (CGDisplayModeRef mode) static
References GLFW_FALSE, GLFW_TRUE, and mode().
Referenced by _glfwPlatformGetVideoModes(), and _glfwSetVideoModeNS().
vidmodeFromCGDisplayMode()
static GLFWvidmode vidmodeFromCGDisplayMode (CGDisplayModeRef mode, CVDisplayLinkRef link) static
References GLFWvidmode::blueBits, GLFWvidmode::greenBits, GLFWvidmode::height, mode(), GLFWvidmode::redBits, GLFWvidmode::refreshRate, and GLFWvidmode::width.
Referenced by _glfwPlatformGetVideoMode(), _glfwPlatformGetVideoModes(), and _glfwSetVideoModeNS().
beginFadeReservation()
static CGDisplayFadeReservationToken beginFadeReservation (void) static
Referenced by _glfwRestoreVideoModeNS(), and _glfwSetVideoModeNS().
endFadeReservation()
static void endFadeReservation (CGDisplayFadeReservationToken token) static
Referenced by _glfwRestoreVideoModeNS(), and _glfwSetVideoModeNS().
_glfwPollMonitorsNS()
void _glfwPollMonitorsNS (void)
References _glfw, _GLFW_INSERT_LAST, _glfw_strdup(), _glfwAllocMonitor(), _glfwInputMonitor(), getDisplayName(), GLFW_CONNECTED, GLFW_DISCONNECTED, memcpy(), _GLFWlibrary::monitorCount, _GLFWlibrary::monitors, setup::name, and NULL.
Referenced by _glfwPlatformInit().
_glfwSetVideoModeNS()
void _glfwSetVideoModeNS (_GLFWmonitor * monitor, const GLFWvidmode * desired)
References _glfwChooseVideoMode(), _glfwCompareVideoModes(), _glfwPlatformGetVideoMode(), beginFadeReservation(), endFadeReservation(), mode(), modeIsGood(), NULL, and vidmodeFromCGDisplayMode().
Referenced by acquireMonitor().
_glfwRestoreVideoModeNS()
void _glfwRestoreVideoModeNS (_GLFWmonitor * monitor)
References beginFadeReservation(), endFadeReservation(), and NULL.
Referenced by releaseMonitor().
_glfwPlatformFreeMonitor()
void _glfwPlatformFreeMonitor (_GLFWmonitor * monitor)
Referenced by _glfwFreeMonitor().
_glfwPlatformGetMonitorPos()
void _glfwPlatformGetMonitorPos (_GLFWmonitor * monitor, int * xpos, int * ypos)
Referenced by acquireMonitor(), createNativeWindow(), and glfwGetMonitorPos().
_glfwPlatformGetMonitorContentScale()
void _glfwPlatformGetMonitorContentScale (_GLFWmonitor * monitor, float * xscale, float * yscale)
Referenced by glfwGetMonitorContentScale().
_glfwPlatformGetVideoModes()
GLFWvidmode* _glfwPlatformGetVideoModes (_GLFWmonitor * monitor, int * count)
Referenced by refreshVideoModes().
_glfwPlatformGetVideoMode()
void _glfwPlatformGetVideoMode (_GLFWmonitor * monitor, GLFWvidmode * mode)
Referenced by _glfwPlatformCreateWindow(), _glfwSetVideoModeNS(), acquireMonitor(), createNativeWindow(), and glfwGetVideoMode().
_glfwPlatformGetGammaRamp()
void _glfwPlatformGetGammaRamp (_GLFWmonitor * monitor, GLFWgammaramp * ramp)
Referenced by glfwGetGammaRamp(), and glfwSetGammaRamp().
_glfwPlatformSetGammaRamp()
void _glfwPlatformSetGammaRamp (_GLFWmonitor * monitor, const GLFWgammaramp * ramp)
Referenced by glfwSetGammaRamp(), and terminate().
glfwGetCocoaMonitor()
GLFWAPI CGDirectDisplayID glfwGetCocoaMonitor (GLFWmonitor * handle)
References _GLFW_REQUIRE_INIT_OR_RETURN.