Aurora Framework: Window.c File Reference
Wayland/Window.c File Reference
Macros
#define _GNU_SOURCE
Functions
int _glfwPlatformCreateCursor (_GLFWcursor *cursor, const GLFWimage *image, int xhot, int yhot)
int _glfwPlatformCreateStandardCursor (_GLFWcursor *cursor, int shape)
int _glfwPlatformCreateWindow (_GLFWwindow *window, const _GLFWwndconfig *wndconfig, const _GLFWctxconfig *ctxconfig, const _GLFWfbconfig *fbconfig)
VkResult _glfwPlatformCreateWindowSurface (VkInstance instance, _GLFWwindow *window, const VkAllocationCallbacks *allocator, VkSurfaceKHR *surface)
void _glfwPlatformDestroyCursor (_GLFWcursor *cursor)
void _glfwPlatformDestroyWindow (_GLFWwindow *window)
void _glfwPlatformFocusWindow (_GLFWwindow *window)
int _glfwPlatformFramebufferTransparent (_GLFWwindow *window)
const char * _glfwPlatformGetClipboardString (void)
void _glfwPlatformGetCursorPos (_GLFWwindow *window, double *xpos, double *ypos)
void _glfwPlatformGetFramebufferSize (_GLFWwindow *window, int *width, int *height)
int _glfwPlatformGetKeyScancode (int key)
int _glfwPlatformGetPhysicalDevicePresentationSupport (VkInstance instance, VkPhysicalDevice device, uint32_t queuefamily)
void _glfwPlatformGetRequiredInstanceExtensions (char **extensions)
const char * _glfwPlatformGetScancodeName (int scancode)
void _glfwPlatformGetWindowContentScale (_GLFWwindow *window, float *xscale, float *yscale)
void _glfwPlatformGetWindowFrameSize (_GLFWwindow *window, int *left, int *top, int *right, int *bottom)
float _glfwPlatformGetWindowOpacity (_GLFWwindow *window)
void _glfwPlatformGetWindowPos (_GLFWwindow *window, int *xpos, int *ypos)
void _glfwPlatformGetWindowSize (_GLFWwindow *window, int *width, int *height)
void _glfwPlatformHideWindow (_GLFWwindow *window)
void _glfwPlatformIconifyWindow (_GLFWwindow *window)
void _glfwPlatformMaximizeWindow (_GLFWwindow *window)
void _glfwPlatformPollEvents (void)
void _glfwPlatformPostEmptyEvent (void)
void _glfwPlatformRequestWindowAttention (_GLFWwindow *window)
void _glfwPlatformRestoreWindow (_GLFWwindow *window)
void _glfwPlatformSetClipboardString (const char *string)
void _glfwPlatformSetCursor (_GLFWwindow *window, _GLFWcursor *cursor)
void _glfwPlatformSetCursorMode (_GLFWwindow *window, int mode)
void _glfwPlatformSetCursorPos (_GLFWwindow *window, double x, double y)
void _glfwPlatformSetWindowAspectRatio (_GLFWwindow *window, int numer, int denom)
void _glfwPlatformSetWindowDecorated (_GLFWwindow *window, GLFWbool enabled)
void _glfwPlatformSetWindowFloating (_GLFWwindow *window, GLFWbool enabled)
void _glfwPlatformSetWindowIcon (_GLFWwindow *window, int count, const GLFWimage *images)
void _glfwPlatformSetWindowMonitor (_GLFWwindow *window, _GLFWmonitor *monitor, int xpos, int ypos, int width, int height, int refreshRate)
void _glfwPlatformSetWindowOpacity (_GLFWwindow *window, float opacity)
void _glfwPlatformSetWindowPos (_GLFWwindow *window, int xpos, int ypos)
void _glfwPlatformSetWindowResizable (_GLFWwindow *window, GLFWbool enabled)
void _glfwPlatformSetWindowSize (_GLFWwindow *window, int width, int height)
void _glfwPlatformSetWindowSizeLimits (_GLFWwindow *window, int minwidth, int minheight, int maxwidth, int maxheight)
void _glfwPlatformSetWindowTitle (_GLFWwindow *window, const char *title)
void _glfwPlatformShowWindow (_GLFWwindow *window)
void _glfwPlatformWaitEvents (void)
void _glfwPlatformWaitEventsTimeout (double timeout)
int _glfwPlatformWindowFocused (_GLFWwindow *window)
int _glfwPlatformWindowHovered (_GLFWwindow *window)
int _glfwPlatformWindowIconified (_GLFWwindow *window)
int _glfwPlatformWindowMaximized (_GLFWwindow *window)
int _glfwPlatformWindowVisible (_GLFWwindow *window)
static void checkScaleChange (_GLFWwindow *window)
static int createAnonymousFile (off_t size)
static void createDecoration (_GLFWdecorationWayland *decoration, struct wl_surface *parent, struct wl_buffer *buffer, GLFWbool opaque, int x, int y, int width, int height)
static void createDecorations (_GLFWwindow *window)
static GLFWbool createShellSurface (_GLFWwindow *window)
static struct wl_buffer * createShmBuffer (const GLFWimage *image)
static GLFWbool createSurface (_GLFWwindow *window, const _GLFWwndconfig *wndconfig)
static int createTmpfileCloexec (char *tmpname)
static GLFWbool createXdgSurface (_GLFWwindow *window)
static void destroyDecoration (_GLFWdecorationWayland *decoration)
static void destroyDecorations (_GLFWwindow *window)
GLFWAPI struct wl_display * glfwGetWaylandDisplay (void)
GLFWAPI struct wl_surface * glfwGetWaylandWindow (GLFWwindow *handle)
static void handleConfigure (void *data, struct wl_shell_surface *shellSurface, uint32_t edges, int32_t width, int32_t height)
static void handleEnter (void *data, struct wl_surface *surface, struct wl_output *output)
static void handleEvents (int timeout)
static void handleLeave (void *data, struct wl_surface *surface, struct wl_output *output)
static void handleLocked (void *data, struct zwp_locked_pointer_v1 *lockedPointer)
static void handlePing (void *data, struct wl_shell_surface *shellSurface, uint32_t serial)
static void handlePopupDone (void *data, struct wl_shell_surface *shellSurface)
static void handleRelativeMotion (void *data, struct zwp_relative_pointer_v1 *pointer, uint32_t timeHi, uint32_t timeLo, wl_fixed_t dx, wl_fixed_t dy, wl_fixed_t dxUnaccel, wl_fixed_t dyUnaccel)
static void handleUnlocked (void *data, struct zwp_locked_pointer_v1 *lockedPointer)
static GLFWbool isPointerLocked (_GLFWwindow *window)
static void lockPointer (_GLFWwindow *window)
static void resizeWindow (_GLFWwindow *window)
static void setFullscreen (_GLFWwindow *window, _GLFWmonitor *monitor, int refreshRate)
static void setIdleInhibitor (_GLFWwindow *window, GLFWbool enable)
static void setOpaqueRegion (_GLFWwindow *window)
static char * translateCursorShape (int shape)
static void unlockPointer (_GLFWwindow *window)
static void xdgSurfaceHandleConfigure (void *data, struct xdg_surface *surface, uint32_t serial)
static void xdgToplevelHandleClose (void *data, struct xdg_toplevel *toplevel)
static void xdgToplevelHandleConfigure (void *data, struct xdg_toplevel *toplevel, int32_t width, int32_t height, struct wl_array *states)
Variables
static const struct zwp_locked_pointer_v1_listener lockedPointerListener
static const struct zwp_relative_pointer_v1_listener relativePointerListener
static const struct wl_shell_surface_listener shellSurfaceListener
static const struct wl_surface_listener surfaceListener
static const struct xdg_surface_listener xdgSurfaceListener
static const struct xdg_toplevel_listener xdgToplevelListener
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Function Documentation
handlePing()
static void handlePing (void * data, struct wl_shell_surface * shellSurface, uint32_t serial) static
handleConfigure()
static void handleConfigure (void * data, struct wl_shell_surface * shellSurface, uint32_t edges, int32_t width, int32_t height) static
References _glfw, _GLFW_DECORATION_HORIZONTAL, _GLFW_DECORATION_VERTICAL, _glfwInputWindowDamage(), _glfwInputWindowSize(), _glfwPlatformSetWindowSize(), _GLFWwindow::decorated, _GLFWwindow::denom, GLFW_DONT_CARE, height, _GLFWwindow::maxheight, _GLFWwindow::maxwidth, _GLFWwindow::minheight, _GLFWwindow::minwidth, _GLFWwindow::monitor, _GLFWwindow::numer, and width.
handlePopupDone()
static void handlePopupDone (void * data, struct wl_shell_surface * shellSurface) static
createTmpfileCloexec()
static int createTmpfileCloexec (char * tmpname) static
Referenced by createAnonymousFile().
createAnonymousFile()
static int createAnonymousFile (off_t size) static
References createTmpfileCloexec(), and setup::name.
Referenced by createShmBuffer().
createShmBuffer()
static struct wl_buffer* createShmBuffer (const GLFWimage * image) static
References _glfw, _glfwInputError(), createAnonymousFile(), GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFWimage::height, NULL, GLFWimage::pixels, source, and GLFWimage::width.
Referenced by _glfwPlatformCreateCursor(), and createDecorations().
createDecoration()
static void createDecoration (_GLFWdecorationWayland * decoration, struct wl_surface * parent, struct wl_buffer * buffer, GLFWbool opaque, int x, int y, int width, int height) static
References _glfw, height, _GLFWdecorationWayland::subsurface, _GLFWdecorationWayland::surface, _GLFWdecorationWayland::viewport, and width.
Referenced by createDecorations().
createDecorations()
static void createDecorations (_GLFWwindow * window) static
References _glfw, _GLFW_DECORATION_HORIZONTAL, _GLFW_DECORATION_TOP, _GLFW_DECORATION_WIDTH, createDecoration(), and createShmBuffer().
Referenced by _glfwPlatformSetWindowDecorated(), _glfwPlatformSetWindowMonitor(), and createSurface().
destroyDecoration()
static void destroyDecoration (_GLFWdecorationWayland * decoration) static
References NULL, _GLFWdecorationWayland::subsurface, _GLFWdecorationWayland::surface, and _GLFWdecorationWayland::viewport.
Referenced by destroyDecorations().
destroyDecorations()
static void destroyDecorations (_GLFWwindow * window) static
References destroyDecoration().
Referenced by _glfwPlatformDestroyWindow(), _glfwPlatformSetWindowDecorated(), and setFullscreen().
setOpaqueRegion()
static void setOpaqueRegion (_GLFWwindow * window) static
References _glfw.
Referenced by createSurface(), and resizeWindow().
resizeWindow()
static void resizeWindow (_GLFWwindow * window) static
References _GLFW_DECORATION_HORIZONTAL, _GLFW_DECORATION_TOP, _GLFW_DECORATION_WIDTH, _glfwInputFramebufferSize(), _glfwInputWindowContentScale(), scale(), _GLFWwindow::scale, setOpaqueRegion(), and wl_egl_window_resize.
Referenced by _glfwPlatformSetWindowSize(), and checkScaleChange().
checkScaleChange()
static void checkScaleChange (_GLFWwindow * window) static
References _glfw, resizeWindow(), scale(), and _GLFWwindow::scale.
Referenced by handleEnter(), and handleLeave().
handleEnter()
static void handleEnter (void * data, struct wl_surface * surface, struct wl_output * output) static
References checkScaleChange().
handleLeave()
static void handleLeave (void * data, struct wl_surface * surface, struct wl_output * output) static
References checkScaleChange(), GLFW_FALSE, GLFW_TRUE, and NULL.
setIdleInhibitor()
static void setIdleInhibitor (_GLFWwindow * window, GLFWbool enable) static
References _glfw, _glfwInputError(), GLFW_PLATFORM_ERROR, and NULL.
Referenced by _glfwPlatformSetWindowMonitor(), createShellSurface(), createXdgSurface(), and setFullscreen().
createSurface()
static GLFWbool createSurface (_GLFWwindow * window, const _GLFWwndconfig * wndconfig) static
References _glfw, createDecorations(), _GLFWwindow::decorated, GLFW_FALSE, GLFW_TRUE, _GLFWwndconfig::height, _GLFWwindow::monitor, _GLFWwindow::scale, setOpaqueRegion(), surfaceListener, _GLFWwndconfig::width, and wl_egl_window_create.
Referenced by _glfwPlatformCreateWindow().
setFullscreen()
static void setFullscreen (_GLFWwindow * window, _GLFWmonitor * monitor, int refreshRate) static
References destroyDecorations(), GLFW_TRUE, and setIdleInhibitor().
Referenced by _glfwPlatformSetWindowMonitor(), and createShellSurface().
createShellSurface()
static GLFWbool createShellSurface (_GLFWwindow * window) static
References _glfw, _glfwInputError(), GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, _GLFWwindow::monitor, NULL, setFullscreen(), setIdleInhibitor(), and shellSurfaceListener.
Referenced by _glfwPlatformCreateWindow(), and _glfwPlatformShowWindow().
xdgToplevelHandleConfigure()
static void xdgToplevelHandleConfigure (void * data, struct xdg_toplevel * toplevel, int32_t width, int32_t height, struct wl_array * states) static
References _glfwInputWindowDamage(), _glfwInputWindowFocus(), _glfwInputWindowSize(), _glfwPlatformIconifyWindow(), _glfwPlatformSetWindowSize(), _GLFWwindow::autoIconify, _GLFWwindow::denom, GLFW_DONT_CARE, GLFW_FALSE, GLFW_TRUE, height, _GLFWwindow::numer, and width.
xdgToplevelHandleClose()
static void xdgToplevelHandleClose (void * data, struct xdg_toplevel * toplevel) static
References _glfwInputWindowCloseRequest().
xdgSurfaceHandleConfigure()
static void xdgSurfaceHandleConfigure (void * data, struct xdg_surface * surface, uint32_t serial) static
createXdgSurface()
static GLFWbool createXdgSurface (_GLFWwindow * window) static
References _glfw, _glfwInputError(), GLFW_DONT_CARE, GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, _GLFWwindow::maxheight, _GLFWwindow::maxwidth, _GLFWwindow::minheight, _GLFWwindow::minwidth, _GLFWwindow::monitor, setIdleInhibitor(), xdgSurfaceListener, and xdgToplevelListener.
Referenced by _glfwPlatformCreateWindow(), and _glfwPlatformShowWindow().
handleEvents()
static void handleEvents (int timeout) static
References _glfw, _glfwInputKey(), _glfwInputWindowCloseRequest(), display(), GLFW_REPEAT, _GLFWwindow::next, ssize_t, and _GLFWlibrary::windowListHead.
Referenced by _glfwPlatformPollEvents(), _glfwPlatformWaitEvents(), and _glfwPlatformWaitEventsTimeout().
translateCursorShape()
static char* translateCursorShape (int shape) static
References GLFW_ARROW_CURSOR, GLFW_CROSSHAIR_CURSOR, GLFW_HAND_CURSOR, GLFW_HRESIZE_CURSOR, GLFW_IBEAM_CURSOR, GLFW_VRESIZE_CURSOR, and NULL.
Referenced by _glfwPlatformCreateStandardCursor().
_glfwPlatformCreateWindow()
int _glfwPlatformCreateWindow (_GLFWwindow * window, const _GLFWwndconfig * wndconfig, const _GLFWctxconfig * ctxconfig, const _GLFWfbconfig * fbconfig)
References _glfw, _glfw_strdup(), _glfwCreateContextEGL(), _glfwCreateContextOSMesa(), _glfwInitEGL(), _glfwInitOSMesa(), _GLFWctxconfig::client, createShellSurface(), createSurface(), createXdgSurface(), GLFW_EGL_CONTEXT_API, GLFW_FALSE, GLFW_NATIVE_CONTEXT_API, GLFW_NO_API, GLFW_OSMESA_CONTEXT_API, GLFW_TRUE, NULL, _GLFWctxconfig::source, _GLFWwndconfig::title, _GLFWfbconfig::transparent, and _GLFWwndconfig::visible.
_glfwPlatformDestroyWindow()
void _glfwPlatformDestroyWindow (_GLFWwindow * window)
References _glfw, _glfwInputCursorEnter(), _glfwInputWindowFocus(), _GLFWwindow::context, _GLFWcontext::destroy, destroyDecorations(), GLFW_FALSE, NULL, and wl_egl_window_destroy.
_glfwPlatformSetWindowTitle()
void _glfwPlatformSetWindowTitle (_GLFWwindow * window, const char * title)
References _glfw_strdup().
_glfwPlatformSetWindowIcon()
void _glfwPlatformSetWindowIcon (_GLFWwindow * window, int count, const GLFWimage * images)
References _glfwInputError(), and GLFW_PLATFORM_ERROR.
_glfwPlatformGetWindowPos()
void _glfwPlatformGetWindowPos (_GLFWwindow * window, int * xpos, int * ypos)
References _glfwInputError(), and GLFW_PLATFORM_ERROR.
_glfwPlatformSetWindowPos()
void _glfwPlatformSetWindowPos (_GLFWwindow * window, int xpos, int ypos)
References _glfwInputError(), and GLFW_PLATFORM_ERROR.
_glfwPlatformGetWindowSize()
void _glfwPlatformGetWindowSize (_GLFWwindow * window, int * width, int * height)
References height, and width.
Referenced by _glfwPlatformGetFramebufferSize().
_glfwPlatformSetWindowSize()
void _glfwPlatformSetWindowSize (_GLFWwindow * window, int width, int height)
References height, resizeWindow(), and width.
Referenced by handleConfigure(), and xdgToplevelHandleConfigure().
_glfwPlatformSetWindowSizeLimits()
void _glfwPlatformSetWindowSizeLimits (_GLFWwindow * window, int minwidth, int minheight, int maxwidth, int maxheight)
References _glfw, and GLFW_DONT_CARE.
_glfwPlatformSetWindowAspectRatio()
void _glfwPlatformSetWindowAspectRatio (_GLFWwindow * window, int numer, int denom)
_glfwPlatformGetFramebufferSize()
void _glfwPlatformGetFramebufferSize (_GLFWwindow * window, int * width, int * height)
References _glfwPlatformGetWindowSize(), height, _GLFWwindow::scale, and width.
_glfwPlatformGetWindowFrameSize()
void _glfwPlatformGetWindowFrameSize (_GLFWwindow * window, int * left, int * top, int * right, int * bottom)
References _GLFW_DECORATION_TOP, _GLFW_DECORATION_WIDTH, _GLFWwindow::decorated, and _GLFWwindow::monitor.
_glfwPlatformGetWindowContentScale()
void _glfwPlatformGetWindowContentScale (_GLFWwindow * window, float * xscale, float * yscale)
References _GLFWwindow::scale.
_glfwPlatformIconifyWindow()
void _glfwPlatformIconifyWindow (_GLFWwindow * window)
References _glfw, _glfwInputError(), and GLFW_PLATFORM_ERROR.
Referenced by xdgToplevelHandleConfigure().
_glfwPlatformRestoreWindow()
void _glfwPlatformRestoreWindow (_GLFWwindow * window)
References _glfwInputWindowMonitor(), GLFW_FALSE, _GLFWwindow::monitor, and NULL.
_glfwPlatformMaximizeWindow()
void _glfwPlatformMaximizeWindow (_GLFWwindow * window)
References GLFW_TRUE, and NULL.
_glfwPlatformShowWindow()
void _glfwPlatformShowWindow (_GLFWwindow * window)
References _glfw, createShellSurface(), createXdgSurface(), and GLFW_TRUE.
_glfwPlatformHideWindow()
void _glfwPlatformHideWindow (_GLFWwindow * window)
References GLFW_FALSE, and NULL.
_glfwPlatformRequestWindowAttention()
void _glfwPlatformRequestWindowAttention (_GLFWwindow * window)
References _glfwInputError(), and GLFW_PLATFORM_ERROR.
_glfwPlatformFocusWindow()
void _glfwPlatformFocusWindow (_GLFWwindow * window)
References _glfwInputError(), and GLFW_PLATFORM_ERROR.
_glfwPlatformSetWindowMonitor()
void _glfwPlatformSetWindowMonitor (_GLFWwindow * window, _GLFWmonitor * monitor, int xpos, int ypos, int width, int height, int refreshRate)
References _glfwInputWindowMonitor(), createDecorations(), _GLFWwindow::decorated, GLFW_FALSE, setFullscreen(), and setIdleInhibitor().
_glfwPlatformWindowFocused()
int _glfwPlatformWindowFocused (_GLFWwindow * window)
References _glfw.
_glfwPlatformWindowIconified()
int _glfwPlatformWindowIconified (_GLFWwindow * window)
References GLFW_FALSE.
_glfwPlatformWindowVisible()
int _glfwPlatformWindowVisible (_GLFWwindow * window)
_glfwPlatformWindowMaximized()
int _glfwPlatformWindowMaximized (_GLFWwindow * window)
_glfwPlatformWindowHovered()
int _glfwPlatformWindowHovered (_GLFWwindow * window)
_glfwPlatformFramebufferTransparent()
int _glfwPlatformFramebufferTransparent (_GLFWwindow * window)
_glfwPlatformSetWindowResizable()
void _glfwPlatformSetWindowResizable (_GLFWwindow * window, GLFWbool enabled)
References _glfwInputError(), and GLFW_PLATFORM_ERROR.
_glfwPlatformSetWindowDecorated()
void _glfwPlatformSetWindowDecorated (_GLFWwindow * window, GLFWbool enabled)
References createDecorations(), destroyDecorations(), and _GLFWwindow::monitor.
_glfwPlatformSetWindowFloating()
void _glfwPlatformSetWindowFloating (_GLFWwindow * window, GLFWbool enabled)
References _glfwInputError(), and GLFW_PLATFORM_ERROR.
_glfwPlatformGetWindowOpacity()
float _glfwPlatformGetWindowOpacity (_GLFWwindow * window)
_glfwPlatformSetWindowOpacity()
void _glfwPlatformSetWindowOpacity (_GLFWwindow * window, float opacity)
_glfwPlatformPollEvents()
void _glfwPlatformPollEvents (void)
References handleEvents().
_glfwPlatformWaitEvents()
void _glfwPlatformWaitEvents (void)
References handleEvents().
_glfwPlatformWaitEventsTimeout()
void _glfwPlatformWaitEventsTimeout (double timeout)
References handleEvents().
_glfwPlatformPostEmptyEvent()
void _glfwPlatformPostEmptyEvent (void)
References _glfw.
_glfwPlatformGetCursorPos()
void _glfwPlatformGetCursorPos (_GLFWwindow * window, double * xpos, double * ypos)
isPointerLocked()
static GLFWbool isPointerLocked (_GLFWwindow * window) static
References NULL.
Referenced by _glfwPlatformSetCursor(), and _glfwPlatformSetCursorPos().
_glfwPlatformSetCursorPos()
void _glfwPlatformSetCursorPos (_GLFWwindow * window, double x, double y)
References isPointerLocked().
_glfwPlatformSetCursorMode()
void _glfwPlatformSetCursorMode (_GLFWwindow * window, int mode)
References _glfwPlatformSetCursor().
_glfwPlatformGetScancodeName()
const char* _glfwPlatformGetScancodeName (int scancode)
References NULL.
_glfwPlatformGetKeyScancode()
int _glfwPlatformGetKeyScancode (int key)
References _glfw.
_glfwPlatformCreateCursor()
int _glfwPlatformCreateCursor (_GLFWcursor * cursor, const GLFWimage * image, int xhot, int yhot)
References createShmBuffer(), GLFW_TRUE, GLFWimage::height, and GLFWimage::width.
_glfwPlatformCreateStandardCursor()
int _glfwPlatformCreateStandardCursor (_GLFWcursor * cursor, int shape)
References _glfw, _glfwInputError(), GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, wl_cursor::images, translateCursorShape(), and wl_cursor_theme_get_cursor.
_glfwPlatformDestroyCursor()
void _glfwPlatformDestroyCursor (_GLFWcursor * cursor)
handleRelativeMotion()
static void handleRelativeMotion (void * data, struct zwp_relative_pointer_v1 * pointer, uint32_t timeHi, uint32_t timeLo, wl_fixed_t dx, wl_fixed_t dy, wl_fixed_t dxUnaccel, wl_fixed_t dyUnaccel) static
References _glfwInputCursorPos(), _GLFWwindow::cursorMode, GLFW_CURSOR_DISABLED, _GLFWwindow::virtualCursorPosX, and _GLFWwindow::virtualCursorPosY.
handleLocked()
static void handleLocked (void * data, struct zwp_locked_pointer_v1 * lockedPointer) static
unlockPointer()
static void unlockPointer (_GLFWwindow * window) static
References NULL.
Referenced by _glfwPlatformSetCursor().
lockPointer()
static void lockPointer (_GLFWwindow * window) static
References _glfw, _glfwInputError(), GLFW_PLATFORM_ERROR, lockedPointerListener, NULL, and relativePointerListener.
Referenced by _glfwPlatformSetCursor().
handleUnlocked()
static void handleUnlocked (void * data, struct zwp_locked_pointer_v1 * lockedPointer) static
_glfwPlatformSetCursor()
void _glfwPlatformSetCursor (_GLFWwindow * window, _GLFWcursor * cursor)
References _glfw, _glfwInputError(), _GLFWwindow::cursorMode, GLFW_CURSOR_DISABLED, GLFW_CURSOR_HIDDEN, GLFW_CURSOR_NORMAL, GLFW_PLATFORM_ERROR, wl_cursor_image::height, wl_cursor_image::hotspot_x, wl_cursor_image::hotspot_y, wl_cursor::images, isPointerLocked(), lockPointer(), NULL, unlockPointer(), wl_cursor_image::width, wl_cursor_image_get_buffer, and wl_cursor_theme_get_cursor.
Referenced by _glfwPlatformSetCursorMode().
_glfwPlatformSetClipboardString()
void _glfwPlatformSetClipboardString (const char * string)
References _glfwInputError(), and GLFW_PLATFORM_ERROR.
_glfwPlatformGetClipboardString()
const char* _glfwPlatformGetClipboardString (void)
References _glfwInputError(), GLFW_PLATFORM_ERROR, and NULL.
_glfwPlatformGetRequiredInstanceExtensions()
void _glfwPlatformGetRequiredInstanceExtensions (char ** extensions)
References _glfw, _GLFWlibrary::KHR_surface, and _GLFWlibrary::vk.
_glfwPlatformGetPhysicalDevicePresentationSupport()
int _glfwPlatformGetPhysicalDevicePresentationSupport (VkInstance instance, VkPhysicalDevice device, uint32_t queuefamily)
References _glfw, _glfwInputError(), GLFW_API_UNAVAILABLE, VK_NULL_HANDLE, and vkGetInstanceProcAddr().
_glfwPlatformCreateWindowSurface()
VkResult _glfwPlatformCreateWindowSurface (VkInstance instance, _GLFWwindow * window, const VkAllocationCallbacks * allocator, VkSurfaceKHR * surface)
References _glfw, _glfwGetVulkanResultString(), _glfwInputError(), VkWaylandSurfaceCreateInfoKHR::display, GLFW_API_UNAVAILABLE, GLFW_PLATFORM_ERROR, memset(), VkWaylandSurfaceCreateInfoKHR::sType, VkWaylandSurfaceCreateInfoKHR::surface, VK_ERROR_EXTENSION_NOT_PRESENT, VK_STRUCTURE_TYPE_WAYLAND_SURFACE_CREATE_INFO_KHR, and vkGetInstanceProcAddr().
glfwGetWaylandDisplay()
GLFWAPI struct wl_display* glfwGetWaylandDisplay (void)
References _glfw, _GLFW_REQUIRE_INIT_OR_RETURN, and NULL.
glfwGetWaylandWindow()
GLFWAPI struct wl_surface* glfwGetWaylandWindow (GLFWwindow * handle)
References _GLFW_REQUIRE_INIT_OR_RETURN, and NULL.
Variable Documentation
shellSurfaceListener
const struct wl_shell_surface_listener shellSurfaceListener static
Initial value:
= {
    handlePing,
    handleConfigure,
    handlePopupDone
}
Referenced by createShellSurface().
surfaceListener
const struct wl_surface_listener surfaceListener static
Initial value:
= {
    handleEnter,
    handleLeave
}
Referenced by createSurface().
xdgToplevelListener
const struct xdg_toplevel_listener xdgToplevelListener static
Initial value:
= {
    xdgToplevelHandleConfigure,
    xdgToplevelHandleClose
}
Referenced by createXdgSurface().
xdgSurfaceListener
const struct xdg_surface_listener xdgSurfaceListener static
Initial value:
= {
    xdgSurfaceHandleConfigure
}
Referenced by createXdgSurface().
relativePointerListener
const struct zwp_relative_pointer_v1_listener relativePointerListener static
Initial value:
= {
    handleRelativeMotion
}
Referenced by lockPointer().
lockedPointerListener
const struct zwp_locked_pointer_v1_listener lockedPointerListener static
Initial value:
= {
    handleLocked,
    handleUnlocked
}
Referenced by lockPointer().