Aurora Framework: ImGui.cpp File Reference
ImGui.cpp File Reference
Classes
struct ImGuiPlotArrayGetterData
struct ImGuiResizeGripDef
struct ImGuiStyleVarInfo
Namespaces
ImGui
ImGuiStb
Macros
#define IM_F32_TO_INT8_SAT(_VAL) ((int)(ImSaturate(_VAL) * 255.0f + 0.5f))
#define IM_F32_TO_INT8_UNBOUND(_VAL) ((int)((_VAL) * 255.0f + ((_VAL)>=0 ? 0.5f : -0.5f)))
#define IMGUI_CDECL
#define IMGUI_DEBUG_NAV_RECTS 0
#define IMGUI_DEBUG_NAV_SCORING 0
#define IMGUI_DEFINE_MATH_OPERATORS
#define NAV_MAP_KEY(_KEY, _NAV_INPUT) if (g.IO.KeyMap[_KEY] != -1 && IsKeyDown(g.IO.KeyMap[_KEY])) g.IO.NavInputs[_NAV_INPUT] = 1.0f;
#define STB_TEXTEDIT_IMPLEMENTATION
#define STB_TEXTEDIT_K_BACKSPACE 0x10009
#define STB_TEXTEDIT_K_DELETE 0x10008
#define STB_TEXTEDIT_K_DOWN 0x10003
#define STB_TEXTEDIT_K_LEFT 0x10000
#define STB_TEXTEDIT_K_LINEEND 0x10005
#define STB_TEXTEDIT_K_LINESTART 0x10004
#define STB_TEXTEDIT_K_REDO 0x1000B
#define STB_TEXTEDIT_K_RIGHT 0x10001
#define STB_TEXTEDIT_K_SHIFT 0x20000
#define STB_TEXTEDIT_K_TEXTEND 0x10007
#define STB_TEXTEDIT_K_TEXTSTART 0x10006
#define STB_TEXTEDIT_K_UNDO 0x1000A
#define STB_TEXTEDIT_K_UP 0x10002
#define STB_TEXTEDIT_K_WORDLEFT 0x1000C
#define STB_TEXTEDIT_K_WORDRIGHT 0x1000D
#define STB_TEXTEDIT_MOVEWORDLEFT STB_TEXTEDIT_MOVEWORDLEFT_IMPL
#define STB_TEXTEDIT_MOVEWORDRIGHT STB_TEXTEDIT_MOVEWORDRIGHT_IMPL
#define va_copy(dest, src) (dest = src)
Enumerations
enum ImGuiPopupPositionPolicy { ImGuiPopupPositionPolicy_Default, ImGuiPopupPositionPolicy_ComboBox }
Functions
static void AddDrawListToDrawData (ImVector< ImDrawList *> *out_list, ImDrawList *draw_list)
static ImGuiWindowSettings * AddWindowSettings (const char *name)
static void AddWindowToDrawData (ImVector< ImDrawList *> *out_list, ImGuiWindow *window)
static void AddWindowToDrawDataSelectLayer (ImGuiWindow *window)
static void AddWindowToSortedBuffer (ImVector< ImGuiWindow *> *out_sorted_windows, ImGuiWindow *window)
static bool BeginChildEx (const char *name, ImGuiID id, const ImVec2 &size_arg, bool border, ImGuiWindowFlags extra_flags)
static float CalcMaxPopupHeightFromItemCount (int items_count)
static ImVec2 CalcNextScrollFromScrollTargetAndClamp (ImGuiWindow *window)
static void CalcResizePosSizeFromAnyCorner (ImGuiWindow *window, const ImVec2 &corner_target, const ImVec2 &corner_norm, ImVec2 *out_pos, ImVec2 *out_size)
static ImVec2 CalcSizeAfterConstraint (ImGuiWindow *window, ImVec2 new_size)
static ImVec2 CalcSizeAutoFit (ImGuiWindow *window, const ImVec2 &size_contents)
static ImVec2 CalcSizeContents (ImGuiWindow *window)
static void CheckStacksSize (ImGuiWindow *window, bool write)
static int IMGUI_CDECL ChildWindowComparer (const void *lhs, const void *rhs)
static void ClosePopupToLevel (int remaining)
static void ColorPickerOptionsPopup (ImGuiColorEditFlags flags, const float *ref_col)
static ImGuiWindow * CreateNewWindow (const char *name, ImVec2 size, ImGuiWindowFlags flags)
static void DataTypeApplyOp (ImGuiDataType data_type, int op, void *value1, const void *value2)
static bool DataTypeApplyOpFromText (const char *buf, const char *initial_value_buf, ImGuiDataType data_type, void *data_ptr, const char *scalar_format)
static void DataTypeFormatString (ImGuiDataType data_type, void *data_ptr, const char *display_format, char *buf, int buf_size)
static void DataTypeFormatString (ImGuiDataType data_type, void *data_ptr, int decimal_precision, char *buf, int buf_size)
static ImVec2 FindBestWindowPosForPopup (const ImVec2 &ref_pos, const ImVec2 &size, ImGuiDir *last_dir, const ImRect &r_avoid, ImGuiPopupPositionPolicy policy=ImGuiPopupPositionPolicy_Default)
static ImGuiWindow * FindHoveredWindow ()
static ImGuiColumnsSet * FindOrAddColumnsSet (ImGuiWindow *window, ImGuiID id)
static int FindWindowIndex (ImGuiWindow *window)
static ImGuiWindow * FindWindowNavigable (int i_start, int i_stop, int dir)
static void ImGui::FocusFrontMostActiveWindow (ImGuiWindow *ignore_window)
static void FreeWrapper (void *ptr, void *user_data)
static ImRect GetBorderRect (ImGuiWindow *window, int border_n, float perp_padding, float thickness)
static const char * GetClipboardTextFn_DefaultImpl (void *user_data)
static float GetColumnsRectHalfWidth ()
static float GetColumnWidthEx (ImGuiColumnsSet *columns, int column_index, bool before_resize=false)
static ImFont * GetDefaultFont ()
static float GetDraggedColumnOffset (ImGuiColumnsSet *columns, int column_index)
static ImGuiWindow * GetFrontMostModalRootWindow ()
static float GetMinimumStepAtDecimalPrecision (int decimal_precision)
static float GetScrollMaxX (ImGuiWindow *window)
static float GetScrollMaxY (ImGuiWindow *window)
static const ImGuiStyleVarInfo * GetStyleVarInfo (ImGuiStyleVar idx)
static ImRect GetViewportRect ()
static ImGuiCol GetWindowBgColorIdxFromFlags (ImGuiWindowFlags flags)
static ImU32 ImAlphaBlendColor (ImU32 col_a, ImU32 col_b)
static const char * ImAtoi (const char *src, int *output)
static void ImeSetInputScreenPosFn_DefaultImpl (int x, int y)
void * ImFileLoadToMemory (const char *filename, const char *file_open_mode, int *out_file_size, int padding_bytes)
FILE * ImFileOpen (const char *filename, const char *mode)
int ImFormatString (char *buf, size_t buf_size, const char *fmt,...)
int ImFormatStringV (char *buf, size_t buf_size, const char *fmt, va_list args)
ImU32 ImHash (const void *data, int data_size, ImU32 seed)
ImVec2 ImLineClosestPoint (const ImVec2 &a, const ImVec2 &b, const ImVec2 &p)
const ImWchar * ImStrbolW (const ImWchar *buf_mid_line, const ImWchar *buf_begin)
char * ImStrchrRange (const char *str, const char *str_end, char c)
char * ImStrdup (const char *str)
int ImStricmp (const char *str1, const char *str2)
const char * ImStristr (const char *haystack, const char *haystack_end, const char *needle, const char *needle_end)
int ImStrlenW (const ImWchar *str)
void ImStrncpy (char *dst, const char *src, size_t count)
int ImStrnicmp (const char *str1, const char *str2, size_t count)
int ImTextCharFromUtf8 (unsigned int *out_char, const char *in_text, const char *in_text_end)
static int ImTextCharToUtf8 (char *buf, int buf_size, unsigned int c)
int ImTextCountCharsFromUtf8 (const char *in_text, const char *in_text_end)
static int ImTextCountUtf8BytesFromChar (unsigned int c)
int ImTextCountUtf8BytesFromStr (const ImWchar *in_text, const ImWchar *in_text_end)
int ImTextStrFromUtf8 (ImWchar *buf, int buf_size, const char *in_text, const char *in_text_end, const char **in_text_remaining)
int ImTextStrToUtf8 (char *buf, int buf_size, const ImWchar *in_text, const ImWchar *in_text_end)
void ImTriangleBarycentricCoords (const ImVec2 &a, const ImVec2 &b, const ImVec2 &c, const ImVec2 &p, float &out_u, float &out_v, float &out_w)
ImVec2 ImTriangleClosestPoint (const ImVec2 &a, const ImVec2 &b, const ImVec2 &c, const ImVec2 &p)
bool ImTriangleContainsPoint (const ImVec2 &a, const ImVec2 &b, const ImVec2 &c, const ImVec2 &p)
static int InputTextCalcTextLenAndLineCount (const char *text_begin, const char **out_text_end)
static ImVec2 InputTextCalcTextSizeW (const ImWchar *text_begin, const ImWchar *text_end, const ImWchar **remaining=NULL, ImVec2 *out_offset=NULL, bool stop_on_new_line=false)
static bool InputTextFilterCharacter (unsigned int *p_char, ImGuiInputTextFlags flags, ImGuiTextEditCallback callback, void *user_data)
static bool ImGuiStb::is_separator (unsigned int c)
static int ImGuiStb::is_word_boundary_from_right (STB_TEXTEDIT_STRING *obj, int idx)
static bool IsKeyPressedMap (ImGuiKey key, bool repeat=true)
static bool IsNavInputDown (ImGuiNavInput n)
static bool IsNavInputPressed (ImGuiNavInput n, ImGuiInputReadMode mode)
static bool IsNavInputPressedAnyOfTwo (ImGuiNavInput n1, ImGuiNavInput n2, ImGuiInputReadMode mode)
static bool IsWindowContentHoverable (ImGuiWindow *window, ImGuiHoveredFlags flags)
static bool Items_ArrayGetter (void *data, int idx, const char **out_text)
static bool Items_SingleStringGetter (void *data, int idx, const char **out_text)
static void LoadIniSettingsFromDisk (const char *ini_filename)
static void LoadIniSettingsFromMemory (const char *buf)
static void LogRenderedText (const ImVec2 *ref_pos, const char *text, const char *text_end=NULL)
static ImVector< ImGuiStorage::Pair >::iterator LowerBound (ImVector< ImGuiStorage::Pair > &data, ImGuiID key)
static void * MallocWrapper (size_t size, void *user_data)
static void MarkIniSettingsDirty (ImGuiWindow *window)
static ImVec2 NavCalcPreferredMousePos ()
static bool NavMoveRequestButNoResultYet ()
static void ImGui::NavProcessItem (ImGuiWindow *window, const ImRect &nav_bb, const ImGuiID id)
static void NavProcessMoveRequestWrapAround (ImGuiWindow *window)
static ImGuiWindow * NavRestoreLastChildNavWindow (ImGuiWindow *window)
static void NavRestoreLayer (int layer)
static void NavSaveLastChildNavWindow (ImGuiWindow *child_window)
static bool NavScoreItem (ImGuiNavMoveResult *result, ImRect cand)
static float NavScoreItemDistInterval (float a0, float a1, float b0, float b1)
static ImGuiDir NavScoreItemGetQuadrant (float dx, float dy)
static void NavScrollToBringItemIntoView (ImGuiWindow *window, ImRect &item_rect_rel)
static void ImGui::NavUpdate ()
static void NavUpdateAnyRequestFlag ()
static void ImGui::NavUpdateWindowing ()
static void NavUpdateWindowingHighlightWindow (int focus_change_dir)
static float OffsetNormToPixels (const ImGuiColumnsSet *columns, float offset_norm)
static float PixelsToOffsetNorm (const ImGuiColumnsSet *columns, float offset)
static float Plot_ArrayGetter (void *data, int idx)
static void RenderArrow (ImDrawList *draw_list, ImVec2 pos, ImVec2 half_sz, ImGuiDir direction, ImU32 col)
static void RenderArrowsForVerticalBar (ImDrawList *draw_list, ImVec2 pos, ImVec2 half_sz, float bar_w)
static void SaveIniSettingsToDisk (const char *ini_filename)
static void SaveIniSettingsToMemory (ImVector< char > &out_buf)
static void SetClipboardTextFn_DefaultImpl (void *user_data, const char *text)
static void SetCurrentWindow (ImGuiWindow *window)
static void SetCursorPosYAndSetupDummyPrevLine (float pos_y, float line_height)
static void SetNavID (ImGuiID id, int nav_layer)
static void SetNavIDAndMoveMouse (ImGuiID id, int nav_layer, const ImRect &rect_rel)
static void SettingsHandlerWindow_ReadLine (ImGuiContext *, ImGuiSettingsHandler *, void *entry, const char *line)
static void * SettingsHandlerWindow_ReadOpen (ImGuiContext *, ImGuiSettingsHandler *, const char *name)
static void SettingsHandlerWindow_WriteAll (ImGuiContext *imgui_ctx, ImGuiSettingsHandler *handler, ImGuiTextBuffer *buf)
static void SetupDrawData (ImVector< ImDrawList *> *draw_lists, ImDrawData *out_draw_data)
static void SetWindowCollapsed (ImGuiWindow *window, bool collapsed, ImGuiCond cond)
static void SetWindowConditionAllowFlags (ImGuiWindow *window, ImGuiCond flags, bool enabled)
static void SetWindowPos (ImGuiWindow *window, const ImVec2 &pos, ImGuiCond cond)
static void SetWindowScrollX (ImGuiWindow *window, float new_scroll_x)
static void SetWindowScrollY (ImGuiWindow *window, float new_scroll_y)
static void SetWindowSize (ImGuiWindow *window, const ImVec2 &size, ImGuiCond cond)
static float SliderBehaviorCalcRatioFromValue (float v, float v_min, float v_max, float power, float linear_zero_pos)
static void ImGuiStb::STB_TEXTEDIT_DELETECHARS (STB_TEXTEDIT_STRING *obj, int pos, int n)
static ImWchar ImGuiStb::STB_TEXTEDIT_GETCHAR (const STB_TEXTEDIT_STRING *obj, int idx)
static float ImGuiStb::STB_TEXTEDIT_GETWIDTH (STB_TEXTEDIT_STRING *obj, int line_start_idx, int char_idx)
static bool ImGuiStb::STB_TEXTEDIT_INSERTCHARS (STB_TEXTEDIT_STRING *obj, int pos, const ImWchar *new_text, int new_text_len)
static int ImGuiStb::STB_TEXTEDIT_KEYTOTEXT (int key)
static void ImGuiStb::STB_TEXTEDIT_LAYOUTROW (StbTexteditRow *r, STB_TEXTEDIT_STRING *obj, int line_start_idx)
static int ImGuiStb::STB_TEXTEDIT_MOVEWORDLEFT_IMPL (STB_TEXTEDIT_STRING *obj, int idx)
static int ImGuiStb::STB_TEXTEDIT_MOVEWORDRIGHT_IMPL (STB_TEXTEDIT_STRING *obj, int idx)
static int ImGuiStb::STB_TEXTEDIT_STRINGLEN (const STB_TEXTEDIT_STRING *obj)
static void ImGui::UpdateManualResize (ImGuiWindow *window, const ImVec2 &size_auto_fit, int *border_held, int resize_grip_count, ImU32 resize_grip_col[4])
static void ImGui::UpdateMovingWindow ()
Variables
static size_t GImAllocatorActiveAllocationsCount = 0
static void *(* GImAllocatorAllocFunc)(size_t size, void *user_data) = MallocWrapper
static void(* GImAllocatorFreeFunc)(void *ptr, void *user_data) = FreeWrapper
static void * GImAllocatorUserData = NULL
ImGuiContext * GImGui = NULL
static const ImGuiStyleVarInfo GStyleVarInfo []
const ImGuiResizeGripDef resize_grip_def [4]
static ImWchar ImGuiStb::STB_TEXTEDIT_NEWLINE = '\n'
Macro Definition Documentation
IMGUI_DEFINE_MATH_OPERATORS
#define IMGUI_DEFINE_MATH_OPERATORS
IMGUI_DEBUG_NAV_SCORING
#define IMGUI_DEBUG_NAV_SCORING 0
Referenced by ImGui::NavProcessItem(), and NavUpdateAnyRequestFlag().
IMGUI_DEBUG_NAV_RECTS
#define IMGUI_DEBUG_NAV_RECTS 0
IMGUI_CDECL
#define IMGUI_CDECL
Referenced by ImGuiStorage::BuildSortByKey().
IM_F32_TO_INT8_UNBOUND
#define IM_F32_TO_INT8_UNBOUND (_VAL) ((int)((_VAL) * 255.0f + ((_VAL)>=0 ? 0.5f : -0.5f)))
Referenced by ImGui::ColorEdit4().
IM_F32_TO_INT8_SAT
#define IM_F32_TO_INT8_SAT (_VAL) ((int)(ImSaturate(_VAL) * 255.0f + 0.5f))
Referenced by ImGui::Begin(), ImGui::ColorConvertFloat4ToU32(), ImGui::ColorEditOptionsPopup(), and ImGui::ColorTooltip().
va_copy
#define va_copy (dest, src) (dest = src)
Referenced by ImGuiTextBuffer::appendfv().
NAV_MAP_KEY
#define NAV_MAP_KEY (_KEY, _NAV_INPUT) if (g.IO.KeyMap[_KEY] != -1 && IsKeyDown(g.IO.KeyMap[_KEY])) g.IO.NavInputs[_NAV_INPUT] = 1.0f;
Referenced by ImGui::NavUpdate().
STB_TEXTEDIT_MOVEWORDLEFT
#define STB_TEXTEDIT_MOVEWORDLEFT STB_TEXTEDIT_MOVEWORDLEFT_IMPL
STB_TEXTEDIT_MOVEWORDRIGHT
#define STB_TEXTEDIT_MOVEWORDRIGHT STB_TEXTEDIT_MOVEWORDRIGHT_IMPL
STB_TEXTEDIT_K_LEFT
#define STB_TEXTEDIT_K_LEFT 0x10000
Referenced by ImGui::InputTextEx().
STB_TEXTEDIT_K_RIGHT
#define STB_TEXTEDIT_K_RIGHT 0x10001
Referenced by ImGui::InputTextEx().
STB_TEXTEDIT_K_UP
#define STB_TEXTEDIT_K_UP 0x10002
Referenced by ImGui::InputTextEx().
STB_TEXTEDIT_K_DOWN
#define STB_TEXTEDIT_K_DOWN 0x10003
Referenced by ImGui::InputTextEx().
STB_TEXTEDIT_K_LINESTART
#define STB_TEXTEDIT_K_LINESTART 0x10004
Referenced by ImGui::InputTextEx().
STB_TEXTEDIT_K_LINEEND
#define STB_TEXTEDIT_K_LINEEND 0x10005
Referenced by ImGui::InputTextEx().
STB_TEXTEDIT_K_TEXTSTART
#define STB_TEXTEDIT_K_TEXTSTART 0x10006
Referenced by ImGui::InputTextEx().
STB_TEXTEDIT_K_TEXTEND
#define STB_TEXTEDIT_K_TEXTEND 0x10007
Referenced by ImGui::InputTextEx().
STB_TEXTEDIT_K_DELETE
#define STB_TEXTEDIT_K_DELETE 0x10008
Referenced by ImGui::InputTextEx().
STB_TEXTEDIT_K_BACKSPACE
#define STB_TEXTEDIT_K_BACKSPACE 0x10009
Referenced by ImGui::InputTextEx().
STB_TEXTEDIT_K_UNDO
#define STB_TEXTEDIT_K_UNDO 0x1000A
Referenced by ImGui::InputTextEx().
STB_TEXTEDIT_K_REDO
#define STB_TEXTEDIT_K_REDO 0x1000B
Referenced by ImGui::InputTextEx().
STB_TEXTEDIT_K_WORDLEFT
#define STB_TEXTEDIT_K_WORDLEFT 0x1000C
Referenced by ImGui::InputTextEx().
STB_TEXTEDIT_K_WORDRIGHT
#define STB_TEXTEDIT_K_WORDRIGHT 0x1000D
Referenced by ImGui::InputTextEx().
STB_TEXTEDIT_K_SHIFT
#define STB_TEXTEDIT_K_SHIFT 0x20000
Referenced by ImGui::InputTextEx().
STB_TEXTEDIT_IMPLEMENTATION
#define STB_TEXTEDIT_IMPLEMENTATION
Enumeration Type Documentation
ImGuiPopupPositionPolicy
enum ImGuiPopupPositionPolicy
Enumerator
ImGuiPopupPositionPolicy_Default
ImGuiPopupPositionPolicy_ComboBox
Function Documentation
IsKeyPressedMap()
static bool IsKeyPressedMap (ImGuiKey key, bool repeat = true) static
References GImGui, ImGuiContext::IO, ImGui::IsKeyPressed(), and ImGuiIO::KeyMap.
Referenced by ImGui::FocusableItemRegister(), ImGui::InputTextEx(), NavScoreItem(), ImGui::NavUpdateWindowing(), and ImGui::NewFrame().
GetDefaultFont()
static ImFont * GetDefaultFont () static
References ImGuiIO::FontDefault, GImGui, and ImGuiContext::IO.
Referenced by ImGui::NewFrame(), ImGui::PopFont(), and ImGui::PushFont().
SetCurrentWindow()
static void SetCurrentWindow (ImGuiWindow * window) static
References ImGuiWindow::CalcFontSize(), ImGuiContext::CurrentWindow, and GImGui.
Referenced by ImGui::Begin(), and ImGui::End().
SetWindowScrollX()
static void SetWindowScrollX (ImGuiWindow * window, float new_scroll_x) static
References ImGuiDrawContext::CursorMaxPos, ImGuiWindow::DC, ImGuiWindow::Scroll, and ImVec2::x.
Referenced by ImGui::NavUpdate(), and ImGui::NewFrame().
SetWindowScrollY()
static void SetWindowScrollY (ImGuiWindow * window, float new_scroll_y) static
References ImGuiDrawContext::CursorMaxPos, ImGuiWindow::DC, ImGuiWindow::Scroll, and ImVec2::y.
Referenced by ImGui::InputTextEx(), ImGui::NavUpdate(), and ImGui::NewFrame().
SetWindowPos()
static void SetWindowPos (ImGuiWindow * window, const ImVec2 & pos, ImGuiCond cond) static
References ImGuiDrawContext::CursorMaxPos, ImGuiDrawContext::CursorPos, ImGuiWindow::DC, FLT_MAX, ImFloor(), ImGuiCond_Appearing, ImGuiCond_FirstUseEver, ImGuiCond_Once, ImGuiWindow::Pos, ImGuiWindow::PosFloat, ImGuiWindow::SetWindowPosAllowFlags, and ImGuiWindow::SetWindowPosVal.
Referenced by ImGui::Begin(), and ImGui::SetWindowPos().
SetWindowSize()
static void SetWindowSize (ImGuiWindow * window, const ImVec2 & size, ImGuiCond cond) static
References ImGuiWindow::AutoFitFramesX, ImGuiWindow::AutoFitFramesY, ImGuiWindow::AutoFitOnlyGrows, ImGuiCond_Appearing, ImGuiCond_FirstUseEver, ImGuiCond_Once, ImGuiWindow::SetWindowSizeAllowFlags, ImGuiWindow::SizeFull, ImVec2::x, and ImVec2::y.
Referenced by ImGui::Begin(), and ImGui::SetWindowSize().
SetWindowCollapsed()
static void SetWindowCollapsed (ImGuiWindow * window, bool collapsed, ImGuiCond cond) static
References ImGuiWindow::Collapsed, ImGuiCond_Appearing, ImGuiCond_FirstUseEver, ImGuiCond_Once, and ImGuiWindow::SetWindowCollapsedAllowFlags.
Referenced by ImGui::Begin(), and ImGui::SetWindowCollapsed().
FindHoveredWindow()
static ImGuiWindow * FindHoveredWindow () static
References ImGuiWindow::Active, ImRect::Contains(), ImGuiWindow::Flags, GImGui, ImGuiWindowFlags_NoInputs, ImRect::Max, ImRect::Min, NULL, and ImGuiWindow::WindowRectClipped.
Referenced by ImGui::NewFrame().
CreateNewWindow()
static ImGuiWindow * CreateNewWindow (const char * name, ImVec2 size, ImGuiWindowFlags flags) static
References ImGuiWindow::AutoFitFramesX, ImGuiWindow::AutoFitFramesY, ImGuiWindow::AutoFitOnlyGrows, ImGuiWindow::Collapsed, ImGui::FindWindowSettings(), ImGuiWindow::Flags, GImGui, ImGuiWindow::ID, IM_NEW, ImFloor(), ImGuiCond_FirstUseEver, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoBringToFrontOnFocus, ImGuiWindowFlags_NoSavedSettings, ImLengthSqr(), ImGuiWindow::Pos, ImGuiWindow::PosFloat, SetWindowConditionAllowFlags(), ImGuiWindow::Size, ImGuiWindow::SizeFull, ImGuiWindow::SizeFullAtLastBegin, ImVec2::x, and ImVec2::y.
Referenced by ImGui::Begin().
CheckStacksSize()
static void CheckStacksSize (ImGuiWindow * window, bool write) static
References ImGuiWindow::DC, GImGui, ImGuiDrawContext::GroupStack, ImGuiWindow::IDStack, IM_ARRAYSIZE, IM_ASSERT, ImVector< T >::Size, and ImGuiDrawContext::StackSizesBackup.
Referenced by ImGui::Begin(), and ImGui::End().
CalcNextScrollFromScrollTargetAndClamp()
static ImVec2 CalcNextScrollFromScrollTargetAndClamp (ImGuiWindow * window) static
References ImGuiWindow::Collapsed, FLT_MAX, GetScrollMaxX(), GetScrollMaxY(), ImMax(), ImMin(), ImGuiWindow::MenuBarHeight(), ImGuiWindow::Scroll, ImGuiWindow::ScrollbarSizes, ImGuiWindow::ScrollTarget, ImGuiWindow::ScrollTargetCenterRatio, ImGuiWindow::SizeFull, ImGuiWindow::SkipItems, ImGuiWindow::TitleBarHeight(), ImVec2::x, and ImVec2::y.
Referenced by ImGui::Begin(), and NavScrollToBringItemIntoView().
AddDrawListToDrawData()
static void AddDrawListToDrawData (ImVector< ImDrawList *> * out_list, ImDrawList * draw_list) static
References ImDrawList::_IdxWritePtr, ImDrawList::_VtxCurrentIdx, ImDrawList::_VtxWritePtr, ImVector< T >::back(), ImDrawList::CmdBuffer, ImVector< T >::Data, ImDrawCmd::ElemCount, ImVector< T >::empty(), ImDrawList::IdxBuffer, IM_ASSERT, NULL, ImVector< T >::pop_back(), ImVector< T >::push_back(), ImVector< T >::Size, ImDrawCmd::UserCallback, and ImDrawList::VtxBuffer.
Referenced by AddWindowToDrawData(), and ImGui::Render().
AddWindowToDrawData()
static void AddWindowToDrawData (ImVector< ImDrawList *> * out_list, ImGuiWindow * window) static
References ImGuiWindow::Active, AddDrawListToDrawData(), ImGuiDrawContext::ChildWindows, ImGuiWindow::DC, ImGuiWindow::DrawList, ImGuiWindow::HiddenFrames, and ImVector< T >::Size.
Referenced by AddWindowToDrawDataSelectLayer().
AddWindowToSortedBuffer()
static void AddWindowToSortedBuffer (ImVector< ImGuiWindow *> * out_sorted_windows, ImGuiWindow * window) static
References ImGuiWindow::Active, ImVector< T >::begin(), ChildWindowComparer(), ImGuiDrawContext::ChildWindows, ImGuiWindow::DC, ImVector< T >::push_back(), and ImVector< T >::Size.
Referenced by ImGui::EndFrame().
AddWindowSettings()
static ImGuiWindowSettings * AddWindowSettings (const char * name) static
References GImGui, ImGuiWindowSettings::Id, ImHash(), ImStrdup(), ImGuiWindowSettings::Name, ImVector< T >::push_back(), and ImGuiContext::SettingsWindows.
Referenced by SettingsHandlerWindow_ReadOpen(), and SettingsHandlerWindow_WriteAll().
LoadIniSettingsFromDisk()
static void LoadIniSettingsFromDisk (const char * ini_filename) static
References ImFileLoadToMemory(), LoadIniSettingsFromMemory(), ImGui::MemFree(), and NULL.
Referenced by ImGui::NewFrame().
LoadIniSettingsFromMemory()
static void LoadIniSettingsFromMemory (const char * buf) static
References ImGui::FindSettingsHandler(), GImGui, ImStrchrRange(), ImStrdup(), ImGui::MemFree(), NULL, ImGuiSettingsHandler::ReadLineFn, and ImGuiSettingsHandler::ReadOpenFn.
Referenced by LoadIniSettingsFromDisk().
SaveIniSettingsToDisk()
static void SaveIniSettingsToDisk (const char * ini_filename) static
References GImGui, ImFileOpen(), SaveIniSettingsToMemory(), and ImGuiContext::SettingsDirtyTimer.
Referenced by ImGui::NewFrame(), and ImGui::Shutdown().
SaveIniSettingsToMemory()
static void SaveIniSettingsToMemory (ImVector< char > & out_buf) static
References GImGui, ImGuiContext::SettingsDirtyTimer, ImVector< T >::swap(), and ImGuiSettingsHandler::WriteAllFn.
Referenced by SaveIniSettingsToDisk().
MarkIniSettingsDirty()
static void MarkIniSettingsDirty (ImGuiWindow * window) static
References ImGuiWindow::Flags, GImGui, ImGuiWindowFlags_NoSavedSettings, and ImGuiContext::SettingsDirtyTimer.
Referenced by ImGui::Begin(), ImGui::NavUpdateWindowing(), ImGui::UpdateManualResize(), and ImGui::UpdateMovingWindow().
GetViewportRect()
static ImRect GetViewportRect () static
References GImGui.
Referenced by ImGui::Begin(), FindBestWindowPosForPopup(), NavCalcPreferredMousePos(), and ImGui::NavUpdate().
ClosePopupToLevel()
static void ClosePopupToLevel (int remaining) static
References ImGuiWindow::DC, ImGui::FocusWindow(), GImGui, IM_ASSERT, ImGuiDrawContext::NavHideHighlightOneFrame, NavRestoreLastChildNavWindow(), and ImGuiWindow::ParentWindow.
Referenced by ImGui::BeginMenu(), ImGui::CloseCurrentPopup(), ImGui::ClosePopup(), ImGui::ClosePopupsOverWindow(), ImGui::EndMenu(), and ImGui::NavUpdate().
GetFrontMostModalRootWindow()
static ImGuiWindow * GetFrontMostModalRootWindow () static
References GImGui, ImGuiWindowFlags_Modal, and NULL.
Referenced by ImGui::Begin(), ImGui::EndFrame(), and ImGui::NewFrame().
InputTextFilterCharacter()
static bool InputTextFilterCharacter (unsigned int * p_char, ImGuiInputTextFlags flags, ImGuiTextEditCallback callback, void * user_data) static
References ImGuiTextEditCallbackData::EventChar, ImGuiTextEditCallbackData::EventFlag, ImGuiTextEditCallbackData::Flags, ImCharIsSpace(), ImGuiInputTextFlags_AllowTabInput, ImGuiInputTextFlags_CallbackCharFilter, ImGuiInputTextFlags_CharsDecimal, ImGuiInputTextFlags_CharsHexadecimal, ImGuiInputTextFlags_CharsNoBlank, ImGuiInputTextFlags_CharsUppercase, ImGuiInputTextFlags_Multiline, memset(), and ImGuiTextEditCallbackData::UserData.
Referenced by ImGui::InputTextEx().
InputTextCalcTextLenAndLineCount()
static int InputTextCalcTextLenAndLineCount (const char * text_begin, const char ** out_text_end) static
Referenced by ImGui::InputTextEx().
InputTextCalcTextSizeW()
static ImVec2 InputTextCalcTextSizeW (const ImWchar * text_begin, const ImWchar * text_end, const ImWchar ** remaining = NULL, ImVec2 * out_offset = NULL, bool stop_on_new_line = false) static
References ImGuiContext::Font, ImGuiContext::FontSize, ImFont::FontSize, ImFont::GetCharAdvance(), GImGui, ImMax(), ImVec2::x, and ImVec2::y.
Referenced by ImGui::InputTextEx(), and ImGuiStb::STB_TEXTEDIT_LAYOUTROW().
DataTypeFormatString() [1/2]
static void DataTypeFormatString (ImGuiDataType data_type, void * data_ptr, const char * display_format, char * buf, int buf_size) inline static
References ImFormatString(), ImGuiDataType_Float, and ImGuiDataType_Int.
Referenced by ImGui::InputScalarAsWidgetReplacement(), and ImGui::InputScalarEx().
DataTypeFormatString() [2/2]
static void DataTypeFormatString (ImGuiDataType data_type, void * data_ptr, int decimal_precision, char * buf, int buf_size) inline static
References ImFormatString(), ImGuiDataType_Float, and ImGuiDataType_Int.
DataTypeApplyOp()
static void DataTypeApplyOp (ImGuiDataType data_type, int op, void * value1, const void * value2) static
References ImGuiDataType_Float, and ImGuiDataType_Int.
Referenced by ImGui::InputScalarEx().
DataTypeApplyOpFromText()
static bool DataTypeApplyOpFromText (const char * buf, const char * initial_value_buf, ImGuiDataType data_type, void * data_ptr, const char * scalar_format) static
References ImCharIsSpace(), ImGuiDataType_Float, and ImGuiDataType_Int.
Referenced by ImGui::InputScalarAsWidgetReplacement(), and ImGui::InputScalarEx().
GetClipboardTextFn_DefaultImpl()
static const char * GetClipboardTextFn_DefaultImpl (void * user_data) static
References ImVector< T >::empty(), GImGui, NULL, and ImGuiContext::PrivateClipboard.
Referenced by ImGuiIO::ImGuiIO().
SetClipboardTextFn_DefaultImpl()
static void SetClipboardTextFn_DefaultImpl (void * user_data, const char * text) static
References ImVector< T >::clear(), GImGui, memcpy(), and ImGuiContext::PrivateClipboard.
Referenced by ImGuiIO::ImGuiIO().
ImeSetInputScreenPosFn_DefaultImpl()
static void ImeSetInputScreenPosFn_DefaultImpl (int x, int y) static
Referenced by ImGuiIO::ImGuiIO().
MallocWrapper()
static void* MallocWrapper (size_t size, void * user_data) static
References void().
FreeWrapper()
static void FreeWrapper (void * ptr, void * user_data) static
References void().
ImLineClosestPoint()
ImVec2 ImLineClosestPoint (const ImVec2 & a, const ImVec2 & b, const ImVec2 & p)
References ImVec2::x, and ImVec2::y.
Referenced by ImTriangleClosestPoint().
ImTriangleContainsPoint()
bool ImTriangleContainsPoint (const ImVec2 & a, const ImVec2 & b, const ImVec2 & c, const ImVec2 & p)
Referenced by ImGui::BeginMenu(), and ImGui::ColorPicker4().
ImTriangleBarycentricCoords()
void ImTriangleBarycentricCoords (const ImVec2 & a, const ImVec2 & b, const ImVec2 & c, const ImVec2 & p, float & out_u, float & out_v, float & out_w)
Referenced by ImGui::ColorPicker4().
ImTriangleClosestPoint()
ImVec2 ImTriangleClosestPoint (const ImVec2 & a, const ImVec2 & b, const ImVec2 & c, const ImVec2 & p)
References ImLengthSqr(), ImLineClosestPoint(), and ImMin().
Referenced by ImGui::ColorPicker4().
ImStricmp()
int ImStricmp (const char * str1, const char * str2)
ImStrnicmp()
int ImStrnicmp (const char * str1, const char * str2, size_t count)
ImStrncpy()
void ImStrncpy (char * dst, const char * src, size_t count)
Referenced by ImGuiTextFilter::ImGuiTextFilter(), ImGui::InputTextEx(), and ImGui::SetDragDropPayload().
ImStrdup()
char* ImStrdup (const char * str)
References ImGui::MemAlloc(), and memcpy().
Referenced by AddWindowSettings(), ImGuiWindow::ImGuiWindow(), and LoadIniSettingsFromMemory().
ImStrchrRange()
char* ImStrchrRange (const char * str, const char * str_end, char c)
References NULL.
Referenced by LoadIniSettingsFromMemory().
ImStrlenW()
int ImStrlenW (const ImWchar * str)
Referenced by ImGuiIO::AddInputCharacter().
ImStrbolW()
const ImWchar* ImStrbolW (const ImWchar * buf_mid_line, const ImWchar * buf_begin)
Referenced by ImGui::InputTextEx().
ImStristr()
const char* ImStristr (const char * haystack, const char * haystack_end, const char * needle, const char * needle_end)
References NULL.
Referenced by ImGuiTextFilter::PassFilter().
ImAtoi()
static const char* ImAtoi (const char * src, int * output) static
Referenced by ImGui::ParseFormatPrecision().
ImFormatString()
int ImFormatString (char * buf, size_t buf_size, const char * fmt, ...)
References NULL.
Referenced by BeginChildEx(), ImGui::BeginCombo(), ImGui::BeginPopupEx(), ImGui::BeginTooltipEx(), ImGui::ColorEdit4(), ImGui::ColorEditOptionsPopup(), DataTypeFormatString(), ImGui::DragFloat(), ImGui::InputFloat(), NavScoreItem(), ImGui::NavUpdate(), ImGui::ProgressBar(), ImGui::ShowMetricsWindow(), ImGui::SliderFloat(), ImGui::Value(), and ImGui::VSliderFloat().
ImFormatStringV()
int ImFormatStringV (char * buf, size_t buf_size, const char * fmt, va_list args)
References NULL.
Referenced by ImGuiTextBuffer::appendfv(), ImGui::BulletTextV(), ImGui::LabelTextV(), ImGui::TextV(), and ImGui::TreeNodeExV().
ImHash()
ImU32 ImHash (const void * data, int data_size, ImU32 seed)
Referenced by AddWindowSettings(), ImGui::BeginDragDropSource(), ImGui::FindSettingsHandler(), ImGui::FindWindowByName(), ImGuiWindow::GetID(), ImGuiWindow::GetIDFromRectangle(), ImGuiWindow::GetIDNoKeepAlive(), ImGuiWindow::ImGuiWindow(), ImGui::Initialize(), and SettingsHandlerWindow_ReadOpen().
ImTextCharFromUtf8()
int ImTextCharFromUtf8 (unsigned int * out_char, const char * in_text, const char * in_text_end)
Referenced by ImFontAtlas::GlyphRangesBuilder::AddText(), ImFont::CalcTextSizeA(), ImFont::CalcWordWrapPositionA(), ImTextCountCharsFromUtf8(), ImTextStrFromUtf8(), ImGui::InputTextEx(), and ImFont::RenderText().
ImTextStrFromUtf8()
int ImTextStrFromUtf8 (ImWchar * buf, int buf_size, const char * in_text, const char * in_text_end, const char ** in_text_remaining)
References ImTextCharFromUtf8().
Referenced by ImGuiIO::AddInputCharactersUTF8(), ImFileOpen(), and ImGui::InputTextEx().
ImTextCountCharsFromUtf8()
int ImTextCountCharsFromUtf8 (const char * in_text, const char * in_text_end)
References ImTextCharFromUtf8().
Referenced by ImFileOpen(), and ImGui::InputTextEx().
ImTextCharToUtf8()
static int ImTextCharToUtf8 (char * buf, int buf_size, unsigned int c) inline static
Referenced by ImTextStrToUtf8().
ImTextCountUtf8BytesFromChar()
static int ImTextCountUtf8BytesFromChar (unsigned int c) inline static
Referenced by ImTextCountUtf8BytesFromStr().
ImTextStrToUtf8()
int ImTextStrToUtf8 (char * buf, int buf_size, const ImWchar * in_text, const ImWchar * in_text_end)
References ImTextCharToUtf8().
Referenced by ImGui::InputTextEx().
ImTextCountUtf8BytesFromStr()
int ImTextCountUtf8BytesFromStr (const ImWchar * in_text, const ImWchar * in_text_end)
References ImTextCountUtf8BytesFromChar().
Referenced by ImGui::InputTextEx(), ImGuiStb::STB_TEXTEDIT_DELETECHARS(), and ImGuiStb::STB_TEXTEDIT_INSERTCHARS().
ImFileOpen()
FILE* ImFileOpen (const char * filename, const char * mode)
References ImTextCountCharsFromUtf8(), ImTextStrFromUtf8(), and NULL.
Referenced by ImFileLoadToMemory(), ImGui::LogToFile(), and SaveIniSettingsToDisk().
ImFileLoadToMemory()
void* ImFileLoadToMemory (const char * filename, const char * file_open_mode, int * out_file_size, int padding_bytes)
References IM_ASSERT, ImFileOpen(), ImGui::MemAlloc(), ImGui::MemFree(), memset(), and NULL.
Referenced by ImFontAtlas::AddFontFromFileTTF(), and LoadIniSettingsFromDisk().
LowerBound()
static ImVector<ImGuiStorage::Pair>::iterator LowerBound (ImVector< ImGuiStorage::Pair > & data, ImGuiID key) static
References ImVector< T >::begin(), and ImVector< T >::end().
Referenced by ImGuiStorage::GetFloat(), ImGuiStorage::GetFloatRef(), ImGuiStorage::GetInt(), ImGuiStorage::GetIntRef(), ImGuiStorage::GetVoidPtr(), ImGuiStorage::GetVoidPtrRef(), ImGuiStorage::SetFloat(), ImGuiStorage::SetInt(), and ImGuiStorage::SetVoidPtr().
SetCursorPosYAndSetupDummyPrevLine()
static void SetCursorPosYAndSetupDummyPrevLine (float pos_y, float line_height) static
References ImGuiColumnsSet::CellMinY, ImGuiDrawContext::ColumnsSet, ImGuiDrawContext::CursorPos, ImGuiDrawContext::CursorPosPrevLine, ImGuiWindow::DC, ImGui::GetCurrentWindow(), GImGui, ImGuiStyle::ItemSpacing, ImGuiDrawContext::PrevLineHeight, ImGui::SetCursorPosY(), ImGuiContext::Style, and ImVec2::y.
Referenced by ImGuiListClipper::Begin(), and ImGuiListClipper::End().
SetNavID()
static void SetNavID (ImGuiID id, int nav_layer) static
References GImGui, and IM_ASSERT.
Referenced by ImGui::NavInitWindow(), ImGui::NavUpdate(), ImGui::Selectable(), SetNavIDAndMoveMouse(), and ImGui::TreePop().
SetNavIDAndMoveMouse()
static void SetNavIDAndMoveMouse (ImGuiID id, int nav_layer, const ImRect & rect_rel) static
References GImGui, and SetNavID().
Referenced by ImGui::EndMenuBar(), NavRestoreLayer(), and ImGui::NavUpdate().
IsWindowContentHoverable()
static bool IsWindowContentHoverable (ImGuiWindow * window, ImGuiHoveredFlags flags) inline static
References GImGui, ImGuiHoveredFlags_AllowWhenBlockedByPopup, ImGuiWindowFlags_Modal, ImGuiWindowFlags_Popup, and ImGuiWindow::RootWindow.
Referenced by ImGui::IsItemHovered(), ImGui::IsWindowHovered(), and ImGui::ItemHoverable().
NavScoreItemGetQuadrant()
static ImGuiDir NavScoreItemGetQuadrant (float dx, float dy) static
References ImGuiDir_Down, ImGuiDir_Left, ImGuiDir_Right, and ImGuiDir_Up.
Referenced by NavScoreItem().
NavScoreItemDistInterval()
static float NavScoreItemDistInterval (float a0, float a1, float b0, float b1) static
Referenced by NavScoreItem().
NavScoreItem()
static bool NavScoreItem (ImGuiNavMoveResult * result, ImRect cand) static
References ImGui::CalcTextSize(), ImGuiWindow::ClipRect, ImGuiWindow::DC, FLT_MAX, GImGui, IM_ARRAYSIZE, IM_COL32, ImClamp(), ImFormatString(), ImGuiDir_Down, ImGuiDir_Left, ImGuiDir_Right, ImGuiDir_Up, ImGuiKey_C, ImGuiWindowFlags_ChildMenu, ImLerp(), IsKeyPressedMap(), ImGui::IsMouseHoveringRect(), ImGuiDrawContext::LastItemId, ImRect::Max, ImRect::Min, ImGuiDrawContext::NavLayerCurrent, NavScoreItemDistInterval(), NavScoreItemGetQuadrant(), ImVec2::x, and ImVec2::y.
Referenced by ImGui::NavProcessItem().
NavSaveLastChildNavWindow()
static void NavSaveLastChildNavWindow (ImGuiWindow * child_window) static
References ImGuiWindow::Flags, ImGuiWindowFlags_ChildMenu, ImGuiWindowFlags_ChildWindow, ImGuiWindowFlags_Popup, ImGuiWindow::NavLastChildNavWindow, and ImGuiWindow::ParentWindow.
Referenced by ImGui::NavUpdate().
NavRestoreLastChildNavWindow()
static ImGuiWindow* NavRestoreLastChildNavWindow (ImGuiWindow * window) static
References ImGuiWindow::NavLastChildNavWindow.
Referenced by ClosePopupToLevel(), ImGui::FocusFrontMostActiveWindow(), NavRestoreLayer(), and ImGui::NavUpdateWindowing().
NavRestoreLayer()
static void NavRestoreLayer (int layer) static
References GImGui, ImGui::NavInitWindow(), ImGuiContext::NavLayer, NavRestoreLastChildNavWindow(), and SetNavIDAndMoveMouse().
Referenced by ImGui::NavUpdate(), and ImGui::NavUpdateWindowing().
NavUpdateAnyRequestFlag()
static void NavUpdateAnyRequestFlag () inline static
References GImGui, IMGUI_DEBUG_NAV_SCORING, and ImGuiContext::NavAnyRequest.
Referenced by ImGui::NavInitWindow(), ImGui::NavMoveRequestCancel(), ImGui::NavProcessItem(), ImGui::NavUpdate(), and ImGui::SetItemDefaultFocus().
NavMoveRequestButNoResultYet()
static bool NavMoveRequestButNoResultYet () static
References GImGui, and ImGuiContext::NavMoveRequest.
Referenced by ImGui::EndMenu(), ImGui::EndMenuBar(), NavProcessMoveRequestWrapAround(), and ImGui::TreePop().
NavCalcPreferredMousePos()
static ImVec2 NavCalcPreferredMousePos () static
References ImRect::GetHeight(), GetViewportRect(), ImRect::GetWidth(), GImGui, ImClamp(), ImFloor(), ImMin(), ImRect::Max, ImRect::Min, ImGuiWindow::NavRectRel, ImVec2::x, and ImVec2::y.
Referenced by ImGui::Begin(), ImGui::NavUpdate(), and ImGui::OpenPopupEx().
FindWindowIndex()
static int FindWindowIndex (ImGuiWindow * window) static
References GImGui.
Referenced by NavUpdateWindowingHighlightWindow().
FindWindowNavigable()
static ImGuiWindow* FindWindowNavigable (int i_start, int i_stop, int dir) static
References GImGui, ImGui::IsWindowNavFocusable(), NULL, and ImGuiContext::Windows.
Referenced by ImGui::NavUpdateWindowing(), and NavUpdateWindowingHighlightWindow().
IsNavInputDown()
static bool IsNavInputDown (ImGuiNavInput n) static
References GImGui, ImGuiContext::IO, and ImGuiIO::NavInputs.
Referenced by ImGui::GetNavInputAmount2d(), ImGui::NavUpdate(), ImGui::NavUpdateWindowing(), and ImGui::SliderBehavior().
IsNavInputPressed()
static bool IsNavInputPressed (ImGuiNavInput n, ImGuiInputReadMode mode) static
References ImGui::GetNavInputAmount().
Referenced by ImGui::ButtonBehavior(), ImGui::NavUpdate(), and ImGui::NavUpdateWindowing().
IsNavInputPressedAnyOfTwo()
static bool IsNavInputPressedAnyOfTwo (ImGuiNavInput n1, ImGuiNavInput n2, ImGuiInputReadMode mode) static
References ImGui::GetNavInputAmount().
Referenced by ImGui::NavUpdate().
NavUpdateWindowingHighlightWindow()
static void NavUpdateWindowingHighlightWindow (int focus_change_dir) static
References FindWindowIndex(), FindWindowNavigable(), GImGui, IM_ASSERT, and ImGuiWindowFlags_Modal.
Referenced by ImGui::NavUpdateWindowing().
NavScrollToBringItemIntoView()
static void NavScrollToBringItemIntoView (ImGuiWindow * window, ImRect & item_rect_rel) static
References CalcNextScrollFromScrollTargetAndClamp(), ImRect::Contains(), GImGui, ImGuiWindow::InnerRect, ImRect::Max, ImRect::Min, ImGuiWindow::Pos, ImGuiWindow::Scroll, ImGuiWindow::ScrollbarX, ImGuiWindow::ScrollTarget, ImGuiWindow::ScrollTargetCenterRatio, ImRect::Translate(), ImVec2::x, and ImVec2::y.
Referenced by ImGui::NavUpdate().
SettingsHandlerWindow_ReadOpen()
static void* SettingsHandlerWindow_ReadOpen (ImGuiContext * , ImGuiSettingsHandler * , const char * name) static
References AddWindowSettings(), ImGui::FindWindowSettings(), and ImHash().
Referenced by ImGui::Initialize().
SettingsHandlerWindow_ReadLine()
static void SettingsHandlerWindow_ReadLine (ImGuiContext * , ImGuiSettingsHandler * , void * entry, const char * line) static
References ImGuiWindowSettings::Collapsed, GImGui, ImMax(), ImGuiWindowSettings::Pos, ImGuiWindowSettings::Size, ImGuiContext::Style, and ImGuiStyle::WindowMinSize.
Referenced by ImGui::Initialize().
SettingsHandlerWindow_WriteAll()
static void SettingsHandlerWindow_WriteAll (ImGuiContext * imgui_ctx, ImGuiSettingsHandler * handler, ImGuiTextBuffer * buf) static
References AddWindowSettings(), ImGuiWindowSettings::Collapsed, ImGuiWindow::Collapsed, ImGui::FindWindowSettings(), ImGuiWindow::Flags, FLT_MAX, ImGuiWindow::ID, ImGuiWindowFlags_NoSavedSettings, ImGuiWindowSettings::Name, ImGuiWindow::Name, ImGuiWindowSettings::Pos, ImGuiWindow::Pos, ImGuiWindowSettings::Size, ImGuiWindow::SizeFull, ImGuiSettingsHandler::TypeName, ImVec2::x, and ImVec2::y.
Referenced by ImGui::Initialize().
ChildWindowComparer()
static int IMGUI_CDECL ChildWindowComparer (const void * lhs, const void * rhs) static
References ImGuiWindowFlags_Popup, and ImGuiWindowFlags_Tooltip.
Referenced by AddWindowToSortedBuffer().
AddWindowToDrawDataSelectLayer()
static void AddWindowToDrawDataSelectLayer (ImGuiWindow * window) static
References AddWindowToDrawData(), ImGuiWindow::Flags, GImGui, ImGuiWindowFlags_Tooltip, ImGuiContext::IO, and ImGuiIO::MetricsActiveWindows.
Referenced by ImGui::Render().
SetupDrawData()
static void SetupDrawData (ImVector< ImDrawList *> * draw_lists, ImDrawData * out_draw_data) static
References ImDrawData::CmdLists, ImDrawData::CmdListsCount, ImVector< T >::Data, ImDrawList::IdxBuffer, NULL, ImVector< T >::Size, ImDrawData::TotalIdxCount, ImDrawData::TotalVtxCount, ImDrawData::Valid, and ImDrawList::VtxBuffer.
Referenced by ImGui::Render().
LogRenderedText()
static void LogRenderedText (const ImVec2 * ref_pos, const char * text, const char * text_end = NULL) static
References ImGuiWindow::DC, ImGui::FindRenderedTextEnd(), GImGui, IM_NEWLINE, ImGuiDrawContext::LogLinePosY, ImGui::LogText(), NULL, ImGuiDrawContext::TreeDepth, and ImVec2::y.
Referenced by ImGui::Checkbox(), ImGui::InputTextEx(), ImGui::RadioButton(), ImGui::RenderText(), ImGui::RenderTextClipped(), ImGui::RenderTextWrapped(), ImGui::Separator(), and ImGui::TreeNodeBehavior().
NavProcessMoveRequestWrapAround()
static void NavProcessMoveRequestWrapAround (ImGuiWindow * window) static
References GImGui, ImGuiDir_Down, ImGuiDir_Up, ImGuiNavForward_ForwardQueued, ImGuiNavForward_None, ImMax(), NavMoveRequestButNoResultYet(), ImGui::NavMoveRequestCancel(), ImGuiContext::NavMoveRequestForward, ImGuiWindow::Scroll, ImGuiWindow::SizeContents, ImGuiWindow::SizeFull, and ImVec2::y.
Referenced by ImGui::EndPopup().
BeginChildEx()
static bool BeginChildEx (const char * name, ImGuiID id, const ImVec2 & size_arg, bool border, ImGuiWindowFlags extra_flags) static
References ImGuiWindow::AutoFitChildAxises, ImGui::Begin(), ImGuiWindow::ChildId, ImGuiWindow::DC, ImGuiWindow::Flags, ImGui::FocusWindow(), ImGui::GetContentRegionAvail(), ImGui::GetCurrentWindow(), GImGui, IM_ARRAYSIZE, ImFloor(), ImFormatString(), ImGuiAxis_X, ImGuiAxis_Y, ImGuiInputSource_Nav, ImGuiWindowFlags_ChildWindow, ImGuiWindowFlags_NavFlattened, ImGuiWindowFlags_NoMove, ImGuiWindowFlags_NoResize, ImGuiWindowFlags_NoSavedSettings, ImGuiWindowFlags_NoTitleBar, ImMax(), ImGuiWindow::Name, ImGuiDrawContext::NavHasScroll, ImGui::NavInitWindow(), ImGuiDrawContext::NavLayerActiveMask, NULL, ImGui::SetActiveID(), ImGui::SetNextWindowSize(), ImVec2::x, and ImVec2::y.
Referenced by ImGui::BeginChild().
FindBestWindowPosForPopup()
static ImVec2 FindBestWindowPosForPopup (const ImVec2 & ref_pos, const ImVec2 & size, ImGuiDir * last_dir, const ImRect & r_avoid, ImGuiPopupPositionPolicy policy = ImGuiPopupPositionPolicy_Default) static
References ImRect::Contains(), ImGuiStyle::DisplaySafeAreaPadding, ImRect::Expand(), ImRect::GetHeight(), GetViewportRect(), ImRect::GetWidth(), GImGui, ImClamp(), ImGuiDir_Count_, ImGuiDir_Down, ImGuiDir_Left, ImGuiDir_None, ImGuiDir_Right, ImGuiDir_Up, ImGuiPopupPositionPolicy_ComboBox, ImMax(), ImMin(), ImRect::Max, ImRect::Min, ImGuiContext::Style, ImVec2::x, and ImVec2::y.
Referenced by ImGui::Begin(), and ImGui::BeginCombo().
SetWindowConditionAllowFlags()
static void SetWindowConditionAllowFlags (ImGuiWindow * window, ImGuiCond flags, bool enabled) static
References ImGuiWindow::SetWindowCollapsedAllowFlags, ImGuiWindow::SetWindowPosAllowFlags, and ImGuiWindow::SetWindowSizeAllowFlags.
Referenced by ImGui::Begin(), and CreateNewWindow().
CalcSizeAfterConstraint()
static ImVec2 CalcSizeAfterConstraint (ImGuiWindow * window, ImVec2 new_size) static
References ImGuiWindow::Flags, GImGui, ImClamp(), ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_ChildWindow, ImMax(), ImRect::Max, ImGuiWindow::MenuBarHeight(), ImRect::Min, ImGuiWindow::Pos, ImGuiWindow::SizeFull, ImGuiWindow::TitleBarHeight(), ImVec2::x, and ImVec2::y.
Referenced by ImGui::Begin(), ImGui::BeginCombo(), CalcResizePosSizeFromAnyCorner(), CalcSizeAutoFit(), and ImGui::UpdateManualResize().
CalcSizeContents()
static ImVec2 CalcSizeContents (ImGuiWindow * window) static
References ImGuiDrawContext::CursorMaxPos, ImGuiWindow::DC, ImGuiWindow::Pos, ImGuiWindow::Scroll, ImGuiWindow::SizeContentsExplicit, ImGuiWindow::WindowPadding, ImVec2::x, and ImVec2::y.
Referenced by ImGui::Begin(), and ImGui::BeginCombo().
CalcSizeAutoFit()
static ImVec2 CalcSizeAutoFit (ImGuiWindow * window, const ImVec2 & size_contents) static
References CalcSizeAfterConstraint(), ImGuiWindow::Flags, GImGui, ImClamp(), ImGuiWindowFlags_HorizontalScrollbar, ImGuiWindowFlags_NoScrollbar, ImGuiWindowFlags_Tooltip, ImMax(), ImGuiStyle::ScrollbarSize, ImGuiStyle::WindowMinSize, ImVec2::x, and ImVec2::y.
Referenced by ImGui::Begin(), and ImGui::BeginCombo().
GetScrollMaxX()
static float GetScrollMaxX (ImGuiWindow * window) static
References ImMax(), ImGuiWindow::ScrollbarSizes, ImGuiWindow::SizeContents, ImGuiWindow::SizeFull, and ImVec2::x.
Referenced by CalcNextScrollFromScrollTargetAndClamp(), ImGui::GetScrollMaxX(), and ImGui::ShowMetricsWindow().
GetScrollMaxY()
static float GetScrollMaxY (ImGuiWindow * window) static
References ImMax(), ImGuiWindow::ScrollbarSizes, ImGuiWindow::SizeContents, ImGuiWindow::SizeFull, and ImVec2::y.
Referenced by ImGui::Begin(), CalcNextScrollFromScrollTargetAndClamp(), ImGui::GetScrollMaxY(), ImGui::InputTextEx(), and ImGui::ShowMetricsWindow().
GetWindowBgColorIdxFromFlags()
static ImGuiCol GetWindowBgColorIdxFromFlags (ImGuiWindowFlags flags) static
References ImGuiCol_ChildBg, ImGuiCol_PopupBg, ImGuiCol_WindowBg, ImGuiWindowFlags_ChildWindow, ImGuiWindowFlags_Popup, and ImGuiWindowFlags_Tooltip.
Referenced by ImGui::Begin().
CalcResizePosSizeFromAnyCorner()
static void CalcResizePosSizeFromAnyCorner (ImGuiWindow * window, const ImVec2 & corner_target, const ImVec2 & corner_norm, ImVec2 * out_pos, ImVec2 * out_size) static
References CalcSizeAfterConstraint(), ImLerp(), ImGuiWindow::Pos, ImGuiWindow::Size, ImVec2::x, and ImVec2::y.
Referenced by ImGui::UpdateManualResize().
GetBorderRect()
static ImRect GetBorderRect (ImGuiWindow * window, int border_n, float perp_padding, float thickness) static
References IM_ASSERT, ImRect::Max, ImRect::Min, ImGuiWindow::Rect(), ImVec2::x, and ImVec2::y.
Referenced by ImGui::Begin(), and ImGui::UpdateManualResize().
GetStyleVarInfo()
static const ImGuiStyleVarInfo* GetStyleVarInfo (ImGuiStyleVar idx) static
References GStyleVarInfo, IM_ARRAYSIZE, IM_ASSERT, and ImGuiStyleVar_Count_.
Referenced by ImGui::PopStyleVar(), and ImGui::PushStyleVar().
GetMinimumStepAtDecimalPrecision()
static float GetMinimumStepAtDecimalPrecision (int decimal_precision) static
Referenced by ImGui::DragBehavior(), and ImGui::RoundScalar().
SliderBehaviorCalcRatioFromValue()
static float SliderBehaviorCalcRatioFromValue (float v, float v_min, float v_max, float power, float linear_zero_pos) inline static
References ImClamp(), ImMax(), and ImMin().
Referenced by ImGui::SliderBehavior().
Plot_ArrayGetter()
static float Plot_ArrayGetter (void * data, int idx) static
References ImGuiPlotArrayGetterData::Stride, and ImGuiPlotArrayGetterData::Values.
Referenced by ImGui::PlotHistogram(), and ImGui::PlotLines().
CalcMaxPopupHeightFromItemCount()
static float CalcMaxPopupHeightFromItemCount (int items_count) static
References FLT_MAX, and GImGui.
Referenced by ImGui::BeginCombo().
Items_ArrayGetter()
static bool Items_ArrayGetter (void * data, int idx, const char ** out_text) static
Referenced by ImGui::Combo(), and ImGui::ListBox().
Items_SingleStringGetter()
static bool Items_SingleStringGetter (void * data, int idx, const char ** out_text) static
Referenced by ImGui::Combo().
ImAlphaBlendColor()
static ImU32 ImAlphaBlendColor (ImU32 col_a, ImU32 col_b) inline static
References IM_COL32, IM_COL32_A_SHIFT, IM_COL32_B_SHIFT, IM_COL32_G_SHIFT, IM_COL32_R_SHIFT, and ImLerp().
Referenced by ImGui::RenderColorRectWithAlphaCheckerboard().
ColorPickerOptionsPopup()
static void ColorPickerOptionsPopup (ImGuiColorEditFlags flags, const float * ref_col) static
References ImGui::BeginPopup(), ImGui::CheckboxFlags(), ImGui::ColorPicker4(), ImGui::EndPopup(), ImGui::GetCursorScreenPos(), ImGui::GetFrameHeight(), GImGui, ImGuiColorEditFlags__PickerMask, ImGuiColorEditFlags_AlphaBar, ImGuiColorEditFlags_NoAlpha, ImGuiColorEditFlags_NoInputs, ImGuiColorEditFlags_NoLabel, ImGuiColorEditFlags_NoOptions, ImGuiColorEditFlags_NoSidePreview, ImGuiColorEditFlags_PickerHueBar, ImGuiColorEditFlags_PickerHueWheel, ImMax(), memcpy(), ImGui::PopID(), ImGui::PopItemWidth(), ImGui::PushID(), ImGui::PushItemWidth(), ImGui::Selectable(), ImGui::Separator(), ImGui::SetCursorScreenPos(), ImVec2::x, and ImVec4::x.
Referenced by ImGui::ColorPicker4().
RenderArrow()
static void RenderArrow (ImDrawList * draw_list, ImVec2 pos, ImVec2 half_sz, ImGuiDir direction, ImU32 col) static
References ImDrawList::AddTriangleFilled(), ImGuiDir_Count_, ImGuiDir_Down, ImGuiDir_Left, ImGuiDir_None, ImGuiDir_Right, ImGuiDir_Up, ImVec2::x, and ImVec2::y.
Referenced by RenderArrowsForVerticalBar().
RenderArrowsForVerticalBar()
static void RenderArrowsForVerticalBar (ImDrawList * draw_list, ImVec2 pos, ImVec2 half_sz, float bar_w) static
References IM_COL32_BLACK, IM_COL32_WHITE, ImGuiDir_Left, ImGuiDir_Right, RenderArrow(), ImVec2::x, and ImVec2::y.
Referenced by ImGui::ColorPicker4().
OffsetNormToPixels()
static float OffsetNormToPixels (const ImGuiColumnsSet * columns, float offset_norm) static
References ImGuiColumnsSet::MaxX, and ImGuiColumnsSet::MinX.
Referenced by ImGui::GetColumnWidth(), and GetColumnWidthEx().
PixelsToOffsetNorm()
static float PixelsToOffsetNorm (const ImGuiColumnsSet * columns, float offset) static
References ImGuiColumnsSet::MaxX, and ImGuiColumnsSet::MinX.
Referenced by ImGui::BeginColumns(), and ImGui::SetColumnOffset().
GetColumnsRectHalfWidth()
static float GetColumnsRectHalfWidth () inline static
Referenced by ImGui::EndColumns(), and GetDraggedColumnOffset().
GetDraggedColumnOffset()
static float GetDraggedColumnOffset (ImGuiColumnsSet * columns, int column_index) static
References ImGuiColumnsSet::Flags, ImGui::GetColumnOffset(), GetColumnsRectHalfWidth(), GImGui, ImGuiColumnsSet::ID, IM_ASSERT, ImGuiColumnsFlags_NoPreserveWidths, ImMax(), ImMin(), ImGuiWindow::Pos, and ImVec2::x.
Referenced by ImGui::EndColumns().
GetColumnWidthEx()
static float GetColumnWidthEx (ImGuiColumnsSet * columns, int column_index, bool before_resize = false) static
References ImGuiColumnsSet::Columns, ImGuiColumnsSet::Current, and OffsetNormToPixels().
Referenced by ImGui::SetColumnOffset().
FindOrAddColumnsSet()
static ImGuiColumnsSet* FindOrAddColumnsSet (ImGuiWindow * window, ImGuiID id) static
References ImVector< T >::back(), ImGuiWindow::ColumnsStorage, ImGuiColumnsSet::ID, ImVector< T >::push_back(), and ImVector< T >::Size.
Referenced by ImGui::BeginColumns().
Variable Documentation
GImGui
ImGuiContext* GImGui = NULL
Referenced by ImGui::AcceptDragDropPayload(), ImGui::ActivateItem(), AddWindowSettings(), AddWindowToDrawDataSelectLayer(), ImGui::AlignTextToFramePadding(), ImGui::ArrowButton(), ImGuiItemHoveredDataBackup::Backup(), ImGui::Begin(), BeginChildEx(), ImGui::BeginChildFrame(), ImGui::BeginColumns(), ImGui::BeginCombo(), ImGui::BeginDragDropSource(), ImGui::BeginDragDropTarget(), ImGui::BeginDragDropTargetCustom(), ImGui::BeginGroup(), ImGui::BeginMainMenuBar(), ImGui::BeginMenu(), ImGui::BeginPopup(), ImGui::BeginPopupContextItem(), ImGui::BeginPopupContextVoid(), ImGui::BeginPopupContextWindow(), ImGui::BeginPopupEx(), ImGui::BeginPopupModal(), ImGui::BeginTooltipEx(), ImGui::BringWindowToBack(), ImGui::BringWindowToFront(), ImGui::Bullet(), ImGui::BulletTextV(), ImGui::ButtonBehavior(), ImGui::ButtonEx(), ImGuiWindow::CalcFontSize(), ImGui::CalcItemSize(), ImGui::CalcListClipping(), CalcMaxPopupHeightFromItemCount(), CalcSizeAfterConstraint(), CalcSizeAutoFit(), ImGui::CalcTextSize(), ImGui::CaptureKeyboardFromApp(), ImGui::CaptureMouseFromApp(), ImGui::Checkbox(), CheckStacksSize(), ImGui::ClearDragDrop(), ImGui::CloseButton(), ImGui::CloseCurrentPopup(), ImGui::ClosePopup(), ImGui::ClosePopupsOverWindow(), ClosePopupToLevel(), ImGui::CollapsingHeader(), ImGui::ColorButton(), ImGui::ColorEdit4(), ImGui::ColorEditOptionsPopup(), ImGui::ColorPicker4(), ColorPickerOptionsPopup(), ImGui::ColorTooltip(), ImGui::CreateContext(), CreateNewWindow(), ImGui::DestroyContext(), ImGui::DragBehavior(), ImGui::DragFloat(), ImGui::DragFloatN(), ImGui::DragFloatRange2(), ImGui::DragIntN(), ImGui::DragIntRange2(), ImGui::End(), ImGui::EndChild(), ImGui::EndColumns(), ImGui::EndCombo(), ImGui::EndDragDropSource(), ImGui::EndDragDropTarget(), ImGui::EndFrame(), ImGui::EndGroup(), ImGui::EndMainMenuBar(), ImGui::EndMenu(), ImGui::EndMenuBar(), ImGui::EndPopup(), FindBestWindowPosForPopup(), FindHoveredWindow(), ImGui::FindSettingsHandler(), ImGui::FindWindowByName(), FindWindowIndex(), FindWindowNavigable(), ImGui::FindWindowSettings(), ImGui::FocusableItemRegister(), ImGui::FocusFrontMostActiveWindow(), ImGui::FocusWindow(), ImGui::GetActiveID(), ImGui::GetClipboardText(), GetClipboardTextFn_DefaultImpl(), ImGui::GetColorU32(), ImGui::GetCurrentContext(), ImGui::GetCurrentWindow(), ImGui::GetCurrentWindowRead(), GetDefaultFont(), GetDraggedColumnOffset(), ImGui::GetDrawData(), ImGui::GetDrawListSharedData(), ImGui::GetFont(), ImGui::GetFontSize(), ImGui::GetFontTexUvWhitePixel(), ImGui::GetFrameCount(), ImGui::GetFrameHeight(), ImGui::GetFrameHeightWithSpacing(), GetFrontMostModalRootWindow(), ImGui::GetHoveredID(), ImGui::GetID(), ImGui::GetIO(), ImGui::GetKeyIndex(), ImGui::GetKeyPressedAmount(), ImGui::GetMouseCursor(), ImGui::GetMouseDragDelta(), ImGui::GetMousePos(), ImGui::GetMousePosOnOpeningCurrentPopup(), ImGui::GetNavInputAmount(), ImGui::GetOverlayDrawList(), ImGui::GetScrollMaxX(), ImGui::GetScrollMaxY(), ImGui::GetScrollX(), ImGui::GetScrollY(), ImGui::GetStyle(), ImGui::GetStyleColorVec4(), ImGui::GetTextLineHeight(), ImGui::GetTextLineHeightWithSpacing(), ImGui::GetTime(), ImGui::GetTreeNodeToLabelSpacing(), GetViewportRect(), ImGui::GetWindowHeight(), ImGui::GetWindowPos(), ImGui::GetWindowWidth(), ImGui::ImageButton(), ImGui::Indent(), ImGui::InputFloatN(), ImGui::InputIntN(), ImGui::InputScalarAsWidgetReplacement(), ImGui::InputScalarEx(), InputTextCalcTextSizeW(), ImGui::InputTextEx(), ImGui::IsAnyItemActive(), ImGui::IsAnyItemFocused(), ImGui::IsAnyItemHovered(), ImGui::IsAnyMouseDown(), ImGui::IsClippedEx(), ImGui::IsDragDropPayloadBeingAccepted(), ImGui::IsItemActive(), ImGui::IsItemFocused(), ImGui::IsItemHovered(), ImGui::IsKeyDown(), ImGui::IsKeyPressed(), IsKeyPressedMap(), ImGui::IsKeyReleased(), ImGui::IsMouseClicked(), ImGui::IsMouseDoubleClicked(), ImGui::IsMouseDown(), ImGui::IsMouseDragging(), ImGui::IsMouseHoveringRect(), ImGui::IsMousePosValid(), ImGui::IsMouseReleased(), IsNavInputDown(), ImGui::IsPopupOpen(), IsWindowContentHoverable(), ImGui::IsWindowFocused(), ImGui::IsWindowHovered(), ImGui::IsWindowNavFocusable(), ImGui::ItemAdd(), ImGui::ItemHoverable(), ImGui::ItemSize(), ImGui::KeepAliveID(), ImGui::LabelTextV(), LoadIniSettingsFromMemory(), ImGui::LogButtons(), ImGui::LogFinish(), LogRenderedText(), ImGui::LogText(), ImGui::LogToClipboard(), ImGui::LogToFile(), ImGui::LogToTTY(), MarkIniSettingsDirty(), ImGui::MarkIniSettingsDirty(), ImGuiWindow::MenuBarHeight(), ImGui::MenuItem(), NavCalcPreferredMousePos(), ImGui::NavInitWindow(), NavMoveRequestButNoResultYet(), ImGui::NavMoveRequestCancel(), ImGui::NavProcessItem(), NavProcessMoveRequestWrapAround(), NavRestoreLayer(), NavScoreItem(), NavScrollToBringItemIntoView(), ImGui::NavUpdate(), NavUpdateAnyRequestFlag(), ImGui::NavUpdateWindowing(), NavUpdateWindowingHighlightWindow(), ImGui::NewFrame(), ImGui::NewLine(), ImGui::NextColumn(), ImGui::OpenPopup(), ImGui::OpenPopupEx(), ImGui::OpenPopupOnItemClick(), ImGui::PlotEx(), ImGui::PopFont(), ImGui::PopStyleColor(), ImGui::PopStyleVar(), ImGui::ProgressBar(), ImGui::PushFont(), ImGui::PushMultiItemsWidths(), ImGui::PushStyleColor(), ImGui::PushStyleVar(), ImGui::RadioButton(), ImGui::Render(), ImGui::RenderBullet(), ImGui::RenderCheckMark(), ImGui::RenderFrame(), ImGui::RenderFrameBorder(), ImGui::RenderNavHighlight(), ImGui::RenderText(), ImGui::RenderTextClipped(), ImGui::RenderTextWrapped(), ImGui::RenderTriangle(), ImGui::ResetMouseDragDelta(), ImGuiItemHoveredDataBackup::Restore(), ImGui::SameLine(), SaveIniSettingsToDisk(), SaveIniSettingsToMemory(), ImGui::Scrollbar(), ImGui::Selectable(), ImGui::Separator(), ImGui::SetActiveID(), ImGui::SetClipboardText(), SetClipboardTextFn_DefaultImpl(), ImGui::SetColorEditOptions(), ImGui::SetColumnOffset(), ImGui::SetCurrentContext(), ImGui::SetCurrentFont(), SetCurrentWindow(), SetCursorPosYAndSetupDummyPrevLine(), ImGui::SetDragDropPayload(), ImGui::SetFocusID(), ImGui::SetHoveredID(), ImGui::SetItemAllowOverlap(), ImGui::SetItemDefaultFocus(), ImGui::SetMouseCursor(), SetNavID(), SetNavIDAndMoveMouse(), ImGui::SetNextTreeNodeOpen(), ImGui::SetNextWindowBgAlpha(), ImGui::SetNextWindowCollapsed(), ImGui::SetNextWindowContentSize(), ImGui::SetNextWindowFocus(), ImGui::SetNextWindowPos(), ImGui::SetNextWindowSize(), ImGui::SetNextWindowSizeConstraints(), ImGui::SetScrollFromPosY(), ImGui::SetScrollHere(), SettingsHandlerWindow_ReadLine(), ImGui::SetWindowCollapsed(), ImGui::SetWindowFocus(), ImGui::SetWindowFontScale(), ImGui::SetWindowSize(), ImGui::ShowMetricsWindow(), ImGui::SliderBehavior(), ImGui::SliderFloat(), ImGui::SliderFloatN(), ImGui::SliderIntN(), ImGui::SmallButton(), ImGui::SplitterBehavior(), ImGuiStb::STB_TEXTEDIT_GETWIDTH(), ImGui::TextDisabledV(), ImGui::TextUnformatted(), ImGui::TextV(), ImGui::TextWrappedV(), ImGuiWindow::TitleBarHeight(), ImGui::TreeAdvanceToLabelPos(), ImGui::TreeNodeBehavior(), ImGui::TreeNodeBehaviorIsOpen(), ImGui::TreeNodeExV(), ImGui::TreePop(), ImGui::Unindent(), ImGui::UpdateManualResize(), ImGui::UpdateMovingWindow(), ImGui::VerticalSeparator(), and ImGui::VSliderFloat().
GImAllocatorAllocFunc
void*(* GImAllocatorAllocFunc) (size_t size, void *user_data) = MallocWrapper static
Referenced by ImGui::MemAlloc(), and ImGui::SetAllocatorFunctions().
GImAllocatorFreeFunc
void(* GImAllocatorFreeFunc) (void *ptr, void *user_data) = FreeWrapper static
Referenced by ImGui::MemFree(), and ImGui::SetAllocatorFunctions().
GImAllocatorUserData
void* GImAllocatorUserData = NULL static
Referenced by ImGui::MemAlloc(), ImGui::MemFree(), and ImGui::SetAllocatorFunctions().
GImAllocatorActiveAllocationsCount
size_t GImAllocatorActiveAllocationsCount = 0 static
Referenced by ImGui::MemAlloc(), ImGui::MemFree(), and ImGui::ShowMetricsWindow().
resize_grip_def
const ImGuiResizeGripDef resize_grip_def[4]
Initial value:
=
{
    { ImVec2(1,1), ImVec2(-1,-1), 0, 3 },
    { ImVec2(0,1), ImVec2(+1,-1), 3, 6 },
    { ImVec2(0,0), ImVec2(+1,+1), 6, 9 },
    { ImVec2(1,0), ImVec2(-1,+1), 9,12 },
}
Referenced by ImGui::Begin(), and ImGui::UpdateManualResize().
GStyleVarInfo
const ImGuiStyleVarInfo GStyleVarInfo[] static
Initial value:
=
{
    { ImGuiDataType_Float,  (ImU32)IM_OFFSETOF(ImGuiStyle, Alpha) },
    { ImGuiDataType_Float2, (ImU32)IM_OFFSETOF(ImGuiStyle, WindowPadding) },
    { ImGuiDataType_Float,  (ImU32)IM_OFFSETOF(ImGuiStyle, WindowRounding) },
    { ImGuiDataType_Float,  (ImU32)IM_OFFSETOF(ImGuiStyle, WindowBorderSize) },
    { ImGuiDataType_Float2, (ImU32)IM_OFFSETOF(ImGuiStyle, WindowMinSize) },
    { ImGuiDataType_Float2, (ImU32)IM_OFFSETOF(ImGuiStyle, WindowTitleAlign) },
    { ImGuiDataType_Float,  (ImU32)IM_OFFSETOF(ImGuiStyle, ChildRounding) },
    { ImGuiDataType_Float,  (ImU32)IM_OFFSETOF(ImGuiStyle, ChildBorderSize) },
    { ImGuiDataType_Float,  (ImU32)IM_OFFSETOF(ImGuiStyle, PopupRounding) },
    { ImGuiDataType_Float,  (ImU32)IM_OFFSETOF(ImGuiStyle, PopupBorderSize) },
    { ImGuiDataType_Float2, (ImU32)IM_OFFSETOF(ImGuiStyle, FramePadding) },
    { ImGuiDataType_Float,  (ImU32)IM_OFFSETOF(ImGuiStyle, FrameRounding) },
    { ImGuiDataType_Float,  (ImU32)IM_OFFSETOF(ImGuiStyle, FrameBorderSize) },
    { ImGuiDataType_Float2, (ImU32)IM_OFFSETOF(ImGuiStyle, ItemSpacing) },
    { ImGuiDataType_Float2, (ImU32)IM_OFFSETOF(ImGuiStyle, ItemInnerSpacing) },
    { ImGuiDataType_Float,  (ImU32)IM_OFFSETOF(ImGuiStyle, IndentSpacing) },
    { ImGuiDataType_Float,  (ImU32)IM_OFFSETOF(ImGuiStyle, ScrollbarSize) },
    { ImGuiDataType_Float,  (ImU32)IM_OFFSETOF(ImGuiStyle, ScrollbarRounding) },
    { ImGuiDataType_Float,  (ImU32)IM_OFFSETOF(ImGuiStyle, GrabMinSize) },
    { ImGuiDataType_Float,  (ImU32)IM_OFFSETOF(ImGuiStyle, GrabRounding) },
    { ImGuiDataType_Float2, (ImU32)IM_OFFSETOF(ImGuiStyle, ButtonTextAlign) },
}
Referenced by GetStyleVarInfo().