Aurora Framework: AuroraFW::GUI::Window Class Reference
AuroraFW::GUI::Window Class Reference
Public Types
enum WindowPosition {
NonePosition, CenterPosition, MousePosition, AlwaysCenterPosition,
CenterParentPosition
}
enum WindowType { ToplevelWindow, PopupWindow }
Public Member Functions
Window (const std::string &="Aurora Window", const int &=800, const int &=600, const WindowPosition &=NonePosition, const WindowType &=ToplevelWindow)
Window (const Window &)=delete
~Window ()
void addWidget (Widget *)
void close ()
template<typename R , typename... Args>
void connect (const std::string &, R(*)(Args...), void *=AFW_NULLPTR)
template<typename R , typename... Args>
void connect (const std::string &signal_, std::function< R(Args...)> callback, void *data=AFW_NULLPTR)
void deiconify ()
void destroy ()
void fullscreen ()
AFW_FORCE_INLINE GtkWidget * getNativeGtkWidget () const
double getOpacity () const
WindowPosition getPos () const
Math::Vector2D getSize () const
std::string getTitle () const
void hide ()
void iconify ()
bool isFocused () const
bool isMaximized () const
bool isResizable () const
void maximize ()
void move (int, int)
void move (Math::Vector2D &vec)
std::string name () const
Window & operator= (const Window &)=delete
Widget * parent () const
void resize (int, int)
void resize (Math::Vector2D &vec)
void setIcon (const unsigned char *, int, int, int, bool)
void setIcon (ImageManager::Image &)
void setIcon (const char *)
void setIcon (const std::string &str)
void setName (const std::string &)
void setOpacity (double)
void setParent (Widget *)
void setPos (const WindowPosition &)
void setResizable (bool)
void setTitle (const std::string &)
void show () override
void start (std::function< void()>=[]{})
void stick ()
void unfullscreen ()
void unmaximize ()
void unstick ()
Protected Member Functions
void _show ()
Protected Attributes
GtkWidget * _widget
Member Enumeration Documentation
WindowType
enum AuroraFW::GUI::Window::WindowType
Enumerator
ToplevelWindow
PopupWindow
WindowPosition
enum AuroraFW::GUI::Window::WindowPosition
Enumerator
NonePosition
CenterPosition
MousePosition
AlwaysCenterPosition
CenterParentPosition
Constructor & Destructor Documentation
Window() [1/2]
AuroraFW::GUI::Window::Window (const std::string & name = "Aurora Window", const int & width = 800, const int & height = 600, const WindowPosition & pos = NonePosition, const WindowType & type = ToplevelWindow)
References AuroraFW::GUI::Widget::_widget, AuroraFW::GUI::Widget::connect(), height, AuroraFW::DebugManager::Log(), AuroraFW::GUI::Widget::name(), setPos(), setTitle(), and width.
~Window()
AuroraFW::GUI::Window::~Window ()
References AuroraFW::GUI::Widget::destroy().
Window() [2/2]
AuroraFW::GUI::Window::Window (const Window &) delete
Member Function Documentation
operator=()
Window& AuroraFW::GUI::Window::operator= (const Window &) delete
show()
void AuroraFW::GUI::Window::show () override virtual
Reimplemented from AuroraFW::GUI::Widget.
References AuroraFW::GUI::Widget::_show().
addWidget()
void AuroraFW::GUI::Window::addWidget (Widget * widget)
References AuroraFW::GUI::Widget::_widget, AFW_NULLPTR, and AuroraFW::GUI::Widget::getNativeGtkWidget().
setTitle()
void AuroraFW::GUI::Window::setTitle (const std::string & title)
References AuroraFW::GUI::Widget::_widget, and AuroraFW::DebugManager::Log().
Referenced by Window().
setPos()
void AuroraFW::GUI::Window::setPos (const WindowPosition & pos)
References AuroraFW::GUI::Widget::_widget, and AuroraFW::DebugManager::Log().
Referenced by Window().
resize() [1/2]
void AuroraFW::GUI::Window::resize (int w, int h)
References AuroraFW::GUI::Widget::_widget, and AuroraFW::DebugManager::Log().
resize() [2/2]
void AuroraFW::GUI::Window::resize (Math::Vector2D & vec) inline
References resize(), AuroraFW::Math::vec2< T >::x, and AuroraFW::Math::vec2< T >::y.
Referenced by resize().
move() [1/2]
void AuroraFW::GUI::Window::move (int x, int y)
References AuroraFW::GUI::Widget::_widget, and AuroraFW::DebugManager::Log().
move() [2/2]
void AuroraFW::GUI::Window::move (Math::Vector2D & vec) inline
References move(), AuroraFW::Math::vec2< T >::x, and AuroraFW::Math::vec2< T >::y.
Referenced by move().
setOpacity()
void AuroraFW::GUI::Window::setOpacity (double val)
References AuroraFW::GUI::Widget::_widget, and AuroraFW::DebugManager::Log().
setResizable()
void AuroraFW::GUI::Window::setResizable (bool val)
References AuroraFW::GUI::Widget::_widget, and AuroraFW::DebugManager::Log().
setIcon() [1/4]
void AuroraFW::GUI::Window::setIcon (const unsigned char * data, int width, int height, int bpp, bool alpha)
References AuroraFW::GUI::Widget::_widget, height, AuroraFW::DebugManager::Log(), NULL, and width.
setIcon() [2/4]
void AuroraFW::GUI::Window::setIcon (ImageManager::Image &)
setIcon() [3/4]
void AuroraFW::GUI::Window::setIcon (const char *)
setIcon() [4/4]
void AuroraFW::GUI::Window::setIcon (const std::string & str) inline
References setIcon().
Referenced by setIcon().
maximize()
void AuroraFW::GUI::Window::maximize ()
References AuroraFW::GUI::Widget::_widget, and AuroraFW::DebugManager::Log().
unmaximize()
void AuroraFW::GUI::Window::unmaximize ()
References AuroraFW::GUI::Widget::_widget, and AuroraFW::DebugManager::Log().
iconify()
void AuroraFW::GUI::Window::iconify ()
References AuroraFW::GUI::Widget::_widget, and AuroraFW::DebugManager::Log().
deiconify()
void AuroraFW::GUI::Window::deiconify ()
References AuroraFW::GUI::Widget::_widget, and AuroraFW::DebugManager::Log().
stick()
void AuroraFW::GUI::Window::stick ()
References AuroraFW::GUI::Widget::_widget, and AuroraFW::DebugManager::Log().
unstick()
void AuroraFW::GUI::Window::unstick ()
References AuroraFW::GUI::Widget::_widget, and AuroraFW::DebugManager::Log().
fullscreen()
void AuroraFW::GUI::Window::fullscreen ()
References AuroraFW::GUI::Widget::_widget, and AuroraFW::DebugManager::Log().
unfullscreen()
void AuroraFW::GUI::Window::unfullscreen ()
References AuroraFW::GUI::Widget::_widget, and AuroraFW::DebugManager::Log().
close()
void AuroraFW::GUI::Window::close ()
References AuroraFW::GUI::Widget::_widget, and AuroraFW::DebugManager::Log().
getOpacity()
double AuroraFW::GUI::Window::getOpacity () const
getSize()
Math::Vector2D AuroraFW::GUI::Window::getSize () const
getPos()
WindowPosition AuroraFW::GUI::Window::getPos () const
getTitle()
std::string AuroraFW::GUI::Window::getTitle () const
isResizable()
bool AuroraFW::GUI::Window::isResizable () const
isMaximized()
bool AuroraFW::GUI::Window::isMaximized () const
isFocused()
bool AuroraFW::GUI::Window::isFocused () const
start()
void AuroraFW::GUI::Window::start (std::function< void()> = []{})
hide()
void AuroraFW::GUI::Widget::hide () inherited
References AuroraFW::GUI::Widget::_widget.
destroy()
void AuroraFW::GUI::Widget::destroy () inherited
References AuroraFW::GUI::Widget::_widget.
Referenced by ~Window().
setParent()
void AuroraFW::GUI::Widget::setParent (Widget * parent) inherited
References AuroraFW::GUI::Widget::_widget, and AuroraFW::GUI::Widget::parent().
Referenced by AuroraFW::GUI::Button::Button(), and AuroraFW::GUI::Label::Label().
setName()
void AuroraFW::GUI::Widget::setName (const std::string & str) inherited
References AuroraFW::GUI::Widget::_widget.
name()
std::string AuroraFW::GUI::Widget::name () const inherited
Referenced by AuroraFW::GUI::Button::Button(), AuroraFW::GUI::Label::Label(), and Window().
parent()
Widget * AuroraFW::GUI::Widget::parent () const inherited
References AuroraFW::GUI::Widget::_widget.
Referenced by AuroraFW::GUI::Button::Button(), AuroraFW::GUI::Label::Label(), and AuroraFW::GUI::Widget::setParent().
getNativeGtkWidget()
AFW_FORCE_INLINE GtkWidget* AuroraFW::GUI::Widget::getNativeGtkWidget () const inline inherited
Referenced by addWidget().
connect() [1/2]
template<typename R , typename... Args> void AuroraFW::GUI::Widget::connect (const std::string & signal_, R(*)(Args...) callback, void * data = AFW_NULLPTR) inherited
References AuroraFW::GUI::Widget::_widget, and AuroraFW::DebugManager::Log().
Referenced by Window().
connect() [2/2]
template<typename R , typename... Args> void AuroraFW::GUI::Widget::connect (const std::string & signal_, std::function< R(Args...)> callback, void * data = AFW_NULLPTR) inline inherited
References AuroraFW::getCallbackPtr().
_show()
void AuroraFW::GUI::Widget::_show () protected inherited
References AuroraFW::GUI::Widget::_widget.
Referenced by show().
Member Data Documentation
_widget
GtkWidget* AuroraFW::GUI::Widget::_widget protected inherited
Referenced by AuroraFW::GUI::Widget::_show(), addWidget(), AuroraFW::GUI::Button::Button(), close(), AuroraFW::GUI::Widget::connect(), deiconify(), AuroraFW::GUI::Widget::destroy(), fullscreen(), AuroraFW::GUI::Label::getAlignment(), AuroraFW::GUI::Label::getText(), AuroraFW::GUI::Label::getWrapMode(), AuroraFW::GUI::Label::getXAlignment(), AuroraFW::GUI::Label::getYAlignment(), AuroraFW::GUI::Widget::hide(), iconify(), AuroraFW::GUI::Label::isSelectable(), AuroraFW::GUI::Label::isWrap(), AuroraFW::GUI::Label::Label(), maximize(), move(), AuroraFW::GUI::Widget::parent(), resize(), AuroraFW::GUI::Label::setAlignment(), setIcon(), AuroraFW::GUI::Widget::setName(), setOpacity(), AuroraFW::GUI::Widget::setParent(), setPos(), setResizable(), AuroraFW::GUI::Label::setSelectable(), AuroraFW::GUI::Label::setText(), setTitle(), AuroraFW::GUI::Label::setWrap(), AuroraFW::GUI::Label::setWrapMode(), stick(), unfullscreen(), unmaximize(), unstick(), and Window().
The documentation for this class was generated from the following files:
gui/include/AuroraFW/GUI/Window.h
gui/src/Window.cpp