Aurora Framework: g72x_test.c File Reference
g72x_test.c File Reference
Macros
#define BUFFER_SIZE (1 << 14)
#define DECAY_COUNT 1000
#define M_PI 3.14159265358979323846264338
#define SAMPLE_RATE 11025
#define SIGNAL_MAXVAL 30000.0
Functions
static int error_function (double data, double orig, double margin)
static void g721_test (void)
static void g723_test (double margin)
static void gen_signal_double (double *data, double scale, int datalen)
int main (int argc, char *argv [])
static int oct_save_short (short *a, short *b, int len)
Macro Definition Documentation
M_PI
#define M_PI 3.14159265358979323846264338
Referenced by gen_signal_double().
BUFFER_SIZE
#define BUFFER_SIZE (1 << 14)
Referenced by g723_test().
SAMPLE_RATE
#define SAMPLE_RATE 11025
Referenced by gen_signal_double().
SIGNAL_MAXVAL
#define SIGNAL_MAXVAL 30000.0
DECAY_COUNT
#define DECAY_COUNT 1000
Referenced by gen_signal_double().
Function Documentation
g721_test()
static void g721_test (void) static
Referenced by main().
g723_test()
static void g723_test (double margin) static
References BUFFER_SIZE, g72x_state::codec_bits, g72x_state::decoder, g72x_state::encoder, error_function(), g723_24_decoder(), g723_24_encoder(), gen_signal_double(), memset(), oct_save_short(), and private_init_state().
Referenced by main().
gen_signal_double()
static void gen_signal_double (double * data, double scale, int datalen) static
References AuroraFW::Math::cos(), DECAY_COUNT, M_PI, SAMPLE_RATE, scale(), and AuroraFW::Math::sin().
Referenced by g723_test().
error_function()
static int error_function (double data, double orig, double margin) static
Referenced by g723_test().
oct_save_short()
static int oct_save_short (short * a, short * b, int len) static
References a, and g72x_state::b.
Referenced by g723_test().
main()
int main (int argc, char * argv[])
References g721_test(), and g723_test().