Aurora Framework: Window.c File Reference
NULL/Window.c File Reference
Functions
int _glfwPlatformCreateCursor (_GLFWcursor *cursor, const GLFWimage *image, int xhot, int yhot)
int _glfwPlatformCreateStandardCursor (_GLFWcursor *cursor, int shape)
int _glfwPlatformCreateWindow (_GLFWwindow *window, const _GLFWwndconfig *wndconfig, const _GLFWctxconfig *ctxconfig, const _GLFWfbconfig *fbconfig)
VkResult _glfwPlatformCreateWindowSurface (VkInstance instance, _GLFWwindow *window, const VkAllocationCallbacks *allocator, VkSurfaceKHR *surface)
void _glfwPlatformDestroyCursor (_GLFWcursor *cursor)
void _glfwPlatformDestroyWindow (_GLFWwindow *window)
void _glfwPlatformFocusWindow (_GLFWwindow *window)
int _glfwPlatformFramebufferTransparent (_GLFWwindow *window)
const char * _glfwPlatformGetClipboardString (void)
void _glfwPlatformGetCursorPos (_GLFWwindow *window, double *xpos, double *ypos)
void _glfwPlatformGetFramebufferSize (_GLFWwindow *window, int *width, int *height)
int _glfwPlatformGetKeyScancode (int key)
int _glfwPlatformGetPhysicalDevicePresentationSupport (VkInstance instance, VkPhysicalDevice device, uint32_t queuefamily)
void _glfwPlatformGetRequiredInstanceExtensions (char **extensions)
const char * _glfwPlatformGetScancodeName (int scancode)
void _glfwPlatformGetWindowContentScale (_GLFWwindow *window, float *xscale, float *yscale)
void _glfwPlatformGetWindowFrameSize (_GLFWwindow *window, int *left, int *top, int *right, int *bottom)
float _glfwPlatformGetWindowOpacity (_GLFWwindow *window)
void _glfwPlatformGetWindowPos (_GLFWwindow *window, int *xpos, int *ypos)
void _glfwPlatformGetWindowSize (_GLFWwindow *window, int *width, int *height)
void _glfwPlatformHideWindow (_GLFWwindow *window)
void _glfwPlatformIconifyWindow (_GLFWwindow *window)
void _glfwPlatformMaximizeWindow (_GLFWwindow *window)
void _glfwPlatformPollEvents (void)
void _glfwPlatformPostEmptyEvent (void)
void _glfwPlatformRequestWindowAttention (_GLFWwindow *window)
void _glfwPlatformRestoreWindow (_GLFWwindow *window)
void _glfwPlatformSetClipboardString (const char *string)
void _glfwPlatformSetCursor (_GLFWwindow *window, _GLFWcursor *cursor)
void _glfwPlatformSetCursorMode (_GLFWwindow *window, int mode)
void _glfwPlatformSetCursorPos (_GLFWwindow *window, double x, double y)
void _glfwPlatformSetWindowAspectRatio (_GLFWwindow *window, int n, int d)
void _glfwPlatformSetWindowDecorated (_GLFWwindow *window, GLFWbool enabled)
void _glfwPlatformSetWindowFloating (_GLFWwindow *window, GLFWbool enabled)
void _glfwPlatformSetWindowIcon (_GLFWwindow *window, int count, const GLFWimage *images)
void _glfwPlatformSetWindowMonitor (_GLFWwindow *window, _GLFWmonitor *monitor, int xpos, int ypos, int width, int height, int refreshRate)
void _glfwPlatformSetWindowOpacity (_GLFWwindow *window, float opacity)
void _glfwPlatformSetWindowPos (_GLFWwindow *window, int xpos, int ypos)
void _glfwPlatformSetWindowResizable (_GLFWwindow *window, GLFWbool enabled)
void _glfwPlatformSetWindowSize (_GLFWwindow *window, int width, int height)
void _glfwPlatformSetWindowSizeLimits (_GLFWwindow *window, int minwidth, int minheight, int maxwidth, int maxheight)
void _glfwPlatformSetWindowTitle (_GLFWwindow *window, const char *title)
void _glfwPlatformShowWindow (_GLFWwindow *window)
void _glfwPlatformUnhideWindow (_GLFWwindow *window)
void _glfwPlatformWaitEvents (void)
void _glfwPlatformWaitEventsTimeout (double timeout)
int _glfwPlatformWindowFocused (_GLFWwindow *window)
int _glfwPlatformWindowHovered (_GLFWwindow *window)
int _glfwPlatformWindowIconified (_GLFWwindow *window)
int _glfwPlatformWindowMaximized (_GLFWwindow *window)
int _glfwPlatformWindowVisible (_GLFWwindow *window)
static int createNativeWindow (_GLFWwindow *window, const _GLFWwndconfig *wndconfig)
Function Documentation
createNativeWindow()
static int createNativeWindow (_GLFWwindow * window, const _GLFWwndconfig * wndconfig) static
References GLFW_TRUE, _GLFWwndconfig::height, and _GLFWwndconfig::width.
Referenced by _glfwPlatformCreateWindow().
_glfwPlatformCreateWindow()
int _glfwPlatformCreateWindow (_GLFWwindow * window, const _GLFWwndconfig * wndconfig, const _GLFWctxconfig * ctxconfig, const _GLFWfbconfig * fbconfig)
References _glfwCreateContextOSMesa(), _glfwInitOSMesa(), _glfwInputError(), _GLFWctxconfig::client, createNativeWindow(), GLFW_API_UNAVAILABLE, GLFW_FALSE, GLFW_NATIVE_CONTEXT_API, GLFW_NO_API, GLFW_OSMESA_CONTEXT_API, GLFW_TRUE, and _GLFWctxconfig::source.
_glfwPlatformDestroyWindow()
void _glfwPlatformDestroyWindow (_GLFWwindow * window)
References _GLFWwindow::context, and _GLFWcontext::destroy.
_glfwPlatformSetWindowTitle()
void _glfwPlatformSetWindowTitle (_GLFWwindow * window, const char * title)
_glfwPlatformSetWindowIcon()
void _glfwPlatformSetWindowIcon (_GLFWwindow * window, int count, const GLFWimage * images)
_glfwPlatformSetWindowMonitor()
void _glfwPlatformSetWindowMonitor (_GLFWwindow * window, _GLFWmonitor * monitor, int xpos, int ypos, int width, int height, int refreshRate)
_glfwPlatformGetWindowPos()
void _glfwPlatformGetWindowPos (_GLFWwindow * window, int * xpos, int * ypos)
_glfwPlatformSetWindowPos()
void _glfwPlatformSetWindowPos (_GLFWwindow * window, int xpos, int ypos)
_glfwPlatformGetWindowSize()
void _glfwPlatformGetWindowSize (_GLFWwindow * window, int * width, int * height)
References height, and width.
_glfwPlatformSetWindowSize()
void _glfwPlatformSetWindowSize (_GLFWwindow * window, int width, int height)
References height, and width.
_glfwPlatformSetWindowSizeLimits()
void _glfwPlatformSetWindowSizeLimits (_GLFWwindow * window, int minwidth, int minheight, int maxwidth, int maxheight)
_glfwPlatformSetWindowAspectRatio()
void _glfwPlatformSetWindowAspectRatio (_GLFWwindow * window, int n, int d)
_glfwPlatformGetFramebufferSize()
void _glfwPlatformGetFramebufferSize (_GLFWwindow * window, int * width, int * height)
References height, and width.
_glfwPlatformGetWindowFrameSize()
void _glfwPlatformGetWindowFrameSize (_GLFWwindow * window, int * left, int * top, int * right, int * bottom)
_glfwPlatformGetWindowContentScale()
void _glfwPlatformGetWindowContentScale (_GLFWwindow * window, float * xscale, float * yscale)
_glfwPlatformIconifyWindow()
void _glfwPlatformIconifyWindow (_GLFWwindow * window)
_glfwPlatformRestoreWindow()
void _glfwPlatformRestoreWindow (_GLFWwindow * window)
_glfwPlatformMaximizeWindow()
void _glfwPlatformMaximizeWindow (_GLFWwindow * window)
_glfwPlatformWindowMaximized()
int _glfwPlatformWindowMaximized (_GLFWwindow * window)
References GLFW_FALSE.
_glfwPlatformWindowHovered()
int _glfwPlatformWindowHovered (_GLFWwindow * window)
References GLFW_FALSE.
_glfwPlatformFramebufferTransparent()
int _glfwPlatformFramebufferTransparent (_GLFWwindow * window)
References GLFW_FALSE.
_glfwPlatformSetWindowResizable()
void _glfwPlatformSetWindowResizable (_GLFWwindow * window, GLFWbool enabled)
_glfwPlatformSetWindowDecorated()
void _glfwPlatformSetWindowDecorated (_GLFWwindow * window, GLFWbool enabled)
_glfwPlatformSetWindowFloating()
void _glfwPlatformSetWindowFloating (_GLFWwindow * window, GLFWbool enabled)
_glfwPlatformGetWindowOpacity()
float _glfwPlatformGetWindowOpacity (_GLFWwindow * window)
_glfwPlatformSetWindowOpacity()
void _glfwPlatformSetWindowOpacity (_GLFWwindow * window, float opacity)
_glfwPlatformShowWindow()
void _glfwPlatformShowWindow (_GLFWwindow * window)
_glfwPlatformRequestWindowAttention()
void _glfwPlatformRequestWindowAttention (_GLFWwindow * window)
_glfwPlatformUnhideWindow()
void _glfwPlatformUnhideWindow (_GLFWwindow * window)
_glfwPlatformHideWindow()
void _glfwPlatformHideWindow (_GLFWwindow * window)
_glfwPlatformFocusWindow()
void _glfwPlatformFocusWindow (_GLFWwindow * window)
_glfwPlatformWindowFocused()
int _glfwPlatformWindowFocused (_GLFWwindow * window)
References GLFW_FALSE.
_glfwPlatformWindowIconified()
int _glfwPlatformWindowIconified (_GLFWwindow * window)
References GLFW_FALSE.
_glfwPlatformWindowVisible()
int _glfwPlatformWindowVisible (_GLFWwindow * window)
References GLFW_FALSE.
_glfwPlatformPollEvents()
void _glfwPlatformPollEvents (void)
_glfwPlatformWaitEvents()
void _glfwPlatformWaitEvents (void)
_glfwPlatformWaitEventsTimeout()
void _glfwPlatformWaitEventsTimeout (double timeout)
_glfwPlatformPostEmptyEvent()
void _glfwPlatformPostEmptyEvent (void)
_glfwPlatformGetCursorPos()
void _glfwPlatformGetCursorPos (_GLFWwindow * window, double * xpos, double * ypos)
_glfwPlatformSetCursorPos()
void _glfwPlatformSetCursorPos (_GLFWwindow * window, double x, double y)
_glfwPlatformSetCursorMode()
void _glfwPlatformSetCursorMode (_GLFWwindow * window, int mode)
_glfwPlatformCreateCursor()
int _glfwPlatformCreateCursor (_GLFWcursor * cursor, const GLFWimage * image, int xhot, int yhot)
References GLFW_TRUE.
_glfwPlatformCreateStandardCursor()
int _glfwPlatformCreateStandardCursor (_GLFWcursor * cursor, int shape)
References GLFW_TRUE.
_glfwPlatformDestroyCursor()
void _glfwPlatformDestroyCursor (_GLFWcursor * cursor)
_glfwPlatformSetCursor()
void _glfwPlatformSetCursor (_GLFWwindow * window, _GLFWcursor * cursor)
_glfwPlatformSetClipboardString()
void _glfwPlatformSetClipboardString (const char * string)
_glfwPlatformGetClipboardString()
const char* _glfwPlatformGetClipboardString (void)
References NULL.
_glfwPlatformGetScancodeName()
const char* _glfwPlatformGetScancodeName (int scancode)
_glfwPlatformGetKeyScancode()
int _glfwPlatformGetKeyScancode (int key)
_glfwPlatformGetRequiredInstanceExtensions()
void _glfwPlatformGetRequiredInstanceExtensions (char ** extensions)
_glfwPlatformGetPhysicalDevicePresentationSupport()
int _glfwPlatformGetPhysicalDevicePresentationSupport (VkInstance instance, VkPhysicalDevice device, uint32_t queuefamily)
References GLFW_FALSE.
_glfwPlatformCreateWindowSurface()
VkResult _glfwPlatformCreateWindowSurface (VkInstance instance, _GLFWwindow * window, const VkAllocationCallbacks * allocator, VkSurfaceKHR * surface)
References VK_ERROR_INITIALIZATION_FAILED.