Aurora Framework: internal Namespace Reference
internal Namespace Reference
Classes
class BigInteger
class DecodedStream
struct DiyFp
class Double
class GenericRegex
Regular expression engine with subset of ECMAscript grammar.
class GenericRegexSearch
class Hasher
class ISchemaStateFactory
class ISchemaValidator
struct IsGenericValue
struct IsGenericValueImpl
struct IsGenericValueImpl< T, typename Void< typename T::EncodingType >::Type, typename Void< typename T::AllocatorType >::Type >
class IValidationErrorHandler
class Schema
struct SchemaValidationContext
class Stack
A type-unsafe stack for storing different types of data.
class StreamLocalCopy
class StreamLocalCopy< Stream, 0 >
Keep reference.
class StreamLocalCopy< Stream, 1 >
Do copy optimization.
struct TokenHelper
struct TokenHelper< Stack, char >
struct TypeHelper
struct TypeHelper< ValueType, bool >
struct TypeHelper< ValueType, const typename ValueType::Ch * >
struct TypeHelper< ValueType, double >
struct TypeHelper< ValueType, float >
struct TypeHelper< ValueType, int >
struct TypeHelper< ValueType, int64_t >
struct TypeHelper< ValueType, typename ValueType::Array >
struct TypeHelper< ValueType, typename ValueType::ConstArray >
struct TypeHelper< ValueType, typename ValueType::ConstObject >
struct TypeHelper< ValueType, typename ValueType::Object >
struct TypeHelper< ValueType, uint64_t >
struct TypeHelper< ValueType, unsigned >
Typedefs
typedef GenericRegex< UTF8<> > Regex
typedef GenericRegexSearch< Regex > RegexSearch
Functions
int CheckWithinHalfULP (double b, const BigInteger &d, int dExp)
int CountDecimalDigit32 (uint32_t n)
template<typename Encoding >
bool CountStringCodePoint (const typename Encoding::Ch *s, SizeType length, SizeType *outCount)
Returns number of code points in a encoded string.
void DigitGen (const DiyFp &W, const DiyFp &Mp, uint64_t delta, char *buffer, int *len, int *K)
char * dtoa (double value, char *buffer, int maxDecimalPlaces=324)
double FastPath (double significand, int exp)
DiyFp GetCachedPower (int e, int *K)
DiyFp GetCachedPower10 (int exp, int *outExp)
DiyFp GetCachedPowerByIndex (size_t index)
const char * GetDigitsLut ()
void Grisu2 (double value, char *buffer, int *length, int *K)
void GrisuRound (char *buffer, int len, uint64_t delta, uint64_t rest, uint64_t ten_kappa, uint64_t wp_w)
char * i32toa (int32_t value, char *buffer)
char * i64toa (int64_t value, char *buffer)
template<typename T >
T Min3 (T a, T b, T c)
double Pow10 (int n)
Computes integer powers of 10 in double (10.0^n).
char * Prettify (char *buffer, int length, int k, int maxDecimalPlaces)
template<typename Ch >
SizeType StrLen (const Ch *s)
Custom strlen() which works on different character types.
template<>
SizeType StrLen (const char *s)
template<>
SizeType StrLen (const wchar_t *s)
double StrtodBigInteger (double approx, const char *decimals, size_t length, size_t decimalPosition, int exp)
bool StrtodDiyFp (const char *decimals, size_t length, size_t decimalPosition, int exp, double *result)
bool StrtodFast (double d, int p, double *result)
double StrtodFullPrecision (double d, int p, const char *decimals, size_t length, size_t decimalPosition, int exp)
double StrtodNormalPrecision (double d, int p)
template<typename T >
void Swap (T &a, T &b) RAPIDJSON_NOEXCEPT
Custom swap() to avoid dependency on C++ <algorithm> header.
char * u32toa (uint32_t value, char *buffer)
char * u64toa (uint64_t value, char *buffer)
char * WriteExponent (int K, char *buffer)
Variables
static const SizeType kRegexInvalidRange = ~SizeType(0)
static const SizeType kRegexInvalidState = ~SizeType(0)
Represents an invalid index in GenericRegex::State::out, out1.
Typedef Documentation
Regex
typedef GenericRegex<UTF8<> > internal::Regex
RegexSearch
typedef GenericRegexSearch<Regex> internal::RegexSearch
Function Documentation
GetCachedPowerByIndex()
DiyFp internal::GetCachedPowerByIndex (size_t index) inline
References RAPIDJSON_UINT64_C2.
Referenced by GetCachedPower(), and GetCachedPower10().
GetCachedPower()
DiyFp internal::GetCachedPower (int e, int * K) inline
References GetCachedPowerByIndex().
Referenced by Grisu2().
GetCachedPower10()
DiyFp internal::GetCachedPower10 (int exp, int * outExp) inline
References GetCachedPowerByIndex().
Referenced by StrtodDiyFp().
GrisuRound()
void internal::GrisuRound (char * buffer, int len, uint64_t delta, uint64_t rest, uint64_t ten_kappa, uint64_t wp_w) inline
closer
Referenced by DigitGen().
CountDecimalDigit32()
int internal::CountDecimalDigit32 (uint32_t n) inline
Referenced by DigitGen().
DigitGen()
void internal::DigitGen (const DiyFp & W, const DiyFp & Mp, uint64_t delta, char * buffer, int * len, int * K) inline
References CountDecimalDigit32(), internal::DiyFp::e, internal::DiyFp::f, and GrisuRound().
Referenced by Grisu2().
Grisu2()
void internal::Grisu2 (double value, char * buffer, int * length, int * K) inline
References DigitGen(), internal::DiyFp::e, internal::DiyFp::f, GetCachedPower(), internal::DiyFp::Normalize(), internal::DiyFp::NormalizedBoundaries(), and value.
Referenced by dtoa().
WriteExponent()
char* internal::WriteExponent (int K, char * buffer) inline
References GetDigitsLut().
Referenced by Prettify().
Prettify()
char* internal::Prettify (char * buffer, int length, int k, int maxDecimalPlaces) inline
References memmove(), and WriteExponent().
Referenced by dtoa().
dtoa()
char* internal::dtoa (double value, char * buffer, int maxDecimalPlaces = 324) inline
References Grisu2(), internal::Double::IsZero(), Prettify(), RAPIDJSON_ASSERT, internal::Double::Sign(), and value.
Referenced by Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteDouble().
GetDigitsLut()
const char* internal::GetDigitsLut () inline
Referenced by u32toa(), u64toa(), and WriteExponent().
u32toa()
char* internal::u32toa (uint32_t value, char * buffer) inline
References a, GetDigitsLut(), RAPIDJSON_ASSERT, and value.
Referenced by internal::TokenHelper< Stack, Ch >::AppendIndexToken(), internal::TokenHelper< Stack, char >::AppendIndexToken(), i32toa(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteUint().
i32toa()
char* internal::i32toa (int32_t value, char * buffer) inline
References RAPIDJSON_ASSERT, u32toa(), and value.
Referenced by Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteInt().
u64toa()
char* internal::u64toa (uint64_t value, char * buffer) inline
References a, GetDigitsLut(), RAPIDJSON_ASSERT, and value.
Referenced by internal::TokenHelper< Stack, Ch >::AppendIndexToken(), internal::TokenHelper< Stack, char >::AppendIndexToken(), i64toa(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteUint64().
i64toa()
char* internal::i64toa (int64_t value, char * buffer) inline
References RAPIDJSON_ASSERT, u64toa(), and value.
Referenced by Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::WriteInt64().
Pow10()
double internal::Pow10 (int n) inline
Computes integer powers of 10 in double (10.0^n).
This function uses lookup table for fast and accurate results.
Parameters
n non-negative exponent. Must <= 308.
Returns
10.0^n
References RAPIDJSON_ASSERT.
Referenced by FastPath(), and StrtodFast().
StrLen() [1/3]
template<typename Ch > SizeType internal::StrLen (const Ch * s) inline
Custom strlen() which works on different character types.
Template Parameters
Ch Character type (e.g. char, wchar_t, short)
Parameters
s Null-terminated input string.
Returns
Number of characters in the string.
Note
This has the same semantics as strlen(), the return value is not number of Unicode codepoints.
References RAPIDJSON_ASSERT, and SizeType.
Referenced by GenericPointer< ValueType, Allocator >::GenericPointer(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Key(), Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::Key(), PrettyWriter< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String(), and Writer< OutputStream, SourceEncoding, TargetEncoding, StackAllocator, writeFlags >::String().
StrLen() [2/3]
template<> SizeType internal::StrLen (const char * s) inline
References SizeType.
StrLen() [3/3]
template<> SizeType internal::StrLen (const wchar_t * s) inline
References SizeType.
CountStringCodePoint()
template<typename Encoding > bool internal::CountStringCodePoint (const typename Encoding::Ch * s, SizeType length, SizeType * outCount)
Returns number of code points in a encoded string.
References RAPIDJSON_ASSERT, SizeType, and GenericStringStream< Encoding >::src_.
FastPath()
double internal::FastPath (double significand, int exp) inline
References Pow10().
Referenced by StrtodFast(), and StrtodNormalPrecision().
StrtodNormalPrecision()
double internal::StrtodNormalPrecision (double d, int p) inline
References FastPath().
Min3()
template<typename T > T internal::Min3 (T a, T b, T c) inline
References a.
Referenced by CheckWithinHalfULP().
CheckWithinHalfULP()
int internal::CheckWithinHalfULP (double b, const BigInteger & d, int dExp) inline
References internal::BigInteger::Compare(), internal::BigInteger::Difference(), internal::Double::IntegerExponent(), internal::Double::IntegerSignificand(), Min3(), and internal::BigInteger::MultiplyPow5().
Referenced by StrtodBigInteger().
StrtodFast()
bool internal::StrtodFast (double d, int p, double * result) inline
References FastPath(), and Pow10().
Referenced by StrtodFullPrecision().
StrtodDiyFp()
bool internal::StrtodDiyFp (const char * decimals, size_t length, size_t decimalPosition, int exp, double * result) inline
References internal::DiyFp::e, internal::Double::EffectiveSignificandSize(), internal::DiyFp::f, GetCachedPower10(), internal::DiyFp::kDpHiddenBit, internal::DiyFp::Normalize(), RAPIDJSON_ASSERT, RAPIDJSON_UINT64_C2, and internal::DiyFp::ToDouble().
Referenced by StrtodFullPrecision().
StrtodBigInteger()
double internal::StrtodBigInteger (double approx, const char * decimals, size_t length, size_t decimalPosition, int exp) inline
References a, and CheckWithinHalfULP().
Referenced by StrtodFullPrecision().
StrtodFullPrecision()
double internal::StrtodFullPrecision (double d, int p, const char * decimals, size_t length, size_t decimalPosition, int exp) inline
References RAPIDJSON_ASSERT, StrtodBigInteger(), StrtodDiyFp(), and StrtodFast().
Swap()
template<typename T > void internal::Swap (T & a, T & b) inline
Custom swap() to avoid dependency on C++ <algorithm> header.
Template Parameters
T Type of the arguments to swap, should be instantiated with primitive C++ types only.
Note
This has the same semantics as std::swap().
References a.
Referenced by internal::Stack< StackAllocator >::Swap(), GenericDocument< Encoding, Allocator, StackAllocator >::Swap(), and SwapValueByPointer().
Variable Documentation
kRegexInvalidState
const SizeType internal::kRegexInvalidState = ~SizeType(0) static
Represents an invalid index in GenericRegex::State::out, out1.
Referenced by internal::GenericRegex< Encoding, Allocator >::IsValid().
kRegexInvalidRange
const SizeType internal::kRegexInvalidRange = ~SizeType(0) static