Aurora Framework: spirv_cross::Compiler Class Reference
spirv_cross::Compiler Class Reference
Classes
struct ActiveBuiltinHandler
struct BufferAccessHandler
struct CombinedImageSamplerHandler
struct CombinedImageSamplerUsageHandler
struct DummySamplerForCombinedImageHandler
struct InterfaceVariableAccessHandler
struct OpcodeHandler
struct Source
Public Member Functions
Compiler (std::vector< uint32_t > ir)
Compiler (const uint32_t *ir, size_t word_count)
virtual ~Compiler ()=default
bool buffer_get_hlsl_counter_buffer (uint32_t id, uint32_t &counter_id) const
bool buffer_is_hlsl_counter_buffer (uint32_t id) const
void build_combined_image_samplers ()
uint32_t build_dummy_sampler_for_combined_images ()
virtual std::string compile ()
std::vector< BufferRange > get_active_buffer_ranges (uint32_t id) const
std::unordered_set< uint32_t > get_active_interface_variables () const
bool get_binary_offset_for_decoration (uint32_t id, spv::Decoration decoration, uint32_t &word_offset) const
virtual const std::string get_block_fallback_name (uint32_t id) const
const std::string & get_cleansed_entry_point_name (const std::string &name, spv::ExecutionModel execution_model) const
const std::vector< CombinedImageSampler > & get_combined_image_samplers () const
SPIRConstant & get_constant (uint32_t id)
const SPIRConstant & get_constant (uint32_t id) const
uint32_t get_current_id_bound () const
const std::vector< spv::Capability > & get_declared_capabilities () const
const std::vector< std::string > & get_declared_extensions () const
virtual size_t get_declared_struct_member_size (const SPIRType &struct_type, uint32_t index) const
size_t get_declared_struct_size (const SPIRType &struct_type) const
uint32_t get_decoration (uint32_t id, spv::Decoration decoration) const
const Bitset & get_decoration_bitset (uint32_t id) const
uint64_t get_decoration_mask (uint32_t id) const
SPIREntryPoint & get_entry_point (const std::string &name)
const SPIREntryPoint & get_entry_point (const std::string &name, spv::ExecutionModel execution_model) const
SPIREntryPoint & get_entry_point (const std::string &name, spv::ExecutionModel execution_model)
std::vector< std::string > get_entry_points () const
uint32_t get_execution_mode_argument (spv::ExecutionMode mode, uint32_t index=0) const
const Bitset & get_execution_mode_bitset () const
uint64_t get_execution_mode_mask () const
spv::ExecutionModel get_execution_model () const
virtual const std::string get_fallback_member_name (uint32_t index) const
virtual const std::string get_fallback_name (uint32_t id) const
uint32_t get_member_decoration (uint32_t id, uint32_t index, spv::Decoration decoration) const
const Bitset & get_member_decoration_bitset (uint32_t id, uint32_t index) const
uint64_t get_member_decoration_mask (uint32_t id, uint32_t index) const
const std::string & get_member_name (uint32_t id, uint32_t index) const
const std::string & get_member_qualified_name (uint32_t type_id, uint32_t index) const
const std::string & get_name (uint32_t id) const
std::string get_remapped_declared_block_name (uint32_t id) const
bool get_remapped_variable_state (uint32_t id) const
ShaderResources get_shader_resources () const
ShaderResources get_shader_resources (const std::unordered_set< uint32_t > &active_variables) const
std::vector< SpecializationConstant > get_specialization_constants () const
spv::StorageClass get_storage_class (uint32_t id) const
uint32_t get_subpass_input_remapped_components (uint32_t id) const
const SPIRType & get_type (uint32_t id) const
const SPIRType & get_type_from_variable (uint32_t id) const
uint32_t get_work_group_size_specialization_constants (SpecializationConstant &x, SpecializationConstant &y, SpecializationConstant &z) const
bool has_decoration (uint32_t id, spv::Decoration decoration) const
bool has_member_decoration (uint32_t id, uint32_t index, spv::Decoration decoration) const
void rename_entry_point (const std::string &old_name, const std::string &new_name, spv::ExecutionModel execution_model)
void set_decoration (uint32_t id, spv::Decoration decoration, uint32_t argument=0)
void set_enabled_interface_variables (std::unordered_set< uint32_t > active_variables)
void set_entry_point (const std::string &name)
void set_entry_point (const std::string &entry, spv::ExecutionModel execution_model)
void set_execution_mode (spv::ExecutionMode mode, uint32_t arg0=0, uint32_t arg1=0, uint32_t arg2=0)
void set_member_decoration (uint32_t id, uint32_t index, spv::Decoration decoration, uint32_t argument=0)
void set_member_name (uint32_t id, uint32_t index, const std::string &name)
void set_member_qualified_name (uint32_t type_id, uint32_t index, const std::string &name)
void set_name (uint32_t id, const std::string &name)
void set_remapped_variable_state (uint32_t id, bool remap_enable)
void set_subpass_input_remapped_components (uint32_t id, uint32_t components)
void set_variable_type_remap_callback (VariableTypeRemapCallback cb)
SPIRV_CROSS_DEPRECATED ("Please use flatten_buffer_block instead.") void flatten_interface_block(uint32_t id)
uint32_t type_struct_member_array_stride (const SPIRType &type, uint32_t index) const
uint32_t type_struct_member_matrix_stride (const SPIRType &type, uint32_t index) const
uint32_t type_struct_member_offset (const SPIRType &type, uint32_t index) const
void unset_decoration (uint32_t id, spv::Decoration decoration)
void unset_execution_mode (spv::ExecutionMode mode)
void unset_member_decoration (uint32_t id, uint32_t index, spv::Decoration decoration)
Public Attributes
SPIRV_CROSS_DEPRECATED("Please use rename_entry_point(const std::string&, const std::string&, spv::ExecutionModel) instead.") void rename_entry_point(const std const SPIREntryPoint & get_entry_point (const std::string &name) const
SPIRV_CROSS_DEPRECATED("Please use get_cleansed_entry_point_name(const std::string &, spv::ExecutionModel) instead.") const std std::vector< EntryPoint > get_entry_points_and_stages () const
Protected Member Functions
void analyze_image_and_sampler_usage ()
void analyze_parameter_preservation (SPIRFunction &entry, const CFG &cfg, const std::unordered_map< uint32_t, std::unordered_set< uint32_t >> &variable_to_blocks, const std::unordered_map< uint32_t, std::unordered_set< uint32_t >> &complete_write_blocks)
void analyze_variable_scope (SPIRFunction &function)
bool block_is_loop_candidate (const SPIRBlock &block, SPIRBlock::Method method) const
bool block_is_outside_flow_control_from_block (const SPIRBlock &from, const SPIRBlock &to)
bool block_is_pure (const SPIRBlock &block)
SPIRBlock::ContinueBlockType continue_block_type (const SPIRBlock &continue_block) const
bool execution_is_branchless (const SPIRBlock &from, const SPIRBlock &to) const
bool execution_is_noop (const SPIRBlock &from, const SPIRBlock &to) const
bool expression_is_lvalue (uint32_t id) const
const SPIRType & expression_type (uint32_t id) const
uint32_t expression_type_id (uint32_t id) const
void flush_all_active_variables ()
void flush_all_aliased_variables ()
void flush_all_atomic_capable_variables ()
void flush_control_dependent_expressions (uint32_t block)
void flush_dependees (SPIRVariable &var)
bool function_is_pure (const SPIRFunction &func)
template<typename T >
T & get (uint32_t id)
template<typename T >
const T & get (uint32_t id) const
Bitset get_buffer_block_flags (const SPIRVariable &var)
bool get_common_basic_type (const SPIRType &type, SPIRType::BaseType &base_type)
const SPIREntryPoint & get_entry_point () const
SPIREntryPoint & get_entry_point ()
ShaderResources get_shader_resources (const std::unordered_set< uint32_t > *active_variables) const
bool has_active_builtin (spv::BuiltIn builtin, spv::StorageClass storage)
uint32_t increase_bound_by (uint32_t incr_amount)
void inherit_expression_dependencies (uint32_t dst, uint32_t source)
bool instruction_to_result_type (uint32_t &result_type, uint32_t &result_id, spv::Op op, const uint32_t *args, uint32_t length)
bool interface_variable_exists_in_entry_point (uint32_t id) const
bool is_array (const SPIRType &type) const
bool is_break (uint32_t next) const
bool is_builtin_variable (const SPIRVariable &var) const
bool is_conditional (uint32_t next) const
bool is_continue (uint32_t next) const
bool is_hidden_variable (const SPIRVariable &var, bool include_builtins=false) const
bool is_immutable (uint32_t id) const
bool is_loop_break (uint32_t next) const
bool is_matrix (const SPIRType &type) const
bool is_member_builtin (const SPIRType &type, uint32_t index, spv::BuiltIn *builtin) const
bool is_scalar (const SPIRType &type) const
bool is_single_block_loop (uint32_t next) const
bool is_vector (const SPIRType &type) const
void make_constant_null (uint32_t id, uint32_t type)
void mark_used_as_array_length (uint32_t id)
template<typename T >
T * maybe_get (uint32_t id)
template<typename T >
const T * maybe_get (uint32_t id) const
SPIRVariable * maybe_get_backing_variable (uint32_t chain)
void parse ()
void parse (const Instruction &i)
void register_global_read_dependencies (const SPIRBlock &func, uint32_t id)
void register_global_read_dependencies (const SPIRFunction &func, uint32_t id)
void register_read (uint32_t expr, uint32_t chain, bool forwarded)
void register_write (uint32_t chain)
void remap_variable_type_name (const SPIRType &type, const std::string &var_name, std::string &type_name) const
template<typename T , typename... P>
T & set (uint32_t id, P &&... args)
const uint32_t * stream (const Instruction &instr) const
virtual std::string to_name (uint32_t id, bool allow_alias=true) const
bool traverse_all_reachable_opcodes (const SPIRBlock &block, OpcodeHandler &handler) const
bool traverse_all_reachable_opcodes (const SPIRFunction &block, OpcodeHandler &handler) const
bool types_are_logically_equivalent (const SPIRType &a, const SPIRType &b) const
void update_active_builtins ()
void update_name_cache (std::unordered_set< std::string > &cache, std::string &name)
bool variable_storage_is_aliased (const SPIRVariable &var)
Protected Attributes
Bitset active_input_builtins
std::unordered_set< uint32_t > active_interface_variables
Bitset active_output_builtins
std::vector< uint32_t > aliased_variables
bool check_active_interface_variables = false
uint32_t clip_distance_count = 0
std::vector< CombinedImageSampler > combined_image_samplers
std::unordered_set< uint32_t > comparison_images
std::unordered_set< uint32_t > comparison_samplers
std::unordered_map< uint32_t, uint32_t > continue_block_to_loop_header
std::unordered_set< uint32_t > continue_blocks
uint32_t cull_distance_count = 0
SPIRBlock * current_block = nullptr
SPIRFunction * current_function = nullptr
std::unordered_map< uint32_t, std::string > declared_block_names
std::vector< spv::Capability > declared_capabilities
std::vector< std::string > declared_extensions
uint32_t dummy_sampler_id = 0
uint32_t entry_point = 0
std::unordered_map< uint32_t, SPIREntryPoint > entry_points
bool force_recompile = false
std::unordered_set< uint32_t > forced_temporaries
std::unordered_set< uint32_t > forwarded_temporaries
std::vector< uint32_t > global_struct_cache
std::vector< uint32_t > global_variables
std::unordered_set< uint32_t > hoisted_temporaries
std::vector< Variant > ids
std::vector< Instruction > inst
std::unordered_set< uint32_t > invalid_expressions
std::unordered_set< uint32_t > loop_blocks
std::unordered_set< uint32_t > loop_merge_targets
std::vector< Meta > meta
std::unordered_set< uint32_t > multiselect_merge_targets
bool need_subpass_input = false
bool position_invariant = false
std::unordered_set< uint32_t > selection_merge_targets
struct spirv_cross::Compiler::Source source
std::vector< uint32_t > spirv
VariableTypeRemapCallback variable_remap_callback
Constructor & Destructor Documentation
Compiler() [1/2]
spirv_cross::Compiler::Compiler (std::vector< uint32_t > ir)
Compiler() [2/2]
Compiler::Compiler (const uint32_t * ir, size_t word_count)
References parse().
~Compiler()
virtual spirv_cross::Compiler::~Compiler () virtual default
Member Function Documentation
compile()
string Compiler::compile () virtual
Reimplemented in spirv_cross::CompilerMSL, spirv_cross::CompilerGLSL, spirv_cross::CompilerHLSL, and spirv_cross::CompilerCPP.
get_name()
const std::string & Compiler::get_name (uint32_t id) const
References meta.
Referenced by spirv_cross::CompilerMSL::add_input_buffer_block_member(), buffer_get_hlsl_counter_buffer(), get_block_fallback_name(), and parse().
set_decoration()
void Compiler::set_decoration (uint32_t id, spv::Decoration decoration, uint32_t argument = 0)
References spv::DecorationArrayStride, spv::DecorationBinding, spv::DecorationBuiltIn, spv::DecorationDescriptorSet, spv::DecorationInputAttachmentIndex, spv::DecorationLocation, spv::DecorationMatrixStride, spv::DecorationOffset, spv::DecorationSpecId, and meta.
Referenced by spirv_cross::CompilerMSL::add_input_buffer_block_member(), spirv_cross::CompilerMSL::add_interface_block(), spirv_cross::CompilerMSL::build_implicit_builtins(), spirv_cross::CompilerMSL::get_input_buffer_block_var_id(), spirv_cross::CompilerMSL::mark_as_packable(), parse(), and AuroraFW::GEngine::RTShaderConverter::toGLSL().
set_name()
void Compiler::set_name (uint32_t id, const std::string & name)
References ensure_valid_identifier(), spirv_cross::Compiler::Source::hlsl, meta, setup::name, and source.
Referenced by spirv_cross::CompilerMSL::add_interface_block(), build_dummy_sampler_for_combined_images(), spirv_cross::CompilerMSL::extract_global_variables_from_function(), spirv_cross::CompilerMSL::get_input_buffer_block_var_id(), parse(), and spirv_cross_util::rename_interface_variable().
get_decoration_mask()
uint64_t Compiler::get_decoration_mask (uint32_t id) const
References get_decoration_bitset(), and spirv_cross::Bitset::get_lower().
get_decoration_bitset()
const Bitset & Compiler::get_decoration_bitset (uint32_t id) const
References meta.
Referenced by spirv_cross::CompilerMSL::add_interface_block(), get_decoration_mask(), and has_decoration().
has_decoration()
bool Compiler::has_decoration (uint32_t id, spv::Decoration decoration) const
References spirv_cross::Bitset::get(), and get_decoration_bitset().
Referenced by spirv_cross::CompilerMSL::add_interface_block(), buffer_get_hlsl_counter_buffer(), buffer_is_hlsl_counter_buffer(), spirv_cross::CompilerMSL::emit_resources(), spirv_cross::CompilerMSL::mark_packable_structs(), spirv_cross::CompilerMSL::move_to_input_buffer(), spirv_cross_util::rename_interface_variable(), and to_name().
get_decoration()
uint32_t Compiler::get_decoration (uint32_t id, spv::Decoration decoration) const
References spv::DecorationArrayStride, spv::DecorationBinding, spv::DecorationBuiltIn, spv::DecorationDescriptorSet, spv::DecorationInputAttachmentIndex, spv::DecorationLocation, spv::DecorationMatrixStride, spv::DecorationOffset, spv::DecorationSpecId, and meta.
Referenced by spirv_cross::CompilerMSL::add_interface_block(), get_specialization_constants(), get_work_group_size_specialization_constants(), spirv_cross::CompilerMSL::move_to_input_buffer(), spirv_cross_util::rename_interface_variable(), and AuroraFW::GEngine::RTShaderConverter::toGLSL().
unset_decoration()
void Compiler::unset_decoration (uint32_t id, spv::Decoration decoration)
References spv::DecorationBinding, spv::DecorationBuiltIn, spv::DecorationDescriptorSet, spv::DecorationInputAttachmentIndex, spv::DecorationLocation, spv::DecorationOffset, spv::DecorationSpecId, and meta.
Referenced by AuroraFW::GEngine::RTShaderConverter::toGLSL().
get_type()
const SPIRType & Compiler::get_type (uint32_t id) const
Referenced by spirv_cross::CompilerMSL::add_interface_block(), build_combined_image_samplers(), spirv_cross::CompilerMSL::build_implicit_builtins(), spirv_cross::CompilerMSL::declare_constant_arrays(), spirv_cross::CompilerMSL::declare_undefined_values(), spirv_cross::CompilerMSL::emit_resources(), expression_type_id(), spirv_cross::CompilerMSL::extract_global_variables_from_functions(), get_specialization_constants(), is_immutable(), spirv_cross::CompilerMSL::mark_packable_structs(), mark_used_as_array_length(), parse(), spirv_cross_util::rename_interface_variable(), and spirv_cross::CompilerMSL::resolve_specialized_array_lengths().
get_type_from_variable()
const SPIRType & Compiler::get_type_from_variable (uint32_t id) const
get_storage_class()
StorageClass Compiler::get_storage_class (uint32_t id) const
get_fallback_name()
const std::string Compiler::get_fallback_name (uint32_t id) const virtual
References spirv_cross::join().
get_block_fallback_name()
const std::string Compiler::get_block_fallback_name (uint32_t id) const virtual
References get_name(), and spirv_cross::join().
Referenced by get_remapped_declared_block_name().
get_member_name()
const std::string & Compiler::get_member_name (uint32_t id, uint32_t index) const
References meta.
get_member_decoration()
uint32_t Compiler::get_member_decoration (uint32_t id, uint32_t index, spv::Decoration decoration) const
References spv::DecorationBinding, spv::DecorationBuiltIn, spv::DecorationLocation, spv::DecorationOffset, spv::DecorationSpecId, and meta.
Referenced by spirv_cross::CompilerMSL::add_interface_block(), spirv_cross::CompilerMSL::align_struct(), spirv_cross::CompilerMSL::is_member_packable(), and spirv_cross::CompilerMSL::move_member_to_input_buffer().
set_member_name()
void Compiler::set_member_name (uint32_t id, uint32_t index, const std::string & name)
References ensure_valid_identifier(), afwstd::max(), meta, and setup::name.
Referenced by spirv_cross::CompilerMSL::add_input_buffer_block_member(), spirv_cross::CompilerMSL::add_interface_block(), parse(), and spirv_cross_util::rename_interface_variable().
get_member_qualified_name()
const std::string & Compiler::get_member_qualified_name (uint32_t type_id, uint32_t index) const
References meta.
set_member_qualified_name()
void Compiler::set_member_qualified_name (uint32_t type_id, uint32_t index, const std::string & name)
References afwstd::max(), meta, and setup::name.
Referenced by spirv_cross::CompilerMSL::add_interface_block(), and spirv_cross::CompilerMSL::move_member_to_input_buffer().
get_member_decoration_mask()
uint64_t Compiler::get_member_decoration_mask (uint32_t id, uint32_t index) const
References spirv_cross::Bitset::get_lower(), and get_member_decoration_bitset().
get_member_decoration_bitset()
const Bitset & Compiler::get_member_decoration_bitset (uint32_t id, uint32_t index) const
References meta.
Referenced by get_buffer_block_flags(), get_declared_struct_member_size(), get_member_decoration_mask(), and has_member_decoration().
has_member_decoration()
bool Compiler::has_member_decoration (uint32_t id, uint32_t index, spv::Decoration decoration) const
References spirv_cross::Bitset::get(), and get_member_decoration_bitset().
Referenced by spirv_cross::CompilerMSL::add_interface_block(), spirv_cross::CompilerMSL::is_member_packable(), and spirv_cross::CompilerMSL::move_member_to_input_buffer().
set_member_decoration()
void Compiler::set_member_decoration (uint32_t id, uint32_t index, spv::Decoration decoration, uint32_t argument = 0)
References spv::DecorationBinding, spv::DecorationBuiltIn, spv::DecorationLocation, spv::DecorationMatrixStride, spv::DecorationOffset, spv::DecorationSpecId, afwstd::max(), and meta.
Referenced by spirv_cross::CompilerMSL::add_input_buffer_block_member(), spirv_cross::CompilerMSL::add_interface_block(), spirv_cross::CompilerMSL::align_struct(), and parse().
unset_member_decoration()
void Compiler::unset_member_decoration (uint32_t id, uint32_t index, spv::Decoration decoration)
References spv::DecorationBuiltIn, spv::DecorationLocation, spv::DecorationOffset, spv::DecorationSpecId, and meta.
get_fallback_member_name()
virtual const std::string spirv_cross::Compiler::get_fallback_member_name (uint32_t index) const inline virtual
References spirv_cross::join().
get_active_buffer_ranges()
std::vector< BufferRange > Compiler::get_active_buffer_ranges (uint32_t id) const
References entry_point, and traverse_all_reachable_opcodes().
get_declared_struct_size()
size_t Compiler::get_declared_struct_size (const SPIRType & struct_type) const
References get_declared_struct_member_size(), spirv_cross::SPIRType::member_types, and type_struct_member_offset().
Referenced by get_declared_struct_member_size().
get_declared_struct_member_size()
size_t Compiler::get_declared_struct_member_size (const SPIRType & struct_type, uint32_t index) const virtual
Reimplemented in spirv_cross::CompilerMSL.
References spirv_cross::SPIRType::AtomicCounter, spirv_cross::SPIRType::Boolean, spv::DecorationColMajor, spv::DecorationRowMajor, get_declared_struct_size(), get_member_decoration_bitset(), spirv_cross::SPIRType::Image, spirv_cross::SPIRType::member_types, spirv_cross::SPIRType::SampledImage, spirv_cross::SPIRType::Sampler, spirv_cross::IVariant::self, SPIRV_CROSS_THROW, spirv_cross::SPIRType::Struct, type_struct_member_array_stride(), type_struct_member_matrix_stride(), spirv_cross::SPIRType::Unknown, and spirv_cross::SPIRType::Void.
Referenced by get_declared_struct_size().
SPIRV_CROSS_DEPRECATED()
spirv_cross::Compiler::SPIRV_CROSS_DEPRECATED ("Please use flatten_buffer_block instead.")
get_active_interface_variables()
unordered_set< uint32_t > Compiler::get_active_interface_variables () const
References dummy_sampler_id, entry_point, and traverse_all_reachable_opcodes().
Referenced by spirv_cross::CompilerMSL::compile().
set_enabled_interface_variables()
void Compiler::set_enabled_interface_variables (std::unordered_set< uint32_t > active_variables)
References active_interface_variables, and check_active_interface_variables.
Referenced by spirv_cross::CompilerMSL::compile().
get_shader_resources() [1/3]
ShaderResources Compiler::get_shader_resources () const
Referenced by AuroraFW::GEngine::RTShaderConverter::toGLSL().
get_shader_resources() [2/3]
ShaderResources spirv_cross::Compiler::get_shader_resources (const std::unordered_set< uint32_t > & active_variables) const
set_remapped_variable_state()
void Compiler::set_remapped_variable_state (uint32_t id, bool remap_enable)
get_remapped_variable_state()
bool Compiler::get_remapped_variable_state (uint32_t id) const
set_subpass_input_remapped_components()
void Compiler::set_subpass_input_remapped_components (uint32_t id, uint32_t components)
get_subpass_input_remapped_components()
uint32_t Compiler::get_subpass_input_remapped_components (uint32_t id) const
get_entry_points()
vector< string > Compiler::get_entry_points () const
References entry_points.
set_entry_point() [1/2]
void Compiler::set_entry_point (const std::string & name)
References entry_point, and setup::name.
get_entry_point() [1/5]
SPIREntryPoint& spirv_cross::Compiler::get_entry_point (const std::string & name)
set_entry_point() [2/2]
void Compiler::set_entry_point (const std::string & entry, spv::ExecutionModel execution_model)
References entry_point, get_entry_point(), and setup::name.
rename_entry_point()
void Compiler::rename_entry_point (const std::string & old_name, const std::string & new_name, spv::ExecutionModel execution_model)
get_entry_point() [2/5]
const SPIREntryPoint& spirv_cross::Compiler::get_entry_point (const std::string & name, spv::ExecutionModel execution_model) const
get_entry_point() [3/5]
SPIREntryPoint& spirv_cross::Compiler::get_entry_point (const std::string & name, spv::ExecutionModel execution_model)
get_cleansed_entry_point_name()
const string & Compiler::get_cleansed_entry_point_name (const std::string & name, spv::ExecutionModel execution_model) const
References setup::name, and spirv_cross::SPIREntryPoint::name.
get_execution_mode_mask()
uint64_t Compiler::get_execution_mode_mask () const
References spirv_cross::SPIREntryPoint::flags, get_entry_point(), and spirv_cross::Bitset::get_lower().
get_execution_mode_bitset()
const Bitset & Compiler::get_execution_mode_bitset () const
References spirv_cross::SPIREntryPoint::flags, and get_entry_point().
unset_execution_mode()
void Compiler::unset_execution_mode (spv::ExecutionMode mode)
References get_entry_point(), and mode().
set_execution_mode()
void Compiler::set_execution_mode (spv::ExecutionMode mode, uint32_t arg0 = 0, uint32_t arg1 = 0, uint32_t arg2 = 0)
References spv::ExecutionModeInvocations, spv::ExecutionModeLocalSize, spv::ExecutionModeOutputVertices, get_entry_point(), and mode().
get_execution_mode_argument()
uint32_t Compiler::get_execution_mode_argument (spv::ExecutionMode mode, uint32_t index = 0) const
References spv::ExecutionModeInvocations, spv::ExecutionModeLocalSize, spv::ExecutionModeOutputVertices, get_entry_point(), and mode().
get_execution_model()
ExecutionModel Compiler::get_execution_model () const
References get_entry_point().
get_work_group_size_specialization_constants()
uint32_t Compiler::get_work_group_size_specialization_constants (SpecializationConstant & x, SpecializationConstant & y, SpecializationConstant & z) const
References spirv_cross::SpecializationConstant::constant_id, spv::DecorationSpecId, get_decoration(), get_entry_point(), and spirv_cross::SpecializationConstant::id.
Referenced by spirv_cross::CompilerMSL::emit_specialization_constants().
build_dummy_sampler_for_combined_images()
uint32_t Compiler::build_dummy_sampler_for_combined_images ()
References spirv_cross::SPIRType::basetype, dummy_sampler_id, entry_point, increase_bound_by(), spirv_cross::Compiler::DummySamplerForCombinedImageHandler::need_dummy_sampler, spirv_cross::SPIRType::Sampler, set_name(), spv::StorageClassUniformConstant, and traverse_all_reachable_opcodes().
build_combined_image_samplers()
void Compiler::build_combined_image_samplers ()
References combined_image_samplers, spirv_cross::SPIRFunction::combined_parameters, entry_point, get_type(), ids, traverse_all_reachable_opcodes(), and spirv_cross::TypeFunction.
get_combined_image_samplers()
const std::vector<CombinedImageSampler>& spirv_cross::Compiler::get_combined_image_samplers () const inline
References combined_image_samplers.
set_variable_type_remap_callback()
void spirv_cross::Compiler::set_variable_type_remap_callback (VariableTypeRemapCallback cb) inline
References variable_remap_callback.
get_specialization_constants()
vector< SpecializationConstant > Compiler::get_specialization_constants () const
References spv::DecorationSpecId, get_decoration(), get_type(), ids, and spirv_cross::TypeConstant.
Referenced by spirv_cross::CompilerMSL::emit_specialization_constants().
get_constant() [1/2]
SPIRConstant & Compiler::get_constant (uint32_t id)
get_constant() [2/2]
const SPIRConstant & Compiler::get_constant (uint32_t id) const
get_current_id_bound()
uint32_t spirv_cross::Compiler::get_current_id_bound () const inline
References ids.
Referenced by buffer_get_hlsl_counter_buffer(), and spirv_cross::CFG::CFG().
type_struct_member_offset()
uint32_t Compiler::type_struct_member_offset (const SPIRType & type, uint32_t index) const
References spv::DecorationOffset, meta, spirv_cross::IVariant::self, and SPIRV_CROSS_THROW.
Referenced by get_declared_struct_size().
type_struct_member_array_stride()
uint32_t Compiler::type_struct_member_array_stride (const SPIRType & type, uint32_t index) const
References spv::DecorationArrayStride, spirv_cross::SPIRType::member_types, meta, and SPIRV_CROSS_THROW.
Referenced by get_declared_struct_member_size(), and spirv_cross::CompilerMSL::is_member_packable().
type_struct_member_matrix_stride()
uint32_t Compiler::type_struct_member_matrix_stride (const SPIRType & type, uint32_t index) const
References spv::DecorationMatrixStride, meta, spirv_cross::IVariant::self, and SPIRV_CROSS_THROW.
Referenced by get_declared_struct_member_size().
get_binary_offset_for_decoration()
bool Compiler::get_binary_offset_for_decoration (uint32_t id, spv::Decoration decoration, uint32_t & word_offset) const
References meta.
buffer_is_hlsl_counter_buffer()
bool Compiler::buffer_is_hlsl_counter_buffer (uint32_t id) const
References spv::DecorationBufferBlock, has_decoration(), meta, and spv::StorageClassStorageBuffer.
buffer_get_hlsl_counter_buffer()
bool Compiler::buffer_get_hlsl_counter_buffer (uint32_t id, uint32_t & counter_id) const
References spv::DecorationBufferBlock, get_current_id_bound(), get_name(), has_decoration(), meta, setup::name, and spv::StorageClassStorageBuffer.
get_declared_capabilities()
const std::vector< spv::Capability > & Compiler::get_declared_capabilities () const
References declared_capabilities.
get_declared_extensions()
const std::vector< std::string > & Compiler::get_declared_extensions () const
References declared_extensions.
get_remapped_declared_block_name()
std::string Compiler::get_remapped_declared_block_name (uint32_t id) const
References declared_block_names, get_block_fallback_name(), and meta.
stream()
const uint32_t* spirv_cross::Compiler::stream (const Instruction & instr) const inline protected
References spirv_cross::Instruction::length, spirv_cross::Instruction::offset, spirv, and SPIRV_CROSS_THROW.
Referenced by block_is_pure(), spirv_cross::CompilerMSL::extract_global_variables_from_function(), parse(), register_global_read_dependencies(), and traverse_all_reachable_opcodes().
set()
template<typename T , typename... P> T& spirv_cross::Compiler::set (uint32_t id, P &&... args) inline protected
References ids.
get() [1/2]
template<typename T > T& spirv_cross::Compiler::get (uint32_t id) inline protected
References ids.
Referenced by spirv_cross::Compiler::InterfaceVariableAccessHandler::handle(), and spirv_cross::DominatorBuilder::lift_continue_block_dominator().
maybe_get() [1/2]
template<typename T > T* spirv_cross::Compiler::maybe_get (uint32_t id) inline protected
References ids.
Referenced by spirv_cross::Compiler::InterfaceVariableAccessHandler::handle().
get() [2/2]
template<typename T > const T& spirv_cross::Compiler::get (uint32_t id) const inline protected
References ids.
maybe_get() [2/2]
template<typename T > const T* spirv_cross::Compiler::maybe_get (uint32_t id) const inline protected
References ids.
get_entry_point() [4/5]
const SPIREntryPoint& spirv_cross::Compiler::get_entry_point () const protected
Referenced by spirv_cross::CompilerMSL::add_interface_block(), get_execution_mode_argument(), get_execution_mode_bitset(), get_execution_mode_mask(), get_execution_model(), get_work_group_size_specialization_constants(), interface_variable_exists_in_entry_point(), spirv_cross::CompilerMSL::mark_location_as_used_by_shader(), set_entry_point(), set_execution_mode(), spirv_cross::CompilerMSL::should_move_to_input_buffer(), and unset_execution_mode().
get_entry_point() [5/5]
SPIREntryPoint& spirv_cross::Compiler::get_entry_point () protected
to_name()
string Compiler::to_name (uint32_t id, bool allow_alias = true) const protected virtual
Reimplemented in spirv_cross::CompilerMSL.
References spv::DecorationCPacked, has_decoration(), ids, spirv_cross::join(), meta, and spirv_cross::TypeType.
is_builtin_variable()
bool Compiler::is_builtin_variable (const SPIRVariable & var) const protected
References spirv_cross::SPIRVariable::basetype, spirv_cross::SPIRVariable::compat_builtin, meta, and spirv_cross::IVariant::self.
Referenced by spirv_cross::CompilerMSL::add_interface_block(), and is_hidden_variable().
is_hidden_variable()
bool Compiler::is_hidden_variable (const SPIRVariable & var, bool include_builtins = false) const protected
References active_interface_variables, check_active_interface_variables, spirv_cross::CombinedImageSampler::combined_id, combined_image_samplers, is_builtin_variable(), spirv_cross::SPIRVariable::remapped_variable, spirv_cross::IVariant::self, spirv_cross::SPIRVariable::storage, and storage_class_is_interface().
Referenced by spirv_cross::CompilerMSL::add_interface_block(), and spirv_cross::CompilerMSL::mark_packable_structs().
is_immutable()
bool Compiler::is_immutable (uint32_t id) const protected
References expression_is_lvalue(), get_type(), ids, spv::StorageClassUniformConstant, spirv_cross::TypeAccessChain, spirv_cross::TypeConstant, spirv_cross::TypeConstantOp, spirv_cross::TypeExpression, spirv_cross::TypeUndef, and spirv_cross::TypeVariable.
Referenced by register_read().
is_member_builtin()
bool Compiler::is_member_builtin (const SPIRType & type, uint32_t index, spv::BuiltIn * builtin) const protected
References meta, and spirv_cross::IVariant::self.
Referenced by spirv_cross::CompilerMSL::add_interface_block().
is_scalar()
bool Compiler::is_scalar (const SPIRType & type) const protected
References spirv_cross::SPIRType::columns, and spirv_cross::SPIRType::vecsize.
is_vector()
bool Compiler::is_vector (const SPIRType & type) const protected
References spirv_cross::SPIRType::columns, and spirv_cross::SPIRType::vecsize.
is_matrix()
bool Compiler::is_matrix (const SPIRType & type) const protected
References spirv_cross::SPIRType::columns, and spirv_cross::SPIRType::vecsize.
Referenced by spirv_cross::CompilerMSL::is_member_packable(), and spirv_cross::CompilerMSL::should_move_to_input_buffer().
is_array()
bool Compiler::is_array (const SPIRType & type) const protected
References spirv_cross::SPIRType::array.
Referenced by spirv_cross::CompilerMSL::ensure_correct_builtin_type(), spirv_cross::CompilerMSL::is_member_packable(), and spirv_cross::CompilerMSL::should_move_to_input_buffer().
expression_type_id()
uint32_t Compiler::expression_type_id (uint32_t id) const protected
References expression_type(), get_type(), ids, SPIRV_CROSS_THROW, spirv_cross::TypeAccessChain, spirv_cross::TypeCombinedImageSampler, spirv_cross::TypeConstant, spirv_cross::TypeConstantOp, spirv_cross::TypeExpression, spirv_cross::TypeUndef, and spirv_cross::TypeVariable.
Referenced by expression_type().
expression_type()
const SPIRType & Compiler::expression_type (uint32_t id) const protected
References expression_type_id().
Referenced by analyze_variable_scope(), block_is_pure(), spirv_cross::CompilerMSL::emit_specialization_constants(), expression_is_lvalue(), and expression_type_id().
expression_is_lvalue()
bool Compiler::expression_is_lvalue (uint32_t id) const protected
References expression_type(), spirv_cross::SPIRType::Image, spirv_cross::SPIRType::SampledImage, and spirv_cross::SPIRType::Sampler.
Referenced by is_immutable().
variable_storage_is_aliased()
bool Compiler::variable_storage_is_aliased (const SPIRVariable & var) protected
References spirv_cross::SPIRType::AtomicCounter, spirv_cross::SPIRVariable::basetype, spv::DecorationBufferBlock, spv::DecorationRestrict, spirv_cross::SPIRType::Image, meta, spirv_cross::IVariant::self, spirv_cross::SPIRVariable::storage, and spv::StorageClassStorageBuffer.
Referenced by parse(), and register_write().
maybe_get_backing_variable()
SPIRVariable * Compiler::maybe_get_backing_variable (uint32_t chain) protected
Referenced by register_global_read_dependencies(), and register_read().
mark_used_as_array_length()
void Compiler::mark_used_as_array_length (uint32_t id) protected
References get_type(), ids, SPIRV_CROSS_THROW, spirv_cross::TypeConstant, spirv_cross::TypeConstantOp, and spirv_cross::TypeUndef.
Referenced by parse().
register_read()
void Compiler::register_read (uint32_t expr, uint32_t chain, bool forwarded) protected
References is_immutable(), and maybe_get_backing_variable().
register_write()
void Compiler::register_write (uint32_t chain) protected
References flush_all_aliased_variables(), flush_dependees(), force_recompile, and variable_storage_is_aliased().
is_continue()
bool spirv_cross::Compiler::is_continue (uint32_t next) const inline protected
References continue_blocks.
Referenced by analyze_variable_scope(), and block_is_outside_flow_control_from_block().
is_single_block_loop()
bool spirv_cross::Compiler::is_single_block_loop (uint32_t next) const inline protected
References spirv_cross::SPIRBlock::MergeLoop.
Referenced by analyze_variable_scope().
is_break()
bool spirv_cross::Compiler::is_break (uint32_t next) const inline protected
References loop_merge_targets, and multiselect_merge_targets.
is_loop_break()
bool spirv_cross::Compiler::is_loop_break (uint32_t next) const inline protected
References loop_merge_targets.
is_conditional()
bool spirv_cross::Compiler::is_conditional (uint32_t next) const inline protected
References multiselect_merge_targets, and selection_merge_targets.
flush_dependees()
void Compiler::flush_dependees (SPIRVariable & var) protected
References spirv_cross::SPIRVariable::dependees, and invalid_expressions.
Referenced by flush_all_active_variables(), flush_all_aliased_variables(), flush_all_atomic_capable_variables(), and register_write().
flush_all_active_variables()
void Compiler::flush_all_active_variables () protected
References spirv_cross::SPIRFunction::arguments, current_function, flush_all_aliased_variables(), flush_dependees(), global_variables, and spirv_cross::SPIRFunction::local_variables.
flush_control_dependent_expressions()
void Compiler::flush_control_dependent_expressions (uint32_t block) protected
References invalid_expressions.
flush_all_atomic_capable_variables()
void Compiler::flush_all_atomic_capable_variables () protected
References flush_all_aliased_variables(), flush_dependees(), and global_variables.
flush_all_aliased_variables()
void Compiler::flush_all_aliased_variables () protected
References aliased_variables, and flush_dependees().
Referenced by flush_all_active_variables(), flush_all_atomic_capable_variables(), and register_write().
register_global_read_dependencies() [1/2]
void Compiler::register_global_read_dependencies (const SPIRBlock & func, uint32_t id) protected
References spv::DimSubpassData, spirv_cross::SPIRType::Image, maybe_get_backing_variable(), spv::OpFunctionCall, spv::OpImageRead, spv::OpLoad, spirv_cross::SPIRBlock::ops, spv::StorageClassFunction, and stream().
Referenced by register_global_read_dependencies().
register_global_read_dependencies() [2/2]
void Compiler::register_global_read_dependencies (const SPIRFunction & func, uint32_t id) protected
References spirv_cross::SPIRFunction::blocks, and register_global_read_dependencies().
update_name_cache()
void Compiler::update_name_cache (std::unordered_set< std::string > & cache, std::string & name) protected
References spirv_cross::convert_to_string(), and setup::name.
function_is_pure()
bool Compiler::function_is_pure (const SPIRFunction & func) protected
References block_is_pure(), and spirv_cross::SPIRFunction::blocks.
Referenced by block_is_pure().
block_is_pure()
bool Compiler::block_is_pure (const SPIRBlock & block) protected
References expression_type(), function_is_pure(), spv::OpAtomicAnd, spv::OpAtomicCompareExchange, spv::OpAtomicCompareExchangeWeak, spv::OpAtomicExchange, spv::OpAtomicIAdd, spv::OpAtomicIDecrement, spv::OpAtomicIIncrement, spv::OpAtomicISub, spv::OpAtomicLoad, spv::OpAtomicOr, spv::OpAtomicSMax, spv::OpAtomicSMin, spv::OpAtomicStore, spv::OpAtomicUMax, spv::OpAtomicUMin, spv::OpAtomicXor, spv::OpControlBarrier, spv::OpCopyMemory, spv::OpEmitStreamVertex, spv::OpEmitVertex, spv::OpEndPrimitive, spv::OpEndStreamPrimitive, spv::OpFunctionCall, spv::OpImageWrite, spv::OpMemoryBarrier, spirv_cross::SPIRBlock::ops, spv::OpStore, spv::StorageClassFunction, and stream().
Referenced by function_is_pure().
block_is_outside_flow_control_from_block()
bool Compiler::block_is_outside_flow_control_from_block (const SPIRBlock & from, const SPIRBlock & to) protected
References is_continue(), spirv_cross::SPIRBlock::MergeNone, spirv_cross::SPIRBlock::Select, and spirv_cross::IVariant::self.
execution_is_branchless()
bool Compiler::execution_is_branchless (const SPIRBlock & from, const SPIRBlock & to) const protected
References spirv_cross::SPIRBlock::Direct, spirv_cross::SPIRBlock::MergeNone, and spirv_cross::IVariant::self.
Referenced by continue_block_type(), and execution_is_noop().
execution_is_noop()
bool Compiler::execution_is_noop (const SPIRBlock & from, const SPIRBlock & to) const protected
References execution_is_branchless(), and spirv_cross::IVariant::self.
Referenced by continue_block_type().
continue_block_type()
SPIRBlock::ContinueBlockType Compiler::continue_block_type (const SPIRBlock & continue_block) const protected
References spirv_cross::SPIRBlock::complex_continue, spirv_cross::SPIRBlock::ComplexLoop, spirv_cross::SPIRBlock::DoWhileLoop, execution_is_branchless(), execution_is_noop(), spirv_cross::SPIRBlock::false_block, spirv_cross::SPIRBlock::ForLoop, spirv_cross::SPIRBlock::loop_dominator, spirv_cross::SPIRBlock::merge, spirv_cross::SPIRBlock::MergeLoop, spirv_cross::SPIRBlock::MergeNone, spirv_cross::SPIRBlock::Select, spirv_cross::SPIRBlock::terminator, spirv_cross::SPIRBlock::true_block, and spirv_cross::SPIRBlock::WhileLoop.
block_is_loop_candidate()
bool Compiler::block_is_loop_candidate (const SPIRBlock & block, SPIRBlock::Method method) const protected
References spirv_cross::SPIRBlock::complex_continue, spirv_cross::SPIRBlock::continue_block, spirv_cross::SPIRBlock::Direct, spirv_cross::SPIRBlock::disable_block_optimization, spirv_cross::SPIRBlock::false_block, spirv_cross::merge(), spirv_cross::SPIRBlock::merge, spirv_cross::SPIRBlock::merge_block, spirv_cross::SPIRBlock::MergeLoop, spirv_cross::SPIRBlock::MergeNone, spirv_cross::SPIRBlock::MergeToDirectForLoop, spirv_cross::SPIRBlock::MergeToSelectContinueForLoop, spirv_cross::SPIRBlock::MergeToSelectForLoop, spirv_cross::SPIRBlock::next_block, spirv_cross::SPIRBlock::ops, spirv_cross::SPIRBlock::phi_variables, spirv_cross::SPIRBlock::Select, spirv_cross::IVariant::self, spirv_cross::SPIRBlock::terminator, and spirv_cross::SPIRBlock::true_block.
increase_bound_by()
uint32_t Compiler::increase_bound_by (uint32_t incr_amount) protected
References ids, and meta.
Referenced by spirv_cross::CompilerMSL::add_interface_block(), build_dummy_sampler_for_combined_images(), spirv_cross::CompilerMSL::build_implicit_builtins(), spirv_cross::CompilerMSL::ensure_correct_builtin_type(), spirv_cross::CompilerMSL::extract_global_variables_from_function(), spirv_cross::CompilerMSL::get_input_buffer_block_var_id(), and make_constant_null().
types_are_logically_equivalent()
bool Compiler::types_are_logically_equivalent (const SPIRType & a, const SPIRType & b) const protected
References a, spirv_cross::SPIRType::array, spirv_cross::SPIRType::basetype, spirv_cross::SPIRType::columns, spirv_cross::SPIRType::Image, spirv_cross::SPIRType::image, spirv_cross::SPIRType::member_types, memcmp(), spirv_cross::SPIRType::SampledImage, spirv_cross::SPIRType::vecsize, and spirv_cross::SPIRType::width.
Referenced by parse().
inherit_expression_dependencies()
void Compiler::inherit_expression_dependencies (uint32_t dst, uint32_t source) protected
References forced_temporaries, and forwarded_temporaries.
interface_variable_exists_in_entry_point()
bool Compiler::interface_variable_exists_in_entry_point (uint32_t id) const protected
References entry_points, get_entry_point(), SPIRV_CROSS_THROW, spv::StorageClassInput, spv::StorageClassOutput, and spv::StorageClassUniformConstant.
Referenced by spirv_cross::CompilerMSL::add_interface_block().
remap_variable_type_name()
void spirv_cross::Compiler::remap_variable_type_name (const SPIRType & type, const std::string & var_name, std::string & type_name) const inline protected
References variable_remap_callback.
analyze_variable_scope()
void Compiler::analyze_variable_scope (SPIRFunction & function) protected
References spirv_cross::DominatorBuilder::add_block(), analyze_parameter_preservation(), spirv_cross::SPIRBlock::cases, spirv_cross::SPIRBlock::condition, continue_block_to_loop_header, current_block, spirv_cross::SPIRBlock::default_block, spirv_cross::SPIRBlock::Direct, expression_type(), spirv_cross::SPIRBlock::false_block, forced_temporaries, spirv_cross::DominatorBuilder::get_dominator(), spirv_cross::CFG::get_preceding_edges(), spirv_cross::CFG::get_succeeding_edges(), hoisted_temporaries, is_continue(), is_single_block_loop(), spirv_cross::DominatorBuilder::lift_continue_block_dominator(), loop_blocks, spirv_cross::SPIRBlock::MultiSelect, spirv_cross::SPIRBlock::next_block, spv::OpAccessChain, spv::OpArrayLength, spv::OpCompositeExtract, spv::OpCompositeInsert, spv::OpCopyMemory, spv::OpCopyObject, spv::OpExtInst, spv::OpFunctionCall, spv::OpInBoundsAccessChain, spv::OpLoad, spv::OpStore, spv::OpVectorShuffle, spirv_cross::SPIRVariable::phi_variable, spirv_cross::SPIRBlock::Select, spirv_cross::IVariant::self, spv::StorageClassFunction, spirv_cross::SPIRType::Struct, spirv_cross::SPIRBlock::terminator, traverse_all_reachable_opcodes(), spirv_cross::SPIRBlock::true_block, spirv_cross::TypeExpression, and spirv_cross::CFG::walk_from().
parse() [1/2]
void Compiler::parse () protected
References spv::BuiltInWorkgroupSize, current_block, current_function, entry_points, get_type(), ids, inst, is_valid_spirv_version(), spv::MagicNumber, meta, spirv_cross::IVariant::self, spirv, SPIRV_CROSS_THROW, swap_endian(), and spirv_cross::TypeConstant.
Referenced by Compiler().
parse() [2/2]
void Compiler::parse (const Instruction & i) protected
References spv::AccessQualifierMax, spirv_cross::SPIRFunction::add_local_variable(), spirv_cross::SPIRFunction::add_parameter(), aliased_variables, spirv_cross::SPIRType::AtomicCounter, spirv_cross::SPIRFunction::blocks, spirv_cross::SPIRType::Boolean, spv::CapabilityKernel, spirv_cross::SPIRBlock::cases, spirv_cross::SPIRBlock::condition, spirv_cross::SPIRBlock::continue_block, continue_block_to_loop_header, continue_blocks, current_block, current_function, declared_capabilities, declared_extensions, spv::DecorationNonReadable, spv::DecorationNonWritable, spirv_cross::SPIRBlock::default_block, spirv_cross::SPIRBlock::Direct, spirv_cross::SPIRType::Double, spirv_cross::SPIRFunction::entry_block, entry_point, entry_points, spirv_cross::Compiler::Source::es, spv::ExecutionModeInvocations, spv::ExecutionModeLocalSize, spv::ExecutionModeOutputVertices, extract_string(), spirv_cross::SPIRBlock::false_block, spirv_cross::SPIRType::Float, get_name(), global_struct_cache, global_variables, spirv_cross::SPIRExtension::GLSL, spirv_cross::SPIRType::Half, spirv_cross::Compiler::Source::hlsl, ImGui::Image(), spirv_cross::SPIRType::Image, spirv_cross::SPIRType::Int, spirv_cross::SPIRType::Int64, spirv_cross::SPIRBlock::Kill, spirv_cross::Compiler::Source::known, spirv_cross::Instruction::length, loop_blocks, loop_merge_targets, make_constant_null(), mark_used_as_array_length(), spirv_cross::SPIRBlock::merge, spirv_cross::SPIRBlock::merge_block, spirv_cross::SPIRBlock::MergeLoop, spirv_cross::SPIRBlock::MergeNone, spirv_cross::SPIRBlock::MergeSelection, meta, mode(), spirv_cross::SPIRBlock::MultiSelect, multiselect_merge_targets, spirv_cross::SPIRBlock::next_block, spirv_cross::Instruction::offset, spirv_cross::Instruction::op, spv::OpBranch, spv::OpBranchConditional, spv::OpCapability, spv::OpConstant, spv::OpConstantComposite, spv::OpConstantFalse, spv::OpConstantNull, spv::OpConstantTrue, spv::OpDecorate, spv::OpEntryPoint, spv::OpExecutionMode, spv::OpExtension, spv::OpExtInstImport, spv::OpFunction, spv::OpFunctionEnd, spv::OpFunctionParameter, spv::OpKill, spv::OpLabel, spv::OpLine, spv::OpLoopMerge, spv::OpMemberDecorate, spv::OpMemberName, spv::OpMemoryModel, spv::OpName, spv::OpNoLine, spv::OpNop, spv::OpPhi, spv::OpReturn, spv::OpReturnValue, spirv_cross::SPIRBlock::ops, spv::OpSelectionMerge, spv::OpSource, spv::OpSourceExtension, spv::OpSpecConstant, spv::OpSpecConstantComposite, spv::OpSpecConstantFalse, spv::OpSpecConstantOp, spv::OpSpecConstantTrue, spv::OpString, spv::OpSwitch, spv::OpTypeArray, spv::OpTypeBool, spv::OpTypeFloat, spv::OpTypeFunction, spv::OpTypeImage, spv::OpTypeInt, spv::OpTypeMatrix, spv::OpTypePointer, spv::OpTypeRuntimeArray, spv::OpTypeSampledImage, spv::OpTypeSampler, spv::OpTypeStruct, spv::OpTypeVector, spv::OpTypeVoid, spv::OpUndef, spv::OpUnreachable, spv::OpVariable, spirv_cross::SPIRBlock::phi_variables, spirv_cross::SPIRBlock::Return, spirv_cross::SPIRBlock::return_value, spirv_cross::SPIRType::SampledImage, spirv_cross::SPIRType::Sampler, spirv_cross::SPIRBlock::Select, selection_merge_targets, spirv_cross::IVariant::self, set_decoration(), set_member_decoration(), set_member_name(), set_name(), source, spv::SourceLanguageESSL, spv::SourceLanguageGLSL, spv::SourceLanguageHLSL, spirv, SPIRV_CROSS_THROW, spirv_cross::SPIRExtension::SPV_AMD_gcn_shader, spirv_cross::SPIRExtension::SPV_AMD_shader_ballot, spirv_cross::SPIRExtension::SPV_AMD_shader_explicit_vertex_parameter, spirv_cross::SPIRExtension::SPV_AMD_shader_trinary_minmax, spv::StorageClassAtomicCounter, spv::StorageClassFunction, spv::StorageClassOutput, spv::StorageClassPrivate, spv::StorageClassWorkgroup, stream(), spirv_cross::SPIRType::Struct, spirv_cross::SPIRBlock::terminator, spirv_cross::SPIRBlock::true_block, types_are_logically_equivalent(), spirv_cross::SPIRType::UInt, spirv_cross::SPIRType::UInt64, spirv_cross::SPIRBlock::Unreachable, spirv_cross::SPIRExtension::Unsupported, variable_storage_is_aliased(), spirv_cross::Compiler::Source::version, spirv_cross::SPIRType::Void, and width.
traverse_all_reachable_opcodes() [1/2]
bool Compiler::traverse_all_reachable_opcodes (const SPIRBlock & block, OpcodeHandler & handler) const protected
References spirv_cross::Compiler::OpcodeHandler::begin_function_scope(), spirv_cross::Compiler::OpcodeHandler::end_function_scope(), spirv_cross::Compiler::OpcodeHandler::follow_function_call(), spirv_cross::Compiler::OpcodeHandler::handle(), spv::OpFunctionCall, spirv_cross::SPIRBlock::ops, spirv_cross::Compiler::OpcodeHandler::set_current_block(), and stream().
Referenced by analyze_image_and_sampler_usage(), analyze_variable_scope(), build_combined_image_samplers(), build_dummy_sampler_for_combined_images(), get_active_buffer_ranges(), get_active_interface_variables(), spirv_cross::CompilerMSL::preprocess_op_codes(), traverse_all_reachable_opcodes(), and update_active_builtins().
traverse_all_reachable_opcodes() [2/2]
bool Compiler::traverse_all_reachable_opcodes (const SPIRFunction & block, OpcodeHandler & handler) const protected
References spirv_cross::SPIRFunction::blocks, and traverse_all_reachable_opcodes().
get_shader_resources() [3/3]
ShaderResources spirv_cross::Compiler::get_shader_resources (const std::unordered_set< uint32_t > * active_variables) const protected
get_buffer_block_flags()
Bitset Compiler::get_buffer_block_flags (const SPIRVariable & var) protected
References spirv_cross::SPIRVariable::basetype, get_member_decoration_bitset(), spirv_cross::Bitset::merge_and(), spirv_cross::Bitset::merge_or(), meta, spirv_cross::IVariant::self, and spirv_cross::SPIRType::Struct.
get_common_basic_type()
bool Compiler::get_common_basic_type (const SPIRType & type, SPIRType::BaseType & base_type) protected
References spirv_cross::SPIRType::basetype, spirv_cross::SPIRType::member_types, spirv_cross::SPIRType::Struct, and spirv_cross::SPIRType::Unknown.
update_active_builtins()
void Compiler::update_active_builtins () protected
References active_input_builtins, active_output_builtins, clip_distance_count, cull_distance_count, entry_point, spirv_cross::Bitset::reset(), and traverse_all_reachable_opcodes().
Referenced by spirv_cross::CompilerMSL::compile().
has_active_builtin()
bool Compiler::has_active_builtin (spv::BuiltIn builtin, spv::StorageClass storage) protected
References active_input_builtins, active_output_builtins, spirv_cross::Bitset::get(), spv::StorageClassInput, and spv::StorageClassOutput.
Referenced by spirv_cross::CompilerMSL::add_interface_block().
analyze_parameter_preservation()
void Compiler::analyze_parameter_preservation (SPIRFunction & entry, const CFG & cfg, const std::unordered_map< uint32_t, std::unordered_set< uint32_t >> & variable_to_blocks, const std::unordered_map< uint32_t, std::unordered_set< uint32_t >> & complete_write_blocks) protected
References spirv_cross::SPIRFunction::arguments, spirv_cross::SPIRType::AtomicCounter, spirv_cross::SPIRFunction::entry_block, exists_unaccessed_path_to_return(), spirv_cross::SPIRType::Image, spirv_cross::SPIRType::SampledImage, and spirv_cross::SPIRType::Sampler.
Referenced by analyze_variable_scope().
analyze_image_and_sampler_usage()
void Compiler::analyze_image_and_sampler_usage () protected
References comparison_images, spirv_cross::Compiler::CombinedImageSamplerUsageHandler::comparison_images, comparison_samplers, spirv_cross::Compiler::CombinedImageSamplerUsageHandler::comparison_samplers, entry_point, need_subpass_input, spirv_cross::Compiler::CombinedImageSamplerUsageHandler::need_subpass_input, and traverse_all_reachable_opcodes().
Referenced by spirv_cross::CompilerMSL::compile().
make_constant_null()
void Compiler::make_constant_null (uint32_t id, uint32_t type) protected
References increase_bound_by(), and SPIRV_CROSS_THROW.
Referenced by parse().
instruction_to_result_type()
bool Compiler::instruction_to_result_type (uint32_t & result_type, uint32_t & result_id, spv::Op op, const uint32_t * args, uint32_t length) protected
References spv::OpAtomicFlagClear, spv::OpAtomicStore, spv::OpCaptureEventProfilingInfo, spv::OpCommitReadPipe, spv::OpCommitWritePipe, spv::OpControlBarrier, spv::OpCopyMemory, spv::OpCopyMemorySized, spv::OpEmitStreamVertex, spv::OpEndStreamPrimitive, spv::OpGroupCommitReadPipe, spv::OpGroupCommitWritePipe, spv::OpGroupWaitEvents, spv::OpImageWrite, spv::OpMemoryBarrier, spv::OpReleaseEvent, spv::OpRetainEvent, spv::OpSetUserEventStatus, and spv::OpStore.
Member Data Documentation
get_entry_point
SPIREntryPoint & Compiler::get_entry_point
get_entry_points_and_stages
vector< EntryPoint > Compiler::get_entry_points_and_stages
spirv
std::vector<uint32_t> spirv_cross::Compiler::spirv protected
Referenced by extract_string(), parse(), and stream().
inst
std::vector<Instruction> spirv_cross::Compiler::inst protected
Referenced by parse().
ids
std::vector<Variant> spirv_cross::Compiler::ids protected
Referenced by spirv_cross::CompilerMSL::add_interface_block(), build_combined_image_samplers(), spirv_cross::CompilerMSL::build_implicit_builtins(), spirv_cross::CompilerMSL::declare_constant_arrays(), spirv_cross::CompilerMSL::declare_undefined_values(), spirv_cross::CompilerMSL::emit_resources(), expression_type_id(), spirv_cross::CompilerMSL::extract_global_variables_from_functions(), get(), get_current_id_bound(), get_specialization_constants(), increase_bound_by(), is_immutable(), spirv_cross::CompilerMSL::mark_packable_structs(), mark_used_as_array_length(), maybe_get(), parse(), spirv_cross::CompilerMSL::resolve_specialized_array_lengths(), set(), and to_name().
meta
std::vector<Meta> spirv_cross::Compiler::meta protected
Referenced by spirv_cross::CompilerMSL::add_interface_block(), spirv_cross::CompilerMSL::align_struct(), buffer_get_hlsl_counter_buffer(), buffer_is_hlsl_counter_buffer(), spirv_cross::CompilerMSL::build_implicit_builtins(), spirv_cross::CompilerMSL::extract_global_variables_from_function(), get_binary_offset_for_decoration(), get_buffer_block_flags(), get_decoration(), get_decoration_bitset(), get_member_decoration(), get_member_decoration_bitset(), get_member_name(), get_member_qualified_name(), get_name(), get_remapped_declared_block_name(), increase_bound_by(), is_builtin_variable(), is_member_builtin(), spirv_cross::CompilerMSL::move_to_input_buffer(), parse(), set_decoration(), set_member_decoration(), set_member_name(), set_member_qualified_name(), set_name(), to_name(), type_struct_member_array_stride(), type_struct_member_matrix_stride(), type_struct_member_offset(), unset_decoration(), unset_member_decoration(), and variable_storage_is_aliased().
current_function
SPIRFunction* spirv_cross::Compiler::current_function = nullptr protected
Referenced by flush_all_active_variables(), and parse().
current_block
SPIRBlock* spirv_cross::Compiler::current_block = nullptr protected
Referenced by analyze_variable_scope(), and parse().
global_variables
std::vector<uint32_t> spirv_cross::Compiler::global_variables protected
Referenced by flush_all_active_variables(), flush_all_atomic_capable_variables(), spirv_cross::CompilerMSL::localize_global_variables(), and parse().
aliased_variables
std::vector<uint32_t> spirv_cross::Compiler::aliased_variables protected
Referenced by flush_all_aliased_variables(), and parse().
active_interface_variables
std::unordered_set<uint32_t> spirv_cross::Compiler::active_interface_variables protected
Referenced by spirv_cross::CompilerMSL::add_interface_block(), is_hidden_variable(), and set_enabled_interface_variables().
check_active_interface_variables
bool spirv_cross::Compiler::check_active_interface_variables = false protected
Referenced by is_hidden_variable(), and set_enabled_interface_variables().
entry_point
uint32_t spirv_cross::Compiler::entry_point = 0 protected
Referenced by spirv_cross::CompilerMSL::add_interface_block(), analyze_image_and_sampler_usage(), build_combined_image_samplers(), build_dummy_sampler_for_combined_images(), spirv_cross::CompilerMSL::compile(), spirv_cross::CompilerMSL::extract_global_variables_from_function(), spirv_cross::CompilerMSL::extract_global_variables_from_functions(), get_active_buffer_ranges(), get_active_interface_variables(), spirv_cross::CompilerMSL::localize_global_variables(), parse(), spirv_cross::CompilerMSL::preprocess_op_codes(), set_entry_point(), and update_active_builtins().
entry_points
std::unordered_map<uint32_t, SPIREntryPoint> spirv_cross::Compiler::entry_points protected
Referenced by get_entry_points(), interface_variable_exists_in_entry_point(), and parse().
source
struct spirv_cross::Compiler::Source spirv_cross::Compiler::source protected
Referenced by parse(), and set_name().
loop_blocks
std::unordered_set<uint32_t> spirv_cross::Compiler::loop_blocks protected
Referenced by analyze_variable_scope(), and parse().
continue_blocks
std::unordered_set<uint32_t> spirv_cross::Compiler::continue_blocks protected
Referenced by is_continue(), and parse().
loop_merge_targets
std::unordered_set<uint32_t> spirv_cross::Compiler::loop_merge_targets protected
Referenced by is_break(), is_loop_break(), and parse().
selection_merge_targets
std::unordered_set<uint32_t> spirv_cross::Compiler::selection_merge_targets protected
Referenced by is_conditional(), and parse().
multiselect_merge_targets
std::unordered_set<uint32_t> spirv_cross::Compiler::multiselect_merge_targets protected
Referenced by is_break(), is_conditional(), and parse().
continue_block_to_loop_header
std::unordered_map<uint32_t, uint32_t> spirv_cross::Compiler::continue_block_to_loop_header protected
Referenced by analyze_variable_scope(), and parse().
invalid_expressions
std::unordered_set<uint32_t> spirv_cross::Compiler::invalid_expressions protected
Referenced by flush_control_dependent_expressions(), and flush_dependees().
force_recompile
bool spirv_cross::Compiler::force_recompile = false protected
Referenced by spirv_cross::CompilerMSL::add_pragma_line(), spirv_cross::CompilerMSL::add_typedef_line(), spirv_cross::CompilerMSL::compile(), register_write(), and spirv_cross::CompilerGLSL::statement().
combined_image_samplers
std::vector<CombinedImageSampler> spirv_cross::Compiler::combined_image_samplers protected
Referenced by build_combined_image_samplers(), get_combined_image_samplers(), and is_hidden_variable().
global_struct_cache
std::vector<uint32_t> spirv_cross::Compiler::global_struct_cache protected
Referenced by parse().
variable_remap_callback
VariableTypeRemapCallback spirv_cross::Compiler::variable_remap_callback protected
Referenced by remap_variable_type_name(), and set_variable_type_remap_callback().
forced_temporaries
std::unordered_set<uint32_t> spirv_cross::Compiler::forced_temporaries protected
Referenced by analyze_variable_scope(), and inherit_expression_dependencies().
forwarded_temporaries
std::unordered_set<uint32_t> spirv_cross::Compiler::forwarded_temporaries protected
Referenced by inherit_expression_dependencies().
hoisted_temporaries
std::unordered_set<uint32_t> spirv_cross::Compiler::hoisted_temporaries protected
Referenced by analyze_variable_scope().
active_input_builtins
Bitset spirv_cross::Compiler::active_input_builtins protected
Referenced by has_active_builtin(), and update_active_builtins().
active_output_builtins
Bitset spirv_cross::Compiler::active_output_builtins protected
Referenced by has_active_builtin(), and update_active_builtins().
clip_distance_count
uint32_t spirv_cross::Compiler::clip_distance_count = 0 protected
Referenced by update_active_builtins().
cull_distance_count
uint32_t spirv_cross::Compiler::cull_distance_count = 0 protected
Referenced by update_active_builtins().
position_invariant
bool spirv_cross::Compiler::position_invariant = false protected
comparison_samplers
std::unordered_set<uint32_t> spirv_cross::Compiler::comparison_samplers protected
Referenced by spirv_cross::Compiler::CombinedImageSamplerUsageHandler::add_hierarchy_to_comparison_samplers(), and analyze_image_and_sampler_usage().
comparison_images
std::unordered_set<uint32_t> spirv_cross::Compiler::comparison_images protected
Referenced by spirv_cross::Compiler::CombinedImageSamplerUsageHandler::add_hierarchy_to_comparison_images(), and analyze_image_and_sampler_usage().
need_subpass_input
bool spirv_cross::Compiler::need_subpass_input = false protected
Referenced by analyze_image_and_sampler_usage(), spirv_cross::CompilerMSL::build_implicit_builtins(), and spirv_cross::Compiler::CombinedImageSamplerUsageHandler::handle().
dummy_sampler_id
uint32_t spirv_cross::Compiler::dummy_sampler_id = 0 protected
Referenced by build_dummy_sampler_for_combined_images(), and get_active_interface_variables().
declared_capabilities
std::vector<spv::Capability> spirv_cross::Compiler::declared_capabilities protected
Referenced by get_declared_capabilities(), and parse().
declared_extensions
std::vector<std::string> spirv_cross::Compiler::declared_extensions protected
Referenced by get_declared_extensions(), and parse().
declared_block_names
std::unordered_map<uint32_t, std::string> spirv_cross::Compiler::declared_block_names protected
Referenced by get_remapped_declared_block_name().
The documentation for this class was generated from the following files:
Cross.h
Cross.cpp