Aurora Framework: audio_detect.c File Reference
audio_detect.c File Reference
Classes
struct VOTE
Functions
int audio_detect (SF_PRIVATE *psf, AUDIO_DETECT *ad, const unsigned char *data, int datalen)
static void vote_for_format (VOTE *vote, const unsigned char *data, int datalen)
Function Documentation
vote_for_format()
static void vote_for_format (VOTE * vote, const unsigned char * data, int datalen) static
References VOTE::be_float, VOTE::le_float, VOTE::le_int_24_32, and memset().
Referenced by audio_detect().
audio_detect()
int audio_detect (SF_PRIVATE * psf, AUDIO_DETECT * ad, const unsigned char * data, int datalen)
References VOTE::be_float, VOTE::be_int_24_32, sf_private_tag::buf, AUDIO_DETECT::endianness, VOTE::le_float, VOTE::le_int_24_32, NULL, sf_private_tag::parselog, psf_log_printf(), and vote_for_format().
Referenced by wavlike_analyze().