Aurora Framework: nms_adpcm.c File Reference
nms_adpcm.c File Reference
Classes
struct NMS_ADPCM_PRIVATE
struct nms_adpcm_state
Macros
#define NMS_BLOCK_SHORTS_16 21
#define NMS_BLOCK_SHORTS_24 31
#define NMS_BLOCK_SHORTS_32 41
#define NMS_SAMPLES_PER_BLOCK 160
Enumerations
enum nms_enc_type { NMS16, NMS24, NMS32 }
Functions
static int nms_adpcm_antilog (int exp)
static void nms_adpcm_block_pack_16 (const int16_t codewords [], uint16_t block [], int16_t rms)
static void nms_adpcm_block_pack_24 (const int16_t codewords [], uint16_t block [], int16_t rms)
static void nms_adpcm_block_pack_32 (const int16_t codewords [], uint16_t block [], int16_t rms)
static void nms_adpcm_block_unpack_16 (const uint16_t block [], int16_t codewords [], int16_t *rms)
NMS ADPCM Codeword packing scheme.
static void nms_adpcm_block_unpack_24 (const uint16_t block [], int16_t codewords [], int16_t *rms)
static void nms_adpcm_block_unpack_32 (const uint16_t block [], int16_t codewords [], int16_t *rms)
static int nms_adpcm_close (SF_PRIVATE *psf)
static void nms_adpcm_codec_init (struct nms_adpcm_state *s, enum nms_enc_type type)
static int nms_adpcm_decode_block (SF_PRIVATE *psf, NMS_ADPCM_PRIVATE *pnms, uint16_t block [], int16_t samples [])
static int16_t nms_adpcm_decode_sample (struct nms_adpcm_state *s, uint8_t code)
static int nms_adpcm_encode_block (SF_PRIVATE *psf, NMS_ADPCM_PRIVATE *pnms, int16_t samples [], uint16_t block [])
static uint8_t nms_adpcm_encode_sample (struct nms_adpcm_state *s, int16_t sl)
int nms_adpcm_init (SF_PRIVATE *psf)
static int nms_adpcm_read_block (SF_PRIVATE *psf, NMS_ADPCM_PRIVATE *pnms, short *ptr, int len)
static sf_count_t nms_adpcm_read_d (SF_PRIVATE *psf, double *ptr, sf_count_t len)
static sf_count_t nms_adpcm_read_f (SF_PRIVATE *psf, float *ptr, sf_count_t len)
static sf_count_t nms_adpcm_read_i (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static sf_count_t nms_adpcm_read_s (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static int16_t nms_adpcm_reconstruct_sample (struct nms_adpcm_state *s, uint8_t I)
static sf_count_t nms_adpcm_seek (SF_PRIVATE *psf, int mode, sf_count_t offset)
static void nms_adpcm_update (struct nms_adpcm_state *s)
static int nms_adpcm_write_block (SF_PRIVATE *psf, NMS_ADPCM_PRIVATE *pnms, const short *ptr, int len)
static sf_count_t nms_adpcm_write_d (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
static sf_count_t nms_adpcm_write_f (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
static sf_count_t nms_adpcm_write_i (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
static sf_count_t nms_adpcm_write_s (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
static int psf_nms_adpcm_decode_block (SF_PRIVATE *psf, NMS_ADPCM_PRIVATE *pnms)
static int psf_nms_adpcm_encode_block (SF_PRIVATE *psf, NMS_ADPCM_PRIVATE *pnms)
Variables
static unsigned int table_expn []
static int table_scale_factor_step []
static unsigned int table_step []
static int table_step_search []
Macro Definition Documentation
NMS_SAMPLES_PER_BLOCK
#define NMS_SAMPLES_PER_BLOCK 160
Referenced by nms_adpcm_block_pack_16(), nms_adpcm_block_pack_24(), nms_adpcm_block_pack_32(), nms_adpcm_block_unpack_16(), nms_adpcm_block_unpack_24(), nms_adpcm_block_unpack_32(), nms_adpcm_close(), nms_adpcm_decode_block(), nms_adpcm_encode_block(), nms_adpcm_init(), nms_adpcm_read_block(), and nms_adpcm_write_block().
NMS_BLOCK_SHORTS_32
#define NMS_BLOCK_SHORTS_32 41
Referenced by nms_adpcm_init().
NMS_BLOCK_SHORTS_24
#define NMS_BLOCK_SHORTS_24 31
Referenced by nms_adpcm_init().
NMS_BLOCK_SHORTS_16
#define NMS_BLOCK_SHORTS_16 21
Referenced by nms_adpcm_init().
Enumeration Type Documentation
nms_enc_type
enum nms_enc_type
Enumerator
NMS16
NMS24
NMS32
Function Documentation
nms_adpcm_update()
static void nms_adpcm_update (struct nms_adpcm_state * s) static
References nms_adpcm_state::a, nms_adpcm_state::b, nms_adpcm_state::d_q, nms_adpcm_state::Ik, nms_adpcm_antilog(), nms_adpcm_state::p, nms_adpcm_state::s_e, nms_adpcm_state::s_ez, nms_adpcm_state::s_r, nms_adpcm_state::t_off, table_scale_factor_step, nms_adpcm_state::y, and nms_adpcm_state::yl.
Referenced by nms_adpcm_decode_sample(), and nms_adpcm_encode_sample().
nms_adpcm_codec_init()
static void nms_adpcm_codec_init (struct nms_adpcm_state * s, enum nms_enc_type type) static
References memset(), NMS24, NMS32, and nms_adpcm_state::t_off.
Referenced by nms_adpcm_init(), and nms_adpcm_seek().
nms_adpcm_reconstruct_sample()
static int16_t nms_adpcm_reconstruct_sample (struct nms_adpcm_state * s, uint8_t I) static
References nms_adpcm_state::d_q, nms_adpcm_state::Ik, nms_adpcm_state::p, nms_adpcm_state::s_e, nms_adpcm_state::s_ez, nms_adpcm_state::s_r, nms_adpcm_state::t_off, table_step, and nms_adpcm_state::y.
Referenced by nms_adpcm_decode_sample(), and nms_adpcm_encode_sample().
nms_adpcm_encode_sample()
static uint8_t nms_adpcm_encode_sample (struct nms_adpcm_state * s, int16_t sl) static
References nms_adpcm_reconstruct_sample(), nms_adpcm_update(), nms_adpcm_state::parity, nms_adpcm_state::s_e, nms_adpcm_state::t_off, table_step_search, and nms_adpcm_state::y.
Referenced by nms_adpcm_encode_block().
nms_adpcm_decode_sample()
static int16_t nms_adpcm_decode_sample (struct nms_adpcm_state * s, uint8_t code) static
References nms_adpcm_reconstruct_sample(), and nms_adpcm_update().
Referenced by nms_adpcm_decode_block().
nms_adpcm_block_pack_16()
static void nms_adpcm_block_pack_16 (const int16_t codewords[], uint16_t block[], int16_t rms) static
References NMS_SAMPLES_PER_BLOCK.
Referenced by nms_adpcm_encode_block().
nms_adpcm_block_pack_24()
static void nms_adpcm_block_pack_24 (const int16_t codewords[], uint16_t block[], int16_t rms) static
References NMS_SAMPLES_PER_BLOCK.
Referenced by nms_adpcm_encode_block().
nms_adpcm_block_pack_32()
static void nms_adpcm_block_pack_32 (const int16_t codewords[], uint16_t block[], int16_t rms) static
References NMS_SAMPLES_PER_BLOCK.
Referenced by nms_adpcm_encode_block().
nms_adpcm_block_unpack_16()
static void nms_adpcm_block_unpack_16 (const uint16_t block[], int16_t codewords[], int16_t * rms) static
NMS ADPCM Codeword packing scheme.
The serialized form of NMS-ADPCM operates on blocks of 160 mono samples (20ms at 8000Hz.) Blocks are 42, 62 and 82 bytes in size for the 2, 3, and 4 bit codeword sizes respectively. The data is treated as an array of little-endian 2-byte shorts, and the data is packed into the first 20, 30 or 40 shorts. The last short represents the block's root-mean-square average. This is apparently an optimization so that energy/silence detection processes can avoid decoding a block.
All codewords are nibbles, with the least significant bits dropped as required for the 3 and 2 bit codeword sizes.
Nibbles are packed into shorts in order of most significant to least. The 4-bit scheme is trivial. The three bit scheme reconstructs a fourth sample from the leftover bits of the proceeding three samples. The 2-bit scheme uses a two-pass, left two bit shift.
References NMS_SAMPLES_PER_BLOCK.
Referenced by nms_adpcm_decode_block().
nms_adpcm_block_unpack_24()
static void nms_adpcm_block_unpack_24 (const uint16_t block[], int16_t codewords[], int16_t * rms) static
References NMS_SAMPLES_PER_BLOCK.
Referenced by nms_adpcm_decode_block().
nms_adpcm_block_unpack_32()
static void nms_adpcm_block_unpack_32 (const uint16_t block[], int16_t codewords[], int16_t * rms) static
References NMS_SAMPLES_PER_BLOCK.
Referenced by nms_adpcm_decode_block().
nms_adpcm_decode_block()
static int nms_adpcm_decode_block (SF_PRIVATE * psf, NMS_ADPCM_PRIVATE * pnms, uint16_t block[], int16_t samples[]) static
References NMS16, NMS24, NMS32, nms_adpcm_block_unpack_16(), nms_adpcm_block_unpack_24(), nms_adpcm_block_unpack_32(), nms_adpcm_decode_sample(), NMS_SAMPLES_PER_BLOCK, NULL, psf_log_printf(), NMS_ADPCM_PRIVATE::state, and NMS_ADPCM_PRIVATE::type.
Referenced by psf_nms_adpcm_decode_block().
nms_adpcm_encode_block()
static int nms_adpcm_encode_block (SF_PRIVATE * psf, NMS_ADPCM_PRIVATE * pnms, int16_t samples[], uint16_t block[]) static
References NMS16, NMS24, NMS32, nms_adpcm_block_pack_16(), nms_adpcm_block_pack_24(), nms_adpcm_block_pack_32(), nms_adpcm_encode_sample(), NMS_SAMPLES_PER_BLOCK, psf_log_printf(), NMS_ADPCM_PRIVATE::state, and NMS_ADPCM_PRIVATE::type.
Referenced by psf_nms_adpcm_encode_block().
nms_adpcm_read_s()
static sf_count_t nms_adpcm_read_s (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
References sf_private_tag::codec_data, nms_adpcm_read_block(), and NULL.
Referenced by nms_adpcm_init().
nms_adpcm_read_i()
static sf_count_t nms_adpcm_read_i (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
References arith_shift_left(), sf_private_tag::codec_data, nms_adpcm_read_block(), NULL, BUF_UNION::sbuf, and SF_BUFFER_LEN.
Referenced by nms_adpcm_init().
nms_adpcm_read_f()
static sf_count_t nms_adpcm_read_f (SF_PRIVATE * psf, float * ptr, sf_count_t len) static
References sf_private_tag::codec_data, nms_adpcm_read_block(), sf_private_tag::norm_float, NULL, BUF_UNION::sbuf, and SF_BUFFER_LEN.
Referenced by nms_adpcm_init().
nms_adpcm_read_d()
static sf_count_t nms_adpcm_read_d (SF_PRIVATE * psf, double * ptr, sf_count_t len) static
References sf_private_tag::codec_data, nms_adpcm_read_block(), sf_private_tag::norm_double, NULL, BUF_UNION::sbuf, and SF_BUFFER_LEN.
Referenced by nms_adpcm_init().
nms_adpcm_write_s()
static sf_count_t nms_adpcm_write_s (SF_PRIVATE * psf, const short * ptr, sf_count_t len) static
References sf_private_tag::codec_data, nms_adpcm_write_block(), and NULL.
Referenced by nms_adpcm_init().
nms_adpcm_write_i()
static sf_count_t nms_adpcm_write_i (SF_PRIVATE * psf, const int * ptr, sf_count_t len) static
References sf_private_tag::codec_data, nms_adpcm_write_block(), NULL, BUF_UNION::sbuf, and SF_BUFFER_LEN.
Referenced by nms_adpcm_init().
nms_adpcm_write_f()
static sf_count_t nms_adpcm_write_f (SF_PRIVATE * psf, const float * ptr, sf_count_t len) static
References sf_private_tag::codec_data, nms_adpcm_write_block(), sf_private_tag::norm_float, NULL, BUF_UNION::sbuf, and SF_BUFFER_LEN.
Referenced by nms_adpcm_init().
nms_adpcm_write_d()
static sf_count_t nms_adpcm_write_d (SF_PRIVATE * psf, const double * ptr, sf_count_t len) static
References sf_private_tag::codec_data, nms_adpcm_write_block(), sf_private_tag::norm_double, NULL, BUF_UNION::sbuf, and SF_BUFFER_LEN.
Referenced by nms_adpcm_init().
nms_adpcm_close()
static int nms_adpcm_close (SF_PRIVATE * psf) static
References sf_private_tag::codec_data, sf_private_tag::file, memset(), PSF_FILE::mode, NMS_SAMPLES_PER_BLOCK, psf_nms_adpcm_encode_block(), NMS_ADPCM_PRIVATE::sample_curr, NMS_ADPCM_PRIVATE::samples, and sf_private_tag::write_header.
Referenced by nms_adpcm_init().
nms_adpcm_seek()
static sf_count_t nms_adpcm_seek (SF_PRIVATE * psf, int mode, sf_count_t offset) static
References NMS_ADPCM_PRIVATE::block_curr, sf_private_tag::codec_data, sf_private_tag::dataoffset, sf_private_tag::error, sf_private_tag::file, mode(), PSF_FILE::mode, nms_adpcm_codec_init(), psf_fseek(), PSF_SEEK_ERROR, NMS_ADPCM_PRIVATE::sample_curr, SFE_BAD_SEEK, NMS_ADPCM_PRIVATE::state, and NMS_ADPCM_PRIVATE::type.
Referenced by nms_adpcm_init().
nms_adpcm_antilog()
static int nms_adpcm_antilog (int exp) inline static
References table_expn.
Referenced by nms_adpcm_update().
psf_nms_adpcm_decode_block()
static int psf_nms_adpcm_decode_block (SF_PRIVATE * psf, NMS_ADPCM_PRIVATE * pnms) static
References NMS_ADPCM_PRIVATE::block, endswap_short_array(), memset(), nms_adpcm_decode_block(), psf_fread(), psf_log_printf(), NMS_ADPCM_PRIVATE::samples, and NMS_ADPCM_PRIVATE::shortsperblock.
Referenced by nms_adpcm_read_block().
nms_adpcm_read_block()
static int nms_adpcm_read_block (SF_PRIVATE * psf, NMS_ADPCM_PRIVATE * pnms, short * ptr, int len) static
References NMS_ADPCM_PRIVATE::block_curr, NMS_ADPCM_PRIVATE::blocks_total, memcpy(), memset(), NMS_SAMPLES_PER_BLOCK, psf_nms_adpcm_decode_block(), NMS_ADPCM_PRIVATE::sample_curr, and NMS_ADPCM_PRIVATE::samples.
Referenced by nms_adpcm_read_d(), nms_adpcm_read_f(), nms_adpcm_read_i(), and nms_adpcm_read_s().
psf_nms_adpcm_encode_block()
static int psf_nms_adpcm_encode_block (SF_PRIVATE * psf, NMS_ADPCM_PRIVATE * pnms) static
References NMS_ADPCM_PRIVATE::block, NMS_ADPCM_PRIVATE::block_curr, endswap_short_array(), nms_adpcm_encode_block(), psf_fwrite(), psf_log_printf(), NMS_ADPCM_PRIVATE::sample_curr, NMS_ADPCM_PRIVATE::samples, and NMS_ADPCM_PRIVATE::shortsperblock.
Referenced by nms_adpcm_close(), and nms_adpcm_write_block().
nms_adpcm_write_block()
static int nms_adpcm_write_block (SF_PRIVATE * psf, NMS_ADPCM_PRIVATE * pnms, const short * ptr, int len) static
References memcpy(), NMS_SAMPLES_PER_BLOCK, psf_nms_adpcm_encode_block(), NMS_ADPCM_PRIVATE::sample_curr, and NMS_ADPCM_PRIVATE::samples.
Referenced by nms_adpcm_write_d(), nms_adpcm_write_f(), nms_adpcm_write_i(), and nms_adpcm_write_s().
nms_adpcm_init()
int nms_adpcm_init (SF_PRIVATE * psf)
References NMS_ADPCM_PRIVATE::block_curr, NMS_ADPCM_PRIVATE::blocks_total, sf_private_tag::codec_close, sf_private_tag::codec_data, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::file, sf_private_tag::filelength, PSF_FILE::mode, NMS16, NMS24, NMS32, nms_adpcm_close(), nms_adpcm_codec_init(), nms_adpcm_read_d(), nms_adpcm_read_f(), nms_adpcm_read_i(), nms_adpcm_read_s(), nms_adpcm_seek(), nms_adpcm_write_d(), nms_adpcm_write_f(), nms_adpcm_write_i(), nms_adpcm_write_s(), NMS_BLOCK_SHORTS_16, NMS_BLOCK_SHORTS_24, NMS_BLOCK_SHORTS_32, NMS_SAMPLES_PER_BLOCK, NULL, psf_get_filelen(), psf_log_printf(), sf_private_tag::read_double, sf_private_tag::read_float, sf_private_tag::read_int, sf_private_tag::read_short, NMS_ADPCM_PRIVATE::sample_curr, sf_private_tag::seek, sf_private_tag::sf, SF_CODEC, SFE_INTERNAL, SFE_MALLOC_FAILED, SFE_NMS_ADPCM_NOT_MONO, SFE_UNIMPLEMENTED, NMS_ADPCM_PRIVATE::shortsperblock, NMS_ADPCM_PRIVATE::state, NMS_ADPCM_PRIVATE::type, sf_private_tag::write_double, sf_private_tag::write_float, sf_private_tag::write_int, and sf_private_tag::write_short.
Referenced by raw_open(), and wav_open().
Variable Documentation
table_expn
unsigned int table_expn[] static
Initial value:
=
{   0x4000, 0x4167, 0x42d5, 0x444c, 0x45cb, 0x4752, 0x48e2, 0x4a7a,
    0x4c1b, 0x4dc7, 0x4f7a, 0x5138, 0x52ff, 0x54d1, 0x56ac, 0x5892,
    0x5a82, 0x5c7e, 0x5e84, 0x6096, 0x62b4, 0x64dd, 0x6712, 0x6954,
    0x6ba2, 0x6dfe, 0x7066, 0x72dc, 0x7560, 0x77f2, 0x7a93, 0x7d42,
}
Referenced by nms_adpcm_antilog().
table_scale_factor_step
int table_scale_factor_step[] static
Initial value:
=
{   0x0,    0x0,    0x0,    0x0,    0x4b0,  0x0,    0x0,    0x0,
    -0x3c,  0x0,    0x90,   0x0,    0x2ee,  0x0,    0x898,  0x0,
    -0x30,  0x12,   0x6b,   0xc8,   0x188,  0x2e0,  0x551,  0x1150,
}
Referenced by nms_adpcm_update().
table_step
unsigned int table_step[] static
Initial value:
=
{   0x73F,  0,      0,      0,      0x1829, 0,      0,      0,
    0x3EB,  0,      0xC18,  0,      0x1581, 0,      0x226E, 0,
    0x20C,  0x635,  0xA83,  0xF12,  0x1418, 0x19E3, 0x211A, 0x2BBA,
}
Referenced by nms_adpcm_reconstruct_sample().
table_step_search
int table_step_search[] static
Initial value:
=
{   0,      0x1F6D, 0,      -0x1F6D,    0,      0,          0,          0,
    0x1008, 0x1192, 0,      -0x219A,    0x1656, -0x1656,    0,          0,
    0x872,  0x1277, -0x8E6, -0x232B,    0xD06,  -0x17D7,    -0x11D3,    0,
}
Referenced by nms_adpcm_encode_sample().