Aurora Framework: spirv_cross::Compiler::CombinedImageSamplerUsageHandler Struct Reference
spirv_cross::Compiler::CombinedImageSamplerUsageHandler Struct Reference
Public Member Functions
CombinedImageSamplerUsageHandler (Compiler &compiler_)
void add_hierarchy_to_comparison_images (uint32_t sampler)
void add_hierarchy_to_comparison_samplers (uint32_t sampler)
bool begin_function_scope (const uint32_t *args, uint32_t length) override
virtual bool end_function_scope (const uint32_t *, uint32_t)
virtual bool follow_function_call (const SPIRFunction &)
bool handle (spv::Op opcode, const uint32_t *args, uint32_t length) override
virtual void set_current_block (const SPIRBlock &)
Public Attributes
std::unordered_set< uint32_t > comparison_images
std::unordered_set< uint32_t > comparison_samplers
Compiler & compiler
std::unordered_map< uint32_t, std::unordered_set< uint32_t > > dependency_hierarchy
bool need_subpass_input = false
Constructor & Destructor Documentation
CombinedImageSamplerUsageHandler()
spirv_cross::Compiler::CombinedImageSamplerUsageHandler::CombinedImageSamplerUsageHandler (Compiler & compiler_) inline
Member Function Documentation
begin_function_scope()
bool Compiler::CombinedImageSamplerUsageHandler::begin_function_scope (const uint32_t * args, uint32_t length) override virtual
Reimplemented from spirv_cross::Compiler::OpcodeHandler.
References spirv_cross::SPIRFunction::arguments.
handle()
bool Compiler::CombinedImageSamplerUsageHandler::handle (spv::Op opcode, const uint32_t * args, uint32_t length) override virtual
Implements spirv_cross::Compiler::OpcodeHandler.
References spv::DimSubpassData, spirv_cross::Compiler::need_subpass_input, spv::OpAccessChain, spv::OpInBoundsAccessChain, spv::OpLoad, and spv::OpSampledImage.
add_hierarchy_to_comparison_samplers()
void Compiler::CombinedImageSamplerUsageHandler::add_hierarchy_to_comparison_samplers (uint32_t sampler)
References spirv_cross::Compiler::comparison_samplers.
add_hierarchy_to_comparison_images()
void Compiler::CombinedImageSamplerUsageHandler::add_hierarchy_to_comparison_images (uint32_t sampler)
References spirv_cross::Compiler::comparison_images.
follow_function_call()
virtual bool spirv_cross::Compiler::OpcodeHandler::follow_function_call (const SPIRFunction &) inline virtual inherited
Referenced by spirv_cross::Compiler::traverse_all_reachable_opcodes().
set_current_block()
virtual void spirv_cross::Compiler::OpcodeHandler::set_current_block (const SPIRBlock &) inline virtual inherited
Referenced by spirv_cross::Compiler::traverse_all_reachable_opcodes().
end_function_scope()
virtual bool spirv_cross::Compiler::OpcodeHandler::end_function_scope (const uint32_t * , uint32_t) inline virtual inherited
Reimplemented in spirv_cross::Compiler::CombinedImageSamplerHandler.
Referenced by spirv_cross::Compiler::traverse_all_reachable_opcodes().
Member Data Documentation
compiler
Compiler& spirv_cross::Compiler::CombinedImageSamplerUsageHandler::compiler
dependency_hierarchy
std::unordered_map<uint32_t, std::unordered_set<uint32_t> > spirv_cross::Compiler::CombinedImageSamplerUsageHandler::dependency_hierarchy
comparison_images
std::unordered_set<uint32_t> spirv_cross::Compiler::CombinedImageSamplerUsageHandler::comparison_images
Referenced by spirv_cross::Compiler::analyze_image_and_sampler_usage().
comparison_samplers
std::unordered_set<uint32_t> spirv_cross::Compiler::CombinedImageSamplerUsageHandler::comparison_samplers
Referenced by spirv_cross::Compiler::analyze_image_and_sampler_usage().
need_subpass_input
bool spirv_cross::Compiler::CombinedImageSamplerUsageHandler::need_subpass_input = false
Referenced by spirv_cross::Compiler::analyze_image_and_sampler_usage().
The documentation for this struct was generated from the following files:
Cross.h
Cross.cpp