Aurora Framework: g72x.h File Reference
g72x.h File Reference
Macros
#define G72x_BLOCK_SIZE (3 * 5 * 8)
Enumerations
enum {
G723_16_BITS_PER_SAMPLE = 2, G723_24_BITS_PER_SAMPLE = 3, G723_40_BITS_PER_SAMPLE = 5, G721_32_BITS_PER_SAMPLE = 4,
G721_40_BITS_PER_SAMPLE = 5, G723_16_SAMPLES_PER_BLOCK = G72x_BLOCK_SIZE, G723_24_SAMPLES_PER_BLOCK = G723_24_BITS_PER_SAMPLE * (G72x_BLOCK_SIZE / G723_24_BITS_PER_SAMPLE), G723_40_SAMPLES_PER_BLOCK = G723_40_BITS_PER_SAMPLE * (G72x_BLOCK_SIZE / G723_40_BITS_PER_SAMPLE),
G721_32_SAMPLES_PER_BLOCK = G72x_BLOCK_SIZE, G721_40_SAMPLES_PER_BLOCK = G721_40_BITS_PER_SAMPLE * (G72x_BLOCK_SIZE / G721_40_BITS_PER_SAMPLE), G723_16_BYTES_PER_BLOCK = (G723_16_BITS_PER_SAMPLE * G72x_BLOCK_SIZE) / 8, G723_24_BYTES_PER_BLOCK = (G723_24_BITS_PER_SAMPLE * G72x_BLOCK_SIZE) / 8,
G723_40_BYTES_PER_BLOCK = (G723_40_BITS_PER_SAMPLE * G72x_BLOCK_SIZE) / 8, G721_32_BYTES_PER_BLOCK = (G721_32_BITS_PER_SAMPLE * G72x_BLOCK_SIZE) / 8, G721_40_BYTES_PER_BLOCK = (G721_40_BITS_PER_SAMPLE * G72x_BLOCK_SIZE) / 8
}
Functions
int g72x_decode_block (struct g72x_state *pstate, const unsigned char *block, short *samples)
int g72x_encode_block (struct g72x_state *pstate, short *samples, unsigned char *block)
struct g72x_state * g72x_reader_init (int codec, int *blocksize, int *samplesperblock)
struct g72x_state * g72x_writer_init (int codec, int *blocksize, int *samplesperblock)
Macro Definition Documentation
G72x_BLOCK_SIZE
#define G72x_BLOCK_SIZE (3 * 5 * 8)
Referenced by g72x_close(), pack_bytes(), psf_g72x_decode_block(), psf_g72x_encode_block(), and unpack_bytes().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
G723_16_BITS_PER_SAMPLE
G723_24_BITS_PER_SAMPLE
G723_40_BITS_PER_SAMPLE
G721_32_BITS_PER_SAMPLE
G721_40_BITS_PER_SAMPLE
G723_16_SAMPLES_PER_BLOCK
G723_24_SAMPLES_PER_BLOCK
G723_40_SAMPLES_PER_BLOCK
G721_32_SAMPLES_PER_BLOCK
G721_40_SAMPLES_PER_BLOCK
G723_16_BYTES_PER_BLOCK
G723_24_BYTES_PER_BLOCK
G723_40_BYTES_PER_BLOCK
G721_32_BYTES_PER_BLOCK
G721_40_BYTES_PER_BLOCK
Function Documentation
g72x_reader_init()
struct g72x_state* g72x_reader_init (int codec, int * blocksize, int * samplesperblock)
References g72x_state::blocksize, g72x_state::codec_bits, g72x_state::decoder, g72x_state::encoder, G721_32_BITS_PER_SAMPLE, G721_32_BYTES_PER_BLOCK, G721_32_SAMPLES_PER_BLOCK, G721_40_BITS_PER_SAMPLE, G721_40_BYTES_PER_BLOCK, G721_40_SAMPLES_PER_BLOCK, g721_decoder(), G723_16_BITS_PER_SAMPLE, G723_16_BYTES_PER_BLOCK, g723_16_decoder(), G723_16_SAMPLES_PER_BLOCK, G723_24_BITS_PER_SAMPLE, G723_24_BYTES_PER_BLOCK, g723_24_decoder(), G723_24_SAMPLES_PER_BLOCK, g723_40_decoder(), g72x_state_new(), NULL, private_init_state(), and g72x_state::samplesperblock.
Referenced by g72x_init().
g72x_writer_init()
struct g72x_state* g72x_writer_init (int codec, int * blocksize, int * samplesperblock)
References g72x_state::blocksize, g72x_state::codec_bits, g72x_state::decoder, g72x_state::encoder, G721_32_BITS_PER_SAMPLE, G721_32_BYTES_PER_BLOCK, G721_32_SAMPLES_PER_BLOCK, G721_40_BITS_PER_SAMPLE, G721_40_BYTES_PER_BLOCK, G721_40_SAMPLES_PER_BLOCK, g721_encoder(), G723_16_BITS_PER_SAMPLE, G723_16_BYTES_PER_BLOCK, g723_16_encoder(), G723_16_SAMPLES_PER_BLOCK, G723_24_BITS_PER_SAMPLE, G723_24_BYTES_PER_BLOCK, g723_24_encoder(), G723_24_SAMPLES_PER_BLOCK, g723_40_encoder(), g72x_state_new(), NULL, private_init_state(), and g72x_state::samplesperblock.
Referenced by g72x_init().
g72x_decode_block()
int g72x_decode_block (struct g72x_state * pstate, const unsigned char * block, short * samples)
References g72x_state::blocksize, g72x_state::codec_bits, g72x_state::decoder, and unpack_bytes().
Referenced by psf_g72x_decode_block().
g72x_encode_block()
int g72x_encode_block (struct g72x_state * pstate, short * samples, unsigned char * block)
References g72x_state::codec_bits, g72x_state::encoder, pack_bytes(), and g72x_state::samplesperblock.
Referenced by psf_g72x_encode_block().