Aurora Framework: rf64.c File Reference
rf64.c File Reference
Macros
#define bext_MARKER MAKE_MARKER ('b', 'e', 'x', 't')
#define cart_MARKER MAKE_MARKER ('c', 'a', 'r', 't')
#define data_MARKER MAKE_MARKER ('d', 'a', 't', 'a')
#define ds64_MARKER MAKE_MARKER ('d', 's', '6', '4')
#define fact_MARKER MAKE_MARKER ('f', 'a', 'c', 't')
#define FFFF_MARKER MAKE_MARKER (0xff, 0xff, 0xff, 0xff)
#define fmt_MARKER MAKE_MARKER ('f', 'm', 't', ' ')
#define HAVE_CHUNK(CHUNK) ((parsestage & CHUNK) != 0)
#define JUNK_MARKER MAKE_MARKER ('J', 'U', 'N', 'K')
#define LIST_MARKER MAKE_MARKER ('L', 'I', 'S', 'T')
#define OggS_MARKER MAKE_MARKER ('O', 'g', 'g', 'S')
#define RF64_MARKER MAKE_MARKER ('R', 'F', '6', '4')
#define RIFF_DOWNGRADE_BYTES ((sf_count_t) 0xffffffff)
#define RIFF_MARKER MAKE_MARKER ('R', 'I', 'F', 'F')
#define WAVE_MARKER MAKE_MARKER ('W', 'A', 'V', 'E')
#define wvpk_MARKER MAKE_MARKER ('w', 'v', 'p', 'k')
Enumerations
enum {
HAVE_ds64 = 0x01, HAVE_fmt = 0x02, HAVE_bext = 0x04, HAVE_data = 0x08,
HAVE_cart = 0x10, HAVE_PEAK = 0x20, HAVE_other = 0x40
}
Functions
static int rf64_close (SF_PRIVATE *psf)
static int rf64_command (SF_PRIVATE *psf, int command, void *UNUSED(data), int datasize)
static int rf64_get_chunk_data (SF_PRIVATE *psf, const SF_CHUNK_ITERATOR *iterator, SF_CHUNK_INFO *chunk_info)
static int rf64_get_chunk_size (SF_PRIVATE *psf, const SF_CHUNK_ITERATOR *iterator, SF_CHUNK_INFO *chunk_info)
static SF_CHUNK_ITERATOR * rf64_next_chunk_iterator (SF_PRIVATE *psf, SF_CHUNK_ITERATOR *iterator)
int rf64_open (SF_PRIVATE *psf)
static int rf64_read_header (SF_PRIVATE *psf, int *blockalign, int *framesperblock)
static int rf64_set_chunk (SF_PRIVATE *psf, const SF_CHUNK_INFO *chunk_info)
static int rf64_write_fmt_chunk (SF_PRIVATE *psf)
static int rf64_write_header (SF_PRIVATE *psf, int calc_length)
static int rf64_write_tailer (SF_PRIVATE *psf)
Variables
static const EXT_SUBFORMAT MSGUID_SUBTYPE_ALAW
static const EXT_SUBFORMAT MSGUID_SUBTYPE_AMBISONIC_B_FORMAT_IEEE_FLOAT
static const EXT_SUBFORMAT MSGUID_SUBTYPE_AMBISONIC_B_FORMAT_PCM
static const EXT_SUBFORMAT MSGUID_SUBTYPE_IEEE_FLOAT
static const EXT_SUBFORMAT MSGUID_SUBTYPE_MULAW
static const EXT_SUBFORMAT MSGUID_SUBTYPE_PCM
Macro Definition Documentation
RF64_MARKER
#define RF64_MARKER MAKE_MARKER ('R', 'F', '6', '4')
Referenced by rf64_read_header(), and rf64_write_header().
RIFF_MARKER
#define RIFF_MARKER MAKE_MARKER ('R', 'I', 'F', 'F')
Referenced by rf64_write_header().
JUNK_MARKER
#define JUNK_MARKER MAKE_MARKER ('J', 'U', 'N', 'K')
Referenced by rf64_read_header(), and rf64_write_header().
FFFF_MARKER
#define FFFF_MARKER MAKE_MARKER (0xff, 0xff, 0xff, 0xff)
Referenced by rf64_read_header().
WAVE_MARKER
#define WAVE_MARKER MAKE_MARKER ('W', 'A', 'V', 'E')
Referenced by rf64_read_header(), and rf64_write_header().
ds64_MARKER
#define ds64_MARKER MAKE_MARKER ('d', 's', '6', '4')
Referenced by rf64_read_header(), and rf64_write_header().
fmt_MARKER
#define fmt_MARKER MAKE_MARKER ('f', 'm', 't', ' ')
Referenced by rf64_read_header(), and rf64_write_header().
fact_MARKER
#define fact_MARKER MAKE_MARKER ('f', 'a', 'c', 't')
Referenced by rf64_write_header().
data_MARKER
#define data_MARKER MAKE_MARKER ('d', 'a', 't', 'a')
Referenced by rf64_read_header(), and rf64_write_header().
bext_MARKER
#define bext_MARKER MAKE_MARKER ('b', 'e', 'x', 't')
Referenced by rf64_read_header(), wav_read_header(), and wavlike_write_bext_chunk().
cart_MARKER
#define cart_MARKER MAKE_MARKER ('c', 'a', 'r', 't')
Referenced by rf64_read_header(), wav_read_header(), and wavlike_write_cart_chunk().
OggS_MARKER
#define OggS_MARKER MAKE_MARKER ('O', 'g', 'g', 'S')
Referenced by rf64_read_header().
wvpk_MARKER
#define wvpk_MARKER MAKE_MARKER ('w', 'v', 'p', 'k')
Referenced by rf64_read_header().
LIST_MARKER
#define LIST_MARKER MAKE_MARKER ('L', 'I', 'S', 'T')
Referenced by rf64_read_header(), wav_read_header(), and wavlike_write_strings().
RIFF_DOWNGRADE_BYTES
#define RIFF_DOWNGRADE_BYTES ((sf_count_t) 0xffffffff)
Referenced by rf64_write_header().
HAVE_CHUNK
#define HAVE_CHUNK (CHUNK) ((parsestage & CHUNK) != 0)
Referenced by rf64_read_header().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
HAVE_ds64
HAVE_fmt
HAVE_bext
HAVE_data
HAVE_cart
HAVE_PEAK
HAVE_other
Function Documentation
rf64_read_header()
static int rf64_read_header (SF_PRIVATE * psf, int * blockalign, int * framesperblock) static
References bext_MARKER, MS_ADPCM_WAV_FMT::blockalign, IMA_ADPCM_WAV_FMT::blockalign, sf_private_tag::blockwidth, sf_private_tag::bytewidth, cart_MARKER, sf_private_tag::container_data, data_MARKER, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, done(), ds64_MARKER, sf_private_tag::endian, FFFF_MARKER, sf_private_tag::filelength, WAVLIKE_PRIVATE::fmt_is_broken, fmt_MARKER, WAV_FMT::format, HAVE_bext, HAVE_cart, HAVE_CHUNK, HAVE_data, HAVE_ds64, HAVE_fmt, HAVE_other, HAVE_PEAK, IBM_FORMAT_ALAW, IBM_FORMAT_MULAW, WAV_FMT::ima, INFO_MARKER, sf_private_tag::is_pipe, JUNK_MARKER, LIST_MARKER, WAV_FMT::msadpcm, NOT, NULL, OggS_MARKER, PAD_MARKER, sf_private_tag::peak_info, PEAK_INFO::peak_loc, PEAK_MARKER, psf_binheader_readf(), psf_fseek(), psf_ftell(), psf_log_printf(), psf_store_read_chunk_u32(), sf_private_tag::rchunks, RF64_MARKER, sf_private_tag::rwf_endian, MS_ADPCM_WAV_FMT::samplesperblock, IMA_ADPCM_WAV_FMT::samplesperblock, sf_private_tag::sf, SF_MAX_CHANNELS, SF_PEAK_END, SF_PEAK_START, SFE_CHANNEL_COUNT, SFE_CHANNEL_COUNT_ZERO, SFE_INTERNAL, SFE_RF64_NO_DATA, SFE_RF64_NOT_RF64, SFE_RF64_PEAK_B4_FMT, SFE_UNIMPLEMENTED, SFE_WAV_WVPK_DATA, SIGNED_SIZEOF, u_bitwidth_to_subformat(), WAVLIKE_PRIVATE::wav_fmt, WAVE_FORMAT_ALAW, WAVE_FORMAT_EXTENSIBLE, WAVE_FORMAT_G721_ADPCM, WAVE_FORMAT_GSM610, WAVE_FORMAT_IEEE_FLOAT, WAVE_FORMAT_IMA_ADPCM, WAVE_FORMAT_MS_ADPCM, WAVE_FORMAT_MULAW, WAVE_FORMAT_PCM, WAVE_MARKER, wavlike_analyze(), wavlike_read_bext_chunk(), wavlike_read_cart_chunk(), wavlike_read_fmt_chunk(), wavlike_read_peak_chunk(), wavlike_subchunk_parse(), and wvpk_MARKER.
Referenced by rf64_open().
rf64_write_header()
static int rf64_write_header (SF_PRIVATE * psf, int calc_length) static
References BHW4, BHW8, BHWm, BHWz, sf_private_tag::broadcast_16k, sf_private_tag::bytewidth, sf_private_tag::cart_16k, sf_private_tag::container_data, data_MARKER, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, ds64_MARKER, sf_private_tag::error, fact_MARKER, sf_private_tag::filelength, sf_private_tag::flags, fmt_MARKER, sf_private_tag::header, sf_private_tag::indx, sf_private_tag::instrument, JUNK_MARKER, NOT, NULL, PAD_MARKER, sf_private_tag::peak_info, PEAK_INFO::peak_loc, psf_binheader_writef(), psf_fseek(), psf_ftell(), psf_fwrite(), psf_get_filelen(), psf_log_printf(), sf_private_tag::ptr, WAVLIKE_PRIVATE::rf64_downgrade, RF64_MARKER, rf64_write_fmt_chunk(), RIFF_DOWNGRADE_BYTES, RIFF_MARKER, sf_private_tag::sf, SF_PEAK_START, SF_STR_LOCATE_START, SFE_INTERNAL, SFE_UNIMPLEMENTED, smpl_MARKER, sf_private_tag::strings, WRITE_CHUNKS::used, WAVE_MARKER, wavlike_write_bext_chunk(), wavlike_write_cart_chunk(), wavlike_write_custom_chunks(), wavlike_write_peak_chunk(), wavlike_write_strings(), and sf_private_tag::wchunks.
Referenced by rf64_close(), and rf64_open().
rf64_write_tailer()
static int rf64_write_tailer (SF_PRIVATE * psf) static
References BHWz, sf_private_tag::bytewidth, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::flags, sf_private_tag::header, sf_private_tag::indx, psf_binheader_writef(), psf_fseek(), psf_fwrite(), sf_private_tag::ptr, sf_private_tag::sf, SF_STR_LOCATE_END, sf_private_tag::strings, and wavlike_write_strings().
Referenced by rf64_close().
rf64_close()
static int rf64_close (SF_PRIVATE * psf) static
References sf_private_tag::file, PSF_FILE::mode, rf64_write_header(), and rf64_write_tailer().
Referenced by rf64_open().
rf64_command()
static int rf64_command (SF_PRIVATE * psf, int command, void * UNUSEDdata, int datasize) static
References sf_private_tag::channel_map, sf_private_tag::container_data, sf_private_tag::have_written, NULL, WAVLIKE_PRIVATE::rf64_downgrade, sf_private_tag::sf, SF_CONTAINER, SFE_INTERNAL, WAVLIKE_PRIVATE::wavex_ambisonic, WAVLIKE_PRIVATE::wavex_channelmask, and wavlike_gen_channel_mask().
Referenced by rf64_open().
rf64_set_chunk()
static int rf64_set_chunk (SF_PRIVATE * psf, const SF_CHUNK_INFO * chunk_info) static
References psf_save_write_chunk(), and sf_private_tag::wchunks.
Referenced by rf64_open().
rf64_next_chunk_iterator()
static SF_CHUNK_ITERATOR * rf64_next_chunk_iterator (SF_PRIVATE * psf, SF_CHUNK_ITERATOR * iterator) static
References psf_next_chunk_iterator(), and sf_private_tag::rchunks.
Referenced by rf64_open().
rf64_get_chunk_size()
static int rf64_get_chunk_size (SF_PRIVATE * psf, const SF_CHUNK_ITERATOR * iterator, SF_CHUNK_INFO * chunk_info) static
References READ_CHUNKS::chunks, READ_CHUNK::len, psf_find_read_chunk_iterator(), sf_private_tag::rchunks, SFE_NO_ERROR, and SFE_UNKNOWN_CHUNK.
Referenced by rf64_open().
rf64_get_chunk_data()
static int rf64_get_chunk_data (SF_PRIVATE * psf, const SF_CHUNK_ITERATOR * iterator, SF_CHUNK_INFO * chunk_info) static
References READ_CHUNKS::chunks, READ_CHUNK::id, READ_CHUNK::id_size, READ_CHUNK::len, memcpy(), NULL, READ_CHUNK::offset, psf_find_read_chunk_iterator(), psf_fread(), psf_fseek(), psf_ftell(), sf_private_tag::rchunks, SF_MIN, SFE_BAD_CHUNK_DATA_PTR, SFE_NO_ERROR, and SFE_UNKNOWN_CHUNK.
Referenced by rf64_open().
rf64_open()
int rf64_open (SF_PRIVATE * psf)
References alaw_init(), sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::command, sf_private_tag::container_close, sf_private_tag::container_data, double64_init(), sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, sf_private_tag::flags, float32_init(), sf_private_tag::get_chunk_data, sf_private_tag::get_chunk_size, sf_private_tag::is_pipe, PSF_FILE::mode, sf_private_tag::next_chunk_iterator, NULL, pcm_init(), rf64_close(), rf64_command(), rf64_get_chunk_data(), rf64_get_chunk_size(), rf64_next_chunk_iterator(), rf64_read_header(), rf64_set_chunk(), rf64_write_header(), sf_private_tag::set_chunk, sf_private_tag::sf, SF_STR_ALLOW_END, SF_STR_ALLOW_START, SFE_BAD_OPEN_FORMAT, SFE_MALLOC_FAILED, SFE_NO_PIPE_WRITE, SFE_UNIMPLEMENTED, sf_private_tag::strings, ulaw_init(), WAVLIKE_PRIVATE::wavex_ambisonic, and sf_private_tag::write_header.
Referenced by psf_open_file().
rf64_write_fmt_chunk()
static int rf64_write_fmt_chunk (SF_PRIVATE * psf) static
References BHW2, BHW4, sf_private_tag::bytewidth, sf_private_tag::container_data, MSGUID_SUBTYPE_ALAW, MSGUID_SUBTYPE_AMBISONIC_B_FORMAT_IEEE_FLOAT, MSGUID_SUBTYPE_AMBISONIC_B_FORMAT_PCM, MSGUID_SUBTYPE_IEEE_FLOAT, MSGUID_SUBTYPE_MULAW, MSGUID_SUBTYPE_PCM, NULL, psf_binheader_writef(), sf_private_tag::sf, SFE_INTERNAL, SFE_UNIMPLEMENTED, WAVE_FORMAT_EXTENSIBLE, WAVLIKE_PRIVATE::wavex_ambisonic, WAVLIKE_PRIVATE::wavex_channelmask, and wavlike_write_guid().
Referenced by rf64_write_header().
Variable Documentation
MSGUID_SUBTYPE_PCM
const EXT_SUBFORMAT MSGUID_SUBTYPE_PCM static
Initial value:
=
{   0x00000001, 0x0000, 0x0010, {   0x80, 0x00, 0x00, 0xaa, 0x00, 0x38, 0x9b, 0x71 }
}
Referenced by rf64_write_fmt_chunk().
MSGUID_SUBTYPE_IEEE_FLOAT
const EXT_SUBFORMAT MSGUID_SUBTYPE_IEEE_FLOAT static
Initial value:
=
{   0x00000003, 0x0000, 0x0010, {   0x80, 0x00, 0x00, 0xaa, 0x00, 0x38, 0x9b, 0x71 }
}
Referenced by rf64_write_fmt_chunk().
MSGUID_SUBTYPE_ALAW
const EXT_SUBFORMAT MSGUID_SUBTYPE_ALAW static
Initial value:
=
{   0x00000006, 0x0000, 0x0010, {   0x80, 0x00, 0x00, 0xaa, 0x00, 0x38, 0x9b, 0x71 }
}
Referenced by rf64_write_fmt_chunk().
MSGUID_SUBTYPE_MULAW
const EXT_SUBFORMAT MSGUID_SUBTYPE_MULAW static
Initial value:
=
{   0x00000007, 0x0000, 0x0010, {   0x80, 0x00, 0x00, 0xaa, 0x00, 0x38, 0x9b, 0x71 }
}
Referenced by rf64_write_fmt_chunk().
MSGUID_SUBTYPE_AMBISONIC_B_FORMAT_PCM
const EXT_SUBFORMAT MSGUID_SUBTYPE_AMBISONIC_B_FORMAT_PCM static
Initial value:
=
{   0x00000001, 0x0721, 0x11d3, {   0x86, 0x44, 0xC8, 0xC1, 0xCA, 0x00, 0x00, 0x00 }
}
Referenced by rf64_write_fmt_chunk().
MSGUID_SUBTYPE_AMBISONIC_B_FORMAT_IEEE_FLOAT
const EXT_SUBFORMAT MSGUID_SUBTYPE_AMBISONIC_B_FORMAT_IEEE_FLOAT static
Initial value:
=
{   0x00000003, 0x0721, 0x11d3, {   0x86, 0x44, 0xC8, 0xC1, 0xCA, 0x00, 0x00, 0x00 }
}
Referenced by rf64_write_fmt_chunk().