Aurora Framework: decode.c File Reference
decode.c File Reference
Functions
void Gsm_Decoder (struct gsm_state *S, int16_t *LARcr, int16_t *Ncr, int16_t *bcr, int16_t *Mcr, int16_t *xmaxcr, int16_t *xMcr, int16_t *s)
static void Postprocessing (struct gsm_state *S, register int16_t *s)
Function Documentation
Postprocessing()
static void Postprocessing (struct gsm_state * S, register int16_t * s) static
References GSM_ADD(), and GSM_MULT_R().
Referenced by Gsm_Decoder().
Gsm_Decoder()
void Gsm_Decoder (struct gsm_state * S, int16_t * LARcr, int16_t * Ncr, int16_t * bcr, int16_t * Mcr, int16_t * xmaxcr, int16_t * xMcr, int16_t * s)
References Gsm_Long_Term_Synthesis_Filtering(), Gsm_RPE_Decoding(), Gsm_Short_Term_Synthesis_Filter(), and Postprocessing().
Referenced by gsm_decode().