Aurora Framework: g721.c File Reference
g721.c File Reference
Functions
int g721_decoder (int i, G72x_STATE *state_ptr)
int g721_encoder (int sl, G72x_STATE *state_ptr)
Variables
static short _dqlntab [16]
static short _fitab [16]
static short _witab [16]
static short qtab_721 [7] = { -124, 80, 178, 246, 300, 349, 400 }
Function Documentation
g721_encoder()
int g721_encoder (int sl, G72x_STATE * state_ptr)
References _dqlntab, _fitab, _witab, arith_shift_left(), predictor_pole(), predictor_zero(), qtab_721, quantize(), reconstruct(), step_size(), and update().
Referenced by g72x_writer_init().
g721_decoder()
int g721_decoder (int i, G72x_STATE * state_ptr)
References _dqlntab, _fitab, _witab, arith_shift_left(), predictor_pole(), predictor_zero(), reconstruct(), step_size(), and update().
Referenced by g72x_reader_init().
Variable Documentation
qtab_721
short qtab_721[7] = { -124, 80, 178, 246, 300, 349, 400 } static
Referenced by g721_encoder().
_dqlntab
short _dqlntab[16] static
Initial value:
= { -2048, 4, 135, 213, 273, 323, 373, 425,
                            425, 373, 323, 273, 213, 135, 4, -2048 }
Referenced by g721_decoder(), and g721_encoder().
_witab
short _witab[16] static
Initial value:
= { -12, 18, 41, 64, 112, 198, 355, 1122,
                            1122, 355, 198, 112, 64, 41, 18, -12 }
Referenced by g721_decoder(), and g721_encoder().
_fitab
short _fitab[16] static
Initial value:
= { 0, 0, 0, 0x200, 0x200, 0x200, 0x600, 0xE00,
                            0xE00, 0x600, 0x200, 0x200, 0x200, 0, 0, 0 }
Referenced by g721_decoder(), and g721_encoder().