Aurora Framework: file_io.c File Reference
file_io.c File Reference
Macros
#define O_BINARY 0
#define SENSIBLE_SIZE (0x40000000)
Functions
static int psf_close_fd (int fd)
int psf_close_rsrc (SF_PRIVATE *psf)
int psf_fclose (SF_PRIVATE *psf)
sf_count_t psf_fgets (char *buffer, sf_count_t bufsize, SF_PRIVATE *psf)
int psf_file_valid (SF_PRIVATE *psf)
int psf_fopen (SF_PRIVATE *psf)
sf_count_t psf_fread (void *ptr, sf_count_t bytes, sf_count_t items, SF_PRIVATE *psf)
sf_count_t psf_fseek (SF_PRIVATE *psf, sf_count_t offset, int whence)
void psf_fsync (SF_PRIVATE *psf)
sf_count_t psf_ftell (SF_PRIVATE *psf)
int psf_ftruncate (SF_PRIVATE *psf, sf_count_t len)
sf_count_t psf_fwrite (const void *ptr, sf_count_t bytes, sf_count_t items, SF_PRIVATE *psf)
sf_count_t psf_get_filelen (SF_PRIVATE *psf)
static sf_count_t psf_get_filelen_fd (int fd)
void psf_init_files (SF_PRIVATE *psf)
int psf_is_pipe (SF_PRIVATE *psf)
static void psf_log_syserr (SF_PRIVATE *psf, int error)
static int psf_open_fd (PSF_FILE *pfile)
int psf_open_rsrc (SF_PRIVATE *psf)
void psf_set_file (SF_PRIVATE *psf, int fd)
int psf_set_stdio (SF_PRIVATE *psf)
void psf_use_rsrc (SF_PRIVATE *psf, int on_off)
Macro Definition Documentation
SENSIBLE_SIZE
#define SENSIBLE_SIZE (0x40000000)
Referenced by psf_fread(), and psf_fwrite().
O_BINARY
#define O_BINARY 0
Referenced by psf_open_fd().
Function Documentation
psf_log_syserr()
static void psf_log_syserr (SF_PRIVATE * psf, int error) static
References sf_private_tag::error, SFE_SYSTEM, and sf_private_tag::syserr.
Referenced by psf_fclose(), psf_fgets(), psf_fopen(), psf_fread(), psf_fseek(), psf_ftell(), psf_ftruncate(), psf_fwrite(), psf_get_filelen(), psf_is_pipe(), and psf_open_rsrc().
psf_close_fd()
static int psf_close_fd (int fd) static
Referenced by psf_close_rsrc(), psf_fclose(), and psf_open_rsrc().
psf_open_fd()
static int psf_open_fd (PSF_FILE * pfile) static
References PSF_FILE::c, mode(), PSF_FILE::mode, O_BINARY, PSF_FILE::path, S_IRGRP, S_IROTH, S_IRUSR, S_IWGRP, S_IWOTH, S_IWUSR, and SFE_BAD_OPEN_MODE.
Referenced by psf_fopen(), and psf_open_rsrc().
psf_get_filelen_fd()
static sf_count_t psf_get_filelen_fd (int fd) static
Referenced by psf_get_filelen(), and psf_open_rsrc().
psf_fopen()
int psf_fopen (SF_PRIVATE * psf)
References sf_private_tag::error, sf_private_tag::file, PSF_FILE::filedes, psf_log_syserr(), psf_open_fd(), and SFE_BAD_OPEN_MODE.
Referenced by sf_open().
psf_fclose()
int psf_fclose (SF_PRIVATE * psf)
References PSF_FILE::do_not_close_descriptor, sf_private_tag::file, PSF_FILE::filedes, psf_close_fd(), psf_log_syserr(), and sf_private_tag::virtual_io.
Referenced by psf_close().
psf_open_rsrc()
int psf_open_rsrc (SF_PRIVATE * psf)
References PSF_FILE::c, PSF_FILE::dir, sf_private_tag::error, sf_private_tag::file, PSF_FILE::filedes, PSF_FILE::mode, PSF_FILE::name, PSF_FILE::path, psf_close_fd(), psf_get_filelen_fd(), psf_log_syserr(), psf_open_fd(), sf_private_tag::rsrc, sf_private_tag::rsrclength, SFE_BAD_OPEN_MODE, and SFE_NO_ERROR.
Referenced by sd2_open(), and try_resource_fork().
psf_get_filelen()
sf_count_t psf_get_filelen (SF_PRIVATE * psf)
References sf_private_tag::error, sf_private_tag::file, PSF_FILE::filedes, sf_private_tag::filelength, sf_private_tag::fileoffset, PSF_FILE::mode, psf_get_filelen_fd(), psf_log_syserr(), SFE_BAD_STAT_SIZE, sf_private_tag::vio, sf_private_tag::vio_user_data, and sf_private_tag::virtual_io.
Referenced by aiff_write_header(), au_write_header(), avr_write_header(), caf_write_header(), dpcm_init(), g72x_init(), gsm610_init(), htk_write_header(), ima_reader_init(), mat4_write_header(), mpc2k_write_header(), nist_write_header(), nms_adpcm_init(), paf24_init(), psf_open_file(), rf64_write_header(), sd2_parse_rsrc_fork(), svx_write_header(), voc_write_header(), w64_write_header(), wav_write_header(), and wve_write_header().
psf_close_rsrc()
int psf_close_rsrc (SF_PRIVATE * psf)
References PSF_FILE::filedes, psf_close_fd(), and sf_private_tag::rsrc.
Referenced by psf_close(), and sd2_open().
psf_set_stdio()
int psf_set_stdio (SF_PRIVATE * psf)
References sf_private_tag::file, PSF_FILE::filedes, sf_private_tag::filelength, PSF_FILE::mode, SFE_BAD_OPEN_MODE, and SFE_OPEN_PIPE_RDWR.
Referenced by sf_open().
psf_set_file()
void psf_set_file (SF_PRIVATE * psf, int fd)
References sf_private_tag::file, and PSF_FILE::filedes.
Referenced by sf_open_fd().
psf_file_valid()
int psf_file_valid (SF_PRIVATE * psf)
References sf_private_tag::file, and PSF_FILE::filedes.
Referenced by sd2_open().
psf_fseek()
sf_count_t psf_fseek (SF_PRIVATE * psf, sf_count_t offset, int whence)
References sf_private_tag::file, PSF_FILE::filedes, sf_private_tag::fileoffset, sf_private_tag::is_pipe, sf_private_tag::pipeoffset, psf_log_printf(), psf_log_syserr(), sf_private_tag::vio, sf_private_tag::vio_user_data, and sf_private_tag::virtual_io.
Referenced by aiff_get_chunk_data(), aiff_ima_seek(), aiff_open(), aiff_read_header(), aiff_rewrite_header(), aiff_write_header(), aiff_write_tailer(), alac_decode_block(), alac_kuki_read(), alac_seek(), au_write_header(), avr_write_header(), caf_get_chunk_data(), caf_read_header(), caf_write_header(), caf_write_tailer(), dpcm_seek(), dwvw_seek(), gsm610_init(), gsm610_seek(), header_seek(), htk_write_header(), interleave_read_double(), interleave_read_float(), interleave_read_int(), interleave_read_short(), ircam_write_header(), mat4_write_header(), mat5_write_header(), mpc2k_write_header(), msadpcm_seek(), nist_read_header(), nist_write_header(), nms_adpcm_seek(), paf24_seek(), psf_decode_frame_count(), psf_default_seek(), psf_open_file(), pvf_write_header(), rf64_get_chunk_data(), rf64_read_header(), rf64_write_header(), rf64_write_tailer(), sd2_open(), sds_open(), sds_read_header(), sds_seek(), sds_write_header(), sf_command(), svx_open(), svx_read_header(), svx_write_header(), voc_close(), voc_write_header(), vox_adpcm_init(), w64_read_header(), w64_write_header(), wav_get_chunk_data(), wav_read_header(), wav_write_header(), wav_write_tailer(), wavlike_analyze(), wavlike_ima_seek(), wavlike_subchunk_parse(), wve_write_header(), xi_read_header(), and xi_write_header().
psf_fread()
sf_count_t psf_fread (void * ptr, sf_count_t bytes, sf_count_t items, SF_PRIVATE * psf)
References sf_private_tag::file, PSF_FILE::filedes, sf_private_tag::is_pipe, sf_private_tag::pipeoffset, psf_log_syserr(), SENSIBLE_SIZE, ssize_t, sf_private_tag::vio, sf_private_tag::vio_user_data, and sf_private_tag::virtual_io.
Referenced by aiff_get_chunk_data(), aiff_ima_decode_block(), aiff_rewrite_header(), alac_decode_block(), alac_kuki_read(), alaw_read_alaw2d(), alaw_read_alaw2f(), alaw_read_alaw2i(), alaw_read_alaw2s(), caf_get_chunk_data(), dpcm_read_dles2d(), dpcm_read_dles2f(), dpcm_read_dles2i(), dpcm_read_dles2s(), dpcm_read_dsc2d(), dpcm_read_dsc2f(), dpcm_read_dsc2i(), dpcm_read_dsc2s(), dwvw_decode_load_bits(), gsm610_decode_block(), gsm610_wav_decode_block(), header_gets(), header_read(), header_seek(), host_read_d(), host_read_d2f(), host_read_d2i(), host_read_d2s(), host_read_f(), host_read_f2d(), host_read_f2i(), host_read_f2s(), msadpcm_decode_block(), paf24_read_block(), pcm_read_bei2d(), pcm_read_bei2f(), pcm_read_bei2i(), pcm_read_bei2s(), pcm_read_bes2d(), pcm_read_bes2f(), pcm_read_bes2i(), pcm_read_bes2s(), pcm_read_bet2d(), pcm_read_bet2f(), pcm_read_bet2i(), pcm_read_bet2s(), pcm_read_lei2d(), pcm_read_lei2f(), pcm_read_lei2i(), pcm_read_lei2s(), pcm_read_les2d(), pcm_read_les2f(), pcm_read_les2i(), pcm_read_les2s(), pcm_read_let2d(), pcm_read_let2f(), pcm_read_let2i(), pcm_read_let2s(), pcm_read_sc2d(), pcm_read_sc2f(), pcm_read_sc2i(), pcm_read_sc2s(), pcm_read_uc2d(), pcm_read_uc2f(), pcm_read_uc2i(), pcm_read_uc2s(), psf_g72x_decode_block(), psf_nms_adpcm_decode_block(), replace_read_d(), replace_read_d2f(), replace_read_d2i(), replace_read_d2s(), replace_read_f(), replace_read_f2d(), replace_read_f2i(), replace_read_f2s(), rf64_get_chunk_data(), sd2_parse_rsrc_fork(), sds_2byte_read(), sds_3byte_read(), sds_4byte_read(), sds_read_header(), sf_read_raw(), ulaw_read_ulaw2d(), ulaw_read_ulaw2f(), ulaw_read_ulaw2i(), ulaw_read_ulaw2s(), vox_read_block(), wav_get_chunk_data(), wavlike_analyze(), and wavlike_ima_decode_block().
psf_fwrite()
sf_count_t psf_fwrite (const void * ptr, sf_count_t bytes, sf_count_t items, SF_PRIVATE * psf)
References sf_private_tag::file, PSF_FILE::filedes, sf_private_tag::is_pipe, sf_private_tag::pipeoffset, psf_log_syserr(), SENSIBLE_SIZE, ssize_t, sf_private_tag::vio, sf_private_tag::vio_user_data, and sf_private_tag::virtual_io.
Referenced by aiff_ima_encode_block(), aiff_rewrite_header(), aiff_write_header(), aiff_write_tailer(), alac_close(), alaw_write_d2alaw(), alaw_write_f2alaw(), alaw_write_i2alaw(), alaw_write_s2alaw(), au_write_header(), avr_write_header(), caf_write_header(), caf_write_tailer(), dpcm_write_d2dles(), dpcm_write_d2dsc(), dpcm_write_f2dles(), dpcm_write_f2dsc(), dpcm_write_i2dles(), dpcm_write_i2dsc(), dpcm_write_s2dles(), dpcm_write_s2dsc(), dwvw_close(), dwvw_encode_store_bits(), gsm610_encode_block(), gsm610_wav_encode_block(), host_write_d(), host_write_d2f(), host_write_f(), host_write_f2d(), host_write_i2d(), host_write_i2f(), host_write_s2d(), host_write_s2f(), htk_write_header(), ircam_write_header(), mat4_write_header(), mat5_write_header(), mpc2k_write_header(), msadpcm_encode_block(), nist_write_header(), paf24_write_block(), paf_write_header(), pcm_write_d2bei(), pcm_write_d2bes(), pcm_write_d2bet(), pcm_write_d2lei(), pcm_write_d2les(), pcm_write_d2let(), pcm_write_d2sc(), pcm_write_d2uc(), pcm_write_f2bei(), pcm_write_f2bes(), pcm_write_f2bet(), pcm_write_f2lei(), pcm_write_f2les(), pcm_write_f2let(), pcm_write_f2sc(), pcm_write_f2uc(), pcm_write_i2bei(), pcm_write_i2bes(), pcm_write_i2bet(), pcm_write_i2lei(), pcm_write_i2les(), pcm_write_i2let(), pcm_write_i2sc(), pcm_write_i2uc(), pcm_write_s2bei(), pcm_write_s2bes(), pcm_write_s2bet(), pcm_write_s2lei(), pcm_write_s2les(), pcm_write_s2let(), pcm_write_s2sc(), pcm_write_s2uc(), psf_g72x_encode_block(), psf_nms_adpcm_encode_block(), pvf_write_header(), replace_write_d(), replace_write_d2f(), replace_write_f(), replace_write_f2d(), replace_write_i2d(), replace_write_i2f(), replace_write_s2d(), replace_write_s2f(), rf64_write_header(), rf64_write_tailer(), sd2_write_rsrc_fork(), sds_2byte_write(), sds_3byte_write(), sds_4byte_write(), sds_write_header(), sf_write_raw(), svx_write_header(), ulaw_write_d2ulaw(), ulaw_write_f2ulaw(), ulaw_write_i2ulaw(), ulaw_write_s2ulaw(), voc_close(), voc_write_header(), vox_write_block(), w64_write_header(), wav_write_header(), wav_write_tailer(), wavlike_ima_encode_block(), wve_write_header(), and xi_write_header().
psf_ftell()
sf_count_t psf_ftell (SF_PRIVATE * psf)
References sf_private_tag::file, PSF_FILE::filedes, sf_private_tag::fileoffset, sf_private_tag::is_pipe, sf_private_tag::pipeoffset, psf_log_syserr(), sf_private_tag::vio, sf_private_tag::vio_user_data, and sf_private_tag::virtual_io.
Referenced by aiff_get_chunk_data(), aiff_read_header(), aiff_write_header(), au_read_header(), au_write_header(), avr_read_header(), avr_write_header(), caf_get_chunk_data(), caf_read_header(), caf_write_header(), htk_write_header(), ircam_write_header(), mat4_read_header(), mat4_write_header(), mat5_read_header(), mat5_write_header(), mpc2k_read_header(), mpc2k_write_header(), nist_write_header(), paf_write_header(), psf_binheader_readf(), psf_open_file(), pvf_read_header(), pvf_write_header(), rf64_get_chunk_data(), rf64_read_header(), rf64_write_header(), sds_write_header(), sf_open_fd(), svx_read_header(), svx_write_header(), voc_write_header(), vox_read_block(), w64_read_header(), w64_write_header(), wav_close(), wav_get_chunk_data(), wav_read_header(), wav_write_header(), wve_write_header(), xi_read_header(), and xi_write_header().
psf_fgets()
sf_count_t psf_fgets (char * buffer, sf_count_t bufsize, SF_PRIVATE * psf)
References sf_private_tag::file, PSF_FILE::filedes, and psf_log_syserr().
psf_is_pipe()
int psf_is_pipe (SF_PRIVATE * psf)
References sf_private_tag::file, PSF_FILE::filedes, psf_log_syserr(), S_ISFIFO, and sf_private_tag::virtual_io.
Referenced by psf_decode_frame_count(), psf_open_file(), and sf_open_fd().
psf_ftruncate()
int psf_ftruncate (SF_PRIVATE * psf, sf_count_t len)
References sf_private_tag::file, PSF_FILE::filedes, and psf_log_syserr().
Referenced by sf_command(), and wav_close().
psf_init_files()
void psf_init_files (SF_PRIVATE * psf)
References sf_private_tag::file, PSF_FILE::filedes, sf_private_tag::rsrc, and PSF_FILE::savedes.
Referenced by sf_open(), sf_open_fd(), and sf_open_virtual().
psf_use_rsrc()
void psf_use_rsrc (SF_PRIVATE * psf, int on_off)
References sf_private_tag::file, PSF_FILE::filedes, sf_private_tag::rsrc, and PSF_FILE::savedes.
Referenced by sd2_open(), sd2_parse_rsrc_fork(), and sd2_write_rsrc_fork().
psf_fsync()
void psf_fsync (SF_PRIVATE * psf)
References sf_private_tag::file, PSF_FILE::filedes, PSF_FILE::mode, and NULL.
Referenced by sf_write_sync().