Aurora Framework: alac_decoder.c File Reference
alac_decoder.c File Reference
Enumerations
enum bool {
false = 0, true = 1, false = 0, ALAC_TRUE = 1,
false = 0, true = 1
}
Functions
static int32_t alac_data_stream_element (struct BitBuffer *bits)
int32_t alac_decode (ALAC_DECODER *p, struct BitBuffer *bits, int32_t *sampleBuffer, uint32_t numSamples, uint32_t *outNumSamples)
int32_t alac_decoder_init (ALAC_DECODER *p, void *inMagicCookie, uint32_t inMagicCookieSize)
static int32_t alac_fill_element (struct BitBuffer *bits)
static void Zero32 (int32_t *buffer, uint32_t numItems, uint32_t stride)
Variables
const uint32_t kMaxBitDepth = 32
Enumeration Type Documentation
bool
enum bool
Enumerator
false
true
false
ALAC_TRUE
false
true
Function Documentation
alac_fill_element()
static int32_t alac_fill_element (struct BitBuffer * bits) static
References ALAC_noErr, BitBufferAdvance(), BitBufferReadSmall(), BitBuffer::cur, BitBuffer::end, kALAC_ParamError, and RequireAction.
Referenced by alac_decode().
alac_data_stream_element()
static int32_t alac_data_stream_element (struct BitBuffer * bits) static
References ALAC_noErr, BitBufferAdvance(), BitBufferByteAlign(), BitBufferReadOne(), BitBufferReadSmall(), BitBuffer::cur, BitBuffer::end, kALAC_ParamError, and RequireAction.
Referenced by alac_decode().
Zero32()
static void Zero32 (int32_t * buffer, uint32_t numItems, uint32_t stride) static
References memset().
Referenced by alac_decode().
alac_decoder_init()
int32_t alac_decoder_init (ALAC_DECODER * p, void * inMagicCookie, uint32_t inMagicCookieSize)
References ALAC_FRAME_LENGTH, ALAC_noErr, ALACSpecificConfig::avgBitRate, ALACSpecificConfig::bitDepth, ALACSpecificConfig::compatibleVersion, fALAC_FrameLengthError, ALACSpecificConfig::frameLength, kALAC_BadBitWidth, kALAC_BadSpecificConfigSize, kALAC_IncompatibleVersion, kALAC_MemFullError, kALACVersion, ALACSpecificConfig::kb, ALACSpecificConfig::maxFrameBytes, ALACSpecificConfig::maxRun, ALACSpecificConfig::mb, alac_decoder_s::mConfig, alac_decoder_s::mMixBufferU, alac_decoder_s::mMixBufferV, alac_decoder_s::mNumChannels, alac_decoder_s::mPredictor, NULL, ALACSpecificConfig::numChannels, ALACSpecificConfig::pb, psf_get_be16(), psf_get_be32(), RequireAction, and ALACSpecificConfig::sampleRate.
Referenced by alac_reader_init().
alac_decode()
int32_t alac_decode (ALAC_DECODER * p, struct BitBuffer * bits, int32_t * sampleBuffer, uint32_t numSamples, uint32_t * outNumSamples)
References alac_data_stream_element(), alac_fill_element(), ALAC_noErr, arith_shift_left(), BitBufferAdvance(), BitBufferByteAlign(), BitBufferRead(), BitBufferReadSmall(), ALACSpecificConfig::bitDepth, copyPredictorTo20(), copyPredictorTo24(), copyPredictorTo24Shift(), copyPredictorTo32(), copyPredictorTo32Shift(), BitBuffer::cur, dyn_decomp(), BitBuffer::end, ID_CCE, ID_CPE, ID_DSE, ID_END, ID_FIL, ID_LFE, ID_PCE, ID_SCE, kALAC_NumSamplesTooBig, kALAC_ParamError, kALAC_UnsupportedElement, kALAC_ZeroChannelCount, kALACDefaultFramesPerPacket, ALACSpecificConfig::kb, alac_decoder_s::mActiveElements, ALACSpecificConfig::maxRun, ALACSpecificConfig::mb, alac_decoder_s::mConfig, alac_decoder_s::mMixBufferU, alac_decoder_s::mMixBufferV, alac_decoder_s::mNumChannels, alac_decoder_s::mPredictor, alac_decoder_s::mShiftBuffer, NULL, ALACSpecificConfig::pb, RequireAction, RequireNoErr, set_ag_params(), unmix16(), unmix20(), unmix24(), unmix32(), unpc_block(), and Zero32().
Referenced by alac_decode_block().
Variable Documentation
kMaxBitDepth
const uint32_t kMaxBitDepth = 32