Aurora Framework: Context.m File Reference
Context.m File Reference
Macros
#define addAttrib(a)
#define setAttrib(a, v) { addAttrib(a); addAttrib(v); }
Functions
GLFWbool _glfwCreateContextNSGL (_GLFWwindow *window, const _GLFWctxconfig *ctxconfig, const _GLFWfbconfig *fbconfig)
GLFWbool _glfwInitNSGL (void)
void _glfwTerminateNSGL (void)
static void destroyContextNSGL (_GLFWwindow *window)
static int extensionSupportedNSGL (const char *extension)
static GLFWglproc getProcAddressNSGL (const char *procname)
GLFWAPI id glfwGetNSGLContext (GLFWwindow *handle)
static void makeContextCurrentNSGL (_GLFWwindow *window)
static void swapBuffersNSGL (_GLFWwindow *window)
static void swapIntervalNSGL (int interval)
Macro Definition Documentation
addAttrib
#define addAttrib (a)
Value:
{ \
    assert((size_t) index < sizeof(attribs) / sizeof(attribs[0])); \
    attribs[index++] = a; \
}
Referenced by _glfwCreateContextNSGL().
setAttrib
#define setAttrib (a, v) { addAttrib(a); addAttrib(v); }
Referenced by _glfwCreateContextNSGL().
Function Documentation
makeContextCurrentNSGL()
static void makeContextCurrentNSGL (_GLFWwindow * window) static
References _glfw, _glfwPlatformSetTls(), and _GLFWlibrary::contextSlot.
Referenced by _glfwCreateContextNSGL().
swapBuffersNSGL()
static void swapBuffersNSGL (_GLFWwindow * window) static
Referenced by _glfwCreateContextNSGL().
swapIntervalNSGL()
static void swapIntervalNSGL (int interval) static
References _glfw, _glfwPlatformGetTls(), and _GLFWlibrary::contextSlot.
Referenced by _glfwCreateContextNSGL().
extensionSupportedNSGL()
static int extensionSupportedNSGL (const char * extension) static
References GLFW_FALSE.
Referenced by _glfwCreateContextNSGL().
getProcAddressNSGL()
static GLFWglproc getProcAddressNSGL (const char * procname) static
References _glfw.
Referenced by _glfwCreateContextNSGL().
destroyContextNSGL()
static void destroyContextNSGL (_GLFWwindow * window) static
References _GLFWwindow::context.
Referenced by _glfwCreateContextNSGL().
_glfwInitNSGL()
GLFWbool _glfwInitNSGL (void)
References _glfw, _glfwInputError(), GLFW_API_UNAVAILABLE, GLFW_FALSE, GLFW_TRUE, and NULL.
Referenced by _glfwPlatformCreateWindow().
_glfwTerminateNSGL()
void _glfwTerminateNSGL (void)
Referenced by _glfwPlatformTerminate().
_glfwCreateContextNSGL()
GLFWbool _glfwCreateContextNSGL (_GLFWwindow * window, const _GLFWctxconfig * ctxconfig, const _GLFWfbconfig * fbconfig)
References _glfwInputError(), _GLFWfbconfig::accumAlphaBits, _GLFWfbconfig::accumBlueBits, _GLFWfbconfig::accumGreenBits, _GLFWfbconfig::accumRedBits, addAttrib, _GLFWfbconfig::alphaBits, _GLFWfbconfig::auxBuffers, _GLFWfbconfig::blueBits, _GLFWctxconfig::client, _GLFWwindow::context, _GLFWfbconfig::depthBits, _GLFWcontext::destroy, destroyContextNSGL(), _GLFWfbconfig::doublebuffer, _GLFWcontext::extensionSupported, extensionSupportedNSGL(), _GLFWctxconfig::forward, _GLFWcontext::getProcAddress, getProcAddressNSGL(), GLFW_API_UNAVAILABLE, GLFW_DONT_CARE, GLFW_FALSE, GLFW_FORMAT_UNAVAILABLE, GLFW_OPENGL_CORE_PROFILE, GLFW_OPENGL_ES_API, GLFW_TRUE, GLFW_VERSION_UNAVAILABLE, _GLFWfbconfig::greenBits, _GLFWctxconfig::major, makeContextCurrentNSGL(), _GLFWcontext::makeCurrent, _GLFWctxconfig::minor, _GLFWctxconfig::nsgl, NULL, _GLFWctxconfig::offline, _GLFWctxconfig::profile, _GLFWfbconfig::redBits, _GLFWfbconfig::samples, setAttrib, _GLFWctxconfig::share, _GLFWfbconfig::stencilBits, _GLFWfbconfig::stereo, _GLFWcontext::swapBuffers, swapBuffersNSGL(), _GLFWcontext::swapInterval, swapIntervalNSGL(), and _GLFWfbconfig::transparent.
Referenced by _glfwPlatformCreateWindow().
glfwGetNSGLContext()
GLFWAPI id glfwGetNSGLContext (GLFWwindow * handle)
References _GLFW_REQUIRE_INIT_OR_RETURN, _glfwInputError(), _GLFWcontext::client, _GLFWwindow::context, GLFW_NO_API, GLFW_NO_WINDOW_CONTEXT, and NULL.