Aurora Framework: Monitor.c File Reference
Mir/Monitor.c File Reference
Functions
void _glfwPlatformFreeMonitor (_GLFWmonitor *monitor)
void _glfwPlatformGetGammaRamp (_GLFWmonitor *monitor, GLFWgammaramp *ramp)
void _glfwPlatformGetMonitorContentScale (_GLFWmonitor *monitor, float *xscale, float *yscale)
void _glfwPlatformGetMonitorPos (_GLFWmonitor *monitor, int *xpos, int *ypos)
void _glfwPlatformGetVideoMode (_GLFWmonitor *monitor, GLFWvidmode *mode)
GLFWvidmode * _glfwPlatformGetVideoModes (_GLFWmonitor *monitor, int *found)
void _glfwPlatformSetGammaRamp (_GLFWmonitor *monitor, const GLFWgammaramp *ramp)
void _glfwPollMonitorsMir (void)
static void FillInRGBBitsFromPixelFormat (GLFWvidmode *mode, const MirPixelFormat pf)
GLFWAPI int glfwGetMirMonitor (GLFWmonitor *handle)
Function Documentation
_glfwPollMonitorsMir()
void _glfwPollMonitorsMir (void)
References _glfw, _GLFW_INSERT_LAST, _glfwAllocMonitor(), _glfwInputMonitor(), _glfwPlatformGetVideoModes(), GLFW_CONNECTED, _GLFWmonitor::modeCount, _GLFWmonitor::modes, and setup::name.
Referenced by _glfwPlatformInit().
_glfwPlatformFreeMonitor()
void _glfwPlatformFreeMonitor (_GLFWmonitor * monitor)
_glfwPlatformGetMonitorPos()
void _glfwPlatformGetMonitorPos (_GLFWmonitor * monitor, int * xpos, int * ypos)
_glfwPlatformGetMonitorContentScale()
void _glfwPlatformGetMonitorContentScale (_GLFWmonitor * monitor, float * xscale, float * yscale)
FillInRGBBitsFromPixelFormat()
static void FillInRGBBitsFromPixelFormat (GLFWvidmode * mode, const MirPixelFormat pf) static
References mode().
Referenced by _glfwPlatformGetVideoModes().
_glfwPlatformGetVideoModes()
GLFWvidmode* _glfwPlatformGetVideoModes (_GLFWmonitor * monitor, int * found)
References _glfw, _glfwInputError(), FillInRGBBitsFromPixelFormat(), GLFW_PLATFORM_ERROR, height, GLFWvidmode::height, mode(), NULL, GLFWvidmode::refreshRate, width, and GLFWvidmode::width.
Referenced by _glfwPollMonitorsMir().
_glfwPlatformGetVideoMode()
void _glfwPlatformGetVideoMode (_GLFWmonitor * monitor, GLFWvidmode * mode)
References mode(), and _GLFWmonitor::modes.
_glfwPlatformGetGammaRamp()
void _glfwPlatformGetGammaRamp (_GLFWmonitor * monitor, GLFWgammaramp * ramp)
References _glfwInputError(), and GLFW_PLATFORM_ERROR.
_glfwPlatformSetGammaRamp()
void _glfwPlatformSetGammaRamp (_GLFWmonitor * monitor, const GLFWgammaramp * ramp)
References _glfwInputError(), and GLFW_PLATFORM_ERROR.
glfwGetMirMonitor()
GLFWAPI int glfwGetMirMonitor (GLFWmonitor * handle)
References _GLFW_REQUIRE_INIT_OR_RETURN.