Aurora Framework: Joystick.c File Reference
Linux/Joystick.c File Reference
Macros
#define isBitSet(bit, arr) (arr[(bit) / 8] & (1 << ((bit) % 8)))
#define SYN_DROPPED 3
Functions
void _glfwDetectJoystickConnectionLinux (void)
GLFWbool _glfwInitJoysticksLinux (void)
int _glfwPlatformPollJoystick (_GLFWjoystick *js, int mode)
void _glfwPlatformUpdateGamepadGUID (char *guid)
void _glfwTerminateJoysticksLinux (void)
static void closeJoystick (_GLFWjoystick *js)
static int compareJoysticks (const void *fp, const void *sp)
static void handleAbsEvent (_GLFWjoystick *js, int code, int value)
static void handleKeyEvent (_GLFWjoystick *js, int code, int value)
static GLFWbool openJoystickDevice (const char *path)
static void pollAbsState (_GLFWjoystick *js)
Macro Definition Documentation
SYN_DROPPED
#define SYN_DROPPED 3
Referenced by _glfwPlatformPollJoystick().
isBitSet
#define isBitSet (bit, arr) (arr[(bit) / 8] & (1 << ((bit) % 8)))
Referenced by openJoystickDevice().
Function Documentation
handleKeyEvent()
static void handleKeyEvent (_GLFWjoystick * js, int code, int value) static
References _glfwInputJoystickButton(), GLFW_PRESS, GLFW_RELEASE, and value.
Referenced by _glfwPlatformPollJoystick().
handleAbsEvent()
static void handleAbsEvent (_GLFWjoystick * js, int code, int value) static
References _glfwInputJoystickAxis(), _glfwInputJoystickHat(), GLFW_HAT_CENTERED, GLFW_HAT_DOWN, GLFW_HAT_LEFT, GLFW_HAT_LEFT_DOWN, GLFW_HAT_LEFT_UP, GLFW_HAT_RIGHT, GLFW_HAT_RIGHT_DOWN, GLFW_HAT_RIGHT_UP, GLFW_HAT_UP, _GLFWjoystick::hats, and value.
Referenced by _glfwPlatformPollJoystick(), and pollAbsState().
pollAbsState()
static void pollAbsState (_GLFWjoystick * js) static
References handleAbsEvent().
Referenced by _glfwPlatformPollJoystick(), and openJoystickDevice().
openJoystickDevice()
static GLFWbool openJoystickDevice (const char * path) static
References _glfw, _glfwAllocJoystick(), _glfwInputError(), _glfwInputJoystick(), GLFW_CONNECTED, GLFW_FALSE, GLFW_JOYSTICK_LAST, GLFW_PLATFORM_ERROR, GLFW_TRUE, isBitSet, _GLFWlibrary::joysticks, memcpy(), setup::name, NULL, pollAbsState(), _GLFWjoystick::present, and create_symbols_file::version.
Referenced by _glfwDetectJoystickConnectionLinux(), and _glfwInitJoysticksLinux().
closeJoystick()
static void closeJoystick (_GLFWjoystick * js) static
References _glfwFreeJoystick(), _glfwInputJoystick(), and GLFW_DISCONNECTED.
Referenced by _glfwDetectJoystickConnectionLinux(), _glfwPlatformPollJoystick(), and _glfwTerminateJoysticksLinux().
compareJoysticks()
static int compareJoysticks (const void * fp, const void * sp) static
Referenced by _glfwInitJoysticksLinux().
_glfwInitJoysticksLinux()
GLFWbool _glfwInitJoysticksLinux (void)
References _glfw, _glfwInputError(), compareJoysticks(), GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, _GLFWlibrary::joysticks, and openJoystickDevice().
Referenced by _glfwPlatformInit().
_glfwTerminateJoysticksLinux()
void _glfwTerminateJoysticksLinux (void)
References _glfw, closeJoystick(), GLFW_JOYSTICK_LAST, _GLFWlibrary::joysticks, and _GLFWjoystick::present.
Referenced by _glfwPlatformTerminate().
_glfwDetectJoystickConnectionLinux()
void _glfwDetectJoystickConnectionLinux (void)
References _glfw, closeJoystick(), GLFW_JOYSTICK_LAST, _GLFWlibrary::joysticks, openJoystickDevice(), and ssize_t.
Referenced by _glfwPlatformPollEvents().
_glfwPlatformPollJoystick()
int _glfwPlatformPollJoystick (_GLFWjoystick * js, int mode)
References _glfw, closeJoystick(), GLFW_FALSE, GLFW_TRUE, handleAbsEvent(), handleKeyEvent(), pollAbsState(), _GLFWjoystick::present, and SYN_DROPPED.
_glfwPlatformUpdateGamepadGUID()
void _glfwPlatformUpdateGamepadGUID (char * guid)