Aurora Framework: spirv_cross::Compiler::OpcodeHandler Struct Reference
spirv_cross::Compiler::OpcodeHandler Struct Reference abstract
Public Member Functions
virtual ~OpcodeHandler ()=default
virtual bool begin_function_scope (const uint32_t *, uint32_t)
virtual bool end_function_scope (const uint32_t *, uint32_t)
virtual bool follow_function_call (const SPIRFunction &)
virtual bool handle (spv::Op opcode, const uint32_t *args, uint32_t length)=0
virtual void set_current_block (const SPIRBlock &)
Constructor & Destructor Documentation
~OpcodeHandler()
virtual spirv_cross::Compiler::OpcodeHandler::~OpcodeHandler () virtual default
Member Function Documentation
handle()
virtual bool spirv_cross::Compiler::OpcodeHandler::handle (spv::Op opcode, const uint32_t * args, uint32_t length) pure virtual
Implemented in spirv_cross::Compiler::CombinedImageSamplerUsageHandler, spirv_cross::Compiler::ActiveBuiltinHandler, spirv_cross::Compiler::DummySamplerForCombinedImageHandler, spirv_cross::Compiler::CombinedImageSamplerHandler, spirv_cross::Compiler::InterfaceVariableAccessHandler, and spirv_cross::Compiler::BufferAccessHandler.
Referenced by spirv_cross::Compiler::traverse_all_reachable_opcodes().
follow_function_call()
virtual bool spirv_cross::Compiler::OpcodeHandler::follow_function_call (const SPIRFunction &) inline virtual
Referenced by spirv_cross::Compiler::traverse_all_reachable_opcodes().
set_current_block()
virtual void spirv_cross::Compiler::OpcodeHandler::set_current_block (const SPIRBlock &) inline virtual
Referenced by spirv_cross::Compiler::traverse_all_reachable_opcodes().
begin_function_scope()
virtual bool spirv_cross::Compiler::OpcodeHandler::begin_function_scope (const uint32_t * , uint32_t) inline virtual
Reimplemented in spirv_cross::Compiler::CombinedImageSamplerUsageHandler, and spirv_cross::Compiler::CombinedImageSamplerHandler.
Referenced by spirv_cross::Compiler::traverse_all_reachable_opcodes().
end_function_scope()
virtual bool spirv_cross::Compiler::OpcodeHandler::end_function_scope (const uint32_t * , uint32_t) inline virtual
Reimplemented in spirv_cross::Compiler::CombinedImageSamplerHandler.
Referenced by spirv_cross::Compiler::traverse_all_reachable_opcodes().
The documentation for this struct was generated from the following file:
Cross.h