Aurora Framework: AuroraFW::GEngine::GLContext Class Reference
AuroraFW::GEngine::GLContext Class Reference
Public Member Functions
GLContext (WindowProperties)
Static Public Member Functions
static void create (WindowProperties, std::string &)
static void destroy ()
static uint getAPIVersion ()
static RenderAPI getRenderAPI ()
static void init (GLFWwindow *)
static void setRenderAPI (RenderAPI api)
Protected Member Functions
void _destroy () override
void _init (GLFWwindow *) override
Static Protected Member Functions
static GLContext * getInstance ()
Static Protected Attributes
static Context * _instance = AFW_NULLPTR
static RenderAPI _rapi = RenderAPI::OpenGL
static uint _version
Constructor & Destructor Documentation
GLContext()
AuroraFW::GEngine::GLContext::GLContext (WindowProperties wp)
References GLCall, GLFW_CONTEXT_VERSION_MAJOR, GLFW_CONTEXT_VERSION_MINOR, GLFW_OPENGL_ANY_PROFILE, GLFW_OPENGL_DEBUG_CONTEXT, GLFW_OPENGL_FORWARD_COMPAT, GLFW_OPENGL_PROFILE, GLFW_TRUE, glfwWindowHint(), and AuroraFW::GEngine::WindowProperties::samples.
Member Function Documentation
_init()
void AuroraFW::GEngine::GLContext::_init (GLFWwindow *) override protected virtual
Implements AuroraFW::GEngine::API::Context.
_destroy()
void AuroraFW::GEngine::GLContext::_destroy () override protected virtual
Implements AuroraFW::GEngine::API::Context.
getInstance()
static GLContext* AuroraFW::GEngine::GLContext::getInstance () inline static protected
create()
void AuroraFW::GEngine::API::Context::create (WindowProperties wp, std::string & name) static inherited
References AuroraFW::GEngine::API::Context::_instance, AFW_NEW, AuroraFW::GEngine::API::Context::getRenderAPI(), setup::name, and OpenGL.
Referenced by AuroraFW::GEngine::Window::Window().
init()
void AuroraFW::GEngine::API::Context::init (GLFWwindow * window) static inherited
References AuroraFW::GEngine::API::Context::_init(), and AuroraFW::GEngine::API::Context::_instance.
Referenced by AuroraFW::GEngine::Window::Window().
destroy()
void AuroraFW::GEngine::API::Context::destroy () static inherited
References AuroraFW::GEngine::API::Context::_destroy(), and AuroraFW::GEngine::API::Context::_instance.
Referenced by AuroraFW::GEngine::Window::~Window().
getRenderAPI()
static RenderAPI AuroraFW::GEngine::API::Context::getRenderAPI () inline static inherited
Referenced by AuroraFW::GEngine::API::Context::create(), AuroraFW::GEngine::ImGuiLoader::Load(), and AuroraFW::GEngine::Renderer::Load().
getAPIVersion()
static uint AuroraFW::GEngine::API::Context::getAPIVersion () inline static inherited
setRenderAPI()
static void AuroraFW::GEngine::API::Context::setRenderAPI (RenderAPI api) inline static inherited
Referenced by AuroraFW::GEngine::Application::Application(), and AuroraFW::GEngine::GraphicsContext::GraphicsContext().
Member Data Documentation
_instance
Context * AuroraFW::GEngine::API::Context::_instance = AFW_NULLPTR static protected inherited
Referenced by AuroraFW::GEngine::API::Context::create(), AuroraFW::GEngine::API::Context::destroy(), and AuroraFW::GEngine::API::Context::init().
_rapi
RenderAPI AuroraFW::GEngine::API::Context::_rapi = RenderAPI::OpenGL static protected inherited
_version
uint AuroraFW::GEngine::API::Context::_version static protected inherited
The documentation for this class was generated from the following files:
opengl/include/AuroraFW/GEngine/GL/Context.h
GLContext.cpp