Aurora Framework: GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator > Class Template Reference
GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator > Class Template Reference abstract
JSON Schema Validator.
Public Types
typedef EncodingType::Ch Ch
typedef SchemaType::EncodingType EncodingType
typedef SchemaDocumentType::PointerType PointerType
typedef SchemaDocumentType::SchemaType SchemaType
typedef GenericStringRef< Ch > StringRefType
typedef SchemaType::SValue SValue
typedef GenericValue< EncodingType, StateAllocator > ValueType
Public Member Functions
GenericSchemaValidator (const SchemaDocumentType &schemaDocument, StateAllocator *allocator=0, size_t schemaStackCapacity=kDefaultSchemaStackCapacity, size_t documentStackCapacity=kDefaultDocumentStackCapacity)
Constructor without output handler.
GenericSchemaValidator (const SchemaDocumentType &schemaDocument, OutputHandler &outputHandler, StateAllocator *allocator=0, size_t schemaStackCapacity=kDefaultSchemaStackCapacity, size_t documentStackCapacity=kDefaultDocumentStackCapacity)
Constructor with output handler.
~GenericSchemaValidator ()
Destructor.
virtual void AboveMaximum (int64_t actual, const SValue &expected, bool exclusive)=0
virtual void AboveMaximum (uint64_t actual, const SValue &expected, bool exclusive)=0
virtual void AboveMaximum (double actual, const SValue &expected, bool exclusive)=0
void AboveMaximum (int64_t actual, const SValue &expected, bool exclusive)
void AboveMaximum (uint64_t actual, const SValue &expected, bool exclusive)
void AboveMaximum (double actual, const SValue &expected, bool exclusive)
virtual void AddDependencySchemaError (const SValue &souceName, ISchemaValidator *subvalidator)=0
void AddDependencySchemaError (const SValue &sourceName, ISchemaValidator *subvalidator)
virtual void AddExpectedType (const typename SchemaDocumentType::SchemaType ::ValueType &expectedType)=0
void AddExpectedType (const typename SchemaType::ValueType &expectedType)
virtual void AddMissingDependentProperty (const SValue &targetName)=0
void AddMissingDependentProperty (const SValue &targetName)
virtual void AddMissingProperty (const SValue &name)=0
void AddMissingProperty (const SValue &name)
virtual void BelowMinimum (int64_t actual, const SValue &expected, bool exclusive)=0
virtual void BelowMinimum (uint64_t actual, const SValue &expected, bool exclusive)=0
virtual void BelowMinimum (double actual, const SValue &expected, bool exclusive)=0
void BelowMinimum (int64_t actual, const SValue &expected, bool exclusive)
void BelowMinimum (uint64_t actual, const SValue &expected, bool exclusive)
void BelowMinimum (double actual, const SValue &expected, bool exclusive)
bool Bool (bool b)
virtual void * CreateHasher ()
virtual ISchemaValidator * CreateSchemaValidator (const SchemaType &root)
virtual void DestroryHasher (void *hasher)
virtual void DestroySchemaValidator (ISchemaValidator *validator)=0
virtual void DestroySchemaValidator (ISchemaValidator *validator)
void Disallowed ()
void DisallowedItem (SizeType index)
virtual void DisallowedProperty (const Ch *name, SizeType length)=0
void DisallowedProperty (const Ch *name, SizeType length)
void DisallowedValue ()
virtual void DoesNotMatch (const Ch *str, SizeType length)=0
void DoesNotMatch (const Ch *str, SizeType length)
bool Double (double d)
void DuplicateItems (SizeType index1, SizeType index2)
bool EndArray (SizeType elementCount)
bool EndDependencyErrors ()
virtual void EndDisallowedType (const typename SchemaDocumentType::SchemaType ::ValueType &actualType)=0
void EndDisallowedType (const typename SchemaType::ValueType &actualType)
virtual void EndMissingDependentProperties (const SValue &sourceName)=0
void EndMissingDependentProperties (const SValue &sourceName)
bool EndMissingProperties ()
bool EndObject (SizeType memberCount)
virtual void FreeState (void *p)
ValueType & GetError ()
Gets the error object.
const ValueType & GetError () const
virtual uint64_t GetHashCode (void *hasher)
PointerType GetInvalidDocumentPointer () const
Gets the JSON pointer pointed to the invalid value.
const Ch * GetInvalidSchemaKeyword () const
Gets the keyword of invalid schema.
PointerType GetInvalidSchemaPointer () const
Gets the JSON pointer pointed to the invalid schema.
bool Int (int i)
bool Int64 (int64_t i)
virtual bool IsValid () const
Checks whether the current state is valid.
bool Key (const Ch *str, SizeType len, bool copy)
virtual void * MallocState (size_t size)
virtual void NoneOf (ISchemaValidator **subvalidators, SizeType count)=0
void NoneOf (ISchemaValidator **subvalidators, SizeType count)
virtual void NotAllOf (ISchemaValidator **subvalidators, SizeType count)=0
void NotAllOf (ISchemaValidator **subvalidators, SizeType count)
virtual void NotMultipleOf (int64_t actual, const SValue &expected)=0
virtual void NotMultipleOf (uint64_t actual, const SValue &expected)=0
virtual void NotMultipleOf (double actual, const SValue &expected)=0
void NotMultipleOf (int64_t actual, const SValue &expected)
void NotMultipleOf (uint64_t actual, const SValue &expected)
void NotMultipleOf (double actual, const SValue &expected)
virtual void NotOneOf (ISchemaValidator **subvalidators, SizeType count)=0
void NotOneOf (ISchemaValidator **subvalidators, SizeType count)
bool Null ()
virtual void PropertyViolations (ISchemaValidator **subvalidators, SizeType count)=0
void PropertyViolations (ISchemaValidator **subvalidators, SizeType count)
bool RawNumber (const Ch *str, SizeType length, bool copy)
void Reset ()
Reset the internal states.
bool StartArray ()
void StartDependencyErrors ()
void StartDisallowedType ()
void StartMissingDependentProperties ()
void StartMissingProperties ()
bool StartObject ()
bool String (const Ch *str, SizeType length, bool copy)
void TooFewItems (SizeType actualCount, SizeType expectedCount)
void TooFewProperties (SizeType actualCount, SizeType expectedCount)
virtual void TooLong (const Ch *str, SizeType length, SizeType expected)=0
void TooLong (const Ch *str, SizeType length, SizeType expected)
void TooManyItems (SizeType actualCount, SizeType expectedCount)
void TooManyProperties (SizeType actualCount, SizeType expectedCount)
virtual void TooShort (const Ch *str, SizeType length, SizeType expected)=0
void TooShort (const Ch *str, SizeType length, SizeType expected)
bool Uint (unsigned u)
bool Uint64 (uint64_t u)
Detailed Description
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator>
class GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >
JSON Schema Validator.
A SAX style JSON schema validator. It uses a GenericSchemaDocument to validate SAX events. It delegates the incoming SAX events to an output handler. The default output handler does nothing. It can be reused multiple times by calling Reset().
Template Parameters
SchemaDocumentType Type of schema document.
OutputHandler Type of output handler. Default handler does nothing.
StateAllocator Allocator for storing the internal validation states.
Member Typedef Documentation
SchemaType
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> typedef SchemaDocumentType::SchemaType GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::SchemaType
PointerType
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> typedef SchemaDocumentType::PointerType GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::PointerType
EncodingType
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> typedef SchemaType::EncodingType GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EncodingType
SValue
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> typedef SchemaType::SValue GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::SValue
Ch
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> typedef EncodingType::Ch GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Ch
StringRefType
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> typedef GenericStringRef<Ch> GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StringRefType
ValueType
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> typedef GenericValue<EncodingType, StateAllocator> GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::ValueType
Constructor & Destructor Documentation
GenericSchemaValidator() [1/2]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GenericSchemaValidator (const SchemaDocumentType & schemaDocument, StateAllocator * allocator = 0, size_t schemaStackCapacity = kDefaultSchemaStackCapacity, size_t documentStackCapacity = kDefaultDocumentStackCapacity) inline
Constructor without output handler.
Parameters
schemaDocument The schema document to conform to.
allocator Optional allocator for storing internal validation states.
schemaStackCapacity Optional initial capacity of schema path stack.
documentStackCapacity Optional initial capacity of document path stack.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CreateSchemaValidator().
GenericSchemaValidator() [2/2]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GenericSchemaValidator (const SchemaDocumentType & schemaDocument, OutputHandler & outputHandler, StateAllocator * allocator = 0, size_t schemaStackCapacity = kDefaultSchemaStackCapacity, size_t documentStackCapacity = kDefaultDocumentStackCapacity) inline
Constructor with output handler.
Parameters
schemaDocument The schema document to conform to.
allocator Optional allocator for storing internal validation states.
schemaStackCapacity Optional initial capacity of schema path stack.
documentStackCapacity Optional initial capacity of document path stack.
~GenericSchemaValidator()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::~GenericSchemaValidator () inline
Destructor.
References RAPIDJSON_DELETE, and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Reset().
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DestroySchemaValidator().
Member Function Documentation
Reset()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Reset () inline
Reset the internal states.
References internal::Stack< Allocator >::Clear(), and internal::Stack< Allocator >::Empty().
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::~GenericSchemaValidator().
IsValid()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> virtual bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::IsValid () const inline virtual
Checks whether the current state is valid.
Implements internal::ISchemaValidator.
Referenced by SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::operator()().
GetError() [1/2]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> ValueType& GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetError () inline
Gets the error object.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddDependencySchemaError(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::NotAllOf(), SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::operator()(), and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::PropertyViolations().
GetError() [2/2]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> const ValueType& GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetError () const inline
GetInvalidSchemaPointer()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> PointerType GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidSchemaPointer () const inline
Gets the JSON pointer pointed to the invalid schema.
References internal::Stack< Allocator >::Empty().
Referenced by SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::operator()().
GetInvalidSchemaKeyword()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> const Ch* GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidSchemaKeyword () const inline
Gets the keyword of invalid schema.
References internal::Stack< Allocator >::Empty().
Referenced by SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::operator()().
GetInvalidDocumentPointer()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> PointerType GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidDocumentPointer () const inline
Gets the JSON pointer pointed to the invalid value.
References internal::Stack< Allocator >::Empty(), and internal::Stack< Allocator >::GetSize().
Referenced by SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::operator()().
NotMultipleOf() [1/6]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::NotMultipleOf (int64_t actual, const SValue & expected) inline
NotMultipleOf() [2/6]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::NotMultipleOf (uint64_t actual, const SValue & expected) inline
NotMultipleOf() [3/6]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::NotMultipleOf (double actual, const SValue & expected) inline
AboveMaximum() [1/6]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AboveMaximum (int64_t actual, const SValue & expected, bool exclusive) inline
AboveMaximum() [2/6]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AboveMaximum (uint64_t actual, const SValue & expected, bool exclusive) inline
AboveMaximum() [3/6]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AboveMaximum (double actual, const SValue & expected, bool exclusive) inline
BelowMinimum() [1/6]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::BelowMinimum (int64_t actual, const SValue & expected, bool exclusive) inline
BelowMinimum() [2/6]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::BelowMinimum (uint64_t actual, const SValue & expected, bool exclusive) inline
BelowMinimum() [3/6]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::BelowMinimum (double actual, const SValue & expected, bool exclusive) inline
TooLong() [1/2]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::TooLong (const Ch * str, SizeType length, SizeType expected) inline
TooShort() [1/2]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::TooShort (const Ch * str, SizeType length, SizeType expected) inline
DoesNotMatch() [1/2]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DoesNotMatch (const Ch * str, SizeType length) inline
DisallowedItem()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DisallowedItem (SizeType index) inline virtual
Implements internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
TooFewItems()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::TooFewItems (SizeType actualCount, SizeType expectedCount) inline virtual
Implements internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
TooManyItems()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::TooManyItems (SizeType actualCount, SizeType expectedCount) inline virtual
Implements internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
DuplicateItems()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DuplicateItems (SizeType index1, SizeType index2) inline virtual
Implements internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
References kArrayType.
TooManyProperties()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::TooManyProperties (SizeType actualCount, SizeType expectedCount) inline virtual
Implements internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
TooFewProperties()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::TooFewProperties (SizeType actualCount, SizeType expectedCount) inline virtual
Implements internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
StartMissingProperties()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartMissingProperties () inline virtual
Implements internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
AddMissingProperty() [1/2]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddMissingProperty (const SValue & name) inline
References setup::name.
EndMissingProperties()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndMissingProperties () inline virtual
Implements internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
References kObjectType.
PropertyViolations() [1/2]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::PropertyViolations (ISchemaValidator ** subvalidators, SizeType count) inline
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetError(), and SizeType.
DisallowedProperty() [1/2]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DisallowedProperty (const Ch * name, SizeType length) inline
References setup::name.
StartDependencyErrors()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartDependencyErrors () inline virtual
Implements internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
StartMissingDependentProperties()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartMissingDependentProperties () inline virtual
Implements internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
AddMissingDependentProperty() [1/2]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddMissingDependentProperty (const SValue & targetName) inline
EndMissingDependentProperties() [1/2]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndMissingDependentProperties (const SValue & sourceName) inline
AddDependencySchemaError() [1/2]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddDependencySchemaError (const SValue & sourceName, ISchemaValidator * subvalidator) inline
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetError().
EndDependencyErrors()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndDependencyErrors () inline virtual
Implements internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
References kObjectType.
DisallowedValue()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DisallowedValue () inline virtual
Implements internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
StartDisallowedType()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartDisallowedType () inline virtual
Implements internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
AddExpectedType() [1/2]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::AddExpectedType (const typename SchemaType::ValueType & expectedType) inline
EndDisallowedType() [1/2]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndDisallowedType (const typename SchemaType::ValueType & actualType) inline
References kObjectType.
NotAllOf() [1/2]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::NotAllOf (ISchemaValidator ** subvalidators, SizeType count) inline
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetError(), and SizeType.
NoneOf() [1/2]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::NoneOf (ISchemaValidator ** subvalidators, SizeType count) inline
NotOneOf() [1/2]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::NotOneOf (ISchemaValidator ** subvalidators, SizeType count) inline
Disallowed()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Disallowed () inline virtual
Implements internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >.
Null()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Null () inline
References RAPIDJSON_SCHEMA_HANDLE_VALUE_.
Bool()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Bool (bool b) inline
References RAPIDJSON_SCHEMA_HANDLE_VALUE_.
Int()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Int (int i) inline
References RAPIDJSON_SCHEMA_HANDLE_VALUE_.
Uint()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Uint (unsigned u) inline
References RAPIDJSON_SCHEMA_HANDLE_VALUE_.
Int64()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Int64 (int64_t i) inline
References RAPIDJSON_SCHEMA_HANDLE_VALUE_.
Uint64()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Uint64 (uint64_t u) inline
References RAPIDJSON_SCHEMA_HANDLE_VALUE_.
Double()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Double (double d) inline
References RAPIDJSON_SCHEMA_HANDLE_VALUE_.
RawNumber()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::RawNumber (const Ch * str, SizeType length, bool copy) inline
References RAPIDJSON_SCHEMA_HANDLE_VALUE_, and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::String().
String()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::String (const Ch * str, SizeType length, bool copy) inline
References RAPIDJSON_SCHEMA_HANDLE_VALUE_.
Referenced by GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::RawNumber().
StartObject()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartObject () inline
References RAPIDJSON_SCHEMA_HANDLE_BEGIN_, and RAPIDJSON_SCHEMA_HANDLE_PARALLEL_.
Key()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::Key (const Ch * str, SizeType len, bool copy) inline
References RAPIDJSON_SCHEMA_HANDLE_PARALLEL_.
EndObject()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndObject (SizeType memberCount) inline
References RAPIDJSON_SCHEMA_HANDLE_END_, and RAPIDJSON_SCHEMA_HANDLE_PARALLEL_.
StartArray()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::StartArray () inline
References RAPIDJSON_SCHEMA_HANDLE_BEGIN_, and RAPIDJSON_SCHEMA_HANDLE_PARALLEL_.
EndArray()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> bool GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::EndArray (SizeType elementCount) inline
References RAPIDJSON_SCHEMA_HANDLE_END_, and RAPIDJSON_SCHEMA_HANDLE_PARALLEL_.
CreateSchemaValidator()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> virtual ISchemaValidator* GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CreateSchemaValidator (const SchemaType & root) inline virtual
Implements internal::ISchemaStateFactory< SchemaDocumentType::SchemaType >.
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GenericSchemaValidator(), and internal::Stack< Allocator >::GetSize().
DestroySchemaValidator() [1/2]
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> virtual void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DestroySchemaValidator (ISchemaValidator * validator) inline virtual
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::~GenericSchemaValidator().
CreateHasher()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> virtual void* GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::CreateHasher () inline virtual
Implements internal::ISchemaStateFactory< SchemaDocumentType::SchemaType >.
GetHashCode()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> virtual uint64_t GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetHashCode (void * hasher) inline virtual
Implements internal::ISchemaStateFactory< SchemaDocumentType::SchemaType >.
DestroryHasher()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> virtual void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::DestroryHasher (void * hasher) inline virtual
Implements internal::ISchemaStateFactory< SchemaDocumentType::SchemaType >.
MallocState()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> virtual void* GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::MallocState (size_t size) inline virtual
Implements internal::ISchemaStateFactory< SchemaDocumentType::SchemaType >.
FreeState()
template<typename SchemaDocumentType, typename OutputHandler = BaseReaderHandler<typename SchemaDocumentType::SchemaType::EncodingType>, typename StateAllocator = CrtAllocator> virtual void GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::FreeState (void * p) inline virtual
Implements internal::ISchemaStateFactory< SchemaDocumentType::SchemaType >.
DestroySchemaValidator() [2/2]
virtual void internal::ISchemaStateFactory< SchemaDocumentType::SchemaType >::DestroySchemaValidator (ISchemaValidator * validator) pure virtual inherited
NotMultipleOf() [4/6]
virtual void internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >::NotMultipleOf (int64_t actual, const SValue & expected) pure virtual inherited
NotMultipleOf() [5/6]
virtual void internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >::NotMultipleOf (uint64_t actual, const SValue & expected) pure virtual inherited
NotMultipleOf() [6/6]
virtual void internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >::NotMultipleOf (double actual, const SValue & expected) pure virtual inherited
AboveMaximum() [4/6]
virtual void internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >::AboveMaximum (int64_t actual, const SValue & expected, bool exclusive) pure virtual inherited
AboveMaximum() [5/6]
virtual void internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >::AboveMaximum (uint64_t actual, const SValue & expected, bool exclusive) pure virtual inherited
AboveMaximum() [6/6]
virtual void internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >::AboveMaximum (double actual, const SValue & expected, bool exclusive) pure virtual inherited
BelowMinimum() [4/6]
virtual void internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >::BelowMinimum (int64_t actual, const SValue & expected, bool exclusive) pure virtual inherited
BelowMinimum() [5/6]
virtual void internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >::BelowMinimum (uint64_t actual, const SValue & expected, bool exclusive) pure virtual inherited
BelowMinimum() [6/6]
virtual void internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >::BelowMinimum (double actual, const SValue & expected, bool exclusive) pure virtual inherited
TooLong() [2/2]
virtual void internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >::TooLong (const Ch * str, SizeType length, SizeType expected) pure virtual inherited
TooShort() [2/2]
virtual void internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >::TooShort (const Ch * str, SizeType length, SizeType expected) pure virtual inherited
DoesNotMatch() [2/2]
virtual void internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >::DoesNotMatch (const Ch * str, SizeType length) pure virtual inherited
AddMissingProperty() [2/2]
virtual void internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >::AddMissingProperty (const SValue & name) pure virtual inherited
PropertyViolations() [2/2]
virtual void internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >::PropertyViolations (ISchemaValidator ** subvalidators, SizeType count) pure virtual inherited
DisallowedProperty() [2/2]
virtual void internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >::DisallowedProperty (const Ch * name, SizeType length) pure virtual inherited
AddMissingDependentProperty() [2/2]
virtual void internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >::AddMissingDependentProperty (const SValue & targetName) pure virtual inherited
EndMissingDependentProperties() [2/2]
virtual void internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >::EndMissingDependentProperties (const SValue & sourceName) pure virtual inherited
AddDependencySchemaError() [2/2]
virtual void internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >::AddDependencySchemaError (const SValue & souceName, ISchemaValidator * subvalidator) pure virtual inherited
AddExpectedType() [2/2]
virtual void internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >::AddExpectedType (const typename SchemaDocumentType::SchemaType ::ValueType & expectedType) pure virtual inherited
EndDisallowedType() [2/2]
virtual void internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >::EndDisallowedType (const typename SchemaDocumentType::SchemaType ::ValueType & actualType) pure virtual inherited
NotAllOf() [2/2]
virtual void internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >::NotAllOf (ISchemaValidator ** subvalidators, SizeType count) pure virtual inherited
NoneOf() [2/2]
virtual void internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >::NoneOf (ISchemaValidator ** subvalidators, SizeType count) pure virtual inherited
NotOneOf() [2/2]
virtual void internal::IValidationErrorHandler< SchemaDocumentType::SchemaType >::NotOneOf (ISchemaValidator ** subvalidators, SizeType count) pure virtual inherited
The documentation for this class was generated from the following files:
fwd.h
schema.h