Aurora Framework: glloader.lang.common.util Namespace Reference
glloader.lang.common.util Namespace Reference
Functions
def enforce (exp, message, exc)
def makefiledir (path)
Function Documentation
enforce()
def glloader.lang.common.util.enforce (exp, message, exc)
makefiledir()
def glloader.lang.common.util.makefiledir (path)
Referenced by glloader.lang.c.generator.make_path(), glloader.lang.nim.generator.NimGenerator.make_path(), and glloader.lang.d.generator.BaseDGenerator.make_path().