Aurora Framework: spirv_cross::Compiler::InterfaceVariableAccessHandler Struct Reference
spirv_cross::Compiler::InterfaceVariableAccessHandler Struct Reference
Public Member Functions
InterfaceVariableAccessHandler (const Compiler &compiler_, std::unordered_set< uint32_t > &variables_)
virtual bool begin_function_scope (const uint32_t *, uint32_t)
virtual bool end_function_scope (const uint32_t *, uint32_t)
virtual bool follow_function_call (const SPIRFunction &)
bool handle (spv::Op opcode, const uint32_t *args, uint32_t length) override
virtual void set_current_block (const SPIRBlock &)
Public Attributes
const Compiler & compiler
std::unordered_set< uint32_t > & variables
Constructor & Destructor Documentation
InterfaceVariableAccessHandler()
spirv_cross::Compiler::InterfaceVariableAccessHandler::InterfaceVariableAccessHandler (const Compiler & compiler_, std::unordered_set< uint32_t > & variables_) inline
Member Function Documentation
handle()
bool Compiler::InterfaceVariableAccessHandler::handle (spv::Op opcode, const uint32_t * args, uint32_t length) override virtual
Implements spirv_cross::Compiler::OpcodeHandler.
References compiler, spirv_cross::SPIRExtension::ext, spirv_cross::Compiler::get(), spirv_cross::Compiler::maybe_get(), spv::OpAccessChain, spv::OpAtomicAnd, spv::OpAtomicCompareExchange, spv::OpAtomicCompareExchangeWeak, spv::OpAtomicExchange, spv::OpAtomicIAdd, spv::OpAtomicIDecrement, spv::OpAtomicIIncrement, spv::OpAtomicISub, spv::OpAtomicLoad, spv::OpAtomicOr, spv::OpAtomicSMax, spv::OpAtomicSMin, spv::OpAtomicStore, spv::OpAtomicUMax, spv::OpAtomicUMin, spv::OpAtomicXor, spv::OpCopyMemory, spv::OpCopyObject, spv::OpExtInst, spv::OpFunctionCall, spv::OpImageTexelPointer, spv::OpInBoundsAccessChain, spv::OpLoad, spv::OpStore, spirv_cross::SPIRExtension::SPV_AMD_shader_explicit_vertex_parameter, storage_class_is_interface(), and variables.
follow_function_call()
virtual bool spirv_cross::Compiler::OpcodeHandler::follow_function_call (const SPIRFunction &) inline virtual inherited
Referenced by spirv_cross::Compiler::traverse_all_reachable_opcodes().
set_current_block()
virtual void spirv_cross::Compiler::OpcodeHandler::set_current_block (const SPIRBlock &) inline virtual inherited
Referenced by spirv_cross::Compiler::traverse_all_reachable_opcodes().
begin_function_scope()
virtual bool spirv_cross::Compiler::OpcodeHandler::begin_function_scope (const uint32_t * , uint32_t) inline virtual inherited
Reimplemented in spirv_cross::Compiler::CombinedImageSamplerUsageHandler, and spirv_cross::Compiler::CombinedImageSamplerHandler.
Referenced by spirv_cross::Compiler::traverse_all_reachable_opcodes().
end_function_scope()
virtual bool spirv_cross::Compiler::OpcodeHandler::end_function_scope (const uint32_t * , uint32_t) inline virtual inherited
Reimplemented in spirv_cross::Compiler::CombinedImageSamplerHandler.
Referenced by spirv_cross::Compiler::traverse_all_reachable_opcodes().
Member Data Documentation
compiler
const Compiler& spirv_cross::Compiler::InterfaceVariableAccessHandler::compiler
Referenced by handle().
variables
std::unordered_set<uint32_t>& spirv_cross::Compiler::InterfaceVariableAccessHandler::variables
Referenced by handle().
The documentation for this struct was generated from the following files:
Cross.h
Cross.cpp