Aurora Framework: float32.c File Reference
float32.c File Reference
Enumerations
enum {
FLOAT_UNKNOWN = 0x00, FLOAT_CAN_RW_LE = 0x12, FLOAT_CAN_RW_BE = 0x23, FLOAT_BROKEN_LE = 0x34,
FLOAT_BROKEN_BE = 0x45
}
Functions
static void bf2f_array (float *buffer, int count)
static void d2f_array (const double *src, float *dest, int count)
static void f2bf_array (float *buffer, int count)
static void f2d_array (const float *src, int count, double *dest)
static void f2i_array (const float *src, int count, int *dest, float scale)
static void f2i_clip_array (const float *src, int count, int *dest, float scale)
static void f2s_array (const float *src, int count, short *dest, float scale)
static void f2s_clip_array (const float *src, int count, short *dest, float scale)
float float32_be_read (const unsigned char *cptr)
void float32_be_write (float in, unsigned char *out)
static int float32_get_capability (SF_PRIVATE *psf)
int float32_init (SF_PRIVATE *psf)
float float32_le_read (const unsigned char *cptr)
void float32_le_write (float in, unsigned char *out)
static void float32_peak_update (SF_PRIVATE *psf, const float *buffer, int count, sf_count_t indx)
static sf_count_t host_read_f (SF_PRIVATE *psf, float *ptr, sf_count_t len)
static sf_count_t host_read_f2d (SF_PRIVATE *psf, double *ptr, sf_count_t len)
static sf_count_t host_read_f2i (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static sf_count_t host_read_f2s (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static sf_count_t host_write_d2f (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
static sf_count_t host_write_f (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
static sf_count_t host_write_i2f (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
static sf_count_t host_write_s2f (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
static void i2f_array (const int *src, float *dest, int count, float scale)
static sf_count_t replace_read_f (SF_PRIVATE *psf, float *ptr, sf_count_t len)
static sf_count_t replace_read_f2d (SF_PRIVATE *psf, double *ptr, sf_count_t len)
static sf_count_t replace_read_f2i (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static sf_count_t replace_read_f2s (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static sf_count_t replace_write_d2f (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
static sf_count_t replace_write_f (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
static sf_count_t replace_write_i2f (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
static sf_count_t replace_write_s2f (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
static void s2f_array (const short *src, float *dest, int count, float scale)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
FLOAT_UNKNOWN
FLOAT_CAN_RW_LE
FLOAT_CAN_RW_BE
FLOAT_BROKEN_LE
FLOAT_BROKEN_BE
Function Documentation
host_read_f2s()
static sf_count_t host_read_f2s (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
References sf_private_tag::add_clipping, ARRAY_LEN, sf_private_tag::data_endswap, endswap_int_array(), f2s_array(), f2s_clip_array(), BUF_UNION::fbuf, sf_private_tag::float_int_mult, sf_private_tag::float_max, BUF_UNION::ibuf, psf_fread(), and scale().
Referenced by float32_init().
host_read_f2i()
static sf_count_t host_read_f2i (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
References sf_private_tag::add_clipping, ARRAY_LEN, sf_private_tag::data_endswap, endswap_int_array(), f2i_array(), f2i_clip_array(), BUF_UNION::fbuf, sf_private_tag::float_int_mult, sf_private_tag::float_max, BUF_UNION::ibuf, psf_fread(), and scale().
Referenced by float32_init().
host_read_f()
static sf_count_t host_read_f (SF_PRIVATE * psf, float * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::data_endswap, endswap_int_copy(), BUF_UNION::fbuf, BUF_UNION::ibuf, and psf_fread().
Referenced by float32_init().
host_read_f2d()
static sf_count_t host_read_f2d (SF_PRIVATE * psf, double * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::data_endswap, endswap_int_array(), f2d_array(), BUF_UNION::fbuf, BUF_UNION::ibuf, and psf_fread().
Referenced by float32_init().
host_write_s2f()
static sf_count_t host_write_s2f (SF_PRIVATE * psf, const short * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::data_endswap, endswap_int_array(), BUF_UNION::fbuf, float32_peak_update(), BUF_UNION::ibuf, sf_private_tag::peak_info, psf_fwrite(), s2f_array(), scale(), sf_private_tag::scale_int_float, and sf_private_tag::sf.
Referenced by float32_init().
host_write_i2f()
static sf_count_t host_write_i2f (SF_PRIVATE * psf, const int * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::data_endswap, endswap_int_array(), BUF_UNION::fbuf, float32_peak_update(), i2f_array(), BUF_UNION::ibuf, sf_private_tag::peak_info, psf_fwrite(), scale(), sf_private_tag::scale_int_float, and sf_private_tag::sf.
Referenced by float32_init().
host_write_f()
static sf_count_t host_write_f (SF_PRIVATE * psf, const float * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::data_endswap, endswap_int_copy(), BUF_UNION::fbuf, float32_peak_update(), BUF_UNION::ibuf, sf_private_tag::peak_info, and psf_fwrite().
Referenced by float32_init().
host_write_d2f()
static sf_count_t host_write_d2f (SF_PRIVATE * psf, const double * ptr, sf_count_t len) static
References ARRAY_LEN, d2f_array(), sf_private_tag::data_endswap, endswap_int_array(), BUF_UNION::fbuf, float32_peak_update(), BUF_UNION::ibuf, sf_private_tag::peak_info, psf_fwrite(), and sf_private_tag::sf.
Referenced by float32_init().
float32_peak_update()
static void float32_peak_update (SF_PRIVATE * psf, const float * buffer, int count, sf_count_t indx) static
References sf_private_tag::peak_info, PEAK_INFO::peaks, PEAK_POS::position, sf_private_tag::sf, PEAK_POS::value, and sf_private_tag::write_current.
Referenced by host_write_d2f(), host_write_f(), host_write_i2f(), host_write_s2f(), replace_write_d2f(), replace_write_f(), replace_write_i2f(), and replace_write_s2f().
replace_read_f2s()
static sf_count_t replace_read_f2s (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
References ARRAY_LEN, bf2f_array(), sf_private_tag::data_endswap, endswap_int_array(), f2s_array(), BUF_UNION::fbuf, sf_private_tag::float_int_mult, sf_private_tag::float_max, BUF_UNION::ibuf, psf_fread(), and scale().
Referenced by float32_init().
replace_read_f2i()
static sf_count_t replace_read_f2i (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
References ARRAY_LEN, bf2f_array(), sf_private_tag::data_endswap, endswap_int_array(), f2i_array(), BUF_UNION::fbuf, sf_private_tag::float_int_mult, sf_private_tag::float_max, BUF_UNION::ibuf, psf_fread(), and scale().
Referenced by float32_init().
replace_read_f()
static sf_count_t replace_read_f (SF_PRIVATE * psf, float * ptr, sf_count_t len) static
References ARRAY_LEN, bf2f_array(), sf_private_tag::data_endswap, endswap_int_array(), BUF_UNION::fbuf, BUF_UNION::ibuf, memcpy(), and psf_fread().
Referenced by float32_init().
replace_read_f2d()
static sf_count_t replace_read_f2d (SF_PRIVATE * psf, double * ptr, sf_count_t len) static
References ARRAY_LEN, bf2f_array(), sf_private_tag::data_endswap, endswap_int_array(), f2d_array(), BUF_UNION::fbuf, BUF_UNION::ibuf, and psf_fread().
Referenced by float32_init().
replace_write_s2f()
static sf_count_t replace_write_s2f (SF_PRIVATE * psf, const short * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::data_endswap, endswap_int_array(), f2bf_array(), BUF_UNION::fbuf, float32_peak_update(), BUF_UNION::ibuf, sf_private_tag::peak_info, psf_fwrite(), s2f_array(), scale(), sf_private_tag::scale_int_float, and sf_private_tag::sf.
Referenced by float32_init().
replace_write_i2f()
static sf_count_t replace_write_i2f (SF_PRIVATE * psf, const int * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::data_endswap, endswap_int_array(), f2bf_array(), BUF_UNION::fbuf, float32_peak_update(), i2f_array(), BUF_UNION::ibuf, sf_private_tag::peak_info, psf_fwrite(), scale(), sf_private_tag::scale_int_float, and sf_private_tag::sf.
Referenced by float32_init().
replace_write_f()
static sf_count_t replace_write_f (SF_PRIVATE * psf, const float * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::data_endswap, endswap_int_array(), f2bf_array(), BUF_UNION::fbuf, float32_peak_update(), BUF_UNION::ibuf, memcpy(), sf_private_tag::peak_info, and psf_fwrite().
Referenced by float32_init().
replace_write_d2f()
static sf_count_t replace_write_d2f (SF_PRIVATE * psf, const double * ptr, sf_count_t len) static
References ARRAY_LEN, d2f_array(), sf_private_tag::data_endswap, endswap_int_array(), f2bf_array(), BUF_UNION::fbuf, float32_peak_update(), BUF_UNION::ibuf, sf_private_tag::peak_info, psf_fwrite(), and sf_private_tag::sf.
Referenced by float32_init().
bf2f_array()
static void bf2f_array (float * buffer, int count) static
Referenced by replace_read_f(), replace_read_f2d(), replace_read_f2i(), and replace_read_f2s().
f2bf_array()
static void f2bf_array (float * buffer, int count) static
Referenced by replace_write_d2f(), replace_write_f(), replace_write_i2f(), and replace_write_s2f().
float32_get_capability()
static int float32_get_capability (SF_PRIVATE * psf) static
References FLOAT_BROKEN_BE, FLOAT_BROKEN_LE, FLOAT_CAN_RW_BE, FLOAT_CAN_RW_LE, sf_private_tag::ieee_replace, and psf_log_printf().
Referenced by float32_init().
float32_init()
int float32_init (SF_PRIVATE * psf)
References sf_private_tag::blockwidth, sf_private_tag::data_endswap, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, float32_get_capability(), FLOAT_BROKEN_BE, FLOAT_BROKEN_LE, FLOAT_CAN_RW_BE, FLOAT_CAN_RW_LE, host_read_f(), host_read_f2d(), host_read_f2i(), host_read_f2s(), host_write_d2f(), host_write_f(), host_write_i2f(), host_write_s2f(), PSF_FILE::mode, psf_log_printf(), sf_private_tag::read_double, sf_private_tag::read_float, sf_private_tag::read_int, sf_private_tag::read_short, replace_read_f(), replace_read_f2d(), replace_read_f2i(), replace_read_f2s(), replace_write_d2f(), replace_write_f(), replace_write_i2f(), replace_write_s2f(), sf_private_tag::sf, SFE_INTERNAL, sf_private_tag::write_double, sf_private_tag::write_float, sf_private_tag::write_int, and sf_private_tag::write_short.
Referenced by aiff_open(), au_open(), caf_open(), ircam_open(), mat4_open(), mat5_open(), raw_open(), rf64_open(), sf_command(), w64_open(), and wav_open().
float32_be_read()
float float32_be_read (const unsigned char * cptr)
Referenced by psf_binheader_readf().
float32_le_read()
float float32_le_read (const unsigned char * cptr)
Referenced by psf_binheader_readf().
float32_le_write()
void float32_le_write (float in, unsigned char * out)
References memset().
Referenced by psf_binheader_writef().
float32_be_write()
void float32_be_write (float in, unsigned char * out)
References memset().
Referenced by psf_binheader_writef().
f2s_array()
static void f2s_array (const float * src, int count, short * dest, float scale) static
References scale().
Referenced by host_read_f2s(), and replace_read_f2s().
f2s_clip_array()
static void f2s_clip_array (const float * src, int count, short * dest, float scale) static
References scale().
Referenced by host_read_f2s().
f2i_array()
static void f2i_array (const float * src, int count, int * dest, float scale) inline static
References scale().
Referenced by host_read_f2i(), and replace_read_f2i().
f2i_clip_array()
static void f2i_clip_array (const float * src, int count, int * dest, float scale) inline static
References scale().
Referenced by host_read_f2i().
f2d_array()
static void f2d_array (const float * src, int count, double * dest) inline static
Referenced by host_read_f2d(), and replace_read_f2d().
s2f_array()
static void s2f_array (const short * src, float * dest, int count, float scale) inline static
References scale().
Referenced by host_write_s2f(), and replace_write_s2f().
i2f_array()
static void i2f_array (const int * src, float * dest, int count, float scale) inline static
References scale().
Referenced by host_write_i2f(), and replace_write_i2f().
d2f_array()
static void d2f_array (const double * src, float * dest, int count) inline static
Referenced by host_write_d2f(), and replace_write_d2f().