Aurora Framework: Memory.c File Reference
Memory.c File Reference
Functions
int memcmp (const void *cs, const void *ct, size_t n)
void * memcpy (void *dst, const void *src, size_t n)
void * memmove (void *dst, const void *src, size_t n)
void * memset (void *s, const int c, size_t n)
Function Documentation
memcpy()
void* memcpy (void * dst, const void * src, size_t n)
Referenced by _glfwPlatformCreateCursor(), _glfwPlatformGetGammaRamp(), _glfwPlatformSetGammaRamp(), _glfwPollMonitorsNS(), _glfwPollMonitorsWin32(), _glfwPollMonitorsX11(), ImFontAtlas::AddFont(), aiff_get_chunk_data(), aiff_read_chanmap(), alac_get_magic_cookie(), AuroraFW::MemoryAllocator::allocate(), GenericPointer< ValueType, Allocator >::Append(), internal::BigInteger::BigInteger(), broadcast_var_get(), broadcast_var_set(), caf_get_chunk_data(), caf_read_chanmap(), cart_var_get(), cart_var_set(), ImDrawList::ChannelsMerge(), ImDrawList::ChannelsSetCurrent(), ImGui::ColorEdit4(), ImGui::ColorPicker4(), ColorPickerOptionsPopup(), createKeyTables(), AuroraFW::AES::decrypt(), AuroraFW::AES::encrypt(), ImDrawDataBuilder::FlattenIntoSingleLayer(), g72x_read_block(), g72x_write_block(), ImFontAtlas::GetGlyphRangesJapanese(), glfwUpdateGamepadMappings(), gsm610_read_block(), gsm610_write_block(), Gsm_Coder(), header_read(), ima_read_block(), ima_write_block(), ImStrdup(), ImGuiTextEditCallbackData::InsertChars(), AuroraFW::Math::mat< T, m, n >::mat(), msadpcm_read_block(), msadpcm_write_block(), AuroraFW::Math::mat< T, m, n >::multiply(), ImGui::NavUpdate(), ImGui::NewFrame(), nms_adpcm_read_block(), nms_adpcm_write_block(), openJoystickDevice(), internal::BigInteger::operator=(), paf24_read(), paf24_write(), parseMapping(), pc_block(), psf_binheader_writef(), psf_cues_dup(), psf_get_chunk_iterator(), psf_get_cues(), psf_get_date_str(), psf_get_format_info(), psf_get_format_major(), psf_get_format_simple(), psf_get_format_subtype(), psf_memdup(), psf_open_file(), psf_store_read_chunk_str(), psf_store_read_chunk_u32(), psf_store_string(), MemoryPoolAllocator< BaseAllocator >::Realloc(), replace_read_d(), replace_read_d2f(), replace_read_f(), replace_write_d(), replace_write_f(), ImVector< ImGuiStorage::Pair >::reserve(), rf64_get_chunk_data(), sds_read(), sds_write(), GenericValue< EncodingType, Allocator >::SetArrayRaw(), SetClipboardTextFn_DefaultImpl(), ImGui::SetDragDropPayload(), GenericValue< EncodingType, Allocator >::SetObjectRaw(), GenericValue< EncodingType, Allocator >::SetStringRaw(), sf_command(), stb__lit(), ImGuiStb::STB_TEXTEDIT_INSERTCHARS(), unpc_block(), vox_read_block(), vox_write_block(), wav_get_chunk_data(), and xi_open().
memmove()
void* memmove (void * dst, const void * src, size_t n)
Referenced by _glfwInputMonitor(), ImGui::BringWindowToBack(), ImVector< ImGuiStorage::Pair >::erase(), ImVector< ImGuiStorage::Pair >::insert(), ImGuiTextEditCallbackData::InsertChars(), internal::BigInteger::operator<<=(), internal::Prettify(), and ImGuiStb::STB_TEXTEDIT_INSERTCHARS().
memcmp()
int memcmp (const void * cs, const void * ct, size_t n)
Referenced by aiff_caf_find_channel_layout_tag(), ImGui::ColorPicker4(), deviceCallback(), deviceObjectCallback(), internal::BigInteger::operator==(), ImDrawList::PathLineToMergeDuplicate(), GenericValue< EncodingType, Allocator >::StringEqual(), spirv_cross::Compiler::types_are_logically_equivalent(), ImDrawList::UpdateClipRect(), ImDrawList::UpdateTextureID(), and wavex_guid_equal().
memset()
void* memset (void * s, const int c, size_t n)
Referenced by _glfwFreeGammaArrays(), _glfwFreeJoystick(), _glfwPlatformCreateWindowSurface(), _glfwPlatformDestroyMutex(), _glfwPlatformDestroyTls(), _glfwPlatformPostEmptyEvent(), _glfwUpdateKeyNamesWin32(), aiff_ima_decode_block(), aiff_ima_encode_block(), aiff_open(), aiff_read_comm_chunk(), aiff_read_header(), aiff_write_header(), alac_close(), alac_pakt_read_decode(), AuroraFW::MemoryAllocator::allocate(), au_read_header(), avr_read_header(), caf_read_header(), caf_write_header(), caf_write_strings(), ImDrawList::ChannelsSplit(), ImGuiPayload::Clear(), ImDrawList::ClearFreeMemory(), createKeyTables(), deviceCallback(), double64_be_write(), double64_le_write(), dwvw_read_reset(), ImGui::EndFrame(), float32_be_write(), float32_le_write(), g723_test(), g72x_read_block(), glfwDefaultWindowHints(), glfwDestroyWindow(), glfwGetGamepadState(), glfwInit(), ImFontAtlas::GlyphRangesBuilder::GlyphRangesBuilder(), gsm610_decode_block(), gsm610_encode_block(), gsm610_init(), gsm610_read_block(), gsm610_wav_decode_block(), gsm610_wav_encode_block(), gsm_create(), gsm_init(), handleSelectionRequest(), id3_skip(), ima_oki_adpcm_init(), ima_read_block(), ImFileLoadToMemory(), ImFontAtlasBuildPackCustomRects(), ImFontAtlasBuildWithStbTruetype(), ImFontConfig::ImFontConfig(), ImGuiContext::ImGuiContext(), ImGuiDrawContext::ImGuiDrawContext(), ImGuiIO::ImGuiIO(), ImGuiMenuColumns::ImGuiMenuColumns(), ImGuiSettingsHandler::ImGuiSettingsHandler(), ImGuiTextEditState::ImGuiTextEditState(), ImGui::InputTextEx(), InputTextFilterCharacter(), spirv_cross::SPIRConstant::make_null(), AuroraFW::Math::mat< T, m, n >::mat(), mat5_write_header(), msadpcm_decode_block(), msadpcm_encode_block(), msadpcm_read_block(), ImGui::NavUpdate(), AuroraFW::GEngine::ImGuiLoader::newFrame(), ImGui::NewFrame(), nist_write_header(), nms_adpcm_close(), nms_adpcm_codec_init(), nms_adpcm_read_block(), internal::BigInteger::operator<<=(), paf24_read(), paf24_read_block(), paf_read_header(), processEvent(), psf_binheader_readf(), psf_bump_header_allocation(), psf_calc_max_all_channels(), psf_g72x_decode_block(), psf_g72x_encode_block(), psf_get_format_info(), psf_hexdump(), psf_memset(), psf_next_chunk_iterator(), psf_nms_adpcm_decode_block(), psf_open_file(), psf_open_tmpfile(), psf_store_read_chunk_str(), psf_store_read_chunk_u32(), FileWriteStream::PutN(), PutN(), read_rsrc_str(), Reflection_coefficients(), internal::Schema< SchemaDocumentType >::Schema(), sd2_parse_rsrc_fork(), sd2_write_rsrc_fork(), sds_2byte_read(), sds_3byte_read(), sds_4byte_read(), sds_close(), sds_read(), sendEventToWM(), ImGui::SetDragDropPayload(), internal::Schema< SchemaDocumentType >::StartObject(), supportsXInput(), svx_read_header(), terminate(), AuroraFW::GEngine::ImGuiLoader::Unload(), ImGuiMenuColumns::Update(), voc_read_header(), vote_for_format(), vox_adpcm_init(), wavlike_ima_decode_block(), wavlike_ima_encode_block(), wavlike_read_fmt_chunk(), xi_open(), xi_read_header(), and Zero32().