Aurora Framework: AuroraFW::GEngine::GraphicsContext Class Reference
AuroraFW::GEngine::GraphicsContext Class Reference
Public Member Functions
GraphicsContext (std::string, const API::RenderAPI &=API::OpenGL, WindowProperties={})
GraphicsContext (std::string, const char *)
virtual ~GraphicsContext ()
void addInputListener (InputListener *)
float getFramerate ()
float getTPF ()
virtual void onRender ()
void renderLoop ()
Protected Attributes
Root * root
Constructor & Destructor Documentation
GraphicsContext() [1/2]
AuroraFW::GEngine::GraphicsContext::GraphicsContext (std::string name, const API::RenderAPI & api = API::OpenGL, WindowProperties wp = {})
References AuroraFW::GEngine::Root::addRenderer(), AFW_NEW, ImGui::CreateContext(), ImGui::GetIO(), AuroraFW::GEngine::Root::inputHandler, AuroraFW::GEngine::ImGuiLoader::Load(), AuroraFW::GEngine::Renderer::Load(), setup::name, root, and AuroraFW::GEngine::API::Context::setRenderAPI().
GraphicsContext() [2/2]
AuroraFW::GEngine::GraphicsContext::GraphicsContext (std::string name, const char * path)
~GraphicsContext()
AuroraFW::GEngine::GraphicsContext::~GraphicsContext () virtual
References root.
Member Function Documentation
renderLoop()
void AuroraFW::GEngine::GraphicsContext::renderLoop ()
References AuroraFW::GEngine::Renderer::clear(), AuroraFW::IO::Timer::elapsedMillis(), ImGui::GetDrawData(), AuroraFW::GEngine::Window::getHeight(), AuroraFW::GEngine::Root::getRenderer(), AuroraFW::GEngine::Window::getWidth(), AuroraFW::GEngine::Window::isClosed(), AuroraFW::GEngine::ImGuiLoader::newFrame(), onRender(), AuroraFW::GEngine::Window::present(), ImGui::Render(), AuroraFW::GEngine::ImGuiLoader::renderDrawLists(), AuroraFW::IO::Timer::reset(), root, AuroraFW::GEngine::Renderer::setViewport(), and AuroraFW::GEngine::Window::update().
onRender()
void AuroraFW::GEngine::GraphicsContext::onRender () virtual
Referenced by renderLoop().
addInputListener()
void AuroraFW::GEngine::GraphicsContext::addInputListener (InputListener * in)
References AuroraFW::GEngine::Root::inputHandler, AuroraFW::InputListener::keyPressed(), AuroraFW::InputListener::keyReleased(), AuroraFW::InputListener::mousePressed(), AuroraFW::InputListener::mouseReleased(), AuroraFW::GEngine::Pressed, AuroraFW::GEngine::Released, and root.
getFramerate()
float AuroraFW::GEngine::GraphicsContext::getFramerate () inline
getTPF()
float AuroraFW::GEngine::GraphicsContext::getTPF () inline
Member Data Documentation
root
Root* AuroraFW::GEngine::GraphicsContext::root protected
Referenced by addInputListener(), glloader.parse.Spec::commands(), glloader.parse.Spec::comment(), glloader.parse.Spec::enums(), glloader.parse.Spec::extensions(), glloader.parse.Spec::features(), GraphicsContext(), glloader.parse.Spec::groups(), renderLoop(), glloader.parse.Spec::types(), and ~GraphicsContext().
The documentation for this class was generated from the following files:
GraphicsContext.h
GraphicsContext.cpp