Aurora Framework: AuroraFW::GEngine::GLVertexArray Class Reference
AuroraFW::GEngine::GLVertexArray Class Reference
Public Member Functions
GLVertexArray ()
~GLVertexArray ()
void addBuffer (const GLBuffer &, const GLVertexBufferLayout &)
void bind () const
void unbind () const
Constructor & Destructor Documentation
GLVertexArray()
AuroraFW::GEngine::GLVertexArray::GLVertexArray () inline
References GLCall.
~GLVertexArray()
AuroraFW::GEngine::GLVertexArray::~GLVertexArray () inline
References GLCall.
Member Function Documentation
addBuffer()
void AuroraFW::GEngine::GLVertexArray::addBuffer (const GLBuffer & buf, const GLVertexBufferLayout & layout)
References bind(), AuroraFW::GEngine::GLBuffer::bind(), AuroraFW::GEngine::GLVertexBufferElement::count, AuroraFW::GEngine::GLVertexBufferLayout::getElements(), AuroraFW::GEngine::GLVertexBufferLayout::getStride(), GLCall, AuroraFW::GEngine::GLVertexBufferElement::normalized, AuroraFW::GEngine::GLVertexBufferElement::sizeOf(), AuroraFW::GEngine::GLVertexBufferElement::type, unbind(), and AuroraFW::GEngine::GLBuffer::unbind().
bind()
void AuroraFW::GEngine::GLVertexArray::bind () const inline
References GLCall.
Referenced by addBuffer().
unbind()
void AuroraFW::GEngine::GLVertexArray::unbind () const inline
References GLCall.
Referenced by addBuffer().
The documentation for this class was generated from the following files:
VertexArray.h
GLVertexArray.cpp