Aurora Framework: AuroraFW::AudioManager::AudioDevice Struct Reference
AuroraFW::AudioManager::AudioDevice Struct Reference
A struct representing an audio device.
Public Member Functions
AudioDevice ()
Constructs an AudioDevice with the system's default audio device.
AudioDevice (const PaDeviceInfo *)
Constructs an AudioDevice with the desired audio device's info (from PortAudio).
~AudioDevice ()
Destructs an AudioDevice.
PaTime getDefaultHighInputLatency () const
Gets the high-level input latency for this audio device.
PaTime getDefaultHighOutputLatency () const
Gets the high-level output latency for this audio device.
PaTime getDefaultLowInputLatency () const
Gets the low-level input latency for this audio device.
PaTime getDefaultLowOutputLatency () const
Gets the low-level output latency for this audio device.
double getDefaultSampleRate () const
Gets the default sample rate for this audio device.
PaHostApiIndex getHostAPI () const
Gets the current host API for this audio device.
int getMaxInputChannels () const
Gets the maximum number of input channels this audio device supports.
int getMaxOutputChannels () const
Gets the maximum number of output channels this audio device supports.
const char * getName () const
Gets the name of the audio device.
bool isDefaultInputDevice () const
Checks if this AudioDevice is the system's default input audio device.
bool isDefaultOutputDevice () const
Checks if this AudioDevice is the system's default output audio device.
bool isInputDevice () const
Checks if this audio device can record audio.
bool isOutputDevice () const
Checks if this audio device can play audio.
Detailed Description
A struct representing an audio device.
A struct that represents a pyhsical audio device and has some helper methods.
Constructor & Destructor Documentation
AudioDevice() [1/2]
AuroraFW::AudioManager::AudioDevice::AudioDevice ()
Constructs an AudioDevice with the system's default audio device.
See also
AudioDevice(const PaDeviceInfo*)
Since
snapshot20180330
AudioDevice() [2/2]
AuroraFW::AudioManager::AudioDevice::AudioDevice (const PaDeviceInfo * deviceInfo)
Constructs an AudioDevice with the desired audio device's info (from PortAudio).
Parameters
deviceInfo The PortAudio's audio device info.
See also
AudioDevice()
Since
snapshot20180330
~AudioDevice()
AuroraFW::AudioManager::AudioDevice::~AudioDevice () inline
Destructs an AudioDevice.
Since
snapshot20180330
Member Function Documentation
getName()
const char * AuroraFW::AudioManager::AudioDevice::getName () const
Gets the name of the audio device.
Returns
String containing the name of the device.
Since
snapshot20180330
getHostAPI()
PaHostApiIndex AuroraFW::AudioManager::AudioDevice::getHostAPI () const
Gets the current host API for this audio device.
Returns
An index of the host API (See PortAudio's docs)
Since
snapshot20180330
getMaxInputChannels()
int AuroraFW::AudioManager::AudioDevice::getMaxInputChannels () const
Gets the maximum number of input channels this audio device supports.
Returns
The max number of input channels.
See also
getMaxOutputChannels()
Since
snapshot20180330
Referenced by AuroraFW::AudioManager::AudioBackend::getInputDevices(), and isInputDevice().
getMaxOutputChannels()
int AuroraFW::AudioManager::AudioDevice::getMaxOutputChannels () const
Gets the maximum number of output channels this audio device supports.
Returns
The max number of output channels.
See also
getMaxInputChannels()
Since
snapshot20180330
Referenced by AuroraFW::AudioManager::AudioBackend::getOutputDevices(), and isOutputDevice().
getDefaultLowInputLatency()
PaTime AuroraFW::AudioManager::AudioDevice::getDefaultLowInputLatency () const
Gets the low-level input latency for this audio device.
Returns
The low-level input latency.
See also
getDefaultHighInputLatency()
Since
snapshot20180330
getDefaultLowOutputLatency()
PaTime AuroraFW::AudioManager::AudioDevice::getDefaultLowOutputLatency () const
Gets the low-level output latency for this audio device.
Returns
The low-level output latency.
See also
getDefaultHighOutputLatency()
Since
snapshot20180330
getDefaultHighInputLatency()
PaTime AuroraFW::AudioManager::AudioDevice::getDefaultHighInputLatency () const
Gets the high-level input latency for this audio device.
Returns
The high-level input latency.
See also
getDefaultLowInputLatency()
Since
snapshot20180330
getDefaultHighOutputLatency()
PaTime AuroraFW::AudioManager::AudioDevice::getDefaultHighOutputLatency () const
Gets the high-level output latency for this audio device.
Returns
The high-level output latency.
See also
getDefaultLowOutputLatency()
Since
snapshot20180330
getDefaultSampleRate()
double AuroraFW::AudioManager::AudioDevice::getDefaultSampleRate () const
Gets the default sample rate for this audio device.
Returns
The default sample rate of this device.
Since
snapshot20180330
Referenced by AuroraFW::AudioManager::AudioOStream::AudioOStream().
isInputDevice()
bool AuroraFW::AudioManager::AudioDevice::isInputDevice () const
Checks if this audio device can record audio.
Returns
true if this AudioDevice has any input channels. false otherwise.
See also
isOutputDevice()
Since
snapshot20180330
References getMaxInputChannels().
isOutputDevice()
bool AuroraFW::AudioManager::AudioDevice::isOutputDevice () const
Checks if this audio device can play audio.
Returns
true if this AudioDevice has any output channels. false otherwise.
See also
isInputDevice()
Since
snapshot20180330
References getMaxOutputChannels().
isDefaultOutputDevice()
bool AuroraFW::AudioManager::AudioDevice::isDefaultOutputDevice () const
Checks if this AudioDevice is the system's default output audio device.
Returns
true if this device is the system's default output device. false otherwise.
See also
isDefaultInputDevice()
Since
snapshot20180330
isDefaultInputDevice()
bool AuroraFW::AudioManager::AudioDevice::isDefaultInputDevice () const
Checks if this AudioDevice is the system's default input audio device.
Returns
true if this device is the system's default input device. false otherwise.
See also
isDefaultOutputDevice()
Since
snapshot20180330
The documentation for this struct was generated from the following files:
AudioBackend.h
AudioBackend.cpp