Aurora Framework: dither.c File Reference
dither.c File Reference
Classes
struct DITHER_DATA
Macros
#define SFE_DITHER_BAD_PTR 666
#define SFE_DITHER_BAD_TYPE 667
Functions
static void dither_double (const double *in, double *out, int frames, int channels)
static void dither_float (const float *in, float *out, int frames, int channels)
int dither_init (SF_PRIVATE *psf, int mode)
static void dither_int (const int *in, int *out, int frames, int channels)
static sf_count_t dither_read_int (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static sf_count_t dither_read_int (SF_PRIVATE *UNUSED(psf), int *UNUSED(ptr), sf_count_t len)
static sf_count_t dither_read_short (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static sf_count_t dither_read_short (SF_PRIVATE *UNUSED(psf), short *UNUSED(ptr), sf_count_t len)
static void dither_short (const short *in, short *out, int frames, int channels)
static sf_count_t dither_write_double (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
static sf_count_t dither_write_float (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
static sf_count_t dither_write_int (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
static sf_count_t dither_write_short (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
Macro Definition Documentation
SFE_DITHER_BAD_PTR
#define SFE_DITHER_BAD_PTR 666
Referenced by dither_write_double(), dither_write_float(), dither_write_int(), and dither_write_short().
SFE_DITHER_BAD_TYPE
#define SFE_DITHER_BAD_TYPE 667
Function Documentation
dither_read_short() [1/2]
static sf_count_t dither_read_short (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
Referenced by dither_init().
dither_read_int() [1/2]
static sf_count_t dither_read_int (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
Referenced by dither_init().
dither_write_short()
static sf_count_t dither_write_short (SF_PRIVATE * psf, const short * ptr, sf_count_t len) static
References DITHER_DATA::buffer, sf_private_tag::dither, dither_short(), sf_private_tag::error, NULL, sf_private_tag::sf, SF_CODEC, SFE_DITHER_BAD_PTR, and DITHER_DATA::write_short.
Referenced by dither_init().
dither_write_int()
static sf_count_t dither_write_int (SF_PRIVATE * psf, const int * ptr, sf_count_t len) static
References DITHER_DATA::buffer, sf_private_tag::dither, dither_int(), sf_private_tag::error, NULL, sf_private_tag::sf, SF_CODEC, SFE_DITHER_BAD_PTR, and DITHER_DATA::write_int.
Referenced by dither_init().
dither_write_float()
static sf_count_t dither_write_float (SF_PRIVATE * psf, const float * ptr, sf_count_t len) static
References DITHER_DATA::buffer, sf_private_tag::dither, dither_float(), sf_private_tag::error, NULL, sf_private_tag::sf, SF_CODEC, SFE_DITHER_BAD_PTR, and DITHER_DATA::write_float.
Referenced by dither_init().
dither_write_double()
static sf_count_t dither_write_double (SF_PRIVATE * psf, const double * ptr, sf_count_t len) static
References DITHER_DATA::buffer, sf_private_tag::dither, dither_double(), sf_private_tag::error, NULL, sf_private_tag::sf, SF_CODEC, SFE_DITHER_BAD_PTR, and DITHER_DATA::write_double.
Referenced by dither_init().
dither_init()
int dither_init (SF_PRIVATE * psf, int mode)
References sf_private_tag::dither, dither_read_int(), dither_read_short(), dither_write_double(), dither_write_float(), dither_write_int(), dither_write_short(), mode(), NULL, sf_private_tag::read_dither, DITHER_DATA::read_double, sf_private_tag::read_double, DITHER_DATA::read_float, sf_private_tag::read_float, DITHER_DATA::read_int, sf_private_tag::read_int, DITHER_DATA::read_short, sf_private_tag::read_short, sf_private_tag::sf, SF_CODEC, SFE_MALLOC_FAILED, sf_private_tag::write_dither, DITHER_DATA::write_double, sf_private_tag::write_double, DITHER_DATA::write_float, sf_private_tag::write_float, DITHER_DATA::write_int, sf_private_tag::write_int, DITHER_DATA::write_short, and sf_private_tag::write_short.
Referenced by sf_command().
dither_short()
static void dither_short (const short * in, short * out, int frames, int channels) static
Referenced by dither_write_short().
dither_int()
static void dither_int (const int * in, int * out, int frames, int channels) static
Referenced by dither_write_int().
dither_float()
static void dither_float (const float * in, float * out, int frames, int channels) static
Referenced by dither_write_float().
dither_double()
static void dither_double (const double * in, double * out, int frames, int channels) static
Referenced by dither_write_double().
dither_read_short() [2/2]
static sf_count_t dither_read_short (SF_PRIVATE * UNUSEDpsf, short * UNUSEDptr, sf_count_t len) static
dither_read_int() [2/2]
static sf_count_t dither_read_int (SF_PRIVATE * UNUSEDpsf, int * UNUSEDptr, sf_count_t len) static