Aurora Framework: AuroraFW::GEngine::InputManager Class Reference
AuroraFW::GEngine::InputManager Class Reference
A class that handles user input.
Public Member Functions
InputManager (const Window *)
Constructs an InputManager object associated with the given Window.
~InputManager ()
Destructs the object.
void addCharCallback (std::function< void(uint)>)
void addCursorPosCallback (std::function< void(double, double)>)
void addKeyCallback (std::function< void(InputKey, int, InputAction, InputMod)>)
void addMouseButtonCallback (std::function< void(InputButton, InputAction, InputMod)>)
void addScrollCallback (std::function< void(double, double)>)
void getMousePosition (double &, double &) const
Stores the mouse's current position in the two given variables.
void getScrollPosition (const double &, const double &) const
Not implemented yet, presumably stores the mouse's scroll position in the two given variables.
bool isKeyPressed (const InputKey &) const
Checks to see if the given key is being pressed.
bool isMouseButtonPressed (const InputButton &) const
Checks to see if the given mouse button is being pressed.
void removeCharCallback (std::function< void(uint)>)
void removeCursorPosCallback (std::function< void(double, double)>)
void removeKeyCallback (std::function< void(InputKey, int, InputAction, InputMod)>)
void removeMouseButtonCallback (std::function< void(InputButton, InputAction, InputMod)>)
void removeScrollCallback (std::function< void(double, double)>)
Detailed Description
A class that handles user input.
A class that listens to any input ocurred inside a Window object.
Since
snapshot20170930
Constructor & Destructor Documentation
InputManager()
AuroraFW::GEngine::InputManager::InputManager (const Window * parent)
Constructs an InputManager object associated with the given Window.
Parameters
parent The window's pointer
See also
~InputManager()
Since
snapshot20170930
References AFW_GENGINE_INPUT_MAX_KEYS, AFW_GENGINE_INPUT_MAX_MOUSE_BUTTONS, glfwSetCharCallback(), glfwSetCursorPosCallback(), glfwSetKeyCallback(), glfwSetMouseButtonCallback(), glfwSetScrollCallback(), glfwSetWindowUserPointer(), and AuroraFW::GEngine::Window::window.
~InputManager()
AuroraFW::GEngine::InputManager::~InputManager ()
Destructs the object.
See also
InputManager()
Since
snapshot20170930
Member Function Documentation
isKeyPressed()
bool AuroraFW::GEngine::InputManager::isKeyPressed (const InputKey & key) const
Checks to see if the given key is being pressed.
Parameters
key The key code to check.
Returns
true if the key is being pressed. false otherwise.
See also
isMouseButtonPressed()
Since
snapshot20170930
References AFW_GENGINE_INPUT_KEY_OFFSET, and AFW_GENGINE_INPUT_MAX_KEYS.
isMouseButtonPressed()
bool AuroraFW::GEngine::InputManager::isMouseButtonPressed (const InputButton & btn) const
Checks to see if the given mouse button is being pressed.
Parameters
btn The mouse button code code to check.
Returns
true if the mouse button is being pressed. false otherwise.
See also
isKeyPressed()
Since
snapshot20170930
References AFW_GENGINE_INPUT_MAX_MOUSE_BUTTONS, and AFW_GENGINE_INPUT_MOUSE_BUTTONS_OFFSET.
getMousePosition()
void AuroraFW::GEngine::InputManager::getMousePosition (double & x, double & y) const
Stores the mouse's current position in the two given variables.
Parameters
x,y The variables to store respectively the mouse's X and Y coordinates.
See also
getScrollPosition()
Since
snapshot20170930
getScrollPosition()
void AuroraFW::GEngine::InputManager::getScrollPosition (const double & , const double &) const
Not implemented yet, presumably stores the mouse's scroll position in the two given variables.
See also
getMousePosition()
Since
snapshot20170930
addKeyCallback()
void AuroraFW::GEngine::InputManager::addKeyCallback (std::function< void(InputKey, int, InputAction, InputMod)> func)
Referenced by AuroraFW::GEngine::ImGuiLoader::Load().
removeKeyCallback()
void AuroraFW::GEngine::InputManager::removeKeyCallback (std::function< void(InputKey, int, InputAction, InputMod)> func)
References AuroraFW::getCallbackPtr().
addMouseButtonCallback()
void AuroraFW::GEngine::InputManager::addMouseButtonCallback (std::function< void(InputButton, InputAction, InputMod)> func)
Referenced by AuroraFW::GEngine::ImGuiLoader::Load().
removeMouseButtonCallback()
void AuroraFW::GEngine::InputManager::removeMouseButtonCallback (std::function< void(InputButton, InputAction, InputMod)> func)
References AuroraFW::getCallbackPtr().
addCursorPosCallback()
void AuroraFW::GEngine::InputManager::addCursorPosCallback (std::function< void(double, double)> func)
removeCursorPosCallback()
void AuroraFW::GEngine::InputManager::removeCursorPosCallback (std::function< void(double, double)> func)
References AuroraFW::getCallbackPtr().
addScrollCallback()
void AuroraFW::GEngine::InputManager::addScrollCallback (std::function< void(double, double)> func)
Referenced by AuroraFW::GEngine::ImGuiLoader::Load().
removeScrollCallback()
void AuroraFW::GEngine::InputManager::removeScrollCallback (std::function< void(double, double)> func)
References AuroraFW::getCallbackPtr().
addCharCallback()
void AuroraFW::GEngine::InputManager::addCharCallback (std::function< void(uint)> func)
Referenced by AuroraFW::GEngine::ImGuiLoader::Load().
removeCharCallback()
void AuroraFW::GEngine::InputManager::removeCharCallback (std::function< void(uint)> func)
References AuroraFW::getCallbackPtr().
The documentation for this class was generated from the following files:
gengine/core/include/AuroraFW/GEngine/Input.h
gengine/core/src/Input.cpp