Aurora Framework: double64.c File Reference
double64.c File Reference
Macros
#define SENSIBLE_LEN (0x8000000)
Enumerations
enum {
DOUBLE_UNKNOWN = 0x00, DOUBLE_CAN_RW_LE = 0x23, DOUBLE_CAN_RW_BE = 0x34, DOUBLE_BROKEN_LE = 0x45,
DOUBLE_BROKEN_BE = 0x56
}
Functions
static void bd2d_write (double *buffer, int count)
static void d2bd_read (double *buffer, int count)
static void d2f_array (const double *src, int count, float *dest)
static void d2i_array (const double *src, int count, int *dest, double scale)
static void d2i_clip_array (const double *src, int count, int *dest, double scale)
static void d2s_array (const double *src, int count, short *dest, double scale)
static void d2s_clip_array (const double *src, int count, short *dest, double scale)
double double64_be_read (const unsigned char *cptr)
void double64_be_write (double in, unsigned char *out)
static int double64_get_capability (SF_PRIVATE *psf)
int double64_init (SF_PRIVATE *psf)
double double64_le_read (const unsigned char *cptr)
void double64_le_write (double in, unsigned char *out)
static void double64_peak_update (SF_PRIVATE *psf, const double *buffer, int count, sf_count_t indx)
static void f2d_array (const float *src, double *dest, int count)
static sf_count_t host_read_d (SF_PRIVATE *psf, double *ptr, sf_count_t len)
static sf_count_t host_read_d2f (SF_PRIVATE *psf, float *ptr, sf_count_t len)
static sf_count_t host_read_d2i (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static sf_count_t host_read_d2s (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static sf_count_t host_write_d (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
static sf_count_t host_write_f2d (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
static sf_count_t host_write_i2d (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
static sf_count_t host_write_s2d (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
static void i2d_array (const int *src, double *dest, int count, double scale)
static sf_count_t replace_read_d (SF_PRIVATE *psf, double *ptr, sf_count_t len)
static sf_count_t replace_read_d2f (SF_PRIVATE *psf, float *ptr, sf_count_t len)
static sf_count_t replace_read_d2i (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static sf_count_t replace_read_d2s (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static sf_count_t replace_write_d (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
static sf_count_t replace_write_f2d (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
static sf_count_t replace_write_i2d (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
static sf_count_t replace_write_s2d (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
static void s2d_array (const short *src, double *dest, int count, double scale)
Macro Definition Documentation
SENSIBLE_LEN
#define SENSIBLE_LEN (0x8000000)
Referenced by host_read_d().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
DOUBLE_UNKNOWN
DOUBLE_CAN_RW_LE
DOUBLE_CAN_RW_BE
DOUBLE_BROKEN_LE
DOUBLE_BROKEN_BE
Function Documentation
host_read_d2s()
static sf_count_t host_read_d2s (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
References sf_private_tag::add_clipping, ARRAY_LEN, d2s_array(), d2s_clip_array(), sf_private_tag::data_endswap, BUF_UNION::dbuf, endswap_double_array(), sf_private_tag::float_int_mult, sf_private_tag::float_max, psf_fread(), and scale().
Referenced by double64_init().
host_read_d2i()
static sf_count_t host_read_d2i (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
References sf_private_tag::add_clipping, ARRAY_LEN, d2i_array(), d2i_clip_array(), sf_private_tag::data_endswap, BUF_UNION::dbuf, endswap_double_array(), sf_private_tag::float_int_mult, sf_private_tag::float_max, psf_fread(), and scale().
Referenced by double64_init().
host_read_d2f()
static sf_count_t host_read_d2f (SF_PRIVATE * psf, float * ptr, sf_count_t len) static
References ARRAY_LEN, d2f_array(), sf_private_tag::data_endswap, BUF_UNION::dbuf, endswap_double_array(), and psf_fread().
Referenced by double64_init().
host_read_d()
static sf_count_t host_read_d (SF_PRIVATE * psf, double * ptr, sf_count_t len) static
References sf_private_tag::data_endswap, endswap_double_array(), psf_fread(), and SENSIBLE_LEN.
Referenced by double64_init().
host_write_s2d()
static sf_count_t host_write_s2d (SF_PRIVATE * psf, const short * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::data_endswap, BUF_UNION::dbuf, double64_peak_update(), endswap_double_array(), sf_private_tag::peak_info, psf_fwrite(), s2d_array(), scale(), sf_private_tag::scale_int_float, and sf_private_tag::sf.
Referenced by double64_init().
host_write_i2d()
static sf_count_t host_write_i2d (SF_PRIVATE * psf, const int * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::data_endswap, BUF_UNION::dbuf, double64_peak_update(), endswap_double_array(), i2d_array(), sf_private_tag::peak_info, psf_fwrite(), scale(), sf_private_tag::scale_int_float, and sf_private_tag::sf.
Referenced by double64_init().
host_write_f2d()
static sf_count_t host_write_f2d (SF_PRIVATE * psf, const float * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::data_endswap, BUF_UNION::dbuf, double64_peak_update(), endswap_double_array(), f2d_array(), sf_private_tag::peak_info, psf_fwrite(), and sf_private_tag::sf.
Referenced by double64_init().
host_write_d()
static sf_count_t host_write_d (SF_PRIVATE * psf, const double * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::data_endswap, BUF_UNION::dbuf, double64_peak_update(), endswap_double_copy(), sf_private_tag::peak_info, and psf_fwrite().
Referenced by double64_init().
double64_peak_update()
static void double64_peak_update (SF_PRIVATE * psf, const double * buffer, int count, sf_count_t indx) static
References sf_private_tag::peak_info, PEAK_INFO::peaks, PEAK_POS::position, sf_private_tag::sf, PEAK_POS::value, and sf_private_tag::write_current.
Referenced by host_write_d(), host_write_f2d(), host_write_i2d(), host_write_s2d(), replace_write_d(), replace_write_i2d(), and replace_write_s2d().
double64_get_capability()
static int double64_get_capability (SF_PRIVATE * psf) static
References DOUBLE_BROKEN_BE, DOUBLE_BROKEN_LE, DOUBLE_CAN_RW_BE, DOUBLE_CAN_RW_LE, sf_private_tag::ieee_replace, and psf_log_printf().
Referenced by double64_init().
replace_read_d2s()
static sf_count_t replace_read_d2s (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
References ARRAY_LEN, d2bd_read(), d2s_array(), sf_private_tag::data_endswap, BUF_UNION::dbuf, endswap_double_array(), sf_private_tag::float_int_mult, sf_private_tag::float_max, psf_fread(), and scale().
Referenced by double64_init().
replace_read_d2i()
static sf_count_t replace_read_d2i (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
References ARRAY_LEN, d2bd_read(), d2i_array(), sf_private_tag::data_endswap, BUF_UNION::dbuf, endswap_double_array(), sf_private_tag::float_int_mult, sf_private_tag::float_max, psf_fread(), and scale().
Referenced by double64_init().
replace_read_d2f()
static sf_count_t replace_read_d2f (SF_PRIVATE * psf, float * ptr, sf_count_t len) static
References ARRAY_LEN, d2bd_read(), sf_private_tag::data_endswap, BUF_UNION::dbuf, endswap_double_array(), memcpy(), and psf_fread().
Referenced by double64_init().
replace_read_d()
static sf_count_t replace_read_d (SF_PRIVATE * psf, double * ptr, sf_count_t len) static
References ARRAY_LEN, d2bd_read(), sf_private_tag::data_endswap, BUF_UNION::dbuf, endswap_double_array(), memcpy(), and psf_fread().
Referenced by double64_init().
replace_write_s2d()
static sf_count_t replace_write_s2d (SF_PRIVATE * psf, const short * ptr, sf_count_t len) static
References ARRAY_LEN, bd2d_write(), sf_private_tag::data_endswap, BUF_UNION::dbuf, double64_peak_update(), endswap_double_array(), sf_private_tag::peak_info, psf_fwrite(), s2d_array(), scale(), sf_private_tag::scale_int_float, and sf_private_tag::sf.
Referenced by double64_init().
replace_write_i2d()
static sf_count_t replace_write_i2d (SF_PRIVATE * psf, const int * ptr, sf_count_t len) static
References ARRAY_LEN, bd2d_write(), sf_private_tag::data_endswap, BUF_UNION::dbuf, double64_peak_update(), endswap_double_array(), i2d_array(), sf_private_tag::peak_info, psf_fwrite(), scale(), sf_private_tag::scale_int_float, and sf_private_tag::sf.
Referenced by double64_init().
replace_write_f2d()
static sf_count_t replace_write_f2d (SF_PRIVATE * psf, const float * ptr, sf_count_t len) static
References ARRAY_LEN, bd2d_write(), sf_private_tag::data_endswap, BUF_UNION::dbuf, endswap_double_array(), f2d_array(), and psf_fwrite().
Referenced by double64_init().
replace_write_d()
static sf_count_t replace_write_d (SF_PRIVATE * psf, const double * ptr, sf_count_t len) static
References ARRAY_LEN, bd2d_write(), sf_private_tag::data_endswap, BUF_UNION::dbuf, double64_peak_update(), endswap_double_array(), memcpy(), sf_private_tag::peak_info, and psf_fwrite().
Referenced by double64_init().
d2bd_read()
static void d2bd_read (double * buffer, int count) static
Referenced by replace_read_d(), replace_read_d2f(), replace_read_d2i(), and replace_read_d2s().
bd2d_write()
static void bd2d_write (double * buffer, int count) static
Referenced by replace_write_d(), replace_write_f2d(), replace_write_i2d(), and replace_write_s2d().
double64_init()
int double64_init (SF_PRIVATE * psf)
References sf_private_tag::blockwidth, sf_private_tag::data_endswap, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, double64_get_capability(), DOUBLE_BROKEN_BE, DOUBLE_BROKEN_LE, DOUBLE_CAN_RW_BE, DOUBLE_CAN_RW_LE, sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, host_read_d(), host_read_d2f(), host_read_d2i(), host_read_d2s(), host_write_d(), host_write_f2d(), host_write_i2d(), host_write_s2d(), PSF_FILE::mode, psf_log_printf(), sf_private_tag::read_double, sf_private_tag::read_float, sf_private_tag::read_int, sf_private_tag::read_short, replace_read_d(), replace_read_d2f(), replace_read_d2i(), replace_read_d2s(), replace_write_d(), replace_write_f2d(), replace_write_i2d(), replace_write_s2d(), sf_private_tag::sf, SF_MAX_CHANNELS, SFE_INTERNAL, sf_private_tag::write_double, sf_private_tag::write_float, sf_private_tag::write_int, and sf_private_tag::write_short.
Referenced by aiff_open(), au_open(), caf_open(), mat4_open(), mat5_open(), raw_open(), rf64_open(), sf_command(), w64_open(), and wav_open().
double64_be_read()
double double64_be_read (const unsigned char * cptr)
Referenced by caf_read_header(), and psf_binheader_readf().
double64_le_read()
double double64_le_read (const unsigned char * cptr)
Referenced by psf_binheader_readf().
double64_be_write()
void double64_be_write (double in, unsigned char * out)
References memset().
Referenced by caf_write_header(), and psf_binheader_writef().
double64_le_write()
void double64_le_write (double in, unsigned char * out)
References memset().
Referenced by psf_binheader_writef().
d2s_array()
static void d2s_array (const double * src, int count, short * dest, double scale) static
References scale().
Referenced by host_read_d2s(), and replace_read_d2s().
d2s_clip_array()
static void d2s_clip_array (const double * src, int count, short * dest, double scale) static
References scale().
Referenced by host_read_d2s().
d2i_array()
static void d2i_array (const double * src, int count, int * dest, double scale) static
References scale().
Referenced by host_read_d2i(), and replace_read_d2i().
d2i_clip_array()
static void d2i_clip_array (const double * src, int count, int * dest, double scale) static
References scale().
Referenced by host_read_d2i().
d2f_array()
static void d2f_array (const double * src, int count, float * dest) inline static
Referenced by host_read_d2f().
s2d_array()
static void s2d_array (const short * src, double * dest, int count, double scale) inline static
References scale().
Referenced by host_write_s2d(), and replace_write_s2d().
i2d_array()
static void i2d_array (const int * src, double * dest, int count, double scale) inline static
References scale().
Referenced by host_write_i2d(), and replace_write_i2d().
f2d_array()
static void f2d_array (const float * src, double * dest, int count) inline static
Referenced by host_write_f2d(), and replace_write_f2d().