Aurora Framework: ImGuiMenuColumns Struct Reference
ImGuiMenuColumns Struct Reference
Public Member Functions
ImGuiMenuColumns ()
float CalcExtraSpace (float avail_w)
float DeclColumns (float w0, float w1, float w2)
void Update (int count, float spacing, bool clear)
Public Attributes
int Count
float NextWidth
float NextWidths [4]
float Pos [4]
float Spacing
float Width
Constructor & Destructor Documentation
ImGuiMenuColumns()
ImGuiMenuColumns::ImGuiMenuColumns ()
References memset(), and ImGui::Spacing().
Member Function Documentation
Update()
void ImGuiMenuColumns::Update (int count, float spacing, bool clear)
References IM_ARRAYSIZE, IM_ASSERT, memset(), and ImGui::Spacing().
Referenced by ImGui::Begin().
DeclColumns()
float ImGuiMenuColumns::DeclColumns (float w0, float w1, float w2)
References ImMax(), and ImGui::Spacing().
Referenced by ImGui::BeginMenu(), and ImGui::MenuItem().
CalcExtraSpace()
float ImGuiMenuColumns::CalcExtraSpace (float avail_w)
References ImMax().
Member Data Documentation
Count
int ImGuiMenuColumns::Count
Spacing
float ImGuiMenuColumns::Spacing
Width
float ImGuiMenuColumns::Width
NextWidth
float ImGuiMenuColumns::NextWidth
Pos
float ImGuiMenuColumns::Pos[4]
Referenced by ImGui::BeginMenu(), and ImGui::MenuItem().
NextWidths
float ImGuiMenuColumns::NextWidths[4]
The documentation for this struct was generated from the following files:
_ImGui.h
ImGui.cpp