Aurora Framework: aglib.h File Reference
aglib.h File Reference
Classes
struct AGParamRec
Macros
#define BITOFF 24
#define KB0 14
#define MAX_DATATYPE_BITS_16 16
#define MAX_PREFIX_16 9
#define MAX_PREFIX_32 9
#define MAX_PREFIX_TOLONG_16 15
#define MAX_RUN_DEFAULT 255
#define MB0 10
#define MDENSHIFT (QBSHIFT - MMULSHIFT - 1)
#define MMULSHIFT 2
#define MOFF ((1 << (MDENSHIFT - 2)))
#define PB0 40
#define QB (1 << QBSHIFT)
#define QBSHIFT 9
Typedefs
typedef struct AGParamRec AGParamRec
typedef struct AGParamRec * AGParamRecPtr
Functions
int32_t dyn_comp (AGParamRecPtr params, int32_t *pc, struct BitBuffer *bitstream, int32_t numSamples, int32_t bitSize, uint32_t *outNumBits)
int32_t dyn_decomp (AGParamRecPtr params, struct BitBuffer *bitstream, int32_t *pc, int32_t numSamples, int32_t maxSize, uint32_t *outNumBits)
void set_ag_params (AGParamRecPtr params, uint32_t m, uint32_t p, uint32_t k, uint32_t f, uint32_t s, uint32_t maxrun)
void set_standard_ag_params (AGParamRecPtr params, uint32_t fullwidth, uint32_t sectorwidth)
Macro Definition Documentation
QBSHIFT
#define QBSHIFT 9
Referenced by dyn_comp(), and dyn_decomp().
QB
#define QB (1 << QBSHIFT)
Referenced by dyn_comp(), dyn_decomp(), and set_ag_params().
PB0
#define PB0 40
Referenced by EncodeMono(), EncodeStereo(), EncodeStereoFast(), GetConfig(), and set_standard_ag_params().
MB0
#define MB0 10
Referenced by EncodeMono(), EncodeStereo(), EncodeStereoFast(), GetConfig(), and set_standard_ag_params().
KB0
#define KB0 14
Referenced by EncodeMono(), EncodeStereo(), EncodeStereoFast(), GetConfig(), and set_standard_ag_params().
MAX_RUN_DEFAULT
#define MAX_RUN_DEFAULT 255
Referenced by EncodeMono(), EncodeStereo(), EncodeStereoFast(), GetConfig(), and set_standard_ag_params().
MMULSHIFT
#define MMULSHIFT 2
Referenced by dyn_comp(), and dyn_decomp().
MDENSHIFT
#define MDENSHIFT (QBSHIFT - MMULSHIFT - 1)
Referenced by dyn_comp(), and dyn_decomp().
MOFF
#define MOFF ((1 << (MDENSHIFT - 2)))
Referenced by dyn_comp(), and dyn_decomp().
BITOFF
#define BITOFF 24
Referenced by dyn_comp(), and dyn_decomp().
MAX_PREFIX_16
#define MAX_PREFIX_16 9
Referenced by dyn_code(), and dyn_get().
MAX_PREFIX_TOLONG_16
#define MAX_PREFIX_TOLONG_16 15
MAX_PREFIX_32
#define MAX_PREFIX_32 9
Referenced by dyn_code_32bit(), and dyn_get_32bit().
MAX_DATATYPE_BITS_16
#define MAX_DATATYPE_BITS_16 16
Referenced by dyn_code(), and dyn_get().
Typedef Documentation
AGParamRec
typedef struct AGParamRec AGParamRec
AGParamRecPtr
typedef struct AGParamRec * AGParamRecPtr
Function Documentation
set_standard_ag_params()
void set_standard_ag_params (AGParamRecPtr params, uint32_t fullwidth, uint32_t sectorwidth)
References KB0, MAX_RUN_DEFAULT, MB0, PB0, and set_ag_params().
Referenced by EncodeMono().
set_ag_params()
void set_ag_params (AGParamRecPtr params, uint32_t m, uint32_t p, uint32_t k, uint32_t f, uint32_t s, uint32_t maxrun)
References AGParamRec::fw, AGParamRec::kb, AGParamRec::maxrun, AGParamRec::mb, AGParamRec::mb0, AGParamRec::pb, QB, AGParamRec::qb, AGParamRec::sw, and AGParamRec::wb.
Referenced by alac_decode(), EncodeMono(), EncodeStereo(), EncodeStereoFast(), and set_standard_ag_params().
dyn_comp()
int32_t dyn_comp (AGParamRecPtr params, int32_t * pc, struct BitBuffer * bitstream, int32_t numSamples, int32_t bitSize, uint32_t * outNumBits)
References abs_func(), ALAC_noErr, BitBufferAdvance(), BitBuffer::bitIndex, BITOFF, BitBuffer::cur, dyn_code(), dyn_code_32bit(), dyn_jam_noDeref(), dyn_jam_noDeref_large(), AGParamRec::fw, kALAC_ParamError, AGParamRec::kb, lead(), lg3a(), AGParamRec::mb, AGParamRec::mb0, MDENSHIFT, MMULSHIFT, MOFF, N_MAX_MEAN_CLAMP, N_MEAN_CLAMP_VAL, AGParamRec::pb, QB, QBSHIFT, RequireAction, AGParamRec::sw, value, and AGParamRec::wb.
Referenced by EncodeMono(), EncodeStereo(), and EncodeStereoFast().
dyn_decomp()
int32_t dyn_decomp (AGParamRecPtr params, struct BitBuffer * bitstream, int32_t * pc, int32_t numSamples, int32_t maxSize, uint32_t * outNumBits)
References ALAC_noErr, arithmin, BitBufferAdvance(), BitBuffer::bitIndex, BITOFF, BitBuffer::byteSize, BitBuffer::cur, dyn_get(), dyn_get_32bit(), BitBuffer::end, kALAC_ParamError, AGParamRec::kb, lead(), lg3a(), AGParamRec::mb0, MDENSHIFT, MMULSHIFT, MOFF, N_MAX_MEAN_CLAMP, N_MEAN_CLAMP_VAL, NULL, AGParamRec::pb, QB, QBSHIFT, RequireAction, and AGParamRec::wb.
Referenced by alac_decode().