Aurora Framework: htk.c File Reference
htk.c File Reference
Macros
#define SFE_HTK_BAD_FILE_LEN 1666
#define SFE_HTK_NOT_WAVEFORM 1667
Functions
static int htk_close (SF_PRIVATE *psf)
int htk_open (SF_PRIVATE *psf)
static int htk_read_header (SF_PRIVATE *psf)
static int htk_write_header (SF_PRIVATE *psf, int calc_length)
Macro Definition Documentation
SFE_HTK_BAD_FILE_LEN
#define SFE_HTK_BAD_FILE_LEN 1666
Referenced by htk_read_header().
SFE_HTK_NOT_WAVEFORM
#define SFE_HTK_NOT_WAVEFORM 1667
Referenced by htk_read_header().
Function Documentation
htk_close()
static int htk_close (SF_PRIVATE * psf) static
References sf_private_tag::file, htk_write_header(), and PSF_FILE::mode.
Referenced by htk_open().
htk_write_header()
static int htk_write_header (SF_PRIVATE * psf, int calc_length) static
References BHW4, sf_private_tag::dataoffset, sf_private_tag::error, sf_private_tag::filelength, sf_private_tag::header, sf_private_tag::indx, psf_binheader_writef(), psf_fseek(), psf_ftell(), psf_fwrite(), psf_get_filelen(), sf_private_tag::ptr, and sf_private_tag::sf.
Referenced by htk_close(), and htk_open().
htk_read_header()
static int htk_read_header (SF_PRIVATE * psf) static
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::endian, sf_private_tag::filelength, psf_binheader_readf(), psf_log_printf(), sf_private_tag::sf, SFE_HTK_BAD_FILE_LEN, and SFE_HTK_NOT_WAVEFORM.
Referenced by htk_open().
htk_open()
int htk_open (SF_PRIVATE * psf)
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::container_close, sf_private_tag::endian, sf_private_tag::error, sf_private_tag::file, sf_private_tag::filelength, htk_close(), htk_read_header(), htk_write_header(), sf_private_tag::is_pipe, PSF_FILE::mode, pcm_init(), sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SFE_BAD_OPEN_FORMAT, SFE_HTK_NO_PIPE, and sf_private_tag::write_header.
Referenced by psf_open_file().