Aurora Framework: Window.c File Reference
X11/Window.c File Reference
Macros
#define _GLFW_XDND_VERSION 5
#define _NET_WM_STATE_ADD 1
#define _NET_WM_STATE_REMOVE 0
#define _NET_WM_STATE_TOGGLE 2
#define Button6 6
#define Button7 7
Functions
unsigned long _glfwGetWindowPropertyX11 (Window window, Atom property, Atom type, unsigned char **value)
GLFWbool _glfwIsVisualTransparentX11 (Visual *visual)
int _glfwPlatformCreateCursor (_GLFWcursor *cursor, const GLFWimage *image, int xhot, int yhot)
int _glfwPlatformCreateStandardCursor (_GLFWcursor *cursor, int shape)
int _glfwPlatformCreateWindow (_GLFWwindow *window, const _GLFWwndconfig *wndconfig, const _GLFWctxconfig *ctxconfig, const _GLFWfbconfig *fbconfig)
VkResult _glfwPlatformCreateWindowSurface (VkInstance instance, _GLFWwindow *window, const VkAllocationCallbacks *allocator, VkSurfaceKHR *surface)
void _glfwPlatformDestroyCursor (_GLFWcursor *cursor)
void _glfwPlatformDestroyWindow (_GLFWwindow *window)
void _glfwPlatformFocusWindow (_GLFWwindow *window)
int _glfwPlatformFramebufferTransparent (_GLFWwindow *window)
const char * _glfwPlatformGetClipboardString (void)
void _glfwPlatformGetCursorPos (_GLFWwindow *window, double *xpos, double *ypos)
void _glfwPlatformGetFramebufferSize (_GLFWwindow *window, int *width, int *height)
int _glfwPlatformGetKeyScancode (int key)
int _glfwPlatformGetPhysicalDevicePresentationSupport (VkInstance instance, VkPhysicalDevice device, uint32_t queuefamily)
void _glfwPlatformGetRequiredInstanceExtensions (char **extensions)
const char * _glfwPlatformGetScancodeName (int scancode)
void _glfwPlatformGetWindowContentScale (_GLFWwindow *window, float *xscale, float *yscale)
void _glfwPlatformGetWindowFrameSize (_GLFWwindow *window, int *left, int *top, int *right, int *bottom)
float _glfwPlatformGetWindowOpacity (_GLFWwindow *window)
void _glfwPlatformGetWindowPos (_GLFWwindow *window, int *xpos, int *ypos)
void _glfwPlatformGetWindowSize (_GLFWwindow *window, int *width, int *height)
void _glfwPlatformHideWindow (_GLFWwindow *window)
void _glfwPlatformIconifyWindow (_GLFWwindow *window)
void _glfwPlatformMaximizeWindow (_GLFWwindow *window)
void _glfwPlatformPollEvents (void)
void _glfwPlatformPostEmptyEvent (void)
void _glfwPlatformRequestWindowAttention (_GLFWwindow *window)
void _glfwPlatformRestoreWindow (_GLFWwindow *window)
void _glfwPlatformSetClipboardString (const char *string)
void _glfwPlatformSetCursor (_GLFWwindow *window, _GLFWcursor *cursor)
void _glfwPlatformSetCursorMode (_GLFWwindow *window, int mode)
void _glfwPlatformSetCursorPos (_GLFWwindow *window, double x, double y)
void _glfwPlatformSetWindowAspectRatio (_GLFWwindow *window, int numer, int denom)
void _glfwPlatformSetWindowDecorated (_GLFWwindow *window, GLFWbool enabled)
void _glfwPlatformSetWindowFloating (_GLFWwindow *window, GLFWbool enabled)
void _glfwPlatformSetWindowIcon (_GLFWwindow *window, int count, const GLFWimage *images)
void _glfwPlatformSetWindowMonitor (_GLFWwindow *window, _GLFWmonitor *monitor, int xpos, int ypos, int width, int height, int refreshRate)
void _glfwPlatformSetWindowOpacity (_GLFWwindow *window, float opacity)
void _glfwPlatformSetWindowPos (_GLFWwindow *window, int xpos, int ypos)
void _glfwPlatformSetWindowResizable (_GLFWwindow *window, GLFWbool enabled)
void _glfwPlatformSetWindowSize (_GLFWwindow *window, int width, int height)
void _glfwPlatformSetWindowSizeLimits (_GLFWwindow *window, int minwidth, int minheight, int maxwidth, int maxheight)
void _glfwPlatformSetWindowTitle (_GLFWwindow *window, const char *title)
void _glfwPlatformShowWindow (_GLFWwindow *window)
void _glfwPlatformWaitEvents (void)
void _glfwPlatformWaitEventsTimeout (double timeout)
int _glfwPlatformWindowFocused (_GLFWwindow *window)
int _glfwPlatformWindowHovered (_GLFWwindow *window)
int _glfwPlatformWindowIconified (_GLFWwindow *window)
int _glfwPlatformWindowMaximized (_GLFWwindow *window)
int _glfwPlatformWindowVisible (_GLFWwindow *window)
void _glfwPushSelectionToManagerX11 (void)
static void acquireMonitor (_GLFWwindow *window)
static void centerCursor (_GLFWwindow *window)
static char * convertLatin1toUTF8 (const char *source)
static GLFWbool createNativeWindow (_GLFWwindow *window, const _GLFWwndconfig *wndconfig, Visual *visual, int depth)
static size_t encodeUTF8 (char *s, unsigned int ch)
static _GLFWwindow * findWindowByHandle (Window handle)
static const char * getSelectionString (Atom selection)
static int getWindowState (_GLFWwindow *window)
GLFWAPI Display * glfwGetX11Display (void)
GLFWAPI const char * glfwGetX11SelectionString (void)
GLFWAPI Window glfwGetX11Window (GLFWwindow *handle)
GLFWAPI void glfwSetX11SelectionString (const char *string)
static void handleSelectionClear (XEvent *event)
static void handleSelectionRequest (XEvent *event)
static Bool isFrameExtentsEvent (Display *display, XEvent *event, XPointer pointer)
static Bool isSelectionEvent (Display *display, XEvent *event, XPointer pointer)
static Bool isSelPropNewValueNotify (Display *display, XEvent *event, XPointer pointer)
static char ** parseUriList (char *text, int *count)
static void processEvent (XEvent *event)
static void releaseMonitor (_GLFWwindow *window)
static void sendEventToWM (_GLFWwindow *window, Atom type, long a, long b, long c, long d, long e)
static int translateCursorShape (int shape)
static int translateKey (int scancode)
static int translateState (int state)
static void updateCursorImage (_GLFWwindow *window)
static void updateNormalHints (_GLFWwindow *window, int width, int height)
static void updateWindowMode (_GLFWwindow *window)
static GLFWbool waitForEvent (double *timeout)
static GLFWbool waitForVisibilityNotify (_GLFWwindow *window)
static Atom writeTargetToProperty (const XSelectionRequestEvent *request)
Macro Definition Documentation
_NET_WM_STATE_REMOVE
#define _NET_WM_STATE_REMOVE 0
Referenced by _glfwPlatformRestoreWindow(), _glfwPlatformSetWindowFloating(), and updateWindowMode().
_NET_WM_STATE_ADD
#define _NET_WM_STATE_ADD 1
Referenced by _glfwPlatformMaximizeWindow(), _glfwPlatformRequestWindowAttention(), _glfwPlatformSetWindowFloating(), and updateWindowMode().
_NET_WM_STATE_TOGGLE
#define _NET_WM_STATE_TOGGLE 2
Button6
#define Button6 6
Referenced by processEvent().
Button7
#define Button7 7
Referenced by processEvent().
_GLFW_XDND_VERSION
#define _GLFW_XDND_VERSION 5
Referenced by createNativeWindow(), and processEvent().
Function Documentation
waitForEvent()
static GLFWbool waitForEvent (double * timeout) static
References _glfw, _glfwPlatformGetTimerFrequency(), _glfwPlatformGetTimerValue(), GLFW_FALSE, GLFW_TRUE, and NULL.
Referenced by _glfwPlatformGetWindowFrameSize(), _glfwPlatformWaitEvents(), _glfwPlatformWaitEventsTimeout(), _glfwPushSelectionToManagerX11(), getSelectionString(), and waitForVisibilityNotify().
waitForVisibilityNotify()
static GLFWbool waitForVisibilityNotify (_GLFWwindow * window) static
References _glfw, GLFW_FALSE, GLFW_TRUE, and waitForEvent().
Referenced by _glfwPlatformRestoreWindow(), _glfwPlatformSetWindowMonitor(), and _glfwPlatformShowWindow().
getWindowState()
static int getWindowState (_GLFWwindow * window) static
References _glfw, _glfwGetWindowPropertyX11(), and NULL.
Referenced by _glfwPlatformWindowIconified(), and processEvent().
isSelectionEvent()
static Bool isSelectionEvent (Display * display, XEvent * event, XPointer pointer) static
References _glfw.
Referenced by _glfwPushSelectionToManagerX11().
isFrameExtentsEvent()
static Bool isFrameExtentsEvent (Display * display, XEvent * event, XPointer pointer) static
References _glfw, and pointer.
Referenced by _glfwPlatformGetWindowFrameSize().
isSelPropNewValueNotify()
static Bool isSelPropNewValueNotify (Display * display, XEvent * event, XPointer pointer) static
References pointer.
Referenced by getSelectionString().
translateCursorShape()
static int translateCursorShape (int shape) static
References GLFW_ARROW_CURSOR, GLFW_CROSSHAIR_CURSOR, GLFW_HAND_CURSOR, GLFW_HRESIZE_CURSOR, GLFW_IBEAM_CURSOR, and GLFW_VRESIZE_CURSOR.
Referenced by _glfwPlatformCreateStandardCursor().
translateState()
static int translateState (int state) static
References GLFW_MOD_ALT, GLFW_MOD_CAPS_LOCK, GLFW_MOD_CONTROL, GLFW_MOD_NUM_LOCK, GLFW_MOD_SHIFT, and GLFW_MOD_SUPER.
Referenced by processEvent().
translateKey()
static int translateKey (int scancode) static
References _glfw, and GLFW_KEY_UNKNOWN.
Referenced by processEvent().
findWindowByHandle()
static _GLFWwindow* findWindowByHandle (Window handle) static
References _glfw, _GLFWlibrary::context, and NULL.
Referenced by processEvent().
sendEventToWM()
static void sendEventToWM (_GLFWwindow * window, Atom type, long a, long b, long c, long d, long e) static
References _glfw, a, and memset().
Referenced by _glfwPlatformFocusWindow(), _glfwPlatformGetWindowFrameSize(), _glfwPlatformMaximizeWindow(), _glfwPlatformRequestWindowAttention(), _glfwPlatformRestoreWindow(), _glfwPlatformSetWindowFloating(), and updateWindowMode().
updateNormalHints()
static void updateNormalHints (_GLFWwindow * window, int width, int height) static
References _glfw, _GLFWwindow::denom, GLFW_DONT_CARE, height, _GLFWwindow::maxheight, _GLFWwindow::maxwidth, _GLFWwindow::minheight, _GLFWwindow::minwidth, _GLFWwindow::monitor, _GLFWwindow::numer, _GLFWwindow::resizable, and width.
Referenced by _glfwPlatformSetWindowAspectRatio(), _glfwPlatformSetWindowMonitor(), _glfwPlatformSetWindowResizable(), _glfwPlatformSetWindowSize(), _glfwPlatformSetWindowSizeLimits(), and createNativeWindow().
updateWindowMode()
static void updateWindowMode (_GLFWwindow * window) static
References _glfw, _NET_WM_STATE_ADD, _NET_WM_STATE_REMOVE, _GLFWlibrary::available, GLFW_FALSE, GLFW_TRUE, _GLFWwindow::monitor, sendEventToWM(), and value.
Referenced by _glfwPlatformCreateWindow(), and _glfwPlatformSetWindowMonitor().
parseUriList()
static char** parseUriList (char * text, int * count) static
References NULL.
Referenced by processEvent().
encodeUTF8()
static size_t encodeUTF8 (char * s, unsigned int ch) static
Referenced by _glfwPlatformGetScancodeName(), and convertLatin1toUTF8().
convertLatin1toUTF8()
static char* convertLatin1toUTF8 (const char * source) static
References encodeUTF8(), and source.
Referenced by getSelectionString().
centerCursor()
static void centerCursor (_GLFWwindow * window) static
References _glfwPlatformGetWindowSize(), _glfwPlatformSetCursorPos(), height, and width.
Referenced by _glfwPlatformSetCursorMode().
updateCursorImage()
static void updateCursorImage (_GLFWwindow * window) static
References _glfw, _GLFWwindow::cursor, _GLFWwindow::cursorMode, and GLFW_CURSOR_NORMAL.
Referenced by _glfwPlatformSetCursor(), and _glfwPlatformSetCursorMode().
createNativeWindow()
static GLFWbool createNativeWindow (_GLFWwindow * window, const _GLFWwndconfig * wndconfig, Visual * visual, int depth) static
References _glfw, _GLFW_XDND_VERSION, _glfwGrabErrorHandlerX11(), _glfwInputError(), _glfwInputErrorX11(), _glfwIsVisualTransparentX11(), _glfwPlatformGetWindowPos(), _glfwPlatformGetWindowSize(), _glfwPlatformSetWindowDecorated(), _glfwPlatformSetWindowTitle(), _glfwReleaseErrorHandlerX11(), _GLFWwndconfig::className, _GLFWlibrary::context, _GLFWwndconfig::decorated, _GLFWwndconfig::floating, GLFW_FALSE, GLFW_OUT_OF_MEMORY, GLFW_PLATFORM_ERROR, GLFW_TRUE, _GLFWwndconfig::height, _GLFWwndconfig::instanceName, _GLFWwndconfig::maximized, _GLFWwindow::monitor, NULL, _GLFWwndconfig::title, updateNormalHints(), create_symbols_file::version, _GLFWwndconfig::width, and _GLFWwndconfig::x11.
Referenced by _glfwPlatformCreateWindow().
writeTargetToProperty()
static Atom writeTargetToProperty (const XSelectionRequestEvent * request) static
References _glfw, _glfwGetWindowPropertyX11(), AuroraFW::None, and NULL.
Referenced by handleSelectionRequest().
handleSelectionClear()
static void handleSelectionClear (XEvent * event) static
References _glfw, and NULL.
Referenced by _glfwPushSelectionToManagerX11(), and processEvent().
handleSelectionRequest()
static void handleSelectionRequest (XEvent * event) static
References _glfw, memset(), and writeTargetToProperty().
Referenced by _glfwPushSelectionToManagerX11(), and processEvent().
getSelectionString()
static const char* getSelectionString (Atom selection) static
References _glfw, _glfw_strdup(), _glfwInputError(), convertLatin1toUTF8(), GLFW_FORMAT_UNAVAILABLE, isSelPropNewValueNotify(), AuroraFW::None, NULL, and waitForEvent().
Referenced by _glfwPlatformGetClipboardString(), and glfwGetX11SelectionString().
acquireMonitor()
static void acquireMonitor (_GLFWwindow * window) static
References _glfw, _glfwInputMonitorWindow(), _glfwPlatformGetMonitorPos(), _glfwPlatformGetVideoMode(), _glfwSetVideoModeX11(), mode(), _GLFWwindow::monitor, _GLFWwindow::videoMode, and _GLFWmonitor::window.
Referenced by _glfwPlatformCreateWindow(), _glfwPlatformSetWindowMonitor(), _glfwPlatformSetWindowSize(), and processEvent().
releaseMonitor()
static void releaseMonitor (_GLFWwindow * window) static
References _glfw, _glfwInputMonitorWindow(), _glfwRestoreVideoModeX11(), _GLFWwindow::monitor, NULL, and _GLFWmonitor::window.
Referenced by _glfwPlatformDestroyWindow(), _glfwPlatformSetWindowMonitor(), and processEvent().
processEvent()
static void processEvent (XEvent * event) static
References _glfw, _GLFW_XDND_VERSION, _glfwGetWindowPropertyX11(), _glfwInputChar(), _glfwInputCursorEnter(), _glfwInputCursorPos(), _glfwInputDrop(), _glfwInputFramebufferSize(), _glfwInputKey(), _glfwInputMouseClick(), _glfwInputScroll(), _glfwInputWindowCloseRequest(), _glfwInputWindowDamage(), _glfwInputWindowFocus(), _glfwInputWindowIconify(), _glfwInputWindowMaximize(), _glfwInputWindowPos(), _glfwInputWindowSize(), _glfwKeySym2Unicode(), _glfwPlatformIconifyWindow(), _glfwPlatformSetCursorMode(), _glfwPlatformWindowMaximized(), _glfwPollMonitorsX11(), acquireMonitor(), _GLFWwindow::autoIconify, _GLFWlibrary::available, Button6, Button7, _GLFWwindow::cursorMode, findWindowByHandle(), getWindowState(), GLFW_CURSOR_DISABLED, GLFW_CURSOR_HIDDEN, GLFW_CURSOR_NORMAL, GLFW_FALSE, GLFW_MOD_ALT, GLFW_MOD_CONTROL, GLFW_MOUSE_BUTTON_LEFT, GLFW_MOUSE_BUTTON_MIDDLE, GLFW_MOUSE_BUTTON_RIGHT, GLFW_PRESS, GLFW_RELEASE, GLFW_TRUE, handleSelectionClear(), handleSelectionRequest(), memset(), _GLFWwindow::monitor, AuroraFW::None, NULL, parseUriList(), releaseMonitor(), translateKey(), translateState(), _GLFWwindow::virtualCursorPosX, _GLFWwindow::virtualCursorPosY, and XRRUpdateConfiguration.
Referenced by _glfwPlatformPollEvents().
_glfwGetWindowPropertyX11()
unsigned long _glfwGetWindowPropertyX11 (Window window, Atom property, Atom type, unsigned char ** value)
References _glfw, and value.
Referenced by _glfwPlatformGetWindowFrameSize(), _glfwPlatformGetWindowOpacity(), _glfwPlatformSetWindowFloating(), _glfwPlatformWindowMaximized(), detectEWMH(), getWindowState(), processEvent(), and writeTargetToProperty().
_glfwIsVisualTransparentX11()
GLFWbool _glfwIsVisualTransparentX11 (Visual * visual)
References _glfw, _GLFWlibrary::available, GLFW_FALSE, and XRenderFindVisualFormat.
Referenced by chooseEGLConfig(), chooseGLXFBConfig(), and createNativeWindow().
_glfwPushSelectionToManagerX11()
void _glfwPushSelectionToManagerX11 (void)
References _glfw, handleSelectionClear(), handleSelectionRequest(), isSelectionEvent(), AuroraFW::None, NULL, and waitForEvent().
Referenced by _glfwPlatformTerminate().
_glfwPlatformCreateWindow()
int _glfwPlatformCreateWindow (_GLFWwindow * window, const _GLFWwndconfig * wndconfig, const _GLFWctxconfig * ctxconfig, const _GLFWfbconfig * fbconfig)
References _glfw, _glfwChooseVisualGLX(), _glfwCreateContextEGL(), _glfwCreateContextGLX(), _glfwCreateContextNSGL(), _glfwCreateContextOSMesa(), _glfwInitEGL(), _glfwInitGLX(), _glfwInitNSGL(), _glfwInitOSMesa(), _glfwPlatformFocusWindow(), _glfwPlatformShowWindow(), acquireMonitor(), _GLFWctxconfig::client, createNativeWindow(), GLFW_EGL_CONTEXT_API, GLFW_FALSE, GLFW_NATIVE_CONTEXT_API, GLFW_NO_API, GLFW_OSMESA_CONTEXT_API, GLFW_TRUE, initializeAppKit(), _GLFWwindow::monitor, _GLFWctxconfig::source, and updateWindowMode().
_glfwPlatformDestroyWindow()
void _glfwPlatformDestroyWindow (_GLFWwindow * window)
References _glfw, _GLFWwindow::close, _GLFWwindow::context, _GLFWlibrary::context, _GLFWcontext::destroy, _GLFWwindow::monitor, NULL, and releaseMonitor().
_glfwPlatformSetWindowTitle()
void _glfwPlatformSetWindowTitle (_GLFWwindow * window, const char * title)
References _glfw, and NULL.
Referenced by createNativeWindow().
_glfwPlatformSetWindowIcon()
void _glfwPlatformSetWindowIcon (_GLFWwindow * window, int count, const GLFWimage * images)
References _glfw, height, GLFWimage::height, GLFWimage::pixels, width, and GLFWimage::width.
_glfwPlatformGetWindowPos()
void _glfwPlatformGetWindowPos (_GLFWwindow * window, int * xpos, int * ypos)
References _glfw, and transformY().
Referenced by createNativeWindow().
_glfwPlatformSetWindowPos()
void _glfwPlatformSetWindowPos (_GLFWwindow * window, int xpos, int ypos)
References _glfw, _glfwPlatformWindowVisible(), and transformY().
_glfwPlatformGetWindowSize()
void _glfwPlatformGetWindowSize (_GLFWwindow * window, int * width, int * height)
References _glfw, height, and width.
Referenced by _glfwPlatformGetFramebufferSize(), _glfwPlatformPollEvents(), _glfwPlatformSetWindowAspectRatio(), _glfwPlatformSetWindowResizable(), _glfwPlatformSetWindowSizeLimits(), centerCursor(), and createNativeWindow().
_glfwPlatformSetWindowSize()
void _glfwPlatformSetWindowSize (_GLFWwindow * window, int width, int height)
References _glfw, acquireMonitor(), height, _GLFWwindow::monitor, _GLFWwindow::resizable, updateNormalHints(), width, and _GLFWmonitor::window.
_glfwPlatformSetWindowSizeLimits()
void _glfwPlatformSetWindowSizeLimits (_GLFWwindow * window, int minwidth, int minheight, int maxwidth, int maxheight)
References _glfw, _glfwPlatformGetWindowSize(), GLFW_DONT_CARE, height, updateNormalHints(), and width.
_glfwPlatformSetWindowAspectRatio()
void _glfwPlatformSetWindowAspectRatio (_GLFWwindow * window, int numer, int denom)
References _glfw, _glfwPlatformGetWindowSize(), GLFW_DONT_CARE, height, updateNormalHints(), and width.
_glfwPlatformGetFramebufferSize()
void _glfwPlatformGetFramebufferSize (_GLFWwindow * window, int * width, int * height)
References _glfwPlatformGetWindowSize(), height, and width.
_glfwPlatformGetWindowFrameSize()
void _glfwPlatformGetWindowFrameSize (_GLFWwindow * window, int * left, int * top, int * right, int * bottom)
References _glfw, _glfwGetWindowPropertyX11(), _glfwInputError(), _glfwPlatformWindowVisible(), _GLFWwindow::decorated, GLFW_PLATFORM_ERROR, isFrameExtentsEvent(), _GLFWwindow::monitor, AuroraFW::None, NULL, sendEventToWM(), and waitForEvent().
_glfwPlatformGetWindowContentScale()
void _glfwPlatformGetWindowContentScale (_GLFWwindow * window, float * xscale, float * yscale)
References _glfw.
_glfwPlatformIconifyWindow()
void _glfwPlatformIconifyWindow (_GLFWwindow * window)
References _glfw, _glfwInputError(), and GLFW_PLATFORM_ERROR.
Referenced by processEvent().
_glfwPlatformRestoreWindow()
void _glfwPlatformRestoreWindow (_GLFWwindow * window)
References _glfw, _glfwInputError(), _glfwPlatformWindowIconified(), _glfwPlatformWindowVisible(), _NET_WM_STATE_REMOVE, GLFW_PLATFORM_ERROR, sendEventToWM(), and waitForVisibilityNotify().
_glfwPlatformMaximizeWindow()
void _glfwPlatformMaximizeWindow (_GLFWwindow * window)
References _glfw, _NET_WM_STATE_ADD, and sendEventToWM().
_glfwPlatformShowWindow()
void _glfwPlatformShowWindow (_GLFWwindow * window)
References _glfw, _glfwPlatformWindowVisible(), and waitForVisibilityNotify().
Referenced by _glfwPlatformCreateWindow().
_glfwPlatformHideWindow()
void _glfwPlatformHideWindow (_GLFWwindow * window)
References _glfw.
_glfwPlatformRequestWindowAttention()
void _glfwPlatformRequestWindowAttention (_GLFWwindow * window)
References _glfw, _NET_WM_STATE_ADD, and sendEventToWM().
_glfwPlatformFocusWindow()
void _glfwPlatformFocusWindow (_GLFWwindow * window)
References _glfw, and sendEventToWM().
_glfwPlatformSetWindowMonitor()
void _glfwPlatformSetWindowMonitor (_GLFWwindow * window, _GLFWmonitor * monitor, int xpos, int ypos, int width, int height, int refreshRate)
References _glfw, _glfwInputWindowMonitor(), _glfwPlatformPollEvents(), acquireMonitor(), _GLFWwindow::denom, _GLFWwindow::floating, getStyleMask(), GLFW_DONT_CARE, height, _GLFWwindow::maxheight, _GLFWwindow::maxwidth, _GLFWwindow::minheight, _GLFWwindow::minwidth, _GLFWwindow::monitor, _GLFWwindow::numer, releaseMonitor(), transformY(), updateNormalHints(), updateWindowMode(), waitForVisibilityNotify(), width, and _GLFWmonitor::window.
_glfwPlatformWindowFocused()
int _glfwPlatformWindowFocused (_GLFWwindow * window)
References _glfw.
_glfwPlatformWindowIconified()
int _glfwPlatformWindowIconified (_GLFWwindow * window)
References getWindowState().
Referenced by _glfwPlatformRestoreWindow().
_glfwPlatformWindowVisible()
int _glfwPlatformWindowVisible (_GLFWwindow * window)
References _glfw.
Referenced by _glfwPlatformGetWindowFrameSize(), _glfwPlatformRestoreWindow(), _glfwPlatformSetWindowFloating(), _glfwPlatformSetWindowPos(), and _glfwPlatformShowWindow().
_glfwPlatformWindowMaximized()
int _glfwPlatformWindowMaximized (_GLFWwindow * window)
References _glfw, _glfwGetWindowPropertyX11(), GLFW_FALSE, and GLFW_TRUE.
Referenced by processEvent().
_glfwPlatformWindowHovered()
int _glfwPlatformWindowHovered (_GLFWwindow * window)
References _glfw, GLFW_FALSE, and GLFW_TRUE.
_glfwPlatformFramebufferTransparent()
int _glfwPlatformFramebufferTransparent (_GLFWwindow * window)
References _glfw, GLFW_FALSE, and AuroraFW::None.
_glfwPlatformSetWindowResizable()
void _glfwPlatformSetWindowResizable (_GLFWwindow * window, GLFWbool enabled)
References _glfwPlatformGetWindowSize(), height, updateNormalHints(), and width.
_glfwPlatformSetWindowDecorated()
void _glfwPlatformSetWindowDecorated (_GLFWwindow * window, GLFWbool enabled)
References _glfw.
Referenced by createNativeWindow().
_glfwPlatformSetWindowFloating()
void _glfwPlatformSetWindowFloating (_GLFWwindow * window, GLFWbool enabled)
References _glfw, _glfwGetWindowPropertyX11(), _glfwPlatformWindowVisible(), _NET_WM_STATE_ADD, _NET_WM_STATE_REMOVE, and sendEventToWM().
_glfwPlatformGetWindowOpacity()
float _glfwPlatformGetWindowOpacity (_GLFWwindow * window)
References _glfw, _glfwGetWindowPropertyX11(), NULL, and value.
_glfwPlatformSetWindowOpacity()
void _glfwPlatformSetWindowOpacity (_GLFWwindow * window, float opacity)
References _glfw, and value.
_glfwPlatformPollEvents()
void _glfwPlatformPollEvents (void)
References _glfw, _glfwDetectJoystickConnectionLinux(), _glfwPlatformGetWindowSize(), _glfwPlatformSetCursorPos(), height, initializeAppKit(), processEvent(), and width.
Referenced by _glfwPlatformWaitEvents(), and _glfwPlatformWaitEventsTimeout().
_glfwPlatformWaitEvents()
void _glfwPlatformWaitEvents (void)
References _glfw, _glfwPlatformPollEvents(), NULL, and waitForEvent().
_glfwPlatformWaitEventsTimeout()
void _glfwPlatformWaitEventsTimeout (double timeout)
References _glfw, _glfwPlatformPollEvents(), and waitForEvent().
_glfwPlatformPostEmptyEvent()
void _glfwPlatformPostEmptyEvent (void)
References _glfw, and memset().
_glfwPlatformGetCursorPos()
void _glfwPlatformGetCursorPos (_GLFWwindow * window, double * xpos, double * ypos)
References _glfw.
Referenced by _glfwPlatformSetCursorMode().
_glfwPlatformSetCursorPos()
void _glfwPlatformSetCursorPos (_GLFWwindow * window, double x, double y)
References _glfw, _GLFWwindow::monitor, AuroraFW::None, _GLFWwindow::size, transformY(), and updateCursorImage().
Referenced by _glfwPlatformPollEvents(), _glfwPlatformSetCursorMode(), and centerCursor().
_glfwPlatformSetCursorMode()
void _glfwPlatformSetCursorMode (_GLFWwindow * window, int mode)
References _glfw, _glfwPlatformGetCursorPos(), _glfwPlatformSetCursorPos(), _GLFWlibrary::available, centerCursor(), cursorInClientArea(), GLFW_CURSOR_DISABLED, mode(), NULL, updateCursorImage(), and XISelectEvents.
Referenced by processEvent().
_glfwPlatformGetScancodeName()
const char* _glfwPlatformGetScancodeName (int scancode)
References _glfw, _glfwKeySym2Unicode(), _GLFWlibrary::available, encodeUTF8(), LMGetKbdType, and NULL.
_glfwPlatformGetKeyScancode()
int _glfwPlatformGetKeyScancode (int key)
References _glfw.
_glfwPlatformCreateCursor()
int _glfwPlatformCreateCursor (_GLFWcursor * cursor, const GLFWimage * image, int xhot, int yhot)
References _glfwCreateCursorX11(), GLFW_FALSE, GLFW_TRUE, GLFWimage::height, initializeAppKit(), memcpy(), GLFWimage::pixels, and GLFWimage::width.
_glfwPlatformCreateStandardCursor()
int _glfwPlatformCreateStandardCursor (_GLFWcursor * cursor, int shape)
References _glfw, _glfwInputError(), GLFW_ARROW_CURSOR, GLFW_CROSSHAIR_CURSOR, GLFW_FALSE, GLFW_HAND_CURSOR, GLFW_HRESIZE_CURSOR, GLFW_IBEAM_CURSOR, GLFW_PLATFORM_ERROR, GLFW_TRUE, GLFW_VRESIZE_CURSOR, initializeAppKit(), and translateCursorShape().
_glfwPlatformDestroyCursor()
void _glfwPlatformDestroyCursor (_GLFWcursor * cursor)
References _glfw.
_glfwPlatformSetCursor()
void _glfwPlatformSetCursor (_GLFWwindow * window, _GLFWcursor * cursor)
References _glfw, cursorInClientArea(), _GLFWwindow::cursorMode, GLFW_CURSOR_NORMAL, and updateCursorImage().
_glfwPlatformSetClipboardString()
void _glfwPlatformSetClipboardString (const char * string)
References _glfw, _glfw_strdup(), _glfwInputError(), and GLFW_PLATFORM_ERROR.
_glfwPlatformGetClipboardString()
const char* _glfwPlatformGetClipboardString (void)
References _glfw, _glfw_strdup(), _glfwInputError(), getSelectionString(), GLFW_FORMAT_UNAVAILABLE, GLFW_PLATFORM_ERROR, and NULL.
_glfwPlatformGetRequiredInstanceExtensions()
void _glfwPlatformGetRequiredInstanceExtensions (char ** extensions)
References _glfw, _GLFWlibrary::handle, _GLFWlibrary::KHR_surface, and _GLFWlibrary::vk.
_glfwPlatformGetPhysicalDevicePresentationSupport()
int _glfwPlatformGetPhysicalDevicePresentationSupport (VkInstance instance, VkPhysicalDevice device, uint32_t queuefamily)
References _glfw, _glfwInputError(), GLFW_API_UNAVAILABLE, GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, _GLFWlibrary::handle, _GLFWlibrary::vk, vkGetInstanceProcAddr(), and XGetXCBConnection.
_glfwPlatformCreateWindowSurface()
VkResult _glfwPlatformCreateWindowSurface (VkInstance instance, _GLFWwindow * window, const VkAllocationCallbacks * allocator, VkSurfaceKHR * surface)
References _glfw, _glfwGetVulkanResultString(), _glfwInputError(), VkXcbSurfaceCreateInfoKHR::connection, VkXlibSurfaceCreateInfoKHR::dpy, GLFW_API_UNAVAILABLE, GLFW_PLATFORM_ERROR, _GLFWlibrary::handle, memset(), VkMacOSSurfaceCreateInfoMVK::pView, VkMacOSSurfaceCreateInfoMVK::sType, VkXlibSurfaceCreateInfoKHR::sType, VkXcbSurfaceCreateInfoKHR::sType, _GLFWlibrary::vk, VK_ERROR_EXTENSION_NOT_PRESENT, VK_STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK, VK_STRUCTURE_TYPE_XCB_SURFACE_CREATE_INFO_KHR, VK_STRUCTURE_TYPE_XLIB_SURFACE_CREATE_INFO_KHR, vkGetInstanceProcAddr(), VkXlibSurfaceCreateInfoKHR::window, VkXcbSurfaceCreateInfoKHR::window, and XGetXCBConnection.
glfwGetX11Display()
GLFWAPI Display* glfwGetX11Display (void)
References _glfw, _GLFW_REQUIRE_INIT_OR_RETURN, and NULL.
glfwGetX11Window()
GLFWAPI Window glfwGetX11Window (GLFWwindow * handle)
References _GLFW_REQUIRE_INIT_OR_RETURN, and AuroraFW::None.
glfwSetX11SelectionString()
GLFWAPI void glfwSetX11SelectionString (const char * string)
References _glfw, _GLFW_REQUIRE_INIT, _glfw_strdup(), _glfwInputError(), and GLFW_PLATFORM_ERROR.
glfwGetX11SelectionString()
GLFWAPI const char* glfwGetX11SelectionString (void)
References _glfw, _GLFW_REQUIRE_INIT_OR_RETURN, getSelectionString(), and NULL.