Aurora Framework: Context.c File Reference
Context.c File Reference
Functions
const _GLFWfbconfig * _glfwChooseFBConfig (const _GLFWfbconfig *desired, const _GLFWfbconfig *alternatives, unsigned int count)
GLFWbool _glfwIsValidContextConfig (const _GLFWctxconfig *ctxconfig)
GLFWbool _glfwRefreshContextAttribs (_GLFWwindow *window, const _GLFWctxconfig *ctxconfig)
GLFWbool _glfwStringInExtensionString (const char *string, const char *extensions)
GLFWAPI int glfwExtensionSupported (const char *extension)
Returns whether the specified extension is available.
GLFWAPI GLFWwindow * glfwGetCurrentContext (void)
Returns the window whose context is current on the calling thread.
GLFWAPI GLFWglproc glfwGetProcAddress (const char *procname)
Returns the address of the specified function for the current context.
GLFWAPI void glfwMakeContextCurrent (GLFWwindow *handle)
Makes the context of the specified window current for the calling thread.
GLFWAPI void glfwSwapBuffers (GLFWwindow *handle)
Swaps the front and back buffers of the specified window.
GLFWAPI void glfwSwapInterval (int interval)
Sets the swap interval for the current context.
Function Documentation
_glfwIsValidContextConfig()
GLFWbool _glfwIsValidContextConfig (const _GLFWctxconfig * ctxconfig)
References _glfwInputError(), _GLFWctxconfig::client, _GLFWcontext::client, _GLFWwindow::context, _GLFWctxconfig::forward, GLFW_EGL_CONTEXT_API, GLFW_FALSE, GLFW_INVALID_ENUM, GLFW_INVALID_VALUE, GLFW_LOSE_CONTEXT_ON_RESET, GLFW_NATIVE_CONTEXT_API, GLFW_NO_API, GLFW_NO_RESET_NOTIFICATION, GLFW_NO_WINDOW_CONTEXT, GLFW_OPENGL_API, GLFW_OPENGL_COMPAT_PROFILE, GLFW_OPENGL_CORE_PROFILE, GLFW_OPENGL_ES_API, GLFW_OSMESA_CONTEXT_API, GLFW_RELEASE_BEHAVIOR_FLUSH, GLFW_RELEASE_BEHAVIOR_NONE, GLFW_TRUE, _GLFWctxconfig::major, _GLFWctxconfig::minor, NULL, _GLFWctxconfig::profile, _GLFWctxconfig::release, _GLFWctxconfig::robustness, _GLFWctxconfig::share, and _GLFWctxconfig::source.
Referenced by glfwCreateWindow().
_glfwChooseFBConfig()
const _GLFWfbconfig* _glfwChooseFBConfig (const _GLFWfbconfig * desired, const _GLFWfbconfig * alternatives, unsigned int count)
References _GLFWfbconfig::accumAlphaBits, _GLFWfbconfig::accumBlueBits, _GLFWfbconfig::accumGreenBits, _GLFWfbconfig::accumRedBits, _GLFWfbconfig::alphaBits, _GLFWfbconfig::auxBuffers, _GLFWfbconfig::blueBits, _GLFWfbconfig::depthBits, _GLFWfbconfig::doublebuffer, GLFW_DONT_CARE, _GLFWfbconfig::greenBits, NULL, _GLFWfbconfig::redBits, _GLFWfbconfig::samples, _GLFWfbconfig::sRGB, _GLFWfbconfig::stencilBits, _GLFWfbconfig::stereo, and _GLFWfbconfig::transparent.
Referenced by chooseEGLConfig(), chooseGLXFBConfig(), and choosePixelFormat().
_glfwRefreshContextAttribs()
GLFWbool _glfwRefreshContextAttribs (_GLFWwindow * window, const _GLFWctxconfig * ctxconfig)
References _glfw, _glfwInputError(), _glfwPlatformGetTls(), _GLFWctxconfig::client, _GLFWcontext::client, _GLFWwindow::context, _GLFWlibrary::contextSlot, _GLFWctxconfig::debug, GL_COLOR_BUFFER_BIT, GL_CONTEXT_COMPATIBILITY_PROFILE_BIT, GL_CONTEXT_CORE_PROFILE_BIT, GL_CONTEXT_FLAG_DEBUG_BIT, GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT, GL_CONTEXT_FLAG_NO_ERROR_BIT_KHR, GL_CONTEXT_FLAGS, GL_CONTEXT_PROFILE_MASK, GL_CONTEXT_RELEASE_BEHAVIOR, GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH, GL_LOSE_CONTEXT_ON_RESET_ARB, GL_NO_RESET_NOTIFICATION_ARB, GL_NONE, GL_RESET_NOTIFICATION_STRATEGY_ARB, GL_VERSION, GLFW_FALSE, GLFW_LOSE_CONTEXT_ON_RESET, GLFW_NO_RESET_NOTIFICATION, GLFW_OPENGL_API, GLFW_OPENGL_COMPAT_PROFILE, GLFW_OPENGL_CORE_PROFILE, GLFW_OPENGL_ES_API, GLFW_PLATFORM_ERROR, GLFW_RELEASE_BEHAVIOR_FLUSH, GLFW_RELEASE_BEHAVIOR_NONE, GLFW_TRUE, GLFW_VERSION_UNAVAILABLE, glfwExtensionSupported(), glfwMakeContextCurrent(), _GLFWctxconfig::major, _GLFWctxconfig::minor, NULL, _GLFWctxconfig::source, _GLFWcontext::source, and create_symbols_file::version.
Referenced by glfwCreateWindow().
_glfwStringInExtensionString()
GLFWbool _glfwStringInExtensionString (const char * string, const char * extensions)
References GLFW_FALSE, and GLFW_TRUE.
Referenced by extensionSupportedEGL(), extensionSupportedGLX(), extensionSupportedWGL(), and glfwExtensionSupported().