Aurora Framework: spirv_cross::CompilerMSL::Options Struct Reference
spirv_cross::CompilerMSL::Options Struct Reference
Public Types
enum Platform { iOS, macOS }
Public Member Functions
bool is_ios ()
bool is_macos ()
void set_msl_version (uint32_t major, uint32_t minor=0, uint32_t patch=0)
bool supports_msl_version (uint32_t major, uint32_t minor=0, uint32_t patch=0)
Static Public Member Functions
static uint32_t make_msl_version (uint32_t major, uint32_t minor=0, uint32_t patch=0)
Public Attributes
bool enable_point_size_builtin = true
uint32_t msl_version = make_msl_version(1, 2)
Platform platform = macOS
bool resolve_specialized_array_lengths = true
Member Enumeration Documentation
Platform
enum spirv_cross::CompilerMSL::Options::Platform
Enumerator
iOS
macOS
Member Function Documentation
is_ios()
bool spirv_cross::CompilerMSL::Options::is_ios () inline
References iOS, and platform.
is_macos()
bool spirv_cross::CompilerMSL::Options::is_macos () inline
References macOS, and platform.
set_msl_version()
void spirv_cross::CompilerMSL::Options::set_msl_version (uint32_t major, uint32_t minor = 0, uint32_t patch = 0) inline
References make_msl_version(), and msl_version.
supports_msl_version()
bool spirv_cross::CompilerMSL::Options::supports_msl_version (uint32_t major, uint32_t minor = 0, uint32_t patch = 0) inline
References make_msl_version(), and msl_version.
make_msl_version()
static uint32_t spirv_cross::CompilerMSL::Options::make_msl_version (uint32_t major, uint32_t minor = 0, uint32_t patch = 0) inline static
Referenced by set_msl_version(), and supports_msl_version().
Member Data Documentation
platform
Platform spirv_cross::CompilerMSL::Options::platform = macOS
Referenced by is_ios(), and is_macos().
msl_version
uint32_t spirv_cross::CompilerMSL::Options::msl_version = make_msl_version(1, 2)
Referenced by set_msl_version(), and supports_msl_version().
enable_point_size_builtin
bool spirv_cross::CompilerMSL::Options::enable_point_size_builtin = true
resolve_specialized_array_lengths
bool spirv_cross::CompilerMSL::Options::resolve_specialized_array_lengths = true
Referenced by spirv_cross::CompilerMSL::compile().
The documentation for this struct was generated from the following file:
MSL.h