Aurora Framework: shift.h File Reference
shift.h File Reference
Macros
#define ALWAYS_INLINE
Functions
static int32_t ALWAYS_INLINE arith_shift_left (int32_t x, int shift)
Macro Definition Documentation
ALWAYS_INLINE
#define ALWAYS_INLINE
Function Documentation
arith_shift_left()
static int32_t ALWAYS_INLINE arith_shift_left (int32_t x, int shift) inline static
Referenced by alac_decode(), alac_write_s(), APCM_inverse_quantization(), APCM_quantization(), bes2i_array(), copyPredictorTo20(), copyPredictorTo24Shift(), copyPredictorTo32(), copyPredictorTo32Shift(), d2dsc_array(), dles2i_array(), dsc2d_array(), dsc2f_array(), dsc2i_array(), dsc2s_array(), dwvw_decode_data(), dwvw_decode_load_bits(), dwvw_encode_store_bits(), dwvw_write_s(), f2dsc_array(), g721_decoder(), g721_encoder(), g723_24_decoder(), g723_40_decoder(), g72x_read_i(), gsm610_read_i(), Gsm_Preprocess(), i2dsc_array(), ima_oki_adpcm_init(), ima_read_i(), les2i_array(), msadpcm_read_i(), nms_adpcm_read_i(), pc_block(), s2dsc_array(), sc2i_array(), sds_2byte_read(), sds_write_s(), uc2i_array(), unmix16(), unmix20(), unmix24(), unmix32(), unpc_block(), and vox_read_i().