Aurora Framework: gsm610.c File Reference
gsm610.c File Reference
Classes
struct gsm610_tag
Macros
#define GSM610_BLOCKSIZE 33
#define GSM610_SAMPLES 160
Typedefs
typedef struct gsm610_tag GSM610_PRIVATE
Functions
static int gsm610_close (SF_PRIVATE *psf)
static int gsm610_decode_block (SF_PRIVATE *psf, GSM610_PRIVATE *pgsm610)
static int gsm610_encode_block (SF_PRIVATE *psf, GSM610_PRIVATE *pgsm610)
int gsm610_init (SF_PRIVATE *psf)
static int gsm610_read_block (SF_PRIVATE *psf, GSM610_PRIVATE *pgsm610, short *ptr, int len)
static sf_count_t gsm610_read_d (SF_PRIVATE *psf, double *ptr, sf_count_t len)
static sf_count_t gsm610_read_f (SF_PRIVATE *psf, float *ptr, sf_count_t len)
static sf_count_t gsm610_read_i (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static sf_count_t gsm610_read_s (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static sf_count_t gsm610_seek (SF_PRIVATE *psf, int mode, sf_count_t offset)
static sf_count_t gsm610_seek (SF_PRIVATE *psf, int UNUSED(mode), sf_count_t offset)
static int gsm610_wav_decode_block (SF_PRIVATE *psf, GSM610_PRIVATE *pgsm610)
static int gsm610_wav_encode_block (SF_PRIVATE *psf, GSM610_PRIVATE *pgsm610)
static int gsm610_write_block (SF_PRIVATE *psf, GSM610_PRIVATE *pgsm610, const short *ptr, int len)
static sf_count_t gsm610_write_d (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
static sf_count_t gsm610_write_f (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
static sf_count_t gsm610_write_i (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
static sf_count_t gsm610_write_s (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
Macro Definition Documentation
GSM610_BLOCKSIZE
#define GSM610_BLOCKSIZE 33
Referenced by gsm610_decode_block(), gsm610_encode_block(), and gsm610_init().
GSM610_SAMPLES
#define GSM610_SAMPLES 160
Referenced by gsm610_init().
Typedef Documentation
GSM610_PRIVATE
typedef struct gsm610_tag GSM610_PRIVATE
Function Documentation
gsm610_read_s()
static sf_count_t gsm610_read_s (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
References sf_private_tag::codec_data, gsm610_read_block(), and NULL.
Referenced by gsm610_init().
gsm610_read_i()
static sf_count_t gsm610_read_i (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
References arith_shift_left(), ARRAY_LEN, sf_private_tag::codec_data, gsm610_read_block(), NULL, and BUF_UNION::sbuf.
Referenced by gsm610_init().
gsm610_read_f()
static sf_count_t gsm610_read_f (SF_PRIVATE * psf, float * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, gsm610_read_block(), sf_private_tag::norm_float, NULL, and BUF_UNION::sbuf.
Referenced by gsm610_init().
gsm610_read_d()
static sf_count_t gsm610_read_d (SF_PRIVATE * psf, double * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, gsm610_read_block(), sf_private_tag::norm_double, NULL, and BUF_UNION::sbuf.
Referenced by gsm610_init().
gsm610_write_s()
static sf_count_t gsm610_write_s (SF_PRIVATE * psf, const short * ptr, sf_count_t len) static
References sf_private_tag::codec_data, gsm610_write_block(), and NULL.
Referenced by gsm610_init().
gsm610_write_i()
static sf_count_t gsm610_write_i (SF_PRIVATE * psf, const int * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, gsm610_write_block(), NULL, and BUF_UNION::sbuf.
Referenced by gsm610_init().
gsm610_write_f()
static sf_count_t gsm610_write_f (SF_PRIVATE * psf, const float * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, gsm610_write_block(), sf_private_tag::norm_float, NULL, and BUF_UNION::sbuf.
Referenced by gsm610_init().
gsm610_write_d()
static sf_count_t gsm610_write_d (SF_PRIVATE * psf, const double * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, gsm610_write_block(), sf_private_tag::norm_double, NULL, and BUF_UNION::sbuf.
Referenced by gsm610_init().
gsm610_read_block()
static int gsm610_read_block (SF_PRIVATE * psf, GSM610_PRIVATE * pgsm610, short * ptr, int len) static
References gsm610_tag::blockcount, gsm610_tag::blocks, gsm610_tag::decode_block, memcpy(), memset(), gsm610_tag::samplecount, gsm610_tag::samples, and gsm610_tag::samplesperblock.
Referenced by gsm610_read_d(), gsm610_read_f(), gsm610_read_i(), and gsm610_read_s().
gsm610_write_block()
static int gsm610_write_block (SF_PRIVATE * psf, GSM610_PRIVATE * pgsm610, const short * ptr, int len) static
References gsm610_tag::encode_block, memcpy(), gsm610_tag::samplecount, gsm610_tag::samples, and gsm610_tag::samplesperblock.
Referenced by gsm610_write_d(), gsm610_write_f(), gsm610_write_i(), and gsm610_write_s().
gsm610_decode_block()
static int gsm610_decode_block (SF_PRIVATE * psf, GSM610_PRIVATE * pgsm610) static
References gsm610_tag::block, gsm610_tag::blockcount, gsm610_tag::blocks, GSM610_BLOCKSIZE, gsm610_tag::gsm_data, gsm_decode(), memset(), psf_fread(), psf_log_printf(), gsm610_tag::samplecount, and gsm610_tag::samples.
Referenced by gsm610_init().
gsm610_encode_block()
static int gsm610_encode_block (SF_PRIVATE * psf, GSM610_PRIVATE * pgsm610) static
References gsm610_tag::block, gsm610_tag::blockcount, GSM610_BLOCKSIZE, gsm610_tag::gsm_data, gsm_encode(), memset(), psf_fwrite(), psf_log_printf(), gsm610_tag::samplecount, and gsm610_tag::samples.
Referenced by gsm610_init().
gsm610_wav_decode_block()
static int gsm610_wav_decode_block (SF_PRIVATE * psf, GSM610_PRIVATE * pgsm610) static
References gsm610_tag::block, gsm610_tag::blockcount, gsm610_tag::blocks, gsm610_tag::gsm_data, gsm_decode(), memset(), psf_fread(), psf_log_printf(), gsm610_tag::samplecount, gsm610_tag::samples, WAVLIKE_GSM610_BLOCKSIZE, and WAVLIKE_GSM610_SAMPLES.
Referenced by gsm610_init().
gsm610_wav_encode_block()
static int gsm610_wav_encode_block (SF_PRIVATE * psf, GSM610_PRIVATE * pgsm610) static
References gsm610_tag::block, gsm610_tag::blockcount, gsm610_tag::gsm_data, gsm_encode(), memset(), psf_fwrite(), psf_log_printf(), gsm610_tag::samplecount, gsm610_tag::samples, WAVLIKE_GSM610_BLOCKSIZE, and WAVLIKE_GSM610_SAMPLES.
Referenced by gsm610_init().
gsm610_seek() [1/2]
static sf_count_t gsm610_seek (SF_PRIVATE * psf, int mode, sf_count_t offset) static
Referenced by gsm610_init().
gsm610_close()
static int gsm610_close (SF_PRIVATE * psf) static
References sf_private_tag::codec_data, gsm610_tag::encode_block, sf_private_tag::file, gsm610_tag::gsm_data, gsm_destroy(), PSF_FILE::mode, NULL, gsm610_tag::samplecount, and gsm610_tag::samplesperblock.
Referenced by gsm610_init().
gsm610_init()
int gsm610_init (SF_PRIVATE * psf)
References gsm610_tag::blockcount, gsm610_tag::blocks, gsm610_tag::blocksize, sf_private_tag::codec_close, sf_private_tag::codec_data, sf_private_tag::datalength, sf_private_tag::dataoffset, gsm610_tag::decode_block, gsm610_tag::encode_block, sf_private_tag::file, sf_private_tag::filelength, GSM610_BLOCKSIZE, gsm610_close(), gsm610_decode_block(), gsm610_encode_block(), gsm610_read_d(), gsm610_read_f(), gsm610_read_i(), gsm610_read_s(), GSM610_SAMPLES, gsm610_seek(), gsm610_wav_decode_block(), gsm610_wav_encode_block(), gsm610_write_d(), gsm610_write_f(), gsm610_write_i(), gsm610_write_s(), gsm_create(), gsm610_tag::gsm_data, GSM_OPT_WAV49, gsm_option(), memset(), PSF_FILE::mode, NULL, psf_fseek(), psf_get_filelen(), psf_log_printf(), sf_private_tag::read_double, sf_private_tag::read_float, sf_private_tag::read_int, sf_private_tag::read_short, gsm610_tag::samplecount, gsm610_tag::samplesperblock, sf_private_tag::seek, sf_private_tag::sf, SF_CONTAINER, SFE_BAD_MODE_RW, SFE_INTERNAL, SFE_MALLOC_FAILED, WAVLIKE_GSM610_BLOCKSIZE, WAVLIKE_GSM610_SAMPLES, sf_private_tag::write_double, sf_private_tag::write_float, sf_private_tag::write_int, and sf_private_tag::write_short.
Referenced by aiff_open(), raw_open(), w64_open(), and wav_open().
gsm610_seek() [2/2]
static sf_count_t gsm610_seek (SF_PRIVATE * psf, int UNUSEDmode, sf_count_t offset) static
References gsm610_tag::blockcount, gsm610_tag::blocks, sf_private_tag::codec_data, sf_private_tag::dataoffset, gsm610_tag::decode_block, sf_private_tag::error, sf_private_tag::file, gsm610_tag::gsm_data, gsm_init(), GSM_OPT_WAV49, gsm_option(), PSF_FILE::mode, NULL, psf_fseek(), PSF_SEEK_ERROR, sf_private_tag::read_current, gsm610_tag::samplecount, gsm610_tag::samplesperblock, sf_private_tag::sf, SF_CONTAINER, and SFE_BAD_SEEK.