Aurora Framework: AuroraFW::GEngine::GLRenderer Class Reference
AuroraFW::GEngine::GLRenderer Class Reference
Public Member Functions
GLRenderer ()
void clear (uint) override
void setBlend (bool) override
void setDepthTesting (bool) override
void setViewport (uint, uint, uint, uint) override
Static Public Member Functions
static uint getGLRendererBuffer (uint)
static Renderer * Load ()
Constructor & Destructor Documentation
GLRenderer()
AuroraFW::GEngine::GLRenderer::GLRenderer ()
Member Function Documentation
clear()
void AuroraFW::GEngine::GLRenderer::clear (uint buf) override virtual
Implements AuroraFW::GEngine::Renderer.
References getGLRendererBuffer(), and GLCall.
setViewport()
void AuroraFW::GEngine::GLRenderer::setViewport (uint x, uint y, uint width, uint height) override virtual
Implements AuroraFW::GEngine::Renderer.
References GLCall, height, and width.
setDepthTesting()
void AuroraFW::GEngine::GLRenderer::setDepthTesting (bool val) override virtual
Implements AuroraFW::GEngine::Renderer.
References GLCall.
setBlend()
void AuroraFW::GEngine::GLRenderer::setBlend (bool val) override virtual
Implements AuroraFW::GEngine::Renderer.
References GLCall.
getGLRendererBuffer()
uint AuroraFW::GEngine::GLRenderer::getGLRendererBuffer (uint buf) static
References GL_COLOR_BUFFER_BIT, RENDERER_BUFFER_COLOR, and RENDERER_BUFFER_DEPTH.
Referenced by clear().
Load()
Renderer * AuroraFW::GEngine::Renderer::Load () static inherited
References AFW_NEW, AFW_NULLPTR, AuroraFW::GEngine::API::Context::getRenderAPI(), and OpenGL.
Referenced by AuroraFW::GEngine::GraphicsContext::GraphicsContext().
The documentation for this class was generated from the following files:
opengl/include/AuroraFW/GEngine/GL/Renderer.h
GLRenderer.cpp