Aurora Framework: alac_codec.h File Reference
alac_codec.h File Reference
Classes
struct alac_decoder_s
struct alac_encoder_s
Macros
#define ALAC_FRAME_LENGTH 4096
Typedefs
typedef struct alac_decoder_s ALAC_DECODER
typedef struct alac_encoder_s ALAC_ENCODER
Functions
int32_t alac_decode (ALAC_DECODER *, struct BitBuffer *bits, int32_t *sampleBuffer, uint32_t numSamples, uint32_t *outNumSamples)
int32_t alac_decoder_init (ALAC_DECODER *p, void *inMagicCookie, uint32_t inMagicCookieSize)
int32_t alac_encode (ALAC_ENCODER *p, uint32_t numSamples, const int32_t *theReadBuffer, unsigned char *theWriteBuffer, uint32_t *ioNumBytes)
int32_t alac_encoder_init (ALAC_ENCODER *p, uint32_t samplerate, uint32_t channels, uint32_t format_flags, uint32_t frameSize)
void alac_get_magic_cookie (ALAC_ENCODER *p, void *config, uint32_t *ioSize)
uint32_t alac_get_magic_cookie_size (uint32_t inNumChannels)
void alac_get_source_format (ALAC_ENCODER *p, const AudioFormatDescription *source, AudioFormatDescription *output)
void alac_set_fastmode (ALAC_ENCODER *p, int32_t fast)
Macro Definition Documentation
ALAC_FRAME_LENGTH
#define ALAC_FRAME_LENGTH 4096
Referenced by alac_decoder_init(), alac_encoder_init(), alac_get_desc_chunk_items(), alac_reader_init(), and alac_writer_init().
Typedef Documentation
ALAC_DECODER
typedef struct alac_decoder_s ALAC_DECODER
ALAC_ENCODER
typedef struct alac_encoder_s ALAC_ENCODER
Function Documentation
alac_decoder_init()
int32_t alac_decoder_init (ALAC_DECODER * p, void * inMagicCookie, uint32_t inMagicCookieSize)
References ALAC_FRAME_LENGTH, ALAC_noErr, ALACSpecificConfig::avgBitRate, ALACSpecificConfig::bitDepth, ALACSpecificConfig::compatibleVersion, fALAC_FrameLengthError, ALACSpecificConfig::frameLength, kALAC_BadBitWidth, kALAC_BadSpecificConfigSize, kALAC_IncompatibleVersion, kALAC_MemFullError, kALACVersion, ALACSpecificConfig::kb, ALACSpecificConfig::maxFrameBytes, ALACSpecificConfig::maxRun, ALACSpecificConfig::mb, alac_decoder_s::mConfig, alac_decoder_s::mMixBufferU, alac_decoder_s::mMixBufferV, alac_decoder_s::mNumChannels, alac_decoder_s::mPredictor, NULL, ALACSpecificConfig::numChannels, ALACSpecificConfig::pb, psf_get_be16(), psf_get_be32(), RequireAction, and ALACSpecificConfig::sampleRate.
Referenced by alac_reader_init().
alac_encoder_init()
int32_t alac_encoder_init (ALAC_ENCODER * p, uint32_t samplerate, uint32_t channels, uint32_t format_flags, uint32_t frameSize)
References ALAC_FRAME_LENGTH, ALAC_noErr, DENSHIFT_DEFAULT, init_coefs(), kALACMaxChannels, kALACMaxCoefs, kALACMaxSearches, kDefaultMixRes, kMaxSampleSize, alac_encoder_s::mBitDepth, alac_encoder_s::mCoefsU, alac_encoder_s::mCoefsV, alac_encoder_s::mFrameSize, alac_encoder_s::mLastMixRes, alac_encoder_s::mMaxOutputBytes, alac_encoder_s::mNumChannels, and alac_encoder_s::mOutputSampleRate.
Referenced by alac_writer_init().
alac_decode()
int32_t alac_decode (ALAC_DECODER * , struct BitBuffer * bits, int32_t * sampleBuffer, uint32_t numSamples, uint32_t * outNumSamples)
References alac_data_stream_element(), alac_fill_element(), ALAC_noErr, arith_shift_left(), BitBufferAdvance(), BitBufferByteAlign(), BitBufferRead(), BitBufferReadSmall(), ALACSpecificConfig::bitDepth, copyPredictorTo20(), copyPredictorTo24(), copyPredictorTo24Shift(), copyPredictorTo32(), copyPredictorTo32Shift(), BitBuffer::cur, dyn_decomp(), BitBuffer::end, ID_CCE, ID_CPE, ID_DSE, ID_END, ID_FIL, ID_LFE, ID_PCE, ID_SCE, kALAC_NumSamplesTooBig, kALAC_ParamError, kALAC_UnsupportedElement, kALAC_ZeroChannelCount, kALACDefaultFramesPerPacket, ALACSpecificConfig::kb, alac_decoder_s::mActiveElements, ALACSpecificConfig::maxRun, ALACSpecificConfig::mb, alac_decoder_s::mConfig, alac_decoder_s::mMixBufferU, alac_decoder_s::mMixBufferV, alac_decoder_s::mNumChannels, alac_decoder_s::mPredictor, alac_decoder_s::mShiftBuffer, NULL, ALACSpecificConfig::pb, RequireAction, RequireNoErr, set_ag_params(), unmix16(), unmix20(), unmix24(), unmix32(), unpc_block(), and Zero32().
Referenced by alac_decode_block().
alac_encode()
int32_t alac_encode (ALAC_ENCODER * p, uint32_t numSamples, const int32_t * theReadBuffer, unsigned char * theWriteBuffer, uint32_t * ioNumBytes)
References ALAC_noErr, BitBufferByteAlign(), BitBufferGetPosition(), BitBufferInit(), BitBufferWrite(), BitBuffer::byteSize, EncodeMono(), EncodeStereo(), EncodeStereoFast(), ID_CPE, ID_END, ID_LFE, ID_SCE, kALAC_ParamError, MAX, alac_encoder_s::mBitDepth, alac_encoder_s::mFastMode, alac_encoder_s::mMaxFrameBytes, alac_encoder_s::mMaxOutputBytes, alac_encoder_s::mNumChannels, alac_encoder_s::mTotalBytesGenerated, RequireAction, RequireNoErr, and sChannelMaps.
Referenced by alac_encode_block().
alac_set_fastmode()
void alac_set_fastmode (ALAC_ENCODER * p, int32_t fast)
References alac_encoder_s::mFastMode.
alac_get_magic_cookie_size()
uint32_t alac_get_magic_cookie_size (uint32_t inNumChannels)
References kChannelAtomSize.
Referenced by alac_writer_init().
alac_get_magic_cookie()
void alac_get_magic_cookie (ALAC_ENCODER * p, void * config, uint32_t * ioSize)
References ALACChannelLayoutTags, GetConfig(), kChannelAtomSize, ALACAudioChannelLayout::mChannelLayoutTag, memcpy(), ALACSpecificConfig::numChannels, and Swap32NtoB.
Referenced by alac_close().
alac_get_source_format()
void alac_get_source_format (ALAC_ENCODER * p, const AudioFormatDescription * source, AudioFormatDescription * output)
References kALACFormatFlagIsFloat, kALACFormatLinearPCM, alac_encoder_s::mBitDepth, and source.