Aurora Framework: hellowindow2.cpp File Reference
hellowindow2.cpp File Reference
Functions
void key_callback (GLFWwindow *window, int key, int scancode, int action, int mode)
int main ()
Variables
const GLuint HEIGHT = 600
const GLuint WIDTH = 800
Function Documentation
key_callback()
void key_callback (GLFWwindow * window, int key, int scancode, int action, int mode)
References GLFW_KEY_ESCAPE, GLFW_PRESS, and glfwSetWindowShouldClose().
Referenced by main().
main()
int main ()
References GL_COLOR_BUFFER_BIT, GLFW_CONTEXT_VERSION_MAJOR, GLFW_CONTEXT_VERSION_MINOR, GLFW_OPENGL_CORE_PROFILE, GLFW_OPENGL_PROFILE, GLFW_RESIZABLE, glfwCreateWindow(), glfwGetProcAddress(), glfwInit(), glfwMakeContextCurrent(), glfwPollEvents(), glfwSetKeyCallback(), glfwSwapBuffers(), glfwTerminate(), glfwWindowHint(), glfwWindowShouldClose(), HEIGHT, key_callback(), NULL, and WIDTH.
Variable Documentation
WIDTH
const GLuint WIDTH = 800
Referenced by main().
HEIGHT
const GLuint HEIGHT = 600
Referenced by main().