Aurora Framework: spirv_cross::CompilerMSL Class Reference
spirv_cross::CompilerMSL Class Reference
Classes
struct MemberSorter
struct OpCodePreprocessor
struct Options
Public Types
typedef Options MSLConfiguration
enum SPVFuncImpl {
SPVFuncImplNone, SPVFuncImplMod, SPVFuncImplRadians, SPVFuncImplDegrees,
SPVFuncImplFindILsb, SPVFuncImplFindSMsb, SPVFuncImplFindUMsb, SPVFuncImplArrayCopy,
SPVFuncImplInverse4x4, SPVFuncImplInverse3x3, SPVFuncImplInverse2x2, SPVFuncImplRowMajor2x3,
SPVFuncImplRowMajor2x4, SPVFuncImplRowMajor3x2, SPVFuncImplRowMajor3x4, SPVFuncImplRowMajor4x2,
SPVFuncImplRowMajor4x3
}
Public Member Functions
CompilerMSL (std::vector< uint32_t > spirv, std::vector< MSLVertexAttr > *p_vtx_attrs=nullptr, std::vector< MSLResourceBinding > *p_res_bindings=nullptr)
CompilerMSL (const uint32_t *ir, size_t word_count, MSLVertexAttr *p_vtx_attrs=nullptr, size_t vtx_attrs_count=0, MSLResourceBinding *p_res_bindings=nullptr, size_t res_bindings_count=0)
void add_header_line (const std::string &str)
bool buffer_get_hlsl_counter_buffer (uint32_t id, uint32_t &counter_id) const
bool buffer_is_hlsl_counter_buffer (uint32_t id) const
void build_combined_image_samplers ()
uint32_t build_dummy_sampler_for_combined_images ()
std::string compile () override
std::string compile (std::vector< MSLVertexAttr > *p_vtx_attrs, std::vector< MSLResourceBinding > *p_res_bindings)
void flatten_buffer_block (uint32_t id)
std::vector< BufferRange > get_active_buffer_ranges (uint32_t id) const
std::unordered_set< uint32_t > get_active_interface_variables () const
bool get_binary_offset_for_decoration (uint32_t id, spv::Decoration decoration, uint32_t &word_offset) const
virtual const std::string get_block_fallback_name (uint32_t id) const
const std::string & get_cleansed_entry_point_name (const std::string &name, spv::ExecutionModel execution_model) const
const std::vector< CombinedImageSampler > & get_combined_image_samplers () const
const Options & get_common_options () const
SPIRConstant & get_constant (uint32_t id)
const SPIRConstant & get_constant (uint32_t id) const
uint32_t get_current_id_bound () const
const std::vector< spv::Capability > & get_declared_capabilities () const
const std::vector< std::string > & get_declared_extensions () const
size_t get_declared_struct_size (const SPIRType &struct_type) const
uint32_t get_decoration (uint32_t id, spv::Decoration decoration) const
const Bitset & get_decoration_bitset (uint32_t id) const
uint64_t get_decoration_mask (uint32_t id) const
SPIREntryPoint & get_entry_point (const std::string &name)
const SPIREntryPoint & get_entry_point (const std::string &name, spv::ExecutionModel execution_model) const
SPIREntryPoint & get_entry_point (const std::string &name, spv::ExecutionModel execution_model)
std::vector< std::string > get_entry_points () const
uint32_t get_execution_mode_argument (spv::ExecutionMode mode, uint32_t index=0) const
const Bitset & get_execution_mode_bitset () const
uint64_t get_execution_mode_mask () const
spv::ExecutionModel get_execution_model () const
virtual const std::string get_fallback_member_name (uint32_t index) const
virtual const std::string get_fallback_name (uint32_t id) const
uint32_t get_member_decoration (uint32_t id, uint32_t index, spv::Decoration decoration) const
const Bitset & get_member_decoration_bitset (uint32_t id, uint32_t index) const
uint64_t get_member_decoration_mask (uint32_t id, uint32_t index) const
const std::string & get_member_name (uint32_t id, uint32_t index) const
const std::string & get_member_qualified_name (uint32_t type_id, uint32_t index) const
const Options & get_msl_options () const
const std::string & get_name (uint32_t id) const
std::string get_partial_source ()
std::string get_remapped_declared_block_name (uint32_t id) const
bool get_remapped_variable_state (uint32_t id) const
ShaderResources get_shader_resources () const
ShaderResources get_shader_resources (const std::unordered_set< uint32_t > &active_variables) const
std::vector< SpecializationConstant > get_specialization_constants () const
spv::StorageClass get_storage_class (uint32_t id) const
uint32_t get_subpass_input_remapped_components (uint32_t id) const
const SPIRType & get_type (uint32_t id) const
const SPIRType & get_type_from_variable (uint32_t id) const
uint32_t get_work_group_size_specialization_constants (SpecializationConstant &x, SpecializationConstant &y, SpecializationConstant &z) const
bool has_decoration (uint32_t id, spv::Decoration decoration) const
bool has_member_decoration (uint32_t id, uint32_t index, spv::Decoration decoration) const
void remap_pixel_local_storage (std::vector< PlsRemap > inputs, std::vector< PlsRemap > outputs)
void rename_entry_point (const std::string &old_name, const std::string &new_name, spv::ExecutionModel execution_model)
void require_extension (const std::string &ext)
void set_common_options (const Options &opts)
void set_decoration (uint32_t id, spv::Decoration decoration, uint32_t argument=0)
void set_enabled_interface_variables (std::unordered_set< uint32_t > active_variables)
void set_entry_point (const std::string &name)
void set_entry_point (const std::string &entry, spv::ExecutionModel execution_model)
void set_execution_mode (spv::ExecutionMode mode, uint32_t arg0=0, uint32_t arg1=0, uint32_t arg2=0)
void set_member_decoration (uint32_t id, uint32_t index, spv::Decoration decoration, uint32_t argument=0)
void set_member_name (uint32_t id, uint32_t index, const std::string &name)
void set_member_qualified_name (uint32_t type_id, uint32_t index, const std::string &name)
void set_msl_options (const Options &opts)
void set_name (uint32_t id, const std::string &name)
void set_remapped_variable_state (uint32_t id, bool remap_enable)
void set_subpass_input_remapped_components (uint32_t id, uint32_t components)
void set_variable_type_remap_callback (VariableTypeRemapCallback cb)
SPIRV_CROSS_DEPRECATED ("CompilerMSL::get_options() is obsolete, use get_msl_options() instead.") const Options &get_options() const
SPIRV_CROSS_DEPRECATED ("CompilerMSL::set_options() is obsolete, use set_msl_options() instead.") void set_options(Options &opts)
SPIRV_CROSS_DEPRECATED ("get_options() is obsolete, use get_common_options() instead.") const Options &get_options() const
SPIRV_CROSS_DEPRECATED ("set_options() is obsolete, use set_common_options() instead.") void set_options(Options &opts)
SPIRV_CROSS_DEPRECATED ("Please use flatten_buffer_block instead.") void flatten_interface_block(uint32_t id)
uint32_t type_struct_member_array_stride (const SPIRType &type, uint32_t index) const
uint32_t type_struct_member_matrix_stride (const SPIRType &type, uint32_t index) const
uint32_t type_struct_member_offset (const SPIRType &type, uint32_t index) const
void unset_decoration (uint32_t id, spv::Decoration decoration)
void unset_execution_mode (spv::ExecutionMode mode)
void unset_member_decoration (uint32_t id, uint32_t index, spv::Decoration decoration)
Public Attributes
SPIRV_CROSS_DEPRECATED("Please use rename_entry_point(const std::string&, const std::string&, spv::ExecutionModel) instead.") void rename_entry_point(const std const SPIREntryPoint & get_entry_point (const std::string &name) const
SPIRV_CROSS_DEPRECATED("Please use get_cleansed_entry_point_name(const std::string &, spv::ExecutionModel) instead.") const std std::vector< EntryPoint > get_entry_points_and_stages () const
Protected Member Functions
std::string access_chain (uint32_t base, const uint32_t *indices, uint32_t count, const SPIRType &target_type, bool *need_transpose=nullptr, bool *result_is_packed=nullptr)
std::string access_chain_internal (uint32_t base, const uint32_t *indices, uint32_t count, bool index_is_literal, bool chain_only=false, bool *need_transpose=nullptr, bool *result_is_packed=nullptr)
void add_convert_row_major_matrix_function (uint32_t cols, uint32_t rows)
void add_function_overload (const SPIRFunction &func)
std::string add_input_buffer_block_member (uint32_t mbr_type_id, std::string mbr_name, uint32_t mbr_locn)
uint32_t add_interface_block (spv::StorageClass storage)
void add_local_variable_name (uint32_t id)
void add_member_name (SPIRType &type, uint32_t name)
void add_pragma_line (const std::string &line)
void add_resource_name (uint32_t id)
void add_typedef_line (const std::string &line)
void add_variable (std::unordered_set< std::string > &variables, uint32_t id)
void add_variable (std::unordered_set< std::string > &variables, std::string &name)
void align_struct (SPIRType &ib_type)
void analyze_image_and_sampler_usage ()
void analyze_parameter_preservation (SPIRFunction &entry, const CFG &cfg, const std::unordered_map< uint32_t, std::unordered_set< uint32_t >> &variable_to_blocks, const std::unordered_map< uint32_t, std::unordered_set< uint32_t >> &complete_write_blocks)
void analyze_variable_scope (SPIRFunction &function)
void append_global_func_args (const SPIRFunction &func, uint32_t index, std::vector< std::string > &arglist)
bool args_will_forward (uint32_t id, const uint32_t *args, uint32_t num_args, bool pure)
std::string argument_decl (const SPIRFunction::Parameter &arg)
bool attempt_emit_loop_header (SPIRBlock &block, SPIRBlock::Method method)
void begin_scope ()
SPIRType binary_op_bitcast_helper (std::string &cast_op0, std::string &cast_op1, SPIRType::BaseType &input_type, uint32_t op0, uint32_t op1, bool skip_cast_if_equal_type)
std::string bitcast_expression (SPIRType::BaseType target_type, uint32_t arg)
std::string bitcast_expression (const SPIRType &target_type, SPIRType::BaseType expr_type, const std::string &expr)
std::string bitcast_glsl (const SPIRType &result_type, uint32_t arg)
std::string bitcast_glsl_op (const SPIRType &result_type, const SPIRType &argument_type) override
bool block_is_loop_candidate (const SPIRBlock &block, SPIRBlock::Method method) const
bool block_is_outside_flow_control_from_block (const SPIRBlock &from, const SPIRBlock &to)
bool block_is_pure (const SPIRBlock &block)
void branch (uint32_t from, uint32_t to)
void branch (uint32_t from, uint32_t cond, uint32_t true_block, uint32_t false_block)
void branch_to_continue (uint32_t from, uint32_t to)
bool buffer_is_packing_standard (const SPIRType &type, BufferPackingStandard packing, uint32_t start_offset=0, uint32_t end_offset=std::numeric_limits< uint32_t >::max())
std::string build_composite_combiner (uint32_t result_type, const uint32_t *elems, uint32_t length)
void build_implicit_builtins ()
std::string built_in_func_arg (spv::BuiltIn builtin, bool prefix_comma)
std::string builtin_qualifier (spv::BuiltIn builtin)
std::string builtin_to_glsl (spv::BuiltIn builtin, spv::StorageClass storage) override
std::string builtin_type_decl (spv::BuiltIn builtin)
bool can_use_io_location (spv::StorageClass storage)
bool check_atomic_image (uint32_t id)
bool check_explicit_lod_allowed (uint32_t lod)
void check_function_call_constraints (const uint32_t *args, uint32_t length)
Bitset combined_decoration_for_member (const SPIRType &type, uint32_t index)
std::string constant_expression (const SPIRConstant &c) override
virtual std::string constant_expression_vector (const SPIRConstant &c, uint32_t vector)
std::string constant_op_expression (const SPIRConstantOp &cop)
SPIRBlock::ContinueBlockType continue_block_type (const SPIRBlock &continue_block) const
std::string convert_double_to_string (const SPIRConstant &value, uint32_t col, uint32_t row)
std::string convert_float_to_string (const SPIRConstant &value, uint32_t col, uint32_t row)
std::string convert_half_to_string (const SPIRConstant &value, uint32_t col, uint32_t row)
std::string convert_row_major_matrix (std::string exp_str, const SPIRType &exp_type, bool is_packed) override
void declare_constant_arrays ()
std::string declare_temporary (uint32_t type, uint32_t id)
void declare_undefined_values () override
void emit_array_copy (const std::string &lhs, uint32_t rhs_id) override
void emit_atomic_func_op (uint32_t result_type, uint32_t result_id, const char *op, uint32_t mem_order_1, uint32_t mem_order_2, bool has_mem_order_2, uint32_t op0, uint32_t op1=0, bool op1_is_pointer=false, uint32_t op2=0)
void emit_barrier (uint32_t id_exe_scope, uint32_t id_mem_scope, uint32_t id_mem_sem)
void emit_binary_func_op (uint32_t result_type, uint32_t result_id, uint32_t op0, uint32_t op1, const char *op)
void emit_binary_func_op_cast (uint32_t result_type, uint32_t result_id, uint32_t op0, uint32_t op1, const char *op, SPIRType::BaseType input_type, bool skip_cast_if_equal_type)
void emit_binary_op (uint32_t result_type, uint32_t result_id, uint32_t op0, uint32_t op1, const char *op)
void emit_binary_op_cast (uint32_t result_type, uint32_t result_id, uint32_t op0, uint32_t op1, const char *op, SPIRType::BaseType input_type, bool skip_cast_if_equal_type)
void emit_block_chain (SPIRBlock &block)
void emit_block_instructions (SPIRBlock &block)
virtual void emit_buffer_block (const SPIRVariable &type)
void emit_buffer_block_flattened (const SPIRVariable &type)
void emit_buffer_block_legacy (const SPIRVariable &var)
void emit_buffer_block_native (const SPIRVariable &var)
std::string emit_continue_block (uint32_t continue_block)
void emit_custom_functions ()
void emit_declared_builtin_block (spv::StorageClass storage, spv::ExecutionModel model)
void emit_fixup () override
void emit_flattened_io_block (const SPIRVariable &var, const char *qual)
std::string emit_for_loop_initializers (const SPIRBlock &block)
void emit_function (SPIRFunction &func, const Bitset &return_flags)
void emit_function_prototype (SPIRFunction &func, const Bitset &return_flags) override
void emit_glsl_op (uint32_t result_type, uint32_t result_id, uint32_t op, const uint32_t *args, uint32_t count) override
void emit_header () override
void emit_hoisted_temporaries (std::vector< std::pair< uint32_t, uint32_t >> &temporaries)
void emit_instruction (const Instruction &instr) override
void emit_interface_block (uint32_t ib_var_id)
void emit_interface_block (const SPIRVariable &type)
void emit_mix_op (uint32_t result_type, uint32_t id, uint32_t left, uint32_t right, uint32_t lerp)
SPIRExpression & emit_op (uint32_t result_type, uint32_t result_id, const std::string &rhs, bool forward_rhs, bool suppress_usage_tracking=false)
void emit_pls ()
virtual void emit_push_constant_block (const SPIRVariable &var)
void emit_push_constant_block_glsl (const SPIRVariable &var)
void emit_push_constant_block_vulkan (const SPIRVariable &var)
void emit_quaternary_func_op (uint32_t result_type, uint32_t result_id, uint32_t op0, uint32_t op1, uint32_t op2, uint32_t op3, const char *op)
void emit_resources ()
void emit_sampled_image_op (uint32_t result_type, uint32_t result_id, uint32_t image_id, uint32_t samp_id) override
void emit_specialization_constant (const SPIRConstant &constant)
void emit_specialization_constants ()
virtual void emit_spv_amd_gcn_shader_op (uint32_t result_type, uint32_t result_id, uint32_t op, const uint32_t *args, uint32_t count)
virtual void emit_spv_amd_shader_ballot_op (uint32_t result_type, uint32_t result_id, uint32_t op, const uint32_t *args, uint32_t count)
virtual void emit_spv_amd_shader_explicit_vertex_parameter_op (uint32_t result_type, uint32_t result_id, uint32_t op, const uint32_t *args, uint32_t count)
virtual void emit_spv_amd_shader_trinary_minmax_op (uint32_t result_type, uint32_t result_id, uint32_t op, const uint32_t *args, uint32_t count)
void emit_struct (SPIRType &type)
void emit_struct_member (const SPIRType &type, uint32_t member_type_id, uint32_t index, const std::string &qualifier="", uint32_t base_offset=0) override
virtual void emit_texture_op (const Instruction &i)
void emit_trinary_func_op (uint32_t result_type, uint32_t result_id, uint32_t op0, uint32_t op1, uint32_t op2, const char *op)
void emit_unary_func_op (uint32_t result_type, uint32_t result_id, uint32_t op0, const char *op)
void emit_unary_op (uint32_t result_type, uint32_t result_id, uint32_t op0, const char *op)
virtual void emit_uniform (const SPIRVariable &var)
void emit_unrolled_binary_op (uint32_t result_type, uint32_t result_id, uint32_t op0, uint32_t op1, const char *op)
void emit_unrolled_unary_op (uint32_t result_type, uint32_t result_id, uint32_t operand, const char *op)
std::string enclose_expression (const std::string &expr)
void end_scope ()
void end_scope_decl ()
void end_scope_decl (const std::string &decl)
uint32_t ensure_correct_builtin_type (uint32_t type_id, spv::BuiltIn builtin)
std::string ensure_valid_name (std::string name, std::string pfx)
std::string entry_point_args (bool append_comma)
bool execution_is_branchless (const SPIRBlock &from, const SPIRBlock &to) const
bool execution_is_noop (const SPIRBlock &from, const SPIRBlock &to) const
bool expression_is_forwarded (uint32_t id)
bool expression_is_lvalue (uint32_t id) const
const SPIRType & expression_type (uint32_t id) const
uint32_t expression_type_id (uint32_t id) const
void extract_global_variables_from_function (uint32_t func_id, std::set< uint32_t > &added_arg_ids, std::unordered_set< uint32_t > &global_var_ids, std::unordered_set< uint32_t > &processed_func_ids)
void extract_global_variables_from_functions ()
void find_static_extensions ()
void fixup_image_load_store_access ()
const char * flags_to_precision_qualifiers_glsl (const SPIRType &type, const Bitset &flags)
std::string flattened_access_chain (uint32_t base, const uint32_t *indices, uint32_t count, const SPIRType &target_type, uint32_t offset, uint32_t matrix_stride, bool need_transpose)
std::string flattened_access_chain_matrix (uint32_t base, const uint32_t *indices, uint32_t count, const SPIRType &target_type, uint32_t offset, uint32_t matrix_stride, bool need_transpose)
std::pair< std::string, uint32_t > flattened_access_chain_offset (const SPIRType &basetype, const uint32_t *indices, uint32_t count, uint32_t offset, uint32_t word_stride, bool *need_transpose=nullptr, uint32_t *matrix_stride=nullptr)
std::string flattened_access_chain_struct (uint32_t base, const uint32_t *indices, uint32_t count, const SPIRType &target_type, uint32_t offset)
std::string flattened_access_chain_vector (uint32_t base, const uint32_t *indices, uint32_t count, const SPIRType &target_type, uint32_t offset, uint32_t matrix_stride, bool need_transpose)
void flush_all_active_variables ()
void flush_all_aliased_variables ()
void flush_all_atomic_capable_variables ()
void flush_control_dependent_expressions (uint32_t block)
void flush_dependees (SPIRVariable &var)
void flush_phi (uint32_t from, uint32_t to)
bool flush_phi_required (uint32_t from, uint32_t to)
void flush_undeclared_variables (SPIRBlock &block)
void flush_variable_declaration (uint32_t id)
bool for_loop_initializers_are_same_type (const SPIRBlock &block)
const char * format_to_glsl (spv::ImageFormat format)
std::string func_type_decl (SPIRType &type)
bool function_is_pure (const SPIRFunction &func)
template<typename T >
T & get (uint32_t id)
template<typename T >
const T & get (uint32_t id) const
std::string get_argument_address_space (const SPIRVariable &argument)
Bitset get_buffer_block_flags (const SPIRVariable &var)
bool get_common_basic_type (const SPIRType &type, SPIRType::BaseType &base_type)
size_t get_declared_struct_member_alignment (const SPIRType &struct_type, uint32_t index) const
size_t get_declared_struct_member_size (const SPIRType &struct_type, uint32_t index) const override
const SPIREntryPoint & get_entry_point () const
SPIREntryPoint & get_entry_point ()
std::string get_entry_point_name ()
uint32_t get_input_buffer_block_var_id (uint32_t msl_buffer)
const char * get_memory_order (uint32_t spv_mem_sem)
uint32_t get_metal_resource_index (SPIRVariable &var, SPIRType::BaseType basetype)
const Instruction * get_next_instruction_in_block (const Instruction &instr)
uint32_t get_ordered_member_location (uint32_t type_id, uint32_t index)
ShaderResources get_shader_resources (const std::unordered_set< uint32_t > *active_variables) const
MSLStructMemberKey get_struct_member_key (uint32_t type_id, uint32_t index)
void handle_invalid_expression (uint32_t id)
bool has_active_builtin (spv::BuiltIn builtin, spv::StorageClass storage)
bool has_extension (const std::string &ext) const
std::string image_type_glsl (const SPIRType &type, uint32_t id=0) override
uint32_t increase_bound_by (uint32_t incr_amount)
const char * index_to_swizzle (uint32_t index)
void inherit_expression_dependencies (uint32_t dst, uint32_t source)
bool instruction_to_result_type (uint32_t &result_type, uint32_t &result_id, spv::Op op, const uint32_t *args, uint32_t length)
bool interface_variable_exists_in_entry_point (uint32_t id) const
bool is_array (const SPIRType &type) const
bool is_break (uint32_t next) const
bool is_builtin_variable (const SPIRVariable &var) const
bool is_conditional (uint32_t next) const
bool is_continue (uint32_t next) const
bool is_hidden_variable (const SPIRVariable &var, bool include_builtins=false) const
bool is_immutable (uint32_t id) const
bool is_legacy () const
bool is_legacy_desktop () const
bool is_legacy_es () const
bool is_loop_break (uint32_t next) const
bool is_matrix (const SPIRType &type) const
bool is_member_builtin (const SPIRType &type, uint32_t index, spv::BuiltIn *builtin) const
bool is_member_packable (SPIRType &ib_type, uint32_t index)
bool is_non_native_row_major_matrix (uint32_t id) override
bool is_scalar (const SPIRType &type) const
bool is_single_block_loop (uint32_t next) const
bool is_vector (const SPIRType &type) const
virtual std::string layout_for_member (const SPIRType &type, uint32_t index)
std::string layout_for_variable (const SPIRVariable &variable)
std::string legacy_tex_op (const std::string &op, const SPIRType &imgtype, uint32_t lod)
std::string load_flattened_struct (SPIRVariable &var)
void localize_global_variables ()
void make_constant_null (uint32_t id, uint32_t type)
void mark_as_packable (SPIRType &type)
void mark_location_as_used_by_shader (uint32_t location, spv::StorageClass storage)
void mark_packable_structs ()
void mark_used_as_array_length (uint32_t id)
bool maybe_emit_array_assignment (uint32_t id_lhs, uint32_t id_rhs)
bool maybe_emit_input_struct_assignment (uint32_t id_lhs, uint32_t id_rhs)
template<typename T >
T * maybe_get (uint32_t id)
template<typename T >
const T * maybe_get (uint32_t id) const
SPIRVariable * maybe_get_backing_variable (uint32_t chain)
std::string member_attribute_qualifier (const SPIRType &type, uint32_t index)
bool member_is_non_native_row_major_matrix (const SPIRType &type, uint32_t index) override
bool member_is_packed_type (const SPIRType &type, uint32_t index) const
void move_member_to_input_buffer (const SPIRType &type, uint32_t index)
void move_to_input_buffer (SPIRVariable &var)
bool optimize_read_modify_write (const std::string &lhs, const std::string &rhs)
void parse ()
void parse (const Instruction &i)
std::string pls_decl (const PlsRemap &variable)
void preprocess_op_codes ()
void propagate_loop_dominators (const SPIRBlock &block)
void register_call_out_argument (uint32_t id)
void register_control_dependent_expression (uint32_t expr)
void register_global_read_dependencies (const SPIRBlock &func, uint32_t id)
void register_global_read_dependencies (const SPIRFunction &func, uint32_t id)
void register_impure_function_call ()
void register_read (uint32_t expr, uint32_t chain, bool forwarded)
void register_write (uint32_t chain)
void remap_pls_variables ()
std::string remap_swizzle (const SPIRType &result_type, uint32_t input_components, const std::string &expr)
void remap_variable_type_name (const SPIRType &type, const std::string &var_name, std::string &type_name) const
bool remove_duplicate_swizzle (std::string &op)
bool remove_unity_swizzle (uint32_t base, std::string &op)
void replace_fragment_output (SPIRVariable &var)
void replace_fragment_outputs ()
void replace_illegal_names () override
void reset ()
void resolve_specialized_array_lengths ()
std::string round_fp_tex_coords (std::string tex_coords, bool coord_is_fp)
template<typename T , typename... P>
T & set (uint32_t id, P &&... args)
bool should_forward (uint32_t id)
bool should_move_to_input_buffer (uint32_t type_id, bool is_builtin, spv::StorageClass storage)
bool skip_argument (uint32_t id) const override
template<typename... Ts>
void statement (Ts &&... ts)
template<typename T >
void statement_inner (T &&t)
template<typename T , typename... Ts>
void statement_inner (T &&t, Ts &&... ts)
template<typename... Ts>
void statement_no_indent (Ts &&... ts)
void store_flattened_struct (SPIRVariable &var, uint32_t value)
const uint32_t * stream (const Instruction &instr) const
void strip_enclosed_expression (std::string &expr)
std::string to_array_size (const SPIRType &type, uint32_t index)
uint32_t to_array_size_literal (const SPIRType &type, uint32_t index) const
std::string to_combined_image_sampler (uint32_t image_id, uint32_t samp_id)
std::string to_component_argument (uint32_t id)
std::string to_enclosed_expression (uint32_t id)
std::string to_expression (uint32_t id)
std::string to_flattened_struct_member (const SPIRVariable &var, uint32_t index)
std::string to_func_call_arg (uint32_t id) override
std::string to_function_args (uint32_t img, const SPIRType &imgtype, bool is_fetch, bool is_gather, bool is_proj, uint32_t coord, uint32_t coord_components, uint32_t dref, uint32_t grad_x, uint32_t grad_y, uint32_t lod, uint32_t coffset, uint32_t offset, uint32_t bias, uint32_t comp, uint32_t sample, bool *p_forward) override
std::string to_function_name (uint32_t img, const SPIRType &imgtype, bool is_fetch, bool is_gather, bool is_proj, bool has_array_offsets, bool has_offset, bool has_grad, bool has_dref, uint32_t lod) override
virtual std::string to_interpolation_qualifiers (const Bitset &flags)
std::string to_member_name (const SPIRType &type, uint32_t index)
std::string to_name (uint32_t id, bool allow_alias=true) const override
const char * to_pls_qualifiers_glsl (const SPIRVariable &variable)
const char * to_precision_qualifiers_glsl (uint32_t id)
std::string to_qualified_member_name (const SPIRType &type, uint32_t index)
std::string to_qualifiers_glsl (uint32_t id) override
std::string to_sampler_expression (uint32_t id)
virtual const char * to_storage_qualifiers_glsl (const SPIRVariable &var)
bool to_trivial_mix_op (const SPIRType &type, std::string &op, uint32_t left, uint32_t right, uint32_t lerp)
void track_expression_read (uint32_t id)
bool traverse_all_reachable_opcodes (const SPIRBlock &block, OpcodeHandler &handler) const
bool traverse_all_reachable_opcodes (const SPIRFunction &block, OpcodeHandler &handler) const
bool type_is_empty (const SPIRType &type)
std::string type_to_array_glsl (const SPIRType &type)
std::string type_to_glsl (const SPIRType &type, uint32_t id=0) override
std::string type_to_glsl_constructor (const SPIRType &type)
uint32_t type_to_packed_alignment (const SPIRType &type, const Bitset &flags, BufferPackingStandard packing)
uint32_t type_to_packed_array_stride (const SPIRType &type, const Bitset &flags, BufferPackingStandard packing)
uint32_t type_to_packed_base_size (const SPIRType &type, BufferPackingStandard packing)
uint32_t type_to_packed_size (const SPIRType &type, const Bitset &flags, BufferPackingStandard packing)
bool types_are_logically_equivalent (const SPIRType &a, const SPIRType &b) const
std::string unpack_expression_type (std::string expr_str, const SPIRType &type) override
void update_active_builtins ()
void update_name_cache (std::unordered_set< std::string > &cache, std::string &name)
virtual std::string variable_decl (const SPIRType &type, const std::string &name, uint32_t id=0)
std::string variable_decl (const SPIRVariable &variable)
std::string variable_decl_function_local (SPIRVariable &variable)
bool variable_storage_is_aliased (const SPIRVariable &var)
Static Protected Member Functions
static uint32_t mask_relevant_memory_semantics (uint32_t semantics)
static std::string sanitize_underscores (const std::string &str)
Protected Attributes
Bitset active_input_builtins
std::unordered_set< uint32_t > active_interface_variables
Bitset active_output_builtins
std::vector< uint32_t > aliased_variables
struct spirv_cross::CompilerGLSL::BackendVariations backend
std::unique_ptr< std::ostringstream > buffer
uint32_t builtin_frag_coord_id = 0
bool check_active_interface_variables = false
uint32_t clip_distance_count = 0
std::vector< CombinedImageSampler > combined_image_samplers
std::unordered_set< uint32_t > comparison_images
std::unordered_set< uint32_t > comparison_samplers
std::unordered_map< uint32_t, uint32_t > continue_block_to_loop_header
std::unordered_set< uint32_t > continue_blocks
uint32_t cull_distance_count = 0
SPIRBlock * current_block = nullptr
const SPIRBlock * current_continue_block = nullptr
SPIRBlock * current_emitting_block = nullptr
SPIRFunction * current_function = nullptr
std::unordered_map< uint32_t, std::string > declared_block_names
std::vector< spv::Capability > declared_capabilities
std::vector< std::string > declared_extensions
uint32_t dummy_sampler_id = 0
std::unordered_set< uint32_t > emitted_functions
uint32_t entry_point = 0
std::unordered_map< uint32_t, SPIREntryPoint > entry_points
std::unordered_map< uint32_t, uint32_t > expression_usage_counts
std::unordered_set< uint32_t > flattened_buffer_blocks
std::unordered_set< uint32_t > flattened_structs
bool force_recompile = false
std::vector< std::string > forced_extensions
std::unordered_set< uint32_t > forced_temporaries
std::unordered_set< uint32_t > forwarded_temporaries
std::unordered_map< uint32_t, std::set< uint32_t > > function_global_vars
std::unordered_map< std::string, std::unordered_set< uint64_t > > function_overloads
std::vector< uint32_t > global_struct_cache
std::vector< uint32_t > global_variables
std::vector< std::string > header_lines
std::unordered_set< uint32_t > hoisted_temporaries
std::vector< Variant > ids
uint32_t indent = 0
std::vector< Instruction > inst
std::unordered_set< uint32_t > invalid_expressions
std::unordered_set< std::string > local_variable_names
std::unordered_set< uint32_t > loop_blocks
std::unordered_set< uint32_t > loop_merge_targets
std::vector< Meta > meta
Options msl_options
std::unordered_set< uint32_t > multiselect_merge_targets
bool need_subpass_input = false
bool needs_instance_idx_arg = false
bool needs_vertex_idx_arg = false
MSLResourceBinding next_metal_resource_index
std::map< uint32_t, uint32_t > non_stage_in_input_var_ids
Options options
std::vector< PlsRemap > pls_inputs
std::vector< PlsRemap > pls_outputs
bool position_invariant = false
std::set< std::string > pragma_lines
spv::Op previous_instruction_opcode = spv::OpNop
bool processing_entry_point = false
std::string qual_pos_var_name
std::vector< std::string > * redirect_statement = nullptr
std::vector< MSLResourceBinding * > resource_bindings
std::unordered_set< std::string > resource_names
std::string sampler_name_suffix = "Smplr"
std::unordered_set< uint32_t > selection_merge_targets
struct spirv_cross::Compiler::Source source
std::vector< uint32_t > spirv
std::set< SPVFuncImpl > spv_function_implementations
uint32_t stage_in_var_id = 0
std::string stage_in_var_name = "in"
uint32_t stage_out_var_id = 0
std::string stage_out_var_name = "out"
std::string stage_uniform_var_name = "uniforms"
uint32_t stage_uniforms_var_id = 0
uint32_t statement_count
std::unordered_map< MSLStructMemberKey, uint32_t > struct_member_padding
std::set< std::string > typedef_lines
VariableTypeRemapCallback variable_remap_callback
std::unordered_map< uint32_t, MSLVertexAttr * > vtx_attrs_by_location
Member Typedef Documentation
MSLConfiguration
typedef Options spirv_cross::CompilerMSL::MSLConfiguration
Member Enumeration Documentation
SPVFuncImpl
enum spirv_cross::CompilerMSL::SPVFuncImpl
Enumerator
SPVFuncImplNone
SPVFuncImplMod
SPVFuncImplRadians
SPVFuncImplDegrees
SPVFuncImplFindILsb
SPVFuncImplFindSMsb
SPVFuncImplFindUMsb
SPVFuncImplArrayCopy
SPVFuncImplInverse4x4
SPVFuncImplInverse3x3
SPVFuncImplInverse2x2
SPVFuncImplRowMajor2x3
SPVFuncImplRowMajor2x4
SPVFuncImplRowMajor3x2
SPVFuncImplRowMajor3x4
SPVFuncImplRowMajor4x2
SPVFuncImplRowMajor4x3
Constructor & Destructor Documentation
CompilerMSL() [1/2]
spirv_cross::CompilerMSL::CompilerMSL (std::vector< uint32_t > spirv, std::vector< MSLVertexAttr > * p_vtx_attrs = nullptr, std::vector< MSLResourceBinding > * p_res_bindings = nullptr)
CompilerMSL() [2/2]
CompilerMSL::CompilerMSL (const uint32_t * ir, size_t word_count, MSLVertexAttr * p_vtx_attrs = nullptr, size_t vtx_attrs_count = 0, MSLResourceBinding * p_res_bindings = nullptr, size_t res_bindings_count = 0)
References resource_bindings, and vtx_attrs_by_location.
Member Function Documentation
SPIRV_CROSS_DEPRECATED() [1/5]
spirv_cross::CompilerMSL::SPIRV_CROSS_DEPRECATED ("CompilerMSL::get_options() is obsolete, use get_msl_options() instead.") const & inline
References msl_options.
get_msl_options()
const Options& spirv_cross::CompilerMSL::get_msl_options () const inline
References msl_options.
SPIRV_CROSS_DEPRECATED() [2/5]
spirv_cross::CompilerMSL::SPIRV_CROSS_DEPRECATED ("CompilerMSL::set_options() is obsolete, use set_msl_options() instead.") & inline
References msl_options.
set_msl_options()
void spirv_cross::CompilerMSL::set_msl_options (const Options & opts) inline
References msl_options.
compile() [1/2]
string CompilerMSL::compile () override virtual
Reimplemented from spirv_cross::CompilerGLSL.
References add_interface_block(), spirv_cross::CompilerGLSL::BackendVariations::allow_truncated_access_chain, spirv_cross::Compiler::analyze_image_and_sampler_usage(), spirv_cross::CompilerGLSL::backend, spirv_cross::CompilerGLSL::BackendVariations::basic_int_type, spirv_cross::CompilerGLSL::BackendVariations::basic_uint_type, spirv_cross::CompilerGLSL::BackendVariations::boolean_mix_support, spirv_cross::CompilerGLSL::buffer, build_implicit_builtins(), spirv_cross::CompilerGLSL::BackendVariations::can_declare_arrays_inline, spirv_cross::CompilerGLSL::BackendVariations::can_return_array, spirv_cross::CompilerGLSL::BackendVariations::discard_literal, emit_custom_functions(), spirv_cross::CompilerGLSL::emit_function(), emit_header(), emit_resources(), emit_specialization_constants(), spirv_cross::Compiler::entry_point, extract_global_variables_from_functions(), spirv_cross::CompilerGLSL::fixup_image_load_store_access(), spirv_cross::CompilerGLSL::BackendVariations::flexible_member_array_supported, spirv_cross::CompilerGLSL::BackendVariations::float_literal_suffix, spirv_cross::Compiler::force_recompile, spirv_cross::Compiler::get_active_interface_variables(), spirv_cross::CompilerGLSL::BackendVariations::half_literal_suffix, localize_global_variables(), mark_packable_structs(), msl_options, spirv_cross::CompilerGLSL::BackendVariations::native_row_major_matrix, next_metal_resource_index, non_stage_in_input_var_ids, spirv_cross::CompilerGLSL::options, preprocess_op_codes(), qual_pos_var_name, replace_illegal_names(), spirv_cross::CompilerGLSL::reset(), spirv_cross::CompilerMSL::Options::resolve_specialized_array_lengths, resolve_specialized_array_lengths(), spirv_cross::Compiler::set_enabled_interface_variables(), spirv_cross::CompilerGLSL::BackendVariations::shared_is_implied, SPIRV_CROSS_THROW, stage_in_var_id, stage_out_var_id, stage_uniforms_var_id, spv::StorageClassInput, spv::StorageClassOutput, spv::StorageClassUniformConstant, struct_member_padding, spirv_cross::CompilerGLSL::BackendVariations::swizzle_is_function, spirv_cross::CompilerGLSL::BackendVariations::uint32_t_literal_suffix, spirv_cross::Compiler::update_active_builtins(), spirv_cross::CompilerGLSL::BackendVariations::use_initializer_list, and spirv_cross::CompilerGLSL::BackendVariations::use_typed_initializer_list.
compile() [2/2]
std::string spirv_cross::CompilerMSL::compile (std::vector< MSLVertexAttr > * p_vtx_attrs, std::vector< MSLResourceBinding > * p_res_bindings)
emit_instruction()
void spirv_cross::CompilerMSL::emit_instruction (const Instruction & instr) override protected virtual
Reimplemented from spirv_cross::CompilerGLSL.
emit_glsl_op()
void spirv_cross::CompilerMSL::emit_glsl_op (uint32_t result_type, uint32_t result_id, uint32_t op, const uint32_t * args, uint32_t count) override protected virtual
Reimplemented from spirv_cross::CompilerGLSL.
emit_header()
void CompilerMSL::emit_header () override protected virtual
Reimplemented from spirv_cross::CompilerGLSL.
References spirv_cross::CompilerGLSL::header_lines, pragma_lines, spirv_cross::CompilerGLSL::statement(), and typedef_lines.
Referenced by compile().
emit_function_prototype()
void spirv_cross::CompilerMSL::emit_function_prototype (SPIRFunction & func, const Bitset & return_flags) override protected virtual
Reimplemented from spirv_cross::CompilerGLSL.
emit_sampled_image_op()
void spirv_cross::CompilerMSL::emit_sampled_image_op (uint32_t result_type, uint32_t result_id, uint32_t image_id, uint32_t samp_id) override protected virtual
Reimplemented from spirv_cross::CompilerGLSL.
emit_fixup()
void spirv_cross::CompilerMSL::emit_fixup () override protected virtual
Reimplemented from spirv_cross::CompilerGLSL.
emit_struct_member()
void spirv_cross::CompilerMSL::emit_struct_member (const SPIRType & type, uint32_t member_type_id, uint32_t index, const std::string & qualifier = "", uint32_t base_offset = 0) override protected virtual
Reimplemented from spirv_cross::CompilerGLSL.
type_to_glsl()
std::string spirv_cross::CompilerMSL::type_to_glsl (const SPIRType & type, uint32_t id = 0) override protected virtual
Reimplemented from spirv_cross::CompilerGLSL.
Referenced by emit_specialization_constants(), and unpack_expression_type().
image_type_glsl()
std::string spirv_cross::CompilerMSL::image_type_glsl (const SPIRType & type, uint32_t id = 0) override protected virtual
Reimplemented from spirv_cross::CompilerGLSL.
builtin_to_glsl()
std::string spirv_cross::CompilerMSL::builtin_to_glsl (spv::BuiltIn builtin, spv::StorageClass storage) override protected virtual
Reimplemented from spirv_cross::CompilerGLSL.
Referenced by add_input_buffer_block_member(), and emit_specialization_constants().
constant_expression()
std::string spirv_cross::CompilerMSL::constant_expression (const SPIRConstant & c) override protected virtual
Reimplemented from spirv_cross::CompilerGLSL.
Referenced by declare_constant_arrays(), and emit_specialization_constants().
get_declared_struct_member_size()
size_t spirv_cross::CompilerMSL::get_declared_struct_member_size (const SPIRType & struct_type, uint32_t index) const override protected virtual
Reimplemented from spirv_cross::Compiler.
Referenced by align_struct().
to_func_call_arg()
std::string spirv_cross::CompilerMSL::to_func_call_arg (uint32_t id) override protected virtual
Reimplemented from spirv_cross::CompilerGLSL.
to_name()
std::string spirv_cross::CompilerMSL::to_name (uint32_t id, bool allow_alias = true) const override protected virtual
Reimplemented from spirv_cross::Compiler.
Referenced by add_interface_block(), declare_constant_arrays(), declare_undefined_values(), emit_specialization_constants(), and extract_global_variables_from_function().
to_function_name()
std::string spirv_cross::CompilerMSL::to_function_name (uint32_t img, const SPIRType & imgtype, bool is_fetch, bool is_gather, bool is_proj, bool has_array_offsets, bool has_offset, bool has_grad, bool has_dref, uint32_t lod) override protected virtual
Reimplemented from spirv_cross::CompilerGLSL.
to_function_args()
std::string spirv_cross::CompilerMSL::to_function_args (uint32_t img, const SPIRType & imgtype, bool is_fetch, bool is_gather, bool is_proj, uint32_t coord, uint32_t coord_components, uint32_t dref, uint32_t grad_x, uint32_t grad_y, uint32_t lod, uint32_t coffset, uint32_t offset, uint32_t bias, uint32_t comp, uint32_t sample, bool * p_forward) override protected virtual
Reimplemented from spirv_cross::CompilerGLSL.
unpack_expression_type()
string CompilerMSL::unpack_expression_type (std::string expr_str, const SPIRType & type) override protected virtual
Reimplemented from spirv_cross::CompilerGLSL.
References spirv_cross::join(), and type_to_glsl().
bitcast_glsl_op()
std::string spirv_cross::CompilerMSL::bitcast_glsl_op (const SPIRType & result_type, const SPIRType & argument_type) override protected virtual
Reimplemented from spirv_cross::CompilerGLSL.
skip_argument()
bool spirv_cross::CompilerMSL::skip_argument (uint32_t id) const override protected virtual
Reimplemented from spirv_cross::CompilerGLSL.
to_qualifiers_glsl()
std::string spirv_cross::CompilerMSL::to_qualifiers_glsl (uint32_t id) override protected virtual
Reimplemented from spirv_cross::CompilerGLSL.
replace_illegal_names()
void spirv_cross::CompilerMSL::replace_illegal_names () override protected virtual
Reimplemented from spirv_cross::CompilerGLSL.
Referenced by compile().
declare_undefined_values()
void CompilerMSL::declare_undefined_values () override protected virtual
Reimplemented from spirv_cross::CompilerGLSL.
References spirv_cross::Compiler::get_type(), spirv_cross::Compiler::ids, spirv_cross::CompilerGLSL::statement(), to_name(), spirv_cross::TypeUndef, and spirv_cross::CompilerGLSL::variable_decl().
Referenced by emit_resources().
declare_constant_arrays()
void CompilerMSL::declare_constant_arrays () protected
References constant_expression(), spirv_cross::Compiler::get_type(), spirv_cross::Compiler::ids, setup::name, spirv_cross::CompilerGLSL::statement(), to_name(), spirv_cross::TypeConstant, and spirv_cross::CompilerGLSL::variable_decl().
Referenced by emit_resources().
is_non_native_row_major_matrix()
bool spirv_cross::CompilerMSL::is_non_native_row_major_matrix (uint32_t id) override protected virtual
Reimplemented from spirv_cross::CompilerGLSL.
member_is_non_native_row_major_matrix()
bool spirv_cross::CompilerMSL::member_is_non_native_row_major_matrix (const SPIRType & type, uint32_t index) override protected virtual
Reimplemented from spirv_cross::CompilerGLSL.
convert_row_major_matrix()
std::string spirv_cross::CompilerMSL::convert_row_major_matrix (std::string exp_str, const SPIRType & exp_type, bool is_packed) override protected virtual
Reimplemented from spirv_cross::CompilerGLSL.
preprocess_op_codes()
void CompilerMSL::preprocess_op_codes () protected
References spirv_cross::CompilerGLSL::add_header_line(), add_pragma_line(), spirv_cross::Compiler::entry_point, spv_function_implementations, spirv_cross::CompilerMSL::OpCodePreprocessor::suppress_missing_prototypes, spirv_cross::Compiler::traverse_all_reachable_opcodes(), and spirv_cross::CompilerMSL::OpCodePreprocessor::uses_atomics.
Referenced by compile().
localize_global_variables()
void CompilerMSL::localize_global_variables () protected
References spirv_cross::Compiler::entry_point, spirv_cross::Compiler::global_variables, spv::StorageClassFunction, spv::StorageClassPrivate, and spv::StorageClassWorkgroup.
Referenced by compile().
extract_global_variables_from_functions()
void CompilerMSL::extract_global_variables_from_functions () protected
References spirv_cross::Compiler::entry_point, extract_global_variables_from_function(), spirv_cross::Compiler::get_type(), spirv_cross::Compiler::ids, spv::StorageClassInput, spv::StorageClassPushConstant, spv::StorageClassStorageBuffer, spv::StorageClassUniform, spv::StorageClassUniformConstant, and spirv_cross::TypeVariable.
Referenced by compile().
resolve_specialized_array_lengths()
void CompilerMSL::resolve_specialized_array_lengths () protected
References spirv_cross::Compiler::get_type(), spirv_cross::Compiler::ids, spirv_cross::SPIRConstant::specialization, and spirv_cross::TypeConstant.
Referenced by compile().
mark_packable_structs()
void CompilerMSL::mark_packable_structs () protected
References spv::DecorationBlock, spv::DecorationBufferBlock, spirv_cross::Compiler::get_type(), spirv_cross::Compiler::has_decoration(), spirv_cross::Compiler::ids, spirv_cross::Compiler::is_hidden_variable(), mark_as_packable(), spv::StorageClassFunction, spv::StorageClassPushConstant, spv::StorageClassStorageBuffer, spv::StorageClassUniform, spv::StorageClassUniformConstant, and spirv_cross::TypeVariable.
Referenced by compile().
mark_as_packable()
void CompilerMSL::mark_as_packable (SPIRType & type) protected
References spirv_cross::SPIRType::basetype, spv::DecorationCPacked, spirv_cross::SPIRType::member_types, spirv_cross::SPIRType::parent_type, spirv_cross::IVariant::self, spirv_cross::Compiler::set_decoration(), and spirv_cross::SPIRType::Struct.
Referenced by mark_packable_structs().
extract_global_variables_from_function()
void CompilerMSL::extract_global_variables_from_function (uint32_t func_id, std::set< uint32_t > & added_arg_ids, std::unordered_set< uint32_t > & global_var_ids, std::unordered_set< uint32_t > & processed_func_ids) protected
References builtin_frag_coord_id, spv::DimSubpassData, ensure_valid_name(), spirv_cross::Compiler::entry_point, function_global_vars, spirv_cross::SPIRType::Image, spirv_cross::Compiler::increase_bound_by(), spirv_cross::Compiler::meta, spv::OpAccessChain, spv::OpFunctionCall, spv::OpInBoundsAccessChain, spv::OpLoad, spirv_cross::Compiler::set_name(), spv::StorageClassFunction, spirv_cross::Compiler::stream(), and to_name().
Referenced by extract_global_variables_from_functions().
add_interface_block()
uint32_t CompilerMSL::add_interface_block (spv::StorageClass storage) protected
References spirv_cross::Compiler::active_interface_variables, spirv_cross::SPIRType::Boolean, spv::BuiltInPosition, spirv_cross::SPIRType::Char, spv::DecorationBlock, spv::DecorationBuiltIn, spv::DecorationLocation, ensure_correct_builtin_type(), ensure_valid_name(), spirv_cross::Compiler::entry_point, spv::ExecutionModelFragment, spirv_cross::Bitset::get(), spirv_cross::Compiler::get_decoration(), spirv_cross::Compiler::get_decoration_bitset(), spirv_cross::Compiler::get_entry_point(), get_entry_point_name(), spirv_cross::Compiler::get_member_decoration(), spirv_cross::Compiler::get_type(), spirv_cross::Compiler::has_active_builtin(), spirv_cross::Compiler::has_decoration(), spirv_cross::Compiler::has_member_decoration(), spirv_cross::Compiler::ids, spirv_cross::Compiler::increase_bound_by(), spirv_cross::SPIRType::Int, spirv_cross::SPIRType::Int64, spirv_cross::Compiler::interface_variable_exists_in_entry_point(), spirv_cross::Compiler::is_builtin_variable(), spirv_cross::Compiler::is_hidden_variable(), spirv_cross::Compiler::is_member_builtin(), spirv_cross::join(), spirv_cross::CompilerMSL::MemberSorter::Location, spirv_cross::CompilerMSL::MemberSorter::LocationReverse, mark_location_as_used_by_shader(), spirv_cross::Compiler::meta, move_member_to_input_buffer(), move_to_input_buffer(), qual_pos_var_name, spirv_cross::SPIRBlock::Return, spirv_cross::Compiler::set_decoration(), spirv_cross::Compiler::set_member_decoration(), spirv_cross::Compiler::set_member_name(), spirv_cross::Compiler::set_member_qualified_name(), spirv_cross::Compiler::set_name(), should_move_to_input_buffer(), spirv_cross::CompilerMSL::MemberSorter::sort(), SPIRV_CROSS_THROW, stage_in_var_name, stage_out_var_name, stage_uniform_var_name, spv::StorageClassInput, spv::StorageClassOutput, spv::StorageClassUniformConstant, spirv_cross::SPIRType::Struct, spirv_cross::CompilerGLSL::to_expression(), to_name(), to_qualified_member_name(), spirv_cross::type_is_floating_point(), spirv_cross::TypeVariable, spirv_cross::SPIRType::UInt, and spirv_cross::SPIRType::UInt64.
Referenced by compile().
mark_location_as_used_by_shader()
void CompilerMSL::mark_location_as_used_by_shader (uint32_t location, spv::StorageClass storage) protected
References spv::ExecutionModelVertex, spirv_cross::Compiler::get_entry_point(), spv::StorageClassInput, spirv_cross::MSLVertexAttr::used_by_shader, and vtx_attrs_by_location.
Referenced by add_input_buffer_block_member(), and add_interface_block().
ensure_correct_builtin_type()
uint32_t CompilerMSL::ensure_correct_builtin_type (uint32_t type_id, spv::BuiltIn builtin) protected
References spv::BuiltInSampleMask, spirv_cross::Compiler::increase_bound_by(), spirv_cross::Compiler::is_array(), and spirv_cross::SPIRType::UInt.
Referenced by add_interface_block().
emit_custom_functions()
void CompilerMSL::emit_custom_functions () protected
References spirv_cross::CompilerGLSL::begin_scope(), spirv_cross::CompilerGLSL::end_scope(), spv_function_implementations, SPVFuncImplArrayCopy, SPVFuncImplDegrees, SPVFuncImplFindILsb, SPVFuncImplFindSMsb, SPVFuncImplFindUMsb, SPVFuncImplInverse2x2, SPVFuncImplInverse3x3, SPVFuncImplInverse4x4, SPVFuncImplMod, SPVFuncImplRadians, SPVFuncImplRowMajor2x3, SPVFuncImplRowMajor2x4, SPVFuncImplRowMajor3x2, SPVFuncImplRowMajor3x4, SPVFuncImplRowMajor4x2, SPVFuncImplRowMajor4x3, spirv_cross::CompilerGLSL::statement(), and spirv_cross::CompilerGLSL::statement_no_indent().
Referenced by compile().
emit_resources()
void CompilerMSL::emit_resources () protected
References align_struct(), declare_constant_arrays(), declare_undefined_values(), spv::DecorationBlock, spv::DecorationBufferBlock, spv::DecorationCPacked, emit_interface_block(), spirv_cross::CompilerGLSL::emit_struct(), spirv_cross::Compiler::get_type(), spirv_cross::Compiler::has_decoration(), spirv_cross::Compiler::ids, non_stage_in_input_var_ids, spirv_cross::IVariant::self, stage_in_var_id, stage_out_var_id, stage_uniforms_var_id, spv::StorageClassInput, spv::StorageClassOutput, spv::StorageClassUniformConstant, spirv_cross::SPIRType::Struct, and spirv_cross::TypeType.
Referenced by compile().
emit_specialization_constants()
void CompilerMSL::emit_specialization_constants () protected
References builtin_to_glsl(), spv::BuiltInWorkgroupSize, constant_expression(), spirv_cross::convert_to_string(), spirv_cross::Compiler::expression_type(), spirv_cross::Compiler::get_specialization_constants(), spirv_cross::Compiler::get_work_group_size_specialization_constants(), spirv_cross::CompilerGLSL::statement(), spv::StorageClassWorkgroup, spirv_cross::SPIRType::Struct, to_name(), and type_to_glsl().
Referenced by compile().
emit_interface_block() [1/2]
void spirv_cross::CompilerMSL::emit_interface_block (uint32_t ib_var_id) protected
Referenced by emit_resources().
maybe_emit_input_struct_assignment()
bool spirv_cross::CompilerMSL::maybe_emit_input_struct_assignment (uint32_t id_lhs, uint32_t id_rhs) protected
maybe_emit_array_assignment()
bool spirv_cross::CompilerMSL::maybe_emit_array_assignment (uint32_t id_lhs, uint32_t id_rhs) protected
add_convert_row_major_matrix_function()
void spirv_cross::CompilerMSL::add_convert_row_major_matrix_function (uint32_t cols, uint32_t rows) protected
func_type_decl()
std::string spirv_cross::CompilerMSL::func_type_decl (SPIRType & type) protected
entry_point_args()
std::string spirv_cross::CompilerMSL::entry_point_args (bool append_comma) protected
get_entry_point_name()
std::string spirv_cross::CompilerMSL::get_entry_point_name () protected
Referenced by add_interface_block(), and get_input_buffer_block_var_id().
to_qualified_member_name()
std::string spirv_cross::CompilerMSL::to_qualified_member_name (const SPIRType & type, uint32_t index) protected
Referenced by add_interface_block(), and move_member_to_input_buffer().
ensure_valid_name()
std::string spirv_cross::CompilerMSL::ensure_valid_name (std::string name, std::string pfx) protected
Referenced by add_interface_block(), extract_global_variables_from_function(), move_member_to_input_buffer(), and move_to_input_buffer().
to_sampler_expression()
std::string spirv_cross::CompilerMSL::to_sampler_expression (uint32_t id) protected
builtin_qualifier()
std::string spirv_cross::CompilerMSL::builtin_qualifier (spv::BuiltIn builtin) protected
builtin_type_decl()
std::string spirv_cross::CompilerMSL::builtin_type_decl (spv::BuiltIn builtin) protected
built_in_func_arg()
std::string spirv_cross::CompilerMSL::built_in_func_arg (spv::BuiltIn builtin, bool prefix_comma) protected
member_attribute_qualifier()
std::string spirv_cross::CompilerMSL::member_attribute_qualifier (const SPIRType & type, uint32_t index) protected
argument_decl()
std::string spirv_cross::CompilerMSL::argument_decl (const SPIRFunction::Parameter & arg) protected
round_fp_tex_coords()
std::string spirv_cross::CompilerMSL::round_fp_tex_coords (std::string tex_coords, bool coord_is_fp) protected
get_metal_resource_index()
uint32_t spirv_cross::CompilerMSL::get_metal_resource_index (SPIRVariable & var, SPIRType::BaseType basetype) protected
get_ordered_member_location()
uint32_t spirv_cross::CompilerMSL::get_ordered_member_location (uint32_t type_id, uint32_t index) protected
get_declared_struct_member_alignment()
size_t spirv_cross::CompilerMSL::get_declared_struct_member_alignment (const SPIRType & struct_type, uint32_t index) const protected
Referenced by align_struct().
to_component_argument()
std::string spirv_cross::CompilerMSL::to_component_argument (uint32_t id) protected
should_move_to_input_buffer()
bool CompilerMSL::should_move_to_input_buffer (uint32_t type_id, bool is_builtin, spv::StorageClass storage) protected
References spv::ExecutionModelFragment, spv::ExecutionModelVertex, spirv_cross::Compiler::get_entry_point(), spirv_cross::Compiler::is_array(), spirv_cross::Compiler::is_matrix(), SPIRV_CROSS_THROW, spv::StorageClassInput, and spv::StorageClassOutput.
Referenced by add_interface_block().
move_to_input_buffer()
void CompilerMSL::move_to_input_buffer (SPIRVariable & var) protected
References add_input_buffer_block_member(), spirv_cross::SPIRVariable::basetype, spv::DecorationLocation, ensure_valid_name(), spirv_cross::Compiler::get_decoration(), spirv_cross::Compiler::has_decoration(), spirv_cross::Compiler::meta, spirv_cross::IVariant::self, and spirv_cross::CompilerGLSL::to_expression().
Referenced by add_interface_block().
move_member_to_input_buffer()
void CompilerMSL::move_member_to_input_buffer (const SPIRType & type, uint32_t index) protected
References add_input_buffer_block_member(), spv::DecorationLocation, ensure_valid_name(), spirv_cross::Compiler::get_member_decoration(), spirv_cross::Compiler::has_member_decoration(), spirv_cross::SPIRType::member_types, spirv_cross::IVariant::self, spirv_cross::Compiler::set_member_qualified_name(), and to_qualified_member_name().
Referenced by add_interface_block().
add_input_buffer_block_member()
string CompilerMSL::add_input_buffer_block_member (uint32_t mbr_type_id, std::string mbr_name, uint32_t mbr_locn) protected
References builtin_to_glsl(), spv::BuiltInInstanceIndex, spv::BuiltInVertexIndex, spv::DecorationBinding, spv::DecorationLocation, spv::DecorationOffset, get_input_buffer_block_var_id(), spirv_cross::Compiler::get_name(), k_unknown_location, mark_location_as_used_by_shader(), spirv_cross::MSLVertexAttr::msl_buffer, spirv_cross::MSLVertexAttr::msl_offset, spirv_cross::MSLVertexAttr::msl_stride, needs_instance_idx_arg, needs_vertex_idx_arg, spirv_cross::MSLVertexAttr::per_instance, spirv_cross::Compiler::set_decoration(), spirv_cross::Compiler::set_member_decoration(), spirv_cross::Compiler::set_member_name(), spv::StorageClassInput, and vtx_attrs_by_location.
Referenced by move_member_to_input_buffer(), and move_to_input_buffer().
get_input_buffer_block_var_id()
uint32_t CompilerMSL::get_input_buffer_block_var_id (uint32_t msl_buffer) protected
References spirv_cross::convert_to_string(), spv::DecorationBlock, get_entry_point_name(), spirv_cross::Compiler::increase_bound_by(), non_stage_in_input_var_ids, spirv_cross::Compiler::set_decoration(), spirv_cross::Compiler::set_name(), stage_in_var_name, spv::StorageClassInput, and spirv_cross::SPIRType::Struct.
Referenced by add_input_buffer_block_member().
align_struct()
void CompilerMSL::align_struct (SPIRType & ib_type) protected
References spv::DecorationCPacked, spv::DecorationOffset, get_declared_struct_member_alignment(), get_declared_struct_member_size(), spirv_cross::Compiler::get_member_decoration(), get_struct_member_key(), is_member_packable(), spirv_cross::SPIRType::member_types, spirv_cross::Compiler::meta, spirv_cross::CompilerMSL::MemberSorter::Offset, spirv_cross::IVariant::self, spirv_cross::Compiler::set_member_decoration(), spirv_cross::CompilerMSL::MemberSorter::sort(), and struct_member_padding.
Referenced by emit_resources().
is_member_packable()
bool CompilerMSL::is_member_packable (SPIRType & ib_type, uint32_t index) protected
References spv::DecorationCPacked, spv::DecorationOffset, spv::DecorationRowMajor, spirv_cross::Compiler::get_member_decoration(), spirv_cross::Compiler::has_member_decoration(), spirv_cross::Compiler::is_array(), spirv_cross::Compiler::is_matrix(), afwstd::max(), spirv_cross::SPIRType::member_types, spirv_cross::IVariant::self, spirv_cross::CompilerGLSL::to_array_size_literal(), and spirv_cross::Compiler::type_struct_member_array_stride().
Referenced by align_struct().
get_struct_member_key()
MSLStructMemberKey CompilerMSL::get_struct_member_key (uint32_t type_id, uint32_t index) protected
Referenced by align_struct().
get_argument_address_space()
std::string spirv_cross::CompilerMSL::get_argument_address_space (const SPIRVariable & argument) protected
emit_atomic_func_op()
void spirv_cross::CompilerMSL::emit_atomic_func_op (uint32_t result_type, uint32_t result_id, const char * op, uint32_t mem_order_1, uint32_t mem_order_2, bool has_mem_order_2, uint32_t op0, uint32_t op1 = 0, bool op1_is_pointer = false, uint32_t op2 = 0) protected
get_memory_order()
const char* spirv_cross::CompilerMSL::get_memory_order (uint32_t spv_mem_sem) protected
add_pragma_line()
void CompilerMSL::add_pragma_line (const std::string & line) protected
References spirv_cross::Compiler::force_recompile, and pragma_lines.
Referenced by preprocess_op_codes().
add_typedef_line()
void CompilerMSL::add_typedef_line (const std::string & line) protected
References spirv_cross::Compiler::force_recompile, and typedef_lines.
emit_barrier()
void spirv_cross::CompilerMSL::emit_barrier (uint32_t id_exe_scope, uint32_t id_mem_scope, uint32_t id_mem_sem) protected
emit_array_copy()
void spirv_cross::CompilerMSL::emit_array_copy (const std::string & lhs, uint32_t rhs_id) override protected virtual
Reimplemented from spirv_cross::CompilerGLSL.
build_implicit_builtins()
void CompilerMSL::build_implicit_builtins () protected
References spirv_cross::SPIRType::basetype, builtin_frag_coord_id, spv::BuiltInFragCoord, spv::DecorationBuiltIn, spirv_cross::SPIRType::Float, spirv_cross::Compiler::get_type(), spirv_cross::Compiler::ids, spirv_cross::Compiler::increase_bound_by(), spirv_cross::Compiler::meta, spirv_cross::Compiler::need_subpass_input, spirv_cross::SPIRType::pointer, spirv_cross::Compiler::set_decoration(), spv::StorageClassInput, spirv_cross::TypeVariable, spirv_cross::SPIRType::vecsize, and spirv_cross::SPIRType::width.
Referenced by compile().
remap_pixel_local_storage()
void spirv_cross::CompilerGLSL::remap_pixel_local_storage (std::vector< PlsRemap > inputs, std::vector< PlsRemap > outputs) inline inherited
References spirv_cross::CompilerGLSL::pls_inputs, spirv_cross::CompilerGLSL::pls_outputs, and spirv_cross::CompilerGLSL::remap_pls_variables().
SPIRV_CROSS_DEPRECATED() [3/5]
spirv_cross::CompilerGLSL::SPIRV_CROSS_DEPRECATED ("get_options() is obsolete, use get_common_options() instead.") const & inline inherited
References spirv_cross::CompilerGLSL::options.
SPIRV_CROSS_DEPRECATED() [4/5]
spirv_cross::CompilerGLSL::SPIRV_CROSS_DEPRECATED ("set_options() is obsolete, use set_common_options() instead.") & inline inherited
References spirv_cross::CompilerGLSL::options.
SPIRV_CROSS_DEPRECATED() [5/5]
spirv_cross::Compiler::SPIRV_CROSS_DEPRECATED ("Please use flatten_buffer_block instead.") inherited
get_common_options()
const Options& spirv_cross::CompilerGLSL::get_common_options () const inline inherited
References spirv_cross::CompilerGLSL::options.
set_common_options()
void spirv_cross::CompilerGLSL::set_common_options (const Options & opts) inline inherited
References spirv_cross::CompilerGLSL::options.
get_partial_source()
std::string CompilerGLSL::get_partial_source () inherited
add_header_line()
void CompilerGLSL::add_header_line (const std::string & str) inherited
Referenced by preprocess_op_codes().
require_extension()
void CompilerGLSL::require_extension (const std::string & ext) inherited
flatten_buffer_block()
void CompilerGLSL::flatten_buffer_block (uint32_t id) inherited
References spv::DecorationBlock, setup::name, and SPIRV_CROSS_THROW.
reset()
void CompilerGLSL::reset () protected inherited
References spirv_cross::TypeExpression, spirv_cross::TypeFunction, and spirv_cross::TypeVariable.
Referenced by compile().
emit_function()
void CompilerGLSL::emit_function (SPIRFunction & func, const Bitset & return_flags) protected inherited
References spirv_cross::SPIRFunction::active, spirv_cross::SPIRFunction::analyzed_variable_scope, spirv_cross::SPIRType::basetype, spirv_cross::SPIRFunction::blocks, spirv_cross::SPIRFunction::entry_block, spirv_cross::SPIRFunction::local_variables, spirv_cross::SPIRType::member_types, and spv::OpFunctionCall.
Referenced by compile().
has_extension()
bool CompilerGLSL::has_extension (const std::string & ext) const protected inherited
emit_block_instructions()
void CompilerGLSL::emit_block_instructions (SPIRBlock & block) protected inherited
References spirv_cross::SPIRBlock::ops.
emit_spv_amd_shader_ballot_op()
void CompilerGLSL::emit_spv_amd_shader_ballot_op (uint32_t result_type, uint32_t result_id, uint32_t op, const uint32_t * args, uint32_t count) protected virtual inherited
emit_spv_amd_shader_explicit_vertex_parameter_op()
void CompilerGLSL::emit_spv_amd_shader_explicit_vertex_parameter_op (uint32_t result_type, uint32_t result_id, uint32_t op, const uint32_t * args, uint32_t count) protected virtual inherited
emit_spv_amd_shader_trinary_minmax_op()
void CompilerGLSL::emit_spv_amd_shader_trinary_minmax_op (uint32_t result_type, uint32_t result_id, uint32_t op, const uint32_t * args, uint32_t count) protected virtual inherited
emit_spv_amd_gcn_shader_op()
void CompilerGLSL::emit_spv_amd_gcn_shader_op (uint32_t result_type, uint32_t result_id, uint32_t op, const uint32_t * args, uint32_t count) protected virtual inherited
emit_texture_op()
void CompilerGLSL::emit_texture_op (const Instruction & i) protected virtual inherited
References spv::Dim1D, spv::Dim2D, spv::Dim3D, spv::DimBuffer, spv::DimCube, spv::ImageOperandsBiasMask, spv::ImageOperandsConstOffsetMask, spv::ImageOperandsConstOffsetsMask, spv::ImageOperandsGradMask, spv::ImageOperandsLodMask, spv::ImageOperandsOffsetMask, spv::ImageOperandsSampleMask, spirv_cross::Instruction::length, spirv_cross::Instruction::offset, spirv_cross::Instruction::op, spv::OpImageDrefGather, spv::OpImageFetch, spv::OpImageGather, spv::OpImageRead, spv::OpImageSampleDrefExplicitLod, spv::OpImageSampleDrefImplicitLod, spv::OpImageSampleImplicitLod, spv::OpImageSampleProjDrefExplicitLod, spv::OpImageSampleProjDrefImplicitLod, spv::OpImageSampleProjExplicitLod, spv::OpImageSampleProjImplicitLod, and SPIRV_CROSS_THROW.
constant_op_expression()
string CompilerGLSL::constant_op_expression (const SPIRConstantOp & cop) protected inherited
References spirv_cross::SPIRConstantOp::arguments, spirv_cross::SPIRConstantOp::basetype, BOP, glsl_opcode_is_sign_invariant(), spirv_cross::join(), spirv_cross::SPIRConstantOp::opcode, spv::OpFConvert, spv::OpIEqual, spv::OpINotEqual, spv::OpSConvert, spv::OpSelect, spv::OpUConvert, SPIRV_CROSS_THROW, and UOP.
constant_expression_vector()
string CompilerGLSL::constant_expression_vector (const SPIRConstant & c, uint32_t vector) protected virtual inherited
References spirv_cross::SPIRConstant::constant_type, spirv_cross::convert_to_string(), spirv_cross::SPIRConstant::scalar(), spirv_cross::SPIRConstant::scalar_i32(), spirv_cross::SPIRConstant::scalar_i64(), spirv_cross::SPIRConstant::scalar_u64(), spirv_cross::SPIRConstant::specialization_constant_id(), SPIRV_CROSS_THROW, spirv_cross::type_is_floating_point(), and spirv_cross::SPIRConstant::vector_size().
variable_decl() [1/2]
virtual std::string spirv_cross::CompilerGLSL::variable_decl (const SPIRType & type, const std::string & name, uint32_t id = 0) protected virtual inherited
Referenced by declare_constant_arrays(), and declare_undefined_values().
variable_decl() [2/2]
string CompilerGLSL::variable_decl (const SPIRVariable & variable) protected inherited
References spirv_cross::SPIRVariable::basetype, spirv_cross::SPIRVariable::initializer, spirv_cross::join(), spirv_cross::SPIRVariable::loop_variable, spirv_cross::IVariant::self, spirv_cross::SPIRVariable::static_expression, and spirv_cross::TypeUndef.
emit_buffer_block()
void CompilerGLSL::emit_buffer_block (const SPIRVariable & type) protected virtual inherited
References spirv_cross::IVariant::self.
emit_push_constant_block()
void CompilerGLSL::emit_push_constant_block (const SPIRVariable & var) protected virtual inherited
References spirv_cross::IVariant::self.
emit_uniform()
void CompilerGLSL::emit_uniform (const SPIRVariable & var) protected virtual inherited
References spirv_cross::SPIRVariable::basetype, ImGui::Image(), spirv_cross::IVariant::self, and SPIRV_CROSS_THROW.
statement_inner() [1/2]
template<typename T > void spirv_cross::CompilerGLSL::statement_inner (T && t) inline protected inherited
References spirv_cross::CompilerGLSL::statement_count.
Referenced by spirv_cross::CompilerGLSL::statement(), and spirv_cross::CompilerGLSL::statement_inner().
statement_inner() [2/2]
template<typename T , typename... Ts> void spirv_cross::CompilerGLSL::statement_inner (T && t, Ts &&... ts) inline protected inherited
References spirv_cross::CompilerGLSL::statement_count, and spirv_cross::CompilerGLSL::statement_inner().
statement()
template<typename... Ts> void spirv_cross::CompilerGLSL::statement (Ts &&... ts) inline protected inherited
References spirv_cross::CompilerGLSL::buffer, spirv_cross::Compiler::force_recompile, spirv_cross::CompilerGLSL::indent, spirv_cross::join(), spirv_cross::CompilerGLSL::redirect_statement, spirv_cross::CompilerGLSL::statement_count, and spirv_cross::CompilerGLSL::statement_inner().
Referenced by declare_constant_arrays(), declare_undefined_values(), emit_custom_functions(), emit_header(), emit_specialization_constants(), and spirv_cross::CompilerGLSL::statement_no_indent().
statement_no_indent()
template<typename... Ts> void spirv_cross::CompilerGLSL::statement_no_indent (Ts &&... ts) inline protected inherited
References spirv_cross::CompilerGLSL::indent, and spirv_cross::CompilerGLSL::statement().
Referenced by emit_custom_functions().
begin_scope()
void CompilerGLSL::begin_scope () protected inherited
Referenced by emit_custom_functions().
end_scope()
void CompilerGLSL::end_scope () protected inherited
References SPIRV_CROSS_THROW.
Referenced by emit_custom_functions().
end_scope_decl() [1/2]
void CompilerGLSL::end_scope_decl () protected inherited
References SPIRV_CROSS_THROW.
end_scope_decl() [2/2]
void spirv_cross::CompilerGLSL::end_scope_decl (const std::string & decl) protected inherited
type_to_array_glsl()
string CompilerGLSL::type_to_array_glsl (const SPIRType & type) protected inherited
References spirv_cross::SPIRType::array, and SPIRV_CROSS_THROW.
to_array_size()
string CompilerGLSL::to_array_size (const SPIRType & type, uint32_t index) protected inherited
References spirv_cross::SPIRType::array, spirv_cross::SPIRType::array_size_literal, spirv_cross::convert_to_string(), spv::ExecutionModelTessellationControl, spirv_cross::SPIRType::storage, and spv::StorageClassInput.
to_array_size_literal()
uint32_t CompilerGLSL::to_array_size_literal (const SPIRType & type, uint32_t index) const protected inherited
References spirv_cross::SPIRType::array, and spirv_cross::SPIRType::array_size_literal.
Referenced by is_member_packable().
variable_decl_function_local()
string CompilerGLSL::variable_decl_function_local (SPIRVariable & variable) protected inherited
References spirv_cross::SPIRVariable::storage, and spv::StorageClassFunction.
add_local_variable_name()
void CompilerGLSL::add_local_variable_name (uint32_t id) protected inherited
add_resource_name()
void CompilerGLSL::add_resource_name (uint32_t id) protected inherited
add_member_name()
void CompilerGLSL::add_member_name (SPIRType & type, uint32_t name) protected inherited
References spirv_cross::SPIRType::member_name_cache, setup::name, and spirv_cross::IVariant::self.
add_function_overload()
void CompilerGLSL::add_function_overload (const SPIRFunction & func) protected inherited
References spirv_cross::SPIRFunction::arguments, spirv_cross::Hasher::get(), spirv_cross::SPIRType::parent_type, spirv_cross::SPIRType::pointer, spirv_cross::IVariant::self, and spirv_cross::Hasher::u32().
member_is_packed_type()
bool CompilerGLSL::member_is_packed_type (const SPIRType & type, uint32_t index) const protected inherited
References spv::DecorationCPacked, and spirv_cross::IVariant::self.
emit_struct()
void CompilerGLSL::emit_struct (SPIRType & type) protected inherited
References spv::DecorationCPacked, spirv_cross::SPIRType::member_name_cache, spirv_cross::SPIRType::member_types, setup::name, spirv_cross::IVariant::self, and spirv_cross::SPIRType::type_alias.
Referenced by emit_resources().
emit_buffer_block_native()
void CompilerGLSL::emit_buffer_block_native (const SPIRVariable & var) protected inherited
References spirv_cross::SPIRVariable::basetype, spv::DecorationBufferBlock, spv::DecorationCoherent, spv::DecorationNonReadable, spv::DecorationNonWritable, spv::DecorationRestrict, spirv_cross::join(), spirv_cross::IVariant::self, spirv_cross::SPIRVariable::storage, and spv::StorageClassStorageBuffer.
emit_buffer_block_legacy()
void CompilerGLSL::emit_buffer_block_legacy (const SPIRVariable & var) protected inherited
References spirv_cross::SPIRVariable::basetype, spv::DecorationBlock, spv::DecorationBufferBlock, SPIRV_CROSS_THROW, spirv_cross::SPIRVariable::storage, and spv::StorageClassStorageBuffer.
emit_buffer_block_flattened()
void CompilerGLSL::emit_buffer_block_flattened (const SPIRVariable & type) protected inherited
References spirv_cross::SPIRType::basetype, spirv_cross::SPIRVariable::basetype, SPIRV_CROSS_THROW, and spirv_cross::SPIRType::vecsize.
emit_declared_builtin_block()
void CompilerGLSL::emit_declared_builtin_block (spv::StorageClass storage, spv::ExecutionModel model) protected inherited
References spv::BuiltInClipDistance, spv::BuiltInCullDistance, spv::BuiltInPointSize, spv::BuiltInPosition, spv::DecorationBlock, spirv_cross::Bitset::empty(), spv::ExecutionModelTessellationControl, spv::ExecutionModelTessellationEvaluation, spirv_cross::Bitset::get(), spirv_cross::Bitset::get_lower(), spirv_cross::join(), spirv_cross::IVariant::self, spirv_cross::Bitset::set(), SPIRV_CROSS_THROW, spv::StorageClassInput, spv::StorageClassOutput, and spirv_cross::TypeVariable.
emit_push_constant_block_vulkan()
void CompilerGLSL::emit_push_constant_block_vulkan (const SPIRVariable & var) protected inherited
emit_push_constant_block_glsl()
void CompilerGLSL::emit_push_constant_block_glsl (const SPIRVariable & var) protected inherited
References spirv_cross::SPIRVariable::basetype, spv::DecorationBinding, spv::DecorationBlock, spv::DecorationDescriptorSet, spirv_cross::IVariant::self, and SPIRV_CROSS_THROW.
emit_interface_block() [2/2]
void CompilerGLSL::emit_interface_block (const SPIRVariable & type) protected inherited
References spirv_cross::SPIRVariable::basetype, spv::DecorationBlock, spirv_cross::join(), and spirv_cross::IVariant::self.
emit_flattened_io_block()
void CompilerGLSL::emit_flattened_io_block (const SPIRVariable & var, const char * qual) protected inherited
References spirv_cross::SPIRVariable::basetype, spv::DecorationBlock, spirv_cross::join(), spirv_cross::IVariant::self, and SPIRV_CROSS_THROW.
emit_block_chain()
void CompilerGLSL::emit_block_chain (SPIRBlock & block) protected inherited
References spirv_cross::SPIRType::array, spirv_cross::SPIRType::basetype, spirv_cross::SPIRBlock::cases, spirv_cross::SPIRBlock::condition, spirv_cross::SPIRBlock::continue_block, spirv_cross::convert_to_string(), spirv_cross::SPIRBlock::declare_temporary, spirv_cross::SPIRBlock::default_block, spirv_cross::SPIRBlock::false_block, spirv_cross::join(), spirv_cross::SPIRBlock::loop_dominator, spirv_cross::SPIRBlock::loop_variables, spirv_cross::SPIRBlock::merge, spirv_cross::SPIRBlock::merge_block, spirv_cross::SPIRBlock::next_block, spirv_cross::SPIRBlock::potential_declare_temporary, spirv_cross::SPIRBlock::return_value, spirv_cross::IVariant::self, SPIRV_CROSS_THROW, spirv_cross::SPIRBlock::terminator, spirv_cross::SPIRBlock::true_block, and spirv_cross::TypeUndef.
emit_hoisted_temporaries()
void CompilerGLSL::emit_hoisted_temporaries (std::vector< std::pair< uint32_t, uint32_t >> & temporaries) protected inherited
References a.
emit_specialization_constant()
void CompilerGLSL::emit_specialization_constant (const SPIRConstant & constant) protected inherited
References spirv_cross::SPIRConstant::constant_type, spv::DecorationSpecId, spirv_cross::SpecializationConstant::id, setup::name, and spirv_cross::IVariant::self.
emit_continue_block()
string CompilerGLSL::emit_continue_block (uint32_t continue_block) protected inherited
References spirv_cross::merge().
attempt_emit_loop_header()
bool CompilerGLSL::attempt_emit_loop_header (SPIRBlock & block, SPIRBlock::Method method) protected inherited
References spirv_cross::SPIRBlock::condition, spirv_cross::SPIRBlock::continue_block, spirv_cross::SPIRBlock::disable_block_optimization, spirv_cross::SPIRBlock::next_block, and SPIRV_CROSS_THROW.
propagate_loop_dominators()
void CompilerGLSL::propagate_loop_dominators (const SPIRBlock & block) protected inherited
References spirv_cross::SPIRBlock::cases, spirv_cross::SPIRBlock::continue_block, spirv_cross::SPIRBlock::false_block, spirv_cross::SPIRBlock::loop_dominator, spirv_cross::SPIRBlock::merge, spirv_cross::SPIRBlock::merge_block, spirv_cross::SPIRBlock::next_block, spirv_cross::IVariant::self, and spirv_cross::SPIRBlock::true_block.
branch() [1/2]
void CompilerGLSL::branch (uint32_t from, uint32_t to) protected inherited
branch() [2/2]
void CompilerGLSL::branch (uint32_t from, uint32_t cond, uint32_t true_block, uint32_t false_block) protected inherited
branch_to_continue()
void CompilerGLSL::branch_to_continue (uint32_t from, uint32_t to) protected inherited
flush_phi()
void CompilerGLSL::flush_phi (uint32_t from, uint32_t to) protected inherited
flush_phi_required()
bool CompilerGLSL::flush_phi_required (uint32_t from, uint32_t to) protected inherited
flush_variable_declaration()
void CompilerGLSL::flush_variable_declaration (uint32_t id) protected inherited
flush_undeclared_variables()
void CompilerGLSL::flush_undeclared_variables (SPIRBlock & block) protected inherited
References spirv_cross::SPIRBlock::dominated_variables.
should_forward()
bool CompilerGLSL::should_forward (uint32_t id) protected inherited
emit_mix_op()
void CompilerGLSL::emit_mix_op (uint32_t result_type, uint32_t id, uint32_t left, uint32_t right, uint32_t lerp) protected inherited
References spirv_cross::join().
to_trivial_mix_op()
bool CompilerGLSL::to_trivial_mix_op (const SPIRType & type, std::string & op, uint32_t left, uint32_t right, uint32_t lerp) protected inherited
References spirv_cross::SPIRType::basetype.
emit_quaternary_func_op()
void CompilerGLSL::emit_quaternary_func_op (uint32_t result_type, uint32_t result_id, uint32_t op0, uint32_t op1, uint32_t op2, uint32_t op3, const char * op) protected inherited
References spirv_cross::join().
emit_trinary_func_op()
void CompilerGLSL::emit_trinary_func_op (uint32_t result_type, uint32_t result_id, uint32_t op0, uint32_t op1, uint32_t op2, const char * op) protected inherited
References spirv_cross::join().
emit_binary_func_op()
void CompilerGLSL::emit_binary_func_op (uint32_t result_type, uint32_t result_id, uint32_t op0, uint32_t op1, const char * op) protected inherited
References spirv_cross::join().
emit_binary_func_op_cast()
void CompilerGLSL::emit_binary_func_op_cast (uint32_t result_type, uint32_t result_id, uint32_t op0, uint32_t op1, const char * op, SPIRType::BaseType input_type, bool skip_cast_if_equal_type) protected inherited
References spirv_cross::join().
emit_unary_func_op()
void CompilerGLSL::emit_unary_func_op (uint32_t result_type, uint32_t result_id, uint32_t op0, const char * op) protected inherited
References spirv_cross::join().
emit_unrolled_unary_op()
void CompilerGLSL::emit_unrolled_unary_op (uint32_t result_type, uint32_t result_id, uint32_t operand, const char * op) protected inherited
emit_binary_op()
void CompilerGLSL::emit_binary_op (uint32_t result_type, uint32_t result_id, uint32_t op0, uint32_t op1, const char * op) protected inherited
References spirv_cross::join().
emit_unrolled_binary_op()
void CompilerGLSL::emit_unrolled_binary_op (uint32_t result_type, uint32_t result_id, uint32_t op0, uint32_t op1, const char * op) protected inherited
emit_binary_op_cast()
void CompilerGLSL::emit_binary_op_cast (uint32_t result_type, uint32_t result_id, uint32_t op0, uint32_t op1, const char * op, SPIRType::BaseType input_type, bool skip_cast_if_equal_type) protected inherited
References spirv_cross::join().
binary_op_bitcast_helper()
SPIRType CompilerGLSL::binary_op_bitcast_helper (std::string & cast_op0, std::string & cast_op1, SPIRType::BaseType & input_type, uint32_t op0, uint32_t op1, bool skip_cast_if_equal_type) protected inherited
References spirv_cross::SPIRType::basetype, spirv_cross::SPIRType::columns, spirv_cross::SPIRType::vecsize, and spirv_cross::SPIRType::width.
emit_unary_op()
void CompilerGLSL::emit_unary_op (uint32_t result_type, uint32_t result_id, uint32_t op0, const char * op) protected inherited
References spirv_cross::join().
expression_is_forwarded()
bool CompilerGLSL::expression_is_forwarded (uint32_t id) protected inherited
emit_op()
SPIRExpression & CompilerGLSL::emit_op (uint32_t result_type, uint32_t result_id, const std::string & rhs, bool forward_rhs, bool suppress_usage_tracking = false) protected inherited
access_chain_internal()
string CompilerGLSL::access_chain_internal (uint32_t base, const uint32_t * indices, uint32_t count, bool index_is_literal, bool chain_only = false, bool * need_transpose = nullptr, bool * result_is_packed = nullptr) protected inherited
References spv::BuiltInPointSize, spv::BuiltInPosition, spirv_cross::convert_to_string(), spv::DecorationBlock, spv::DecorationCPacked, spirv_cross::join(), SPIRV_CROSS_THROW, spv::StorageClassInput, spv::StorageClassOutput, and spirv_cross::TypeConstant.
access_chain()
string CompilerGLSL::access_chain (uint32_t base, const uint32_t * indices, uint32_t count, const SPIRType & target_type, bool * need_transpose = nullptr, bool * result_is_packed = nullptr) protected inherited
References spirv_cross::SPIRType::columns, and spirv_cross::join().
flattened_access_chain()
std::string CompilerGLSL::flattened_access_chain (uint32_t base, const uint32_t * indices, uint32_t count, const SPIRType & target_type, uint32_t offset, uint32_t matrix_stride, bool need_transpose) protected inherited
References spirv_cross::SPIRType::array, spirv_cross::SPIRType::basetype, spirv_cross::SPIRType::columns, and SPIRV_CROSS_THROW.
flattened_access_chain_struct()
std::string CompilerGLSL::flattened_access_chain_struct (uint32_t base, const uint32_t * indices, uint32_t count, const SPIRType & target_type, uint32_t offset) protected inherited
References spirv_cross::SPIRType::columns, spv::DecorationRowMajor, and spirv_cross::SPIRType::member_types.
flattened_access_chain_matrix()
std::string CompilerGLSL::flattened_access_chain_matrix (uint32_t base, const uint32_t * indices, uint32_t count, const SPIRType & target_type, uint32_t offset, uint32_t matrix_stride, bool need_transpose) protected inherited
References spirv_cross::SPIRType::columns, and spirv_cross::SPIRType::vecsize.
flattened_access_chain_vector()
std::string CompilerGLSL::flattened_access_chain_vector (uint32_t base, const uint32_t * indices, uint32_t count, const SPIRType & target_type, uint32_t offset, uint32_t matrix_stride, bool need_transpose) protected inherited
References spirv_cross::convert_to_string(), spirv_cross::SPIRType::vecsize, vector_swizzle(), and spirv_cross::SPIRType::width.
flattened_access_chain_offset()
std::pair< std::string, uint32_t > CompilerGLSL::flattened_access_chain_offset (const SPIRType & basetype, const uint32_t * indices, uint32_t count, uint32_t offset, uint32_t word_stride, bool * need_transpose = nullptr, uint32_t * matrix_stride = nullptr) protected inherited
References spirv_cross::convert_to_string(), spv::DecorationArrayStride, spv::DecorationRowMajor, and SPIRV_CROSS_THROW.
index_to_swizzle()
const char * CompilerGLSL::index_to_swizzle (uint32_t index) protected inherited
References SPIRV_CROSS_THROW.
remap_swizzle()
string CompilerGLSL::remap_swizzle (const SPIRType & result_type, uint32_t input_components, const std::string & expr) protected inherited
References spirv_cross::join(), min(), and spirv_cross::SPIRType::vecsize.
declare_temporary()
string CompilerGLSL::declare_temporary (uint32_t type, uint32_t id) protected inherited
References spirv_cross::join().
append_global_func_args()
void CompilerGLSL::append_global_func_args (const SPIRFunction & func, uint32_t index, std::vector< std::string > & arglist) protected inherited
References spirv_cross::SPIRFunction::arguments.
to_expression()
string CompilerGLSL::to_expression (uint32_t id) protected inherited
References spv::DecorationCPacked, SPIRV_CROSS_THROW, spv::StorageClassGeneric, spirv_cross::TypeAccessChain, spirv_cross::TypeCombinedImageSampler, spirv_cross::TypeConstant, spirv_cross::TypeConstantOp, spirv_cross::TypeExpression, and spirv_cross::TypeVariable.
Referenced by add_interface_block(), and move_to_input_buffer().
to_enclosed_expression()
string CompilerGLSL::to_enclosed_expression (uint32_t id) protected inherited
enclose_expression()
string CompilerGLSL::enclose_expression (const std::string & expr) protected inherited
References spirv_cross::join().
strip_enclosed_expression()
void CompilerGLSL::strip_enclosed_expression (std::string & expr) protected inherited
to_member_name()
string CompilerGLSL::to_member_name (const SPIRType & type, uint32_t index) protected inherited
References spirv_cross::join(), and spirv_cross::IVariant::self.
type_to_glsl_constructor()
string CompilerGLSL::type_to_glsl_constructor (const SPIRType & type) protected inherited
References spirv_cross::SPIRType::array, and SPIRV_CROSS_THROW.
to_precision_qualifiers_glsl()
const char * CompilerGLSL::to_precision_qualifiers_glsl (uint32_t id) protected inherited
to_storage_qualifiers_glsl()
const char * CompilerGLSL::to_storage_qualifiers_glsl (const SPIRVariable & var) protected virtual inherited
References spv::ExecutionModelFragment, spv::ExecutionModelVertex, spirv_cross::SPIRVariable::storage, spv::StorageClassInput, spv::StorageClassOutput, spv::StorageClassPushConstant, spv::StorageClassUniform, and spv::StorageClassUniformConstant.
flags_to_precision_qualifiers_glsl()
const char * CompilerGLSL::flags_to_precision_qualifiers_glsl (const SPIRType & type, const Bitset & flags) protected inherited
References spirv_cross::SPIRType::basetype, spv::DecorationRelaxedPrecision, spv::ExecutionModelFragment, spirv_cross::Bitset::get(), and ImGui::Image().
format_to_glsl()
const char * CompilerGLSL::format_to_glsl (spv::ImageFormat format) protected inherited
References spv::ImageFormatR11fG11fB10f, spv::ImageFormatR16, spv::ImageFormatR16f, spv::ImageFormatR16i, spv::ImageFormatR16Snorm, spv::ImageFormatR16ui, spv::ImageFormatR32f, spv::ImageFormatR32i, spv::ImageFormatR32ui, spv::ImageFormatR8, spv::ImageFormatR8i, spv::ImageFormatR8Snorm, spv::ImageFormatR8ui, spv::ImageFormatRg16, spv::ImageFormatRg16f, spv::ImageFormatRg16i, spv::ImageFormatRg16Snorm, spv::ImageFormatRg16ui, spv::ImageFormatRg32f, spv::ImageFormatRg32i, spv::ImageFormatRg32ui, spv::ImageFormatRg8, spv::ImageFormatRg8i, spv::ImageFormatRg8Snorm, spv::ImageFormatRg8ui, spv::ImageFormatRgb10A2, spv::ImageFormatRgb10a2ui, spv::ImageFormatRgba16, spv::ImageFormatRgba16f, spv::ImageFormatRgba16i, spv::ImageFormatRgba16Snorm, spv::ImageFormatRgba16ui, spv::ImageFormatRgba32f, spv::ImageFormatRgba32i, spv::ImageFormatRgba32ui, spv::ImageFormatRgba8, spv::ImageFormatRgba8i, spv::ImageFormatRgba8Snorm, spv::ImageFormatRgba8ui, spv::ImageFormatUnknown, and SPIRV_CROSS_THROW.
layout_for_member()
string CompilerGLSL::layout_for_member (const SPIRType & type, uint32_t index) protected virtual inherited
References spv::DecorationBlock, spv::DecorationBufferBlock, spv::DecorationCPacked, spv::DecorationLocation, spv::DecorationOffset, spv::DecorationRowMajor, spirv_cross::Bitset::get(), spirv_cross::join(), spirv_cross::merge(), spirv_cross::IVariant::self, and spirv_cross::SPIRType::storage.
to_interpolation_qualifiers()
string CompilerGLSL::to_interpolation_qualifiers (const Bitset & flags) protected virtual inherited
References spv::DecorationCentroid, spv::DecorationExplicitInterpAMD, spv::DecorationFlat, spv::DecorationInvariant, spv::DecorationNoPerspective, spv::DecorationPatch, spv::DecorationSample, and spirv_cross::Bitset::get().
combined_decoration_for_member()
Bitset CompilerGLSL::combined_decoration_for_member (const SPIRType & type, uint32_t index) protected inherited
References spirv_cross::SPIRType::member_types, spirv_cross::Bitset::merge_or(), and spirv_cross::IVariant::self.
layout_for_variable()
string CompilerGLSL::layout_for_variable (const SPIRVariable & variable) protected inherited
References spirv_cross::SPIRVariable::basetype, spirv_cross::BufferPackingStd140, spirv_cross::BufferPackingStd140EnhancedLayout, spirv_cross::BufferPackingStd430, spirv_cross::BufferPackingStd430EnhancedLayout, spv::DecorationBinding, spv::DecorationBlock, spv::DecorationBufferBlock, spv::DecorationColMajor, spv::DecorationCPacked, spv::DecorationDescriptorSet, spv::DecorationInputAttachmentIndex, spv::DecorationLocation, spv::DecorationOffset, spv::DecorationRowMajor, spirv_cross::Bitset::get(), ImGui::Image(), spirv_cross::join(), spirv_cross::merge(), spirv_cross::Bitset::merge_or(), spirv_cross::IVariant::self, SPIRV_CROSS_THROW, spirv_cross::SPIRVariable::storage, spv::StorageClassPushConstant, spv::StorageClassStorageBuffer, and spv::StorageClassUniform.
to_combined_image_sampler()
string CompilerGLSL::to_combined_image_sampler (uint32_t image_id, uint32_t samp_id) protected inherited
References spirv_cross::SPIRFunction::CombinedImageSamplerParameter::global_image, spirv_cross::SPIRFunction::CombinedImageSamplerParameter::global_sampler, spirv_cross::SPIRFunction::Parameter::id, spirv_cross::CombinedImageSampler::image_id, spirv_cross::SPIRFunction::CombinedImageSamplerParameter::image_id, spirv_cross::CombinedImageSampler::sampler_id, spirv_cross::SPIRFunction::CombinedImageSamplerParameter::sampler_id, and SPIRV_CROSS_THROW.
buffer_is_packing_standard()
bool CompilerGLSL::buffer_is_packing_standard (const SPIRType & type, BufferPackingStandard packing, uint32_t start_offset = 0, uint32_t end_offset = std::numeric_limits<uint32_t>::max()) protected inherited
References afwstd::max(), spirv_cross::SPIRType::member_types, packing_has_flexible_offset(), packing_is_hlsl(), packing_to_substruct_packing(), and spirv_cross::IVariant::self.
type_to_packed_base_size()
uint32_t CompilerGLSL::type_to_packed_base_size (const SPIRType & type, BufferPackingStandard packing) protected inherited
References spirv_cross::SPIRType::basetype, and SPIRV_CROSS_THROW.
type_to_packed_alignment()
uint32_t CompilerGLSL::type_to_packed_alignment (const SPIRType & type, const Bitset & flags, BufferPackingStandard packing) protected inherited
References spirv_cross::SPIRType::array, spirv_cross::SPIRType::basetype, spirv_cross::SPIRType::columns, spv::DecorationColMajor, spv::DecorationRowMajor, spirv_cross::Bitset::get(), afwstd::max(), spirv_cross::SPIRType::member_types, packing_is_hlsl(), packing_is_vec4_padded(), spirv_cross::SPIRType::parent_type, spirv_cross::IVariant::self, SPIRV_CROSS_THROW, and spirv_cross::SPIRType::vecsize.
type_to_packed_array_stride()
uint32_t CompilerGLSL::type_to_packed_array_stride (const SPIRType & type, const Bitset & flags, BufferPackingStandard packing) protected inherited
References spirv_cross::SPIRType::parent_type.
type_to_packed_size()
uint32_t CompilerGLSL::type_to_packed_size (const SPIRType & type, const Bitset & flags, BufferPackingStandard packing) protected inherited
References spirv_cross::SPIRType::array, spirv_cross::SPIRType::basetype, spirv_cross::SPIRType::columns, spv::DecorationColMajor, spv::DecorationRowMajor, spirv_cross::Bitset::get(), afwstd::max(), spirv_cross::SPIRType::member_types, packing_is_vec4_padded(), spirv_cross::IVariant::self, and spirv_cross::SPIRType::vecsize.
bitcast_glsl()
string CompilerGLSL::bitcast_glsl (const SPIRType & result_type, uint32_t arg) protected inherited
References spirv_cross::join().
bitcast_expression() [1/2]
std::string CompilerGLSL::bitcast_expression (SPIRType::BaseType target_type, uint32_t arg) protected inherited
References spirv_cross::join().
bitcast_expression() [2/2]
std::string CompilerGLSL::bitcast_expression (const SPIRType & target_type, SPIRType::BaseType expr_type, const std::string & expr) protected inherited
References spirv_cross::SPIRType::basetype, and spirv_cross::join().
build_composite_combiner()
string CompilerGLSL::build_composite_combiner (uint32_t result_type, const uint32_t * elems, uint32_t length) protected inherited
remove_duplicate_swizzle()
bool CompilerGLSL::remove_duplicate_swizzle (std::string & op) protected inherited
remove_unity_swizzle()
bool CompilerGLSL::remove_unity_swizzle (uint32_t base, std::string & op) protected inherited
check_atomic_image()
bool CompilerGLSL::check_atomic_image (uint32_t id) protected inherited
References spv::DecorationNonReadable, spv::DecorationNonWritable, spirv_cross::SPIRType::storage, and spv::StorageClassImage.
replace_fragment_output()
void CompilerGLSL::replace_fragment_output (SPIRVariable & var) protected inherited
References spirv_cross::SPIRVariable::basetype, spirv_cross::SPIRVariable::compat_builtin, spv::DecorationLocation, spirv_cross::join(), spirv_cross::IVariant::self, and SPIRV_CROSS_THROW.
replace_fragment_outputs()
void CompilerGLSL::replace_fragment_outputs () protected inherited
References spirv_cross::SPIRVariable::storage, spv::StorageClassOutput, and spirv_cross::TypeVariable.
check_explicit_lod_allowed()
bool CompilerGLSL::check_explicit_lod_allowed (uint32_t lod) protected inherited
References spv::ExecutionModelFragment, and SPIRV_CROSS_THROW.
legacy_tex_op()
string CompilerGLSL::legacy_tex_op (const std::string & op, const SPIRType & imgtype, uint32_t lod) protected inherited
References spirv_cross::SPIRType::ImageType::arrayed, spirv_cross::SPIRType::ImageType::dim, spv::Dim1D, spv::Dim2D, spv::Dim3D, spv::DimBuffer, spv::DimCube, spv::DimSubpassData, spirv_cross::SPIRType::image, spirv_cross::join(), and SPIRV_CROSS_THROW.
load_flattened_struct()
string CompilerGLSL::load_flattened_struct (SPIRVariable & var) protected inherited
References spirv_cross::SPIRVariable::basetype.
to_flattened_struct_member()
string CompilerGLSL::to_flattened_struct_member (const SPIRVariable & var, uint32_t index) protected inherited
References spirv_cross::SPIRVariable::basetype, spirv_cross::join(), and spirv_cross::IVariant::self.
store_flattened_struct()
void CompilerGLSL::store_flattened_struct (SPIRVariable & var, uint32_t value) protected inherited
References spirv_cross::SPIRVariable::basetype, spirv_cross::join(), spirv_cross::IVariant::self, and value.
track_expression_read()
void CompilerGLSL::track_expression_read (uint32_t id) protected inherited
is_legacy()
bool spirv_cross::CompilerGLSL::is_legacy () const inline protected inherited
References spirv_cross::CompilerGLSL::Options::es, spirv_cross::CompilerGLSL::options, and spirv_cross::CompilerGLSL::Options::version.
is_legacy_es()
bool spirv_cross::CompilerGLSL::is_legacy_es () const inline protected inherited
References spirv_cross::CompilerGLSL::Options::es, spirv_cross::CompilerGLSL::options, and spirv_cross::CompilerGLSL::Options::version.
is_legacy_desktop()
bool spirv_cross::CompilerGLSL::is_legacy_desktop () const inline protected inherited
References spirv_cross::CompilerGLSL::Options::es, spirv_cross::CompilerGLSL::options, and spirv_cross::CompilerGLSL::Options::version.
args_will_forward()
bool CompilerGLSL::args_will_forward (uint32_t id, const uint32_t * args, uint32_t num_args, bool pure) protected inherited
register_call_out_argument()
void CompilerGLSL::register_call_out_argument (uint32_t id) protected inherited
register_impure_function_call()
void CompilerGLSL::register_impure_function_call () protected inherited
register_control_dependent_expression()
void CompilerGLSL::register_control_dependent_expression (uint32_t expr) protected inherited
pls_decl()
string CompilerGLSL::pls_decl (const PlsRemap & variable) protected inherited
References spirv_cross::PlsRemap::format, spirv_cross::PlsRemap::id, spirv_cross::join(), pls_format_to_basetype(), pls_format_to_components(), to_pls_layout(), and spirv_cross::SPIRType::vecsize.
to_pls_qualifiers_glsl()
const char * CompilerGLSL::to_pls_qualifiers_glsl (const SPIRVariable & variable) protected inherited
References spv::DecorationRelaxedPrecision, and spirv_cross::IVariant::self.
emit_pls()
void CompilerGLSL::emit_pls () protected inherited
References spv::ExecutionModelFragment, and SPIRV_CROSS_THROW.
remap_pls_variables()
void CompilerGLSL::remap_pls_variables () protected inherited
References spv::DimSubpassData, SPIRV_CROSS_THROW, spv::StorageClassInput, spv::StorageClassOutput, and spv::StorageClassUniformConstant.
Referenced by spirv_cross::CompilerGLSL::remap_pixel_local_storage().
add_variable() [1/2]
void spirv_cross::CompilerGLSL::add_variable (std::unordered_set< std::string > & variables, uint32_t id) protected inherited
add_variable() [2/2]
void spirv_cross::CompilerGLSL::add_variable (std::unordered_set< std::string > & variables, std::string & name) protected inherited
check_function_call_constraints()
void CompilerGLSL::check_function_call_constraints (const uint32_t * args, uint32_t length) protected inherited
References spirv_cross::SPIRType::basetype, spirv_cross::SPIRType::ImageType::dim, spv::DimSubpassData, ImGui::Image(), spirv_cross::SPIRType::image, and SPIRV_CROSS_THROW.
handle_invalid_expression()
void CompilerGLSL::handle_invalid_expression (uint32_t id) protected inherited
find_static_extensions()
void CompilerGLSL::find_static_extensions () protected inherited
References spv::ExecutionModeInvocations, spv::ExecutionModelGeometry, spv::ExecutionModelGLCompute, spv::ExecutionModelTessellationControl, spv::ExecutionModelTessellationEvaluation, SPIRV_CROSS_THROW, and spirv_cross::TypeType.
emit_for_loop_initializers()
string CompilerGLSL::emit_for_loop_initializers (const SPIRBlock & block) protected inherited
References spirv_cross::join(), spirv_cross::SPIRBlock::loop_variables, and spirv_cross::TypeUndef.
for_loop_initializers_are_same_type()
bool CompilerGLSL::for_loop_initializers_are_same_type (const SPIRBlock & block) protected inherited
References spirv_cross::SPIRBlock::loop_variables, and spirv_cross::TypeUndef.
optimize_read_modify_write()
bool CompilerGLSL::optimize_read_modify_write (const std::string & lhs, const std::string & rhs) protected inherited
fixup_image_load_store_access()
void CompilerGLSL::fixup_image_load_store_access () protected inherited
References spirv_cross::SPIRVariable::basetype, spv::DecorationNonReadable, spv::DecorationNonWritable, ImGui::Image(), and spirv_cross::TypeVariable.
Referenced by compile().
type_is_empty()
bool CompilerGLSL::type_is_empty (const SPIRType & type) protected inherited
References spirv_cross::SPIRType::basetype, and spirv_cross::SPIRType::member_types.
sanitize_underscores()
string CompilerGLSL::sanitize_underscores (const std::string & str) static protected inherited
can_use_io_location()
bool CompilerGLSL::can_use_io_location (spv::StorageClass storage) protected inherited
References spv::ExecutionModelFragment, spv::ExecutionModelVertex, spv::StorageClassInput, and spv::StorageClassOutput.
get_next_instruction_in_block()
const Instruction * CompilerGLSL::get_next_instruction_in_block (const Instruction & instr) protected inherited
mask_relevant_memory_semantics()
uint32_t CompilerGLSL::mask_relevant_memory_semantics (uint32_t semantics) static protected inherited
References spv::MemorySemanticsAtomicCounterMemoryMask, spv::MemorySemanticsCrossWorkgroupMemoryMask, spv::MemorySemanticsImageMemoryMask, spv::MemorySemanticsSubgroupMemoryMask, spv::MemorySemanticsUniformMemoryMask, and spv::MemorySemanticsWorkgroupMemoryMask.
convert_half_to_string()
string CompilerGLSL::convert_half_to_string (const SPIRConstant & value, uint32_t col, uint32_t row) protected inherited
References spirv_cross::SPIRType::basetype, spirv_cross::SPIRType::columns, spirv_cross::convert_to_string(), spirv_cross::join(), spirv_cross::SPIRConstant::scalar_f16(), SPIRV_CROSS_THROW, and spirv_cross::SPIRType::vecsize.
convert_float_to_string()
string CompilerGLSL::convert_float_to_string (const SPIRConstant & value, uint32_t col, uint32_t row) protected inherited
References spirv_cross::SPIRType::basetype, spirv_cross::convert_to_string(), spirv_cross::join(), spirv_cross::SPIRConstant::scalar(), spirv_cross::SPIRConstant::scalar_f32(), SPIRV_CROSS_THROW, spirv_cross::SPIRType::vecsize, and spirv_cross::SPIRType::width.
convert_double_to_string()
std::string CompilerGLSL::convert_double_to_string (const SPIRConstant & value, uint32_t col, uint32_t row) protected inherited
References spirv_cross::SPIRType::basetype, spirv_cross::convert_to_string(), spirv_cross::join(), spirv_cross::SPIRConstant::scalar_f64(), spirv_cross::SPIRConstant::scalar_u64(), SPIRV_CROSS_THROW, spirv_cross::SPIRType::vecsize, and spirv_cross::SPIRType::width.
get_entry_point() [1/5]
SPIREntryPoint& spirv_cross::Compiler::get_entry_point (const std::string & name) inherited
get_entry_point() [2/5]
const SPIREntryPoint& spirv_cross::Compiler::get_entry_point (const std::string & name, spv::ExecutionModel execution_model) const inherited
get_entry_point() [3/5]
SPIREntryPoint& spirv_cross::Compiler::get_entry_point (const std::string & name, spv::ExecutionModel execution_model) inherited
get_entry_point() [4/5]
const SPIREntryPoint& spirv_cross::Compiler::get_entry_point () const protected inherited
Referenced by add_interface_block(), spirv_cross::Compiler::get_execution_mode_argument(), spirv_cross::Compiler::get_execution_mode_bitset(), spirv_cross::Compiler::get_execution_mode_mask(), spirv_cross::Compiler::get_execution_model(), spirv_cross::Compiler::get_work_group_size_specialization_constants(), spirv_cross::Compiler::interface_variable_exists_in_entry_point(), mark_location_as_used_by_shader(), spirv_cross::Compiler::set_entry_point(), spirv_cross::Compiler::set_execution_mode(), should_move_to_input_buffer(), and spirv_cross::Compiler::unset_execution_mode().
get_entry_point() [5/5]
SPIREntryPoint& spirv_cross::Compiler::get_entry_point () protected inherited
get_name()
const std::string & Compiler::get_name (uint32_t id) const inherited
References spirv_cross::Compiler::meta.
Referenced by add_input_buffer_block_member(), spirv_cross::Compiler::buffer_get_hlsl_counter_buffer(), spirv_cross::Compiler::get_block_fallback_name(), and spirv_cross::Compiler::parse().
set_decoration()
void Compiler::set_decoration (uint32_t id, spv::Decoration decoration, uint32_t argument = 0) inherited
References spv::DecorationArrayStride, spv::DecorationBinding, spv::DecorationBuiltIn, spv::DecorationDescriptorSet, spv::DecorationInputAttachmentIndex, spv::DecorationLocation, spv::DecorationMatrixStride, spv::DecorationOffset, spv::DecorationSpecId, and spirv_cross::Compiler::meta.
Referenced by add_input_buffer_block_member(), add_interface_block(), build_implicit_builtins(), get_input_buffer_block_var_id(), mark_as_packable(), spirv_cross::Compiler::parse(), and AuroraFW::GEngine::RTShaderConverter::toGLSL().
set_name()
void Compiler::set_name (uint32_t id, const std::string & name) inherited
References ensure_valid_identifier(), spirv_cross::Compiler::Source::hlsl, spirv_cross::Compiler::meta, setup::name, and spirv_cross::Compiler::source.
Referenced by add_interface_block(), spirv_cross::Compiler::build_dummy_sampler_for_combined_images(), extract_global_variables_from_function(), get_input_buffer_block_var_id(), spirv_cross::Compiler::parse(), and spirv_cross_util::rename_interface_variable().
get_decoration_mask()
uint64_t Compiler::get_decoration_mask (uint32_t id) const inherited
References spirv_cross::Compiler::get_decoration_bitset(), and spirv_cross::Bitset::get_lower().
get_decoration_bitset()
const Bitset & Compiler::get_decoration_bitset (uint32_t id) const inherited
References spirv_cross::Compiler::meta.
Referenced by add_interface_block(), spirv_cross::Compiler::get_decoration_mask(), and spirv_cross::Compiler::has_decoration().
has_decoration()
bool Compiler::has_decoration (uint32_t id, spv::Decoration decoration) const inherited
References spirv_cross::Bitset::get(), and spirv_cross::Compiler::get_decoration_bitset().
Referenced by add_interface_block(), spirv_cross::Compiler::buffer_get_hlsl_counter_buffer(), spirv_cross::Compiler::buffer_is_hlsl_counter_buffer(), emit_resources(), mark_packable_structs(), move_to_input_buffer(), spirv_cross_util::rename_interface_variable(), and spirv_cross::Compiler::to_name().
get_decoration()
uint32_t Compiler::get_decoration (uint32_t id, spv::Decoration decoration) const inherited
References spv::DecorationArrayStride, spv::DecorationBinding, spv::DecorationBuiltIn, spv::DecorationDescriptorSet, spv::DecorationInputAttachmentIndex, spv::DecorationLocation, spv::DecorationMatrixStride, spv::DecorationOffset, spv::DecorationSpecId, and spirv_cross::Compiler::meta.
Referenced by add_interface_block(), spirv_cross::Compiler::get_specialization_constants(), spirv_cross::Compiler::get_work_group_size_specialization_constants(), move_to_input_buffer(), spirv_cross_util::rename_interface_variable(), and AuroraFW::GEngine::RTShaderConverter::toGLSL().
unset_decoration()
void Compiler::unset_decoration (uint32_t id, spv::Decoration decoration) inherited
References spv::DecorationBinding, spv::DecorationBuiltIn, spv::DecorationDescriptorSet, spv::DecorationInputAttachmentIndex, spv::DecorationLocation, spv::DecorationOffset, spv::DecorationSpecId, and spirv_cross::Compiler::meta.
Referenced by AuroraFW::GEngine::RTShaderConverter::toGLSL().
get_type()
const SPIRType & Compiler::get_type (uint32_t id) const inherited
Referenced by add_interface_block(), spirv_cross::Compiler::build_combined_image_samplers(), build_implicit_builtins(), declare_constant_arrays(), declare_undefined_values(), emit_resources(), spirv_cross::Compiler::expression_type_id(), extract_global_variables_from_functions(), spirv_cross::Compiler::get_specialization_constants(), spirv_cross::Compiler::is_immutable(), mark_packable_structs(), spirv_cross::Compiler::mark_used_as_array_length(), spirv_cross::Compiler::parse(), spirv_cross_util::rename_interface_variable(), and resolve_specialized_array_lengths().
get_type_from_variable()
const SPIRType & Compiler::get_type_from_variable (uint32_t id) const inherited
get_storage_class()
StorageClass Compiler::get_storage_class (uint32_t id) const inherited
get_fallback_name()
const std::string Compiler::get_fallback_name (uint32_t id) const virtual inherited
References spirv_cross::join().
get_block_fallback_name()
const std::string Compiler::get_block_fallback_name (uint32_t id) const virtual inherited
References spirv_cross::Compiler::get_name(), and spirv_cross::join().
Referenced by spirv_cross::Compiler::get_remapped_declared_block_name().
get_member_name()
const std::string & Compiler::get_member_name (uint32_t id, uint32_t index) const inherited
References spirv_cross::Compiler::meta.
get_member_decoration()
uint32_t Compiler::get_member_decoration (uint32_t id, uint32_t index, spv::Decoration decoration) const inherited
References spv::DecorationBinding, spv::DecorationBuiltIn, spv::DecorationLocation, spv::DecorationOffset, spv::DecorationSpecId, and spirv_cross::Compiler::meta.
Referenced by add_interface_block(), align_struct(), is_member_packable(), and move_member_to_input_buffer().
set_member_name()
void Compiler::set_member_name (uint32_t id, uint32_t index, const std::string & name) inherited
References ensure_valid_identifier(), afwstd::max(), spirv_cross::Compiler::meta, and setup::name.
Referenced by add_input_buffer_block_member(), add_interface_block(), spirv_cross::Compiler::parse(), and spirv_cross_util::rename_interface_variable().
get_member_qualified_name()
const std::string & Compiler::get_member_qualified_name (uint32_t type_id, uint32_t index) const inherited
References spirv_cross::Compiler::meta.
set_member_qualified_name()
void Compiler::set_member_qualified_name (uint32_t type_id, uint32_t index, const std::string & name) inherited
References afwstd::max(), spirv_cross::Compiler::meta, and setup::name.
Referenced by add_interface_block(), and move_member_to_input_buffer().
get_member_decoration_mask()
uint64_t Compiler::get_member_decoration_mask (uint32_t id, uint32_t index) const inherited
References spirv_cross::Bitset::get_lower(), and spirv_cross::Compiler::get_member_decoration_bitset().
get_member_decoration_bitset()
const Bitset & Compiler::get_member_decoration_bitset (uint32_t id, uint32_t index) const inherited
References spirv_cross::Compiler::meta.
Referenced by spirv_cross::Compiler::get_buffer_block_flags(), spirv_cross::Compiler::get_declared_struct_member_size(), spirv_cross::Compiler::get_member_decoration_mask(), and spirv_cross::Compiler::has_member_decoration().
has_member_decoration()
bool Compiler::has_member_decoration (uint32_t id, uint32_t index, spv::Decoration decoration) const inherited
References spirv_cross::Bitset::get(), and spirv_cross::Compiler::get_member_decoration_bitset().
Referenced by add_interface_block(), is_member_packable(), and move_member_to_input_buffer().
set_member_decoration()
void Compiler::set_member_decoration (uint32_t id, uint32_t index, spv::Decoration decoration, uint32_t argument = 0) inherited
References spv::DecorationBinding, spv::DecorationBuiltIn, spv::DecorationLocation, spv::DecorationMatrixStride, spv::DecorationOffset, spv::DecorationSpecId, afwstd::max(), and spirv_cross::Compiler::meta.
Referenced by add_input_buffer_block_member(), add_interface_block(), align_struct(), and spirv_cross::Compiler::parse().
unset_member_decoration()
void Compiler::unset_member_decoration (uint32_t id, uint32_t index, spv::Decoration decoration) inherited
References spv::DecorationBuiltIn, spv::DecorationLocation, spv::DecorationOffset, spv::DecorationSpecId, and spirv_cross::Compiler::meta.
get_fallback_member_name()
virtual const std::string spirv_cross::Compiler::get_fallback_member_name (uint32_t index) const inline virtual inherited
References spirv_cross::join().
get_active_buffer_ranges()
std::vector< BufferRange > Compiler::get_active_buffer_ranges (uint32_t id) const inherited
References spirv_cross::Compiler::entry_point, and spirv_cross::Compiler::traverse_all_reachable_opcodes().
get_declared_struct_size()
size_t Compiler::get_declared_struct_size (const SPIRType & struct_type) const inherited
References spirv_cross::Compiler::get_declared_struct_member_size(), spirv_cross::SPIRType::member_types, and spirv_cross::Compiler::type_struct_member_offset().
Referenced by spirv_cross::Compiler::get_declared_struct_member_size().
get_active_interface_variables()
unordered_set< uint32_t > Compiler::get_active_interface_variables () const inherited
References spirv_cross::Compiler::dummy_sampler_id, spirv_cross::Compiler::entry_point, and spirv_cross::Compiler::traverse_all_reachable_opcodes().
Referenced by compile().
set_enabled_interface_variables()
void Compiler::set_enabled_interface_variables (std::unordered_set< uint32_t > active_variables) inherited
References spirv_cross::Compiler::active_interface_variables, and spirv_cross::Compiler::check_active_interface_variables.
Referenced by compile().
get_shader_resources() [1/3]
ShaderResources Compiler::get_shader_resources () const inherited
Referenced by AuroraFW::GEngine::RTShaderConverter::toGLSL().
get_shader_resources() [2/3]
ShaderResources spirv_cross::Compiler::get_shader_resources (const std::unordered_set< uint32_t > & active_variables) const inherited
get_shader_resources() [3/3]
ShaderResources spirv_cross::Compiler::get_shader_resources (const std::unordered_set< uint32_t > * active_variables) const protected inherited
set_remapped_variable_state()
void Compiler::set_remapped_variable_state (uint32_t id, bool remap_enable) inherited
get_remapped_variable_state()
bool Compiler::get_remapped_variable_state (uint32_t id) const inherited
set_subpass_input_remapped_components()
void Compiler::set_subpass_input_remapped_components (uint32_t id, uint32_t components) inherited
get_subpass_input_remapped_components()
uint32_t Compiler::get_subpass_input_remapped_components (uint32_t id) const inherited
get_entry_points()
vector< string > Compiler::get_entry_points () const inherited
References spirv_cross::Compiler::entry_points.
set_entry_point() [1/2]
void Compiler::set_entry_point (const std::string & name) inherited
References spirv_cross::Compiler::entry_point, and setup::name.
set_entry_point() [2/2]
void Compiler::set_entry_point (const std::string & entry, spv::ExecutionModel execution_model) inherited
References spirv_cross::Compiler::entry_point, spirv_cross::Compiler::get_entry_point(), and setup::name.
rename_entry_point()
void Compiler::rename_entry_point (const std::string & old_name, const std::string & new_name, spv::ExecutionModel execution_model) inherited
get_cleansed_entry_point_name()
const string & Compiler::get_cleansed_entry_point_name (const std::string & name, spv::ExecutionModel execution_model) const inherited
References setup::name, and spirv_cross::SPIREntryPoint::name.
get_execution_mode_mask()
uint64_t Compiler::get_execution_mode_mask () const inherited
References spirv_cross::SPIREntryPoint::flags, spirv_cross::Compiler::get_entry_point(), and spirv_cross::Bitset::get_lower().
get_execution_mode_bitset()
const Bitset & Compiler::get_execution_mode_bitset () const inherited
References spirv_cross::SPIREntryPoint::flags, and spirv_cross::Compiler::get_entry_point().
unset_execution_mode()
void Compiler::unset_execution_mode (spv::ExecutionMode mode) inherited
References spirv_cross::Compiler::get_entry_point(), and mode().
set_execution_mode()
void Compiler::set_execution_mode (spv::ExecutionMode mode, uint32_t arg0 = 0, uint32_t arg1 = 0, uint32_t arg2 = 0) inherited
References spv::ExecutionModeInvocations, spv::ExecutionModeLocalSize, spv::ExecutionModeOutputVertices, spirv_cross::Compiler::get_entry_point(), and mode().
get_execution_mode_argument()
uint32_t Compiler::get_execution_mode_argument (spv::ExecutionMode mode, uint32_t index = 0) const inherited
References spv::ExecutionModeInvocations, spv::ExecutionModeLocalSize, spv::ExecutionModeOutputVertices, spirv_cross::Compiler::get_entry_point(), and mode().
get_execution_model()
ExecutionModel Compiler::get_execution_model () const inherited
References spirv_cross::Compiler::get_entry_point().
get_work_group_size_specialization_constants()
uint32_t Compiler::get_work_group_size_specialization_constants (SpecializationConstant & x, SpecializationConstant & y, SpecializationConstant & z) const inherited
References spirv_cross::SpecializationConstant::constant_id, spv::DecorationSpecId, spirv_cross::Compiler::get_decoration(), spirv_cross::Compiler::get_entry_point(), and spirv_cross::SpecializationConstant::id.
Referenced by emit_specialization_constants().
build_dummy_sampler_for_combined_images()
uint32_t Compiler::build_dummy_sampler_for_combined_images () inherited
References spirv_cross::SPIRType::basetype, spirv_cross::Compiler::dummy_sampler_id, spirv_cross::Compiler::entry_point, spirv_cross::Compiler::increase_bound_by(), spirv_cross::Compiler::DummySamplerForCombinedImageHandler::need_dummy_sampler, spirv_cross::SPIRType::Sampler, spirv_cross::Compiler::set_name(), spv::StorageClassUniformConstant, and spirv_cross::Compiler::traverse_all_reachable_opcodes().
build_combined_image_samplers()
void Compiler::build_combined_image_samplers () inherited
References spirv_cross::Compiler::combined_image_samplers, spirv_cross::SPIRFunction::combined_parameters, spirv_cross::Compiler::entry_point, spirv_cross::Compiler::get_type(), spirv_cross::Compiler::ids, spirv_cross::Compiler::traverse_all_reachable_opcodes(), and spirv_cross::TypeFunction.
get_combined_image_samplers()
const std::vector<CombinedImageSampler>& spirv_cross::Compiler::get_combined_image_samplers () const inline inherited
References spirv_cross::Compiler::combined_image_samplers.
set_variable_type_remap_callback()
void spirv_cross::Compiler::set_variable_type_remap_callback (VariableTypeRemapCallback cb) inline inherited
References spirv_cross::Compiler::variable_remap_callback.
get_specialization_constants()
vector< SpecializationConstant > Compiler::get_specialization_constants () const inherited
References spv::DecorationSpecId, spirv_cross::Compiler::get_decoration(), spirv_cross::Compiler::get_type(), spirv_cross::Compiler::ids, and spirv_cross::TypeConstant.
Referenced by emit_specialization_constants().
get_constant() [1/2]
SPIRConstant & Compiler::get_constant (uint32_t id) inherited
get_constant() [2/2]
const SPIRConstant & Compiler::get_constant (uint32_t id) const inherited
get_current_id_bound()
uint32_t spirv_cross::Compiler::get_current_id_bound () const inline inherited
References spirv_cross::Compiler::ids.
Referenced by spirv_cross::Compiler::buffer_get_hlsl_counter_buffer(), and spirv_cross::CFG::CFG().
type_struct_member_offset()
uint32_t Compiler::type_struct_member_offset (const SPIRType & type, uint32_t index) const inherited
References spv::DecorationOffset, spirv_cross::Compiler::meta, spirv_cross::IVariant::self, and SPIRV_CROSS_THROW.
Referenced by spirv_cross::Compiler::get_declared_struct_size().
type_struct_member_array_stride()
uint32_t Compiler::type_struct_member_array_stride (const SPIRType & type, uint32_t index) const inherited
References spv::DecorationArrayStride, spirv_cross::SPIRType::member_types, spirv_cross::Compiler::meta, and SPIRV_CROSS_THROW.
Referenced by spirv_cross::Compiler::get_declared_struct_member_size(), and is_member_packable().
type_struct_member_matrix_stride()
uint32_t Compiler::type_struct_member_matrix_stride (const SPIRType & type, uint32_t index) const inherited
References spv::DecorationMatrixStride, spirv_cross::Compiler::meta, spirv_cross::IVariant::self, and SPIRV_CROSS_THROW.
Referenced by spirv_cross::Compiler::get_declared_struct_member_size().
get_binary_offset_for_decoration()
bool Compiler::get_binary_offset_for_decoration (uint32_t id, spv::Decoration decoration, uint32_t & word_offset) const inherited
References spirv_cross::Compiler::meta.
buffer_is_hlsl_counter_buffer()
bool Compiler::buffer_is_hlsl_counter_buffer (uint32_t id) const inherited
References spv::DecorationBufferBlock, spirv_cross::Compiler::has_decoration(), spirv_cross::Compiler::meta, and spv::StorageClassStorageBuffer.
buffer_get_hlsl_counter_buffer()
bool Compiler::buffer_get_hlsl_counter_buffer (uint32_t id, uint32_t & counter_id) const inherited
References spv::DecorationBufferBlock, spirv_cross::Compiler::get_current_id_bound(), spirv_cross::Compiler::get_name(), spirv_cross::Compiler::has_decoration(), spirv_cross::Compiler::meta, setup::name, and spv::StorageClassStorageBuffer.
get_declared_capabilities()
const std::vector< spv::Capability > & Compiler::get_declared_capabilities () const inherited
References spirv_cross::Compiler::declared_capabilities.
get_declared_extensions()
const std::vector< std::string > & Compiler::get_declared_extensions () const inherited
References spirv_cross::Compiler::declared_extensions.
get_remapped_declared_block_name()
std::string Compiler::get_remapped_declared_block_name (uint32_t id) const inherited
References spirv_cross::Compiler::declared_block_names, spirv_cross::Compiler::get_block_fallback_name(), and spirv_cross::Compiler::meta.
stream()
const uint32_t* spirv_cross::Compiler::stream (const Instruction & instr) const inline protected inherited
References spirv_cross::Instruction::length, spirv_cross::Instruction::offset, spirv_cross::Compiler::spirv, and SPIRV_CROSS_THROW.
Referenced by spirv_cross::Compiler::block_is_pure(), extract_global_variables_from_function(), spirv_cross::Compiler::parse(), spirv_cross::Compiler::register_global_read_dependencies(), and spirv_cross::Compiler::traverse_all_reachable_opcodes().
set()
template<typename T , typename... P> T& spirv_cross::Compiler::set (uint32_t id, P &&... args) inline protected inherited
References spirv_cross::Compiler::ids.
get() [1/2]
template<typename T > T& spirv_cross::Compiler::get (uint32_t id) inline protected inherited
References spirv_cross::Compiler::ids.
Referenced by spirv_cross::Compiler::InterfaceVariableAccessHandler::handle(), and spirv_cross::DominatorBuilder::lift_continue_block_dominator().
get() [2/2]
template<typename T > const T& spirv_cross::Compiler::get (uint32_t id) const inline protected inherited
References spirv_cross::Compiler::ids.
maybe_get() [1/2]
template<typename T > T* spirv_cross::Compiler::maybe_get (uint32_t id) inline protected inherited
References spirv_cross::Compiler::ids.
Referenced by spirv_cross::Compiler::InterfaceVariableAccessHandler::handle().
maybe_get() [2/2]
template<typename T > const T* spirv_cross::Compiler::maybe_get (uint32_t id) const inline protected inherited
References spirv_cross::Compiler::ids.
is_builtin_variable()
bool Compiler::is_builtin_variable (const SPIRVariable & var) const protected inherited
References spirv_cross::SPIRVariable::basetype, spirv_cross::SPIRVariable::compat_builtin, spirv_cross::Compiler::meta, and spirv_cross::IVariant::self.
Referenced by add_interface_block(), and spirv_cross::Compiler::is_hidden_variable().
is_hidden_variable()
bool Compiler::is_hidden_variable (const SPIRVariable & var, bool include_builtins = false) const protected inherited
References spirv_cross::Compiler::active_interface_variables, spirv_cross::Compiler::check_active_interface_variables, spirv_cross::CombinedImageSampler::combined_id, spirv_cross::Compiler::combined_image_samplers, spirv_cross::Compiler::is_builtin_variable(), spirv_cross::SPIRVariable::remapped_variable, spirv_cross::IVariant::self, spirv_cross::SPIRVariable::storage, and storage_class_is_interface().
Referenced by add_interface_block(), and mark_packable_structs().
is_immutable()
bool Compiler::is_immutable (uint32_t id) const protected inherited
References spirv_cross::Compiler::expression_is_lvalue(), spirv_cross::Compiler::get_type(), spirv_cross::Compiler::ids, spv::StorageClassUniformConstant, spirv_cross::TypeAccessChain, spirv_cross::TypeConstant, spirv_cross::TypeConstantOp, spirv_cross::TypeExpression, spirv_cross::TypeUndef, and spirv_cross::TypeVariable.
Referenced by spirv_cross::Compiler::register_read().
is_member_builtin()
bool Compiler::is_member_builtin (const SPIRType & type, uint32_t index, spv::BuiltIn * builtin) const protected inherited
References spirv_cross::Compiler::meta, and spirv_cross::IVariant::self.
Referenced by add_interface_block().
is_scalar()
bool Compiler::is_scalar (const SPIRType & type) const protected inherited
References spirv_cross::SPIRType::columns, and spirv_cross::SPIRType::vecsize.
is_vector()
bool Compiler::is_vector (const SPIRType & type) const protected inherited
References spirv_cross::SPIRType::columns, and spirv_cross::SPIRType::vecsize.
is_matrix()
bool Compiler::is_matrix (const SPIRType & type) const protected inherited
References spirv_cross::SPIRType::columns, and spirv_cross::SPIRType::vecsize.
Referenced by is_member_packable(), and should_move_to_input_buffer().
is_array()
bool Compiler::is_array (const SPIRType & type) const protected inherited
References spirv_cross::SPIRType::array.
Referenced by ensure_correct_builtin_type(), is_member_packable(), and should_move_to_input_buffer().
expression_type_id()
uint32_t Compiler::expression_type_id (uint32_t id) const protected inherited
References spirv_cross::Compiler::expression_type(), spirv_cross::Compiler::get_type(), spirv_cross::Compiler::ids, SPIRV_CROSS_THROW, spirv_cross::TypeAccessChain, spirv_cross::TypeCombinedImageSampler, spirv_cross::TypeConstant, spirv_cross::TypeConstantOp, spirv_cross::TypeExpression, spirv_cross::TypeUndef, and spirv_cross::TypeVariable.
Referenced by spirv_cross::Compiler::expression_type().
expression_type()
const SPIRType & Compiler::expression_type (uint32_t id) const protected inherited
References spirv_cross::Compiler::expression_type_id().
Referenced by spirv_cross::Compiler::analyze_variable_scope(), spirv_cross::Compiler::block_is_pure(), emit_specialization_constants(), spirv_cross::Compiler::expression_is_lvalue(), and spirv_cross::Compiler::expression_type_id().
expression_is_lvalue()
bool Compiler::expression_is_lvalue (uint32_t id) const protected inherited
References spirv_cross::Compiler::expression_type(), spirv_cross::SPIRType::Image, spirv_cross::SPIRType::SampledImage, and spirv_cross::SPIRType::Sampler.
Referenced by spirv_cross::Compiler::is_immutable().
variable_storage_is_aliased()
bool Compiler::variable_storage_is_aliased (const SPIRVariable & var) protected inherited
References spirv_cross::SPIRType::AtomicCounter, spirv_cross::SPIRVariable::basetype, spv::DecorationBufferBlock, spv::DecorationRestrict, spirv_cross::SPIRType::Image, spirv_cross::Compiler::meta, spirv_cross::IVariant::self, spirv_cross::SPIRVariable::storage, and spv::StorageClassStorageBuffer.
Referenced by spirv_cross::Compiler::parse(), and spirv_cross::Compiler::register_write().
maybe_get_backing_variable()
SPIRVariable * Compiler::maybe_get_backing_variable (uint32_t chain) protected inherited
Referenced by spirv_cross::Compiler::register_global_read_dependencies(), and spirv_cross::Compiler::register_read().
mark_used_as_array_length()
void Compiler::mark_used_as_array_length (uint32_t id) protected inherited
References spirv_cross::Compiler::get_type(), spirv_cross::Compiler::ids, SPIRV_CROSS_THROW, spirv_cross::TypeConstant, spirv_cross::TypeConstantOp, and spirv_cross::TypeUndef.
Referenced by spirv_cross::Compiler::parse().
register_read()
void Compiler::register_read (uint32_t expr, uint32_t chain, bool forwarded) protected inherited
References spirv_cross::Compiler::is_immutable(), and spirv_cross::Compiler::maybe_get_backing_variable().
register_write()
void Compiler::register_write (uint32_t chain) protected inherited
References spirv_cross::Compiler::flush_all_aliased_variables(), spirv_cross::Compiler::flush_dependees(), spirv_cross::Compiler::force_recompile, and spirv_cross::Compiler::variable_storage_is_aliased().
is_continue()
bool spirv_cross::Compiler::is_continue (uint32_t next) const inline protected inherited
References spirv_cross::Compiler::continue_blocks.
Referenced by spirv_cross::Compiler::analyze_variable_scope(), and spirv_cross::Compiler::block_is_outside_flow_control_from_block().
is_single_block_loop()
bool spirv_cross::Compiler::is_single_block_loop (uint32_t next) const inline protected inherited
References spirv_cross::SPIRBlock::MergeLoop.
Referenced by spirv_cross::Compiler::analyze_variable_scope().
is_break()
bool spirv_cross::Compiler::is_break (uint32_t next) const inline protected inherited
References spirv_cross::Compiler::loop_merge_targets, and spirv_cross::Compiler::multiselect_merge_targets.
is_loop_break()
bool spirv_cross::Compiler::is_loop_break (uint32_t next) const inline protected inherited
References spirv_cross::Compiler::loop_merge_targets.
is_conditional()
bool spirv_cross::Compiler::is_conditional (uint32_t next) const inline protected inherited
References spirv_cross::Compiler::multiselect_merge_targets, and spirv_cross::Compiler::selection_merge_targets.
flush_dependees()
void Compiler::flush_dependees (SPIRVariable & var) protected inherited
References spirv_cross::SPIRVariable::dependees, and spirv_cross::Compiler::invalid_expressions.
Referenced by spirv_cross::Compiler::flush_all_active_variables(), spirv_cross::Compiler::flush_all_aliased_variables(), spirv_cross::Compiler::flush_all_atomic_capable_variables(), and spirv_cross::Compiler::register_write().
flush_all_active_variables()
void Compiler::flush_all_active_variables () protected inherited
References spirv_cross::SPIRFunction::arguments, spirv_cross::Compiler::current_function, spirv_cross::Compiler::flush_all_aliased_variables(), spirv_cross::Compiler::flush_dependees(), spirv_cross::Compiler::global_variables, and spirv_cross::SPIRFunction::local_variables.
flush_control_dependent_expressions()
void Compiler::flush_control_dependent_expressions (uint32_t block) protected inherited
References spirv_cross::Compiler::invalid_expressions.
flush_all_atomic_capable_variables()
void Compiler::flush_all_atomic_capable_variables () protected inherited
References spirv_cross::Compiler::flush_all_aliased_variables(), spirv_cross::Compiler::flush_dependees(), and spirv_cross::Compiler::global_variables.
flush_all_aliased_variables()
void Compiler::flush_all_aliased_variables () protected inherited
References spirv_cross::Compiler::aliased_variables, and spirv_cross::Compiler::flush_dependees().
Referenced by spirv_cross::Compiler::flush_all_active_variables(), spirv_cross::Compiler::flush_all_atomic_capable_variables(), and spirv_cross::Compiler::register_write().
register_global_read_dependencies() [1/2]
void Compiler::register_global_read_dependencies (const SPIRBlock & func, uint32_t id) protected inherited
References spv::DimSubpassData, spirv_cross::SPIRType::Image, spirv_cross::Compiler::maybe_get_backing_variable(), spv::OpFunctionCall, spv::OpImageRead, spv::OpLoad, spirv_cross::SPIRBlock::ops, spv::StorageClassFunction, and spirv_cross::Compiler::stream().
Referenced by spirv_cross::Compiler::register_global_read_dependencies().
register_global_read_dependencies() [2/2]
void Compiler::register_global_read_dependencies (const SPIRFunction & func, uint32_t id) protected inherited
References spirv_cross::SPIRFunction::blocks, and spirv_cross::Compiler::register_global_read_dependencies().
update_name_cache()
void Compiler::update_name_cache (std::unordered_set< std::string > & cache, std::string & name) protected inherited
References spirv_cross::convert_to_string(), and setup::name.
function_is_pure()
bool Compiler::function_is_pure (const SPIRFunction & func) protected inherited
References spirv_cross::Compiler::block_is_pure(), and spirv_cross::SPIRFunction::blocks.
Referenced by spirv_cross::Compiler::block_is_pure().
block_is_pure()
bool Compiler::block_is_pure (const SPIRBlock & block) protected inherited
References spirv_cross::Compiler::expression_type(), spirv_cross::Compiler::function_is_pure(), spv::OpAtomicAnd, spv::OpAtomicCompareExchange, spv::OpAtomicCompareExchangeWeak, spv::OpAtomicExchange, spv::OpAtomicIAdd, spv::OpAtomicIDecrement, spv::OpAtomicIIncrement, spv::OpAtomicISub, spv::OpAtomicLoad, spv::OpAtomicOr, spv::OpAtomicSMax, spv::OpAtomicSMin, spv::OpAtomicStore, spv::OpAtomicUMax, spv::OpAtomicUMin, spv::OpAtomicXor, spv::OpControlBarrier, spv::OpCopyMemory, spv::OpEmitStreamVertex, spv::OpEmitVertex, spv::OpEndPrimitive, spv::OpEndStreamPrimitive, spv::OpFunctionCall, spv::OpImageWrite, spv::OpMemoryBarrier, spirv_cross::SPIRBlock::ops, spv::OpStore, spv::StorageClassFunction, and spirv_cross::Compiler::stream().
Referenced by spirv_cross::Compiler::function_is_pure().
block_is_outside_flow_control_from_block()
bool Compiler::block_is_outside_flow_control_from_block (const SPIRBlock & from, const SPIRBlock & to) protected inherited
References spirv_cross::Compiler::is_continue(), spirv_cross::SPIRBlock::MergeNone, spirv_cross::SPIRBlock::Select, and spirv_cross::IVariant::self.
execution_is_branchless()
bool Compiler::execution_is_branchless (const SPIRBlock & from, const SPIRBlock & to) const protected inherited
References spirv_cross::SPIRBlock::Direct, spirv_cross::SPIRBlock::MergeNone, and spirv_cross::IVariant::self.
Referenced by spirv_cross::Compiler::continue_block_type(), and spirv_cross::Compiler::execution_is_noop().
execution_is_noop()
bool Compiler::execution_is_noop (const SPIRBlock & from, const SPIRBlock & to) const protected inherited
References spirv_cross::Compiler::execution_is_branchless(), and spirv_cross::IVariant::self.
Referenced by spirv_cross::Compiler::continue_block_type().
continue_block_type()
SPIRBlock::ContinueBlockType Compiler::continue_block_type (const SPIRBlock & continue_block) const protected inherited
References spirv_cross::SPIRBlock::complex_continue, spirv_cross::SPIRBlock::ComplexLoop, spirv_cross::SPIRBlock::DoWhileLoop, spirv_cross::Compiler::execution_is_branchless(), spirv_cross::Compiler::execution_is_noop(), spirv_cross::SPIRBlock::false_block, spirv_cross::SPIRBlock::ForLoop, spirv_cross::SPIRBlock::loop_dominator, spirv_cross::SPIRBlock::merge, spirv_cross::SPIRBlock::MergeLoop, spirv_cross::SPIRBlock::MergeNone, spirv_cross::SPIRBlock::Select, spirv_cross::SPIRBlock::terminator, spirv_cross::SPIRBlock::true_block, and spirv_cross::SPIRBlock::WhileLoop.
block_is_loop_candidate()
bool Compiler::block_is_loop_candidate (const SPIRBlock & block, SPIRBlock::Method method) const protected inherited
References spirv_cross::SPIRBlock::complex_continue, spirv_cross::SPIRBlock::continue_block, spirv_cross::SPIRBlock::Direct, spirv_cross::SPIRBlock::disable_block_optimization, spirv_cross::SPIRBlock::false_block, spirv_cross::merge(), spirv_cross::SPIRBlock::merge, spirv_cross::SPIRBlock::merge_block, spirv_cross::SPIRBlock::MergeLoop, spirv_cross::SPIRBlock::MergeNone, spirv_cross::SPIRBlock::MergeToDirectForLoop, spirv_cross::SPIRBlock::MergeToSelectContinueForLoop, spirv_cross::SPIRBlock::MergeToSelectForLoop, spirv_cross::SPIRBlock::next_block, spirv_cross::SPIRBlock::ops, spirv_cross::SPIRBlock::phi_variables, spirv_cross::SPIRBlock::Select, spirv_cross::IVariant::self, spirv_cross::SPIRBlock::terminator, and spirv_cross::SPIRBlock::true_block.
increase_bound_by()
uint32_t Compiler::increase_bound_by (uint32_t incr_amount) protected inherited
References spirv_cross::Compiler::ids, and spirv_cross::Compiler::meta.
Referenced by add_interface_block(), spirv_cross::Compiler::build_dummy_sampler_for_combined_images(), build_implicit_builtins(), ensure_correct_builtin_type(), extract_global_variables_from_function(), get_input_buffer_block_var_id(), and spirv_cross::Compiler::make_constant_null().
types_are_logically_equivalent()
bool Compiler::types_are_logically_equivalent (const SPIRType & a, const SPIRType & b) const protected inherited
References a, spirv_cross::SPIRType::array, spirv_cross::SPIRType::basetype, spirv_cross::SPIRType::columns, spirv_cross::SPIRType::Image, spirv_cross::SPIRType::image, spirv_cross::SPIRType::member_types, memcmp(), spirv_cross::SPIRType::SampledImage, spirv_cross::SPIRType::vecsize, and spirv_cross::SPIRType::width.
Referenced by spirv_cross::Compiler::parse().
inherit_expression_dependencies()
void Compiler::inherit_expression_dependencies (uint32_t dst, uint32_t source) protected inherited
References spirv_cross::Compiler::forced_temporaries, and spirv_cross::Compiler::forwarded_temporaries.
interface_variable_exists_in_entry_point()
bool Compiler::interface_variable_exists_in_entry_point (uint32_t id) const protected inherited
References spirv_cross::Compiler::entry_points, spirv_cross::Compiler::get_entry_point(), SPIRV_CROSS_THROW, spv::StorageClassInput, spv::StorageClassOutput, and spv::StorageClassUniformConstant.
Referenced by add_interface_block().
remap_variable_type_name()
void spirv_cross::Compiler::remap_variable_type_name (const SPIRType & type, const std::string & var_name, std::string & type_name) const inline protected inherited
References spirv_cross::Compiler::variable_remap_callback.
analyze_variable_scope()
void Compiler::analyze_variable_scope (SPIRFunction & function) protected inherited
References spirv_cross::DominatorBuilder::add_block(), spirv_cross::Compiler::analyze_parameter_preservation(), spirv_cross::SPIRBlock::cases, spirv_cross::SPIRBlock::condition, spirv_cross::Compiler::continue_block_to_loop_header, spirv_cross::Compiler::current_block, spirv_cross::SPIRBlock::default_block, spirv_cross::SPIRBlock::Direct, spirv_cross::Compiler::expression_type(), spirv_cross::SPIRBlock::false_block, spirv_cross::Compiler::forced_temporaries, spirv_cross::DominatorBuilder::get_dominator(), spirv_cross::CFG::get_preceding_edges(), spirv_cross::CFG::get_succeeding_edges(), spirv_cross::Compiler::hoisted_temporaries, spirv_cross::Compiler::is_continue(), spirv_cross::Compiler::is_single_block_loop(), spirv_cross::DominatorBuilder::lift_continue_block_dominator(), spirv_cross::Compiler::loop_blocks, spirv_cross::SPIRBlock::MultiSelect, spirv_cross::SPIRBlock::next_block, spv::OpAccessChain, spv::OpArrayLength, spv::OpCompositeExtract, spv::OpCompositeInsert, spv::OpCopyMemory, spv::OpCopyObject, spv::OpExtInst, spv::OpFunctionCall, spv::OpInBoundsAccessChain, spv::OpLoad, spv::OpStore, spv::OpVectorShuffle, spirv_cross::SPIRVariable::phi_variable, spirv_cross::SPIRBlock::Select, spirv_cross::IVariant::self, spv::StorageClassFunction, spirv_cross::SPIRType::Struct, spirv_cross::SPIRBlock::terminator, spirv_cross::Compiler::traverse_all_reachable_opcodes(), spirv_cross::SPIRBlock::true_block, spirv_cross::TypeExpression, and spirv_cross::CFG::walk_from().
parse() [1/2]
void Compiler::parse () protected inherited
References spv::BuiltInWorkgroupSize, spirv_cross::Compiler::current_block, spirv_cross::Compiler::current_function, spirv_cross::Compiler::entry_points, spirv_cross::Compiler::get_type(), spirv_cross::Compiler::ids, spirv_cross::Compiler::inst, is_valid_spirv_version(), spv::MagicNumber, spirv_cross::Compiler::meta, spirv_cross::IVariant::self, spirv_cross::Compiler::spirv, SPIRV_CROSS_THROW, swap_endian(), and spirv_cross::TypeConstant.
Referenced by spirv_cross::Compiler::Compiler().
parse() [2/2]
void Compiler::parse (const Instruction & i) protected inherited
References spv::AccessQualifierMax, spirv_cross::SPIRFunction::add_local_variable(), spirv_cross::SPIRFunction::add_parameter(), spirv_cross::Compiler::aliased_variables, spirv_cross::SPIRType::AtomicCounter, spirv_cross::SPIRFunction::blocks, spirv_cross::SPIRType::Boolean, spv::CapabilityKernel, spirv_cross::SPIRBlock::cases, spirv_cross::SPIRBlock::condition, spirv_cross::SPIRBlock::continue_block, spirv_cross::Compiler::continue_block_to_loop_header, spirv_cross::Compiler::continue_blocks, spirv_cross::Compiler::current_block, spirv_cross::Compiler::current_function, spirv_cross::Compiler::declared_capabilities, spirv_cross::Compiler::declared_extensions, spv::DecorationNonReadable, spv::DecorationNonWritable, spirv_cross::SPIRBlock::default_block, spirv_cross::SPIRBlock::Direct, spirv_cross::SPIRType::Double, spirv_cross::SPIRFunction::entry_block, spirv_cross::Compiler::entry_point, spirv_cross::Compiler::entry_points, spirv_cross::Compiler::Source::es, spv::ExecutionModeInvocations, spv::ExecutionModeLocalSize, spv::ExecutionModeOutputVertices, extract_string(), spirv_cross::SPIRBlock::false_block, spirv_cross::SPIRType::Float, spirv_cross::Compiler::get_name(), spirv_cross::Compiler::global_struct_cache, spirv_cross::Compiler::global_variables, spirv_cross::SPIRExtension::GLSL, spirv_cross::SPIRType::Half, spirv_cross::Compiler::Source::hlsl, ImGui::Image(), spirv_cross::SPIRType::Image, spirv_cross::SPIRType::Int, spirv_cross::SPIRType::Int64, spirv_cross::SPIRBlock::Kill, spirv_cross::Compiler::Source::known, spirv_cross::Instruction::length, spirv_cross::Compiler::loop_blocks, spirv_cross::Compiler::loop_merge_targets, spirv_cross::Compiler::make_constant_null(), spirv_cross::Compiler::mark_used_as_array_length(), spirv_cross::SPIRBlock::merge, spirv_cross::SPIRBlock::merge_block, spirv_cross::SPIRBlock::MergeLoop, spirv_cross::SPIRBlock::MergeNone, spirv_cross::SPIRBlock::MergeSelection, spirv_cross::Compiler::meta, mode(), spirv_cross::SPIRBlock::MultiSelect, spirv_cross::Compiler::multiselect_merge_targets, spirv_cross::SPIRBlock::next_block, spirv_cross::Instruction::offset, spirv_cross::Instruction::op, spv::OpBranch, spv::OpBranchConditional, spv::OpCapability, spv::OpConstant, spv::OpConstantComposite, spv::OpConstantFalse, spv::OpConstantNull, spv::OpConstantTrue, spv::OpDecorate, spv::OpEntryPoint, spv::OpExecutionMode, spv::OpExtension, spv::OpExtInstImport, spv::OpFunction, spv::OpFunctionEnd, spv::OpFunctionParameter, spv::OpKill, spv::OpLabel, spv::OpLine, spv::OpLoopMerge, spv::OpMemberDecorate, spv::OpMemberName, spv::OpMemoryModel, spv::OpName, spv::OpNoLine, spv::OpNop, spv::OpPhi, spv::OpReturn, spv::OpReturnValue, spirv_cross::SPIRBlock::ops, spv::OpSelectionMerge, spv::OpSource, spv::OpSourceExtension, spv::OpSpecConstant, spv::OpSpecConstantComposite, spv::OpSpecConstantFalse, spv::OpSpecConstantOp, spv::OpSpecConstantTrue, spv::OpString, spv::OpSwitch, spv::OpTypeArray, spv::OpTypeBool, spv::OpTypeFloat, spv::OpTypeFunction, spv::OpTypeImage, spv::OpTypeInt, spv::OpTypeMatrix, spv::OpTypePointer, spv::OpTypeRuntimeArray, spv::OpTypeSampledImage, spv::OpTypeSampler, spv::OpTypeStruct, spv::OpTypeVector, spv::OpTypeVoid, spv::OpUndef, spv::OpUnreachable, spv::OpVariable, spirv_cross::SPIRBlock::phi_variables, spirv_cross::SPIRBlock::Return, spirv_cross::SPIRBlock::return_value, spirv_cross::SPIRType::SampledImage, spirv_cross::SPIRType::Sampler, spirv_cross::SPIRBlock::Select, spirv_cross::Compiler::selection_merge_targets, spirv_cross::IVariant::self, spirv_cross::Compiler::set_decoration(), spirv_cross::Compiler::set_member_decoration(), spirv_cross::Compiler::set_member_name(), spirv_cross::Compiler::set_name(), spirv_cross::Compiler::source, spv::SourceLanguageESSL, spv::SourceLanguageGLSL, spv::SourceLanguageHLSL, spirv_cross::Compiler::spirv, SPIRV_CROSS_THROW, spirv_cross::SPIRExtension::SPV_AMD_gcn_shader, spirv_cross::SPIRExtension::SPV_AMD_shader_ballot, spirv_cross::SPIRExtension::SPV_AMD_shader_explicit_vertex_parameter, spirv_cross::SPIRExtension::SPV_AMD_shader_trinary_minmax, spv::StorageClassAtomicCounter, spv::StorageClassFunction, spv::StorageClassOutput, spv::StorageClassPrivate, spv::StorageClassWorkgroup, spirv_cross::Compiler::stream(), spirv_cross::SPIRType::Struct, spirv_cross::SPIRBlock::terminator, spirv_cross::SPIRBlock::true_block, spirv_cross::Compiler::types_are_logically_equivalent(), spirv_cross::SPIRType::UInt, spirv_cross::SPIRType::UInt64, spirv_cross::SPIRBlock::Unreachable, spirv_cross::SPIRExtension::Unsupported, spirv_cross::Compiler::variable_storage_is_aliased(), spirv_cross::Compiler::Source::version, spirv_cross::SPIRType::Void, and width.
traverse_all_reachable_opcodes() [1/2]
bool Compiler::traverse_all_reachable_opcodes (const SPIRBlock & block, OpcodeHandler & handler) const protected inherited
References spirv_cross::Compiler::OpcodeHandler::begin_function_scope(), spirv_cross::Compiler::OpcodeHandler::end_function_scope(), spirv_cross::Compiler::OpcodeHandler::follow_function_call(), spirv_cross::Compiler::OpcodeHandler::handle(), spv::OpFunctionCall, spirv_cross::SPIRBlock::ops, spirv_cross::Compiler::OpcodeHandler::set_current_block(), and spirv_cross::Compiler::stream().
Referenced by spirv_cross::Compiler::analyze_image_and_sampler_usage(), spirv_cross::Compiler::analyze_variable_scope(), spirv_cross::Compiler::build_combined_image_samplers(), spirv_cross::Compiler::build_dummy_sampler_for_combined_images(), spirv_cross::Compiler::get_active_buffer_ranges(), spirv_cross::Compiler::get_active_interface_variables(), preprocess_op_codes(), spirv_cross::Compiler::traverse_all_reachable_opcodes(), and spirv_cross::Compiler::update_active_builtins().
traverse_all_reachable_opcodes() [2/2]
bool Compiler::traverse_all_reachable_opcodes (const SPIRFunction & block, OpcodeHandler & handler) const protected inherited
References spirv_cross::SPIRFunction::blocks, and spirv_cross::Compiler::traverse_all_reachable_opcodes().
get_buffer_block_flags()
Bitset Compiler::get_buffer_block_flags (const SPIRVariable & var) protected inherited
References spirv_cross::SPIRVariable::basetype, spirv_cross::Compiler::get_member_decoration_bitset(), spirv_cross::Bitset::merge_and(), spirv_cross::Bitset::merge_or(), spirv_cross::Compiler::meta, spirv_cross::IVariant::self, and spirv_cross::SPIRType::Struct.
get_common_basic_type()
bool Compiler::get_common_basic_type (const SPIRType & type, SPIRType::BaseType & base_type) protected inherited
References spirv_cross::SPIRType::basetype, spirv_cross::SPIRType::member_types, spirv_cross::SPIRType::Struct, and spirv_cross::SPIRType::Unknown.
update_active_builtins()
void Compiler::update_active_builtins () protected inherited
References spirv_cross::Compiler::active_input_builtins, spirv_cross::Compiler::active_output_builtins, spirv_cross::Compiler::clip_distance_count, spirv_cross::Compiler::cull_distance_count, spirv_cross::Compiler::entry_point, spirv_cross::Bitset::reset(), and spirv_cross::Compiler::traverse_all_reachable_opcodes().
Referenced by compile().
has_active_builtin()
bool Compiler::has_active_builtin (spv::BuiltIn builtin, spv::StorageClass storage) protected inherited
References spirv_cross::Compiler::active_input_builtins, spirv_cross::Compiler::active_output_builtins, spirv_cross::Bitset::get(), spv::StorageClassInput, and spv::StorageClassOutput.
Referenced by add_interface_block().
analyze_parameter_preservation()
void Compiler::analyze_parameter_preservation (SPIRFunction & entry, const CFG & cfg, const std::unordered_map< uint32_t, std::unordered_set< uint32_t >> & variable_to_blocks, const std::unordered_map< uint32_t, std::unordered_set< uint32_t >> & complete_write_blocks) protected inherited
References spirv_cross::SPIRFunction::arguments, spirv_cross::SPIRType::AtomicCounter, spirv_cross::SPIRFunction::entry_block, exists_unaccessed_path_to_return(), spirv_cross::SPIRType::Image, spirv_cross::SPIRType::SampledImage, and spirv_cross::SPIRType::Sampler.
Referenced by spirv_cross::Compiler::analyze_variable_scope().
analyze_image_and_sampler_usage()
void Compiler::analyze_image_and_sampler_usage () protected inherited
References spirv_cross::Compiler::comparison_images, spirv_cross::Compiler::CombinedImageSamplerUsageHandler::comparison_images, spirv_cross::Compiler::comparison_samplers, spirv_cross::Compiler::CombinedImageSamplerUsageHandler::comparison_samplers, spirv_cross::Compiler::entry_point, spirv_cross::Compiler::need_subpass_input, spirv_cross::Compiler::CombinedImageSamplerUsageHandler::need_subpass_input, and spirv_cross::Compiler::traverse_all_reachable_opcodes().
Referenced by compile().
make_constant_null()
void Compiler::make_constant_null (uint32_t id, uint32_t type) protected inherited
References spirv_cross::Compiler::increase_bound_by(), and SPIRV_CROSS_THROW.
Referenced by spirv_cross::Compiler::parse().
instruction_to_result_type()
bool Compiler::instruction_to_result_type (uint32_t & result_type, uint32_t & result_id, spv::Op op, const uint32_t * args, uint32_t length) protected inherited
References spv::OpAtomicFlagClear, spv::OpAtomicStore, spv::OpCaptureEventProfilingInfo, spv::OpCommitReadPipe, spv::OpCommitWritePipe, spv::OpControlBarrier, spv::OpCopyMemory, spv::OpCopyMemorySized, spv::OpEmitStreamVertex, spv::OpEndStreamPrimitive, spv::OpGroupCommitReadPipe, spv::OpGroupCommitWritePipe, spv::OpGroupWaitEvents, spv::OpImageWrite, spv::OpMemoryBarrier, spv::OpReleaseEvent, spv::OpRetainEvent, spv::OpSetUserEventStatus, and spv::OpStore.
Member Data Documentation
function_global_vars
std::unordered_map<uint32_t, std::set<uint32_t> > spirv_cross::CompilerMSL::function_global_vars protected
Referenced by extract_global_variables_from_function().
builtin_frag_coord_id
uint32_t spirv_cross::CompilerMSL::builtin_frag_coord_id = 0 protected
Referenced by build_implicit_builtins(), and extract_global_variables_from_function().
msl_options
Options spirv_cross::CompilerMSL::msl_options protected
Referenced by compile(), get_msl_options(), set_msl_options(), and SPIRV_CROSS_DEPRECATED().
spv_function_implementations
std::set<SPVFuncImpl> spirv_cross::CompilerMSL::spv_function_implementations protected
Referenced by emit_custom_functions(), and preprocess_op_codes().
vtx_attrs_by_location
std::unordered_map<uint32_t, MSLVertexAttr *> spirv_cross::CompilerMSL::vtx_attrs_by_location protected
Referenced by add_input_buffer_block_member(), CompilerMSL(), and mark_location_as_used_by_shader().
non_stage_in_input_var_ids
std::map<uint32_t, uint32_t> spirv_cross::CompilerMSL::non_stage_in_input_var_ids protected
Referenced by compile(), emit_resources(), and get_input_buffer_block_var_id().
struct_member_padding
std::unordered_map<MSLStructMemberKey, uint32_t> spirv_cross::CompilerMSL::struct_member_padding protected
Referenced by align_struct(), and compile().
pragma_lines
std::set<std::string> spirv_cross::CompilerMSL::pragma_lines protected
Referenced by add_pragma_line(), and emit_header().
typedef_lines
std::set<std::string> spirv_cross::CompilerMSL::typedef_lines protected
Referenced by add_typedef_line(), and emit_header().
resource_bindings
std::vector<MSLResourceBinding *> spirv_cross::CompilerMSL::resource_bindings protected
Referenced by CompilerMSL().
next_metal_resource_index
MSLResourceBinding spirv_cross::CompilerMSL::next_metal_resource_index protected
Referenced by compile().
stage_in_var_id
uint32_t spirv_cross::CompilerMSL::stage_in_var_id = 0 protected
Referenced by compile(), and emit_resources().
stage_out_var_id
uint32_t spirv_cross::CompilerMSL::stage_out_var_id = 0 protected
Referenced by compile(), and emit_resources().
stage_uniforms_var_id
uint32_t spirv_cross::CompilerMSL::stage_uniforms_var_id = 0 protected
Referenced by compile(), and emit_resources().
needs_vertex_idx_arg
bool spirv_cross::CompilerMSL::needs_vertex_idx_arg = false protected
Referenced by add_input_buffer_block_member().
needs_instance_idx_arg
bool spirv_cross::CompilerMSL::needs_instance_idx_arg = false protected
Referenced by add_input_buffer_block_member().
qual_pos_var_name
std::string spirv_cross::CompilerMSL::qual_pos_var_name protected
Referenced by add_interface_block(), and compile().
stage_in_var_name
std::string spirv_cross::CompilerMSL::stage_in_var_name = "in" protected
Referenced by add_interface_block(), and get_input_buffer_block_var_id().
stage_out_var_name
std::string spirv_cross::CompilerMSL::stage_out_var_name = "out" protected
Referenced by add_interface_block().
stage_uniform_var_name
std::string spirv_cross::CompilerMSL::stage_uniform_var_name = "uniforms" protected
Referenced by add_interface_block().
sampler_name_suffix
std::string spirv_cross::CompilerMSL::sampler_name_suffix = "Smplr" protected
previous_instruction_opcode
spv::Op spirv_cross::CompilerMSL::previous_instruction_opcode = spv::OpNop protected
current_emitting_block
SPIRBlock* spirv_cross::CompilerGLSL::current_emitting_block = nullptr protected inherited
buffer
std::unique_ptr<std::ostringstream> spirv_cross::CompilerGLSL::buffer protected inherited
Referenced by compile(), and spirv_cross::CompilerGLSL::statement().
redirect_statement
std::vector<std::string>* spirv_cross::CompilerGLSL::redirect_statement = nullptr protected inherited
Referenced by spirv_cross::CompilerGLSL::statement().
current_continue_block
const SPIRBlock* spirv_cross::CompilerGLSL::current_continue_block = nullptr protected inherited
options
Options spirv_cross::CompilerGLSL::options protected inherited
Referenced by compile(), spirv_cross::CompilerGLSL::get_common_options(), spirv_cross::CompilerGLSL::is_legacy(), spirv_cross::CompilerGLSL::is_legacy_desktop(), spirv_cross::CompilerGLSL::is_legacy_es(), spirv_cross::CompilerGLSL::set_common_options(), and spirv_cross::CompilerGLSL::SPIRV_CROSS_DEPRECATED().
local_variable_names
std::unordered_set<std::string> spirv_cross::CompilerGLSL::local_variable_names protected inherited
resource_names
std::unordered_set<std::string> spirv_cross::CompilerGLSL::resource_names protected inherited
function_overloads
std::unordered_map<std::string, std::unordered_set<uint64_t> > spirv_cross::CompilerGLSL::function_overloads protected inherited
processing_entry_point
bool spirv_cross::CompilerGLSL::processing_entry_point = false protected inherited
backend
struct spirv_cross::CompilerGLSL::BackendVariations spirv_cross::CompilerGLSL::backend protected inherited
Referenced by compile().
indent
uint32_t spirv_cross::CompilerGLSL::indent = 0 protected inherited
Referenced by spirv_cross::CompilerGLSL::statement(), and spirv_cross::CompilerGLSL::statement_no_indent().
emitted_functions
std::unordered_set<uint32_t> spirv_cross::CompilerGLSL::emitted_functions protected inherited
flattened_buffer_blocks
std::unordered_set<uint32_t> spirv_cross::CompilerGLSL::flattened_buffer_blocks protected inherited
flattened_structs
std::unordered_set<uint32_t> spirv_cross::CompilerGLSL::flattened_structs protected inherited
expression_usage_counts
std::unordered_map<uint32_t, uint32_t> spirv_cross::CompilerGLSL::expression_usage_counts protected inherited
forced_extensions
std::vector<std::string> spirv_cross::CompilerGLSL::forced_extensions protected inherited
header_lines
std::vector<std::string> spirv_cross::CompilerGLSL::header_lines protected inherited
Referenced by emit_header().
statement_count
uint32_t spirv_cross::CompilerGLSL::statement_count protected inherited
Referenced by spirv_cross::CompilerGLSL::statement(), and spirv_cross::CompilerGLSL::statement_inner().
pls_inputs
std::vector<PlsRemap> spirv_cross::CompilerGLSL::pls_inputs protected inherited
Referenced by spirv_cross::CompilerGLSL::remap_pixel_local_storage().
pls_outputs
std::vector<PlsRemap> spirv_cross::CompilerGLSL::pls_outputs protected inherited
Referenced by spirv_cross::CompilerGLSL::remap_pixel_local_storage().
get_entry_point
SPIREntryPoint & Compiler::get_entry_point inherited
get_entry_points_and_stages
vector< EntryPoint > Compiler::get_entry_points_and_stages inherited
spirv
std::vector<uint32_t> spirv_cross::Compiler::spirv protected inherited
Referenced by extract_string(), spirv_cross::Compiler::parse(), and spirv_cross::Compiler::stream().
inst
std::vector<Instruction> spirv_cross::Compiler::inst protected inherited
Referenced by spirv_cross::Compiler::parse().
ids
std::vector<Variant> spirv_cross::Compiler::ids protected inherited
Referenced by add_interface_block(), spirv_cross::Compiler::build_combined_image_samplers(), build_implicit_builtins(), declare_constant_arrays(), declare_undefined_values(), emit_resources(), spirv_cross::Compiler::expression_type_id(), extract_global_variables_from_functions(), spirv_cross::Compiler::get(), spirv_cross::Compiler::get_current_id_bound(), spirv_cross::Compiler::get_specialization_constants(), spirv_cross::Compiler::increase_bound_by(), spirv_cross::Compiler::is_immutable(), mark_packable_structs(), spirv_cross::Compiler::mark_used_as_array_length(), spirv_cross::Compiler::maybe_get(), spirv_cross::Compiler::parse(), resolve_specialized_array_lengths(), spirv_cross::Compiler::set(), and spirv_cross::Compiler::to_name().
meta
std::vector<Meta> spirv_cross::Compiler::meta protected inherited
Referenced by add_interface_block(), align_struct(), spirv_cross::Compiler::buffer_get_hlsl_counter_buffer(), spirv_cross::Compiler::buffer_is_hlsl_counter_buffer(), build_implicit_builtins(), extract_global_variables_from_function(), spirv_cross::Compiler::get_binary_offset_for_decoration(), spirv_cross::Compiler::get_buffer_block_flags(), spirv_cross::Compiler::get_decoration(), spirv_cross::Compiler::get_decoration_bitset(), spirv_cross::Compiler::get_member_decoration(), spirv_cross::Compiler::get_member_decoration_bitset(), spirv_cross::Compiler::get_member_name(), spirv_cross::Compiler::get_member_qualified_name(), spirv_cross::Compiler::get_name(), spirv_cross::Compiler::get_remapped_declared_block_name(), spirv_cross::Compiler::increase_bound_by(), spirv_cross::Compiler::is_builtin_variable(), spirv_cross::Compiler::is_member_builtin(), move_to_input_buffer(), spirv_cross::Compiler::parse(), spirv_cross::Compiler::set_decoration(), spirv_cross::Compiler::set_member_decoration(), spirv_cross::Compiler::set_member_name(), spirv_cross::Compiler::set_member_qualified_name(), spirv_cross::Compiler::set_name(), spirv_cross::Compiler::to_name(), spirv_cross::Compiler::type_struct_member_array_stride(), spirv_cross::Compiler::type_struct_member_matrix_stride(), spirv_cross::Compiler::type_struct_member_offset(), spirv_cross::Compiler::unset_decoration(), spirv_cross::Compiler::unset_member_decoration(), and spirv_cross::Compiler::variable_storage_is_aliased().
current_function
SPIRFunction* spirv_cross::Compiler::current_function = nullptr protected inherited
Referenced by spirv_cross::Compiler::flush_all_active_variables(), and spirv_cross::Compiler::parse().
current_block
SPIRBlock* spirv_cross::Compiler::current_block = nullptr protected inherited
Referenced by spirv_cross::Compiler::analyze_variable_scope(), and spirv_cross::Compiler::parse().
global_variables
std::vector<uint32_t> spirv_cross::Compiler::global_variables protected inherited
Referenced by spirv_cross::Compiler::flush_all_active_variables(), spirv_cross::Compiler::flush_all_atomic_capable_variables(), localize_global_variables(), and spirv_cross::Compiler::parse().
aliased_variables
std::vector<uint32_t> spirv_cross::Compiler::aliased_variables protected inherited
Referenced by spirv_cross::Compiler::flush_all_aliased_variables(), and spirv_cross::Compiler::parse().
active_interface_variables
std::unordered_set<uint32_t> spirv_cross::Compiler::active_interface_variables protected inherited
Referenced by add_interface_block(), spirv_cross::Compiler::is_hidden_variable(), and spirv_cross::Compiler::set_enabled_interface_variables().
check_active_interface_variables
bool spirv_cross::Compiler::check_active_interface_variables = false protected inherited
Referenced by spirv_cross::Compiler::is_hidden_variable(), and spirv_cross::Compiler::set_enabled_interface_variables().
entry_point
uint32_t spirv_cross::Compiler::entry_point = 0 protected inherited
Referenced by add_interface_block(), spirv_cross::Compiler::analyze_image_and_sampler_usage(), spirv_cross::Compiler::build_combined_image_samplers(), spirv_cross::Compiler::build_dummy_sampler_for_combined_images(), compile(), extract_global_variables_from_function(), extract_global_variables_from_functions(), spirv_cross::Compiler::get_active_buffer_ranges(), spirv_cross::Compiler::get_active_interface_variables(), localize_global_variables(), spirv_cross::Compiler::parse(), preprocess_op_codes(), spirv_cross::Compiler::set_entry_point(), and spirv_cross::Compiler::update_active_builtins().
entry_points
std::unordered_map<uint32_t, SPIREntryPoint> spirv_cross::Compiler::entry_points protected inherited
Referenced by spirv_cross::Compiler::get_entry_points(), spirv_cross::Compiler::interface_variable_exists_in_entry_point(), and spirv_cross::Compiler::parse().
source
struct spirv_cross::Compiler::Source spirv_cross::Compiler::source protected inherited
Referenced by spirv_cross::Compiler::parse(), and spirv_cross::Compiler::set_name().
loop_blocks
std::unordered_set<uint32_t> spirv_cross::Compiler::loop_blocks protected inherited
Referenced by spirv_cross::Compiler::analyze_variable_scope(), and spirv_cross::Compiler::parse().
continue_blocks
std::unordered_set<uint32_t> spirv_cross::Compiler::continue_blocks protected inherited
Referenced by spirv_cross::Compiler::is_continue(), and spirv_cross::Compiler::parse().
loop_merge_targets
std::unordered_set<uint32_t> spirv_cross::Compiler::loop_merge_targets protected inherited
Referenced by spirv_cross::Compiler::is_break(), spirv_cross::Compiler::is_loop_break(), and spirv_cross::Compiler::parse().
selection_merge_targets
std::unordered_set<uint32_t> spirv_cross::Compiler::selection_merge_targets protected inherited
Referenced by spirv_cross::Compiler::is_conditional(), and spirv_cross::Compiler::parse().
multiselect_merge_targets
std::unordered_set<uint32_t> spirv_cross::Compiler::multiselect_merge_targets protected inherited
Referenced by spirv_cross::Compiler::is_break(), spirv_cross::Compiler::is_conditional(), and spirv_cross::Compiler::parse().
continue_block_to_loop_header
std::unordered_map<uint32_t, uint32_t> spirv_cross::Compiler::continue_block_to_loop_header protected inherited
Referenced by spirv_cross::Compiler::analyze_variable_scope(), and spirv_cross::Compiler::parse().
invalid_expressions
std::unordered_set<uint32_t> spirv_cross::Compiler::invalid_expressions protected inherited
Referenced by spirv_cross::Compiler::flush_control_dependent_expressions(), and spirv_cross::Compiler::flush_dependees().
force_recompile
bool spirv_cross::Compiler::force_recompile = false protected inherited
Referenced by add_pragma_line(), add_typedef_line(), compile(), spirv_cross::Compiler::register_write(), and spirv_cross::CompilerGLSL::statement().
combined_image_samplers
std::vector<CombinedImageSampler> spirv_cross::Compiler::combined_image_samplers protected inherited
Referenced by spirv_cross::Compiler::build_combined_image_samplers(), spirv_cross::Compiler::get_combined_image_samplers(), and spirv_cross::Compiler::is_hidden_variable().
global_struct_cache
std::vector<uint32_t> spirv_cross::Compiler::global_struct_cache protected inherited
Referenced by spirv_cross::Compiler::parse().
variable_remap_callback
VariableTypeRemapCallback spirv_cross::Compiler::variable_remap_callback protected inherited
Referenced by spirv_cross::Compiler::remap_variable_type_name(), and spirv_cross::Compiler::set_variable_type_remap_callback().
forced_temporaries
std::unordered_set<uint32_t> spirv_cross::Compiler::forced_temporaries protected inherited
Referenced by spirv_cross::Compiler::analyze_variable_scope(), and spirv_cross::Compiler::inherit_expression_dependencies().
forwarded_temporaries
std::unordered_set<uint32_t> spirv_cross::Compiler::forwarded_temporaries protected inherited
Referenced by spirv_cross::Compiler::inherit_expression_dependencies().
hoisted_temporaries
std::unordered_set<uint32_t> spirv_cross::Compiler::hoisted_temporaries protected inherited
Referenced by spirv_cross::Compiler::analyze_variable_scope().
active_input_builtins
Bitset spirv_cross::Compiler::active_input_builtins protected inherited
Referenced by spirv_cross::Compiler::has_active_builtin(), and spirv_cross::Compiler::update_active_builtins().
active_output_builtins
Bitset spirv_cross::Compiler::active_output_builtins protected inherited
Referenced by spirv_cross::Compiler::has_active_builtin(), and spirv_cross::Compiler::update_active_builtins().
clip_distance_count
uint32_t spirv_cross::Compiler::clip_distance_count = 0 protected inherited
Referenced by spirv_cross::Compiler::update_active_builtins().
cull_distance_count
uint32_t spirv_cross::Compiler::cull_distance_count = 0 protected inherited
Referenced by spirv_cross::Compiler::update_active_builtins().
position_invariant
bool spirv_cross::Compiler::position_invariant = false protected inherited
comparison_samplers
std::unordered_set<uint32_t> spirv_cross::Compiler::comparison_samplers protected inherited
Referenced by spirv_cross::Compiler::CombinedImageSamplerUsageHandler::add_hierarchy_to_comparison_samplers(), and spirv_cross::Compiler::analyze_image_and_sampler_usage().
comparison_images
std::unordered_set<uint32_t> spirv_cross::Compiler::comparison_images protected inherited
Referenced by spirv_cross::Compiler::CombinedImageSamplerUsageHandler::add_hierarchy_to_comparison_images(), and spirv_cross::Compiler::analyze_image_and_sampler_usage().
need_subpass_input
bool spirv_cross::Compiler::need_subpass_input = false protected inherited
Referenced by spirv_cross::Compiler::analyze_image_and_sampler_usage(), build_implicit_builtins(), and spirv_cross::Compiler::CombinedImageSamplerUsageHandler::handle().
dummy_sampler_id
uint32_t spirv_cross::Compiler::dummy_sampler_id = 0 protected inherited
Referenced by spirv_cross::Compiler::build_dummy_sampler_for_combined_images(), and spirv_cross::Compiler::get_active_interface_variables().
declared_capabilities
std::vector<spv::Capability> spirv_cross::Compiler::declared_capabilities protected inherited
Referenced by spirv_cross::Compiler::get_declared_capabilities(), and spirv_cross::Compiler::parse().
declared_extensions
std::vector<std::string> spirv_cross::Compiler::declared_extensions protected inherited
Referenced by spirv_cross::Compiler::get_declared_extensions(), and spirv_cross::Compiler::parse().
declared_block_names
std::unordered_map<uint32_t, std::string> spirv_cross::Compiler::declared_block_names protected inherited
Referenced by spirv_cross::Compiler::get_remapped_declared_block_name().
The documentation for this class was generated from the following files:
MSL.h
MSL.cpp