Aurora Framework: long_term.c File Reference
long_term.c File Reference
Macros
#define STEP(K, a, b, c, d, e, f, g, h)
#define STEP(K, a, b, c, d, e, f, g, h)
#define STEP(BP)
#define STEP_A(K) STEP (K, a, b, c, d, e, f, g, h)
#define STEP_A(K) STEP (K, a, b, c, d, e, f, g, h)
#define STEP_B(K) STEP (K, b, c, d, e, f, g, h, a)
#define STEP_B(K) STEP (K, b, c, d, e, f, g, h, a)
#define STEP_C(K) STEP (K, c, d, e, f, g, h, a, b)
#define STEP_C(K) STEP (K, c, d, e, f, g, h, a, b)
#define STEP_D(K) STEP (K, d, e, f, g, h, a, b, c)
#define STEP_D(K) STEP (K, d, e, f, g, h, a, b, c)
#define STEP_E(K) STEP (K, e, f, g, h, a, b, c, d)
#define STEP_E(K) STEP (K, e, f, g, h, a, b, c, d)
#define STEP_F(K) STEP (K, f, g, h, a, b, c, d, e)
#define STEP_F(K) STEP (K, f, g, h, a, b, c, d, e)
#define STEP_G(K) STEP (K, g, h, a, b, c, d, e, f)
#define STEP_G(K) STEP (K, g, h, a, b, c, d, e, f)
#define STEP_H(K) STEP (K, h, a, b, c, d, e, f, g)
#define STEP_H(K) STEP (K, h, a, b, c, d, e, f, g)
Functions
static void Calculation_of_the_LTP_parameters (register int16_t *din, register int16_t *dp, int16_t *bc_out, int16_t *Nc_out)
static void Fast_Calculation_of_the_LTP_parameters (register int16_t *din, register int16_t *dp, int16_t *bc_out, int16_t *Nc_out)
void Gsm_Long_Term_Predictor (struct gsm_state *S, int16_t *d, int16_t *dp, int16_t *e, int16_t *dpp, int16_t *Nc, int16_t *bc)
void Gsm_Long_Term_Synthesis_Filtering (struct gsm_state *S, int16_t Ncr, int16_t bcr, register int16_t *erp, register int16_t *drp)
static void Long_term_analysis_filtering (int16_t bc, int16_t Nc, register int16_t *dp, register int16_t *d, register int16_t *dpp, register int16_t *e)
Macro Definition Documentation
STEP [1/3]
#define STEP (K, a, b, c, d, e, f, g, h)
Value:
W = wt_float [K] ;      \
            E = W * a ; S8 += E ;       \
            E = W * b ; S7 += E ;       \
            E = W * c ; S6 += E ;       \
            E = W * d ; S5 += E ;       \
            E = W * e ; S4 += E ;       \
            E = W * f ; S3 += E ;       \
            E = W * g ; S2 += E ;       \
            E = W * h ; S1 += E ;       \
            a = lp [K] ;                \
            E = W * a ; S0 += E
Referenced by Long_term_analysis_filtering().
STEP_A [1/2]
#define STEP_A (K) STEP (K, a, b, c, d, e, f, g, h)
Referenced by Calculation_of_the_LTP_parameters(), and Fast_Calculation_of_the_LTP_parameters().
STEP_B [1/2]
#define STEP_B (K) STEP (K, b, c, d, e, f, g, h, a)
Referenced by Calculation_of_the_LTP_parameters(), and Fast_Calculation_of_the_LTP_parameters().
STEP_C [1/2]
#define STEP_C (K) STEP (K, c, d, e, f, g, h, a, b)
Referenced by Calculation_of_the_LTP_parameters(), and Fast_Calculation_of_the_LTP_parameters().
STEP_D [1/2]
#define STEP_D (K) STEP (K, d, e, f, g, h, a, b, c)
Referenced by Calculation_of_the_LTP_parameters(), and Fast_Calculation_of_the_LTP_parameters().
STEP_E [1/2]
#define STEP_E (K) STEP (K, e, f, g, h, a, b, c, d)
Referenced by Calculation_of_the_LTP_parameters(), and Fast_Calculation_of_the_LTP_parameters().
STEP_F [1/2]
#define STEP_F (K) STEP (K, f, g, h, a, b, c, d, e)
Referenced by Calculation_of_the_LTP_parameters(), and Fast_Calculation_of_the_LTP_parameters().
STEP_G [1/2]
#define STEP_G (K) STEP (K, g, h, a, b, c, d, e, f)
Referenced by Calculation_of_the_LTP_parameters(), and Fast_Calculation_of_the_LTP_parameters().
STEP_H [1/2]
#define STEP_H (K) STEP (K, h, a, b, c, d, e, f, g)
Referenced by Calculation_of_the_LTP_parameters(), and Fast_Calculation_of_the_LTP_parameters().
STEP [2/3]
#define STEP (K, a, b, c, d, e, f, g, h)
Value:
W = wt_float [K] ;      \
            E = W * a ; S8 += E ;       \
            E = W * b ; S7 += E ;       \
            E = W * c ; S6 += E ;       \
            E = W * d ; S5 += E ;       \
            E = W * e ; S4 += E ;       \
            E = W * f ; S3 += E ;       \
            E = W * g ; S2 += E ;       \
            E = W * h ; S1 += E ;       \
            a = lp [K] ;                \
            E = W * a ; S0 += E
STEP_A [2/2]
#define STEP_A (K) STEP (K, a, b, c, d, e, f, g, h)
STEP_B [2/2]
#define STEP_B (K) STEP (K, b, c, d, e, f, g, h, a)
STEP_C [2/2]
#define STEP_C (K) STEP (K, c, d, e, f, g, h, a, b)
STEP_D [2/2]
#define STEP_D (K) STEP (K, d, e, f, g, h, a, b, c)
STEP_E [2/2]
#define STEP_E (K) STEP (K, e, f, g, h, a, b, c, d)
STEP_F [2/2]
#define STEP_F (K) STEP (K, f, g, h, a, b, c, d, e)
STEP_G [2/2]
#define STEP_G (K) STEP (K, g, h, a, b, c, d, e, f)
STEP_H [2/2]
#define STEP_H (K) STEP (K, h, a, b, c, d, e, f, g)
STEP [3/3]
#define STEP (BP)
Value:
for (k = 0 ; k <= 39 ; k++)     \
    {   dpp [k] = GSM_MULT_R (BP, dp [k - Nc]) ;    \
        e [k]   = GSM_SUB (d [k], dpp [k]) ;    \
        }
Function Documentation
Calculation_of_the_LTP_parameters()
static void Calculation_of_the_LTP_parameters (register int16_t * din, register int16_t * dp, int16_t * bc_out, int16_t * Nc_out) static
References a, GSM_ABS(), gsm_DLB, gsm_mult(), gsm_norm(), SASR_L(), SASR_W(), STEP_A, STEP_B, STEP_C, STEP_D, STEP_E, STEP_F, STEP_G, and STEP_H.
Referenced by Gsm_Long_Term_Predictor().
Fast_Calculation_of_the_LTP_parameters()
static void Fast_Calculation_of_the_LTP_parameters (register int16_t * din, register int16_t * dp, int16_t * bc_out, int16_t * Nc_out) static
References a, gsm_DLB, STEP_A, STEP_B, STEP_C, STEP_D, STEP_E, STEP_F, STEP_G, and STEP_H.
Referenced by Gsm_Long_Term_Predictor().
Long_term_analysis_filtering()
static void Long_term_analysis_filtering (int16_t bc, int16_t Nc, register int16_t * dp, register int16_t * d, register int16_t * dpp, register int16_t * e) static
References STEP.
Referenced by Gsm_Long_Term_Predictor().
Gsm_Long_Term_Predictor()
void Gsm_Long_Term_Predictor (struct gsm_state * S, int16_t * d, int16_t * dp, int16_t * e, int16_t * dpp, int16_t * Nc, int16_t * bc)
References Calculation_of_the_LTP_parameters(), Fast_Calculation_of_the_LTP_parameters(), and Long_term_analysis_filtering().
Referenced by Gsm_Coder().
Gsm_Long_Term_Synthesis_Filtering()
void Gsm_Long_Term_Synthesis_Filtering (struct gsm_state * S, int16_t Ncr, int16_t bcr, register int16_t * erp, register int16_t * drp)
References GSM_ADD(), GSM_MULT_R(), gsm_QLB, and MIN_WORD.