Aurora Framework: paf.c File Reference
paf.c File Reference
Classes
struct PAF24_PRIVATE
struct PAF_FMT
Macros
#define FAP_MARKER (MAKE_MARKER ('f', 'a', 'p', ' '))
#define PAF24_BLOCK_SIZE 32
#define PAF24_SAMPLES_PER_BLOCK 10
#define PAF_HEADER_LENGTH 2048
#define PAF_MARKER (MAKE_MARKER (' ', 'p', 'a', 'f'))
Enumerations
enum { PAF_PCM_16 = 0, PAF_PCM_24 = 1, PAF_PCM_S8 = 2 }
Functions
static int paf24_close (SF_PRIVATE *psf)
static int paf24_init (SF_PRIVATE *psf)
static int paf24_read (SF_PRIVATE *psf, PAF24_PRIVATE *ppaf24, int *ptr, int len)
static int paf24_read_block (SF_PRIVATE *psf, PAF24_PRIVATE *ppaf24)
static sf_count_t paf24_read_d (SF_PRIVATE *psf, double *ptr, sf_count_t len)
static sf_count_t paf24_read_f (SF_PRIVATE *psf, float *ptr, sf_count_t len)
static sf_count_t paf24_read_i (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static sf_count_t paf24_read_s (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static sf_count_t paf24_seek (SF_PRIVATE *psf, int mode, sf_count_t offset)
static int paf24_write (SF_PRIVATE *psf, PAF24_PRIVATE *ppaf24, const int *ptr, int len)
static int paf24_write_block (SF_PRIVATE *psf, PAF24_PRIVATE *ppaf24)
static sf_count_t paf24_write_d (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
static sf_count_t paf24_write_f (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
static sf_count_t paf24_write_i (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
static sf_count_t paf24_write_s (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
int paf_open (SF_PRIVATE *psf)
static int paf_read_header (SF_PRIVATE *psf)
static int paf_write_header (SF_PRIVATE *psf, int calc_length)
static int paf_write_header (SF_PRIVATE *psf, int UNUSED(calc_length))
Macro Definition Documentation
FAP_MARKER
#define FAP_MARKER (MAKE_MARKER ('f', 'a', 'p', ' '))
Referenced by paf_read_header(), and paf_write_header().
PAF_MARKER
#define PAF_MARKER (MAKE_MARKER (' ', 'p', 'a', 'f'))
Referenced by paf_read_header(), and paf_write_header().
PAF_HEADER_LENGTH
#define PAF_HEADER_LENGTH 2048
Referenced by paf_open(), paf_read_header(), and paf_write_header().
PAF24_SAMPLES_PER_BLOCK
#define PAF24_SAMPLES_PER_BLOCK 10
Referenced by paf24_init(), paf24_read(), paf24_read_block(), paf24_seek(), paf24_write(), paf24_write_block(), and paf_read_header().
PAF24_BLOCK_SIZE
#define PAF24_BLOCK_SIZE 32
Referenced by paf24_init(), paf24_read_block(), paf24_write_block(), and paf_read_header().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PAF_PCM_16
PAF_PCM_24
PAF_PCM_S8
Function Documentation
paf24_init()
static int paf24_init (SF_PRIVATE * psf) static
References PAF24_PRIVATE::block, PAF24_PRIVATE::blocksize, PAF24_PRIVATE::channels, sf_private_tag::codec_data, sf_private_tag::container_close, PAF24_PRIVATE::data, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::file, sf_private_tag::filelength, sf_private_tag::last_op, PAF24_PRIVATE::max_blocks, PSF_FILE::mode, PAF24_BLOCK_SIZE, paf24_close(), paf24_read_block(), paf24_read_d(), paf24_read_f(), paf24_read_i(), paf24_read_s(), PAF24_SAMPLES_PER_BLOCK, paf24_seek(), paf24_write_d(), paf24_write_f(), paf24_write_i(), paf24_write_s(), psf_get_filelen(), psf_log_printf(), PAF24_PRIVATE::read_block, sf_private_tag::read_double, sf_private_tag::read_float, sf_private_tag::read_int, sf_private_tag::read_short, PAF24_PRIVATE::sample_count, PAF24_PRIVATE::samples, sf_private_tag::seek, sf_private_tag::sf, SFE_MALLOC_FAILED, PAF24_PRIVATE::write_block, sf_private_tag::write_double, sf_private_tag::write_float, sf_private_tag::write_int, and sf_private_tag::write_short.
Referenced by paf_open().
paf_read_header()
static int paf_read_header (SF_PRIVATE * psf) static
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, PAF_FMT::channels, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::endian, PAF_FMT::endianness, FAP_MARKER, sf_private_tag::filelength, PAF_FMT::format, memset(), PAF24_BLOCK_SIZE, PAF24_SAMPLES_PER_BLOCK, PAF_HEADER_LENGTH, PAF_MARKER, PAF_PCM_16, PAF_PCM_24, PAF_PCM_S8, psf_binheader_readf(), psf_log_printf(), PAF_FMT::samplerate, sf_private_tag::sf, SF_MAX_CHANNELS, SFE_PAF_BAD_CHANNELS, SFE_PAF_NO_MARKER, SFE_PAF_SHORT_HEADER, SFE_PAF_UNKNOWN_FORMAT, SFE_PAF_VERSION, PAF_FMT::source, and PAF_FMT::version.
Referenced by paf_open().
paf_write_header() [1/2]
static int paf_write_header (SF_PRIVATE * psf, int calc_length) static
Referenced by paf_open().
paf24_read_s()
static sf_count_t paf24_read_s (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, BUF_UNION::ibuf, NULL, and paf24_read().
Referenced by paf24_init().
paf24_read_i()
static sf_count_t paf24_read_i (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
References sf_private_tag::codec_data, NULL, and paf24_read().
Referenced by paf24_init().
paf24_read_f()
static sf_count_t paf24_read_f (SF_PRIVATE * psf, float * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, BUF_UNION::ibuf, sf_private_tag::norm_float, NULL, and paf24_read().
Referenced by paf24_init().
paf24_read_d()
static sf_count_t paf24_read_d (SF_PRIVATE * psf, double * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, BUF_UNION::ibuf, sf_private_tag::norm_double, NULL, and paf24_read().
Referenced by paf24_init().
paf24_write_s()
static sf_count_t paf24_write_s (SF_PRIVATE * psf, const short * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, BUF_UNION::ibuf, NULL, and paf24_write().
Referenced by paf24_init().
paf24_write_i()
static sf_count_t paf24_write_i (SF_PRIVATE * psf, const int * ptr, sf_count_t len) static
References sf_private_tag::codec_data, NULL, and paf24_write().
Referenced by paf24_init().
paf24_write_f()
static sf_count_t paf24_write_f (SF_PRIVATE * psf, const float * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, BUF_UNION::ibuf, sf_private_tag::norm_float, NULL, and paf24_write().
Referenced by paf24_init().
paf24_write_d()
static sf_count_t paf24_write_d (SF_PRIVATE * psf, const double * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, BUF_UNION::ibuf, sf_private_tag::norm_double, NULL, and paf24_write().
Referenced by paf24_init().
paf24_seek()
static sf_count_t paf24_seek (SF_PRIVATE * psf, int mode, sf_count_t offset) static
References PAF24_PRIVATE::blocksize, sf_private_tag::codec_data, sf_private_tag::dataoffset, sf_private_tag::error, sf_private_tag::last_op, mode(), NULL, paf24_read_block(), PAF24_SAMPLES_PER_BLOCK, paf24_write_block(), psf_fseek(), PSF_SEEK_ERROR, PAF24_PRIVATE::read_block, PAF24_PRIVATE::read_count, PAF24_PRIVATE::sample_count, SFE_BAD_SEEK, SFE_INTERNAL, PAF24_PRIVATE::write_block, and PAF24_PRIVATE::write_count.
Referenced by paf24_init().
paf_open()
int paf_open (SF_PRIVATE * psf)
References sf_private_tag::bytewidth, sf_private_tag::dataoffset, sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, PSF_FILE::mode, paf24_init(), PAF_HEADER_LENGTH, paf_read_header(), paf_write_header(), pcm_init(), sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SF_ENDIAN, SFE_BAD_OPEN_FORMAT, SFE_PAF_UNKNOWN_FORMAT, and sf_private_tag::write_header.
Referenced by psf_open_file().
paf_write_header() [2/2]
static int paf_write_header (SF_PRIVATE * psf, int UNUSEDcalc_length) static
References BHW4, BHWm, BHWz, sf_private_tag::dataoffset, sf_private_tag::endian, sf_private_tag::error, FAP_MARKER, sf_private_tag::header, sf_private_tag::indx, PAF_HEADER_LENGTH, PAF_MARKER, PAF_PCM_16, PAF_PCM_24, PAF_PCM_S8, psf_binheader_writef(), psf_ftell(), psf_fwrite(), sf_private_tag::ptr, sf_private_tag::sf, SF_CODEC, and SFE_PAF_UNKNOWN_FORMAT.
paf24_read_block()
static int paf24_read_block (SF_PRIVATE * psf, PAF24_PRIVATE * ppaf24) static
References PAF24_PRIVATE::block, PAF24_PRIVATE::blocksize, PAF24_PRIVATE::channels, sf_private_tag::endian, endswap_int_array(), memset(), PAF24_BLOCK_SIZE, PAF24_SAMPLES_PER_BLOCK, psf_fread(), psf_log_printf(), PAF24_PRIVATE::read_block, PAF24_PRIVATE::read_count, PAF24_PRIVATE::sample_count, and PAF24_PRIVATE::samples.
Referenced by paf24_init(), paf24_read(), and paf24_seek().
paf24_write_block()
static int paf24_write_block (SF_PRIVATE * psf, PAF24_PRIVATE * ppaf24) static
References PAF24_PRIVATE::block, PAF24_PRIVATE::blocksize, PAF24_PRIVATE::channels, sf_private_tag::endian, endswap_int_array(), PAF24_BLOCK_SIZE, PAF24_SAMPLES_PER_BLOCK, psf_fwrite(), psf_log_printf(), PAF24_PRIVATE::sample_count, PAF24_PRIVATE::samples, PAF24_PRIVATE::write_block, and PAF24_PRIVATE::write_count.
Referenced by paf24_close(), paf24_seek(), and paf24_write().
paf24_close()
static int paf24_close (SF_PRIVATE * psf) static
References sf_private_tag::codec_data, sf_private_tag::file, PSF_FILE::mode, NULL, paf24_write_block(), and PAF24_PRIVATE::write_count.
Referenced by paf24_init().
paf24_read()
static int paf24_read (SF_PRIVATE * psf, PAF24_PRIVATE * ppaf24, int * ptr, int len) static
References PAF24_PRIVATE::channels, memcpy(), memset(), paf24_read_block(), PAF24_SAMPLES_PER_BLOCK, PAF24_PRIVATE::read_block, PAF24_PRIVATE::read_count, PAF24_PRIVATE::sample_count, and PAF24_PRIVATE::samples.
Referenced by paf24_read_d(), paf24_read_f(), paf24_read_i(), and paf24_read_s().
paf24_write()
static int paf24_write (SF_PRIVATE * psf, PAF24_PRIVATE * ppaf24, const int * ptr, int len) static
References PAF24_PRIVATE::channels, memcpy(), PAF24_SAMPLES_PER_BLOCK, paf24_write_block(), PAF24_PRIVATE::samples, and PAF24_PRIVATE::write_count.
Referenced by paf24_write_d(), paf24_write_f(), paf24_write_i(), and paf24_write_s().