Aurora Framework: dplib.h File Reference
dplib.h File Reference
Macros
#define AINIT 38
#define BINIT (-29)
#define CINIT (-2)
#define DENSHIFT_DEFAULT 9
#define DENSHIFT_MAX 15
#define NUMCOEPAIRS 16
Functions
void copy_coefs (const int16_t *srcCoefs, int16_t *dstCoefs, int32_t numPairs)
void init_coefs (int16_t *coefs, uint32_t denshift, int32_t numPairs)
void pc_block (int32_t *in, int32_t *pc, int32_t num, int16_t *coefs, int32_t numactive, uint32_t chanbits, uint32_t denshift)
void unpc_block (const int32_t *pc, int32_t *out, int32_t num, int16_t *coefs, int32_t numactive, uint32_t chanbits, uint32_t denshift)
Macro Definition Documentation
DENSHIFT_MAX
#define DENSHIFT_MAX 15
DENSHIFT_DEFAULT
#define DENSHIFT_DEFAULT 9
Referenced by alac_encoder_init(), EncodeMono(), EncodeStereo(), and EncodeStereoFast().
AINIT
#define AINIT 38
Referenced by init_coefs().
BINIT
#define BINIT (-29)
Referenced by init_coefs().
CINIT
#define CINIT (-2)
Referenced by init_coefs().
NUMCOEPAIRS
#define NUMCOEPAIRS 16
Function Documentation
init_coefs()
void init_coefs (int16_t * coefs, uint32_t denshift, int32_t numPairs)
References AINIT, BINIT, and CINIT.
Referenced by alac_encoder_init().
copy_coefs()
void copy_coefs (const int16_t * srcCoefs, int16_t * dstCoefs, int32_t numPairs)
pc_block()
void pc_block (int32_t * in, int32_t * pc, int32_t num, int16_t * coefs, int32_t numactive, uint32_t chanbits, uint32_t denshift)
References arith_shift_left(), LOOP_ALIGN, memcpy(), and sign_of_int().
Referenced by EncodeMono(), EncodeStereo(), and EncodeStereoFast().
unpc_block()
void unpc_block (const int32_t * pc, int32_t * out, int32_t num, int16_t * coefs, int32_t numactive, uint32_t chanbits, uint32_t denshift)
References arith_shift_left(), LOOP_ALIGN, memcpy(), and sign_of_int().
Referenced by alac_decode().