Aurora Framework: gsm610_priv.h File Reference
gsm610_priv.h File Reference
Classes
struct gsm_state
Macros
#define ALWAYS_INLINE
#define FAST
#define MAX_LONGWORD 2147483647
#define MAX_WORD 32767
#define MIN_LONGWORD (-2147483647 - 1)
#define MIN_WORD (-32767 - 1)
#define USE_FLOAT_MUL
#define WAV49
Typedefs
typedef struct gsm_state GSM_STATE
Functions
static int32_t ALWAYS_INLINE arith_shift_left (int32_t x, int shift)
static int32_t ALWAYS_INLINE arith_shift_right (int32_t x, int shift)
int16_t gsm_abs (int16_t a)
static int16_t GSM_ABS (int16_t a)
int16_t gsm_add (int16_t a, int16_t b)
static int32_t GSM_ADD (int16_t a, int16_t b)
int16_t gsm_asl (int16_t a, int n)
int16_t gsm_asr (int16_t a, int n)
void Gsm_Coder (struct gsm_state *S, int16_t *s, int16_t *LARc, int16_t *Nc, int16_t *bc, int16_t *Mc, int16_t *xmaxc, int16_t *xMc)
void gsm_debug_int16_t (char *name, int16_t)
void gsm_debug_int16_ts (char *name, int, int, int16_t *)
void gsm_debug_int32_t (char *name, int32_t)
void gsm_debug_int32_ts (char *name, int, int, int32_t *)
void Gsm_Decoder (struct gsm_state *S, int16_t *LARcr, int16_t *Ncr, int16_t *bcr, int16_t *Mcr, int16_t *xmaxcr, int16_t *xMcr, int16_t *s)
void Gsm_Decoding (struct gsm_state *S, int16_t xmaxcr, int16_t Mcr, int16_t *xMcr, int16_t *erp)
int16_t gsm_div (int16_t num, int16_t denum)
void Gsm_Encoding (struct gsm_state *S, int16_t *e, int16_t *ep, int16_t *xmaxc, int16_t *Mc, int16_t *xMc)
int32_t gsm_L_add (int32_t a, int32_t b)
static int32_t GSM_L_ADD (int32_t a, int32_t b)
int32_t gsm_L_asl (int32_t a, int n)
int32_t gsm_L_asr (int32_t a, int n)
int32_t gsm_L_mult (int16_t a, int16_t b)
static int32_t GSM_L_MULT (int16_t a, int16_t b)
int32_t gsm_L_sub (int32_t a, int32_t b)
void Gsm_Long_Term_Predictor (struct gsm_state *S, int16_t *d, int16_t *dp, int16_t *e, int16_t *dpp, int16_t *Nc, int16_t *bc)
void Gsm_Long_Term_Synthesis_Filtering (struct gsm_state *S, int16_t Ncr, int16_t bcr, int16_t *erp, int16_t *drp)
void Gsm_LPC_Analysis (struct gsm_state *S, int16_t *s, int16_t *LARc)
int16_t gsm_mult (int16_t a, int16_t b)
static int32_t GSM_MULT (int16_t a, int16_t b)
int16_t gsm_mult_r (int16_t a, int16_t b)
static int32_t GSM_MULT_R (int16_t a, int16_t b)
int16_t gsm_norm (int32_t a)
void Gsm_Preprocess (struct gsm_state *S, int16_t *s, int16_t *so)
void Gsm_RPE_Decoding (int16_t xmaxcr, int16_t Mcr, int16_t *xMcr, int16_t *erp)
void Gsm_RPE_Encoding (int16_t *e, int16_t *xmaxc, int16_t *Mc, int16_t *xMc)
void Gsm_Short_Term_Analysis_Filter (struct gsm_state *S, int16_t *LARc, int16_t *d)
void Gsm_Short_Term_Synthesis_Filter (struct gsm_state *S, int16_t *LARcr, int16_t *drp, int16_t *s)
int16_t gsm_sub (int16_t a, int16_t b)
static int32_t GSM_SUB (int16_t a, int16_t b)
void Gsm_Update_of_reconstructed_short_time_residual_signal (int16_t *dpp, int16_t *ep, int16_t *dp)
static int32_t SASL_L (int32_t x, int16_t by)
static int16_t SASL_W (int16_t x, int16_t by)
static int32_t SASR_L (int32_t x, int16_t by)
static int16_t SASR_W (int16_t x, int16_t by)
Variables
int16_t gsm_A [8]
int16_t gsm_B [8]
int16_t gsm_DLB [4]
int16_t gsm_FAC [8]
int16_t gsm_H [11]
int16_t gsm_INVA [8]
int16_t gsm_MAC [8]
int16_t gsm_MIC [8]
int16_t gsm_NRFAC [8]
int16_t gsm_QLB [4]
Macro Definition Documentation
USE_FLOAT_MUL
#define USE_FLOAT_MUL
FAST
#define FAST
WAV49
#define WAV49
MIN_WORD
#define MIN_WORD (-32767 - 1)
Referenced by gsm_abs(), GSM_ABS(), GSM_ADD(), gsm_L_mult(), Gsm_Long_Term_Synthesis_Filtering(), gsm_mult(), gsm_mult_r(), Gsm_Preprocess(), GSM_SUB(), LARp_to_rp(), Reflection_coefficients(), Short_term_synthesis_filtering(), Transformation_to_Log_Area_Ratios(), and Weighting_filter().
MAX_WORD
#define MAX_WORD 32767
Referenced by gsm_abs(), GSM_ABS(), GSM_ADD(), gsm_mult(), gsm_mult_r(), GSM_SUB(), LARp_to_rp(), Short_term_synthesis_filtering(), and Weighting_filter().
MIN_LONGWORD
#define MIN_LONGWORD (-2147483647 - 1)
Referenced by gsm_L_add(), GSM_L_ADD(), and gsm_L_sub().
MAX_LONGWORD
#define MAX_LONGWORD 2147483647
Referenced by Fast_Autocorrelation(), gsm_L_add(), GSM_L_ADD(), and gsm_L_sub().
ALWAYS_INLINE
#define ALWAYS_INLINE
Typedef Documentation
GSM_STATE
typedef struct gsm_state GSM_STATE
Function Documentation
SASR_W()
static int16_t SASR_W (int16_t x, int16_t by) inline static
Referenced by APCM_quantization(), APCM_quantization_xmaxc_to_exp_mant(), Calculation_of_the_LTP_parameters(), Coefficients_0_12(), Coefficients_13_26(), Coefficients_27_39(), gsm_asr(), and Gsm_Preprocess().
SASR_L()
static int32_t SASR_L (int32_t x, int16_t by) inline static
Referenced by Calculation_of_the_LTP_parameters(), gsm_L_asr(), gsm_mult(), Gsm_Preprocess(), Reflection_coefficients(), and Weighting_filter().
SASL_W()
static int16_t SASL_W (int16_t x, int16_t by) inline static
Referenced by Autocorrelation().
SASL_L()
static int32_t SASL_L (int32_t x, int16_t by) inline static
Referenced by Autocorrelation(), and Reflection_coefficients().
gsm_mult()
int16_t gsm_mult (int16_t a, int16_t b)
References a, MAX_WORD, MIN_WORD, and SASR_L().
Referenced by Calculation_of_the_LTP_parameters().
gsm_L_mult()
int32_t gsm_L_mult (int16_t a, int16_t b)
References a, and MIN_WORD.
gsm_mult_r()
int16_t gsm_mult_r (int16_t a, int16_t b)
References a, MAX_WORD, and MIN_WORD.
gsm_div()
int16_t gsm_div (int16_t num, int16_t denum)
Referenced by Reflection_coefficients().
gsm_add()
int16_t gsm_add (int16_t a, int16_t b)
References a, and saturate.
Referenced by APCM_quantization().
gsm_L_add()
int32_t gsm_L_add (int32_t a, int32_t b)
References a, MAX_LONGWORD, and MIN_LONGWORD.
gsm_sub()
int16_t gsm_sub (int16_t a, int16_t b)
References a, and saturate.
Referenced by APCM_inverse_quantization().
gsm_L_sub()
int32_t gsm_L_sub (int32_t a, int32_t b)
References a, MAX_LONGWORD, and MIN_LONGWORD.
gsm_abs()
int16_t gsm_abs (int16_t a)
References a, MAX_WORD, and MIN_WORD.
gsm_norm()
int16_t gsm_norm (int32_t a)
References a, and bitoff.
Referenced by Autocorrelation(), Calculation_of_the_LTP_parameters(), and Reflection_coefficients().
gsm_L_asl()
int32_t gsm_L_asl (int32_t a, int n)
References a, and gsm_L_asr().
gsm_asl()
int16_t gsm_asl (int16_t a, int n)
References a, and gsm_asr().
Referenced by APCM_inverse_quantization().
gsm_L_asr()
int32_t gsm_L_asr (int32_t a, int n)
References a, and SASR_L().
Referenced by gsm_L_asl().
gsm_asr()
int16_t gsm_asr (int16_t a, int n)
References a, and SASR_W().
Referenced by APCM_inverse_quantization(), and gsm_asl().
GSM_MULT_R()
static int32_t GSM_MULT_R (int16_t a, int16_t b) inline static
References a.
Referenced by APCM_inverse_quantization(), Gsm_Long_Term_Synthesis_Filtering(), Gsm_Preprocess(), Postprocessing(), Reflection_coefficients(), and Short_term_analysis_filtering().
GSM_MULT()
static int32_t GSM_MULT (int16_t a, int16_t b) inline static
References a.
Referenced by APCM_quantization().
GSM_L_MULT()
static int32_t GSM_L_MULT (int16_t a, int16_t b) inline static
References a.
GSM_L_ADD()
static int32_t GSM_L_ADD (int32_t a, int32_t b) inline static
References a, MAX_LONGWORD, and MIN_LONGWORD.
Referenced by Gsm_Preprocess().
GSM_ADD()
static int32_t GSM_ADD (int16_t a, int16_t b) inline static
References a, MAX_WORD, and MIN_WORD.
Referenced by APCM_inverse_quantization(), Coefficients_0_12(), Coefficients_13_26(), Coefficients_27_39(), Gsm_Coder(), Gsm_Long_Term_Synthesis_Filtering(), Gsm_Preprocess(), LARp_to_rp(), Postprocessing(), Reflection_coefficients(), Short_term_analysis_filtering(), and Short_term_synthesis_filtering().
GSM_SUB()
static int32_t GSM_SUB (int16_t a, int16_t b) inline static
References a, MAX_WORD, and MIN_WORD.
Referenced by Short_term_synthesis_filtering().
GSM_ABS()
static int16_t GSM_ABS (int16_t a) inline static
References a, MAX_WORD, and MIN_WORD.
Referenced by APCM_quantization(), Autocorrelation(), Calculation_of_the_LTP_parameters(), Reflection_coefficients(), and Transformation_to_Log_Area_Ratios().
Gsm_Coder()
void Gsm_Coder (struct gsm_state * S, int16_t * s, int16_t * LARc, int16_t * Nc, int16_t * bc, int16_t * Mc, int16_t * xmaxc, int16_t * xMc)
References gsm_state::dp0, gsm_state::e, GSM_ADD(), Gsm_Long_Term_Predictor(), Gsm_LPC_Analysis(), Gsm_Preprocess(), Gsm_RPE_Encoding(), Gsm_Short_Term_Analysis_Filter(), and memcpy().
Referenced by gsm_encode().
Gsm_Long_Term_Predictor()
void Gsm_Long_Term_Predictor (struct gsm_state * S, int16_t * d, int16_t * dp, int16_t * e, int16_t * dpp, int16_t * Nc, int16_t * bc)
References Calculation_of_the_LTP_parameters(), Fast_Calculation_of_the_LTP_parameters(), and Long_term_analysis_filtering().
Referenced by Gsm_Coder().
Gsm_LPC_Analysis()
void Gsm_LPC_Analysis (struct gsm_state * S, int16_t * s, int16_t * LARc)
References Autocorrelation(), Fast_Autocorrelation(), Quantization_and_coding(), Reflection_coefficients(), and Transformation_to_Log_Area_Ratios().
Referenced by Gsm_Coder().
Gsm_Preprocess()
void Gsm_Preprocess (struct gsm_state * S, int16_t * s, int16_t * so)
References arith_shift_left(), GSM_ADD(), GSM_L_ADD(), GSM_MULT_R(), MIN_WORD, SASR_L(), and SASR_W().
Referenced by Gsm_Coder().
Gsm_Encoding()
void Gsm_Encoding (struct gsm_state * S, int16_t * e, int16_t * ep, int16_t * xmaxc, int16_t * Mc, int16_t * xMc)
Gsm_Short_Term_Analysis_Filter()
void Gsm_Short_Term_Analysis_Filter (struct gsm_state * S, int16_t * LARc, int16_t * d)
References Coefficients_0_12(), Coefficients_13_26(), Coefficients_27_39(), Coefficients_40_159(), Decoding_of_the_coded_Log_Area_Ratios(), FILTER, and LARp_to_rp().
Referenced by Gsm_Coder().
Gsm_Decoder()
void Gsm_Decoder (struct gsm_state * S, int16_t * LARcr, int16_t * Ncr, int16_t * bcr, int16_t * Mcr, int16_t * xmaxcr, int16_t * xMcr, int16_t * s)
References Gsm_Long_Term_Synthesis_Filtering(), Gsm_RPE_Decoding(), Gsm_Short_Term_Synthesis_Filter(), and Postprocessing().
Referenced by gsm_decode().
Gsm_Decoding()
void Gsm_Decoding (struct gsm_state * S, int16_t xmaxcr, int16_t Mcr, int16_t * xMcr, int16_t * erp)
Gsm_Long_Term_Synthesis_Filtering()
void Gsm_Long_Term_Synthesis_Filtering (struct gsm_state * S, int16_t Ncr, int16_t bcr, int16_t * erp, int16_t * drp)
Referenced by Gsm_Decoder().
Gsm_RPE_Decoding()
void Gsm_RPE_Decoding (int16_t xmaxcr, int16_t Mcr, int16_t * xMcr, int16_t * erp)
References APCM_inverse_quantization(), APCM_quantization_xmaxc_to_exp_mant(), and RPE_grid_positioning().
Referenced by Gsm_Decoder().
Gsm_RPE_Encoding()
void Gsm_RPE_Encoding (int16_t * e, int16_t * xmaxc, int16_t * Mc, int16_t * xMc)
References APCM_inverse_quantization(), APCM_quantization(), RPE_grid_positioning(), RPE_grid_selection(), and Weighting_filter().
Referenced by Gsm_Coder().
Gsm_Short_Term_Synthesis_Filter()
void Gsm_Short_Term_Synthesis_Filter (struct gsm_state * S, int16_t * LARcr, int16_t * drp, int16_t * s)
References Coefficients_0_12(), Coefficients_13_26(), Coefficients_27_39(), Coefficients_40_159(), Decoding_of_the_coded_Log_Area_Ratios(), FILTER, and LARp_to_rp().
Referenced by Gsm_Decoder().
Gsm_Update_of_reconstructed_short_time_residual_signal()
void Gsm_Update_of_reconstructed_short_time_residual_signal (int16_t * dpp, int16_t * ep, int16_t * dp)
arith_shift_left()
static int32_t ALWAYS_INLINE arith_shift_left (int32_t x, int shift) inline static
arith_shift_right()
static int32_t ALWAYS_INLINE arith_shift_right (int32_t x, int shift) inline static
gsm_debug_int16_ts()
void gsm_debug_int16_ts (char * name, int , int , int16_t *)
gsm_debug_int32_ts()
void gsm_debug_int32_ts (char * name, int , int , int32_t *)
gsm_debug_int32_t()
void gsm_debug_int32_t (char * name, int32_t)
gsm_debug_int16_t()
void gsm_debug_int16_t (char * name, int16_t)
Variable Documentation
gsm_A
int16_t gsm_A[8]
gsm_B
int16_t gsm_B[8]
gsm_MIC
int16_t gsm_MIC[8]
gsm_MAC
int16_t gsm_MAC[8]
gsm_INVA
int16_t gsm_INVA[8]
gsm_DLB
int16_t gsm_DLB[4]
Referenced by Calculation_of_the_LTP_parameters(), and Fast_Calculation_of_the_LTP_parameters().
gsm_QLB
int16_t gsm_QLB[4]
Referenced by Gsm_Long_Term_Synthesis_Filtering().
gsm_H
int16_t gsm_H[11]
gsm_NRFAC
int16_t gsm_NRFAC[8]
Referenced by APCM_quantization().
gsm_FAC
int16_t gsm_FAC[8]
Referenced by APCM_inverse_quantization().