Aurora Framework: aiff.c File Reference
aiff.c File Reference
Classes
struct AIFF_PRIVATE
struct basc_CHUNK
struct COMM_CHUNK
struct INST_CHUNK
struct INST_LOOP
struct MARK_ID_POS
struct SSND_CHUNK
Macros
#define ADP4_MARKER (MAKE_MARKER ('A', 'D', 'P', '4'))
#define AIFC_IMA4_BLOCK_LEN 34
#define AIFC_IMA4_SAMPLES_PER_BLOCK 64
#define AIFC_MARKER (MAKE_MARKER ('A', 'I', 'F', 'C'))
#define AIFF_MARKER (MAKE_MARKER ('A', 'I', 'F', 'F'))
#define AIFF_PEAK_CHUNK_SIZE(ch) (2 * sizeof (int) + ch * (sizeof (float) + sizeof (int)))
#define alaw_MARKER (MAKE_MARKER ('a', 'l', 'a', 'w'))
#define ALAW_MARKER (MAKE_MARKER ('A', 'L', 'A', 'W'))
#define ANNO_MARKER (MAKE_MARKER ('A', 'N', 'N', 'O'))
#define APPL_MARKER (MAKE_MARKER ('A', 'P', 'P', 'L'))
#define AUTH_MARKER (MAKE_MARKER ('A', 'U', 'T', 'H'))
#define basc_MARKER (MAKE_MARKER ('b', 'a', 's', 'c'))
#define c_MARKER (MAKE_MARKER ('(', 'c', ')', ' '))
#define CHAN_MARKER (MAKE_MARKER ('C', 'H', 'A', 'N'))
#define COMM_MARKER (MAKE_MARKER ('C', 'O', 'M', 'M'))
#define COMT_MARKER (MAKE_MARKER ('C', 'O', 'M', 'T'))
#define DWVW_MARKER (MAKE_MARKER ('D', 'W', 'V', 'W'))
#define fl32_MARKER (MAKE_MARKER ('f', 'l', '3', '2'))
#define FL32_MARKER (MAKE_MARKER ('F', 'L', '3', '2'))
#define fl64_MARKER (MAKE_MARKER ('f', 'l', '6', '4'))
#define FL64_MARKER (MAKE_MARKER ('F', 'L', '6', '4'))
#define FORM_MARKER (MAKE_MARKER ('F', 'O', 'R', 'M'))
#define FVER_MARKER (MAKE_MARKER ('F', 'V', 'E', 'R'))
#define GSM_MARKER (MAKE_MARKER ('G', 'S', 'M', ' '))
#define ima4_MARKER (MAKE_MARKER ('i', 'm', 'a', '4'))
#define in24_MARKER (MAKE_MARKER ('i', 'n', '2', '4'))
#define in32_MARKER (MAKE_MARKER ('i', 'n', '3', '2'))
#define INST_MARKER (MAKE_MARKER ('I', 'N', 'S', 'T'))
#define m3ga_MARKER (MAKE_MARKER ('m', '3', 'g', 'a'))
#define MAC3_MARKER (MAKE_MARKER ('M', 'A', 'C', '3'))
#define MAC6_MARKER (MAKE_MARKER ('M', 'A', 'C', '6'))
#define MARK_MARKER (MAKE_MARKER ('M', 'A', 'R', 'K'))
#define NAME_MARKER (MAKE_MARKER ('N', 'A', 'M', 'E'))
#define ni24_MARKER (MAKE_MARKER ('4', '2', 'n', '1'))
#define ni32_MARKER (MAKE_MARKER ('2', '3', 'n', 'i'))
#define NONE_MARKER (MAKE_MARKER ('N', 'O', 'N', 'E'))
#define PEAK_MARKER (MAKE_MARKER ('P', 'E', 'A', 'K'))
#define raw_MARKER (MAKE_MARKER ('r', 'a', 'w', ' '))
#define SFX_MARKER (MAKE_MARKER ('S', 'F', 'X', '!'))
#define SIZEOF_AIFC_COMM 24
#define SIZEOF_AIFC_COMM_MIN 22
#define SIZEOF_AIFF_COMM 18
#define SIZEOF_INST_CHUNK 20
#define SIZEOF_SSND_CHUNK 8
#define sowt_MARKER (MAKE_MARKER ('s', 'o', 'w', 't'))
#define SSND_MARKER (MAKE_MARKER ('S', 'S', 'N', 'D'))
#define twos_MARKER (MAKE_MARKER ('t', 'w', 'o', 's'))
#define ulaw_MARKER (MAKE_MARKER ('u', 'l', 'a', 'w'))
#define ULAW_MARKER (MAKE_MARKER ('U', 'L', 'A', 'W'))
Enumerations
enum {
HAVE_FORM = 0x01, HAVE_AIFF = 0x02, HAVE_AIFC = 0x04, HAVE_FVER = 0x08,
HAVE_COMM = 0x10, HAVE_SSND = 0x20
}
enum { basc_SCALE_MINOR = 1, basc_SCALE_MAJOR, basc_SCALE_NEITHER, basc_SCALE_BOTH }
enum { basc_TYPE_LOOP = 0, basc_TYPE_ONE_SHOT }
Functions
static int aiff_close (SF_PRIVATE *psf)
static int aiff_command (SF_PRIVATE *psf, int command, void *data, int datasize)
static int aiff_command (SF_PRIVATE *psf, int command, void *UNUSED(data), int UNUSED(datasize))
static int aiff_get_chunk_data (SF_PRIVATE *psf, const SF_CHUNK_ITERATOR *iterator, SF_CHUNK_INFO *chunk_info)
static int aiff_get_chunk_size (SF_PRIVATE *psf, const SF_CHUNK_ITERATOR *iterator, SF_CHUNK_INFO *chunk_info)
static SF_CHUNK_ITERATOR * aiff_next_chunk_iterator (SF_PRIVATE *psf, SF_CHUNK_ITERATOR *iterator)
int aiff_open (SF_PRIVATE *psf)
static int aiff_read_basc_chunk (SF_PRIVATE *psf, int)
static int aiff_read_chanmap (SF_PRIVATE *psf, unsigned dword)
static int aiff_read_comm_chunk (SF_PRIVATE *psf, COMM_CHUNK *comm_fmt)
static int aiff_read_header (SF_PRIVATE *psf, COMM_CHUNK *comm_fmt)
static void aiff_rewrite_header (SF_PRIVATE *psf)
static int aiff_set_chunk (SF_PRIVATE *psf, const SF_CHUNK_INFO *chunk_info)
static int aiff_write_header (SF_PRIVATE *psf, int calc_length)
static void aiff_write_strings (SF_PRIVATE *psf, int location)
static int aiff_write_tailer (SF_PRIVATE *psf)
static int16_t get_loop_mode (int16_t mode)
static const char * get_loop_mode_str (int16_t mode)
static uint32_t marker_to_position (const MARK_ID_POS *m, uint16_t n, int marksize)
static int tenbytefloat2int (uint8_t *bytes)
static void uint2tenbytefloat (uint32_t num, uint8_t *bytes)
Macro Definition Documentation
FORM_MARKER
#define FORM_MARKER (MAKE_MARKER ('F', 'O', 'R', 'M'))
Referenced by aiff_read_header(), aiff_rewrite_header(), and aiff_write_header().
AIFF_MARKER
#define AIFF_MARKER (MAKE_MARKER ('A', 'I', 'F', 'F'))
Referenced by aiff_read_header(), and aiff_write_header().
AIFC_MARKER
#define AIFC_MARKER (MAKE_MARKER ('A', 'I', 'F', 'C'))
Referenced by aiff_read_header(), and aiff_write_header().
COMM_MARKER
#define COMM_MARKER (MAKE_MARKER ('C', 'O', 'M', 'M'))
Referenced by aiff_read_header(), aiff_rewrite_header(), and aiff_write_header().
SSND_MARKER
#define SSND_MARKER (MAKE_MARKER ('S', 'S', 'N', 'D'))
Referenced by aiff_read_header(), aiff_rewrite_header(), and aiff_write_header().
MARK_MARKER
#define MARK_MARKER (MAKE_MARKER ('M', 'A', 'R', 'K'))
Referenced by aiff_read_header(), and aiff_write_header().
INST_MARKER
#define INST_MARKER (MAKE_MARKER ('I', 'N', 'S', 'T'))
Referenced by aiff_read_header().
APPL_MARKER
#define APPL_MARKER (MAKE_MARKER ('A', 'P', 'P', 'L'))
Referenced by aiff_read_header(), and aiff_write_strings().
CHAN_MARKER
#define CHAN_MARKER (MAKE_MARKER ('C', 'H', 'A', 'N'))
Referenced by aiff_read_header(), and aiff_write_header().
c_MARKER
#define c_MARKER (MAKE_MARKER ('(', 'c', ')', ' '))
Referenced by aiff_read_header(), and aiff_write_strings().
NAME_MARKER
#define NAME_MARKER (MAKE_MARKER ('N', 'A', 'M', 'E'))
Referenced by aiff_read_header(), and aiff_write_strings().
AUTH_MARKER
#define AUTH_MARKER (MAKE_MARKER ('A', 'U', 'T', 'H'))
Referenced by aiff_read_header(), and aiff_write_strings().
ANNO_MARKER
#define ANNO_MARKER (MAKE_MARKER ('A', 'N', 'N', 'O'))
Referenced by aiff_read_header(), and aiff_write_strings().
COMT_MARKER
#define COMT_MARKER (MAKE_MARKER ('C', 'O', 'M', 'T'))
Referenced by aiff_read_header().
FVER_MARKER
#define FVER_MARKER (MAKE_MARKER ('F', 'V', 'E', 'R'))
Referenced by aiff_read_header(), and aiff_write_header().
SFX_MARKER
#define SFX_MARKER (MAKE_MARKER ('S', 'F', 'X', '!'))
Referenced by aiff_read_header().
PEAK_MARKER
#define PEAK_MARKER (MAKE_MARKER ('P', 'E', 'A', 'K'))
Referenced by aiff_read_header(), aiff_rewrite_header(), aiff_write_header(), aiff_write_tailer(), rf64_read_header(), wav_read_header(), and wavlike_write_peak_chunk().
basc_MARKER
#define basc_MARKER (MAKE_MARKER ('b', 'a', 's', 'c'))
Referenced by aiff_read_header().
NONE_MARKER
#define NONE_MARKER (MAKE_MARKER ('N', 'O', 'N', 'E'))
Referenced by aiff_read_comm_chunk(), and aiff_read_header().
sowt_MARKER
#define sowt_MARKER (MAKE_MARKER ('s', 'o', 'w', 't'))
Referenced by aiff_read_comm_chunk(), and aiff_write_header().
twos_MARKER
#define twos_MARKER (MAKE_MARKER ('t', 'w', 'o', 's'))
Referenced by aiff_read_comm_chunk(), and aiff_write_header().
raw_MARKER
#define raw_MARKER (MAKE_MARKER ('r', 'a', 'w', ' '))
Referenced by aiff_read_comm_chunk(), and aiff_write_header().
in24_MARKER
#define in24_MARKER (MAKE_MARKER ('i', 'n', '2', '4'))
Referenced by aiff_read_comm_chunk(), and aiff_write_header().
ni24_MARKER
#define ni24_MARKER (MAKE_MARKER ('4', '2', 'n', '1'))
Referenced by aiff_read_comm_chunk(), and aiff_write_header().
in32_MARKER
#define in32_MARKER (MAKE_MARKER ('i', 'n', '3', '2'))
Referenced by aiff_read_comm_chunk(), and aiff_write_header().
ni32_MARKER
#define ni32_MARKER (MAKE_MARKER ('2', '3', 'n', 'i'))
Referenced by aiff_read_comm_chunk(), and aiff_write_header().
fl32_MARKER
#define fl32_MARKER (MAKE_MARKER ('f', 'l', '3', '2'))
Referenced by aiff_read_comm_chunk().
FL32_MARKER
#define FL32_MARKER (MAKE_MARKER ('F', 'L', '3', '2'))
Referenced by aiff_read_comm_chunk(), and aiff_write_header().
fl64_MARKER
#define fl64_MARKER (MAKE_MARKER ('f', 'l', '6', '4'))
Referenced by aiff_read_comm_chunk().
FL64_MARKER
#define FL64_MARKER (MAKE_MARKER ('F', 'L', '6', '4'))
Referenced by aiff_read_comm_chunk(), and aiff_write_header().
ulaw_MARKER
#define ulaw_MARKER (MAKE_MARKER ('u', 'l', 'a', 'w'))
Referenced by aiff_read_comm_chunk(), and aiff_write_header().
ULAW_MARKER
#define ULAW_MARKER (MAKE_MARKER ('U', 'L', 'A', 'W'))
Referenced by aiff_read_comm_chunk().
alaw_MARKER
#define alaw_MARKER (MAKE_MARKER ('a', 'l', 'a', 'w'))
Referenced by aiff_read_comm_chunk(), and aiff_write_header().
ALAW_MARKER
#define ALAW_MARKER (MAKE_MARKER ('A', 'L', 'A', 'W'))
Referenced by aiff_read_comm_chunk().
DWVW_MARKER
#define DWVW_MARKER (MAKE_MARKER ('D', 'W', 'V', 'W'))
Referenced by aiff_read_comm_chunk(), and aiff_write_header().
GSM_MARKER
#define GSM_MARKER (MAKE_MARKER ('G', 'S', 'M', ' '))
Referenced by aiff_read_comm_chunk(), and aiff_write_header().
ima4_MARKER
#define ima4_MARKER (MAKE_MARKER ('i', 'm', 'a', '4'))
Referenced by aiff_read_comm_chunk(), and aiff_write_header().
m3ga_MARKER
#define m3ga_MARKER (MAKE_MARKER ('m', '3', 'g', 'a'))
Referenced by aiff_write_strings().
MAC3_MARKER
#define MAC3_MARKER (MAKE_MARKER ('M', 'A', 'C', '3'))
MAC6_MARKER
#define MAC6_MARKER (MAKE_MARKER ('M', 'A', 'C', '6'))
ADP4_MARKER
#define ADP4_MARKER (MAKE_MARKER ('A', 'D', 'P', '4'))
SIZEOF_AIFF_COMM
#define SIZEOF_AIFF_COMM 18
Referenced by aiff_read_comm_chunk(), and aiff_write_header().
SIZEOF_AIFC_COMM_MIN
#define SIZEOF_AIFC_COMM_MIN 22
Referenced by aiff_read_comm_chunk().
SIZEOF_AIFC_COMM
#define SIZEOF_AIFC_COMM 24
Referenced by aiff_read_comm_chunk(), and aiff_write_header().
SIZEOF_SSND_CHUNK
#define SIZEOF_SSND_CHUNK 8
Referenced by aiff_rewrite_header(), and aiff_write_header().
SIZEOF_INST_CHUNK
#define SIZEOF_INST_CHUNK 20
Referenced by aiff_read_header().
AIFC_IMA4_BLOCK_LEN
#define AIFC_IMA4_BLOCK_LEN 34
Referenced by aiff_open().
AIFC_IMA4_SAMPLES_PER_BLOCK
#define AIFC_IMA4_SAMPLES_PER_BLOCK 64
Referenced by aiff_open(), and aiff_write_header().
AIFF_PEAK_CHUNK_SIZE
#define AIFF_PEAK_CHUNK_SIZE (ch) (2 * sizeof (int) + ch * (sizeof (float) + sizeof (int)))
Referenced by aiff_read_header(), aiff_rewrite_header(), aiff_write_header(), and aiff_write_tailer().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
HAVE_FORM
HAVE_AIFF
HAVE_AIFC
HAVE_FVER
HAVE_COMM
HAVE_SSND
anonymous enum
anonymous enum
Enumerator
basc_SCALE_MINOR
basc_SCALE_MAJOR
basc_SCALE_NEITHER
basc_SCALE_BOTH
anonymous enum
anonymous enum
Enumerator
basc_TYPE_LOOP
basc_TYPE_ONE_SHOT
Function Documentation
aiff_close()
static int aiff_close (SF_PRIVATE * psf) static
References aiff_write_header(), aiff_write_tailer(), sf_private_tag::container_data, sf_private_tag::file, AIFF_PRIVATE::markstr, PSF_FILE::mode, and NULL.
Referenced by aiff_open().
tenbytefloat2int()
static int tenbytefloat2int (uint8_t * bytes) static
Referenced by aiff_read_comm_chunk().
uint2tenbytefloat()
static void uint2tenbytefloat (uint32_t num, uint8_t * bytes) static
Referenced by aiff_write_header().
aiff_read_comm_chunk()
static int aiff_read_comm_chunk (SF_PRIVATE * psf, COMM_CHUNK * comm_fmt) static
References alaw_MARKER, ALAW_MARKER, BITWIDTH2BYTES, sf_private_tag::bytewidth, DWVW_MARKER, COMM_CHUNK::encoding, sf_private_tag::endian, ENDSWAP_32, sf_private_tag::filelength, fl32_MARKER, FL32_MARKER, fl64_MARKER, FL64_MARKER, GSM_MARKER, ima4_MARKER, in24_MARKER, in32_MARKER, make_size_t(), memset(), ni24_MARKER, ni32_MARKER, NONE_MARKER, COMM_CHUNK::numChannels, COMM_CHUNK::numSampleFrames, psf_binheader_readf(), psf_log_printf(), raw_MARKER, s_bitwidth_to_subformat(), COMM_CHUNK::sampleRate, COMM_CHUNK::sampleSize, BUF_UNION::scbuf, sf_private_tag::sf, SF_MAX_CHANNELS, SF_MIN, SFE_CHANNEL_COUNT_BAD, SFE_UNIMPLEMENTED, SIGNED_SIZEOF, COMM_CHUNK::size, SIZEOF_AIFC_COMM, SIZEOF_AIFC_COMM_MIN, SIZEOF_AIFF_COMM, sowt_MARKER, tenbytefloat2int(), twos_MARKER, ulaw_MARKER, and ULAW_MARKER.
Referenced by aiff_read_header().
aiff_read_header()
static int aiff_read_header (SF_PRIVATE * psf, COMM_CHUNK * comm_fmt) static
References AIFC_MARKER, AIFF_MARKER, AIFF_PEAK_CHUNK_SIZE, aiff_read_basc_chunk(), aiff_read_chanmap(), aiff_read_comm_chunk(), ANNO_MARKER, APPL_MARKER, ARRAY_LEN, AUTH_MARKER, basc_MARKER, SSND_CHUNK::blocksize, c_MARKER, BUF_UNION::cbuf, CHAN_MARKER, COMM_MARKER, AIFF_PRIVATE::comm_offset, COMT_MARKER, sf_private_tag::container_data, sf_private_tag::cues, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, done(), BitBuffer::end, sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, sf_private_tag::fileoffset, FORM_MARKER, FVER_MARKER, get_loop_mode(), get_loop_mode_str(), HAVE_AIFC, HAVE_AIFF, HAVE_COMM, HAVE_FORM, HAVE_FVER, HAVE_SSND, INST_MARKER, sf_private_tag::instrument, make_size_t(), MARK_MARKER, marker_to_position(), MARK_ID_POS::markerID, AIFF_PRIVATE::markstr, memset(), mode(), PSF_FILE::mode, NAME_MARKER, NONE_MARKER, NULL, SSND_CHUNK::offset, sf_private_tag::peak_info, peak_info_calloc(), PEAK_INFO::peak_loc, PEAK_MARKER, PEAK_INFO::peaks, MARK_ID_POS::position, PEAK_POS::position, PRId64, psf_binheader_readf(), psf_cues_alloc(), psf_fseek(), psf_ftell(), psf_instrument_alloc(), psf_isprint(), psf_log_printf(), psf_sanitize_string(), psf_store_read_chunk_u32(), psf_store_string(), psf_strlcpy(), sf_private_tag::rchunks, BUF_UNION::scbuf, sf_private_tag::sf, SF_MAX_CHANNELS, SF_PEAK_END, SF_PEAK_START, SFE_AIFF_COMM_NO_FORM, SFE_AIFF_NO_DATA, SFE_AIFF_NO_FORM, SFE_AIFF_PEAK_B4_COMM, SFE_AIFF_RW_SSND_NOT_LAST, SFE_AIFF_SSND_NO_COMM, SFE_CHANNEL_COUNT, SFE_CHANNEL_COUNT_ZERO, SFE_INTERNAL, SFE_MALLOC_FAILED, SFE_WAV_BAD_PEAK, SFX_MARKER, SIGNED_SIZEOF, COMM_CHUNK::size, SIZEOF_INST_CHUNK, SSND_MARKER, AIFF_PRIVATE::ssnd_offset, PEAK_INFO::timestamp, PEAK_POS::value, value, and PEAK_INFO::version.
Referenced by aiff_open().
aiff_write_header()
static int aiff_write_header (SF_PRIVATE * psf, int calc_length) static
References AIFC_IMA4_SAMPLES_PER_BLOCK, AIFC_MARKER, AIFF_MARKER, AIFF_PEAK_CHUNK_SIZE, aiff_rewrite_header(), aiff_write_strings(), alaw_MARKER, BHW2, BHW4, BHW8, BHWf, BHWm, BHWp, BHWv, BHWz, sf_private_tag::bytewidth, CHAN_MARKER, AIFF_PRIVATE::chanmap_tag, sf_private_tag::channel_map, WRITE_CHUNKS::chunks, COMM_MARKER, AIFF_PRIVATE::comm_offset, sf_private_tag::container_data, READ_CHUNKS::count, sf_private_tag::cues, WRITE_CHUNK::data, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, DWVW_MARKER, sf_private_tag::endian, sf_private_tag::error, sf_private_tag::file, sf_private_tag::filelength, FL32_MARKER, FL64_MARKER, sf_private_tag::flags, FORM_MARKER, FVER_MARKER, GSM_MARKER, sf_private_tag::header, ima4_MARKER, in24_MARKER, in32_MARKER, sf_private_tag::indx, sf_private_tag::instrument, WRITE_CHUNK::len, WRITE_CHUNK::mark32, MARK_MARKER, memset(), PSF_FILE::mode, ni24_MARKER, ni32_MARKER, NULL, sf_private_tag::peak_info, PEAK_INFO::peak_loc, PEAK_MARKER, PEAK_INFO::peaks, PEAK_POS::position, psf_binheader_writef(), psf_fseek(), psf_ftell(), psf_fwrite(), psf_get_filelen(), sf_private_tag::ptr, raw_MARKER, sf_private_tag::rchunks, sf_private_tag::sf, SF_CODEC, SF_ENDIAN, SF_PEAK_START, SF_STR_LOCATE_START, SFE_BAD_OPEN_FORMAT, SFE_INTERNAL, SIZEOF_AIFC_COMM, SIZEOF_AIFF_COMM, SIZEOF_SSND_CHUNK, sowt_MARKER, SSND_MARKER, AIFF_PRIVATE::ssnd_offset, sf_private_tag::strings, twos_MARKER, uint2tenbytefloat(), ulaw_MARKER, WRITE_CHUNKS::used, PEAK_POS::value, and sf_private_tag::wchunks.
Referenced by aiff_close(), and aiff_open().
aiff_write_tailer()
static int aiff_write_tailer (SF_PRIVATE * psf) static
References AIFF_PEAK_CHUNK_SIZE, aiff_write_strings(), BHW4, BHW8, BHWf, BHWm, sf_private_tag::dataend, sf_private_tag::flags, sf_private_tag::header, sf_private_tag::indx, NULL, sf_private_tag::peak_info, PEAK_INFO::peak_loc, PEAK_MARKER, PEAK_INFO::peaks, PEAK_POS::position, psf_binheader_writef(), psf_fseek(), psf_fwrite(), sf_private_tag::ptr, sf_private_tag::sf, SF_PEAK_END, SF_STR_LOCATE_END, sf_private_tag::strings, and PEAK_POS::value.
Referenced by aiff_close().
aiff_write_strings()
static void aiff_write_strings (SF_PRIVATE * psf, int location) static
References ANNO_MARKER, APPL_MARKER, AUTH_MARKER, BHW4, BHWm, BHWS, BHWv, BHWz, c_MARKER, sf_private_tag::data, STR_DATA::flags, m3ga_MARKER, NAME_MARKER, STR_DATA::offset, psf_binheader_writef(), SF_MAX_STRINGS, sf_private_tag::storage, sf_private_tag::strings, and STR_DATA::type.
Referenced by aiff_write_header(), and aiff_write_tailer().
aiff_command() [1/2]
static int aiff_command (SF_PRIVATE * psf, int command, void * data, int datasize) static
Referenced by aiff_open().
get_loop_mode_str()
static const char * get_loop_mode_str (int16_t mode) static
References mode().
Referenced by aiff_read_header().
get_loop_mode()
static int16_t get_loop_mode (int16_t mode) static
References mode().
Referenced by aiff_read_header().
aiff_read_basc_chunk()
static int aiff_read_basc_chunk (SF_PRIVATE * psf, int datasize) static
References basc_SCALE_BOTH, basc_SCALE_MAJOR, basc_SCALE_MINOR, basc_SCALE_NEITHER, basc_TYPE_LOOP, basc_TYPE_ONE_SHOT, sf_private_tag::loop_info, basc_CHUNK::loopType, NULL, basc_CHUNK::numBeats, psf_binheader_readf(), psf_log_printf(), basc_CHUNK::rootNote, basc_CHUNK::scaleType, sf_private_tag::sf, SFE_MALLOC_FAILED, basc_CHUNK::sigDenominator, basc_CHUNK::sigNumerator, and basc_CHUNK::version.
Referenced by aiff_read_header().
aiff_read_chanmap()
static int aiff_read_chanmap (SF_PRIVATE * psf, unsigned dword) static
References aiff_caf_of_channel_layout_tag(), AIFF_CAF_CHANNEL_MAP::channel_map, sf_private_tag::channel_map, memcpy(), AIFF_CAF_CHANNEL_MAP::name, NULL, psf_binheader_readf(), psf_log_printf(), sf_private_tag::sf, SF_MIN, and SFE_MALLOC_FAILED.
Referenced by aiff_read_header().
marker_to_position()
static uint32_t marker_to_position (const MARK_ID_POS * m, uint16_t n, int marksize) static
References MARK_ID_POS::position.
Referenced by aiff_read_header().
aiff_set_chunk()
static int aiff_set_chunk (SF_PRIVATE * psf, const SF_CHUNK_INFO * chunk_info) static
References psf_save_write_chunk(), and sf_private_tag::wchunks.
Referenced by aiff_open().
aiff_next_chunk_iterator()
static SF_CHUNK_ITERATOR * aiff_next_chunk_iterator (SF_PRIVATE * psf, SF_CHUNK_ITERATOR * iterator) static
References psf_next_chunk_iterator(), and sf_private_tag::rchunks.
Referenced by aiff_open().
aiff_get_chunk_size()
static int aiff_get_chunk_size (SF_PRIVATE * psf, const SF_CHUNK_ITERATOR * iterator, SF_CHUNK_INFO * chunk_info) static
References READ_CHUNKS::chunks, READ_CHUNK::len, psf_find_read_chunk_iterator(), sf_private_tag::rchunks, SFE_NO_ERROR, and SFE_UNKNOWN_CHUNK.
Referenced by aiff_open().
aiff_get_chunk_data()
static int aiff_get_chunk_data (SF_PRIVATE * psf, const SF_CHUNK_ITERATOR * iterator, SF_CHUNK_INFO * chunk_info) static
References READ_CHUNKS::chunks, READ_CHUNK::id, READ_CHUNK::id_size, READ_CHUNK::len, memcpy(), NULL, READ_CHUNK::offset, psf_find_read_chunk_iterator(), psf_fread(), psf_fseek(), psf_ftell(), sf_private_tag::rchunks, SF_MIN, SFE_BAD_CHUNK_DATA_PTR, SFE_NO_ERROR, and SFE_UNKNOWN_CHUNK.
Referenced by aiff_open().
aiff_open()
int aiff_open (SF_PRIVATE * psf)
References AIFC_IMA4_BLOCK_LEN, AIFC_IMA4_SAMPLES_PER_BLOCK, aiff_close(), aiff_command(), aiff_get_chunk_data(), aiff_get_chunk_size(), aiff_ima_init(), aiff_next_chunk_iterator(), aiff_read_header(), aiff_set_chunk(), aiff_write_header(), alaw_init(), sf_private_tag::command, sf_private_tag::container_close, sf_private_tag::container_data, sf_private_tag::datalength, sf_private_tag::dataoffset, double64_init(), dwvw_init(), sf_private_tag::file, sf_private_tag::filelength, sf_private_tag::flags, float32_init(), sf_private_tag::get_chunk_data, sf_private_tag::get_chunk_size, gsm610_init(), sf_private_tag::is_pipe, memset(), PSF_FILE::mode, sf_private_tag::next_chunk_iterator, NULL, COMM_CHUNK::numSampleFrames, pcm_init(), sf_private_tag::peak_info, peak_info_calloc(), PEAK_INFO::peak_loc, psf_fseek(), psf_log_printf(), COMM_CHUNK::sampleSize, sf_private_tag::set_chunk, sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SF_PEAK_START, SF_STR_ALLOW_END, SF_STR_ALLOW_START, SFE_BAD_OPEN_FORMAT, SFE_DWVW_BAD_BITWIDTH, SFE_MALLOC_FAILED, SFE_NO_PIPE_WRITE, SFE_UNIMPLEMENTED, sf_private_tag::strings, ulaw_init(), and sf_private_tag::write_header.
Referenced by psf_open_file().
aiff_rewrite_header()
static void aiff_rewrite_header (SF_PRIVATE * psf) static
References AIFF_PEAK_CHUNK_SIZE, BHW2, BHW4, BHW8, BHWf, BHWm, READ_CHUNKS::chunks, COMM_MARKER, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::filelength, FORM_MARKER, sf_private_tag::header, sf_private_tag::indx, READ_CHUNK::len, NULL, READ_CHUNK::offset, sf_private_tag::peak_info, PEAK_MARKER, PEAK_INFO::peaks, PEAK_POS::position, psf_binheader_writef(), psf_find_read_chunk_m32(), psf_fread(), psf_fseek(), psf_fwrite(), sf_private_tag::ptr, sf_private_tag::rchunks, sf_private_tag::sf, SIZEOF_SSND_CHUNK, SSND_MARKER, and PEAK_POS::value.
Referenced by aiff_write_header().
aiff_command() [2/2]
static int aiff_command (SF_PRIVATE * psf, int command, void * UNUSEDdata, int UNUSEDdatasize) static
References aiff_caf_find_channel_layout_tag(), AIFF_PRIVATE::chanmap_tag, sf_private_tag::channel_map, sf_private_tag::container_data, NULL, sf_private_tag::sf, and SFE_INTERNAL.