Aurora Framework: spirv_cross::DominatorBuilder Class Reference
spirv_cross::DominatorBuilder Class Reference
Public Member Functions
DominatorBuilder (const CFG &cfg)
void add_block (uint32_t block)
uint32_t get_dominator () const
void lift_continue_block_dominator ()
Constructor & Destructor Documentation
DominatorBuilder()
spirv_cross::DominatorBuilder::DominatorBuilder (const CFG & cfg)
Member Function Documentation
add_block()
void spirv_cross::DominatorBuilder::add_block (uint32_t block)
References spirv_cross::CFG::find_common_dominator(), and spirv_cross::CFG::get_immediate_dominator().
Referenced by spirv_cross::Compiler::analyze_variable_scope().
get_dominator()
uint32_t spirv_cross::DominatorBuilder::get_dominator () const inline
Referenced by spirv_cross::Compiler::analyze_variable_scope().
lift_continue_block_dominator()
void spirv_cross::DominatorBuilder::lift_continue_block_dominator ()
References spirv_cross::SPIRBlock::Direct, spirv_cross::SPIRFunction::entry_block, spirv_cross::Compiler::get(), spirv_cross::CFG::get_compiler(), spirv_cross::CFG::get_function(), spirv_cross::CFG::get_visit_order(), spirv_cross::SPIRBlock::MultiSelect, and spirv_cross::SPIRBlock::Select.
Referenced by spirv_cross::Compiler::analyze_variable_scope().
The documentation for this class was generated from the following files:
CFG.h
CFG.cpp