Aurora Framework: AuroraFW::AudioManager::AudioInfo Struct Reference
AuroraFW::AudioManager::AudioInfo Struct Reference
A struct to hold audio info.
Public Member Functions
AudioInfo (SF_INFO *=new SF_INFO(), SNDFILE *=nullptr)
Constructs an AudioInfo object, either with empty information or with already existing one.
~AudioInfo ()
Destructs an AudioInfo object.
const char * getAlbum () const
Gets the "Album" string of the audio file.
const char * getArtist () const
Gets the "Artist" string of the audio file.
int getChannels () const
Gets the number of channels of the audio file.
const char * getComment () const
Gets the "Comment" string of the audio file.
const char * getCopyright () const
Gets the "Copyright" string of the audio file.
const char * getDate () const
Gets the "Date" string of the audio file.
int getFormat () const
Gets the format of the audio file.
sf_count_t getFrames () const
Gets the number of frames of the audio file.
const char * getGenre () const
Gets the "Genre" string of the audio file.
const char * getLicense () const
Gets the "License" string of the audio file.
int getSampleRate () const
Gets the sample rate of the audio file.
const char * getSoftware () const
Gets the "Software" string of the audio file.
const char * getTitle () const
Gets the "Title" string of the audio file.
const char * getTrackNumber () const
Gets the "TrackNumber" string of the audio file.
void setAlbum (const char *album)
Sets the "Album" string of the audio file to the given string.
void setArtist (const char *artist)
Sets the "Artist" string of the audio file to the given string.
void setChannels (const int)
Sets the number of channels of the audio file.
void setComment (const char *comment)
Sets the "Comment" string of the audio file to the given string.
void setCopyright (const char *copyright)
Sets the "Copyright" string of the audio file to the given string.
void setDate (const char *date)
Sets the "Date" string of the audio file to the given string.
void setFormat (const int)
Sets the format of the audio file.
void setFrames (const sf_count_t)
Sets the number of frames of the audio file.
void setGenre (const char *genre)
Sets the "Genre" string of the audio file to the given string.
void setLicense (const char *license)
Sets the "License" string of the audio file to the given string.
void setSampleRate (const int)
Sets the samplerate of the audio file.
void setSoftware (const char *software)
Sets the "Software" string of the audio file to the given string.
void setTitle (const char *title)
Sets the "Title" string of the audio file to the given string.
void setTrackNumber (const char *trackNumber)
Sets the "TrackNumber" string of the audio file to the given string.
Friends
int audioOutputCallback (const void *, void *, size_t, const PaStreamCallbackTimeInfo *, PaStreamCallbackFlags, void *)
Detailed Description
A struct to hold audio info.
A struct whose purpose is to store all the information about an audio stream/file, either technical (samplerate, channels, etc...) or additional. (title, artist, album, etc...)
Since
snapshot20180330
Constructor & Destructor Documentation
AudioInfo()
AuroraFW::AudioManager::AudioInfo::AudioInfo (SF_INFO * sndInfo = new SF_INFO(), SNDFILE * sndFile = nullptr)
Constructs an AudioInfo object, either with empty information or with already existing one.
Parameters
sndInfo The libsndfile info object, in case the user already has one (default = new empty object)
sndFile The libsndfile file object, in case the user already has one (default = nullptr)
Since
snapshot20180330
~AudioInfo()
AuroraFW::AudioManager::AudioInfo::~AudioInfo ()
Destructs an AudioInfo object.
Since
snapshot20180330
References AFW_NULLPTR, AuroraFW::AudioManager::catchSNDFILEProblem(), and sf_close().
Member Function Documentation
getSampleRate()
int AuroraFW::AudioManager::AudioInfo::getSampleRate () const
Gets the sample rate of the audio file.
Returns
The sample rate of the audio file.
See also
setSampleRate(const int)
Since
snapshot20180330
Referenced by AuroraFW::AudioManager::AudioIStream::AudioIStream().
getFrames()
sf_count_t AuroraFW::AudioManager::AudioInfo::getFrames () const
Gets the number of frames of the audio file.
Returns
The number of frames of the audio file, without counting in the number of channels.
See also
setFrames(const sf_count_t)
Since
snapshot20180330
Referenced by AuroraFW::AudioManager::AudioOStream::AudioOStream(), and AuroraFW::AudioManager::audioOutputCallback().
getChannels()
int AuroraFW::AudioManager::AudioInfo::getChannels () const
Gets the number of channels of the audio file.
Returns
The number of channels of the audio file.
See also
setChannels(const int)
Since
snapshot20180330
Referenced by AuroraFW::AudioManager::audioInputCallback(), AuroraFW::AudioManager::AudioIStream::AudioIStream(), AuroraFW::AudioManager::AudioOStream::AudioOStream(), and AuroraFW::AudioManager::audioOutputCallback().
getFormat()
int AuroraFW::AudioManager::AudioInfo::getFormat () const
Gets the format of the audio file.
The format is the result of a bit-wise operation between a major and minor value from libsndfile. More info on this on the lib's API page.
Returns
The format as an int resulting from bit-wise operations.
See also
setFormat(const int)
Since
snapshot20180330
setSampleRate()
void AuroraFW::AudioManager::AudioInfo::setSampleRate (const int samplerate)
Sets the samplerate of the audio file.
Parameters
samplerate The desired samplerato.
See also
getSamplerate()
Since
snapshot20180330
setFrames()
void AuroraFW::AudioManager::AudioInfo::setFrames (const sf_count_t frames)
Sets the number of frames of the audio file.
Parameters
frames The desired number of frames, without counting in the number of channels.
See also
getFrames()
Since
snapshot20180330
setChannels()
void AuroraFW::AudioManager::AudioInfo::setChannels (const int channels)
Sets the number of channels of the audio file.
Parameters
channels The desired number of channels.
See also
getChannels()
Since
snapshot20180330
setFormat()
void AuroraFW::AudioManager::AudioInfo::setFormat (const int format)
Sets the format of the audio file.
The format must be the result of a bit-wise operation between a major and minor value from libsndfile. More info on this on the lib's API page.
Parameters
format The desired format
See also
getFormat()
Since
snapshot20180330
getTitle()
const char * AuroraFW::AudioManager::AudioInfo::getTitle () const
Gets the "Title" string of the audio file.
Returns
A string containing the data, or "null" if there's no data.
See also
setTitle(const char*)
Since
snapshot20180330
References sf_get_string().
getCopyright()
const char * AuroraFW::AudioManager::AudioInfo::getCopyright () const
Gets the "Copyright" string of the audio file.
Returns
A string containing the data, or "null" if there's no data.
See also
setCopyright(const char*)
Since
snapshot20180330
References sf_get_string().
getSoftware()
const char * AuroraFW::AudioManager::AudioInfo::getSoftware () const
Gets the "Software" string of the audio file.
Returns
A string containing the data, or "null" if there's no data.
See also
setSoftware(const char*)
Since
snapshot20180330
References sf_get_string().
getArtist()
const char * AuroraFW::AudioManager::AudioInfo::getArtist () const
Gets the "Artist" string of the audio file.
Returns
A string containing the data, or "null" if there's no data.
See also
setArtist(const char*)
Since
snapshot20180330
References sf_get_string().
getComment()
const char * AuroraFW::AudioManager::AudioInfo::getComment () const
Gets the "Comment" string of the audio file.
Returns
A string containing the data, or "null" if there's no data.
See also
setComment(const char*)
Since
snapshot20180330
References sf_get_string().
getDate()
const char * AuroraFW::AudioManager::AudioInfo::getDate () const
Gets the "Date" string of the audio file.
Returns
A string containing the data, or "null" if there's no data.
See also
setDate(const char*)
Since
snapshot20180330
References sf_get_string().
getAlbum()
const char * AuroraFW::AudioManager::AudioInfo::getAlbum () const
Gets the "Album" string of the audio file.
Returns
A string containing the data, or "null" if there's no data.
See also
setAlbum(const char*)
Since
snapshot20180330
References sf_get_string().
getLicense()
const char * AuroraFW::AudioManager::AudioInfo::getLicense () const
Gets the "License" string of the audio file.
Returns
A string containing the data, or "null" if there's no data.
See also
setLicense(const char*)
Since
snapshot20180330
References sf_get_string().
getTrackNumber()
const char * AuroraFW::AudioManager::AudioInfo::getTrackNumber () const
Gets the "TrackNumber" string of the audio file.
Returns
A string containing the data, or "null" if there's no data.
See also
setTrackNumber(const char*)
Since
snapshot20180330
References sf_get_string().
getGenre()
const char * AuroraFW::AudioManager::AudioInfo::getGenre () const
Gets the "Genre" string of the audio file.
Returns
A string containing the data, or "null" if there's no data.
See also
setGenre(const char*)
Since
snapshot20180330
References sf_get_string().
setTitle()
void AuroraFW::AudioManager::AudioInfo::setTitle (const char * title)
Sets the "Title" string of the audio file to the given string.
Parameters
title The desired string
See also
getTitle()
Since
snapshot20180330
References sf_set_string().
setCopyright()
void AuroraFW::AudioManager::AudioInfo::setCopyright (const char * copyright)
Sets the "Copyright" string of the audio file to the given string.
Parameters
copyright The desired string
See also
getCopyright()
Since
snapshot20180330
References sf_set_string().
setSoftware()
void AuroraFW::AudioManager::AudioInfo::setSoftware (const char * software)
Sets the "Software" string of the audio file to the given string.
Parameters
software The desired string
See also
getSoftware()
Since
snapshot20180330
References sf_set_string().
setArtist()
void AuroraFW::AudioManager::AudioInfo::setArtist (const char * artist)
Sets the "Artist" string of the audio file to the given string.
Parameters
artist The desired string
See also
getArtist()
Since
snapshot20180330
References sf_set_string().
setComment()
void AuroraFW::AudioManager::AudioInfo::setComment (const char * comment)
Sets the "Comment" string of the audio file to the given string.
Parameters
comment The desired string
See also
getComment()
Since
snapshot20180330
References sf_set_string().
setDate()
void AuroraFW::AudioManager::AudioInfo::setDate (const char * date)
Sets the "Date" string of the audio file to the given string.
Parameters
date The desired string
See also
getDate()
Since
snapshot20180330
References sf_set_string().
setAlbum()
void AuroraFW::AudioManager::AudioInfo::setAlbum (const char * album)
Sets the "Album" string of the audio file to the given string.
Parameters
album The desired string
See also
getAlbum()
Since
snapshot20180330
References sf_set_string().
setLicense()
void AuroraFW::AudioManager::AudioInfo::setLicense (const char * license)
Sets the "License" string of the audio file to the given string.
Parameters
license The desired string
See also
getLicense()
Since
snapshot20180330
References setup::license, and sf_set_string().
setTrackNumber()
void AuroraFW::AudioManager::AudioInfo::setTrackNumber (const char * trackNumber)
Sets the "TrackNumber" string of the audio file to the given string.
Parameters
trackNumber The desired string
See also
getTrackNumber()
Since
snapshot20180330
References sf_set_string().
setGenre()
void AuroraFW::AudioManager::AudioInfo::setGenre (const char * genre)
Sets the "Genre" string of the audio file to the given string.
Parameters
genre The desired string
See also
getGenre()
Since
snapshot20180330
References sf_set_string().
Friends And Related Function Documentation
audioOutputCallback
int audioOutputCallback (const void * inputBuffer, void * outputBuffer, size_t framesPerBuffer, const PaStreamCallbackTimeInfo * timeInfo, PaStreamCallbackFlags statusFlags, void * userData) friend
The documentation for this struct was generated from the following files:
AudioUtils.h
AudioUtils.cpp