Aurora Framework: sd2.c File Reference
sd2.c File Reference
Classes
struct SD2_RSRC
struct STR_RSRC
Macros
#define ALCH_MARKER MAKE_MARKER ('A', 'L', 'C', 'H')
#define lsf1_MARKER MAKE_MARKER ('l', 's', 'f', '1')
#define Sd2a_MARKER MAKE_MARKER ('S', 'd', '2', 'a')
#define Sd2f_MARKER MAKE_MARKER ('S', 'd', '2', 'f')
#define sdML_MARKER MAKE_MARKER ('s', 'd', 'M', 'L')
#define STR_MARKER MAKE_MARKER ('S', 'T', 'R', ' ')
Enumerations
enum { RSRC_STR = 111, RSRC_BIN }
Functions
static int parse_str_rsrc (SF_PRIVATE *psf, SD2_RSRC *rsrc)
static int read_rsrc_char (const SD2_RSRC *prsrc, int offset)
static int read_rsrc_int (const SD2_RSRC *prsrc, int offset)
static int read_rsrc_marker (const SD2_RSRC *prsrc, int offset)
static int read_rsrc_short (const SD2_RSRC *prsrc, int offset)
static void read_rsrc_str (const SD2_RSRC *prsrc, int offset, char *buffer, int buffer_len)
static int sd2_close (SF_PRIVATE *psf)
int sd2_open (SF_PRIVATE *psf)
static int sd2_parse_rsrc_fork (SF_PRIVATE *psf)
static int sd2_write_rsrc_fork (SF_PRIVATE *psf, int calc_length)
static int sd2_write_rsrc_fork (SF_PRIVATE *psf, int UNUSED(calc_length))
Macro Definition Documentation
Sd2f_MARKER
#define Sd2f_MARKER MAKE_MARKER ('S', 'd', '2', 'f')
Referenced by sd2_write_rsrc_fork().
Sd2a_MARKER
#define Sd2a_MARKER MAKE_MARKER ('S', 'd', '2', 'a')
ALCH_MARKER
#define ALCH_MARKER MAKE_MARKER ('A', 'L', 'C', 'H')
lsf1_MARKER
#define lsf1_MARKER MAKE_MARKER ('l', 's', 'f', '1')
Referenced by sd2_write_rsrc_fork().
STR_MARKER
#define STR_MARKER MAKE_MARKER ('S', 'T', 'R', ' ')
Referenced by sd2_parse_rsrc_fork(), and sd2_write_rsrc_fork().
sdML_MARKER
#define sdML_MARKER MAKE_MARKER ('s', 'd', 'M', 'L')
Referenced by sd2_write_rsrc_fork().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
RSRC_STR
RSRC_BIN
Function Documentation
sd2_close()
static int sd2_close (SF_PRIVATE * psf) static
References sf_private_tag::file, and PSF_FILE::mode.
Referenced by sd2_open().
sd2_parse_rsrc_fork()
static int sd2_parse_rsrc_fork (SF_PRIVATE * psf) static
References SD2_RSRC::data_length, SD2_RSRC::data_offset, sf_private_tag::end, sf_private_tag::header, sf_private_tag::indx, SD2_RSRC::item_offset, sf_private_tag::len, SD2_RSRC::map_length, SD2_RSRC::map_offset, memset(), SD2_RSRC::need_to_free_rsrc_data, parse_str_rsrc(), psf_fread(), psf_get_filelen(), psf_log_printf(), psf_use_rsrc(), sf_private_tag::ptr, read_rsrc_int(), read_rsrc_marker(), read_rsrc_short(), SD2_RSRC::rsrc_data, SD2_RSRC::rsrc_len, SFE_SD2_BAD_DATA_LENGTH, SFE_SD2_BAD_DATA_OFFSET, SFE_SD2_BAD_MAP_LENGTH, SFE_SD2_BAD_MAP_OFFSET, SFE_SD2_BAD_RSRC, SD2_RSRC::str_count, SD2_RSRC::str_index, STR_MARKER, SD2_RSRC::string_offset, SD2_RSRC::type_count, and SD2_RSRC::type_offset.
Referenced by sd2_open().
parse_str_rsrc()
static int parse_str_rsrc (SF_PRIVATE * psf, SD2_RSRC * rsrc) static
References sf_private_tag::bytewidth, SD2_RSRC::channels, SD2_RSRC::data_offset, SD2_RSRC::item_offset, setup::name, NULL, psf_log_printf(), read_rsrc_char(), read_rsrc_int(), read_rsrc_short(), read_rsrc_str(), SD2_RSRC::rsrc_len, SD2_RSRC::sample_rate, SD2_RSRC::sample_size, sf_private_tag::sf, SF_MIN, SFE_SD2_BAD_RSRC, SFE_SD2_BAD_SAMPLE_SIZE, SIGNED_SIZEOF, SD2_RSRC::string_offset, and value.
Referenced by sd2_parse_rsrc_fork().
sd2_write_rsrc_fork() [1/2]
static int sd2_write_rsrc_fork (SF_PRIVATE * psf, int calc_length) static
Referenced by sd2_open().
sd2_open()
int sd2_open (SF_PRIVATE * psf)
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::container_close, sf_private_tag::dataoffset, sf_private_tag::endian, sf_private_tag::file, PSF_FILE::mode, NULL, pcm_init(), psf_close_rsrc(), psf_file_valid(), psf_fseek(), psf_log_printf(), psf_open_rsrc(), psf_use_rsrc(), sf_private_tag::rsrc, sf_private_tag::rsrclength, sd2_close(), sd2_parse_rsrc_fork(), sd2_write_rsrc_fork(), sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SFE_BAD_OPEN_FORMAT, SFE_SD2_BAD_RSRC, SFE_UNIMPLEMENTED, and sf_private_tag::write_header.
Referenced by psf_open_file().
sd2_write_rsrc_fork() [2/2]
static int sd2_write_rsrc_fork (SF_PRIVATE * psf, int UNUSEDcalc_length) static
References ARRAY_LEN, BHW1, BHW2, BHW4, BHWm, BHWo, BHWp, BHWv, BHWz, sf_private_tag::bytewidth, PSF_FILE::c, SD2_RSRC::channels, SD2_RSRC::data_length, SD2_RSRC::data_offset, sf_private_tag::error, sf_private_tag::file, sf_private_tag::header, sf_private_tag::indx, SD2_RSRC::item_offset, sf_private_tag::len, lsf1_MARKER, SD2_RSRC::map_length, SD2_RSRC::map_offset, memset(), setup::name, STR_RSRC::name, PSF_FILE::name, psf_binheader_writef(), psf_fwrite(), psf_use_rsrc(), sf_private_tag::ptr, RSRC_BIN, SD2_RSRC::rsrc_data, SD2_RSRC::rsrc_len, RSRC_STR, SD2_RSRC::sample_rate, SD2_RSRC::sample_size, Sd2f_MARKER, sdML_MARKER, sf_private_tag::sf, SD2_RSRC::str_count, STR_MARKER, SD2_RSRC::string_offset, SD2_RSRC::type_count, SD2_RSRC::type_offset, STR_RSRC::value, value, and STR_RSRC::value_len.
read_rsrc_char()
static int read_rsrc_char (const SD2_RSRC * prsrc, int offset) inline static
References SD2_RSRC::rsrc_data, and SD2_RSRC::rsrc_len.
Referenced by parse_str_rsrc().
read_rsrc_short()
static int read_rsrc_short (const SD2_RSRC * prsrc, int offset) inline static
References SD2_RSRC::rsrc_data, and SD2_RSRC::rsrc_len.
Referenced by parse_str_rsrc(), and sd2_parse_rsrc_fork().
read_rsrc_int()
static int read_rsrc_int (const SD2_RSRC * prsrc, int offset) inline static
References SD2_RSRC::rsrc_data, and SD2_RSRC::rsrc_len.
Referenced by parse_str_rsrc(), and sd2_parse_rsrc_fork().
read_rsrc_marker()
static int read_rsrc_marker (const SD2_RSRC * prsrc, int offset) inline static
References SD2_RSRC::rsrc_data, and SD2_RSRC::rsrc_len.
Referenced by sd2_parse_rsrc_fork().
read_rsrc_str()
static void read_rsrc_str (const SD2_RSRC * prsrc, int offset, char * buffer, int buffer_len) static
References memset(), psf_isprint(), SD2_RSRC::rsrc_data, and SD2_RSRC::rsrc_len.
Referenced by parse_str_rsrc().