Aurora Framework: AuroraFW::GEngine::GLVertexBufferLayout Class Reference
AuroraFW::GEngine::GLVertexBufferLayout Class Reference
Public Member Functions
GLVertexBufferLayout ()
const std::vector< GLVertexBufferElement > getElements () const
uint getStride () const
template<typename T >
void push (uint count)
template<>
void push (uint count)
template<>
void push (uint count)
template<>
void push (uint count)
Constructor & Destructor Documentation
GLVertexBufferLayout()
AuroraFW::GEngine::GLVertexBufferLayout::GLVertexBufferLayout () inline
Member Function Documentation
push() [1/4]
template<typename T > void AuroraFW::GEngine::GLVertexBufferLayout::push (uint count)
References AFW_DEBUGBREAK.
getElements()
const std::vector<GLVertexBufferElement> AuroraFW::GEngine::GLVertexBufferLayout::getElements () const inline
Referenced by AuroraFW::GEngine::GLVertexArray::addBuffer().
getStride()
uint AuroraFW::GEngine::GLVertexBufferLayout::getStride () const inline
Referenced by AuroraFW::GEngine::GLVertexArray::addBuffer().
push() [2/4]
template<> void AuroraFW::GEngine::GLVertexBufferLayout::push (uint count)
References GL_FLOAT, and AuroraFW::GEngine::GLVertexBufferElement::sizeOf().
push() [3/4]
template<> void AuroraFW::GEngine::GLVertexBufferLayout::push (uint count)
References GL_UNSIGNED_INT, and AuroraFW::GEngine::GLVertexBufferElement::sizeOf().
push() [4/4]
template<> void AuroraFW::GEngine::GLVertexBufferLayout::push (uint count)
References GL_UNSIGNED_BYTE, and AuroraFW::GEngine::GLVertexBufferElement::sizeOf().
The documentation for this class was generated from the following file:
VertexBufferLayout.h