Aurora Framework: raw.c File Reference
raw.c File Reference
Functions
int raw_open (SF_PRIVATE *psf)
Function Documentation
raw_open()
int raw_open (SF_PRIVATE * psf)
References alaw_init(), sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::datalength, sf_private_tag::dataoffset, double64_init(), dwvw_init(), sf_private_tag::endian, sf_private_tag::filelength, float32_init(), gsm610_init(), nms_adpcm_init(), pcm_init(), sf_private_tag::sf, SF_CODEC, SF_ENDIAN, SFE_BAD_OPEN_FORMAT, SFE_NO_ERROR, ulaw_init(), and vox_adpcm_init().
Referenced by psf_open_file().