Aurora Framework: g72x.c File Reference
G72x/g72x.c File Reference
Functions
static int fmult (int an, int srn)
int g72x_decode_block (G72x_STATE *pstate, const unsigned char *block, short *samples)
int g72x_encode_block (G72x_STATE *pstate, short *samples, unsigned char *block)
struct g72x_state * g72x_reader_init (int codec, int *blocksize, int *samplesperblock)
static G72x_STATE * g72x_state_new (void)
struct g72x_state * g72x_writer_init (int codec, int *blocksize, int *samplesperblock)
static int pack_bytes (int bits, const short *samples, unsigned char *block)
int predictor_pole (G72x_STATE *state_ptr)
int predictor_zero (G72x_STATE *state_ptr)
void private_init_state (G72x_STATE *state_ptr)
static int quan (int val, short *table, int size)
int quantize (int d, int y, short *table, int size)
int reconstruct (int sign, int dqln, int y)
int step_size (G72x_STATE *state_ptr)
static int unpack_bytes (int bits, int blocksize, const unsigned char *block, short *samples)
void update (int code_size, int y, int wi, int fi, int dq, int sr, int dqsez, G72x_STATE *state_ptr)
Variables
static short power2 [15]
Function Documentation
g72x_state_new()
static G72x_STATE * g72x_state_new (void) static
Referenced by g72x_reader_init(), and g72x_writer_init().
unpack_bytes()
static int unpack_bytes (int bits, int blocksize, const unsigned char * block, short * samples) static
References g72x_state::blocksize, and G72x_BLOCK_SIZE.
Referenced by g72x_decode_block().
pack_bytes()
static int pack_bytes (int bits, const short * samples, unsigned char * block) static
References G72x_BLOCK_SIZE.
Referenced by g72x_encode_block().
quan()
static int quan (int val, short * table, int size) static
Referenced by fmult(), quantize(), and update().
fmult()
static int fmult (int an, int srn) static
References power2, and quan().
Referenced by predictor_pole(), and predictor_zero().
private_init_state()
void private_init_state (G72x_STATE * state_ptr)
References g72x_state::a, g72x_state::ap, g72x_state::b, g72x_state::dml, g72x_state::dms, g72x_state::dq, g72x_state::pk, g72x_state::sr, g72x_state::td, g72x_state::yl, and g72x_state::yu.
Referenced by g723_test(), g72x_reader_init(), and g72x_writer_init().
g72x_reader_init()
struct g72x_state* g72x_reader_init (int codec, int * blocksize, int * samplesperblock)
References g72x_state::blocksize, g72x_state::codec_bits, g72x_state::decoder, g72x_state::encoder, G721_32_BITS_PER_SAMPLE, G721_32_BYTES_PER_BLOCK, G721_32_SAMPLES_PER_BLOCK, G721_40_BITS_PER_SAMPLE, G721_40_BYTES_PER_BLOCK, G721_40_SAMPLES_PER_BLOCK, g721_decoder(), G723_16_BITS_PER_SAMPLE, G723_16_BYTES_PER_BLOCK, g723_16_decoder(), G723_16_SAMPLES_PER_BLOCK, G723_24_BITS_PER_SAMPLE, G723_24_BYTES_PER_BLOCK, g723_24_decoder(), G723_24_SAMPLES_PER_BLOCK, g723_40_decoder(), g72x_state_new(), NULL, private_init_state(), and g72x_state::samplesperblock.
Referenced by g72x_init().
g72x_writer_init()
struct g72x_state* g72x_writer_init (int codec, int * blocksize, int * samplesperblock)
References g72x_state::blocksize, g72x_state::codec_bits, g72x_state::decoder, g72x_state::encoder, G721_32_BITS_PER_SAMPLE, G721_32_BYTES_PER_BLOCK, G721_32_SAMPLES_PER_BLOCK, G721_40_BITS_PER_SAMPLE, G721_40_BYTES_PER_BLOCK, G721_40_SAMPLES_PER_BLOCK, g721_encoder(), G723_16_BITS_PER_SAMPLE, G723_16_BYTES_PER_BLOCK, g723_16_encoder(), G723_16_SAMPLES_PER_BLOCK, G723_24_BITS_PER_SAMPLE, G723_24_BYTES_PER_BLOCK, g723_24_encoder(), G723_24_SAMPLES_PER_BLOCK, g723_40_encoder(), g72x_state_new(), NULL, private_init_state(), and g72x_state::samplesperblock.
Referenced by g72x_init().
g72x_decode_block()
int g72x_decode_block (G72x_STATE * pstate, const unsigned char * block, short * samples)
References g72x_state::blocksize, g72x_state::codec_bits, g72x_state::decoder, and unpack_bytes().
Referenced by psf_g72x_decode_block().
g72x_encode_block()
int g72x_encode_block (G72x_STATE * pstate, short * samples, unsigned char * block)
References g72x_state::codec_bits, g72x_state::encoder, pack_bytes(), and g72x_state::samplesperblock.
Referenced by psf_g72x_encode_block().
predictor_zero()
int predictor_zero (G72x_STATE * state_ptr)
References g72x_state::b, g72x_state::dq, and fmult().
Referenced by g721_decoder(), g721_encoder(), g723_16_decoder(), g723_16_encoder(), g723_24_decoder(), g723_24_encoder(), g723_40_decoder(), and g723_40_encoder().
predictor_pole()
int predictor_pole (G72x_STATE * state_ptr)
References g72x_state::a, fmult(), and g72x_state::sr.
Referenced by g721_decoder(), g721_encoder(), g723_16_decoder(), g723_16_encoder(), g723_24_decoder(), g723_24_encoder(), g723_40_decoder(), and g723_40_encoder().
step_size()
int step_size (G72x_STATE * state_ptr)
References g72x_state::ap, g72x_state::yl, and g72x_state::yu.
Referenced by g721_decoder(), g721_encoder(), g723_16_decoder(), g723_16_encoder(), g723_24_decoder(), g723_24_encoder(), g723_40_decoder(), and g723_40_encoder().
quantize()
int quantize (int d, int y, short * table, int size)
References power2, and quan().
Referenced by g721_encoder(), g723_16_encoder(), g723_24_encoder(), and g723_40_encoder().
reconstruct()
int reconstruct (int sign, int dqln, int y)
References g72x_state::dq.
Referenced by g721_decoder(), g721_encoder(), g723_16_decoder(), g723_16_encoder(), g723_24_decoder(), g723_24_encoder(), g723_40_decoder(), and g723_40_encoder().
update()
void update (int code_size, int y, int wi, int fi, int dq, int sr, int dqsez, G72x_STATE * state_ptr)
References g72x_state::a, g72x_state::ap, g72x_state::b, g72x_state::dml, g72x_state::dms, g72x_state::dq, g72x_state::pk, power2, quan(), g72x_state::sr, g72x_state::td, g72x_state::yl, and g72x_state::yu.
Referenced by g721_decoder(), g721_encoder(), g723_16_decoder(), g723_16_encoder(), g723_24_decoder(), g723_24_encoder(), g723_40_decoder(), and g723_40_encoder().
Variable Documentation
power2
short power2[15] static
Initial value:
=
{   1, 2, 4, 8, 0x10, 0x20, 0x40, 0x80,
    0x100, 0x200, 0x400, 0x800, 0x1000, 0x2000, 0x4000
}
Referenced by fmult(), quantize(), and update().