Aurora Framework: Thread.c File Reference
POSIX/Thread.c File Reference
Functions
GLFWbool _glfwPlatformCreateMutex (_GLFWmutex *mutex)
GLFWbool _glfwPlatformCreateTls (_GLFWtls *tls)
void _glfwPlatformDestroyMutex (_GLFWmutex *mutex)
void _glfwPlatformDestroyTls (_GLFWtls *tls)
void * _glfwPlatformGetTls (_GLFWtls *tls)
void _glfwPlatformLockMutex (_GLFWmutex *mutex)
void _glfwPlatformSetTls (_GLFWtls *tls, void *value)
void _glfwPlatformUnlockMutex (_GLFWmutex *mutex)
Function Documentation
_glfwPlatformCreateTls()
GLFWbool _glfwPlatformCreateTls (_GLFWtls * tls)
References _glfwInputError(), GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, and NULL.
_glfwPlatformDestroyTls()
void _glfwPlatformDestroyTls (_GLFWtls * tls)
References memset().
_glfwPlatformGetTls()
void* _glfwPlatformGetTls (_GLFWtls * tls)
References GLFW_TRUE.
_glfwPlatformSetTls()
void _glfwPlatformSetTls (_GLFWtls * tls, void * value)
References GLFW_TRUE, and value.
_glfwPlatformCreateMutex()
GLFWbool _glfwPlatformCreateMutex (_GLFWmutex * mutex)
References _glfwInputError(), GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, and NULL.
_glfwPlatformDestroyMutex()
void _glfwPlatformDestroyMutex (_GLFWmutex * mutex)
References memset().
_glfwPlatformLockMutex()
void _glfwPlatformLockMutex (_GLFWmutex * mutex)
References GLFW_TRUE.
_glfwPlatformUnlockMutex()
void _glfwPlatformUnlockMutex (_GLFWmutex * mutex)
References GLFW_TRUE.