Aurora Framework: broadcast.c File Reference
broadcast.c File Reference
Functions
static size_t bc_min_size (const SF_BROADCAST_INFO *info)
SF_BROADCAST_INFO_16K * broadcast_var_alloc (void)
int broadcast_var_get (SF_PRIVATE *psf, SF_BROADCAST_INFO *data, size_t datasize)
int broadcast_var_set (SF_PRIVATE *psf, const SF_BROADCAST_INFO *info, size_t datasize)
static int gen_coding_history (char *added_history, int added_history_max, const SF_INFO *psfinfo)
Function Documentation
gen_coding_history()
static int gen_coding_history (char * added_history, int added_history_max, const SF_INFO * psfinfo) static
References psf_strlcpy(), SF_CODEC, and width.
Referenced by broadcast_var_set().
bc_min_size()
static size_t bc_min_size (const SF_BROADCAST_INFO * info) inline static
References NULL.
Referenced by broadcast_var_get(), and broadcast_var_set().
broadcast_var_alloc()
SF_BROADCAST_INFO_16K* broadcast_var_alloc (void)
Referenced by broadcast_var_set(), and wavlike_read_bext_chunk().
broadcast_var_set()
int broadcast_var_set (SF_PRIVATE * psf, const SF_BROADCAST_INFO * info, size_t datasize)
References bc_min_size(), sf_private_tag::broadcast_16k, broadcast_var_alloc(), sf_private_tag::error, sf_private_tag::file, gen_coding_history(), memcpy(), PSF_FILE::mode, NULL, psf_strlcat(), psf_strlcpy_crlf(), sf_private_tag::sf, SFE_BAD_BROADCAST_INFO_SIZE, SFE_BAD_BROADCAST_INFO_TOO_BIG, and SFE_MALLOC_FAILED.
Referenced by sf_command().
broadcast_var_get()
int broadcast_var_get (SF_PRIVATE * psf, SF_BROADCAST_INFO * data, size_t datasize)
References bc_min_size(), sf_private_tag::broadcast_16k, memcpy(), NULL, and SF_MIN.
Referenced by sf_command().