Aurora Framework: Platform.h File Reference
Cocoa/Platform.h File Reference
Classes
struct _GLFWcursorNS
struct _GLFWlibraryNS
struct _GLFWmonitorNS
struct _GLFWtimerNS
struct _GLFWwindowNS
struct VkMacOSSurfaceCreateInfoMVK
Macros
#define _glfw_dlclose(handle) dlclose(handle)
#define _glfw_dlopen(name) dlopen(name, RTLD_LAZY | RTLD_LOCAL)
#define _glfw_dlsym(handle, name) dlsym(handle, name)
#define _GLFW_EGL_NATIVE_DISPLAY EGL_DEFAULT_DISPLAY
#define _GLFW_EGL_NATIVE_WINDOW ((EGLNativeWindowType) window->ns.view)
#define _GLFW_PLATFORM_CURSOR_STATE _GLFWcursorNS ns
#define _GLFW_PLATFORM_LIBRARY_TIMER_STATE _GLFWtimerNS ns
#define _GLFW_PLATFORM_LIBRARY_WINDOW_STATE _GLFWlibraryNS ns
#define _GLFW_PLATFORM_MONITOR_STATE _GLFWmonitorNS ns
#define _GLFW_PLATFORM_WINDOW_STATE _GLFWwindowNS ns
#define kTISPropertyUnicodeKeyLayoutData _glfw.ns.tis.kPropertyUnicodeKeyLayoutData
#define LMGetKbdType _glfw.ns.tis.GetKbdType
#define TISCopyCurrentKeyboardLayoutInputSource _glfw.ns.tis.CopyCurrentKeyboardLayoutInputSource
#define TISGetInputSourceProperty _glfw.ns.tis.GetInputSourceProperty
Typedefs
typedef struct _GLFWcursorNS _GLFWcursorNS
typedef struct _GLFWlibraryNS _GLFWlibraryNS
typedef struct _GLFWmonitorNS _GLFWmonitorNS
typedef struct _GLFWtimerNS _GLFWtimerNS
typedef struct _GLFWwindowNS _GLFWwindowNS
typedef void * id
typedef UInt8(* PFN_LMGetKbdType) (void)
typedef TISInputSourceRef(* PFN_TISCopyCurrentKeyboardLayoutInputSource) (void)
typedef void *(* PFN_TISGetInputSourceProperty) (TISInputSourceRef, CFStringRef)
typedef VkResult(APIENTRY * PFN_vkCreateMacOSSurfaceMVK) (VkInstance, const VkMacOSSurfaceCreateInfoMVK *, const VkAllocationCallbacks *, VkSurfaceKHR *)
typedef VkFlags VkMacOSSurfaceCreateFlagsMVK
typedef struct VkMacOSSurfaceCreateInfoMVK VkMacOSSurfaceCreateInfoMVK
Functions
void _glfwInitTimerNS (void)
void _glfwPollMonitorsNS (void)
void _glfwRestoreVideoModeNS (_GLFWmonitor *monitor)
void _glfwSetVideoModeNS (_GLFWmonitor *monitor, const GLFWvidmode *desired)
Macro Definition Documentation
_glfw_dlopen
#define _glfw_dlopen (name) dlopen(name, RTLD_LAZY | RTLD_LOCAL)
Referenced by _glfwCreateContextEGL(), _glfwInitEGL(), _glfwInitGLX(), _glfwInitOSMesa(), _glfwPlatformInit(), and initExtensions().
_glfw_dlclose
#define _glfw_dlclose (handle) dlclose(handle)
Referenced by _glfwPlatformTerminate(), _glfwTerminateEGL(), _glfwTerminateGLX(), _glfwTerminateOSMesa(), and destroyContextEGL().
_glfw_dlsym
#define _glfw_dlsym (handle, name) dlsym(handle, name)
Referenced by _glfwInitEGL(), _glfwInitGLX(), _glfwInitOSMesa(), _glfwPlatformInit(), getProcAddressEGL(), getProcAddressGLX(), and initExtensions().
_GLFW_EGL_NATIVE_WINDOW
#define _GLFW_EGL_NATIVE_WINDOW ((EGLNativeWindowType) window->ns.view)
Referenced by _glfwCreateContextEGL().
_GLFW_EGL_NATIVE_DISPLAY
#define _GLFW_EGL_NATIVE_DISPLAY EGL_DEFAULT_DISPLAY
Referenced by _glfwInitEGL().
_GLFW_PLATFORM_WINDOW_STATE
#define _GLFW_PLATFORM_WINDOW_STATE _GLFWwindowNS ns
_GLFW_PLATFORM_LIBRARY_WINDOW_STATE
#define _GLFW_PLATFORM_LIBRARY_WINDOW_STATE _GLFWlibraryNS ns
_GLFW_PLATFORM_LIBRARY_TIMER_STATE
#define _GLFW_PLATFORM_LIBRARY_TIMER_STATE _GLFWtimerNS ns
_GLFW_PLATFORM_MONITOR_STATE
#define _GLFW_PLATFORM_MONITOR_STATE _GLFWmonitorNS ns
_GLFW_PLATFORM_CURSOR_STATE
#define _GLFW_PLATFORM_CURSOR_STATE _GLFWcursorNS ns
kTISPropertyUnicodeKeyLayoutData
#define kTISPropertyUnicodeKeyLayoutData _glfw.ns.tis.kPropertyUnicodeKeyLayoutData
Referenced by updateUnicodeDataNS().
TISCopyCurrentKeyboardLayoutInputSource
#define TISCopyCurrentKeyboardLayoutInputSource _glfw.ns.tis.CopyCurrentKeyboardLayoutInputSource
Referenced by initializeTIS(), and updateUnicodeDataNS().
TISGetInputSourceProperty
#define TISGetInputSourceProperty _glfw.ns.tis.GetInputSourceProperty
Referenced by initializeTIS(), and updateUnicodeDataNS().
LMGetKbdType
#define LMGetKbdType _glfw.ns.tis.GetKbdType
Referenced by _glfwPlatformGetScancodeName(), and initializeTIS().
Typedef Documentation
id
typedef void* id
VkMacOSSurfaceCreateFlagsMVK
typedef VkFlags VkMacOSSurfaceCreateFlagsMVK
VkMacOSSurfaceCreateInfoMVK
typedef struct VkMacOSSurfaceCreateInfoMVK VkMacOSSurfaceCreateInfoMVK
PFN_vkCreateMacOSSurfaceMVK
typedef VkResult(APIENTRY * PFN_vkCreateMacOSSurfaceMVK) (VkInstance, const VkMacOSSurfaceCreateInfoMVK *, const VkAllocationCallbacks *, VkSurfaceKHR *)
PFN_TISCopyCurrentKeyboardLayoutInputSource
typedef TISInputSourceRef(* PFN_TISCopyCurrentKeyboardLayoutInputSource) (void)
PFN_TISGetInputSourceProperty
typedef void*(* PFN_TISGetInputSourceProperty) (TISInputSourceRef, CFStringRef)
PFN_LMGetKbdType
typedef UInt8(* PFN_LMGetKbdType) (void)
_GLFWwindowNS
typedef struct _GLFWwindowNS _GLFWwindowNS
_GLFWlibraryNS
typedef struct _GLFWlibraryNS _GLFWlibraryNS
_GLFWmonitorNS
typedef struct _GLFWmonitorNS _GLFWmonitorNS
_GLFWcursorNS
typedef struct _GLFWcursorNS _GLFWcursorNS
_GLFWtimerNS
typedef struct _GLFWtimerNS _GLFWtimerNS
Function Documentation
_glfwInitTimerNS()
void _glfwInitTimerNS (void)
References _glfw, and _GLFWlibrary::timer.
Referenced by _glfwPlatformInit().
_glfwPollMonitorsNS()
void _glfwPollMonitorsNS (void)
References _glfw, _GLFW_INSERT_LAST, _glfw_strdup(), _glfwAllocMonitor(), _glfwInputMonitor(), getDisplayName(), GLFW_CONNECTED, GLFW_DISCONNECTED, memcpy(), _GLFWlibrary::monitorCount, _GLFWlibrary::monitors, setup::name, and NULL.
Referenced by _glfwPlatformInit().
_glfwSetVideoModeNS()
void _glfwSetVideoModeNS (_GLFWmonitor * monitor, const GLFWvidmode * desired)
References _glfwChooseVideoMode(), _glfwCompareVideoModes(), _glfwPlatformGetVideoMode(), beginFadeReservation(), endFadeReservation(), mode(), modeIsGood(), NULL, and vidmodeFromCGDisplayMode().
Referenced by acquireMonitor().
_glfwRestoreVideoModeNS()
void _glfwRestoreVideoModeNS (_GLFWmonitor * monitor)
References beginFadeReservation(), endFadeReservation(), and NULL.
Referenced by releaseMonitor().