Aurora Framework: AuroraFW::GUI::Application Class Reference
AuroraFW::GUI::Application Class Reference
Public Types
enum ApplicationFlags {
NoneFlag, ServiceFlag, LauncherFlag, HandlesOpenFlag,
HandlesCommandLineFlag, SendEnvironmentFlag, NonUniqueFlag, OverrideAppIDFlag
}
Public Member Functions
template<typename R , typename... Args>
Application (const std::string &pkgname="org.aurora.example", const ApplicationFlags &flags=NoneFlag, R(*)(Args...)=[]{}, int argc=0, char **argv=NULL)
Application (const Application &)=delete
~Application ()
template<typename R , typename... Args>
void connect (const std::string &, R(*)(Args...), void *=AFW_NULLPTR)
template<typename R , typename... Args>
void connect (const std::string &signal_, std::function< R(Args...)> callback, void *data=AFW_NULLPTR)
GtkApplication * getNativeGtkApplication () const
int getStatus () const
Application & operator= (const Application &)=delete
Member Enumeration Documentation
ApplicationFlags
enum AuroraFW::GUI::Application::ApplicationFlags
Enumerator
NoneFlag
ServiceFlag
LauncherFlag
HandlesOpenFlag
HandlesCommandLineFlag
SendEnvironmentFlag
NonUniqueFlag
OverrideAppIDFlag
Constructor & Destructor Documentation
Application() [1/2]
template<typename R , typename... Args> AuroraFW::GUI::Application::Application (const std::string & pkgname = "org.aurora.example", const ApplicationFlags & flags = NoneFlag, R(*)(Args...) mainfunction = []{}, int argc = 0, char ** argv = NULL)
References connect(), and AuroraFW::DebugManager::Log().
~Application()
AuroraFW::GUI::Application::~Application ()
Application() [2/2]
AuroraFW::GUI::Application::Application (const Application &) delete
Member Function Documentation
operator=()
Application& AuroraFW::GUI::Application::operator= (const Application &) delete
getStatus()
int AuroraFW::GUI::Application::getStatus () const inline
getNativeGtkApplication()
GtkApplication* AuroraFW::GUI::Application::getNativeGtkApplication () const inline
connect() [1/2]
template<typename R , typename... Args> void AuroraFW::GUI::Application::connect (const std::string & signal_, R(*)(Args...) callback, void * data = AFW_NULLPTR)
References AuroraFW::DebugManager::Log().
Referenced by Application().
connect() [2/2]
template<typename R , typename... Args> void AuroraFW::GUI::Application::connect (const std::string & signal_, std::function< R(Args...)> callback, void * data = AFW_NULLPTR) inline
References AuroraFW::getCallbackPtr().
The documentation for this class was generated from the following files:
gui/include/AuroraFW/GUI/Application.h
Application_impl.h
gui/src/Application.cpp