Aurora Framework: ms_adpcm.c File Reference
ms_adpcm.c File Reference
Classes
struct MSADPCM_PRIVATE
Macros
#define IDELTA_COUNT 3
Functions
static void choose_predictor (unsigned int channels, short *data, int *bpred, int *idelta)
static int msadpcm_close (SF_PRIVATE *psf)
static int msadpcm_decode_block (SF_PRIVATE *psf, MSADPCM_PRIVATE *pms)
static int msadpcm_encode_block (SF_PRIVATE *psf, MSADPCM_PRIVATE *pms)
static short msadpcm_get_bpred (SF_PRIVATE *psf, MSADPCM_PRIVATE *pms, unsigned char value)
static sf_count_t msadpcm_read_block (SF_PRIVATE *psf, MSADPCM_PRIVATE *pms, short *ptr, int len)
static sf_count_t msadpcm_read_d (SF_PRIVATE *psf, double *ptr, sf_count_t len)
static sf_count_t msadpcm_read_f (SF_PRIVATE *psf, float *ptr, sf_count_t len)
static sf_count_t msadpcm_read_i (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static sf_count_t msadpcm_read_s (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static sf_count_t msadpcm_seek (SF_PRIVATE *psf, int mode, sf_count_t offset)
static sf_count_t msadpcm_write_block (SF_PRIVATE *psf, MSADPCM_PRIVATE *pms, const short *ptr, int len)
static sf_count_t msadpcm_write_d (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
static sf_count_t msadpcm_write_f (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
static sf_count_t msadpcm_write_i (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
static sf_count_t msadpcm_write_s (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
int wavlike_msadpcm_init (SF_PRIVATE *psf, int blockalign, int samplesperblock)
void wavlike_msadpcm_write_adapt_coeffs (SF_PRIVATE *psf)
Variables
static int AdaptationTable []
static int AdaptCoeff1 [WAVLIKE_MSADPCM_ADAPT_COEFF_COUNT]
static int AdaptCoeff2 [WAVLIKE_MSADPCM_ADAPT_COEFF_COUNT]
Macro Definition Documentation
IDELTA_COUNT
#define IDELTA_COUNT 3
Referenced by choose_predictor().
Function Documentation
msadpcm_decode_block()
static int msadpcm_decode_block (SF_PRIVATE * psf, MSADPCM_PRIVATE * pms) static
References AdaptationTable, AdaptCoeff1, AdaptCoeff2, MSADPCM_PRIVATE::block, MSADPCM_PRIVATE::blockcount, MSADPCM_PRIVATE::blocks, MSADPCM_PRIVATE::blocksize, MSADPCM_PRIVATE::channels, memset(), msadpcm_get_bpred(), psf_fread(), psf_log_printf(), MSADPCM_PRIVATE::samplecount, MSADPCM_PRIVATE::samples, and MSADPCM_PRIVATE::samplesperblock.
Referenced by msadpcm_read_block(), msadpcm_seek(), and wavlike_msadpcm_init().
msadpcm_read_block()
static sf_count_t msadpcm_read_block (SF_PRIVATE * psf, MSADPCM_PRIVATE * pms, short * ptr, int len) static
References MSADPCM_PRIVATE::blockcount, MSADPCM_PRIVATE::blocks, MSADPCM_PRIVATE::channels, memcpy(), memset(), msadpcm_decode_block(), MSADPCM_PRIVATE::samplecount, MSADPCM_PRIVATE::samples, and MSADPCM_PRIVATE::samplesperblock.
Referenced by msadpcm_read_d(), msadpcm_read_f(), msadpcm_read_i(), and msadpcm_read_s().
msadpcm_encode_block()
static int msadpcm_encode_block (SF_PRIVATE * psf, MSADPCM_PRIVATE * pms) static
References AdaptationTable, AdaptCoeff1, AdaptCoeff2, MSADPCM_PRIVATE::block, MSADPCM_PRIVATE::blockcount, MSADPCM_PRIVATE::blocksize, MSADPCM_PRIVATE::channels, choose_predictor(), memset(), psf_fwrite(), psf_log_printf(), MSADPCM_PRIVATE::samplecount, MSADPCM_PRIVATE::samples, and MSADPCM_PRIVATE::samplesperblock.
Referenced by msadpcm_close(), and msadpcm_write_block().
msadpcm_write_block()
static sf_count_t msadpcm_write_block (SF_PRIVATE * psf, MSADPCM_PRIVATE * pms, const short * ptr, int len) static
References MSADPCM_PRIVATE::channels, memcpy(), msadpcm_encode_block(), MSADPCM_PRIVATE::samplecount, MSADPCM_PRIVATE::samples, and MSADPCM_PRIVATE::samplesperblock.
Referenced by msadpcm_write_d(), msadpcm_write_f(), msadpcm_write_i(), and msadpcm_write_s().
msadpcm_read_s()
static sf_count_t msadpcm_read_s (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
References sf_private_tag::codec_data, and msadpcm_read_block().
Referenced by wavlike_msadpcm_init().
msadpcm_read_i()
static sf_count_t msadpcm_read_i (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
References arith_shift_left(), ARRAY_LEN, sf_private_tag::codec_data, msadpcm_read_block(), and BUF_UNION::sbuf.
Referenced by wavlike_msadpcm_init().
msadpcm_read_f()
static sf_count_t msadpcm_read_f (SF_PRIVATE * psf, float * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, msadpcm_read_block(), sf_private_tag::norm_float, and BUF_UNION::sbuf.
Referenced by wavlike_msadpcm_init().
msadpcm_read_d()
static sf_count_t msadpcm_read_d (SF_PRIVATE * psf, double * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, msadpcm_read_block(), sf_private_tag::norm_double, and BUF_UNION::sbuf.
Referenced by wavlike_msadpcm_init().
msadpcm_write_s()
static sf_count_t msadpcm_write_s (SF_PRIVATE * psf, const short * ptr, sf_count_t len) static
References sf_private_tag::codec_data, and msadpcm_write_block().
Referenced by wavlike_msadpcm_init().
msadpcm_write_i()
static sf_count_t msadpcm_write_i (SF_PRIVATE * psf, const int * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, msadpcm_write_block(), and BUF_UNION::sbuf.
Referenced by wavlike_msadpcm_init().
msadpcm_write_f()
static sf_count_t msadpcm_write_f (SF_PRIVATE * psf, const float * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, msadpcm_write_block(), sf_private_tag::norm_float, and BUF_UNION::sbuf.
Referenced by wavlike_msadpcm_init().
msadpcm_write_d()
static sf_count_t msadpcm_write_d (SF_PRIVATE * psf, const double * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, msadpcm_write_block(), sf_private_tag::norm_double, and BUF_UNION::sbuf.
Referenced by wavlike_msadpcm_init().
msadpcm_seek()
static sf_count_t msadpcm_seek (SF_PRIVATE * psf, int mode, sf_count_t offset) static
References MSADPCM_PRIVATE::blockcount, MSADPCM_PRIVATE::blocks, MSADPCM_PRIVATE::blocksize, sf_private_tag::codec_data, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::error, mode(), msadpcm_decode_block(), psf_fseek(), PSF_SEEK_ERROR, MSADPCM_PRIVATE::samplecount, MSADPCM_PRIVATE::samplesperblock, and SFE_BAD_SEEK.
Referenced by wavlike_msadpcm_init().
msadpcm_close()
static int msadpcm_close (SF_PRIVATE * psf) static
References sf_private_tag::codec_data, sf_private_tag::file, PSF_FILE::mode, msadpcm_encode_block(), MSADPCM_PRIVATE::samplecount, and MSADPCM_PRIVATE::samplesperblock.
Referenced by wavlike_msadpcm_init().
choose_predictor()
static void choose_predictor (unsigned int channels, short * data, int * bpred, int * idelta) static
References AdaptCoeff1, AdaptCoeff2, and IDELTA_COUNT.
Referenced by msadpcm_encode_block().
wavlike_msadpcm_init()
int wavlike_msadpcm_init (SF_PRIVATE * psf, int blockalign, int samplesperblock)
References MSADPCM_PRIVATE::block, MSADPCM_PRIVATE::blocks, MSADPCM_PRIVATE::blocksize, MSADPCM_PRIVATE::channels, sf_private_tag::codec_close, sf_private_tag::codec_data, sf_private_tag::datalength, MSADPCM_PRIVATE::dataremaining, MSADPCM_PRIVATE::dummydata, sf_private_tag::file, PSF_FILE::mode, msadpcm_close(), msadpcm_decode_block(), msadpcm_read_d(), msadpcm_read_f(), msadpcm_read_i(), msadpcm_read_s(), msadpcm_seek(), msadpcm_write_d(), msadpcm_write_f(), msadpcm_write_i(), msadpcm_write_s(), NULL, psf_log_printf(), sf_private_tag::read_double, sf_private_tag::read_float, sf_private_tag::read_int, sf_private_tag::read_short, MSADPCM_PRIVATE::samplecount, MSADPCM_PRIVATE::samples, MSADPCM_PRIVATE::samplesperblock, sf_private_tag::seek, sf_private_tag::sf, SFE_INTERNAL, SFE_MALLOC_FAILED, MSADPCM_PRIVATE::sync_error, sf_private_tag::write_double, sf_private_tag::write_float, sf_private_tag::write_int, and sf_private_tag::write_short.
Referenced by w64_open(), and wav_open().
msadpcm_get_bpred()
static short msadpcm_get_bpred (SF_PRIVATE * psf, MSADPCM_PRIVATE * pms, unsigned char value) inline static
References psf_log_printf(), MSADPCM_PRIVATE::sync_error, value, and WAVLIKE_MSADPCM_ADAPT_COEFF_COUNT.
Referenced by msadpcm_decode_block().
wavlike_msadpcm_write_adapt_coeffs()
void wavlike_msadpcm_write_adapt_coeffs (SF_PRIVATE * psf)
References AdaptCoeff1, AdaptCoeff2, BHW2, psf_binheader_writef(), and WAVLIKE_MSADPCM_ADAPT_COEFF_COUNT.
Referenced by w64_write_header(), and wav_write_fmt_chunk().
Variable Documentation
AdaptationTable
int AdaptationTable[] static
Initial value:
=
{   230, 230, 230, 230, 307, 409, 512, 614,
    768, 614, 512, 409, 307, 230, 230, 230
}
Referenced by msadpcm_decode_block(), and msadpcm_encode_block().
AdaptCoeff1
int AdaptCoeff1[WAVLIKE_MSADPCM_ADAPT_COEFF_COUNT] static
Initial value:
=
{   256, 512, 0, 192, 240, 460, 392
}
Referenced by choose_predictor(), msadpcm_decode_block(), msadpcm_encode_block(), and wavlike_msadpcm_write_adapt_coeffs().
AdaptCoeff2
int AdaptCoeff2[WAVLIKE_MSADPCM_ADAPT_COEFF_COUNT] static
Initial value:
=
{   0, -256, 0, 64, 0, -208, -232
}
Referenced by choose_predictor(), msadpcm_decode_block(), msadpcm_encode_block(), and wavlike_msadpcm_write_adapt_coeffs().