Aurora Framework: spirv_cross Namespace Reference
spirv_cross Namespace Reference
Namespaces
inner
Classes
class Bitset
struct BufferRange
class CFG
class ClassicLocale
struct CombinedImageSampler
class Compiler
class CompilerCPP
class CompilerError
class CompilerGLSL
class CompilerHLSL
class CompilerMSL
class DominatorBuilder
struct EntryPoint
class Hasher
struct HLSLVertexAttributeRemap
struct Instruction
struct IVariant
struct Meta
struct MSLResourceBinding
struct MSLVertexAttr
struct PlsRemap
struct Resource
struct RootConstants
struct ShaderResources
struct SpecializationConstant
struct SPIRAccessChain
struct SPIRBlock
struct SPIRCombinedImageSampler
struct SPIRConstant
struct SPIRConstantOp
struct SPIREntryPoint
struct SPIRExpression
struct SPIRExtension
struct SPIRFunction
struct SPIRFunctionPrototype
struct SPIRType
struct SPIRUndef
struct SPIRVariable
class Variant
Typedefs
using MSLStructMemberKey = uint64_t
using VariableTypeRemapCallback = std::function< void(const SPIRType &type, const std::string &var_name, std::string &name_of_type)>
Enumerations
enum BufferPackingStandard {
BufferPackingStd140, BufferPackingStd430, BufferPackingStd140EnhancedLayout, BufferPackingStd430EnhancedLayout,
BufferPackingHLSLCbuffer, BufferPackingHLSLCbufferPackOffset
}
enum PlsFormat {
PlsNone = 0, PlsR11FG11FB10F, PlsR32F, PlsRG16F,
PlsRGB10A2, PlsRGBA8, PlsRG16, PlsRGBA8I,
PlsRG16I, PlsRGB10A2UI, PlsRGBA8UI, PlsRG16UI,
PlsR32UI
}
enum Types {
TypeNone, TypeType, TypeVariable, TypeConstant,
TypeFunction, TypeFunctionPrototype, TypePointer, TypeBlock,
TypeExtension, TypeExpression, TypeConstantOp, TypeCombinedImageSampler,
TypeAccessChain, TypeUndef
}
Functions
template<typename T >
std::string convert_to_string (T &&t)
std::string convert_to_string (float t)
std::string convert_to_string (double t)
template<typename... Ts>
std::string join (Ts &&... ts)
std::string merge (const std::vector< std::string > &list)
static bool type_is_floating_point (const SPIRType &type)
template<typename T >
T & variant_get (Variant &var)
template<typename T >
const T & variant_get (const Variant &var)
template<typename T , typename... P>
T & variant_set (Variant &var, P &&... args)
Variables
static const uint32_t kPushConstBinding = 0
static const uint32_t kPushConstDescSet = std::numeric_limits<uint32_t>::max()
Typedef Documentation
VariableTypeRemapCallback
using spirv_cross::VariableTypeRemapCallback = typedef std::function<void(const SPIRType &type, const std::string &var_name, std::string &name_of_type)>
MSLStructMemberKey
using spirv_cross::MSLStructMemberKey = typedef uint64_t
Enumeration Type Documentation
Types
enum spirv_cross::Types
Enumerator
TypeNone
TypeType
TypeVariable
TypeConstant
TypeFunction
TypeFunctionPrototype
TypePointer
TypeBlock
TypeExtension
TypeExpression
TypeConstantOp
TypeCombinedImageSampler
TypeAccessChain
TypeUndef
BufferPackingStandard
enum spirv_cross::BufferPackingStandard
Enumerator
BufferPackingStd140
BufferPackingStd430
BufferPackingStd140EnhancedLayout
BufferPackingStd430EnhancedLayout
BufferPackingHLSLCbuffer
BufferPackingHLSLCbufferPackOffset
PlsFormat
enum spirv_cross::PlsFormat
Enumerator
PlsNone
PlsR11FG11FB10F
PlsR32F
PlsRG16F
PlsRGB10A2
PlsRGBA8
PlsRG16
PlsRGBA8I
PlsRG16I
PlsRGB10A2UI
PlsRGBA8UI
PlsRG16UI
PlsR32UI
Function Documentation
join()
template<typename... Ts> std::string spirv_cross::join (Ts &&... ts)
References spirv_cross::inner::join_helper().
Referenced by spirv_cross::CompilerGLSL::access_chain(), spirv_cross::CompilerGLSL::access_chain_internal(), spirv_cross::CompilerMSL::add_interface_block(), spirv_cross::CompilerGLSL::argument_decl(), spirv_cross::CompilerGLSL::bitcast_expression(), spirv_cross::CompilerGLSL::bitcast_glsl(), spirv_cross::CompilerGLSL::builtin_to_glsl(), glloader.lang.common.generator.Generator::commandline(), spirv_cross::CompilerGLSL::constant_op_expression(), spirv_cross::CompilerGLSL::convert_double_to_string(), spirv_cross::CompilerGLSL::convert_float_to_string(), spirv_cross::CompilerGLSL::convert_half_to_string(), spirv_cross::CompilerGLSL::convert_row_major_matrix(), spirv_cross::CompilerGLSL::declare_temporary(), spirv_cross::CompilerGLSL::emit_binary_func_op(), spirv_cross::CompilerGLSL::emit_binary_func_op_cast(), spirv_cross::CompilerGLSL::emit_binary_op(), spirv_cross::CompilerGLSL::emit_binary_op_cast(), spirv_cross::CompilerGLSL::emit_block_chain(), spirv_cross::CompilerGLSL::emit_buffer_block_native(), spirv_cross::CompilerGLSL::emit_declared_builtin_block(), spirv_cross::CompilerGLSL::emit_flattened_io_block(), spirv_cross::CompilerGLSL::emit_for_loop_initializers(), spirv_cross::CompilerGLSL::emit_header(), spirv_cross::CompilerGLSL::emit_instruction(), spirv_cross::CompilerGLSL::emit_interface_block(), spirv_cross::CompilerGLSL::emit_mix_op(), spirv_cross::CompilerGLSL::emit_quaternary_func_op(), spirv_cross::CompilerGLSL::emit_trinary_func_op(), spirv_cross::CompilerGLSL::emit_unary_func_op(), spirv_cross::CompilerGLSL::emit_unary_op(), spirv_cross::CompilerGLSL::enclose_expression(), spirv_cross::Compiler::get_block_fallback_name(), spirv_cross::Compiler::get_fallback_member_name(), spirv_cross::Compiler::get_fallback_name(), glloader.lang.common.generator.Generator::header(), spirv_cross::CompilerGLSL::layout_for_member(), spirv_cross::CompilerGLSL::layout_for_variable(), spirv_cross::CompilerGLSL::legacy_tex_op(), glloader.lang.common.generator.Generator::online(), spirv_cross::CompilerGLSL::pls_decl(), spirv_cross::Compiler::CombinedImageSamplerHandler::register_combined_image_sampler(), spirv_cross::CompilerGLSL::remap_swizzle(), spirv_cross_util::rename_interface_variable(), spirv_cross::CompilerGLSL::replace_fragment_output(), spirv_cross::CompilerGLSL::replace_illegal_names(), spirv_cross::CompilerGLSL::statement(), spirv_cross::CompilerGLSL::store_flattened_struct(), spirv_cross::CompilerGLSL::to_flattened_struct_member(), spirv_cross::CompilerGLSL::to_function_args(), spirv_cross::CompilerGLSL::to_member_name(), spirv_cross::Compiler::to_name(), spirv_cross::CompilerGLSL::type_to_glsl(), spirv_cross::CompilerMSL::unpack_expression_type(), spirv_cross::CompilerGLSL::variable_decl(), glloader.lang.c.debug.CDebugGenerator::write_function(), glloader.lang.nim.generator.NimGenerator::write_function_declaration(), glloader.lang.c.generator.CGenerator::write_function_def(), glloader.lang.nim.generator.NimGenerator::write_function_def(), glloader.lang.d.generator.DGenerator::write_function_def(), glloader.lang.c.debug.CDebugGenerator::write_function_prototype(), glloader.lang.c.generator.CGenerator::write_function_prototype(), and glloader.lang.d.generator.DGenerator::write_function_prototype().
merge()
std::string spirv_cross::merge (const std::vector< std::string > & list) inline
Referenced by spirv_cross::Compiler::block_is_loop_candidate(), spirv_cross::CompilerGLSL::emit_continue_block(), spirv_cross::CompilerGLSL::emit_function_prototype(), spirv_cross::CompilerGLSL::emit_header(), spirv_cross::CompilerGLSL::emit_instruction(), spirv_cross::CompilerGLSL::layout_for_member(), and spirv_cross::CompilerGLSL::layout_for_variable().
convert_to_string() [1/3]
template<typename T > std::string spirv_cross::convert_to_string (T && t) inline
Referenced by spirv_cross::CompilerGLSL::access_chain_internal(), spirv_cross::CompilerGLSL::builtin_to_glsl(), spirv_cross::CompilerGLSL::constant_expression_vector(), spirv_cross::CompilerGLSL::convert_double_to_string(), spirv_cross::CompilerGLSL::convert_float_to_string(), spirv_cross::CompilerGLSL::convert_half_to_string(), spirv_cross::CompilerGLSL::emit_block_chain(), spirv_cross::CompilerMSL::emit_specialization_constants(), spirv_cross::CompilerGLSL::flattened_access_chain_offset(), spirv_cross::CompilerGLSL::flattened_access_chain_vector(), spirv_cross::CompilerMSL::get_input_buffer_block_var_id(), spirv_cross::CompilerGLSL::to_array_size(), and spirv_cross::Compiler::update_name_cache().
convert_to_string() [2/3]
std::string spirv_cross::convert_to_string (float t) inline
References SPIRV_CROSS_FLT_FMT.
convert_to_string() [3/3]
std::string spirv_cross::convert_to_string (double t) inline
References SPIRV_CROSS_FLT_FMT.
variant_get() [1/2]
template<typename T > T& spirv_cross::variant_get (Variant & var)
References spirv_cross::Variant::get().
variant_get() [2/2]
template<typename T > const T& spirv_cross::variant_get (const Variant & var)
References spirv_cross::Variant::get().
variant_set()
template<typename T , typename... P> T& spirv_cross::variant_set (Variant & var, P &&... args)
References spirv_cross::Variant::set().
type_is_floating_point()
static bool spirv_cross::type_is_floating_point (const SPIRType & type) inline static
References spirv_cross::SPIRType::basetype, spirv_cross::SPIRType::Double, spirv_cross::SPIRType::Float, and spirv_cross::SPIRType::Half.
Referenced by spirv_cross::CompilerMSL::add_interface_block(), spirv_cross::CompilerGLSL::constant_expression_vector(), and spirv_cross::CompilerGLSL::emit_instruction().
Variable Documentation
kPushConstDescSet
const uint32_t spirv_cross::kPushConstDescSet = std::numeric_limits<uint32_t>::max() static
kPushConstBinding
const uint32_t spirv_cross::kPushConstBinding = 0 static