Aurora Framework: ALACBitUtilities.c File Reference
ALACBitUtilities.c File Reference
Macros
#define PRAGMA_MARK 0
Functions
void BitBufferAdvance (BitBuffer *bits, uint32_t numBits)
void BitBufferByteAlign (BitBuffer *bits, int32_t addZeros)
uint32_t BitBufferGetPosition (BitBuffer *bits)
void BitBufferInit (BitBuffer *bits, uint8_t *buffer, uint32_t byteSize)
uint32_t BitBufferPeek (BitBuffer *bits, uint8_t numBits)
uint32_t BitBufferPeekOne (BitBuffer *bits)
uint32_t BitBufferRead (BitBuffer *bits, uint8_t numBits)
uint8_t BitBufferReadOne (BitBuffer *bits)
uint8_t BitBufferReadSmall (BitBuffer *bits, uint8_t numBits)
void BitBufferReset (BitBuffer *bits)
void BitBufferRewind (BitBuffer *bits, uint32_t numBits)
uint32_t BitBufferUnpackBERSize (BitBuffer *bits)
void BitBufferWrite (BitBuffer *bits, uint32_t bitValues, uint32_t numBits)
Macro Definition Documentation
PRAGMA_MARK
#define PRAGMA_MARK 0
Function Documentation
BitBufferInit()
void BitBufferInit (BitBuffer * bits, uint8_t * buffer, uint32_t byteSize)
References BitBuffer::bitIndex, BitBuffer::byteSize, BitBuffer::cur, and BitBuffer::end.
Referenced by alac_decode_block(), alac_encode(), EncodeMono(), and EncodeStereo().
BitBufferRead()
uint32_t BitBufferRead (BitBuffer * bits, uint8_t numBits)
References BitBuffer::bitIndex, and BitBuffer::cur.
Referenced by alac_decode().
BitBufferReadSmall()
uint8_t BitBufferReadSmall (BitBuffer * bits, uint8_t numBits)
References BitBuffer::bitIndex, and BitBuffer::cur.
Referenced by alac_data_stream_element(), alac_decode(), alac_fill_element(), and BitBufferUnpackBERSize().
BitBufferReadOne()
uint8_t BitBufferReadOne (BitBuffer * bits)
References BitBuffer::bitIndex, and BitBuffer::cur.
Referenced by alac_data_stream_element().
BitBufferPeek()
uint32_t BitBufferPeek (BitBuffer * bits, uint8_t numBits)
References BitBuffer::bitIndex, and BitBuffer::cur.
BitBufferPeekOne()
uint32_t BitBufferPeekOne (BitBuffer * bits)
References BitBuffer::bitIndex, and BitBuffer::cur.
BitBufferUnpackBERSize()
uint32_t BitBufferUnpackBERSize (BitBuffer * bits)
References BitBufferReadSmall().
BitBufferGetPosition()
uint32_t BitBufferGetPosition (BitBuffer * bits)
References BitBuffer::bitIndex, BitBuffer::byteSize, BitBuffer::cur, and BitBuffer::end.
Referenced by alac_encode(), EncodeMono(), EncodeStereo(), and EncodeStereoFast().
BitBufferByteAlign()
void BitBufferByteAlign (BitBuffer * bits, int32_t addZeros)
References BitBufferAdvance(), BitBufferWrite(), and BitBuffer::bitIndex.
Referenced by alac_data_stream_element(), alac_decode(), and alac_encode().
BitBufferAdvance()
void BitBufferAdvance (BitBuffer * bits, uint32_t numBits)
References BitBuffer::bitIndex, and BitBuffer::cur.
Referenced by alac_data_stream_element(), alac_decode(), alac_fill_element(), BitBufferByteAlign(), dyn_comp(), and dyn_decomp().
BitBufferRewind()
void BitBufferRewind (BitBuffer * bits, uint32_t numBits)
References BitBuffer::bitIndex, BitBuffer::byteSize, BitBuffer::cur, and BitBuffer::end.
BitBufferWrite()
void BitBufferWrite (BitBuffer * bits, uint32_t bitValues, uint32_t numBits)
References BitBuffer::bitIndex, BitBuffer::cur, MIN, NULL, RequireAction, and RequireActionSilent.
Referenced by alac_encode(), BitBufferByteAlign(), EncodeMono(), EncodeStereo(), EncodeStereoEscape(), and EncodeStereoFast().
BitBufferReset()
void BitBufferReset (BitBuffer * bits)
References BitBuffer::bitIndex, BitBuffer::byteSize, BitBuffer::cur, and BitBuffer::end.