Aurora Framework: g72x.c File Reference
g72x.c File Reference
Classes
struct G72x_PRIVATE
Typedefs
typedef struct g72x_state G72x_STATE
Functions
static int g72x_close (SF_PRIVATE *psf)
int g72x_init (SF_PRIVATE *psf)
static int g72x_read_block (SF_PRIVATE *psf, G72x_PRIVATE *pg72x, short *ptr, int len)
static sf_count_t g72x_read_d (SF_PRIVATE *psf, double *ptr, sf_count_t len)
static sf_count_t g72x_read_f (SF_PRIVATE *psf, float *ptr, sf_count_t len)
static sf_count_t g72x_read_i (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static sf_count_t g72x_read_s (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static sf_count_t g72x_seek (SF_PRIVATE *psf, int mode, sf_count_t offset)
static sf_count_t g72x_seek (SF_PRIVATE *psf, int UNUSED(mode), sf_count_t UNUSED(offset))
static int g72x_write_block (SF_PRIVATE *psf, G72x_PRIVATE *pg72x, const short *ptr, int len)
static sf_count_t g72x_write_d (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
static sf_count_t g72x_write_f (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
static sf_count_t g72x_write_i (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
static sf_count_t g72x_write_s (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
static int psf_g72x_decode_block (SF_PRIVATE *psf, G72x_PRIVATE *pg72x)
static int psf_g72x_encode_block (SF_PRIVATE *psf, G72x_PRIVATE *pg72x)
Typedef Documentation
G72x_STATE
typedef struct g72x_state G72x_STATE
Function Documentation
psf_g72x_decode_block()
static int psf_g72x_decode_block (SF_PRIVATE * psf, G72x_PRIVATE * pg72x) static
References G72x_PRIVATE::block, G72x_PRIVATE::block_curr, G72x_PRIVATE::blocks_total, G72x_PRIVATE::blocksize, G72x_PRIVATE::bytesperblock, G72x_BLOCK_SIZE, g72x_decode_block(), memset(), G72x_PRIVATE::private, psf_fread(), psf_log_printf(), G72x_PRIVATE::sample_curr, and G72x_PRIVATE::samples.
Referenced by g72x_init(), and g72x_read_block().
psf_g72x_encode_block()
static int psf_g72x_encode_block (SF_PRIVATE * psf, G72x_PRIVATE * pg72x) static
References G72x_PRIVATE::block, G72x_PRIVATE::block_curr, G72x_PRIVATE::blocksize, G72x_BLOCK_SIZE, g72x_encode_block(), memset(), G72x_PRIVATE::private, psf_fwrite(), psf_log_printf(), G72x_PRIVATE::sample_curr, and G72x_PRIVATE::samples.
Referenced by g72x_close(), and g72x_write_block().
g72x_read_s()
static sf_count_t g72x_read_s (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
References sf_private_tag::codec_data, g72x_read_block(), and NULL.
Referenced by g72x_init().
g72x_read_i()
static sf_count_t g72x_read_i (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
References arith_shift_left(), sf_private_tag::codec_data, g72x_read_block(), NULL, BUF_UNION::sbuf, and SF_BUFFER_LEN.
Referenced by g72x_init().
g72x_read_f()
static sf_count_t g72x_read_f (SF_PRIVATE * psf, float * ptr, sf_count_t len) static
References sf_private_tag::codec_data, g72x_read_block(), sf_private_tag::norm_float, NULL, BUF_UNION::sbuf, and SF_BUFFER_LEN.
Referenced by g72x_init().
g72x_read_d()
static sf_count_t g72x_read_d (SF_PRIVATE * psf, double * ptr, sf_count_t len) static
References sf_private_tag::codec_data, g72x_read_block(), sf_private_tag::norm_double, NULL, BUF_UNION::sbuf, and SF_BUFFER_LEN.
Referenced by g72x_init().
g72x_write_s()
static sf_count_t g72x_write_s (SF_PRIVATE * psf, const short * ptr, sf_count_t len) static
References sf_private_tag::codec_data, g72x_write_block(), and NULL.
Referenced by g72x_init().
g72x_write_i()
static sf_count_t g72x_write_i (SF_PRIVATE * psf, const int * ptr, sf_count_t len) static
References sf_private_tag::codec_data, g72x_write_block(), NULL, BUF_UNION::sbuf, and SF_BUFFER_LEN.
Referenced by g72x_init().
g72x_write_f()
static sf_count_t g72x_write_f (SF_PRIVATE * psf, const float * ptr, sf_count_t len) static
References sf_private_tag::codec_data, g72x_write_block(), sf_private_tag::norm_float, NULL, BUF_UNION::sbuf, and SF_BUFFER_LEN.
Referenced by g72x_init().
g72x_write_d()
static sf_count_t g72x_write_d (SF_PRIVATE * psf, const double * ptr, sf_count_t len) static
References sf_private_tag::codec_data, g72x_write_block(), sf_private_tag::norm_double, NULL, BUF_UNION::sbuf, and SF_BUFFER_LEN.
Referenced by g72x_init().
g72x_seek() [1/2]
static sf_count_t g72x_seek (SF_PRIVATE * psf, int mode, sf_count_t offset) static
Referenced by g72x_init().
g72x_close()
static int g72x_close (SF_PRIVATE * psf) static
References sf_private_tag::codec_data, sf_private_tag::file, G72x_BLOCK_SIZE, PSF_FILE::mode, G72x_PRIVATE::private, psf_g72x_encode_block(), G72x_PRIVATE::sample_curr, and sf_private_tag::write_header.
Referenced by g72x_init().
g72x_init()
int g72x_init (SF_PRIVATE * psf)
References G72x_PRIVATE::block_curr, G72x_PRIVATE::blocks_total, G72x_PRIVATE::blocksize, G72x_PRIVATE::bytesperblock, sf_private_tag::codec_close, sf_private_tag::codec_data, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::file, sf_private_tag::filelength, G721_32_BITS_PER_SAMPLE, G721_32_BYTES_PER_BLOCK, G723_24_BITS_PER_SAMPLE, G723_24_BYTES_PER_BLOCK, G723_40_BITS_PER_SAMPLE, G723_40_BYTES_PER_BLOCK, g72x_close(), g72x_read_d(), g72x_read_f(), g72x_read_i(), g72x_read_s(), g72x_reader_init(), g72x_seek(), g72x_write_d(), g72x_write_f(), g72x_write_i(), g72x_write_s(), g72x_writer_init(), PSF_FILE::mode, NULL, G72x_PRIVATE::private, psf_g72x_decode_block(), psf_get_filelen(), psf_log_printf(), sf_private_tag::read_double, sf_private_tag::read_float, sf_private_tag::read_int, sf_private_tag::read_short, G72x_PRIVATE::sample_curr, G72x_PRIVATE::samplesperblock, sf_private_tag::seek, sf_private_tag::sf, SF_CODEC, SFE_G72X_NOT_MONO, SFE_INTERNAL, SFE_MALLOC_FAILED, SFE_UNIMPLEMENTED, sf_private_tag::write_double, sf_private_tag::write_float, sf_private_tag::write_int, and sf_private_tag::write_short.
Referenced by au_open(), and wav_open().
g72x_read_block()
static int g72x_read_block (SF_PRIVATE * psf, G72x_PRIVATE * pg72x, short * ptr, int len) static
References G72x_PRIVATE::block_curr, G72x_PRIVATE::blocks_total, memcpy(), memset(), psf_g72x_decode_block(), G72x_PRIVATE::sample_curr, G72x_PRIVATE::samples, and G72x_PRIVATE::samplesperblock.
Referenced by g72x_read_d(), g72x_read_f(), g72x_read_i(), and g72x_read_s().
g72x_seek() [2/2]
static sf_count_t g72x_seek (SF_PRIVATE * psf, int UNUSEDmode, sf_count_t UNUSEDoffset) static
References psf_log_printf().
g72x_write_block()
static int g72x_write_block (SF_PRIVATE * psf, G72x_PRIVATE * pg72x, const short * ptr, int len) static
References memcpy(), psf_g72x_encode_block(), G72x_PRIVATE::sample_curr, G72x_PRIVATE::samples, and G72x_PRIVATE::samplesperblock.
Referenced by g72x_write_d(), g72x_write_f(), g72x_write_i(), and g72x_write_s().