Aurora Framework: ima_adpcm.c File Reference
ima_adpcm.c File Reference
Classes
struct IMA_ADPCM_PRIVATE_tag
Typedefs
typedef struct IMA_ADPCM_PRIVATE_tag IMA_ADPCM_PRIVATE
Functions
static int aiff_ima_decode_block (SF_PRIVATE *psf, IMA_ADPCM_PRIVATE *pima)
static int aiff_ima_encode_block (SF_PRIVATE *psf, IMA_ADPCM_PRIVATE *pima)
int aiff_ima_init (SF_PRIVATE *psf, int blockalign, int samplesperblock)
static sf_count_t aiff_ima_seek (SF_PRIVATE *psf, int mode, sf_count_t offset)
static int clamp_ima_step_index (int indx)
static int ima_close (SF_PRIVATE *psf)
static int ima_read_block (SF_PRIVATE *psf, IMA_ADPCM_PRIVATE *pima, short *ptr, int len)
static sf_count_t ima_read_d (SF_PRIVATE *psf, double *ptr, sf_count_t len)
static sf_count_t ima_read_f (SF_PRIVATE *psf, float *ptr, sf_count_t len)
static sf_count_t ima_read_i (SF_PRIVATE *psf, int *ptr, sf_count_t len)
static sf_count_t ima_read_s (SF_PRIVATE *psf, short *ptr, sf_count_t len)
static int ima_reader_init (SF_PRIVATE *psf, int blockalign, int samplesperblock)
static int ima_write_block (SF_PRIVATE *psf, IMA_ADPCM_PRIVATE *pima, const short *ptr, int len)
static sf_count_t ima_write_d (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
static sf_count_t ima_write_f (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
static sf_count_t ima_write_i (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
static sf_count_t ima_write_s (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
static int ima_writer_init (SF_PRIVATE *psf, int blockalign)
static int wavlike_ima_decode_block (SF_PRIVATE *psf, IMA_ADPCM_PRIVATE *pima)
static int wavlike_ima_encode_block (SF_PRIVATE *psf, IMA_ADPCM_PRIVATE *pima)
int wavlike_ima_init (SF_PRIVATE *psf, int blockalign, int samplesperblock)
static sf_count_t wavlike_ima_seek (SF_PRIVATE *psf, int mode, sf_count_t offset)
Variables
static int ima_indx_adjust [16]
static int ima_step_size [89]
Typedef Documentation
IMA_ADPCM_PRIVATE
typedef struct IMA_ADPCM_PRIVATE_tag IMA_ADPCM_PRIVATE
Function Documentation
ima_reader_init()
static int ima_reader_init (SF_PRIVATE * psf, int blockalign, int samplesperblock) static
References aiff_ima_decode_block(), IMA_ADPCM_PRIVATE_tag::block, IMA_ADPCM_PRIVATE_tag::blocks, IMA_ADPCM_PRIVATE_tag::blocksize, IMA_ADPCM_PRIVATE_tag::channels, sf_private_tag::codec_data, IMA_ADPCM_PRIVATE_tag::data, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, IMA_ADPCM_PRIVATE_tag::decode_block, sf_private_tag::file, sf_private_tag::filelength, ima_read_d(), ima_read_f(), ima_read_i(), ima_read_s(), PSF_FILE::mode, psf_get_filelen(), psf_log_printf(), sf_private_tag::read_double, sf_private_tag::read_float, sf_private_tag::read_int, sf_private_tag::read_short, IMA_ADPCM_PRIVATE_tag::samples, IMA_ADPCM_PRIVATE_tag::samplesperblock, sf_private_tag::sf, SF_CONTAINER, SFE_BAD_MODE_RW, SFE_INTERNAL, SFE_MALLOC_FAILED, and wavlike_ima_decode_block().
Referenced by aiff_ima_init(), and wavlike_ima_init().
ima_writer_init()
static int ima_writer_init (SF_PRIVATE * psf, int blockalign) static
References aiff_ima_encode_block(), IMA_ADPCM_PRIVATE_tag::block, IMA_ADPCM_PRIVATE_tag::blocksize, IMA_ADPCM_PRIVATE_tag::channels, sf_private_tag::codec_data, IMA_ADPCM_PRIVATE_tag::data, IMA_ADPCM_PRIVATE_tag::encode_block, sf_private_tag::file, ima_write_d(), ima_write_f(), ima_write_i(), ima_write_s(), PSF_FILE::mode, NULL, psf_log_printf(), IMA_ADPCM_PRIVATE_tag::samplecount, IMA_ADPCM_PRIVATE_tag::samples, IMA_ADPCM_PRIVATE_tag::samplesperblock, sf_private_tag::sf, SF_CONTAINER, SFE_BAD_MODE_RW, SFE_INTERNAL, SFE_MALLOC_FAILED, wavlike_ima_encode_block(), sf_private_tag::write_double, sf_private_tag::write_float, sf_private_tag::write_int, and sf_private_tag::write_short.
Referenced by aiff_ima_init(), and wavlike_ima_init().
ima_read_block()
static int ima_read_block (SF_PRIVATE * psf, IMA_ADPCM_PRIVATE * pima, short * ptr, int len) static
References IMA_ADPCM_PRIVATE_tag::blockcount, IMA_ADPCM_PRIVATE_tag::blocks, IMA_ADPCM_PRIVATE_tag::channels, IMA_ADPCM_PRIVATE_tag::decode_block, memcpy(), memset(), IMA_ADPCM_PRIVATE_tag::samplecount, IMA_ADPCM_PRIVATE_tag::samples, and IMA_ADPCM_PRIVATE_tag::samplesperblock.
Referenced by ima_read_d(), ima_read_f(), ima_read_i(), and ima_read_s().
ima_write_block()
static int ima_write_block (SF_PRIVATE * psf, IMA_ADPCM_PRIVATE * pima, const short * ptr, int len) static
References IMA_ADPCM_PRIVATE_tag::channels, IMA_ADPCM_PRIVATE_tag::encode_block, memcpy(), IMA_ADPCM_PRIVATE_tag::samplecount, IMA_ADPCM_PRIVATE_tag::samples, and IMA_ADPCM_PRIVATE_tag::samplesperblock.
Referenced by ima_write_d(), ima_write_f(), ima_write_i(), and ima_write_s().
ima_read_s()
static sf_count_t ima_read_s (SF_PRIVATE * psf, short * ptr, sf_count_t len) static
References sf_private_tag::codec_data, and ima_read_block().
Referenced by ima_reader_init().
ima_read_i()
static sf_count_t ima_read_i (SF_PRIVATE * psf, int * ptr, sf_count_t len) static
References arith_shift_left(), ARRAY_LEN, sf_private_tag::codec_data, ima_read_block(), and BUF_UNION::sbuf.
Referenced by ima_reader_init().
ima_read_f()
static sf_count_t ima_read_f (SF_PRIVATE * psf, float * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, ima_read_block(), sf_private_tag::norm_float, and BUF_UNION::sbuf.
Referenced by ima_reader_init().
ima_read_d()
static sf_count_t ima_read_d (SF_PRIVATE * psf, double * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, ima_read_block(), sf_private_tag::norm_double, and BUF_UNION::sbuf.
Referenced by ima_reader_init().
ima_write_s()
static sf_count_t ima_write_s (SF_PRIVATE * psf, const short * ptr, sf_count_t len) static
References sf_private_tag::codec_data, and ima_write_block().
Referenced by ima_writer_init().
ima_write_i()
static sf_count_t ima_write_i (SF_PRIVATE * psf, const int * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, ima_write_block(), and BUF_UNION::sbuf.
Referenced by ima_writer_init().
ima_write_f()
static sf_count_t ima_write_f (SF_PRIVATE * psf, const float * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, ima_write_block(), sf_private_tag::norm_float, and BUF_UNION::sbuf.
Referenced by ima_writer_init().
ima_write_d()
static sf_count_t ima_write_d (SF_PRIVATE * psf, const double * ptr, sf_count_t len) static
References ARRAY_LEN, sf_private_tag::codec_data, ima_write_block(), sf_private_tag::norm_double, and BUF_UNION::sbuf.
Referenced by ima_writer_init().
aiff_ima_seek()
static sf_count_t aiff_ima_seek (SF_PRIVATE * psf, int mode, sf_count_t offset) static
References IMA_ADPCM_PRIVATE_tag::blockcount, IMA_ADPCM_PRIVATE_tag::blocks, IMA_ADPCM_PRIVATE_tag::blocksize, sf_private_tag::codec_data, sf_private_tag::datalength, sf_private_tag::dataoffset, IMA_ADPCM_PRIVATE_tag::decode_block, sf_private_tag::error, mode(), psf_fseek(), PSF_SEEK_ERROR, IMA_ADPCM_PRIVATE_tag::samplecount, IMA_ADPCM_PRIVATE_tag::samplesperblock, sf_private_tag::sf, and SFE_BAD_SEEK.
Referenced by aiff_ima_init().
wavlike_ima_seek()
static sf_count_t wavlike_ima_seek (SF_PRIVATE * psf, int mode, sf_count_t offset) static
References IMA_ADPCM_PRIVATE_tag::blockcount, IMA_ADPCM_PRIVATE_tag::blocks, IMA_ADPCM_PRIVATE_tag::blocksize, sf_private_tag::codec_data, sf_private_tag::datalength, sf_private_tag::dataoffset, IMA_ADPCM_PRIVATE_tag::decode_block, sf_private_tag::error, mode(), psf_fseek(), PSF_SEEK_ERROR, IMA_ADPCM_PRIVATE_tag::samplecount, IMA_ADPCM_PRIVATE_tag::samplesperblock, and SFE_BAD_SEEK.
Referenced by wavlike_ima_init().
ima_close()
static int ima_close (SF_PRIVATE * psf) static
References IMA_ADPCM_PRIVATE_tag::blockcount, sf_private_tag::codec_data, IMA_ADPCM_PRIVATE_tag::encode_block, sf_private_tag::file, PSF_FILE::mode, IMA_ADPCM_PRIVATE_tag::samplecount, IMA_ADPCM_PRIVATE_tag::samplesperblock, and sf_private_tag::sf.
Referenced by aiff_ima_init(), and wavlike_ima_init().
wavlike_ima_decode_block()
static int wavlike_ima_decode_block (SF_PRIVATE * psf, IMA_ADPCM_PRIVATE * pima) static
References IMA_ADPCM_PRIVATE_tag::block, IMA_ADPCM_PRIVATE_tag::blockcount, IMA_ADPCM_PRIVATE_tag::blocks, IMA_ADPCM_PRIVATE_tag::blocksize, IMA_ADPCM_PRIVATE_tag::channels, clamp_ima_step_index(), ima_indx_adjust, ima_step_size, memset(), psf_fread(), psf_log_printf(), IMA_ADPCM_PRIVATE_tag::samplecount, IMA_ADPCM_PRIVATE_tag::samples, IMA_ADPCM_PRIVATE_tag::samplesperblock, and IMA_ADPCM_PRIVATE_tag::stepindx.
Referenced by ima_reader_init().
wavlike_ima_encode_block()
static int wavlike_ima_encode_block (SF_PRIVATE * psf, IMA_ADPCM_PRIVATE * pima) static
References IMA_ADPCM_PRIVATE_tag::block, IMA_ADPCM_PRIVATE_tag::blockcount, IMA_ADPCM_PRIVATE_tag::blocksize, IMA_ADPCM_PRIVATE_tag::channels, clamp_ima_step_index(), ima_indx_adjust, ima_step_size, memset(), IMA_ADPCM_PRIVATE_tag::previous, psf_fwrite(), psf_log_printf(), IMA_ADPCM_PRIVATE_tag::samplecount, IMA_ADPCM_PRIVATE_tag::samples, IMA_ADPCM_PRIVATE_tag::samplesperblock, and IMA_ADPCM_PRIVATE_tag::stepindx.
Referenced by ima_writer_init().
aiff_ima_decode_block()
static int aiff_ima_decode_block (SF_PRIVATE * psf, IMA_ADPCM_PRIVATE * pima) static
References IMA_ADPCM_PRIVATE_tag::block, IMA_ADPCM_PRIVATE_tag::blockcount, IMA_ADPCM_PRIVATE_tag::blocks, IMA_ADPCM_PRIVATE_tag::blocksize, IMA_ADPCM_PRIVATE_tag::channels, clamp_ima_step_index(), ima_indx_adjust, ima_step_size, memset(), psf_fread(), psf_log_printf(), IMA_ADPCM_PRIVATE_tag::samplecount, IMA_ADPCM_PRIVATE_tag::samples, IMA_ADPCM_PRIVATE_tag::samplesperblock, and IMA_ADPCM_PRIVATE_tag::stepindx.
Referenced by ima_reader_init().
aiff_ima_encode_block()
static int aiff_ima_encode_block (SF_PRIVATE * psf, IMA_ADPCM_PRIVATE * pima) static
References IMA_ADPCM_PRIVATE_tag::block, IMA_ADPCM_PRIVATE_tag::blockcount, IMA_ADPCM_PRIVATE_tag::blocksize, IMA_ADPCM_PRIVATE_tag::channels, clamp_ima_step_index(), ima_indx_adjust, ima_step_size, memset(), IMA_ADPCM_PRIVATE_tag::previous, psf_fwrite(), psf_log_printf(), IMA_ADPCM_PRIVATE_tag::samplecount, IMA_ADPCM_PRIVATE_tag::samples, IMA_ADPCM_PRIVATE_tag::samplesperblock, and IMA_ADPCM_PRIVATE_tag::stepindx.
Referenced by ima_writer_init().
clamp_ima_step_index()
static int clamp_ima_step_index (int indx) inline static
References ARRAY_LEN, and ima_step_size.
Referenced by aiff_ima_decode_block(), aiff_ima_encode_block(), wavlike_ima_decode_block(), and wavlike_ima_encode_block().
wavlike_ima_init()
int wavlike_ima_init (SF_PRIVATE * psf, int blockalign, int samplesperblock)
References sf_private_tag::codec_close, sf_private_tag::codec_data, sf_private_tag::file, ima_close(), ima_reader_init(), ima_writer_init(), PSF_FILE::mode, NULL, psf_log_printf(), IMA_ADPCM_PRIVATE_tag::samplesperblock, sf_private_tag::seek, SFE_BAD_MODE_RW, SFE_INTERNAL, and wavlike_ima_seek().
Referenced by w64_open(), and wav_open().
aiff_ima_init()
int aiff_ima_init (SF_PRIVATE * psf, int blockalign, int samplesperblock)
References aiff_ima_seek(), sf_private_tag::codec_close, sf_private_tag::file, ima_close(), ima_reader_init(), ima_writer_init(), PSF_FILE::mode, IMA_ADPCM_PRIVATE_tag::samplesperblock, sf_private_tag::seek, and SFE_BAD_MODE_RW.
Referenced by aiff_open().
Variable Documentation
ima_indx_adjust
int ima_indx_adjust[16] static
Initial value:
=
{   -1, -1, -1, -1,
    +2, +4, +6, +8,
    -1, -1, -1, -1,
    +2, +4, +6, +8,
}
Referenced by aiff_ima_decode_block(), aiff_ima_encode_block(), wavlike_ima_decode_block(), and wavlike_ima_encode_block().
ima_step_size
int ima_step_size[89] static
Initial value:
=
{   7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 19, 21, 23, 25, 28, 31, 34, 37, 41, 45,
    50, 55, 60, 66, 73, 80, 88, 97, 107, 118, 130, 143, 157, 173, 190, 209, 230,
    253, 279, 307, 337, 371, 408, 449, 494, 544, 598, 658, 724, 796, 876, 963,
    1060, 1166, 1282, 1411, 1552, 1707, 1878, 2066, 2272, 2499, 2749, 3024, 3327,
    3660, 4026, 4428, 4871, 5358, 5894, 6484, 7132, 7845, 8630, 9493, 10442,
    11487, 12635, 13899, 15289, 16818, 18500, 20350, 22385, 24623, 27086, 29794,
    32767
}
Referenced by aiff_ima_decode_block(), aiff_ima_encode_block(), clamp_ima_step_index(), wavlike_ima_decode_block(), and wavlike_ima_encode_block().