Aurora Framework: Monitor.c File Reference
Wayland/Monitor.c File Reference
Functions
void _glfwAddOutputWayland (uint32_t name, uint32_t version)
void _glfwPlatformFreeMonitor (_GLFWmonitor *monitor)
void _glfwPlatformGetGammaRamp (_GLFWmonitor *monitor, GLFWgammaramp *ramp)
void _glfwPlatformGetMonitorContentScale (_GLFWmonitor *monitor, float *xscale, float *yscale)
void _glfwPlatformGetMonitorPos (_GLFWmonitor *monitor, int *xpos, int *ypos)
void _glfwPlatformGetVideoMode (_GLFWmonitor *monitor, GLFWvidmode *mode)
GLFWvidmode * _glfwPlatformGetVideoModes (_GLFWmonitor *monitor, int *found)
void _glfwPlatformSetGammaRamp (_GLFWmonitor *monitor, const GLFWgammaramp *ramp)
static void done (void *data, struct wl_output *output)
static void geometry (void *data, struct wl_output *output, int32_t x, int32_t y, int32_t physicalWidth, int32_t physicalHeight, int32_t subpixel, const char *make, const char *model, int32_t transform)
GLFWAPI struct wl_output * glfwGetWaylandMonitor (GLFWmonitor *handle)
static void mode (void *data, struct wl_output *output, uint32_t flags, int32_t width, int32_t height, int32_t refresh)
static void scale (void *data, struct wl_output *output, int32_t factor)
Variables
static const struct wl_output_listener outputListener
Function Documentation
geometry()
static void geometry (void * data, struct wl_output * output, int32_t x, int32_t y, int32_t physicalWidth, int32_t physicalHeight, int32_t subpixel, const char * make, const char * model, int32_t transform) static
References _glfw_strdup(), _GLFWmonitor::heightMM, setup::name, _GLFWmonitor::name, and _GLFWmonitor::widthMM.
mode()
static void mode (void * data, struct wl_output * output, uint32_t flags, int32_t width, int32_t height, int32_t refresh) static
References _GLFWmonitor::currentMode, height, _GLFWmonitor::modeCount, _GLFWmonitor::modes, and width.
Referenced by _glfwInitVulkan(), _glfwPlatformCreateWindow(), _glfwPlatformGetVideoMode(), _glfwPlatformGetVideoModes(), _glfwPlatformPollJoystick(), _glfwPlatformSetCursorMode(), _glfwSetVideoModeNS(), _glfwSetVideoModeX11(), acquireMonitor(), aiff_ima_seek(), aiff_read_header(), alac_seek(), createNativeWindow(), dither_init(), dpcm_seek(), EncodeStereo(), EncodeStereoFast(), FillInRGBBitsFromPixelFormat(), spirv_cross::Compiler::get_execution_mode_argument(), get_loop_mode(), get_loop_mode_str(), ImGui::GetNavInputAmount(), ImGui::GetNavInputAmount2d(), glfwGetInputMode(), glfwSetInputMode(), ImFileOpen(), IsNavInputPressed(), IsNavInputPressedAnyOfTwo(), modeIsGood(), msadpcm_seek(), nms_adpcm_seek(), paf24_seek(), spirv_cross::Compiler::parse(), psf_open_fd(), sds_seek(), spirv_cross::Compiler::set_execution_mode(), AuroraFW::GUI::Label::setAlignment(), AuroraFW::GUI::Label::setWrapMode(), sf_open(), sf_open_fd(), sf_open_virtual(), SndfileHandle::SndfileHandle(), str_of_open_mode(), spirv_cross::Compiler::unset_execution_mode(), vidmodeFromCGDisplayMode(), vidmodeFromModeInfo(), wavlike_ima_seek(), and AuroraFW::GEngine::Window::Window().
done()
static void done (void * data, struct wl_output * output) static
References _GLFW_INSERT_LAST, _glfwInputMonitor(), and GLFW_CONNECTED.
Referenced by aiff_read_header(), rf64_read_header(), svx_read_header(), w64_read_header(), and wav_read_header().
scale()
static void scale (void * data, struct wl_output * output, int32_t factor) static
Referenced by ImDrawList::AddConvexPolyFilled(), ImDrawList::AddPolyline(), ImFont::CalcTextSizeA(), ImFont::CalcWordWrapPositionA(), checkScaleChange(), d2i_array(), d2i_clip_array(), d2s_array(), d2s_clip_array(), f2i_array(), f2i_clip_array(), f2s_array(), f2s_clip_array(), Fast_Autocorrelation(), gen_signal_double(), host_read_d2i(), host_read_d2s(), host_read_f2i(), host_read_f2s(), host_write_i2d(), host_write_i2f(), host_write_s2d(), host_write_s2f(), i2d_array(), i2f_array(), InputTextCalcTextSizeW(), ImGui::NewFrame(), ImFont::RenderChar(), ImFont::RenderText(), ImGui::RenderTriangle(), replace_read_d2i(), replace_read_d2s(), replace_read_f2i(), replace_read_f2s(), replace_write_i2d(), replace_write_i2f(), replace_write_s2d(), replace_write_s2f(), resizeWindow(), s2d_array(), s2f_array(), ImDrawData::ScaleClipRects(), ImGui::SetWindowFontScale(), and ImGui::ShadeVertsLinearUV().
_glfwAddOutputWayland()
void _glfwAddOutputWayland (uint32_t name, uint32_t version)
References _glfw, _glfwAllocMonitor(), _glfwFreeMonitor(), _glfwInputError(), GLFW_PLATFORM_ERROR, setup::name, _GLFWmonitor::name, NULL, outputListener, and create_symbols_file::version.
Referenced by registryHandleGlobal().
_glfwPlatformFreeMonitor()
void _glfwPlatformFreeMonitor (_GLFWmonitor * monitor)
_glfwPlatformGetMonitorPos()
void _glfwPlatformGetMonitorPos (_GLFWmonitor * monitor, int * xpos, int * ypos)
_glfwPlatformGetMonitorContentScale()
void _glfwPlatformGetMonitorContentScale (_GLFWmonitor * monitor, float * xscale, float * yscale)
_glfwPlatformGetVideoModes()
GLFWvidmode* _glfwPlatformGetVideoModes (_GLFWmonitor * monitor, int * found)
References _GLFWmonitor::modeCount, and _GLFWmonitor::modes.
_glfwPlatformGetVideoMode()
void _glfwPlatformGetVideoMode (_GLFWmonitor * monitor, GLFWvidmode * mode)
References _GLFWmonitor::currentMode, mode(), and _GLFWmonitor::modes.
_glfwPlatformGetGammaRamp()
void _glfwPlatformGetGammaRamp (_GLFWmonitor * monitor, GLFWgammaramp * ramp)
References _glfwInputError(), and GLFW_PLATFORM_ERROR.
_glfwPlatformSetGammaRamp()
void _glfwPlatformSetGammaRamp (_GLFWmonitor * monitor, const GLFWgammaramp * ramp)
References _glfwInputError(), and GLFW_PLATFORM_ERROR.
glfwGetWaylandMonitor()
GLFWAPI struct wl_output* glfwGetWaylandMonitor (GLFWmonitor * handle)
References _GLFW_REQUIRE_INIT_OR_RETURN, and NULL.
Variable Documentation
outputListener
const struct wl_output_listener outputListener static
Initial value:
= {
    geometry,
    mode,
    done,
    scale,
}
Referenced by _glfwAddOutputWayland().