Aurora Framework: AuroraFW::GEngine::ImGuiLoader Class Reference
AuroraFW::GEngine::ImGuiLoader Class Reference abstract
Public Member Functions
virtual bool createDeviceObjects ()=0
virtual void invalidateDeviceObjects ()=0
void newFrame ()
virtual void renderDrawLists (ImDrawData *)=0
void Unload ()
Static Public Member Functions
static ImGuiLoader * Load (Window *, InputManager *)
Member Function Documentation
Load()
ImGuiLoader * AuroraFW::GEngine::ImGuiLoader::Load (Window * win, InputManager * input) static
References AFW_CALLBACK, AFW_NEW, AFW_NULLPTR, ImGuiIO::ClipboardUserData, ImGuiIO::GetClipboardTextFn, ImGui::GetIO(), AuroraFW::GEngine::API::Context::getRenderAPI(), ImGuiIO::ImeWindowHandle, ImGuiKey_A, ImGuiKey_Backspace, ImGuiKey_C, ImGuiKey_Delete, ImGuiKey_DownArrow, ImGuiKey_End, ImGuiKey_Enter, ImGuiKey_Escape, ImGuiKey_Home, ImGuiKey_Insert, ImGuiKey_LeftArrow, ImGuiKey_PageDown, ImGuiKey_PageUp, ImGuiKey_RightArrow, ImGuiKey_Space, ImGuiKey_Tab, ImGuiKey_UpArrow, ImGuiKey_V, ImGuiKey_X, ImGuiKey_Y, ImGuiKey_Z, ImGuiMouseCursor_Arrow, ImGuiMouseCursor_ResizeAll, ImGuiMouseCursor_ResizeEW, ImGuiMouseCursor_ResizeNESW, ImGuiMouseCursor_ResizeNS, ImGuiMouseCursor_ResizeNWSE, ImGuiMouseCursor_TextInput, ImGuiIO::KeyMap, OpenGL, renderDrawLists(), ImGuiIO::RenderDrawListsFn, ImGuiIO::SetClipboardTextFn, and AuroraFW::GEngine::Window::window.
Unload()
void AuroraFW::GEngine::ImGuiLoader::Unload ()
References ImGuiMouseCursor_Count_, invalidateDeviceObjects(), and memset().
newFrame()
void AuroraFW::GEngine::ImGuiLoader::newFrame ()
References ImGuiIO::ConfigFlags, ImGuiIO::DeltaTime, ImGuiIO::DisplayFramebufferScale, ImGuiIO::DisplaySize, FLT_MAX, ImGui::GetIO(), ImGui::GetMouseCursor(), ImGuiConfigFlags_NavEnableGamepad, ImGuiMouseCursor_Arrow, ImGuiMouseCursor_None, ImGuiNavInput_Activate, ImGuiNavInput_Cancel, ImGuiNavInput_DpadDown, ImGuiNavInput_DpadLeft, ImGuiNavInput_DpadRight, ImGuiNavInput_DpadUp, ImGuiNavInput_FocusNext, ImGuiNavInput_FocusPrev, ImGuiNavInput_Input, ImGuiNavInput_LStickDown, ImGuiNavInput_LStickLeft, ImGuiNavInput_LStickRight, ImGuiNavInput_LStickUp, ImGuiNavInput_Menu, ImGuiNavInput_TweakFast, ImGuiNavInput_TweakSlow, MAP_ANALOG, MAP_BUTTON, memset(), ImGuiIO::MouseDown, ImGuiIO::MouseDrawCursor, ImGuiIO::MousePos, ImGuiIO::NavInputs, ImGui::NewFrame(), ImGuiIO::WantMoveMouse, ImVec2::x, and ImVec2::y.
createDeviceObjects()
virtual bool AuroraFW::GEngine::ImGuiLoader::createDeviceObjects () pure virtual
Implemented in AuroraFW::GEngine::GLImGuiLoader.
invalidateDeviceObjects()
virtual void AuroraFW::GEngine::ImGuiLoader::invalidateDeviceObjects () pure virtual
Implemented in AuroraFW::GEngine::GLImGuiLoader.
Referenced by Unload().
renderDrawLists()
virtual void AuroraFW::GEngine::ImGuiLoader::renderDrawLists (ImDrawData *) pure virtual
Implemented in AuroraFW::GEngine::GLImGuiLoader.
Referenced by Load().
The documentation for this class was generated from the following files:
core/include/AuroraFW/GEngine/ImGui/Loader.h
Loader.cpp