Aurora Framework: lpc.c File Reference
lpc.c File Reference
Macros
#define NEXTI sl = *++sp
#define SCALE(n)
#define STEP(k) L_ACF [k] += (int32_t) (sl * sp [- (k)]) ;
#define STEP(A, B, MAC, MIC)
Functions
static void Autocorrelation (int16_t *s, int32_t *L_ACF)
static void Fast_Autocorrelation (int16_t *s, int32_t *L_ACF)
void Gsm_LPC_Analysis (struct gsm_state *S, int16_t *s, int16_t *LARc)
static void Quantization_and_coding (register int16_t *LAR)
static void Reflection_coefficients (int32_t *L_ACF, register int16_t *r)
static void Transformation_to_Log_Area_Ratios (register int16_t *r)
Macro Definition Documentation
SCALE
#define SCALE (n)
Value:
case n: for (k = 0 ; k <= 159 ; k++) \
            float_s [k] = (float)   \
                (s [k] = GSM_MULT_R (s [k], 16384 >> (n-1))) ;\
        break ;
Referenced by Autocorrelation().
STEP [1/2]
#define STEP (k) L_ACF [k] += (int32_t) (sl * sp [- (k)]) ;
Referenced by Autocorrelation(), and Quantization_and_coding().
NEXTI
#define NEXTI sl = *++sp
Referenced by Autocorrelation().
STEP [2/2]
#define STEP (A, B, MAC, MIC)
Value:
temp = GSM_MULT (A, *LAR) ; \
        temp = GSM_ADD (temp, B) ;  \
        temp = GSM_ADD (temp, 256) ;    \
        temp = SASR_W (temp, 9) ;   \
        *LAR = temp > MAC ? MAC - MIC : (temp < MIC ? 0 : temp - MIC) ; \
        LAR++ ;
Function Documentation
Autocorrelation()
static void Autocorrelation (int16_t * s, int32_t * L_ACF) static
References GSM_ABS(), gsm_norm(), NEXTI, SASL_L(), SASL_W(), SCALE, and STEP.
Referenced by Gsm_LPC_Analysis().
Fast_Autocorrelation()
static void Fast_Autocorrelation (int16_t * s, int32_t * L_ACF) static
References MAX_LONGWORD, and scale().
Referenced by Gsm_LPC_Analysis().
Reflection_coefficients()
static void Reflection_coefficients (int32_t * L_ACF, register int16_t * r) static
References GSM_ABS(), GSM_ADD(), gsm_div(), GSM_MULT_R(), gsm_norm(), memset(), MIN_WORD, SASL_L(), and SASR_L().
Referenced by Gsm_LPC_Analysis().
Transformation_to_Log_Area_Ratios()
static void Transformation_to_Log_Area_Ratios (register int16_t * r) static
References GSM_ABS(), and MIN_WORD.
Referenced by Gsm_LPC_Analysis().
Quantization_and_coding()
static void Quantization_and_coding (register int16_t * LAR) static
References STEP.
Referenced by Gsm_LPC_Analysis().
Gsm_LPC_Analysis()
void Gsm_LPC_Analysis (struct gsm_state * S, int16_t * s, int16_t * LARc)
References Autocorrelation(), Fast_Autocorrelation(), Quantization_and_coding(), Reflection_coefficients(), and Transformation_to_Log_Area_Ratios().
Referenced by Gsm_Coder().