Aurora Framework: simple.c File Reference
simple.c File Reference
Functions
static void display (void)
int main (int argc, char **argv)
static void reshape (int w, int h)
Variables
static int height = 600
static int width = 600
Function Documentation
display()
static void display (void) static
References GL_COLOR_BUFFER_BIT, GL_DEPTH_BUFFER_BIT, glClear, and glClearColor.
Referenced by main().
reshape()
static void reshape (int w, int h) static
References GL_DEPTH_TEST, glClearColor, glClearDepth, glEnable, and glViewport.
Referenced by main().
main()
int main (int argc, char ** argv)
References display(), GL_SHADING_LANGUAGE_VERSION, GL_VERSION, glGetString, GLVersion, afwglGLversionStruct::major, afwglGLversionStruct::minor, and reshape().
Variable Documentation
width
int width = 600 static
height
int height = 600 static