Aurora Framework: AuroraFW::AudioManager::AudioSource Struct Reference
AuroraFW::AudioManager::AudioSource Struct Reference
A struct representing an audio source.
Public Member Functions
AudioSource ()
Constructs an AudioSource at (0, 0, 0) coordinates.
AudioSource (const Math::Vector3D)
Constructs an AudioSource at the coordinates of the given vector.
AudioSource (const float, const float, const float)
Constructs an AudioSource at the coordinates given by the three variables.
AudioSource (const AudioSource &)
Copy constructor.
void calculateValues ()
Notifies the system that the user changed some 3D values, and recalculates the 3D effect.
float getMaxDistance ()
Gets the maximum distance for the audio source.
float getMedDistance ()
Gets the medium distance for the audio source.
float getPanning ()
Gets the calculated panning for the 3D effect.
Math::Vector3D getPosition ()
Gets the audio source's position.
float getStrength ()
Gets the calculated strength of the audio source.
void setMaxDistance (float)
Sets the maximum distance, specified in WU: it defines the distance at which the sound will no longer be audible.
void setMedDistance (float)
Sets the medium distance, specified in WU: it defines at which distance the sound loses it's strength to 50%.
void setPosition (Math::Vector3D)
Sets the position of the audio source.
Public Attributes
AudioFallout falloutType
The desired AudioFallout type.
Detailed Description
A struct representing an audio source.
A class that represents an audio source in 3D space, used to calculate 3D effects.
Since
snapshot20180330
Constructor & Destructor Documentation
AudioSource() [1/4]
AuroraFW::AudioManager::AudioSource::AudioSource ()
Constructs an AudioSource at (0, 0, 0) coordinates.
See also
AudioSource(const Math::Vector3D)
AudioSource(const float , const float , const float)
Since
snapshot20180330
References calculateValues().
AudioSource() [2/4]
AuroraFW::AudioManager::AudioSource::AudioSource (const Math::Vector3D vec)
Constructs an AudioSource at the coordinates of the given vector.
Parameters
vec The Vector3D indicating the coordinates.
See also
AudioSource()
AudioSource(const float , const float , const float)
Since
snapshot20180330
References calculateValues().
AudioSource() [3/4]
AuroraFW::AudioManager::AudioSource::AudioSource (const float x, const float y, const float z)
Constructs an AudioSource at the coordinates given by the three variables.
Parameters
xyz The 3D coordinates for, respectively, X, Y and Z axis.
See also
AudioSource()
AudioSource(const Math::Vector3D)
Since
snapshot20180330
References calculateValues().
AudioSource() [4/4]
AuroraFW::AudioManager::AudioSource::AudioSource (const AudioSource & audioSource)
Copy constructor.
Since
snapshot20180330
References calculateValues().
Member Function Documentation
setPosition()
void AuroraFW::AudioManager::AudioSource::setPosition (Math::Vector3D position)
Sets the position of the audio source.
Parameters
position The Vector3D indicating the new coordinates.
Since
snapshot20180330
setMedDistance()
void AuroraFW::AudioManager::AudioSource::setMedDistance (float medDistance)
Sets the medium distance, specified in WU: it defines at which distance the sound loses it's strength to 50%.
Parameters
medDistance The medium distance from the source's center.
See also
setMaxDistance(float)
Since
snapshot20180330
setMaxDistance()
void AuroraFW::AudioManager::AudioSource::setMaxDistance (float maxDistance)
Sets the maximum distance, specified in WU: it defines the distance at which the sound will no longer be audible.
Parameters
maxDistance The maximum distance from the source's center.
See also
setMedDistance(float)
Since
snapshot20180330
getPanning()
float AuroraFW::AudioManager::AudioSource::getPanning ()
Gets the calculated panning for the 3D effect.
Returns
A value between -1 and 1: -1 means only audible on the left ear; 1 mean only audible on the right ear; 0 means an equilibrium between the two ears.
See also
getStrength()
Since
snapshot20180330
getStrength()
float AuroraFW::AudioManager::AudioSource::getStrength ()
Gets the calculated strength of the audio source.
Returns
A value between 0 and 1: 1 means maximum strength; 0 means the audio is inaudible.
See also
getPanning()
Since
snapshot20180330
getPosition()
Math::Vector3D AuroraFW::AudioManager::AudioSource::getPosition ()
Gets the audio source's position.
Returns
The Vector3D representing the 3D coordinates.
Since
snapshot20180330
getMedDistance()
float AuroraFW::AudioManager::AudioSource::getMedDistance ()
Gets the medium distance for the audio source.
Returns
The medium distance from the source's center.
See also
getMaxDistance()
Since
snapshot20180330
getMaxDistance()
float AuroraFW::AudioManager::AudioSource::getMaxDistance ()
Gets the maximum distance for the audio source.
Returns
The maximum distance from the source's center.
See also
getMedDistance()
Since
snapshot20180330
calculateValues()
void AuroraFW::AudioManager::AudioSource::calculateValues ()
Notifies the system that the user changed some 3D values, and recalculates the 3D effect.
Note
You only need to call this method if you changed any 3D value using local methods; the values given in the constructor are calculated automatically.
Since
snapshot20180330
Referenced by AudioSource().
Member Data Documentation
falloutType
AudioFallout AuroraFW::AudioManager::AudioSource::falloutType
The desired AudioFallout type.
Since
snapshot20180330
The documentation for this struct was generated from the following files:
AudioOutput.h
AudioOutput.cpp