Aurora Framework: Window.c File Reference
Mir/Window.c File Reference
Classes
struct EventNode
Typedefs
typedef struct EventNode EventNode
Functions
void _glfwDeleteEventQueueMir (EventQueue *queue)
void _glfwInitEventQueueMir (EventQueue *queue)
int _glfwPlatformCreateCursor (_GLFWcursor *cursor, const GLFWimage *image, int xhot, int yhot)
int _glfwPlatformCreateStandardCursor (_GLFWcursor *cursor, int shape)
int _glfwPlatformCreateWindow (_GLFWwindow *window, const _GLFWwndconfig *wndconfig, const _GLFWctxconfig *ctxconfig, const _GLFWfbconfig *fbconfig)
VkResult _glfwPlatformCreateWindowSurface (VkInstance instance, _GLFWwindow *window, const VkAllocationCallbacks *allocator, VkSurfaceKHR *surface)
void _glfwPlatformDestroyCursor (_GLFWcursor *cursor)
void _glfwPlatformDestroyWindow (_GLFWwindow *window)
void _glfwPlatformFocusWindow (_GLFWwindow *window)
int _glfwPlatformFramebufferTransparent (_GLFWwindow *window)
const char * _glfwPlatformGetClipboardString (void)
void _glfwPlatformGetCursorPos (_GLFWwindow *window, double *xpos, double *ypos)
void _glfwPlatformGetFramebufferSize (_GLFWwindow *window, int *width, int *height)
int _glfwPlatformGetKeyScancode (int key)
int _glfwPlatformGetPhysicalDevicePresentationSupport (VkInstance instance, VkPhysicalDevice device, uint32_t queuefamily)
void _glfwPlatformGetRequiredInstanceExtensions (char **extensions)
const char * _glfwPlatformGetScancodeName (int scancode)
void _glfwPlatformGetWindowContentScale (_GLFWwindow *window, float *xscale, float *yscale)
void _glfwPlatformGetWindowFrameSize (_GLFWwindow *window, int *left, int *top, int *right, int *bottom)
float _glfwPlatformGetWindowOpacity (_GLFWwindow *window)
void _glfwPlatformGetWindowPos (_GLFWwindow *window, int *xpos, int *ypos)
void _glfwPlatformGetWindowSize (_GLFWwindow *window, int *width, int *height)
void _glfwPlatformHideWindow (_GLFWwindow *window)
void _glfwPlatformIconifyWindow (_GLFWwindow *window)
void _glfwPlatformMaximizeWindow (_GLFWwindow *window)
void _glfwPlatformPollEvents (void)
void _glfwPlatformPostEmptyEvent (void)
void _glfwPlatformRequestWindowAttention (_GLFWwindow *window)
void _glfwPlatformRestoreWindow (_GLFWwindow *window)
void _glfwPlatformSetClipboardString (const char *string)
void _glfwPlatformSetCursor (_GLFWwindow *window, _GLFWcursor *cursor)
void _glfwPlatformSetCursorMode (_GLFWwindow *window, int mode)
void _glfwPlatformSetCursorPos (_GLFWwindow *window, double xpos, double ypos)
void _glfwPlatformSetWindowAspectRatio (_GLFWwindow *window, int numer, int denom)
void _glfwPlatformSetWindowDecorated (_GLFWwindow *window, GLFWbool enabled)
void _glfwPlatformSetWindowFloating (_GLFWwindow *window, GLFWbool enabled)
void _glfwPlatformSetWindowIcon (_GLFWwindow *window, int count, const GLFWimage *images)
void _glfwPlatformSetWindowMonitor (_GLFWwindow *window, _GLFWmonitor *monitor, int xpos, int ypos, int width, int height, int refreshRate)
void _glfwPlatformSetWindowOpacity (_GLFWwindow *window, float opacity)
void _glfwPlatformSetWindowPos (_GLFWwindow *window, int xpos, int ypos)
void _glfwPlatformSetWindowResizable (_GLFWwindow *window, GLFWbool enabled)
void _glfwPlatformSetWindowSize (_GLFWwindow *window, int width, int height)
void _glfwPlatformSetWindowSizeLimits (_GLFWwindow *window, int minwidth, int minheight, int maxwidth, int maxheight)
void _glfwPlatformSetWindowTitle (_GLFWwindow *window, const char *title)
void _glfwPlatformShowWindow (_GLFWwindow *window)
void _glfwPlatformWaitEvents (void)
void _glfwPlatformWaitEventsTimeout (double timeout)
int _glfwPlatformWindowFocused (_GLFWwindow *window)
int _glfwPlatformWindowHovered (_GLFWwindow *window)
int _glfwPlatformWindowIconified (_GLFWwindow *window)
int _glfwPlatformWindowMaximized (_GLFWwindow *window)
int _glfwPlatformWindowVisible (_GLFWwindow *window)
static void addNewEvent (MirWindow *window, const MirEvent *event, void *context)
static GLFWbool createWindow (_GLFWwindow *window)
static void deleteNode (EventQueue *queue, EventNode *node)
static EventNode * dequeueEvent (EventQueue *queue)
static GLFWbool emptyEventQueue (EventQueue *queue)
static void enqueueEvent (const MirEvent *event, _GLFWwindow *context)
static MirPixelFormat findValidPixelFormat (void)
static const char * getSystemCursorName (int shape)
GLFWAPI MirConnection * glfwGetMirDisplay (void)
GLFWAPI MirWindow * glfwGetMirWindow (GLFWwindow *handle)
static void handleEvent (const MirEvent *event, _GLFWwindow *window)
static void handleInput (const MirInputEvent *input_event, _GLFWwindow *window)
static void handleKeyEvent (const MirKeyboardEvent *key_event, _GLFWwindow *window)
static void handlePointerButton (_GLFWwindow *window, int pressed, const MirPointerEvent *pointer_event)
static void handlePointerEvent (const MirPointerEvent *pointer_event, _GLFWwindow *window)
static void handlePointerMotion (_GLFWwindow *window, const MirPointerEvent *pointer_event)
static int mirModToGLFWMod (uint32_t mods)
static EventNode * newEventNode (const MirEvent *event, _GLFWwindow *context)
static void setCursorNameForWindow (MirWindow *window, char const *name)
static void setWindowConfinement (_GLFWwindow *window, MirPointerConfinementState state)
static int toGLFWKeyCode (uint32_t key)
Typedef Documentation
EventNode
typedef struct EventNode EventNode
Function Documentation
deleteNode()
static void deleteNode (EventQueue * queue, EventNode * node) static
Referenced by _glfwDeleteEventQueueMir(), and _glfwPlatformPollEvents().
emptyEventQueue()
static GLFWbool emptyEventQueue (EventQueue * queue) static
References NULL.
Referenced by _glfwPlatformWaitEvents(), and _glfwPlatformWaitEventsTimeout().
newEventNode()
static EventNode* newEventNode (const MirEvent * event, _GLFWwindow * context) static
Referenced by enqueueEvent().
enqueueEvent()
static void enqueueEvent (const MirEvent * event, _GLFWwindow * context) static
References _glfw, and newEventNode().
Referenced by addNewEvent().
dequeueEvent()
static EventNode* dequeueEvent (EventQueue * queue) static
References _glfw, and NULL.
Referenced by _glfwPlatformPollEvents().
findValidPixelFormat()
static MirPixelFormat findValidPixelFormat (void) static
References _glfw.
Referenced by createWindow().
mirModToGLFWMod()
static int mirModToGLFWMod (uint32_t mods) static
References GLFW_MOD_ALT, GLFW_MOD_CAPS_LOCK, GLFW_MOD_CONTROL, GLFW_MOD_NUM_LOCK, GLFW_MOD_SHIFT, and GLFW_MOD_SUPER.
Referenced by handleKeyEvent(), and handlePointerButton().
toGLFWKeyCode()
static int toGLFWKeyCode (uint32_t key) static
References _glfw, and GLFW_KEY_UNKNOWN.
Referenced by handleKeyEvent().
handleKeyEvent()
static void handleKeyEvent (const MirKeyboardEvent * key_event, _GLFWwindow * window) static
References _glfwInputChar(), _glfwInputKey(), _glfwKeySym2Unicode(), GLFW_MOD_ALT, GLFW_MOD_CONTROL, GLFW_PRESS, GLFW_RELEASE, mirModToGLFWMod(), and toGLFWKeyCode().
Referenced by handleInput().
handlePointerButton()
static void handlePointerButton (_GLFWwindow * window, int pressed, const MirPointerEvent * pointer_event) static
References _glfwInputMouseClick(), GLFW_MOUSE_BUTTON_4, GLFW_MOUSE_BUTTON_5, GLFW_MOUSE_BUTTON_LEFT, GLFW_MOUSE_BUTTON_MIDDLE, GLFW_MOUSE_BUTTON_RIGHT, and mirModToGLFWMod().
Referenced by handlePointerEvent().
handlePointerMotion()
static void handlePointerMotion (_GLFWwindow * window, const MirPointerEvent * pointer_event) static
References _glfw, _glfwInputCursorPos(), _glfwInputScroll(), _GLFWwindow::cursorMode, GLFW_CURSOR_DISABLED, _GLFWwindow::virtualCursorPosX, and _GLFWwindow::virtualCursorPosY.
Referenced by handlePointerEvent().
handlePointerEvent()
static void handlePointerEvent (const MirPointerEvent * pointer_event, _GLFWwindow * window) static
References GLFW_PRESS, GLFW_RELEASE, handlePointerButton(), and handlePointerMotion().
Referenced by handleInput().
handleInput()
static void handleInput (const MirInputEvent * input_event, _GLFWwindow * window) static
References handleKeyEvent(), and handlePointerEvent().
Referenced by handleEvent().
handleEvent()
static void handleEvent (const MirEvent * event, _GLFWwindow * window) static
References handleInput().
Referenced by _glfwPlatformPollEvents().
addNewEvent()
static void addNewEvent (MirWindow * window, const MirEvent * event, void * context) static
References enqueueEvent().
Referenced by createWindow().
createWindow()
static GLFWbool createWindow (_GLFWwindow * window) static
References _glfw, _glfwInputError(), addNewEvent(), findValidPixelFormat(), GLFW_FALSE, GLFW_PLATFORM_ERROR, and GLFW_TRUE.
Referenced by _glfwPlatformCreateWindow().
setWindowConfinement()
static void setWindowConfinement (_GLFWwindow * window, MirPointerConfinementState state) static
References _glfw.
Referenced by _glfwPlatformSetCursorMode().
_glfwInitEventQueueMir()
void _glfwInitEventQueueMir (EventQueue * queue)
Referenced by _glfwPlatformInit().
_glfwDeleteEventQueueMir()
void _glfwDeleteEventQueueMir (EventQueue * queue)
References deleteNode(), and NULL.
Referenced by _glfwPlatformTerminate().
_glfwPlatformCreateWindow()
int _glfwPlatformCreateWindow (_GLFWwindow * window, const _GLFWwndconfig * wndconfig, const _GLFWctxconfig * ctxconfig, const _GLFWfbconfig * fbconfig)
References _glfwCreateContextEGL(), _glfwCreateContextOSMesa(), _glfwInitEGL(), _glfwInitOSMesa(), _glfwInputError(), _glfwPlatformGetVideoMode(), _GLFWctxconfig::client, createWindow(), GLFW_EGL_CONTEXT_API, GLFW_FALSE, GLFW_NATIVE_CONTEXT_API, GLFW_NO_API, GLFW_OSMESA_CONTEXT_API, GLFW_PLATFORM_ERROR, GLFW_TRUE, _GLFWwndconfig::height, mode(), _GLFWwindow::monitor, NULL, _GLFWctxconfig::source, and _GLFWwndconfig::width.
_glfwPlatformDestroyWindow()
void _glfwPlatformDestroyWindow (_GLFWwindow * window)
References _glfw, _GLFWwindow::context, _GLFWcontext::destroy, and NULL.
_glfwPlatformSetWindowTitle()
void _glfwPlatformSetWindowTitle (_GLFWwindow * window, const char * title)
References _glfw.
_glfwPlatformSetWindowIcon()
void _glfwPlatformSetWindowIcon (_GLFWwindow * window, int count, const GLFWimage * images)
References _glfwInputError(), and GLFW_PLATFORM_ERROR.
_glfwPlatformSetWindowSize()
void _glfwPlatformSetWindowSize (_GLFWwindow * window, int width, int height)
References _glfw, height, and width.
_glfwPlatformSetWindowSizeLimits()
void _glfwPlatformSetWindowSizeLimits (_GLFWwindow * window, int minwidth, int minheight, int maxwidth, int maxheight)
References _glfw.
_glfwPlatformSetWindowAspectRatio()
void _glfwPlatformSetWindowAspectRatio (_GLFWwindow * window, int numer, int denom)
References _glfwInputError(), and GLFW_PLATFORM_ERROR.
_glfwPlatformSetWindowPos()
void _glfwPlatformSetWindowPos (_GLFWwindow * window, int xpos, int ypos)
References _glfwInputError(), and GLFW_PLATFORM_ERROR.
_glfwPlatformGetWindowFrameSize()
void _glfwPlatformGetWindowFrameSize (_GLFWwindow * window, int * left, int * top, int * right, int * bottom)
References _glfwInputError(), and GLFW_PLATFORM_ERROR.
_glfwPlatformGetWindowPos()
void _glfwPlatformGetWindowPos (_GLFWwindow * window, int * xpos, int * ypos)
References _glfwInputError(), and GLFW_PLATFORM_ERROR.
_glfwPlatformGetWindowSize()
void _glfwPlatformGetWindowSize (_GLFWwindow * window, int * width, int * height)
References height, and width.
_glfwPlatformGetWindowContentScale()
void _glfwPlatformGetWindowContentScale (_GLFWwindow * window, float * xscale, float * yscale)
_glfwPlatformIconifyWindow()
void _glfwPlatformIconifyWindow (_GLFWwindow * window)
References _glfw.
_glfwPlatformRestoreWindow()
void _glfwPlatformRestoreWindow (_GLFWwindow * window)
References _glfw.
_glfwPlatformMaximizeWindow()
void _glfwPlatformMaximizeWindow (_GLFWwindow * window)
References _glfw.
_glfwPlatformHideWindow()
void _glfwPlatformHideWindow (_GLFWwindow * window)
References _glfw.
_glfwPlatformShowWindow()
void _glfwPlatformShowWindow (_GLFWwindow * window)
References _glfw.
_glfwPlatformRequestWindowAttention()
void _glfwPlatformRequestWindowAttention (_GLFWwindow * window)
References _glfwInputError(), and GLFW_PLATFORM_ERROR.
_glfwPlatformFocusWindow()
void _glfwPlatformFocusWindow (_GLFWwindow * window)
References _glfwInputError(), and GLFW_PLATFORM_ERROR.
_glfwPlatformSetWindowMonitor()
void _glfwPlatformSetWindowMonitor (_GLFWwindow * window, _GLFWmonitor * monitor, int xpos, int ypos, int width, int height, int refreshRate)
References _glfwInputError(), and GLFW_PLATFORM_ERROR.
_glfwPlatformWindowFocused()
int _glfwPlatformWindowFocused (_GLFWwindow * window)
_glfwPlatformWindowIconified()
int _glfwPlatformWindowIconified (_GLFWwindow * window)
References _glfwInputError(), GLFW_FALSE, and GLFW_PLATFORM_ERROR.
_glfwPlatformWindowVisible()
int _glfwPlatformWindowVisible (_GLFWwindow * window)
_glfwPlatformWindowMaximized()
int _glfwPlatformWindowMaximized (_GLFWwindow * window)
_glfwPlatformWindowHovered()
int _glfwPlatformWindowHovered (_GLFWwindow * window)
References _glfwInputError(), GLFW_FALSE, and GLFW_PLATFORM_ERROR.
_glfwPlatformFramebufferTransparent()
int _glfwPlatformFramebufferTransparent (_GLFWwindow * window)
References _glfwInputError(), GLFW_FALSE, and GLFW_PLATFORM_ERROR.
_glfwPlatformSetWindowResizable()
void _glfwPlatformSetWindowResizable (_GLFWwindow * window, GLFWbool enabled)
References _glfwInputError(), and GLFW_PLATFORM_ERROR.
_glfwPlatformSetWindowDecorated()
void _glfwPlatformSetWindowDecorated (_GLFWwindow * window, GLFWbool enabled)
References _glfwInputError(), and GLFW_PLATFORM_ERROR.
_glfwPlatformSetWindowFloating()
void _glfwPlatformSetWindowFloating (_GLFWwindow * window, GLFWbool enabled)
References _glfwInputError(), and GLFW_PLATFORM_ERROR.
_glfwPlatformGetWindowOpacity()
float _glfwPlatformGetWindowOpacity (_GLFWwindow * window)
_glfwPlatformSetWindowOpacity()
void _glfwPlatformSetWindowOpacity (_GLFWwindow * window, float opacity)
_glfwPlatformPollEvents()
void _glfwPlatformPollEvents (void)
References _glfw, deleteNode(), dequeueEvent(), handleEvent(), and NULL.
Referenced by _glfwPlatformWaitEvents(), and _glfwPlatformWaitEventsTimeout().
_glfwPlatformWaitEvents()
void _glfwPlatformWaitEvents (void)
References _glfw, _glfwPlatformPollEvents(), and emptyEventQueue().
_glfwPlatformWaitEventsTimeout()
void _glfwPlatformWaitEventsTimeout (double timeout)
References _glfw, _glfwPlatformPollEvents(), and emptyEventQueue().
_glfwPlatformPostEmptyEvent()
void _glfwPlatformPostEmptyEvent (void)
_glfwPlatformGetFramebufferSize()
void _glfwPlatformGetFramebufferSize (_GLFWwindow * window, int * width, int * height)
References height, and width.
_glfwPlatformCreateCursor()
int _glfwPlatformCreateCursor (_GLFWcursor * cursor, const GLFWimage * image, int xhot, int yhot)
References _glfw, GLFW_TRUE, GLFWimage::height, GLFWimage::pixels, and GLFWimage::width.
getSystemCursorName()
static const char* getSystemCursorName (int shape) static
References GLFW_ARROW_CURSOR, GLFW_CROSSHAIR_CURSOR, GLFW_HAND_CURSOR, GLFW_HRESIZE_CURSOR, GLFW_IBEAM_CURSOR, GLFW_VRESIZE_CURSOR, and NULL.
Referenced by _glfwPlatformCreateStandardCursor().
_glfwPlatformCreateStandardCursor()
int _glfwPlatformCreateStandardCursor (_GLFWcursor * cursor, int shape)
References getSystemCursorName(), and NULL.
_glfwPlatformDestroyCursor()
void _glfwPlatformDestroyCursor (_GLFWcursor * cursor)
setCursorNameForWindow()
static void setCursorNameForWindow (MirWindow * window, char const * name) static
References _glfw, and setup::name.
Referenced by _glfwPlatformSetCursor(), and _glfwPlatformSetCursorMode().
_glfwPlatformSetCursor()
void _glfwPlatformSetCursor (_GLFWwindow * window, _GLFWcursor * cursor)
References setCursorNameForWindow().
Referenced by _glfwPlatformSetCursorMode().
_glfwPlatformGetCursorPos()
void _glfwPlatformGetCursorPos (_GLFWwindow * window, double * xpos, double * ypos)
References _glfwInputError(), and GLFW_PLATFORM_ERROR.
_glfwPlatformSetCursorPos()
void _glfwPlatformSetCursorPos (_GLFWwindow * window, double xpos, double ypos)
References _glfwInputError(), and GLFW_PLATFORM_ERROR.
_glfwPlatformSetCursorMode()
void _glfwPlatformSetCursorMode (_GLFWwindow * window, int mode)
References _glfw, _glfwPlatformSetCursor(), _GLFWwindow::cursorMode, GLFW_CURSOR_DISABLED, GLFW_CURSOR_HIDDEN, GLFW_CURSOR_NORMAL, mode(), NULL, setCursorNameForWindow(), and setWindowConfinement().
_glfwPlatformGetScancodeName()
const char* _glfwPlatformGetScancodeName (int scancode)
References _glfwInputError(), GLFW_PLATFORM_ERROR, and NULL.
_glfwPlatformGetKeyScancode()
int _glfwPlatformGetKeyScancode (int key)
References _glfw.
_glfwPlatformSetClipboardString()
void _glfwPlatformSetClipboardString (const char * string)
References _glfwInputError(), and GLFW_PLATFORM_ERROR.
_glfwPlatformGetClipboardString()
const char* _glfwPlatformGetClipboardString (void)
References _glfwInputError(), GLFW_PLATFORM_ERROR, and NULL.
_glfwPlatformGetRequiredInstanceExtensions()
void _glfwPlatformGetRequiredInstanceExtensions (char ** extensions)
References _glfw, _GLFWlibrary::KHR_surface, and _GLFWlibrary::vk.
_glfwPlatformGetPhysicalDevicePresentationSupport()
int _glfwPlatformGetPhysicalDevicePresentationSupport (VkInstance instance, VkPhysicalDevice device, uint32_t queuefamily)
References _glfw, _glfwInputError(), GLFW_API_UNAVAILABLE, GLFW_FALSE, and vkGetInstanceProcAddr().
_glfwPlatformCreateWindowSurface()
VkResult _glfwPlatformCreateWindowSurface (VkInstance instance, _GLFWwindow * window, const VkAllocationCallbacks * allocator, VkSurfaceKHR * surface)
References _glfw, _glfwGetVulkanResultString(), _glfwInputError(), VkMirWindowCreateInfoKHR::connection, GLFW_API_UNAVAILABLE, GLFW_PLATFORM_ERROR, memset(), VkMirWindowCreateInfoKHR::mirWindow, VkMirWindowCreateInfoKHR::sType, VK_ERROR_EXTENSION_NOT_PRESENT, VK_STRUCTURE_TYPE_MIR_SURFACE_CREATE_INFO_KHR, and vkGetInstanceProcAddr().
glfwGetMirDisplay()
GLFWAPI MirConnection* glfwGetMirDisplay (void)
References _glfw, _GLFW_REQUIRE_INIT_OR_RETURN, and NULL.
glfwGetMirWindow()
GLFWAPI MirWindow* glfwGetMirWindow (GLFWwindow * handle)
References _GLFW_REQUIRE_INIT_OR_RETURN, and NULL.