Aurora Framework: ImGuiTextBuffer Struct Reference
ImGuiTextBuffer Struct Reference
Public Member Functions
ImGuiTextBuffer ()
IMGUI_API void appendf (const char *fmt,...) IM_FMTARGS(2)
IMGUI_API void appendfv (const char *fmt, va_list args) IM_FMTLIST(2)
const char * begin () const
const char * c_str () const
void clear ()
bool empty ()
const char * end () const
char operator[] (int i)
void reserve (int capacity)
int size () const
Public Attributes
ImVector< char > Buf
Constructor & Destructor Documentation
ImGuiTextBuffer()
ImGuiTextBuffer::ImGuiTextBuffer () inline
References ImVector< T >::push_back().
Member Function Documentation
operator[]()
char ImGuiTextBuffer::operator[] (int i) inline
References ImVector< T >::Data.
begin()
const char* ImGuiTextBuffer::begin () const inline
References ImVector< T >::front().
Referenced by ImGui::LogFinish().
end()
const char* ImGuiTextBuffer::end () const inline
References ImVector< T >::back().
size()
int ImGuiTextBuffer::size () const inline
References ImVector< T >::Size.
Referenced by ImGui::LogFinish(), and SettingsHandlerWindow_WriteAll().
empty()
bool ImGuiTextBuffer::empty () inline
References ImVector< T >::Size.
clear()
void ImGuiTextBuffer::clear () inline
References ImVector< T >::clear(), and ImVector< T >::push_back().
Referenced by ImGui::LogFinish().
reserve()
void ImGuiTextBuffer::reserve (int capacity) inline
References ImVector< T >::reserve().
Referenced by SettingsHandlerWindow_WriteAll().
c_str()
const char* ImGuiTextBuffer::c_str () const inline
References ImVector< T >::Data.
appendf()
void ImGuiTextBuffer::appendf (const char * fmt, ...)
Referenced by SettingsHandlerWindow_WriteAll().
appendfv()
void ImGuiTextBuffer::appendfv (const char * fmt, va_list args)
References ImFormatStringV(), NULL, and va_copy.
Referenced by ImGui::LogText().
Member Data Documentation
Buf
ImVector<char> ImGuiTextBuffer::Buf
Referenced by SaveIniSettingsToMemory().
The documentation for this struct was generated from the following files:
ImGui.h
ImGui.cpp