Aurora Framework: chanmap.h File Reference
chanmap.h File Reference
Classes
struct AIFF_CAF_CHANNEL_MAP
Functions
int aiff_caf_find_channel_layout_tag (const int *chan_map, int channels)
const AIFF_CAF_CHANNEL_MAP * aiff_caf_of_channel_layout_tag (int tag)
Function Documentation
aiff_caf_find_channel_layout_tag()
int aiff_caf_find_channel_layout_tag (const int * chan_map, int channels)
References ARRAY_LEN, AIFF_CAF_CHANNEL_MAP::channel_layout_tag, MAP_MAP::len, MAP_MAP::map, map, memcmp(), and NULL.
Referenced by aiff_command(), and caf_command().
aiff_caf_of_channel_layout_tag()
const AIFF_CAF_CHANNEL_MAP* aiff_caf_of_channel_layout_tag (int tag)
References ARRAY_LEN, MAP_MAP::len, MAP_MAP::map, map, and NULL.
Referenced by aiff_read_chanmap(), and caf_read_chanmap().