Aurora Framework: AuroraFW::GEngine Namespace Reference
AuroraFW::GEngine Namespace Reference
Namespaces
API
GL
Vulkan
Classes
class Application
A class representing an AuroraFW graphical application.
class AssetManager
A singleton class used to load any assets needed.
class AssetNotFoundException
An exception to indicate an asset was not found.
class AssetTypeInvalidException
An exception to indicate an invalid asset type (from the enum AssetType)
struct BaseColor
A template struct that represents colors.
class DuplicatedShaderException
class GLBuffer
class GLContext
class GLImGuiLoader
class GLProgram
class GLRenderer
class GLShader
class GLVertexArray
struct GLVertexBufferElement
class GLVertexBufferLayout
class GraphicsContext
class ImGuiLoader
class InputManager
A class that handles user input.
class InvalidShaderException
class Renderable
class Renderer
struct Root
class RTShader
class RTShaderConverter
class RTShaderManager
class RTShaderPipeline
class Shader
class TextureAsset
class VKContext
class VKRenderer
class Window
struct WindowProperties
Typedefs
typedef BaseColor< byte_t > Color
A struct that represents colors 24-bit colors and a 8-bit alpha channel using byte_ts as color components.
typedef BaseColor< float > ColorF
A struct that represents high precision colors 96-bit colors and a 32-bit alpha channel using precision floating point as color components.
Enumerations
enum AssetType {
AssetType::Audio, AssetType::Font, AssetType::GUI, AssetType::Material,
AssetType::Model, AssetType::Terrain, AssetType::Texture, AssetType::Shader
}
An enum to indicate the type of asset wanted.
enum CommonColor : uint32_t {
CommonColor::Black = 0x000000, CommonColor::Red = 0xFF0000, CommonColor::DarkRed = 0x800000, CommonColor::Green = 0x00FF00,
CommonColor::DarkGreen = 0x008000, CommonColor::Blue = 0x0000FF, CommonColor::DarkBlue = 0x000080, CommonColor::Cyan = 0x00FFFF,
CommonColor::DarkCyan = 0x008080, CommonColor::Magenta = 0xFF00FF, CommonColor::DarkMagenta = 0x800080, CommonColor::Yellow = 0xFFFF00,
CommonColor::DarkYellow = 0x808000, CommonColor::White = 0xFFFFFF, CommonColor::DarkGray = 0x808080, CommonColor::LightGray = 0xC0C0C0,
CommonColor::Gray = 0xA0A0A0, CommonColor::Tomato = 0xFF6347, CommonColor::AliceBlue = 0xF0F8FF, CommonColor::AntiqueWhite = 0xFAEBD7,
CommonColor::Aquamarine = 0x7FFFD4, CommonColor::Azure = 0xF0FFFF, CommonColor::Beige = 0xF5F5DC, CommonColor::Bisque = 0xFFE4C4,
CommonColor::BlanchedAlmond = 0xFFEBCD, CommonColor::BlueViolet =0x8A2BE2, CommonColor::Brown = 0x964B00, CommonColor::BurlyWood = 0xDEB887,
CommonColor::CadetBlue = 0x5F9EA0, CommonColor::Chartreuse = 0x7FFF00
}
An enum that stores hex-coded colors to be used generally.
enum InputAction { InputAction::Pressed, InputAction::Released }
enum InputButton {
InputButton::B1, InputButton::B2, InputButton::B3, InputButton::B4,
InputButton::B5, InputButton::B6, InputButton::B7, InputButton::B8,
InputButton::Last = B8, InputButton::Left = B1, InputButton::Right = B2, InputButton::Middle = B3
}
enum InputKey {
InputKey::Unknown = -1, InputKey::Space = 32, InputKey::Apostrophe = 39, InputKey::Comma = 44,
InputKey::Minus, InputKey::Period, InputKey::Slash, InputKey::Num0,
InputKey::Num1, InputKey::Num2, InputKey::Num3, InputKey::Num4,
InputKey::Num5, InputKey::Num6, InputKey::Num7, InputKey::Num8,
InputKey::Num9, InputKey::Semicolon = 59, InputKey::Equal = 61, InputKey::A = 65,
InputKey::B, InputKey::C, InputKey::D, InputKey::E,
InputKey::F, InputKey::G, InputKey::H, InputKey::I,
InputKey::J, InputKey::K, InputKey::L, InputKey::M,
InputKey::N, InputKey::O, InputKey::P, InputKey::Q,
InputKey::R, InputKey::S, InputKey::T, InputKey::U,
InputKey::V, InputKey::W, InputKey::X, InputKey::Y,
InputKey::Z, InputKey::LeftBracket, InputKey::BackSlash, InputKey::RightBracket,
InputKey::GraveAccent = 96, InputKey::World1 = 161, InputKey::World2 = 162, InputKey::Escape = 256,
InputKey::Enter, InputKey::Tab, InputKey::Backspace, InputKey::Insert,
InputKey::Delete, InputKey::Right, InputKey::Left, InputKey::Down,
InputKey::Up, InputKey::PageUp, InputKey::PageDown, InputKey::Home,
InputKey::End, InputKey::CapsLock = 280, InputKey::ScrollLock, InputKey::NumLock,
InputKey::PrintScreen, InputKey::Pause, InputKey::F1 = 290, InputKey::F2,
InputKey::F3, InputKey::F4, InputKey::F5, InputKey::F6,
InputKey::F7, InputKey::F8, InputKey::F9, InputKey::F10,
InputKey::F11, InputKey::F12, InputKey::F13, InputKey::F14,
InputKey::F15, InputKey::F16, InputKey::F17, InputKey::F18,
InputKey::F19, InputKey::F20, InputKey::F21, InputKey::F22,
InputKey::F23, InputKey::F24, InputKey::F25, InputKey::NumPad0 = 320,
InputKey::NumPad1, InputKey::NumPad2, InputKey::NumPad3, InputKey::NumPad4,
InputKey::NumPad5, InputKey::NumPad6, InputKey::NumPad7, InputKey::NumPad8,
InputKey::NumPad9, InputKey::NumPadDecimal, InputKey::NumPadDivide, InputKey::NumPadMultiply,
InputKey::NumPadSubtract, InputKey::NumPadAdd, InputKey::NumPadEnter, InputKey::NumPadEqual,
InputKey::LeftShift = 340, InputKey::LeftControl, InputKey::LeftAlt, InputKey::LeftSuper,
InputKey::RightShift, InputKey::RightControl, InputKey::RightAlt, InputKey::RightSuper,
InputKey::Menu, InputKey::Last = Menu
}
enum InputMod : ushort {
InputMod::Shift = AFW_BIT(1), InputMod::Control = AFW_BIT(2), InputMod::Alt = AFW_BIT(3), InputMod::Super = AFW_BIT(4),
InputMod::CapsLock = AFW_BIT(5), InputMod::NumLock = AFW_BIT(6)
}
enum OrientationMode {
Degree, Degree, Degree, Degree,
Portrait = 0Degree, LandscapeRight = 90Degree, LandscapeLeft = 270Degree
}
enum ProjectionType { Orthographic, Perspective }
Functions
GLenum GLCheckError ()
bool GLLogCall (const char *, const char *file, uint_t)
InputMod operator| (InputMod a, InputMod b)
void setValue (const std::string &, Math::Vector3D &)
void setValue (const std::string &, Math::Vector4D &)
Variables
enum AuroraFW::GEngine::ProjectionType Bottom
enum AuroraFW::GEngine::ProjectionType Far
enum AuroraFW::GEngine::ProjectionType Left
enum AuroraFW::GEngine::ProjectionType Near
enum AuroraFW::GEngine::ProjectionType Right
enum AuroraFW::GEngine::ProjectionType Top
Typedef Documentation
Color
typedef BaseColor<byte_t> AuroraFW::GEngine::Color
A struct that represents colors 24-bit colors and a 8-bit alpha channel using byte_ts as color components.
Since
snapshot20170930
ColorF
typedef BaseColor<float> AuroraFW::GEngine::ColorF
A struct that represents high precision colors 96-bit colors and a 32-bit alpha channel using precision floating point as color components.
Since
snapshot20170930
Enumeration Type Documentation
AssetType
enum AuroraFW::GEngine::AssetType strong
An enum to indicate the type of asset wanted.
Since
snapshot20170930
Enumerator
Audio
An AudioAsset.
Font
A FontAsset.
GUI
A GUIAsset.
Material
A MaterialAsset.
Model
A ModelAsset.
Terrain
A TerainAsset.
Texture
A TextureAsset.
Shader
A ShaderAsset.
CommonColor
enum AuroraFW::GEngine::CommonColor : uint32_t strong
An enum that stores hex-coded colors to be used generally.
Since
snapshot20170930
Enumerator
Black
0x000000 = color
Red
0xFF0000 = color
DarkRed
0x800000 = color
Green
0x00FF00 = color
DarkGreen
0x008000 = color
Blue
0x0000FF = color
DarkBlue
0x000080 = color
Cyan
0x00FFFF = color
DarkCyan
0x008080 = color
Magenta
0xFF00FF = color
DarkMagenta
0x800080 = color
Yellow
0xFFFF00 = color
DarkYellow
0x808000 = color
White
0xFFFFFF = color
DarkGray
0x808080 = color
LightGray
0xC0C0C0 = color
Gray
0xA0A0A0 = color
Tomato
0xFF6347 = color
AliceBlue
0xF0F8FF = color
AntiqueWhite
0xFAEBD7 = color
Aquamarine
0x7FFFD4 = color
Azure
0xF0FFFF = color
Beige
0xF5F5DC = color
Bisque
0xFFE4C4 = color
BlanchedAlmond
0xFFEBCD = color
BlueViolet
0x8A2BE2 = color
Brown
0x964B00 = color
BurlyWood
0xDEB887 = color
CadetBlue
0x5F9EA0 = color
Chartreuse
0x7FFF00 = color
OrientationMode
enum AuroraFW::GEngine::OrientationMode
Enumerator
Degree
Degree
Degree
Degree
Portrait
LandscapeRight
LandscapeLeft
ProjectionType
enum AuroraFW::GEngine::ProjectionType
Enumerator
Orthographic
Perspective
InputAction
enum AuroraFW::GEngine::InputAction strong
Enumerator
Pressed
Released
InputKey
enum AuroraFW::GEngine::InputKey strong
Enumerator
Unknown
Space
Apostrophe
Comma
Minus
Period
Slash
Num0
Num1
Num2
Num3
Num4
Num5
Num6
Num7
Num8
Num9
Semicolon
Equal
A
B
C
D
E
F
G
H
I
J
K
L
M
N
O
P
Q
R
S
T
U
V
W
X
Y
Z
LeftBracket
BackSlash
RightBracket
GraveAccent
World1
World2
Escape
Enter
Tab
Backspace
Insert
Delete
Right
Left
Down
Up
PageUp
PageDown
Home
End
CapsLock
ScrollLock
NumLock
PrintScreen
Pause
F1
F2
F3
F4
F5
F6
F7
F8
F9
F10
F11
F12
F13
F14
F15
F16
F17
F18
F19
F20
F21
F22
F23
F24
F25
NumPad0
NumPad1
NumPad2
NumPad3
NumPad4
NumPad5
NumPad6
NumPad7
NumPad8
NumPad9
NumPadDecimal
NumPadDivide
NumPadMultiply
NumPadSubtract
NumPadAdd
NumPadEnter
NumPadEqual
LeftShift
LeftControl
LeftAlt
LeftSuper
RightShift
RightControl
RightAlt
RightSuper
Menu
Last
InputButton
enum AuroraFW::GEngine::InputButton strong
Enumerator
B1
B2
B3
B4
B5
B6
B7
B8
Last
Left
Right
Middle
InputMod
enum AuroraFW::GEngine::InputMod : ushort strong
Enumerator
Shift
Control
Alt
Super
CapsLock
NumLock
Function Documentation
operator|()
InputMod AuroraFW::GEngine::operator| (InputMod a, InputMod b) inline
References a.
GLCheckError()
AFW_API GLenum AuroraFW::GEngine::GLCheckError ()
Referenced by GLLogCall().
GLLogCall()
AFW_API bool AuroraFW::GEngine::GLLogCall (const char * function, const char * file, uint_t line)
References AuroraFW::CLI::Error, GLCheckError(), and AuroraFW::CLI::Log().
setValue() [1/2]
void AuroraFW::GEngine::setValue (const std::string & , Math::Vector3D &)
setValue() [2/2]
void AuroraFW::GEngine::setValue (const std::string & , Math::Vector4D &)
Variable Documentation
Near
enum AuroraFW::GEngine::ProjectionType AuroraFW::GEngine::Near
Far
enum AuroraFW::GEngine::ProjectionType AuroraFW::GEngine::Far
Left
enum AuroraFW::GEngine::ProjectionType AuroraFW::GEngine::Left
Right
enum AuroraFW::GEngine::ProjectionType AuroraFW::GEngine::Right
Top
enum AuroraFW::GEngine::ProjectionType AuroraFW::GEngine::Top
Bottom
enum AuroraFW::GEngine::ProjectionType AuroraFW::GEngine::Bottom