Aurora Framework: Window reference
Window reference
Functions and types related to windows.
Macros
#define GLFW_ACCUM_ALPHA_BITS 0x0002100A
Framebuffer bit depth hint.
#define GLFW_ACCUM_BLUE_BITS 0x00021009
Framebuffer bit depth hint.
#define GLFW_ACCUM_GREEN_BITS 0x00021008
Framebuffer bit depth hint.
#define GLFW_ACCUM_RED_BITS 0x00021007
Framebuffer bit depth hint.
#define GLFW_ALPHA_BITS 0x00021004
Framebuffer bit depth hint.
#define GLFW_AUTO_ICONIFY 0x00020006
Window auto-iconification window hint and attribute.
#define GLFW_AUX_BUFFERS 0x0002100B
Framebuffer auxiliary buffer hint.
#define GLFW_BLUE_BITS 0x00021003
Framebuffer bit depth hint.
#define GLFW_CENTER_CURSOR 0x00020009
Cursor centering window hint.
#define GLFW_CLIENT_API 0x00022001
Context client API hint and attribute.
#define GLFW_COCOA_FRAME_NAME 0x00023002
#define GLFW_COCOA_GRAPHICS_SWITCHING 0x00023003
#define GLFW_COCOA_RETINA_FRAMEBUFFER 0x00023001
#define GLFW_CONTEXT_CREATION_API 0x0002200B
Context creation API hint and attribute.
#define GLFW_CONTEXT_NO_ERROR 0x0002200A
Context error suppression hint and attribute.
#define GLFW_CONTEXT_RELEASE_BEHAVIOR 0x00022009
Context flush-on-release hint and attribute.
#define GLFW_CONTEXT_REVISION 0x00022004
Context client API revision number hint and attribute.
#define GLFW_CONTEXT_ROBUSTNESS 0x00022005
Context robustness hint and attribute.
#define GLFW_CONTEXT_VERSION_MAJOR 0x00022002
Context client API major version hint and attribute.
#define GLFW_CONTEXT_VERSION_MINOR 0x00022003
Context client API minor version hint and attribute.
#define GLFW_DECORATED 0x00020005
Window decoration window hint and attribute.
#define GLFW_DEPTH_BITS 0x00021005
Framebuffer bit depth hint.
#define GLFW_DOUBLEBUFFER 0x00021010
Framebuffer double buffering hint.
#define GLFW_FLOATING 0x00020007
Window decoration window hint and attribute.
#define GLFW_FOCUSED 0x00020001
Input focus window hint and attribute.
#define GLFW_GREEN_BITS 0x00021002
Framebuffer bit depth hint.
#define GLFW_HOVERED 0x0002000B
Mouse cursor hover window attribute.
#define GLFW_ICONIFIED 0x00020002
Window iconification window attribute.
#define GLFW_MAXIMIZED 0x00020008
Window maximization window hint and attribute.
#define GLFW_OPENGL_DEBUG_CONTEXT 0x00022007
OpenGL debug context hint and attribute.
#define GLFW_OPENGL_FORWARD_COMPAT 0x00022006
OpenGL forward-compatibility hint and attribute.
#define GLFW_OPENGL_PROFILE 0x00022008
OpenGL profile hint and attribute.
#define GLFW_RED_BITS 0x00021001
Framebuffer bit depth hint.
#define GLFW_REFRESH_RATE 0x0002100F
Monitor refresh rate hint.
#define GLFW_RESIZABLE 0x00020003
Window resize-ability window hint and attribute.
#define GLFW_SAMPLES 0x0002100D
Framebuffer MSAA samples hint.
#define GLFW_SRGB_CAPABLE 0x0002100E
Framebuffer sRGB hint.
#define GLFW_STENCIL_BITS 0x00021006
Framebuffer bit depth hint.
#define GLFW_STEREO 0x0002100C
OpenGL stereoscopic rendering hint.
#define GLFW_TRANSPARENT_FRAMEBUFFER 0x0002000A
Window framebuffer transparency hint and attribute.
#define GLFW_VISIBLE 0x00020004
Window visibility window hint and attribute.
#define GLFW_X11_CLASS_NAME 0x00024001
#define GLFW_X11_INSTANCE_NAME 0x00024002
Typedefs
typedef void(* GLFWframebuffersizefun) (GLFWwindow *, int, int)
The function signature for framebuffer resize callbacks.
typedef struct GLFWwindow GLFWwindow
Opaque window object.
typedef void(* GLFWwindowclosefun) (GLFWwindow *)
The function signature for window close callbacks.
typedef void(* GLFWwindowcontentscalefun) (GLFWwindow *, float, float)
The function signature for window content scale callbacks.
typedef void(* GLFWwindowfocusfun) (GLFWwindow *, int)
The function signature for window focus/defocus callbacks.
typedef void(* GLFWwindowiconifyfun) (GLFWwindow *, int)
The function signature for window iconify/restore callbacks.
typedef void(* GLFWwindowmaximizefun) (GLFWwindow *, int)
The function signature for window maximize/restore callbacks.
typedef void(* GLFWwindowposfun) (GLFWwindow *, int, int)
The function signature for window position callbacks.
typedef void(* GLFWwindowrefreshfun) (GLFWwindow *)
The function signature for window content refresh callbacks.
typedef void(* GLFWwindowsizefun) (GLFWwindow *, int, int)
The function signature for window resize callbacks.
Functions
GLFWAPI GLFWwindow * glfwCreateWindow (int width, int height, const char *title, GLFWmonitor *monitor, GLFWwindow *share)
Creates a window and its associated context.
GLFWAPI void glfwDefaultWindowHints (void)
Resets all window hints to their default values.
GLFWAPI void glfwDestroyWindow (GLFWwindow *window)
Destroys the specified window and its context.
GLFWAPI void glfwFocusWindow (GLFWwindow *window)
Brings the specified window to front and sets input focus.
GLFWAPI void glfwGetFramebufferSize (GLFWwindow *window, int *width, int *height)
Retrieves the size of the framebuffer of the specified window.
GLFWAPI int glfwGetWindowAttrib (GLFWwindow *window, int attrib)
Returns an attribute of the specified window.
GLFWAPI void glfwGetWindowContentScale (GLFWwindow *window, float *xscale, float *yscale)
Retrieves the content scale for the specified window.
GLFWAPI void glfwGetWindowFrameSize (GLFWwindow *window, int *left, int *top, int *right, int *bottom)
Retrieves the size of the frame of the window.
GLFWAPI GLFWmonitor * glfwGetWindowMonitor (GLFWwindow *window)
Returns the monitor that the window uses for full screen mode.
GLFWAPI float glfwGetWindowOpacity (GLFWwindow *window)
Returns the opacity of the whole window.
GLFWAPI void glfwGetWindowPos (GLFWwindow *window, int *xpos, int *ypos)
Retrieves the position of the client area of the specified window.
GLFWAPI void glfwGetWindowSize (GLFWwindow *window, int *width, int *height)
Retrieves the size of the client area of the specified window.
GLFWAPI void * glfwGetWindowUserPointer (GLFWwindow *window)
Returns the user pointer of the specified window.
GLFWAPI void glfwHideWindow (GLFWwindow *window)
Hides the specified window.
GLFWAPI void glfwIconifyWindow (GLFWwindow *window)
Iconifies the specified window.
GLFWAPI void glfwMaximizeWindow (GLFWwindow *window)
Maximizes the specified window.
GLFWAPI void glfwPollEvents (void)
Processes all pending events.
GLFWAPI void glfwPostEmptyEvent (void)
Posts an empty event to the event queue.
GLFWAPI void glfwRequestWindowAttention (GLFWwindow *window)
Requests user attention to the specified window.
GLFWAPI void glfwRestoreWindow (GLFWwindow *window)
Restores the specified window.
GLFWAPI GLFWframebuffersizefun glfwSetFramebufferSizeCallback (GLFWwindow *window, GLFWframebuffersizefun cbfun)
Sets the framebuffer resize callback for the specified window.
GLFWAPI void glfwSetWindowAspectRatio (GLFWwindow *window, int numer, int denom)
Sets the aspect ratio of the specified window.
GLFWAPI void glfwSetWindowAttrib (GLFWwindow *window, int attrib, int value)
Sets an attribute of the specified window.
GLFWAPI GLFWwindowclosefun glfwSetWindowCloseCallback (GLFWwindow *window, GLFWwindowclosefun cbfun)
Sets the close callback for the specified window.
GLFWAPI GLFWwindowcontentscalefun glfwSetWindowContentScaleCallback (GLFWwindow *window, GLFWwindowcontentscalefun cbfun)
Sets the window content scale callback for the specified window.
GLFWAPI GLFWwindowfocusfun glfwSetWindowFocusCallback (GLFWwindow *window, GLFWwindowfocusfun cbfun)
Sets the focus callback for the specified window.
GLFWAPI void glfwSetWindowIcon (GLFWwindow *window, int count, const GLFWimage *images)
Sets the icon for the specified window.
GLFWAPI GLFWwindowiconifyfun glfwSetWindowIconifyCallback (GLFWwindow *window, GLFWwindowiconifyfun cbfun)
Sets the iconify callback for the specified window.
GLFWAPI GLFWwindowmaximizefun glfwSetWindowMaximizeCallback (GLFWwindow *window, GLFWwindowmaximizefun cbfun)
Sets the maximize callback for the specified window.
GLFWAPI void glfwSetWindowMonitor (GLFWwindow *window, GLFWmonitor *monitor, int xpos, int ypos, int width, int height, int refreshRate)
Sets the mode, monitor, video mode and placement of a window.
GLFWAPI void glfwSetWindowOpacity (GLFWwindow *window, float opacity)
Sets the opacity of the whole window.
GLFWAPI void glfwSetWindowPos (GLFWwindow *window, int xpos, int ypos)
Sets the position of the client area of the specified window.
GLFWAPI GLFWwindowposfun glfwSetWindowPosCallback (GLFWwindow *window, GLFWwindowposfun cbfun)
Sets the position callback for the specified window.
GLFWAPI GLFWwindowrefreshfun glfwSetWindowRefreshCallback (GLFWwindow *window, GLFWwindowrefreshfun cbfun)
Sets the refresh callback for the specified window.
GLFWAPI void glfwSetWindowShouldClose (GLFWwindow *window, int value)
Sets the close flag of the specified window.
GLFWAPI void glfwSetWindowSize (GLFWwindow *window, int width, int height)
Sets the size of the client area of the specified window.
GLFWAPI GLFWwindowsizefun glfwSetWindowSizeCallback (GLFWwindow *window, GLFWwindowsizefun cbfun)
Sets the size callback for the specified window.
GLFWAPI void glfwSetWindowSizeLimits (GLFWwindow *window, int minwidth, int minheight, int maxwidth, int maxheight)
Sets the size limits of the specified window.
GLFWAPI void glfwSetWindowTitle (GLFWwindow *window, const char *title)
Sets the title of the specified window.
GLFWAPI void glfwSetWindowUserPointer (GLFWwindow *window, void *pointer)
Sets the user pointer of the specified window.
GLFWAPI void glfwShowWindow (GLFWwindow *window)
Makes the specified window visible.
GLFWAPI void glfwSwapBuffers (GLFWwindow *window)
Swaps the front and back buffers of the specified window.
GLFWAPI void glfwWaitEvents (void)
Waits until events are queued and processes them.
GLFWAPI void glfwWaitEventsTimeout (double timeout)
Waits with timeout until events are queued and processes them.
GLFWAPI void glfwWindowHint (int hint, int value)
Sets the specified window hint to the desired value.
GLFWAPI void glfwWindowHintString (int hint, const char *value)
Sets the specified window hint to the desired value.
GLFWAPI int glfwWindowShouldClose (GLFWwindow *window)
Checks the close flag of the specified window.
Detailed Description
Functions and types related to windows.
This is the reference documentation for window related functions and types, including creation, deletion and event polling. For more task-oriented information, see the window_guide.
Macro Definition Documentation
GLFW_FOCUSED
#define GLFW_FOCUSED 0x00020001
Input focus window hint and attribute.
Input focus window hint or window attribute.
Referenced by glfwGetWindowAttrib(), glfwWindowHint(), AuroraFW::GEngine::ImGuiLoader::newFrame(), and AuroraFW::GEngine::Window::Window().
GLFW_ICONIFIED
#define GLFW_ICONIFIED 0x00020002
Window iconification window attribute.
Window iconification window attribute.
Referenced by glfwGetWindowAttrib().
GLFW_RESIZABLE
#define GLFW_RESIZABLE 0x00020003
Window resize-ability window hint and attribute.
Window resize-ability window hint and window attribute.
Referenced by glfwGetWindowAttrib(), glfwSetWindowAttrib(), glfwWindowHint(), main(), and AuroraFW::GEngine::Window::Window().
GLFW_VISIBLE
#define GLFW_VISIBLE 0x00020004
Window visibility window hint and attribute.
Window visibility window hint and window attribute.
Referenced by glfwGetWindowAttrib(), glfwWindowHint(), and AuroraFW::GEngine::Window::Window().
GLFW_DECORATED
#define GLFW_DECORATED 0x00020005
Window decoration window hint and attribute.
Window decoration window hint and window attribute.
Referenced by glfwGetWindowAttrib(), glfwSetWindowAttrib(), glfwWindowHint(), and AuroraFW::GEngine::Window::Window().
GLFW_AUTO_ICONIFY
#define GLFW_AUTO_ICONIFY 0x00020006
Window auto-iconification window hint and attribute.
Window auto-iconification window hint and window attribute.
Referenced by glfwGetWindowAttrib(), glfwSetWindowAttrib(), glfwWindowHint(), and AuroraFW::GEngine::Window::Window().
GLFW_FLOATING
#define GLFW_FLOATING 0x00020007
Window decoration window hint and attribute.
Window decoration window hint and window attribute.
Referenced by glfwGetWindowAttrib(), glfwSetWindowAttrib(), glfwWindowHint(), and AuroraFW::GEngine::Window::Window().
GLFW_MAXIMIZED
#define GLFW_MAXIMIZED 0x00020008
Window maximization window hint and attribute.
Window maximization window hint and window attribute.
Referenced by glfwGetWindowAttrib(), glfwWindowHint(), and AuroraFW::GEngine::Window::Window().
GLFW_CENTER_CURSOR
#define GLFW_CENTER_CURSOR 0x00020009
Cursor centering window hint.
Cursor centering window hint.
Referenced by glfwWindowHint().
GLFW_TRANSPARENT_FRAMEBUFFER
#define GLFW_TRANSPARENT_FRAMEBUFFER 0x0002000A
Window framebuffer transparency hint and attribute.
Window framebuffer transparency window hint and window attribute.
Referenced by glfwGetWindowAttrib(), and glfwWindowHint().
GLFW_HOVERED
#define GLFW_HOVERED 0x0002000B
Mouse cursor hover window attribute.
Mouse cursor hover window attribute.
Referenced by glfwGetWindowAttrib().
GLFW_RED_BITS
#define GLFW_RED_BITS 0x00021001
Framebuffer bit depth hint.
Framebuffer bit depth hint.
Referenced by glfwWindowHint(), and AuroraFW::GEngine::Window::Window().
GLFW_GREEN_BITS
#define GLFW_GREEN_BITS 0x00021002
Framebuffer bit depth hint.
Framebuffer bit depth hint.
Referenced by glfwWindowHint(), and AuroraFW::GEngine::Window::Window().
GLFW_BLUE_BITS
#define GLFW_BLUE_BITS 0x00021003
Framebuffer bit depth hint.
Framebuffer bit depth hint.
Referenced by glfwWindowHint(), and AuroraFW::GEngine::Window::Window().
GLFW_ALPHA_BITS
#define GLFW_ALPHA_BITS 0x00021004
Framebuffer bit depth hint.
Framebuffer bit depth hint.
Referenced by glfwWindowHint().
GLFW_DEPTH_BITS
#define GLFW_DEPTH_BITS 0x00021005
Framebuffer bit depth hint.
Framebuffer bit depth hint.
Referenced by glfwWindowHint().
GLFW_STENCIL_BITS
#define GLFW_STENCIL_BITS 0x00021006
Framebuffer bit depth hint.
Framebuffer bit depth hint.
Referenced by glfwWindowHint().
GLFW_ACCUM_RED_BITS
#define GLFW_ACCUM_RED_BITS 0x00021007
Framebuffer bit depth hint.
Framebuffer bit depth hint.
Referenced by glfwWindowHint().
GLFW_ACCUM_GREEN_BITS
#define GLFW_ACCUM_GREEN_BITS 0x00021008
Framebuffer bit depth hint.
Framebuffer bit depth hint.
Referenced by glfwWindowHint().
GLFW_ACCUM_BLUE_BITS
#define GLFW_ACCUM_BLUE_BITS 0x00021009
Framebuffer bit depth hint.
Framebuffer bit depth hint.
Referenced by glfwWindowHint().
GLFW_ACCUM_ALPHA_BITS
#define GLFW_ACCUM_ALPHA_BITS 0x0002100A
Framebuffer bit depth hint.
Framebuffer bit depth hint.
Referenced by glfwWindowHint().
GLFW_AUX_BUFFERS
#define GLFW_AUX_BUFFERS 0x0002100B
Framebuffer auxiliary buffer hint.
Framebuffer auxiliary buffer hint.
Referenced by glfwWindowHint(), and AuroraFW::GEngine::Window::Window().
GLFW_STEREO
#define GLFW_STEREO 0x0002100C
OpenGL stereoscopic rendering hint.
OpenGL stereoscopic rendering hint.
Referenced by glfwWindowHint(), and AuroraFW::GEngine::Window::Window().
GLFW_SAMPLES
#define GLFW_SAMPLES 0x0002100D
Framebuffer MSAA samples hint.
Framebuffer MSAA samples hint.
Referenced by glfwWindowHint(), and AuroraFW::GEngine::Window::Window().
GLFW_SRGB_CAPABLE
#define GLFW_SRGB_CAPABLE 0x0002100E
Framebuffer sRGB hint.
Framebuffer sRGB hint.
Referenced by glfwWindowHint(), and AuroraFW::GEngine::Window::Window().
GLFW_REFRESH_RATE
#define GLFW_REFRESH_RATE 0x0002100F
Monitor refresh rate hint.
Monitor refresh rate hint.
Referenced by glfwWindowHint(), and AuroraFW::GEngine::Window::Window().
GLFW_DOUBLEBUFFER
#define GLFW_DOUBLEBUFFER 0x00021010
Framebuffer double buffering hint.
Framebuffer double buffering hint.
Referenced by glfwWindowHint(), and AuroraFW::GEngine::Window::Window().
GLFW_CLIENT_API
#define GLFW_CLIENT_API 0x00022001
Context client API hint and attribute.
Context client API hint and attribute.
Referenced by glfwGetWindowAttrib(), glfwWindowHint(), and AuroraFW::GEngine::VKContext::VKContext().
GLFW_CONTEXT_VERSION_MAJOR
#define GLFW_CONTEXT_VERSION_MAJOR 0x00022002
Context client API major version hint and attribute.
Context client API major version hint and attribute.
Referenced by AuroraFW::GEngine::GLContext::GLContext(), glfwGetWindowAttrib(), glfwWindowHint(), and main().
GLFW_CONTEXT_VERSION_MINOR
#define GLFW_CONTEXT_VERSION_MINOR 0x00022003
Context client API minor version hint and attribute.
Context client API minor version hint and attribute.
Referenced by AuroraFW::GEngine::GLContext::GLContext(), glfwGetWindowAttrib(), glfwWindowHint(), and main().
GLFW_CONTEXT_REVISION
#define GLFW_CONTEXT_REVISION 0x00022004
Context client API revision number hint and attribute.
Context client API revision number hint and attribute.
Referenced by glfwGetWindowAttrib().
GLFW_CONTEXT_ROBUSTNESS
#define GLFW_CONTEXT_ROBUSTNESS 0x00022005
Context robustness hint and attribute.
Context client API revision number hint and attribute.
Referenced by glfwGetWindowAttrib(), and glfwWindowHint().
GLFW_OPENGL_FORWARD_COMPAT
#define GLFW_OPENGL_FORWARD_COMPAT 0x00022006
OpenGL forward-compatibility hint and attribute.
OpenGL forward-compatibility hint and attribute.
Referenced by AuroraFW::GEngine::GLContext::GLContext(), glfwGetWindowAttrib(), and glfwWindowHint().
GLFW_OPENGL_DEBUG_CONTEXT
#define GLFW_OPENGL_DEBUG_CONTEXT 0x00022007
OpenGL debug context hint and attribute.
OpenGL debug context hint and attribute.
Referenced by AuroraFW::GEngine::GLContext::GLContext(), glfwGetWindowAttrib(), and glfwWindowHint().
GLFW_OPENGL_PROFILE
#define GLFW_OPENGL_PROFILE 0x00022008
OpenGL profile hint and attribute.
OpenGL profile hint and attribute.
Referenced by AuroraFW::GEngine::GLContext::GLContext(), glfwGetWindowAttrib(), glfwWindowHint(), and main().
GLFW_CONTEXT_RELEASE_BEHAVIOR
#define GLFW_CONTEXT_RELEASE_BEHAVIOR 0x00022009
Context flush-on-release hint and attribute.
Context flush-on-release hint and attribute.
Referenced by glfwGetWindowAttrib(), and glfwWindowHint().
GLFW_CONTEXT_NO_ERROR
#define GLFW_CONTEXT_NO_ERROR 0x0002200A
Context error suppression hint and attribute.
Context error suppression hint and attribute.
Referenced by glfwGetWindowAttrib(), and glfwWindowHint().
GLFW_CONTEXT_CREATION_API
#define GLFW_CONTEXT_CREATION_API 0x0002200B
Context creation API hint and attribute.
Context creation API hint and attribute.
Referenced by glfwGetWindowAttrib(), and glfwWindowHint().
GLFW_COCOA_RETINA_FRAMEBUFFER
#define GLFW_COCOA_RETINA_FRAMEBUFFER 0x00023001
Referenced by glfwWindowHint().
GLFW_COCOA_FRAME_NAME
#define GLFW_COCOA_FRAME_NAME 0x00023002
Referenced by glfwWindowHintString().
GLFW_COCOA_GRAPHICS_SWITCHING
#define GLFW_COCOA_GRAPHICS_SWITCHING 0x00023003
Referenced by glfwWindowHint().
GLFW_X11_CLASS_NAME
#define GLFW_X11_CLASS_NAME 0x00024001
Referenced by glfwWindowHintString().
GLFW_X11_INSTANCE_NAME
#define GLFW_X11_INSTANCE_NAME 0x00024002
Referenced by glfwWindowHintString().
Typedef Documentation
GLFWwindow
typedef struct GLFWwindow GLFWwindow
Opaque window object.
Opaque window object.
See also
window_object
Since
Added in version 3.0.
GLFWwindowposfun
typedef void(* GLFWwindowposfun) (GLFWwindow *, int, int)
The function signature for window position callbacks.
This is the function signature for window position callback functions.
Parameters
[in] window The window that was moved.
[in] xpos The new x-coordinate, in screen coordinates, of the upper-left corner of the client area of the window.
[in] ypos The new y-coordinate, in screen coordinates, of the upper-left corner of the client area of the window.
See also
window_pos
glfwSetWindowPosCallback
Since
Added in version 3.0.
GLFWwindowsizefun
typedef void(* GLFWwindowsizefun) (GLFWwindow *, int, int)
The function signature for window resize callbacks.
This is the function signature for window size callback functions.
Parameters
[in] window The window that was resized.
[in] width The new width, in screen coordinates, of the window.
[in] height The new height, in screen coordinates, of the window.
See also
window_size
glfwSetWindowSizeCallback
Since
Added in version 1.0. Added window handle parameter.
GLFWwindowclosefun
typedef void(* GLFWwindowclosefun) (GLFWwindow *)
The function signature for window close callbacks.
This is the function signature for window close callback functions.
Parameters
[in] window The window that the user attempted to close.
See also
window_close
glfwSetWindowCloseCallback
Since
Added in version 2.5. Added window handle parameter.
GLFWwindowrefreshfun
typedef void(* GLFWwindowrefreshfun) (GLFWwindow *)
The function signature for window content refresh callbacks.
This is the function signature for window refresh callback functions.
Parameters
[in] window The window whose content needs to be refreshed.
See also
window_refresh
glfwSetWindowRefreshCallback
Since
Added in version 2.5. Added window handle parameter.
GLFWwindowfocusfun
typedef void(* GLFWwindowfocusfun) (GLFWwindow *, int)
The function signature for window focus/defocus callbacks.
This is the function signature for window focus callback functions.
Parameters
[in] window The window that gained or lost input focus.
[in] focused GLFW_TRUE if the window was given input focus, or GLFW_FALSE if it lost it.
See also
window_focus
glfwSetWindowFocusCallback
Since
Added in version 3.0.
GLFWwindowiconifyfun
typedef void(* GLFWwindowiconifyfun) (GLFWwindow *, int)
The function signature for window iconify/restore callbacks.
This is the function signature for window iconify/restore callback functions.
Parameters
[in] window The window that was iconified or restored.
[in] iconified GLFW_TRUE if the window was iconified, or GLFW_FALSE if it was restored.
See also
window_iconify
glfwSetWindowIconifyCallback
Since
Added in version 3.0.
GLFWwindowmaximizefun
typedef void(* GLFWwindowmaximizefun) (GLFWwindow *, int)
The function signature for window maximize/restore callbacks.
This is the function signature for window maximize/restore callback functions.
Parameters
[in] window The window that was maximized or restored.
[in] iconified GLFW_TRUE if the window was maximized, or GLFW_FALSE if it was restored.
See also
window_maximize
glfwSetWindowMaximizeCallback
Since
Added in version 3.3.
GLFWframebuffersizefun
typedef void(* GLFWframebuffersizefun) (GLFWwindow *, int, int)
The function signature for framebuffer resize callbacks.
This is the function signature for framebuffer resize callback functions.
Parameters
[in] window The window whose framebuffer was resized.
[in] width The new width, in pixels, of the framebuffer.
[in] height The new height, in pixels, of the framebuffer.
See also
window_fbsize
glfwSetFramebufferSizeCallback
Since
Added in version 3.0.
GLFWwindowcontentscalefun
typedef void(* GLFWwindowcontentscalefun) (GLFWwindow *, float, float)
The function signature for window content scale callbacks.
This is the function signature for window content scale callback functions.
Parameters
[in] window The window whose content scale changed.
[in] xscale The new x-axis content scale of the window.
[in] yscale The new y-axis content scale of the window.
See also
window_scale
glfwSetWindowContentScaleCallback
Since
Added in version 3.3.
Function Documentation
glfwDefaultWindowHints()
GLFWAPI void glfwDefaultWindowHints (void)
Resets all window hints to their default values.
This function resets all window hints to their default values.
Possible errors include GLFW_NOT_INITIALIZED.
This function must only be called from the main thread.
See also
window_hints
glfwWindowHint
glfwWindowHintString
Since
Added in version 3.0.
References _glfw, _GLFW_REQUIRE_INIT, _GLFWfbconfig::alphaBits, _GLFWwndconfig::autoIconify, _GLFWfbconfig::blueBits, _GLFWwndconfig::centerCursor, _GLFWctxconfig::client, _GLFWlibrary::context, _GLFWwndconfig::decorated, _GLFWfbconfig::depthBits, _GLFWfbconfig::doublebuffer, _GLFWwndconfig::focused, _GLFWlibrary::framebuffer, GLFW_DONT_CARE, GLFW_NATIVE_CONTEXT_API, GLFW_OPENGL_API, GLFW_TRUE, _GLFWfbconfig::greenBits, _GLFWlibrary::hints, _GLFWctxconfig::major, memset(), _GLFWctxconfig::minor, _GLFWwndconfig::ns, _GLFWfbconfig::redBits, _GLFWlibrary::refreshRate, _GLFWwndconfig::resizable, _GLFWwndconfig::retina, _GLFWctxconfig::source, _GLFWfbconfig::stencilBits, _GLFWwndconfig::visible, and _GLFWlibrary::window.
Referenced by glfwInit(), and AuroraFW::GEngine::Window::Window().
glfwWindowHint()
GLFWAPI void glfwWindowHint (int hint, int value)
Sets the specified window hint to the desired value.
This function sets hints for the next call to glfwCreateWindow. The hints, once set, retain their values until changed by a call to this function or glfwDefaultWindowHints, or until the library is terminated.
Only integer value hints can be set with this function. String value hints are set with glfwWindowHintString.
This function does not check whether the specified hint values are valid. If you set hints to invalid values this will instead be reported by the next call to glfwCreateWindow.
Some hints are platform specific. These may be set on any platform but they will only affect their specific platform. Other platforms will ignore them. Setting these hints requires no platform specific headers or functions.
Parameters
[in] hint The window hint to set.
[in] value The new value of the window hint.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_INVALID_ENUM.
This function must only be called from the main thread.
See also
window_hints
glfwWindowHintString
glfwDefaultWindowHints
Since
Added in version 3.0. Replaces glfwOpenWindowHint.
References _glfw, _GLFW_REQUIRE_INIT, _glfwInputError(), _GLFWfbconfig::accumAlphaBits, _GLFWfbconfig::accumBlueBits, _GLFWfbconfig::accumGreenBits, _GLFWfbconfig::accumRedBits, _GLFWfbconfig::alphaBits, _GLFWwndconfig::autoIconify, _GLFWfbconfig::auxBuffers, _GLFWfbconfig::blueBits, _GLFWwndconfig::centerCursor, _GLFWctxconfig::client, _GLFWlibrary::context, _GLFWctxconfig::debug, _GLFWwndconfig::decorated, _GLFWfbconfig::depthBits, _GLFWfbconfig::doublebuffer, _GLFWwndconfig::floating, _GLFWwndconfig::focused, _GLFWctxconfig::forward, _GLFWlibrary::framebuffer, GLFW_ACCUM_ALPHA_BITS, GLFW_ACCUM_BLUE_BITS, GLFW_ACCUM_GREEN_BITS, GLFW_ACCUM_RED_BITS, GLFW_ALPHA_BITS, GLFW_AUTO_ICONIFY, GLFW_AUX_BUFFERS, GLFW_BLUE_BITS, GLFW_CENTER_CURSOR, GLFW_CLIENT_API, GLFW_COCOA_GRAPHICS_SWITCHING, GLFW_COCOA_RETINA_FRAMEBUFFER, GLFW_CONTEXT_CREATION_API, GLFW_CONTEXT_NO_ERROR, GLFW_CONTEXT_RELEASE_BEHAVIOR, GLFW_CONTEXT_ROBUSTNESS, GLFW_CONTEXT_VERSION_MAJOR, GLFW_CONTEXT_VERSION_MINOR, GLFW_DECORATED, GLFW_DEPTH_BITS, GLFW_DOUBLEBUFFER, GLFW_FALSE, GLFW_FLOATING, GLFW_FOCUSED, GLFW_GREEN_BITS, GLFW_INVALID_ENUM, GLFW_MAXIMIZED, GLFW_OPENGL_DEBUG_CONTEXT, GLFW_OPENGL_FORWARD_COMPAT, GLFW_OPENGL_PROFILE, GLFW_RED_BITS, GLFW_REFRESH_RATE, GLFW_RESIZABLE, GLFW_SAMPLES, GLFW_SRGB_CAPABLE, GLFW_STENCIL_BITS, GLFW_STEREO, GLFW_TRANSPARENT_FRAMEBUFFER, GLFW_TRUE, GLFW_VISIBLE, _GLFWfbconfig::greenBits, _GLFWlibrary::hints, _GLFWctxconfig::major, _GLFWwndconfig::maximized, _GLFWctxconfig::minor, _GLFWctxconfig::noerror, _GLFWwndconfig::ns, _GLFWctxconfig::nsgl, _GLFWctxconfig::offline, _GLFWctxconfig::profile, _GLFWfbconfig::redBits, _GLFWlibrary::refreshRate, _GLFWctxconfig::release, _GLFWwndconfig::resizable, _GLFWwndconfig::retina, _GLFWctxconfig::robustness, _GLFWfbconfig::samples, _GLFWctxconfig::source, _GLFWfbconfig::sRGB, _GLFWfbconfig::stencilBits, _GLFWfbconfig::stereo, _GLFWfbconfig::transparent, value, _GLFWwndconfig::visible, and _GLFWlibrary::window.
Referenced by AuroraFW::GEngine::GLContext::GLContext(), main(), AuroraFW::GEngine::VKContext::VKContext(), and AuroraFW::GEngine::Window::Window().
glfwWindowHintString()
GLFWAPI void glfwWindowHintString (int hint, const char * value)
Sets the specified window hint to the desired value.
This function sets hints for the next call to glfwCreateWindow. The hints, once set, retain their values until changed by a call to this function or glfwDefaultWindowHints, or until the library is terminated.
Only string type hints can be set with this function. Integer value hints are set with glfwWindowHint.
This function does not check whether the specified hint values are valid. If you set hints to invalid values this will instead be reported by the next call to glfwCreateWindow.
Some hints are platform specific. These may be set on any platform but they will only affect their specific platform. Other platforms will ignore them. Setting these hints requires no platform specific headers or functions.
Parameters
[in] hint The window hint to set.
[in] value The new value of the window hint.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_INVALID_ENUM.
The specified string is copied before this function returns.
This function must only be called from the main thread.
See also
window_hints
glfwWindowHint
glfwDefaultWindowHints
Since
Added in version 3.3.
References _glfw, _GLFW_REQUIRE_INIT, _glfwInputError(), _GLFWwndconfig::className, _GLFWwndconfig::frameName, GLFW_COCOA_FRAME_NAME, GLFW_INVALID_ENUM, GLFW_X11_CLASS_NAME, GLFW_X11_INSTANCE_NAME, _GLFWlibrary::hints, _GLFWwndconfig::instanceName, _GLFWwndconfig::ns, NULL, value, _GLFWlibrary::window, and _GLFWwndconfig::x11.
glfwCreateWindow()
GLFWAPI GLFWwindow* glfwCreateWindow (int width, int height, const char * title, GLFWmonitor * monitor, GLFWwindow * share)
Creates a window and its associated context.
This function creates a window and its associated OpenGL or OpenGL ES context. Most of the options controlling how the window and its context should be created are specified with window hints.
Successful creation does not change which context is current. Before you can use the newly created context, you need to make it current. For information about the share parameter, see context_sharing.
The created window, framebuffer and context may differ from what you requested, as not all parameters and hints are hard constraints. This includes the size of the window, especially for full screen windows. To query the actual attributes of the created window, framebuffer and context, see glfwGetWindowAttrib, glfwGetWindowSize and glfwGetFramebufferSize.
To create a full screen window, you need to specify the monitor the window will cover. If no monitor is specified, the window will be windowed mode. Unless you have a way for the user to choose a specific monitor, it is recommended that you pick the primary monitor. For more information on how to query connected monitors, see monitor_monitors.
For full screen windows, the specified size becomes the resolution of the window's desired video mode. As long as a full screen window is not iconified, the supported video mode most closely matching the desired video mode is set for the specified monitor. For more information about full screen windows, including the creation of so called windowed full screen or borderless full screen windows, see window_windowed_full_screen.
Once you have created the window, you can switch it between windowed and full screen mode with glfwSetWindowMonitor. This will not affect its OpenGL or OpenGL ES context.
By default, newly created windows use the placement recommended by the window system. To create the window at a specific position, make it initially invisible using the GLFW_VISIBLE window hint, set its position and then show it.
As long as at least one full screen window is not iconified, the screensaver is prohibited from starting.
Window systems put limits on window sizes. Very large or very small window dimensions may be overridden by the window system on creation. Check the actual size after creation.
The swap interval is not set during window creation and the initial value may vary depending on driver settings and defaults.
Parameters
[in] width The desired width, in screen coordinates, of the window. This must be greater than zero.
[in] height The desired height, in screen coordinates, of the window. This must be greater than zero.
[in] title The initial, UTF-8 encoded window title.
[in] monitor The monitor to use for full screen mode, or NULL for windowed mode.
[in] share The window whose context to share resources with, or NULL to not share resources.
Returns
The handle of the created window, or NULL if an error occurred.
Possible errors include GLFW_NOT_INITIALIZED, GLFW_INVALID_ENUM, GLFW_INVALID_VALUE, GLFW_API_UNAVAILABLE, GLFW_VERSION_UNAVAILABLE, GLFW_FORMAT_UNAVAILABLE and GLFW_PLATFORM_ERROR.
Remarks
Window creation will fail if the Microsoft GDI software OpenGL implementation is the only one available.
If the executable has an icon resource named GLFW_ICON, it will be set as the initial icon for the window. If no such icon is present, the IDI_APPLICATION icon will be used instead. To set a different icon, see glfwSetWindowIcon.
The context to share resources with must not be current on any other thread.
The OS only supports forward-compatible core profile contexts for OpenGL versions 3.2 and later. Before creating an OpenGL context of version 3.2 or later you must set the GLFW_OPENGL_FORWARD_COMPAT and GLFW_OPENGL_PROFILE hints accordingly. OpenGL 3.0 and 3.1 contexts are not supported at all on macOS.
The GLFW window has no icon, as it is not a document window, but the dock icon will be the same as the application bundle's icon. For more information on bundles, see the Bundle Programming Guide in the Mac Developer Library.
The first time a window is created the menu bar is created. If GLFW finds a MainMenu.nib it is loaded and assumed to contain a menu bar. Otherwise a minimal menu bar is created manually with common commands like Hide, Quit and About. The About entry opens a minimal about dialog with information from the application's bundle. Menu bar creation can be disabled entirely with the GLFW_COCOA_MENUBAR init hint.
On OS X 10.10 and later the window frame will not be rendered at full resolution on Retina displays unless the GLFW_COCOA_RETINA_FRAMEBUFFER hint is GLFW_TRUE and the NSHighResolutionCapable key is enabled in the application bundle's Info.plist. For more information, see High Resolution Guidelines for OS X in the Mac Developer Library. The GLFW test and example programs use a custom Info.plist template for this, which can be found as CMake/MacOSXBundleInfo.plist.in in the source tree.
When activating frame autosaving with GLFW_COCOA_FRAME_NAME, the specified window size and position may be overriden by previously saved values.
Some window managers will not respect the placement of initially hidden windows.
Due to the asynchronous nature of X11, it may take a moment for a window to reach its requested state. This means you may not be able to query the final size, position or other attributes directly after window creation.
The class part of the WM_CLASS window property will by default be set to the window title passed to this function. The instance part will use the contents of the RESOURCE_NAME environment variable, if present and not empty, or fall back to the window title. Set the GLFW_X11_CLASS_NAME and GLFW_X11_INSTANCE_NAME window hints to override this.
The window frame is currently very simple, only allowing window resize or move. A compositor can still emit close, maximize or fullscreen events, using for example a keybind mechanism. Additionally, the wp_viewporter protocol is required for this feature, otherwise the window will not be decorated.
A full screen window will not attempt to change the mode, no matter what the requested size or refresh rate.
Screensaver inhibition requires the idle-inhibit protocol to be implemented in the user's compositor.
This function must only be called from the main thread.
See also
window_creation
glfwDestroyWindow
Since
Added in version 3.0. Replaces glfwOpenWindow.
References _glfw, _GLFW_REQUIRE_INIT_OR_RETURN, _glfwInputError(), _glfwIsValidContextConfig(), _glfwPlatformCreateWindow(), _glfwPlatformFocusWindow(), _glfwPlatformGetWindowSize(), _glfwPlatformSetCursorPos(), _glfwPlatformShowWindow(), _glfwRefreshContextAttribs(), _GLFWwndconfig::autoIconify, _GLFWwindow::autoIconify, _GLFWfbconfig::blueBits, GLFWvidmode::blueBits, _GLFWwndconfig::centerCursor, _GLFWctxconfig::client, _GLFWlibrary::context, _GLFWwindow::cursorMode, _GLFWwndconfig::decorated, _GLFWwindow::decorated, _GLFWwindow::denom, _GLFWwndconfig::floating, _GLFWwindow::floating, _GLFWwndconfig::focused, _GLFWlibrary::framebuffer, GLFW_CURSOR_NORMAL, GLFW_DONT_CARE, GLFW_INVALID_VALUE, GLFW_NO_API, glfwDestroyWindow(), _GLFWfbconfig::greenBits, GLFWvidmode::greenBits, height, _GLFWwndconfig::height, GLFWvidmode::height, _GLFWlibrary::hints, _GLFWwindow::maxheight, _GLFWwindow::maxwidth, _GLFWwindow::minheight, _GLFWwindow::minwidth, _GLFWwindow::monitor, _GLFWwindow::next, NULL, _GLFWwindow::numer, _GLFWfbconfig::redBits, GLFWvidmode::redBits, _GLFWlibrary::refreshRate, GLFWvidmode::refreshRate, _GLFWwndconfig::resizable, _GLFWwindow::resizable, _GLFWctxconfig::share, _GLFWwndconfig::title, _GLFWwindow::videoMode, _GLFWwndconfig::visible, width, _GLFWwndconfig::width, GLFWvidmode::width, _GLFWlibrary::window, and _GLFWlibrary::windowListHead.
Referenced by main(), and AuroraFW::GEngine::Window::Window().
glfwDestroyWindow()
GLFWAPI void glfwDestroyWindow (GLFWwindow * window)
Destroys the specified window and its context.
This function destroys the specified window and its context. On calling this function, no further callbacks will be called for that window.
If the context of the specified window is current on the main thread, it is detached before being destroyed.
Parameters
[in] window The window to destroy.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
Note
The context of the specified window must not be current on any other thread when this function is called.
This function must not be called from a callback.
This function must only be called from the main thread.
See also
window_creation
glfwCreateWindow
Since
Added in version 3.0. Replaces glfwCloseWindow.
References _glfw, _GLFW_REQUIRE_INIT, _glfwPlatformDestroyWindow(), _glfwPlatformGetTls(), _GLFWwindow::callbacks, _GLFWlibrary::contextSlot, glfwMakeContextCurrent(), memset(), _GLFWwindow::next, NULL, and _GLFWlibrary::windowListHead.
Referenced by glfwCreateWindow(), terminate(), and AuroraFW::GEngine::Window::~Window().
glfwWindowShouldClose()
GLFWAPI int glfwWindowShouldClose (GLFWwindow * window)
Checks the close flag of the specified window.
This function returns the value of the close flag of the specified window.
Parameters
[in] window The window to query.
Returns
The value of the close flag.
Possible errors include GLFW_NOT_INITIALIZED.
This function may be called from any thread. Access is not synchronized.
See also
window_close
Since
Added in version 3.0.
References _GLFW_REQUIRE_INIT_OR_RETURN, NULL, and _GLFWwindow::shouldClose.
Referenced by AuroraFW::GEngine::Window::isClosed(), and main().
glfwSetWindowShouldClose()
GLFWAPI void glfwSetWindowShouldClose (GLFWwindow * window, int value)
Sets the close flag of the specified window.
This function sets the value of the close flag of the specified window. This can be used to override the user's attempt to close the window, or to signal that it should be closed.
Parameters
[in] window The window whose flag to change.
[in] value The new value.
Possible errors include GLFW_NOT_INITIALIZED.
This function may be called from any thread. Access is not synchronized.
See also
window_close
Since
Added in version 3.0.
References _GLFW_REQUIRE_INIT, NULL, _GLFWwindow::shouldClose, and value.
Referenced by key_callback().
glfwSetWindowTitle()
GLFWAPI void glfwSetWindowTitle (GLFWwindow * window, const char * title)
Sets the title of the specified window.
This function sets the window title, encoded as UTF-8, of the specified window.
Parameters
[in] window The window whose title to change.
[in] title The UTF-8 encoded window title.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
Remarks
The window title will not be updated until the next time you process events.
This function must only be called from the main thread.
See also
window_title
Since
Added in version 1.0. Added window handle parameter.
References _GLFW_REQUIRE_INIT, _glfwPlatformSetWindowTitle(), and NULL.
glfwSetWindowIcon()
GLFWAPI void glfwSetWindowIcon (GLFWwindow * window, int count, const GLFWimage * images)
Sets the icon for the specified window.
This function sets the icon of the specified window. If passed an array of candidate images, those of or closest to the sizes desired by the system are selected. If no images are specified, the window reverts to its default icon.
The pixels are 32-bit, little-endian, non-premultiplied RGBA, i.e. eight bits per channel with the red channel first. They are arranged canonically as packed sequential rows, starting from the top-left corner.
The desired image sizes varies depending on platform and system settings. The selected images will be rescaled as needed. Good sizes include 16x16, 32x32 and 48x48.
Parameters
[in] window The window whose icon to set.
[in] count The number of images in the specified array, or zero to revert to the default window icon.
[in] images The images to create the icon from. This is ignored if count is zero.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
The specified image data is copied before this function returns.
Remarks
The GLFW window has no icon, as it is not a document window, so this function does nothing. The dock icon will be the same as the application bundle's icon. For more information on bundles, see the Bundle Programming Guide in the Mac Developer Library.
There is no existing protocol to change an icon, the window will thus inherit the one defined in the application's desktop file. This function always emits GLFW_PLATFORM_ERROR.
This function must only be called from the main thread.
See also
window_icon
Since
Added in version 3.2.
References _GLFW_REQUIRE_INIT, _glfwPlatformSetWindowIcon(), and NULL.
glfwGetWindowPos()
GLFWAPI void glfwGetWindowPos (GLFWwindow * window, int * xpos, int * ypos)
Retrieves the position of the client area of the specified window.
This function retrieves the position, in screen coordinates, of the upper-left corner of the client area of the specified window.
Any or all of the position arguments may be NULL. If an error occurs, all non-NULL position arguments will be set to zero.
Parameters
[in] window The window to query.
[out] xpos Where to store the x-coordinate of the upper-left corner of the client area, or NULL.
[out] ypos Where to store the y-coordinate of the upper-left corner of the client area, or NULL.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
Remarks
There is no way for an application to retrieve the global position of its windows, this function will always emit GLFW_PLATFORM_ERROR.
This function must only be called from the main thread.
See also
window_pos
glfwSetWindowPos
Since
Added in version 3.0.
References _GLFW_REQUIRE_INIT, _glfwPlatformGetWindowPos(), and NULL.
glfwSetWindowPos()
GLFWAPI void glfwSetWindowPos (GLFWwindow * window, int xpos, int ypos)
Sets the position of the client area of the specified window.
This function sets the position, in screen coordinates, of the upper-left corner of the client area of the specified windowed mode window. If the window is a full screen window, this function does nothing.
Do not use this function to move an already visible window unless you have very good reasons for doing so, as it will confuse and annoy the user.
The window manager may put limits on what positions are allowed. GLFW cannot and should not override these limits.
Parameters
[in] window The window to query.
[in] xpos The x-coordinate of the upper-left corner of the client area.
[in] ypos The y-coordinate of the upper-left corner of the client area.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
Remarks
There is no way for an application to set the global position of its windows, this function will always emit GLFW_PLATFORM_ERROR.
This function must only be called from the main thread.
See also
window_pos
glfwGetWindowPos
Since
Added in version 1.0. Added window handle parameter.
References _GLFW_REQUIRE_INIT, _glfwPlatformSetWindowPos(), _GLFWwindow::monitor, and NULL.
glfwGetWindowSize()
GLFWAPI void glfwGetWindowSize (GLFWwindow * window, int * width, int * height)
Retrieves the size of the client area of the specified window.
This function retrieves the size, in screen coordinates, of the client area of the specified window. If you wish to retrieve the size of the framebuffer of the window in pixels, see glfwGetFramebufferSize.
Any or all of the size arguments may be NULL. If an error occurs, all non-NULL size arguments will be set to zero.
Parameters
[in] window The window whose size to retrieve.
[out] width Where to store the width, in screen coordinates, of the client area, or NULL.
[out] height Where to store the height, in screen coordinates, of the client area, or NULL.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
This function must only be called from the main thread.
See also
window_size
glfwSetWindowSize
Since
Added in version 1.0. Added window handle parameter.
References _GLFW_REQUIRE_INIT, _glfwPlatformGetWindowSize(), height, NULL, and width.
Referenced by AuroraFW::GEngine::ImGuiLoader::newFrame().
glfwSetWindowSizeLimits()
GLFWAPI void glfwSetWindowSizeLimits (GLFWwindow * window, int minwidth, int minheight, int maxwidth, int maxheight)
Sets the size limits of the specified window.
This function sets the size limits of the client area of the specified window. If the window is full screen, the size limits only take effect once it is made windowed. If the window is not resizable, this function does nothing.
The size limits are applied immediately to a windowed mode window and may cause it to be resized.
The maximum dimensions must be greater than or equal to the minimum dimensions and all must be greater than or equal to zero.
Parameters
[in] window The window to set limits for.
[in] minwidth The minimum width, in screen coordinates, of the client area, or GLFW_DONT_CARE.
[in] minheight The minimum height, in screen coordinates, of the client area, or GLFW_DONT_CARE.
[in] maxwidth The maximum width, in screen coordinates, of the client area, or GLFW_DONT_CARE.
[in] maxheight The maximum height, in screen coordinates, of the client area, or GLFW_DONT_CARE.
Possible errors include GLFW_NOT_INITIALIZED, GLFW_INVALID_VALUE and GLFW_PLATFORM_ERROR.
Remarks
If you set size limits and an aspect ratio that conflict, the results are undefined.
The size limits will not be applied until the window is actually resized, either by the user or by the compositor.
This function must only be called from the main thread.
See also
window_sizelimits
glfwSetWindowAspectRatio
Since
Added in version 3.2.
References _GLFW_REQUIRE_INIT, _glfwInputError(), _glfwPlatformSetWindowSizeLimits(), GLFW_DONT_CARE, GLFW_INVALID_VALUE, _GLFWwindow::maxheight, _GLFWwindow::maxwidth, _GLFWwindow::minheight, _GLFWwindow::minwidth, _GLFWwindow::monitor, NULL, and _GLFWwindow::resizable.
glfwSetWindowAspectRatio()
GLFWAPI void glfwSetWindowAspectRatio (GLFWwindow * window, int numer, int denom)
Sets the aspect ratio of the specified window.
This function sets the required aspect ratio of the client area of the specified window. If the window is full screen, the aspect ratio only takes effect once it is made windowed. If the window is not resizable, this function does nothing.
The aspect ratio is specified as a numerator and a denominator and both values must be greater than zero. For example, the common 16:9 aspect ratio is specified as 16 and 9, respectively.
If the numerator and denominator is set to GLFW_DONT_CARE then the aspect ratio limit is disabled.
The aspect ratio is applied immediately to a windowed mode window and may cause it to be resized.
Parameters
[in] window The window to set limits for.
[in] numer The numerator of the desired aspect ratio, or GLFW_DONT_CARE.
[in] denom The denominator of the desired aspect ratio, or GLFW_DONT_CARE.
Possible errors include GLFW_NOT_INITIALIZED, GLFW_INVALID_VALUE and GLFW_PLATFORM_ERROR.
Remarks
If you set size limits and an aspect ratio that conflict, the results are undefined.
The aspect ratio will not be applied until the window is actually resized, either by the user or by the compositor.
This function must only be called from the main thread.
See also
window_sizelimits
glfwSetWindowSizeLimits
Since
Added in version 3.2.
References _GLFW_REQUIRE_INIT, _glfwInputError(), _glfwPlatformSetWindowAspectRatio(), _GLFWwindow::denom, GLFW_DONT_CARE, GLFW_INVALID_VALUE, _GLFWwindow::monitor, NULL, _GLFWwindow::numer, and _GLFWwindow::resizable.
glfwSetWindowSize()
GLFWAPI void glfwSetWindowSize (GLFWwindow * window, int width, int height)
Sets the size of the client area of the specified window.
This function sets the size, in screen coordinates, of the client area of the specified window.
For full screen windows, this function updates the resolution of its desired video mode and switches to the video mode closest to it, without affecting the window's context. As the context is unaffected, the bit depths of the framebuffer remain unchanged.
If you wish to update the refresh rate of the desired video mode in addition to its resolution, see glfwSetWindowMonitor.
The window manager may put limits on what sizes are allowed. GLFW cannot and should not override these limits.
Parameters
[in] window The window to resize.
[in] width The desired width, in screen coordinates, of the window client area.
[in] height The desired height, in screen coordinates, of the window client area.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
Remarks
A full screen window will not attempt to change the mode, no matter what the requested size.
This function must only be called from the main thread.
See also
window_size
glfwGetWindowSize
glfwSetWindowMonitor
Since
Added in version 1.0. Added window handle parameter.
References _GLFW_REQUIRE_INIT, _glfwPlatformSetWindowSize(), height, GLFWvidmode::height, NULL, _GLFWwindow::videoMode, width, and GLFWvidmode::width.
glfwGetFramebufferSize()
GLFWAPI void glfwGetFramebufferSize (GLFWwindow * window, int * width, int * height)
Retrieves the size of the framebuffer of the specified window.
This function retrieves the size, in pixels, of the framebuffer of the specified window. If you wish to retrieve the size of the window in screen coordinates, see glfwGetWindowSize.
Any or all of the size arguments may be NULL. If an error occurs, all non-NULL size arguments will be set to zero.
Parameters
[in] window The window whose framebuffer to query.
[out] width Where to store the width, in pixels, of the framebuffer, or NULL.
[out] height Where to store the height, in pixels, of the framebuffer, or NULL.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
This function must only be called from the main thread.
See also
window_fbsize
glfwSetFramebufferSizeCallback
Since
Added in version 3.0.
References _GLFW_REQUIRE_INIT, _glfwPlatformGetFramebufferSize(), height, NULL, and width.
Referenced by AuroraFW::GEngine::ImGuiLoader::newFrame(), and AuroraFW::GEngine::Window::present().
glfwGetWindowFrameSize()
GLFWAPI void glfwGetWindowFrameSize (GLFWwindow * window, int * left, int * top, int * right, int * bottom)
Retrieves the size of the frame of the window.
This function retrieves the size, in screen coordinates, of each edge of the frame of the specified window. This size includes the title bar, if the window has one. The size of the frame may vary depending on the window-related hints used to create it.
Because this function retrieves the size of each window frame edge and not the offset along a particular coordinate axis, the retrieved values will always be zero or positive.
Any or all of the size arguments may be NULL. If an error occurs, all non-NULL size arguments will be set to zero.
Parameters
[in] window The window whose frame size to query.
[out] left Where to store the size, in screen coordinates, of the left edge of the window frame, or NULL.
[out] top Where to store the size, in screen coordinates, of the top edge of the window frame, or NULL.
[out] right Where to store the size, in screen coordinates, of the right edge of the window frame, or NULL.
[out] bottom Where to store the size, in screen coordinates, of the bottom edge of the window frame, or NULL.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
This function must only be called from the main thread.
See also
window_size
Since
Added in version 3.1.
References _GLFW_REQUIRE_INIT, _glfwPlatformGetWindowFrameSize(), and NULL.
glfwGetWindowContentScale()
GLFWAPI void glfwGetWindowContentScale (GLFWwindow * window, float * xscale, float * yscale)
Retrieves the content scale for the specified window.
This function retrieves the content scale for the specified window. The content scale is the ratio between the current DPI and the platform's default DPI. If you scale all pixel dimensions by this scale then your content should appear at an appropriate size. This is especially important for text and any UI elements.
On systems where each monitors can have its own content scale, the window content scale will depend on which monitor the system considers the window to be on.
Parameters
[in] window The window to query.
[out] xscale Where to store the x-axis content scale, or NULL.
[out] yscale Where to store the y-axis content scale, or NULL.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
This function must only be called from the main thread.
See also
window_scale
glfwSetWindowContentScaleCallback
glfwGetMonitorContentScale
Since
Added in version 3.3.
References _GLFW_REQUIRE_INIT, _glfwPlatformGetWindowContentScale(), and NULL.
glfwGetWindowOpacity()
GLFWAPI float glfwGetWindowOpacity (GLFWwindow * window)
Returns the opacity of the whole window.
This function returns the opacity of the window, including any decorations.
The opacity (or alpha) value is a positive finite number between zero and one, where zero is fully transparent and one is fully opaque. If the system does not support whole window transparency, this function always returns one.
The initial opacity value for newly created windows is one.
Parameters
[in] window The window to query.
Returns
The opacity value of the specified window.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
This function must only be called from the main thread.
See also
window_transparency
glfwSetWindowOpacity
Since
Added in version 3.3.
References _GLFW_REQUIRE_INIT_OR_RETURN, _glfwPlatformGetWindowOpacity(), and NULL.
glfwSetWindowOpacity()
GLFWAPI void glfwSetWindowOpacity (GLFWwindow * window, float opacity)
Sets the opacity of the whole window.
This function sets the opacity of the window, including any decorations.
The opacity (or alpha) value is a positive finite number between zero and one, where zero is fully transparent and one is fully opaque.
The initial opacity value for newly created windows is one.
A window created with framebuffer transparency may not use whole window transparency. The results of doing this are undefined.
Parameters
[in] window The window to set the opacity for.
[in] opacity The desired opacity of the specified window.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
This function must only be called from the main thread.
See also
window_transparency
glfwGetWindowOpacity
Since
Added in version 3.3.
References _GLFW_REQUIRE_INIT, _glfwInputError(), _glfwPlatformSetWindowOpacity(), GLFW_INVALID_VALUE, and NULL.
glfwIconifyWindow()
GLFWAPI void glfwIconifyWindow (GLFWwindow * window)
Iconifies the specified window.
This function iconifies (minimizes) the specified window if it was previously restored. If the window is already iconified, this function does nothing.
If the specified window is a full screen window, the original monitor resolution is restored until the window is restored.
Parameters
[in] window The window to iconify.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
Remarks
There is no concept of iconification in wl_shell, this function will emit GLFW_PLATFORM_ERROR when using this deprecated protocol.
This function must only be called from the main thread.
See also
window_iconify
glfwRestoreWindow
glfwMaximizeWindow
Since
Added in version 2.1. Added window handle parameter.
References _GLFW_REQUIRE_INIT, _glfwPlatformIconifyWindow(), and NULL.
glfwRestoreWindow()
GLFWAPI void glfwRestoreWindow (GLFWwindow * window)
Restores the specified window.
This function restores the specified window if it was previously iconified (minimized) or maximized. If the window is already restored, this function does nothing.
If the specified window is a full screen window, the resolution chosen for the window is restored on the selected monitor.
Parameters
[in] window The window to restore.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
This function must only be called from the main thread.
See also
window_iconify
glfwIconifyWindow
glfwMaximizeWindow
Since
Added in version 2.1. Added window handle parameter.
References _GLFW_REQUIRE_INIT, _glfwPlatformRestoreWindow(), and NULL.
glfwMaximizeWindow()
GLFWAPI void glfwMaximizeWindow (GLFWwindow * window)
Maximizes the specified window.
This function maximizes the specified window if it was previously not maximized. If the window is already maximized, this function does nothing.
If the specified window is a full screen window, this function does nothing.
Parameters
[in] window The window to maximize.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
Thread Safety
This function may only be called from the main thread.
See also
window_iconify
glfwIconifyWindow
glfwRestoreWindow
Since
Added in GLFW 3.2.
References _GLFW_REQUIRE_INIT, _glfwPlatformMaximizeWindow(), _GLFWwindow::monitor, and NULL.
glfwShowWindow()
GLFWAPI void glfwShowWindow (GLFWwindow * window)
Makes the specified window visible.
This function makes the specified window visible if it was previously hidden. If the window is already visible or is in full screen mode, this function does nothing.
Parameters
[in] window The window to make visible.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
This function must only be called from the main thread.
See also
window_hide
glfwHideWindow
Since
Added in version 3.0.
References _GLFW_REQUIRE_INIT, _glfwPlatformFocusWindow(), _glfwPlatformShowWindow(), _GLFWwindow::monitor, and NULL.
glfwHideWindow()
GLFWAPI void glfwHideWindow (GLFWwindow * window)
Hides the specified window.
This function hides the specified window if it was previously visible. If the window is already hidden or is in full screen mode, this function does nothing.
Parameters
[in] window The window to hide.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
This function must only be called from the main thread.
See also
window_hide
glfwShowWindow
Since
Added in version 3.0.
References _GLFW_REQUIRE_INIT, _glfwPlatformHideWindow(), _GLFWwindow::monitor, and NULL.
glfwFocusWindow()
GLFWAPI void glfwFocusWindow (GLFWwindow * window)
Brings the specified window to front and sets input focus.
This function brings the specified window to front and sets input focus. The window should already be visible and not iconified.
By default, both windowed and full screen mode windows are focused when initially created. Set the GLFW_FOCUSED to disable this behavior.
Do not use this function to steal focus from other applications unless you are certain that is what the user wants. Focus stealing can be extremely disruptive.
For a less disruptive way of getting the user's attention, see attention requests.
Parameters
[in] window The window to give input focus.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
Remarks
It is not possible for an application to bring its windows to front, this function will always emit GLFW_PLATFORM_ERROR.
This function must only be called from the main thread.
See also
window_focus
window_attention
Since
Added in version 3.2.
References _GLFW_REQUIRE_INIT, _glfwPlatformFocusWindow(), and NULL.
glfwRequestWindowAttention()
GLFWAPI void glfwRequestWindowAttention (GLFWwindow * window)
Requests user attention to the specified window.
This function requests user attention to the specified window. On platforms where this is not supported, attention is requested to the application as a whole.
Once the user has given attention, usually by focusing the window or application, the system will end the request automatically.
Parameters
[in] window The window to request attention to.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
Remarks
Attention is requested to the application as a whole, not the specific window.
This function must only be called from the main thread.
See also
window_attention
Since
Added in version 3.3.
References _GLFW_REQUIRE_INIT, _glfwPlatformRequestWindowAttention(), and NULL.
glfwGetWindowMonitor()
GLFWAPI GLFWmonitor* glfwGetWindowMonitor (GLFWwindow * window)
Returns the monitor that the window uses for full screen mode.
This function returns the handle of the monitor that the specified window is in full screen on.
Parameters
[in] window The window to query.
Returns
The monitor, or NULL if the window is in windowed mode or an error occurred.
Possible errors include GLFW_NOT_INITIALIZED.
This function must only be called from the main thread.
See also
window_monitor
glfwSetWindowMonitor
Since
Added in version 3.0.
References _GLFW_REQUIRE_INIT_OR_RETURN, _GLFWwindow::monitor, and NULL.
glfwSetWindowMonitor()
GLFWAPI void glfwSetWindowMonitor (GLFWwindow * window, GLFWmonitor * monitor, int xpos, int ypos, int width, int height, int refreshRate)
Sets the mode, monitor, video mode and placement of a window.
This function sets the monitor that the window uses for full screen mode or, if the monitor is NULL, makes it windowed mode.
When setting a monitor, this function updates the width, height and refresh rate of the desired video mode and switches to the video mode closest to it. The window position is ignored when setting a monitor.
When the monitor is NULL, the position, width and height are used to place the window client area. The refresh rate is ignored when no monitor is specified.
If you only wish to update the resolution of a full screen window or the size of a windowed mode window, see glfwSetWindowSize.
When a window transitions from full screen to windowed mode, this function restores any previous window settings such as whether it is decorated, floating, resizable, has size or aspect ratio limits, etc.
Parameters
[in] window The window whose monitor, size or video mode to set.
[in] monitor The desired monitor, or NULL to set windowed mode.
[in] xpos The desired x-coordinate of the upper-left corner of the client area.
[in] ypos The desired y-coordinate of the upper-left corner of the client area.
[in] width The desired with, in screen coordinates, of the client area or video mode.
[in] height The desired height, in screen coordinates, of the client area or video mode.
[in] refreshRate The desired refresh rate, in Hz, of the video mode, or GLFW_DONT_CARE.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
Remarks
The OpenGL or OpenGL ES context will not be destroyed or otherwise affected by any resizing or mode switching, although you may need to update your viewport if the framebuffer size has changed.
The desired window position is ignored, as there is no way for an application to set this property.
Setting the window to full screen will not attempt to change the mode, no matter what the requested size or refresh rate.
This function must only be called from the main thread.
See also
window_monitor
window_full_screen
glfwGetWindowMonitor
glfwSetWindowSize
Since
Added in version 3.2.
References _GLFW_REQUIRE_INIT, _glfwInputError(), _glfwPlatformSetWindowMonitor(), GLFW_DONT_CARE, GLFW_INVALID_VALUE, height, GLFWvidmode::height, NULL, GLFWvidmode::refreshRate, _GLFWwindow::videoMode, width, and GLFWvidmode::width.
Referenced by AuroraFW::GEngine::Window::Window().
glfwGetWindowAttrib()
GLFWAPI int glfwGetWindowAttrib (GLFWwindow * window, int attrib)
Returns an attribute of the specified window.
This function returns the value of an attribute of the specified window or its OpenGL or OpenGL ES context.
Parameters
[in] window The window to query.
[in] attrib The window attribute whose value to return.
Returns
The value of the attribute, or zero if an error occurred.
Possible errors include GLFW_NOT_INITIALIZED, GLFW_INVALID_ENUM and GLFW_PLATFORM_ERROR.
Remarks
Framebuffer related hints are not window attributes. See window_attribs_fb for more information.
Zero is a valid value for many window and context related attributes so you cannot use a return value of zero as an indication of errors. However, this function should not fail as long as it is passed valid arguments and the library has been initialized.
This function must only be called from the main thread.
See also
window_attribs
glfwSetWindowAttrib
Since
Added in version 3.0. Replaces glfwGetWindowParam and glfwGetGLVersion.
References _GLFW_REQUIRE_INIT_OR_RETURN, _glfwInputError(), _glfwPlatformFramebufferTransparent(), _glfwPlatformWindowFocused(), _glfwPlatformWindowHovered(), _glfwPlatformWindowIconified(), _glfwPlatformWindowMaximized(), _glfwPlatformWindowVisible(), _GLFWwindow::autoIconify, _GLFWcontext::client, _GLFWwindow::context, _GLFWcontext::debug, _GLFWwindow::decorated, _GLFWwindow::floating, _GLFWcontext::forward, GLFW_AUTO_ICONIFY, GLFW_CLIENT_API, GLFW_CONTEXT_CREATION_API, GLFW_CONTEXT_NO_ERROR, GLFW_CONTEXT_RELEASE_BEHAVIOR, GLFW_CONTEXT_REVISION, GLFW_CONTEXT_ROBUSTNESS, GLFW_CONTEXT_VERSION_MAJOR, GLFW_CONTEXT_VERSION_MINOR, GLFW_DECORATED, GLFW_FLOATING, GLFW_FOCUSED, GLFW_HOVERED, GLFW_ICONIFIED, GLFW_INVALID_ENUM, GLFW_MAXIMIZED, GLFW_OPENGL_DEBUG_CONTEXT, GLFW_OPENGL_FORWARD_COMPAT, GLFW_OPENGL_PROFILE, GLFW_RESIZABLE, GLFW_TRANSPARENT_FRAMEBUFFER, GLFW_VISIBLE, _GLFWcontext::major, _GLFWcontext::minor, _GLFWcontext::noerror, NULL, _GLFWcontext::profile, _GLFWcontext::release, _GLFWwindow::resizable, _GLFWcontext::revision, _GLFWcontext::robustness, and _GLFWcontext::source.
Referenced by AuroraFW::GEngine::ImGuiLoader::newFrame().
glfwSetWindowAttrib()
GLFWAPI void glfwSetWindowAttrib (GLFWwindow * window, int attrib, int value)
Sets an attribute of the specified window.
This function sets the value of an attribute of the specified window.
The supported attributes are GLFW_DECORATED, GLFW_RESIZABLE, GLFW_FLOATING and GLFW_AUTO_ICONIFY.
Some of these attributes are ignored for full screen windows. The new value will take effect if the window is later made windowed.
Some of these attributes are ignored for windowed mode windows. The new value will take effect if the window is later made full screen.
Parameters
[in] window The window to set the attribute for.
[in] attrib A supported window attribute.
[in] value GLFW_TRUE or GLFW_FALSE.
Possible errors include GLFW_NOT_INITIALIZED, GLFW_INVALID_ENUM, GLFW_INVALID_VALUE and GLFW_PLATFORM_ERROR.
Remarks
Calling glfwGetWindowAttrib will always return the latest value, even if that value is ignored by the current mode of the window.
This function must only be called from the main thread.
See also
window_attribs
glfwGetWindowAttrib
Since
Added in version 3.3.
References _GLFW_REQUIRE_INIT, _glfwInputError(), _glfwPlatformSetWindowDecorated(), _glfwPlatformSetWindowFloating(), _glfwPlatformSetWindowResizable(), _GLFWwindow::autoIconify, _GLFWwindow::decorated, _GLFWwindow::floating, GLFW_AUTO_ICONIFY, GLFW_DECORATED, GLFW_FALSE, GLFW_FLOATING, GLFW_INVALID_ENUM, GLFW_RESIZABLE, GLFW_TRUE, _GLFWwindow::monitor, NULL, _GLFWwindow::resizable, and value.
glfwSetWindowUserPointer()
GLFWAPI void glfwSetWindowUserPointer (GLFWwindow * window, void * pointer)
Sets the user pointer of the specified window.
This function sets the user-defined pointer of the specified window. The current value is retained until the window is destroyed. The initial value is NULL.
Parameters
[in] window The window whose pointer to set.
[in] pointer The new value.
Possible errors include GLFW_NOT_INITIALIZED.
This function may be called from any thread. Access is not synchronized.
See also
window_userptr
glfwGetWindowUserPointer
Since
Added in version 3.0.
References _GLFW_REQUIRE_INIT, NULL, pointer, and _GLFWwindow::userPointer.
Referenced by AuroraFW::GEngine::InputManager::InputManager().
glfwGetWindowUserPointer()
GLFWAPI void* glfwGetWindowUserPointer (GLFWwindow * window)
Returns the user pointer of the specified window.
This function returns the current value of the user-defined pointer of the specified window. The initial value is NULL.
Parameters
[in] window The window whose pointer to return.
Possible errors include GLFW_NOT_INITIALIZED.
This function may be called from any thread. Access is not synchronized.
See also
window_userptr
glfwSetWindowUserPointer
Since
Added in version 3.0.
References _GLFW_REQUIRE_INIT_OR_RETURN, NULL, and _GLFWwindow::userPointer.
glfwSetWindowPosCallback()
GLFWAPI GLFWwindowposfun glfwSetWindowPosCallback (GLFWwindow * window, GLFWwindowposfun cbfun)
Sets the position callback for the specified window.
This function sets the position callback of the specified window, which is called when the window is moved. The callback is provided with the position, in screen coordinates, of the upper-left corner of the client area of the window.
Parameters
[in] window The window whose callback to set.
[in] cbfun The new callback, or NULL to remove the currently set callback.
Returns
The previously set callback, or NULL if no callback was set or the library had not been initialized.
Possible errors include GLFW_NOT_INITIALIZED.
Remarks
This callback will never be called, as there is no way for an application to know its global position.
This function must only be called from the main thread.
See also
window_pos
Since
Added in version 3.0.
References _GLFW_REQUIRE_INIT_OR_RETURN, _GLFW_SWAP_POINTERS, _GLFWwindow::callbacks, NULL, and _GLFWwindow::pos.
glfwSetWindowSizeCallback()
GLFWAPI GLFWwindowsizefun glfwSetWindowSizeCallback (GLFWwindow * window, GLFWwindowsizefun cbfun)
Sets the size callback for the specified window.
This function sets the size callback of the specified window, which is called when the window is resized. The callback is provided with the size, in screen coordinates, of the client area of the window.
Parameters
[in] window The window whose callback to set.
[in] cbfun The new callback, or NULL to remove the currently set callback.
Returns
The previously set callback, or NULL if no callback was set or the library had not been initialized.
Possible errors include GLFW_NOT_INITIALIZED.
This function must only be called from the main thread.
See also
window_size
Since
Added in version 1.0. Added window handle parameter and return value.
References _GLFW_REQUIRE_INIT_OR_RETURN, _GLFW_SWAP_POINTERS, _GLFWwindow::callbacks, NULL, and _GLFWwindow::size.
glfwSetWindowCloseCallback()
GLFWAPI GLFWwindowclosefun glfwSetWindowCloseCallback (GLFWwindow * window, GLFWwindowclosefun cbfun)
Sets the close callback for the specified window.
This function sets the close callback of the specified window, which is called when the user attempts to close the window, for example by clicking the close widget in the title bar.
The close flag is set before this callback is called, but you can modify it at any time with glfwSetWindowShouldClose.
The close callback is not triggered by glfwDestroyWindow.
Parameters
[in] window The window whose callback to set.
[in] cbfun The new callback, or NULL to remove the currently set callback.
Returns
The previously set callback, or NULL if no callback was set or the library had not been initialized.
Possible errors include GLFW_NOT_INITIALIZED.
Remarks
Selecting Quit from the application menu will trigger the close callback for all windows.
This function must only be called from the main thread.
See also
window_close
Since
Added in version 2.5. Added window handle parameter and return value.
References _GLFW_REQUIRE_INIT_OR_RETURN, _GLFW_SWAP_POINTERS, _GLFWwindow::callbacks, _GLFWwindow::close, and NULL.
glfwSetWindowRefreshCallback()
GLFWAPI GLFWwindowrefreshfun glfwSetWindowRefreshCallback (GLFWwindow * window, GLFWwindowrefreshfun cbfun)
Sets the refresh callback for the specified window.
This function sets the refresh callback of the specified window, which is called when the client area of the window needs to be redrawn, for example if the window has been exposed after having been covered by another window.
On compositing window systems such as Aero, Compiz, Aqua or Wayland, where the window contents are saved off-screen, this callback may be called only very infrequently or never at all.
Parameters
[in] window The window whose callback to set.
[in] cbfun The new callback, or NULL to remove the currently set callback.
Returns
The previously set callback, or NULL if no callback was set or the library had not been initialized.
Possible errors include GLFW_NOT_INITIALIZED.
This function must only be called from the main thread.
See also
window_refresh
Since
Added in version 2.5. Added window handle parameter and return value.
References _GLFW_REQUIRE_INIT_OR_RETURN, _GLFW_SWAP_POINTERS, _GLFWwindow::callbacks, NULL, and _GLFWwindow::refresh.
glfwSetWindowFocusCallback()
GLFWAPI GLFWwindowfocusfun glfwSetWindowFocusCallback (GLFWwindow * window, GLFWwindowfocusfun cbfun)
Sets the focus callback for the specified window.
This function sets the focus callback of the specified window, which is called when the window gains or loses input focus.
After the focus callback is called for a window that lost input focus, synthetic key and mouse button release events will be generated for all such that had been pressed. For more information, see glfwSetKeyCallback and glfwSetMouseButtonCallback.
Parameters
[in] window The window whose callback to set.
[in] cbfun The new callback, or NULL to remove the currently set callback.
Returns
The previously set callback, or NULL if no callback was set or the library had not been initialized.
Possible errors include GLFW_NOT_INITIALIZED.
This function must only be called from the main thread.
See also
window_focus
Since
Added in version 3.0.
References _GLFW_REQUIRE_INIT_OR_RETURN, _GLFW_SWAP_POINTERS, _GLFWwindow::callbacks, _GLFWwindow::focus, and NULL.
glfwSetWindowIconifyCallback()
GLFWAPI GLFWwindowiconifyfun glfwSetWindowIconifyCallback (GLFWwindow * window, GLFWwindowiconifyfun cbfun)
Sets the iconify callback for the specified window.
This function sets the iconification callback of the specified window, which is called when the window is iconified or restored.
Parameters
[in] window The window whose callback to set.
[in] cbfun The new callback, or NULL to remove the currently set callback.
Returns
The previously set callback, or NULL if no callback was set or the library had not been initialized.
Possible errors include GLFW_NOT_INITIALIZED.
Remarks
The wl_shell protocol has no concept of iconification, this callback will never be called when using this deprecated protocol.
This function must only be called from the main thread.
See also
window_iconify
Since
Added in version 3.0.
References _GLFW_REQUIRE_INIT_OR_RETURN, _GLFW_SWAP_POINTERS, _GLFWwindow::callbacks, _GLFWwindow::iconify, and NULL.
glfwSetWindowMaximizeCallback()
GLFWAPI GLFWwindowmaximizefun glfwSetWindowMaximizeCallback (GLFWwindow * window, GLFWwindowmaximizefun cbfun)
Sets the maximize callback for the specified window.
This function sets the maximization callback of the specified window, which is called when the window is maximized or restored.
Parameters
[in] window The window whose callback to set.
[in] cbfun The new callback, or NULL to remove the currently set callback.
Returns
The previously set callback, or NULL if no callback was set or the library had not been initialized.
Possible errors include GLFW_NOT_INITIALIZED.
This function must only be called from the main thread.
See also
window_maximize
Since
Added in version 3.3.
References _GLFW_REQUIRE_INIT_OR_RETURN, _GLFW_SWAP_POINTERS, _GLFWwindow::callbacks, _GLFWwindow::maximize, and NULL.
glfwSetFramebufferSizeCallback()
GLFWAPI GLFWframebuffersizefun glfwSetFramebufferSizeCallback (GLFWwindow * window, GLFWframebuffersizefun cbfun)
Sets the framebuffer resize callback for the specified window.
This function sets the framebuffer resize callback of the specified window, which is called when the framebuffer of the specified window is resized.
Parameters
[in] window The window whose callback to set.
[in] cbfun The new callback, or NULL to remove the currently set callback.
Returns
The previously set callback, or NULL if no callback was set or the library had not been initialized.
Possible errors include GLFW_NOT_INITIALIZED.
This function must only be called from the main thread.
See also
window_fbsize
Since
Added in version 3.0.
References _GLFW_REQUIRE_INIT_OR_RETURN, _GLFW_SWAP_POINTERS, _GLFWwindow::callbacks, _GLFWwindow::fbsize, and NULL.
glfwSetWindowContentScaleCallback()
GLFWAPI GLFWwindowcontentscalefun glfwSetWindowContentScaleCallback (GLFWwindow * window, GLFWwindowcontentscalefun cbfun)
Sets the window content scale callback for the specified window.
This function sets the window content scale callback of the specified window, which is called when the content scale of the specified window changes.
Parameters
[in] window The window whose callback to set.
[in] cbfun The new callback, or NULL to remove the currently set callback.
Returns
The previously set callback, or NULL if no callback was set or the library had not been initialized.
Possible errors include GLFW_NOT_INITIALIZED.
This function must only be called from the main thread.
See also
window_scale
glfwGetWindowContentScale
Since
Added in version 3.3.
References _GLFW_REQUIRE_INIT_OR_RETURN, _GLFW_SWAP_POINTERS, _GLFWwindow::callbacks, NULL, and _GLFWwindow::scale.
glfwPollEvents()
GLFWAPI void glfwPollEvents (void)
Processes all pending events.
This function processes only those events that are already in the event queue and then returns immediately. Processing events will cause the window and input callbacks associated with those events to be called.
On some platforms, a window move, resize or menu operation will cause event processing to block. This is due to how event processing is designed on those platforms. You can use the window refresh callback to redraw the contents of your window when necessary during such operations.
Do not assume that callbacks you set will only be called in response to event processing functions like this one. While it is necessary to poll for events, window systems that require GLFW to register callbacks of its own can pass events to GLFW in response to many window system function calls. GLFW will pass those events on to the application callbacks before returning.
Event processing is not required for joystick input to work.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
This function must not be called from a callback.
This function must only be called from the main thread.
See also
events
glfwWaitEvents
glfwWaitEventsTimeout
Since
Added in version 1.0.
References _GLFW_REQUIRE_INIT, and _glfwPlatformPollEvents().
Referenced by main(), and AuroraFW::GEngine::Window::present().
glfwWaitEvents()
GLFWAPI void glfwWaitEvents (void)
Waits until events are queued and processes them.
This function puts the calling thread to sleep until at least one event is available in the event queue. Once one or more events are available, it behaves exactly like glfwPollEvents, i.e. the events in the queue are processed and the function then returns immediately. Processing events will cause the window and input callbacks associated with those events to be called.
Since not all events are associated with callbacks, this function may return without a callback having been called even if you are monitoring all callbacks.
On some platforms, a window move, resize or menu operation will cause event processing to block. This is due to how event processing is designed on those platforms. You can use the window refresh callback to redraw the contents of your window when necessary during such operations.
Do not assume that callbacks you set will only be called in response to event processing functions like this one. While it is necessary to poll for events, window systems that require GLFW to register callbacks of its own can pass events to GLFW in response to many window system function calls. GLFW will pass those events on to the application callbacks before returning.
If no windows exist, this function returns immediately. For synchronization of threads in applications that do not create windows, use your threading library of choice.
Event processing is not required for joystick input to work.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
This function must not be called from a callback.
This function must only be called from the main thread.
See also
events
glfwPollEvents
glfwWaitEventsTimeout
Since
Added in version 2.5.
References _glfw, _GLFW_REQUIRE_INIT, _glfwPlatformWaitEvents(), and _GLFWlibrary::windowListHead.
glfwWaitEventsTimeout()
GLFWAPI void glfwWaitEventsTimeout (double timeout)
Waits with timeout until events are queued and processes them.
This function puts the calling thread to sleep until at least one event is available in the event queue, or until the specified timeout is reached. If one or more events are available, it behaves exactly like glfwPollEvents, i.e. the events in the queue are processed and the function then returns immediately. Processing events will cause the window and input callbacks associated with those events to be called.
The timeout value must be a positive finite number.
Since not all events are associated with callbacks, this function may return without a callback having been called even if you are monitoring all callbacks.
On some platforms, a window move, resize or menu operation will cause event processing to block. This is due to how event processing is designed on those platforms. You can use the window refresh callback to redraw the contents of your window when necessary during such operations.
Do not assume that callbacks you set will only be called in response to event processing functions like this one. While it is necessary to poll for events, window systems that require GLFW to register callbacks of its own can pass events to GLFW in response to many window system function calls. GLFW will pass those events on to the application callbacks before returning.
If no windows exist, this function returns immediately. For synchronization of threads in applications that do not create windows, use your threading library of choice.
Event processing is not required for joystick input to work.
Parameters
[in] timeout The maximum amount of time, in seconds, to wait.
This function must not be called from a callback.
This function must only be called from the main thread.
See also
events
glfwPollEvents
glfwWaitEvents
Since
Added in version 3.2.
References _GLFW_REQUIRE_INIT, _glfwInputError(), _glfwPlatformWaitEventsTimeout(), DBL_MAX, and GLFW_INVALID_VALUE.
glfwPostEmptyEvent()
GLFWAPI void glfwPostEmptyEvent (void)
Posts an empty event to the event queue.
This function posts an empty event from the current thread to the event queue, causing glfwWaitEvents or glfwWaitEventsTimeout to return.
If no windows exist, this function returns immediately. For synchronization of threads in applications that do not create windows, use your threading library of choice.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
This function may be called from any thread.
See also
events
glfwWaitEvents
glfwWaitEventsTimeout
Since
Added in version 3.1.
References _glfw, _GLFW_REQUIRE_INIT, _glfwPlatformPostEmptyEvent(), and _GLFWlibrary::windowListHead.
glfwSwapBuffers()
GLFWAPI void glfwSwapBuffers (GLFWwindow * window)
Swaps the front and back buffers of the specified window.
This function swaps the front and back buffers of the specified window when rendering with OpenGL or OpenGL ES. If the swap interval is greater than zero, the GPU driver waits the specified number of screen updates before swapping the buffers.
The specified window must have an OpenGL or OpenGL ES context. Specifying a window without a context will generate a GLFW_NO_WINDOW_CONTEXT error.
This function does not apply to Vulkan. If you are rendering with Vulkan, see vkQueuePresentKHR instead.
Parameters
[in] window The window whose buffers to swap.
Possible errors include GLFW_NOT_INITIALIZED, GLFW_NO_WINDOW_CONTEXT and GLFW_PLATFORM_ERROR.
Remarks
EGL: The context of the specified window must be current on the calling thread.
This function may be called from any thread.
See also
buffer_swap
glfwSwapInterval
Since
Added in version 1.0. Added window handle parameter.
References _GLFW_REQUIRE_INIT, _glfwInputError(), _GLFWcontext::client, _GLFWwindow::context, GLFW_NO_API, GLFW_NO_WINDOW_CONTEXT, NULL, and _GLFWcontext::swapBuffers.
Referenced by main(), and AuroraFW::GEngine::Window::update().