Aurora Framework: AuroraFW::IO::Timer Class Reference
AuroraFW::IO::Timer Class Reference
Public Member Functions
Timer ()
float elapsed ()
float elapsedMillis ()
void reset ()
Constructor & Destructor Documentation
Timer()
AuroraFW::IO::Timer::Timer ()
References reset().
Member Function Documentation
reset()
void AuroraFW::IO::Timer::reset ()
Referenced by AuroraFW::GEngine::GraphicsContext::renderLoop(), and Timer().
elapsed()
float AuroraFW::IO::Timer::elapsed ()
References elapsedMillis().
Referenced by elapsedMillis().
elapsedMillis()
float AuroraFW::IO::Timer::elapsedMillis ()
References elapsed().
Referenced by elapsed(), and AuroraFW::GEngine::GraphicsContext::renderLoop().
The documentation for this class was generated from the following files:
Timer.h
Timer.cpp