Aurora Framework: Thread.c File Reference
Win32/Thread.c File Reference
Functions
GLFWbool _glfwPlatformCreateMutex (_GLFWmutex *mutex)
GLFWbool _glfwPlatformCreateTls (_GLFWtls *tls)
void _glfwPlatformDestroyMutex (_GLFWmutex *mutex)
void _glfwPlatformDestroyTls (_GLFWtls *tls)
void * _glfwPlatformGetTls (_GLFWtls *tls)
void _glfwPlatformLockMutex (_GLFWmutex *mutex)
void _glfwPlatformSetTls (_GLFWtls *tls, void *value)
void _glfwPlatformUnlockMutex (_GLFWmutex *mutex)
Function Documentation
_glfwPlatformCreateTls()
GLFWbool _glfwPlatformCreateTls (_GLFWtls * tls)
References _glfwInputErrorWin32(), GLFW_FALSE, GLFW_PLATFORM_ERROR, and GLFW_TRUE.
Referenced by glfwInit().
_glfwPlatformDestroyTls()
void _glfwPlatformDestroyTls (_GLFWtls * tls)
References memset().
Referenced by terminate().
_glfwPlatformGetTls()
void* _glfwPlatformGetTls (_GLFWtls * tls)
References GLFW_TRUE.
Referenced by _glfwInputError(), _glfwRefreshContextAttribs(), getProcAddressEGL(), glfwDestroyWindow(), glfwExtensionSupported(), glfwGetCurrentContext(), glfwGetError(), glfwGetProcAddress(), glfwMakeContextCurrent(), glfwSwapInterval(), swapBuffersEGL(), swapIntervalGLX(), swapIntervalNSGL(), and swapIntervalWGL().
_glfwPlatformSetTls()
void _glfwPlatformSetTls (_GLFWtls * tls, void * value)
References GLFW_TRUE, and value.
Referenced by _glfwInputError(), glfwInit(), makeContextCurrentEGL(), makeContextCurrentGLX(), makeContextCurrentNSGL(), makeContextCurrentOSMesa(), and makeContextCurrentWGL().
_glfwPlatformCreateMutex()
GLFWbool _glfwPlatformCreateMutex (_GLFWmutex * mutex)
References GLFW_FALSE, and GLFW_TRUE.
Referenced by glfwInit().
_glfwPlatformDestroyMutex()
void _glfwPlatformDestroyMutex (_GLFWmutex * mutex)
References memset().
Referenced by terminate().
_glfwPlatformLockMutex()
void _glfwPlatformLockMutex (_GLFWmutex * mutex)
References GLFW_TRUE.
Referenced by _glfwInputError().
_glfwPlatformUnlockMutex()
void _glfwPlatformUnlockMutex (_GLFWmutex * mutex)
References GLFW_TRUE.
Referenced by _glfwInputError().