Aurora Framework: spirv_cross::Compiler::CombinedImageSamplerHandler Struct Reference
spirv_cross::Compiler::CombinedImageSamplerHandler Struct Reference
Public Member Functions
CombinedImageSamplerHandler (Compiler &compiler_)
bool begin_function_scope (const uint32_t *args, uint32_t length) override
bool end_function_scope (const uint32_t *args, uint32_t length) override
virtual bool follow_function_call (const SPIRFunction &)
bool handle (spv::Op opcode, const uint32_t *args, uint32_t length) override
void pop_remap_parameters ()
void push_remap_parameters (const SPIRFunction &func, const uint32_t *args, uint32_t length)
void register_combined_image_sampler (SPIRFunction &caller, uint32_t texture_id, uint32_t sampler_id, bool depth)
uint32_t remap_parameter (uint32_t id)
virtual void set_current_block (const SPIRBlock &)
Public Attributes
Compiler & compiler
std::stack< SPIRFunction * > functions
std::stack< std::unordered_map< uint32_t, uint32_t > > parameter_remapping
Constructor & Destructor Documentation
CombinedImageSamplerHandler()
spirv_cross::Compiler::CombinedImageSamplerHandler::CombinedImageSamplerHandler (Compiler & compiler_) inline
Member Function Documentation
handle()
bool Compiler::CombinedImageSamplerHandler::handle (spv::Op opcode, const uint32_t * args, uint32_t length) override virtual
Implements spirv_cross::Compiler::OpcodeHandler.
References spirv_cross::SPIRType::basetype, spirv_cross::SPIRVariable::decoration, spv::DecorationRelaxedPrecision, spv::DimBuffer, spirv_cross::SPIRType::Image, spv::OpAccessChain, spv::OpImageFetch, spv::OpInBoundsAccessChain, spv::OpLoad, spv::OpSampledImage, spirv_cross::SPIRType::pointer, spirv_cross::SPIRType::SampledImage, spirv_cross::SPIRType::Sampler, spirv_cross::IVariant::self, SPIRV_CROSS_THROW, spirv_cross::SPIRType::storage, and spv::StorageClassUniformConstant.
begin_function_scope()
bool Compiler::CombinedImageSamplerHandler::begin_function_scope (const uint32_t * args, uint32_t length) override virtual
Reimplemented from spirv_cross::Compiler::OpcodeHandler.
end_function_scope()
bool Compiler::CombinedImageSamplerHandler::end_function_scope (const uint32_t * args, uint32_t length) override virtual
Reimplemented from spirv_cross::Compiler::OpcodeHandler.
References spirv_cross::IVariant::self.
remap_parameter()
uint32_t Compiler::CombinedImageSamplerHandler::remap_parameter (uint32_t id)
push_remap_parameters()
void Compiler::CombinedImageSamplerHandler::push_remap_parameters (const SPIRFunction & func, const uint32_t * args, uint32_t length)
References spirv_cross::SPIRFunction::arguments.
pop_remap_parameters()
void Compiler::CombinedImageSamplerHandler::pop_remap_parameters ()
register_combined_image_sampler()
void Compiler::CombinedImageSamplerHandler::register_combined_image_sampler (SPIRFunction & caller, uint32_t texture_id, uint32_t sampler_id, bool depth)
References spirv_cross::SPIRFunction::arguments, spirv_cross::SPIRType::basetype, spirv_cross::SPIRFunction::combined_parameters, spirv_cross::SPIRVariable::decoration, spv::DecorationRelaxedPrecision, spirv_cross::SPIRType::ImageType::depth, spirv_cross::SPIRFunction::CombinedImageSamplerParameter::global_image, spirv_cross::SPIRFunction::CombinedImageSamplerParameter::global_sampler, spirv_cross::SPIRFunction::CombinedImageSamplerParameter::id, spirv_cross::SPIRType::image, spirv_cross::SPIRFunction::CombinedImageSamplerParameter::image_id, spirv_cross::join(), spirv_cross::SPIRType::pointer, spirv_cross::SPIRType::SampledImage, spirv_cross::SPIRFunction::CombinedImageSamplerParameter::sampler_id, spirv_cross::IVariant::self, spirv_cross::SPIRFunction::shadow_arguments, spirv_cross::SPIRType::storage, spv::StorageClassFunction, spv::StorageClassGeneric, and spv::StorageClassUniformConstant.
follow_function_call()
virtual bool spirv_cross::Compiler::OpcodeHandler::follow_function_call (const SPIRFunction &) inline virtual inherited
Referenced by spirv_cross::Compiler::traverse_all_reachable_opcodes().
set_current_block()
virtual void spirv_cross::Compiler::OpcodeHandler::set_current_block (const SPIRBlock &) inline virtual inherited
Referenced by spirv_cross::Compiler::traverse_all_reachable_opcodes().
Member Data Documentation
compiler
Compiler& spirv_cross::Compiler::CombinedImageSamplerHandler::compiler
parameter_remapping
std::stack<std::unordered_map<uint32_t, uint32_t> > spirv_cross::Compiler::CombinedImageSamplerHandler::parameter_remapping
functions
std::stack<SPIRFunction *> spirv_cross::Compiler::CombinedImageSamplerHandler::functions
The documentation for this struct was generated from the following files:
Cross.h
Cross.cpp