Aurora Framework: AuroraFW::GEngine::GLBuffer Class Reference
AuroraFW::GEngine::GLBuffer Class Reference
Public Member Functions
GLBuffer (GLenum=GL::Array)
GLBuffer (GLenum, GLsizeiptr, const void *=AFW_NULL, GLenum=GL::StaticDraw)
~GLBuffer ()
void allocate (GLenum, GLsizeiptr, const void *=AFW_NULL, GLenum=GL::StaticDraw)
void allocate (GLsizeiptr, const void *=AFW_NULL, GLenum=GL::StaticDraw)
void bind () const
GLuint getGLBuffer () const
GLsizeiptr length () const
void resize (GLsizeiptr)
GLsizeiptr size () const
void unbind () const
Constructor & Destructor Documentation
GLBuffer() [1/2]
AuroraFW::GEngine::GLBuffer::GLBuffer (GLenum type = GL::Array)
References GLCall.
GLBuffer() [2/2]
AuroraFW::GEngine::GLBuffer::GLBuffer (GLenum type, GLsizeiptr count, const void * data = AFW_NULL, GLenum usage = GL::StaticDraw)
References allocate(), and GLCall.
~GLBuffer()
AuroraFW::GEngine::GLBuffer::~GLBuffer () inline
References GLCall.
Member Function Documentation
allocate() [1/2]
void AuroraFW::GEngine::GLBuffer::allocate (GLenum type, GLsizeiptr count, const void * data = AFW_NULL, GLenum usage = GL::StaticDraw)
References bind(), and GLCall.
Referenced by allocate(), GLBuffer(), and resize().
allocate() [2/2]
void AuroraFW::GEngine::GLBuffer::allocate (GLsizeiptr count, const void * data = AFW_NULL, GLenum usage = GL::StaticDraw) inline
References allocate().
resize()
void AuroraFW::GEngine::GLBuffer::resize (GLsizeiptr size) inline
References allocate(), and size().
getGLBuffer()
GLuint AuroraFW::GEngine::GLBuffer::getGLBuffer () const inline
size()
GLsizeiptr AuroraFW::GEngine::GLBuffer::size () const
References GLCall.
Referenced by resize().
length()
GLsizeiptr AuroraFW::GEngine::GLBuffer::length () const inline
bind()
void AuroraFW::GEngine::GLBuffer::bind () const inline
References GLCall.
Referenced by AuroraFW::GEngine::GLVertexArray::addBuffer(), and allocate().
unbind()
void AuroraFW::GEngine::GLBuffer::unbind () const inline
References GLCall.
Referenced by AuroraFW::GEngine::GLVertexArray::addBuffer().
The documentation for this class was generated from the following files:
Buffer.h
GLBuffer.cpp