Aurora Framework: short_term.c File Reference
short_term.c File Reference
Macros
#define FILTER
#define FILTER
#define STEP(B, MIC, INVA)
Functions
static void Coefficients_0_12 (register int16_t *LARpp_j_1, register int16_t *LARpp_j, register int16_t *LARp)
static void Coefficients_13_26 (register int16_t *LARpp_j_1, register int16_t *LARpp_j, register int16_t *LARp)
static void Coefficients_27_39 (register int16_t *LARpp_j_1, register int16_t *LARpp_j, register int16_t *LARp)
static void Coefficients_40_159 (register int16_t *LARpp_j, register int16_t *LARp)
static void Decoding_of_the_coded_Log_Area_Ratios (int16_t *LARc, int16_t *LARpp)
static void Fast_Short_term_analysis_filtering (struct gsm_state *S, register int16_t *rp, register int k_n, register int16_t *s)
static void Fast_Short_term_synthesis_filtering (struct gsm_state *S, register int16_t *rrp, register int k, register int16_t *wt, register int16_t *sr)
void Gsm_Short_Term_Analysis_Filter (struct gsm_state *S, int16_t *LARc, int16_t *s)
void Gsm_Short_Term_Synthesis_Filter (struct gsm_state *S, int16_t *LARcr, int16_t *wt, int16_t *s)
static void LARp_to_rp (register int16_t *LARp)
static void Short_term_analysis_filtering (struct gsm_state *S, register int16_t *rp, register int k_n, register int16_t *s)
static void Short_term_synthesis_filtering (struct gsm_state *S, register int16_t *rrp, register int k, register int16_t *wt, register int16_t *sr)
Macro Definition Documentation
STEP
#define STEP (B, MIC, INVA)
Value:
temp1   = arith_shift_left (GSM_ADD (*LARc++, MIC), 10) ;   \
        temp1   = GSM_SUB (temp1, B * 2) ;          \
        temp1   = GSM_MULT_R (INVA, temp1) ;        \
        *LARpp++ = GSM_ADD (temp1, temp1) ;
Referenced by Decoding_of_the_coded_Log_Area_Ratios().
FILTER [1/2]
#define FILTER
Value:
(* (S->fast                             \
                    ? Fast_Short_term_analysis_filtering    \
                    : Short_term_analysis_filtering))
Referenced by Gsm_Short_Term_Analysis_Filter(), and Gsm_Short_Term_Synthesis_Filter().
FILTER [2/2]
#define FILTER
Value:
(* (S->fast                         \
                ? Fast_Short_term_synthesis_filtering   \
                : Short_term_synthesis_filtering))
Function Documentation
Decoding_of_the_coded_Log_Area_Ratios()
static void Decoding_of_the_coded_Log_Area_Ratios (int16_t * LARc, int16_t * LARpp) static
References STEP.
Referenced by Gsm_Short_Term_Analysis_Filter(), and Gsm_Short_Term_Synthesis_Filter().
Coefficients_0_12()
static void Coefficients_0_12 (register int16_t * LARpp_j_1, register int16_t * LARpp_j, register int16_t * LARp) static
References GSM_ADD(), and SASR_W().
Referenced by Gsm_Short_Term_Analysis_Filter(), and Gsm_Short_Term_Synthesis_Filter().
Coefficients_13_26()
static void Coefficients_13_26 (register int16_t * LARpp_j_1, register int16_t * LARpp_j, register int16_t * LARp) static
References GSM_ADD(), and SASR_W().
Referenced by Gsm_Short_Term_Analysis_Filter(), and Gsm_Short_Term_Synthesis_Filter().
Coefficients_27_39()
static void Coefficients_27_39 (register int16_t * LARpp_j_1, register int16_t * LARpp_j, register int16_t * LARp) static
References GSM_ADD(), and SASR_W().
Referenced by Gsm_Short_Term_Analysis_Filter(), and Gsm_Short_Term_Synthesis_Filter().
Coefficients_40_159()
static void Coefficients_40_159 (register int16_t * LARpp_j, register int16_t * LARp) static
Referenced by Gsm_Short_Term_Analysis_Filter(), and Gsm_Short_Term_Synthesis_Filter().
LARp_to_rp()
static void LARp_to_rp (register int16_t * LARp) static
References GSM_ADD(), MAX_WORD, and MIN_WORD.
Referenced by Gsm_Short_Term_Analysis_Filter(), and Gsm_Short_Term_Synthesis_Filter().
Short_term_analysis_filtering()
static void Short_term_analysis_filtering (struct gsm_state * S, register int16_t * rp, register int k_n, register int16_t * s) static
References GSM_ADD(), and GSM_MULT_R().
Fast_Short_term_analysis_filtering()
static void Fast_Short_term_analysis_filtering (struct gsm_state * S, register int16_t * rp, register int k_n, register int16_t * s) static
Short_term_synthesis_filtering()
static void Short_term_synthesis_filtering (struct gsm_state * S, register int16_t * rrp, register int k, register int16_t * wt, register int16_t * sr) static
References GSM_ADD(), GSM_SUB(), MAX_WORD, and MIN_WORD.
Fast_Short_term_synthesis_filtering()
static void Fast_Short_term_synthesis_filtering (struct gsm_state * S, register int16_t * rrp, register int k, register int16_t * wt, register int16_t * sr) static
Gsm_Short_Term_Analysis_Filter()
void Gsm_Short_Term_Analysis_Filter (struct gsm_state * S, int16_t * LARc, int16_t * s)
References Coefficients_0_12(), Coefficients_13_26(), Coefficients_27_39(), Coefficients_40_159(), Decoding_of_the_coded_Log_Area_Ratios(), FILTER, and LARp_to_rp().
Referenced by Gsm_Coder().
Gsm_Short_Term_Synthesis_Filter()
void Gsm_Short_Term_Synthesis_Filter (struct gsm_state * S, int16_t * LARcr, int16_t * wt, int16_t * s)
References Coefficients_0_12(), Coefficients_13_26(), Coefficients_27_39(), Coefficients_40_159(), Decoding_of_the_coded_Log_Area_Ratios(), FILTER, and LARp_to_rp().
Referenced by Gsm_Decoder().