Aurora Framework: Window.c File Reference
Window.c File Reference
Functions
void _glfwInputFramebufferSize (_GLFWwindow *window, int width, int height)
void _glfwInputWindowCloseRequest (_GLFWwindow *window)
void _glfwInputWindowContentScale (_GLFWwindow *window, float xscale, float yscale)
void _glfwInputWindowDamage (_GLFWwindow *window)
void _glfwInputWindowFocus (_GLFWwindow *window, GLFWbool focused)
void _glfwInputWindowIconify (_GLFWwindow *window, GLFWbool iconified)
void _glfwInputWindowMaximize (_GLFWwindow *window, GLFWbool maximized)
void _glfwInputWindowMonitor (_GLFWwindow *window, _GLFWmonitor *monitor)
void _glfwInputWindowPos (_GLFWwindow *window, int x, int y)
void _glfwInputWindowSize (_GLFWwindow *window, int width, int height)
GLFWAPI GLFWwindow * glfwCreateWindow (int width, int height, const char *title, GLFWmonitor *monitor, GLFWwindow *share)
Creates a window and its associated context.
void glfwDefaultWindowHints (void)
Resets all window hints to their default values.
GLFWAPI void glfwDestroyWindow (GLFWwindow *handle)
Destroys the specified window and its context.
GLFWAPI void glfwFocusWindow (GLFWwindow *handle)
Brings the specified window to front and sets input focus.
GLFWAPI void glfwGetFramebufferSize (GLFWwindow *handle, int *width, int *height)
Retrieves the size of the framebuffer of the specified window.
GLFWAPI int glfwGetWindowAttrib (GLFWwindow *handle, int attrib)
Returns an attribute of the specified window.
GLFWAPI void glfwGetWindowContentScale (GLFWwindow *handle, float *xscale, float *yscale)
Retrieves the content scale for the specified window.
GLFWAPI void glfwGetWindowFrameSize (GLFWwindow *handle, int *left, int *top, int *right, int *bottom)
Retrieves the size of the frame of the window.
GLFWAPI GLFWmonitor * glfwGetWindowMonitor (GLFWwindow *handle)
Returns the monitor that the window uses for full screen mode.
GLFWAPI float glfwGetWindowOpacity (GLFWwindow *handle)
Returns the opacity of the whole window.
GLFWAPI void glfwGetWindowPos (GLFWwindow *handle, int *xpos, int *ypos)
Retrieves the position of the client area of the specified window.
GLFWAPI void glfwGetWindowSize (GLFWwindow *handle, int *width, int *height)
Retrieves the size of the client area of the specified window.
GLFWAPI void * glfwGetWindowUserPointer (GLFWwindow *handle)
Returns the user pointer of the specified window.
GLFWAPI void glfwHideWindow (GLFWwindow *handle)
Hides the specified window.
GLFWAPI void glfwIconifyWindow (GLFWwindow *handle)
Iconifies the specified window.
GLFWAPI void glfwMaximizeWindow (GLFWwindow *handle)
Maximizes the specified window.
GLFWAPI void glfwPollEvents (void)
Processes all pending events.
GLFWAPI void glfwPostEmptyEvent (void)
Posts an empty event to the event queue.
GLFWAPI void glfwRequestWindowAttention (GLFWwindow *handle)
Requests user attention to the specified window.
GLFWAPI void glfwRestoreWindow (GLFWwindow *handle)
Restores the specified window.
GLFWAPI GLFWframebuffersizefun glfwSetFramebufferSizeCallback (GLFWwindow *handle, GLFWframebuffersizefun cbfun)
Sets the framebuffer resize callback for the specified window.
GLFWAPI void glfwSetWindowAspectRatio (GLFWwindow *handle, int numer, int denom)
Sets the aspect ratio of the specified window.
GLFWAPI void glfwSetWindowAttrib (GLFWwindow *handle, int attrib, int value)
Sets an attribute of the specified window.
GLFWAPI GLFWwindowclosefun glfwSetWindowCloseCallback (GLFWwindow *handle, GLFWwindowclosefun cbfun)
Sets the close callback for the specified window.
GLFWAPI GLFWwindowcontentscalefun glfwSetWindowContentScaleCallback (GLFWwindow *handle, GLFWwindowcontentscalefun cbfun)
Sets the window content scale callback for the specified window.
GLFWAPI GLFWwindowfocusfun glfwSetWindowFocusCallback (GLFWwindow *handle, GLFWwindowfocusfun cbfun)
Sets the focus callback for the specified window.
GLFWAPI void glfwSetWindowIcon (GLFWwindow *handle, int count, const GLFWimage *images)
Sets the icon for the specified window.
GLFWAPI GLFWwindowiconifyfun glfwSetWindowIconifyCallback (GLFWwindow *handle, GLFWwindowiconifyfun cbfun)
Sets the iconify callback for the specified window.
GLFWAPI GLFWwindowmaximizefun glfwSetWindowMaximizeCallback (GLFWwindow *handle, GLFWwindowmaximizefun cbfun)
Sets the maximize callback for the specified window.
GLFWAPI void glfwSetWindowMonitor (GLFWwindow *wh, GLFWmonitor *mh, int xpos, int ypos, int width, int height, int refreshRate)
Sets the mode, monitor, video mode and placement of a window.
GLFWAPI void glfwSetWindowOpacity (GLFWwindow *handle, float opacity)
Sets the opacity of the whole window.
GLFWAPI void glfwSetWindowPos (GLFWwindow *handle, int xpos, int ypos)
Sets the position of the client area of the specified window.
GLFWAPI GLFWwindowposfun glfwSetWindowPosCallback (GLFWwindow *handle, GLFWwindowposfun cbfun)
Sets the position callback for the specified window.
GLFWAPI GLFWwindowrefreshfun glfwSetWindowRefreshCallback (GLFWwindow *handle, GLFWwindowrefreshfun cbfun)
Sets the refresh callback for the specified window.
GLFWAPI void glfwSetWindowShouldClose (GLFWwindow *handle, int value)
Sets the close flag of the specified window.
GLFWAPI void glfwSetWindowSize (GLFWwindow *handle, int width, int height)
Sets the size of the client area of the specified window.
GLFWAPI GLFWwindowsizefun glfwSetWindowSizeCallback (GLFWwindow *handle, GLFWwindowsizefun cbfun)
Sets the size callback for the specified window.
GLFWAPI void glfwSetWindowSizeLimits (GLFWwindow *handle, int minwidth, int minheight, int maxwidth, int maxheight)
Sets the size limits of the specified window.
GLFWAPI void glfwSetWindowTitle (GLFWwindow *handle, const char *title)
Sets the title of the specified window.
GLFWAPI void glfwSetWindowUserPointer (GLFWwindow *handle, void *pointer)
Sets the user pointer of the specified window.
GLFWAPI void glfwShowWindow (GLFWwindow *handle)
Makes the specified window visible.
GLFWAPI void glfwWaitEvents (void)
Waits until events are queued and processes them.
GLFWAPI void glfwWaitEventsTimeout (double timeout)
Waits with timeout until events are queued and processes them.
GLFWAPI void glfwWindowHint (int hint, int value)
Sets the specified window hint to the desired value.
GLFWAPI void glfwWindowHintString (int hint, const char *value)
Sets the specified window hint to the desired value.
GLFWAPI int glfwWindowShouldClose (GLFWwindow *handle)
Checks the close flag of the specified window.
Function Documentation
_glfwInputWindowFocus()
void _glfwInputWindowFocus (_GLFWwindow * window, GLFWbool focused)
References _glfwInputKey(), _glfwInputMouseClick(), _glfwPlatformGetKeyScancode(), _GLFWwindow::callbacks, _GLFWwindow::focus, GLFW_KEY_LAST, GLFW_MOUSE_BUTTON_LAST, GLFW_PRESS, and GLFW_RELEASE.
Referenced by _glfwPlatformDestroyWindow(), keyboardHandleEnter(), keyboardHandleLeave(), processEvent(), windowProc(), and xdgToplevelHandleConfigure().
_glfwInputWindowPos()
void _glfwInputWindowPos (_GLFWwindow * window, int x, int y)
References _GLFWwindow::callbacks, and _GLFWwindow::pos.
Referenced by processEvent(), and windowProc().
_glfwInputWindowSize()
void _glfwInputWindowSize (_GLFWwindow * window, int width, int height)
References _GLFWwindow::callbacks, height, _GLFWwindow::size, and width.
Referenced by handleConfigure(), processEvent(), windowProc(), and xdgToplevelHandleConfigure().
_glfwInputWindowIconify()
void _glfwInputWindowIconify (_GLFWwindow * window, GLFWbool iconified)
References _GLFWwindow::callbacks, and _GLFWwindow::iconify.
Referenced by processEvent(), and windowProc().
_glfwInputWindowMaximize()
void _glfwInputWindowMaximize (_GLFWwindow * window, GLFWbool maximized)
References _GLFWwindow::callbacks, and _GLFWwindow::maximize.
Referenced by processEvent(), and windowProc().
_glfwInputFramebufferSize()
void _glfwInputFramebufferSize (_GLFWwindow * window, int width, int height)
References _GLFWwindow::callbacks, _GLFWwindow::fbsize, height, and width.
Referenced by processEvent(), resizeWindow(), and windowProc().
_glfwInputWindowContentScale()
void _glfwInputWindowContentScale (_GLFWwindow * window, float xscale, float yscale)
References _GLFWwindow::callbacks, and _GLFWwindow::scale.
Referenced by resizeWindow(), and windowProc().
_glfwInputWindowDamage()
void _glfwInputWindowDamage (_GLFWwindow * window)
References _GLFWwindow::callbacks, and _GLFWwindow::refresh.
Referenced by handleConfigure(), processEvent(), windowProc(), and xdgToplevelHandleConfigure().
_glfwInputWindowCloseRequest()
void _glfwInputWindowCloseRequest (_GLFWwindow * window)
References _GLFWwindow::callbacks, _GLFWwindow::close, GLFW_TRUE, and _GLFWwindow::shouldClose.
Referenced by _glfwPlatformPollEvents(), handleEvents(), processEvent(), windowProc(), and xdgToplevelHandleClose().
_glfwInputWindowMonitor()
void _glfwInputWindowMonitor (_GLFWwindow * window, _GLFWmonitor * monitor)
References _GLFWwindow::monitor.
Referenced by _glfwPlatformRestoreWindow(), and _glfwPlatformSetWindowMonitor().