Aurora Framework: gsm.h File Reference
gsm.h File Reference
Macros
#define GSM_MAGIC 0xD /* 13 kbit/s RPE-LTP */
#define GSM_MAJOR 1
#define GSM_MINOR 0
#define GSM_OPT_FAST 2
#define GSM_OPT_FRAME_CHAIN 6
#define GSM_OPT_FRAME_INDEX 5
#define GSM_OPT_LTP_CUT 3
#define GSM_OPT_VERBOSE 1
#define GSM_OPT_WAV49 4
#define GSM_PATCHLEVEL 10
Typedefs
typedef struct gsm_state * gsm
typedef unsigned char gsm_byte
typedef gsm_byte gsm_frame[33]
typedef short gsm_signal
Functions
gsm gsm_create (void)
int gsm_decode (gsm, gsm_byte *, gsm_signal *)
void gsm_destroy (gsm)
void gsm_encode (gsm, gsm_signal *, gsm_byte *)
int gsm_explode (gsm, gsm_byte *, gsm_signal *)
void gsm_implode (gsm, gsm_signal *, gsm_byte *)
void gsm_init (gsm)
int gsm_option (gsm, int, int *)
int gsm_print (FILE *, gsm, gsm_byte *)
Macro Definition Documentation
GSM_MAGIC
#define GSM_MAGIC 0xD /* 13 kbit/s RPE-LTP */
Referenced by gsm_decode(), and gsm_encode().
GSM_PATCHLEVEL
#define GSM_PATCHLEVEL 10
GSM_MINOR
#define GSM_MINOR 0
GSM_MAJOR
#define GSM_MAJOR 1
GSM_OPT_VERBOSE
#define GSM_OPT_VERBOSE 1
Referenced by gsm_option().
GSM_OPT_FAST
#define GSM_OPT_FAST 2
Referenced by gsm_option().
GSM_OPT_LTP_CUT
#define GSM_OPT_LTP_CUT 3
Referenced by gsm_option().
GSM_OPT_WAV49
#define GSM_OPT_WAV49 4
Referenced by gsm610_init(), gsm610_seek(), and gsm_option().
GSM_OPT_FRAME_INDEX
#define GSM_OPT_FRAME_INDEX 5
Referenced by gsm_option().
GSM_OPT_FRAME_CHAIN
#define GSM_OPT_FRAME_CHAIN 6
Referenced by gsm_option().
Typedef Documentation
gsm
typedef struct gsm_state* gsm
gsm_signal
typedef short gsm_signal
gsm_byte
typedef unsigned char gsm_byte
gsm_frame
typedef gsm_byte gsm_frame[33]
Function Documentation
gsm_create()
gsm gsm_create (void)
References memset().
Referenced by gsm610_init().
gsm_init()
void gsm_init (gsm)
References memset(), and gsm_state::nrp.
Referenced by gsm610_seek().
gsm_destroy()
void gsm_destroy (gsm)
Referenced by gsm610_close().
gsm_print()
int gsm_print (FILE * , gsm , gsm_byte *)
gsm_option()
int gsm_option (gsm , int , int *)
References gsm_state::fast, gsm_state::frame_chain, gsm_state::frame_index, GSM_OPT_FAST, GSM_OPT_FRAME_CHAIN, GSM_OPT_FRAME_INDEX, GSM_OPT_LTP_CUT, GSM_OPT_VERBOSE, GSM_OPT_WAV49, gsm_state::ltp_cut, gsm_state::verbose, and gsm_state::wav_fmt.
Referenced by gsm610_init(), and gsm610_seek().
gsm_encode()
void gsm_encode (gsm , gsm_signal * , gsm_byte *)
References gsm_state::frame_chain, gsm_state::frame_index, Gsm_Coder(), GSM_MAGIC, source, and gsm_state::wav_fmt.
Referenced by gsm610_encode_block(), and gsm610_wav_encode_block().
gsm_decode()
int gsm_decode (gsm , gsm_byte * , gsm_signal *)
References gsm_state::frame_chain, gsm_state::frame_index, Gsm_Decoder(), GSM_MAGIC, and gsm_state::wav_fmt.
Referenced by gsm610_decode_block(), and gsm610_wav_decode_block().
gsm_explode()
int gsm_explode (gsm , gsm_byte * , gsm_signal *)
gsm_implode()
void gsm_implode (gsm , gsm_signal * , gsm_byte *)