Aurora Framework: AuroraFW::GEngine::GLShader Class Reference
AuroraFW::GEngine::GLShader Class Reference abstract
Public Types
enum Language {
Language::Unknown, Language::ARB, Language::GLSL, Language::HLSL,
Language::CG, Language::SPIR, Language::SPIR_V, Language::AGAL,
Language::PSSL, Language::MSL, Language::TGSI
}
enum LangVersion {
LangVersion::Unknown, LangVersion::GLSL110, LangVersion::GLSL120, LangVersion::GLSL130,
LangVersion::GLSL140, LangVersion::GLSL150, LangVersion::GLSL330, LangVersion::GLSL330_CORE,
LangVersion::GLSL400, LangVersion::GLSL400_CORE, LangVersion::GLSL410, LangVersion::GLSL410_CORE,
LangVersion::GLSL420, LangVersion::GLSL420_CORE, LangVersion::GLSL430, LangVersion::GLSL430_CORE,
LangVersion::GLSL440, LangVersion::GLSL440_CORE, LangVersion::GLSL450, LangVersion::GLSL450_CORE,
LangVersion::GLSL460, LangVersion::GLSL460_CORE, LangVersion::HLSL11, LangVersion::HLSL20,
LangVersion::HLSL20_A, LangVersion::HLSL20_B, LangVersion::HLSL30, LangVersion::HLSL40,
LangVersion::HLSL41, LangVersion::HLSL50, LangVersion::SPIR_12, LangVersion::SPIR_20,
LangVersion::SPIRV
}
enum Parameter : GLenum {
Type = GL_SHADER_TYPE, DeleteStatus = GL_DELETE_STATUS, CompileStatus = GL_COMPILE_STATUS, LogLength = GL_INFO_LOG_LENGTH,
SourceLength = GL_SHADER_SOURCE_LENGTH
}
enum ShaderType : uint {
Unknown = 0x31, Cached = 0x32, Vertex = 0x1, Fragment = 0x2,
Geometry = 0x4, TessellationControl = 0x8, TessellationEvaluation = 0x10, Compute = 0x20
}
Public Member Functions
GLShader (ShaderType)
~GLShader ()
GLShader & compileFromFile (const std::string)
GLShader & compileFromFile (const char *)
void compileFromFile (std::string, Language)
void compileFromFile (std::map< Language, std::string >)
GLShader & compileFromSource (const std::string &)
GLShader & compileFromSource (const char *)
void compileFromSource (const char *, Language)
GLint getInfo (Parameter)
GLuint getShader ()
void importCachedFile (std::string)
void importCachedFile (std::string, Language)
virtual Shader & importCachedSource (const char *)=0
void importCachedSource (const char *, Language)
GLShader & importCachedSourceFile (const char *)
GLShader & importCachedSourceFile (std::string)
bool isCompiled ()
Static Public Member Functions
static GLuint compileShaderFromFile (std::string)
static GLuint compileShaderFromFile (const char *)
static GLuint compileShaderFromSource (std::string &)
static GLuint compileShaderFromSource (const char *)
static GLint getShaderInfo (GLuint, Parameter)
static GLuint importCachedSourceFileShader (std::string)
static GLuint importCachedSourceFileShader (const char *)
static void Load (Shader::ShaderType, Settings)
Protected Attributes
Settings _settings
Member Enumeration Documentation
Parameter
enum AuroraFW::GEngine::GLShader::Parameter : GLenum
Enumerator
Type
DeleteStatus
CompileStatus
LogLength
SourceLength
ShaderType
enum AuroraFW::GEngine::GLShader::ShaderType : uint
Enumerator
Unknown
Cached
Vertex
Fragment
Geometry
TessellationControl
TessellationEvaluation
Compute
Language
enum AuroraFW::GEngine::RTShader::Language strong inherited
Enumerator
Unknown
ARB
GLSL
HLSL
CG
SPIR
SPIR_V
AGAL
PSSL
MSL
TGSI
LangVersion
enum AuroraFW::GEngine::RTShader::LangVersion strong inherited
Enumerator
Unknown
GLSL110
GLSL120
GLSL130
GLSL140
GLSL150
GLSL330
GLSL330_CORE
GLSL400
GLSL400_CORE
GLSL410
GLSL410_CORE
GLSL420
GLSL420_CORE
GLSL430
GLSL430_CORE
GLSL440
GLSL440_CORE
GLSL450
GLSL450_CORE
GLSL460
GLSL460_CORE
HLSL11
HLSL20
HLSL20_A
HLSL20_B
HLSL30
HLSL40
HLSL41
HLSL50
SPIR_12
SPIR_20
SPIRV
Constructor & Destructor Documentation
GLShader()
AuroraFW::GEngine::GLShader::GLShader (GLShader::ShaderType type)
~GLShader()
AuroraFW::GEngine::GLShader::~GLShader ()
References Cached, and GLCall.
Member Function Documentation
importCachedSourceFileShader() [1/2]
static GLuint AuroraFW::GEngine::GLShader::importCachedSourceFileShader (std::string) static
importCachedSourceFileShader() [2/2]
static GLuint AuroraFW::GEngine::GLShader::importCachedSourceFileShader (const char *) static
compileShaderFromSource() [1/2]
static GLuint AuroraFW::GEngine::GLShader::compileShaderFromSource (std::string &) static
compileShaderFromSource() [2/2]
static GLuint AuroraFW::GEngine::GLShader::compileShaderFromSource (const char *) static
compileShaderFromFile() [1/2]
static GLuint AuroraFW::GEngine::GLShader::compileShaderFromFile (std::string) static
compileShaderFromFile() [2/2]
static GLuint AuroraFW::GEngine::GLShader::compileShaderFromFile (const char *) static
getShaderInfo()
static GLint AuroraFW::GEngine::GLShader::getShaderInfo (GLuint , Parameter) static
importCachedSourceFile() [1/2]
GLShader& AuroraFW::GEngine::GLShader::importCachedSourceFile (const char *)
importCachedSourceFile() [2/2]
GLShader& AuroraFW::GEngine::GLShader::importCachedSourceFile (std::string)
compileFromSource() [1/3]
GLShader& AuroraFW::GEngine::GLShader::compileFromSource (const std::string &)
compileFromSource() [2/3]
GLShader & AuroraFW::GEngine::GLShader::compileFromSource (const char * src) virtual
Implements AuroraFW::GEngine::Shader.
References AFW_NULL, CompileStatus, AuroraFW::CLI::Error, getInfo(), GLCall, AuroraFW::CLI::Log(), and LogLength.
compileFromFile() [1/4]
GLShader& AuroraFW::GEngine::GLShader::compileFromFile (const std::string)
compileFromFile() [2/4]
GLShader& AuroraFW::GEngine::GLShader::compileFromFile (const char *)
getInfo()
GLint AuroraFW::GEngine::GLShader::getInfo (GLShader::Parameter param)
References GLCall.
Referenced by compileFromSource().
isCompiled()
bool AuroraFW::GEngine::GLShader::isCompiled ()
getShader()
GLuint AuroraFW::GEngine::GLShader::getShader ()
Load()
void AuroraFW::GEngine::RTShader::Load (Shader::ShaderType type, RTShader::Settings) static inherited
compileFromFile() [3/4]
void AuroraFW::GEngine::RTShader::compileFromFile (std::string , Language) inherited
compileFromFile() [4/4]
void AuroraFW::GEngine::RTShader::compileFromFile (std::map< Language, std::string >) inherited
importCachedFile() [1/2]
void AuroraFW::GEngine::RTShader::importCachedFile (std::string , Language) inherited
importCachedFile() [2/2]
void AuroraFW::GEngine::Shader::importCachedFile (std::string) inherited
importCachedSource() [1/2]
void AuroraFW::GEngine::RTShader::importCachedSource (const char * , Language) inherited
importCachedSource() [2/2]
virtual Shader& AuroraFW::GEngine::Shader::importCachedSource (const char *) pure virtual inherited
compileFromSource() [3/3]
void AuroraFW::GEngine::RTShader::compileFromSource (const char * , Language) inherited
Member Data Documentation
_settings
Settings AuroraFW::GEngine::RTShader::_settings protected inherited
The documentation for this class was generated from the following files:
opengl/include/AuroraFW/GEngine/GL/Shader.h
GLShader.cpp