Aurora Framework: AuroraFW::GEngine::GLImGuiLoader Class Reference
AuroraFW::GEngine::GLImGuiLoader Class Reference
Public Member Functions
GLImGuiLoader ()
bool createDeviceObjects () override
void invalidateDeviceObjects () override
void newFrame ()
void renderDrawLists (ImDrawData *) override
void Unload ()
Static Public Member Functions
static ImGuiLoader * Load (Window *, InputManager *)
Constructor & Destructor Documentation
GLImGuiLoader()
AuroraFW::GEngine::GLImGuiLoader::GLImGuiLoader ()
Member Function Documentation
createDeviceObjects()
bool AuroraFW::GEngine::GLImGuiLoader::createDeviceObjects () override virtual
Implements AuroraFW::GEngine::ImGuiLoader.
References ImGuiIO::Fonts, ImGui::GetIO(), ImFontAtlas::GetTexDataAsRGBA32(), GL_ARRAY_BUFFER, GL_ARRAY_BUFFER_BINDING, GL_FRAGMENT_SHADER, GL_LINEAR, GL_RGBA, GL_TEXTURE_2D, GL_TEXTURE_BINDING_2D, GL_TEXTURE_MAG_FILTER, GL_TEXTURE_MIN_FILTER, GL_UNPACK_ROW_LENGTH, GL_UNSIGNED_BYTE, GL_VERTEX_ARRAY_BINDING, GL_VERTEX_SHADER, glAttachShader, glBindBuffer, glBindTexture, glBindVertexArray, GLCall, glCompileShader, glCreateProgram, glCreateShader, glGenBuffers, glGenTextures, glGetAttribLocation, glGetIntegerv, glGetUniformLocation, glLinkProgram, glPixelStorei, glShaderSource, glTexImage2D, glTexParameteri, and ImFontAtlas::TexID.
invalidateDeviceObjects()
void AuroraFW::GEngine::GLImGuiLoader::invalidateDeviceObjects () override virtual
Implements AuroraFW::GEngine::ImGuiLoader.
References ImGuiIO::Fonts, ImGui::GetIO(), GLCall, glDeleteBuffers, glDeleteProgram, glDeleteShader, glDeleteTextures, glDetachShader, and ImFontAtlas::TexID.
renderDrawLists()
void AuroraFW::GEngine::GLImGuiLoader::renderDrawLists (ImDrawData * data) override virtual
Implements AuroraFW::GEngine::ImGuiLoader.
References ImDrawCmd::ClipRect, ImDrawList::CmdBuffer, ImVector< T >::Data, ImGuiIO::DisplayFramebufferScale, ImGuiIO::DisplaySize, ImDrawCmd::ElemCount, ImGui::GetIO(), GL_ACTIVE_TEXTURE, GL_ARRAY_BUFFER, GL_ARRAY_BUFFER_BINDING, GL_BLEND, GL_BLEND_DST_ALPHA, GL_BLEND_DST_RGB, GL_BLEND_EQUATION_ALPHA, GL_BLEND_EQUATION_RGB, GL_BLEND_SRC_ALPHA, GL_BLEND_SRC_RGB, GL_CULL_FACE, GL_CURRENT_PROGRAM, GL_DEPTH_TEST, GL_ELEMENT_ARRAY_BUFFER, GL_ELEMENT_ARRAY_BUFFER_BINDING, GL_FALSE, GL_FILL, GL_FLOAT, GL_FRONT_AND_BACK, GL_FUNC_ADD, GL_ONE_MINUS_SRC_ALPHA, GL_POLYGON_MODE, GL_SAMPLER_BINDING, GL_SCISSOR_BOX, GL_SCISSOR_TEST, GL_SRC_ALPHA, GL_STREAM_DRAW, GL_TEXTURE0, GL_TEXTURE_2D, GL_TEXTURE_BINDING_2D, GL_TRIANGLES, GL_TRUE, GL_UNSIGNED_BYTE, GL_UNSIGNED_INT, GL_UNSIGNED_SHORT, GL_VERTEX_ARRAY_BINDING, GL_VIEWPORT, glActiveTexture, glBindBuffer, glBindSampler, glBindTexture, glBindVertexArray, glBlendEquation, glBlendEquationSeparate, glBlendFunc, glBlendFuncSeparate, glBufferData, GLCall, glDeleteVertexArrays, glDisable, glDrawElements, glEnable, glEnableVertexAttribArray, glGenVertexArrays, glGetIntegerv, glIsEnabled, glPolygonMode, glScissor, glUniform1i, glUniformMatrix4fv, glUseProgram, glVertexAttribPointer, glViewport, ImDrawList::IdxBuffer, IM_OFFSETOF, ImVector< T >::Size, ImDrawCmd::TextureId, ImDrawCmd::UserCallback, ImDrawList::VtxBuffer, ImVec4::w, ImVec2::x, ImVec4::x, ImVec2::y, ImVec4::y, and ImVec4::z.
Load()
ImGuiLoader * AuroraFW::GEngine::ImGuiLoader::Load (Window * win, InputManager * input) static inherited
References AFW_CALLBACK, AFW_NEW, AFW_NULLPTR, ImGuiIO::ClipboardUserData, ImGuiIO::GetClipboardTextFn, ImGui::GetIO(), AuroraFW::GEngine::API::Context::getRenderAPI(), ImGuiIO::ImeWindowHandle, ImGuiKey_A, ImGuiKey_Backspace, ImGuiKey_C, ImGuiKey_Delete, ImGuiKey_DownArrow, ImGuiKey_End, ImGuiKey_Enter, ImGuiKey_Escape, ImGuiKey_Home, ImGuiKey_Insert, ImGuiKey_LeftArrow, ImGuiKey_PageDown, ImGuiKey_PageUp, ImGuiKey_RightArrow, ImGuiKey_Space, ImGuiKey_Tab, ImGuiKey_UpArrow, ImGuiKey_V, ImGuiKey_X, ImGuiKey_Y, ImGuiKey_Z, ImGuiMouseCursor_Arrow, ImGuiMouseCursor_ResizeAll, ImGuiMouseCursor_ResizeEW, ImGuiMouseCursor_ResizeNESW, ImGuiMouseCursor_ResizeNS, ImGuiMouseCursor_ResizeNWSE, ImGuiMouseCursor_TextInput, ImGuiIO::KeyMap, OpenGL, AuroraFW::GEngine::ImGuiLoader::renderDrawLists(), ImGuiIO::RenderDrawListsFn, ImGuiIO::SetClipboardTextFn, and AuroraFW::GEngine::Window::window.
Unload()
void AuroraFW::GEngine::ImGuiLoader::Unload () inherited
References ImGuiMouseCursor_Count_, AuroraFW::GEngine::ImGuiLoader::invalidateDeviceObjects(), and memset().
newFrame()
void AuroraFW::GEngine::ImGuiLoader::newFrame () inherited
References ImGuiIO::ConfigFlags, ImGuiIO::DeltaTime, ImGuiIO::DisplayFramebufferScale, ImGuiIO::DisplaySize, FLT_MAX, ImGui::GetIO(), ImGui::GetMouseCursor(), ImGuiConfigFlags_NavEnableGamepad, ImGuiMouseCursor_Arrow, ImGuiMouseCursor_None, ImGuiNavInput_Activate, ImGuiNavInput_Cancel, ImGuiNavInput_DpadDown, ImGuiNavInput_DpadLeft, ImGuiNavInput_DpadRight, ImGuiNavInput_DpadUp, ImGuiNavInput_FocusNext, ImGuiNavInput_FocusPrev, ImGuiNavInput_Input, ImGuiNavInput_LStickDown, ImGuiNavInput_LStickLeft, ImGuiNavInput_LStickRight, ImGuiNavInput_LStickUp, ImGuiNavInput_Menu, ImGuiNavInput_TweakFast, ImGuiNavInput_TweakSlow, MAP_ANALOG, MAP_BUTTON, memset(), ImGuiIO::MouseDown, ImGuiIO::MouseDrawCursor, ImGuiIO::MousePos, ImGuiIO::NavInputs, ImGui::NewFrame(), ImGuiIO::WantMoveMouse, ImVec2::x, and ImVec2::y.
The documentation for this class was generated from the following files:
opengl/include/AuroraFW/GEngine/GL/ImGui/Loader.h
GLImGuiLoader.cpp