Aurora Framework: AuroraFW::AES Class Reference
AuroraFW::AES Class Reference
A class used to encrypt/decrypt AES ciphers.
Static Public Member Functions
static unsigned char * decrypt (const unsigned char *, const int &, unsigned char *)
static unsigned char * encrypt (const unsigned char *, const int &, unsigned char *)
Detailed Description
A class used to encrypt/decrypt AES ciphers.
Since
20170930
Member Function Documentation
encrypt()
unsigned char * AuroraFW::AES::encrypt (const unsigned char * , const int & , unsigned char *) static
References AuroraFW::CLI::Error, AuroraFW::CLI::Log(), memcpy(), and NULL.
decrypt()
unsigned char * AuroraFW::AES::decrypt (const unsigned char * , const int & , unsigned char *) static
References AuroraFW::CLI::Error, AuroraFW::CLI::Log(), memcpy(), and NULL.
The documentation for this class was generated from the following files:
AES.h
AES.cpp