Aurora Framework: code.c File Reference
code.c File Reference
Functions
void Gsm_Coder (struct gsm_state *State, int16_t *s, int16_t *LARc, int16_t *Nc, int16_t *bc, int16_t *Mc, int16_t *xmaxc, int16_t *xMc)
Function Documentation
Gsm_Coder()
void Gsm_Coder (struct gsm_state * State, int16_t * s, int16_t * LARc, int16_t * Nc, int16_t * bc, int16_t * Mc, int16_t * xmaxc, int16_t * xMc)
References gsm_state::dp0, gsm_state::e, GSM_ADD(), Gsm_Long_Term_Predictor(), Gsm_LPC_Analysis(), Gsm_Preprocess(), Gsm_RPE_Encoding(), Gsm_Short_Term_Analysis_Filter(), and memcpy().
Referenced by gsm_encode().