Aurora Framework: mat5.c File Reference
mat5.c File Reference
Classes
struct MAT5_MATRIX
Macros
#define IM_MARKER (('I' << 8) + 'M')
#define MATL_MARKER (MAKE_MARKER ('M', 'A', 'T', 'L'))
#define MI_MARKER (('M' << 8) + 'I')
Enumerations
enum {
MAT5_TYPE_SCHAR = 0x1, MAT5_TYPE_UCHAR = 0x2, MAT5_TYPE_INT16 = 0x3, MAT5_TYPE_UINT16 = 0x4,
MAT5_TYPE_INT32 = 0x5, MAT5_TYPE_UINT32 = 0x6, MAT5_TYPE_FLOAT = 0x7, MAT5_TYPE_DOUBLE = 0x9,
MAT5_TYPE_ARRAY = 0xE, MAT5_TYPE_COMP_USHORT = 0x00020004, MAT5_TYPE_COMP_UINT = 0x00040006
}
Functions
static int mat5_close (SF_PRIVATE *psf)
int mat5_open (SF_PRIVATE *psf)
static int mat5_read_header (SF_PRIVATE *psf)
static int mat5_write_header (SF_PRIVATE *psf, int calc_length)
Macro Definition Documentation
MATL_MARKER
#define MATL_MARKER (MAKE_MARKER ('M', 'A', 'T', 'L'))
IM_MARKER
#define IM_MARKER (('I' << 8) + 'M')
Referenced by mat5_read_header().
MI_MARKER
#define MI_MARKER (('M' << 8) + 'I')
Referenced by mat5_read_header().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
MAT5_TYPE_SCHAR
MAT5_TYPE_UCHAR
MAT5_TYPE_INT16
MAT5_TYPE_UINT16
MAT5_TYPE_INT32
MAT5_TYPE_UINT32
MAT5_TYPE_FLOAT
MAT5_TYPE_DOUBLE
MAT5_TYPE_ARRAY
MAT5_TYPE_COMP_USHORT
MAT5_TYPE_COMP_UINT
Function Documentation
mat5_close()
static int mat5_close (SF_PRIVATE * psf) static
References sf_private_tag::file, mat5_write_header(), and PSF_FILE::mode.
Referenced by mat5_open().
mat5_write_header()
static int mat5_write_header (SF_PRIVATE * psf, int calc_length) static
References BHW2, BHW4, BHW8, BHWv, BHWz, sf_private_tag::bytewidth, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::endian, sf_private_tag::error, sf_private_tag::filelength, sf_private_tag::header, sf_private_tag::indx, MAT5_TYPE_ARRAY, MAT5_TYPE_COMP_UINT, MAT5_TYPE_COMP_USHORT, MAT5_TYPE_DOUBLE, MAT5_TYPE_FLOAT, MAT5_TYPE_INT16, MAT5_TYPE_INT32, MAT5_TYPE_SCHAR, MAT5_TYPE_UCHAR, MAT5_TYPE_UINT32, memset(), psf_binheader_writef(), psf_fseek(), psf_ftell(), psf_fwrite(), psf_get_date_str(), sf_private_tag::ptr, sf_private_tag::rwf_endian, sf_private_tag::sf, SF_CODEC, and SFE_BAD_OPEN_FORMAT.
Referenced by mat5_close(), and mat5_open().
mat5_read_header()
static int mat5_read_header (SF_PRIVATE * psf) static
References sf_private_tag::bytewidth, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::endian, ENDSWAP_16, sf_private_tag::filelength, IM_MARKER, MAT5_TYPE_ARRAY, MAT5_TYPE_COMP_UINT, MAT5_TYPE_COMP_USHORT, MAT5_TYPE_DOUBLE, MAT5_TYPE_FLOAT, MAT5_TYPE_INT16, MAT5_TYPE_INT32, MAT5_TYPE_SCHAR, MAT5_TYPE_UCHAR, MAT5_TYPE_UINT32, MI_MARKER, setup::name, psf_binheader_readf(), psf_ftell(), psf_log_printf(), sf_private_tag::rwf_endian, sf_private_tag::sf, SFE_CHANNEL_COUNT_ZERO, SFE_MAT5_BAD_ENDIAN, SFE_MAT5_NO_BLOCK, SFE_MAT5_SAMPLE_RATE, SFE_UNIMPLEMENTED, SIGNED_SIZEOF, and create_symbols_file::version.
Referenced by mat5_open().
mat5_open()
int mat5_open (SF_PRIVATE * psf)
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::container_close, double64_init(), sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, float32_init(), sf_private_tag::is_pipe, mat5_close(), mat5_read_header(), mat5_write_header(), PSF_FILE::mode, pcm_init(), sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SF_ENDIAN, SFE_BAD_OPEN_FORMAT, SFE_NO_PIPE_WRITE, and sf_private_tag::write_header.
Referenced by psf_open_file().