Aurora Framework: preprocess.c File Reference
preprocess.c File Reference
Functions
void Gsm_Preprocess (struct gsm_state *S, int16_t *s, int16_t *so)
Function Documentation
Gsm_Preprocess()
void Gsm_Preprocess (struct gsm_state * S, int16_t * s, int16_t * so)
References arith_shift_left(), GSM_ADD(), GSM_L_ADD(), GSM_MULT_R(), MIN_WORD, SASR_L(), and SASR_W().
Referenced by Gsm_Coder().