Aurora Framework: spirv_cross::Compiler::DummySamplerForCombinedImageHandler Struct Reference
spirv_cross::Compiler::DummySamplerForCombinedImageHandler Struct Reference
Public Member Functions
DummySamplerForCombinedImageHandler (Compiler &compiler_)
virtual bool begin_function_scope (const uint32_t *, uint32_t)
virtual bool end_function_scope (const uint32_t *, uint32_t)
virtual bool follow_function_call (const SPIRFunction &)
bool handle (spv::Op opcode, const uint32_t *args, uint32_t length) override
virtual void set_current_block (const SPIRBlock &)
Public Attributes
Compiler & compiler
bool need_dummy_sampler = false
Constructor & Destructor Documentation
DummySamplerForCombinedImageHandler()
spirv_cross::Compiler::DummySamplerForCombinedImageHandler::DummySamplerForCombinedImageHandler (Compiler & compiler_) inline
Member Function Documentation
handle()
bool Compiler::DummySamplerForCombinedImageHandler::handle (spv::Op opcode, const uint32_t * args, uint32_t length) override virtual
Implements spirv_cross::Compiler::OpcodeHandler.
References spirv_cross::SPIRType::basetype, spv::DimBuffer, spirv_cross::SPIRType::Image, spv::OpAccessChain, spv::OpImageFetch, spv::OpInBoundsAccessChain, spv::OpLoad, and SPIRV_CROSS_THROW.
follow_function_call()
virtual bool spirv_cross::Compiler::OpcodeHandler::follow_function_call (const SPIRFunction &) inline virtual inherited
Referenced by spirv_cross::Compiler::traverse_all_reachable_opcodes().
set_current_block()
virtual void spirv_cross::Compiler::OpcodeHandler::set_current_block (const SPIRBlock &) inline virtual inherited
Referenced by spirv_cross::Compiler::traverse_all_reachable_opcodes().
begin_function_scope()
virtual bool spirv_cross::Compiler::OpcodeHandler::begin_function_scope (const uint32_t * , uint32_t) inline virtual inherited
Reimplemented in spirv_cross::Compiler::CombinedImageSamplerUsageHandler, and spirv_cross::Compiler::CombinedImageSamplerHandler.
Referenced by spirv_cross::Compiler::traverse_all_reachable_opcodes().
end_function_scope()
virtual bool spirv_cross::Compiler::OpcodeHandler::end_function_scope (const uint32_t * , uint32_t) inline virtual inherited
Reimplemented in spirv_cross::Compiler::CombinedImageSamplerHandler.
Referenced by spirv_cross::Compiler::traverse_all_reachable_opcodes().
Member Data Documentation
compiler
Compiler& spirv_cross::Compiler::DummySamplerForCombinedImageHandler::compiler
need_dummy_sampler
bool spirv_cross::Compiler::DummySamplerForCombinedImageHandler::need_dummy_sampler = false
Referenced by spirv_cross::Compiler::build_dummy_sampler_for_combined_images().
The documentation for this struct was generated from the following files:
Cross.h
Cross.cpp