Aurora Framework: pvf.c File Reference
pvf.c File Reference
Macros
#define PVF1_MARKER (MAKE_MARKER ('P', 'V', 'F', '1'))
Functions
static int pvf_close (SF_PRIVATE *psf)
static int pvf_close (SF_PRIVATE *UNUSED(psf))
int pvf_open (SF_PRIVATE *psf)
static int pvf_read_header (SF_PRIVATE *psf)
static int pvf_write_header (SF_PRIVATE *psf, int calc_length)
static int pvf_write_header (SF_PRIVATE *psf, int UNUSED(calc_length))
Macro Definition Documentation
PVF1_MARKER
#define PVF1_MARKER (MAKE_MARKER ('P', 'V', 'F', '1'))
Referenced by pvf_read_header().
Function Documentation
pvf_close() [1/2]
static int pvf_close (SF_PRIVATE * psf) static
Referenced by pvf_open().
pvf_write_header() [1/2]
static int pvf_write_header (SF_PRIVATE * psf, int calc_length) static
Referenced by pvf_open().
pvf_read_header()
static int pvf_read_header (SF_PRIVATE * psf) static
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::endian, sf_private_tag::filelength, psf_binheader_readf(), psf_ftell(), psf_log_printf(), PVF1_MARKER, sf_private_tag::sf, SFE_PVF_BAD_BITWIDTH, SFE_PVF_BAD_HEADER, and SFE_PVF_NO_PVF1.
Referenced by pvf_open().
pvf_open()
int pvf_open (SF_PRIVATE * psf)
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::container_close, sf_private_tag::endian, sf_private_tag::error, sf_private_tag::file, sf_private_tag::filelength, PSF_FILE::mode, pcm_init(), pvf_close(), pvf_read_header(), pvf_write_header(), sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SFE_BAD_OPEN_FORMAT, and sf_private_tag::write_header.
Referenced by psf_open_file().
pvf_close() [2/2]
static int pvf_close (SF_PRIVATE * UNUSEDpsf) static
pvf_write_header() [2/2]
static int pvf_write_header (SF_PRIVATE * psf, int UNUSEDcalc_length) static
References sf_private_tag::bytewidth, sf_private_tag::dataoffset, sf_private_tag::error, sf_private_tag::header, sf_private_tag::indx, sf_private_tag::is_pipe, sf_private_tag::len, sf_private_tag::pipeoffset, psf_fseek(), psf_ftell(), psf_fwrite(), sf_private_tag::ptr, and sf_private_tag::sf.