Aurora Framework: AuroraFW::Math::mat< T, m, n > Struct Template Reference
AuroraFW::Math::mat< T, m, n > Struct Template Reference
Public Member Functions
mat ()
constexpr mat (T)
mat (const mat< T, m, n > &)
mat (T *)
vec4< T > getColumn (uint_t) const
vec3< T > getPos () const
mat< T, m, n > & invert ()
mat & multiply (const mat< T, m, n > &)
vec3< T > multiply (const vec3< T > &) const
vec4< T > multiply (const vec4< T > &) const
mat< T, m, n > operator* (const mat< T, m, n > &)
vec3< T > operator* (const vec3< T > &) const
vec3< T > operator* (const vec3< T > &)
vec3< T > operator* (const vec4< T > &) const
vec4< T > operator* (const vec4< T > &)
mat< T, m, n > & operator*= (const mat< T, m, n > &)
void setColumn (uint_t, const vec4< T > &)
void setPos (const vec3< T > &)
std::string toString () const
Static Public Member Functions
static mat< T, m, n > identity ()
static mat< T, m, n > invert (const mat4< T > &)
static mat< T, m, n > lookAt (const vec3< T > &, const vec3< T > &, const vec3< T > &)
static mat< T, m, n > orthographic (T, T, T, T, T, T)
static mat< T, m, n > perspective (T, T, T, T)
static mat< T, m, n > rotation (T, const vec3< T > &)
static mat< T, m, n > scale (const vec3< T > &)
static mat< T, m, n > translate (const vec3< T > &)
static mat< T, m, n > transpose (const mat4< T > &)
Public Attributes
T matrix [m][n]
Friends
template<typename t >
std::ostream & operator<< (std::ostream &, const vec3< T > &)
Constructor & Destructor Documentation
mat() [1/4]
template<typename T , uint m, uint n> AuroraFW::Math::mat< T, m, n >::mat ()
References memset().
mat() [2/4]
template<typename T , uint m, uint n> constexpr AuroraFW::Math::mat< T, m, n >::mat (T diagonal)
References memset().
mat() [3/4]
template<typename T , uint m, uint n> AuroraFW::Math::mat< T, m, n >::mat (const mat< T, m, n > & mat)
References AuroraFW::Math::mat< T, m, n >::matrix.
mat() [4/4]
template<typename T , uint m, uint n> AuroraFW::Math::mat< T, m, n >::mat (T * mat)
References memcpy().
Member Function Documentation
multiply() [1/3]
template<typename T , uint m, uint n> mat< T, m, n > & AuroraFW::Math::mat< T, m, n >::multiply (const mat< T, m, n > & mat)
References AuroraFW::Math::mat< T, m, n >::matrix, and memcpy().
multiply() [2/3]
template<typename T , uint m, uint n> vec3< T > AuroraFW::Math::mat< T, m, n >::multiply (const vec3< T > & vec) const
References AuroraFW::Math::vec3< T >::multiply().
multiply() [3/3]
template<typename T , uint m, uint n> vec4< T > AuroraFW::Math::mat< T, m, n >::multiply (const vec4< T > & vec) const
References AuroraFW::Math::vec4< T >::multiply().
operator*() [1/5]
template<typename T , uint m, uint n> mat< T, m, n > AuroraFW::Math::mat< T, m, n >::operator* (const mat< T, m, n > & mat)
operator*=()
template<typename T , uint m, uint n> mat< T, m, n > & AuroraFW::Math::mat< T, m, n >::operator*= (const mat< T, m, n > & mat)
operator*() [2/5]
template<typename T, uint m, uint n> vec3<T> AuroraFW::Math::mat< T, m, n >::operator* (const vec3< T > &) const
operator*() [3/5]
template<typename T , uint m, uint n> vec3< T > AuroraFW::Math::mat< T, m, n >::operator* (const vec3< T > & vec)
operator*() [4/5]
template<typename T, uint m, uint n> vec3<T> AuroraFW::Math::mat< T, m, n >::operator* (const vec4< T > &) const
operator*() [5/5]
template<typename T , uint m, uint n> vec4< T > AuroraFW::Math::mat< T, m, n >::operator* (const vec4< T > & vec)
invert() [1/2]
template<typename T, uint m, uint n> mat<T, m, n>& AuroraFW::Math::mat< T, m, n >::invert ()
getColumn()
template<typename T, uint m, uint n> vec4<T> AuroraFW::Math::mat< T, m, n >::getColumn (uint_t) const
getPos()
template<typename T, uint m, uint n> vec3<T> AuroraFW::Math::mat< T, m, n >::getPos () const
setColumn()
template<typename T, uint m, uint n> void AuroraFW::Math::mat< T, m, n >::setColumn (uint_t , const vec4< T > &)
setPos()
template<typename T, uint m, uint n> void AuroraFW::Math::mat< T, m, n >::setPos (const vec3< T > &)
identity()
template<typename T , uint m, uint n> mat< T, m, n > AuroraFW::Math::mat< T, m, n >::identity () static
orthographic()
template<typename T , uint m, uint n> mat< T, m, n > AuroraFW::Math::mat< T, m, n >::orthographic (T left, T right, T bottom, T top, T near_, T far_) static
References AuroraFW::Math::mat< T, m, n >::matrix.
perspective()
template<typename T, uint m, uint n> static mat<T, m, n> AuroraFW::Math::mat< T, m, n >::perspective (T , T , T , T) static
lookAt()
template<typename T, uint m, uint n> static mat<T, m, n> AuroraFW::Math::mat< T, m, n >::lookAt (const vec3< T > & , const vec3< T > & , const vec3< T > &) static
translate()
template<typename T , uint m, uint n> mat< T, m, n > AuroraFW::Math::mat< T, m, n >::translate (const vec3< T > & vec) static
References AuroraFW::Math::mat< T, m, n >::matrix, AuroraFW::Math::vec3< T >::x, AuroraFW::Math::vec3< T >::y, and AuroraFW::Math::vec3< T >::z.
rotation()
template<typename T, uint m, uint n> static mat<T, m, n> AuroraFW::Math::mat< T, m, n >::rotation (T , const vec3< T > &) static
scale()
template<typename T, uint m, uint n> static mat<T, m, n> AuroraFW::Math::mat< T, m, n >::scale (const vec3< T > &) static
invert() [2/2]
template<typename T, uint m, uint n> static mat<T, m, n> AuroraFW::Math::mat< T, m, n >::invert (const mat4< T > &) static
transpose()
template<typename T, uint m, uint n> static mat<T, m, n> AuroraFW::Math::mat< T, m, n >::transpose (const mat4< T > &) static
toString()
template<typename T, uint m, uint n> std::string AuroraFW::Math::mat< T, m, n >::toString () const
Friends And Related Function Documentation
operator<<
template<typename T, uint m, uint n> template<typename t > std::ostream& operator<< (std::ostream & stream, const vec3< T > & vector) friend
Member Data Documentation
matrix
template<typename T, uint m, uint n> T AuroraFW::Math::mat< T, m, n >::matrix[m][n]
Referenced by AuroraFW::Math::mat< T, m, n >::mat(), AuroraFW::Math::mat< T, m, n >::multiply(), AuroraFW::Math::mat< T, m, n >::orthographic(), AuroraFW::GEngine::GLProgram::setValue(), and AuroraFW::Math::mat< T, m, n >::translate().
The documentation for this struct was generated from the following files:
Matrix.h
Matrix_impl.h