Aurora Framework: DITHER_DATA Struct Reference
DITHER_DATA Struct Reference
Public Attributes
double buffer [SF_BUFFER_LEN/sizeof(double)]
sf_count_t(* read_double)(SF_PRIVATE *psf, double *ptr, sf_count_t len)
double read_double_dither_bits
sf_count_t(* read_float)(SF_PRIVATE *psf, float *ptr, sf_count_t len)
double read_float_dither_scale
sf_count_t(* read_int)(SF_PRIVATE *psf, int *ptr, sf_count_t len)
int read_int_dither_bits
sf_count_t(* read_short)(SF_PRIVATE *psf, short *ptr, sf_count_t len)
int read_short_dither_bits
sf_count_t(* write_double)(SF_PRIVATE *psf, const double *ptr, sf_count_t len)
double write_double_dither_bits
sf_count_t(* write_float)(SF_PRIVATE *psf, const float *ptr, sf_count_t len)
double write_float_dither_scale
sf_count_t(* write_int)(SF_PRIVATE *psf, const int *ptr, sf_count_t len)
int write_int_dither_bits
sf_count_t(* write_short)(SF_PRIVATE *psf, const short *ptr, sf_count_t len)
int write_short_dither_bits
Member Data Documentation
read_short_dither_bits
int DITHER_DATA::read_short_dither_bits
read_int_dither_bits
int DITHER_DATA::read_int_dither_bits
write_short_dither_bits
int DITHER_DATA::write_short_dither_bits
write_int_dither_bits
int DITHER_DATA::write_int_dither_bits
read_float_dither_scale
double DITHER_DATA::read_float_dither_scale
read_double_dither_bits
double DITHER_DATA::read_double_dither_bits
write_float_dither_scale
double DITHER_DATA::write_float_dither_scale
write_double_dither_bits
double DITHER_DATA::write_double_dither_bits
read_short
sf_count_t(* DITHER_DATA::read_short) (SF_PRIVATE *psf, short *ptr, sf_count_t len)
Referenced by dither_init().
read_int
sf_count_t(* DITHER_DATA::read_int) (SF_PRIVATE *psf, int *ptr, sf_count_t len)
Referenced by dither_init().
read_float
sf_count_t(* DITHER_DATA::read_float) (SF_PRIVATE *psf, float *ptr, sf_count_t len)
Referenced by dither_init().
read_double
sf_count_t(* DITHER_DATA::read_double) (SF_PRIVATE *psf, double *ptr, sf_count_t len)
Referenced by dither_init().
write_short
sf_count_t(* DITHER_DATA::write_short) (SF_PRIVATE *psf, const short *ptr, sf_count_t len)
Referenced by dither_init(), and dither_write_short().
write_int
sf_count_t(* DITHER_DATA::write_int) (SF_PRIVATE *psf, const int *ptr, sf_count_t len)
Referenced by dither_init(), and dither_write_int().
write_float
sf_count_t(* DITHER_DATA::write_float) (SF_PRIVATE *psf, const float *ptr, sf_count_t len)
Referenced by dither_init(), and dither_write_float().
write_double
sf_count_t(* DITHER_DATA::write_double) (SF_PRIVATE *psf, const double *ptr, sf_count_t len)
Referenced by dither_init(), and dither_write_double().
buffer
double DITHER_DATA::buffer[SF_BUFFER_LEN/sizeof(double)]
Referenced by dither_write_double(), dither_write_float(), dither_write_int(), and dither_write_short().
The documentation for this struct was generated from the following file:
dither.c