Aurora Framework: AuroraFW::Application Struct Reference
AuroraFW::Application Struct Reference
Public Member Functions
Application (int argc=0, char *argv[]=NULL, void(mainFunction)(Application *)=[](Application *){})
~Application ()
Static Public Member Functions
static void ExitFail ()
static void ExitSuccess ()
Public Attributes
std::vector< std::string > * args
Constructor & Destructor Documentation
Application()
AuroraFW::Application::Application (int argc = 0, char * argv[] = NULL, void(mainFunction)(Application *) = [](Application *){})
~Application()
AuroraFW::Application::~Application ()
References args, and AuroraFW::DebugManager::Log().
Member Function Documentation
ExitSuccess()
void AuroraFW::Application::ExitSuccess () static
References AuroraFW::DebugManager::Log().
ExitFail()
void AuroraFW::Application::ExitFail () static
References AuroraFW::DebugManager::Log().
Member Data Documentation
args
std::vector<std::string>* AuroraFW::Application::args
Referenced by ~Application().
The documentation for this struct was generated from the following files:
core/include/AuroraFW/Core/Application.h
core/src/Application.cpp