Aurora Framework: Context.c File Reference
GLX/Context.c File Reference
Macros
#define GLXBadProfileARB 13
#define setAttrib(a, v)
Functions
GLFWbool _glfwChooseVisualGLX (const _GLFWwndconfig *wndconfig, const _GLFWctxconfig *ctxconfig, const _GLFWfbconfig *fbconfig, Visual **visual, int *depth)
GLFWbool _glfwCreateContextGLX (_GLFWwindow *window, const _GLFWctxconfig *ctxconfig, const _GLFWfbconfig *fbconfig)
GLFWbool _glfwInitGLX (void)
void _glfwTerminateGLX (void)
static GLFWbool chooseGLXFBConfig (const _GLFWfbconfig *desired, GLXFBConfig *result)
static GLXContext createLegacyContextGLX (_GLFWwindow *window, GLXFBConfig fbconfig, GLXContext share)
static void destroyContextGLX (_GLFWwindow *window)
static int extensionSupportedGLX (const char *extension)
static int getGLXFBConfigAttrib (GLXFBConfig fbconfig, int attrib)
static GLFWglproc getProcAddressGLX (const char *procname)
GLFWAPI GLXContext glfwGetGLXContext (GLFWwindow *handle)
GLFWAPI GLXWindow glfwGetGLXWindow (GLFWwindow *handle)
static void makeContextCurrentGLX (_GLFWwindow *window)
static void swapBuffersGLX (_GLFWwindow *window)
static void swapIntervalGLX (int interval)
Macro Definition Documentation
GLXBadProfileARB
#define GLXBadProfileARB 13
Referenced by _glfwCreateContextGLX().
setAttrib
#define setAttrib (a, v)
Value:
{ \
    assert((size_t) (index + 1) < sizeof(attribs) / sizeof(attribs[0])); \
    attribs[index++] = a; \
    attribs[index++] = v; \
}
Referenced by _glfwCreateContextGLX().
Function Documentation
getGLXFBConfigAttrib()
static int getGLXFBConfigAttrib (GLXFBConfig fbconfig, int attrib) static
References _glfw, glXGetFBConfigAttrib, and value.
Referenced by chooseGLXFBConfig().
chooseGLXFBConfig()
static GLFWbool chooseGLXFBConfig (const _GLFWfbconfig * desired, GLXFBConfig * result) static
References _glfw, _glfwChooseFBConfig(), _glfwInputError(), _glfwIsVisualTransparentX11(), _GLFWfbconfig::accumAlphaBits, _GLFWfbconfig::accumBlueBits, _GLFWfbconfig::accumGreenBits, _GLFWfbconfig::accumRedBits, _GLFWfbconfig::alphaBits, _GLFWfbconfig::auxBuffers, _GLFWfbconfig::blueBits, _GLFWfbconfig::depthBits, _GLFWfbconfig::doublebuffer, getGLXFBConfigAttrib(), GLFW_API_UNAVAILABLE, GLFW_FALSE, GLFW_TRUE, GLX_ACCUM_ALPHA_SIZE, GLX_ACCUM_BLUE_SIZE, GLX_ACCUM_GREEN_SIZE, GLX_ACCUM_RED_SIZE, GLX_ALPHA_SIZE, GLX_AUX_BUFFERS, GLX_BLUE_SIZE, GLX_DEPTH_SIZE, GLX_DOUBLEBUFFER, GLX_DRAWABLE_TYPE, GLX_FRAMEBUFFER_SRGB_CAPABLE_ARB, GLX_GREEN_SIZE, GLX_RED_SIZE, GLX_RENDER_TYPE, GLX_RGBA_BIT, GLX_SAMPLES, GLX_STENCIL_SIZE, GLX_STEREO, GLX_VENDOR, GLX_WINDOW_BIT, glXGetClientString, glXGetFBConfigs, glXGetVisualFromFBConfig, _GLFWfbconfig::greenBits, _GLFWfbconfig::handle, NULL, _GLFWfbconfig::redBits, _GLFWfbconfig::samples, _GLFWfbconfig::sRGB, _GLFWfbconfig::stencilBits, _GLFWfbconfig::stereo, and _GLFWfbconfig::transparent.
Referenced by _glfwChooseVisualGLX(), and _glfwCreateContextGLX().
createLegacyContextGLX()
static GLXContext createLegacyContextGLX (_GLFWwindow * window, GLXFBConfig fbconfig, GLXContext share) static
References _glfw, GLX_RGBA_TYPE, and glXCreateNewContext.
Referenced by _glfwCreateContextGLX().
makeContextCurrentGLX()
static void makeContextCurrentGLX (_GLFWwindow * window) static
References _glfw, _glfwInputError(), _glfwPlatformSetTls(), _GLFWwindow::context, _GLFWlibrary::contextSlot, GLFW_PLATFORM_ERROR, glXMakeCurrent, AuroraFW::None, and NULL.
Referenced by _glfwCreateContextGLX().
swapBuffersGLX()
static void swapBuffersGLX (_GLFWwindow * window) static
References _glfw, _GLFWwindow::context, and glXSwapBuffers.
Referenced by _glfwCreateContextGLX().
swapIntervalGLX()
static void swapIntervalGLX (int interval) static
References _glfw, _glfwPlatformGetTls(), _GLFWwindow::context, and _GLFWlibrary::contextSlot.
Referenced by _glfwCreateContextGLX().
extensionSupportedGLX()
static int extensionSupportedGLX (const char * extension) static
References _glfw, _glfwStringInExtensionString(), GLFW_FALSE, GLFW_TRUE, and glXQueryExtensionsString.
Referenced by _glfwCreateContextGLX(), and _glfwInitGLX().
getProcAddressGLX()
static GLFWglproc getProcAddressGLX (const char * procname) static
References _glfw, _glfw_dlsym, and _GLFWlibrary::handle.
Referenced by _glfwCreateContextGLX(), and _glfwInitGLX().
destroyContextGLX()
static void destroyContextGLX (_GLFWwindow * window) static
References _glfw, _GLFWwindow::context, glXDestroyContext, glXDestroyWindow, AuroraFW::None, and NULL.
Referenced by _glfwCreateContextGLX().
_glfwInitGLX()
GLFWbool _glfwInitGLX (void)
References _glfw, _glfw_dlopen, _glfw_dlsym, _glfwInputError(), extensionSupportedGLX(), getProcAddressGLX(), GLFW_API_UNAVAILABLE, GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, glXQueryExtension, glXQueryVersion, _GLFWlibrary::handle, and NULL.
Referenced by _glfwPlatformCreateWindow().
_glfwTerminateGLX()
void _glfwTerminateGLX (void)
References _glfw, _glfw_dlclose, _GLFWlibrary::handle, and NULL.
Referenced by _glfwPlatformTerminate().
_glfwCreateContextGLX()
GLFWbool _glfwCreateContextGLX (_GLFWwindow * window, const _GLFWctxconfig * ctxconfig, const _GLFWfbconfig * fbconfig)
References _glfw, _glfwGrabErrorHandlerX11(), _glfwInputError(), _glfwInputErrorX11(), _glfwReleaseErrorHandlerX11(), chooseGLXFBConfig(), _GLFWctxconfig::client, _GLFWwindow::context, createLegacyContextGLX(), _GLFWctxconfig::debug, _GLFWcontext::destroy, destroyContextGLX(), _GLFWcontext::extensionSupported, extensionSupportedGLX(), _GLFWctxconfig::forward, _GLFWcontext::getProcAddress, getProcAddressGLX(), GLFW_API_UNAVAILABLE, GLFW_FALSE, GLFW_FORMAT_UNAVAILABLE, GLFW_LOSE_CONTEXT_ON_RESET, GLFW_NO_RESET_NOTIFICATION, GLFW_OPENGL_ANY_PROFILE, GLFW_OPENGL_API, GLFW_OPENGL_COMPAT_PROFILE, GLFW_OPENGL_CORE_PROFILE, GLFW_OPENGL_ES_API, GLFW_PLATFORM_ERROR, GLFW_RELEASE_BEHAVIOR_FLUSH, GLFW_RELEASE_BEHAVIOR_NONE, GLFW_TRUE, GLFW_VERSION_UNAVAILABLE, GLX_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB, GLX_CONTEXT_CORE_PROFILE_BIT_ARB, GLX_CONTEXT_DEBUG_BIT_ARB, GLX_CONTEXT_ES2_PROFILE_BIT_EXT, GLX_CONTEXT_FLAGS_ARB, GLX_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB, GLX_CONTEXT_MAJOR_VERSION_ARB, GLX_CONTEXT_MINOR_VERSION_ARB, GLX_CONTEXT_OPENGL_NO_ERROR_ARB, GLX_CONTEXT_PROFILE_MASK_ARB, GLX_CONTEXT_RELEASE_BEHAVIOR_ARB, GLX_CONTEXT_RELEASE_BEHAVIOR_FLUSH_ARB, GLX_CONTEXT_RELEASE_BEHAVIOR_NONE_ARB, GLX_CONTEXT_RESET_NOTIFICATION_STRATEGY_ARB, GLX_CONTEXT_ROBUST_ACCESS_BIT_ARB, GLX_LOSE_CONTEXT_ON_RESET_ARB, GLX_NO_RESET_NOTIFICATION_ARB, GLXBadProfileARB, glXCreateWindow, _GLFWctxconfig::major, makeContextCurrentGLX(), _GLFWcontext::makeCurrent, _GLFWctxconfig::minor, _GLFWctxconfig::noerror, AuroraFW::None, NULL, _GLFWctxconfig::profile, _GLFWctxconfig::release, _GLFWctxconfig::robustness, setAttrib, _GLFWctxconfig::share, _GLFWcontext::swapBuffers, swapBuffersGLX(), _GLFWcontext::swapInterval, and swapIntervalGLX().
Referenced by _glfwPlatformCreateWindow().
_glfwChooseVisualGLX()
GLFWbool _glfwChooseVisualGLX (const _GLFWwndconfig * wndconfig, const _GLFWctxconfig * ctxconfig, const _GLFWfbconfig * fbconfig, Visual ** visual, int * depth)
References _glfw, _glfwInputError(), chooseGLXFBConfig(), GLFW_FALSE, GLFW_FORMAT_UNAVAILABLE, GLFW_PLATFORM_ERROR, GLFW_TRUE, and glXGetVisualFromFBConfig.
Referenced by _glfwPlatformCreateWindow().
glfwGetGLXContext()
GLFWAPI GLXContext glfwGetGLXContext (GLFWwindow * handle)
References _GLFW_REQUIRE_INIT_OR_RETURN, _glfwInputError(), _GLFWcontext::client, _GLFWwindow::context, GLFW_NO_API, GLFW_NO_WINDOW_CONTEXT, and NULL.
glfwGetGLXWindow()
GLFWAPI GLXWindow glfwGetGLXWindow (GLFWwindow * handle)
References _GLFW_REQUIRE_INIT_OR_RETURN, _glfwInputError(), _GLFWcontext::client, _GLFWwindow::context, GLFW_NO_API, GLFW_NO_WINDOW_CONTEXT, AuroraFW::None, and NULL.