Aurora Framework: ima_oki_adpcm.c File Reference
ima_oki_adpcm.c File Reference
Macros
#define MAX_SAMPLE 0x7fff
#define MIN_SAMPLE -0x8000
Functions
int adpcm_decode (IMA_OKI_ADPCM *state, int code)
int adpcm_encode (IMA_OKI_ADPCM *state, int sample)
void ima_oki_adpcm_decode_block (IMA_OKI_ADPCM *state)
void ima_oki_adpcm_encode_block (IMA_OKI_ADPCM *state)
void ima_oki_adpcm_init (IMA_OKI_ADPCM *state, IMA_OKI_ADPCM_TYPE type)
Variables
static int const ima_steps []
static int const oki_steps []
static int const step_changes [] = { -1, -1, -1, -1, 2, 4, 6, 8 }
Macro Definition Documentation
MIN_SAMPLE
#define MIN_SAMPLE -0x8000
Referenced by adpcm_decode().
MAX_SAMPLE
#define MAX_SAMPLE 0x7fff
Referenced by adpcm_decode().
Function Documentation
ima_oki_adpcm_init()
void ima_oki_adpcm_init (IMA_OKI_ADPCM * state, IMA_OKI_ADPCM_TYPE type)
References arith_shift_left(), ARRAY_LEN, IMA_OKI_ADPCM_TYPE_IMA, ima_steps, IMA_OKI_ADPCM::mask, IMA_OKI_ADPCM::max_step_index, memset(), oki_steps, and IMA_OKI_ADPCM::steps.
Referenced by vox_adpcm_init().
adpcm_decode()
int adpcm_decode (IMA_OKI_ADPCM * state, int code)
References IMA_OKI_ADPCM::errors, IMA_OKI_ADPCM::last_output, IMA_OKI_ADPCM::mask, MAX_SAMPLE, IMA_OKI_ADPCM::max_step_index, MIN_SAMPLE, SF_MAX, SF_MIN, step_changes, IMA_OKI_ADPCM::step_index, and IMA_OKI_ADPCM::steps.
Referenced by adpcm_encode(), and ima_oki_adpcm_decode_block().
adpcm_encode()
int adpcm_encode (IMA_OKI_ADPCM * state, int sample)
References adpcm_decode(), IMA_OKI_ADPCM::last_output, SF_MIN, IMA_OKI_ADPCM::step_index, and IMA_OKI_ADPCM::steps.
Referenced by ima_oki_adpcm_encode_block().
ima_oki_adpcm_decode_block()
void ima_oki_adpcm_decode_block (IMA_OKI_ADPCM * state)
References adpcm_decode(), IMA_OKI_ADPCM::code_count, IMA_OKI_ADPCM::codes, IMA_OKI_ADPCM::pcm, and IMA_OKI_ADPCM::pcm_count.
Referenced by vox_read_block().
ima_oki_adpcm_encode_block()
void ima_oki_adpcm_encode_block (IMA_OKI_ADPCM * state)
References adpcm_encode(), IMA_OKI_ADPCM::code_count, IMA_OKI_ADPCM::codes, IMA_OKI_ADPCM::pcm, and IMA_OKI_ADPCM::pcm_count.
Referenced by vox_write_block().
Variable Documentation
ima_steps
int const ima_steps[] static
Initial value:
=
{   7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 19, 21, 23, 25, 28, 31, 34, 37, 41, 45,
    50, 55, 60, 66, 73, 80, 88, 97, 107, 118, 130, 143, 157, 173, 190, 209, 230,
    253, 279, 307, 337, 371, 408, 449, 494, 544, 598, 658, 724, 796, 876, 963,
    1060, 1166, 1282, 1411, 1552, 1707, 1878, 2066, 2272, 2499, 2749, 3024, 3327,
    3660, 4026, 4428, 4871, 5358, 5894, 6484, 7132, 7845, 8630, 9493, 10442,
    11487, 12635, 13899, 15289, 16818, 18500, 20350, 22385, 24623, 27086, 29794,
    32767
}
Referenced by ima_oki_adpcm_init().
oki_steps
int const oki_steps[] static
Initial value:
=
{   256, 272, 304, 336, 368, 400, 448, 496, 544, 592, 656, 720, 800, 880, 960,
    1056, 1168, 1280, 1408, 1552, 1712, 1888, 2080, 2288, 2512, 2768, 3040, 3344,
    3680, 4048, 4464, 4912, 5392, 5936, 6528, 7184, 7904, 8704, 9568, 10528,
    11584, 12736, 14016, 15408, 16960, 18656, 20512, 22576, 24832
}
Referenced by ima_oki_adpcm_init().
step_changes
int const step_changes[] = { -1, -1, -1, -1, 2, 4, 6, 8 } static
Referenced by adpcm_decode().