Aurora Framework: spirv_cross::CFG Class Reference
spirv_cross::CFG Class Reference
Public Member Functions
CFG (Compiler &compiler, const SPIRFunction &function)
uint32_t find_common_dominator (uint32_t a, uint32_t b) const
Compiler & get_compiler ()
const Compiler & get_compiler () const
const SPIRFunction & get_function () const
uint32_t get_immediate_dominator (uint32_t block) const
const std::vector< uint32_t > & get_preceding_edges (uint32_t block) const
const std::vector< uint32_t > & get_succeeding_edges (uint32_t block) const
uint32_t get_visit_order (uint32_t block) const
template<typename Op >
void walk_from (std::unordered_set< uint32_t > &seen_blocks, uint32_t block, const Op &op) const
Constructor & Destructor Documentation
CFG()
spirv_cross::CFG::CFG (Compiler & compiler, const SPIRFunction & function)
References spirv_cross::Compiler::get_current_id_bound().
Member Function Documentation
get_compiler() [1/2]
Compiler& spirv_cross::CFG::get_compiler () inline
Referenced by spirv_cross::DominatorBuilder::lift_continue_block_dominator().
get_compiler() [2/2]
const Compiler& spirv_cross::CFG::get_compiler () const inline
get_function()
const SPIRFunction& spirv_cross::CFG::get_function () const inline
Referenced by spirv_cross::DominatorBuilder::lift_continue_block_dominator().
get_immediate_dominator()
uint32_t spirv_cross::CFG::get_immediate_dominator (uint32_t block) const inline
Referenced by spirv_cross::DominatorBuilder::add_block().
get_visit_order()
uint32_t spirv_cross::CFG::get_visit_order (uint32_t block) const inline
Referenced by spirv_cross::DominatorBuilder::lift_continue_block_dominator().
find_common_dominator()
uint32_t spirv_cross::CFG::find_common_dominator (uint32_t a, uint32_t b) const
References a.
Referenced by spirv_cross::DominatorBuilder::add_block().
get_preceding_edges()
const std::vector<uint32_t>& spirv_cross::CFG::get_preceding_edges (uint32_t block) const inline
Referenced by spirv_cross::Compiler::analyze_variable_scope().
get_succeeding_edges()
const std::vector<uint32_t>& spirv_cross::CFG::get_succeeding_edges (uint32_t block) const inline
Referenced by spirv_cross::Compiler::analyze_variable_scope(), and exists_unaccessed_path_to_return().
walk_from()
template<typename Op > void spirv_cross::CFG::walk_from (std::unordered_set< uint32_t > & seen_blocks, uint32_t block, const Op & op) const inline
Referenced by spirv_cross::Compiler::analyze_variable_scope().
The documentation for this class was generated from the following files:
CFG.h
CFG.cpp