Aurora Framework: Input reference
Input reference
Functions and types related to input handling.
Modules
Gamepad axes
Gamepad axes.
Gamepad buttons
Gamepad buttons.
Joystick hat states
Joysticks
Joystick IDs.
Keyboard keys
Keyboard key IDs.
Modifier key flags
Modifier key flags.
Mouse buttons
Mouse button IDs.
Standard cursor shapes
Standard system cursor shapes.
Typedefs
typedef void(* GLFWcharfun) (GLFWwindow *, unsigned int)
The function signature for Unicode character callbacks.
typedef void(* GLFWcharmodsfun) (GLFWwindow *, unsigned int, int)
The function signature for Unicode character with modifiers callbacks.
typedef void(* GLFWcursorenterfun) (GLFWwindow *, int)
The function signature for cursor enter/leave callbacks.
typedef void(* GLFWcursorposfun) (GLFWwindow *, double, double)
The function signature for cursor position callbacks.
typedef void(* GLFWdropfun) (GLFWwindow *, int, const char **)
The function signature for file drop callbacks.
typedef void(* GLFWjoystickfun) (int, int)
The function signature for joystick configuration callbacks.
typedef void(* GLFWkeyfun) (GLFWwindow *, int, int, int, int)
The function signature for keyboard key callbacks.
typedef void(* GLFWmousebuttonfun) (GLFWwindow *, int, int, int)
The function signature for mouse button callbacks.
typedef void(* GLFWscrollfun) (GLFWwindow *, double, double)
The function signature for scroll callbacks.
Functions
GLFWAPI GLFWcursor * glfwCreateCursor (const GLFWimage *image, int xhot, int yhot)
Creates a custom cursor.
GLFWAPI GLFWcursor * glfwCreateStandardCursor (int shape)
Creates a cursor with a standard shape.
GLFWAPI void glfwDestroyCursor (GLFWcursor *cursor)
Destroys a cursor.
GLFWAPI const char * glfwGetClipboardString (GLFWwindow *window)
Returns the contents of the clipboard as a string.
GLFWAPI void glfwGetCursorPos (GLFWwindow *window, double *xpos, double *ypos)
Retrieves the position of the cursor relative to the client area of the window.
GLFWAPI const char * glfwGetGamepadName (int jid)
Returns the human-readable gamepad name for the specified joystick.
GLFWAPI int glfwGetGamepadState (int jid, GLFWgamepadstate *state)
Retrieves the state of the specified joystick remapped as a gamepad.
GLFWAPI int glfwGetInputMode (GLFWwindow *window, int mode)
Returns the value of an input option for the specified window.
GLFWAPI const float * glfwGetJoystickAxes (int jid, int *count)
Returns the values of all axes of the specified joystick.
GLFWAPI const unsigned char * glfwGetJoystickButtons (int jid, int *count)
Returns the state of all buttons of the specified joystick.
GLFWAPI const char * glfwGetJoystickGUID (int jid)
Returns the SDL comaptible GUID of the specified joystick.
GLFWAPI const unsigned char * glfwGetJoystickHats (int jid, int *count)
Returns the state of all hats of the specified joystick.
GLFWAPI const char * glfwGetJoystickName (int jid)
Returns the name of the specified joystick.
GLFWAPI void * glfwGetJoystickUserPointer (int jid)
Returns the user pointer of the specified joystick.
GLFWAPI int glfwGetKey (GLFWwindow *window, int key)
Returns the last reported state of a keyboard key for the specified window.
GLFWAPI const char * glfwGetKeyName (int key, int scancode)
Returns the layout-specific name of the specified printable key.
GLFWAPI int glfwGetKeyScancode (int key)
Returns the platform-specific scancode of the specified key.
GLFWAPI int glfwGetMouseButton (GLFWwindow *window, int button)
Returns the last reported state of a mouse button for the specified window.
GLFWAPI double glfwGetTime (void)
Returns the value of the GLFW timer.
GLFWAPI uint64_t glfwGetTimerFrequency (void)
Returns the frequency, in Hz, of the raw timer.
GLFWAPI uint64_t glfwGetTimerValue (void)
Returns the current value of the raw timer.
GLFWAPI int glfwJoystickIsGamepad (int jid)
Returns whether the specified joystick has a gamepad mapping.
GLFWAPI int glfwJoystickPresent (int jid)
Returns whether the specified joystick is present.
GLFWAPI GLFWcharfun glfwSetCharCallback (GLFWwindow *window, GLFWcharfun cbfun)
Sets the Unicode character callback.
GLFWAPI GLFWcharmodsfun glfwSetCharModsCallback (GLFWwindow *window, GLFWcharmodsfun cbfun)
Sets the Unicode character with modifiers callback.
GLFWAPI void glfwSetClipboardString (GLFWwindow *window, const char *string)
Sets the clipboard to the specified string.
GLFWAPI void glfwSetCursor (GLFWwindow *window, GLFWcursor *cursor)
Sets the cursor for the window.
GLFWAPI GLFWcursorenterfun glfwSetCursorEnterCallback (GLFWwindow *window, GLFWcursorenterfun cbfun)
Sets the cursor enter/exit callback.
GLFWAPI void glfwSetCursorPos (GLFWwindow *window, double xpos, double ypos)
Sets the position of the cursor, relative to the client area of the window.
GLFWAPI GLFWcursorposfun glfwSetCursorPosCallback (GLFWwindow *window, GLFWcursorposfun cbfun)
Sets the cursor position callback.
GLFWAPI GLFWdropfun glfwSetDropCallback (GLFWwindow *window, GLFWdropfun cbfun)
Sets the file drop callback.
GLFWAPI void glfwSetInputMode (GLFWwindow *window, int mode, int value)
Sets an input option for the specified window.
GLFWAPI GLFWjoystickfun glfwSetJoystickCallback (GLFWjoystickfun cbfun)
Sets the joystick configuration callback.
GLFWAPI void glfwSetJoystickUserPointer (int jid, void *pointer)
Sets the user pointer of the specified joystick.
GLFWAPI GLFWkeyfun glfwSetKeyCallback (GLFWwindow *window, GLFWkeyfun cbfun)
Sets the key callback.
GLFWAPI GLFWmousebuttonfun glfwSetMouseButtonCallback (GLFWwindow *window, GLFWmousebuttonfun cbfun)
Sets the mouse button callback.
GLFWAPI GLFWscrollfun glfwSetScrollCallback (GLFWwindow *window, GLFWscrollfun cbfun)
Sets the scroll callback.
GLFWAPI void glfwSetTime (double time)
Sets the GLFW timer.
GLFWAPI int glfwUpdateGamepadMappings (const char *string)
Adds the specified SDL_GameControllerDB gamepad mappings.
Key and button actions
#define GLFW_RELEASE 0
The key or mouse button was released.
#define GLFW_PRESS 1
The key or mouse button was pressed.
#define GLFW_REPEAT 2
The key was held down until it repeated.
Detailed Description
Functions and types related to input handling.
This is the reference documentation for input related functions and types. For more task-oriented information, see the input_guide.
Macro Definition Documentation
GLFW_RELEASE
#define GLFW_RELEASE 0
The key or mouse button was released.
The key or mouse button was released.
Referenced by _glfwInputJoystickHat(), _glfwInputKey(), _glfwInputMouseClick(), _glfwInputWindowFocus(), _glfwPlatformPollEvents(), glfwGetKey(), glfwGetKeyScancode(), glfwGetMouseButton(), glfwSetInputMode(), handleKeyEvent(), handlePointerEvent(), keyboardHandleKey(), pointerHandleButton(), processEvent(), and windowProc().
GLFW_PRESS
#define GLFW_PRESS 1
The key or mouse button was pressed.
The key or mouse button was pressed.
Referenced by _glfwInputJoystickHat(), _glfwInputKey(), _glfwInputWindowFocus(), _glfwPlatformPollEvents(), glfwGetGamepadState(), glfwGetKey(), glfwGetMouseButton(), handleKeyEvent(), handlePointerEvent(), key_callback(), keyboardHandleKey(), pointerHandleButton(), processEvent(), and windowProc().
GLFW_REPEAT
#define GLFW_REPEAT 2
The key was held down until it repeated.
The key was held down until it repeated.
Referenced by _glfwInputKey(), and handleEvents().
Typedef Documentation
GLFWmousebuttonfun
typedef void(* GLFWmousebuttonfun) (GLFWwindow *, int, int, int)
The function signature for mouse button callbacks.
This is the function signature for mouse button callback functions.
Parameters
[in] window The window that received the event.
[in] button The mouse button that was pressed or released.
[in] action One of GLFW_PRESS or GLFW_RELEASE.
[in] mods Bit field describing which modifier keys were held down.
See also
input_mouse_button
glfwSetMouseButtonCallback
Since
Added in version 1.0. Added window handle and modifier mask parameters.
GLFWcursorposfun
typedef void(* GLFWcursorposfun) (GLFWwindow *, double, double)
The function signature for cursor position callbacks.
This is the function signature for cursor position callback functions.
Parameters
[in] window The window that received the event.
[in] xpos The new cursor x-coordinate, relative to the left edge of the client area.
[in] ypos The new cursor y-coordinate, relative to the top edge of the client area.
See also
cursor_pos
glfwSetCursorPosCallback
Since
Added in version 3.0. Replaces GLFWmouseposfun.
GLFWcursorenterfun
typedef void(* GLFWcursorenterfun) (GLFWwindow *, int)
The function signature for cursor enter/leave callbacks.
This is the function signature for cursor enter/leave callback functions.
Parameters
[in] window The window that received the event.
[in] entered GLFW_TRUE if the cursor entered the window's client area, or GLFW_FALSE if it left it.
See also
cursor_enter
glfwSetCursorEnterCallback
Since
Added in version 3.0.
GLFWscrollfun
typedef void(* GLFWscrollfun) (GLFWwindow *, double, double)
The function signature for scroll callbacks.
This is the function signature for scroll callback functions.
Parameters
[in] window The window that received the event.
[in] xoffset The scroll offset along the x-axis.
[in] yoffset The scroll offset along the y-axis.
See also
scrolling
glfwSetScrollCallback
Since
Added in version 3.0. Replaces GLFWmousewheelfun.
GLFWkeyfun
typedef void(* GLFWkeyfun) (GLFWwindow *, int, int, int, int)
The function signature for keyboard key callbacks.
This is the function signature for keyboard key callback functions.
Parameters
[in] window The window that received the event.
[in] key The keyboard key that was pressed or released.
[in] scancode The system-specific scancode of the key.
[in] action GLFW_PRESS, GLFW_RELEASE or GLFW_REPEAT.
[in] mods Bit field describing which modifier keys were held down.
See also
input_key
glfwSetKeyCallback
Since
Added in version 1.0. Added window handle, scancode and modifier mask parameters.
GLFWcharfun
typedef void(* GLFWcharfun) (GLFWwindow *, unsigned int)
The function signature for Unicode character callbacks.
This is the function signature for Unicode character callback functions.
Parameters
[in] window The window that received the event.
[in] codepoint The Unicode code point of the character.
See also
input_char
glfwSetCharCallback
Since
Added in version 2.4. Added window handle parameter.
GLFWcharmodsfun
typedef void(* GLFWcharmodsfun) (GLFWwindow *, unsigned int, int)
The function signature for Unicode character with modifiers callbacks.
This is the function signature for Unicode character with modifiers callback functions. It is called for each input character, regardless of what modifier keys are held down.
Parameters
[in] window The window that received the event.
[in] codepoint The Unicode code point of the character.
[in] mods Bit field describing which modifier keys were held down.
See also
input_char
glfwSetCharModsCallback
Deprecated:
Scheduled for removal in version 4.0.
Since
Added in version 3.1.
GLFWdropfun
typedef void(* GLFWdropfun) (GLFWwindow *, int, const char **)
The function signature for file drop callbacks.
This is the function signature for file drop callbacks.
Parameters
[in] window The window that received the event.
[in] count The number of dropped files.
[in] paths The UTF-8 encoded file and/or directory path names.
See also
path_drop
glfwSetDropCallback
Since
Added in version 3.1.
GLFWjoystickfun
typedef void(* GLFWjoystickfun) (int, int)
The function signature for joystick configuration callbacks.
This is the function signature for joystick configuration callback functions.
Parameters
[in] jid The joystick that was connected or disconnected.
[in] event One of GLFW_CONNECTED or GLFW_DISCONNECTED. Remaining values reserved for future use.
See also
joystick_event
glfwSetJoystickCallback
Since
Added in version 3.2.
Function Documentation
glfwGetInputMode()
GLFWAPI int glfwGetInputMode (GLFWwindow * window, int mode)
Returns the value of an input option for the specified window.
This function returns the value of an input option for the specified window. The mode must be one of GLFW_CURSOR, GLFW_STICKY_KEYS, GLFW_STICKY_MOUSE_BUTTONS or GLFW_LOCK_KEY_MODS.
Parameters
[in] window The window to query.
[in] mode One of GLFW_CURSOR, GLFW_STICKY_KEYS, GLFW_STICKY_MOUSE_BUTTONS or GLFW_LOCK_KEY_MODS.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_INVALID_ENUM.
This function must only be called from the main thread.
See also
glfwSetInputMode
Since
Added in version 3.0.
References _GLFW_REQUIRE_INIT_OR_RETURN, _glfwInputError(), _GLFWwindow::cursorMode, GLFW_CURSOR, GLFW_INVALID_ENUM, GLFW_LOCK_KEY_MODS, GLFW_STICKY_KEYS, GLFW_STICKY_MOUSE_BUTTONS, _GLFWwindow::lockKeyMods, mode(), NULL, _GLFWwindow::stickyKeys, and _GLFWwindow::stickyMouseButtons.
glfwSetInputMode()
GLFWAPI void glfwSetInputMode (GLFWwindow * window, int mode, int value)
Sets an input option for the specified window.
This function sets an input mode option for the specified window. The mode must be one of GLFW_CURSOR, GLFW_STICKY_KEYS, GLFW_STICKY_MOUSE_BUTTONS or GLFW_LOCK_KEY_MODS.
If the mode is GLFW_CURSOR, the value must be one of the following cursor modes:
GLFW_CURSOR_NORMAL makes the cursor visible and behaving normally.
GLFW_CURSOR_HIDDEN makes the cursor invisible when it is over the client area of the window but does not restrict the cursor from leaving.
GLFW_CURSOR_DISABLED hides and grabs the cursor, providing virtual and unlimited cursor movement. This is useful for implementing for example 3D camera controls.
If the mode is GLFW_STICKY_KEYS, the value must be either GLFW_TRUE to enable sticky keys, or GLFW_FALSE to disable it. If sticky keys are enabled, a key press will ensure that glfwGetKey returns GLFW_PRESS the next time it is called even if the key had been released before the call. This is useful when you are only interested in whether keys have been pressed but not when or in which order.
If the mode is GLFW_STICKY_MOUSE_BUTTONS, the value must be either GLFW_TRUE to enable sticky mouse buttons, or GLFW_FALSE to disable it. If sticky mouse buttons are enabled, a mouse button press will ensure that glfwGetMouseButton returns GLFW_PRESS the next time it is called even if the mouse button had been released before the call. This is useful when you are only interested in whether mouse buttons have been pressed but not when or in which order.
If the mode is GLFW_LOCK_KEY_MODS, the value must be either GLFW_TRUE to enable lock key modifier bits, or GLFW_FALSE to disable them. If enabled, callbacks that receive modifier bits will also have the GLFW_MOD_CAPS_LOCK bit set when the event was generated with Caps Lock on, and the GLFW_MOD_NUM_LOCK bit when Num Lock was on.
Parameters
[in] window The window whose input mode to set.
[in] mode One of GLFW_CURSOR, GLFW_STICKY_KEYS, GLFW_STICKY_MOUSE_BUTTONS or GLFW_LOCK_KEY_MODS.
[in] value The new value of the specified input mode.
Possible errors include GLFW_NOT_INITIALIZED, GLFW_INVALID_ENUM and GLFW_PLATFORM_ERROR.
This function must only be called from the main thread.
See also
glfwGetInputMode
Since
Added in version 3.0. Replaces glfwEnable and glfwDisable.
References _GLFW_REQUIRE_INIT, _GLFW_STICK, _glfwInputError(), _glfwPlatformGetCursorPos(), _glfwPlatformSetCursorMode(), _glfwPlatformWindowFocused(), _GLFWwindow::cursorMode, GLFW_CURSOR, GLFW_CURSOR_DISABLED, GLFW_CURSOR_HIDDEN, GLFW_CURSOR_NORMAL, GLFW_FALSE, GLFW_INVALID_ENUM, GLFW_KEY_LAST, GLFW_LOCK_KEY_MODS, GLFW_MOUSE_BUTTON_LAST, GLFW_RELEASE, GLFW_STICKY_KEYS, GLFW_STICKY_MOUSE_BUTTONS, GLFW_TRUE, _GLFWwindow::keys, _GLFWwindow::lockKeyMods, mode(), _GLFWwindow::mouseButtons, NULL, _GLFWwindow::stickyKeys, _GLFWwindow::stickyMouseButtons, value, _GLFWwindow::virtualCursorPosX, and _GLFWwindow::virtualCursorPosY.
Referenced by AuroraFW::GEngine::ImGuiLoader::newFrame().
glfwGetKeyName()
GLFWAPI const char* glfwGetKeyName (int key, int scancode)
Returns the layout-specific name of the specified printable key.
This function returns the name of the specified printable key, encoded as UTF-8. This is typically the character that key would produce without any modifier keys, intended for displaying key bindings to the user. For dead keys, it is typically the diacritic it would add to a character.
Do not use this function for text input. You will break text input for many languages even if it happens to work for yours.
If the key is GLFW_KEY_UNKNOWN, the scancode is used to identify the key, otherwise the scancode is ignored. If you specify a non-printable key, or GLFW_KEY_UNKNOWN and a scancode that maps to a non-printable key, this function returns NULL but does not emit an error.
This behavior allows you to always pass in the arguments in the key callback without modification.
The printable keys are:
GLFW_KEY_APOSTROPHE
GLFW_KEY_COMMA
GLFW_KEY_MINUS
GLFW_KEY_PERIOD
GLFW_KEY_SLASH
GLFW_KEY_SEMICOLON
GLFW_KEY_EQUAL
GLFW_KEY_LEFT_BRACKET
GLFW_KEY_RIGHT_BRACKET
GLFW_KEY_BACKSLASH
GLFW_KEY_WORLD_1
GLFW_KEY_WORLD_2
GLFW_KEY_0 to GLFW_KEY_9
GLFW_KEY_A to GLFW_KEY_Z
GLFW_KEY_KP_0 to GLFW_KEY_KP_9
GLFW_KEY_KP_DECIMAL
GLFW_KEY_KP_DIVIDE
GLFW_KEY_KP_MULTIPLY
GLFW_KEY_KP_SUBTRACT
GLFW_KEY_KP_ADD
GLFW_KEY_KP_EQUAL
Names for printable keys depend on keyboard layout, while names for non-printable keys are the same across layouts but depend on the application language and should be localized along with other user interface text.
Parameters
[in] key The key to query, or GLFW_KEY_UNKNOWN.
[in] scancode The scancode of the key to query.
Returns
The UTF-8 encoded, layout-specific name of the key, or NULL.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
The returned string is allocated and freed by GLFW. You should not free it yourself. It is valid until the next call to glfwGetKeyName, or until the library is terminated.
This function must only be called from the main thread.
See also
input_key_name
Since
Added in version 3.2.
References _GLFW_REQUIRE_INIT_OR_RETURN, _glfwPlatformGetKeyScancode(), _glfwPlatformGetScancodeName(), GLFW_KEY_KP_ADD, GLFW_KEY_KP_EQUAL, GLFW_KEY_UNKNOWN, GLFW_KEY_WORLD_2, and NULL.
glfwGetKeyScancode()
GLFWAPI int glfwGetKeyScancode (int key)
Returns the platform-specific scancode of the specified key.
This function returns the platform-specific scancode of the specified key.
If the key is GLFW_KEY_UNKNOWN or does not exist on the keyboard this method will return -1.
Parameters
[in] key Any named key.
Returns
The platform-specific scancode for the key, or -1 if an error occurred.
Possible errors include GLFW_NOT_INITIALIZED, GLFW_INVALID_ENUM and GLFW_PLATFORM_ERROR.
This function may be called from any thread.
See also
input_key
Since
Added in version 3.3.
References _GLFW_REQUIRE_INIT_OR_RETURN, _glfwInputError(), _glfwPlatformGetKeyScancode(), GLFW_INVALID_ENUM, GLFW_KEY_LAST, and GLFW_RELEASE.
glfwGetKey()
GLFWAPI int glfwGetKey (GLFWwindow * window, int key)
Returns the last reported state of a keyboard key for the specified window.
This function returns the last state reported for the specified key to the specified window. The returned state is one of GLFW_PRESS or GLFW_RELEASE. The higher-level action GLFW_REPEAT is only reported to the key callback.
If the GLFW_STICKY_KEYS input mode is enabled, this function returns GLFW_PRESS the first time you call it for a key that was pressed, even if that key has already been released.
The key functions deal with physical keys, with key tokens named after their use on the standard US keyboard layout. If you want to input text, use the Unicode character callback instead.
The modifier key bit masks are not key tokens and cannot be used with this function.
Do not use this function to implement text input.
Parameters
[in] window The desired window.
[in] key The desired keyboard key. GLFW_KEY_UNKNOWN is not a valid key for this function.
Returns
One of GLFW_PRESS or GLFW_RELEASE.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_INVALID_ENUM.
This function must only be called from the main thread.
See also
input_key
Since
Added in version 1.0. Added window handle parameter.
References _GLFW_REQUIRE_INIT_OR_RETURN, _GLFW_STICK, _glfwInputError(), GLFW_INVALID_ENUM, GLFW_KEY_LAST, GLFW_PRESS, GLFW_RELEASE, _GLFWwindow::keys, and NULL.
glfwGetMouseButton()
GLFWAPI int glfwGetMouseButton (GLFWwindow * window, int button)
Returns the last reported state of a mouse button for the specified window.
This function returns the last state reported for the specified mouse button to the specified window. The returned state is one of GLFW_PRESS or GLFW_RELEASE.
If the GLFW_STICKY_MOUSE_BUTTONS input mode is enabled, this function GLFW_PRESS the first time you call it for a mouse button that was pressed, even if that mouse button has already been released.
Parameters
[in] window The desired window.
[in] button The desired mouse button.
Returns
One of GLFW_PRESS or GLFW_RELEASE.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_INVALID_ENUM.
This function must only be called from the main thread.
See also
input_mouse_button
Since
Added in version 1.0. Added window handle parameter.
References _GLFW_REQUIRE_INIT_OR_RETURN, _GLFW_STICK, _glfwInputError(), GLFW_INVALID_ENUM, GLFW_MOUSE_BUTTON_LAST, GLFW_PRESS, GLFW_RELEASE, _GLFWwindow::mouseButtons, and NULL.
Referenced by AuroraFW::GEngine::ImGuiLoader::newFrame().
glfwGetCursorPos()
GLFWAPI void glfwGetCursorPos (GLFWwindow * window, double * xpos, double * ypos)
Retrieves the position of the cursor relative to the client area of the window.
This function returns the position of the cursor, in screen coordinates, relative to the upper-left corner of the client area of the specified window.
If the cursor is disabled (with GLFW_CURSOR_DISABLED) then the cursor position is unbounded and limited only by the minimum and maximum values of a double.
The coordinate can be converted to their integer equivalents with the floor function. Casting directly to an integer type works for positive coordinates, but fails for negative ones.
Any or all of the position arguments may be NULL. If an error occurs, all non-NULL position arguments will be set to zero.
Parameters
[in] window The desired window.
[out] xpos Where to store the cursor x-coordinate, relative to the left edge of the client area, or NULL.
[out] ypos Where to store the cursor y-coordinate, relative to the to top edge of the client area, or NULL.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
This function must only be called from the main thread.
See also
cursor_pos
glfwSetCursorPos
Since
Added in version 3.0. Replaces glfwGetMousePos.
References _GLFW_REQUIRE_INIT, _glfwPlatformGetCursorPos(), _GLFWwindow::cursorMode, GLFW_CURSOR_DISABLED, NULL, _GLFWwindow::virtualCursorPosX, and _GLFWwindow::virtualCursorPosY.
Referenced by AuroraFW::GEngine::ImGuiLoader::newFrame().
glfwSetCursorPos()
GLFWAPI void glfwSetCursorPos (GLFWwindow * window, double xpos, double ypos)
Sets the position of the cursor, relative to the client area of the window.
This function sets the position, in screen coordinates, of the cursor relative to the upper-left corner of the client area of the specified window. The window must have input focus. If the window does not have input focus when this function is called, it fails silently.
Do not use this function to implement things like camera controls. GLFW already provides the GLFW_CURSOR_DISABLED cursor mode that hides the cursor, transparently re-centers it and provides unconstrained cursor motion. See glfwSetInputMode for more information.
If the cursor mode is GLFW_CURSOR_DISABLED then the cursor position is unconstrained and limited only by the minimum and maximum values of a double.
Parameters
[in] window The desired window.
[in] xpos The desired x-coordinate, relative to the left edge of the client area.
[in] ypos The desired y-coordinate, relative to the top edge of the client area.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
Remarks
This function will only work when the cursor mode is GLFW_CURSOR_DISABLED, otherwise it will do nothing.
This function must only be called from the main thread.
See also
cursor_pos
glfwGetCursorPos
Since
Added in version 3.0. Replaces glfwSetMousePos.
References _GLFW_REQUIRE_INIT, _glfwInputError(), _glfwPlatformSetCursorPos(), _glfwPlatformWindowFocused(), _GLFWwindow::cursorMode, DBL_MAX, GLFW_CURSOR_DISABLED, GLFW_INVALID_VALUE, NULL, _GLFWwindow::virtualCursorPosX, and _GLFWwindow::virtualCursorPosY.
Referenced by AuroraFW::GEngine::ImGuiLoader::newFrame().
glfwCreateCursor()
GLFWAPI GLFWcursor* glfwCreateCursor (const GLFWimage * image, int xhot, int yhot)
Creates a custom cursor.
Creates a new custom cursor image that can be set for a window with glfwSetCursor. The cursor can be destroyed with glfwDestroyCursor. Any remaining cursors are destroyed by glfwTerminate.
The pixels are 32-bit, little-endian, non-premultiplied RGBA, i.e. eight bits per channel with the red channel first. They are arranged canonically as packed sequential rows, starting from the top-left corner.
The cursor hotspot is specified in pixels, relative to the upper-left corner of the cursor image. Like all other coordinate systems in GLFW, the X-axis points to the right and the Y-axis points down.
Parameters
[in] image The desired cursor image.
[in] xhot The desired x-coordinate, in pixels, of the cursor hotspot.
[in] yhot The desired y-coordinate, in pixels, of the cursor hotspot.
Returns
The handle of the created cursor, or NULL if an error occurred.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
The specified image data is copied before this function returns.
This function must only be called from the main thread.
See also
cursor_object
glfwDestroyCursor
glfwCreateStandardCursor
Since
Added in version 3.1.
References _glfw, _GLFW_REQUIRE_INIT_OR_RETURN, _glfwPlatformCreateCursor(), _GLFWlibrary::cursorListHead, glfwDestroyCursor(), _GLFWcursor::next, and NULL.
glfwCreateStandardCursor()
GLFWAPI GLFWcursor* glfwCreateStandardCursor (int shape)
Creates a cursor with a standard shape.
Returns a cursor with a standard shape, that can be set for a window with glfwSetCursor.
Parameters
[in] shape One of the standard shapes.
Returns
A new cursor ready to use or NULL if an error occurred.
Possible errors include GLFW_NOT_INITIALIZED, GLFW_INVALID_ENUM and GLFW_PLATFORM_ERROR.
This function must only be called from the main thread.
See also
cursor_object
glfwCreateCursor
Since
Added in version 3.1.
References _glfw, _GLFW_REQUIRE_INIT_OR_RETURN, _glfwInputError(), _glfwPlatformCreateStandardCursor(), _GLFWlibrary::cursorListHead, GLFW_ARROW_CURSOR, GLFW_CROSSHAIR_CURSOR, GLFW_HAND_CURSOR, GLFW_HRESIZE_CURSOR, GLFW_IBEAM_CURSOR, GLFW_INVALID_ENUM, GLFW_VRESIZE_CURSOR, glfwDestroyCursor(), _GLFWcursor::next, and NULL.
Referenced by AuroraFW::GEngine::ImGuiLoader::Load().
glfwDestroyCursor()
GLFWAPI void glfwDestroyCursor (GLFWcursor * cursor)
Destroys a cursor.
This function destroys a cursor previously created with glfwCreateCursor. Any remaining cursors will be destroyed by glfwTerminate.
If the specified cursor is current for any window, that window will be reverted to the default cursor. This does not affect the cursor mode.
Parameters
[in] cursor The cursor object to destroy.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
This function must not be called from a callback.
This function must only be called from the main thread.
See also
cursor_object
glfwCreateCursor
Since
Added in version 3.1.
References _glfw, _GLFW_REQUIRE_INIT, _glfwPlatformDestroyCursor(), _GLFWwindow::cursor, _GLFWlibrary::cursorListHead, glfwSetCursor(), _GLFWwindow::next, _GLFWcursor::next, NULL, and _GLFWlibrary::windowListHead.
Referenced by glfwCreateCursor(), glfwCreateStandardCursor(), terminate(), and AuroraFW::GEngine::ImGuiLoader::Unload().
glfwSetCursor()
GLFWAPI void glfwSetCursor (GLFWwindow * window, GLFWcursor * cursor)
Sets the cursor for the window.
This function sets the cursor image to be used when the cursor is over the client area of the specified window. The set cursor will only be visible when the cursor mode of the window is GLFW_CURSOR_NORMAL.
On some platforms, the set cursor may not be visible unless the window also has input focus.
Parameters
[in] window The window to set the cursor for.
[in] cursor The cursor to set, or NULL to switch back to the default arrow cursor.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
This function must only be called from the main thread.
See also
cursor_object
Since
Added in version 3.1.
References _GLFW_REQUIRE_INIT, _glfwPlatformSetCursor(), _GLFWwindow::cursor, and NULL.
Referenced by glfwDestroyCursor(), and AuroraFW::GEngine::ImGuiLoader::newFrame().
glfwSetKeyCallback()
GLFWAPI GLFWkeyfun glfwSetKeyCallback (GLFWwindow * window, GLFWkeyfun cbfun)
Sets the key callback.
This function sets the key callback of the specified window, which is called when a key is pressed, repeated or released.
The key functions deal with physical keys, with layout independent key tokens named after their values in the standard US keyboard layout. If you want to input text, use the character callback instead.
When a window loses input focus, it will generate synthetic key release events for all pressed keys. You can tell these events from user-generated events by the fact that the synthetic ones are generated after the focus loss event has been processed, i.e. after the window focus callback has been called.
The scancode of a key is specific to that platform or sometimes even to that machine. Scancodes are intended to allow users to bind keys that don't have a GLFW key token. Such keys have key set to GLFW_KEY_UNKNOWN, their state is not saved and so it cannot be queried with glfwGetKey.
Sometimes GLFW needs to generate synthetic key events, in which case the scancode may be zero.
Parameters
[in] window The window whose callback to set.
[in] cbfun The new key callback, or NULL to remove the currently set callback.
Returns
The previously set callback, or NULL if no callback was set or the library had not been initialized.
Possible errors include GLFW_NOT_INITIALIZED.
This function must only be called from the main thread.
See also
input_key
Since
Added in version 1.0. Added window handle parameter and return value.
References _GLFW_REQUIRE_INIT_OR_RETURN, _GLFW_SWAP_POINTERS, _GLFWwindow::callbacks, _GLFWwindow::key, and NULL.
Referenced by AuroraFW::GEngine::InputManager::InputManager(), and main().
glfwSetCharCallback()
GLFWAPI GLFWcharfun glfwSetCharCallback (GLFWwindow * window, GLFWcharfun cbfun)
Sets the Unicode character callback.
This function sets the character callback of the specified window, which is called when a Unicode character is input.
The character callback is intended for Unicode text input. As it deals with characters, it is keyboard layout dependent, whereas the key callback is not. Characters do not map 1:1 to physical keys, as a key may produce zero, one or more characters. If you want to know whether a specific physical key was pressed or released, see the key callback instead.
The character callback behaves as system text input normally does and will not be called if modifier keys are held down that would prevent normal text input on that platform, for example a Super (Command) key on macOS or Alt key on Windows. There is a character with modifiers callback that receives these events.
Parameters
[in] window The window whose callback to set.
[in] cbfun The new callback, or NULL to remove the currently set callback.
Returns
The previously set callback, or NULL if no callback was set or the library had not been initialized.
Possible errors include GLFW_NOT_INITIALIZED.
This function must only be called from the main thread.
See also
input_char
Since
Added in version 2.4. Added window handle parameter and return value.
References _GLFW_REQUIRE_INIT_OR_RETURN, _GLFW_SWAP_POINTERS, _GLFWwindow::callbacks, _GLFWwindow::character, and NULL.
Referenced by AuroraFW::GEngine::InputManager::InputManager().
glfwSetCharModsCallback()
GLFWAPI GLFWcharmodsfun glfwSetCharModsCallback (GLFWwindow * window, GLFWcharmodsfun cbfun)
Sets the Unicode character with modifiers callback.
This function sets the character with modifiers callback of the specified window, which is called when a Unicode character is input regardless of what modifier keys are used.
The character with modifiers callback is intended for implementing custom Unicode character input. For regular Unicode text input, see the character callback. Like the character callback, the character with modifiers callback deals with characters and is keyboard layout dependent. Characters do not map 1:1 to physical keys, as a key may produce zero, one or more characters. If you want to know whether a specific physical key was pressed or released, see the key callback instead.
Parameters
[in] window The window whose callback to set.
[in] cbfun The new callback, or NULL to remove the currently set callback.
Returns
The previously set callback, or NULL if no callback was set or an error occurred.
Deprecated:
Scheduled for removal in version 4.0.
Possible errors include GLFW_NOT_INITIALIZED.
This function must only be called from the main thread.
See also
input_char
Since
Added in version 3.1.
References _GLFW_REQUIRE_INIT_OR_RETURN, _GLFW_SWAP_POINTERS, _GLFWwindow::callbacks, _GLFWwindow::charmods, and NULL.
glfwSetMouseButtonCallback()
GLFWAPI GLFWmousebuttonfun glfwSetMouseButtonCallback (GLFWwindow * window, GLFWmousebuttonfun cbfun)
Sets the mouse button callback.
This function sets the mouse button callback of the specified window, which is called when a mouse button is pressed or released.
When a window loses input focus, it will generate synthetic mouse button release events for all pressed mouse buttons. You can tell these events from user-generated events by the fact that the synthetic ones are generated after the focus loss event has been processed, i.e. after the window focus callback has been called.
Parameters
[in] window The window whose callback to set.
[in] cbfun The new callback, or NULL to remove the currently set callback.
Returns
The previously set callback, or NULL if no callback was set or the library had not been initialized.
Possible errors include GLFW_NOT_INITIALIZED.
This function must only be called from the main thread.
See also
input_mouse_button
Since
Added in version 1.0. Added window handle parameter and return value.
References _GLFW_REQUIRE_INIT_OR_RETURN, _GLFW_SWAP_POINTERS, _GLFWwindow::callbacks, _GLFWwindow::mouseButton, and NULL.
Referenced by AuroraFW::GEngine::InputManager::InputManager().
glfwSetCursorPosCallback()
GLFWAPI GLFWcursorposfun glfwSetCursorPosCallback (GLFWwindow * window, GLFWcursorposfun cbfun)
Sets the cursor position callback.
This function sets the cursor position callback of the specified window, which is called when the cursor is moved. The callback is provided with the position, in screen coordinates, relative to the upper-left corner of the client area of the window.
Parameters
[in] window The window whose callback to set.
[in] cbfun The new callback, or NULL to remove the currently set callback.
Returns
The previously set callback, or NULL if no callback was set or the library had not been initialized.
Possible errors include GLFW_NOT_INITIALIZED.
This function must only be called from the main thread.
See also
cursor_pos
Since
Added in version 3.0. Replaces glfwSetMousePosCallback.
References _GLFW_REQUIRE_INIT_OR_RETURN, _GLFW_SWAP_POINTERS, _GLFWwindow::callbacks, _GLFWwindow::cursorPos, and NULL.
Referenced by AuroraFW::GEngine::InputManager::InputManager().
glfwSetCursorEnterCallback()
GLFWAPI GLFWcursorenterfun glfwSetCursorEnterCallback (GLFWwindow * window, GLFWcursorenterfun cbfun)
Sets the cursor enter/exit callback.
This function sets the cursor boundary crossing callback of the specified window, which is called when the cursor enters or leaves the client area of the window.
Parameters
[in] window The window whose callback to set.
[in] cbfun The new callback, or NULL to remove the currently set callback.
Returns
The previously set callback, or NULL if no callback was set or the library had not been initialized.
Possible errors include GLFW_NOT_INITIALIZED.
This function must only be called from the main thread.
See also
cursor_enter
Since
Added in version 3.0.
References _GLFW_REQUIRE_INIT_OR_RETURN, _GLFW_SWAP_POINTERS, _GLFWwindow::callbacks, _GLFWwindow::cursorEnter, and NULL.
glfwSetScrollCallback()
GLFWAPI GLFWscrollfun glfwSetScrollCallback (GLFWwindow * window, GLFWscrollfun cbfun)
Sets the scroll callback.
This function sets the scroll callback of the specified window, which is called when a scrolling device is used, such as a mouse wheel or scrolling area of a touchpad.
The scroll callback receives all scrolling input, like that from a mouse wheel or a touchpad scrolling area.
Parameters
[in] window The window whose callback to set.
[in] cbfun The new scroll callback, or NULL to remove the currently set callback.
Returns
The previously set callback, or NULL if no callback was set or the library had not been initialized.
Possible errors include GLFW_NOT_INITIALIZED.
This function must only be called from the main thread.
See also
scrolling
Since
Added in version 3.0. Replaces glfwSetMouseWheelCallback.
References _GLFW_REQUIRE_INIT_OR_RETURN, _GLFW_SWAP_POINTERS, _GLFWwindow::callbacks, NULL, and _GLFWwindow::scroll.
Referenced by AuroraFW::GEngine::InputManager::InputManager().
glfwSetDropCallback()
GLFWAPI GLFWdropfun glfwSetDropCallback (GLFWwindow * window, GLFWdropfun cbfun)
Sets the file drop callback.
This function sets the file drop callback of the specified window, which is called when one or more dragged files are dropped on the window.
Because the path array and its strings may have been generated specifically for that event, they are not guaranteed to be valid after the callback has returned. If you wish to use them after the callback returns, you need to make a deep copy.
Parameters
[in] window The window whose callback to set.
[in] cbfun The new file drop callback, or NULL to remove the currently set callback.
Returns
The previously set callback, or NULL if no callback was set or the library had not been initialized.
Possible errors include GLFW_NOT_INITIALIZED.
Remarks
File drop is currently unimplemented.
This function must only be called from the main thread.
See also
path_drop
Since
Added in version 3.1.
References _GLFW_REQUIRE_INIT_OR_RETURN, _GLFW_SWAP_POINTERS, _GLFWwindow::callbacks, _GLFWwindow::drop, and NULL.
glfwJoystickPresent()
GLFWAPI int glfwJoystickPresent (int jid)
Returns whether the specified joystick is present.
This function returns whether the specified joystick is present.
There is no need to call this function before other functions that accept a joystick ID, as they all check for presence before performing any other work.
Parameters
[in] jid The joystick to query.
Returns
GLFW_TRUE if the joystick is present, or GLFW_FALSE otherwise.
Possible errors include GLFW_NOT_INITIALIZED, GLFW_INVALID_ENUM and GLFW_PLATFORM_ERROR.
This function must only be called from the main thread.
See also
joystick
Since
Added in version 3.0. Replaces glfwGetJoystickParam.
References _glfw, _GLFW_POLL_PRESENCE, _GLFW_REQUIRE_INIT_OR_RETURN, _glfwInputError(), _glfwPlatformPollJoystick(), GLFW_FALSE, GLFW_INVALID_ENUM, GLFW_JOYSTICK_1, GLFW_JOYSTICK_LAST, _GLFWlibrary::joysticks, and _GLFWjoystick::present.
glfwGetJoystickAxes()
GLFWAPI const float* glfwGetJoystickAxes (int jid, int * count)
Returns the values of all axes of the specified joystick.
This function returns the values of all axes of the specified joystick. Each element in the array is a value between -1.0 and 1.0.
If the specified joystick is not present this function will return NULL but will not generate an error. This can be used instead of first calling glfwJoystickPresent.
Parameters
[in] jid The joystick to query.
[out] count Where to store the number of axis values in the returned array. This is set to zero if the joystick is not present or an error occurred.
Returns
An array of axis values, or NULL if the joystick is not present or an error occurred.
Possible errors include GLFW_NOT_INITIALIZED, GLFW_INVALID_ENUM and GLFW_PLATFORM_ERROR.
The returned array is allocated and freed by GLFW. You should not free it yourself. It is valid until the specified joystick is disconnected or the library is terminated.
This function must only be called from the main thread.
See also
joystick_axis
Since
Added in version 3.0. Replaces glfwGetJoystickPos.
References _glfw, _GLFW_POLL_AXES, _GLFW_REQUIRE_INIT_OR_RETURN, _glfwInputError(), _glfwPlatformPollJoystick(), _GLFWjoystick::axes, _GLFWjoystick::axisCount, GLFW_INVALID_ENUM, GLFW_JOYSTICK_1, GLFW_JOYSTICK_LAST, _GLFWlibrary::joysticks, NULL, and _GLFWjoystick::present.
Referenced by AuroraFW::GEngine::ImGuiLoader::newFrame().
glfwGetJoystickButtons()
GLFWAPI const unsigned char* glfwGetJoystickButtons (int jid, int * count)
Returns the state of all buttons of the specified joystick.
This function returns the state of all buttons of the specified joystick. Each element in the array is either GLFW_PRESS or GLFW_RELEASE.
For backward compatibility with earlier versions that did not have glfwGetJoystickHats, the button array also includes all hats, each represented as four buttons. The hats are in the same order as returned by glfwGetJoystickHats and are in the order up, right, down and left. To disable these extra buttons, set the GLFW_JOYSTICK_HAT_BUTTONS init hint before initialization.
If the specified joystick is not present this function will return NULL but will not generate an error. This can be used instead of first calling glfwJoystickPresent.
Parameters
[in] jid The joystick to query.
[out] count Where to store the number of button states in the returned array. This is set to zero if the joystick is not present or an error occurred.
Returns
An array of button states, or NULL if the joystick is not present or an error occurred.
Possible errors include GLFW_NOT_INITIALIZED, GLFW_INVALID_ENUM and GLFW_PLATFORM_ERROR.
The returned array is allocated and freed by GLFW. You should not free it yourself. It is valid until the specified joystick is disconnected or the library is terminated.
This function must only be called from the main thread.
See also
joystick_button
Since
Added in version 2.2. Changed to return a dynamic array.
References _glfw, _GLFW_POLL_BUTTONS, _GLFW_REQUIRE_INIT_OR_RETURN, _glfwInputError(), _glfwPlatformPollJoystick(), _GLFWjoystick::buttonCount, _GLFWjoystick::buttons, GLFW_INVALID_ENUM, GLFW_JOYSTICK_1, GLFW_JOYSTICK_LAST, _GLFWinitconfig::hatButtons, _GLFWjoystick::hatCount, _GLFWlibrary::hints, _GLFWlibrary::init, _GLFWlibrary::joysticks, NULL, and _GLFWjoystick::present.
Referenced by AuroraFW::GEngine::ImGuiLoader::newFrame().
glfwGetJoystickHats()
GLFWAPI const unsigned char* glfwGetJoystickHats (int jid, int * count)
Returns the state of all hats of the specified joystick.
This function returns the state of all hats of the specified joystick. Each element in the array is one of the following values:
Name Value ------------------—
GLFW_HAT_CENTERED 0
GLFW_HAT_UP 1
GLFW_HAT_RIGHT 2
GLFW_HAT_DOWN 4
GLFW_HAT_LEFT 8
GLFW_HAT_RIGHT_UP GLFW_HAT_RIGHT | GLFW_HAT_UP
GLFW_HAT_RIGHT_DOWN GLFW_HAT_RIGHT | GLFW_HAT_DOWN
GLFW_HAT_LEFT_UP GLFW_HAT_LEFT | GLFW_HAT_UP
GLFW_HAT_LEFT_DOWN GLFW_HAT_LEFT | GLFW_HAT_DOWN
The diagonal directions are bitwise combinations of the primary (up, right, down and left) directions and you can test for these individually by ANDing it with the corresponding direction.
if (hats[2] & GLFW_HAT_RIGHT)
{
    // State of hat 2 could be right-up, right or right-down
}
If the specified joystick is not present this function will return NULL but will not generate an error. This can be used instead of first calling glfwJoystickPresent.
Parameters
[in] jid The joystick to query.
[out] count Where to store the number of hat states in the returned array. This is set to zero if the joystick is not present or an error occurred.
Returns
An array of hat states, or NULL if the joystick is not present or an error occurred.
Possible errors include GLFW_NOT_INITIALIZED, GLFW_INVALID_ENUM and GLFW_PLATFORM_ERROR.
The returned array is allocated and freed by GLFW. You should not free it yourself. It is valid until the specified joystick is disconnected, this function is called again for that joystick or the library is terminated.
This function must only be called from the main thread.
See also
joystick_hat
Since
Added in version 3.3.
References _glfw, _GLFW_POLL_BUTTONS, _GLFW_REQUIRE_INIT_OR_RETURN, _glfwInputError(), _glfwPlatformPollJoystick(), GLFW_INVALID_ENUM, GLFW_JOYSTICK_1, GLFW_JOYSTICK_LAST, _GLFWjoystick::hatCount, _GLFWjoystick::hats, _GLFWlibrary::joysticks, NULL, and _GLFWjoystick::present.
glfwGetJoystickName()
GLFWAPI const char* glfwGetJoystickName (int jid)
Returns the name of the specified joystick.
This function returns the name, encoded as UTF-8, of the specified joystick. The returned string is allocated and freed by GLFW. You should not free it yourself.
If the specified joystick is not present this function will return NULL but will not generate an error. This can be used instead of first calling glfwJoystickPresent.
Parameters
[in] jid The joystick to query.
Returns
The UTF-8 encoded name of the joystick, or NULL if the joystick is not present or an error occurred.
Possible errors include GLFW_NOT_INITIALIZED, GLFW_INVALID_ENUM and GLFW_PLATFORM_ERROR.
The returned string is allocated and freed by GLFW. You should not free it yourself. It is valid until the specified joystick is disconnected or the library is terminated.
This function must only be called from the main thread.
See also
joystick_name
Since
Added in version 3.0.
References _glfw, _GLFW_POLL_PRESENCE, _GLFW_REQUIRE_INIT_OR_RETURN, _glfwInputError(), _glfwPlatformPollJoystick(), GLFW_INVALID_ENUM, GLFW_JOYSTICK_1, GLFW_JOYSTICK_LAST, _GLFWlibrary::joysticks, _GLFWjoystick::name, NULL, and _GLFWjoystick::present.
glfwGetJoystickGUID()
GLFWAPI const char* glfwGetJoystickGUID (int jid)
Returns the SDL comaptible GUID of the specified joystick.
This function returns the SDL compatible GUID, as a UTF-8 encoded hexadecimal string, of the specified joystick. The returned string is allocated and freed by GLFW. You should not free it yourself.
The GUID is what connects a joystick to a gamepad mapping. A connected joystick will always have a GUID even if there is no gamepad mapping assigned to it.
If the specified joystick is not present this function will return NULL but will not generate an error. This can be used instead of first calling glfwJoystickPresent.
The GUID uses the format introduced in SDL 2.0.5. This GUID tries to uniquely identify the make and model of a joystick but does not identify a specific unit, e.g. all wired Xbox 360 controllers will have the same GUID on that platform. The GUID for a unit may vary between platforms depending on what hardware information the platform specific APIs provide.
Parameters
[in] jid The joystick to query.
Returns
The UTF-8 encoded GUID of the joystick, or NULL if the joystick is not present or an error occurred.
Possible errors include GLFW_NOT_INITIALIZED, GLFW_INVALID_ENUM and GLFW_PLATFORM_ERROR.
The returned string is allocated and freed by GLFW. You should not free it yourself. It is valid until the specified joystick is disconnected or the library is terminated.
This function must only be called from the main thread.
See also
gamepad
Since
Added in version 3.3.
References _glfw, _GLFW_POLL_PRESENCE, _GLFW_REQUIRE_INIT_OR_RETURN, _glfwInputError(), _glfwPlatformPollJoystick(), GLFW_INVALID_ENUM, GLFW_JOYSTICK_1, GLFW_JOYSTICK_LAST, _GLFWjoystick::guid, _GLFWlibrary::joysticks, NULL, and _GLFWjoystick::present.
glfwSetJoystickUserPointer()
GLFWAPI void glfwSetJoystickUserPointer (int jid, void * pointer)
Sets the user pointer of the specified joystick.
This function sets the user-defined pointer of the specified joystick. The current value is retained until the joystick is disconnected. The initial value is NULL.
This function may be called from the joystick callback, even for a joystick that is being disconnected.
Parameters
[in] joystick The joystick whose pointer to set.
[in] pointer The new value.
Possible errors include GLFW_NOT_INITIALIZED.
This function may be called from any thread. Access is not synchronized.
See also
joystick_userptr
glfwGetJoystickUserPointer
Since
Added in version 3.3.
References _glfw, _GLFW_REQUIRE_INIT, GLFW_JOYSTICK_1, GLFW_JOYSTICK_LAST, _GLFWlibrary::joysticks, pointer, _GLFWjoystick::present, and _GLFWjoystick::userPointer.
glfwGetJoystickUserPointer()
GLFWAPI void* glfwGetJoystickUserPointer (int jid)
Returns the user pointer of the specified joystick.
This function returns the current value of the user-defined pointer of the specified joystick. The initial value is NULL.
This function may be called from the joystick callback, even for a joystick that is being disconnected.
Parameters
[in] joystick The joystick whose pointer to return.
Possible errors include GLFW_NOT_INITIALIZED.
This function may be called from any thread. Access is not synchronized.
See also
joystick_userptr
glfwSetJoystickUserPointer
Since
Added in version 3.3.
References _glfw, _GLFW_REQUIRE_INIT_OR_RETURN, GLFW_JOYSTICK_1, GLFW_JOYSTICK_LAST, _GLFWlibrary::joysticks, NULL, _GLFWjoystick::present, and _GLFWjoystick::userPointer.
glfwJoystickIsGamepad()
GLFWAPI int glfwJoystickIsGamepad (int jid)
Returns whether the specified joystick has a gamepad mapping.
This function returns whether the specified joystick is both present and has a gamepad mapping.
If the specified joystick is present but does not have a gamepad mapping this function will return GLFW_FALSE but will not generate an error. Call glfwJoystickPresent to check if a joystick is present regardless of whether it has a mapping.
Parameters
[in] jid The joystick to query.
Returns
GLFW_TRUE if a joystick is both present and has a gamepad mapping, or GLFW_FALSE otherwise.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_INVALID_ENUM.
This function must only be called from the main thread.
See also
gamepad
glfwGetGamepadState
Since
Added in version 3.3.
References _glfw, _GLFW_POLL_PRESENCE, _GLFW_REQUIRE_INIT_OR_RETURN, _glfwInputError(), _glfwPlatformPollJoystick(), GLFW_FALSE, GLFW_INVALID_ENUM, GLFW_JOYSTICK_1, GLFW_JOYSTICK_LAST, _GLFWlibrary::joysticks, _GLFWjoystick::mapping, NULL, and _GLFWjoystick::present.
glfwSetJoystickCallback()
GLFWAPI GLFWjoystickfun glfwSetJoystickCallback (GLFWjoystickfun cbfun)
Sets the joystick configuration callback.
This function sets the joystick configuration callback, or removes the currently set callback. This is called when a joystick is connected to or disconnected from the system.
For joystick connection and disconnection events to be delivered on all platforms, you need to call one of the event processing functions. Joystick disconnection may also be detected and the callback called by joystick functions. The function will then return whatever it returns if the joystick is not present.
Parameters
[in] cbfun The new callback, or NULL to remove the currently set callback.
Returns
The previously set callback, or NULL if no callback was set or the library had not been initialized.
Possible errors include GLFW_NOT_INITIALIZED.
This function must only be called from the main thread.
See also
joystick_event
Since
Added in version 3.2.
References _glfw, _GLFW_REQUIRE_INIT_OR_RETURN, _GLFW_SWAP_POINTERS, _GLFWlibrary::callbacks, _GLFWlibrary::joystick, and NULL.
glfwUpdateGamepadMappings()
GLFWAPI int glfwUpdateGamepadMappings (const char * string)
Adds the specified SDL_GameControllerDB gamepad mappings.
This function parses the specified ASCII encoded string and updates the internal list with any gamepad mappings it finds. This string may contain either a single gamepad mapping or many mappings separated by newlines. The parser supports the full format of the gamecontrollerdb.txt source file including empty lines and comments.
See gamepad_mapping for a description of the format.
If there is already a gamepad mapping for a given GUID in the internal list, it will be replaced by the one passed to this function. If the library is terminated and re-initialized the internal list will revert to the built-in default.
Parameters
[in] string The string containing the gamepad mappings.
Returns
GLFW_TRUE if successful, or GLFW_FALSE if an error occurred.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_INVALID_VALUE.
This function must only be called from the main thread.
See also
gamepad
glfwJoystickIsGamepad
glfwGetGamepadName
Since
Added in version 3.3.
References _glfw, _GLFW_REQUIRE_INIT_OR_RETURN, findMapping(), findValidMapping(), GLFW_FALSE, GLFW_JOYSTICK_LAST, GLFW_TRUE, _GLFWmapping::guid, _GLFWlibrary::joysticks, _GLFWjoystick::mapping, _GLFWlibrary::mappingCount, _GLFWlibrary::mappings, memcpy(), NULL, parseMapping(), and _GLFWjoystick::present.
Referenced by glfwInit().
glfwGetGamepadName()
GLFWAPI const char* glfwGetGamepadName (int jid)
Returns the human-readable gamepad name for the specified joystick.
This function returns the human-readable name of the gamepad from the gamepad mapping assigned to the specified joystick.
If the specified joystick is not present or does not have a gamepad mapping this function will return NULL but will not generate an error. Call glfwJoystickPresent to check whether it is present regardless of whether it has a mapping.
Parameters
[in] jid The joystick to query.
Returns
The UTF-8 encoded name of the gamepad, or NULL if the joystick is not present, does not have a mapping or an error occurred.
The returned string is allocated and freed by GLFW. You should not free it yourself. It is valid until the specified joystick is disconnected, the gamepad mappings are updated or the library is terminated.
This function must only be called from the main thread.
See also
gamepad
glfwJoystickIsGamepad
Since
Added in version 3.3.
References _glfw, _GLFW_POLL_PRESENCE, _GLFW_REQUIRE_INIT_OR_RETURN, _glfwInputError(), _glfwPlatformPollJoystick(), GLFW_INVALID_ENUM, GLFW_JOYSTICK_1, GLFW_JOYSTICK_LAST, _GLFWlibrary::joysticks, _GLFWjoystick::mapping, _GLFWmapping::name, NULL, and _GLFWjoystick::present.
glfwGetGamepadState()
GLFWAPI int glfwGetGamepadState (int jid, GLFWgamepadstate * state)
Retrieves the state of the specified joystick remapped as a gamepad.
This function retrives the state of the specified joystick remapped to an Xbox-like gamepad.
If the specified joystick is not present or does not have a gamepad mapping this function will return GLFW_FALSE but will not generate an error. Call glfwJoystickPresent to check whether it is present regardless of whether it has a mapping.
The Guide button may not be available for input as it is often hooked by the system or the Steam client.
Not all devices have all the buttons or axes provided by GLFWgamepadstate. Unavailable buttons and axes will always report GLFW_RELEASE and 0.0 respectively.
Parameters
[in] jid The joystick to query.
[out] state The gamepad input state of the joystick.
Returns
GLFW_TRUE if successful, or GLFW_FALSE if no joystick is connected, it has no gamepad mapping or an error occurred.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_INVALID_ENUM.
See also
gamepad
glfwUpdateGamepadMappings
glfwJoystickIsGamepad
Since
Added in version 3.3.
References _glfw, _GLFW_JOYSTICK_AXIS, _GLFW_JOYSTICK_BUTTON, _GLFW_JOYSTICK_HATBIT, _GLFW_POLL_ALL, _GLFW_REQUIRE_INIT_OR_RETURN, _glfwInputError(), _glfwPlatformPollJoystick(), _GLFWmapping::axes, _GLFWjoystick::axes, GLFWgamepadstate::axes, _GLFWmapelement::axisOffset, _GLFWmapelement::axisScale, _GLFWmapping::buttons, _GLFWjoystick::buttons, GLFWgamepadstate::buttons, GLFW_FALSE, GLFW_GAMEPAD_AXIS_LAST, GLFW_GAMEPAD_BUTTON_LAST, GLFW_INVALID_ENUM, GLFW_JOYSTICK_1, GLFW_JOYSTICK_LAST, GLFW_PRESS, GLFW_TRUE, _GLFWjoystick::hats, _GLFWmapelement::index, _GLFWlibrary::joysticks, _GLFWjoystick::mapping, memset(), NULL, _GLFWjoystick::present, _GLFWmapelement::type, and value.
glfwSetClipboardString()
GLFWAPI void glfwSetClipboardString (GLFWwindow * window, const char * string)
Sets the clipboard to the specified string.
This function sets the system clipboard to the specified, UTF-8 encoded string.
Parameters
[in] window Deprecated. Any valid window or NULL.
[in] string A UTF-8 encoded string.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
Remarks
Clipboard is currently unimplemented.
The specified string is copied before this function returns.
This function must only be called from the main thread.
See also
clipboard
glfwGetClipboardString
Since
Added in version 3.0.
References _GLFW_REQUIRE_INIT, _glfwPlatformSetClipboardString(), and NULL.
glfwGetClipboardString()
GLFWAPI const char* glfwGetClipboardString (GLFWwindow * window)
Returns the contents of the clipboard as a string.
This function returns the contents of the system clipboard, if it contains or is convertible to a UTF-8 encoded string. If the clipboard is empty or if its contents cannot be converted, NULL is returned and a GLFW_FORMAT_UNAVAILABLE error is generated.
Parameters
[in] window Deprecated. Any valid window or NULL.
Returns
The contents of the clipboard as a UTF-8 encoded string, or NULL if an error occurred.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_PLATFORM_ERROR.
Remarks
Clipboard is currently unimplemented.
The returned string is allocated and freed by GLFW. You should not free it yourself. It is valid until the next call to glfwGetClipboardString or glfwSetClipboardString, or until the library is terminated.
This function must only be called from the main thread.
See also
clipboard
glfwSetClipboardString
Since
Added in version 3.0.
References _GLFW_REQUIRE_INIT_OR_RETURN, _glfwPlatformGetClipboardString(), and NULL.
glfwGetTime()
GLFWAPI double glfwGetTime (void)
Returns the value of the GLFW timer.
This function returns the value of the GLFW timer. Unless the timer has been set using glfwSetTime, the timer measures time elapsed since GLFW was initialized.
The resolution of the timer is system dependent, but is usually on the order of a few micro- or nanoseconds. It uses the highest-resolution monotonic time source on each supported platform.
Returns
The current value, in seconds, or zero if an error occurred.
Possible errors include GLFW_NOT_INITIALIZED.
This function may be called from any thread. Reading and writing of the internal timer offset is not atomic, so it needs to be externally synchronized with calls to glfwSetTime.
See also
time
Since
Added in version 1.0.
References _glfw, _GLFW_REQUIRE_INIT_OR_RETURN, _glfwPlatformGetTimerFrequency(), _glfwPlatformGetTimerValue(), _GLFWlibrary::offset, and _GLFWlibrary::timer.
Referenced by AuroraFW::GEngine::ImGuiLoader::newFrame().
glfwSetTime()
GLFWAPI void glfwSetTime (double time)
Sets the GLFW timer.
This function sets the value of the GLFW timer. It then continues to count up from that value. The value must be a positive finite number less than or equal to 18446744073.0, which is approximately 584.5 years.
Parameters
[in] time The new value, in seconds.
Possible errors include GLFW_NOT_INITIALIZED and GLFW_INVALID_VALUE.
Remarks
The upper limit of the timer is calculated as floor((264 - 1) / 109) and is due to implementations storing nanoseconds in 64 bits. The limit may be increased in the future.
This function may be called from any thread. Reading and writing of the internal timer offset is not atomic, so it needs to be externally synchronized with calls to glfwGetTime.
See also
time
Since
Added in version 2.2.
References _glfw, _GLFW_REQUIRE_INIT, _glfwInputError(), _glfwPlatformGetTimerFrequency(), _glfwPlatformGetTimerValue(), GLFW_INVALID_VALUE, _GLFWlibrary::offset, and _GLFWlibrary::timer.
glfwGetTimerValue()
GLFWAPI uint64_t glfwGetTimerValue (void)
Returns the current value of the raw timer.
This function returns the current value of the raw timer, measured in 1 / frequency seconds. To get the frequency, call glfwGetTimerFrequency.
Returns
The value of the timer, or zero if an error occurred.
Possible errors include GLFW_NOT_INITIALIZED.
This function may be called from any thread.
See also
time
glfwGetTimerFrequency
Since
Added in version 3.2.
References _GLFW_REQUIRE_INIT_OR_RETURN, and _glfwPlatformGetTimerValue().
glfwGetTimerFrequency()
GLFWAPI uint64_t glfwGetTimerFrequency (void)
Returns the frequency, in Hz, of the raw timer.
This function returns the frequency, in Hz, of the raw timer.
Returns
The frequency of the timer, in Hz, or zero if an error occurred.
Possible errors include GLFW_NOT_INITIALIZED.
This function may be called from any thread.
See also
time
glfwGetTimerValue
Since
Added in version 3.2.
References _GLFW_REQUIRE_INIT_OR_RETURN, and _glfwPlatformGetTimerFrequency().