Aurora Framework: svx.c File Reference
svx.c File Reference
Classes
struct VHDR_CHUNK
Macros
#define ANNO_MARKER (MAKE_MARKER ('A', 'N', 'N', 'O'))
#define ATAK_MARKER (MAKE_MARKER ('A', 'T', 'A', 'K'))
#define AUTH_MARKER (MAKE_MARKER ('A', 'U', 'T', 'H'))
#define BODY_MARKER (MAKE_MARKER ('B', 'O', 'D', 'Y'))
#define c_MARKER (MAKE_MARKER ('(', 'c', ')', ' '))
#define CHAN_MARKER (MAKE_MARKER ('C', 'H', 'A', 'N'))
#define FORM_MARKER (MAKE_MARKER ('F', 'O', 'R', 'M'))
#define NAME_MARKER (MAKE_MARKER ('N', 'A', 'M', 'E'))
#define RLSE_MARKER (MAKE_MARKER ('R', 'L', 'S', 'E'))
#define SV16_MARKER (MAKE_MARKER ('1', '6', 'S', 'V'))
#define SVX8_MARKER (MAKE_MARKER ('8', 'S', 'V', 'X'))
#define VHDR_MARKER (MAKE_MARKER ('V', 'H', 'D', 'R'))
Enumerations
enum { HAVE_FORM = 0x01, HAVE_SVX = 0x02, HAVE_VHDR = 0x04, HAVE_BODY = 0x08 }
Functions
static int svx_close (SF_PRIVATE *psf)
int svx_open (SF_PRIVATE *psf)
static int svx_read_header (SF_PRIVATE *psf)
static int svx_write_header (SF_PRIVATE *psf, int calc_length)
Macro Definition Documentation
FORM_MARKER
#define FORM_MARKER (MAKE_MARKER ('F', 'O', 'R', 'M'))
Referenced by svx_read_header(), and svx_write_header().
SVX8_MARKER
#define SVX8_MARKER (MAKE_MARKER ('8', 'S', 'V', 'X'))
Referenced by svx_read_header(), and svx_write_header().
SV16_MARKER
#define SV16_MARKER (MAKE_MARKER ('1', '6', 'S', 'V'))
Referenced by svx_read_header(), and svx_write_header().
VHDR_MARKER
#define VHDR_MARKER (MAKE_MARKER ('V', 'H', 'D', 'R'))
Referenced by svx_read_header(), and svx_write_header().
BODY_MARKER
#define BODY_MARKER (MAKE_MARKER ('B', 'O', 'D', 'Y'))
Referenced by svx_read_header(), and svx_write_header().
ATAK_MARKER
#define ATAK_MARKER (MAKE_MARKER ('A', 'T', 'A', 'K'))
RLSE_MARKER
#define RLSE_MARKER (MAKE_MARKER ('R', 'L', 'S', 'E'))
c_MARKER
#define c_MARKER (MAKE_MARKER ('(', 'c', ')', ' '))
Referenced by svx_read_header().
NAME_MARKER
#define NAME_MARKER (MAKE_MARKER ('N', 'A', 'M', 'E'))
Referenced by svx_read_header(), and svx_write_header().
AUTH_MARKER
#define AUTH_MARKER (MAKE_MARKER ('A', 'U', 'T', 'H'))
Referenced by svx_read_header().
ANNO_MARKER
#define ANNO_MARKER (MAKE_MARKER ('A', 'N', 'N', 'O'))
Referenced by svx_read_header(), and svx_write_header().
CHAN_MARKER
#define CHAN_MARKER (MAKE_MARKER ('C', 'H', 'A', 'N'))
Referenced by svx_read_header(), and svx_write_header().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
HAVE_FORM
HAVE_SVX
HAVE_VHDR
HAVE_BODY
Function Documentation
svx_close()
static int svx_close (SF_PRIVATE * psf) static
References sf_private_tag::file, PSF_FILE::mode, and svx_write_header().
Referenced by svx_open().
svx_write_header()
static int svx_write_header (SF_PRIVATE * psf, int calc_length) static
References ANNO_MARKER, BHW1, BHW2, BHW4, BHW8, BHWm, BHWs, BODY_MARKER, sf_private_tag::bytewidth, PSF_FILE::c, CHAN_MARKER, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::error, sf_private_tag::file, sf_private_tag::filelength, FORM_MARKER, sf_private_tag::header, sf_private_tag::indx, PSF_FILE::name, NAME_MARKER, psf_binheader_writef(), psf_fseek(), psf_ftell(), psf_fwrite(), psf_get_filelen(), sf_private_tag::ptr, sf_private_tag::sf, SV16_MARKER, SVX8_MARKER, and VHDR_MARKER.
Referenced by svx_close(), and svx_open().
svx_read_header()
static int svx_read_header (SF_PRIVATE * psf) static
References ANNO_MARKER, AUTH_MARKER, BODY_MARKER, sf_private_tag::bytewidth, PSF_FILE::c, c_MARKER, CHAN_MARKER, VHDR_CHUNK::compression, sf_private_tag::datalength, sf_private_tag::dataoffset, done(), sf_private_tag::file, sf_private_tag::filelength, FORM_MARKER, HAVE_BODY, HAVE_FORM, HAVE_SVX, HAVE_VHDR, memset(), PSF_FILE::name, NAME_MARKER, VHDR_CHUNK::octave, VHDR_CHUNK::oneShotHiSamples, psf_binheader_readf(), psf_fseek(), psf_ftell(), psf_isprint(), psf_log_printf(), VHDR_CHUNK::repeatHiSamples, VHDR_CHUNK::samplesPerHiCycle, VHDR_CHUNK::samplesPerSec, sf_private_tag::sf, SFE_SVX_BAD_COMP, SFE_SVX_BAD_NAME_LENGTH, SFE_SVX_NO_BODY, SFE_SVX_NO_DATA, SFE_SVX_NO_FORM, SIGNED_SIZEOF, SV16_MARKER, SVX8_MARKER, VHDR_MARKER, and VHDR_CHUNK::volume.
Referenced by svx_open().
svx_open()
int svx_open (SF_PRIVATE * psf)
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::container_close, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, sf_private_tag::is_pipe, PSF_FILE::mode, pcm_init(), psf_fseek(), sf_private_tag::sf, SF_CONTAINER, SF_ENDIAN, SFE_BAD_ENDIAN, SFE_BAD_OPEN_FORMAT, SFE_NO_PIPE_WRITE, svx_close(), svx_read_header(), svx_write_header(), and sf_private_tag::write_header.
Referenced by psf_open_file().