Aurora Framework: chunk.c File Reference
chunk.c File Reference
Functions
static int64_t hash_of_str (const char *str)
int psf_find_read_chunk_iterator (const READ_CHUNKS *pchk, const SF_CHUNK_ITERATOR *marker)
int psf_find_read_chunk_m32 (const READ_CHUNKS *pchk, uint32_t marker)
int psf_find_read_chunk_str (const READ_CHUNKS *pchk, const char *marker_str)
SF_CHUNK_ITERATOR * psf_get_chunk_iterator (SF_PRIVATE *psf, const char *marker_str)
SF_CHUNK_ITERATOR * psf_next_chunk_iterator (const READ_CHUNKS *pchk, SF_CHUNK_ITERATOR *iterator)
int psf_save_write_chunk (WRITE_CHUNKS *pchk, const SF_CHUNK_INFO *chunk_info)
static int psf_store_read_chunk (READ_CHUNKS *pchk, const READ_CHUNK *rchunk)
int psf_store_read_chunk_str (READ_CHUNKS *pchk, const char *marker_str, sf_count_t offset, uint32_t len)
int psf_store_read_chunk_u32 (READ_CHUNKS *pchk, uint32_t marker, sf_count_t offset, uint32_t len)
Function Documentation
hash_of_str()
static int64_t hash_of_str (const char * str) static
Referenced by psf_find_read_chunk_str(), psf_get_chunk_iterator(), psf_save_write_chunk(), and psf_store_read_chunk_str().
psf_get_chunk_iterator()
SF_CHUNK_ITERATOR* psf_get_chunk_iterator (SF_PRIVATE * psf, const char * marker_str)
References SF_CHUNK_ITERATOR::current, SF_CHUNK_ITERATOR::hash, hash_of_str(), SF_CHUNK_ITERATOR::id, SF_CHUNK_ITERATOR::id_size, sf_private_tag::iterator, memcpy(), NULL, psf_find_read_chunk_str(), sf_private_tag::rchunks, SF_CHUNK_ITERATOR::sndfile, and READ_CHUNKS::used.
Referenced by alac_pakt_read_decode(), and sf_get_chunk_iterator().
psf_next_chunk_iterator()
SF_CHUNK_ITERATOR* psf_next_chunk_iterator (const READ_CHUNKS * pchk, SF_CHUNK_ITERATOR * iterator)
References READ_CHUNKS::chunks, SF_CHUNK_ITERATOR::current, READ_CHUNK::hash, SF_CHUNK_ITERATOR::hash, memset(), NULL, and READ_CHUNKS::used.
Referenced by aiff_next_chunk_iterator(), caf_next_chunk_iterator(), rf64_next_chunk_iterator(), and wav_next_chunk_iterator().
psf_store_read_chunk()
static int psf_store_read_chunk (READ_CHUNKS * pchk, const READ_CHUNK * rchunk) static
References READ_CHUNKS::chunks, READ_CHUNKS::count, NULL, SFE_INTERNAL, SFE_MALLOC_FAILED, SFE_NO_ERROR, and READ_CHUNKS::used.
Referenced by psf_store_read_chunk_str(), and psf_store_read_chunk_u32().
psf_store_read_chunk_u32()
int psf_store_read_chunk_u32 (READ_CHUNKS * pchk, uint32_t marker, sf_count_t offset, uint32_t len)
References READ_CHUNK::hash, READ_CHUNK::id, READ_CHUNK::id_size, READ_CHUNK::len, READ_CHUNK::mark32, memcpy(), memset(), READ_CHUNK::offset, and psf_store_read_chunk().
Referenced by aiff_read_header(), caf_read_header(), rf64_read_header(), and wav_read_header().
psf_find_read_chunk_str()
int psf_find_read_chunk_str (const READ_CHUNKS * pchk, const char * marker_str)
References READ_CHUNKS::chunks, READ_CHUNK::hash, hash_of_str(), and READ_CHUNKS::used.
Referenced by psf_get_chunk_iterator().
psf_find_read_chunk_m32()
int psf_find_read_chunk_m32 (const READ_CHUNKS * pchk, uint32_t marker)
References READ_CHUNKS::chunks, READ_CHUNK::mark32, and READ_CHUNKS::used.
Referenced by aiff_rewrite_header().
psf_find_read_chunk_iterator()
int psf_find_read_chunk_iterator (const READ_CHUNKS * pchk, const SF_CHUNK_ITERATOR * marker)
References SF_CHUNK_ITERATOR::current, and READ_CHUNKS::used.
Referenced by aiff_get_chunk_data(), aiff_get_chunk_size(), caf_get_chunk_data(), caf_get_chunk_size(), rf64_get_chunk_data(), rf64_get_chunk_size(), wav_get_chunk_data(), and wav_get_chunk_size().
psf_store_read_chunk_str()
int psf_store_read_chunk_str (READ_CHUNKS * pchk, const char * marker_str, sf_count_t offset, uint32_t len)
References READ_CHUNK::hash, hash_of_str(), READ_CHUNK::id, READ_CHUNK::id_size, READ_CHUNK::len, READ_CHUNK::mark32, memcpy(), memset(), READ_CHUNK::offset, and psf_store_read_chunk().
psf_save_write_chunk()
int psf_save_write_chunk (WRITE_CHUNKS * pchk, const SF_CHUNK_INFO * chunk_info)
References WRITE_CHUNKS::chunks, WRITE_CHUNKS::count, WRITE_CHUNK::data, WRITE_CHUNK::hash, hash_of_str(), WRITE_CHUNK::len, WRITE_CHUNK::mark32, NULL, psf_memdup(), SFE_MALLOC_FAILED, SFE_NO_ERROR, and WRITE_CHUNKS::used.
Referenced by aiff_set_chunk(), alac_close(), caf_set_chunk(), rf64_set_chunk(), and wav_set_chunk().