Aurora Framework: _GLFWjoyelementNS Struct Reference
_GLFWjoyelementNS Struct Reference
Protected Attributes
int index
long maximum
long minimum
IOHIDElementRef native
uint32_t usage
Member Data Documentation
native
- (IOHIDElementRef) native protected
Referenced by getElementValue(), and matchCallback().
usage
- (uint32_t) usage protected
Referenced by compareElements(), and matchCallback().
index
- (int) index protected
Referenced by compareElements(), and matchCallback().
minimum
- (long) minimum protected
Referenced by _glfwPlatformPollJoystick(), and matchCallback().
maximum
- (long) maximum protected
Referenced by _glfwPlatformPollJoystick(), and matchCallback().
The documentation for this struct was generated from the following file:
Joystick.m