Aurora Framework: command.c File Reference
command.c File Reference
Functions
int psf_calc_max_all_channels (SF_PRIVATE *psf, double *peaks, int normalize)
double psf_calc_signal_max (SF_PRIVATE *psf, int normalize)
int psf_get_format_info (SF_FORMAT_INFO *data)
int psf_get_format_major (SF_FORMAT_INFO *data)
int psf_get_format_major_count (void)
int psf_get_format_simple (SF_FORMAT_INFO *data)
int psf_get_format_simple_count (void)
int psf_get_format_subtype (SF_FORMAT_INFO *data)
int psf_get_format_subtype_count (void)
int psf_get_max_all_channels (SF_PRIVATE *psf, double *peaks)
int psf_get_signal_max (SF_PRIVATE *psf, double *peak)
Variables
static SF_FORMAT_INFO const major_formats []
static SF_FORMAT_INFO const simple_formats []
static SF_FORMAT_INFO subtype_formats []
Function Documentation
psf_get_format_simple_count()
int psf_get_format_simple_count (void)
References simple_formats.
Referenced by sf_command().
psf_get_format_simple()
int psf_get_format_simple (SF_FORMAT_INFO * data)
References memcpy(), SFE_BAD_COMMAND_PARAM, SIGNED_SIZEOF, and simple_formats.
Referenced by sf_command().
psf_get_format_major_count()
int psf_get_format_major_count (void)
References major_formats.
Referenced by sf_command().
psf_get_format_major()
int psf_get_format_major (SF_FORMAT_INFO * data)
References major_formats, memcpy(), SFE_BAD_COMMAND_PARAM, and SIGNED_SIZEOF.
Referenced by sf_command().
psf_get_format_subtype_count()
int psf_get_format_subtype_count (void)
References subtype_formats.
Referenced by sf_command().
psf_get_format_subtype()
int psf_get_format_subtype (SF_FORMAT_INFO * data)
References memcpy(), SFE_BAD_COMMAND_PARAM, SIGNED_SIZEOF, and subtype_formats.
Referenced by sf_command().
psf_get_format_info()
int psf_get_format_info (SF_FORMAT_INFO * data)
References major_formats, memcpy(), memset(), SF_CODEC, SF_CONTAINER, SFE_BAD_COMMAND_PARAM, SIGNED_SIZEOF, and subtype_formats.
Referenced by sf_command().
psf_calc_signal_max()
double psf_calc_signal_max (SF_PRIVATE * psf, int normalize)
References ARRAY_LEN, BUF_UNION::dbuf, sf_private_tag::error, NULL, sf_private_tag::read_double, sf_private_tag::sf, sf_command(), sf_read_double(), sf_seek(), SFE_NOT_SEEKABLE, and SFE_UNIMPLEMENTED.
Referenced by sf_command().
psf_calc_max_all_channels()
int psf_calc_max_all_channels (SF_PRIVATE * psf, double * peaks, int normalize)
References ARRAY_LEN, BUF_UNION::dbuf, sf_private_tag::error, memset(), NULL, sf_private_tag::read_double, sf_private_tag::sf, sf_command(), sf_read_double(), sf_seek(), SFE_NOT_SEEKABLE, and SFE_UNIMPLEMENTED.
Referenced by sf_command().
psf_get_signal_max()
int psf_get_signal_max (SF_PRIVATE * psf, double * peak)
References NULL, sf_private_tag::peak_info, PEAK_INFO::peaks, sf_private_tag::sf, SF_MAX, and PEAK_POS::value.
Referenced by sf_command().
psf_get_max_all_channels()
int psf_get_max_all_channels (SF_PRIVATE * psf, double * peaks)
References NULL, sf_private_tag::peak_info, PEAK_INFO::peaks, sf_private_tag::sf, and PEAK_POS::value.
Referenced by sf_command().
Variable Documentation
simple_formats
SF_FORMAT_INFO const simple_formats[] static
Referenced by psf_get_format_simple(), and psf_get_format_simple_count().
major_formats
SF_FORMAT_INFO const major_formats[] static
Referenced by psf_get_format_info(), psf_get_format_major(), and psf_get_format_major_count().
subtype_formats
SF_FORMAT_INFO subtype_formats[] static
Referenced by psf_get_format_info(), psf_get_format_subtype(), and psf_get_format_subtype_count().