Aurora Framework: ImDrawList Struct Reference
ImDrawList Struct Reference
Public Member Functions
ImDrawList (const ImDrawListSharedData *shared_data)
~ImDrawList ()
IMGUI_API void AddBezierCurve (const ImVec2 &pos0, const ImVec2 &cp0, const ImVec2 &cp1, const ImVec2 &pos1, ImU32 col, float thickness, int num_segments=0)
IMGUI_API void AddCallback (ImDrawCallback callback, void *callback_data)
IMGUI_API void AddCircle (const ImVec2 &centre, float radius, ImU32 col, int num_segments=12, float thickness=1.0f)
IMGUI_API void AddCircleFilled (const ImVec2 &centre, float radius, ImU32 col, int num_segments=12)
IMGUI_API void AddConvexPolyFilled (const ImVec2 *points, const int num_points, ImU32 col)
IMGUI_API void AddDrawCmd ()
IMGUI_API void AddImage (ImTextureID user_texture_id, const ImVec2 &a, const ImVec2 &b, const ImVec2 &uv_a=ImVec2(0, 0), const ImVec2 &uv_b=ImVec2(1, 1), ImU32 col=0xFFFFFFFF)
IMGUI_API void AddImageQuad (ImTextureID user_texture_id, const ImVec2 &a, const ImVec2 &b, const ImVec2 &c, const ImVec2 &d, const ImVec2 &uv_a=ImVec2(0, 0), const ImVec2 &uv_b=ImVec2(1, 0), const ImVec2 &uv_c=ImVec2(1, 1), const ImVec2 &uv_d=ImVec2(0, 1), ImU32 col=0xFFFFFFFF)
IMGUI_API void AddImageRounded (ImTextureID user_texture_id, const ImVec2 &a, const ImVec2 &b, const ImVec2 &uv_a, const ImVec2 &uv_b, ImU32 col, float rounding, int rounding_corners=ImDrawCornerFlags_All)
IMGUI_API void AddLine (const ImVec2 &a, const ImVec2 &b, ImU32 col, float thickness=1.0f)
IMGUI_API void AddPolyline (const ImVec2 *points, const int num_points, ImU32 col, bool closed, float thickness)
IMGUI_API void AddQuad (const ImVec2 &a, const ImVec2 &b, const ImVec2 &c, const ImVec2 &d, ImU32 col, float thickness=1.0f)
IMGUI_API void AddQuadFilled (const ImVec2 &a, const ImVec2 &b, const ImVec2 &c, const ImVec2 &d, ImU32 col)
IMGUI_API void AddRect (const ImVec2 &a, const ImVec2 &b, ImU32 col, float rounding=0.0f, int rounding_corners_flags=ImDrawCornerFlags_All, float thickness=1.0f)
IMGUI_API void AddRectFilled (const ImVec2 &a, const ImVec2 &b, ImU32 col, float rounding=0.0f, int rounding_corners_flags=ImDrawCornerFlags_All)
IMGUI_API void AddRectFilledMultiColor (const ImVec2 &a, const ImVec2 &b, ImU32 col_upr_left, ImU32 col_upr_right, ImU32 col_bot_right, ImU32 col_bot_left)
IMGUI_API void AddText (const ImVec2 &pos, ImU32 col, const char *text_begin, const char *text_end=NULL)
IMGUI_API void AddText (const ImFont *font, float font_size, const ImVec2 &pos, ImU32 col, const char *text_begin, const char *text_end=NULL, float wrap_width=0.0f, const ImVec4 *cpu_fine_clip_rect=NULL)
IMGUI_API void AddTriangle (const ImVec2 &a, const ImVec2 &b, const ImVec2 &c, ImU32 col, float thickness=1.0f)
IMGUI_API void AddTriangleFilled (const ImVec2 &a, const ImVec2 &b, const ImVec2 &c, ImU32 col)
IMGUI_API void ChannelsMerge ()
IMGUI_API void ChannelsSetCurrent (int channel_index)
IMGUI_API void ChannelsSplit (int channels_count)
IMGUI_API void Clear ()
IMGUI_API void ClearFreeMemory ()
ImVec2 GetClipRectMax () const
ImVec2 GetClipRectMin () const
IMGUI_API void PathArcTo (const ImVec2 &centre, float radius, float a_min, float a_max, int num_segments=10)
IMGUI_API void PathArcToFast (const ImVec2 &centre, float radius, int a_min_of_12, int a_max_of_12)
IMGUI_API void PathBezierCurveTo (const ImVec2 &p1, const ImVec2 &p2, const ImVec2 &p3, int num_segments=0)
void PathClear ()
void PathFillConvex (ImU32 col)
void PathLineTo (const ImVec2 &pos)
void PathLineToMergeDuplicate (const ImVec2 &pos)
IMGUI_API void PathRect (const ImVec2 &rect_min, const ImVec2 &rect_max, float rounding=0.0f, int rounding_corners_flags=ImDrawCornerFlags_All)
void PathStroke (ImU32 col, bool closed, float thickness=1.0f)
IMGUI_API void PopClipRect ()
IMGUI_API void PopTextureID ()
IMGUI_API void PrimQuadUV (const ImVec2 &a, const ImVec2 &b, const ImVec2 &c, const ImVec2 &d, const ImVec2 &uv_a, const ImVec2 &uv_b, const ImVec2 &uv_c, const ImVec2 &uv_d, ImU32 col)
IMGUI_API void PrimRect (const ImVec2 &a, const ImVec2 &b, ImU32 col)
IMGUI_API void PrimRectUV (const ImVec2 &a, const ImVec2 &b, const ImVec2 &uv_a, const ImVec2 &uv_b, ImU32 col)
IMGUI_API void PrimReserve (int idx_count, int vtx_count)
void PrimVtx (const ImVec2 &pos, const ImVec2 &uv, ImU32 col)
void PrimWriteIdx (ImDrawIdx idx)
void PrimWriteVtx (const ImVec2 &pos, const ImVec2 &uv, ImU32 col)
IMGUI_API void PushClipRect (ImVec2 clip_rect_min, ImVec2 clip_rect_max, bool intersect_with_current_clip_rect=false)
IMGUI_API void PushClipRectFullScreen ()
IMGUI_API void PushTextureID (ImTextureID texture_id)
IMGUI_API void UpdateClipRect ()
IMGUI_API void UpdateTextureID ()
Public Attributes
ImVector< ImDrawChannel > _Channels
int _ChannelsCount
int _ChannelsCurrent
ImVector< ImVec4 > _ClipRectStack
const ImDrawListSharedData * _Data
ImDrawIdx * _IdxWritePtr
const char * _OwnerName
ImVector< ImVec2 > _Path
ImVector< ImTextureID > _TextureIdStack
unsigned int _VtxCurrentIdx
ImDrawVert * _VtxWritePtr
ImVector< ImDrawCmd > CmdBuffer
ImDrawListFlags Flags
ImVector< ImDrawIdx > IdxBuffer
ImVector< ImDrawVert > VtxBuffer
Constructor & Destructor Documentation
ImDrawList()
ImDrawList::ImDrawList (const ImDrawListSharedData * shared_data) inline
References NULL.
~ImDrawList()
ImDrawList::~ImDrawList () inline
Member Function Documentation
PushClipRect()
void ImDrawList::PushClipRect (ImVec2 clip_rect_min, ImVec2 clip_rect_max, bool intersect_with_current_clip_rect = false)
References ImMax(), ImVec4::w, ImVec2::x, ImVec4::x, ImVec2::y, ImVec4::y, and ImVec4::z.
Referenced by ImGui::PushClipRect(), and ImGui::RenderNavHighlight().
PushClipRectFullScreen()
void ImDrawList::PushClipRectFullScreen ()
References ImGui::PushClipRect().
Referenced by ImGui::AcceptDragDropPayload().
PopClipRect()
void ImDrawList::PopClipRect ()
References IM_ASSERT.
Referenced by ImGui::AcceptDragDropPayload(), ImGui::PopClipRect(), and ImGui::RenderNavHighlight().
PushTextureID()
void ImDrawList::PushTextureID (ImTextureID texture_id)
Referenced by ImGui::Begin().
PopTextureID()
void ImDrawList::PopTextureID ()
References IM_ASSERT.
Referenced by ImGui::PopFont().
GetClipRectMin()
ImVec2 ImDrawList::GetClipRectMin () const inline
References ImVector< T >::back(), ImVec4::x, and ImVec4::y.
GetClipRectMax()
ImVec2 ImDrawList::GetClipRectMax () const inline
References ImVector< T >::back(), ImVec4::w, and ImVec4::z.
AddLine()
void ImDrawList::AddLine (const ImVec2 & a, const ImVec2 & b, ImU32 col, float thickness = 1.0f)
References IM_COL32_A_MASK.
Referenced by ImGui::Begin(), ImGui::CloseButton(), ImGui::EndColumns(), ImGui::InputTextEx(), ImGui::PlotEx(), ImGui::Separator(), and ImGui::VerticalSeparator().
AddRect()
void ImDrawList::AddRect (const ImVec2 & a, const ImVec2 & b, ImU32 col, float rounding = 0.0f, int rounding_corners_flags = ImDrawCornerFlags_All, float thickness = 1.0f)
References IM_COL32_A_MASK, and ImDrawListFlags_AntiAliasedLines.
Referenced by ImGui::AcceptDragDropPayload(), ImGui::Begin(), ImGui::ColorButton(), ImGui::Image(), ImGui::RenderFrame(), ImGui::RenderFrameBorder(), ImGui::RenderNavHighlight(), and ImGui::ShowMetricsWindow().
AddRectFilled()
void ImDrawList::AddRectFilled (const ImVec2 & a, const ImVec2 & b, ImU32 col, float rounding = 0.0f, int rounding_corners_flags = ImDrawCornerFlags_All)
References IM_COL32_A_MASK.
Referenced by ImGui::Begin(), ImGui::ColorButton(), ImGui::ImageButton(), ImGui::InputTextEx(), ImGui::PlotEx(), ImGui::RenderColorRectWithAlphaCheckerboard(), ImGui::RenderFrame(), ImGui::RenderRectFilledRangeH(), ImGui::Scrollbar(), ImGui::SliderBehavior(), and ImGui::SplitterBehavior().
AddRectFilledMultiColor()
void ImDrawList::AddRectFilledMultiColor (const ImVec2 & a, const ImVec2 & b, ImU32 col_upr_left, ImU32 col_upr_right, ImU32 col_bot_right, ImU32 col_bot_left)
References IM_COL32_A_MASK.
Referenced by ImGui::ColorPicker4().
AddQuad()
void ImDrawList::AddQuad (const ImVec2 & a, const ImVec2 & b, const ImVec2 & c, const ImVec2 & d, ImU32 col, float thickness = 1.0f)
References IM_COL32_A_MASK.
AddQuadFilled()
void ImDrawList::AddQuadFilled (const ImVec2 & a, const ImVec2 & b, const ImVec2 & c, const ImVec2 & d, ImU32 col)
References IM_COL32_A_MASK.
AddTriangle()
void ImDrawList::AddTriangle (const ImVec2 & a, const ImVec2 & b, const ImVec2 & c, ImU32 col, float thickness = 1.0f)
References IM_COL32_A_MASK.
Referenced by ImGui::ColorPicker4().
AddTriangleFilled()
void ImDrawList::AddTriangleFilled (const ImVec2 & a, const ImVec2 & b, const ImVec2 & c, ImU32 col)
References IM_COL32_A_MASK.
Referenced by RenderArrow(), and ImGui::RenderTriangle().
AddCircle()
void ImDrawList::AddCircle (const ImVec2 & centre, float radius, ImU32 col, int num_segments = 12, float thickness = 1.0f)
References IM_COL32_A_MASK, and IM_PI.
Referenced by ImGui::ColorPicker4(), and ImGui::RadioButton().
AddCircleFilled()
void ImDrawList::AddCircleFilled (const ImVec2 & centre, float radius, ImU32 col, int num_segments = 12)
References IM_COL32_A_MASK, and IM_PI.
Referenced by ImGui::CloseButton(), ImGui::ColorPicker4(), ImGui::RadioButton(), and ImGui::RenderBullet().
AddText() [1/2]
void ImDrawList::AddText (const ImVec2 & pos, ImU32 col, const char * text_begin, const char * text_end = NULL)
References NULL.
Referenced by ImGui::InputTextEx(), ImGui::RenderText(), ImGui::RenderTextClipped(), and ImGui::RenderTextWrapped().
AddText() [2/2]
void ImDrawList::AddText (const ImFont * font, float font_size, const ImVec2 & pos, ImU32 col, const char * text_begin, const char * text_end = NULL, float wrap_width = 0.0f, const ImVec4 * cpu_fine_clip_rect = NULL)
References ImFont::ContainerAtlas, ImFont::FontSize, IM_ASSERT, IM_COL32_A_MASK, ImMax(), ImMin(), NULL, ImFont::RenderText(), ImFontAtlas::TexID, ImVec4::w, ImVec4::x, ImVec4::y, and ImVec4::z.
AddImage()
void ImDrawList::AddImage (ImTextureID user_texture_id, const ImVec2 & a, const ImVec2 & b, const ImVec2 & uv_a = ImVec2(0,0), const ImVec2 & uv_b = ImVec2(1,1), ImU32 col = 0xFFFFFFFF)
References IM_COL32_A_MASK.
Referenced by ImGui::Image(), and ImGui::ImageButton().
AddImageQuad()
void ImDrawList::AddImageQuad (ImTextureID user_texture_id, const ImVec2 & a, const ImVec2 & b, const ImVec2 & c, const ImVec2 & d, const ImVec2 & uv_a = ImVec2(0,0), const ImVec2 & uv_b = ImVec2(1,0), const ImVec2 & uv_c = ImVec2(1,1), const ImVec2 & uv_d = ImVec2(0,1), ImU32 col = 0xFFFFFFFF)
References IM_COL32_A_MASK.
AddImageRounded()
void ImDrawList::AddImageRounded (ImTextureID user_texture_id, const ImVec2 & a, const ImVec2 & b, const ImVec2 & uv_a, const ImVec2 & uv_b, ImU32 col, float rounding, int rounding_corners = ImDrawCornerFlags_All)
References IM_COL32_A_MASK, ImDrawCornerFlags_All, and ImGui::ShadeVertsLinearUV().
AddPolyline()
void ImDrawList::AddPolyline (const ImVec2 * points, const int num_points, ImU32 col, bool closed, float thickness)
References IM_COL32_A_MASK, ImDrawListFlags_AntiAliasedLines, ImInvLength(), ImVec2::x, and ImVec2::y.
Referenced by ImGui::ShowMetricsWindow().
AddConvexPolyFilled()
void ImDrawList::AddConvexPolyFilled (const ImVec2 * points, const int num_points, ImU32 col)
References IM_COL32_A_MASK, ImDrawListFlags_AntiAliasedFill, ImInvLength(), ImVec2::x, and ImVec2::y.
AddBezierCurve()
void ImDrawList::AddBezierCurve (const ImVec2 & pos0, const ImVec2 & cp0, const ImVec2 & cp1, const ImVec2 & pos1, ImU32 col, float thickness, int num_segments = 0)
References IM_COL32_A_MASK.
PathClear()
void ImDrawList::PathClear () inline
References ImVector< T >::resize().
PathLineTo()
void ImDrawList::PathLineTo (const ImVec2 & pos) inline
References ImVector< T >::push_back().
Referenced by ImGui::Begin(), ImGui::RenderCheckMark(), and ImGui::RenderRectFilledRangeH().
PathLineToMergeDuplicate()
void ImDrawList::PathLineToMergeDuplicate (const ImVec2 & pos) inline
References memcmp(), ImVector< T >::push_back(), and ImVector< T >::Size.
PathFillConvex()
void ImDrawList::PathFillConvex (ImU32 col) inline
References ImVector< T >::Data, and ImVector< T >::Size.
Referenced by ImGui::Begin(), and ImGui::RenderRectFilledRangeH().
PathStroke()
void ImDrawList::PathStroke (ImU32 col, bool closed, float thickness = 1.0f) inline
References ImVector< T >::Data, and ImVector< T >::Size.
Referenced by ImGui::ColorPicker4(), and ImGui::RenderCheckMark().
PathArcTo()
void ImDrawList::PathArcTo (const ImVec2 & centre, float radius, float a_min, float a_max, int num_segments = 10)
References ImVec2::x, and ImVec2::y.
Referenced by ImGui::ColorPicker4(), and ImGui::RenderRectFilledRangeH().
PathArcToFast()
void ImDrawList::PathArcToFast (const ImVec2 & centre, float radius, int a_min_of_12, int a_max_of_12)
References IM_ARRAYSIZE, ImVec2::x, and ImVec2::y.
Referenced by ImGui::Begin(), and ImGui::RenderRectFilledRangeH().
PathBezierCurveTo()
void ImDrawList::PathBezierCurveTo (const ImVec2 & p1, const ImVec2 & p2, const ImVec2 & p3, int num_segments = 0)
References PathBezierToCasteljau(), ImVec2::x, and ImVec2::y.
PathRect()
void ImDrawList::PathRect (const ImVec2 & rect_min, const ImVec2 & rect_max, float rounding = 0.0f, int rounding_corners_flags = ImDrawCornerFlags_All)
References ImDrawCornerFlags_Bot, ImDrawCornerFlags_BotLeft, ImDrawCornerFlags_BotRight, ImDrawCornerFlags_Left, ImDrawCornerFlags_Right, ImDrawCornerFlags_Top, ImDrawCornerFlags_TopLeft, ImDrawCornerFlags_TopRight, and ImMin().
ChannelsSplit()
void ImDrawList::ChannelsSplit (int channels_count)
References ImDrawCmd::ClipRect, IM_ASSERT, IM_PLACEMENT_NEW, memset(), and ImDrawCmd::TextureId.
Referenced by ImGui::BeginColumns().
ChannelsMerge()
void ImDrawList::ChannelsMerge ()
References ImVector< T >::back(), ImDrawChannel::CmdBuffer, ImVector< T >::Data, ImDrawCmd::ElemCount, ImDrawChannel::IdxBuffer, memcpy(), ImVector< T >::pop_back(), and ImVector< T >::Size.
Referenced by ImGui::EndColumns().
ChannelsSetCurrent()
void ImDrawList::ChannelsSetCurrent (int channel_index)
References IM_ASSERT, and memcpy().
Referenced by ImGui::NextColumn().
AddCallback()
void ImDrawList::AddCallback (ImDrawCallback callback, void * callback_data)
References ImDrawCmd::ElemCount, NULL, ImDrawCmd::UserCallback, and ImDrawCmd::UserCallbackData.
AddDrawCmd()
void ImDrawList::AddDrawCmd ()
References ImDrawCmd::ClipRect, GetCurrentClipRect, GetCurrentTextureId, IM_ASSERT, ImDrawCmd::TextureId, ImVec4::w, ImVec4::x, ImVec4::y, and ImVec4::z.
Clear()
void ImDrawList::Clear ()
References ImDrawListFlags_AntiAliasedFill, ImDrawListFlags_AntiAliasedLines, and NULL.
Referenced by ImGui::Begin().
ClearFreeMemory()
void ImDrawList::ClearFreeMemory ()
References memset(), and NULL.
PrimReserve()
void ImDrawList::PrimReserve (int idx_count, int vtx_count)
References ImDrawCmd::ElemCount.
Referenced by ImGui::ColorPicker4(), ImFont::RenderChar(), and ImFont::RenderText().
PrimRect()
void ImDrawList::PrimRect (const ImVec2 & a, const ImVec2 & b, ImU32 col)
PrimRectUV()
void ImDrawList::PrimRectUV (const ImVec2 & a, const ImVec2 & b, const ImVec2 & uv_a, const ImVec2 & uv_b, ImU32 col)
References ImVec2::x, and ImVec2::y.
Referenced by ImFont::RenderChar().
PrimQuadUV()
void ImDrawList::PrimQuadUV (const ImVec2 & a, const ImVec2 & b, const ImVec2 & c, const ImVec2 & d, const ImVec2 & uv_a, const ImVec2 & uv_b, const ImVec2 & uv_c, const ImVec2 & uv_d, ImU32 col)
PrimWriteVtx()
void ImDrawList::PrimWriteVtx (const ImVec2 & pos, const ImVec2 & uv, ImU32 col) inline
References ImDrawVert::col, ImDrawVert::pos, and ImDrawVert::uv.
PrimWriteIdx()
void ImDrawList::PrimWriteIdx (ImDrawIdx idx) inline
PrimVtx()
void ImDrawList::PrimVtx (const ImVec2 & pos, const ImVec2 & uv, ImU32 col) inline
Referenced by ImGui::ColorPicker4().
UpdateClipRect()
void ImDrawList::UpdateClipRect ()
References ImDrawCmd::ClipRect, ImDrawCmd::ElemCount, GetCurrentClipRect, GetCurrentTextureId, memcmp(), NULL, ImDrawCmd::TextureId, and ImDrawCmd::UserCallback.
UpdateTextureID()
void ImDrawList::UpdateTextureID ()
References ImDrawCmd::ClipRect, ImDrawCmd::ElemCount, GetCurrentClipRect, GetCurrentTextureId, memcmp(), NULL, ImDrawCmd::TextureId, and ImDrawCmd::UserCallback.
Member Data Documentation
CmdBuffer
ImVector<ImDrawCmd> ImDrawList::CmdBuffer
Referenced by AddDrawListToDrawData(), AuroraFW::GEngine::GLImGuiLoader::renderDrawLists(), ImFont::RenderText(), ImDrawData::ScaleClipRects(), and ImGui::ShowMetricsWindow().
IdxBuffer
ImVector<ImDrawIdx> ImDrawList::IdxBuffer
Referenced by AddDrawListToDrawData(), ImDrawData::DeIndexAllBuffers(), AuroraFW::GEngine::GLImGuiLoader::renderDrawLists(), ImFont::RenderText(), SetupDrawData(), and ImGui::ShowMetricsWindow().
VtxBuffer
ImVector<ImDrawVert> ImDrawList::VtxBuffer
Referenced by AddDrawListToDrawData(), ImGui::ColorPicker4(), ImDrawData::DeIndexAllBuffers(), AuroraFW::GEngine::GLImGuiLoader::renderDrawLists(), ImFont::RenderText(), SetupDrawData(), and ImGui::ShowMetricsWindow().
Flags
ImDrawListFlags ImDrawList::Flags
Referenced by ImGui::Begin(), and ImGui::ShowMetricsWindow().
_Data
const ImDrawListSharedData* ImDrawList::_Data
Referenced by ImGuiContext::ImGuiContext().
_OwnerName
const char* ImDrawList::_OwnerName
Referenced by ImGuiContext::ImGuiContext(), and ImGui::ShowMetricsWindow().
_VtxCurrentIdx
unsigned int ImDrawList::_VtxCurrentIdx
Referenced by AddDrawListToDrawData(), and ImFont::RenderText().
_VtxWritePtr
ImDrawVert* ImDrawList::_VtxWritePtr
Referenced by AddDrawListToDrawData(), and ImFont::RenderText().
_IdxWritePtr
ImDrawIdx* ImDrawList::_IdxWritePtr
Referenced by AddDrawListToDrawData(), and ImFont::RenderText().
_ClipRectStack
ImVector<ImVec4> ImDrawList::_ClipRectStack
Referenced by ImGui::PopClipRect(), and ImGui::PushClipRect().
_TextureIdStack
ImVector<ImTextureID> ImDrawList::_TextureIdStack
_Path
ImVector<ImVec2> ImDrawList::_Path
_ChannelsCurrent
int ImDrawList::_ChannelsCurrent
_ChannelsCount
int ImDrawList::_ChannelsCount
_Channels
ImVector<ImDrawChannel> ImDrawList::_Channels
The documentation for this struct was generated from the following files:
ImGui.h
Draw.cpp