Aurora Framework: Platform.h File Reference
Win32/Platform.h File Reference
Classes
struct _GLFWcursorWin32
struct _GLFWlibraryWin32
struct _GLFWmonitorWin32
struct _GLFWmutexWin32
struct _GLFWtimerWin32
struct _GLFWtlsWin32
struct _GLFWwindowWin32
struct CHANGEFILTERSTRUCT
struct DWM_BLURBEHIND
struct VkWin32SurfaceCreateInfoKHR
Macros
#define _glfw_dlclose(handle) FreeLibrary((HMODULE) handle)
#define _glfw_dlopen(name) LoadLibraryA(name)
#define _glfw_dlsym(handle, name) GetProcAddress((HMODULE) handle, name)
#define _GLFW_EGL_NATIVE_DISPLAY EGL_DEFAULT_DISPLAY
#define _GLFW_EGL_NATIVE_WINDOW ((EGLNativeWindowType) window->win32.handle)
#define _GLFW_PLATFORM_CURSOR_STATE _GLFWcursorWin32 win32
#define _GLFW_PLATFORM_LIBRARY_TIMER_STATE _GLFWtimerWin32 win32
#define _GLFW_PLATFORM_LIBRARY_WINDOW_STATE _GLFWlibraryWin32 win32
#define _GLFW_PLATFORM_MONITOR_STATE _GLFWmonitorWin32 win32
#define _GLFW_PLATFORM_MUTEX_STATE _GLFWmutexWin32 win32
#define _GLFW_PLATFORM_TLS_STATE _GLFWtlsWin32 win32
#define _GLFW_PLATFORM_WINDOW_STATE _GLFWwindowWin32 win32
#define _GLFW_WNDCLASSNAME L"GLFW30"
#define _WIN32_WINNT 0x0501
#define _WIN32_WINNT_WINBLUE 0x0602
#define ChangeWindowMessageFilterEx _glfw.win32.user32.ChangeWindowMessageFilterEx_
#define DIDFT_OPTIONAL 0x80000000
#define DirectInput8Create _glfw.win32.dinput8.Create
#define DIRECTINPUT_VERSION 0x0800
#define DISPLAY_DEVICE_ACTIVE 0x00000001
#define DWM_BB_BLURREGION 0x00000002
#define DWM_BB_ENABLE 0x00000001
#define DwmEnableBlurBehindWindow _glfw.win32.dwmapi.EnableBlurBehindWindow
#define DwmFlush _glfw.win32.dwmapi.Flush
#define DwmIsCompositionEnabled _glfw.win32.dwmapi.IsCompositionEnabled
#define EDS_ROTATEDMODE 0x00000004
#define GET_XBUTTON_WPARAM(w) (HIWORD(w))
#define GetDpiForMonitor _glfw.win32.shcore.GetDpiForMonitor_
#define IsWindows7OrGreater()
#define IsWindows8OrGreater()
#define IsWindows8Point1OrGreater()
#define IsWindowsVistaOrGreater()
#define MSGFLT_ALLOW 1
#define SetProcessDPIAware _glfw.win32.user32.SetProcessDPIAware_
#define SetProcessDpiAwareness _glfw.win32.shcore.SetProcessDpiAwareness_
#define timeGetTime _glfw.win32.winmm.GetTime
#define UNICODE
#define UNICODE_NOCHAR 0xFFFF
#define VC_EXTRALEAN
#define WIN32_LEAN_AND_MEAN
#define WINVER 0x0501
#define WM_COPYGLOBALDATA 0x0049
#define WM_DPICHANGED 0x02E0
#define WM_DWMCOMPOSITIONCHANGED 0x031E
#define WM_MOUSEHWHEEL 0x020E
#define WM_UNICHAR 0x0109
#define XINPUT_CAPS_WIRELESS 0x0002
#define XINPUT_DEVSUBTYPE_ARCADE_PAD 0x13
#define XINPUT_DEVSUBTYPE_ARCADE_STICK 0x03
#define XINPUT_DEVSUBTYPE_DANCE_PAD 0x05
#define XINPUT_DEVSUBTYPE_DRUM_KIT 0x08
#define XINPUT_DEVSUBTYPE_FLIGHT_STICK 0x04
#define XINPUT_DEVSUBTYPE_GUITAR 0x06
#define XINPUT_DEVSUBTYPE_WHEEL 0x02
#define XInputGetCapabilities _glfw.win32.xinput.GetCapabilities
#define XInputGetState _glfw.win32.xinput.GetState
#define XUSER_MAX_COUNT 4
Typedefs
typedef struct _GLFWcursorWin32 _GLFWcursorWin32
typedef struct _GLFWlibraryWin32 _GLFWlibraryWin32
typedef struct _GLFWmonitorWin32 _GLFWmonitorWin32
typedef struct _GLFWmutexWin32 _GLFWmutexWin32
typedef struct _GLFWtimerWin32 _GLFWtimerWin32
typedef struct _GLFWtlsWin32 _GLFWtlsWin32
typedef struct _GLFWwindowWin32 _GLFWwindowWin32
typedef BOOL(WINAPI * PFN_ChangeWindowMessageFilterEx) (HWND, UINT, DWORD, CHANGEFILTERSTRUCT *)
typedef HRESULT(WINAPI * PFN_DirectInput8Create) (HINSTANCE, DWORD, REFIID, LPVOID *, LPUNKNOWN)
typedef HRESULT(WINAPI * PFN_DwmEnableBlurBehindWindow) (HWND, const DWM_BLURBEHIND *)
typedef HRESULT(WINAPI * PFN_DwmFlush) (VOID)
typedef HRESULT(WINAPI * PFN_DwmIsCompositionEnabled) (BOOL *)
typedef HRESULT(WINAPI * PFN_GetDpiForMonitor) (HMONITOR, MONITOR_DPI_TYPE, UINT *, UINT *)
typedef BOOL(WINAPI * PFN_SetProcessDPIAware) (void)
typedef HRESULT(WINAPI * PFN_SetProcessDpiAwareness) (PROCESS_DPI_AWARENESS)
typedef DWORD(WINAPI * PFN_timeGetTime) (void)
typedef VkResult(APIENTRY * PFN_vkCreateWin32SurfaceKHR) (VkInstance, const VkWin32SurfaceCreateInfoKHR *, const VkAllocationCallbacks *, VkSurfaceKHR *)
typedef VkBool32(APIENTRY * PFN_vkGetPhysicalDeviceWin32PresentationSupportKHR) (VkPhysicalDevice, uint32_t)
typedef DWORD(WINAPI * PFN_XInputGetCapabilities) (DWORD, DWORD, XINPUT_CAPABILITIES *)
typedef DWORD(WINAPI * PFN_XInputGetState) (DWORD, XINPUT_STATE *)
typedef VkFlags VkWin32SurfaceCreateFlagsKHR
typedef struct VkWin32SurfaceCreateInfoKHR VkWin32SurfaceCreateInfoKHR
Enumerations
enum MONITOR_DPI_TYPE { MDT_EFFECTIVE_DPI = 0, MDT_ANGULAR_DPI = 1, MDT_RAW_DPI = 2, MDT_DEFAULT = MDT_EFFECTIVE_DPI }
enum PROCESS_DPI_AWARENESS { PROCESS_DPI_UNAWARE = 0, PROCESS_SYSTEM_DPI_AWARE = 1, PROCESS_PER_MONITOR_DPI_AWARE = 2 }
Functions
char * _glfwCreateUTF8FromWideStringWin32 (const WCHAR *source)
WCHAR * _glfwCreateWideStringFromUTF8Win32 (const char *source)
void _glfwGetMonitorContentScaleWin32 (HMONITOR handle, float *xscale, float *yscale)
void _glfwInitTimerWin32 (void)
void _glfwInputErrorWin32 (int error, const char *description)
GLFWbool _glfwIsCompositionEnabledWin32 (void)
void _glfwPollMonitorsWin32 (void)
GLFWbool _glfwRegisterWindowClassWin32 (void)
void _glfwRestoreVideoModeWin32 (_GLFWmonitor *monitor)
void _glfwSetVideoModeWin32 (_GLFWmonitor *monitor, const GLFWvidmode *desired)
void _glfwUnregisterWindowClassWin32 (void)
void _glfwUpdateKeyNamesWin32 (void)
BOOL IsWindowsVersionOrGreater (WORD major, WORD minor, WORD sp)
Macro Definition Documentation
VC_EXTRALEAN
#define VC_EXTRALEAN
WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
UNICODE
#define UNICODE
WINVER
#define WINVER 0x0501
_WIN32_WINNT
#define _WIN32_WINNT 0x0501
DIRECTINPUT_VERSION
#define DIRECTINPUT_VERSION 0x0800
Referenced by _glfwInitJoysticksWin32().
WM_MOUSEHWHEEL
#define WM_MOUSEHWHEEL 0x020E
Referenced by windowProc().
WM_DWMCOMPOSITIONCHANGED
#define WM_DWMCOMPOSITIONCHANGED 0x031E
Referenced by windowProc().
WM_COPYGLOBALDATA
#define WM_COPYGLOBALDATA 0x0049
Referenced by createNativeWindow().
WM_UNICHAR
#define WM_UNICHAR 0x0109
Referenced by windowProc().
UNICODE_NOCHAR
#define UNICODE_NOCHAR 0xFFFF
Referenced by windowProc().
WM_DPICHANGED
#define WM_DPICHANGED 0x02E0
Referenced by windowProc().
GET_XBUTTON_WPARAM
#define GET_XBUTTON_WPARAM (w) (HIWORD(w))
Referenced by windowProc().
EDS_ROTATEDMODE
#define EDS_ROTATEDMODE 0x00000004
Referenced by _glfwPlatformGetMonitorPos().
DISPLAY_DEVICE_ACTIVE
#define DISPLAY_DEVICE_ACTIVE 0x00000001
Referenced by _glfwPollMonitorsWin32().
_WIN32_WINNT_WINBLUE
#define _WIN32_WINNT_WINBLUE 0x0602
MSGFLT_ALLOW
#define MSGFLT_ALLOW 1
Referenced by createNativeWindow().
DWM_BB_ENABLE
#define DWM_BB_ENABLE 0x00000001
Referenced by updateFramebufferTransparency().
DWM_BB_BLURREGION
#define DWM_BB_BLURREGION 0x00000002
Referenced by updateFramebufferTransparency().
IsWindowsVistaOrGreater
#define IsWindowsVistaOrGreater ()
Value:
IsWindowsVersionOrGreater(HIBYTE(_WIN32_WINNT_VISTA),      \
                              LOBYTE(_WIN32_WINNT_VISTA), 0)
Referenced by _glfwIsCompositionEnabledWin32(), _glfwPlatformInit(), and updateFramebufferTransparency().
IsWindows7OrGreater
#define IsWindows7OrGreater ()
Value:
IsWindowsVersionOrGreater(HIBYTE(_WIN32_WINNT_WIN7),       \
                              LOBYTE(_WIN32_WINNT_WIN7), 0)
Referenced by createNativeWindow().
IsWindows8OrGreater
#define IsWindows8OrGreater ()
Value:
IsWindowsVersionOrGreater(HIBYTE(_WIN32_WINNT_WIN8),       \
                              LOBYTE(_WIN32_WINNT_WIN8), 0)
IsWindows8Point1OrGreater
#define IsWindows8Point1OrGreater ()
Value:
IsWindowsVersionOrGreater(HIBYTE(_WIN32_WINNT_WINBLUE),    \
                              LOBYTE(_WIN32_WINNT_WINBLUE), 0)
Referenced by _glfwGetMonitorContentScaleWin32(), _glfwPlatformInit(), and createMonitor().
XINPUT_CAPS_WIRELESS
#define XINPUT_CAPS_WIRELESS 0x0002
Referenced by getDeviceDescription().
XINPUT_DEVSUBTYPE_WHEEL
#define XINPUT_DEVSUBTYPE_WHEEL 0x02
Referenced by getDeviceDescription().
XINPUT_DEVSUBTYPE_ARCADE_STICK
#define XINPUT_DEVSUBTYPE_ARCADE_STICK 0x03
Referenced by getDeviceDescription().
XINPUT_DEVSUBTYPE_FLIGHT_STICK
#define XINPUT_DEVSUBTYPE_FLIGHT_STICK 0x04
Referenced by getDeviceDescription().
XINPUT_DEVSUBTYPE_DANCE_PAD
#define XINPUT_DEVSUBTYPE_DANCE_PAD 0x05
Referenced by getDeviceDescription().
XINPUT_DEVSUBTYPE_GUITAR
#define XINPUT_DEVSUBTYPE_GUITAR 0x06
Referenced by getDeviceDescription().
XINPUT_DEVSUBTYPE_DRUM_KIT
#define XINPUT_DEVSUBTYPE_DRUM_KIT 0x08
Referenced by getDeviceDescription().
XINPUT_DEVSUBTYPE_ARCADE_PAD
#define XINPUT_DEVSUBTYPE_ARCADE_PAD 0x13
XUSER_MAX_COUNT
#define XUSER_MAX_COUNT 4
Referenced by _glfwDetectJoystickConnectionWin32().
DIDFT_OPTIONAL
#define DIDFT_OPTIONAL 0x80000000
timeGetTime
#define timeGetTime _glfw.win32.winmm.GetTime
Referenced by _glfwPlatformGetTimerValue().
XInputGetCapabilities
#define XInputGetCapabilities _glfw.win32.xinput.GetCapabilities
Referenced by _glfwDetectJoystickConnectionWin32().
XInputGetState
#define XInputGetState _glfw.win32.xinput.GetState
Referenced by _glfwPlatformPollJoystick().
DirectInput8Create
#define DirectInput8Create _glfw.win32.dinput8.Create
Referenced by _glfwInitJoysticksWin32().
SetProcessDPIAware
#define SetProcessDPIAware _glfw.win32.user32.SetProcessDPIAware_
Referenced by _glfwPlatformInit().
ChangeWindowMessageFilterEx
#define ChangeWindowMessageFilterEx _glfw.win32.user32.ChangeWindowMessageFilterEx_
Referenced by createNativeWindow().
DwmIsCompositionEnabled
#define DwmIsCompositionEnabled _glfw.win32.dwmapi.IsCompositionEnabled
Referenced by _glfwIsCompositionEnabledWin32().
DwmFlush
#define DwmFlush _glfw.win32.dwmapi.Flush
Referenced by swapBuffersWGL().
DwmEnableBlurBehindWindow
#define DwmEnableBlurBehindWindow _glfw.win32.dwmapi.EnableBlurBehindWindow
Referenced by updateFramebufferTransparency().
SetProcessDpiAwareness
#define SetProcessDpiAwareness _glfw.win32.shcore.SetProcessDpiAwareness_
Referenced by _glfwPlatformInit().
GetDpiForMonitor
#define GetDpiForMonitor _glfw.win32.shcore.GetDpiForMonitor_
Referenced by _glfwGetMonitorContentScaleWin32().
_GLFW_WNDCLASSNAME
#define _GLFW_WNDCLASSNAME L"GLFW30"
Referenced by _glfwRegisterWindowClassWin32(), _glfwUnregisterWindowClassWin32(), createHelperWindow(), and createNativeWindow().
_glfw_dlopen
#define _glfw_dlopen (name) LoadLibraryA(name)
_glfw_dlclose
#define _glfw_dlclose (handle) FreeLibrary((HMODULE) handle)
_glfw_dlsym
#define _glfw_dlsym (handle, name) GetProcAddress((HMODULE) handle, name)
_GLFW_EGL_NATIVE_WINDOW
#define _GLFW_EGL_NATIVE_WINDOW ((EGLNativeWindowType) window->win32.handle)
_GLFW_EGL_NATIVE_DISPLAY
#define _GLFW_EGL_NATIVE_DISPLAY EGL_DEFAULT_DISPLAY
_GLFW_PLATFORM_WINDOW_STATE
#define _GLFW_PLATFORM_WINDOW_STATE _GLFWwindowWin32 win32
_GLFW_PLATFORM_LIBRARY_WINDOW_STATE
#define _GLFW_PLATFORM_LIBRARY_WINDOW_STATE _GLFWlibraryWin32 win32
_GLFW_PLATFORM_LIBRARY_TIMER_STATE
#define _GLFW_PLATFORM_LIBRARY_TIMER_STATE _GLFWtimerWin32 win32
_GLFW_PLATFORM_MONITOR_STATE
#define _GLFW_PLATFORM_MONITOR_STATE _GLFWmonitorWin32 win32
_GLFW_PLATFORM_CURSOR_STATE
#define _GLFW_PLATFORM_CURSOR_STATE _GLFWcursorWin32 win32
_GLFW_PLATFORM_TLS_STATE
#define _GLFW_PLATFORM_TLS_STATE _GLFWtlsWin32 win32
_GLFW_PLATFORM_MUTEX_STATE
#define _GLFW_PLATFORM_MUTEX_STATE _GLFWmutexWin32 win32
Typedef Documentation
PFN_timeGetTime
typedef DWORD(WINAPI * PFN_timeGetTime) (void)
PFN_XInputGetCapabilities
typedef DWORD(WINAPI * PFN_XInputGetCapabilities) (DWORD, DWORD, XINPUT_CAPABILITIES *)
PFN_XInputGetState
typedef DWORD(WINAPI * PFN_XInputGetState) (DWORD, XINPUT_STATE *)
PFN_DirectInput8Create
typedef HRESULT(WINAPI * PFN_DirectInput8Create) (HINSTANCE, DWORD, REFIID, LPVOID *, LPUNKNOWN)
PFN_SetProcessDPIAware
typedef BOOL(WINAPI * PFN_SetProcessDPIAware) (void)
PFN_ChangeWindowMessageFilterEx
typedef BOOL(WINAPI * PFN_ChangeWindowMessageFilterEx) (HWND, UINT, DWORD, CHANGEFILTERSTRUCT *)
PFN_DwmIsCompositionEnabled
typedef HRESULT(WINAPI * PFN_DwmIsCompositionEnabled) (BOOL *)
PFN_DwmFlush
typedef HRESULT(WINAPI * PFN_DwmFlush) (VOID)
PFN_DwmEnableBlurBehindWindow
typedef HRESULT(WINAPI * PFN_DwmEnableBlurBehindWindow) (HWND, const DWM_BLURBEHIND *)
PFN_SetProcessDpiAwareness
typedef HRESULT(WINAPI * PFN_SetProcessDpiAwareness) (PROCESS_DPI_AWARENESS)
PFN_GetDpiForMonitor
typedef HRESULT(WINAPI * PFN_GetDpiForMonitor) (HMONITOR, MONITOR_DPI_TYPE, UINT *, UINT *)
VkWin32SurfaceCreateFlagsKHR
typedef VkFlags VkWin32SurfaceCreateFlagsKHR
VkWin32SurfaceCreateInfoKHR
typedef struct VkWin32SurfaceCreateInfoKHR VkWin32SurfaceCreateInfoKHR
PFN_vkCreateWin32SurfaceKHR
typedef VkResult(APIENTRY * PFN_vkCreateWin32SurfaceKHR) (VkInstance, const VkWin32SurfaceCreateInfoKHR *, const VkAllocationCallbacks *, VkSurfaceKHR *)
PFN_vkGetPhysicalDeviceWin32PresentationSupportKHR
typedef VkBool32(APIENTRY * PFN_vkGetPhysicalDeviceWin32PresentationSupportKHR) (VkPhysicalDevice, uint32_t)
_GLFWwindowWin32
typedef struct _GLFWwindowWin32 _GLFWwindowWin32
_GLFWlibraryWin32
typedef struct _GLFWlibraryWin32 _GLFWlibraryWin32
_GLFWmonitorWin32
typedef struct _GLFWmonitorWin32 _GLFWmonitorWin32
_GLFWcursorWin32
typedef struct _GLFWcursorWin32 _GLFWcursorWin32
_GLFWtimerWin32
typedef struct _GLFWtimerWin32 _GLFWtimerWin32
_GLFWtlsWin32
typedef struct _GLFWtlsWin32 _GLFWtlsWin32
_GLFWmutexWin32
typedef struct _GLFWmutexWin32 _GLFWmutexWin32
Enumeration Type Documentation
PROCESS_DPI_AWARENESS
enum PROCESS_DPI_AWARENESS
Enumerator
PROCESS_DPI_UNAWARE
PROCESS_SYSTEM_DPI_AWARE
PROCESS_PER_MONITOR_DPI_AWARE
MONITOR_DPI_TYPE
enum MONITOR_DPI_TYPE
Enumerator
MDT_EFFECTIVE_DPI
MDT_ANGULAR_DPI
MDT_RAW_DPI
MDT_DEFAULT
Function Documentation
IsWindowsVersionOrGreater()
BOOL IsWindowsVersionOrGreater (WORD major, WORD minor, WORD sp)
_glfwRegisterWindowClassWin32()
GLFWbool _glfwRegisterWindowClassWin32 (void)
References _GLFW_WNDCLASSNAME, _glfwInputErrorWin32(), GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, NULL, and windowProc().
Referenced by _glfwPlatformInit().
_glfwUnregisterWindowClassWin32()
void _glfwUnregisterWindowClassWin32 (void)
References _GLFW_WNDCLASSNAME, and NULL.
Referenced by _glfwPlatformTerminate().
_glfwIsCompositionEnabledWin32()
GLFWbool _glfwIsCompositionEnabledWin32 (void)
References DwmIsCompositionEnabled, and IsWindowsVistaOrGreater.
Referenced by _glfwPlatformFramebufferTransparent(), swapBuffersWGL(), swapIntervalWGL(), and updateFramebufferTransparency().
_glfwCreateWideStringFromUTF8Win32()
WCHAR* _glfwCreateWideStringFromUTF8Win32 (const char * source)
References _glfwInputErrorWin32(), GLFW_PLATFORM_ERROR, NULL, and source.
Referenced by _glfwPlatformSetWindowTitle(), and createNativeWindow().
_glfwCreateUTF8FromWideStringWin32()
char* _glfwCreateUTF8FromWideStringWin32 (const WCHAR * source)
References _glfwInputErrorWin32(), GLFW_PLATFORM_ERROR, NULL, and source.
Referenced by _glfwPlatformGetClipboardString(), createMonitor(), and windowProc().
_glfwInputErrorWin32()
void _glfwInputErrorWin32 (int error, const char * description)
References _GLFW_MESSAGE_SIZE, _glfwInputError(), setup::description, and NULL.
Referenced by _glfwCreateContextWGL(), _glfwCreateUTF8FromWideStringWin32(), _glfwCreateWideStringFromUTF8Win32(), _glfwInitWGL(), _glfwPlatformCreateStandardCursor(), _glfwPlatformCreateTls(), _glfwPlatformGetClipboardString(), _glfwPlatformSetClipboardString(), _glfwPlatformSetCursorMode(), _glfwRegisterWindowClassWin32(), createHelperWindow(), createIcon(), createNativeWindow(), getPixelFormatAttrib(), loadLibraries(), and makeContextCurrentWGL().
_glfwUpdateKeyNamesWin32()
void _glfwUpdateKeyNamesWin32 (void)
References _glfw, GLFW_KEY_KP_0, GLFW_KEY_KP_ADD, GLFW_KEY_LAST, GLFW_KEY_SPACE, memset(), and NULL.
Referenced by _glfwPlatformInit(), and windowProc().
_glfwInitTimerWin32()
void _glfwInitTimerWin32 (void)
References _glfw, GLFW_FALSE, GLFW_TRUE, and _GLFWlibrary::timer.
Referenced by _glfwPlatformInit().
_glfwPollMonitorsWin32()
void _glfwPollMonitorsWin32 (void)
References _glfw, _GLFW_INSERT_FIRST, _GLFW_INSERT_LAST, _glfwInputMonitor(), createMonitor(), display(), DISPLAY_DEVICE_ACTIVE, GLFW_CONNECTED, GLFW_DISCONNECTED, memcpy(), _GLFWlibrary::monitorCount, _GLFWlibrary::monitors, and NULL.
Referenced by _glfwPlatformInit(), and windowProc().
_glfwSetVideoModeWin32()
void _glfwSetVideoModeWin32 (_GLFWmonitor * monitor, const GLFWvidmode * desired)
References _glfwChooseVideoMode(), _glfwCompareVideoModes(), _glfwInputError(), _glfwPlatformGetVideoMode(), GLFWvidmode::blueBits, setup::description, GLFW_PLATFORM_ERROR, GLFW_TRUE, GLFWvidmode::greenBits, GLFWvidmode::height, NULL, GLFWvidmode::redBits, GLFWvidmode::refreshRate, and GLFWvidmode::width.
Referenced by acquireMonitor().
_glfwRestoreVideoModeWin32()
void _glfwRestoreVideoModeWin32 (_GLFWmonitor * monitor)
References GLFW_FALSE, and NULL.
Referenced by releaseMonitor().
_glfwGetMonitorContentScaleWin32()
void _glfwGetMonitorContentScaleWin32 (HMONITOR handle, float * xscale, float * yscale)
References GetDpiForMonitor, IsWindows8Point1OrGreater, MDT_EFFECTIVE_DPI, and NULL.
Referenced by _glfwPlatformGetMonitorContentScale(), and _glfwPlatformGetWindowContentScale().