Aurora Framework: SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator > Class Template Reference
SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator > Class Template Reference
A helper class for parsing with validation.
Public Types
typedef InputStream::Ch Ch
typedef SchemaDocumentType::PointerType PointerType
typedef GenericValue< SourceEncoding, StackAllocator > ValueType
Public Member Functions
SchemaValidatingReader (InputStream &is, const SchemaDocumentType &sd)
Constructor.
const ValueType & GetError () const
const PointerType & GetInvalidDocumentPointer () const
const Ch * GetInvalidSchemaKeyword () const
const PointerType & GetInvalidSchemaPointer () const
const ParseResult & GetParseResult () const
bool IsValid () const
template<typename Handler >
bool operator() (Handler &handler)
Detailed Description
template<unsigned parseFlags, typename InputStream, typename SourceEncoding, typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator>
class SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >
A helper class for parsing with validation.
This helper class is a functor, designed as a parameter of GenericDocument::Populate().
Template Parameters
parseFlags Combination of ParseFlag.
InputStream Type of input stream, implementing Stream concept.
SourceEncoding Encoding of the input stream.
SchemaDocumentType Type of schema document.
StackAllocator Allocator type for stack.
Member Typedef Documentation
PointerType
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> typedef SchemaDocumentType::PointerType SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::PointerType
Ch
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> typedef InputStream::Ch SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::Ch
ValueType
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> typedef GenericValue<SourceEncoding, StackAllocator> SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::ValueType
Constructor & Destructor Documentation
SchemaValidatingReader()
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::SchemaValidatingReader (InputStream & is, const SchemaDocumentType & sd) inline
Constructor.
Parameters
is Input stream.
sd Schema document.
Member Function Documentation
operator()()
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> template<typename Handler > bool SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::operator() (Handler & handler) inline
References GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetError(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidDocumentPointer(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidSchemaKeyword(), GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::GetInvalidSchemaPointer(), and GenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >::IsValid().
GetParseResult()
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> const ParseResult& SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::GetParseResult () const inline
IsValid()
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> bool SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::IsValid () const inline
GetInvalidSchemaPointer()
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> const PointerType& SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::GetInvalidSchemaPointer () const inline
GetInvalidSchemaKeyword()
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> const Ch* SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::GetInvalidSchemaKeyword () const inline
GetInvalidDocumentPointer()
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> const PointerType& SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::GetInvalidDocumentPointer () const inline
GetError()
template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator> const ValueType& SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::GetError () const inline
The documentation for this class was generated from the following file:
schema.h