Aurora Framework: avr.c File Reference
avr.c File Reference
Classes
struct AVR_HEADER
Macros
#define AVR_HDR_SIZE 128
#define SFE_AVR_X 666
#define TWOBIT_MARKER (MAKE_MARKER ('2', 'B', 'I', 'T'))
Functions
static int avr_close (SF_PRIVATE *psf)
int avr_open (SF_PRIVATE *psf)
static int avr_read_header (SF_PRIVATE *psf)
static int avr_write_header (SF_PRIVATE *psf, int calc_length)
Macro Definition Documentation
TWOBIT_MARKER
#define TWOBIT_MARKER (MAKE_MARKER ('2', 'B', 'I', 'T'))
Referenced by avr_read_header(), and avr_write_header().
AVR_HDR_SIZE
#define AVR_HDR_SIZE 128
Referenced by avr_read_header().
SFE_AVR_X
#define SFE_AVR_X 666
Referenced by avr_read_header().
Function Documentation
avr_close()
static int avr_close (SF_PRIVATE * psf) static
References avr_write_header(), sf_private_tag::file, and PSF_FILE::mode.
Referenced by avr_open().
avr_read_header()
static int avr_read_header (SF_PRIVATE * psf) static
References AVR_HDR_SIZE, sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::endian, AVR_HEADER::ext, sf_private_tag::filelength, sf_private_tag::fileoffset, AVR_HEADER::frames, AVR_HEADER::lbeg, AVR_HEADER::lend, AVR_HEADER::loop, AVR_HEADER::marker, memset(), AVR_HEADER::midi, AVR_HEADER::mono, AVR_HEADER::name, psf_binheader_readf(), psf_ftell(), psf_log_printf(), AVR_HEADER::res1, AVR_HEADER::res2, AVR_HEADER::res3, AVR_HEADER::rez, sf_private_tag::sf, SFE_AVR_X, AVR_HEADER::sign, AVR_HEADER::srate, TWOBIT_MARKER, and AVR_HEADER::user.
Referenced by avr_open().
avr_write_header()
static int avr_write_header (SF_PRIVATE * psf, int calc_length) static
References BHW2, BHW4, BHWm, BHWz, sf_private_tag::bytewidth, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::error, sf_private_tag::filelength, sf_private_tag::header, sf_private_tag::indx, sf_private_tag::is_pipe, sf_private_tag::pipeoffset, psf_binheader_writef(), psf_fseek(), psf_ftell(), psf_fwrite(), psf_get_filelen(), sf_private_tag::ptr, sf_private_tag::sf, SF_CODEC, and TWOBIT_MARKER.
Referenced by avr_close(), and avr_open().
avr_open()
int avr_open (SF_PRIVATE * psf)
References avr_close(), avr_read_header(), avr_write_header(), sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::container_close, sf_private_tag::endian, sf_private_tag::error, sf_private_tag::file, sf_private_tag::filelength, PSF_FILE::mode, pcm_init(), sf_private_tag::sf, SF_CONTAINER, SFE_BAD_OPEN_FORMAT, and sf_private_tag::write_header.
Referenced by psf_open_file().