Aurora Framework: ircam.c File Reference
ircam.c File Reference
Macros
#define IRCAM_02B_MARKER (MAKE_MARKER (0x64, 0xA3, 0x02, 0x00))
#define IRCAM_03L_MARKER (MAKE_MARKER (0x64, 0xA3, 0x03, 0x00))
#define IRCAM_BE_MARKER (MAKE_MARKER (0x64, 0xA3, 0x00, 0x00))
#define IRCAM_BE_MASK (MAKE_MARKER (0xFF, 0xFF, 0x00, 0xFF))
#define IRCAM_DATA_OFFSET (1024)
#define IRCAM_LE_MARKER (MAKE_MARKER (0x00, 0x00, 0xA3, 0x64))
#define IRCAM_LE_MASK (MAKE_MARKER (0xFF, 0x00, 0xFF, 0xFF))
Enumerations
enum {
IRCAM_PCM_16 = 0x00002, IRCAM_FLOAT = 0x00004, IRCAM_ALAW = 0x10001, IRCAM_ULAW = 0x20001,
IRCAM_PCM_32 = 0x40004
}
Functions
static int get_encoding (int subformat)
static const char * get_encoding_str (int encoding)
static int ircam_close (SF_PRIVATE *psf)
int ircam_open (SF_PRIVATE *psf)
static int ircam_read_header (SF_PRIVATE *psf)
static int ircam_write_header (SF_PRIVATE *psf, int calc_length)
static int ircam_write_header (SF_PRIVATE *psf, int UNUSED(calc_length))
Macro Definition Documentation
IRCAM_BE_MASK
#define IRCAM_BE_MASK (MAKE_MARKER (0xFF, 0xFF, 0x00, 0xFF))
Referenced by ircam_read_header().
IRCAM_BE_MARKER
#define IRCAM_BE_MARKER (MAKE_MARKER (0x64, 0xA3, 0x00, 0x00))
Referenced by ircam_read_header().
IRCAM_LE_MASK
#define IRCAM_LE_MASK (MAKE_MARKER (0xFF, 0x00, 0xFF, 0xFF))
Referenced by ircam_read_header().
IRCAM_LE_MARKER
#define IRCAM_LE_MARKER (MAKE_MARKER (0x00, 0x00, 0xA3, 0x64))
Referenced by ircam_read_header().
IRCAM_02B_MARKER
#define IRCAM_02B_MARKER (MAKE_MARKER (0x64, 0xA3, 0x02, 0x00))
Referenced by ircam_write_header().
IRCAM_03L_MARKER
#define IRCAM_03L_MARKER (MAKE_MARKER (0x64, 0xA3, 0x03, 0x00))
Referenced by ircam_write_header().
IRCAM_DATA_OFFSET
#define IRCAM_DATA_OFFSET (1024)
Referenced by ircam_open(), ircam_read_header(), and ircam_write_header().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
IRCAM_PCM_16
IRCAM_FLOAT
IRCAM_ALAW
IRCAM_ULAW
IRCAM_PCM_32
Function Documentation
ircam_close()
static int ircam_close (SF_PRIVATE * psf) static
References psf_log_printf().
Referenced by ircam_open().
ircam_write_header() [1/2]
static int ircam_write_header (SF_PRIVATE * psf, int calc_length) static
Referenced by ircam_open().
ircam_read_header()
static int ircam_read_header (SF_PRIVATE * psf) static
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::endian, sf_private_tag::filelength, get_encoding_str(), IRCAM_ALAW, IRCAM_BE_MARKER, IRCAM_BE_MASK, IRCAM_DATA_OFFSET, IRCAM_FLOAT, IRCAM_LE_MARKER, IRCAM_LE_MASK, IRCAM_PCM_16, IRCAM_PCM_32, IRCAM_ULAW, psf_binheader_readf(), psf_log_printf(), sf_private_tag::sf, SF_MAX_CHANNELS, SFE_IRCAM_BAD_CHANNELS, SFE_IRCAM_NO_MARKER, SFE_IRCAM_UNKNOWN_FORMAT, and SFE_NO_ERROR.
Referenced by ircam_open().
get_encoding()
static int get_encoding (int subformat) static
References IRCAM_ALAW, IRCAM_FLOAT, IRCAM_PCM_16, IRCAM_PCM_32, and IRCAM_ULAW.
Referenced by ircam_write_header().
get_encoding_str()
static const char * get_encoding_str (int encoding) static
References IRCAM_ALAW, IRCAM_FLOAT, IRCAM_PCM_16, IRCAM_PCM_32, and IRCAM_ULAW.
Referenced by ircam_read_header().
ircam_open()
int ircam_open (SF_PRIVATE * psf)
References alaw_init(), sf_private_tag::container_close, sf_private_tag::dataoffset, sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, float32_init(), ircam_close(), IRCAM_DATA_OFFSET, ircam_read_header(), ircam_write_header(), PSF_FILE::mode, pcm_init(), sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SF_ENDIAN, SFE_BAD_OPEN_FORMAT, SFE_NO_ERROR, ulaw_init(), and sf_private_tag::write_header.
Referenced by psf_open_file().
ircam_write_header() [2/2]
static int ircam_write_header (SF_PRIVATE * psf, int UNUSEDcalc_length) static
References BHW4, BHWf, BHWm, BHWz, sf_private_tag::endian, sf_private_tag::error, get_encoding(), sf_private_tag::header, sf_private_tag::indx, IRCAM_02B_MARKER, IRCAM_03L_MARKER, IRCAM_DATA_OFFSET, sf_private_tag::is_pipe, sf_private_tag::pipeoffset, psf_binheader_writef(), psf_fseek(), psf_ftell(), psf_fwrite(), sf_private_tag::ptr, sf_private_tag::sf, SF_CODEC, and SFE_BAD_OPEN_FORMAT.