Aurora Framework: AuroraFW::GUI::Button Class Reference
AuroraFW::GUI::Button Class Reference
Public Member Functions
Button (Widget *, const std::string &)
Button (const Button &x)=delete
bool isFlat () const
Button & operator= (const Button &x)=delete
void setFlat (const bool &)
Private Member Functions
void _show ()
template<typename R , typename... Args>
void connect (const std::string &, R(*)(Args...), void *=AFW_NULLPTR)
template<typename R , typename... Args>
void connect (const std::string &signal_, std::function< R(Args...)> callback, void *data=AFW_NULLPTR)
void destroy ()
AFW_FORCE_INLINE GtkWidget * getNativeGtkWidget () const
void hide ()
std::string name () const
Widget * parent () const
void setName (const std::string &)
void setParent (Widget *)
virtual void show ()
Private Attributes
GtkWidget * _widget
Constructor & Destructor Documentation
Button() [1/2]
AuroraFW::GUI::Button::Button (Widget * parent, const std::string & name)
References AuroraFW::GUI::Widget::_widget, AuroraFW::GUI::Widget::name(), AuroraFW::GUI::Widget::parent(), and AuroraFW::GUI::Widget::setParent().
Button() [2/2]
AuroraFW::GUI::Button::Button (const Button & x) delete
Member Function Documentation
operator=()
Button& AuroraFW::GUI::Button::operator= (const Button & x) delete
setFlat()
void AuroraFW::GUI::Button::setFlat (const bool &)
isFlat()
bool AuroraFW::GUI::Button::isFlat () const
The documentation for this class was generated from the following files:
Button.h
Button.cpp