Aurora Framework: rpe.c File Reference
rpe.c File Reference
Macros
#define STEP(i, H) (e [k + i] * (int32_t) H)
#define STEP(m, i)
Functions
static void APCM_inverse_quantization (register int16_t *xMc, int16_t mant, int16_t expon, register int16_t *xMp)
static void APCM_quantization (int16_t *xM, int16_t *xMc, int16_t *mant_out, int16_t *expon_out, int16_t *xmaxc_out)
static void APCM_quantization_xmaxc_to_exp_mant (int16_t xmaxc, int16_t *expon_out, int16_t *mant_out)
void Gsm_RPE_Decoding (int16_t xmaxcr, int16_t Mcr, int16_t *xMcr, int16_t *erp)
void Gsm_RPE_Encoding (int16_t *e, int16_t *xmaxc, int16_t *Mc, int16_t *xMc)
static void RPE_grid_positioning (int16_t Mc, register int16_t *xMp, register int16_t *ep)
static void RPE_grid_selection (int16_t *x, int16_t *xM, int16_t *Mc_out)
static void Weighting_filter (register int16_t *e, int16_t *x)
Macro Definition Documentation
STEP [1/2]
#define STEP (i, H) (e [k + i] * (int32_t) H)
Referenced by RPE_grid_selection(), and Weighting_filter().
STEP [2/2]
#define STEP (m, i)
Value:
L_temp = SASR_W (x [m + 3 * i], 2) ;    \
                    L_result += L_temp * L_temp ;
Function Documentation
Weighting_filter()
static void Weighting_filter (register int16_t * e, int16_t * x) static
References MAX_WORD, MIN_WORD, SASR_L(), and STEP.
Referenced by Gsm_RPE_Encoding().
RPE_grid_selection()
static void RPE_grid_selection (int16_t * x, int16_t * xM, int16_t * Mc_out) static
References STEP.
Referenced by Gsm_RPE_Encoding().
APCM_quantization_xmaxc_to_exp_mant()
static void APCM_quantization_xmaxc_to_exp_mant (int16_t xmaxc, int16_t * expon_out, int16_t * mant_out) static
References SASR_W().
Referenced by APCM_quantization(), and Gsm_RPE_Decoding().
APCM_quantization()
static void APCM_quantization (int16_t * xM, int16_t * xMc, int16_t * mant_out, int16_t * expon_out, int16_t * xmaxc_out) static
References APCM_quantization_xmaxc_to_exp_mant(), arith_shift_left(), GSM_ABS(), gsm_add(), GSM_MULT(), gsm_NRFAC, and SASR_W().
Referenced by Gsm_RPE_Encoding().
APCM_inverse_quantization()
static void APCM_inverse_quantization (register int16_t * xMc, int16_t mant, int16_t expon, register int16_t * xMp) static
References arith_shift_left(), GSM_ADD(), gsm_asl(), gsm_asr(), gsm_FAC, GSM_MULT_R(), and gsm_sub().
Referenced by Gsm_RPE_Decoding(), and Gsm_RPE_Encoding().
RPE_grid_positioning()
static void RPE_grid_positioning (int16_t Mc, register int16_t * xMp, register int16_t * ep) static
Referenced by Gsm_RPE_Decoding(), and Gsm_RPE_Encoding().
Gsm_RPE_Encoding()
void Gsm_RPE_Encoding (int16_t * e, int16_t * xmaxc, int16_t * Mc, int16_t * xMc)
References APCM_inverse_quantization(), APCM_quantization(), RPE_grid_positioning(), RPE_grid_selection(), and Weighting_filter().
Referenced by Gsm_Coder().
Gsm_RPE_Decoding()
void Gsm_RPE_Decoding (int16_t xmaxcr, int16_t Mcr, int16_t * xMcr, int16_t * erp)
References APCM_inverse_quantization(), APCM_quantization_xmaxc_to_exp_mant(), and RPE_grid_positioning().
Referenced by Gsm_Decoder().