Aurora Framework: ima_oki_adpcm.h File Reference
ima_oki_adpcm.h File Reference
Classes
struct IMA_OKI_ADPCM
Macros
#define IMA_OKI_ADPCM_CODE_LEN 256
#define IMA_OKI_ADPCM_PCM_LEN (IMA_OKI_ADPCM_CODE_LEN *2)
Enumerations
enum IMA_OKI_ADPCM_TYPE { IMA_OKI_ADPCM_TYPE_IMA, IMA_OKI_ADPCM_TYPE_OKI }
Functions
int adpcm_decode (IMA_OKI_ADPCM *state, int code)
int adpcm_encode (IMA_OKI_ADPCM *state, int sample)
void ima_oki_adpcm_decode_block (IMA_OKI_ADPCM *state)
void ima_oki_adpcm_encode_block (IMA_OKI_ADPCM *state)
void ima_oki_adpcm_init (IMA_OKI_ADPCM *state, IMA_OKI_ADPCM_TYPE type)
Macro Definition Documentation
IMA_OKI_ADPCM_CODE_LEN
#define IMA_OKI_ADPCM_CODE_LEN 256
Referenced by vox_read_block().
IMA_OKI_ADPCM_PCM_LEN
#define IMA_OKI_ADPCM_PCM_LEN (IMA_OKI_ADPCM_CODE_LEN *2)
Referenced by vox_read_block(), and vox_write_block().
Enumeration Type Documentation
IMA_OKI_ADPCM_TYPE
enum IMA_OKI_ADPCM_TYPE
Enumerator
IMA_OKI_ADPCM_TYPE_IMA
IMA_OKI_ADPCM_TYPE_OKI
Function Documentation
ima_oki_adpcm_init()
void ima_oki_adpcm_init (IMA_OKI_ADPCM * state, IMA_OKI_ADPCM_TYPE type)
References arith_shift_left(), ARRAY_LEN, IMA_OKI_ADPCM_TYPE_IMA, ima_steps, IMA_OKI_ADPCM::mask, IMA_OKI_ADPCM::max_step_index, memset(), oki_steps, and IMA_OKI_ADPCM::steps.
Referenced by vox_adpcm_init().
adpcm_decode()
int adpcm_decode (IMA_OKI_ADPCM * state, int code)
References IMA_OKI_ADPCM::errors, IMA_OKI_ADPCM::last_output, IMA_OKI_ADPCM::mask, MAX_SAMPLE, IMA_OKI_ADPCM::max_step_index, MIN_SAMPLE, SF_MAX, SF_MIN, step_changes, IMA_OKI_ADPCM::step_index, and IMA_OKI_ADPCM::steps.
Referenced by adpcm_encode(), and ima_oki_adpcm_decode_block().
adpcm_encode()
int adpcm_encode (IMA_OKI_ADPCM * state, int sample)
References adpcm_decode(), IMA_OKI_ADPCM::last_output, SF_MIN, IMA_OKI_ADPCM::step_index, and IMA_OKI_ADPCM::steps.
Referenced by ima_oki_adpcm_encode_block().
ima_oki_adpcm_decode_block()
void ima_oki_adpcm_decode_block (IMA_OKI_ADPCM * state)
References adpcm_decode(), IMA_OKI_ADPCM::code_count, IMA_OKI_ADPCM::codes, IMA_OKI_ADPCM::pcm, and IMA_OKI_ADPCM::pcm_count.
Referenced by vox_read_block().
ima_oki_adpcm_encode_block()
void ima_oki_adpcm_encode_block (IMA_OKI_ADPCM * state)
References adpcm_encode(), IMA_OKI_ADPCM::code_count, IMA_OKI_ADPCM::codes, IMA_OKI_ADPCM::pcm, and IMA_OKI_ADPCM::pcm_count.
Referenced by vox_write_block().