Aurora Framework: Context.c File Reference
WGL/Context.c File Reference
Macros
#define setAttrib(a, v)
Functions
GLFWbool _glfwCreateContextWGL (_GLFWwindow *window, const _GLFWctxconfig *ctxconfig, const _GLFWfbconfig *fbconfig)
GLFWbool _glfwInitWGL (void)
void _glfwTerminateWGL (void)
static int choosePixelFormat (_GLFWwindow *window, const _GLFWctxconfig *ctxconfig, const _GLFWfbconfig *fbconfig)
static void destroyContextWGL (_GLFWwindow *window)
static int extensionSupportedWGL (const char *extension)
static int getPixelFormatAttrib (_GLFWwindow *window, int pixelFormat, int attrib)
static GLFWglproc getProcAddressWGL (const char *procname)
GLFWAPI HGLRC glfwGetWGLContext (GLFWwindow *handle)
static void makeContextCurrentWGL (_GLFWwindow *window)
static void swapBuffersWGL (_GLFWwindow *window)
static void swapIntervalWGL (int interval)
Macro Definition Documentation
setAttrib
#define setAttrib (a, v)
Value:
{ \
    assert((size_t) (index + 1) < sizeof(attribs) / sizeof(attribs[0])); \
    attribs[index++] = a; \
    attribs[index++] = v; \
}
Referenced by _glfwCreateContextWGL().
Function Documentation
getPixelFormatAttrib()
static int getPixelFormatAttrib (_GLFWwindow * window, int pixelFormat, int attrib) static
References _glfw, _glfwInputErrorWin32(), _GLFWwindow::context, GLFW_PLATFORM_ERROR, and value.
Referenced by choosePixelFormat().
choosePixelFormat()
static int choosePixelFormat (_GLFWwindow * window, const _GLFWctxconfig * ctxconfig, const _GLFWfbconfig * fbconfig) static
References _glfw, _glfwChooseFBConfig(), _glfwInputError(), _GLFWfbconfig::accumAlphaBits, _GLFWfbconfig::accumBlueBits, _GLFWfbconfig::accumGreenBits, _GLFWfbconfig::accumRedBits, _GLFWfbconfig::alphaBits, _GLFWfbconfig::auxBuffers, _GLFWfbconfig::blueBits, _GLFWctxconfig::client, _GLFWwindow::context, _GLFWfbconfig::depthBits, _GLFWfbconfig::doublebuffer, getPixelFormatAttrib(), GLFW_API_UNAVAILABLE, GLFW_FORMAT_UNAVAILABLE, GLFW_OPENGL_API, GLFW_TRUE, _GLFWfbconfig::greenBits, _GLFWfbconfig::handle, NULL, _GLFWfbconfig::redBits, _GLFWfbconfig::samples, _GLFWfbconfig::sRGB, _GLFWfbconfig::stencilBits, _GLFWfbconfig::stereo, WGL_ACCELERATION_ARB, WGL_ACCUM_ALPHA_BITS_ARB, WGL_ACCUM_BLUE_BITS_ARB, WGL_ACCUM_GREEN_BITS_ARB, WGL_ACCUM_RED_BITS_ARB, WGL_ALPHA_BITS_ARB, WGL_AUX_BUFFERS_ARB, WGL_BLUE_BITS_ARB, WGL_COLORSPACE_EXT, WGL_COLORSPACE_SRGB_EXT, WGL_DEPTH_BITS_ARB, WGL_DOUBLE_BUFFER_ARB, WGL_DRAW_TO_WINDOW_ARB, WGL_FRAMEBUFFER_SRGB_CAPABLE_ARB, WGL_GREEN_BITS_ARB, WGL_NO_ACCELERATION_ARB, WGL_NUMBER_PIXEL_FORMATS_ARB, WGL_PIXEL_TYPE_ARB, WGL_RED_BITS_ARB, WGL_SAMPLES_ARB, WGL_STENCIL_BITS_ARB, WGL_STEREO_ARB, WGL_SUPPORT_OPENGL_ARB, and WGL_TYPE_RGBA_ARB.
Referenced by _glfwCreateContextWGL().
makeContextCurrentWGL()
static void makeContextCurrentWGL (_GLFWwindow * window) static
References _glfw, _glfwInputErrorWin32(), _glfwPlatformSetTls(), _GLFWwindow::context, _GLFWlibrary::contextSlot, GLFW_PLATFORM_ERROR, NULL, and wglMakeCurrent.
Referenced by _glfwCreateContextWGL().
swapBuffersWGL()
static void swapBuffersWGL (_GLFWwindow * window) static
References _glfwIsCompositionEnabledWin32(), _GLFWwindow::context, DwmFlush, and _GLFWwindow::monitor.
Referenced by _glfwCreateContextWGL().
swapIntervalWGL()
static void swapIntervalWGL (int interval) static
References _glfw, _glfwIsCompositionEnabledWin32(), _glfwPlatformGetTls(), _GLFWwindow::context, _GLFWlibrary::contextSlot, and _GLFWwindow::monitor.
Referenced by _glfwCreateContextWGL().
extensionSupportedWGL()
static int extensionSupportedWGL (const char * extension) static
References _glfw, _glfwStringInExtensionString(), GLFW_FALSE, GLFW_TRUE, and wglGetCurrentDC.
Referenced by _glfwCreateContextWGL(), and _glfwInitWGL().
getProcAddressWGL()
static GLFWglproc getProcAddressWGL (const char * procname) static
References _glfw, and wglGetProcAddress.
Referenced by _glfwCreateContextWGL().
destroyContextWGL()
static void destroyContextWGL (_GLFWwindow * window) static
References _GLFWwindow::context, NULL, and wglDeleteContext.
Referenced by _glfwCreateContextWGL().
_glfwInitWGL()
GLFWbool _glfwInitWGL (void)
References _glfw, _glfwInputErrorWin32(), extensionSupportedWGL(), GLFW_FALSE, GLFW_PLATFORM_ERROR, GLFW_TRUE, wglCreateContext, wglDeleteContext, wglGetCurrentContext, wglGetCurrentDC, wglGetProcAddress, and wglMakeCurrent.
Referenced by _glfwPlatformCreateWindow().
_glfwTerminateWGL()
void _glfwTerminateWGL (void)
References _glfw.
Referenced by _glfwPlatformTerminate().
_glfwCreateContextWGL()
GLFWbool _glfwCreateContextWGL (_GLFWwindow * window, const _GLFWctxconfig * ctxconfig, const _GLFWfbconfig * fbconfig)
References _glfw, _glfwInputError(), _glfwInputErrorWin32(), choosePixelFormat(), _GLFWctxconfig::client, _GLFWwindow::context, _GLFWctxconfig::debug, _GLFWcontext::destroy, destroyContextWGL(), ERROR_INCOMPATIBLE_DEVICE_CONTEXTS_ARB, ERROR_INVALID_PROFILE_ARB, ERROR_INVALID_VERSION_ARB, _GLFWcontext::extensionSupported, extensionSupportedWGL(), _GLFWctxconfig::forward, _GLFWcontext::getProcAddress, getProcAddressWGL(), GLFW_API_UNAVAILABLE, GLFW_FALSE, GLFW_INVALID_VALUE, GLFW_LOSE_CONTEXT_ON_RESET, GLFW_NO_RESET_NOTIFICATION, GLFW_OPENGL_API, GLFW_OPENGL_COMPAT_PROFILE, GLFW_OPENGL_CORE_PROFILE, GLFW_PLATFORM_ERROR, GLFW_RELEASE_BEHAVIOR_FLUSH, GLFW_RELEASE_BEHAVIOR_NONE, GLFW_TRUE, GLFW_VERSION_UNAVAILABLE, _GLFWctxconfig::major, makeContextCurrentWGL(), _GLFWcontext::makeCurrent, _GLFWctxconfig::minor, _GLFWctxconfig::noerror, NULL, _GLFWctxconfig::profile, _GLFWctxconfig::release, _GLFWctxconfig::robustness, setAttrib, _GLFWctxconfig::share, _GLFWcontext::swapBuffers, swapBuffersWGL(), _GLFWcontext::swapInterval, swapIntervalWGL(), WGL_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB, WGL_CONTEXT_CORE_PROFILE_BIT_ARB, WGL_CONTEXT_DEBUG_BIT_ARB, WGL_CONTEXT_ES2_PROFILE_BIT_EXT, WGL_CONTEXT_FLAGS_ARB, WGL_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB, WGL_CONTEXT_MAJOR_VERSION_ARB, WGL_CONTEXT_MINOR_VERSION_ARB, WGL_CONTEXT_OPENGL_NO_ERROR_ARB, WGL_CONTEXT_PROFILE_MASK_ARB, WGL_CONTEXT_RELEASE_BEHAVIOR_ARB, WGL_CONTEXT_RELEASE_BEHAVIOR_FLUSH_ARB, WGL_CONTEXT_RELEASE_BEHAVIOR_NONE_ARB, WGL_CONTEXT_RESET_NOTIFICATION_STRATEGY_ARB, WGL_CONTEXT_ROBUST_ACCESS_BIT_ARB, WGL_LOSE_CONTEXT_ON_RESET_ARB, WGL_NO_RESET_NOTIFICATION_ARB, wglCreateContext, and wglShareLists.
Referenced by _glfwPlatformCreateWindow().
glfwGetWGLContext()
GLFWAPI HGLRC glfwGetWGLContext (GLFWwindow * handle)
References _GLFW_REQUIRE_INIT_OR_RETURN, _glfwInputError(), _GLFWcontext::client, _GLFWwindow::context, GLFW_NO_API, GLFW_NO_WINDOW_CONTEXT, and NULL.