Aurora Framework: voc.c File Reference
voc.c File Reference
Classes
struct SND_DATA_BLOCKS
struct VOC_DATA
Macros
#define VOC_MAX_SECTIONS 200
Enumerations
enum {
VOC_TERMINATOR = 0, VOC_SOUND_DATA = 1, VOC_SOUND_CONTINUE = 2, VOC_SILENCE = 3,
VOC_MARKER = 4, VOC_ASCII = 5, VOC_REPEAT = 6, VOC_END_REPEAT = 7,
VOC_EXTENDED = 8, VOC_EXTENDED_II = 9
}
Functions
static int voc_close (SF_PRIVATE *psf)
static const char * voc_encoding2str (int encoding)
int voc_open (SF_PRIVATE *psf)
static int voc_read_header (SF_PRIVATE *psf)
static int voc_write_header (SF_PRIVATE *psf, int calc_length)
Macro Definition Documentation
VOC_MAX_SECTIONS
#define VOC_MAX_SECTIONS 200
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
VOC_TERMINATOR
VOC_SOUND_DATA
VOC_SOUND_CONTINUE
VOC_SILENCE
VOC_MARKER
VOC_ASCII
VOC_REPEAT
VOC_END_REPEAT
VOC_EXTENDED
VOC_EXTENDED_II
Function Documentation
voc_close()
static int voc_close (SF_PRIVATE * psf) static
References sf_private_tag::file, PSF_FILE::mode, psf_fseek(), psf_fwrite(), VOC_TERMINATOR, and voc_write_header().
Referenced by voc_open().
voc_write_header()
static int voc_write_header (SF_PRIVATE * psf, int calc_length) static
References BHW1, BHW2, BHW3, BHW4, BHWv, BHWz, sf_private_tag::bytewidth, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::error, sf_private_tag::filelength, sf_private_tag::header, sf_private_tag::indx, psf_binheader_writef(), psf_fseek(), psf_ftell(), psf_fwrite(), psf_get_filelen(), sf_private_tag::ptr, sf_private_tag::sf, SF_CODEC, SFE_CHANNEL_COUNT, SFE_UNIMPLEMENTED, VOC_EXTENDED, VOC_EXTENDED_II, and VOC_SOUND_DATA.
Referenced by voc_close(), and voc_open().
voc_read_header()
static int voc_read_header (SF_PRIVATE * psf) static
References sf_private_tag::bytewidth, sf_private_tag::codec_data, sf_private_tag::dataend, sf_private_tag::dataoffset, sf_private_tag::endian, sf_private_tag::filelength, memset(), psf_binheader_readf(), psf_log_printf(), sf_private_tag::sf, SFE_MALLOC_FAILED, SFE_UNKNOWN_FORMAT, SFE_VOC_BAD_FORMAT, SFE_VOC_BAD_SECTIONS, SFE_VOC_BAD_VERSION, SFE_VOC_NO_CREATIVE, SIGNED_SIZEOF, create_symbols_file::version, VOC_ASCII, voc_encoding2str(), VOC_EXTENDED, VOC_EXTENDED_II, VOC_REPEAT, and VOC_SOUND_DATA.
Referenced by voc_open().
voc_encoding2str()
static const char * voc_encoding2str (int encoding) static
Referenced by voc_read_header().
voc_open()
int voc_open (SF_PRIVATE * psf)
References alaw_init(), sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::container_close, sf_private_tag::endian, sf_private_tag::file, sf_private_tag::filelength, sf_private_tag::is_pipe, PSF_FILE::mode, pcm_init(), sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SFE_BAD_OPEN_FORMAT, SFE_UNIMPLEMENTED, SFE_VOC_NO_PIPE, ulaw_init(), voc_close(), voc_read_header(), voc_write_header(), and sf_private_tag::write_header.
Referenced by psf_open_file().