Aurora Framework: Vulkan.c File Reference
Vulkan.c File Reference
Macros
#define _GLFW_FIND_LOADER 1
#define _GLFW_REQUIRE_LOADER 2
Functions
const char * _glfwGetVulkanResultString (VkResult result)
GLFWbool _glfwInitVulkan (int mode)
void _glfwTerminateVulkan (void)
GLFWAPI VkResult glfwCreateWindowSurface (VkInstance instance, GLFWwindow *handle, const VkAllocationCallbacks *allocator, VkSurfaceKHR *surface)
GLFWAPI GLFWvkproc glfwGetInstanceProcAddress (VkInstance instance, const char *procname)
GLFWAPI int glfwGetPhysicalDevicePresentationSupport (VkInstance instance, VkPhysicalDevice device, uint32_t queuefamily)
GLFWAPI const char ** glfwGetRequiredInstanceExtensions (uint32_t *count)
Returns the Vulkan instance extensions required by GLFW.
GLFWAPI int glfwVulkanSupported (void)
Returns whether the Vulkan loader and an ICD have been found.
Macro Definition Documentation
_GLFW_FIND_LOADER
#define _GLFW_FIND_LOADER 1
Referenced by glfwVulkanSupported().
_GLFW_REQUIRE_LOADER
#define _GLFW_REQUIRE_LOADER 2
Referenced by _glfwInitVulkan(), glfwCreateWindowSurface(), glfwGetInstanceProcAddress(), glfwGetPhysicalDevicePresentationSupport(), and glfwGetRequiredInstanceExtensions().
Function Documentation
_glfwInitVulkan()
GLFWbool _glfwInitVulkan (int mode)
References _glfw, _GLFW_REQUIRE_LOADER, _glfwGetVulkanResultString(), _glfwInputError(), _glfwPlatformGetRequiredInstanceExtensions(), _glfwTerminateVulkan(), _GLFWlibrary::available, _GLFWlibrary::extensions, GLFW_API_UNAVAILABLE, GLFW_FALSE, GLFW_TRUE, _GLFWlibrary::KHR_surface, mode(), NULL, _GLFWlibrary::vk, and vkEnumerateInstanceExtensionProperties().
Referenced by glfwCreateWindowSurface(), glfwGetInstanceProcAddress(), glfwGetPhysicalDevicePresentationSupport(), glfwGetRequiredInstanceExtensions(), and glfwVulkanSupported().
_glfwTerminateVulkan()
void _glfwTerminateVulkan (void)
Referenced by _glfwInitVulkan(), and terminate().
_glfwGetVulkanResultString()
const char* _glfwGetVulkanResultString (VkResult result)
References VK_ERROR_DEVICE_LOST, VK_ERROR_EXTENSION_NOT_PRESENT, VK_ERROR_FEATURE_NOT_PRESENT, VK_ERROR_FORMAT_NOT_SUPPORTED, VK_ERROR_INCOMPATIBLE_DISPLAY_KHR, VK_ERROR_INCOMPATIBLE_DRIVER, VK_ERROR_INITIALIZATION_FAILED, VK_ERROR_LAYER_NOT_PRESENT, VK_ERROR_MEMORY_MAP_FAILED, VK_ERROR_NATIVE_WINDOW_IN_USE_KHR, VK_ERROR_OUT_OF_DATE_KHR, VK_ERROR_OUT_OF_DEVICE_MEMORY, VK_ERROR_OUT_OF_HOST_MEMORY, VK_ERROR_SURFACE_LOST_KHR, VK_ERROR_TOO_MANY_OBJECTS, VK_ERROR_VALIDATION_FAILED_EXT, VK_EVENT_RESET, VK_EVENT_SET, VK_INCOMPLETE, VK_NOT_READY, VK_SUBOPTIMAL_KHR, VK_SUCCESS, and VK_TIMEOUT.
Referenced by _glfwInitVulkan(), and _glfwPlatformCreateWindowSurface().
glfwGetInstanceProcAddress()
GLFWAPI GLFWvkproc glfwGetInstanceProcAddress (VkInstance instance, const char * procname)
References _GLFW_REQUIRE_INIT_OR_RETURN, _GLFW_REQUIRE_LOADER, _glfwInitVulkan(), NULL, and vkGetInstanceProcAddr().
glfwGetPhysicalDevicePresentationSupport()
GLFWAPI int glfwGetPhysicalDevicePresentationSupport (VkInstance instance, VkPhysicalDevice device, uint32_t queuefamily)
References _glfw, _GLFW_REQUIRE_INIT_OR_RETURN, _GLFW_REQUIRE_LOADER, _glfwInitVulkan(), _glfwInputError(), _glfwPlatformGetPhysicalDevicePresentationSupport(), _GLFWlibrary::extensions, GLFW_API_UNAVAILABLE, GLFW_FALSE, _GLFWlibrary::vk, and VK_NULL_HANDLE.
glfwCreateWindowSurface()
GLFWAPI VkResult glfwCreateWindowSurface (VkInstance instance, GLFWwindow * handle, const VkAllocationCallbacks * allocator, VkSurfaceKHR * surface)
References _glfw, _GLFW_REQUIRE_INIT_OR_RETURN, _GLFW_REQUIRE_LOADER, _glfwInitVulkan(), _glfwInputError(), _glfwPlatformCreateWindowSurface(), _GLFWcontext::client, _GLFWwindow::context, _GLFWlibrary::extensions, GLFW_API_UNAVAILABLE, GLFW_INVALID_VALUE, GLFW_NO_API, NULL, _GLFWlibrary::vk, VK_ERROR_EXTENSION_NOT_PRESENT, VK_ERROR_INITIALIZATION_FAILED, VK_ERROR_NATIVE_WINDOW_IN_USE_KHR, and VK_NULL_HANDLE.
Referenced by AuroraFW::GEngine::VKContext::_init().