Aurora Framework: strings.c File Reference
strings.c File Reference
Macros
#define STRINGS_DEBUG 0
Functions
const char * psf_get_string (SF_PRIVATE *psf, int str_type)
int psf_location_string_count (const SF_PRIVATE *psf, int location)
int psf_set_string (SF_PRIVATE *psf, int str_type, const char *str)
int psf_store_string (SF_PRIVATE *psf, int str_type, const char *str)
Macro Definition Documentation
STRINGS_DEBUG
#define STRINGS_DEBUG 0
Function Documentation
psf_store_string()
int psf_store_string (SF_PRIVATE * psf, int str_type, const char * str)
References sf_private_tag::data, sf_private_tag::file, STR_DATA::flags, sf_private_tag::flags, sf_private_tag::have_written, memcpy(), PSF_FILE::mode, NULL, STR_DATA::offset, psf_hexdump(), psf_log_printf(), SF_MAX_STRINGS, SF_STR_ALLOW_END, SF_STR_ALLOW_START, SF_STR_LOCATE_END, SF_STR_LOCATE_START, SFE_MALLOC_FAILED, SFE_STR_BAD_STRING, SFE_STR_BAD_TYPE, SFE_STR_MAX_COUNT, SFE_STR_NO_ADD_END, SFE_STR_NO_SUPPORT, SFE_STR_WEIRD, sf_private_tag::storage, sf_private_tag::storage_len, sf_private_tag::storage_used, sf_private_tag::strings, and STR_DATA::type.
Referenced by aiff_read_header(), caf_read_strings(), psf_set_string(), wavlike_subchunk_parse(), and xi_read_header().
psf_set_string()
int psf_set_string (SF_PRIVATE * psf, int str_type, const char * str)
References sf_private_tag::file, PSF_FILE::mode, psf_store_string(), and SFE_STR_NOT_WRITE.
Referenced by sf_set_string().
psf_get_string()
const char* psf_get_string (SF_PRIVATE * psf, int str_type)
References sf_private_tag::data, NULL, STR_DATA::offset, SF_MAX_STRINGS, sf_private_tag::storage, sf_private_tag::strings, and STR_DATA::type.
Referenced by caf_write_strings(), and sf_get_string().
psf_location_string_count()
int psf_location_string_count (const SF_PRIVATE * psf, int location)
References sf_private_tag::data, STR_DATA::flags, SF_MAX_STRINGS, sf_private_tag::strings, and STR_DATA::type.
Referenced by wavlike_write_strings().