Aurora Framework: AuroraFW::AudioManager Namespace Reference
AuroraFW::AudioManager Namespace Reference
Classes
class AudioBackend
A singleton class representing the audio backend.
struct AudioDevice
A struct representing an audio device.
struct AudioEffect
class AudioFileNotFound
An exception to tell the user the given audio file couldn't be found.
struct AudioInfo
A struct to hold audio info.
struct AudioIStream
A struct representing an audio input stream.
class AudioListener
A singleton struct representing an audio listener.
class AudioNotInitializedException
An exception to tell the user that there was an attempt to process audio data without the backend having initialized yet.
struct AudioOStream
A struct representing an audio output stream.
struct AudioSource
A struct representing an audio source.
struct HighPassEffect
struct LowPassEffect
class PAErrorException
An exception to tell the user that an internal PortAudio error ocurred.
struct ReverbEffect
class SNDFILEErrorException
An exception to tell the user than an internal libSNDFile error ocurred.
Enumerations
enum AudioFallout { AudioFallout::Linear, AudioFallout::Exponential }
An enum to indicate the desired fallout type for 3D audio.
enum AudioPlayMode { AudioPlayMode::Once, AudioPlayMode::Loop }
An enum to indicate the desired play mode for the audio stream.
Functions
int audioInputCallback (const void *inputBuffer, void *outputBuffer, size_t framesPerBuffer, const PaStreamCallbackTimeInfo *timeInfo, PaStreamCallbackFlags statusFlags, void *userData)
int audioOutputCallback (const void *inputBuffer, void *outputBuffer, size_t framesPerBuffer, const PaStreamCallbackTimeInfo *timeInfo, PaStreamCallbackFlags statusFlags, void *userData)
void catchPAProblem (const PaError &error)
void catchSNDFILEProblem (const int &error)
int debugCallback (const void *, void *, size_t, const PaStreamCallbackTimeInfo *, PaStreamCallbackFlags, void *)
Enumeration Type Documentation
AudioFallout
enum AuroraFW::AudioManager::AudioFallout strong
An enum to indicate the desired fallout type for 3D audio.
Since
snapshot20180330
Enumerator
Linear
Linear function.
Exponential
Exponential function.
AudioPlayMode
enum AuroraFW::AudioManager::AudioPlayMode strong
An enum to indicate the desired play mode for the audio stream.
Since
snapshot20180330
Enumerator
Once
Play the audio stream once.
Loop
Loop the audio stream.
Function Documentation
catchPAProblem()
void AuroraFW::AudioManager::catchPAProblem (const PaError & error) inline
Referenced by AuroraFW::AudioManager::AudioIStream::AudioIStream(), AuroraFW::AudioManager::AudioOStream::AudioOStream(), AuroraFW::AudioManager::AudioIStream::pause(), AuroraFW::AudioManager::AudioOStream::pause(), AuroraFW::AudioManager::AudioOStream::play(), AuroraFW::AudioManager::AudioIStream::record(), AuroraFW::AudioManager::AudioIStream::stop(), AuroraFW::AudioManager::AudioOStream::stop(), and AuroraFW::AudioManager::AudioBackend::terminate().
catchSNDFILEProblem()
void AuroraFW::AudioManager::catchSNDFILEProblem (const int & error) inline
Referenced by AuroraFW::AudioManager::AudioInfo::~AudioInfo().
debugCallback()
int AuroraFW::AudioManager::debugCallback (const void * inputBuffer, void * outputBuffer, size_t framesPerBuffer, const PaStreamCallbackTimeInfo * timeInfo, PaStreamCallbackFlags statusFlags, void * userData)
Referenced by AuroraFW::AudioManager::AudioOStream::AudioOStream().
audioInputCallback()
int AuroraFW::AudioManager::audioInputCallback (const void * inputBuffer, void * outputBuffer, size_t framesPerBuffer, const PaStreamCallbackTimeInfo * timeInfo, PaStreamCallbackFlags statusFlags, void * userData)
References AuroraFW::AudioManager::AudioIStream::buffer, AuroraFW::AudioManager::AudioIStream::bufferSize, AuroraFW::AudioManager::AudioInfo::getChannels(), and AuroraFW::AudioManager::AudioIStream::info.
audioOutputCallback()
int AuroraFW::AudioManager::audioOutputCallback (const void * inputBuffer, void * outputBuffer, size_t framesPerBuffer, const PaStreamCallbackTimeInfo * timeInfo, PaStreamCallbackFlags statusFlags, void * userData)
References AuroraFW::AudioManager::AudioOStream::audioInfo, AuroraFW::AudioManager::AudioOStream::audioPlayMode, AuroraFW::AudioManager::AudioInfo::getChannels(), AuroraFW::AudioManager::AudioInfo::getFrames(), AuroraFW::AudioManager::AudioBackend::getInstance(), AuroraFW::AudioManager::AudioBackend::globalVolume, Loop, Once, sf_readf_float(), sf_seek(), source, and AuroraFW::AudioManager::AudioOStream::volume.