Aurora Framework: au.c File Reference
au.c File Reference
Classes
struct AU_FMT
Macros
#define AU_DATA_OFFSET 24
#define DNSDOT_MARKER (MAKE_MARKER ('d', 'n', 's', '.'))
#define DOTSND_MARKER (MAKE_MARKER ('.', 's', 'n', 'd'))
Enumerations
enum {
AU_ENCODING_ULAW_8 = 1, AU_ENCODING_PCM_8 = 2, AU_ENCODING_PCM_16 = 3, AU_ENCODING_PCM_24 = 4,
AU_ENCODING_PCM_32 = 5, AU_ENCODING_FLOAT = 6, AU_ENCODING_DOUBLE = 7, AU_ENCODING_INDIRECT = 8,
AU_ENCODING_NESTED = 9, AU_ENCODING_DSP_CORE = 10, AU_ENCODING_DSP_DATA_8 = 11, AU_ENCODING_DSP_DATA_16 = 12,
AU_ENCODING_DSP_DATA_24 = 13, AU_ENCODING_DSP_DATA_32 = 14, AU_ENCODING_DISPLAY = 16, AU_ENCODING_MULAW_SQUELCH = 17,
AU_ENCODING_EMPHASIZED = 18, AU_ENCODING_NEXT = 19, AU_ENCODING_COMPRESSED_EMPHASIZED = 20, AU_ENCODING_DSP_COMMANDS = 21,
AU_ENCODING_DSP_COMMANDS_SAMPLES = 22, AU_ENCODING_ADPCM_G721_32 = 23, AU_ENCODING_ADPCM_G722 = 24, AU_ENCODING_ADPCM_G723_24 = 25,
AU_ENCODING_ADPCM_G723_40 = 26, AU_ENCODING_ALAW_8 = 27
}
Functions
static int au_close (SF_PRIVATE *psf)
static int au_format_to_encoding (int format)
int au_open (SF_PRIVATE *psf)
static int au_read_header (SF_PRIVATE *psf)
static int au_write_header (SF_PRIVATE *psf, int calc_length)
Macro Definition Documentation
DOTSND_MARKER
#define DOTSND_MARKER (MAKE_MARKER ('.', 's', 'n', 'd'))
Referenced by au_read_header(), and au_write_header().
DNSDOT_MARKER
#define DNSDOT_MARKER (MAKE_MARKER ('d', 'n', 's', '.'))
Referenced by au_read_header(), and au_write_header().
AU_DATA_OFFSET
#define AU_DATA_OFFSET 24
Referenced by au_write_header().
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
AU_ENCODING_ULAW_8
AU_ENCODING_PCM_8
AU_ENCODING_PCM_16
AU_ENCODING_PCM_24
AU_ENCODING_PCM_32
AU_ENCODING_FLOAT
AU_ENCODING_DOUBLE
AU_ENCODING_INDIRECT
AU_ENCODING_NESTED
AU_ENCODING_DSP_CORE
AU_ENCODING_DSP_DATA_8
AU_ENCODING_DSP_DATA_16
AU_ENCODING_DSP_DATA_24
AU_ENCODING_DSP_DATA_32
AU_ENCODING_DISPLAY
AU_ENCODING_MULAW_SQUELCH
AU_ENCODING_EMPHASIZED
AU_ENCODING_NEXT
AU_ENCODING_COMPRESSED_EMPHASIZED
AU_ENCODING_DSP_COMMANDS
AU_ENCODING_DSP_COMMANDS_SAMPLES
AU_ENCODING_ADPCM_G721_32
AU_ENCODING_ADPCM_G722
AU_ENCODING_ADPCM_G723_24
AU_ENCODING_ADPCM_G723_40
AU_ENCODING_ALAW_8
Function Documentation
au_close()
static int au_close (SF_PRIVATE * psf) static
References au_write_header(), sf_private_tag::file, and PSF_FILE::mode.
Referenced by au_open().
au_format_to_encoding()
static int au_format_to_encoding (int format) static
References AU_ENCODING_ADPCM_G721_32, AU_ENCODING_ADPCM_G723_24, AU_ENCODING_ADPCM_G723_40, AU_ENCODING_ALAW_8, AU_ENCODING_DOUBLE, AU_ENCODING_FLOAT, AU_ENCODING_PCM_16, AU_ENCODING_PCM_24, AU_ENCODING_PCM_32, AU_ENCODING_PCM_8, and AU_ENCODING_ULAW_8.
Referenced by au_write_header().
au_write_header()
static int au_write_header (SF_PRIVATE * psf, int calc_length) static
References AU_DATA_OFFSET, au_format_to_encoding(), BHW4, BHWm, sf_private_tag::dataend, sf_private_tag::datalength, sf_private_tag::dataoffset, DNSDOT_MARKER, DOTSND_MARKER, sf_private_tag::endian, sf_private_tag::error, sf_private_tag::filelength, sf_private_tag::header, sf_private_tag::indx, sf_private_tag::is_pipe, sf_private_tag::pipeoffset, psf_binheader_writef(), psf_fseek(), psf_ftell(), psf_fwrite(), psf_get_filelen(), sf_private_tag::ptr, sf_private_tag::sf, SF_CODEC, and SFE_BAD_OPEN_FORMAT.
Referenced by au_close(), and au_open().
au_read_header()
static int au_read_header (SF_PRIVATE * psf) static
References AU_ENCODING_ADPCM_G721_32, AU_ENCODING_ADPCM_G722, AU_ENCODING_ADPCM_G723_24, AU_ENCODING_ADPCM_G723_40, AU_ENCODING_ALAW_8, AU_ENCODING_DOUBLE, AU_ENCODING_FLOAT, AU_ENCODING_NEXT, AU_ENCODING_PCM_16, AU_ENCODING_PCM_24, AU_ENCODING_PCM_32, AU_ENCODING_PCM_8, AU_ENCODING_ULAW_8, sf_private_tag::blockwidth, sf_private_tag::bytewidth, AU_FMT::channels, sf_private_tag::datalength, AU_FMT::dataoffset, sf_private_tag::dataoffset, AU_FMT::datasize, DNSDOT_MARKER, DOTSND_MARKER, AU_FMT::encoding, sf_private_tag::endian, sf_private_tag::filelength, sf_private_tag::fileoffset, memset(), psf_binheader_readf(), psf_ftell(), psf_log_printf(), AU_FMT::samplerate, sf_private_tag::sf, SF_ENDIAN, SF_MAX_CHANNELS, SFE_AU_EMBED_BAD_LEN, SFE_AU_NO_DOTSND, SFE_CHANNEL_COUNT, and SFE_CHANNEL_COUNT_ZERO.
Referenced by au_open().
au_open()
int au_open (SF_PRIVATE * psf)
References alaw_init(), au_close(), au_read_header(), au_write_header(), sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::container_close, double64_init(), sf_private_tag::endian, sf_private_tag::error, sf_private_tag::file, sf_private_tag::filelength, float32_init(), g72x_init(), PSF_FILE::mode, pcm_init(), sf_private_tag::sf, SF_CODEC, SF_CONTAINER, SF_ENDIAN, SFE_BAD_OPEN_FORMAT, ulaw_init(), and sf_private_tag::write_header.
Referenced by psf_open_file().