Aurora Framework: sfendian.h File Reference
sfendian.h File Reference
Macros
#define BET2H_16_PTR(x) (((x) [0] << 8) + (x) [1])
#define BET2H_32_PTR(x) (((x) [0] << 24) + ((x) [1] << 16) + ((x) [2] << 8))
#define ENDSWAP_16(x) ((((x) >> 8) & 0xFF) + (((x) & 0xFF) << 8))
#define ENDSWAP_32(x) ((((x) >> 24) & 0xFF) + (((x) >> 8) & 0xFF00) + (((x) & 0xFF00) << 8) + (((x) & 0xFF) << 24))
#define LET2H_16_PTR(x) ((x) [1] + ((x) [2] << 8))
#define LET2H_32_PTR(x) (((x) [0] << 8) + ((x) [1] << 16) + ((x) [2] << 24))
Functions
static uint64_t ENDSWAP_64 (uint64_t x)
static void endswap_double_array (double *ptr, int len)
static void endswap_double_copy (double *dest, const double *src, int len)
static void endswap_float_array (float *ptr, int len)
static void endswap_float_copy (float *dest, const float *src, int len)
static void endswap_int64_t_array (int64_t *ptr, int len)
static void endswap_int64_t_copy (int64_t *dest, const int64_t *src, int len)
static void endswap_int_array (int *ptr, int len)
static void endswap_int_copy (int *dest, const int *src, int len)
static void endswap_short_array (short *ptr, int len)
static void endswap_short_copy (short *dest, const short *src, int len)
static int16_t psf_get_be16 (uint8_t *ptr, int offset)
static int32_t psf_get_be24 (uint8_t *ptr, int offset)
static int32_t psf_get_be32 (uint8_t *ptr, int offset)
static int64_t psf_get_be64 (uint8_t *ptr, int offset)
static int32_t psf_get_le24 (uint8_t *ptr, int offset)
static int32_t psf_get_le32 (uint8_t *ptr, int offset)
static int64_t psf_get_le64 (uint8_t *ptr, int offset)
static void psf_put_be16 (uint8_t *ptr, int offset, int16_t value)
static void psf_put_be32 (uint8_t *ptr, int offset, int32_t value)
static void psf_put_be64 (uint8_t *ptr, int offset, int64_t value)
Macro Definition Documentation
ENDSWAP_16
#define ENDSWAP_16 (x) ((((x) >> 8) & 0xFF) + (((x) & 0xFF) << 8))
Referenced by endswap_short_array(), endswap_short_copy(), and mat5_read_header().
ENDSWAP_32
#define ENDSWAP_32 (x) ((((x) >> 24) & 0xFF) + (((x) >> 8) & 0xFF00) + (((x) & 0xFF00) << 8) + (((x) & 0xFF) << 24))
Referenced by aiff_read_comm_chunk(), ENDSWAP_64(), endswap_int_array(), and endswap_int_copy().
LET2H_16_PTR
#define LET2H_16_PTR (x) ((x) [1] + ((x) [2] << 8))
Referenced by let2s_array().
LET2H_32_PTR
#define LET2H_32_PTR (x) (((x) [0] << 8) + ((x) [1] << 16) + ((x) [2] << 24))
BET2H_16_PTR
#define BET2H_16_PTR (x) (((x) [0] << 8) + (x) [1])
Referenced by bet2s_array().
BET2H_32_PTR
#define BET2H_32_PTR (x) (((x) [0] << 24) + ((x) [1] << 16) + ((x) [2] << 8))
Function Documentation
ENDSWAP_64()
static uint64_t ENDSWAP_64 (uint64_t x) inline static
References ENDSWAP_32.
Referenced by endswap_int64_t_array(), and endswap_int64_t_copy().
psf_put_be64()
static void psf_put_be64 (uint8_t * ptr, int offset, int64_t value) inline static
References value.
Referenced by alac_pakt_encode().
psf_put_be32()
static void psf_put_be32 (uint8_t * ptr, int offset, int32_t value) inline static
References value.
Referenced by alac_pakt_encode(), dyn_jam_noDeref(), and dyn_jam_noDeref_large().
psf_put_be16()
static void psf_put_be16 (uint8_t * ptr, int offset, int16_t value) inline static
References value.
psf_get_be64()
static int64_t psf_get_be64 (uint8_t * ptr, int offset) inline static
References value.
Referenced by psf_binheader_readf().
psf_get_le64()
static int64_t psf_get_le64 (uint8_t * ptr, int offset) inline static
References value.
Referenced by psf_binheader_readf().
psf_get_be32()
static int32_t psf_get_be32 (uint8_t * ptr, int offset) inline static
References value.
Referenced by alac_decoder_init(), dyn_jam_noDeref(), dyn_jam_noDeref_large(), and psf_binheader_readf().
psf_get_le32()
static int32_t psf_get_le32 (uint8_t * ptr, int offset) inline static
References value.
Referenced by psf_binheader_readf().
psf_get_be24()
static int32_t psf_get_be24 (uint8_t * ptr, int offset) inline static
References value.
Referenced by bet2d_array(), bet2f_array(), and bet2i_array().
psf_get_le24()
static int32_t psf_get_le24 (uint8_t * ptr, int offset) inline static
References value.
Referenced by let2d_array(), let2f_array(), and let2i_array().
psf_get_be16()
static int16_t psf_get_be16 (uint8_t * ptr, int offset) inline static
Referenced by alac_decoder_init().
endswap_short_array()
static void endswap_short_array (short * ptr, int len) inline static
References ENDSWAP_16.
Referenced by pcm_read_bes2s(), pcm_read_les2s(), psf_nms_adpcm_decode_block(), and psf_nms_adpcm_encode_block().
endswap_short_copy()
static void endswap_short_copy (short * dest, const short * src, int len) inline static
References ENDSWAP_16.
Referenced by pcm_write_s2bes(), and pcm_write_s2les().
endswap_int_array()
static void endswap_int_array (int * ptr, int len) inline static
References ENDSWAP_32.
Referenced by endswap_float_array(), host_read_f2d(), host_read_f2i(), host_read_f2s(), host_write_d2f(), host_write_i2f(), host_write_s2f(), paf24_read_block(), paf24_write_block(), pcm_read_bei2i(), pcm_read_lei2i(), replace_read_f(), replace_read_f2d(), replace_read_f2i(), replace_read_f2s(), replace_write_d2f(), replace_write_f(), replace_write_i2f(), and replace_write_s2f().
endswap_int_copy()
static void endswap_int_copy (int * dest, const int * src, int len) inline static
References ENDSWAP_32.
Referenced by endswap_float_copy(), host_read_f(), host_write_f(), pcm_write_i2bei(), and pcm_write_i2lei().
endswap_int64_t_array()
static void endswap_int64_t_array (int64_t * ptr, int len) inline static
References ENDSWAP_64(), and value.
Referenced by endswap_double_array().
endswap_int64_t_copy()
static void endswap_int64_t_copy (int64_t * dest, const int64_t * src, int len) inline static
References ENDSWAP_64(), and value.
Referenced by endswap_double_copy().
endswap_float_array()
static void endswap_float_array (float * ptr, int len) inline static
References endswap_int_array().
endswap_double_array()
static void endswap_double_array (double * ptr, int len) inline static
References endswap_int64_t_array().
Referenced by host_read_d(), host_read_d2f(), host_read_d2i(), host_read_d2s(), host_write_f2d(), host_write_i2d(), host_write_s2d(), replace_read_d(), replace_read_d2f(), replace_read_d2i(), replace_read_d2s(), replace_write_d(), replace_write_f2d(), replace_write_i2d(), and replace_write_s2d().
endswap_float_copy()
static void endswap_float_copy (float * dest, const float * src, int len) inline static
References endswap_int_copy().
endswap_double_copy()
static void endswap_double_copy (double * dest, const double * src, int len) inline static
References endswap_int64_t_copy().
Referenced by host_write_d().