Aurora Framework: mpc2k.c File Reference
mpc2k.c File Reference
Macros
#define HEADER_LENGTH 42 /* Sum of above data fields. */
#define HEADER_NAME_LEN 17 /* Length of name string. */
#define SFE_MPC_NO_MARKER 666
Functions
static int mpc2k_close (SF_PRIVATE *psf)
int mpc2k_open (SF_PRIVATE *psf)
static int mpc2k_read_header (SF_PRIVATE *psf)
static int mpc2k_write_header (SF_PRIVATE *psf, int calc_length)
Macro Definition Documentation
HEADER_LENGTH
#define HEADER_LENGTH 42 /* Sum of above data fields. */
Referenced by mpc2k_write_header().
HEADER_NAME_LEN
#define HEADER_NAME_LEN 17 /* Length of name string. */
Referenced by mpc2k_read_header(), and mpc2k_write_header().
SFE_MPC_NO_MARKER
#define SFE_MPC_NO_MARKER 666
Referenced by mpc2k_read_header().
Function Documentation
mpc2k_close()
static int mpc2k_close (SF_PRIVATE * psf) static
References sf_private_tag::file, PSF_FILE::mode, and mpc2k_write_header().
Referenced by mpc2k_open().
mpc2k_write_header()
static int mpc2k_write_header (SF_PRIVATE * psf, int calc_length) static
References BHW1, BHW2, BHW4, BHW8, BHWv, BHWz, sf_private_tag::bytewidth, PSF_FILE::c, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::endian, sf_private_tag::error, sf_private_tag::file, sf_private_tag::filelength, sf_private_tag::header, HEADER_LENGTH, HEADER_NAME_LEN, sf_private_tag::indx, sf_private_tag::is_pipe, PSF_FILE::name, sf_private_tag::pipeoffset, psf_binheader_writef(), psf_fseek(), psf_ftell(), psf_fwrite(), psf_get_filelen(), sf_private_tag::ptr, and sf_private_tag::sf.
Referenced by mpc2k_close(), and mpc2k_open().
mpc2k_read_header()
static int mpc2k_read_header (SF_PRIVATE * psf) static
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::datalength, sf_private_tag::dataoffset, sf_private_tag::endian, sf_private_tag::filelength, HEADER_NAME_LEN, make_size_t(), psf_binheader_readf(), psf_ftell(), psf_log_printf(), sf_private_tag::sf, and SFE_MPC_NO_MARKER.
Referenced by mpc2k_open().
mpc2k_open()
int mpc2k_open (SF_PRIVATE * psf)
References sf_private_tag::blockwidth, sf_private_tag::bytewidth, sf_private_tag::container_close, sf_private_tag::error, sf_private_tag::file, sf_private_tag::filelength, PSF_FILE::mode, mpc2k_close(), mpc2k_read_header(), mpc2k_write_header(), pcm_init(), sf_private_tag::sf, SF_CONTAINER, SFE_BAD_OPEN_FORMAT, and sf_private_tag::write_header.
Referenced by psf_open_file().