Aurora Framework: ImVector< T > Class Template Reference
ImVector< T > Class Template Reference
Public Types
typedef const value_type * const_iterator
typedef value_type * iterator
typedef T value_type
Public Member Functions
ImVector ()
~ImVector ()
int _grow_capacity (int sz) const
value_type & back ()
const value_type & back () const
iterator begin ()
const_iterator begin () const
int capacity () const
void clear ()
bool contains (const value_type &v) const
bool empty () const
iterator end ()
const_iterator end () const
iterator erase (const_iterator it)
value_type & front ()
const value_type & front () const
iterator insert (const_iterator it, const value_type &v)
value_type & operator[] (int i)
const value_type & operator[] (int i) const
void pop_back ()
void push_back (const value_type &v)
void push_front (const value_type &v)
void reserve (int new_capacity)
void resize (int new_size)
void resize (int new_size, const T &v)
int size () const
void swap (ImVector< T > &rhs)
Public Attributes
int Capacity
T * Data
int Size
Member Typedef Documentation
value_type
template<typename T> typedef T ImVector< T >::value_type
iterator
template<typename T> typedef value_type* ImVector< T >::iterator
const_iterator
template<typename T> typedef const value_type* ImVector< T >::const_iterator
Constructor & Destructor Documentation
ImVector()
template<typename T> ImVector< T >::ImVector () inline
~ImVector()
template<typename T> ImVector< T >::~ImVector () inline
Member Function Documentation
empty()
template<typename T> bool ImVector< T >::empty () const inline
Referenced by AddDrawListToDrawData(), ImGui::Begin(), ImGui::ClosePopupsOverWindow(), ImDrawData::DeIndexAllBuffers(), ImGui::End(), ImGui::EndGroup(), ImDrawDataBuilder::FlattenIntoSingleLayer(), GetClipboardTextFn_DefaultImpl(), ImGui::InputTextEx(), ImGuiTextFilter::IsActive(), ImGui::NewFrame(), ImGui::PopFont(), ImGui::PopItemFlag(), ImGui::PopItemWidth(), ImGui::PopTextWrapPos(), ImGui::Render(), and ImGui::Separator().
size()
template<typename T> int ImVector< T >::size () const inline
capacity()
template<typename T> int ImVector< T >::capacity () const inline
operator[]() [1/2]
template<typename T> value_type& ImVector< T >::operator[] (int i) inline
operator[]() [2/2]
template<typename T> const value_type& ImVector< T >::operator[] (int i) const inline
clear()
template<typename T> void ImVector< T >::clear () inline
Referenced by ImGuiColumnsSet::Clear(), ImGuiTextBuffer::clear(), ImGuiStorage::Clear(), ImGui::NewFrame(), SetClipboardTextFn_DefaultImpl(), and ImGui::Shutdown().
begin() [1/2]
template<typename T> iterator ImVector< T >::begin () inline
Referenced by AddWindowToSortedBuffer(), CreateNewWindow(), GetClipboardTextFn_DefaultImpl(), ImGui::InputScalarAsWidgetReplacement(), ImGui::InputScalarEx(), LowerBound(), and ImGui::ShowMetricsWindow().
begin() [2/2]
template<typename T> const_iterator ImVector< T >::begin () const inline
end() [1/2]
template<typename T> iterator ImVector< T >::end () inline
Referenced by LowerBound(), and ImGui::ShowMetricsWindow().
end() [2/2]
template<typename T> const_iterator ImVector< T >::end () const inline
front() [1/2]
template<typename T> value_type& ImVector< T >::front () inline
Referenced by ImGuiTextBuffer::begin().
front() [2/2]
template<typename T> const value_type& ImVector< T >::front () const inline
back() [1/2]
template<typename T> value_type& ImVector< T >::back () inline
Referenced by AddDrawListToDrawData(), AddWindowSettings(), ImGui::Begin(), ImGui::BeginDragDropSource(), ImGui::BeginGroup(), ImGui::BeginMenu(), ImGui::BringWindowToFront(), ImDrawList::ChannelsMerge(), ImGui::End(), ImGuiTextBuffer::end(), ImGui::EndGroup(), ImGui::EndMenuBar(), FindOrAddColumnsSet(), ImDrawList::GetClipRectMax(), ImDrawList::GetClipRectMin(), ImGui::NavProcessItem(), ImGui::NavUpdate(), ImGui::OpenPopupEx(), ImGui::PopClipRect(), ImGui::PopFont(), ImGui::PopItemFlag(), ImGui::PopItemWidth(), ImGui::PopStyleColor(), ImGui::PopStyleVar(), ImGui::PopTextWrapPos(), ImGui::PushClipRect(), ImGui::PushMultiItemsWidths(), and ImGui::TreePop().
back() [2/2]
template<typename T> const value_type& ImVector< T >::back () const inline
swap()
template<typename T> void ImVector< T >::swap (ImVector< T > & rhs) inline
Referenced by ImDrawData::DeIndexAllBuffers(), ImGui::EndFrame(), and SaveIniSettingsToMemory().
_grow_capacity()
template<typename T> int ImVector< T >::_grow_capacity (int sz) const inline
resize() [1/2]
template<typename T> void ImVector< T >::resize (int new_size) inline
Referenced by ImGui::Begin(), ImGui::BeginColumns(), ImGui::BeginGroup(), ClosePopupToLevel(), ImDrawData::DeIndexAllBuffers(), ImGui::EndFrame(), ImDrawDataBuilder::FlattenIntoSingleLayer(), ImFontAtlas::GlyphRangesBuilder::GlyphRangesBuilder(), ImFileOpen(), ImFontAtlasBuildPackCustomRects(), ImGui::InputTextEx(), ImGui::NewFrame(), ImGui::OpenPopupEx(), ImDrawList::PathClear(), ImFont::RenderText(), SetClipboardTextFn_DefaultImpl(), ImGui::SetDragDropPayload(), and ImGuiTextFilter::TextRange::split().
resize() [2/2]
template<typename T> void ImVector< T >::resize (int new_size, const T & v) inline
reserve()
template<typename T> void ImVector< T >::reserve (int new_capacity) inline
Referenced by ImGui::BeginColumns(), ImGui::EndFrame(), and ImGuiTextBuffer::reserve().
push_back()
template<typename T> void ImVector< T >::push_back (const value_type & v) inline
Referenced by AddDrawListToDrawData(), AddWindowSettings(), AddWindowToSortedBuffer(), ImGui::Begin(), ImGui::BeginColumns(), ImGui::BringWindowToFront(), ImFontAtlas::GlyphRangesBuilder::BuildRanges(), ImGuiTextBuffer::clear(), CreateNewWindow(), FindOrAddColumnsSet(), ImGuiTextBuffer::ImGuiTextBuffer(), ImGui::OpenPopupEx(), PathBezierToCasteljau(), ImDrawList::PathLineTo(), ImDrawList::PathLineToMergeDuplicate(), ImGui::PushFont(), ImGui::PushID(), ImGui::PushItemFlag(), ImGui::PushItemWidth(), ImGui::PushMultiItemsWidths(), ImGui::PushStyleColor(), ImGui::PushStyleVar(), ImGui::PushTextWrapPos(), ImGuiTextFilter::TextRange::split(), and ImGui::TreePushRawID().
pop_back()
template<typename T> void ImVector< T >::pop_back () inline
Referenced by AddDrawListToDrawData(), ImDrawList::ChannelsMerge(), ImGui::End(), ImGui::EndGroup(), ImGui::PopFont(), ImGui::PopID(), ImGui::PopItemFlag(), ImGui::PopItemWidth(), ImGui::PopStyleColor(), ImGui::PopStyleVar(), ImGui::PopTextWrapPos(), and SaveIniSettingsToMemory().
push_front()
template<typename T> void ImVector< T >::push_front (const value_type & v) inline
Referenced by ImGui::Initialize().
erase()
template<typename T> iterator ImVector< T >::erase (const_iterator it) inline
Referenced by ImGui::BringWindowToFront().
insert()
template<typename T> iterator ImVector< T >::insert (const_iterator it, const value_type & v) inline
Referenced by CreateNewWindow().
contains()
template<typename T> bool ImVector< T >::contains (const value_type & v) const inline
Member Data Documentation
Size
template<typename T> int ImVector< T >::Size
Referenced by AddDrawListToDrawData(), AddWindowToDrawData(), AddWindowToSortedBuffer(), ImGui::Begin(), ImGui::BeginColumns(), ImGui::BeginCombo(), ImGui::BeginGroup(), ImGui::BeginMenu(), ImGui::BeginPopup(), ImGui::BeginPopupEx(), ImGui::BringWindowToBack(), ImGui::BringWindowToFront(), ImDrawList::ChannelsMerge(), CheckStacksSize(), ImGui::CloseCurrentPopup(), ImGui::ClosePopup(), ImGui::ClosePopupsOverWindow(), ImGui::ColorPicker4(), ImDrawData::DeIndexAllBuffers(), ImGuiTextBuffer::empty(), ImGui::EndFrame(), ImGui::EndMenu(), ImGui::EndPopup(), FindHoveredWindow(), FindOrAddColumnsSet(), ImGui::FindSettingsHandler(), FindWindowIndex(), FindWindowNavigable(), ImGui::FindWindowSettings(), ImDrawDataBuilder::FlattenIntoSingleLayer(), ImGui::FocusFrontMostActiveWindow(), ImFont::GetCharAdvance(), GetFrontMostModalRootWindow(), ImGui::GetMousePosOnOpeningCurrentPopup(), ImFontAtlasBuildFinish(), ImFontAtlasBuildPackCustomRects(), ImFontAtlasBuildWithStbTruetype(), ImGui::InputTextEx(), ImGui::IsPopupOpen(), ImGui::NavUpdate(), ImGui::NavUpdateWindowing(), NavUpdateWindowingHighlightWindow(), ImGui::NewFrame(), ImGui::OpenPopupEx(), ImDrawList::PathFillConvex(), ImDrawList::PathLineToMergeDuplicate(), ImDrawList::PathStroke(), ImGui::Render(), AuroraFW::GEngine::GLImGuiLoader::renderDrawLists(), ImFont::RenderText(), SaveIniSettingsToDisk(), SaveIniSettingsToMemory(), ImDrawData::ScaleClipRects(), SettingsHandlerWindow_WriteAll(), SetupDrawData(), ImGui::ShowMetricsWindow(), ImGui::Shutdown(), ImGuiTextBuffer::size(), and ImVector< ImGuiStorage::Pair >::swap().
Capacity
template<typename T> int ImVector< T >::Capacity
Referenced by ImVector< ImGuiStorage::Pair >::swap().
Data
template<typename T> T* ImVector< T >::Data
Referenced by AddDrawListToDrawData(), ImGui::BringWindowToFront(), ImGuiTextBuffer::c_str(), ImDrawList::ChannelsMerge(), ImGui::ColorPicker4(), GetFrontMostModalRootWindow(), ImFontAtlas::GlyphRangesBuilder::GlyphRangesBuilder(), ImFontAtlasBuildPackCustomRects(), ImGui::InputTextEx(), ImGuiTextBuffer::operator[](), ImDrawList::PathFillConvex(), ImDrawList::PathStroke(), AuroraFW::GEngine::GLImGuiLoader::renderDrawLists(), ImFont::RenderText(), SaveIniSettingsToDisk(), ImGui::SetDragDropPayload(), SetupDrawData(), ImGui::ShowMetricsWindow(), and ImVector< ImGuiStorage::Pair >::swap().
The documentation for this class was generated from the following file:
ImGui.h