Aurora Framework: AuroraFW::GEngine::RTShaderConverter Class Reference
AuroraFW::GEngine::RTShaderConverter Class Reference
Static Public Member Functions
static const char * toGLSL (const char *, RTShader::Language, RTShader::LangVersion)
static const char * toHLSL (const char *, RTShader::Language, RTShader::LangVersion)
static const char * toSPIRV (const char *, RTShader::Language, RTShader::LangVersion)
Member Function Documentation
toHLSL()
const char * AuroraFW::GEngine::RTShaderConverter::toHLSL (const char * , RTShader::Language , RTShader::LangVersion) static
toGLSL()
const char * AuroraFW::GEngine::RTShaderConverter::toGLSL (const char * src, RTShader::Language srclang, RTShader::LangVersion destlangv) static
References spirv_cross::CompilerGLSL::compile(), spv::DecorationBinding, spv::DecorationDescriptorSet, spirv_cross::CompilerGLSL::Options::es, spirv_cross::Compiler::get_decoration(), spirv_cross::Compiler::get_shader_resources(), AuroraFW::GEngine::RTShader::GLSL330, AuroraFW::GEngine::RTShader::GLSL330_CORE, spirv_cross::ShaderResources::sampled_images, spirv_cross::Compiler::set_decoration(), AuroraFW::GEngine::RTShader::SPIR_V, spirv_cross::Compiler::unset_decoration(), and spirv_cross::CompilerGLSL::Options::version.
toSPIRV()
const char * AuroraFW::GEngine::RTShaderConverter::toSPIRV (const char * , RTShader::Language , RTShader::LangVersion) static
The documentation for this class was generated from the following files:
RTShaderConverter.h
RTShaderConverterGLSL.cpp
RTShaderConverterHLSL.cpp
RTShaderConverterSPIRV.cpp